### ISSUE TITLE
git-lfs error 255 when attempting to push for the first time (Windows)

### ISSUE THREAD

**Issue by jarshwah** [git-lfs/git-lfs#1004]
I've just converted a repo to use git-lfs but I'm unable to push the files back up to github. I ran the git bfg tool to clean history, and then re-added all of the files to the repo. Org/Repo names changed because they're private. Happy to disclose names to staff if need be.

```
λ git lfs push origin master
16:17:45.995391 git.c:561               trace: exec: 'git-lfs' 'push' 'origin' 'master'
16:17:45.995391 run-command.c:343       trace: run_command: 'git-lfs' 'push' 'origin' 'master'
trace git-lfs: Upload refs origin to remote [master]
trace git-lfs: run_command: git rev-list --objects master --not --remotes=origin
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: prepare upload: c96cd487c4cf46d59c1d2acdc4f1e53e0282784e7b8002a575b0ed01b55f8ed0 lib/file.dll 1/115
...
trace git-lfs: tq: sending batch of size 100
trace git-lfs: ssh: git@github.com git-lfs-authenticate MyOrg/my-repo.git upload
...
trace git-lfs: ssh: upload attempted with git@github.com.  Error: exit status 255
trace git-lfs: tq: sending batch of size 15
trace git-lfs: ssh: git@github.com git-lfs-authenticate MyOrg/my-repo.git upload
trace git-lfs: ssh: upload attempted with git@github.com.  Error: exit status 255
Git LFS: (0 of 115 files) 0 B / 49.16 MB
exit status 255
exit status 255
```

I've been fighting lfs for the last few hours, and now I'm completely stuck on this. A regular `git push origin master` also returns exit status 255.

I checked the billing account, and there's 12GB allowance free (never used LFS before) so I doubt that's the issue.

`ls-files` shows what I expect:

```
λ git lfs ls-files
16:26:51.546049 git.c:561               trace: exec: 'git-lfs' 'ls-files'
16:26:51.546049 run-command.c:343       trace: run_command: 'git-lfs' 'ls-files'
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: git ls-tree -r -l --full-tree d4b344f72fd4153a4b6741ae0b3f8fa25b7c9cc3
trace git-lfs: run_command: git cat-file --batch
bbcbb17024 * lib/file1.dll
... 115 more
```

```
λ git lfs env
git-lfs/1.1.1 (GitHub; windows amd64; go 1.5.3; git 69d1419)
git version 2.7.1.windows.2

Endpoint=https://github.com/MyOrg/my-repo.git/info/lfs (auth=none)
  SSH=git@github.com:MyOrg/my-repo.git
LocalWorkingDir=C:\Users\Josh Smeaton\Documents\repos\my-repo
LocalGitDir=C:\Users\Josh Smeaton\Documents\repos\my-repo\.git
LocalGitStorageDir=C:\Users\Josh Smeaton\Documents\repos\my-repo\.git
LocalMediaDir=C:\Users\Josh Smeaton\Documents\repos\my-repo\.git\lfs\objects
TempDir=C:\Users\Josh Smeaton\Documents\repos\my-repo\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_INSTALL_ROOT=C:\Program Files\Git
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

Where am I going wrong here?

**Comment by technoweenie** [comment]
What happens when you run `ssh git@github.com git-lfs-authenticate MyOrg/my-repo.git upload` (with your actual org and repo name)?

**Comment by jarshwah** [comment]
That command dumped some JSON:

```
λ ssh git@github.com git-lfs-authenticate Org/repo.git upload
Enter passphrase for key '/c/Users/Josh Smeaton/.ssh/id_rsa':
{
  "href": "https://api.github.com/lfs/Org/repo",
  "header": {
    "Authorization": "RemoteAuth Base64edString=="
  },
  "expires_at": "2016-02-16T04:30:21Z"
}
```

But that led me to getting ssh-agent working correctly (it wasn't running for theses tests). I've been using cmder shell with the cmd terminal. I switched to the git bash shell which did start ssh-agent, and the push worked fine.

I configured the cmd terminal to also run ssh-agent, and that too is now working correctly. LFS pushes now.

I'm guessing at this point that ssh-agent must be running for LFS to push correctly, though several things I've read seem to suggest that LFS will cache the auth for a short period. I can close this off if you like, or leave it if you'd prefer to follow up. If you want me to debug further just ask. Cheers.

**Comment by technoweenie** [comment]
Ahh, ssh-agent not running is definitely the cause of it. Though it'd be nice if git lfs could detect that better.

> though several things I've read seem to suggest that LFS will cache the auth for a short period

Git has credential helpers for HTTPS remotes only. SSH Agent already does this for SSH remotes.

**Comment by jarshwah** [comment]
I'm no longer personally interested in this. Feel free to reopen (or recreate) if still interested.
