### ISSUE TITLE
Configuration of a server for git-lfs

### ISSUE THREAD

**Issue by Theologie** [git-lfs/git-lfs#1011]
Hi everyone,
I've been looking for how to configurate git-lfs to make it store the binary files on my distant Server but I haven't find anything, so here i come.
What should I do to make it possible?
Just change the .gitconfig? And if yes what should I write in it?
Thanks for the awesome work and for your response!
Regards
Theo G

**Comment by technoweenie** [comment]
This part of the spec describes how the lfs url is defined: https://github.com/github/git-lfs/blob/master/docs/spec.md#the-server. If it can't guess the lfs server by appending "/info/lfs" to the git remote url, then you can configure it through the `lfs.url` or `remote.{name}.lfsurl` properties. You can configure them locally with `git config`, or write it to a `.lfsconfig` file at the root of your repository.

    $ git config -f .lfsconfig lfs.url "http://my-server.com"

**Comment by Theologie** [comment]
Thanks for your answer.

I did `$ git config -f .lfsconfig lfs.url "http://my-server.com"`
with http://my-server.com" being http://username@easydoe:9090/scm/git/Sandbox/userSandbox

But I got this error message:

```
git-c diff.mnemonicprefix=false -c core.quotepath=false add -f -- 6f06c1aa65740e72adb894ff71d22ea9_large.jpg
git-lfs clean '6f06c1aa65740e72adb894ff71d22ea9_large.jpg': git-lfs: command not found

error: external filter git-lfs clean %f failed -1
error: external filter git-lfs clean %f failed


fatal: 6f06c1aa65740e72adb894ff71d22ea9_large.jpg: clean filter 'lfs' failed

Completed with errors, see above.

```
Any idea how to prevent it?

**Comment by technoweenie** [comment]
> git-lfs: command not found

Make sure you've installed `git-lfs` into your system's `$PATH`.

**Comment by Theologie** [comment]
I do make `git lfs install` and the result is:
```
Updated pre-push hook.
Git LFS initialized.

```
So git-lfs is well installed in my system's path apparently!

**Comment by technoweenie** [comment]
It doesn't seem to be in your path in whatever context the command you're running is in. Is it maybe running as a different user?

**Comment by Theologie** [comment]
I use SourceTree as a GUI but I typed the command in Git Bash. Also I am the only user (if I understand well the question)

**Comment by Theologie** [comment]
Using `git add .` I managed to add the file then commit it but It hadn't been handled by git-lfs

`$ git lfs env` give me:

```
git-lfs/1.1.1 (GitHub; windows amd64; go 1.5.3; git 69d1419)
git version 2.7.1.windows.2

Endpoint=http://easydoe:9090/scm/git/Sandbox/theoSandbox%20%5Bremote%20origin%5D%20url%20=%20http://easydoe:9090/scm/git/Sandbox/theoSandbox (auth=none)
LocalWorkingDir=D:\user\Theo\Test Git-lfs
LocalGitDir=D:\user\Theo\Test Git-lfs\.git
LocalGitStorageDir=D:\user\Theo\Test Git-lfs\.git
LocalMediaDir=D:\user\Theo\Test Git-lfs\.git\lfs\objects
TempDir=D:\user\Theo\Test Git-lfs\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"

```

**Comment by technoweenie** [comment]
I'm referring to the user account running on your computer. Maybe @sinbad can help you with the SourceTree issues? I know very little about writing code on windows.

As far as files not being handled by LFS. You need to run `git lfs track` on them _before_ running `git add`. The track command adds an entry to `.gitattributes` that tells Git what files to run through LFS. You can use the following commands to confirm that LFS is being used:

* Use `git lfs status` to see if a file is using LFS _after_ running `git add`.
* Use `git lfs ls-files` to see what committed files in the repository are using LFS. Ignores files staged for the next commit, or not part of the repository at all.

**Comment by Theologie** [comment]
`$ git lfs track` gives me:
```
Listing tracked paths
    *.jpg (.gitattributes)
    *.png (.gitattributes)
    *..txt (.gitattributes)

```

And `$ git lfs status` gives me:
```
On branch master

Git LFS objects to be committed:

        56d01bca5c54e009c3b393a830179522_large.jpg (356.3 KB)

Git LFS objects not staged for commit:
```
And finally `$ git lfs ls-files` gives me:
`fd84c651dc * 6f06c1aa65740e72adb894ff71d22ea9_large.jpg`

However the last file "6f06c1aa65740e72adb894ff71d22ea9_large" is in fact present locally, which shouldn't be the case as JPG are tracked right?
Anyway thanks for your help and your reactivity!

**Comment by sinbad** [comment]
Regards SourceTree: are you running the latest version? And in Tools > Options > Git are you using the Embedded Git or the System Git? If it's Embedded Git and you're on the latest version, it should automatically prompt to download a version of git-lfs to use internally when you open a git-lfs repo. If you're using the System Git though, make sure that git-lfs.exe is either in the same directory as your System git, or is somewhere else that is on the system PATH. If you've had to edit the PATH to make that happen, make sure you restart SourceTree afterwards, otherwise it won't pick up the new PATH until it is next restarted.

**Comment by Theologie** [comment]
I am running the 1.8.036401 Version, I downloaded it two days ago so it seems to be the last one.
I use the System Git Version (2.7.1), and git-lfs.exe is on my Git Folder (C:\Program Files\Git\bin where git.exe is). Or should it be in C:\Program Files\Git ?

**Comment by sinbad** [comment]
Hmm, ok there seems to be a problem in some contexts since the git-lfs installer started putting git-lfs in a different location; calling 'git lfs foo' ourselves works (which is how we test for it working) but if it's called via a secondary command like the filters, it fails with the system git now it's in a different location. I'll investigate, but as a workaround you can either use the embedded git, or copy git-lfs.exe into C:\Program Files\Git\mingw64\bin (this is where the lfs installer used to put it).

**Comment by Theologie** [comment]
Okay I copy git-lfs.exe to C:\Program Files\Git\mingw64\bin (where it wasn't present first) but still the same problem apparently.

**Comment by sinbad** [comment]
Weird, worked for me. Make sure you don't have more than one version of Git installed in different places.

**Comment by Theologie** [comment]
According to Windows program, I have Git Version 2.7.1.2 installed as well as Git LFS Version 1.1.1

**Comment by sinbad** [comment]
Exactly the same as I do, and copying git-lfs.exe into C:\Program Files\Git\mingw64\bin, where git.exe is, fixes it instantly (and breaks again when I take it out). No idea why it doesn't work for you, you could try the embedded git for now.

**Comment by Theologie** [comment]
Now it seems to work but then I've got another problem, Git gives me:
```
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v origin master:master
Pushing to http://easydoe:9090/scm/git/Sandbox/theoSandbox



Repository or object not found: http://easydoe:9090/scm/git/Sandbox/theoSandbox.git/info/lfs/objects
Check that it exists and that you have proper access to it


Git LFS: (0 of 1 files) 0 B / 1.03 MB                                          

error: failed to push some refs to 'http://easydoe:9090/scm/git/Sandbox/theoSandbox'

Completed with errors, see above.

```

**Comment by technoweenie** [comment]
You're getting a 404 or 403 (authorization problem?) from the server.

**Comment by Theologie** [comment]
I don't think so because commit with files that are not managed by Git-lfs works without any problem.

**Comment by ttaylorr** [comment]
Hi @Theologie, I am going to close this issue for now since it's grown stale. Can you please comment here if you have fixed the issue, or are otherwise still having troubles? Thanks!
