### ISSUE TITLE
Pre-push hook problem when branches are deleted server-side

### ISSUE THREAD

**Issue by sinbad** [git-lfs/git-lfs#1014]
We just came across an edge case which can cause data loss with LFS in the following scenario:
1. A branch is deleted on the server but the client doesn't know yet
2. The server deletes unreferenced LFS objects to optimise space

Reproduction:
1. Create branch 'branch1': `git checkout -b branch1`
2. Add a new LFS file: `git add test.jpg`
3. Push branch1: `git push origin branch1`. Note that the new LFS file is uploaded
4. Delete branch1 on **server**: `git push origin --delete branch1` (or via web interface)
5. Note that this leaves .git/refs/remotes/origin/branch1 locally but the server now thinks that the commit containing test.jpg is now orphaned and can be GC'd. If GC is implemented on LFS objects too, the LFS objects would be deleted if it's not referenced elsewhere. Let's assume that's happened.
6. Create another branch at the same commit: `git checkout -b branch2`
7. Push branch2: `git push origin branch2`
8. No LFS objects are pushed. If the server GC'd the unreferenced LFS object already, this is data loss

In that last push step, the pre-push hook doesn't push any LFS objects, because .git/refs/remotes/origin/branch1 still exists and therefore `git rev-list --objects <commit> --not --remotes=origin` returns nothing. If `git fetch --prune` had been run, or the user had also deleted the locally cached version of the remote ref (e.g. `git branch -D -r branch1`) before pushing branch2, then it would have been OK. However we cannot guarantee the sequence that these things happen in, and therefore cannot guarantee that the remote ref we have locally is correct.

Git itself resolves this discrepancy during the push but it doesn't call the pre-push hook again with the updated commit range it will actually push to the server. So LFS never knows. Once this has happened, there's potentially a 'gap' in the commit sequence where the LFS client thinks the server must have everything, but if it GC's itself, it won't. 

I think this is a bug in our use of the pre-push hook and that we should run `git ls-remote` to confirm the existence of the remote refs we have cached locally before relying on them to determine what to push. We don't have to check the SHAs, because they may have moved forward anyway. There's another potential edge case where a force push has moved the remote ref to a non-descendant of our cached version, but in that case `git push` will fail and require that our local versions are updated anyway, so the subsequent push will resolve that.

I'm happy to work on this if you agree with the approach @technoweenie

**Comment by technoweenie** [comment]
Great catch! I think calling `git ls-remote` is a good solution. Though, LFS servers should probably respect Git's built-in prune settings.

**Comment by sinbad** [comment]
> Though, LFS servers should probably respect Git's built-in prune settings.

Can you explain? LFS objects unreferenced by commits because of deleted branches seem valid candidates for GC under git's rules to me, same as .git/objects?

**Comment by technoweenie** [comment]
IMO they should respect `gc.pruneExpire`. Still, it's very possible to have a local cache of a remote branch for more than the default of 2 weeks.

**Comment by sinbad** [comment]
Gotcha - but yeah the problem can still occur regardless of time period, it depends on what you do on the client. I’ll crack on with dealing with it next week, it’s probably not biting anyone yet but it’ll be good to make sure it never does :)

**Comment by ttaylorr** [comment]
Fixed via #1051.

(:wave: @sinbad!)
