### ISSUE TITLE
Auto-push from build agent

### ISSUE THREAD

**Issue by szigetics** [git-lfs/git-lfs#1046]
I would like to build one of my static libraries on one of my build agents, and automatically push the results to Git using Git-LFS. I couldn't make git credential-osxkeychain work yet in my build agent launch daemon. Have any of you succeeded with this already?

Thanks!

**Comment by technoweenie** [comment]
I use `osxkeychain` as my credential helper. I don't have any experience with "build agents" though.

**Comment by ttaylorr** [comment]
@szigetics, this should work as-expected provided that you credential helper does the right thing.

**Comment by 751176723** [comment]
https://446.24k88.live
