### ISSUE TITLE
Git LFS Push problems

### ISSUE THREAD

**Issue by tvandijck** [git-lfs/git-lfs#1061]
I have a git repository (and lets be clear that this is mostly for testing feasibility of converting from SVN to GIT for our team).

Pre-LFS its a 107GB repo,
Post-LFS it's a 5.6GB repo with 280GB of LFS data... 
- using latest LFS, and BFG to do the LFS scrubbing.

now I'm trying a git push, and I get this:

```
[tvandijck@tvandijck-centos repo.git]$ git remote set-url origin https://ghosthub.****.******.***/team1/star2code.git
[tvandijck@tvandijck-centos repo.git]$ git push

Git LFS: (0 of 10003 files, 10003 skipped) 0 B / 42.13 GB, 42.13 GB skipped                                                                      
Git LFS: (0 of 10003 files, 10003 skipped) 0 B / 42.13 GB, 42.13 GB skipped                                                                      
Git LFS: (0 of 10010 files, 10010 skipped) 0 B / 42.25 GB, 42.25 GB skipped                                                                      
Git LFS: (0 of 10332 files, 10332 skipped) 0 B / 44.40 GB, 44.40 GB skipped                                                                      
Git LFS: (0 of 1757 files, 1757 skipped) 0 B / 3.10 GB, 3.10 GB skipped
....
```

The full log is attached, after 150 HOURS of pushing LFS data I interrupted it, somewhat by accident, but alas. But, what is it doing?? Why is it 'checking' everything so many times, I only have 280GB of LFS files, but accumulating all the log info results in:

```
16,552 files actually uploaded.
5,681,847 total files checked.
5,661,501 files skipped.
205.18GB actually uploaded.
36,801 GB total checked (38 TERABYTE)
36,592 GB skipped (36 TERABYTE)
```

SO FAR... I have no clear indication that it would be done anytime soon, it feels a little bit like it is checking each branch individually, so in that case I would have 1100 branches to go, or which 405 have completed, restarting it however, makes it do it all over again.

[git-push-log.txt](https://github.com/github/git-lfs/files/162439/git-push-log.txt)
[git-push-log.xlsx](https://github.com/github/git-lfs/files/162452/git-push-log.xlsx)

I know the repo is big, but testing every file over 400 times seems somewhat of a problem.

**Comment by technoweenie** [comment]
We have PRs (#1040 and #1038) that address this. Basically, the initial push is looping through each branch to upload. Then, it's doing a full scan of each branch's history and picking up files from other branches. 

Thanks for the report!

**Comment by ttaylorr** [comment]
Hi @tvandijck, just coming in to close the loop on this issue. Are you still having problems of this kind? There has been and continues to be lots of effort spent on optimizing this computation, and I would be curious to see of its impact in this case on a modern version of Git LFS.

I am going to close the issue for now optimistically, but please let me know if you have any issues of this kind or otherwise in the future. Thanks!

**Comment by tvandijck** [comment]
I have since moved on to a different company, but after our initial assessment 2 years ago, we abandoned moving to git. So I guess 'we' no longer have these issues.

Closing is fine, but I have no way of verifying it currently. Besides, I'm more excited about gvfs, and hoping to see that go more mainstream.
