### ISSUE TITLE
A one-time network failure may lock a working copy out of batch mode forever

### ISSUE THREAD

**Issue by epriestley** [git-lfs/git-lfs#1095]
I'm implementing an LFS server, and would like to avoid implementing the deprecated older single-file APIs. However, I'm worried about the client potentially locking users into a nonfunctional state when this sequence of actions occurs:
- The user tries to do a fetch.
- The server returns a freak 404 for whatever reason (temporary bad config, load balancer issue, etc. -- in our case, users are deploying the servers, and they've historically found very creative ways to approach system administration tasks, so I think these errors are likely rare but not outside of the realm of imagination).
- The client writes `lfs.batch = false` and the user is now stuck in single-fetch mode forever unless they go learn about this option.
- If the server doesn't implement single-fetch mode at all, the repository is now effectively broken?

I think this can be largely mitigated by swapping the sequencing here, in `Download`:

```
if IsNotImplementedError(err) {
  git.Config.SetLocal("", "lfs.batch", "false")
  return DownloadLegacy(oid)
}
```

Minimally, we could do something like this instead:

```
if IsNotImplementedError(err) {
  stuff, err := DownloadLegacy(oid)
  if err == nil {
    git.Config.SetLocal("", "lfs.batch", "false")
  }
  return stuff, err
}
```

That is, only disable batch mode if batch mode fails _and_ single mode works. Does that seem reasonable?

Broadly, locking users into this mode permanently after one bad fetch seems a little iffy, so maybe this automatic disabling behavior could simply be removed now? The cost should only be an extra HTTP request for any providers that do not implement batch mode. That said, it looks like this behavior was added in 7c2ecb83c so it's only about 5 months old, although I'm not sure what the context was.

(Or maybe this concern is unwarranted or there are other plans to improve this.)

**Comment by epriestley** [comment]
Oh, I found #711 and #708, but it doesn't look like locking the client out with "lfs.batch" is specifically motivated by either of those issues, and clones now empirically work without requiring the server to implement single fetches.

```
$ git clone ssh://local@localvault.phacility.com/diffusion/POEMS/poems.git poemslocal2
...
Downloading lfs/ausdog.png (396.41 KB)
Checking out files: 100% (16019/16019), done.
```

**Comment by sinbad** [comment]
Yeah, we've had exactly this issue before. Personally I think we should remove the non-batch route from the git-lfs client in the next version (or as soon after as possible), and therefore remove the need for the `lfs.batch` sticky setting.

**Comment by ttaylorr** [comment]
Git LFS (as of v2.0.0) no longer supports the non-batch (read: "legacy") API, so I think that this should be resolved!
