### ISSUE TITLE
Changing the URL of a remote in-place without git fetch --prune up can lose data

### ISSUE THREAD

**Issue by sinbad** [git-lfs/git-lfs#1098]
PSA: I'm not sure we can actually do anything about this without requiring the server to store significantly more state & making the API reflect git's own more closely. I just thought it should be recorded somewhere.

If you edit a git remote in-place and change the URL, the remote branch state that is cached locally won't change. This means that if you don't do anything else, the next `git push` you do look at the existing remote state and conclude that nothing before that needs to be pushed, when in fact the URL may now point to a completely blank repo, or even more confusingly a fork that's not as up to date, etc. This will leave a 'hole' in the server LFS state - the commits will be fine since the server will negotiate but at this point it's too late, git-lfs has lost its opportunity and will never have it again. This problem can also happen if the server repo is deleted & re-created in place.

The workaround is to either:
- never edit remote URLs in place; always `git remote remove` then `git remote add`
- always run `git fetch --prune` after editing a remote URL

Since this is a potential data loss scenario maybe we should have it in a FAQ somewhere?

**Comment by ttaylorr** [comment]
> PSA: I'm not sure we can actually do anything about this without requiring the server to store significantly more state & making the API reflect git's own more closely.

I agree. It's an unfortunate problem, but I don't think that there's anything that we could reasonable do that would solve it completely. I'm going to close this for now, but if someone from @git-lfs/core or a contributor is interested in working on this in more detail, I would be more than happy to help.
