### ISSUE TITLE
LFS can track and clean .gitattributes, breaking itself

### ISSUE THREAD

**Issue by epriestley** [git-lfs/git-lfs#1099]
LFS can track `.gitattributes`, clean `.gitattributes` so it is no longer a valid file, and then `git` will fail when trying to read `.gitattributes`, putting the repository into a bad state which seems difficult to get out of.

I believe this will reproduce the issue:

```
$ git lfs track '.gitattributes'
$ git add .gitattributes
$ git commit -m 'track config file'
$ git push
$ git checkout some-other-branch
$ git checkout the-original-branch
```

On the last step, Git will do something like this:

```
$ GIT_TRACE=1 git checkout lfs-self-track
07:14:06.584448 git.c:348               trace: built-in: git 'checkout' 'lfs-self-track'
https://git-lfs.github.com/spec/v1 is not a valid attribute name: .gitattributes:1
sha256:5c13eadc71f64df8469c28b1fc15d60a8581dac6d89d1cf8e7356f7c5a34d259 is not a valid attribute name: .gitattributes:2
Switched to branch 'lfs-self-track'
Your branch is up-to-date with 'origin/lfs-self-track'.
```

That is, the clean `.gitattributes` in this branch is no longer a valid `.gitatttributes` file, so `git` fails to read it. Any LFS files in this working copy (including `.gitattributes` itself) are never smudged.

This scenario is somewhat absurd, but users could hit it accidentally, or I think as a side effect when trying to track everything (like #433).

Since the failure is at the `git` level, I _think_ we can only avoid it by never cleaning this file.

Some possible approaches I can come up with:
- Don't bother? This is admittedly pretty hard to hit without some deliberate mischief on the part of the user, although the "track everything" scenario seems vaguely plausible. This state also seems challenging to get out of, at least for me.
- Refuse to clean any file named `.gitattributes`? (Does the clean filter always have access to the file name? Or always in normal pathways, at least?)
- Refuse to clean any file data which "looks like" it might be a `.gitattributes` file?

**Comment by epriestley** [comment]
@whoisj mentions `.gitignore` and `.gitmodules` in #433. I'm not sure what the Git order-of-operations is so it's possible that smudge/clean get to run before these and it's fine to track them, but they might also lead to ruin in similar ways.

If we can reasonably blacklist files by name it might be a good idea to blacklist them anyway (I can't imagine a scenario where a user has a reasonable and legitimately interest in storing these files in LFS), but trying to, e.g., blacklist `.gitignore` by examining only the content seems very challenging.

**Comment by sinbad** [comment]
Blacklisting `.git*` would seem reasonable to me.

**Comment by javabrett** [comment]
Could `.lfsconfig` be similarly affected and require blacklist protection?

**Comment by sinbad** [comment]
I don't think it would be affected in the same way but would probably be sensible to exclude it anyway.

**Comment by technoweenie** [comment]
Added to the new roadmap: #1145. We'll get this in the next release.

**Comment by ymadzhunkov** [comment]
Hi, today we accidentally caused lfs to track  .gitattributes. We wanted to separate all huge data files in submodule and track everything there with git lfs. As a solution I think you should blacklist .git*

**Comment by pascalandy** [comment]
Hey folks! I have the same issue. Can you please explain what you mean by:

> you should blacklist .git*

You mean put it in your .gitignore?
Thanks!

**Comment by ttaylorr** [comment]
> Hey folks! I have the same issue. Can you please explain what you mean by:
> 
> > you should blacklist .git*

I think that this suggestion was made for Git LFS itself, not users of it. We have a list of patterns that you are not allowed to give to `git lfs track` explicitly, for reasons such as these. If I recall correctly, we implemented this in https://github.com/git-lfs/git-lfs/pull/1346.

Can you make sure that you are on a recent version of Git LFS? If you are and are still experiencing problems, please open a new issue and we'd be more than happy to help out.

I am going to close this issue in the meantime, since it is long stale, and should have been closed when we merged https://github.com/git-lfs/git-lfs/pull/1346 in the first place. Thanks!

**Comment by pascalandy** [comment]
I dropped the project.
I use git everyday but git lfs is unusable. Doing a `git add .` freeze and takes the whole CPU.

**Comment by ttaylorr** [comment]
> Doing a `git add .` freeze and takes the whole CPU.

@pascalandy I'm sorry that this is the case. We'd certainly be interested to learn more about why this is going on, if you are willing to provide that information. Can you open a new issue detailing a reproduction?

**Comment by pascalandy** [comment]
Sorry I won't pursue this avenue. That was a nice to have for me. Cheers!

**Comment by jreniel** [comment]
This is an old thread but for anyone that comes here looking for answers, this is what worked for 
```bash
git lfs track '*'
echo ".gitattributes -filter=lfs -diff=lfs -merge=lfs -text" >> .gitattributes
```
The scenario for tracking '*' is an SVN migration of a series of test branches. No source code was on the branches.
