### ISSUE TITLE
Failed to open man dir

### ISSUE THREAD

**Issue by jean-christophe-manciot** [git-lfs/git-lfs#1111]
Built on commit bf6a6c9979791c85dbef63e68b5a9068e8113d36:

`dpkg-buildpackage -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"`

First, I encountered many error messages stating for many different packages:
`src/github.com/github/git-lfs/commands/command_pre_push.go:4:2: cannot find package "bufio" in any of:`
`/usr/lib/go/src/bufio (from $GOROOT)`
`/home/actionmystique/Program-Files/Ubuntu/Git/git-git-lfs/obj-x86_64-linux-gnu/src/bufio (from $GOPATH)`
All error messages are in the log: 
[First error messages.txt](https://github.com/github/git-lfs/files/190886/First.error.messages.txt)

Since I'm new to GO, I used a trick by symlinking /usr/share/go/src into /usr/lib/go.
That's when I hit the second type of error for which I have no workaround:
`dpkg-parsechangelog: warning:     debian/changelog(l5): assuming long month name 'March'
LINE:  -- Stephen Gelman <gelman@getbraintree.com>  Tue, 1 March 2016 14:29:00 +0000`
`dh_installman -O--buildsystem=golang`
`Converting man pages into code...`
`Failed to open man dir: <nil>`

Whole log: 
[Second error messages.txt](https://github.com/github/git-lfs/files/190889/Second.error.messages.txt)

Any suggestion?

**Comment by technoweenie** [comment]
How exactly are you trying to build it? It should work with a working Go install with valid GOROOT and GOPATH:

```go
$ go get github.com/github/git-lfs
$ cd $GOPATH/src/github.com/github/git-lfs
$ script/bootstrap
```

We should document this better somewhere though, for new Go devs. What debian packages do you have installed? What's your GOPATH set to?

/cc @andyneff, I don't know jack about Debian :) Can you help?

@jean-christophe-manciot: Why are you trying to build it from source? Are you planning on contributing? Did the Debian package not work for you? No wrong answer, I'm just trying to get a sense of your end goal.

> assuming long month name 'March' LINE

Doh, that's probably an easy fix in the debian changelog.

**Comment by jean-christophe-manciot** [comment]
Trying to answer all your questions:
- my system is Ubuntu server 15.10
- there's no git lfs on the official Ubuntu repositories
- even if there were such a package there, it would be outdated anyway
- I am currently building a new PPA to distribute all the latest stable releases of many useful/successful/popular/sound packages that I use on my system;
- I would like to add git lfs to the somewhat already long list (~150 so far, but it does not mean 150 applications...)
- it is rare to find sources shipped with all debian control files (kudos to you guys :-) ), so I'm trying to leverage them with ```dpkg-buildpackage```.
- I don't know anything about go tools, it's the first package I'm trying to build with them;
- I just installed dh-goland and all necessary goland tools packages from Ubuntu repos, without being aware about setting up environment variables;

Right now, on my system;, 
- there are pre-installed /usr/lib/goi and usr/share/go (I removed my symlink):
```
/usr/lib/go# ll
total 60
drwxr-xr-x   4 root root  4096 Mar 28 18:33 ./
drwxr-xr-x 252 root root 45056 Mar 27 18:01 ../
drwxr-xr-x   2 root root  4096 Mar 24 15:26 bin/
lrwxrwxrwx   1 root root    31 Mar 11  2015 doc -> ../../share/doc/golang-doc/html/
lrwxrwxrwx   1 root root    38 Dec  2 21:23 favicon.ico -> ../../share/doc/golang-doc/favicon.ico
drwxr-xr-x   5 root root  4096 Dec  2 21:22 pkg/
lrwxrwxrwx   1 root root    19 Mar 11  2015 test -> ../../share/go/test/
-rw-r--r--   1 root root     7 Sep  9  2015 VERSION

/usr/share/go# ll
total 56
drwxr-xr-x   5 root root  4096 Mar 27 13:48 ./
drwxr-xr-x 532 root root 20480 Mar 28 15:24 ../
drwxr-xr-x   3 root root  4096 Oct 24 21:12 pkg/
drwxr-xr-x  44 root root  4096 Mar 27 15:08 src/
drwxr-xr-x  16 root root 24576 Mar 24 15:26 test/
```
- the GO variables are not set: where should GOROOT/GOPATH point to?

**Comment by jean-christophe-manciot** [comment]
If I set GOROOT to /usr/share/lib, another error show up:
```go tool: no such tool "compile"```

It seems that the only way to go is to let GO find /usr/lib/go as GOROOT, to set GOPATH to some user specific folder where the git lfs sources are located and to symlink /usr/share/lib/src into /usr/lib/go.
But I keep getting the 2nd error as described in 1st post.

**Comment by jean-christophe-manciot** [comment]
@technoweenie: I put the deb package building aside for a while and tried what you suggested, but it also fails:
```
/home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-git-lfs# ./script/bootstrap 
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/code.google.com/p/log4go/filelog.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/code.google.com/p/log4go/log4go.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/code.google.com/p/log4go/pattlog.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/code.google.com/p/log4go/termlog.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/code.google.com/p/log4go/wrapper.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/crypto.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/helpers.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/message_authenticate.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/ntlmv1.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/ntlmv1_test.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/ntlmv2.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/utils/test_auth.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/log4go/filelog.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/log4go/log4go.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/log4go/wrapper.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/cheggaaa/pb/example/copy/copy.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/cheggaaa/pb/example/pb.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/kr/pretty/example_test.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/kr/text/colwriter/column_test.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/kr/text/mc/mc.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/kr/text/wrap.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/technoweenie/assert/assert.go
obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/technoweenie/assert/example/point_test.go
can't load package: package github.com/github/git-lfs/commands: cannot find package "github.com/github/git-lfs/commands" in any of:
	/usr/lib/go/src/github.com/github/git-lfs/commands (from $GOROOT)
	/home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-lfs/commands (from $GOPATH)
can't load package: package github.com/github/git-lfs/lfs: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/usr/lib/go/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-lfs/lfs (from $GOPATH)
script/build.go:15:2: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/usr/lib/go/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-lfs/lfs (from $GOPATH)
root@samsung-ubuntu:/home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-git-lfs# echo $GOPATH
/home/actionmystique/Program-Files/Ubuntu/GO-Packages
```

**Comment by technoweenie** [comment]
@jean-christophe-manciot Sorry for the delay on this. I've been catching up on a bunch of github stuff after being out of town for a couple weeks. I should've brought in external help too :)

First, we publish LFS packages to [PackageCloud](https://packagecloud.io/github/git-lfs):

https://github.com/github/git-lfs/releases/tag/v1.1.2

It sounds like you got the dh-golang issues resolved in #1112, so I'm going to skip that.

## Debian Changelog issue

> dpkg-parsechangelog: warning: debian/changelog(l5): assuming long month name 'March' LINE: -

I just fixed this date abbreviation in master: https://github.com/github/git-lfs/commit/506754392d45d6851ab03e32976cd877ecada73e

> the GO variables are not set: where should GOROOT/GOPATH point to?

Here's what the Go [source install docs](https://golang.org/doc/install/source) say about `$GOROOT`:

> The root of the Go tree, often $HOME/go. Its value is built into the tree when it is compiled, and defaults to the parent of the directory where all.bash was run. There is no need to set this unless you want to switch between multiple local copies of the repository.

I've only ever installed Go from Mac or Windows installers, so I've never had to tweak this. In fact, it's empty on my Mac. The various `go*` binaries live in `/usr/local/bin`, which is in my `$PATH`. `$GOPATH` can be any user directory. Git LFS vendors all of its 3rd party dependencies, so you won't have to worry about clashing versions. I use `$HOME/go` as my `$GOPATH`.

Once that's set up, then you can run `go get github.com/github/git-lfs`. This clones the repository to `$GOPATH/src/github.com/github/git-lfs`. This should fix the import error that you're seeing:

```
can't load package: package github.com/github/git-lfs/commands: cannot find package "github.com/github/git-lfs/commands" in any of:
    /usr/lib/go/src/github.com/github/git-lfs/commands (from $GOROOT)
    /home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-lfs/commands (from $GOPATH)
```

It looks like that command is running from `$GOPATH/src/github.com/github/git-git-lfs`. Try renaming that to `$GOPATH/src/github.com/github/git-lfs`.

Sorry for the difficulties here. I'll add a building guide, geared towards devs inexperienced with Go.

**Comment by jean-christophe-manciot** [comment]
Thanks.
I've restarted from scratch by removing all old ubuntu golang packages and installed everything from the official site (https://golang.org/doc/install/source), including all the tools.
Now, the difficulty is that I cannot build git-lfs with ```dpkg-buildpackage``` anymore since it depends on Ubuntu's golang-go; one solution would be to build golang-go package from sources, but there's no debian control files there. I've originally installed it by running ```./all.bash```.
How could I build a debian package for go in a simple manner?

**Comment by jean-christophe-manciot** [comment]
In the meantime,I installed Ubuntu's golang-go and modified PATH so that the latest version path is before Ubuntu's one.
And... it worked :-) I am now able to build git-lfs. Nice team work.

I remain interested to find a simple way to build the latest golang-go package though if someone knows how to do that.

**Comment by jean-christophe-manciot** [comment]
Another solution is to remove the dependency from debian/control.
As soon as I find some free time, I'll try to build the go package with fpm.

**Comment by ttaylorr** [comment]
Hi @jean-christophe-manciot, I'm going through the project and closing issues that I don't think need to be open anymore. Are you still having trouble building Git LFS? I am going to assume that everything is OK, since it has been over two years since this thread was last updated.

If you're still having problems, please do not hesitate to let me know here, and we'd be more than happy to take a look. Thanks!
