### ISSUE TITLE
git lfs fetch error 301

### ISSUE THREAD

**Issue by jdschw** [git-lfs/git-lfs#1129]
I am trying out git lfs for the first time on github, and it's not working.  I created my repository and pushed it to github, but when I clone it from a different computer, running "git lfs fetch" gives me this:

Fetching master
Git LFS: (0 of 31 files) 0 B / 1.18 GB  
Invalid status for POST http://github.com/Romotive/RoutePlanning.git/info/lfs/objects/batch: 301
Warning: errors occurred

In case it helps, the output of "git lfs env" gives this:

git-lfs/1.1.1 (GitHub; linux amd64; go 1.5.3)
git version 1.9.1

Endpoint=http://github.com/Romotive/RoutePlanning.git/info/lfs (auth=none)
LocalWorkingDir=/home/hitl0/src/RoutePlanning
LocalGitDir=/home/hitl0/src/RoutePlanning/.git
LocalGitStorageDir=/home/hitl0/src/RoutePlanning/.git
LocalMediaDir=/home/hitl0/src/RoutePlanning/.git/lfs/objects
TempDir=/home/hitl0/src/RoutePlanning/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"

This is happening on multiple computers.  The one in particular that I'm looking at now has git-lfs installed via a .deb package.  The computer that originally pushed the data has the package from the github website, which is version 1.1.2 instead of 1.1.1.

Any thoughts?

**Comment by technoweenie** [comment]
Use https: `https://github.com/Romotive/RoutePlanning`. I'll have to look into why it's not following the redirect, but that should get you going.

**Comment by jdschw** [comment]
That did do the trick, yes.  For posterity, I did the following:

git remote set-url origin https://github.com/Romotive/RoutePlanning

And then "git lfs fetch" worked.

Thanks,
Jeremy

**Comment by technoweenie** [comment]
Cool, thanks for reporting back. I'm leaving this open until we can fix the 301 issue.

**Comment by ttaylorr** [comment]
Git LFS does follow redirects properly now, in package `lfsapi`. Please do not hesitate to let me know here or elsewhere if you encounter any problems with this, thanks!
