### ISSUE TITLE
Error buffering media file - unexpected EOF

### ISSUE THREAD

**Issue by FeodorFitsner** [git-lfs/git-lfs#1131]
The following error occurs sometimes when cloning https://github.com/KhronosGroup/KTX repository (contents of Git LFS log file):

```
git-lfs/1.1.0 (GitHub; windows amd64; go 1.5.1; git 258acf1)
git version 2.7.1.windows.2

$ git-lfs.exe smudge other_lib/win/Debug-Win32/SDL2.pdb
Error accessing media: other_lib/win/Debug-Win32/SDL2.pdb (1e29347d67dfcb691397ca0c2d35ab9ed6dffb154238ae56b5ca8a0187d9988d)

Error buffering media file: cannot write data to tempfile ".git\\lfs\\tmp\\objects\\1e29347d67dfcb691397ca0c2d35ab9ed6dffb154238ae56b5ca8a0187d9988d-468655711": unexpected EOF
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0x2e41e8, 0xc0820222e8, 0x2e6ad0, 0xc082199460)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf86
github.com/github/git-lfs/commands.logPanic(0x2e6ad0, 0xc082199460, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x428
github.com/github/git-lfs/commands.handlePanic(0x2e6ad0, 0xc082199460, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x55
github.com/github/git-lfs/commands.LoggedError(0x2e6ad0, 0xc082199460, 0x967a80, 0x1e, 0xc082063c78, 0x2, 0x2)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x89
github.com/github/git-lfs/commands.smudgeCommand(0xb67f60, 0xc08200d9e0, 0x1, 0x1)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd90
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb67f60, 0xc08200d930, 0x1, 0x1, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x40a
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb68fa0, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x59a
github.com/github/git-lfs/commands.Run()
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x2a
main.main()
    C:/Users/techn/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135

ENV:
LocalWorkingDir=C:\projects\ktx
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git\lfs\objects
TempDir=.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
```

Platform: Windows Server 2012 R2
AppVeyor Build URL: https://ci.appveyor.com/project/msc-/ktx/build/1.0.201/job/y7fypiiilj18jm4d
Git LFS version: 1.1.0

**Comment by technoweenie** [comment]
> cannot write data to tempfile ".git\\lfs\\tmp\\objects\\1e29347d67dfcb691397ca0c2d35ab9ed6dffb154238ae56b5ca8a0187d9988d-468655711": unexpected EOF

That's the error message. Is there some reason it can't write it? I wonder if it's swallowing an error somewhere. Can you rerun it with `GIT_TRACE=1`?

**Comment by FeodorFitsner** [comment]
Thanks for looking into that! I'll ask customer to re-run with that option.

**Comment by msc-** [comment]
I have added a setting of GIT_TRACE to 1 in my appveyor.yml.  I can't reproduce the problem on demand so we'll have to wait and see.

I should note that I am using Git LFS 1.1.0 also in my Travis CI builds and have never had this problem there, so this is a problem either with Appveyor or the Windows version of Git LFS.

**Comment by msc-** [comment]
The build failed immediately with a new error

```
Build started
git config --global core.autocrlf true
git : 08:06:04.824312 git.c:348               trace: built-in: git 'config' '--global' 'core.autocrlf' 'true'
At line:1 char:1
+ git config --global core.autocrlf true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (08:06:04.824312...utocrlf' 'true':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: 08:06:04.824312 git.c:348               trace: built-in: git 'config' '--global' 'core.autocrlf' 'true'
Get-ChildItem .\.git\lfs\objects\logs\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
Get-ChildItem : Cannot find path 'C:\projects\ktx\.git\lfs\objects\logs' because it does not exist.
At line:1 char:1
+ Get-ChildItem .\.git\lfs\objects\logs\*.log | % { Push-AppveyorArtifact $_.FullN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\ktx\.git\lfs\objects\logs:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
Command executed with exception: Cannot find path 'C:\projects\ktx\.git\lfs\objects\logs' because it does not exist.
```
Appveyor Build URL: [https://ci.appveyor.com/project/msc-/ktx/build/job/gl2dgw44aa3ftlbb](url)

This is what I put in my appveyor.yml:
```
environment:
  GIT_TRACE: 1
```

**Comment by shiftkey** [comment]
@msc- I believe this line is a red herring

> Get-ChildItem .\.git\lfs\objects\logs\*.log

You should check the directory exists before publishing the log artifacts

**Comment by FeodorFitsner** [comment]
In appveyor.yml change `init` section to look like:

```
init:
  - git config --global core.autocrlf true
```

**Comment by msc-** [comment]
Thanks @shiftkey, but this is only called on failure which, up to now, had only been the LFS failure so the logs would be there.

I have made the change given by @FeodorFitsner, thanks, and the build is now working as before. I will have to trigger a few more builds to try to get the LFS failure to happen.

**Comment by msc-** [comment]
For the first time since adding GIT_TRACE, I finally got a couple of LFS errors. See https://ci.appveyor.com/project/msc-/ktx/build/job/pfiyiqolttmnwgn5 and https://ci.appveyor.com/project/msc-/ktx/build/job/mmc1cb0512yeduhu. You can find the Git LFS log file under ARTIFACTS near the top of these pages.

However these errors are different to the "can't write tempfile" problem at the start of this issue. These are reported as  "connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by ttaylorr** [comment]
Hi @FeodorFitsner is this still an issue? I think that this is safe to close, because it's been a couple of years since it was last updated. If there is still something amiss, please do not hesitate to let me know, and I'd be more than happy to dive in.

Thanks also for AppVeyor, we use it all of the time and it has been tremendously useful for us running integration tests on Windows. Your work is much appreciated by us, here :-).

Thanks!

**Comment by FeodorFitsner** [comment]
Sure! Thanks for the king words! 😸
