### ISSUE TITLE
rpm package install error on centos6

### ISSUE THREAD

**Issue by DuLerWeil** [git-lfs/git-lfs#1139]
[root@np ~]# uname -a
Linux np.test.com2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@np ~]# cat /etc/system-release
CentOS release 6.6 (Final)
[root@np ~]# git version
git version 2.8.1
[root@np ~]# rpm -Uvh Downloads/git-lfs-1.1.2-1.el6.x86_64.rpm 
error: Failed dependencies:
        git >= 1.8.2 is needed by git-lfs-1.1.2-1.el6.x86_64
[root@np ~]# which git
/usr/bin/git
[root@np ~]#

**Comment by DuLerWeil** [comment]
git installed from source tarball

**Comment by javabrett** [comment]
You can try installing the newer Git RPM for Centos6 from the IUS repository, see:

* https://ius.io/GettingStarted/
* https://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/
* https://setup.ius.io/

**Comment by TheFriendlyCoder** [comment]
I've been having this issue as well, on CentOS 6.7. Haven't tried the IUS repositories yet to see if that has any effect.

**Comment by grejones** [comment]
I too have a similar issue. I have CentOS 6.7 and git version 2.7.4 (installed/compiled from source tar). Has anyone got around this without having to install some other specific RPM ? I thought git lfs only needed 1.8.2 or newer? I'm new to all this and would really appreciate any help with the specific steps I need to do to get this working.

**Comment by TheFriendlyCoder** [comment]
I too built git 2.8.2 from source and managed to get it working. One thing I noticed which may not be obvious is that you may need to uninstall the old version of git (1.8.x) before installing git-lfs in order for the install to work. 

I decided to take it a step further and I built the RPMs for git from the sources so I could more easily install / uninstall / upgrade to the new version but just building the binaries "should" be sufficient.

**Comment by ttaylorr** [comment]
Going to close this issue for now, since it appears to be version-specific (and the versions in question are more than two years old.) Git LFS certainly aims to be backwards compatible, so if I have closed this issue in error, please do let me know, and I (or someone else) would be more than happy to look into it. Thanks!
