### ISSUE TITLE
v1.2.0 does not build on Debian 7 or 8

### ISSUE THREAD

**Issue by tpdownes** [git-lfs/git-lfs#1156]
After downloading source and running `dpkg-buildpackage -us -uc` on both Deb7 and Deb8. Deb8 error trace is below.

```
=== RUN TestExistingUpload
--- FAIL: TestExistingUpload (0.00 seconds)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x617447]

goroutine 183 [running]:
runtime.panic(0x7fc0a0, 0xc767d3)
    /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
testing.func·006()
    /usr/lib/go/src/pkg/testing/testing.go:416 +0x176
runtime.panic(0x7fc0a0, 0xc767d3)
    /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/github/git-lfs/localstorage.localObjectDir(0x0, 0x8c4190, 0x28, 0x0, 0x0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/localstorage/localstorage.go:57 +0x127
github.com/github/git-lfs/localstorage.(*LocalStorage).BuildObjectPath(0x0, 0x8c4190, 0x28, 0x0, 0x0, 0x0, 0x0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/localstorage/localstorage.go:48 +0x81
github.com/github/git-lfs/lfs.LocalMediaPath(0x8c4190, 0x28, 0x0, 0x0, 0x0, 0x0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/lfs.go:57 +0x62
github.com/github/git-lfs/lfs.TestExistingUpload(0xc20806ea20)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/upload_test.go:109 +0x3f7
testing.tRunner(0xc20806ea20, 0xc7b200)
    /usr/lib/go/src/pkg/testing/testing.go:422 +0x8b
created by testing.RunTests
    /usr/lib/go/src/pkg/testing/testing.go:504 +0x8db

goroutine 16 [chan receive]:
testing.RunTests(0x91ab50, 0xc7a960, 0x6a, 0x6a, 0xc208000801)
    /usr/lib/go/src/pkg/testing/testing.go:505 +0x923
testing.Main(0x91ab50, 0xc7a960, 0x6a, 0x6a, 0xc70540, 0x1, 0x1, 0xc93140, 0x0, 0x0)
    /usr/lib/go/src/pkg/testing/testing.go:435 +0x84
main.main()
    github.com/github/git-lfs/lfs/_test/_testmain.go:261 +0x9c

goroutine 19 [finalizer wait]:
runtime.park(0x414230, 0xc8dcb0, 0xc79789)
    /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xc8dcb0, 0xc79789)
    /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 23 [chan receive]:
github.com/github/git-lfs/lfs.(*Batcher).acceptInput(0xc20800e0e0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:64 +0xbc
created by github.com/github/git-lfs/lfs.NewBatcher
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:26 +0xa3

goroutine 24 [chan receive]:
github.com/github/git-lfs/lfs.(*Batcher).acceptInput(0xc20800e560)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:64 +0xbc
created by github.com/github/git-lfs/lfs.NewBatcher
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:26 +0xa3

goroutine 25 [chan send]:
github.com/github/git-lfs/lfs.(*Batcher).acceptInput(0xc20800e5c0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:72 +0x13b
created by github.com/github/git-lfs/lfs.NewBatcher
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:26 +0xa3

goroutine 27 [chan send]:
github.com/github/git-lfs/lfs.(*Batcher).acceptInput(0xc20800e600)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:72 +0x13b
created by github.com/github/git-lfs/lfs.NewBatcher
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:26 +0xa3

goroutine 28 [chan send]:
github.com/github/git-lfs/lfs.(*Batcher).acceptInput(0xc20800e6a0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:72 +0x13b
created by github.com/github/git-lfs/lfs.NewBatcher
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:26 +0xa3

goroutine 29 [chan send]:
github.com/github/git-lfs/lfs.(*Batcher).acceptInput(0xc20800e6e0)
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:72 +0x13b
created by github.com/github/git-lfs/lfs.NewBatcher
    /home/thomas.downes/build/git-lfs-1.2.0/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/batcher.go:26 +0xa3

goroutine 184 [runnable]:
net/http.(*Server).Serve(0xc20815e240, 0x7fc01302b4b0, 0xc208025710, 0xf, 0xc2080e9ea0)
    /usr/lib/go/src/pkg/net/http/server.go:1694
created by net/http/httptest.(*Server).Start
    /usr/lib/go/src/pkg/net/http/httptest/server.go:109 +0x2a3
FAIL    github.com/github/git-lfs/lfs   0.308s
?       github.com/github/git-lfs/localstorage  [no test files]
?       github.com/github/git-lfs/script    [no test files]
?       github.com/github/git-lfs/subprocess    [no test files]
dh_auto_test: go test -v github.com/github/git-lfs github.com/github/git-lfs/commands github.com/github/git-lfs/docs/man github.com/github/git-lfs/git github.com/github/git-lfs/lfs github.com/github/git-lfs/localstorage github.com/github/git-lfs/script github.com/github/git-lfs/subprocess returned exit code 1
debian/rules:46: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/thomas.downes/build/git-lfs-1.2.0'
debian/rules:19: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by tpdownes** [comment]
Error occurs on separate hardware so "bad RAM" an unlikely explanation.

**Comment by technoweenie** [comment]
Thanks for the report. What version of go are you on?

Also, if you just want to install LFS, have you tried the package that we provide? 

https://github.com/github/git-lfs/releases/tag/v1.2.0

**Comment by tpdownes** [comment]
Yes, I can use that package personally. For the other 1000 members of my workplace, we repackage code for distribution within a single, signed repo.

I think you're probably not using pbuilder to provide clean package building environments?

Deb8:
`ii  golang-go                          2:1.3.3-1                   amd64        Go programming language compiler`

Deb7:
`ii  golang-go                             2:1.3.3-1~bpo70+1                  amd64        Go programming language compiler`

**Comment by ssgelm** [comment]
It builds fine for me on 2:1.3.2-1~bpo70+1 on wheezy.  Are you using pbuilder to build it currently?

**Comment by ssgelm** [comment]
@tpdownes for what it's worth the debian packages are currently built on a clean debian install via docker (similar in a lot of ways to how pbuilder works) so the packages _should_ be buildable on a new server.

**Comment by tpdownes** [comment]
The only way I can get your package to build is to clone the repo and run `dpkg-buildpackage -us -uc` from within the repo. So the package FTBFS.

**Comment by technoweenie** [comment]
> I think you're probably not using pbuilder to provide clean package building environments?

Ah, thanks for chiming in @ssgelm :)

> `ii golang-go 2:1.3.3-1 amd64 Go programming language compiler`

That seems to be the version of the golang-go package, and not Go itself. I did some googling and clicking around, but couldn't figure it out. What does `go version` say?

Can you possibly get the exact command that is being run for those tests? I imagine `go test ...`. We do run those tests in CI and when building the packages locally, so I'm unclear how we're not running into the same thing. It seems related to an important object not being initialized, and doesn't necessarily point to a nasty bug in the client. Here's a linked stacktrace (mostly for myself, or anyone else that wants to dive in):

* [`github.com/github/git-lfs/localstorage.localObjectDir()`](https://github.com/github/git-lfs/blob/v1.2.0/localstorage/localstorage.go#L57)
* [`github.com/github/git-lfs/localstorage.(*LocalStorage).BuildObjectPath()`](https://github.com/github/git-lfs/blob/v1.2.0/localstorage/localstorage.go#L48)
* [`github.com/github/git-lfs/lfs.LocalMediaPath()`](https://github.com/github/git-lfs/blob/v1.2.0/lfs/lfs.go#L57)
* [`github.com/github/git-lfs/lfs.TestExistingUpload()`](https://github.com/github/git-lfs/blob/v1.2.0/lfs/upload_test.go#L109)

I'll have to check out the state of that `lfs.objects` var at that point in `lfs.TestExistingUpload()`.

**Comment by tpdownes** [comment]
The version reported is what you would expect from the package version.

```
[greatdane:build] go version
go version go1.3.3 linux/amd64
```

But I think we've identified the problem: your build tests do not work on source tarballs. If you want your packages to ever be accepted by debian/ubuntu, that's very likely to have to change.

https://wiki.debian.org/SourcePackage#The_definition_of_a_source_package

**Comment by technoweenie** [comment]
Yikes, that's an ancient version of Go. It'll be a while before the oldest maintained Debian has a version of Go new enough for LFS. I think the minimum version right now is v1.4.x, but we're considering some internal changes that will require v1.6.x+.

It's likely the problem stems from Go, and not LFS. Specifically, Go expects packages to be installed in `$GOPATH/src/github.com/github/git-lfs`. It's difficult to say whether the bug you're experiencing is due to that, or the really old version of Go.

We'll do our best to play nice in your environment though :)

**Comment by tpdownes** [comment]
@technoweenie What basis do you have for that assertion? The build tests pass fine when _built from within a repo_.

**Comment by technoweenie** [comment]
Nope, not on a debian machine, at least.

**Comment by ssgelm** [comment]
@technoweenie FWIW it does seem to build with go-1.3 when built within a repo.

**Comment by ssgelm** [comment]
Having said that I am able to reproduce that error both from within pbuilder and if I use `dpkg-source -x` to extract the tarball and try to build.  I am looking into it more now.

**Comment by tpdownes** [comment]
@ssgelm Thanks!

Is the Git LFS team willing to commit to a particular set of platforms? I'm a bit concerned that your choices don't seem connected to actual "production" OSes. For example, I think RHEL7 offers `go 1.4.2`. I realize you are providing packages you build yourself but eventually you'll probably want to be a standard package like `git-svn`.

**Comment by ssgelm** [comment]
So if I `git init` from a clean tarball extraction directory, the tests fail differently.  The tests now fail on
```
--- FAIL: TestLocalRefs (0.00 seconds)
        git_test.go:385: exit status 1
FAIL
FAIL    github.com/github/git-lfs/git   1.585s
```
@technoweenie: Any idea why that is happening?

**Comment by technoweenie** [comment]
That's probably a crappy test assuming `git show-ref` is being run from within a git repo: https://github.com/github/git-lfs/blob/884677e6b9b714ba0dc1639b51848fa837fbe71b/git/git.go#L179-L182

**Comment by ssgelm** [comment]
OK, so if I run `git init` then `git commit --allow-empty -m 'Empty commit'` from a clean tarball the package builds.  Sounds like the tests should probably set up their own test git repo to use?

**Comment by technoweenie** [comment]
Yeah, you wanna write up a quick issue about that specific thing? I'm about to hop on a flight...

We do something similar for the shell integration tests already, but not for these go tests. I'm not sure how much is reasonable when most people will build from Git. Maybe we can compromise and _always_ use a temp dir with `git init`?

**Comment by technoweenie** [comment]
Don't worry about it, adding a few small things to the roadmap now.

**Comment by tpdownes** [comment]
@technoweenie Thanks for updating the roadmap. I agree that the build checks should create what they expect to see. I'm not even certain that a debian.org pbuilder expects to be connected to the internet.

I do want to clarify though: what platforms do you intend to support and by what methods?

**Comment by tpdownes** [comment]
In particular, debian/control says `Build-Depends: ... golang-go:native (>= 1.3.0)` and, empirically, it passes build tests with `go = 1.3.3`. But you say above that it presently build-depends on `go >= 1.4` and that you're considering requiring `go >= 1.6` which was just released 2 months ago. The [contributing guide](https://github.com/github/git-lfs/blob/73271c1dd61a397a5204bffe375d92f4250329c5/CONTRIBUTING.md) says `go >= 1.5`.

So it's not really clear what version of `golang` that `git-lfs` actually needs.

I'm trying to make git LFS used more widely within my organization and it would greatly help if git-lfs targeted some form of stability. As a concrete suggestion, I don't think it would be off the wall to say that `git-lfs <= 1.2.1` should build with `go >= 1.3.3` and then explicitly drop this support for some version `git-lfs > 1.2.1`. This would put you in a position to place a `git-lfs = 1.2.x` package in EPEL7 and enable clean Debian 8 builds according to the stricter (for a good reason) method of packaging those OSes employ.

If I had to guess, you could probably expect `golang-go > 1.6` [by the time Debian 9 freezes](http://news.softpedia.com/news/debian-9-stretch-freeze-delayed-to-integrated-linux-kernel-4-10-501330.shtml) but right now you would need to support `git-lfs >= 1.5.1` for a few versions.

I do appreciate your responsiveness on this issue: LFS solves a real problem for us, I just want to make sure it can actually be used. Following the practices that the OS maintainers use will help you toward that goal.

**Comment by technoweenie** [comment]
> what platforms do you intend to support and by what methods?

First, keep in mind LFS is a relatively new project, maintained actively by a team of two. When I started, I focused on cross compiled go binary downloads, and mac homebrew support. We've been lucky to have outside contributors that have been wonderful about helping us release rpm/deb packages, and a windows installer. Today, we support everything here:

https://github.com/github/git-lfs/releases/tag/v1.2.0

I'm all for supporting more use cases to help more people out. For example, there's this PR for a windows package manager called Chocolatey (https://github.com/github/git-lfs/pull/1146). My main focus as the lead maintainer right now is stability in the tool, better docs, etc. I think fixing these Debian FTBFS (had to look that up, ha) issues is worthwhile, but it will have to come from contributors in a way that's repeatable and tested. Issues like what @ssgelm brought up in https://github.com/github/git-lfs/issues/1156#issuecomment-211574343 is a small example. Perhaps we should tweak the CI tests so it runs outside of a repository, so issues like that are caught as they're initially submitted, and not when a user tries to build a package from a source tarball.

> So it's not really clear what version of golang that git-lfs actually needs.

I'm assuming you're not that familiar with Go, so here's a quick rundown:

* Go versions maintain very good backwards compatibility. It looks like our code still builds on Go 1.3. Though if we use any new functions defined in a newer version, that will stop being true.
* Go 1.5 introduces a new way to declare 3rd party dependencies, which is why I'm anxious to upgrade. Go 1.6 uses that new dependency declaration stuff by default (which we disable with an env var). I think Go 1.7 will drop the old form. So if we could at least get to 1.5 by then, that's fine by me.

I would say that LFS is too new to have that kind of stability that you're looking for. The tool is still evolving rapidly, as we learn what developers need out of LFS. That said, apparently we still able to compile on Go 1.3. So, I think we should look at adding the older Go versions that are available on Debian 7+ and CentOS 6+ to the current test matrix.

Okay, this turned out longer than I planned. I hope it's helpful.

**Comment by ttaylorr** [comment]
Hi @tpdownes, I'm going through the project and pruning issue that don't need to be open any longer. This issue is now considered 'stale', and as such, I think that it can be closed. Git LFS v2.5.0 is the latest, and I successfully built it on Debian 7, 8, and 9 yesterday for its release.

If you are still having trouble, please do not hesitate to open a new issue and we would be more than happy to help you out there. Thanks!
