### ISSUE TITLE
idea: validate api requests and responses with json schema

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1164]
We provide the full json schema with the api docs, but they're not used. If they were, they could detect cases like https://github.com/github/git-lfs/issues/1163 really easily. Maybe only use them if `GIT_TRACE=1` is enabled?

**Comment by ttaylorr** [comment]
:wave:. Good idea; though I don't think that this is a priority for Git LFS today. We do test API requests and responses conform to the API schema in Go tests, and I think that's sufficient for most of the bugs that we're trying to catch.
