### ISSUE TITLE
`git lfs <command>` works even if not performed `git lfs install`

### ISSUE THREAD

**Issue by rrost** [git-lfs/git-lfs#1165]
In case when LFS package was installed but forgot to run `git lfs install` command for particular user, several `git lfs <command>` are working, but result is usually confusing, e.g. `git lfs pull` downloads tracked files correctly, but they become marked as modified by git.

It would be useful to check LFS proper installation status and give user error or warning on `git lfs` commands.

**Comment by technoweenie** [comment]
That's a good idea. Not sure what it should say, though. Should the command halt with an error? Should it add some kind of message at the top like:

    WARNING: Git LFS blah blah is not installed blah blah

**Comment by rrost** [comment]
I believe it's better to halt with error like:

`ERROR: Git LFS not installed. Please run 'git lfs install' first.`

**Comment by technoweenie** [comment]
Or even just run it, sheesh. All it's doing is setting some `git config` values :)

How did you install it without running `git lfs install`? Packages and installers should definitely do it. Though it's obviously easy to miss it by downloading one of the pre-compiled tarballs.

**Comment by rrost** [comment]
I followed instructions on https://git-lfs.github.com/ for Ubuntu.
Actually instructions are just about connecting to Git LFS package repo, it even doesn't mention `apt-get install` command...

**Comment by technoweenie** [comment]
Hmm, those packages should be installing it for you though. If not, that's a bug. I'll look into that separately.

**Comment by rrost** [comment]
Sorry, I wasn't right, when I've installed package on my workstation all was smooth.

**Comment by technoweenie** [comment]
Cool. Please do file issues if there's some installation method that we provide that isn't running `install` when it should be. 

Thanks for filing this issue though. I think it's a great idea, since it'll always be a potential issue.

**Comment by javabrett** [comment]
Should add label `installation`?

**Comment by ttaylorr** [comment]
We surface these types of issues in the best way that we can at the earliest point possible in lots of places, so I think that it is safe to close this issue for now.

**Comment by mattack1** [comment]
I'm confused, are you saying it no longer lets you do "git lfs" if you haven't installed it? (i.e. it gives you an error)

I would assume 'closed' means it was fixed..

**Comment by ttaylorr** [comment]
> I'm confused, are you saying it no longer lets you do "git lfs" if you haven't installed it? (i.e. it gives you an error)

@mattack1 If you mean installed it to be "have the binary in your `$PATH`", then this has always been the case. If you mean "have run `git lfs install`, we allow any non-destructive actions to be performed, and do not allow destructive actions that will fail without `git lfs` installed.
