### ISSUE TITLE
Changing version of LFS used by GitHub's Git Shell application

### ISSUE THREAD

**Issue by RagtagShawn** [git-lfs/git-lfs#1171]
I have installed Git LFS v1.2.0 on Windows, but it appears that the GitHub Git Shell application that is installed with the GitHub Desktop application is still invoking the git-lfs that is installed with the GitHub Desktop install (ie: lfs-amd64_1.1.0).

I've confirmed the v1.2.0 installation folder is in my system path.

How do I change the Git Shell application to use the git-lfs from the v1.2 installation instead of the one from the GitHub Desktop installation? I don't wan to just copy the file I want to make sure that Git is always using the one in the system path for future updates.

**Comment by shiftkey** [comment]
@RagtagShawn @technoweenie currently this isn't possible, but we're currently QAing an update to v1.2 which will be available in the next week or so...
