### ISSUE TITLE
git --short commit-hash lost from version/UserAgent in 1.2.0 deb packages

### ISSUE THREAD

**Issue by javabrett** [git-lfs/git-lfs#1192]
- 1.1.2/packagecloud/deb `git version` : `git-lfs/1.1.2 (GitHub; linux amd64; go 1.5.3; git bf6a6c9)`
- 1.2.0/packagecloud/deb `git version` : `git-lfs/1.2.0 (GitHub; linux amd64; go 1.5.3)`
- master-54c5efa/localbuild/bin `git version` : `git-lfs/1.2.0 (GitHub; linux amd64; go 1.6; git 54c5efa)`
- master-54c5efa/localbuild/extracted-from-deb `git version` : `git-lfs/1.2.0 (GitHub; linux amd64; go 1.6)`

So this problem is in the package build and is reproducible in sandbox.

It looks like when we build from source in deb, we aren't correctly setting `-ldflags` to `-X github.com/github/git-lfs/lfs.GitCommit=<shortsha>`.  This is likely because the deb is built from source from a non-git-working-directory, which is correct, but of course does not have access to the output of `exec.Command("git", "rev-parse", "--short", "HEAD").Output()` (ref [script/build.go](https://github.com/github/git-lfs/blob/master/script/build.go#L47)).

Not sure how this regressed in 1.2.0 - possibly the deb build was improved to build from disconnected sources.

The fix is probably to inject this into the build via a new env var in [build.go](https://github.com/github/git-lfs/blob/master/script/build.go#L156) and hope that this can be passed-through to `dh_lang` helper when it launches its build.

**Comment by javabrett** [comment]
`git-lfs-1.2.0-1.el7.x86_64.rpm` is not affected:

`git-lfs/1.2.0 (GitHub; linux amd64; go 1.5.3; git 386c5d8)`

**Comment by ttaylorr** [comment]
Fixed by you! Thanks again 😄 .
