### ISSUE TITLE
Build debian deb binary package from source tarball

### ISSUE THREAD

**Issue by javabrett** [git-lfs/git-lfs#1201]
Currently we build the deb-package from source in-situ in the Git LFS project local Git repo.  Because of this, it can rely on things that are only available and valid in the context of building from the Git workspace, e.g. we don't notice a git short-hash dropping from the version string in the deb package build (#1192).

We should consider building the source tarball and then building the binary package from that.  I _think_ that this is best practice.  Currently that build fails due to issues that will be linked to this issue.

**Comment by technoweenie** [comment]
I'm in favor of this :+1: Should be easy enough to add to `script/bootstrap -all`.

**Comment by javabrett** [comment]
Current barrier is described in #1202 .

**Comment by ttaylorr** [comment]
With the recent Makefile changes, I think that this issue is now obsolete. Please let me know if there is more to do here, thanks!
