### ISSUE TITLE
Fail-fast if minimum version not met (>= 1.8.2), esp important for non-package installs

### ISSUE THREAD

**Issue by javabrett** [git-lfs/git-lfs#1210]
I just wasted a significant amount of time assisting a colleague; it was not noticed that having installed LFS from a tarball, the minimum Git version (currently git >= 1.8.2) was not being met.  As observed by many others, this is the default situation for old RHEL and variants, where Git 1.7.1 is commonly pre-installed.

`git-lfs` commands should fail-fast if the minimum Git version is not met, lest they fail in interesting and obscure ways, especially when communicating and authenticating with remote servers.

There is already version-specific code, supported by `IsGitVersionAtLeast`, so it should just be a matter of adding a similar call to all commands, or at the bare-minimum, when `install` runs.

**Comment by technoweenie** [comment]
Thanks for the patch :metal:

**Comment by ttaylorr** [comment]
Thanks again! I think that this ended up getting resolved in https://github.com/git-lfs/git-lfs/pull/1461, so I am going to close this issue for now.
