### ISSUE TITLE
git-lfs: HTTP: 503 error

### ISSUE THREAD

**Issue by scott-plutovr** [git-lfs/git-lfs#1214]
Everyone at my company is having trouble doing an initial clone of our repository and receiving a Service Unavailable error. Is there anything we can do?

Please see attached output of command:
GIT_TRACE=1 GIT_LFS_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://github.com/PlutoVR/core.git 2>&1 | tee welcome-clone-core.txt
[welcome-clone-core.txt](https://github.com/github/git-lfs/files/257911/welcome-clone-core.txt)

And attached lfs log file (renamed as a .txt)
[20160510T113141.6465631.txt](https://github.com/github/git-lfs/files/257914/20160510T113141.6465631.txt)

.

System:
Windows 10,
$ git-lfs version
git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 9bd3b8e)

$ git --version
git version 2.7.4.windows.1

**Comment by technoweenie** [comment]
Unfortunately, that looks like a temporary issue with S3.

I would try the `git lfs clone` command. That way if there are errors, you can still run `git lfs pull` to continue where you left off. It also downloads files in parallel, so it should go much faster.

**Comment by scott-plutovr** [comment]
Thanks for the reply! Unfortunately we haven't been capturing these verbose logs for everyone but have seen the initial clone fail more times than it has succeeded for the last few weeks of trying to get people setup.

And to clarify are you suggesting using `git lfs clone` instead of `git clone` for this initial cloning? Or in addition to `git clone`? 

When it fails we are doing:
`git reset ./*`
`git reset .gitattributes`
`git reset .gitignore`
`git reset .travis.yml`
`git checkout ./*`

but perhaps that is also overkill and we would be fine just using `git lfs pull` as you suggest above?

**Comment by scott-plutovr** [comment]
I just tried the original command on  the same system and it failed with a slightly different set of errors (see attached). Is this an issue I should report with GitHub since we are using their LFS backend?
[20160510T161955.8456864.txt](https://github.com/github/git-lfs/files/258296/20160510T161955.8456864.txt)
[welcome-clone-core2.txt](https://github.com/github/git-lfs/files/258295/welcome-clone-core2.txt)

**Comment by technoweenie** [comment]
I see this error in the log file:

> dial tcp: lookup github-cloud.s3.amazonaws.com: getaddrinfow: No such host is known.

That's a local DNS issue on your end. You're welcome to talk to me about this in an official github context by submitting through https://github.com/contact if you like.

**Comment by scott-plutovr** [comment]
That's interesting. We are using the google public DNS servers (8.8.8.8 and 8.8.4.4) instead of the Comcast one that came with our business internet (as there were many more DNS failures using theirs). I will see if I can come up with anything substantial.

**Comment by ttaylorr** [comment]
Hi @scott-plutovr, just closing the loop on this issue since it has grown a little stale since originally being open. It looks like this was mostly related to a network connectivity/DNS thing, so hopefully the issue has been resolved (or, more likely, resolved itself 😄) since when this issue was originally opened.

If that's not the case, please do let me know here or elsewhere, and I'd be more than happy to dive in and take a look with you. Thanks!
