### ISSUE TITLE
git lfs clone doesn't ask for http password

### ISSUE THREAD

**Issue by sophana** [git-lfs/git-lfs#1216]
Hi

When a new user types `git lfs clone http://myrepo/repo.git`
He is prompted with the username, but then blocks. No password is prompted.

The workaround I found is to do a git clone instead. The user and password is prompted and then stored into ~/.git-credentials

Then git lfs clone works.

I'm on centos7, rpm versions:
git2u-2.5.1-1.ius.centos7.x86_64
git-lfs-1.2.0-1.el7.x86_64

**Comment by technoweenie** [comment]
Hi, thanks for the report. This is fixed in #1185, which should go out in the next release. I'm hoping to ship a new release in the next week or so.

**Comment by ttaylorr** [comment]
Fixed in: https://github.com/git-lfs/git-lfs/pull/1185.
