### ISSUE TITLE
lfs directory created in . by "git-lfs version"

### ISSUE THREAD

**Issue by javabrett** [git-lfs/git-lfs#1231]
I'm not sure if this is new or not; I don't recall it previously, but that could stem from a lack of testing of the `version` command from outside a repo.  From a clean git workspace at 841853d:

```
script/cibuild
$ cd ..
$ mkdir tmp
$ cd tmp
$ ../git-lfs/bin/git-lfs version
git-lfs/1.2.0 (GitHub; linux amd64; go 1.6; git 841853d)
$ ls
lfs
$ find .
.
./lfs
./lfs/objects
./lfs/objects/logs
./lfs/tmp
./lfs/tmp/objects
```

Should the version command be creating an lfs dir?  Perhaps this is in logging-init.

**Comment by technoweenie** [comment]
Thanks for the report. I think this happens when the `localstorage` package is initialized. Should probably make that an explicit method that has to be called by the commands that need it.

**Comment by ttaylorr** [comment]
Hi @javabrett, I was unable to reproduce this using the latest version of Git LFS.
