### ISSUE TITLE
Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by JoabMendes** [git-lfs/git-lfs#1238]
I installed the program through [apt-get](https://github.com/github/git-lfs/blob/master/INSTALLING.md) and when I try to run 
`git lfs install` or `git lfs track "*.output"` I am getting an error:

``` sh
/usr/local/bin/git-lfs: 3: /usr/local/bin/git-lfs: Syntax error: Unterminated quoted string
```

Any thoughts of what may be happening?

**Comment by javabrett** [comment]
If you installed from the packagecloud packages, I wouldn't expect to find your `git-lfs` in `/usr/local/bin/git-lfs`.  Nor would I expect it to be a script - is it?  What do you get for `/usr/local/bin/git-lfs version`?

I think you need to check what the version is at that path, and whether you need to be invoking a version at `/usr/bin/git-lfs`, presuming the package-install has left one there.

**Comment by technoweenie** [comment]
That error sounds like you somehow downloaded the `git-lfs` binary separately for another OS to `/usr/local/bin`. What happens when you run `file /usr/local/bin/git-lfs`?

**Comment by AIREL46** [comment]
I have the same problem.
It is not possible de get the version. At the contrary, I get an error:
/usr/local/bin/git-lfs version
bash: /usr/local/bin/git-lfs : impossible d’exécuter le fichier binaire : Erreur de format pour exec()
The file git-lfs seems no good.
What do you think about ?

**Comment by JoabMendes** [comment]
I gave up of using git-lfs, but I will leave the issue open since another person is having the problem.

**Comment by AIREL46** [comment]
Thanks for your answer, but I do not understand why Git-ifs does nothing !

**Comment by 92161898515** [comment]
#1726 @technoweenie 

> [](url)

**Comment by technoweenie** [comment]
@AIREL46 That error means you're running an LFS build for the wrong platform.

Quick fix: Download the correct binary from https://github.com/git-lfs/git-lfs/releases/tag/v2.2.1.

If you want to troubleshoot it, here are some basic questions:

1. What OS and architecture are you on?
2. How did you install Git LFS?
3. What happens when you run `file /usr/local/bin/git-lfs`?

**Comment by AIREL46** [comment]
1. Ubuntu 16.04 LTS
2. Download V2.2.1 and install
3. No operation

**Comment by technoweenie** [comment]
Did you download the linux version? What CPU architecture are you running? We only release for 32-64bit intel/amd CPUs. You'll have to compile yourself if you're running on something else, such as ARM.

You could also try the (Debian 9 package](https://packagecloud.io/github/git-lfs/packages/debian/stretch/git-lfs_2.2.1_amd64.deb) from PackageCloud.

**Comment by s3intBeko** [comment]
http://ghfvs-installer.github.com/unity/git/[osTYPE]/git-lfs.zip
try to change ur os type like linux
http://ghfvs-installer.github.com/unity/git/linux/git-lfs.zip
and change the file and ll be done ...
