### ISSUE TITLE
'push --all' ignores remote branches

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1254]
Found this discrepancy between `git lfs fetch --all` and `git lfs push --all`. `fetch --all` passes `lfs.ScanAllMode` to the scanner, which runs `git rev-list --do-walk --all`. This searches ALL local refs, even the ones in `refs/remotes/*`. The `push --all` command passes `lfs.ScanRefsMode`, which ignores any remote refs (see https://github.com/github/git-lfs/blob/release-1.2/commands/command_push.go#L78-L86).

**Comment by ttaylorr** [comment]
👋, I think that the difference between the two is a correct one. `git lfs push` should not be syncing remote tracking branches to the remote, that should occur the other way around. Hence, `git lfs fetch` runs `scanAll()`, and `git lfs push` does not.
