### ISSUE TITLE
Removing a file from git-LFS because no more space

### ISSUE THREAD

**Issue by Felina-Lain** [git-lfs/git-lfs#1261]
Hello, sorry to bother, but I've been trying to find how to manage my git-LFS
I was expecting some sort of system, like git itself, where I could see the files I have on LFS repositories and manage them, but I cannot find such thing anywhere

it's really a problem because I got a mail saying I just filled my space quota, and I can't use git-LFS anymore, so I was thinking of deleting some old files from it, and free space, but I can't find how to do so.

I'm using Source Tree as interface for git

Thanks in advance

**Comment by sinbad** [comment]
This is going to depend on what server you're using, but the only way you can remove LFS files from repositories is to change history; this usually means destroying the repo on the server end and re-uploading a different repo to replace it which references fewer LFS files (or less history). Whether that will end up automatically reducing your usage on the server or whether you have to do something else to reclaim the space depends on the server provider.

**Comment by Felina-Lain** [comment]
I wasn't even aware that there are different servers...
I just clicked the Source-tree button, saying "initializing Git LFS" and tracked the files I wanted...
The mail I received is from github itself, so I suppose it's their server.

If I delete all files on my repo, and push that, it should also delete all files on the server right? Including LFS? (I'm asking since you seems to know more than I do XD)
So if I copy my local things somewhere else, erase it all, push the erase, then copy the last version with no heavy files, and push that version... would it work?

**Comment by sinbad** [comment]
>  just clicked the Source-tree button, saying "initializing Git LFS" and tracked the files I wanted...
The mail I received is from github itself, so I suppose it's their server.

Initialising Git LFS in SourceTree sets up your local repo for LFS, but it's pushing which then sends the content to the server you're using. 

> If I delete all files on my repo, and push that, it should also delete all files on the server right?

Assuming you mean delete & commit this deletion as a change, no - that only deletes them from the latest version, they're all still referenced by the history of your repo. That's what I mean when I said you'd need to change history to truly get rid of them. There are various ways with different levels of complexity but if you don't care that much about your history the easiest way is to start again with a fresh repo, commit just the files you want and then delete the repo on GitHub and push the replacement fresh one instead. If you want to keep some of the other history it'll be more complicated. 

I don't know how / if GitHub reclaim LFS space on your account if you do something like this though, best to check with @technoweenie.

**Comment by Felina-Lain** [comment]
alright, thanks for the answers in any case, I'll see what I'll do, and look around some more :)

**Comment by ttaylorr** [comment]
Hi @Felina-Lain, you can now do this with `git lfs migrate export`. To remove a specific file, say `/path/to/file.txt` from _all_ history when being stored in Git LFS, you can run the following:

```ShellSession
$ git lfs migrate export --include="/path/to/file.txt" --everything
```

and all should work as expected. If it doesn't, please don't hesitate to let me know here. Thanks!

**Comment by ve3** [comment]
> git lfs migrate expor

I've tried this command but when I list the files with `git lfs ls-files --all` they are still exists and GitHub LFS storage is not reduced.

**Comment by bk2204** [comment]
Hey,

You'd need to specify the appropriate patterns you're using in `.gitattributes` in the `--include` options in order for this to work correctly.  That also won't clear the GitHub LFS storage; to do that, you'll have to write into GitHub Support.
