### ISSUE TITLE
Clean filter is too slow

### ISSUE THREAD

**Issue by lcsthom** [git-lfs/git-lfs#1301]
I can't stage 4000 files (500MB total) on a windows seven / git lfs 1.2.0 / git 2.8.1 x64 / with SSD and 16Gb RAM.

It seems the filter is not parallelized.

**Comment by lcsthom** [comment]
In fact it succeeded but this is really slow (hours) to get rid of it. I know we can fasten smudge operations by disabling it and use git lfs pull instead. Is there a way to do the same for the clean operation?

**Comment by ttaylorr** [comment]
Hi @lcsthom, thanks for opening this issue. The clean filter is not currently parallelizable in the latest version of Git. You may be able to speed things up a bit by trying @sinbad's idea as mentioned [here](https://github.com/github/git-lfs/issues/376#issuecomment-190290030).

Let me know if that speeds things up for you 😄

**Comment by lcsthom** [comment]
Thanks for your reply but I can't do that, I count 200 users in my team and they should not be custumizing their gitconfig manually. Or we are gonna get too much trouble. By the way, it only hides the real matter ... And I also expected smudge to be quite fast but it is even slower. 
The only way to be acceptable would be to zip the files in one and only one big file. But I think something else must be done.

**Comment by ttaylorr** [comment]
Hi @lcsthom, I'm circling back to old issues that can be closed. The clean and smudge filters are both much faster in modern versions of Git LFS and Git, because of the `process` filter, which eliminates the overhead of spawning many processes. 

Can you give it a shot with that and let me know if we need to debug further?
