### ISSUE TITLE
git lfs clone --recursive or no--recursive question

### ISSUE THREAD

**Issue by dxm5118118** [git-lfs/git-lfs#1309]
hello,I am first time ask question

Uses git lfs clone, to the submodule:
1st, add --the recursive parameter, will not execute GIT LFS
2nd, does not add --the recursive parameter, will execute GIT LFS

**Comment by ttaylorr** [comment]
👋  Thanks for opening this issue.

Are you asking about the `--recursive` and `--no-recursive` options and what they do? Those options exist in the `git lfs clone` command to be passed down to the `git clone` command underneath (see [these](https://github.com/github/git-lfs/blob/master/git/git.go#L664-L714) flags). If you're asking about using LFS in submodules, you may want to look at the `--recurse-submodules` flag instead.

**Comment by dxm5118118** [comment]
thanks for replying my question.
I have not possibly talked clearly my question.
I use the command `git lfs clone --recursive ` or you said the command `git lfs clone --recurse-submodules `,cannot down the lfs files,that after checking out files, no GIT LFS process
If I use the command `git lfs clone` (no --recursive),will down lfs files,but cannot down submodules

@ttaylorr 
thank you

**Comment by ranyan777** [comment]
## Use `git LFS clone`, will be carried out in batch download.
## If the Git repo have submodule repo, the main Git repo will be batch download, but these submodule repo can't batch download, then downloading one by one, very slow.
##  So we want to batch download from lfs server when clone submodule repo use `git LFS clone --recursive`. 

![1](https://cloud.githubusercontent.com/assets/10387155/19594716/e888e0d4-97b8-11e6-9474-0db18b59c9d6.png)

![2](https://cloud.githubusercontent.com/assets/10387155/19594770/3d680184-97b9-11e6-84c7-2585406ce890.png)

@dxm5118118 @ttaylorr @jiangxin @ranyan777
