### ISSUE TITLE
Endless loop when fetching large files

### ISSUE THREAD

**Issue by ReDetection** [git-lfs/git-lfs#1330]
Hello. This might be related to #1204 and #468.

```
$  GIT_TRACE=1 git lfs fetch origin
17:42:40.931755 git.c:557               trace: exec: 'git-lfs' 'fetch' 'origin'
17:42:40.932243 run-command.c:351       trace: run_command: 'git-lfs' 'fetch' 'origin'
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config -l
Fetching HEAD
trace git-lfs: run_command: git rev-list --objects --no-walk 74edf2aadb94f87f003dd9218a61359c5308f5d6 --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: fetch Carthage/Build/iOS/ReactiveCocoa.framework.dSYM/Contents/Resources/DWARF/ReactiveCocoa [7d9ecc4ad4e86ceec8d70d801482e7a5692b740dd1c6bc3b47f767724c433695]
trace git-lfs: fetch Carthage/Build/iOS/ReactiveCocoa.framework/Modules/ReactiveCocoa.swiftmodule/arm.swiftmodule [88a0640522fb4c55a17ae67a1bb7a13a2cdd8e3d72815190e7ed88867a5ab273]
trace git-lfs: fetch Carthage/Build/iOS/ReactiveCocoa.framework/Modules/ReactiveCocoa.swiftmodule/arm64.swiftmodule [0a04ed7285cd060e13ada94413c1c948680d94ec759b90c003da01c5ee996cf4]
trace git-lfs: fetch Carthage/Build/iOS/ReactiveCocoa.framework/Modules/ReactiveCocoa.swiftmodule/i386.swiftmodule [20c30f1d7ef2966f6d4046afc1eceaae2ca86740c7766384e4a40ffae61a974f]
trace git-lfs: fetch Carthage/Build/iOS/ReactiveCocoa.framework/Modules/ReactiveCocoa.swiftmodule/x86_64.swiftmodule [1f3a236015df87b64186b15b128586a79d0c01676fcd26d55d6c58c3995230a5]
trace git-lfs: fetch Carthage/Build/iOS/ReactiveCocoa.framework/ReactiveCocoa [812a7ababc013c23e3100695f395ccb2e55b490e3445a6809a11867957d34144]
trace git-lfs: fetch Carthage/Build/iOS/Result.framework.dSYM/Contents/Resources/DWARF/Result [04e19269748e3a150cc25e4335453cb0866d11008518aa62ae7c0933d809d08d]
trace git-lfs: fetch Carthage/Build/iOS/Result.framework/Modules/Result.swiftmodule/arm.swiftmodule [f95cda99ee9d9acf32d7c642d4993a473cbc44d097c85c1eb3c7b65d1fdac5e2]
trace git-lfs: fetch Carthage/Build/iOS/Result.framework/Modules/Result.swiftmodule/arm64.swiftmodule [6aba5d1831295efc28cce5a574e221fe62e4e04d3dfc1673ce320e068c399662]
trace git-lfs: fetch Carthage/Build/iOS/Result.framework/Modules/Result.swiftmodule/i386.swiftmodule [bbc210efd215b0d6d0dc0c46da86d1d21291225fc155c2e17ccad3e002704bd0]
trace git-lfs: fetch Carthage/Build/iOS/Result.framework/Modules/Result.swiftmodule/x86_64.swiftmodule [53d057270eece9bf865b2878def81520a37a45fbd63aba4a04658e1f8cb0905f]
trace git-lfs: fetch Carthage/Build/iOS/Result.framework/Result [4aee6dcf4f6a087e52b162679240a8a68b74ff0ffb90df64d26304dc58ac96b5]
trace git-lfs: fetch Pods/Realm/core/librealm-ios.a [193d14643a473aaab392e8ae2533196eb17ef11d9312d3cd034b83c91f5a5328]
trace git-lfs: tq: sending batch of size 13
trace git-lfs: api: batch 13 files
trace git-lfs: HTTP: POST https://gitlab-ci-token:some-token@OUR_SERVER/group/app-ios.git/info/lfs/objects/batch
trace git-lfs: HTTP: 401
trace git-lfs: HTTP: Unauthorized
trace git-lfs: setting repository access to basic
trace git-lfs: run_command: 'git' config lfs.https://gitlab-ci-token:some-token@OUR_SERVER/group/app-ios.git/info/lfs.access basic
trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
trace git-lfs: api: batch 13 files
warning: current Git remote contains credentials
trace git-lfs: HTTP: POST https://gitlab-ci-token:some-token@OUR_SERVER/group/app-ios.git/info/lfs/objects/batch
trace git-lfs: HTTP: 401
trace git-lfs: HTTP: Unauthorized
trace git-lfs: setting repository access to basic
trace git-lfs: run_command: 'git' config lfs.https://gitlab-ci-token:some-token@OUR_SERVER/group/app-ios.git/info/lfs.access basic
trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...

```

We're hosting gitlab and running the gitlab runners and at first I thought that it's their fault but now I changed my mind. I think it's clear that if failed once, git-lfs should not repeat exact same request. 
Is there any way to workaround this?

**Comment by ReDetection** [comment]
This leads to a ban by IP on the gitlab side so I have to contact admins to get access back. Only if git-lfs could stop at first (or any small reasonable tries count), I would probably find it before ban.

**Comment by technoweenie** [comment]
The server should be responding 401 if no credentials are given, and 403 if credentials are bad. That will stop the loop.

**Comment by ReDetection** [comment]
Thanks for the reply! Can you please clarify: are you talking about general http response codes or some specific git usage? 

401 has the meaning "no valid credentials supplied, try again with valid ones". It is used for both "no credentials are given" and "wrong credentials are given". From RFC ```If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials.```

403 stands for "you have no permission to see resource". RFC cut `The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated`

**Comment by technoweenie** [comment]
The way Git LFS interprets it is that 401 response means no credentials are given. 403 means the credentials are invalid. This way the client always retries 401 requests, but halts on 403. If it didn't retry on 401 requests, then Git LFS wouldn't work on private repositories without setting a git config value.

**Comment by ReDetection** [comment]
But this is the misuse of HTTP protocol. Can you please point to the discussion where this decision was chosen?
What I see in the [git lfs docs](https://github.com/github/git-lfs/blob/12fe249f2eebb56608a825fdb4a68c00f090bc91/docs/api/v1/http-v1-batch.md#response-errors) is that 
```
403 - The user has read, but not write access. Only applicable when the operation in the request is "upload."
```
In my case I'm trying to download objects. Why should I get 403 then?
And I still can't get why you repeating same request infinitely, why can't stop when request stops changing?

**Comment by technoweenie** [comment]
> And I still can't get why you repeating same request infinitely, why can't stop when request stops changing?

I think that sounds like a worthy patch.

**Comment by technoweenie** [comment]
I'm not positive #1340 is the correct approach. The auth type isn't changing at all. I think this fix will prevent people from fixing passwords entered interactively.

> And I still can't get why you repeating same request infinitely, why can't stop when request stops changing?

The server _should_ return 401 when credentials are bad, giving the user an opportunity to correct the password. In your case, it looks like the credentials are embedded in the remote or lfs url config (common in ci servers), so the authorization won't change. 

I think the client may have to track the Authorization header in retried requests. If it's getting repeated 401s from requests with the same `Authorization` header, it should halt the loop. I think this would be better than detecting when the `AuthType` changes. Does that make sense?

**Comment by ReDetection** [comment]
That's a good point about interactive password, thanks. Not sure about the solution proposed. 
Maybe just count failures like in ssh? But anyway, current implementation of repeated requests does not allow to easily add any retry count without changing method signature. I'd rather postpone this, anyway I have a working solution now — ci is exacly my case.

**Comment by technoweenie** [comment]
Counting failures could work, as long as it gives users enough tries at the keyboard too. Even setting the retry count to just 5 should let the majority of users push successfully, while killing automatic ci jobs well before they reach the service's rate limit.

**Comment by ReDetection** [comment]
Sorry, would you mind to share your thoughts on why did you close the issue? Or you fixed the endless loop?

**Comment by technoweenie** [comment]
Closed by accident!

**Comment by ttaylorr** [comment]
The endless loop should be fixed, and if it isn't, please don't hesitate to let me or someone else know by posting a comment here, or elsewhere in a new issue. Thanks!

**Comment by Korijn** [comment]
I don't think this was ever fixed so I'm

> posting a comment here

**Comment by PeterMinin** [comment]
Still observing this behavior with Git LFW 3.1.4 (latest for Git for Windows).

**Comment by bk2204** [comment]
Hey,

As outlined in the contributing docs, if you're seeing a problem on an issue that's closed, please open a new issue and fill out the issue template so we can look into it, since it's likely a different problem.
