### ISSUE TITLE
git-lfs maintained files are marked as modified by 'git status'

### ISSUE THREAD

**Issue by fedorov** [git-lfs/git-lfs#1339]
I have the following: 

1) check out branch - get LFS pointer

2) do git lfs checkout or pull - get lfs files

3) do git status - lfs files are marked as modified. 

Is this the intended behavior?

This has been discussed on gitter with @shane-kearns. I apparently do have smudge/clean filters installed. I also have git-lfs 1.2.0 in the path. Running `git checkout -f HEAD` resets the lfs files to pointers.

**Comment by fedorov** [comment]
Repo in question https://github.com/fedorov/dcmqi/tree/add-bltest-data

**Comment by technoweenie** [comment]
First, there's no `.gitattributes` file. You should check that in so everyone on your team is tracking the same LFS files.

A `git status` change could mean that an existing file is tracked in `.gitattributes`, but wasn't added to the repo with Git LFS. So by checking out the branch, it's converting it to LFS.

**Comment by fedorov** [comment]
Thanks for your quick response!

I added `.gitattributes`, but still same behavior after branch checkout / git lfs checkout.

I am pretty sure I added the files with git-lfs, and github says "Stored with Git LFS".

**Comment by technoweenie** [comment]
Is that the same pattern you used before? I think you'll want to track `data/BLTests/**` instead, so it matches all the files in the various sub directories.

**Comment by fedorov** [comment]
I never edited that file manually. This line

https://github.com/fedorov/dcmqi/blob/add-bltest-data/.gitattributes#L1

was added by `git lfs track data/BLTests`. Is this a bug? When I add a directory to Git LFS, I expect that all files and subdirectories will be tracked.

After modifying `.gitattributes` as you suggested, I no longer see these files marked as modified by `git status` after `git lfs checkout`. I am hoping my issue is resolved! Thank you!

**Comment by fedorov** [comment]
@technoweenie if the tracked directory specification in `.gitattributes` is not a bug, feel free to close. I do find the current behavior of `git lfs track <directory>` confusing though.

**Comment by technoweenie** [comment]
Are the files correct after the checkout too, or are they just tiny LFS pointers?

The `git lfs track` command just inserts what you send it into `.gitattributes`. So, it's not a _bug_, but `git lfs track` should do more to help you track what you want. We're at the mercy of how `.gitattributes` works.

**Comment by fedorov** [comment]
> Are the files correct after the checkout too, or are they just tiny LFS pointers?

Yes, they appear to be complete files (at least those that I checked manually are!)

**Comment by kenkogi** [comment]
Did you ever find the answer to this @fedorov. I'm experiencing the same issue. Thanks.

**Comment by fedorov** [comment]
@kenkogi after all the idiosyncrasies of git-lfs, I gave up on it altogether

**Comment by technoweenie** [comment]
@kenkogi: Can you open a new issue with details of your problem? The common case is that your `.gitattributes` file doesn't match the state of your repository, and the modified files in `git status` are from git lfs's attempt to fix the repository.

**Comment by SozapBo** [comment]
I Have the exact same symtoms. 1. Pull LFS enabled repository. 2. All tracked files are them marked as modified after the pointers has been replaced with the actual files.

**Comment by divljikunic** [comment]
I guess this is how things are, huh? great :(

**Comment by technoweenie** [comment]
@divljikunic @SozapBo Can you open a new issue with details of your problem? The common case is that your .gitattributes file doesn't match the state of your repository, and the modified files in git status are from git lfs's attempt to fix the repository. If that's not what is happening, opening a separate issue with details will help us address your problems. Thanks!
