### ISSUE TITLE
github pages serving the reference file instead of the actual binary

### ISSUE THREAD

**Issue by jspillers** [git-lfs/git-lfs#1342]
I have a large file I am using git lfs to track as a part of a github.io repo. When I hit the URL to access the large file I am being served what I am assuming is the tiny reference file (134 bytes) instead of the large binary. 

The file that should be the large file has the following contents:

version https://git-lfs.github.com/spec/v1
oid sha256:805400bc5ba8c96f8dff29a70c88d29c0566340b063e66f62326a1d3c3ea78ae
size 110517008

It's strange because this was just working... it wasn't until I committed a new version of the large file to the repo that I started getting this behavior. git lfs untrack + git rm and then re-adding the file appears to get it to push, but when I try to access it I get the wrong file.

The file in question is: http://www.stacktact.com/dynamic_terrain_objects_demo/Demo.unity3d

**Comment by technoweenie** [comment]
GitHub Pages doesn't support Git LFS. This issue isn't really the place to discuss it (this repo is for the `git-lfs` client), but it is something I'd like to support.

**Comment by jspillers** [comment]
Sorry for the noise, I will close this issue. For the future: where is the correct place to get support for git-lfs related issues that are not specific technical issues with the client?

**Comment by technoweenie** [comment]
Depends on the issue. Since you're asking about GitHub Pages, you'll want to hit up GitHub Support: https://github.com/contact.

That said, I'll be forwarding this issue to the team, as a way to gauge interest in new features.

**Comment by maxnordlund** [comment]
I also would like this, and it seems like this was already mentioned in #791. On a more technical level, what would be required to allow public read access to the blob tracked by git-lfs?

I assume that that is the blocker here, after that it's just a matter of writing a jekyll plugin that transforms some hrefs.

Going with that assumption, there needs to be another API that allows for creation of unauthenticated links to the blob in question. Probably a new transfer API type would be good here.

PS. While I do understand that you want to keep GitHub out of this repo, having people contact support removes the discussion, and subsequent answers, from the public. This makes it very hard to figure/find out why it doesn't work. If there is another place where a public discussion should take place, please let us know. Anyway, just some thoughts. DS.

**Comment by oncletom** [comment]
I'd be interested to give some feedback or use cases about this feature – I currently include video files for a book written with Asciidoc, published on GitHub Pages as HTML pages amongst others.

Cf. oncletom/nodebook@6273c01d02a992f7d4ae15aa5af74866c5085522

**Comment by wwdc17** [comment]
Any updates?

**Comment by bhaskarvk** [comment]
+1 this could really help a lot of use cases.

**Comment by harpojaeger** [comment]
Adding my +1 to the mix too!

**Comment by kyledewey** [comment]
Another +1 here!

**Comment by IoriBranford** [comment]
Workaround:

1. Commit and push the LFS file
2. View the LFS file in web
3. Copy link address from Download button; should be in the form
```
https://github.com/USER/PROJ/raw/gh-pages/FILEPATH
```

**Comment by bryanhanson** [comment]
The workaround mentioned by @loriBranford didn't work for me, but this did:

```
https://github.com/USER/PROJECT/blob/gh-pages/PATH_TO_FILE?raw=true
```
I can't claim any great insight here, this is the path associated with the view raw link when you are in the repo looking at the file you want to access.

**Comment by royuttam** [comment]
Dear jspillers,
I faced the same problem. How did you overcome it?

**Comment by Akagilnc** [comment]
@royuttam 
https://media.githubusercontent.com/media/_Username_/_Project_/_Branch_/video/_Path_to_file_
You should replace all the _xxx_ things to your's
I tried it just now it worked fine for me

**Comment by bartlettroscoe** [comment]
This is not really a git-lfs issue but a GitHub Pages implementation issue, right?

**Comment by bk2204** [comment]
Yes, it is.  Talking to GitHub support is the best way to address this.

Since this isn't a Git LFS issue, I'm going to close this.
