### ISSUE TITLE
dpkg-query --search failed with code 31488,  at /usr/bin/dh_golang line 71 although the files are there

### ISSUE THREAD

**Issue by jean-christophe-manciot** [git-lfs/git-lfs#1474]
Ubuntu 16.04 4.4.0-34
go 1.7beta1
dh_golang 1.19
git-lfs git sources checkout 1.4.0
With release_number=1.4.0:

```
        echo --------
        echo Cleaning
        echo --------
        cd git-lfs
        git reset --hard
        git clean -fxd :/
        git checkout master
        git pull -v --progress --rebase
        return_code=$?
        if [[ $return_code != 0 ]]; then
                exit $return_code
        fi
        git checkout v${release_number}

        echo ---------------------------
        echo Checking Build Dependencies
        echo ---------------------------
        dpkg-checkbuilddeps

        echo --------
        echo Building
        echo --------
        dpkg-buildpackage -b -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"
...
   dh_makeshlibs -O--buildsystem=golang
   dh_shlibdeps -O--buildsystem=golang
   dh_installdeb -O--buildsystem=golang
   dh_golang -O--buildsystem=golang
dpkg-query: no path found matching pattern /usr/lib/go/src/vendor/golang_org/x/net/http2/hpack/encode.go
dpkg-query: no path found matching pattern /usr/lib/go/src/vendor/golang_org/x/net/lex/httplex/httplex.go
dpkg-query --search failed with code 31488,  at /usr/bin/dh_golang line 71.
debian/rules:23: recipe for target 'binary' failed
make: *** [binary] Error 123
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```

Although:
- encode.go is already in $GOPATH/src/golang.org/x/net/http2/hpack
- httplex.go was not there, but its absence has not been detected by dpkg-checkbuilddeps

```
go get golang.org/x/net/lex/httplex
```

Another run of the build leads to the exact same 2 issues.

**Comment by technoweenie** [comment]
I had a similar failure trying to release Git LFS v1.4.0 on debian stretch yesterday: https://github.com/github/git-lfs/pull/1472. Seems related to dh_golang and go 1.7.

**Comment by ttaylorr** [comment]
We still use dh_golang, but are three major Golang versions ahead of when this issue was originally opened. Since it has remained quiet for a while, and I am able to install Git LFS correctly, I am going to assume that it isn't an issue any longer.

If this isn't the case, please do not hesitate to let me know here, and I would be more than happy to take a look in the future. Thanks!
