### ISSUE TITLE
Distribute packages using official repos of distros

### ISSUE THREAD

**Issue by KOLANICH** [git-lfs/git-lfs#1475]
It is problematic to install git-lfs on gnu/linux. It asks me to download and run some shell script from some location. I have downloaded it and checked. It seems to be OK, but the files it downloads ... are missing. You should end this mess and use the official repos of distros.

**Comment by technoweenie** [comment]
Good idea, but I'll need some help with that. If you don't want to run some shell script from some location, check out [our packages on PackageCloud](https://packagecloud.io/github/git-lfs). Does that work?

What files are missing?

**Comment by ttaylorr** [comment]
Hi, we now distribute packages on PackageCloud, which you can download yourself or install via a script. If that's not OK, then you can use the Ubuntu Universe repository to install relatively recent version of Git LFS. I'm not a package maintainer on other distribution's official set of repositories, so I would need some help from someone who is to get Git LFS distributed there.
