### ISSUE TITLE
Windows/tfs authentication with user@domain

### ISSUE THREAD

**Issue by Tasteful** [git-lfs/git-lfs#1481]
We are authenticating with user@domain instead of netbios\samaccount name. When I tried to push files i got message that the authentication should be domain\username. Is there any in the API that make the format mandatory or is it only the validation on https://github.com/github/git-lfs/blob/master/httputil/ntlm.go#L28 that not cover user@domain type of login?

**Comment by technoweenie** [comment]
@WillHipschman Can you answer this? I don't use NTLM stuff :)

**Comment by WillHipschman** [comment]
Only the validation doesn't cover user@domain logins--the API should work fine (I haven't tested this).

You can submit a change to split user@domains and pass both parts into 	

`session.SetUserInfo(user, creds["password"], strings.ToUpper(domain))`

**Comment by WillHipschman** [comment]
FYI, this will only work if your lfs server is authenticating with the NTLM protocol, which I didn't see explicitly stated in your question. (it won't work with others like kerberos, etc.)

**Comment by Tasteful** [comment]
I haven't inspect the httprequest but the server is setup to work with both ntlm and basic authentication.

If i'm remmember correct (for a c# project) i doing something simular but I pass the full username@domain as user and null string as domain into the  advapi32.dll LogonUser.

**Comment by ttaylorr** [comment]
Hi @Tasteful, is this still an issue? Since this thread has been stale for quite some time, I am going to assume that this is OK to close for now. If this is not the case, please do let me or @WillHipschman know.

Thanks!

**Comment by Tasteful** [comment]
Hi. This issue still exists, mostly for new developers or if a developer get the environment reinstalled. We have make a note about this issue in our development environment setup instructions but it should be good if it can be solved so both username-types are working.

@ttaylorr @willhipschman

**Comment by bk2204** [comment]
This requests behaviour related to NTLM, and we no longer support NTLM.
