### ISSUE TITLE
git lfs prune hangs on windows 10

### ISSUE THREAD

**Issue by rsporny** [git-lfs/git-lfs#1494]
I'm stuck with
`git lfs prune`
command on Windows 10. It seems to hang up on calculating local objects:
`34 local objects, 39 retained`
and nothing happens next.

Windows 10
git version 2.7.0.windows.1 (git version 2.9.3.windows.2 as well)
git-lfs/1.4.1 (GitHub; windows amd64; go 1.7; git 2070e4c)
tested on git bash terminal and default windows command prompt

It works very well on mac and ubuntu, however it doesn't work on win10. Push/pull commands work very well.

Please help,
Radek

**Comment by technoweenie** [comment]
Hi @rsporny, can you include the full output from `GIT_TRACE=1 git lfs prune`?

**Comment by rsporny** [comment]
Hi
`$ GIT_TRACE=1 git lfs prune
14:52:08.515021 git.c:563               trace: exec: 'git-lfs' 'prune'
14:52:08.515021 run-command.c:336       trace: run_command: 'git-lfs' 'prune'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' rev-parse refs/heads/dev --symbolic-full-name refs/heads/dev
trace git-lfs: run_command: git log --branches --tags --not --remotes=origin -G oid sha256: -p -U12 --format=lfs-commit-sha: %H %P
/ 37 local objects, 0 retained                                                  trace git-lfs: PRUNE: Retaining non-HEAD refs within 10 (7+3) days
trace git-lfs: run_command: git rev-list --objects --no-walk 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6 --
trace git-lfs: RECENT: Getting refs >= 2016-08-21 14:52:08.6286449 +0200 CEST
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: RECENT: origin/dev (2016-08-31 10:32:07 +0200 CEST)
trace git-lfs: RECENT: dev (2016-08-31 10:32:07 +0200 CEST)
trace git-lfs: RECENT: origin/image2 (2016-08-31 09:53:38 +0200 CEST)
trace git-lfs: RECENT: origin/image1 (2016-08-31 09:48:00 +0200 CEST)
trace git-lfs: RECENT: image1 (2016-08-31 09:48:00 +0200 CEST)
trace git-lfs: RECENT: origin/master (2016-08-30 17:29:59 +0200 CEST)
trace git-lfs: RECENT: origin/HEAD (2016-08-30 17:29:59 +0200 CEST)
trace git-lfs: RECENT: master (2016-08-30 17:29:59 +0200 CEST)
trace git-lfs: RECENT: origin/j*** (2016-08-30 15:58:08 +0200 CEST)
trace git-lfs: RECENT: origin/m*** (2016-08-30 15:54:10 +0200 CEST)
trace git-lfs: RECENT: origin/p*** (2016-08-30 11:55:00 +0200 CEST)
trace git-lfs: RECENT: origin/p***-16-16 (2016-08-30 08:47:56 +0200 CEST)
trace git-lfs: RECENT: origin/A*** (2016-08-29 14:02:55 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-29 13:53:56 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-29 13:04:45 +0200 CEST)
trace git-lfs: RECENT: origin/R*** (2016-08-29 12:07:29 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-26 16:07:48 +0200 CEST)
trace git-lfs: RECENT: origin/S*** (2016-08-26 15:22:31 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-26 12:19:26 +0200 CEST)
trace git-lfs: RECENT: origin/S*** (2016-08-25 19:26:45 +0200 CEST)
trace git-lfs: RECENT: origin/S*** (2016-08-25 15:01:19 +0200 CEST)
trace git-lfs: RECENT: origin/r*** (2016-08-25 14:48:23 +0200 CEST)
trace git-lfs: RECENT: origin/i*** (2016-08-25 11:54:42 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-24 15:51:00 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-23 16:40:09 +0200 CEST)
trace git-lfs: RECENT: origin/c*** (2016-08-23 14:50:23 +0200 CEST)
trace git-lfs: RECENT: origin/P*** (2016-08-23 12:31:41 +0200 CEST)
trace git-lfs: RECENT: origin/S*** (2016-08-22 16:30:36 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-22 12:57:30 +0200 CEST)
trace git-lfs: RECENT: origin/N*** (2016-08-22 12:11:25 +0200 CEST)
trace git-lfs: RETAIN: 5b13d2a220198e81143c7641218afcda6331e19b024aa1300f3d2cec750361b7 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
trace git-lfs: RETAIN: 80fd621dd4aae9dc6ac1b632e24d568c30e25f7bfde9ac51f0f66ec1fa6d882a via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
\ 37 local objects, 2 retained                                                  trace git-lfs: RETAIN: 8be2e258e91288010cca32b2d71cd445ef785587342762b86a65d111a2574dff via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 3 retained                                                  trace git-lfs: RETAIN: 6a8f60f741a5fc439e82853cb4182fd7f38ec984e3192acec4ea06e494aacbc2 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 4 retained                                                  trace git-lfs: RETAIN: e345acc97dc748be814f61a3c32ec7ab892a722a2c7ffae8942b1564ebd3f525 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
trace git-lfs: RETAIN: c50310b42089b780cb5161e5050ff23025065877c93d4377736746deff4c045d via ref 49ad2ed0c1cd1bef697f9e1a362ed37a32f5b8d6
- 37 local objects, 5 retained                                                  trace git-lfs: RETAIN: 8fa8a03118fecbd14ef1910e41a566d50b0580d6248aaf8b4887101d7f99f5cb via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
\ 37 local objects, 6 retained                                                  trace git-lfs: RETAIN: 5e8e0c9aa20d5bb5d048ffc9113318b0cfc00781f11797c45df7629a37425257 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 7 retained                                                  trace git-lfs: RETAIN: 120ad0814f206c45d968b05f7535034ecfee8ac1a0958cd984a070dad31f66f3 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 8 retained                                                  trace git-lfs: RETAIN: 0800cdd72c6acb6a71b3e9f6d77e4876590561c3d2d2452f11188af84f6609d6 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
\ 37 local objects, 10 retained                                                 trace git-lfs: RETAIN: 4993521a8c8222721261e6cd583518a745843a53f8e1e13422fb9e4f13c09ee5 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 11 retained                                                 trace git-lfs: RETAIN: e30c259dda3a0b501a74af156506dffc0881c2d945d2e302747fe5775253e3c1 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 12 retained                                                 trace git-lfs: RETAIN: f080086dc2edbfee433e5f7b6bc6aeba03905c7439bbce9735799aaf1697a9c8 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
- 37 local objects, 13 retained                                                 trace git-lfs: RETAIN: b62e0cb3c80a771602fc3606367af3146195220919173a9b9979ac55166f8a7d via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 15 retained                                                 trace git-lfs: RETAIN: 3cb60e6fdf958032acf59f273b40a500a5ac72dc24bb05531e455cb3c24cdbba via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
trace git-lfs: RETAIN: 8ed5f2a21be7a81bb9c67376c090ee553048b3d3af50016117b1e018330e91e8 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
trace git-lfs: RETAIN: ed5fbfd0ca488edc6d94c275c609d894d43d87e72922f76332333034cca7e071 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
- 37 local objects, 17 retained                                                 trace git-lfs: RETAIN: 9e23984f5d850b8d5fa177d13aa1bab36019f538ad23091ca8b8c0a1782b2f49 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
trace git-lfs: RETAIN: fb9baf583b534c7416fe45da1262e2c1ff01590aefcac6a464ebeb35de4aebc6 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 19 retained                                                 trace git-lfs: RETAIN: 7eef11a77abe515befd6825ae2646dccf579edbcdefbdd224ba0e0a68833efa3 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 20 retained                                                 trace git-lfs: RETAIN: 07d11170fe30596ca17302682d2545e09862a8dcdf90c76fa90b70d381eb4973 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
- 37 local objects, 21 retained                                                 trace git-lfs: RETAIN: 983d09b073437b04df18937a83420369f7f7ec067a2c084dfe89c697a5528c26 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
\ 37 local objects, 22 retained                                                 trace git-lfs: RETAIN: ca4a60655def5e9de497f8cfe73a15698f546cb012d80e6c09cd549b706ee25d via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
trace git-lfs: RETAIN: c095e403d2fc8bc4fd5c9729a7259690a625f63113a829a758185dae4149b6e5 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 24 retained                                                 trace git-lfs: RETAIN: 5aef698c9933285a54edfbea0f23aee5c018a75e8c03e7290ac8afe2f49f6eac via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
- 37 local objects, 25 retained                                                 trace git-lfs: RETAIN: a38acd84dcd84f8fb4c8f86827c0489f3b2cb638c823219b5fd3efa7c34a7fcb via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
\ 37 local objects, 26 retained                                                 trace git-lfs: RETAIN: f071b518d1d762428ef3ea8b7b9f9cf547728b307860b6f9a9da26e32e010f8c via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 27 retained                                                 trace git-lfs: RETAIN: 81dba3aaa1b069e84fdc8660ad8262f4cd86bec527508424b82b174562f36935 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 28 retained                                                 trace git-lfs: RETAIN: b9a27e87928fafc45ebee0d2a534bb225208ac69e9398234a02de1d591d3eaf2 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
- 37 local objects, 29 retained                                                 trace git-lfs: RETAIN: 62ff005e222d9c51198bc79ea148886b1512ceb05e29c0f429d86334536acc3a via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
\ 37 local objects, 30 retained                                                 trace git-lfs: RETAIN: 0f1861b01c568a44c21639354ca13d51b7d9745478ccece7b9323b50d434cc22 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
| 37 local objects, 31 retained                                                 trace git-lfs: RETAIN: 10531d6295c8f67910c1ca875d714b8e357788b38dd2734ff81c50855214feaf via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
/ 37 local objects, 32 retained                                                 trace git-lfs: RETAIN: 48482a90de7a69e545e07c1cc1586f75bf9414a0a9326b1addbe0599d6454179 via ref 49ad2ed0c1cd1bef697f9e1a362ed37a31f5b8d6
- 37 local objects, 33 retained`

**Comment by rsporny** [comment]
We've tested it on brand new lfs-enabled repo, with exactly the same binaries and it works. The issue occurs on existing repo converted and migrated according to [https://github.com/bozaro/git-lfs-migrate](url).
There are no logs at all in \repo\.git\lfs\objects\logs\

**Comment by sinbad** [comment]
Are you sure it had hung? Looking at the code, the spinner actually only progresses when it has something to write (like a new retained object). In your case it looks like it retained almost all of the objects just at `HEAD`, but you have a *lot* of other recent branches. It would have to check all those branches too, but if none of the objects were new it wouldn't write anything new, so no spinner activity. We should probably change this so that the spinner ticks over regardless while the process is continuing.

**Comment by rsporny** [comment]
We've waited for 8 hours and nothing happened. However, we did the same steps on clean repo (with just one branch and the same binaries), migrated it to lfs and it works. Seems like there is a problem with a large number of branches. Do you have any suggestion what we should do?

**Comment by sinbad** [comment]
Hrm. I've taken a look at the code but haven't spotted the issue yet. If you don't care about keeping all the binaries at every remote branch, just at local branches, you could run it as follows:
```
git -c lfs.fetchrecentremoterefs=false lfs prune
```
Any object which are solely at a remote branch and not a local branch will be pruned then, if it is the number of branches involved that would avoid it. Our tests do include cases with multiple branches but maybe there's some threshold, or maybe it's some specific layout which is the problem; hard to tell without access to the repo.

**Comment by sinbad** [comment]
It might help if we had some a comparative trace log from Mac/Linux if you're saying the prune works there on this repo. If you can get the local clones into the same state, for example by checking out the same branches and also using `git lfs fetch --all` to ensure you have all the LFS objects locally, then run `git lfs prune` with `GIT_TRACE=1`. The first step that's reported in the successful Mac/Linux trace that's not in the Win10 trace might give us more of a clue where to look.

**Comment by rsporny** [comment]
[mac.txt](https://github.com/github/git-lfs/files/471742/mac.txt)
[win10.txt](https://github.com/github/git-lfs/files/471743/win10.txt)
`git lfs prune` with `GIT_TRACE=1` on mac and win10

**Comment by sinbad** [comment]
Thanks, looks like Windows did manage to determine the complete set of objects it needed to retain, it just never got to the prune itself (not even displaying the `Pruning 23 files` message). Suggests a problem closing a channel, or possibly a process not exiting, in certain circumstances.

On Windows 10 when it hangs, are there any other git processes running? If it's a failure of one of the utility commands to exit cleanly you should see it in Task Manager.

(Apologies for the slow turnaround, I only spend at most one day a week on LFS now)

**Comment by jpschwinghamer** [comment]
Also seeing this on MacOS:

```
~/Development/app me/branch-name git lfs prune GIT_TRACE=1
\ 7 local objects, 0 retained
```

Just hangs here and never resolves. ^

**Comment by ttaylorr** [comment]
> `~/Development/app me/branch-name git lfs prune GIT_TRACE=1`

The `git-lfs` process doesn't see the `GIT_TRACE=1` in its environment, because it's evaluated after the process invocation.

Can you try instead:

```bash
$ GIT_TRACE=1 git lfs prune
```

**Comment by shoelzer** [comment]
This just happened to me for the first time. It's on a machine that's been using LFS for a quite a while, and the problem started after I updated Git for Windows (which included an update to LFS). The prune command would never finish, but I eventually got things working again by deleting `.git/lfs` and then doing `git lfs pull`.

    > git --version --build-options
    git version 2.17.1.windows.2
    cpu: x86_64
    built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
    sizeof-long: 4
    
    > git lfs --version
    git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
    
    > cmd.exe /c ver
    Microsoft Windows [Version 10.0.15063]

Unfortunately I'm not sure which version of Git for Windows or LFS was on the machine before the update.

**Comment by ttaylorr** [comment]
Hi @shoelzer, thanks for dropping a comment here. Do you mind if I redirect you to open a new issue elsewhere? This one is quite stale and I suspect that something else is going on.

**Comment by shoelzer** [comment]
@ttaylorr I opened #3095.
