### ISSUE TITLE
Include http.extraHeader in requests

### ISSUE THREAD

**Issue by Tasteful** [git-lfs/git-lfs#1500]
Git-command have the possibility to pass additional [http-headers](https://github.com/git/git/blob/a42d7b6a5b5addcce01f483547ad96825c7a96e0/Documentation/config.txt#L1733) with the request. This is used by [VSTS](https://github.com/Microsoft/vsts-tasks) build agent (Team Foundation Server) to pass OAuth token in an `AUTHORIZATION: bearer`-header when fetching the files from the server instead of using cached credentials. 

Example how the agent is setting the value

```
git config http.https://fabrikam.visualstudio.com/DefaultCollection/Fabrikam/_git/Fabrikam.extraheader "AUTHORIZATION: bearer ********"
```

Is it possible that git-lfs can pass the extra headers with the request?

**Comment by technoweenie** [comment]
Wow, I had no idea about that. Very possible. :+1:

**Comment by technoweenie** [comment]
@Tasteful What is the git remote you're using? Is it `https://fabrikam.visualstudio.com/DefaultCollection/Fabrikam/_git/Fabrikam`? I'm unfamiliar with how VSO urls work.

It's not super clear how the LFS http client would pick out the correct headers. A typical git and lfs server setup should look something like this:

* Git: `https://git-server.com/user/repo.git`
* LFS: `https://git-server.com/user/repo.git/info/lfs`

LFS builds its default url by adding `info/lfs` to the end of the git url: `{git-remote}/info/lfs`. The LFS client uses this as a base to speak to various APIs: `{lfs-url}/objects/batch` or `{lfs-url}/locks`. What git config key should LFS use when talking to `{lfs-url}/objects/batch`?

1. The git remote: `https://git-server.com/user/repo.git`
2. The lfs url: `https://git-server.com/user/repo.git/info/lfs`
3. The full url: `https://git-server.com/user/repo.git/info/lfs/objects/batch`

If we go with option 1, extra headers for your git server will get applied to your LFS api requests. However, it breaks if the user configures this with custom `lfs.url` or `remote.origin.lfsurl` git config settings, since we probably don't want to send the same headers to an LFS service hosted separately from your Git service.

Option 2 works, but we may want to add lfs specific config values like so that Git doesn't try to use them.

I didn't see much in the git config docs that talk about how git uses it. May have to dig into Git code...

**Comment by Tasteful** [comment]
Here is the some environment information, I replaced the actual domainname, project and repository name with placeholders.

git config -l --local
```
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.autocrlf=true
remote.origin.url=https://domainname/DefaultCollection/projectname/_git/repoitoryname
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.https://domainname/DefaultCollection/projectname/_git/repoitoryname.git/info/lfs.access=ntlm
```
git lfs env
```
git-lfs/1.3.1 (GitHub; windows amd64; go 1.6.3; git 9c9dffb)
git version 2.9.3.windows.1

Endpoint=https://domainname/DefaultCollection/projectname/_git/repoitoryname.git/info/lfs (auth=ntlm)
LocalWorkingDir=C:\repos\repoitoryname
LocalGitDir=C:\repos\repoitoryname\.git
LocalGitStorageDir=C:\repos\repoitoryname\.git
LocalMediaDir=C:\repos\repoitoryname\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\repos\repoitoryname\.git\lfs\tmp
ConcurrentTransfers=1
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=ntlm
AccessUpload=ntlm
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

from `git lfs fetch` with `GIT_TRACE=1`
```
trace git-lfs: HTTP: POST https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"56e27cc3f50ae7fc3249cb5a8d955ffd8543bcd96fe0176f47a5b1879c089555","size":222408,"_links":{"download":{"href":"https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/56e27cc3f50ae7fc3249cb5a8d955ffd8543bcd96fe0176f47a5b1879c089555","header":{"Accept":"application/vnd.git-lfs"}}}},{"oid":"3be1912a86b8bfa4c5ab3ab965405013dc3573b633229c7940a453529f89173d","size":67984,"_links":{"download":{"href":"https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/3be1912a86b8bfa4c5ab3ab965405013dc3573b633229c7940a453529f89173d","header":{"Accept":"application/vnd.git-lfs"}}}},{"oid":"ff85032a493319a2fe233fc8469dfbd051d8b783ad7f526fd591d2cdfc558639","size":18636554,"_links":{"download":{"href":"https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/ff85032a493319a2fe233fc8469dfbd051d8b783ad7f526fd591d2cdfc558639","header":{"Accept":"application/vnd.git-lfs"}}}},{"oid":"e3d03f8bc9039b532382a088656d330441529794a4aaba7b82f2db13a152f038","size":67642,"_links":{"download":{"href":"https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/e3d03f8bc9039b532382a088656d330441529794a4aaba7b82f2db13a152f038","header":{"Accept":"application/vnd.git-lfs"}}}},{"oid":"2996a24e554a1f371733e0ef383ee68db955cb08fb6e2ca5be1c27f9a8a78071","size":22789815,"_links":{"download":{"href":"https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/2996a24e554a1f371733e0ef383ee68db955cb08fb6e2ca5be1c27f9a8a78071","header":{"Accept":"application/vnd.git-lfs"}}}},{"oid":"15e052c697596d2d498eb52444a881aacd0df2e39138c93d1c7d3a99d9a3e2db","size":2746752,"_links":{"download":{"href":"https://domainname/tfs/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/15e052c697596d2d498eb52444a881aacd0df2e39138c93d1c7d3a99d9a3e2db","header":{"Accept":"application/vnd.git-lfs"}}}}]}
....
Git LFS: (0 of 6 files) 0 B / 42.47 MB                                                                                                trace git-lfs: HTTP: 200
Git LFS: (0 of 6 files) 217.20 KB / 42.47 MB                                                                                          trace git-lfs: xfer: adapter "basic" worker 0 finished job for "56e27cc3f50ae7fc3249cb5a8d955ffd8543bcd96fe0176f47a5b1879c089555"
trace git-lfs: xfer: adapter "basic" worker 0 processing job for "3be1912a86b8bfa4c5ab3ab965405013dc3573b633229c7940a453529f89173d"
trace git-lfs: Filled credentials for https://domainname/DefaultCollection/projectname/_git/repositoryname
trace git-lfs: HTTP: GET https://domainname/DefaultCollection/projectname/_git/repositoryname/info/lfs/objects/3be1912a86b8bfa4c5ab3ab965405013dc3573b633229c7940a453529f89173d
```

and extra headers is set with the following when running on the build server
```
git config http.https://domainname/DefaultCollection/projectname/_git/repositoryname.extraheader "AUTHORIZATION: bearer ********"
```

Maybe something like the follwoing
* If client have set `remote.origin.lfsurl` try to match for `http.{remote.origin.lfsurl}.extraheader`
* Else if client have set `remote.origin.lfsurl` try to match for `http.{remote.origin.lfsurl without /info/lfs}.extraheader`
* Else if the client have set `lfs.url` try to match for `http.{lfs.url}.extraheader`
* Else if the client have set `lfs.url` try to match for `http.{lfs.url without /info/lfs}.extraheader`
* Else if the client not have set any overrides try to match for `http.{git-remote}.extraheader`

**Comment by TingluoHuang** [comment]
@technoweenie I think you can have different http.extraheader for different base url.
Ex.
```
git -c http.https://github.com.extraheader="Authentication Basic xxxxx" -c http.https://githublfs.com.extraheader="Authentication Bearer xxxx" push 
```
So, for request url that match https://github.com it will use the Basic Auth header, for request url match https://githublfs.com it will use the Bearer Auth header.

**Comment by technoweenie** [comment]
Hey, I started playing around with a fix for this: https://github.com/git-lfs/git-lfs/pull/1912

It's pretty early still, and focuses on looking at the correct git config keys, making sure we support different values for different urls as you mentioned, @TingluoHuang.

**Comment by mmarchetti** [comment]
I don't normally +1 but I'd like to put in my vote here too. My app's LFS endpoints create pre-signed S3 URLs to enable the client to upload and download, so they need to be access controlled. The authorization model is also based on OAuth2 Bearer tokens, and they are too big to be stuffed into a Basic auth header. Git's `http.extraHeader` works great for the git-http endpoints and it would be great if it worked for LFS too.

**Comment by ttaylorr** [comment]
Added support for this in https://github.com/git-lfs/git-lfs/pull/2159, which will be included in the next 2.1.0 release of LFS 🎉

**Comment by arche89** [comment]
Hi,

I recently set up Azure DevOps Server with local agent and I have the same issue. In attached file is log from 'Checkout' step of build pipeline.
[log_4_38.zip](https://github.com/git-lfs/git-lfs/files/3012084/log_4_38.zip)

**Comment by bk2204** [comment]
I think we're looking at this issue in #3571.
