### ISSUE TITLE
`git lfs track` uses LF on Windows

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#1543]
### Setup

```
git-lfs/1.4.1 (GitHub; windows amd64; go 1.7; git 2070e4c)
git version 2.9.2.windows.1 
Win 7 & Win 8.1
```
### Steps to reproduce

``` bash
$ git init .
$ touch test1
$ git add .
$ git commit -m "test1"
$ echo "large" > test2
$ git lfs track test2
$ git add .

warning: LF will be replaced by CRLF in .gitattributes.
The file will have its original line endings in your working directory.
```

I think `git lfs track` should use CRLF in the `.gitattributes` file on Windows to avoid this warning.

**Comment by ttaylorr** [comment]
Thanks for opening this. We do use `-text` in the `.gitattributes` file (we used to use `-crlf`, but that was renamed to `-text`in Git 1.7.2, and updated in https://github.com/github/git-lfs/pull/475). According to the [documentation](https://git-scm.com/docs/gitattributes) for `.gitattributes`, `-text` does preform an "end-of-line normalization", unless there are competing values from either `core.eol` or `core.autocrlf`.

Can you see what those values are?

**Comment by larsxschneider** [comment]
Thanks for looking at this! `core.autocrlf` is set to `true` and `core.eol` is not defined.

However, I think end-of-line normalization is not the problem. That actually works correctly! I think Git LFS should write the `.gitattributes` file with CRLF to avoid the warning above, no?

**Comment by ttaylorr** [comment]
Ha, I totally misread this on my flight last night 💤 . You're saying that the `.gitattributes` file _itself_ isn't actually written with CRLF-style line endings?

**Comment by ttaylorr** [comment]
Taking another look at this: I'm wondering what the desired behavior is. Should the contents of `.gitattributes` match the native EOL? Should it match what Git converts them to?

Whatever we pick will be easy enough to detect and write, but the challenge is picking the right thing, and dealing with the existing behavior (of just writing LF).

**Comment by larsxschneider** [comment]
The contents of the `.gitattributes` should be written with native EOL. Git would automatically convert them to LF internally and not print the warning anymore.

AFAIK the outcome should be exactly the same as it is right now but we wouldn't confuse the user with the warning anymore. Does this make sense to you or should I try to find better words?

**Comment by ttaylorr** [comment]
After some thought and discussion with @peff, I'm going to punt on this for the the v1.4.2 release. Without trusting the settings, we could just as easily fall into a situation where we silence the warning from Git, but make the file un-editable from the OS.

**Comment by sschuberth** [comment]
> The contents of the .gitattributes should be written with native EOL.

What do you suggest should happen on Windows if a `.gitattributes` with LF already exists in the working tree? I guess the logic would be, if the file already exists, use whatever EOL it already uses, and if the file gets newly created, use native EOL?

**Comment by technoweenie** [comment]
I think there'd be some order of preference when deciding what line ending to use:

1. What does the file use now?
2. How is the git repo configured?
3. What about the OS native setting?

**Comment by technoweenie** [comment]
Attempted a fix: https://github.com/git-lfs/git-lfs/pull/1914
