### ISSUE TITLE
git-lfs install not working

### ISSUE THREAD

**Issue by erbanach** [git-lfs/git-lfs#1554]
Hi there,

I followed the installation instructions for git-lfs but am still getting this error in Terminal when I run `git lfs intall`:

```
git: 'lfs' is not a git command. See 'git --help'.
Did you mean this?
log
```

I am on the macOS operating system. Thanks!

**Comment by ttaylorr** [comment]
Hi @erbanach, thanks for opening this issue. The error you posted means that your computer can't find the Git LFS binary to execute. This can be for one of two reasons, either it was installed correctly, but your system isn't searching in the right place, or it was installed incorrectly, and it's not on your system at all.

If you're using Homebrew, I highly recommend running:

```bash
$ brew install git-lfs
```

This will allow you to easily install and upgrade git-lfs as we push out new releases.

**Comment by erbanach** [comment]
Thank you for your reply! I got this error:

Liz-Banach:~ splashnw$ brew install git-lfs
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for git-lfs: go
==> Installing git-lfs dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.6.3.src.tar.gz
Already downloaded: /Users/splashnw/Library/Caches/Homebrew/go-1.6.3.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10
Already downloaded: /Users/splashnw/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
==> ./make.bash --no-clean
Last 15 lines from /Users/splashnw/Library/Logs/Homebrew/go/02.make.bash:
bootstrap/compile/internal/gc.compile(0xc208d6a480)
	/private/tmp/go-20161003-3791-jpt1nc/go/src/cmd/compile/internal/gc/pgen.go:478 +0xd65 fp=0xc20d073b30 sp=0xc20d0739e8
bootstrap/compile/internal/gc.funccompile(0xc208d6a480)
	/private/tmp/go-20161003-3791-jpt1nc/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c4 fp=0xc20d073ba8 sp=0xc20d073b30
bootstrap/compile/internal/gc.Main()
	/private/tmp/go-20161003-3791-jpt1nc/go/src/cmd/compile/internal/gc/lex.go:472 +0x23a7 fp=0xc20d073e38 sp=0xc20d073ba8
bootstrap/compile/internal/amd64.Main()
	/private/tmp/go-20161003-3791-jpt1nc/go/src/cmd/compile/internal/amd64/galign.go:127 +0x768 fp=0xc20d073ec0 sp=0xc20d073e38
main.main()
	/private/tmp/go-20161003-3791-jpt1nc/go/src/cmd/compile/main.go:32 +0x17b fp=0xc20d073f98 sp=0xc20d073ec0
runtime.main()
	/private/tmp/go-20161003-3791-jpt1nc/go/gobootstrap/src/runtime/proc.go:63 +0xf3 fp=0xc20d073fe0 sp=0xc20d073f98
runtime.goexit()
	/private/tmp/go-20161003-3791-jpt1nc/go/gobootstrap/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20d073fe8 sp=0xc20d073fe0
go tool dist: FAILED: /private/tmp/go-20161003-3791-jpt1nc/go/pkg/tool/darwin_amd64/compile -pack -o /var/folders/0k/8wlq3fjs0l9c7zz9666l1jk40000g_/T/go-tool-dist-796692306/runtime/_go_.a -p runtime -+ -asmhdr /var/folders/0k/8wlq3fjs0l9c7zz9666l1jk40000g_/T/go-tool-dist-796692306/runtime/go_asm.h /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/alg.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/atomic_pointer.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/cgo.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/cgocall.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/cgocallback.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/cgocheck.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/chan.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/compiler.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/complex.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/cpuprof.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/cputicks.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/debug.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/defs_darwin_amd64.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/env_posix.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/error.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/extern.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/fastlog2.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/fastlog2table.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/hash64.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/hashmap.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/hashmap_fast.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/heapdump.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/iface.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/lfstack.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/lfstack_amd64.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/lock_sema.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/malloc.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mbarrier.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mbitmap.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mcache.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mcentral.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mem_darwin.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mfinal.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mfixalloc.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mgc.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mgcmark.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mgcsweep.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mgcwork.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mheap.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mmap.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mprof.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/msan0.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/msize.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mstats.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/mstkbar.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/netpoll.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/netpoll_kqueue.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/os1_darwin.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/os2_darwin.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/os_darwin.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/panic.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/parfor.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/print.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/proc.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/race0.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/rdebug.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/rune.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/runtime.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/runtime1.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/runtime2.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/select.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/sema.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/signal1_unix.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/signal2_unix.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/signal_amd64x.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/signal_darwin.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/signal_darwin_amd64.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/signal_unix.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/sigpanic_unix.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/sigqueue.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/slice.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/softfloat64.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/sqrt.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/stack.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/string.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/stubs.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/stubs2.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/symtab.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/sys_nonppc64x.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/sys_x86.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/time.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/trace.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/traceback.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/type.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/typekind.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/unaligned1.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/vdso_none.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/wbfat.go /private/tmp/go-20161003-3791-jpt1nc/go/src/runtime/write_err.go: exit status 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by ttaylorr** [comment]
Oh no! This looks like a Homebrew/Go issue unrelated to Git LFS. Homebrew doesn't yet provide support for macOS Sierra, so in the meantime you are welcome to download the binary directly from https://git-lfs.github.com/, and place it somewhere in your `$PATH`. I keep my copy of `git-lfs` in `/usr/local/bin`.

**Comment by technoweenie** [comment]
Try updating your homebrew recipes with `brew update`. It looks like homebrew is still trying to use an older version of Go (1.6.3). The latest version of Go should support the pre-release MacOS.

**Comment by wesleymsmith** [comment]
I am getting the same problem, but on CentOs. I installed by running:

curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash

as root.
It appeared to install correctly, but whether as root or a standard user, I get the same error message if i try to use git lfs.

**Comment by ttaylorr** [comment]
Hi, I am going to close this issue for now since it is quite stale. Please don't hesitate to let me know if you're still encountering any issues and I'd be happy to help out here.
