### ISSUE TITLE
Cannot push repository with many files: resource temporarily unavailable

### ISSUE THREAD

**Issue by andyshinn** [git-lfs/git-lfs#1562]
I just converted a repository using BFG to track many PDF files (around 78,000). When I try to push, all the data gets to the server, but it eventually fails:

```
$ git push
Warning: remote port forwarding failed for listen port 2224
Git LFS: (0 of 68335 files, 200 skipped) 0 B / 15.66 GB, 70.54 MB skipped                                                                                                    
Git LFS: (0 of 68235 files, 300 skipped) 0 B / 15.64 GB, 98.60 MB skipped                                                                                                    
Git LFS: (0 of 0 files, 4848 skipped) 0 B / 0 B, 1.38 GB skipped                                                                                                             packet_write_wait: Connection to 10.20.90.232 port 7999: Broken pipe


Git LFS: (0 of 0 files, 97 skipped) 0 B / 0 B, 7.20 MB skipped                                                                                                               Error scanning for Git LFS files

Errors logged to /Users/andy/Projects/natera/eng/lims/lfs/objects/logs/20161006T161227.640338372.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'ssh://git@stash.myorg.com:7999/eng/prodlims.git'
```

And `/Users/andy/Projects/myorg/eng/lims/lfs/objects/logs/20161006T161227.640338372.log` contains:

```
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7.1)
git version 2.10.0

$ git-lfs pre-push origin ssh://git@bitbucket.myorg.com:7999/eng/prodlims.git
Error scanning for Git LFS files

fork/exec /usr/local/Cellar/git/2.10.0/libexec/git-core/git: resource temporarily unavailable

ENV:
LocalWorkingDir=
LocalGitDir=/Users/andy/Projects/myorg/eng/lims
LocalGitStorageDir=/Users/andy/Projects/myorg/eng/lims
LocalMediaDir=/Users/andy/Projects/myorg/eng/lims/lfs/objects
LocalReferenceDir=
TempDir=/Users/andy/Projects/myorg/eng/lims/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.
__GIT_PROMPT_DIR=/Users/andy/.zsh-git-prompt
GIT_IMPLICIT_WORK_TREE=0
GIT_PREFIX=
GIT_PROMPT_EXECUTABLE=python
```

Near the end of the command running (which takes about an hour to error out) I noticed around 600+ git processes running.

I am thinking that it might be hitting some ulimit. I tried increasing my `file decriptor` and `process` limits (I can't seem to go higher than 2048 processes):

```
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2048
-n: file descriptors                262144
```

But it didn't seem to help. Is it possible I am still running into 2048 process limit? If so, what can I do to get this repository pushed?

```
$ git --version
git version 2.10.0
$ git lfs version
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7.1)              
$ sw_vers -productVersion 
10.12
```

**Comment by technoweenie** [comment]
Hi @andyshinn, here's where that exception is coming from:

* [`git lfs pre-push` command](https://github.com/github/git-lfs/blob/f2ce643b9cde397f5814ebd37f033f80c004d044/commands/command_pre_push.go#L74-L77)
* [`lfs.ScanRefs()`](https://github.com/github/git-lfs/blob/f2ce643b9cde397f5814ebd37f033f80c004d044/lfs/scanner.go#L139-L152)

This code is scanning the git commits that you are about to push for any LFS objects. Any found objects will be uploaded to the Git LFS server in Git's `pre-push` hook, before the actual Git push happens. Clearly your repository's large tree is triggering some resource limits. Here are some questions to help us recreate the issue on our end:

* How many branches or tags does your repository have?
* What is `git config push.default` set to? By default, this should only push your current branch, but could be configured to push all of your branches.

If you could send us the output of `GIT_TRACE=1 git push`, that would be helpful. If you're attempting to push lots of branches, try specifying the branch like `GIT_TRACE=1 git push origin master`.

**Comment by technoweenie** [comment]
Another question: How deeply nested are files in your repository? Having the output of `git ls-tree BRANCHNAME -r` would be really helpful, but I understand you may not want to share this info. Git's performance can vary if your repository is full of 70,000 files in the root vs deeply nested files like `path/to/some/file/foo.pdf`.

**Comment by andyshinn** [comment]
```
$ git branch | wc -l
     776
$ git tag | wc -l   
     165
```

Most of these files in the `ls-tree` are nested about 6 or 7 directories deep. But the output contains too much sensitive information to post here.

And yes, I am pushing all branches since I am performing this on a bare repo (trying to convert all objects to git LFS references using BFG). I'll try limiting it to a handful of branches at a time to see if that helps. I wonder if it is pushing these branches in parallel and thus hitting a local resource limit? The process count seems to correlate closely to my branch count.

**Comment by technoweenie** [comment]
@andyshinn Hmm, Git should be calling `.git/hooks/pre-push` once, passing each ref as a single line to STDIN. The [git-lfs `pre-push` hook](https://github.com/github/git-lfs/blob/f2ce643b9cde397f5814ebd37f033f80c004d044/commands/command_pre_push.go#L74-L79) should be processing each ref synchronously. Can you try pushing just a single ref to see if that works around it?

Thanks for the info, this should be enough to replicate on our end.

**Comment by andyshinn** [comment]
I'll post the trace once it finishes as well. I don't see any sensitive information in the trace. But it takes an hour+ for it to fail. At the moment, I count over 800 git processes:

```
$ ps axw | grep git | wc -l
     811
```

And the trace is just repeating the following:

```
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 0
trace git-lfs: run_command: git rev-list --objects --stdin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
```

**Comment by technoweenie** [comment]
I created a test repo with 80k LFS objects and 20k txt files, and I'm unable to replicate the multiple process thing. Git LFS processes each ref sequentially, spinning up 7 git processes:

* `git push`
* `git-remote-https` (called by `git push`)
* `git pre-push` (called by `git push`)
* `git-lfs` (called by `git-pre push`)
* `git rev-list` (called by `git lfs`)
* `git cat-file --batch-check` (called by `git lfs`)
* `git cat-file --batch-` (called by `git lfs`)

I also setup a smaller repo with 100 refs, each adding 200 unique files. I only see 4 processes in the mac Activity Monitor, but that's because scanning the git history is fast enough that the bottom 3 `git` processes don't even show up.

@ttaylorr and I did identify some spots that would improve memory usage, and begin uploading objects earlier on repositories with deep histories. This is something that will be worked on for Git LFS v1.5.0.

**Comment by andyshinn** [comment]
The trace ends up being pretty large. But uploaded it to https://transfer.sh/dVEsU/git-lfs-trace in case it is helpful. I will try pruning some old refs and see if that helps out. I see an opportunity to clean up some old cruft when this repository was migrated from SVN many years ago (!!!!).

**Comment by technoweenie** [comment]
You should be able to push individual refs by explicitly specifying them: `git push origin foo`. I realize this isn't ideal, but I'm trying to find a workaround for you while we work towards improving this for LFS v1.5.0.

**Comment by andyshinn** [comment]
That doesn't work because I am working with a bare repository (doesn't let me push individual refs). But I'll try it on a regular clone and see how it goes.

**Comment by andyshinn** [comment]
I'm going to close this issue. Unfortunately, we had to make a decision not to use git LFS for this particular project. Even for individual branches it seemed to slow down the general workflow due to the large amount of data.

It also takes me 4+ hours to migrate the repository large files to git LFS objects for testing so it is really difficult to test and debug this issue.

Feel free to re-open if you would like to continue tracking this without me. I'll research git LFS again in the future after 1.5.0+.

**Comment by ttaylorr** [comment]
@andyshinn thanks for the honesty. I'm working on several improvements that will make LFS both quicker, and more resilient. I'd love to hear your thoughts on the changes once 1.5.0 is shipped.

**Comment by jjgod** [comment]
We just hit this with a repository with many (> 500) tags. git-lfs forked over 1000 git processes and hit the hard limit of 709 max user process limit on regular macOS. I need to turn on [Server performance mode](https://support.apple.com/en-us/HT202528) of macOS to workaround this. Please still consider fixing this problem or try to limit the maximum forking process to under 500 (or a reasonable number).

**Comment by technoweenie** [comment]
Sure, just need help replicating this. I created a large repo, and had no problems with it spawning that many processes (https://github.com/github/git-lfs/issues/1562#issuecomment-252746180).

**Comment by jjgod** [comment]
Our repository is unfortunately proprietary but I will try to grab some traces.

My current command is `git push --tags origin master`.

**Comment by technoweenie** [comment]
> The problem happens when it's done uploading the majority of lfs files and start scanning tags to upload the remaining ones, it seems, that's when the number of git processes forked skyrocketed.

That `git push` command feeds a list of refs to `.git/hooks/pre-push` to upload, in the form of:

```
# <local ref> <local sha1> <remote ref> <remote sha1>
refs/tags/v1.0 abcdef refs/tags/v1.0 0000000000...
refs/tags/v1.1 abcdef refs/tags/v1.0 0000000000...
refs/tags/v1.2 abcdef refs/tags/v1.0 0000000000...
```

Git LFS processes that input in the [pre-push command](https://github.com/github/git-lfs/blob/7d54b1c0e0e1218aae2ca39e3da9d05b06749007/commands/command_pre_push.go#L62-L80). It should be processing each line sequentially:

* `lfs.ScanRefs()` scans the git history for LFS objects
* `upload()` uploads the objects in parallel

The `upload()` func should be blocking, preventing . That's the behavior that I saw in my own tests. It sounds like it's either trying to run it in parallel, or the commands from `lfs.ScanRefs()` are not shutting down properly.

You should be able to work around this by pushing each tag individually. It should be easy with some basic shell scripting. That should let you get back to work.

```bash
$ git push origin master
$ git push origin v1.0
$ git push origin v1.1
...
```

That said, I'd really like to be able to pin point this bug, too. Would you be willing to run a patched `git-lfs` binary with temporary verbose logging for when `git` commands are spawning? I'll just need your `git lfs version` output to make sure I patch the correct version. I can provide a binary for you, as well as a git branch so you can compile yourself if you like.

**Comment by jjgod** [comment]
The fix I made appears to work. With the same `ps ax | grep git | wc -l` never exceed 12.

**Comment by technoweenie** [comment]
Closing this since #1656 was merged. Thanks @jjgod for reporting and posting a suggested fix!
