### ISSUE TITLE
LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/134753364

### ISSUE THREAD

**Issue by hazzaldo** [git-lfs/git-lfs#1581]
Dear Git LFS support,

When trying to push a large file using LFS tracking I got the error below. I looked at an older post:
https://github.com/github/git-lfs/issues/477  but wasn't sure if my issue is the same to that post, and to be honest I didn't understand what needs to be done.

```
$ git push -u origin master
Git LFS: (0 of 1 files) 113.05 MB / 580.15 MB                                                                                        
LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/134753364/c7/73/c773a6287dec8c0feeb557e8af478b1e7cb2e30f105812718a282f7aaa24d4c6?actor_id=16270718
error: failed to push some refs to 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'
```

Sorry in advance if my query is a duplicate. If someone could guide me on what do to resolve this would be really appreciated. 

Many thanks in advance

**Comment by ttaylorr** [comment]
Hi @hazzaldo, thanks for opening this. The `Client error` means that you're getting a 400 response back from the server. Without much more insight into the contents of the response, I'm not sure what's going on.

Could you retry the command with `GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push -u origin master` and post the results?

**Comment by hazzaldo** [comment]
Hi ttaylor,

Thanks for the super quick response. A lot of text was displayed after running this command. I'll post it the whole thing. Apologies if I'm only meant to post a particular part of it:

```
GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push -u origin master
17:24:57.735746 git.c:350               trace: built-in: git 'push' '-u' 'origin' 'master'
17:24:57.756112 run-command.c:336       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.253.113...
* Connected to github.com (192.30.253.113) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.8.4 (Apple Git-73)
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 72
< WWW-Authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: 56BF9B24:0E02:7D638FD:580106E7
< X-Frame-Options: DENY
< 
* Connection #0 to host github.com left intact
17:25:12.360694 run-command.c:336       trace: run_command: 'git credential-osxkeychain get'
17:25:12.362603 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain get' 'git credential-osxkeychain get'
17:25:12.387230 git.c:563               trace: exec: 'git-credential-osxkeychain' 'get'
17:25:12.388521 run-command.c:336       trace: run_command: 'git-credential-osxkeychain' 'get'
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0x7ff849d0bfa0
* Hostname github.com was found in DNS cache
*   Trying 192.30.253.113...
* Connected to github.com (192.30.253.113) port 443 (#1)
* SSL re-using session ID
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.8.4 (Apple Git-73)
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 72
< WWW-Authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: 56BF9B24:0E04:8BC37C2:580106E8
< X-Frame-Options: DENY
< 
* Ignoring the response-body
* Connection #1 to host github.com left intact
* Issue another request to this URL: 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/refs?service=git-receive-pack'
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0x7ff849d0bfa0
* Re-using existing connection! (#1) with host github.com
* Connected to github.com (192.30.253.113) port 443 (#1)
* Server auth using Basic with user 'hazzaldo@hotmail.com'
> GET /hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic aGF6emFsZG9AaG90bWFpbC5jb206Q2gzbHNlYWZj
User-Agent: git/2.8.4 (Apple Git-73)
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: 56BF9B24:0E04:8BC37C7:580106E9
< X-Frame-Options: DENY
< 
* Connection #1 to host github.com left intact
17:25:13.640573 run-command.c:336       trace: run_command: 'git credential-osxkeychain store'
17:25:13.641463 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain store' 'git credential-osxkeychain store'
17:25:13.646124 git.c:563               trace: exec: 'git-credential-osxkeychain' 'store'
17:25:13.646696 run-command.c:336       trace: run_command: 'git-credential-osxkeychain' 'store'
17:25:13.696787 run-command.c:336       trace: run_command: 'git credential-osxkeychain store'
17:25:13.697584 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain store' 'git credential-osxkeychain store'
17:25:13.702836 git.c:563               trace: exec: 'git-credential-osxkeychain' 'store'
17:25:13.703466 run-command.c:336       trace: run_command: 'git-credential-osxkeychain' 'store'
17:25:13.745636 run-command.c:336       trace: run_command: '.git/hooks/pre-push' 'origin' 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'
17:25:13.753508 git.c:563               trace: exec: 'git-lfs' 'pre-push' 'origin' 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'
17:25:13.754202 run-command.c:336       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: git rev-list --objects 67a4107877fb30bb514907e40b7db635f767c91c --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 1
trace git-lfs: api: batch 1 files
trace git-lfs: Filled credentials for https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git
trace git-lfs: HTTP: POST https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/lfs/objects/batch
> POST /hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 126
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/1.4.2 (GitHub; darwin amd64; go 1.7.1; git 6557f9f)
> 
trace git-lfs: tq: enqueue retry #1 for "c773a6287dec8c0feeb557e8af478b1e7cb2e30f105812718a282f7aaa24d4c6" (size: 608331320)
trace git-lfs: tq: flushing batch in response to retry #1 for "c773a6287dec8c0feeb557e8af478b1e7cb2e30f105812718a282f7aaa24d4c6"
%!(EXTRA int64=608331320)trace git-lfs: tq: sending batch of size 1
trace git-lfs: api: batch 1 files
trace git-lfs: Filled credentials for https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git
trace git-lfs: HTTP: POST https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/lfs/objects/batch
> POST /hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 126
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/1.4.2 (GitHub; darwin amd64; go 1.7.1; git 6557f9f)
> 
trace git-lfs: tq: refusing to retry "c773a6287dec8c0feeb557e8af478b1e7cb2e30f105812718a282f7aaa24d4c6", too many retries (1)
Git LFS: (0 of 1 files) 0 B / 580.15 MB                                                                                              
http: Post https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/lfs/objects/batch: dial tcp: i/o timeout
error: failed to push some refs to 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'
```

**Comment by hazzaldo** [comment]
Hi ttaylorr,

Just wondering did you manage to find what the issue is?

Thanks & regards

**Comment by technoweenie** [comment]
> http: Post https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git/info/lfs/objects/batch: dial tcp: i/o timeout

You had a timeout talking to the API. Try [bumping the dial timeout](https://github.com/github/git-lfs/blob/018ae222d866b0110ff83949f5eecdf17775d40e/docs/man/git-lfs-config.5.ronn#L31-L35).

```bash
$ git config --global lfs.dialtimeout 60
```

However, 30s to dial a tcp connection is a long time. The network connection between your computer and GitHub may have been experiencing some temporary issues at the time. You can also try [bumping the retries up](https://github.com/github/git-lfs/blob/018ae222d866b0110ff83949f5eecdf17775d40e/docs/man/git-lfs-config.5.ronn#L104-L109):

```bash
$ git config --global lfs.transfer.maxretries 5
```

Note: The retry system in general is going to get a complete overhaul in v1.5.0, so this should improve dramatically for intermittent network issues soon.

**Comment by hazzaldo** [comment]
Hi technoweenie,

Thanks for your response. I followed your instruction, i.e. bumping the dial timeout to 60 and tries 5. This is the result:

```
(master) Collect_All_Cubes_(iOS_Build) $ git push -u origin master
Git LFS: (0 of 1 files) 891.80 MB / 580.15 MB                                  
LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/134753364/c7/73/c773a6287dec8c0feeb557e8af478b1e7cb2e30f105812718a282f7aaa24d4c6?actor_id=16270718
error: failed to push some refs to 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'

```

I don't understand what that message means. Why does it show: 891.80 MB / 580.15 MB 
Is it worth me giving it another try, but have it connected to an ethernet cable directly to the router this time. Maybe it needs a faster consistent internet connection?

**Comment by ttaylorr** [comment]
Hey @hazzaldo, hoping in here since I recently worked on the transferqueue. The reason that you're seeing more bytes transferred than the size of the actual file is because of a long-standing bug in LFS that prevents us from accurately deducting progress in the case of a transfer restart.

The 891.80 MB that were transferred represents the _cumulative_ amount of data your LFS client sent to s3 before hitting the 5 retries allotted to it. In other words, even when LFS fails an object after getting part of the way through it, it still leaves the amount of data transferred in the progress meter.

This is on my internal roadmap for 1.5.0, and will be fixed then 👍

**Comment by hazzaldo** [comment]
Many thanks for this info ttaylor. Would it be possible to notify me when the newer version will be ready to download or simply have the existing LFS installed on my machine updated with the new version?

So basically in the meantime, would you advise I use other means of sharing data on cloud for large files, such as Google drive, until this issue is resolved in the newer version? 

Thanks & kind regards,

**Comment by ttaylorr** [comment]
A tag will be pushed when the next major version is released, which you'll be able to see on your GitHub timeline.

In the meantime, I'd recommend bumping the settings described in https://github.com/github/git-lfs/issues/1581#issuecomment-254222380 to higher values.

**Comment by hazzaldo** [comment]
Hi ttaylor,

thanks for the update. I did bump the setting as per @technoweenie previous comment, but as you saw from my response to his comment I was still getting an error. It may be worth mentioning that my Wifi connection isn't great and consistent. I now connected my laptop directly to my router via ethernet cable, so am getting a better network connection. Would you say it's worth giving it another try with: "git push -u origin master" ?

**Comment by ttaylorr** [comment]
Definitely!

**Comment by michaelklachko** [comment]
I'm having this problem right now, have you resolved it?

**Comment by michaelklachko** [comment]
If no solution exists, how can I disable LFS, so I can push other changes to Github? 
Right now 'git push origin remote' tries to upload the large file even after I did 'git lfs untrack filename', so I'm stuck.

**Comment by michaelklachko** [comment]
I did increase time-out and retries per comment above, but still see the following error:
root@TESLA:~/NN# git lfs push origin master
Git LFS: (0 of 1 files) 518.69 KB / 209.88 MB                                                               Git LFS: (0 of 1 files) 1.52 MB / 209.88 MB
LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/137523650/3a/38/3a381be0eb843c2f46632e434b675a7f2c9fc87293a85ab2f0ae32833ff7ee56?actor_id=981619
root@TESLA:~/NN#
root@TESLA:~/NN# git --version
git version 1.9.1
root@TESLA:~/NN# git lfs version
git-lfs/1.5.2 (GitHub; linux amd64; go 1.7.3; git 547a06a)
root@TESLA:~/NN# git lfs ls-files
3a381be0eb * mnist_noval.pkl
root@TESLA:~/NN#

**Comment by technoweenie** [comment]
If you want to revert an LFS file in your most recent commit that has not been pushed to github, this help guide will show you how: [Removing files from a repository's history](https://help.github.com/articles/removing-files-from-a-repository-s-history/).

We are actively working on improving the transfer queue in a future version. Unfortunately, there's not a lot we can do with bad network connections other than more retries.

**Comment by michaelklachko** [comment]
I ended up deleting my local repo, and then cloning it from Github. Had I known this would waste so much of my time I'd never touch this utility.

It's silly to suggest network connection issues, because this is clearly a bug in your code. I'm on a rock solid wired network, and I'm moving large files all the time. In fact, right after I experienced this problem yesterday, I moved my file to Google Drive with no issues at all - took about 3 seconds to upload 200MB.

**Comment by cnukolkuri** [comment]
Hi Guys, I'm getting same error.please advice any work around/throw some light about solution.

$ git lfs push origin master
Git LFS: (0 of 2 files) 0 B / 6.45 MB
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/150639243/55/d5/55d553fff02b732c0b84409bbf072f4f8e4cf7622fab7f1c61eb3bb09f6dd92c?actor_id=29469550: read tcp 192.168.1.2:52127->54.231.41.75:443: i/o timeout
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/150639243/77/51/7751229d01578e4a9e323a25478d0c47b900b3f4afd9cc2bf517e0d4e09e8229?actor_id=29469550: read tcp 192.168.1.2:52128->54.231.72.227:443: i/o timeout

**Comment by cnukolkuri** [comment]
$ git lfs push origin master
Git LFS: (0 of 2 files) 0 B / 6.45 MB
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/150639243/55/d5/55d553fff02b732c0b84409bbf072f4f8e4cf7622fab7f1c61eb3bb09f6dd92c?actor_id=29469550: read tcp 192.168.1.2:52127->54.231.41.75:443: i/o timeout
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/150639243/77/51/7751229d01578e4a9e323a25478d0c47b900b3f4afd9cc2bf517e0d4e09e8229?actor_id=29469550: read tcp 192.168.1.2:52128->54.231.72.227:443: i/o timeout

**Comment by cnukolkuri** [comment]
Hi Team, I'm facing an issue with below error. please throw some light about solution.

$ git lfs push origin master
Git LFS: (0 of 2 files) 0 B / 6.45 MB
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/150639243/55/d5/55d553fff02b732c0b84409bbf072f4f8e4cf7622fab7f1c61eb3bb09f6dd92c?actor_id=29469550: read tcp 192.168.1.2:52127->54.231.41.75:443: i/o timeout
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/150639243/77/51/7751229d01578e4a9e323a25478d0c47b900b3f4afd9cc2bf517e0d4e09e8229?actor_id=29469550: read tcp 192.168.1.2:52128->54.231.72.227:443: i/o timeout

**Comment by simplymichael** [comment]
Okay, so this is 2019, and I'm still having this issue. Infact, I've been battling with it for two straight days now, and multiple retries. The Large file I'm trying to upload is just 233Mb. I sit here looking at the meter, and it reads that it has uploaded 500Mb and then it fails with the reported or similar error. The saddest part is since the transfer queue meter is inconsistent, you are unable to tell when or if your push will ever complete. 
I tried without git-lfs, but github will not accept files above 100Mb.  I could upload only the non-large files, but the the large file (.zip file) is an essential and indispensable part of the repo. Anyone has any idea how I can handle this?

**Comment by bk2204** [comment]
Hey, I've opened #3601 to capture the transfer queue issue so we don't forget about it. If you're seeing other problems that aren't network related (or you aren't sure about), could you open a new issue, please?

**Comment by highskillzz** [comment]
I too am having the same issue

git push origin master
Uploading LFS objects:  99% (260/263), 1.6 GB | 201 KB/s, done
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/227750008/7e/ee/7eee8bf0d0324a5b727ec920616ee2e36c599bd1c5904becb46921c9b5d4477c?actor_id=20688709: read tcp 172.16.152.154:56061->52.216.176.51:443: i/o timeout
LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/227750008/e3/ea/e3ead14d46c78e81ae6ce1ae3d8be457d68cb2a7408a3e5ced9b5dd27ebabeaa?actor_id=20688709
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/227750008/ca/04/ca0444dc5c92ff1cfa95f3064e95a2f1ce3368ff4b11057675323454574df7cb?actor_id=20688709: read tcp 172.16.152.154:56276->52.216.114.3:443: i/o timeout
error: failed to push some refs to 'https://github.com/highskillzz/Hack-Your-Reality.git'

**Comment by WWaynee** [comment]
It's 2020 now and I'm stuck with this shitting problem and don't know how to solve......a waste of time

**Comment by bk2204** [comment]
Hey,

If you're seeing an “i/o timeout” message, that's a network problem between you and Amazon S3, which is where GitHub stores the LFS objects.  There isn't anything that we can address in the client that fixes it because we don't control your network connection.

You can try raising `lfs.activitytimeout` to a larger number (than 30) and see if it helps.  Otherwise, talk to your network administrator or ISP.

If you're seeing a different problem, please open a new issue as directed instead of commenting on this one.

**Comment by guoziqin** [comment]
It's 2021 and it's not settled yet？

**Comment by praveenmak** [comment]
We are experiencing i/o timeouts. Increased the timeouts but no help. 
Disconnected from VPN as well.

**Comment by WWaynee** [comment]
收到了惹。

**Comment by MrKsiJ** [comment]
I have the same problem two days ago I had a project that I had been working on for a year, I had to urgently restore it, which thank God was successfully completed and I urgently need to make a backup of my project, but bitch, because of this error, I can't do it.

**Comment by bk2204** [comment]
Okay, folks, since we continue to get comments on this issue instead of folks opening a new issue, I'm going to lock this.  There are a lot of different places where you could get similar errors, and most of them are network issues that are outside of the client's control.  If you're still seeing a problem, please open a new issue or discussion and we'll try to help.
