### ISSUE TITLE
Deb package for Ubuntu 16.10 (Yakkety Yak) and 17.04 (Zesty Zapus)

### ISSUE THREAD

**Issue by edwinksl** [git-lfs/git-lfs#1587]
From https://packagecloud.io/app/github/git-lfs/search?filter=all&q=&dist=ubuntu, there doesn't seem to be a `.deb` package for Ubuntu 16.10 (Yakkety Yak), which has been officially released on October 13. I am wondering when a `.deb` package for Ubuntu 16.10 would be built.

**Comment by technoweenie** [comment]
Adding a new ubuntu version takes 2 steps:

1. Adding a docker file for the appropriate debian version to https://github.com/git-lfs/build-dockers.
2. Mapping it to the debian and relevant versions in the [packagecloud upload script](https://github.com/github/git-lfs/blob/018ae222d866b0110ff83949f5eecdf17775d40e/script/packagecloud.rb#L43-L54).

I ran into issues with debian 9: https://github.com/github/git-lfs/pull/1472. If those can be solved, we can start pushing releases to it.

**Comment by ttaylorr** [comment]
I was fixing some broken parts of our Docker build process, so I'll take a look at building on Debian 9 now.

**Comment by ph03** [comment]
Any news on this?

**Comment by ttaylorr** [comment]
Sorry for the 📻  silence. I was unable to fix the issues building on Debian 9, and had asked @andyneff to take a look.

**Comment by andyneff** [comment]
I was unable to fix the Debian 9 issue on first glance and thought I had asked @ssgelm to take a look at it. I will take another shot at Debian 9 when I get the chance.

**Comment by ssgelm** [comment]
I don't remember being asked but I'm happy to take a look. 😄

**Comment by jkarkkainen** [comment]
I might be confused here, but is this the reason I can't install git-lfs on Ubuntu 16.10 using either the quick install script or adding the repos and installing through apt? If not, I'll make a new bug report about it. In the meanwhile, how do I go about installing git-lfs on Ubuntu 16.10?

**Comment by technoweenie** [comment]
You can download the linux binary from https://github.com/git-lfs/git-lfs/releases/tag/v1.5.5. If you have Go, you can install it yourself with `go get github.com/git-lfs/git-lfs`.

**Comment by grantstephens** [comment]
So I just installed it by downloading the latest .deb file from the releases page and installed it- no problems. Was pulling my hair out wondering why the package-cloud wasn't working.

**Comment by technoweenie** [comment]
I agree. We never got debian 9 builds working: https://github.com/git-lfs/git-lfs/pull/1472. Can anyone help us figure out those dh_golang build issues?

**Comment by ssgelm** [comment]
@technoweenie sorry - I haven't forgotten about this.  I'll try and get it fixed as soon as I can.

**Comment by ekse** [comment]
As a temporary workaround, edit /etc/apt/sources.list.d/github_git-lfs.list and change 'yaketty' for 'xenial', it seems to be working fine.

**Comment by edwinksl** [comment]
Same problem of no `.deb` package for Ubuntu 17.04, which was released a couple of days ago.

**Comment by x4121** [comment]
Maybe, as a workaround until things are fixed, you could add a OS version check into the install script. It's not really good usability to have users informed of "The repository is setup! You can now install packages." (without printing errors) just to have them look at "E: Unable to locate package git-lfs" when they try to install it.

**Comment by brynn-mahsman** [comment]
Just installed Ubuntu 17.04 and spent quite a while trying to get this to work. The install instructions worked up until `sudo apt install git-lfs`, so I thought I did something wrong. Perhaps put a note in your install documents saying if all else fails, grab the .deb from the GitHub releases tab?

**Comment by x4121** [comment]
@brynn-mahsman you can fix this if you edit `/etc/apt/sources.list.d/github_git-lfs.list` and replace `zesty` with `xenial`.

The packages don't seem to be built for 17.04 (zesty) yet, but the package for 16.04 (xenial) should work fine.
But yes, this should be either documented or printed as an error during installation (as I noted above :confused: )

**Comment by ssgelm** [comment]
I just submitted PR #2203 which should enable building on newer debian and ubuntu versions.

**Comment by ttaylorr** [comment]
This is resolved. You can install LFS on Debian 9-based distributions.

**Comment by x4121** [comment]
@ttaylorr maybe you should still think about some kind of release-version-check or at least stop piping the error messages to /dev/null, otherwise you're just waiting for the same problem to happen in the future.

**Comment by mateodelnorte** [comment]
Am I seeing this same issue? 
```
docker run -it --rm node:10-jessie sh
# apt update -y
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [679 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2420 B]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [23.0 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 12s (793 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
# apt install git-lfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package git-lfs
```

**Comment by bk2204** [comment]
I think what you're seeing here is that Debian jessie doesn't ship the `git-lfs` package, which I've confirmed by looking at [packages.debian.org](https://packages.debian.org/search?keywords=git-lfs).  For stretch, there are backports, but for jessie, there aren't any in the Debian archive.

We do provide packages for jessie [at PackageCloud](https://packagecloud.io/github/git-lfs).

**Comment by ssgelm** [comment]
Yeah, sorry, I really hoped to add git-lfs to jessie-backports-sloppy but now that it's LTS that's no longer allowed.
