### ISSUE TITLE
Investigate automated Windows building/signing

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#1592]

**Comment by ttaylorr** [comment]
Acking out of our internal first-responder rotation.

**Comment by sschuberth** [comment]
As part of implementing this, we should release directly from AppVeyor CI instead of building releases on some "blessed" developer's local machine.

**Comment by ttaylorr** [comment]
> we should release directly from AppVeyor CI instead of building releases on some "blessed" developer's local machine.

I agree. There are a couple of steps involved in making this happen:

- Include the private keys used for signing LFS releases on AppVeyor machines
- Build AppVeyor binaries as normal
- Ensure AppVeyor signs the binaries with our certificate (using the private keys)
- Package the binaries up in our standard format (including the README, CHANGELOG, and relevant binaries)
- Either...
  - Have AppVeyor upload our releases somewhere, or...
  - Update our build scripts to ask AppVeyor for Windows builds instead of having to build them ourselves

**Comment by technoweenie** [comment]
> Include the private keys used for signing LFS releases on AppVeyor machines

Is this possible to do securely? I don't want to leak our LFS cert if possible. Another option is to build an AV, and have a local script (or internal service) that downloads, signs, and uploads to the Releases page.

**Comment by sschuberth** [comment]
> Is this possible to do securely?

Yes I believe so, via https://ci.appveyor.com/tools/encrypt. Or do you also not want to "leak" the encrypted cert to AppVeyor?

**Comment by technoweenie** [comment]
Oh interesting, that could work.

**Comment by bk2204** [comment]
I believe we're now signing Windows builds automatically, so I'm closing this.
