### ISSUE TITLE
Add "Check max file limit of your webserver" to known issues

### ISSUE THREAD

**Issue by filcuc** [git-lfs/git-lfs#1612]
I struggled with git lfs on my bitbucket server.
From git and git-lfs i received this error when uploading a big file (~ >= 50mb)

```
LFS: Repository or object not found: http://my-server/rest/git-lfs/storage/LIBS/test/43275934fc9f6081e15de811b6021a21da06c3cd03470b87438bfb8e5bb164ed
```

This was not a git-lfs fault nor of bitbucket. This was due a limit in my reverse proxy server (IIS) where the maximum request size was set to 30mb.
I think that it could be helpful to put this in a FAQ

**Comment by ttaylorr** [comment]
Hi @filcuc, thanks for opening this. We're working on a user-guide wiki, and I'll make sure that this gets on there.
