### ISSUE TITLE
git-lfs Error: Failed to call git rev-parse --git-dir --show-toplevel: ""

### ISSUE THREAD

**Issue by vaceknt** [git-lfs/git-lfs#1613]
I have:
git version 2.8.1.windows.1
git-lfs/1.2.0 

When I try to init git-lfs I get an error:
Error: Failed to call git rev-parse --git-dir --show-toplevel: ""
WARNING: 'git lfs init' is deprecated. Use 'git lfs install' now.
The filter.lfs.clean attribute should be "git-lfs clean -- %f" but is "Error running git [config --global filter.lfs.clean]"
Run `git lfs install --force` to reset git config.

**Comment by ttaylorr** [comment]
Hi @vaceknt, thanks for opening this. I can't be sure, but It looks like you're running the command `git lfs init`, which is deprecated. To install Git LFS, try `git lfs install` instead.

You're also running an outdated release of LFS. You can grab the latest Windows Installer from our [releases page](https://github.com/github/git-lfs/releases) and use that instead.

Let me know if you have any other questions!

**Comment by vaceknt** [comment]
Thanks you, @ttaylorr 

I've updated git and git-lfs and I still have a problem.
git version 2.10.1.windows.1
git-lfs/1.4.4 (GitHub; windows amd64; go 1.7.3; git cbf91a9)

**$ git-lfs install**
```
Error: Failed to call git rev-parse --git-dir --show-toplevel: ""
Error getting git version: fork/exec git.exe: %1 is not a valid Win32 application.
```

**$ git-lfs init**
```
Error: Failed to call git rev-parse --git-dir --show-toplevel: ""
WARNING: 'git lfs init' is deprecated. Use 'git lfs install' now.
Error getting git version: fork/exec git.exe: %1 is not a valid Win32 application.
```

**Comment by ttaylorr** [comment]
Thanks for the speedy reply, and for updating! The "is not a valid Win32 application" makes me think that this is a Windows issue, which I don't have a ton of experience debugging. I'm going to page @larsxschneider, since I know he has some expertise debugging LFS on Windows.

**Comment by vaceknt** [comment]
This issue has been fixed.
git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git 13fda8da)

**Comment by technoweenie** [comment]
Thanks for confirming the fix :)

**Comment by EnziinSystem** [comment]
Sorry, the problem not fix.

I see this error on Ubuntu:

`git lfs install
Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal: not a git repository (or any of the parent directories): .git\n"
Git LFS initialized.
`

**Comment by davidawad** [comment]
I am also getting this issue, but I have no idea how to provide helpful information about what's causing it.

**Comment by larsxschneider** [comment]
@dakotahawkins where is your repo located? Can you provide the path (maybe anonymized)? Is it located on some special mount? Are you using hard/soft links?

**Comment by dakotahawkins** [comment]
@larsxschneider Wrong issue or wrong name?

**Comment by larsxschneider** [comment]
Oops! Sorry @dakotahawkins ! I wanted to ping @davidawad 😄

**Comment by ttaylorr** [comment]
Hi, I think that the issue is described well in https://github.com/git-lfs/git-lfs/issues/3013#issuecomment-390802139. I am proposing that we move discussion there, since this issue is quite old, and the original topic has diverged from the current discussion.
