### ISSUE TITLE
git lfs push does not work as a subprocess

### ISSUE THREAD

**Issue by theNewFlesh** [git-lfs/git-lfs#1615]
I've tracked down the issue and it is caused by `git lfs push` interactively asking for AWS credentials, even though just hitting enter on all of them works.

Is there someway to suppress this or better yet pass in username/password pairs into `git lfs push`, such that it can be run via subprocess.Popen?

**Comment by technoweenie** [comment]
The AWS credentials? What git and/or lfs service are you using?

**Comment by theNewFlesh** [comment]
I am using git-lfs-s3 as my lfs server.  It connects to S3 and takes in a bunch of environment variables for configuration.  Those variables seem to be clobbered in the process of calling commands programatically, even when I explicitely declare them.  However, passing in `https://:@bucket.amazonaws.com` and `https://user:password@localhost:8080` (server) as URLs in .git-credentials and adding credential.helper to the config seems to do the trick.

**Comment by theNewFlesh** [comment]
If understand LFS architecture correctly, the client talks to the server, says 'I want to upload a bunch of objects', the server responds with 'Ok, here are bunch of links to keys inside an S3 bucket', the server then tries to send its data to said bucket.  At this point S3 complains if a username and password are not supplied, even if neither is required in the regular command line.  So, providing an empty username:password combo works (https://`:@`bucket.amazonaws.com)

**Comment by ttaylorr** [comment]
Hi @theNewFlesh is this still an issue? I am going to assume not, because this thread hasn't seen any activity in some time. If I have assumed incorrectly, please do not hesitate to let me know and I would be more than happy to take a look. Thanks!
