### ISSUE TITLE
LFS Roadmap: v1.5.0 -> v2.0

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1632]
You may have noticed references to new LFS version numbers flying around these
Issues and Milestones. Here's our current plan for the next few Git LFS
releases:

## v1.5.0

This is an exciting release for us, especially @larsxschneider. LFS's biggest
complaint is how slow it is. Unfortunately, a big part of that has to do with
Git's clean and smudge filter implementation, which was never designed for
something like LFS.

@larsxschneider dropped #1382 on us, which claimed to speed up git branch
changes up to *70x* with a new filter process feature in Git. After several
months of patches with the git core team, the filter process feature was
[accepted for Git v2.11](http://public-inbox.org/git/xmqqk2d2ein7.fsf@gitster.mtv.corp.google.com/).

Since then, @larsxschneider and @ttaylorr have been jamming on the Git LFS
implementation of this feature, and it is now nearly ready: #1617.

A couple other things are slated for Git LFS v1.5.0 too:

* Allow usage of proxies even when contacting localhost #1650
* Fast directory walk #1616

View progress in the [v1.5.0 milestone](https://github.com/github/git-lfs/milestone/2).

## v2.0

Since its release over a year ago, Git LFS has been carrying around a lot of
baggage. Git LFS v2.0 removes that baggage, and redesigns some of the core
systems.

* Scanner - The Scanner extracts LFS pointer objects from a range of Git commits.
Our goal is to make the scanner asynchronous so that transfers can begin
immediately when trying to push a large Git history. #1649
* Transfer Queue - The transfer queue will be reworked to support the new
Scanner, and handle network issues better. #1651
* Filter Process - We want to investigate parallel downloads during long
clone/pull operations. #1646 

The bulk of the baggage is the support for the Git LFS legacy API, which is 
removed in #1629. There are also a number legacy commands to remove too.

View progress in the [v2.0 milestone](https://github.com/github/git-lfs/milestone/3).

## File Locking

@sinbad is currently experimenting with File Locking. There's no set release
yet, but it is looking promising:

* Locking part 1: locking package #1625
* [Locking Proposal](https://github.com/github/git-lfs/blob/f493f82e7ae8dfda37c7a2b18d8ba77ba41907a2/docs/proposals/locking.md)

**Comment by ttaylorr** [comment]
Thanks for writing this up! 🎉 

I'm going to post more detailed issues with proposals and high-level overviews of the types of improvements I'd like to make in both the scanner, transfer queue, and the filter process.

@larsxschneider and I have already begun talking about adding a new capability to the protocol to allow the `git-filter-server` (LFS) to "promise" that it will convert a file and yield the path on disk where it will dump the result of that conversion. The `git-filter-client` (Git) can then wait until LFS sends back an "I'm done with everything you asked for", and then Git will move those files into the appropriate locations.

This will allow us to process many transfers concurrently, taking full advantage of the proposed new transfer queue design, and yielding even _greater_ speeds for the new filter protocol implementation. Perhaps more importantly, it will allow us to do normal Git operations (`git clone`, `git push`, `git pull`, and etc.) without needing to temporarily disable the smudge filter to parallelize the transfers. This means that, in-effect, we could get rid of the `git lfs <pull|clone|push>` commands entirely, which is something that I'd be very excited about.

**Comment by sinbad** [comment]
Nice 👍 I'm glad I at least managed to finish something for 1.5 at least :)

**Comment by technoweenie** [comment]
Updated above to reference the first issue for lfs 2.0: Proposal: git/gitscanner package for v2.0 #1649

**Comment by ttaylorr** [comment]
> Updated above to reference the first issue for lfs 2.0: Proposal: git/gitscanner package for v2.0 #1649

Did the same for the transfer queue work outlined in #1651.
