### ISSUE TITLE
Filter protocol follow-up issue

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#1640]
As we're getting close to merging support for the new Filter Protocol introduced in Git 2.11 into LFS, there are a few issues that I'd like to follow up on that are _not necessary to address before merging_.

| | Description | Refs | 
| - | ---------- | ---------- |
|~~◽️~~| ~~Reconcile `io.EOF`s that are legitimate, vs. `io.EOF`s that just mean we're done reading/writing a packet.~~ | https://github.com/github/git-lfs/pull/1617#discussion_r87365141 https://github.com/github/git-lfs/pull/1617#discussion_r87361200 |
|:white_check_mark:| Flush the `io.Writer` only when necessary, not after every packet write. | https://github.com/github/git-lfs/pull/1617#discussion_r87362237 |
|:construction:| ~~Use empty list to repeat `status=` packets.~~ |  |
| 🚫  | ~~Fix `requireStdin` on Windows.~~ | https://github.com/github/git-lfs/issues/1639 |
|🚫| Make error behavior consistent. | https://github.com/github/git-lfs/pull/1617#discussion_r87562930 https://github.com/github/git-lfs/pull/1617#discussion_r87356653 --> Flush part |

---

/cc @larsxschneider @technoweenie

**Comment by ttaylorr** [comment]
Going to take a look at this this week. (+acking out of our internal first-responder queue.)

**Comment by ttaylorr** [comment]
> Fix requireStdin on Windows.

Not sure if this is possible. Tried a number of different approaches locally, but I think there is always a `stdin` since the input can come from your terminal in interactive mode.

**Comment by ttaylorr** [comment]
Tracking: https://github.com/git-lfs/git-lfs/pull/1617#discussion_r88133403.

**Comment by ttaylorr** [comment]
Also tracking: [`git-lfs/git-lfs/fewer-status-bytes`][1]. The implementation appears correct to me based on conversations that I've had with @larsxschneider and inspection of the [relevant Git code][2], but causes a segfault in practice.

@larsxschneider would you be open to 🍐-ing on this tomorrow?

[1]: https://github.com/git-lfs/git-lfs/tree/fewer-status-bytes
[2]: https://github.com/git/git/blob/3ab228137f980ff72dbdf5064a877d07bec76df9/convert.c#L739-L749

**Comment by ttaylorr** [comment]
> Reconcile io.EOFs that are legitimate, vs. io.EOFs that just mean we're done reading/writing a packet.

I think what we have right now is legit. `io.Reader`s expect streams of continuous data, but the `pkt-line` format has delimiters (i.e., the `0000` flush pkt.). What might be better is to invalidate an `io.Reader` after it has read one packet, and just return a new one. I will dive further into this tomorrow.

**Comment by larsxschneider** [comment]
@ttaylorr I don't know if saving 7 bytes is worth the effort to introduce complicated locking structures: https://github.com/git-lfs/git-lfs/commit/e1982d43e1cfc432e29ceb16478ee0d9bc5bef71

My guess is that the difference is not measurable and actually I like the explicit status setting we use right now.

That being said - I am always happy to pair with you to learn your tricks 😄

**Comment by ttaylorr** [comment]
> Also tracking: git-lfs/git-lfs/fewer-status-bytes. The implementation appears correct to me based on conversations that I've had with @larsxschneider and inspection of the relevant Git code, but causes a segfault in practice.

Update: after 🍐-ing with @larsxschneider this morning, he mentioned to me the status is only persisted across a single file, which means _at most_ we can save the length of `status=success\n`, which I don't think is a worthwhile optimization, given the extra complexity.

If @technoweenie or someone else feels strongly, I have a branch prepared that does implement this functionality: [`git-lfs/git-lfs/fewer-status-bytes`][1].

[1]: https://github.com/git-lfs/git-lfs/tree/fewer-status-bytes

**Comment by ttaylorr** [comment]
> Make error behavior consistent.

Following up on this (also after some 🍐-ing with @larsxschneider): I've opened https://github.com/git-lfs/git-lfs/pull/1668 for discussion. 👍

**Comment by ttaylorr** [comment]
Went through and looked at the usage of `io.EOF`s within the `io.Reader` implementation for the pkt-line protocol: I'm happy with where things sit, and I don't think any further changes are warranted.

**Comment by ttaylorr** [comment]
Let's ship this thing.
