### ISSUE TITLE
"Changed" file sticks around (refuses to go away) after "git reset --hard"

### ISSUE THREAD

**Issue by snap9** [git-lfs/git-lfs#1644]
I do "git reset --hard" in my repo. But one of my jpg files refuses to go away. It sticks around under the "Changes not staged for commit:" section in "git status".

I don't even remember ever changing this file in the first place.

Any ideas?

**Comment by larsxschneider** [comment]
I ran into an issue that had a similar effect some time ago: https://github.com/github/git-lfs/issues/1544

Can you post the output of this command here?
```
git cat-file -p :your.jpg | od -c
```

**Comment by ttaylorr** [comment]
Looks like @larsxschneider is on top of this. Acking out of our internal first-responder queue.

**Comment by ttaylorr** [comment]
Hi, this is a common issue when using Git LFS where a file is committed in an invalid environment and thus no longer stored in Git LFS. (This can be verified by running `git lfs status` on an affected working copy and seeing a `LFS -> Git` or `LFS -> File` line).

You can fix this by running `git lfs migrate import --everything --fixup`.
