### ISSUE TITLE
Push from one place, pull to another. (question)

### ISSUE THREAD

**Issue by istvanszoke** [git-lfs/git-lfs#1647]
Hi!

I would like to use git-lfs in a push from one place, pull to another manner. 
This means that there are a set of entities that have permission to pull and to push. (ideal)
There are a set of entities (different from the previous) that have permission to pull but not to push. 
Lastly there would be a third set of entities that has permission to neither.

Is there a way to implement this with the current toolset of git lfs?

What I would think is that there is a way to exclude git-lfs-clone from simple git-clone. (same goes for checkout, pull, fetch etc.) And there is also a way to exclude pushing the binaries from git-push, without excluding it from git-commit manually. 
I know that there is a solution to the cloning with "git-lfs smudge --skip". But I couldn't find a solution to the pushing. 

Can you help? Thanks!

**Comment by ttaylorr** [comment]
> Is there a way to implement this with the current toolset of git lfs?

Sounds like it. To accomplish the granular permissions set-up you've described, I'd recommend hosting your master repository along with two forks, one for the read-only copy and one which will be treated as the frozen copy.

In terms of disabling LFS smudging during push and pull operations, this can be accomplished by unsetting the `filter.lfs.smudge` and `filter.lfs.clean` settings in your .gitconfig, by either running:

```bash
$ git -c "filter.lfs.smudge=" -c "filter.lfs.clean=" -c "filter.lfs.required=false" clone <your repo>
```

or running:

```bash
$ git config --global --unset "filter.lfs.smudge"
$ git config --global --unset "filter.lfs.clean"
$ git config --global "filter.lfs.required" "false"
```

**Comment by technoweenie** [comment]
`git lfs install --skip-smudge` will disable the smudge filter, but keep the clean filter intact (so you can still add new LFS files). You'll then want to use `git lfs pull {some-remote}` whenever you want to download objects.

**Comment by technoweenie** [comment]
Also, there's no way to disable LFS pushes from `git push` without deleting `.git/hooks/pre-push`. However, LFS will keep trying to replace that file unless you add your own custom one. LFS won't overwrite a custom `pre-push` hook.

**Comment by istvanszoke** [comment]
Thanks you for your answers, I can work with these. :)
