### ISSUE TITLE
File is mysteriously unretrievable from the lfs server during git clone, despite being available online

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#1653]
I just noticed that from one of my recent commits, an lfs-tracked file is undownloadable:

```
jonas@cyberman:~/Develop$ git clone https://gitlab.wobble.ninja/JonasT/wobbly wobbly-clone-test
Cloning into 'wobbly-clone-test'...
remote: Counting objects: 2573, done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 2573 (delta 105), reused 0 (delta 0)
Receiving objects: 100% (2573/2573), 644.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1587/1587), done.
Checking connectivity... done.
Downloading docs/font/Quicksand-Light.ttf (20.51 KB)
Downloading docs/font/Quicksand-Regular.ttf (23.27 KB)
Downloading misc/logo/icon.ico (71.62 KB)
Downloading misc/logo/icon.xcf (145.91 KB)
Downloading misc/logo/jellyphoto_orig.jpg (519.08 KB)
Downloading misc/logo/logo.ico (455.33 KB)
Downloading misc/logo/logo.svg.png (61.27 KB)
Downloading misc/logo/logo.xcf (900.90 KB)
Downloading misc/logo/logo_base.xcf (2.26 MB)
Checking out files: 100% (65/65), done.
jonas@cyberman:~/Develop$ cd wobbly-clone-test/
jonas@cyberman:~/Develop/wobbly-clone-test$ git remote update
Fetching origin
jonas@cyberman:~/Develop/wobbly-clone-test$ git fetch origin
jonas@cyberman:~/Develop/wobbly-clone-test$ git checkout 2-the-wobbly-compiler-should-be-able-to-compile-the-wobbly-compilerDownloading misc/logo/icon.ico (89.25 KB)
Error downloading object: misc/logo/icon.ico (e5e4a49bcf1adc0c344f8a276dae44a4ad3376b936755c02ba2cc58e3ebab246)

Errors logged to /home/jonas/Develop/wobbly-clone-test/.git/lfs/objects/logs/20161115T033306.019425508.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: misc/logo/icon.ico: smudge filter lfs failed
jonas@cyberman:~/Develop/wobbly-clone-test$
```
However, the file is clearly available online: https://gitlab.wobble.ninja/JonasT/wobbly/blob/2-the-wobbly-compiler-should-be-able-to-compile-the-wobbly-compiler/misc/logo/icon.ico

Also, pushing from the repo copy where that commit is present does nothing and the file is clearly properly present and properly tracked as well:
```
jonas@cyberman:~/Develop/wobbly$ git branch
* 2-the-wobbly-compiler-should-be-able-to-compile-the-wobbly-compiler
  master
jonas@cyberman:~/Develop/wobbly$ git push
Everything up-to-date
jonas@cyberman:~/Develop/wobbly$ stat misc/logo/icon.ico 
  File: 'misc/logo/icon.ico'
  Size: 91390     	Blocks: 184        IO Block: 4096   regular file
Device: fd02h/64770d	Inode: 19529878    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   jonas)   Gid: ( 1000/   jonas)
Context: unconfined_u:object_r:home_root_t:s0
Access: 2016-11-15 03:02:35.445585472 +0100
Modify: 2016-11-06 20:44:53.325165794 +0100
Change: 2016-11-06 20:44:53.325165794 +0100
 Birth: -
jonas@cyberman:~/Develop/wobbly$ git ls-files misc/logo/icon.ico
misc/logo/icon.ico
jonas@cyberman:~/Develop/wobbly$
```
---
I tried clone'ing the repo on multiple computers, it doesn't work on any of them. (I still use git-lfs 1.4.2 though on both, since https://github.com/github/git-lfs/issues/1652 currently prevents me from upgrading to 1.4.4)

Now I'm not sure what to do, since the repo is too old and also public, making it not really a good option to just nuke it and start over. Any suggestions?

**Comment by technoweenie** [comment]
What are the contents of `/home/jonas/Develop/wobbly-clone-test/.git/lfs/objects/logs/20161115T033306.019425508.log`? That should show the error you got from your host.

**Comment by JonasT** [comment]
Here are the contents of that file:
```
jonas@cyberman:~$ cat /home/jonas/Develop/wobbly-clone-test/.git/lfs/objects/logs/20161115T033306.019425508.log
git-lfs/1.4.2 (GitHub; linux amd64; go 1.7.1; git 6557f9f)
git version 2.7.4

$ git-lfs smudge -- misc/logo/icon.ico
Error downloading object: misc/logo/icon.ico (e5e4a49bcf1adc0c344f8a276dae44a4ad3376b936755c02ba2cc58e3ebab246)

Smudge error: Error buffering media file: Object not found on the server.: 
github.com/github/git-lfs/errors.newWrappedError
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/errors/types.go:166
github.com/github/git-lfs/errors.NewSmudgeError
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/errors/types.go:252
github.com/github/git-lfs/lfs.PointerSmudge
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/lfs/pointer_smudge.go:69
github.com/github/git-lfs/lfs.(*Pointer).Smudge
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/lfs/pointer.go:64
github.com/github/git-lfs/commands.smudgeCommand
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/commands/command_smudge.go:66
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/github/git-lfs/commands.Run
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/commands/run.go:65
main.main
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/git-lfs.go:33
runtime.main
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/proc.go:183
runtime.goexit
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=/home/jonas/Develop/wobbly-clone-test
LocalGitDir=/home/jonas/Develop/wobbly-clone-test/.git
LocalGitStorageDir=/home/jonas/Develop/wobbly-clone-test/.git
LocalMediaDir=/home/jonas/Develop/wobbly-clone-test/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/jonas/Develop/wobbly-clone-test/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_PREFIX=
jonas@cyberman:~$
```

**Comment by technoweenie** [comment]
> Object not found on the server

You'll need to check that your server has the file. The only thing that can be done from the client side is running `git lfs push --all` on the machine that introduced that file.

**Comment by JonasT** [comment]
Right, I just noticed that https://gitlab.wobble.ninja/JonasT/wobbly/blob/2-the-wobbly-compiler-should-be-able-to-compile-the-wobbly-compiler/misc/logo/icon.ico actually gives a 404 once you click the actual download button - so it's probably not on the server as I assumed.

Shouldn't either all files of the commit be available, or the push have been rejected?
I filed a bug with gitlab here: https://gitlab.com/gitlab-org/gitlab-ce/issues/24564

However, it would be very helpful with debugging this if someone could look into #1652 - this happened to me on the machine this broken commit originates from, so I can't try additional commands like `git lfs push --all` to attempt to fix this situation unless I can install git-lfs again..

**Comment by technoweenie** [comment]
> Shouldn't either all files of the commit be available, or the push have been rejected?

By default, no. Git servers need a custom pre-receive hook to reject LFS objects in commits if the LFS objects are unavailable. If you have Git LFS installed, with its pre push hooks in `.git/hooks/pre-push`, then pushes from your client won't push git objects if the LFS push fails.

**Comment by JonasT** [comment]
Git lfs *is* installed for my local clone of that repository where the broken commit originated from. I'm pretty careful doing that with all copies because if I need to invoke manual lfs commands to make sure the lfs files are handled I'm bound to forget.

If you're still saying this can't be a client bug I guess I'll have to take your word for it, the way it hooks into git with the smudge filter and all that goes way beyond my knowledge about inner git workings.

**Comment by technoweenie** [comment]
There definitely can be a bug with the pre-push hook. Can you look at your reflog to see what the before/after of your git repository was when you pushed the commit containing https://gitlab.wobble.ninja/JonasT/wobbly/blob/2-the-wobbly-compiler-should-be-able-to-compile-the-wobbly-compiler/misc/logo/icon.ico? If you can recreate the conditions of that push, maybe we'll find a spot where the pre-push hook is skipping some uploads.

**Comment by technoweenie** [comment]
Okay I just tried it, and realized recreating the conditions of a former push will be tougher than I thought.

The first problem is that I inadvertently broke the `--dry-run` flag: https://github.com/git-lfs/git-lfs/pull/1673. I backported it to this test branch that we're using for debug purposes. You can grab a build at https://github.com/git-lfs/git-lfs/releases/tag/v1.4.4-deadlock if you don't want to compile yourself.

Next, get the before/after commits from your server reflog. Let's say your history looks like this:

```
ccc # current HEAD for the branch
bbb # commit adding the missing file
aaa # commit before the push
```

Assuming that `master` is your branch, you'll want to run `pre-push` directly like this:

```bash
$ echo "refs/heads/master ccc refs/heads/master aaa" | git-lfs pre-push --dry-run origin https://gitlab.wobble.ninja/JonasT/wobbly
```

This is saying: "push the local commit `ccc` to update the remote from `aaa` to `ccc`". Locally, Git LFS runs this to determine the *git* objects being pushed. LFS scans through those for any LFS pointers.

```bash
# find all git blobs in commit ccc that is not on the remote
$ git rev-list --objects ccc --not --remotes=origin --
```

However, since you've already pushed this to your remote, then your repository already has the remote ref locally, so it probably won't show anything. So the best thing here is to push everything up to commit `aaa` to a separate repository, and use that as your remote. Once that's done, the above `rev-list` command should show an entry for `misc/logo/icon.ico` with its git blob OID.

```
$ git rev-list --objects 6c3b5a13264fbba338f4648851aacb9e61e7b813 --not --remotes=origin --
6c3b5a13264fbba338f4648851aacb9e61e7b813 # a tree or something, ignore it
1bca198451cc7404e257e5abe60a8478bf28d4cf jpg/kabuki-tattoo-left.JPG
9baeae349b0d20732ae5ae270d62abbef1fe4fb3 .gitattributes
0744ff7c15fdb618cbb299be8d0fbf228ba4e9b3
```

Now, you should see a similar entry for that file with a pre-push command doing a dry run. This will show the Git LFS OID.

```bash
$ echo "refs/heads/master 6c3b5a13264fbba338f4648851aacb9e61e7b813 refs/heads/master 64239baaced137b321984a68e77e75dead1f0b6a" | git lfs pre-push --dry-run origin https://github.com/github/git-lfs-test
push e1732d149d262963996ca77a47a5d3c51c85c6e97187afad370a8bef2828b6b7 => jpg/kabuki-tattoo-left.JPG
push 55d51edb307ed7bf4a1bbca3867d132a07f76828d57f37e0f31f712c02ceafe0 => png/render.png
push 124733b36d098353ad16bb11646643709e87c4746e0d97913a9826829e0477a3 => render.png
```

This output should

**Comment by technoweenie** [comment]
Well it turns out since your repository is public, I can also do this work :)

1. I cloned `https://gitlab.wobble.ninja/JonasT/wobbly` locally.
2. I found [this commit](https://gitlab.wobble.ninja/JonasT/wobbly/commit/c57a25056893eb985daf14e6ff34a422a2362d0a) which updates that file.
3. I reset my local repository to 11f9fcf308dbc5b80a7decadd773b34e63041f67, and pushed it to a private repo of mine.
4. I reset my local repository back to master, which is c3afb0ae1062b3cddb7d6c592ffbb62d35483aaf now.
5. I simulated the `pre-push` command:

```
$ echo "refs/heads/master c3afb0ae1062b3cddb7d6c592ffbb62d35483aaf refs/heads/master 11f9fcf308dbc5b80a7decadd773b34e63041f67" | git lfs pre-push -d origin https://github.com/technoweenie/wobbly-lfs-debug
push e5e4a49bcf1adc0c344f8a276dae44a4ad3376b936755c02ba2cc58e3ebab246 => misc/logo/icon.ico
push 4803b3aadd3decee26221fa78c99ebd1f9c68c9687d43a1a99cddae114cad883 => misc/logo/icon.xcf
push e667be301190aa69a4707331300766de15a0f14e8d33c10e23bbcab48e966719 => misc/logo/logo.svg.png
push a60ba7426d240859065a60d096c2eb15eb68c7e4e2cc56439d487c5510bcf4c1 => misc/logo/icon.xcf
push 21e62506922eba92ca00387d0b20e10bc58c00a744108f17de8239d10ca6a9f4 => misc/logo/icon.ico
push 74ffb011b3c30c5808d61cffb0c1b8f424964cdb3e7bad4a6262a821700c1572 => misc/logo/logo.ico
push 28fcbb1a24a7cb18e8ed39cee13e330e89d6e915f0c39fb468dea31042db62c8 => misc/logo/icon.xcf
push 4986e9125008383091614a4452a50b78b3cb3821ed0728aee1d4520695ef0fe4 => misc/logo/logo.svg.png
```

This shows `misc/logo/icon.ico` multiple times, implying it's been modified several times. The LFS OID at the commit I found is 21e62506922eba92ca00387d0b20e10bc58c00a744108f17de8239d10ca6a9f4. The LFS OID at master is e5e4a49bcf1adc0c344f8a276dae44a4ad3376b936755c02ba2cc58e3ebab246. I see both of those in the dry run output, so I don't think this is a client bug.

**Comment by JonasT** [comment]
I actually just noticed I made this commit on another machine than I thought, and `git lfs push --all` fixed it!

Should I still try some things to find out why this happened? Because if there's a way this can happen with LFS properly installed into the repo, I really think that you should fix it

**Comment by JonasT** [comment]
What bothers me is that this is a valid outcome. I think either the client or server should have prevented this (ideally both) - so I filed a bug with gitlab: https://gitlab.com/gitlab-org/gitlab-ce/issues/24564

However, I'm not sure which place (client or server) is the best one to add functionality to prevent this from happening..

**Comment by technoweenie** [comment]
My example shows that the LFS pre-push hook found that object in the `--dry-run`, and should've uploaded it. There's not much else we can do on the client side, unfortunately.

**Comment by JonasT** [comment]
Well if it is a client issue at all, it is probably something with unexpected interruption / failure conditions that aren't easily reproduced because I've never had this issue before in multiple months. Anyway, IMHO gitlab should also refuse incomplete pushes so let's see how that bug report goes.
