### ISSUE TITLE
git-lfs not found in epel repository

### ISSUE THREAD

**Issue by Eothred** [git-lfs/git-lfs#1655]
According to the [wiki](https://github.com/github/git-lfs/wiki/Installation), this should be the procedure to install git-lfs on CentOS7:

Recommended method for RHEL/CentOS 5 and 7 (not 6!)

-    Install the epel repo link (For CentOS it's just ```sudo yum install epel-release```)
-    ```sudo yum install git-lfs```

However, as you can see [here](https://dl.fedoraproject.org/pub/epel/7/x86_64/g/), there does not seem to be any git-lfs package in the EPEL repository. I end up having to install the github_git-lfs repo (which is fine by me but instructions seem to be off).

Edit: was according to wiki, not readme. Also installation.md does not mention epel only the packagecloud thing. Maybe just wiki that needs to be updated then?

**Comment by technoweenie** [comment]
I think the markdown is a little weird on that page. It looks like you should be installing git v1.8.2+ from epel, not git-lfs. I just fixed it.

**Comment by romaninsh** [comment]
Just hit the same error, with the help in this ticket was able to proceed.

**Comment by technoweenie** [comment]
What error did you hit? Is git not in the `epel-release` package? The wiki page does not claim that git-lfs is in that package. We currently ship to packagecloud only.

**Comment by Eothred** [comment]
Hi,

Well, I see now that you do not, but it is sort of half way claiming so. The instructions state

> Install git >= 1.8.2
>
>   Recommended method for RHEL/CentOS 5 and 7 (not 6!)
>        Install the epel repo link (For CentOS it's just sudo yum install epel-release)
>       sudo yum install git-lfs

So you are saying that the instruction number one is to install git, but the command is "sudo yum install git-lfs" which is wrong, it should be "sudo yum install git". When I read those instructions I actually understood it as epel-release containing git-lfs. I now see that I misunderstood that.

**Comment by technoweenie** [comment]
Ahh, fixed the typo. Thanks!

![installation_ _git-lfs_git-lfs_wiki](https://cloud.githubusercontent.com/assets/21/20674204/43f31d46-b545-11e6-93d7-78d6772e0fda.png)
