### ISSUE TITLE
Having issues with 'error downloading object' on a particular repo

### ISSUE THREAD

**Issue by JohnCallaghan01** [git-lfs/git-lfs#1665]
We've had lots of issues with a particular repo over the last few months, with lots of 'botch' fixes which usually involve re-cloning the repo. I'm not expert so simple language is appreciated!

It seems like there's lots of large files which 'no longer exist' in LFS, but git keeps trying to pull them down and fail anyway.

Here's the error..
```
git-lfs/1.4.4 (GitHub; darwin amd64; go 1.7.3; git cbf91a9)
git version 2.7.4 (Apple Git-66)

$ git-lfs smudge -- Artwork/Introduction/Introduction.psd
Error downloading object: Artwork/Introduction/Introduction.psd (aa0293a637d2a32fa366b7639ce3868d133b821ecc7354f0a1c8da81e84de5a8)

Smudge error: Error buffering media file: Object not found on the server.: 
github.com/github/git-lfs/errors.newWrappedError
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/errors/types.go:166
github.com/github/git-lfs/errors.NewSmudgeError
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/errors/types.go:252
github.com/github/git-lfs/lfs.PointerSmudge
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/lfs/pointer_smudge.go:69
github.com/github/git-lfs/lfs.(*Pointer).Smudge
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/lfs/pointer.go:64
github.com/github/git-lfs/commands.smudgeCommand
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/commands/command_smudge.go:66
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/github/git-lfs/commands.Run
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/commands/run.go:65
main.main
	/Users/ttaylorr/dev/go/src/github.com/github/git-lfs/git-lfs.go:33
runtime.main
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:183
runtime.goexit
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=[dir]
LocalGitDir=[dir]/.git
LocalGitStorageDir=[dir]/.git
LocalMediaDir=[dir]/.git/lfs/objects
LocalReferenceDir=
TempDir=[dir]/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_REFLOG_ACTION=pull
GIT_PREFIX=
```
`

There's a team of 5 or 6 people using the repo, all through SourceTree, usually the issue first presents itself as certain files appear to be changed on a computer, when nothing has been done to them. For example a PSD may appear as changed on my machine, yet I don't even have photoshop installed.

Eventually pulls will fail as files fail to download from LFS. I have a suspicion that somebody has at some point tried to push large files without LFS installed, but I recently checked all the machines and it appears LFS is now currently installed.

Any help you can offer is massively appreciated. At this point I'm even open to the idea of abandoning LFS (and using local servers for storing large files), but I still don't know how to fix the issues with git trying to pull down large files that are apparently not there anymore?

**Comment by technoweenie** [comment]
> Object not found on the server.

Your server is missing that object. Unfortunately, the only way to fix this is to find a computer that has it, and run `git lfs push --all` to ensure the server gets it. If you're deleting objects from the server on purpose to save disk space, LFS does not support this workflow. There's some discussion of adding object expiration to LFS, however: https://github.com/git-lfs/git-lfs/issues/1101#issuecomment-260769632

**Comment by JohnCallaghan01** [comment]
Thanks for the reply technoweenie, the file is visible on github.com and not affecting my colleagues machine, so I assumed it must still be available on the server? 

However the file (a 150MB psd) is not showing up on `git lfs ls-files` & when I run `git lfs fsck` I get the message below (along with 300 similar entries for different files):

`Object Artwork/Introduction/Introduction.psd (500202b86ded6f846c2919aaacf33320584cd75a46c6fda4d2e630f34fe971ee) could not be checked: no such file or directory`

Sometimes the filename will be different (i think this reflects my colleagues doing recent commits) for example now `git pull` returns:
```
Downloading Artwork/Introduction/Splash Singles.psd (4.63 MB)
Error downloading object: Artwork/Introduction/Splash Singles.psd (c3494e741d1a28df2f619a0e8e2637143b6eee3738ce9fffec3c11be6de488ac)

Errors logged to /Users/john_callaghan/Documents/ClientProjects/WarnDry/WarnDryApp/.git/lfs/objects/logs/20161116T155529.233376871.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: Artwork/Introduction/Splash Singles.psd: smudge filter lfs failed
```

**Comment by technoweenie** [comment]
Can you send us your repo info so we can check it out? Use https://github.com/contact if you want to take it private.

**Comment by JohnCallaghan01** [comment]
Hi - yes it's a private project - is it easier if I invite you as a collaborator, or should I just send the git info via /contact/?

**Comment by technoweenie** [comment]
Please use the contact page. They'll send it to my team.
