### ISSUE TITLE
git checkout branch does not works

### ISSUE THREAD

**Issue by BalamChaac** [git-lfs/git-lfs#1669]
Hi there after a college update a git repository through the github desktop en delete some files, it does not upload the changes to github, so when I try to push the changes manually it shows the next message:

```
"git-lfs clean -- 'articulos/La_milpa_de_los_mayas-_enfoque_y_mÃ©todo..pdf'": git-lfs clean -- 'articulos/La_milpa_de_los_mayas-_enfoque_y_mÃ©todo..pdf': No such file or directory
error: external filter git-lfs clean -- %f failed -1
error: external filter git-lfs clean -- %f failed
fatal: articulos/La_milpa_de_los_mayas-_enfoque_y_método..pdf: clean filter 'lfs' failed
```

and when I try to checkout the prevoios commit for recover the changes locally it does:

```
"git-lfs smudge -- 'articulos/La_milpa_de_los_mayas-_enfoque_y_mÃ©todo..pdf'": git-lfs smudge -- 'articulos/La_milpa_de_los_mayas-_enfoque_y_mÃ©todo..pdf': No such file or directory
error: external filter git-lfs smudge -- %f failed -1
error: external filter git-lfs smudge -- %f failed
fatal: articulos/La_milpa_de_los_mayas-_enfoque_y_método..pdf: smudge filter lfs failed
```

I do not know how to recover the work, I was searching for in other issues and I didn't find any similar so I think this is a bug.

I really appreciate if there is a way to recover the work done. Thanks

**Comment by ttaylorr** [comment]
Looks like the issue is that LFS still thinks that there are files in your working tree that your colleague removed.

You should be able to fix this up by disabling the clean and smudge filter and then doing a hard reset to the tip of whichever branch you want:

```bash
$ git fetch <your remote>
$ git \
    -c "filter.lfs.clean=" \
    -c "filter.lfs.smudge=" \
    reset --hard <your-remote>/<branch> 
```

**Comment by BalamChaac** [comment]
Thanks for the advise, but after apply the command it shows
`fatal: Dioses_mayas.docx: smudge filter lfs failed
`
And when I do a checkout it shows:
`git-lfs smudge -- 'Dioses_mayas.docx': git-lfs: command not found
error: external filter git-lfs smudge -- %f failed -1
error: external filter git-lfs smudge -- %f failed
fatal: Dioses_mayas.docx: smudge filter lfs failed`

So I can't move between commit

**Comment by technoweenie** [comment]
> command not found error

Does running `git-lfs` in the same command prompt work? If not, ensure you've installed Git LFS into your system path.

**Comment by BalamChaac** [comment]
Thanks for the advice it works now with the new version of git lfs
