### ISSUE TITLE
Should we post hashes along with the GitLFS releases?

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#1678]
Can/should we post the SHA256 hashes along with our released binaries similar to the [Git for Windows releases (scroll down)](https://github.com/git-for-windows/git/releases/tag/v2.10.2.windows.1)?

**Comment by technoweenie** [comment]
Yeah, seems like that step could be part of the build process. It already dumps the markdown links to download rpms and debs that we throw at the bottom of the release.

**Comment by ttaylorr** [comment]
I'd be alright with doing this 👍

**Comment by technoweenie** [comment]
#1687 adds this to the `script/release` output.  It's wrong for windows stuff though, since those have to be re-built and signed on Windows.

**Comment by larsxschneider** [comment]
Thanks @technoweenie ! Do you see a way to fix the Windows hashes, too?

**Comment by ttaylorr** [comment]
We do this as regular practice now!
