### ISSUE TITLE
Support for Windows Long Paths

### ISSUE THREAD

**Issue by DoDoENT** [git-lfs/git-lfs#1690]
Hi!

We have a very deep git repository (6 submodules one inside another), and the most deep one has some prebuilt binaries on LFS. When cloning the entire hierarchy on Windows 10, I get an error when the most deep submodule tries to fetch LFS data. I even tried manually with `git lfs fetch`, but same error happens:

    open C:\Users\DoDo\Desktop\Microblink\core-recognizer-api\.git\modules\core-recognizer\modules\core-ocr-engine\modules\core-neural-network\modules\core-utils\modules\opencv-bin\modules\Windows\lfs\objects\incomplete\f98b3d50d1f150b17e3c77b1f6cfb0f77edf9922f93f653a885b6997f380cf9a.tmp: The system cannot find the path specified.

I believe the error is caused by path being too long (280 characters) - I even tried creating a symbolic link on c:\ which points to root git repository and tried fetching from it, but I got the same error. What finally worked was to put my root git directly on c:\ and rename it to a short single-letter name.

Is there any LFS option that will turn on support for long paths? The git has option [`core.longpaths`](http://stackoverflow.com/a/26111092) which I do have enabled, but it seems LFS is not honoring it.

**Comment by ttaylorr** [comment]
Hi, @DoDoENT -- thanks for brining this up! Git LFS should be respecting this option if it's in your `.gitconfig`, but there may be some issues with opening files that have names that long on Windows, which I'm not sure how to handle.

Going to cc @larsxschneider who has some more expertise on debugging these sorts of Windows issues to 👂  his 💭 .

**Comment by ttaylorr** [comment]
Actually, this looks like it might be coming in the next release of Go: ([refs](https://github.com/golang/go/blob/2925427a47f41622f28f84889ad7aade27581144/src/os/path_windows.go#L131-L139)). If the next version of Go hasn't released by the time that we're ready to push the next release of LFS, I'd be okay with temporarily back-porting this function into LFS and using it in conjunction with the `core.longpaths` setting that you mentioned above 👍 .

**Comment by DoDoENT** [comment]
Thank you for quick answers! I am looking forward to a fix.

**Comment by technoweenie** [comment]
I think we should wait for Go 1.8 (or whatever the first go release to include this is), since it seems like it's coming soon. We can ship a new LFS pretty much the day a new Go version is out, even if there are no LFS fixes. We'll just update the binaries. 

For giggles, I'm going to take some time to attempt a backport, and see how terrible the diff is. If it's not bad, we may just sneak it into Git LFS v1.5.3 (which is coming this week to fix #1699).

**Comment by technoweenie** [comment]
I'm not having much luck coming up with a failing test for this. It looks like git itself is having issues with long paths:  https://gist.github.com/technoweenie/bde7de38ff5a731998a5f56effcddb68

1. Confirmed that `core.longpaths` is enabled at the top of the stdout.
2. `git clone` fails with the error:

        fatal: cannot stat '\''C:/Users/techn/AppData/Local/Temp/git-lfs_TEMP.OMvk48/test-long-paths.sh-4400/00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000/.git/hooks/applypatch-msg.sample'\'': Filename too long'

That path is 263 characters. That file is written by `git clone` as part of an empty repo initialization step, so it's not related to LFS. Am I missing something in my [failing test](https://github.com/git-lfs/git-lfs/compare/release-1.5...fix-windows-long-paths?expand=1)?

The version of git on my windows VM is pretty old, so I'm going to try upgrading to see if that helps.

**Comment by technoweenie** [comment]
@DoDoENT can you try this build, based on #1705? Just download, and replace your existing `git-lfs.exe`. The only failing ci test is my failed attempt at writing a test. 

[git-lfs-1.5.1-windows-path-hotfix.zip](https://github.com/git-lfs/git-lfs/files/607440/git-lfs-1.5.1-windows-path-hotfix.zip)

**Comment by DoDoENT** [comment]
It appears it works. Great job! Thank you!

**Comment by ttaylorr** [comment]
Awesome! If Go doesn't include this feature by the time that we release v2.0.0, we'll reverse back-port https://github.com/git-lfs/git-lfs/pull/1705 into that tree.

**Comment by sithmein** [comment]
I believe that the fix didn't cover all situations, at least we are having still problems:

```
$ git-lfs.exe pull knime-jenkins
Could not checkout file
 
Could not create working directory file: open org.knime.build.config/director/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.300.v20150602-1417/eclipse_1611.so: The system cannot find the path specified.
```

After a quick code inspection I believe the problem is that the fixLongPath function assumes it gets an absolute path but according to the error message above only a relative path seems passed to PointerSmudgeToFile and therefore longpathos.Create. Could this be the problem?

**Comment by ttaylorr** [comment]
@sithmein our next release will be on Go 1.8, which has addressed this problem in the standard library.
