### ISSUE TITLE
No support for http.sslCert and http.sslKey

### ISSUE THREAD

**Issue by bgiaccio** [git-lfs/git-lfs#1701]
Looks like at some point http.sslCAInfo was added but no code to parse the Cert and Key making it impossible to pull code where SSLVerifyClient is configured on the server.

Looks like the change is simple enough, I found a sample https://gist.github.com/michaljemala/d6f4e01c4834bf47a9c4 and a blog post http://www.bite-code.com/2015/06/25/tls-mutual-auth-in-golang

**Comment by technoweenie** [comment]
Good news! This will be in Git LFS v2.0 (which should be out sometime in Feb), courtesy of #1869.

**Comment by bgiaccio** [comment]
Sweet, I was trying to find time to work on this myself.
