### ISSUE TITLE
git lfs ls-files not listing lsf files

### ISSUE THREAD

**Issue by loretoparisi** [git-lfs/git-lfs#1714]
I have followed the simplest tutorial in the [wiki](https://github.com/git-lfs/git-lfs/wiki/Tutorial#create-a-new-repo):

```
admin@macbookproloreto:~/Desktop$ mkdir GitLfsDemo
admin@macbookproloreto:~/Desktop$ cd GitLfsDemo/
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git init .
Initialized empty Git repository in /Users/admin/Desktop/GitLfsDemo/.git/
admin@macbookproloreto:~/Desktop/GitLfsDemo$ echo "Hello World Git Lfs" > README.md
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git add README.md 
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git commit -m "Initial commit"
[master (root-commit) 2502123] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > foo.txt
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > bar.txt
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > cat.bin
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > dog.bin
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git add foo.txt bar.txt cat.bin dog.bin 
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git lfs track '*.bin'
Tracking *.bin
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git lfs track
Listing tracked paths
    *.bin (.gitattributes)
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git add .gitattributes
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitattributes
	new file:   bar.txt
	new file:   cat.bin
	new file:   dog.bin
	new file:   foo.txt

admin@macbookproloreto:~/Desktop/GitLfsDemo$ git commit -m "Added files"
[master b78badf] Added files
 5 files changed, 12 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 bar.txt
 create mode 100644 cat.bin
 create mode 100644 dog.bin
 create mode 100644 foo.txt
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git lfs ls-files
admin@macbookproloreto:~/Desktop/GitLfsDemo$
```

**Comment by technoweenie** [comment]
It looks like the problem is caused by not adding the updated bin files in your commit.

```
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > foo.txt
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > bar.txt
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > cat.bin
admin@macbookproloreto:~/Desktop/GitLfsDemo$ ls > dog.bin
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git add foo.txt bar.txt cat.bin dog.bin 
```

This adds a bunch of txt and bin files to the git index, to be added to the next commit. The bin files are not LFS pointers since there's nothing in `.gitattributes` yet.

```
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git lfs track '*.bin'
Tracking *.bin
```

This creates a `.gitattributes` file. It also scans your tree for matching files and converts them to LFS pointers. Note: the LFS pointer versions of the bin files are not in your git index at this point. Your git index should contain the text files from above.

```
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git lfs track
Listing tracked paths
    *.bin (.gitattributes)
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git add .gitattributes
```

This adds _just_ `.gitattributes` to your git index. Your git index should contain all of the original txt and bin files.

```
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitattributes
	new file:   bar.txt
	new file:   cat.bin
	new file:   dog.bin
	new file:   foo.txt
```

This is showing new files being added. It's not immediately clear, but git has differing versions of `cat.bin` in the index (the `ls` output) and on the local file system (the LFS pointer).

```
admin@macbookproloreto:~/Desktop/GitLfsDemo$ git commit -m "Added files"
[master b78badf] Added files
 5 files changed, 12 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 bar.txt
 create mode 100644 cat.bin
 create mode 100644 dog.bin
 create mode 100644 foo.txt
```

This commits everything in the git index.

Here's a similar command run that adds the bin files again after running `git lfs track`:

```
$ git init
Initialized empty Git repository in /Users/rick/p/lfs-demo/.git/

$ git lfs version
git-lfs/1.5.2 (GitHub; darwin amd64; go 1.7.3)
$ git version
git version 2.10.2

$ echo "Hello World Git Lfs" > README.md
$ git add README.md
$ git commit -m "Initial commit"
[master (root-commit) 7de1845] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md

$ ls > foo.txt
$ ls > bar.txt
$ ls > cat.bin
$ ls > dog.bin
$ git add foo.txt bar.txt cat.bin dog.bin
$ git lfs track '*.bin'
Tracking *.bin
$ git lfs track
Listing tracked patterns
    *.bin (.gitattributes)

# This adds .gitattributes AND the bin files replaced by LFS pointers.
$ git add "*.bin" .gitattributes
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitattributes
	new file:   bar.txt
	new file:   cat.bin
	new file:   dog.bin
	new file:   foo.txt

$ git commit -m "Added files"
[master 6a454ce] Added files
 5 files changed, 12 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 bar.txt
 create mode 100644 cat.bin
 create mode 100644 dog.bin
 create mode 100644 foo.txt

$ git lfs ls-files
9aeb42de6d * cat.bin
c77aeedb82 * dog.bin
```

**Comment by technoweenie** [comment]
I also updated the Wiki. I wish the author didn't choose such a confusing example though. A simpler workflow is something like this:

```
$ git lfs track "*.bin"
$ ls > foo.txt
$ ls > bar.txt
$ ls > cat.bin
$ ls > dog.bin
$ git add .
$ git commit -m "add some files"
$ git lfs ls-files
```

**Comment by b0r1sp** [comment]
update: 
all the proposed methods from above did not work for me. imho the missing part is doing a `git lfs install` before tracking files.

Tested on OS X 10.13.2

```bash
$ git lfs version
$ git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.1)
```
Assuming there's already a psd-file in the directory:

```bash
$ git init
$ git lfs install
$ git lfs track "*.psd"
$ git add -A
$ git commit -m "add files"
$ git lfs ls-files
```

Please update the wiki if appropriate - thank you

**Comment by ttaylorr** [comment]
@b0r1sp thanks for sending this, though I am unable to reproduce this issue. Are you saying that by following the above steps you were _not_ able to observe any output from `git lfs ls-files`?

If so, this could be because your `*.psd` files in the directory are empty (contain 0 bytes), and therefore are not considered to be LFS objects. Non-empty files with extensions tracked by LFS should be shown in the output of `git lfs ls-files`.

**Comment by b0r1sp** [comment]
>  Are you saying that by following the above steps you were not able to observe any output from git lfs ls-files?

Yes, true. 

> If so, this could be because your *.psd files in the directory are empty (contain 0 bytes),

No, definitely not. 

I followed tuts strictly, tried all kinds of different variations - did not succeed until I did `git lfs install`. I guess this is something MacOS specific (I installed git-lfs with brew), I did not observe this on CentOS 7.

**Comment by ttaylorr** [comment]
> did not succeed until I did `git lfs install`

Ah, I misread your comment; yes, running `git lfs install` is a required part of this process. It is mentioned in the tutorial via a link to [this][1] page.

[1]: https://github.com/git-lfs/git-lfs/wiki/Installation
