### ISSUE TITLE
git lfs install fails when run in root DIR on windows

### ISSUE THREAD

**Issue by James-Dengel** [git-lfs/git-lfs#1717]
Install 1.5.2

trying to run the install or uninstall command from ROOT fails on windows

> $ git lfs install
> panic: Error trying to init LocalStorage: mkdir lfs: Access is denied.
> 
> goroutine 1 [running]:
> panic(0x7868a0, 0xc04200e1e0)
>         C:/Go/src/runtime/panic.go:500 +0x1af
> github.com/git-lfs/git-lfs/localstorage.ResolveDirs()
>         C:/Go/src/github.com/git-lfs/git-lfs/localstorage/currentstore.go:40 +0x                                                                    4ca
> github.com/git-lfs/git-lfs/commands.resolveLocalStorage(0xc042104000, 0x9ff348,                                                                     0x0, 0x0)
>         C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:78 +0x1b
> github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc0                                                                    42104000, 0x9ff348, 0x0, 0x0, 0xc042104000, 0x9ff348)
>         C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/comma                                                                    nd.go:474 +0x25c
> github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0                                                                    420a69c0, 0xc0420bbeb0, 0x1)
>         C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/comma                                                                    nd.go:551 +0x364
> github.com/git-lfs/git-lfs/commands.Run()
>         C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:65 +0x19d
> main.main()
>         C:/Go/src/github.com/git-lfs/git-lfs/git-lfs.go:33 +0x118

if you run from any other location the command works as expected.

**Comment by technoweenie** [comment]
Posted a fix: https://github.com/git-lfs/git-lfs/pull/1727

**Comment by technoweenie** [comment]
Also, thanks for the bug report with stack trace :)

**Comment by James-Dengel** [comment]
I hate it when people report an issue without a stacktrace/logging/ some sort of reproduction steps/ version they installed.
Drives me insane.

**Comment by anna64000** [comment]
thanks

**Comment by rjk40** [comment]
Was the application being manipulated for my device
