### ISSUE TITLE
Listing fails when [attr] alias is used

### ISSUE THREAD

**Issue by danielbayley** [git-lfs/git-lfs#1719]
This format works as expected:
~~~ ini
*.png filter=lfs diff=lfs merge=lfs -text
~~~
~~~ sh
> git lfs track
Listing tracked patterns
    *.png (.gitattributes)
~~~

But if I use an `[attr]` alias then `git lfs track` (list) on the command line fails to list anything…
~~~ ini
[attr]lfs filter=lfs diff=lfs merge=lfs -text
*.png   lfs
~~~
~~~ sh
> git lfs track
Listing tracked patterns
    [attr]lfs (.gitattributes)
~~~

**Comment by technoweenie** [comment]
Thanks for the pointer. This is a bug in `git lfs track` in listing the patterns, but does not affect actual Git LFS usage. If you're experiencing an issue with LFS objects being added or downloaded properly, you may want to investigate your `.gitattributes` syntax.

**Comment by mathstuf** [comment]
See #2413 for discussion involving this.
