### ISSUE TITLE
How to clean lfs/objects directory? [question]

### ISSUE THREAD

**Issue by AndrewJDR** [git-lfs/git-lfs#1724]
How does one "clean" the lfs/objects directory such that it holds **only** the lfs objects for the currently checked-out revision?

**Comment by technoweenie** [comment]
Check out the [`git lfs prune` command](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn).

**Comment by AndrewJDR** [comment]
Perhaps I misunderstand the command's configuration options or the command's output, but shouldn't i see "8 local objects, 8 retained" here?
```
$ git -c lfs.fetchrecentrefsdays=0 -c lfs.fetchrecentcommitsdays=0 -c lfs.fetchrecentremoterefs=0 -c lfs.pruneoffsetdays=0 lfs prune --verbose
✔ 8 local objects, 14 retained                                                                                                                                                                                                                                                                                                 
Nothing to prune
```

**Comment by sixtyfive** [comment]
Setting them to 0 days disables them, apparently.

**Comment by GandalfSaxe** [comment]
What was the solution? Setting what to zero?

**Comment by Dante1243** [comment]
Thanks guys this freed up 160 GB for me
