### ISSUE TITLE
Trouble with equal (=) signs in filename

### ISSUE THREAD

**Issue by smorin-primero** [git-lfs/git-lfs#1730]
I tried to clone a repository with a lfs file where the filename contains an equal sign, and the clean filter failed:

```
git-lfs/1.5.2 (GitHub; windows amd64; go 1.7.3; git 547a06aa)
git version 2.11.0.windows.1

$ git-lfs clone ...
Error updating the git index:
Unknown command ""
error: packet write failed
error: external filter 'git-lfs filter-process' failed
fatal: Test=.png: clean filter 'lfs' failed
```

Also when we try to add a file with an equal sign, we get a similar error:

```
$ GIT_TRACE=1 git add Test\=.png
09:22:43.235434 git.c:371               trace: built-in: git 'add' 'Test=.png'
09:22:43.240449 run-command.c:350       trace: run_command: 'git-lfs filter-process'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: Initialize filter-process
trace git-lfs: Read filter-process request.
trace git-lfs: Read filter-process request.
09:22:44.165040 run-command.c:42        trace: run_command: running exit handler for pid 8720
Unknown command ""
```

**Comment by larsxschneider** [comment]
Thanks for the report! Unfortunately I cannot reproduce the error on my windows machine.
Can you post the output of the following command?

```
GIT_TRACE=1 git clone --branch equal-bug https://github.com/larsxschneider/lfstest-individual-files.git smudge-error
``

**Comment by larsxschneider** [comment]
Plus, do you use the Git bash or Cygwin?

**Comment by smorin-primero** [comment]
I use Git bash, and I can't reproduce using your example. I will try to create a little example where it works.

I know that we have the problem on a couple of our repositories, so it's not isolated. I doubt it's the servers fault, but we use the self-hosted Bitbucket server.

**Comment by ttaylorr** [comment]
@smorin-primero thanks for opening this. My initial thought is that the `=` character in the filename is unrelated to the issue at hand, and it is rather related to something in the file's contents. The ASCII hexcode for `=` is `0x3d` which has no special bearing in the LFS or the `pkt-line` protocol.

Are you able to share the contents of a repo that is able to reproduce the problem? That would be very helpful in debugging whatever issue is going on here 👍.

**Comment by smorin-primero** [comment]
Ok, so it looks like it's more complicated. I was able to reproduce the problem using the image in attachment, only when there is an equal sign in the filename.

So adding locally this file as a lfs file to @larsxschneider repository, I get the same problem for the add.

![test3=.png](https://cloud.githubusercontent.com/assets/20543545/20807389/b13d145e-b7cc-11e6-865c-6f011858bdbe.png)

**Comment by smorin-primero** [comment]
And looking at the lfs objects that is created, it's truncated at the first 1K exactly.

**Comment by larsxschneider** [comment]
It's not the content, it's the file size. This fails on every repo if *.bin files are tracked on macOS:

`mkfile -n 40999 a=.bin; git add "a=.bin"`

**Comment by larsxschneider** [comment]
@smorin-primero I think I [found and fixed the issue](https://github.com/git-lfs/git-lfs/pull/1731/commits/2fefa7b6ee421ad6ff10fec19411c5c56ed2cf3f). Can you build and test the [lars/fix-equals-in-pathname](https://github.com/git-lfs/git-lfs/tree/lars/fix-equals-in-pathname) branch yourself? If not would you be willing to test a GitLFS executable with this fix?

**Comment by smorin-primero** [comment]
@larsxschneider I don't have the toolchain installed, if you can provide me an executable I have no problem testing it.

**Comment by larsxschneider** [comment]
Here you go: [git-lfs.zip](https://github.com/git-lfs/git-lfs/files/627301/git-lfs.zip)
Please run `git lfs version` and check that you get this (notice the hash!):
```
git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git eb632903)
```

**Comment by smorin-primero** [comment]
```
$ git lfs env
git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git eb632903)
git version 2.11.0.windows.1
```

Yes it works on my side. Good Job.

**Comment by larsxschneider** [comment]
Thank you! 😊
