### ISSUE TITLE
Git lfs problem (need to check if remote is same exact as local)

### ISSUE THREAD

**Issue by pointcache** [git-lfs/git-lfs#1735]
Hi i was pushing ,then i cancelled in sourcetree.
Now it was about 1.3 gig push because i moved a lot of files around so it was showing this 
![image](https://cloud.githubusercontent.com/assets/5315202/20878198/85602138-ba9b-11e6-940f-0637b22937dc.png)
I cancelled due to reasons and now when i try to push again it says its already pushed.
Despite me cancelling.
???????
How can it be completed?
what should i do to force the recheck of literally everything, so it scans my local repo and scans remote and makes sure all discrepancies are detected.

**Comment by pointcache** [comment]
I just need to know if my remote is corrupted now because of the cancel or its just lfs that was showing me wrong information.

**Comment by ttaylorr** [comment]
You can try the push again with the `--all` flag, which will push objects to the server, even if they were already there.

I am curious why LFS is reporting that those objects were already pushed.

**Comment by technoweenie** [comment]
> I am curious why LFS is reporting that those objects were already pushed.

LFS assumes that any pushed Git objects also have their LFS objects pushed. Otherwise, it'd be scanning the entire git history one very push. Cancelling a push _should_ also halt the git push, but I'm not sure how SourceTree works.

**Comment by Thomasnss** [comment]
Sir Please try as many repository as you can there you,surrealy should fine you answer.

**Comment by ttaylorr** [comment]
Hi, I'm not quite able to follow the details of this issue, but if there is still a problem, please let me know here or elsewhere in a new issue. Since this thread has been inactive for a while, I am going to close this discussion for now.

**Comment by ttaylorr** [comment]
> Files are still acting the same way blank scream and the Bowser not access
> the full internet coming in clear not clear

Hi, could you please clarify what's wrong? I'm still having a hard time
following what's going on.
