### ISSUE TITLE
Importing another repo fails

### ISSUE THREAD

**Issue by tmoers** [git-lfs/git-lfs#1748]
Hi,

I'm trying to import a repository `source` that uses lfs into a new repository using lfs while keeping history.

These are the steps I take:

* in `source`: move the entire repo to the directory _newdir_ and push to origin
* in `target`: git init the target repo
* in `target`: point the origin to `source`
* in `target`: pull
* in `target`: set the origin to a new empty repository in gitlab
* in `target`: push

This last step fails with the following errormessage:
```
open E:\workspace\target\doc\foo.pdf: The system cannot find the path specified.
error: failed to push some refs to 'https://.../target.git'
```

For some reason the lfs managed file is expected to be where it was located originally, and not in its new location (the newdir where everything resides now).

Any idea what I'm doing wrong?

Also note that I had to disable lfs while doing the import and re-enable it later, because I got errors doing the import otherwise.

**Comment by technoweenie** [comment]
In step four, when you're pulling `source` into `target`, are you getting all of the LFS objects? LFS only downloads what it needs to satisfy the working directory. Try `git lfs fetch {source} --all` (where `{source}` is the remote name of your source) before pushing to the new repository.

**Comment by tmoers** [comment]
Thanks.. That did the trick!
