### ISSUE TITLE
skipped file

### ISSUE THREAD

**Issue by alejandrorbradford** [git-lfs/git-lfs#1751]
when trying to push my code I get this output;

Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 123.08 MB skipped     
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 3509bacf08db7e7c09ceb60d27baaac8
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps is 113.56 MB; this exceeds GitHub's file size limit of 100.00 MB

I tracked the file already but it's still showing this error

any thoughts?

**Comment by technoweenie** [comment]
There are two things going on here:

1. There is a commit adding that google maps file as a git blob without LFS. Even if you updated it to use LFS, the older commit is still there. Check out [this help guide for resolving this](https://help.github.com/articles/removing-files-from-a-repository-s-history/).
2. A "skipped" file is one that already loves on the server, and doesn't need to be uploaded again.

**Comment by alejandrorbradford** [comment]
Thanks for your input. I removed the file from the older commits with the guide you specified then tried to push the code again. It's still not working.

**Comment by technoweenie** [comment]
What does the entire output look like for the push attempt?

**Comment by alejandrorbradford** [comment]
![screen shot 2016-12-09 at 9 59 18 am](https://cloud.githubusercontent.com/assets/14142837/21053161/35d2acb8-bdf6-11e6-8c28-9da0ecc2a29d.png)

**Comment by alejandrorbradford** [comment]
It says the large file is untracked but its still trying to push it? right?

**Comment by technoweenie** [comment]
It looks like you just reversed the most recent commit which added the LFS file. There's still another unpushed commit that includes that google maps file as a git blob.

**Comment by alejandrorbradford** [comment]
when I do, git rm --cached Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps, again
I get this output;

fatal: pathspec 'Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps' did not match any files

**Comment by technoweenie** [comment]
Compare your current HEAD commit to the one that's on GitHub. That's the range of commits that includes that google maps file that GitHub is rejecting. For example, I just tried adding a 140MB file to Git LFS:

```sh
$ git push origin wat
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 115.04 MiB | 5.42 MiB/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 1 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 6169f7747708a3a4864696abddecffad
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File TF DJ SET SEPT 2013.mp3 is 142.36 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/git-lfs/git-lfs
 ! [remote rejected]   wat -> wat (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/git-lfs/git-lfs'
```

You can see [here](https://github.com/git-lfs/git-lfs/commits/master) that the latest git-lfs commit on our GitHub remote is bfabc5a6f89bd702377dba7978a89c959df1e74e. I can look at the unpushed commits with:

```sh
$ git log HEAD...bfabc5a6f89bd702377dba7978a89c959df1e74e
commit 0b4502e244d078136a40b3c5f6d64c8313286e59
Author: risk danger olson <technoweenie@gmail.com>
Date:   Fri Dec 9 08:15:41 2016 -0700

    remove it

commit a2e3ebdaa01ed3218900f04a98a8a7e91a9fbbd4
Author: risk danger olson <technoweenie@gmail.com>
Date:   Fri Dec 9 08:13:42 2016 -0700

    add mp3

commit a8f68840da7bf6eb5edef985807c153d00f05f5f
Author: risk danger olson <technoweenie@gmail.com>
Date:   Fri Dec 9 08:10:42 2016 -0700

    whatever 2

commit b8f6a911ec98aa987f8b885069e93db5faeadf62
Author: risk danger olson <technoweenie@gmail.com>
Date:   Fri Dec 9 08:10:35 2016 -0700

    whatever 1
```

At this point, `git rm --cached` won't work because the large mp3 file is not in my latest commit, but it is still in `a2e3ebd`. Another way to fix this is to reset the repository before the file was ever added. In my example, I could do this:

```sh
# create a new branch for backup purposes
$ git checkout -b master-backup
$ git checkout master

# reset to the 'whatever 2' commit
$ git reset a8f68840da7bf6eb5edef985807c153d00f05f5f

# add the file with git lfs
$ git lfs track "*.mp3"
$ git add "TF DJ SET SEPT 2013.mp3"
$ git commit -m "add mp3"
$ git push
```

**Comment by alejandrorbradford** [comment]
thanks for your help!

**Comment by technoweenie** [comment]
No sweat, re-open or file a new issue if you have more problems. Thanks for reporting too. I think there's an opportunity lurking here to introduce some git lfs tools to help visualize this, it can be pretty nasty when multiple unpushed commits are involved.
