### ISSUE TITLE
No system level 'uninstall' analogous to system level 'install'

### ISSUE THREAD

**Issue by kavehv** [git-lfs/git-lfs#1753]
You can run 
`git lfs install --system`

but

`git lfs uninstall --system`
yields
`Sorry, no usage text found for "uninstall"

Error: unknown flag: --system`

**Comment by ttaylorr** [comment]
👋 @kavehv, thanks for opening this. The `uninstall` command does remove the .gitconfig attributes from [both the system and global configuration sets][1], but I think we can improve in a few ways here:

1. Adding `--system` and `--global` options to the `git lfs uninstall` command for parity with the `git lfs install` command, and greater flexibility.
2. Documenting that behavior. It's not obvious that that's what's going on from just running the command (or [reading the docs][2]).

[1]: https://github.com/git-lfs/git-lfs/blob/bfabc5a6f89bd702377dba7978a89c959df1e74e/lfs/attribute.go#L105
[2]: https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-uninstall.1.ronn#L12

**Comment by kavehv** [comment]
It's also useful because typically one must sudo the `--system` versions of these commands.  `git lfs uninstall` won't let you know if it's unable to modify /etc/gitconfig, so it doesn't actually do what it's supposed to (if it's supposed to uninstall at the system level).
