### ISSUE TITLE
install.sh only works when current directory is switched to the same directory

### ISSUE THREAD

**Issue by jjgod** [git-lfs/git-lfs#1792]
https://github.com/git-lfs/git-lfs/blob/master/script/install.sh.example#L15

    $ /Users/jjgod/Downloads/git-lfs-1.5.3/install.sh 
    install: git*: No such file or directory

    $ cd /Users/jjgod/Downloads/git-lfs-1.5.3
    git-lfs-1.5.3$ ./install.sh 
    Git LFS initialized.

**Comment by jjgod** [comment]
diff --git a/script/install.sh.example b/script/install.sh.example
    index 2427311..ec1a632 100644
    --- a/script/install.sh.example
    +++ b/script/install.sh.example
    @@ -11,6 +11,7 @@ fi
     
     mkdir -p $prefix/bin
     
    +cd "$( dirname "${BASH_SOURCE[0]}" )"
     rm -rf $prefix/bin/git-lfs*
     for g in git*; do
       install $g "$prefix/bin/$g"

**Comment by technoweenie** [comment]
Thanks, nice suggestion! https://github.com/git-lfs/git-lfs/pull/1793
