### ISSUE TITLE
Update packages for Fedora 25

### ISSUE THREAD

**Issue by rothgar** [git-lfs/git-lfs#1795]
Trying to install git-lfs on fedora 25 and the repo that gets installed doesn't have any packages available. I switched the repo manually to use fedora 24 and git-lfs installed fine.

I'm not sure how package cloud updates packages for new OS releases but if it's a manual process maybe someone can rebuild the packages and make them available in the fedora 25 repo.

**Comment by ttaylorr** [comment]
Hi, @rothgar, thanks for opening this! I went ahead and updated our release scripts to make sure that all future builds get shipped to Fedora 25, as expected 😄 

I also built and released the last stable version of LFS to Fedora 25, so you should be able to download and use it today 👍
