### ISSUE TITLE
Cannot clone repo and push to new empty repo

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#1800]
One of my public repos cannot be cloned and pushed to an empty, new repo on github:
```
jonas@cyberman:~/Develop$ git clone https://gitlab.wobble.ninja/JonasT/ChiCraft ./chicraft.copy
Cloning into './chicraft.copy'...
remote: Counting objects: 2967, done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 2967 (delta 75), reused 0 (delta 0)
Receiving objects: 100% (2967/2967), 724.77 KiB | 564.00 KiB/s, done.
Resolving deltas: 100% (1862/1862), done.
Checking connectivity... done.
Downloading docs/font/Quicksand-Light.ttf (20.51 KB)
Downloading docs/font/Quicksand-Regular.ttf (23.27 KB)
Downloading misc/logo/blender/bg.blend (1.18 MB)
Downloading misc/logo/blender/bg.png (3.46 MB)
Downloading misc/logo/blender/bgsmall.jpg (52.28 KB)
Downloading misc/logo/blender/bgsmall.png (876.78 KB)
Downloading misc/logo/icon.ico (89.25 KB)
Downloading misc/logo/icon.xcf (125.29 KB)
Downloading misc/logo/jellyphoto_orig.jpg (519.08 KB)
Downloading misc/logo/logo.svg.png (64.94 KB)
Downloading misc/logo/logo.xcf (900.90 KB)
Downloading misc/logo/logo_base.xcf (2.26 MB)
Checking out files: 100% (75/75), done.
jonas@cyberman:~/Develop$ cd chicraft.copy/
jonas@cyberman:~/Develop/chicraft.copy$ git remote add github https://github.com/ChiCraft/ChiCraft
jonas@cyberman:~/Develop/chicraft.copy$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
jonas@cyberman:~/Develop/chicraft.copy$ git push github master
Trying to push "misc/logo/blender/bg.blend" with OID 91ba490a2e5e37aee61c7c02925bcfccd5260cb157e59963bb6d80dcfde5e696.
Not found in /home/jonas/Develop/chicraft.copy/.git/lfs/objects/91/ba.
error: failed to push some refs to 'https://github.com/ChiCraft/ChiCraft'
jonas@cyberman:~/Develop/chicraft.copy$
```
(You can try yourself with any new empty git repository somewhere else, with my public repo cloned as a source)

**Comment by ttaylorr** [comment]
Hi, @JonasT, thanks for opening this issue, and sorry to hear that you're having trouble! The error below is what I'm taking a look at:

> ```
> Trying to push "misc/logo/blender/bg.blend" with OID 91ba490...
> Not found in /home/jonas/Develop/chicraft.copy/.git/lfs/objects/91/ba.
> ```

This error means that you're missing an object with the above OID (`91ba`...) in your local copy of the repository. Once you have a complete copy of all LFS objects in your repository, you should be able to push successfully.

Try running `git lfs fetch --all`, to download all objects (and their complete histories) from all branches in your repository.

Once that's complete, you can do a `git lfs push --all <origin>` and you'll have a complete copy of your repository 👍 .

Please feel free to re-open this issue if you have any other questions!

**Comment by JonasT** [comment]
@ttaylorr  now I'm getting this error:

```
ca656c46214997aed06c43480958b8d2a3abeff8d684291f446c92a4ed1bf2a2 does not exist in .git/lfs/objects. Tried docs/font/Quicksand-Light.ttf, which matches ca656c46214997aed06c43480958b8d2a3abeff8d684291f446c92a4ed1bf2a2.
error: failed to push some refs to 'https://JonasT:61933799aa1722acae30ba788349c1fad1f6cb53@github.com/ChiCraft/ChiCraft.git'
```
.. when trying `git push target master`. The full sequence of things done by my script is:

```
git init .
git lfs install --skip-smudge
git remote
git remote add source https://gitlfsiauthenticatednotsupported:noneneeded@gitlab.wobble.ninja/JonasT/ChiCraft.git
git remote update
git remote
git remote add target https://JonasT:<RETRACTED>@github.com/ChiCraft/ChiCraft.git
git remote update
git fetch source
git checkout master
git-lfs fetch --all    # executed repeatedly until exit code 0, because git-lfs will
                       # always abort with a connection closed by peer at some point
                       # without retrying reasonably by itself
git push target master
```

**Comment by JonasT** [comment]
Reopening.

I also tried this again manually with `git fetch --all` from the original source, and then getting this:

```
[jonas@falcon chicraft]$ git push github master
Trying to push "misc/logo/icon.xcf" with OID a60ba7426d240859065a60d096c2eb15eb68c7e4e2cc56439d487c5510bcf4c1.
Not found in /home/jonas/Develop/chicraft/.git/lfs/objects/a6/0b.
error: failed to push some refs to 'https://github.com/ChiCraft/ChiCraft.git'
[jonas@falcon chicraft]$
```

It seems git-lfs really needs some reworking so that:

1. There is an *obvious* command for downloading everything that actually works (e.g. `git-lfs fetch --all` or another one, if that's not the one), and *which gives a big fat error* if just one file is missing or not on the server
2. If I do `git status` or just *anything* and there is 1 or more LFS files missing on the current branch, *there must be a warning message for each single missing LFS file*. Also not just the *first* problematic file as with those random git push errors I am seeing, but a complete list please.
4. `git-lfs fetch` should really behave better with downloads getting stuck or retrying after connection reset by peer. It gets stuck almost with every second larger download I do, and I need to equip my server script with timeouts, parsing for "connection reset by peer" errors and retries (the server has gigabit by the way and so has the source) just to get the download more or less reliably going.

Generally I have to say the overall reliability and error feedback is pretty disappointing right now :disappointed:

**Comment by JonasT** [comment]
Btw, I'm very interested in suggestions on how to fix the repo so that I can push it to other places again. (Independently from the underlying problem of reliability which I really think should be addressed in some way soon)

**Comment by technoweenie** [comment]
What does running `git-lfs fetch --all` show?

As for fixing the repo, you just need to find the lfs object `a60ba7426d240859065a60d096c2eb15eb68c7e4e2cc56439d487c5510bcf4c1` for that file. I'm not sure where that could have gone. If it was on github.com, send us a support request and we can dig it up.

If you can't get that, you'll need to run `git filter-branch` to remove that file from history.

**Comment by JonasT** [comment]
For some very weird reason, trying again right now it completed happily and I can push to where I want to. I have absolutely no idea why, this is the exact clone / working tree from which it failed from before.
Is this some super obscure bug with pruning old objects improperly or something like that? Maybe I also pushed from some other machine where the file was still present and unknowingly repaired it. (I didn't stop working on the project since this is an actual production repository)

Anyway, the file could also have been very easily been gone entirely due to https://gitlab.com/gitlab-org/gitlab-ce/issues/24564 so using git-lfs with gitlab seems to be quite a dangerous combination right now until that is addressed..

The file wouldn't have been super essential, but that git-lfs was so long quiet about it being missing was really unfortunate (combined with gitlab's bug) - I often delete and recreate my local repo copy both due to sometimes other minor git-lfs hiccups / misuses on my part which are sometimes fixed easiest that way, and of course the obvious "man I just made a merge I didn't want to make" recover delete & reclone which I suppose everyone using git sometimes does.
Better error checking (and also more frequent and not only on git push) in git-lfs would therefore be *highly appreciated* as far as I'm concerned! - assuming the file was even on the master branch, which I don't know, since the error message is somewhat spotty and unhelpful to the average user. (e.g. a complete list of other missing files would also be nice. Is there something like `git-lfs health check`? If there isn't, maybe it should be added. If there is, maybe it should be run automatically on each Nth git status??)

**Comment by JonasT** [comment]
Sorry for the reopen spam, I guess this specific instance is now actually solved. -> Closing

However, unless git-lfs steps up its error reporting and gitlab fixes accepting incomplete commits, this is bound to happen again at some point... (which is very bad in my opinion)
