### ISSUE TITLE
LFS downloads duplicate files

### ISSUE THREAD

**Issue by gregbillock** [git-lfs/git-lfs#1842]
Here's what I did:

I have two sets of large files on two machines. The files are the same.

1. Use LFS to create a PR adding the large files to LFS. 
2. Push the PR (which completes and all)
3. On the second machine, use GIT_LFS_SKIP_SMUDGE to do a git pull
4. Copy the identical files overtop of the pointer files
5. Run git lfs pull

What I expected is for git lfs pull to assess the local files, discover they are identical, and skip the download. Instead, it downloads the files anyway.

**Comment by technoweenie** [comment]
This isn't something we're interested in supporting. Try copying the `.git/lfs/objects` from the first repository over the second repository. That should achieve your desired effect.
