### ISSUE TITLE
Batch downloads for checkout?

### ISSUE THREAD

**Issue by jjgod** [git-lfs/git-lfs#1853]
For projects with a lot of files tracked by lfs, `git lfs clone` is much faster than `git clone`, thanks for that! But for checking out a different branch, is there a way to let git to switch branch without running the default smudge, then do all the lfs checkout in one `git lfs checkout` operation?

**Comment by technoweenie** [comment]
Yes, you can run `git lfs install --skip-smudge`, which changes your git config from:

```sh
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
```

To:

```sh
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
```

However, you should be running `git lfs pull` to download the LFS objects, and check them out in a single command.  That's essentially what `git lfs clone` is doing. 

Also, work has just started on an update to the new git filter process that would make all this obsolete. Here's the original idea: https://github.com/git-lfs/git-lfs/pull/1646. This is likely a ways off, but hopefully we won't need this `--skip-smudge` change forever :)

**Comment by jjgod** [comment]
Thanks, I will keep this as a workaround and look forward to the promised downloads change!

**Comment by mattack1** [comment]
I totally don't understand that.  I barely get git itself..  I'm trying to do as minimal different from 'regular' git usage as normal..

so e.g. I use git clone to first get a project..
and then I use git checkout branch
to switch branches..

and git pull to update the current branch..

This request is/was asking for a way to do the "git checkout branch" part in an lfs fast way..

how do we switch a current directory to a different branch on an lfs project in a "quick" way (like git lfs clone)

**Comment by ttaylorr** [comment]
> how do we switch a current directory to a different branch on an lfs project
> in a "quick" way (like git lfs clone)

Git checkouts where all LFS objects are available in your local cache
(`.git/lfs/objects`) are fast as of Git v2.11 with the introduction of the
`process` filter. In other words, if you have Git v2.11.0 or better, `git
checkout <branch>` will be fast.

If you don't have Git v2.11.0 yet, you can use the wrapped command: `git lfs
checkout` which has the same semantics.

**Comment by jjgod** [comment]
This one is mostly about the uncached ones, so I guess the `process` filter doesn't help that.

**Comment by mattack1** [comment]
Thanks.  I'll check the other one mentioned above to "make this all obsolete".  But it sounds like I really want a way to automagically make all of my "git whatever" commands be "git lfs whatever" commands, behind my back.
