### ISSUE TITLE
lfs prune hangs on old commits

### ISSUE THREAD

**Issue by monitorjbl** [git-lfs/git-lfs#1860]
When running `git lfs prune --dry-run` on a repo with commits old enough to exceed the default `lfs.pruneoffsetdays` setting, the command hangs forever. After running `GIT_TRACE git lfs prun --dry-run`, I can see that the last command run by git-lfs is this:

```
git for-each-ref --sort=-committerdate --format=%(refname) %(objectname) %(committerdate:iso) refs
```

Doing a `ps aux | grep git` shows this as well:

```
[tayjones@TAYJONES-M-X2P9:/Users/tayjones]$ ps aux | grep git
tayjones         36376   0.1  0.1 556628824   9364 s003  S+    9:28AM   0:00.10 git-lfs prune --dry-run
tayjones         36389   0.0  0.0  2434840    796 s008  S+    9:28AM   0:00.00 grep git
tayjones         36384   0.0  0.0  2508100   2500 s003  S+    9:28AM   0:00.02 git for-each-ref --sort=-committerdate --format=%(refname) %(objectname) %(committerdate:iso) refs
tayjones         36375   0.0  0.0  2436796   1036 s003  S+    9:28AM   0:00.00 git lfs prune --dry-run
```

I noticed that the `git for-each-ref` command still has stdout open:

```
[tayjones@TAYJONES-M-X2P9:/Users/tayjones]$ lsof -p 36384
COMMAND   PID     USER   FD   TYPE             DEVICE  SIZE/OFF     NODE NAME
git     36384 tayjones  cwd    DIR                1,4       612 33887097 /private/tmp/comp-11000429
git     36384 tayjones  txt    REG                1,4   1877284 27791096 /usr/local/Cellar/git/2.10.1/bin/git
git     36384 tayjones  txt    REG                1,4     98064 33887145 /private/tmp/comp-11000429/.git/objects/pack/pack-6c003df035337371ad9f80b87baf41470a81ced5.idx
git     36384 tayjones  txt    REG                1,4   6321866 33887143 /private/tmp/comp-11000429/.git/objects/pack/pack-6c003df035337371ad9f80b87baf41470a81ced5.pack
git     36384 tayjones  txt    REG                1,4    646624 27407494 /usr/lib/dyld
git     36384 tayjones  txt    REG                1,4 558300650 27414567 /private/var/db/dyld/dyld_shared_cache_x86_64h
git     36384 tayjones    0r   CHR                3,2       0t0      302 /dev/null
git     36384 tayjones    1   PIPE 0x29a6ea35c0555d71     65536          ->0x29a6ea35a897ec71
git     36384 tayjones    2w   CHR                3,2       0t0      302 /dev/null
``` 

After a bit of debugging the Go code for this command, I found that the issue lies on the [defer statement](https://github.com/git-lfs/git-lfs/blob/v1.5.5/git/git.go#L449). The command completes, and the function gets to the return statement but the call to `Cmd.Wait()` is where its actually hanging.

**Comment by monitorjbl** [comment]
I found that the reason for this hang is because the [stdout Pipe](https://github.com/git-lfs/git-lfs/blob/v1.5.5/git/git.go#L444) is not empty when the function returns. This is due to the fact that the scanner [does not fully read the Pipe](https://github.com/git-lfs/git-lfs/blob/v1.5.5/git/git.go#L483) before breaking the loop.

The solution that I found for this was to simply add an extra line to the [defer statement](https://github.com/git-lfs/git-lfs/blob/v1.5.5/git/git.go#L449) that ensures the Pipe closes:

```go
	defer func(){
		outp.Close()
		cmd.Wait()
	}()
```

I opened #1861 with this fix included.

**Comment by monitorjbl** [comment]
After writing the integration test for this fix, it looks like the root cause is that the stdout pipe isn't exhausted if the number of refs is very large. Since the code reads data through `bufio.Scanner` is buffered by some amount, the pipe is typically exhausted for most repos. However, if you have more than 900 refs in your repo, the amount of output from `git for-each-ref` is large enough that not all of it gets buffered.

I wonder if this kind of issue is possibly the root cause of some of the other various hanging issues that folks have reported. There are [several](https://github.com/git-lfs/git-lfs/blob/master/git/git.go#L227) [instances](https://github.com/git-lfs/git-lfs/blob/master/git/git.go#L182) [of](https://github.com/git-lfs/git-lfs/blob/master/git/git.go#L934) [commands](https://github.com/git-lfs/git-lfs/blob/master/git/git.go#L1040) just using `Cmd.Wait()` and not closing the associated pipe scattered around the codebase.

**Comment by technoweenie** [comment]
Great work tracking this down. I agree with your assessment, and will make sure we look into this before the next LFS release.

**Comment by technoweenie** [comment]
Tracking this in https://github.com/git-lfs/git-lfs/issues/1874 now.
