### ISSUE TITLE
Git push is stuck while pushing large files

### ISSUE THREAD

**Issue by bhaprayan** [git-lfs/git-lfs#1864]
I encountered an issue today while using git lfs to push a large file to the server. The upload got stuck in between e.g.
Git LFS: (99 of 172 files) 211.59 MB / 288.18 MB 

It was stuck for around 20 minutes or so, then I pressed enter multiple times to refresh the output. Apparently it was prompting for a username (was not visible in output log, flashed briefly for a fraction of a second), so I entered it, and the password as well.
It started uploading again (however I had to redo the same procedure, multiple times throughout the upload period (uploading around 400 MB of data).

**Comment by technoweenie** [comment]
Thanks for the report. It looks like the prompt from git is interfering with the Git LFS output. A simple workaround on your end is to setup a better credential helper that remembers passwords long term. This is something I want to look at for the next Git LFS release though.

**Comment by bhaprayan** [comment]
Great! Sounds good. That's the workaround that I've implemented for now. I could attempt to fix this. Are there any pointers that you have on where to look for the bug?
