### ISSUE TITLE
Errors downloading object:

### ISSUE THREAD

**Issue by amaredeus** [git-lfs/git-lfs#1865]
I'm having issues using git-lfs on Win10 with powersehll/cmd. When I try cloning a test repository by ssh I get the errors below. I don't get any errors when I try the same in the Git Bash shell. I tried again on Ubuntu and again nothing went wrong. Is there something I can do to make this work on Win10?

```
P:\Users\Brian\Projects>git clone git@github.com:amaredeus/test
Cloning into 'test'...
Enter passphrase for key '/c/Users/Brian/.ssh/id_rsa':
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), 18.24 MiB | 7.43 MiB/s, done.
Downloading preview.mp4 (19.22 MB)
Error downloading object: preview.mp4 (7688a88b1ddcf8e3a181f22b38aebc4f060cb38d3ad55b2b8290cc8a37919389)

Errors logged to P:\Users\Brian\Projects\test\.git\lfs\objects\logs\20170114T001412.8566763.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: preview.mp4: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```
```
git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)
git version 2.11.0.windows.2

$ git-lfs.exe filter-process
Error downloading object: preview.mp4 (7688a88b1ddcf8e3a181f22b38aebc4f060cb38d3ad55b2b8290cc8a37919389)

Smudge error: Error downloading 7688a88b1ddcf8e3a181f22b38aebc4f060cb38d3ad55b2b8290cc8a37919389: batch request: exit status 255: Permission denied (publickey).: batch request: exit status 255: Permission denied (publickey).
github.com/git-lfs/git-lfs/errors.newWrappedError
        C:/Go/src/github.com/git-lfs/git-lfs/errors/types.go:166
github.com/git-lfs/git-lfs/errors.NewSmudgeError
        C:/Go/src/github.com/git-lfs/git-lfs/errors/types.go:252
github.com/git-lfs/git-lfs/lfs.PointerSmudge
        C:/Go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
        C:/Go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:65
github.com/git-lfs/git-lfs/commands.smudge
        C:/Go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:84
github.com/git-lfs/git-lfs/commands.filterCommand
        C:/Go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:65
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
        C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
        C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
        C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:66
main.main
        C:/Go/src/github.com/git-lfs/git-lfs/git-lfs.go:33
runtime.main
        C:/Go/src/runtime/proc.go:183
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=P:\Users\Brian\Projects\test
LocalGitDir=P:\Users\Brian\Projects\test\.git
LocalGitStorageDir=P:\Users\Brian\Projects\test\.git
LocalMediaDir=P:\Users\Brian\Projects\test\.git\lfs\objects
LocalReferenceDir=
TempDir=P:\Users\Brian\Projects\test\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_PREFIX=
```

**Comment by conanne** [comment]
salut ami je bousoin un logiciel ru pour activer mon iphone 6 aider moi
slvpl ami jatond votre riponse

2017-01-14 6:33 GMT+01:00 Brian Patino <notifications@github.com>:

**Comment by ttaylorr** [comment]
Hi @amaredeus, thanks for opening this and sorry that you're having troubles! I tried this on both my macOS installation and my Windows 10 VM, and was unable to reproduce the issue:

```
ttaylorr@DESKTOP-T47OGNH MINGW64 ~/Desktop
$ git lfs version
git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)

ttaylorr@DESKTOP-T47OGNH MINGW64 ~/Desktop
$ git clone https://github.com/amaredeus/test.git
Cloning into 'test'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Downloading preview.mp4 (19.22 MB)

ttaylorr@DESKTOP-T47OGNH MINGW64 ~/Desktop
$ cat ./test/preview.mp4 | wc -c
20154342
```

Looking at where the error is coming from in LFS, it means that either LFS was unable to download the file, or it was unable to read the file. We should improve that error for v2.0.0.

**Comment by technoweenie** [comment]
> batch request: exit status 255: Permission denied (publickey).: batch request: exit status 255: Permission denied (publickey).

This is an SSH issue, unrelated to Git LFS. Can you try running the following?

```sh
$ ssh git@github.com git-lfs-authenticate amaredeus/test download
```

Since you're on Windows, how is SSH configured? Are you using Putty or something else?

**Comment by JarrettR** [comment]
Same problem reproduced on another repo.

Version (installed from AMD64 rar file on website):
```
> git lfs version
git-lfs/2.0.1 (GitHub; windows amd64; go 1.8; git 678cdbd4)
```

Output: 
```
> git clone --depth=1 http
s://github.com/issus/altium-library.git
Cloning into 'altium-library'...
remote: Counting objects: 738, done.
remote: Compressing objects: 100% (261/261), done.
remote: Total 738 (delta 531), reused 642 (delta 475), pack-reused 0
Receiving objects: 100% (738/738), 139.31 MiB | 466.00 KiB/s, done.

Resolving deltas: 100% (531/531), done.
Downloading DB/Components.sql (278.23 MB)
Error downloading object: DB/Components.sql (e52cd31521369720d490bdd89ea7c631a0d
94ded95c5bf9e0478c277a17b2183)

Errors logged to C:\Users\jrainier\Documents\what\git\PCBs\Altium\altium-library
\.git\lfs\objects\logs\20170322T140645.9099675.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: DB/Components.sql: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

The contents of the log are:
```
git-lfs/2.0.1 (GitHub; windows amd64; go 1.8; git 678cdbd4)
git version 2.11.0.windows.3

$ git-lfs.exe filter-process
Error downloading object: DB/Components.sql (e52cd31521369720d490bdd89ea7c631a0d94ded95c5bf9e0478c277a17b2183)

Smudge error: Error downloading DB/Components.sql (e52cd31521369720d490bdd89ea7c631a0d94ded95c5bf9e0478c277a17b2183): batch response: This repository is over its data quota. Purchase more data packs to restore access.
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:166
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:252
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:68
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:63
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:65
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197

ENV:
LocalWorkingDir=C:\Users\jrainier\Documents\what\git\PCBs\Altium\altium-library
LocalGitDir=C:\Users\jrainier\Documents\what\git\PCBs\Altium\altium-library\.git
LocalGitStorageDir=C:\Users\jrainier\Documents\what\git\PCBs\Altium\altium-library\.git
LocalMediaDir=C:\Users\jrainier\Documents\what\git\PCBs\Altium\altium-library\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\jrainier\Documents\what\git\PCBs\Altium\altium-library\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
```

Seems strange that it's referencing @ttaylorr's home directory, but I don't know how Go works.
Also, I'm not sure if it's within the scope of this project to care, but the log file is Lunix-formatted, so displays on one line in Notepad, which is non-standard behaviour.


Regards,
Jarrett

**Comment by ttaylorr** [comment]
Hi @JarrettR. The problem appears to be that your repository is over its allotted data quota on GitHub.com. 

> Smudge error: Error downloading DB/Components.sql (e52cd31521369720d490bdd89ea7c631a0d94ded95c5bf9e0478c277a17b2183): batch response: This repository is over its data quota. Purchase more data packs to restore access.

You can learn more about our pricing packages here: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/.

> Seems strange that it's referencing @ttaylorr's home directory, but I don't know how Go works.

That's an artifact of me building LFS release binaries on my laptop 😄 .

**Comment by JarrettR** [comment]
Ah, of course, I have to scroll right to see that portion :)

Ignore my post here, and I've created issue #2076 to capture where my confusion comes from and how to clarify for future users.

**Comment by ShubhamThkr** [comment]
[20220119T175147.8831886.log](https://github.com/git-lfs/git-lfs/files/7897242/20220119T175147.8831886.log)


> I'm having issues using git-lfs on Win10 with powersehll/cmd. When I try cloning a test repository by ssh I get the errors below. I don't get any errors when I try the same in the Git Bash shell. I tried again on Ubuntu and again nothing went wrong. Is there something I can do to make this work on Win10?
> 
> ```
> P:\Users\Brian\Projects>git clone git@github.com:amaredeus/test
> Cloning into 'test'...
> Enter passphrase for key '/c/Users/Brian/.ssh/id_rsa':
> remote: Counting objects: 12, done.
> remote: Compressing objects: 100% (9/9), done.
> remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
> Receiving objects: 100% (12/12), 18.24 MiB | 7.43 MiB/s, done.
> Downloading preview.mp4 (19.22 MB)
> Error downloading object: preview.mp4 (7688a88b1ddcf8e3a181f22b38aebc4f060cb38d3ad55b2b8290cc8a37919389)
> 
> Errors logged to P:\Users\Brian\Projects\test\.git\lfs\objects\logs\20170114T001412.8566763.log
> Use `git lfs logs last` to view the log.
> error: external filter 'git-lfs filter-process' failed
> fatal: preview.mp4: smudge filter lfs failed
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'
> ```
> 
> ```
> git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)
> git version 2.11.0.windows.2
> 
> $ git-lfs.exe filter-process
> Error downloading object: preview.mp4 (7688a88b1ddcf8e3a181f22b38aebc4f060cb38d3ad55b2b8290cc8a37919389)
> 
> Smudge error: Error downloading 7688a88b1ddcf8e3a181f22b38aebc4f060cb38d3ad55b2b8290cc8a37919389: batch request: exit status 255: Permission denied (publickey).: batch request: exit status 255: Permission denied (publickey).
> github.com/git-lfs/git-lfs/errors.newWrappedError
>         C:/Go/src/github.com/git-lfs/git-lfs/errors/types.go:166
> github.com/git-lfs/git-lfs/errors.NewSmudgeError
>         C:/Go/src/github.com/git-lfs/git-lfs/errors/types.go:252
> github.com/git-lfs/git-lfs/lfs.PointerSmudge
>         C:/Go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
> github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
>         C:/Go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:65
> github.com/git-lfs/git-lfs/commands.smudge
>         C:/Go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:84
> github.com/git-lfs/git-lfs/commands.filterCommand
>         C:/Go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:65
> github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
>         C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
> github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
>         C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
> github.com/git-lfs/git-lfs/commands.Run
>         C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:66
> main.main
>         C:/Go/src/github.com/git-lfs/git-lfs/git-lfs.go:33
> runtime.main
>         C:/Go/src/runtime/proc.go:183
> runtime.goexit
>         C:/Go/src/runtime/asm_amd64.s:2086
> 
> ENV:
> LocalWorkingDir=P:\Users\Brian\Projects\test
> LocalGitDir=P:\Users\Brian\Projects\test\.git
> LocalGitStorageDir=P:\Users\Brian\Projects\test\.git
> LocalMediaDir=P:\Users\Brian\Projects\test\.git\lfs\objects
> LocalReferenceDir=
> TempDir=P:\Users\Brian\Projects\test\.git\lfs\tmp
> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> BatchTransfer=true
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic
> UploadTransfers=basic
> GIT_DIR=.git
> GIT_LFS_PATH=C:\Program Files\Git LFS
> GIT_PREFIX=
> ```

Can anyone provide the solution to this issue? As part of my project, is cloned in Jenkins while the rest can't be downloaded because of the errors. I have attached the log file of Jenkins.

**Comment by bk2204** [comment]
Hey,

Could you open a new issue and fill out the issue template as requested in the CONTRIBUTING documentation?  The version of Git and Git LFS you're quoting is about six years old and a lot has changed, and we'd want to see the logs and the relevant information about your platform and environment to provide a good answer.

**Comment by ShubhamThkr** [comment]
> Hey,
> 
> Could you open a new issue and fill out the issue template as requested in the CONTRIBUTING documentation? The version of Git and Git LFS you're quoting is about six years old and a lot has changed, and we'd want to see the logs and the relevant information about your platform and environment to provide a good answer.

Thanks for the reply...
But, I resolved this issue. It was on Jenkins's side. Since the log was not descriptive it took a lot of time to discover it.

**Comment by benjamin-king13** [comment]
@ShubhamThkr I think we might be having a similar issue with our Jenkins build, any info on what you had to do there to get past this?
