### ISSUE TITLE
Unexpected server error when trying to pull objects.

### ISSUE THREAD

**Issue by kylezhaoxc** [git-lfs/git-lfs#1866]
My project is hosted in visual studio online, and we have been working with git lfs for a long time since the project started, and it always worked well, until last week no member in our team was able to pull objects from the server , either by "git lfs pull " or by "git lfs fetch"

Here is the error info : 

batch response: Fatal error: Server error: repourl/DefaultCollection/_git/ProjectName.git/info/lfs/objects/batch

And this is the git lfs logs last:
git-lfs/1.4.4 (GitHub; darwin amd64; go 1.7.3)
git version 2.10.1

$ git-lfs fetch
Fetching master
batch response: Fatal error: Server error: repourl/DefaultCollection/_git/ProjectName.git/info/lfs/objects/batch

batch response: Fatal error: Server error: repourl/DefaultCollection/_git/ProjectName.git/info/lfs/objects/batch
github.com/github/git-lfs/errors.newWrappedError
	/private/tmp/git-lfs-20161024-90801-1qwlrek/git-lfs-1.4.4/src/github.com/github/git-lfs/errors/types.go:166
github.com/github/git-lfs/errors.Wrap
	/private/tmp/git-lfs-20161024-90801-1qwlrek/git-lfs-1.4.4/src/github.com/github/git-lfs/errors/errors.go:73
github.com/github/git-lfs/api.Batch
	/private/tmp/git-lfs-20161024-90801-1qwlrek/git-lfs-1.4.4/src/github.com/github/git-lfs/api/api.go:105
github.com/github/git-lfs/lfs.(*TransferQueue).batchApiRoutine
	/private/tmp/git-lfs-20161024-90801-1qwlrek/git-lfs-1.4.4/src/github.com/github/git-lfs/lfs/transfer_queue.go:426
runtime.goexit
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=<my local dir>
LocalGitDir=<my local dir>/.git
LocalGitStorageDir=<my local dir>/.git
LocalMediaDir=<my local dir>/.git/lfs/objects
LocalReferenceDir=
TempDir=<my local dir>/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic

**Comment by technoweenie** [comment]
> batch response: Fatal error: Server error: repourl/DefaultCollection/_git/ProjectName.git/info/lfs/objects/batch

That looks like an error from your server, and not the Git LFS client. I saw in another issue last week that VSO sometimes returns plaintext errors, which the git-lfs client can't interpret. Try running `GIT_CURL_VERBOSE=1 git-lfs fetch` to see the actual error from VSO. Be sure to scrub any `Authorization:` header values in that output.

**Comment by kylezhaoxc** [comment]
Thanks @technoweenie  for responding. I have tried the command and below is what I got. 

We are using multi-factor logging in git , so Authorization block might not contain useful info, though I did notice a "ProjectDoesNotExistWithNameException"



kyle-mbp: kylezhao$ GIT_CURL_VERBOSE=1 git-lfs fetch
Fetching master

> POST /DefaultCollection/_git/PROJECTNAME.git/info/lfs/objects/batch HTTP/1.1

> Host: TFSHOST

> Accept: application/vnd.git-lfs+json; charset=utf-8

> Authorization: Basic * * * * *

> Content-Length: 1106

> Content-Type: application/vnd.git-lfs+json; charset=utf-8

> User-Agent: git-lfs/1.4.4 (GitHub; darwin amd64; go 1.7.3)

> \
{"operation":"download","objects":[\{"oid":"bcde8ba7295718245ee326110d9c2629587d1ce60324ffaa9baea31e7c0180d7","size":786446\},{"oid":"7ea9a3255eb389c2b9df6b94fc52a03e4c7f4259acbe1586ecbbd7856d0dc09d","size":24360037\},{"oid":"11e4de61cd787c4b88d41fd2b8d2baf708de34fd490d04dc5c8ef0097a8cda17","size":222697243\},{"oid":"9b94131f134f45a6d78a18d168e6aa8dbd3b33d778a635f2ad0afe6f4082157e","size":75617980\},{"oid":"3607141d018303f2ccb967e2ded64f4c92b7aa59dd732288a95ce9795134f152","size":3648512\},{"oid":"e38a677c56ddad54e03ca12e803d8dd4ada80c4f886bfc65e02ae2a2f805e000","size":17544\},{"oid":"c1c17cf98afd16b99fd5c0aa5a00593695b1c0e47097600b096a0a077a2614f4","size":34095\},{"oid":"1f7cb0b66366a58ad2cc3e20b861d132c3e5f9fdd38a62b06253f28c51d87719","size":741\},{"oid":"a04aebc9f6314aab00d72377274fcf70e7ec62056b6b03e7372e7b9574fbe58d","size":32279\},{"oid":"9953c183243cd215d6554a3a958785a997a7fa3d7f9467c75cc7c8c19b7e51da","size":38347\},{"oid":"e28ebaa735d8c256b00a1788843e86b8b3e1da5a9e6b2397216f9ddeedbe08b1","size":68510\},{"oid":"2c0eac7148b0b874c578d5322f7a672312d0f4d77870b54a6d0560b94447f9ed","size":25571272\}]\}\
\


< HTTP/1.1 500 Internal Server Error\

< Content-Length: 179\

< Cache-Control: private\

< Content-Type: text/plain; charset=utf-8\

< Date: Wed, 18 Jan 2017 05:50:30 GMT\

< P3p: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"\

< Server: Microsoft-IIS/10.0\

< Strict-Transport-Security: max-age=31536000; includeSubDomains\

< X-Aspnet-Version: 4.0.30319\

< X-Content-Type-Options: nosniff\

< X-Frame-Options: SAMEORIGIN\

< X-Powered-By: ASP.NET\

< X-Tfs-Exception: ProjectDoesNotExistWithNameException\

< X-Tfs-Processid: a07f1a79-3124-45d6-bce1-98610eef0b44\

< X-Vss-Userdata: 65c1d159-bccb-435a-ad4e-713c0538a980:myemail@fake.com\

< 

TF200016: The following project does not exist: PROJECTNAME.git. Verify that the name of the project is correct and that the project exists on the specified Team
Git LFS: (0 of 12 files) 0 B / 336.53 MB                                   
\
batch response: Fatal error: Server error: https://ServerURL/DefaultCollection/_git/RROJECTNAME.git/info/lfs/objects/batch\
\
Errors logged to LOCALDIR/.git/lfs/objects/logs/20170118T135030.370385931.log\

Use `git lfs logs last` to view the log.\

Warning: errors occurred}

**Comment by derrickstolee** [comment]
This is a known issue on VSTS that will be fixed in our hotfix tomorrow. For now, you can work around the issue by changing your remote url:

`git remote set-url origin https://account.visualstudio.com/RepoName/_git/RepoName`

Sorry for the problems!

**Comment by kylezhaoxc** [comment]
Thank you very much @derrickstolee for the work around , it perfectly resolved my issue.

**Comment by derrickstolee** [comment]
For the record: the server bug on VSTS is fixed and this will no longer be an issue for any users.
