### ISSUE TITLE
GIT LFS hangs forever

### ISSUE THREAD

**Issue by neslekkim** [git-lfs/git-lfs#1871]
Not possible to checkout files on our teamcity (windows) server, teamcity have this log:

```
Failed to perform checkout on agent: '"C:\Program Files\Git\bin\git.exe" -c core.askpass=C:\TeamCity\buildAgent\temp\buildTmp\pass7085098079506218856.bat -c credential.helper= -c credential.helper=C:\TeamCity\buildAgent\temp\buildTmp\credHelper6140378093301666134.bat reset --hard 77b35829f1a87b13da9afec3eb9835cb2e9d664e' command failed.
exit code: -1
exception: jetbrains.buildServer.ProcessTimeoutException: Timeout exception: the process did not produce output longer than 3600 seconds; Process: "C:\Program Files\Git\bin\git.exe" -c core.askpass=C:\TeamCity\buildAgent\temp\buildTmp\pass7085098079506218856.bat -c credential.helper= -c credential.helper=C:\TeamCity\buildAgent\temp\buildTmp\credHelper6140378093301666134.bat reset --hard 77b35829f1a87b13da9afec3eb9835cb2e9d664e
```

When checking taskmanager it seems that git-lfs is just waiting, after all my tests it seems like git-lfs cannot get the credentials?

**Comment by technoweenie** [comment]
That seems to be an issue with your credential helper, and not LFS. This seems to come from running `git reset --hard` as part of some checkout process. Git LFS does not ever run `git reset`.

**Comment by neslekkim** [comment]
That one is from teamcity, not sure if it does hard reset, but anyway, teamcity is feeding git.exe with the credentials through those two bat files, there is no interactivity on an buildserver, so git-lfs should get the credentials from git, right?

**Comment by neslekkim** [comment]
would be nice if one could enable full logging of what is going on, the puny logs that I have found doesn't have any information other than environmentsettings etc.

**Comment by technoweenie** [comment]
You can get more details with these Git environment flags (they'll work for git and git lfs):

* `GIT_TERMINAL_PROMPT=0` will disable prompting for credentials. Not sure if this will work with the `core.askpass` git config value that is set though.
* `GIT_TRACE=1` will dump internal tracing info from git and git lfs.
* `GIT_CURL_VERBOSE=1` will dump raw http requests and responses made by git and git lfs. Note: This may leak the `Authorization:` header from Git. Git LFS obscures it by default.

**Comment by ttaylorr** [comment]
Hi @neslekkim, I am going to close this issue for now, since it's been a little over a year without any activity. If this issue is persistent under the latest Git and Git LFS, please let me know here and I'd be happy to figure out what's going on.
