### ISSUE TITLE
Bring git-lfs to the source repository

### ISSUE THREAD

**Issue by teolaz** [git-lfs/git-lfs#1873]
Hi guys,
i followed your tutorial to move assets from 3 sites to git-lfs i'm managing and they're all online.
Problem is, your tutorial here https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs show only how to create a new remote repository and rebuild the entire history.
If in my projects i try to
`rm .git`
`git init`
`git add -A .`
`git commit -m "new repo created"` (this is only to recreate master branch)
`git remote add git@blablabla` (bitbucket)
`git pull`
tons of merge unsolved conflicts are shown....

Is it possible to work in the same project without having to checkout from the new repo created?

**Comment by technoweenie** [comment]
If you have an existing project, and don't need to convert all objects in the history of your repository to use LFS, you can just start with a `git lfs track "*.foo"` command and start using LFS. It will convert the current versions of the matching files to LFS, but will leave older objects alone.

**Comment by ttaylorr** [comment]
As @-technoweenie points out, you can use `git lfs track` in your existing repository to avoid migrating existing data. You can use `git lfs migrate` to migrate existing history. Please let me know if you have any issues with either of these commands and I'd be more than happy to help out!
