### ISSUE TITLE
common object store

### ISSUE THREAD

**Issue by eminence** [git-lfs/git-lfs#1875]
I've got several related repositories that will share a large number of large files.  Instead of having them duplicated in both `/repoA/.git/lfs/objects` and `/repoB/.git/lfs/objects`, can these be shared somehow?

**Comment by ttaylorr** [comment]
You can force LFS to use a different LFS server than the Git remote by running:

```sh
$ git config lfs.url <URL>
```

More information about how servers are discovered is in: https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md.

**Comment by eminence** [comment]
I'm sorry, but can you please clarify something.  My understanding was that the `lfs.url` configuration parameter is used to tell git-lfs where to find the remote LFS server.    But what I'm looking for is a way to customized where local objects are stored/cached on my local machine.

**Comment by ttaylorr** [comment]
My misunderstanding, the `lfs.url` config value does exactly what you described. I thought you were wondering how to use the same endpoint to store objects on the server, not locally.

In terms of storing the objects in the same place locally, LFS has some support for this through Git's `alternates` mechanism.

If you have repository A and B, and touch the file `.git/objects/info/alternates` with a single line pointing to a third directory, LFS should store the objects from both repositories in the same place.
