### ISSUE TITLE
git checkout hangs indefinitely at "Read filter-process request" on macOS

### ISSUE THREAD

**Issue by andrewrech** [git-lfs/git-lfs#1880]
When I attempt to checkout a branch in a repository migrated to LFS, `git checkout <mybranch>` hangs indefinitely at 0 CPU usage on macOS. I am able to checkout branches in the same repository instantly on Linux.

`git version`
> git version 2.11.0

`git-lfs version`
> git-lfs/1.5.5 (GitHub; darwin amd64; go 1.7.4)

`GIT_TRACE=1 git checkout another_branch`

> 11:19:58.175795 git.c:371               trace: built-in: git 'checkout' 'another_branch'
> 11:19:58.188330 run-command.c:350       trace: run_command: 'git-lfs filter-process'
> 11:19:58.188864 run-command.c:209       trace: exec: '/bin/sh' '-c' 'git-lfs filter-process' 'git-lfs filter-process'
> trace git-lfs: run_command: 'git' version
> trace git-lfs: run_command: 'git' config -l
> trace git-lfs: Initialize filter-process
> trace git-lfs: Read filter-process request.
> trace git-lfs: Read filter-process request.
> HANGS FOREVER

`git lfs env`

> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> BatchTransfer=true
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic
> UploadTransfers=basic
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"

I can post with `GIT_TRACE_PACKET=1` if it is helpful. `GIT_CURL_VERBOSE=1` did not yield anything.

Thank you!

**Comment by technoweenie** [comment]
Reposting with `GIT_TRACE_PACKET=1` would be a big help. If it contains anything too sensitive for an OSS issue, you can send it to https://github.com/contact, and we can discuss there.

**Comment by andrewrech** [comment]
Output from GIT_TRACE_PACKET is emailed. Thanks.

**Comment by xerootg** [comment]
I believe I am having the same issue on Windows. Anything I can provide in order to help out?

**Comment by technoweenie** [comment]
@xerootg Same thing :)

> Reposting with GIT_TRACE_PACKET=1 would be a big help. If it contains anything too sensitive for an OSS issue, you can send it to https://github.com/contact, and we can discuss there.

@andrewrech Based on your extensive logs, this doesn't necessarily look like a Git LFS bug. But, we're still going through it.

You can disable the new filter process stuff if you're blocked and want to get back to work:

    $ git config --global --unset filter.lfs.process

**Comment by qeomash** [comment]
I have also encountered this on Windows, git version 2.11.0.windows.3 and git-lfs 1.5.5. Downgrading to git version 2.10.0 corrected the problem.

**Comment by larsxschneider** [comment]
@andrewrech I think I ran into the same issue and I added a test case here: https://github.com/git-lfs/git-lfs/pull/1922

You can fix the issue with the current Git LFS version by fixing the malformed pointers. Please let me know if you want me to write up a quick tutorial.

**Comment by andrewrech** [comment]
Thanks for the offer @larsxschneider, I appreciate it. This is fixed for me with `v1.5.6`; thank you Taylor and others!

**Comment by dustinfreeman** [comment]
Hmmm, I am also hanging forever with `trace git-lfs: Read filter-process request.` even after a git lfs upgrade 1.5.5 -> 2.0.2

**Comment by ttaylorr** [comment]
@dustinfreeman thanks for updating. I fixed a bug that can potentially cause a hang in #1932 which was released in v2.0.0.

**Comment by yrazin** [comment]
I'm having this same issue using git 2.15.0.windows.1 and git-lfs 2.3.4

**Comment by bk2204** [comment]
@yrazin Could you open a new issue for this after testing with the latest version? It's possible that we've fixed the hang in 2.3.4 in a newer version, and I think if there is a hang it's separate from the one fixed in 2.0.0.
