### ISSUE TITLE
Github Desktop LFS issue

### ISSUE THREAD

**Issue by hf2186** [git-lfs/git-lfs#1888]
Openning any repo with LFS gives me the following error:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: gitLFSInfo != nil'
terminating with uncaught exception of type NSException
abort() called

**Comment by technoweenie** [comment]
Can you send that to https://github.com/contact, along with relevant GitHub Desktop version info? That error is coming from Desktop, and not git-lfs.
