### ISSUE TITLE
wrong git-lfs-windows-amd64-1.5.5.zip sha256

### ISSUE THREAD

**Issue by dfroger** [git-lfs/git-lfs#1892]
https://github.com/git-lfs/git-lfs/releases/tag/v1.5.5 says:

```
git-lfs-windows-amd64-1.5.5.zip
33c0facff41052ecb5cdcf9e42f7bb8300e95162b788820f91ea39bb3a669b6a
```

but sha256 is 7c23635f34b0b4eed55621231148ef3e0de9a46e2d629b4bba7f706a96ae77ea

**Comment by technoweenie** [comment]
Doh, thanks for the report. I think the old sha is from the zips before the exes were digitally signed. I've updated the releases page. I've confirmed that the files weren't tampered with.

We definitely need to be more careful in the future though. The Windows build process has a lot of manual steps, that need to be automated.

**Comment by ttaylorr** [comment]
@dfroger, thanks for opening this and @technoweenie, thanks for making sure that everything was 🆗 .

I think I did forget to re-SHA the signed builds, as adding signing metadata on Windows does change the contents of the files on disk.

Going to close this for now and move discussion to #1592, which will address these concerns.

**Comment by dfroger** [comment]
Thanks for fixing this so fast 👍
