### ISSUE TITLE
Fatal verify errors on push

### ISSUE THREAD

**Issue by azlinrahim** [git-lfs/git-lfs#1898]
I've been consistently getting the following fatal errors when trying to push lfs-tracked files today.

> Git LFS: (0 of 2 files) 36.74 MB / 36.74 MB
Fatal error: http: error getting verify links
Docs: https://github.com/contact
Request ID: BF8A:2C94:9012F9B:B637D00:58906E05
error: failed to push some refs to 'git@github.com:quickschools/QSDeploy.git'

Other info: I'm running Git 2.9.3 & Git-lfs 1.4.4 on Ubuntu

I've attached the trace log in case this would help anyone figure out what's wrong. From the log, looks like the verify link is returning http 500 server error. Hopefully that means this is an interim issue.

[qs-git-lfs.out.txt](https://github.com/git-lfs/git-lfs/files/741793/qs-git-lfs.out.txt)

Would appreciate it if anyone could help decipher what's going on. Is this problem caused by something on my end? I was able to push the files successfully a few days back, so whatever causing this, it must be recent. Also, I've tried to push using a different machine, unfortunately with the same result.

**Comment by ttaylorr** [comment]
Same issues as: https://github.com/git-lfs/git-lfs/issues/1897.
