### ISSUE TITLE
Commits with malformed pointers cause working copy to always look dirty

### ISSUE THREAD

**Issue by arh-oxbotica** [git-lfs/git-lfs#1900]
Certain IDEs, [in particular XCode](http://gopalkri.com/2016/05/17/git-lfs-xcode-asset-catalogs/)  seem to be able to stage files without invoking the lfs 'clean' filter. Because of this, we've now got a number of old commits in our repos that appear to have malformed lfs pointers. We've added subsequent commits to replace the binary blobs with valid lfs pointer files, but checking out one of those old 'broken' commits gets git into a state where it won't allow any other commit to be checked out.

### Steps to reproduce:
```
$ git lfs version
git-lfs/1.5.5 (GitHub; darwin amd64; go 1.7.4)
```

First set up a repo with a 'problem' commit, and then a commit that resolves the problem.
```
git init
git lfs install
git lfs track *.dat
git add .gitattributes
git commit -m "Initial commit"

# Stage the file, but skip the lfs clean filter
base64 /dev/urandom | head -c 64 > file.dat
git \
  -c "filter.lfs.process=" \
  -c "filter.lfs.clean=cat" \
  -c "filter.lfs.required=false" \
  add file.dat

git commit -m "Commit binary blob (not lfs pointer)"

# Recommit the file, but allow the clean filter to run properly
touch file.dat
git add file.dat
git commit -m "Commit file.dat properly with lfs"
```

If we subsequently check out the problem commit, git refuses to let us check out any other commits, as it believes the working copy is dirty.
```
$ git checkout -b problem HEAD^
Switched to a new branch 'problem'
Encountered 1 file(s) that should have been pointers, but weren't:
	file.dat

$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	file.dat
Please commit your changes or stash them before you switch branches.
Aborting

$ git diff
diff --git a/file.dat b/file.dat
index b556de2..06dec56 100644
--- a/file.dat
+++ b/file.dat
@@ -1 +1,3 @@
-5gE16BcwO84d5xTL+kqkdHhUWoaI4PutjLnABSeuUhBYl6mQ2480MCl3o554Y9mw
\ No newline at end of file
+version https://git-lfs.github.com/spec/v1
+oid sha256:7e0c9fd2e00e349a2bcd546bd503042e0e5dd13c70bc8a15deae74ae7cd414a4
+size 64
```

It's possible to get out of this state using `git checkout --force`. But it causes all sorts of issues for scripted processes which don't understand what's going on and just blow up whenever they encounter one of these commits.

Given that lfs detected the malformed pointer and just correctly outputted the raw file.dat blob, is it reasonable/possible for git to treat the working copy as being clean?

**Comment by ttaylorr** [comment]
Hi @arh-oxbotica, thanks for opening up such a detailed issue. Much appreciated :-).

The code that you're referring to at the end:

> Given that lfs detected the malformed pointer and just correctly outputted the raw file.dat blob, is it reasonable/possible for git to treat the working copy as being clean?

is [here][1]:

```go
if len(malformed) > 0 {
	fmt.Fprintf(os.Stderr, "Encountered %d file(s) that should have been pointers, but weren't:\n", len(malformed))
	for _, m := range malformed {
		fmt.Fprintf(os.Stderr, "\t%s\n", m)
	}
}
```

That code does _not_ exit in a dirty state by itself. Handling the error below:

```go
if err := s.Err(); err != nil && err != io.EOF {
	ExitWithError(err)
}
```

does, however, exit with `2`.

In terms of what's actually going on, this could be a few things:

1. Git treats any output from `stderr` as error-like, causing the checkout to fail. I don't recall seeing anything like this in `convert.c`, but @larsxschneider will have to double-check my thinking.
2. There's a legitimate error that we're _not_ reporting. One way to figure this out would be to rerun the checkout with `GIT_TRACE_PACKET=1`.

I'd be curious about the second-to-last packet that LFS sends back to Git. One thing you could do to accomplish that would be to:

```sh
$ GIT_TRACE_PACKET git checkout my-feature 2>trace_pkt.log
$ tail trace_pkt.log
```

[1]: https://github.com/git-lfs/git-lfs/blob/7e495f5cf7f1962bea40f570db874b9c49a92b1f/commands/command_filter_process.go#L85-L90

**Comment by arh-oxbotica** [comment]
I did already try suppressing the the malformed pointer error message and it made no difference. I also tried outputting stuff to Stderr *every* time the clean filter ran, and git dealt with it fine. So I don't think there's a problem with sending output to Stderr.

As far as I could tell, the problem was happening at the point where git was checking that the working copy was clean. It was running the smudge and clean filters multiple times to generate the output of `git status`. I was getting a bit out of my depth at that point, so I thought I'd submit an issue to see if this was something that was already known.

I'll go and try the `GIT_TRACE_PACKET' test sometime today.

**Comment by arh-oxbotica** [comment]
This is the output of the packet trace when I `git checkout problem`:
```
11:06:25.740317 pkt-line.c:80           packet:          git> git-filter-client
11:06:25.740889 pkt-line.c:80           packet:          git> version=2
11:06:25.740896 pkt-line.c:80           packet:          git> 0000
11:06:25.763092 pkt-line.c:80           packet:          git< git-filter-server
11:06:25.763108 pkt-line.c:80           packet:          git< version=2
11:06:25.763113 pkt-line.c:80           packet:          git< 0000
11:06:25.763117 pkt-line.c:80           packet:          git> capability=clean
11:06:25.763122 pkt-line.c:80           packet:          git> capability=smudge
11:06:25.763126 pkt-line.c:80           packet:          git> 0000
11:06:25.763156 pkt-line.c:80           packet:          git< capability=clean
11:06:25.763170 pkt-line.c:80           packet:          git< capability=smudge
11:06:25.763175 pkt-line.c:80           packet:          git< 0000
11:06:25.763192 pkt-line.c:80           packet:          git> command=smudge
11:06:25.763199 pkt-line.c:80           packet:          git> pathname=file.dat
11:06:25.763203 pkt-line.c:80           packet:          git> 0000
11:06:25.763207 pkt-line.c:80           packet:          git> 2elfxUkNqVdkJ9wcicvYmQZad944upSL6g4iowi82y0hWMVrUJAMQv+Holo+dg1h
11:06:25.763220 pkt-line.c:80           packet:          git> 0000
11:06:25.763261 pkt-line.c:80           packet:          git< status=success
11:06:25.763277 pkt-line.c:80           packet:          git< 0000
11:06:25.763341 pkt-line.c:80           packet:          git< 2elfxUkNqVdkJ9wcicvYmQZad944upSL6g4iowi82y0hWMVrUJAMQv+Holo+dg1h
11:06:25.763417 pkt-line.c:80           packet:          git< 0000
11:06:25.763423 pkt-line.c:80           packet:          git< status=success
11:06:25.763428 pkt-line.c:80           packet:          git< 0000
Switched to branch 'problem'
Encountered 1 file(s) that should have been pointers, but weren't:
        file.dat
```

**Comment by arh-oxbotica** [comment]
When I run `git status` on the 'problem' commit I get this:
```
11:08:49.952370 pkt-line.c:80           packet:          git> git-filter-client
11:08:49.952952 pkt-line.c:80           packet:          git> version=2
11:08:49.952958 pkt-line.c:80           packet:          git> 0000
11:08:49.977845 pkt-line.c:80           packet:          git< git-filter-server
11:08:49.977861 pkt-line.c:80           packet:          git< version=2
11:08:49.977865 pkt-line.c:80           packet:          git< 0000
11:08:49.977869 pkt-line.c:80           packet:          git> capability=clean
11:08:49.977876 pkt-line.c:80           packet:          git> capability=smudge
11:08:49.977881 pkt-line.c:80           packet:          git> 0000
11:08:49.977928 pkt-line.c:80           packet:          git< capability=clean
11:08:49.977941 pkt-line.c:80           packet:          git< capability=smudge
11:08:49.977946 pkt-line.c:80           packet:          git< 0000
11:08:49.977961 pkt-line.c:80           packet:          git> command=clean
11:08:49.977968 pkt-line.c:80           packet:          git> pathname=file.dat
11:08:49.977972 pkt-line.c:80           packet:          git> 0000
11:08:49.977981 pkt-line.c:80           packet:          git> 2elfxUkNqVdkJ9wcicvYmQZad944upSL6g4iowi82y0hWMVrUJAMQv+Holo+dg1h
11:08:49.977995 pkt-line.c:80           packet:          git> 0000
11:08:49.978010 pkt-line.c:80           packet:          git< status=success
11:08:49.978022 pkt-line.c:80           packet:          git< 0000
11:08:49.978406 pkt-line.c:80           packet:          git< version https://git-lfs.github.com/spec/v1oid sha256:a4c6fe369a7a1f4e45c79f73e0f6d744f0630a75b5c2ba416d1221bd6422d6fbsize 64
11:08:49.978482 pkt-line.c:80           packet:          git< 0000
11:08:49.978488 pkt-line.c:80           packet:          git< status=success
11:08:49.978493 pkt-line.c:80           packet:          git< 0000
11:08:49.978527 pkt-line.c:80           packet:          git> command=clean
11:08:49.978534 pkt-line.c:80           packet:          git> pathname=file.dat
11:08:49.978538 pkt-line.c:80           packet:          git> 0000
11:08:49.978544 pkt-line.c:80           packet:          git> 2elfxUkNqVdkJ9wcicvYmQZad944upSL6g4iowi82y0hWMVrUJAMQv+Holo+dg1h
11:08:49.978548 pkt-line.c:80           packet:          git> 0000
11:08:49.978591 pkt-line.c:80           packet:          git< status=success
11:08:49.978604 pkt-line.c:80           packet:          git< 0000
11:08:49.978867 pkt-line.c:80           packet:          git< version https://git-lfs.github.com/spec/v1oid sha256:a4c6fe369a7a1f4e45c79f73e0f6d744f0630a75b5c2ba416d1221bd6422d6fbsize 64
11:08:49.978925 pkt-line.c:80           packet:          git< 0000
11:08:49.978932 pkt-line.c:80           packet:          git< status=success
11:08:49.978937 pkt-line.c:80           packet:          git< 0000
11:08:49.979210 pkt-line.c:80           packet:          git> command=clean
11:08:49.979220 pkt-line.c:80           packet:          git> pathname=file.dat
11:08:49.979224 pkt-line.c:80           packet:          git> 0000
11:08:49.979230 pkt-line.c:80           packet:          git> 2elfxUkNqVdkJ9wcicvYmQZad944upSL6g4iowi82y0hWMVrUJAMQv+Holo+dg1h
11:08:49.979234 pkt-line.c:80           packet:          git> 0000
11:08:49.979288 pkt-line.c:80           packet:          git< status=success
11:08:49.979302 pkt-line.c:80           packet:          git< 0000
11:08:49.979584 pkt-line.c:80           packet:          git< version https://git-lfs.github.com/spec/v1oid sha256:a4c6fe369a7a1f4e45c79f73e0f6d744f0630a75b5c2ba416d1221bd6422d6fbsize 64
11:08:49.979628 pkt-line.c:80           packet:          git< 0000
11:08:49.979633 pkt-line.c:80           packet:          git< status=success
11:08:49.979638 pkt-line.c:80           packet:          git< 0000
11:08:49.980141 pkt-line.c:80           packet:          git> command=clean
11:08:49.980153 pkt-line.c:80           packet:          git> pathname=file.dat
11:08:49.980157 pkt-line.c:80           packet:          git> 0000
11:08:49.980162 pkt-line.c:80           packet:          git> 2elfxUkNqVdkJ9wcicvYmQZad944upSL6g4iowi82y0hWMVrUJAMQv+Holo+dg1h
11:08:49.980174 pkt-line.c:80           packet:          git> 0000
11:08:49.980198 pkt-line.c:80           packet:          git< status=success
11:08:49.980205 pkt-line.c:80           packet:          git< 0000
11:08:49.980447 pkt-line.c:80           packet:          git< version https://git-lfs.github.com/spec/v1oid sha256:a4c6fe369a7a1f4e45c79f73e0f6d744f0630a75b5c2ba416d1221bd6422d6fbsize 64
11:08:49.980518 pkt-line.c:80           packet:          git< 0000
11:08:49.980523 pkt-line.c:80           packet:          git< status=success
11:08:49.980528 pkt-line.c:80           packet:          git< 0000
```

**Comment by arh-oxbotica** [comment]
OK, I think I have a bit more understanding of the problem.

Suppose I have a file `image1.png` which is correctly tracked by lfs and has already been committed. If I make a modification to that file in my working copy, then `git diff` will show me the change in the lfs pointer file, rather than the change to the underlying png file. If does this by first running the 'clean' filter on the file in the working copy, and then comparing the result against the lfs pointer file in the `HEAD` commit.

Now consider the case where image2.png has been committed, but somehow skipped the 'clean' filter. I then `touch image2.png` but make no changes. When I run `git diff`, git will run the 'clean' filter on the file in the working copy, producing a valid pointer file. It will then compare that against the binary blob of image2.png stored in the `HEAD` commit. And it will obviously look different. Now, no matter what I do (even `git reset --hard`), git will think there are changes in the working copy.

Here's an example. First prepare the problematic commit:
```
git init
git lfs install
git lfs track *.png
git add .gitattributes
git commit -m "Initial commit"

# Stage the file, but skip the lfs clean filter
base64 /dev/urandom | head -c 64 > image2.png
git \
  -c "filter.lfs.process=" \
  -c "filter.lfs.clean=cat" \
  -c "filter.lfs.required=false" \
  add image2.png
git commit -m "Commit binary blob (not lfs pointer)"
```

Then make no changes at all, but see that the diff shows changes:
```
$ touch image2.png
$ git diff
diff --git a/image2.png b/image2.png
index 499254b..8855920 100644
--- a/image2.png
+++ b/image2.png
@@ -1 +1,3 @@
-TVeDAOs6+puPWj9dOIUc7VdgwvLelajns1Fb2fTgsnO/t44bSvqrVcAF8ynb8587
\ No newline at end of file
+version https://git-lfs.github.com/spec/v1
+oid sha256:1ee5e4ce7914a03c00e558d04569a759a6ec0a3e68825b8a7375a9d36d886faf
+size 64
```

I'm not entirely sure what a solution to this problem would even look like. When then 'clean' filter is run on the file in the working copy, it would somehow need to check the `HEAD` commit to see if the file is already tracked by git. If the blob for that file is a valid lfs pointer then it should 'clean' as normal. If there is a malformed pointer in `HEAD` then it should emit a warning, then just `cat` the contents of the file in the working copy.

This would mean that the file would remain untracked by git-lfs until the user explicitly chose to convert it to a git-lfs pointer. They would at least see warning messages any time git-lfs encountered the malformed pointer.

**Comment by ttaylorr** [comment]
> ```bash
> # Stage the file, but skip the lfs clean filter
> base64 /dev/urandom | head -c 64 > image2.png
> git \
>   -c "filter.lfs.process=" \
>   -c "filter.lfs.clean=cat" \
>   -c "filter.lfs.required=false" \
>   add image2.png
> ```

Importantly, this is a case reachable by committing a file _before_ `lfs track`-ing it, which happens all the time when people convert their repositories to use LFS, but don't actually rewrite history.

> I don't know if it would be possible (or desirable!) to implement this sort of functionality.

It would definitely be desirable to find a solution to this problem, but I don't think offering to rewrite history would be the right way to go about it.

We could ask the user if they wanted to "upgrade" it to a LFS-tracked object, which would solve interactions with the repository from that point forward, but doesn't deal with the history prior.

@git-lfs/core: what do you think?

**Comment by sinbad** [comment]
The main issue happens when they commit the content of an LFS file and the change to the `.gitattributes` in different commits. So long as they commit both the change to the `.gitattributes` and re-commit the contents of the files affected at the same commit, it's all fine because `git checkout` will always update `.gitattributes` at a checkout before other files. This is why `git lfs track` checks for files which are already tracked in git and forces them to appear as modified, to try to encourage people to re-commit.

If we wanted to make this more robust, we could add a check in the `pre-commit` hook to make sure that:

# If `.gitattributes` is being changed, that every file which is now marked as lfs actually contains LFS content at "HEAD+index"
# If an lfs tracked file is being committed, that changes to `.gitattributes` are being committed at the same time

There may be other checks to deal with cases of removing a file from lfs tracking but that would probably catch most cases.

**Comment by sinbad** [comment]
As for the OP case of having forced the filter off during commit - although that would be caught by the hook I suggest, historical cases will still exist. I don't think we should try to avoid that, because it represents an accurate situation; the file *is* modified according to git rules. We should try to make it less likely to happen but this repo is essentially broken and needs fixing.

**Comment by AndyBan** [comment]
I have gotten into this state and am getting "Encountered 18 file(s) that should have been pointers, but weren't" by:
Commit with LFS files
Commit with none lfs files
pull --rebase

Which resulted in a log of (older to new)
Pulled commit
Commit with LFS files
Pulled commit
Commit with none lfs files

I have since synced with our main repo and other people are getting the error that I have committed a non pointer file. What is the correct process for fixing these files?  I have tried deleting and adding them again between two commits and it just seemed to pick up the raw binaries.  They are only a few meg so the fact they are blobs in the git repo isn't an issue so we don't need to rewrite them out but i'd like to stop the errors coming up.  I can see you can get the pointer data with git lfs pointer but I don't want to just change the file to that as the remote git fls server will not have a copy of the binary.

**Comment by ttaylorr** [comment]
Hi @AndyBan! Thanks for the comment, and I'm sorry that you're having trouble. To address your question:

> I have since synced with our main repo and other people are getting the error that I have committed a non pointer file. What is the correct process for fixing these files? I have tried deleting and adding them again between two commits and it just seemed to pick up the raw binaries.

Deleting and adding a file whose pathspec contains a malfomed pointer earlier in your Git history won't quite solve the problem, since there are still places in the history that contain the malformed pointer.

If you have large binaries in your history, you can use the new [`git-lfs-migrate(1)` command][1] to fix those issues. I'd recommend something like:

```bash
$ git lfs migrate import --include="<file1>" --include="<file2>"
```

I think now that we have the `git-lfs-migrate(1)` command, we can safely close this issue, as that command should fix the underlying problem.

[1]: https://github.com/git-lfs/git-lfs/blob/v2.2.0/docs/man/git-lfs-migrate.1.ronn
