### ISSUE TITLE
 can not upload new objects to public fork 

### ISSUE THREAD

**Issue by trustfarm-dev** [git-lfs/git-lfs#1906]
@git-lfs 

$ GIT_TRACE_CURL=true;  git push origin master
Username for 'https://github.com': trustfarm.info@gmail.com
Password for 'https://trustfarm.info@gmail.com@github.com':
Git LFS: (0 of 1 files) 0 B / 180.84 MB
batch response: http: @trustfarm-dev can not upload new objects to public fork trustfarm/orangepi_h2_linux_tfarm
Docs: https://github.com/contact
error: failed to push some refs to 'https://github.com/trustfarm/orangepi_h2_linux_tfarm.git'

How can I solve this ?
thanks.
I've already contact to github.com/contact ,  even though, there's git-lfs problem uses @git-lfs

**Comment by ttaylorr** [comment]
Hi @trustfarm-dev, Git LFS on github.com does not currently support pushing LFS objects to public forks. GitHub Enterprise does support this behavior.

**Comment by trustfarm-dev** [comment]
@ttaylorr , Ok I see. thanks.
And How can I revert it? client side commits.
every time it checks git lfs .

**Comment by ttaylorr** [comment]
You can rewrite (amend/rebase) the commits with LFS enabled and write the large files as-is.

**Comment by Pranav02** [comment]
@ttaylorr 
I am facing below issue. Please let me know the what is the issue and how to resolve it.


14:50:28.789680 git.c:350               trace: built-in: git 'push' 'origin' 'LFS-test'
14:50:28.791304 run-command.c:336       trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '\''Pranav02/dcos-cassandra-service.git'\'''
14:50:32.572912 run-command.c:336       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
14:50:32.579416 git.c:563               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
14:50:32.579968 run-command.c:336       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: ssh: git@github.com git-lfs-authenticate Pranav02/dcos-cassandra-service.git upload
trace git-lfs: HTTP: POST https://lfs.github.com/Pranav02/dcos-cassandra-service/locks/verify
> POST /Pranav02/dcos-cassandra-service/locks/verify HTTP/1.1
> Host: lfs.github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth AHDiXLypXIwkvtF7W0HYky93lxcdWRklks5ZB1JDwA==
> Content-Length: 2
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
> 
{}trace git-lfs: HTTP: 200


< HTTP/1.1 200 OK
< Content-Length: 41
< Content-Type: application/vnd.git-lfs+json
< Date: Mon, 01 May 2017 09:20:37 GMT
< X-Github-Request-Id: 8674:6F30:3B7F62A:4C83C9F:5906FDE4
< 
trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

{"ours":[],"theirs":[],"next_cursor":""}
trace git-lfs: pre-push: refs/heads/LFS-test e584ca8b106020030a20a31428fc0b8cb84e6436 refs/heads/LFS-test 0000000000000000000000000000000000000000
trace git-lfs: run_command: git rev-list --objects e584ca8b106020030a20a31428fc0b8cb84e6436 --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: sending batch of size 5
trace git-lfs: ssh: git@github.com git-lfs-authenticate Pranav02/dcos-cassandra-service.git upload
trace git-lfs: api: batch 5 files
trace git-lfs: HTTP: POST https://lfs.github.com/Pranav02/dcos-cassandra-service/objects/batch
> POST /Pranav02/dcos-cassandra-service/objects/batch HTTP/1.1
> Host: lfs.github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth AHDiXMHe8FizETzTKxWHeILjFUsoKpw4ks5ZB1JLwA==
> Content-Length: 478
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
> 
{"operation":"upload","objects":[{"oid":"30bf5fbac0cfbc9201cac1d6973dbc96e5f55043ab315eda8c7aeb23df4f2644","size":73676107},{"oid":"bab04ef8ad997197a0e4f02250ed71240f339a44209b8d9f941ee6291130fa9a","size":31027554},{"oid":"6f5468dd8fb8a2cd84fef950ab945bfafaa405edffa5c62fdc1a475e9f86b4ef","size":27721301},{"oid":"363631f4dafcf934b2a33e6919f3db33f0dd5630de62b851424f00ae76e80cb0","size":205},{"oid":"f595019467466ddb8f06c2909f4f59c54f2707a3fd433d4ceea5594dea28bf7a","size":40}]}trace git-lfs: HTTP: 403


< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Content-Security-Policy: default-src 'none'
< Content-Type: application/json; charset=utf-8
< Date: Mon, 01 May 2017 09:20:43 GMT
< Server: GitHub.com
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Media-Type: unknown
< X-Github-Request-Id: 8674:6F30:3B7F96E:4C83CD5:5906FDE5
< X-Ratelimit-Limit: 3000
< X-Ratelimit-Remaining: 2999
< X-Ratelimit-Reset: 1493630503
< X-Xss-Protection: 1; mode=block
< 
trace git-lfs: HTTP: {"message":"@Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service","documentation_url":"https://github.com/contact"}
{"message":"@Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service","documentation_url":"https://github.com/contact"}trace git-lfs: api error: @Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service
Git LFS: (0 of 5 files) 0 B / 126.29 MB                                                                                                                                                                                                                                        
batch response: @Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service
error: failed to push some refs to 'git@github.com:Pranav02/dcos-cassandra-service.git'
prjindal-osx-1:dcos-cassandra-service prjindal$

**Comment by Pranav02** [comment]
I am facing below issue using LFS , please check and let me know what is the issue and how to resolve it.


14:50:28.789680 git.c:350               trace: built-in: git 'push' 'origin' 'LFS-test'
14:50:28.791304 run-command.c:336       trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '\''Pranav02/dcos-cassandra-service.git'\'''
14:50:32.572912 run-command.c:336       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
14:50:32.579416 git.c:563               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
14:50:32.579968 run-command.c:336       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: ssh: git@github.com git-lfs-authenticate Pranav02/dcos-cassandra-service.git upload
trace git-lfs: HTTP: POST https://lfs.github.com/Pranav02/dcos-cassandra-service/locks/verify
> POST /Pranav02/dcos-cassandra-service/locks/verify HTTP/1.1
> Host: lfs.github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth AHDiXLypXIwkvtF7W0HYky93lxcdWRklks5ZB1JDwA==
> Content-Length: 2
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
> 
{}trace git-lfs: HTTP: 200


< HTTP/1.1 200 OK
< Content-Length: 41
< Content-Type: application/vnd.git-lfs+json
< Date: Mon, 01 May 2017 09:20:37 GMT
< X-Github-Request-Id: 8674:6F30:3B7F62A:4C83C9F:5906FDE4
< 
trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

{"ours":[],"theirs":[],"next_cursor":""}
trace git-lfs: pre-push: refs/heads/LFS-test e584ca8b106020030a20a31428fc0b8cb84e6436 refs/heads/LFS-test 0000000000000000000000000000000000000000
trace git-lfs: run_command: git rev-list --objects e584ca8b106020030a20a31428fc0b8cb84e6436 --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: sending batch of size 5
trace git-lfs: ssh: git@github.com git-lfs-authenticate Pranav02/dcos-cassandra-service.git upload
trace git-lfs: api: batch 5 files
trace git-lfs: HTTP: POST https://lfs.github.com/Pranav02/dcos-cassandra-service/objects/batch
> POST /Pranav02/dcos-cassandra-service/objects/batch HTTP/1.1
> Host: lfs.github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth AHDiXMHe8FizETzTKxWHeILjFUsoKpw4ks5ZB1JLwA==
> Content-Length: 478
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
> 
{"operation":"upload","objects":[{"oid":"30bf5fbac0cfbc9201cac1d6973dbc96e5f55043ab315eda8c7aeb23df4f2644","size":73676107},{"oid":"bab04ef8ad997197a0e4f02250ed71240f339a44209b8d9f941ee6291130fa9a","size":31027554},{"oid":"6f5468dd8fb8a2cd84fef950ab945bfafaa405edffa5c62fdc1a475e9f86b4ef","size":27721301},{"oid":"363631f4dafcf934b2a33e6919f3db33f0dd5630de62b851424f00ae76e80cb0","size":205},{"oid":"f595019467466ddb8f06c2909f4f59c54f2707a3fd433d4ceea5594dea28bf7a","size":40}]}trace git-lfs: HTTP: 403


< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Content-Security-Policy: default-src 'none'
< Content-Type: application/json; charset=utf-8
< Date: Mon, 01 May 2017 09:20:43 GMT
< Server: GitHub.com
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Media-Type: unknown
< X-Github-Request-Id: 8674:6F30:3B7F96E:4C83CD5:5906FDE5
< X-Ratelimit-Limit: 3000
< X-Ratelimit-Remaining: 2999
< X-Ratelimit-Reset: 1493630503
< X-Xss-Protection: 1; mode=block
< 
trace git-lfs: HTTP: {"message":"@Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service","documentation_url":"https://github.com/contact"}
{"message":"@Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service","documentation_url":"https://github.com/contact"}trace git-lfs: api error: @Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service
Git LFS: (0 of 5 files) 0 B / 126.29 MB                                                                                                                                                                                                                                        
batch response: @Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service
error: failed to push some refs to 'git@github.com:Pranav02/dcos-cassandra-service.git'

**Comment by fxfactorial** [comment]
@ttaylorr Is this still the case that public forks can't get git lfs?

**Comment by ttaylorr** [comment]
> @ttaylorr Is this still the case that public forks can't get git lfs?

This is still the case. @-technoweenie's recent work in including affected references makes progress towards introducing a feature like this, but I cannot comment on GitHub's unreleased features.

**Comment by lrq3000** [comment]
Please fix this issue, it's ridiculous we can't use git-lfs on forks!

**Comment by phillipjohnston** [comment]
As a workaround, is there a way to disassociate the repo as a fork?

**Comment by paroque28** [comment]
As a workaround, delete the repo and create and empty one with the exact same name.
Then : `git push`

**Comment by cosine99** [comment]
> Git LFS on github.com does not currently support pushing LFS objects to public forks. GitHub Enterprise does support this behavior.

This should be part of the official docs. Change my mind.

**Comment by Dragon1573** [comment]
Hi @ttaylorr 

```text
$ git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v origin develop:develop
Pushing to git@github.com:Dragon1573/Parallel-GMM.git
Uploading LFS objects:   0% (0/2), 0 B | 0 B/s, done.
batch response: @Dragon1573 can not upload new objects to public fork Dragon1573/Parallel-GMM
error: failed to push some refs to 'git@github.com:Dragon1573/Parallel-GMM.git'
```

> Hi @trustfarm-dev, Git LFS on github.com does not currently support pushing LFS objects to public forks. GitHub Enterprise does support this behavior.

Accroding to your reply, the only way to enalbe Git LFS Support is duplicate the repository which I was forked from? Could you please tell us when this feature (Git LFS Support on Public Forks) could be added to GitHub?

**Comment by paroque28** [comment]
Hi @Dragon1573 ,
The only way I found possible to use Git LFS was by forking the repository manuallt.
I mean:
```
git clone
git remote rename ...
git remote add ...
git push --all ...
```

But honestly don't waste your time, Github has some stupid quota limitations.
Use Git Lab instead, I can even upload big files without LFS.

Regards,
Pablo

**Comment by Dragon1573** [comment]
@paroque28 ,

Thanks. I act like [Duplicating a repository - GitHub](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository), and `git push` to my duplicated repository. AND IT WORKS!

For your advice of **GitLab** ...

- GitHub is the biggest community of developers and it has so many users all around the world, so I registerd an account on it.
- I heard about GitLab before, but I haven't used it.
- I also registerd an **Atlassian** Account and enabled **BitBucket** only for activating **SourceTree**, but I deleted the account forever after the activation.
- I had intention to create an account on **Gitee**, but I think those are all beginner-developers in my country. None of the high-level coders and developers using **Gitee** as their major working platform.

I have no idea moving all my repositoies to one of these platforms. It's nice using GitHub. It doesn't matter I can't enable Git LFS on GitHub Public Forks Repository. We still have other ways to enable it and upload our massive files, don't we?

**Comment by NightMachinary** [comment]
Well, if I had known this, I would not have made a fork via Github automatically. Github forks suck.

**Comment by Dragon1573** [comment]
@NightMachinary , I met another promlem 2years ago. It is not related to Git LFS on Public Forks, but DOES related to Git LFS itself. The problem details is at apachecn/python_data_analysis_and_mining_action#4.

I used to clone [a public repository](https://github.com/apachecn/python_data_analysis_and_mining_action) via SSH. The repository provides plenties of massive dataset files for cloners learning Data Analysis and Data Mining. The Git LFS storage and bandwidth of the repository owner is overflow so I can't clone them through `git clone ...`. The repository owner provide me 2 external links to those massive datasets - one at [**Baidu Netdisk**](https://pan.baidu.com/) for users in my country and the other at **OneDrive** for users in anywhere else.

Maybe store these massive files (datasets, images, sounds, videos, etc.) seperately from GitHub and only attach a simple `*.txt` file discribing the downloadable link for the massive files could make sence? I also tried to upload those files to DHT with BitCommet and provide only a `*.torrent` for files doanloading.

**Comment by JulesGM** [comment]
@ttaylorr  This is so strange. Why did you folks decide to do this?

**Comment by avivajpeyi** [comment]
@ttaylorr this makes collaborating on open source projects quite a hassle! Will there ever be plans for changing this?

**Comment by bk2204** [comment]
Hey, folks,

This is not a limitation of the Git LFS open source client, but a part of how GitHub works.  This repository is for tracking and implementing features of the Git LFS open source client; if you have feedback or questions about GitHub, please contact the GitHub Support team.

**Comment by crpietschmann** [comment]
Doe GitHub still not support LFS on Public Repos?

**Comment by bk2204** [comment]
Hey,

As mentioned, this repo is for the Git LFS open source project.  Whether GitHub allows LFS on public repos isn't on topic here and is best addressed to GitHub.  I'm going to lock conversation on this thread because it isn't likely to return to being on topic.
