### ISSUE TITLE
Finalize File Locking for Git LFS v2.0

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1908]
As discussed in #1883, we are planning on bootstrapping basic file locking in Git LFS v2.0. The intention is to get a bare bones locking implementation out, even if it's only supporting the basic single-branch locking workflow. We'll use this as a starting point to collect feedback and experiment with more advanced locking workflows. Here's what we need:

* [x] API Specification https://github.com/git-lfs/git-lfs/pull/1909
* [x] JSON Schema for requests and responses #1931
* [x] Command man pages https://github.com/git-lfs/git-lfs/pull/1936
* [x] Drop `GITLFSLOCKSENABLED` requirement https://github.com/git-lfs/git-lfs/pull/1946

**Comment by sinbad** [comment]
Cross-reference to #1844 (future extensions beyond 2.0)

**Comment by sinbad** [comment]
I've just discovered that Bitbucket Server (not cloud) returns a 501 Unimplemented for `info/lfs/locks` - we're going to get that changed to 404 but I'd like to get a PR in here to ignore that code silently too (and maybe others?) 

Perhaps as a safety measure a config value to disable the rules would be useful too to cope with unforeseen issues with other implementations.

I'm going to try to get that PR done asap but I'm laid low with flu right now so just wanted to flag this in the meantime until I'm back up to speed.

**Comment by technoweenie** [comment]
No worries, I'll add 501 support today.

> Perhaps as a safety measure a config value to disable the rules would be useful too to cope with unforeseen issues with other implementations.

What would disabling the rules look like? You want to be able to disable the pre-push lock check, for example?

**Comment by sinbad** [comment]
> CORRECTION: The current version in master ignores any error. I've updated the proposal in #1884 to support 501 instead of 410 though.

Ah, thanks so much - my brain just wasn't functioning well enough to check the detail & I must have been remembering the proposal. 👍 

> What would disabling the rules look like? You want to be able to disable the pre-push lock check, for example?

Yeah, it just made me think about unexpected combinations and how having a safety valve is always good for temporary workarounds, but  in #1884 the `lfs.<url>.locks=false` option actually looks perfect so that's already covered.

**Comment by technoweenie** [comment]
All done! Now to whittle away at that 2.0 milestone.

**Comment by ttaylorr** [comment]
🤘 let's do it.
