### ISSUE TITLE
unexpected EOF error when fetch LFS files

### ISSUE THREAD

**Issue by falcongreatly** [git-lfs/git-lfs#1915]
When I tried to fetch a gerrit change to my machine. I face a problem to fetch large files from LFS (~=10MBytes or ~= 20MBytes)

Do you know how can I overcome this error?

My Error Log
----------------------------------
git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)
git version 2.9.2.windows.1

$ git-lfs.exe smudge targetplatform/plugins/com.ibm.icu_56.1.0.v201601250100.jar
Error downloading object: targetplatform/plugins/com.ibm.icu_56.1.0.v201601250100.jar (799f4c95c43d0a6fa6e0000bba12783065cc17f492b2be9de5cba7fc16b686e0)

Smudge error: Error buffering media file: cannot write data to tempfile "C:\\workset\\.git\\lfs\\objects\\incomplete\\799f4c95c43d0a6fa6e0000bba12783065cc17f492b2be9de5cba7fc16b686e0.tmp": LFS: unexpected EOF: 
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Go/src/github.com/git-lfs/git-lfs/errors/types.go:166
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	C:/Go/src/github.com/git-lfs/git-lfs/errors/types.go:252
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	C:/Go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	C:/Go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:65
github.com/git-lfs/git-lfs/commands.smudge
	C:/Go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:84
github.com/git-lfs/git-lfs/commands.smudgeCommand
	C:/Go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:112
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:66
main.main
	C:/Go/src/github.com/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	C:/Go/src/runtime/proc.go:183
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=C:\workset
LocalGitDir=C:\workset\.git
LocalGitStorageDir=C:\workset\.git
LocalMediaDir=C:\workset\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\workset\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=true
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_PREFIX=

**Comment by frankbenoit** [comment]
Additional information:
The files can be downloaded good in other locations.
But one country it does not work reliably. Hence it seems to be related to download speed.
Is there perhaps a timeout/retry setting, that can be adjusted?

**Comment by technoweenie** [comment]
Try setting `$ git config lfs.transfer.maxretries 5`. There are [several lfs config options](https://github.com/git-lfs/git-lfs/blob/390edc6193bba2414f6bad216f29f88e6d82e329/docs/man/git-lfs-config.5.ronn), but I don't think the timeout ones apply in your case. LFS doesn't set a timeout for an entire download, just the initial tcp dial and tls timeouts. Since you're able to transfer data, those timeouts won't really change anything.

**Comment by falcongreatly** [comment]
I tried before maxretries configuration and it simply failed in the 5
retries.


On Feb 6, 2017 4:43 PM, "risk danger olson" <notifications@github.com>
wrote:

Try setting $ git config lfs.transfer.maxretries 5. There are several lfs
config options
<https://github.com/git-lfs/git-lfs/blob/390edc6193bba2414f6bad216f29f88e6d82e329/docs/man/git-lfs-config.5.ronn>,
but I don't think the timeout ones apply in your case. LFS doesn't set a
timeout for an entire download, just the initial tcp dial and tls timeouts.
Since you're able to transfer data, those timeouts won't really change
anything.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/git-lfs/git-lfs/issues/1915#issuecomment-277702076>,
or mute
the thread

**Comment by falcongreatly** [comment]
Attached log with trace enabled.
[command_log.txt](https://github.com/git-lfs/git-lfs/files/755519/command_log.txt)

**Comment by technoweenie** [comment]
That looks like a flaky internet connection. An "unexpected EOF" can happen when the connection is disrupted. Also, your LFS server doesn't support resumable downloads, so each retry has to start over from the beginning.

**Comment by ttaylorr** [comment]
I agree with @-technoweenie's interpretation. I am going to close this for now, since it's been about a year without any activity, but if this still remains an issue with the latest version of Git and Git LFS please let me know here!
