### ISSUE TITLE
Referenced versions of file lost due to server misconfiguration

### ISSUE THREAD

**Issue by Daerst** [git-lfs/git-lfs#1916]
I tried to execute the first big LFS commit earlier today on a branch - 1100 files (some, but not all, LFS tracked), about 1.5 gb total. While I was at this, I added some files to track, only on my branch, not yet on master. My git client crashed while adding some of the files, which may be part of the problem's root. Also, the server was misconfigured when I did the push. The directory that would store the Git LFS files did not exist, so everything went into oblivion. Nice, huh?

The steps that I took were the following:
1) A fresh clone, failed. Smudge error: Error buffering media file: Object not found on the server. Understandable. After calling `git lfs install --skip-smudge` I was able to clone and get the pointers, but of course not the actual files.
2) I fixed the server configuration and managed to push all but 2 files using `git lfs push --all`. The two files that didn't work are missing locally (i.e. not found in .git/lfs/objects/xx/yy) and are - I think - old versions of a file. I no longer have those versions, since I pushed them into oblivion, so I have no chance to upload them. The current version is pushed properly.
3) A fresh checkout still fails (smudge error - because of the two missing revisions?!). With smudge disabled, I am able to clone and switch to my branch. I've been staring at this for about 20 minutes now:
```
$ git lfs fetch
Fetching lfstestbranch
Git LFS: (0 of 692 files) 0 B / 1.41 GB
```

Any idea how I can bring smudge to reason, make `git lfs fetch` wake up and ideally even remove those two lost UIDs from the index?

If push comes to shove, the history of the repo is not super important. Just so you know. I'm prepared, mentally. Thanks in advance!

**Comment by technoweenie** [comment]
Try running `GIT_TRACE=1 git lfs fetch` to see where it's blocked.

It's really difficult to answer questions about the smudge issues and missing versions without seeing the repository. Smudge is only called by Git when it's checking files out to the working directory, so that means it shouldn't be pulling up old versions of a file (unless you're checking out an old commit or branch).

**Comment by Daerst** [comment]
Thank you for your reply. Let me go into more detail.

First, a clone of the master branch with smudge enabled works without problems.

When switching to the lfstestbranch, I get the following errors:
Downloading Assets/Decals/Drains/Textures/Drain1_AlbedoSpecular.png (7.30 KB)
```
Error downloading object: Assets/Decals/Drains/Textures/Drain1_AlbedoSpecular.png (7c28a98428b3c928d6ee1cdfc5e0440a4cdd7f10926c0016d7087fc5f14939bb)

Errors logged to D:\SWARMED\.git\lfs\objects\logs\20170206T215942.4603226.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: Assets/Decals/Drains/Textures/Drain1_AlbedoSpecular.png: smudge filter lfs failed

git did not exit cleanly (exit code 128) (1123 ms @ 06.02.2017 21:59:42)

```
Understandable, since the object can not be found on the server, it's not in the directory where the LFS objects are stored (checked via SSH), and I get a 404 error when I try to access it from GitLab. Which then again is kinda weird, because this is not one of the two items that I had problems pushing.

So, I deactivated smudge, switched the branch without problems and reactivated it. `GIT_TRACE=1 git lfs fetch` gives me countless 404 responses from GitLab, and then just hangs at a random point:

```
[404 response here]
</html>

Git LFS: (1 of 693 Files) 945.69 KB/ 1.41 GB
```

Maybe I should just delete the branch and start with a new one based on master, since it pulled just fine. Do you think this would help?

**Comment by technoweenie** [comment]
Yes, starting over from master would work. Alternatively, running `git lfs push --all` on the repository that pushed that branch should work, if it still has the branch and all the lfs files locally.

Can I get more details on the hanging fetch call? 404s should not make it hang. What happens when you run `GIT_TRACE=1 git lfs fetch` or `GIT_CURL_VERBOSE=1 git lfs fetch` ?

**Comment by Daerst** [comment]
`git lfs push --all` won't work in my case because some revision are lost, and there probably is no easy way to remove all references to them.

`GIT_TRACE=1 git lfs fetch` fetches some files, gives me an `Error reading cert file: "/bin/curl-ca-bundle.crt"` (I'm on windows, and fetching via HTTP), then prints 404 messages galore. I tried to count, it's roughly 80-90 messages, each one about 2750 bytes, so quite a lot of text there. At some point, it literally just stops. Same happens for `GIT_CURL_VERBOSE=1 git lfs fetch`.

I'll try deleting the branch and pushing everything again. Hope that fixes it. Thanks for your support!

**Comment by Daerst** [comment]
I tried with a fresh branch - no luck. When I try to push the files, LFS skips them, thinking for some reason that the server already has them, but it hasn't.

So I deleted the whole repository on the server and created a fresh one.

When I push some of the previous files, LFS skips them, because the server, despite a completely fresh repository, seems to think it has those. Or is it client side? How can I reset LFS and make it forget about all the mischief I have done in the last couple of days?

**Comment by technoweenie** [comment]
Whether uploadable files are skipped or not are completely based on the server side response to the batch api.

**Comment by ttaylorr** [comment]
HI @Daerst, can you let me know if this is still an issue? It has been ~1 year since there's been any activity on this thread, so I am going to close it for now. That said, if you're still encountering any trouble, please do not hesitate to let me know, and I'd be more than happy to lend a hand
