### ISSUE TITLE
Error downloading object, file not on server and branch has been deleted

### ISSUE THREAD

**Issue by Flipster77** [git-lfs/git-lfs#1917]
Hi, I'm encountering an error downloading a file that is managed by git lfs in our repo.
The git pull starts updating my local repository with the changes, and when it gets to this large file, it responds with the error below:

```
~\Documents\GitHub\NewStarboardRepo [master ↓2]> git fetch
~\Documents\GitHub\NewStarboardRepo [master ↓2]> git pull
Updating ecdf49ee..68e5dff3078/3850)
Downloading INT/Assets/Art/Materials/Textures/Arch/Apt_Arch_d.tga (64.00 MB)
Error downloading object: INT/Assets/Art/Materials/Textures/Arch/Apt_Arch_d.tga (d6b4267451308bbad3f8d22f12e6b5332fdd361a34cccf7335c0312e57614527)

Errors logged to C:\Users\flips\Documents\GitHub\NewStarboardRepo\.git\lfs\objects\logs\20170206T115250.0013308.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: INT/Assets/Art/Materials/Textures/Arch/Apt_Arch_d.tga: smudge filter lfs failed
```

I've attached the log file referenced by the error: [20170206T115250.txt](https://github.com/git-lfs/git-lfs/files/753523/20170206T115250.txt)

The main thing of interest in the log file seems to be this: 
```
$ git-lfs.exe filter-process
Error downloading object: INT/Assets/Art/Materials/Textures/Arch/Apt_Arch_d.tga (d6b4267451308bbad3f8d22f12e6b5332fdd361a34cccf7335c0312e57614527)

Smudge error: Error buffering media file: Object not found on the server.: 
```
which indicates that the file is not on the server.

The file (and several other files) were committed to a branch, then merged into the master branch via a pull request. The branch where the original changes were committed to was then deleted. 

Looking around, the issue seems similar to [https://github.com/git-lfs/git-lfs/issues/1665](https://github.com/git-lfs/git-lfs/issues/1665) where you suggest running `git lfs push --all` on the machine that has the files to ensure that the server gets them. Unfortunately, since the branch was deleted, we can't push the files.

Is there a way to confirm that the files were committed to the git lfs server correctly, so we can determine if that is the cause of the problem? And if they are missing/corrupt, what is the best way to go about pushing them to the repo?

Thanks,
Peter.

**Comment by Flipster77** [comment]
**UPDATE:** 

We created a new repository and committed everything from the previous repo, but when I cloned the new repository I encountered the same error on a different file.

```
~\Documents\GitHub> git clone https://github.com/KadenINT/NewSBGTestRepo.git
Cloning into 'NewSBGTestRepo'...
remote: Counting objects: 6854, done.
remote: Compressing objects: 100% (3570/3570), done.
remote: Total 6854 (delta 3282), reused 6854 (delta 3282), pack-reused 0Receiving objects: 100% (6854/6854), 952.86 MiB | 38.00 KiB/s
Receiving objects: 100% (6854/6854), 952.87 MiB | 36.00 KiB/s, done.
Resolving deltas: 100% (3282/3282), done.
Downloading INT/Assets/Art/3D/Environment/Apartment_Level/Roof_Models/Misc/Real fire_unity5/3d_models/Barrel/Barrel_D.tga (603.20 KB)
Error downloading object: INT/Assets/Art/3D/Environment/Apartment_Level/Roof_Models/Misc/Real fire_unity5/3d_models/Barrel/Barrel_D.tga (2059578630248b4d7ca381f70ff8718537630cfff3b62e7329f3ad040affd49a)

Errors logged to C:\Users\flips\Documents\GitHub\NewSBGTestRepo\.git\lfs\objects\logs\20170206T192351.0351377.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: INT/Assets/Art/3D/Environment/Apartment_Level/Roof_Models/Misc/Real fire_unity5/3d_models/Barrel/Barrel_D.tga: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```
Error log: 
[20170206T192351.txt](https://github.com/git-lfs/git-lfs/files/754184/20170206T192351.txt)


This file was also a part of the last commit in the previous repository, so that may indicate a common cause.

Is there something we can do to ensure that the files are committed correctly using git-lfs?
Is there a work-around we can use to complete the checkout so that we can continue to work on the project?

This issue is currently holding up the whole project, so any help would be appreciated.

**Comment by technoweenie** [comment]
Unfortunately, there's not much LFS can do if a server doesn't have the file. If you have the files in another copy of the repository (in its `.git/lfs/objects` dir), you should be able to push them like this:

```sh
# where remote is the name, like 'master'
$ git lfs push --object-id {remote} 2059578630248b4d7ca381f70ff8718537630cfff3b62e7329f3ad040affd49a oid2 oid3
```

**Comment by Flipster77** [comment]
Hi technoweenie, thanks for the reply.

We do have the files, and we had tried a `git lfs push --all` from the current master branch but it didn't seem to work. Pushing the specific files as you suggest would probably be the best way to resolve the issue.

In any case, we've decided to switch to using Unity Collaborate for our project. Thanks for the help, I'm closing the issue now.
