### ISSUE TITLE
Git LFS hangs when pushing 1 file in simple test with Atlassian BitBucket 4.11

### ISSUE THREAD

**Issue by mbrennan** [git-lfs/git-lfs#1918]
Hello,

Git LFS is hanging when trying to push a single LFS tracked file to an Atlassian BitBucket-based repository with LFS enabled.  I'm using Atlassian BitBucket 4.11 on the server, and locally Windows 7, Git LFS 1.5.5, git 2.10.0.windows.1, and PowerShell v5.0.117.10586.

I created a new brand new repository in Atlassian BitBucket, enabled LFS support, then issued the following commands:
`git clone ssh://git@cedt-icg-bitbucketcli.nam.nsroot.net:7999/lfstest/lfs_test.git`
`cd lfs_test`
`git lfs track *.exe`
`git add -A`
`git commit -m 'Added .gitattributes file'`
`git push --all`

This uploaded the `.gitattributes` file successfully to the BitBucket repository.  Next, I copied a 20mb .exe file into the root of the repository. Then I issued the following commands:
`git add -A`
`git commit -m 'Added .exe file to repository'`
`git push`

The Git LFS client hangs showing:
> Git LFS: (0 of 1 files) 0 B / 19.54 MB

I tried getting more information by setting environment variables GIT_TRACE=1 and GIT_CURL_VERBOSE=1: `&{ $env:GIT_TRACE='1'; $env:GIT_CURL_VERBOSE='1'; git push }`

Here's the output:
> 14:00:11.825169 git.c:350               trace: built-in: git 'push'
> 14:00:11.828169 run-command.c:336       trace: run_command: 'ssh' '-p' '7999' 'git@cedt-icg-bitbucketcli.nam.nsroot.net' 'git-receive-pack '\''/lfstest/lfs_test.git'\'''
> 14:00:12.632250 run-command.c:336       trace: run_command: '.git/hooks/pre-push' 'origin' 'ssh://git@cedt-icg-bitbucketcli.nam.nsroot.net:7999/lfstest/lfs_test.git'
> 14:00:12.769264 git.c:564               trace: exec: 'git-lfs' 'pre-push' 'origin' 'ssh://git@cedt-icg-bitbucketcli.nam.nsroot.net:7999/lfstest/lfs_test.git'
> 14:00:12.770264 run-command.c:336       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'ssh://git@cedt-icg-bitbucketcli.nam.nsroot.net:7999/lfstest/lfs_test.git'
> trace git-lfs: run_command: 'git' version
> trace git-lfs: pre-push: refs/heads/master cc1cefd47196d47227d0f91ea3dd5939bc1bd710 refs/heads/master 4a66b53be6dcf74fb894be983c04fdafb7b5333a
> trace git-lfs: run_command: git rev-list --objects cc1cefd47196d47227d0f91ea3dd5939bc1bd710 --not --remotes=origin --
> trace git-lfs: run_command: git cat-file --batch-check
> trace git-lfs: run_command: git cat-file --batch
> trace git-lfs: run_command: 'git' config -l
> trace git-lfs: tq: running as batched queue, batch size of 100
> trace git-lfs: tq: sending batch of size 1
> trace git-lfs: ssh: git@cedt-icg-bitbucketcli.nam.nsroot.net git-lfs-authenticate lfstest/lfs_test.git upload
> trace git-lfs: api: batch 1 files
> trace git-lfs: HTTP: POST https://cedt-icg-bitbucket.nam.nsroot.net/bitbucket/scm/lfstest/lfs_test.git/info/lfs/objects/batch
> &gt; POST /bitbucket/scm/lfstest/lfs_test.git/info/lfs/objects/batch HTTP/1.1
> &gt; Host: cedt-icg-bitbucket.nam.nsroot.net
> &gt; Accept: application/vnd.git-lfs+json; charset=utf-8
> &gt; Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5MDczIiwicmVwbyI6MTg2MTksInFzaCI6IjY2ZGIwMWU0ZjFjN2RlNzliMzZjZDA2ZjJiOTY1MWMxM2I2NDQ3M2YwZjIyZDk0NzE0YTBjNGE2MTdiY2VkNjEiLCJpc3MiOiJjb20uYXRsYXNzaWFuLmJpdGJ1Y2tldC5zZXJ2ZXIuYml0YnVja2V0LWdpdC1sZnMiLCJjb250ZXh0Ijp7InVzZXIiOnsiaGlnaGVzdFBlcm1pc3Npb24iOiJQUk9KRUNUX0NSRUFURSIsInVzZXJLZXkiOiI5MDczIiwiZGlzcGxheU5hbWUiOiJNaWNoYWVsIFAgQnJlbm5hbiIsInNsdWciOiJtYjg2ODA4IiwidXNlcm5hbWUiOiJtYjg2ODA4In19LCJleHAiOjE0ODY0MDc5MTQsImlhdCI6MTQ4NjQwNzYxNH0.z1JsSaAHgGwZyEAe8GHKjzokES-0PQ9Wbxv_orPufCU
> &gt; Content-Length: 125
> &gt; Content-Type: application/vnd.git-lfs+json; charset=utf-8
> &gt; User-Agent: git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)
> &gt;
> {"operation":"upload","objects":[{"oid":"304affcd9be8c1d07644ff53d45c1236d2c4a6b2ff4b7d7ded50e4a00a5144fc","size":20494336}]}trace git-lfs: HTTP: 200
> 
> 
> < HTTP/1.1 200 OK
> < Content-Length: 968
> < Cache-Control: no-store
> < Content-Type: text/html; charset=iso-8859-1
> < Date: Mon, 06 Feb 2017 19:00:15 GMT
> <
> Git LFS: (0 of 1 files) 0 B / 19.54 MB

Here's the output of `git lfs env`:
> git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)
> git version 2.10.0.windows.1
> 
> Endpoint=https://cedt-icg-bitbucketcli.nam.nsroot.net/lfstest/lfs_test.git/info/lfs (auth=none)
> &nbsp;&nbsp;SSH=git@cedt-icg-bitbucketcli.nam.nsroot.net:lfstest/lfs_test.git
> LocalWorkingDir=E:\lfs_test
> LocalGitDir=E:\lfs_test\.git
> LocalGitStorageDir=E:\lfs_test\.git
> LocalMediaDir=E:\lfs_test\.git\lfs\objects
> LocalReferenceDir=
> TempDir=E:\lfs_test\.git\lfs\tmp
> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> BatchTransfer=true
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic
> UploadTransfers=basic
> GIT_LFS_PATH=C:\Program Files\Git LFS
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"

What else should I try?  Is this a bug?

**Comment by technoweenie** [comment]
Thanks for the report. This looks like a server issue:

```
< HTTP/1.1 200 OK
< Content-Length: 968
< Cache-Control: no-store
< Content-Type: text/html; charset=iso-8859-1
< Date: Mon, 06 Feb 2017 19:00:15 GMT
```

That is not a valid LFS response. I think you should contact BitBucket support so they can look into this.

**Comment by mbrennan** [comment]
Thanks @technoweenie, I'll contact Atlassian.  What would a normal response look like?

**Comment by technoweenie** [comment]
A successful response would have returned some json data with `Content-Type: application/vnd.git-lfs+json`. With the amount of tracing you had enabled, you should've seen a JSON response that resembles the JSON request body that Git LFS sent too.

This is an interesting case that we should handle on the client though. I'd really like to know why it's hanging, and not reporting an error.

**Comment by mbrennan** [comment]
I see.  If there's anything I can do to help you let me know.

**Comment by moiseevigor** [comment]
We have the similar issue, always with Atlassian. Did you find any solutions?
Here is the trace

```
GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push

18:45:22.972872 git.c:344               trace: built-in: git 'push'
18:45:22.973464 run-command.c:334       trace: run_command: 'ssh' 'git@bitbucket.org' 'git-receive-pack '\''groupp/repoo.git'\'''
18:45:24.445509 run-command.c:334       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@bitbucket.org:groupp/repoo.git'
18:45:24.449638 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@bitbucket.org:groupp/repoo.git'
18:45:24.449724 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@bitbucket.org:groupp/repoo.git'
18:45:24.459124 trace git-lfs: run_command: 'git' version
18:45:24.462023 trace git-lfs: run_command: 'git' config -l
18:45:24.465080 trace git-lfs: tq: running as batched queue, batch size of 100
18:45:26.073199 trace git-lfs: pre-push: refs/heads/master d3075da831a34d08da1f9883b95521d2fa28dd5f refs/heads/master 1aefc2592af566cbe0bd848e61ae70af68055b2c
18:45:26.073503 trace git-lfs: run_command: git rev-list --objects d3075da831a34d08da1f9883b95521d2fa28dd5f --not --remotes=origin --
18:45:26.076189 trace git-lfs: run_command: git cat-file --batch
18:45:26.081487 trace git-lfs: tq: sending batch of size 1
18:45:26.081777 trace git-lfs: api: batch 1 files
18:45:26.081831 trace git-lfs: creds: git credential fill ("http", "server-one:9999", "")
Username for 'http://server-one:9999': user
Password for 'http://user@server-one:9999': 
18:45:30.111265 trace git-lfs: Filled credentials for http://server-one:9999/
18:45:30.111530 trace git-lfs: HTTP: POST http://server-one:9999/objects/batch
> POST /objects/batch HTTP/1.1
> Host: server-one:9999
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 123
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.3.2 (GitHub; linux amd64; go 1.8.1)
> 
{"operation":"upload","objects":[{"oid":"11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","size":307374}]}18:45:30.115886 trace git-lfs: HTTP: 200


< HTTP/1.1 200 OK
< Content-Length: 513
< Content-Type: application/vnd.git-lfs+json
< Date: Wed, 04 Oct 2017 16:44:57 GMT
< 
18:45:30.119045 trace git-lfs: HTTP: {"objects":[{"oid":"11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","size":307374,"actions":{"download":{"href":"http://server-one:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"},"upload":{"href":"http://server-one:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"}}}]}
{"objects":[{"oid":"11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","size":307374,"actions":{"download":{"href":"http://server-one:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"},"upload":{"href":"http://server-one:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"}}}]}18:45:30.119211 trace git-lfs: tq: starting transfer adapter "basic"
Git LFS: (0 of 1 files) 0 B / 300.17 KB                                                                                                                                        18:45:30.119472 trace git-lfs: creds: git credential fill ("http", "server-one:9999", "")
Git LFS: (0 of 1 files) 0 B / 300.17 KB                                                                                                                                        ^C
Exiting because of "interrupt" signal.
18:45:46.913179 trace git-lfs: tq: retrying object 11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec: LFS: Git credentials for http://server-one:9999/ not found:
'git credential fill' error: signal: interrupt
```

**Comment by ttaylorr** [comment]
Hi @mbrennan, I agree with @-technoweenie's interpretation that this is an incorrect implementation of the Git LFS API specification. Since there is nothing that LFS can do about this, I am going to close this issue for now, but please let me know if there has been any update from Atlassian. Thanks!
