### ISSUE TITLE
progress meter doesn't update bytes transferred

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1926]
```
$ git lfs clone https://github.com/larsxschneider/lfstest-manyfiles
Cloning into 'lfstest-manyfiles'...
remote: Counting objects: 15012, done.
remote: Total 15012 (delta 0), reused 0 (delta 0), pack-reused 15012
Receiving objects: 100% (15012/15012), 2.02 MiB | 1.87 MiB/s, done.
Git LFS: (1798 of 1901 files) 0 B / 10.16 KB
```

Why is the first part stuck at `0 B`? 

I've also noticed that sometimes the command exits with an incorrect value:

```
$ git lfs clone https://github.com/github/git-lfs-test
Cloning into 'git-lfs-test'...
remote: Counting objects: 46, done.
remote: Total 46 (delta 0), reused 0 (delta 0), pack-reused 46
Unpacking objects: 100% (46/46), done.
Git LFS: (6 of 6 files) 780.54 KB / 818.95 KB
```

I think this is just a race condition. The command could be exiting before the progress meter has another chance to write to stdout.

**Comment by ttaylorr** [comment]
Huh, I've definitely run into this before, but I am not sure what's causing it. I'll look into this more next week.

**Comment by stoneburner** [comment]
i can confirm this bug, on my machine, the push command starts to count up to around 10-20 MB, then just stops updating the values, but the upload continues

**Comment by technoweenie** [comment]
@stoneburner what version of LFS are you on?

**Comment by stoneburner** [comment]
@technoweenie 
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)
git version 2.10.1 (Apple Git-78)

i see that they are quite old, i will install the newest version and check again!

**Comment by stoneburner** [comment]
@technoweenie i updated to 1.5.5, everything is fine!
(i installed the newest version with homebrew but forgot to link it, so there was an old version in use i was not aware of)
