### ISSUE TITLE
Missing objects on the server

### ISSUE THREAD

**Issue by rderimay** [git-lfs/git-lfs#1928]
I'm having a hard time with git-lfs and a situation where everything seems to be pushed/uploaded but where files are missing on the server.

1. I decided to make a new (git 2.11.1 / git-lfs 1.5.5) repo for our marketing files using git-lfs.
2. Everything were "successfully" pushed and uploaded to the server
3. To be sure I decided to clone the repo and check everything for consistency with the original folder.
4. Files are missing.

On the original folder ``git push`` / ``git lfs push`` are all happy. Nothing to upload.
On the cloned repo, ``git pull`` / ``git lfs pull``  / ``git lfs fetch`` / ``git lfs fetch --all`` are happy, but ``git lfs ls-files`` shows about 20 files with "-" in front.

Why a ``git push`` on the source folder does not trigger an upload of the missing files on the server ?
Is there a way to run a check to see which files are missing from the server ?

Thanks !

**Comment by technoweenie** [comment]
> Why a git push on the source folder does not trigger an upload of the missing files on the server ?

1. There's no `.git/hooks/pre-push` hook. Git LFS should be installing this automatically when you run commands like `git lfs [ install | update | track ]`.
2. The LFS pre-push hook scans the range of Git commits being pushed for LFS pointers, and uploads those objects to the LFS server. It won't scan the entire Git history on every push, as that'd increase the push time as your repository history grows. It also doesn't scan commits in the local cache of the remote (in ref `refs/remotes/{remote-name}/{branch-name}`). Judging by steps 1 and 2, this doesn't sound like a problem with your workflow though.

You can run `git lfs push --all` to scan your entire local repository for LFS objects, and upload the missing ones to the server.

**Comment by technoweenie** [comment]
Oh yeah, one more thing:

> On the cloned repo, git pull / git lfs pull / git lfs fetch / git lfs fetch --all are happy, but git lfs ls-files shows about 20 files with "-" in front.

Do you have the `skip-smudge` option enabled? 

```sh
$ git lfs env | grep filter
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Do you have either `lfs.fetchinclude` or `lfs.fetchexclude` setup? See [include and exclude docs](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-fetch.1.ronn#L37).

**Comment by rderimay** [comment]
Hi there. Thanks for taking the time.

here is ENV:
```
git-lfs/1.5.5 (GitHub; darwin amd64; go 1.7.4)
git version 2.11.1
[REDACTED]
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by rderimay** [comment]
Using git lfs push --all origin master correctly recognises missing files on the server.
Not sure why git push or git lfs push does not.

Still, one file is throwing an authentication error. Could it be some sort of timeout as this file takes quite long to upload ?

```
Authentication required: Authorization error: https://...lfs/objects/6ea8ae6cc3fddf1bcb41eed39919988f9626c3e7b7705c753731b49f57747ef8/14892202043
```

**Comment by ttaylorr** [comment]
> Could it be some sort of timeout as this file takes quite long to upload ?

I don't think this is the case, since LFS knows how to retry objects that are expiring soon in the future.<sup>[[1](https://github.com/git-lfs/git-lfs/blob/2f85ddbffa01423dcf1996bbd1c4e16d1fe06567/tq/transfer.go#L110-L112)]</sup>

Unless your system clock is off, or your LFS server isn't sending back an `expires_at` field, I think we can rule this one out.

**Comment by rderimay** [comment]
Is there any way to get a detailed log on the client or on the server, so we can search for the reason ?

**Comment by ttaylorr** [comment]
@rderimay you can re-run the command on your LFS client with `GIT_TRACE=1` to get some extra information. If you send it here, make sure to block out any `Authorization` headers, or filenames that you don't want exposed.

If you'd like a bit more privacy, you can send it to support@github.com and it'll get routed to me 👍 .

**Comment by rderimay** [comment]
Hi there I have just forwarded you the log redacted file . There are 401 Authentication errors which I don't understand as all other files have been uploaded without problem.
Let me know, I really appreciate you taking the time to look at this.
