### ISSUE TITLE
Failing to push large files

### ISSUE THREAD

**Issue by hexxd** [git-lfs/git-lfs#1933]
I can't seem to push large files (.zip) to github. LFS (version 1.3.1 installed via Homebrew) returns the following error:

`remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.`
`remote: error: Trace: 63a488b53055cc71938b40da95b11be9`
`remote: error: See http://git.io/iEPt8g for more information.`
`remote: error: File vanilla-app.zip is 129.25 MB; this exceeds GitHub's file size limit of 100.00 MB`
`To https://github.com/hexxd/vanilla.git`
` ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/hexxd/vanilla.git'`

The order of operations I've been using is as follows:

1. Place the file in my local repository with git already initialized.
2. `git lfs track myfile`
3. `git add .gitattributes`
4. `git commit -m ".gitattributes"`
5. `git push`
6. `git add myfile`
7. `git commit -m "myfile"`
8. `git push`

What am I doing wrong?

**Comment by ttaylorr** [comment]
Hi @hexxd, thanks for opening this issue, and sorry to hear that you're having trouble! I think the problem lies in the existing state of your repository when you installed LFS:

> Place the file in my local repository with git already initialized.

Due to the way that Git works, the file you want to track with LFS (`myfile`) _cannot be staged_ before it is "tracked" via your `.gitattributes`. To fix this, you can do a hard reset to before you added the file and run `git lfs track myfile` before you `git add myfile`. I noticed that that _is_ the order it seems you ran those commands, but if the file `myfile` is _already_ staged, subsequent `git add`s are treated as no-ops.

A few other things you could take a look at:

1. Upgrade your Git LFS version to the latest, which is 1.5.5 and available via Homebrew. Just `brew update && brew upgrade git-lfs` and you should be good to go.
2. Make sure that Git LFS is installed correctly, by running `git lfs install`.

Let me know if you have any more trouble!

**Comment by hexxd** [comment]
This worked beautifully. I used BFG to clean the repo and then followed the same procedure above.

For what it's worth, I would definitely put something about cleaning the repo out (either with BFG or something else; I like BFG because I didn't have to start my repo from scratch) in the readme. I stumbled upon LFS when I realized I couldn't push 100M+ files to a repository I had already created, and I imagine the same is true for other users who are new to git and have the same problem.

**Comment by ttaylorr** [comment]
Happy to help!

**Comment by wsurles** [comment]
Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:

`git lfs migrate import --include="*.csv"`

I had large csv files with data. This added some small files too, but at least I can push.

**Comment by seinick** [comment]
@wsurles - your migrate command helped immensely. Thank you.

**Comment by lcd10415** [comment]
@hexxd ,hello, I meet the same issues when I commit my code that is 108.85MB. But Git remind me of that it exceeds GitHub's file size limit of 100.00 MB.so I must install git-lfs via homebrew

**Comment by diginsheetal** [comment]
$ git push -u origin master                                                                                                                                                                      Enumerating objects: 10843, done.                                                                                                                                                                Counting objects: 100% (10843/10843), done.                                                                                                                                                      Delta compression using up to 4 threads                                                                                                                                                          Compressing objects: 100% (7251/7251), done.                                                                                                                                                     Writing objects: 100% (10843/10843), 301.63 MiB \| 488.00 KiB/s, done.                                                                                                                            Total 10843 (delta 3375), reused 10843 (delta 3375)                                                                                                                                              remote: Resolving deltas: 100% (3375/3375), done.                                                                                                                                                remote: warning: File atms_last.zip is 50.27 MB; this is larger than GitHub's re                                                                                                                 commended maximum file size of 50.00 MB                                                                                                                                                          remote: warning: File vms.zip is 63.71 MB; this is larger than GitHub's recommen                                                                                                                 ded maximum file size of 50.00 MB                                                                                                                                                                remote: error: GH001: Large files detected. You may want to try Git Large File S                                                                                                                 torage - https://git-lfs.github.com.                                                                                                                                                             remote: error: Trace: 7df7ae259e9e4f377519f6a816738371                                                                                                                                           remote: error: See http://git.io/iEPt8g for more information.                                                                                                                                    remote: error: File atms_last/atms/Reports/leave_approval_report_fc4bc09984867f4                                                                                                                 f66e4912968a06090.csv is 109.66 MB; this exceeds GitHub's file size limit of 100                                                                                                                 .00 MB                                                                                                                                                                                           To https://github.com/diginsheetal/bridgestone_CLMS.git                                                                                                                                           ! [remote rejected] master -> master (pre-receive hook declined)                                                                                                                                error: failed to push some refs to 'https://github.com/diginsheetal/bridgestone_                                                                                                                 CLMS.git'
--

PLZ Give me solution

**Comment by bk2204** [comment]
For those of you that are looking for a better solution in modern versions of Git LFS, the tool you're probably looking for is `git lfs migrate import` and it can take `--include` options which specify the pathspecs to migrate. Be sure to quote the pathspecs if they contains any characters special to the shell, such as "*".

https://github.com/git-lfs/git-lfs/issues/1933#issuecomment-351275765 provides a great example of how to use this functionality.

**Comment by SuninKingdom** [comment]
Helps a lot! Thank you!

**Comment by lianatumikyan** [comment]
@wsurles  Your solution was really helpful. Thanks a lot !

**Comment by NoahTheGr8** [comment]
Awesome solution. What can someone do to initially avoid this? I went to the git lfs page and followed instructions but this worked and the instructions didn't.

**Comment by abushoeb** [comment]
> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

You are the lifesaver and I should have noticed that from all the reaction emojis you received 🕺

**Comment by ahcyip** [comment]
Unfortunately I get
git lfs migrate import --include="*.csv"
migrate: Fetching remote refs: ..., done.                                                                                                                                                     
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 128 fatal: bad revision '^refs/remotes/origin/1.0.0'

**Comment by bk2204** [comment]
@ahcyip You may want to verify that you're using the latest version, since we've fixed several issues with that error message.  If you're still seeing a problem, please open a new issue, fill out the issue template, and provide reproduction steps.

**Comment by StupidRepo** [comment]
This is happening to me at the moment and I've tried everything, I can't fix this stupid error. I really hate GitHub and Git LFS for wasting my time. I've searched up for about 30 minutes now, trying every solution I see but none works. Please fix this.

Error:

```
remote: error: Trace: [not sure if this is private info]
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File [file].zip is 245.90 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:StupidRepo/[git].git (I AM LITERALLY TRYING IT RIGHT NOW!)
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'github.com:StupidRepo/[git].git'
```

It's not working.

**Comment by bk2204** [comment]
Hey,

This is likely because you have large files somewhere in your history even though you may have changed to use Git LFS in the latest commit.  Since we get this a lot, can you please follow [the directions in the last FAQ entry](https://github.com/git-lfs/git-lfs/wiki/FAQ) to see if they help you, and if you're still having problems, please open a new discussion as outlined in the contributing documentation?  I've just added the FAQ entry, so if you looked there before, that's why it wasn't there before.

**Comment by ifeoluwaayo** [comment]
Still getting the issue after changing my Git LFS.... any other way out?

**Comment by ifeoluwaayo** [comment]
> Still getting the issue after changing my Git LFS.... any other way out?

Would deleting that repo and opening another one to push the codes again work?

**Comment by lucacm** [comment]
> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

omg you helped me so hard thank you!

**Comment by JayanaGunaweera01** [comment]
@wsurles  Thanks a lot :)  !

**Comment by adityank11** [comment]
> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

This worked for me, thanks!

**Comment by Pravin69** [comment]
Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:

    git lfs migrate import --include="*.csv"

    I had large csv files with data. This added some small files too, but at least I can push.

This worked for me, thanks! @wsurles

**Comment by munish-on-git** [comment]
> > Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> > `git lfs migrate import --include="*.csv"`
> > I had large csv files with data. This added some small files too, but at least I can push.
> 
> You are the lifesaver and I should have noticed that from all the reaction emojis you received 🕺

it really help thanks a lot...

**Comment by daniyal214** [comment]
> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

Thanks that worked like a champ!!!

**Comment by gilangwokeh** [comment]
I still have errors

**Comment by appiniakhil** [comment]
remote: Resolving deltas: 100% (4/4), completed with 1 local object.
remote: error: Trace: fe25667905601d8e654630fbefc31e50d0eb91536d8103c758b3026d1015aac8
remote: error: See https://gh.io/lfs for more information.
remote: error: File best_model.h5 is 254.71 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File leaf_classification_model.h5 is 254.71 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/appiniakhil/Medicinal-Plant-Leaf-Detection.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/appiniakhil/Medicinal-Plant-Leaf-Detection.git'

**Comment by PhilipeFernandino** [comment]
> *



> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

To anyone reading this in the future: be cautious. Not only did this corrupt all of my PSDs, but it also rewrote the entire history. I don't know if I'll be able to recover, but this is not a safe solution—perhaps not a solution at all.

**Comment by PhilipeFernandino** [comment]
> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

I had a little panic moment after doing this and opening my Unity project too see that all of my now tracked Git LFS files seemed broken. This occurred because all of the files were replaced with a Git LFS pointer file containing information about the remote file. Running ``git lfs checkout`` brings the actual contents of the file back to the repository.

**Comment by sdmanson8** [comment]
I removed a pending commit in the GitHub GUI (wasn't sure how to do it via CLI). Then, I followed these steps:

Used the following command to migrate files to Git LFS:
`git lfs migrate import --include="*.csv"`
Re-added the files because `git lfs checkout` didn’t work for me:
`git add <file>`
`git commit -m "<comment>"`
`git push --all --force`

It is now showing in my repo

**Comment by Abuhurera-coder** [comment]
> Trying to get git-lfs working when you have already committed large files is a total mess. Just rewrite your history they said. I really have no idea how to do that. But.... this seems to do it all for you:
> 
> `git lfs migrate import --include="*.csv"`
> 
> I had large csv files with data. This added some small files too, but at least I can push.

**Comment by Abuhurera-coder** [comment]
This is what i needed thanks

**Comment by douxiaobo** [comment]
> I removed a pending commit `git reset --hard HEAD~1`. Then, I followed these steps:
> 
> Used the following command to migrate files to Git LFS: `git lfs migrate import --include="*.<extension>"` Re-added the files because `git lfs checkout` didn’t work for me: `git add <file>` `git commit -m "<comment>"` `git push --all --force`
> 
> It is now showing in my repo
> 
> I was then able to commit all my smaller files and push it to the repo

非常感谢您
