### ISSUE TITLE
libgit2 friendly library core?

### ISSUE THREAD

**Issue by zezba9000** [git-lfs/git-lfs#1934]
Is it possible to design git-lfs as having a library core that can in turn be easily used with gitlib2 without the need for clean/smudge filters or maybe I should say without the need for stdin/stdoutl? A lib i could invoke from a "C' app?

The issue with git-lfs as it stands now, is the requirement for git and stdin/stdout. This #1 causes performance issues on Windows and #2 isn't compatible with libgit2 without git-core being installed.

It would be cool to have the best of both works like would be possible with libgit2 if a stdin/stdout layer was added and replacing git core.

I hope this question is clear.

**Comment by ttaylorr** [comment]
Hi @zezba9000, thanks for opening this. Here are some of my thoughts on your questions:

> A lib i could invoke from a "C' app?

Technically this is possible, though our library code isn't designed for it. You can compile LFS with `cgo` like:

```bash
$ go tool cgo *.go
```

which will give you linkable libraries you can call over FFIs. More information about that can be found [here][1].

In particular, you'd have to link to [`lfs.PointerSmudge`][2] and [`lfs.PointerClean`][3]. These functions use Go types from the standard library not available in C, so my guess is that you'd have to write your own library wrapping those APIs with C-compatible types. This is certainly possible, but not something the LFS team has on its roadmap currently.

In response to your other note:

> This #1 causes performance issues on Windows

As of Git LFS [v1.5.0][4] the clean/smudge operations are about 70x faster on Windows.

[1]: https://medium.com/using-go-in-mobile-apps/using-go-in-mobile-apps-part-1-calling-go-functions-from-c-be1ecf7dfbc6#.r58fvt1gl 
[2]: https://github.com/git-lfs/git-lfs/blob/2f85ddbffa01423dcf1996bbd1c4e16d1fe06567/lfs/pointer_smudge.go#L39
[3]: https://github.com/git-lfs/git-lfs/blob/2f85ddbffa01423dcf1996bbd1c4e16d1fe06567/lfs/pointer_clean.go#L21
[4]: https://github.com/git-lfs/git-lfs/releases/tag/v1.5.0

**Comment by ttaylorr** [comment]
> As of Git LFS [v1.5.0](https://github.com/git-lfs/git-lfs/releases/tag/v1.5.0) the clean/smudge operations are about 70x faster on Windows.

A quick follow-up, Git v2.11.0 or greater is required for this release to work with the new `process` filter, which is what makes things quick.

**Comment by zezba9000** [comment]
Ok tnx for the info.
