### ISSUE TITLE
`git lfs status` should know why files are changed

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1941]
It'd be great if `git lfs status` could tell you why LFS files are marked as updated.

1. Was the file actually updated?
2. Is a regular git blob being converted to an LFS blob?

Probably some other things it could do, but this is a good start.

**Comment by ttaylorr** [comment]
Sounds good, I think we can get this into v2.0.0.

**Comment by ttaylorr** [comment]
Closing this out as of #2070. 🎉
