### ISSUE TITLE
confusing error message regarding locking on every git push

### ISSUE THREAD

**Issue by lloyd** [git-lfs/git-lfs#1943]
```
$ git push origin master
>> WARNING: Unable to search for locks contained in this push.
>>         Temporarily skipping check ...http: http: Unable to verify locks
Docs: https://github.com/contact
Request ID: B2F6:7899:5828562:761989A:58A382D2
Counting objects: 3, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 266 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local objects.
To github.com:lloyd/lfsplay.git
   4df31f2..bfc5f40  master -> master
```
```
$ git-lfs version
git-lfs/2.0-pre (GitHub; linux amd64; go 1.7.5)
[lloyd@scylla (dev) ~/dev/lfsplay]$ git version
git version 2.11.1
```

Steps to reproduce: create a repo on GitHub, add track and push an lfs file, then make a small commit and push to it.

Expected: no warnings

Got: a scary warning about locks.

What is the nature of the warning message "Unable to search for locks contained in this push"?  Do I need to care about it?  What can I do to make it go away or resolve the underlying problem that it is indicating?

**Comment by ttaylorr** [comment]
Hi @lloyd, thanks for opening this issue. That warning is on `master` right now and isn't yet published in a release. It's to let users know that the LFS remote doesn't yet support lock verification (which is a new feature), and therefore the pre-push command can't verify if any of the locked files contained in your push were legal to push.

That said, you don't need to worry about it, the push will still occur as expected.

**Comment by lloyd** [comment]
@ttaylorr thank you so much for the prompt and clear explanation.  It sounds like we need to use the latest stable tagged version and we can not be frightened by warning messages.

Happy Valentine's Day!  🎁
