### ISSUE TITLE
Git subtree pull is not working with git LFS 

### ISSUE THREAD

**Issue by anshulgarg11** [git-lfs/git-lfs#1948]
My git repositories setup:

Repository1 -> Child : It has many files in LFS
Repository2 -> Parent : This is a container repo
I want to make a subtree inside parent repo and make child repo a subtree node.

Step -1 : 
(Under parent repo)
git subtree add --prefix child http://X.X.X.X/child master

This gives me following error 
**Smudge error: Error buffering media file: Object not found on the server.:**

Then I followed this fix: https://github.com/git-lfs/git-lfs/issues/854
which is : git lfs push Child master --all (push in to parent from child repo)

It make sense and every thing worked like a charm, but now
**If I add some new file in child LFS then How should I get that new file in parent repo using subtree pull?**

Doing this:
git subtree pull --prefix child http://X.X.X.X/child master is giving me this error again:

**Smudge error: Error buffering media file: Object not found on the server.:**

Many Thanks in advance

**Comment by ttaylorr** [comment]
Hi @anshulgarg11, thanks for opening this issue, and sorry that you're having trouble. I think to migrate the files over, you could re-install LFS with the smudge filter disabled (`git lfs install --skip-smudge`) and move the files between the parent/child trees, and then restore them individually with the smudge filter re-enabled.

**Comment by ttaylorr** [comment]
Hi @anshulgarg11, Git LFS currently does not support subtrees, and this is not currently an item on our ROADMAP. That said, if someone is interested in taking this on, I would be more than happy to help them through any challenges.

Until then, I am going to close this issue.

**Comment by mloskot** [comment]
@ttaylorr 
> Git LFS currently does not support subtrees, and this is not currently an item on our ROADMAP. 

Could you confirm this is still true?

The [changelog <=2.6.0]( https://github.com/git-lfs/git-lfs/blob/183d7341006c799f6dbaa24d2c33bcb235f619f2/CHANGELOG.md) does not mention `subtree`, so I think it is. Correct?

**Comment by bk2204** [comment]
> > Git LFS currently does not support subtrees, and this is not currently an item on our ROADMAP.
> 
> Could you confirm this is still true?

This is still true.  It may happen to work (or not), but support for it isn't something we have planned.  Of course, someone is free to pick it up if they'd like to implement it.

**Comment by mloskot** [comment]
@bk2204 Thanks for the confirmation.

**Comment by guitarrapc** [comment]
Is it still not supporting? I've tried and got same issue.

**Comment by mloskot** [comment]
@guitarrapc read the last comment by @bk2204 It should explain the status.

**Comment by hezhijun80** [comment]
y

**Comment by guitarrapc** [comment]
thanks. got it.

**Comment by max-critcrew** [comment]
Is there an update to this? :)

**Comment by bk2204** [comment]
My previous comment stands:

>  It may happen to work (or not), but support for it isn't something we have planned. Of course, someone is free to pick it up if they'd like to implement it.

As far as I'm aware, nobody on the core team uses subtrees (I use submodules instead), so nobody here has the expertise to implement this or make it work without seeing an external patch.  I don't expect that will change anytime soon.

If this functionality ever appears in a public release, it will be in the changelog.

**Comment by max-critcrew** [comment]
Many thanks for the quick response. You really helped me out here!

**Comment by jtroe** [comment]
I (seem to, based on being able to clone and fetch the lfs items) have git-lfs working as a subtree by adding the `.lfsconfig` from the subtree repo to the root of the host repo, however this commandeers any lfs usage from this repo.  In addition, there can only be one config, so adding another subtree to a different repo with lfs doesn't work.

It seems to me that a workable solution could be having path-dependent configs in the lfsconfig:
```toml
[lfs.path.path/to/subtree-a]
url = "https://my.gitlfsapi.local/subtree-a"

[lfs.path.path/to/subtree-b]
url = "https://my.gitlfsapi.local/subtree-b"
```

Excuse my example, I don't know if the path in the key is syntactically correct here, just trying to provide my thought process.
