### ISSUE TITLE
Install without admin access on Windows

### ISSUE THREAD

**Issue by bbodenmiller** [git-lfs/git-lfs#1964]
It appears Git LFS cannot be installed without administrator access on Windows. Git for Windows can be however. Please add support or details on how to install Git LFS without admin access.

![image](https://cloud.githubusercontent.com/assets/1192780/23142265/e721c730-f76f-11e6-9a11-866f6738b819.png)

**Comment by ttaylorr** [comment]
@bbodenmiller thanks for opening this issue, and sorry that you're having trouble. I took a quick look to refresh my memory on how our Windows installation process works, and I don't see anything that would necessitate administrator access to successfully install LFS.

That said, I imagine that there are Windows configurations that forbid non-admin users from installing executables on the computer. Would you mind double checking that that isn't the case?

**Comment by bbodenmiller** [comment]
That doesn't appear to be the case here. Do you know where in the LFS installer code I could see where it might be causing this alert?

Here's some screenshots comparing Git for Windows and Git LFS installation on the same machine running as a non-admin user. As you can see Git for Windows installs but Git LFS doesn't make it anywhere. 😞 

![image](https://cloud.githubusercontent.com/assets/1192780/23147041/d574fc52-f790-11e6-8587-8ced8e1a168a.png)
![image](https://cloud.githubusercontent.com/assets/1192780/23147046/df8130bc-f790-11e6-8e1f-fef29976e1d9.png)
![image](https://cloud.githubusercontent.com/assets/1192780/23147064/fdc00152-f790-11e6-8a8d-445e0ed31c51.png)

**Comment by ttaylorr** [comment]
@bbodenmiller thanks for posting. The contents of our Windows Installer is [here](https://github.com/git-lfs/git-lfs/blob/master/script/windows-installer/inno-setup-git-lfs-installer.iss), but I was unable to find anything that would indicate a need for administrative privileges.

@sschuberth is more of an expert in this area than I am, so perhaps he could help.

**Comment by sschuberth** [comment]
@bbodenmiller Would you mind trying the installer from https://ci.appveyor.com/api/buildjobs/23511y185oxf3gv6/artifacts/git-lfs-windows-1.5.0.exe?

**Comment by dcorbin-wintellect** [comment]
Git-2.33.0.2-64-bit.exe  -- prompts for Administrator, and can not go past it....

**Comment by KalleOlaviNiemitalo** [comment]
@dcorbin-wintellect, Git-2.33.0.2-64-bit.exe is published from <https://github.com/git-for-windows/git/>, so if you have problems with installing it, you'd better report them there.

**Comment by dcorbin-wintellect** [comment]
I am nderstand. I was posting here to indicate that the previous posted information (2017) no longer appears to be correct.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
