### ISSUE TITLE
git-lfs failes to work on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by moritz-wundke** [git-lfs/git-lfs#1970]
For those of us who use git on Bash on Windows (https://msdn.microsoft.com/es-es/commandline/wsl/about) using git-lfs on it would be quite handy. Git itself performs faster then using the windows git port.

When pushing refs using git-lfs it just hangs and then failes with the following output:

```
Git LFS: (0 of 1 files) 519.21 KB / 49.64 MB
http: Put <obj/url/here>: EOF
error: failed to push some refs to '<git/repo/here>'
```

The `<>` parts are just stubs to where the real stuff is ^^

**Comment by technoweenie** [comment]
Bash on Windows is pretty new, so it's not _that_ surprising things don't work. What does `git lfs env` show?

**Comment by moritz-wundke** [comment]
New things tend to break ^^

Here is the log:

```
git-lfs/1.5.5 (GitHub; linux amd64; go 1.7.4)
git version 2.10.2

Endpoint=https://<git/host>/test-lfs.git/info/lfs (auth=none)
  SSH=git@<git/host>:test-lfs.git
LocalWorkingDir=/mnt/c/Repos/test-lfs
LocalGitDir=/mnt/c/Moss/test-lfs/.git
LocalGitStorageDir=/mnt/c/Repos/test-lfs/.git
LocalMediaDir=/mnt/c/Repos/test-lfs/.git/lfs/objects
LocalReferenceDir=
TempDir=/mnt/c/Repos/test-lfs/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by technoweenie** [comment]
An `EOF` sounds more like a server issue. Based on your `env` output, assuming the paths are all correct. Does this work in the Bash env that Git for Windows sets up?

**Comment by moritz-wundke** [comment]
Yep it works well from a native linux box, a mac and a windows thourgh git lfs for windows. The only place where it fails is on Bash On Windows.

**Comment by technoweenie** [comment]
Cool, thanks for the report. I've added this to our roadmap. It's probably too soon to make the next release (unless someone else can contribute fixes).

**Comment by moritz-wundke** [comment]
If I get some free time I might be able to have a look but good to have it
on the roadmap

On Feb 22, 2017 5:35 PM, "risk danger olson" <notifications@github.com>
wrote:

Cool, thanks for the report. I've added this to our roadmap. It's probably
too soon to make the next release (unless someone else can contribute
fixes).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/git-lfs/git-lfs/issues/1970#issuecomment-281723778>,
or mute
the thread

**Comment by larsxschneider** [comment]
Bash on Ubuntu is not ready for Git (and therefore I would expect problems for GitLFS as well):
https://groups.google.com/d/msg/git-for-windows/SCViPjCsGgI/yMKaw2XvEQAJ
(Johannes Schindelin is the Git for Windows maintainer)

**Comment by evitolins** [comment]
Having a very similar issue with someone on our dev team using Window's Ubuntu Bash, LFS v1.5.6 and Gitlab as our remote.

As we have Windows, Mac and Linux dev envs... it'd be ideal to keep everyone in a Linux terminal.  Looking forward to a solution.

Here's some output from our failed push attempt.  Further push attempts failed or hung without any feedback or logs.

```
http: Put <remotepath>/gitlab-lfs/objects/eadb1264c95ffd1e3fba211d317a7d578888ae3d404b86b89ee7b95b20e4b06e/807312: EOF
http: Put <remotepath>/gitlab-lfs/objects/eca0158e3e7726202312037dc31e1b46d3a789ac32f4d3d8e346140f60a70aa5/582044: EOF
http: <remotepath>/gitlab-lfs/objects/28bd4bc6ab8fa7a4cc71508a5deed19aacc6d069ea21ede988d4edde6bb61a2d/584419: EOF
error: failed to push some refs to <remotepath>
http: Put <path>/objects/eadb1264c95ffd1e3fba211d317a7d578888ae3d404b86b89ee7b95b20e4b06e/807312: EOF
http: <remotepath>/gitlab-lfs/objects/eca0158e3e7726202312037dc31e1b46d3a789ac32f4d3d8e346140f60a70aa5/582044: EOF
http: Put <remotepath>/gitlab-lfs/objects/28bd4bc6ab8fa7a4cc71508a5deed19aacc6d069ea21ede988d4edde6bb61a2d/584419: EOF
error: failed to push some refs to '<remotepath>'
```

#### Ran

#### Results after `git lfs logs last` after a `git lfs push --dry-run origin <branch>`
```
git-lfs/1.5.6 (GitHub; linux amd64; go 1.7.4)
git version 1.9.1

$ git-lfs push --dry-run origin <branch>
Error scanning for Git LFS files in the "<branch>" ref

Error in git rev-list --objects: exit status 128 fatal: bad revision '<branch>'


ENV:
LocalWorkingDir=/mnt/d/chani/HP/Assembly_SaltLake - Master - Copy
LocalGitDir=/mnt/d/chani/HP/Assembly_SaltLake - Master - Copy/.git
LocalGitStorageDir=/mnt/d/chani/HP/Assembly_SaltLake - Master - Copy/.git
LocalMediaDir=/mnt/d/chani/HP/Assembly_SaltLake - Master - Copy/.git/lfs/objects
LocalReferenceDir=
TempDir=/mnt/d/chani/HP/Assembly_SaltLake - Master - Copy/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
```

**Comment by SRombauts** [comment]
This is fixed in the [Windows 10 Creators Update release yesterday 2017/04/05](https://www.microsoft.com/en-us/software-download/windows10) 👍 

I did a fresh install of the "Bash" Windows Subsystem for Linux:

```
srombauts@ASUS-SEB:~$ lsb_release  -a
Description:    Ubuntu 16.04.2 LTS
...
git version 2.11.0
...
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8)
```

Regards!
