### ISSUE TITLE
Cloning with the smudge filter disabled still downloads big files

### ISSUE THREAD

**Issue by monoburn** [git-lfs/git-lfs#1973]
I'm attempting to clone a repo with some very big files, but since I don't always need them, I'm doing a "shallow" cloning:
`git lfs install --force --skip-smudge`
`git lfs clone git@something.something.git`
Also tried
`GIT_LFS_SKIP_SMUDGE=1 git lfs clone git@something.something.git`

The smudge filter seems to have been set correctly:
`git lfs env`
 shows 
```
git-lfs/1.5.5 (GitHub; darwin amd64; go 1.7.4)
git version 2.11.0
...
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
```
My understanding is that the smudge filter looks at the file blob and downloads whatever is referenced in the blob. Having configured the --skip option should prevent download when cloning.

Am I doing something wrong? Or is the repo/LFS server set up incorrectly?

Any help is highly appreciated.

Erik

**Comment by ttaylorr** [comment]
What is the behavior with `git clone` (not using the LFS wrapper?) You should be fine to run this, since skipping the smudge filter won't download any large files, so there's no penalty paid by the sequential behavior of `git clone`.

**Comment by technoweenie** [comment]
Hi @monoburn, this looks like a misunderstanding of what `git lfs clone` is doing. It's essentially running this:

```sh
$ GIT_LFS_SKIP_SMUDGE=1 git clone git@something.something.git
$ cd something
$ git lfs pull
```

You can tell Git LFS to ignore all LFS downloads like this:

```sh
$ git lfs clone git@something.something.git -X "*.*"
```

The [`git lfs clone` command has include/exclude flags](https://github.com/git-lfs/git-lfs/blob/43cad0b0a54aaa42a860d6df38d32dd21f45542e/docs/man/git-lfs-clone.1.ronn#L25-L26) to control what's downloaded. The `fetch` and `pull` commands accept the same flags, and include [info on making this configuration default if you want](https://github.com/git-lfs/git-lfs/blob/43cad0b0a54aaa42a860d6df38d32dd21f45542e/docs/man/git-lfs-fetch.1.ronn).

**Comment by medington** [comment]
There seems to have been some change in behavior between Git 1.8.x and Git 2.11.1 with regards to disabling the LFS smudge filter. When using Git 1.8.3 using:

  git config --global filter.lfs.smudge "git-lfs smudge --skip %f"

before executing a git clone (not git lfs clone) would prevent lfs artifacts from being downloaded. With Git 2.11.1 this setting alone does not appear to prevent download on it's own.

Upon further testing I discovered that it's also necessary to have the --skip specified on the process config using:

    git config --global filter.lfs.process "git-lfs filter-process --skip"

Both of these are automatically configured when using the full:

    git lfs install --skip-smudge

Anyway, sharing this here in case anyone else runs into this.

**Comment by monoburn** [comment]
My initial observations were wrong. The smudge filter config works as intended (preventing LFS downloads)!

I interpreted the lengthy/big cloning  (which I terminated before it finished) as a LFS downloads. However the reason was a huge file that was previously committed, and even though the file itself was removed, it's still part of the git history and it resulted in a huge pack file (in .git/objects/pack, which is how git efficiently stores file content in a packed/compressed manner).

Doing a
```
git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
git clone git@something.something.git
```
works as intented (preventing LFS downloads) for both git 1.8.3.1 and 2.11.0.

So my task is now remove the big commit from the history. That's a another story.

Thanks for all your input and effort.

**Comment by sactiw13** [comment]
_>>> However the reason was a huge file that was previously committed,_
Just to be sure, this huge file wasn't a LFS file object right?

**Comment by monoburn** [comment]
Right. The "huge" was a normal file, not a LFS file.

**Comment by ttaylorr** [comment]
> Right. The "huge" was a normal file, not a LFS file.

In this case the `git lfs migrate import` command (and its related
counterparts) can be helpful. Since this is an older issue, I'd
recommend that if you're having more trouble later on, please open a new
issue (and we'd be more than happy to help out).
