### ISSUE TITLE
git-lfs & submodules do not play nice together

### ISSUE THREAD

**Issue by lacombar** [git-lfs/git-lfs#1974]
There is no way to pass parameters to git-lfs from a repository to an LFS-enabled submodules, in a *LOCAL* fashion.

More precisely, the following does *not* work as intended:

```
$ git clone /path/to/repo.git
$ cd repo
$ git config --local lfs.fetchinclude 'external/linux/'
$ git submodule update --init
Downloading external/android/package.apk (1.23 MB)
```

[ note: this use-case prohibit usage of --global as it may collide with other repositories ]

**Comment by technoweenie** [comment]
Without Git adding some general hook, I think our options here are:

* Add env var for this: `LFS_FETCHINCLUDE="external/linux/" git submodule update --init`
* Add custom command? `git lfs submodule-update`...

You may be able to do this with something like:

    $ git -c "lfs.fetchinclude=external/linux/" submodule update --init
