### ISSUE TITLE
What am I doing wrong in tracking a file with LFS process?

### ISSUE THREAD

**Issue by BarryAllenJr** [git-lfs/git-lfs#1984]
How do i upload files to LFS? They were added to repo but only than tracked with LFS
*
Git LFS: (0 of 0 files, 3 skipped) 0 B / 0 B, 302.44 MB skipped                                                       Counting objects: 170, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (168/168), done.
Writing objects: 100% (170/170), 117.23 MiB | 457.00 KiB/s, done.
Total 170 (delta 78), reused 0 (delta 0)
remote: Resolving deltas: 100% (78/78), completed with 25 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: d13a996f8ac94b4f85818793cc5d9d48
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Content/Levels/gameMapBackedUp_BuiltData.uasset is 115.55 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/BarryAllenJr/CSM.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/BarryAllenJr/CSM.git'
*
Halp ():

**Comment by ttaylorr** [comment]
Hi @BarryAllenJr, thanks for opening this and sorry that you're having trouble. Based on your logs, I think there are a few issues at play:

> ```
> Git LFS: (0 of 0 files, 3 skipped) 0 B / 0 B, 302.44 MB skipped
> ```

When Git LFS "skips" a file, it indicates that the server already has it, so it doesn't need to reupload the object. This means that the remote _does_ have your object(s) already.

> ```
> remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> ```

This means that the large file is still committed in it's entirety somewhere in your Git history. To stop uploading the large blob outside of LFS, you can:

1. Reset to a point _before_ you committed the large blob into Git, and then retrack it under LFS, or...
2. Use a tool like BFG (or a `filter-branch` command) and remove the object from Git.

Please don't hesitate to re-open this issue if you have any further questions.
