### ISSUE TITLE
Git LFS is using a deprecated API, which will be removed in v2.0.

### ISSUE THREAD

**Issue by markknol** [git-lfs/git-lfs#1985]
Hi, sorry for this probably stupid question, but I try to use git lfs on a new project but get some errors. I never experienced this issue before. My gitattributes file looks like this:

```
*.swf filter=lfs diff=lfs merge=lfs -text
*.fla filter=lfs diff=lfs merge=lfs -text
```
Then I try to push, but I get this error:

```
git.exe push -v --progress "origin" master:master

Pushing to git@git.assembla.com:xxxx/xxxx.git
WARNING: Git LFS is using a deprecated API, which will be removed in v2.0.
Consider enabling the latest API by running: `git config lfs.batch true`.
Git LFS: (0 of 2 files) 0 B / 1.75 MB
upload check: exit status 255: Welcome! You have successfully authenticated.
Please use Git client to access your repository, Assembla does not provide shell access.
upload check: exit status 255: Welcome! You have successfully authenticated.
Please use Git client to access your repository, Assembla does not provide shell access.
error: failed to push some refs to 'git@git.assembla.com:xxxx/xxxx.git'
```

I runned `git config lfs.batch true` but I'm not sure what it does since it doesn't log/output anything.

Now I cannot push anything anything anymore. Not sure if this is related to my configuration or Assembla's configuration. 

This is my setup: 

* git-lfs/1.5.6 (GitHub; windows amd64; go 1.7.5; git bbd328b1)
* git version 2.10.2.windows.1

Can you help me out?

**Comment by ttaylorr** [comment]
Hi @markknol, thanks for opening this up. The latest version of LFS, which you're running, has marked the batch API as deprecated, and it will be removed in v2.0.0. There are a few things that could be going on here:

1. Your server doesn't support the LFS batch API<sup>[[1](https://github.com/git-lfs/git-lfs/blob/master/docs/api/batch.md)]</sup>. This means that you have to either stay on the current version of LFS, or implement the batch API on the server to upgrade.
2. You've configured LFS to _not_ use the Batch API. It looks like you did configure it correctly (`git config lfs.batch true`), so perhaps try re-running the command again and see what happens.

If you have any other problems, please don't hesitate to re-open this issue.
