### ISSUE TITLE
Files are skipped, while pushing code

### ISSUE THREAD

**Issue by SavageTechnologies** [git-lfs/git-lfs#1992]
I'm trying to push my code to github repository and I can see the following error. I installed git lfs to track large files, but I can see that they are being skipped. 
Could anyone help me with this, please ?
Thank you. 

<img width="610" alt="capture" src="https://cloud.githubusercontent.com/assets/26069352/23466313/54be8624-fe60-11e6-8441-68e839e0ca46.PNG">
<img width="342" alt="capture1" src="https://cloud.githubusercontent.com/assets/26069352/23466460/cff6c590-fe60-11e6-937b-d1c25a29de95.PNG">

**Comment by technoweenie** [comment]
That message means you have old files in the git repository that are not using LFS, but exceed GitHub's blob size limits. Have you tried something like https://github.com/bozaro/git-lfs-migrate to migrate your older files?

**Comment by SavageTechnologies** [comment]
I haven't. And I'm not trying to push something new to old repository. I created an organisation account and a new repository.

**Comment by technoweenie** [comment]
The `git lfs track` settings are read from `.gitattributes`, so they don't affect old commits that you've already made. So, essentially you'll have to start over on `master`, run the `git lfs track` command to add those file patterns, and then add your changes that include `public/images/draft.mp4`.

**Comment by SavageTechnologies** [comment]
So do I need to use git-lfs-migrate ? or Is there any other way that I can do ?

**Comment by SavageTechnologies** [comment]
I figured it out. Thanks much.

**Comment by jonasty19** [comment]
@SavageTechnologies Can you elaborate on how you figured it out?  I'm running into the same issue here and completely stuck. :(

**Comment by ttaylorr** [comment]
Hi @jonasty19, thanks for commenting. I have a few thoughts to share, but if you run into additional trouble, please don't hesitate to open a new issue (and link to this thread).

Reading the original post, I think this is two things:

1. The "skipped" portion of the progress bar means that the remote LFS server already has the LFS objects that were requested to be uploaded. Since they're already present on the remote, there is no need to reupload them, thus they are skipped. This is not an error.
2. The "GH001" means that there are still large files somewhere in your repository as `@technoweenie` indicated, and can be fixed by running the `git-lfs-migrate(1)`'s 'import' sub-command. You can use `git lfs migrate info` with difference `--include-ref` and `--exclude-ref` combinations to find where the large files are in your history.

**Comment by jlbaxter** [comment]
Hello all, I'm trying to push an Xcode project to a fresh GitHub repository master branch for the first time. I've tried all of these recommendations and nothing's worked. The offending large files are two googlemaps files each 123MB in size. I got git lfs to add one of the files once, but it skipped the other. Now it skips both every time I try. It doesn't matter if I start over in the branch, backup, re-add, track, commit and push...it always skips and errors out. Any recommendations would be appreciated. Thanks!

**Comment by ttaylorr** [comment]
> it always skips and errors out

@jlbaxter skipping files is not considered an error (see: https://github.com/git-lfs/git-lfs/issues/1992#issuecomment-313244142). Can you post the error that you are seeing in a new issue, please?

**Comment by jlbaxter** [comment]
Hi @ttaylorr, I understand, to clarify it skips, then it errors. This is the error I'm seeing. Will open a new issue.

Jims-MacBook-Pro:pintip Jim$ git push -u origin master
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 123.08 MB skipped                                                                                                                     Counting objects: 1441, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1280/1280), done.
Writing objects: 100% (1441/1441), 75.53 MiB | 1.24 MiB/s, done.
Total 1441 (delta 472), reused 0 (delta 0)
remote: Resolving deltas: 100% (472/472), done.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: acc3634bb74e4c2efeb912c08a8e8b48
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps is 123.08 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/pintip/pintip.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/pintip/pintip.git'
