### ISSUE TITLE
Problems setting a lock.

### ISSUE THREAD

**Issue by gamefiend** [git-lfs/git-lfs#1993]
I have created a project to test git-lfs locking and I am running into some issues.

When I try to lock a file, I get the following error:

`Lock failed: Repository or object not found: https://lfs.github.com/github/<repo>/locks
`
When I push the repo upstream to GH, I get: 

`Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config 'lfs.https://github.com/github/<repo>/info/lfs.locksverify' false
`

Is there something I might still be missing from my config for locking to work?

Running this on OSX 10.12.3 with:
git 2.10.1 
git-lfs 2.0 (installed from the binary release install.sh, not Homebrew)

**Comment by technoweenie** [comment]
Hey @gamefiend :wave: I fixed something on the server, so you should be good to go now :)

**Comment by gamefiend** [comment]
Confirmed that it worked, thank you! Closing it out.
