### ISSUE TITLE
Git-LFS 2.0.0 Pre-Push "fatal: bad revision"

### ISSUE THREAD

**Issue by zezba9000** [git-lfs/git-lfs#1994]
**With Git-LFS 2.0.0 I'm getting an error I wasn't with 1.5.6.**

> Error in git rev-list --objects: exit status 128 fatal: bad revision ''

I'm pushing to a Linux GitLab server updated one month ago with git-lfs 1.5.5 on it.
I'm pushing from a Win10 PC.

Git-lfs is invoked like so:

> git-lfs pre-push origin

My stdin looks like:

> refs/heads/dev 32642eb19946df7a29209d4ed199c136c3d263fe refs/heads/dev 32642eb19946df7a29209d4ed199c136c3d263fe

This is being used with gitlib2sharp in Git-It-GUI here: https://github.com/reignstudios/Git-It-GUI/blob/master/GitItGUI.Core/ChangesManager.cs#L624

A working example can be done by running the app: https://github.com/reignstudios/Git-It-GUI/releases

**Comment by ttaylorr** [comment]
@zezba9000 thanks for opening this, and sorry that you're having trouble. I have a few ideas of what's going on, but I'd love to see the output of this command re-run with `GIT_TRACE=1` for reference.

Just as a heads up, your client _may_ generate some HTTP requests with an `Authorization` header, which you should be sure to blank out.

If your repository is private, or you don't feel comfortable posting those details here, you can feel free to send the logs to support@github.com and it'll be routed to me.

**Comment by zezba9000** [comment]
I'm moving away from libgit and directly invoking git commands. Which is how git-lfs was designed and doesn't have any issues.

I'll close this issue for now.
