### ISSUE TITLE
running lfs commands create Git processes that hang

### ISSUE THREAD

**Issue by nbenty** [git-lfs/git-lfs#1995]
I'm using git version 2.12.0.windows.1 with git-lfs/2.0.0.

After running 'git lfs' commands, I can see in the task manager that some GIT processes never quit.
The commands seam to complete succesuly. I also try running just 'git lfs'. It happens with that command as well.

This doesn't happen if I don't use 'git lfs'.

**Comment by ttaylorr** [comment]
@nbenty thanks for opening this issue. Would you mind the names of those processes, i.e., what Git commands they are?

**Comment by nbenty** [comment]
It's the git for windows processes:
* C:\Program Files\Git\cmd\git.exe
* C:\Program Files\Git\mingw64\bin\git.exe

For every command I run, these 2 are always executed and hang.

**Comment by ttaylorr** [comment]
@nbenty thanks for the quick reply. Is there anyway to determine in particular what Git commands those are? I'm not quite sure how to do that on Windows, since I'm a macOS user.

**Comment by nbenty** [comment]
I'm not sure. I think the git from the cmd directory invokes the executable from the mingw64 directory.
The one in mingw64 is the primary binary which contains all the commands. In my case, just running 'git' causes the hang (only after 'git lfs pull').

If you need help, I can build GIT for windows and look at what happens.

**Comment by ttaylorr** [comment]
> If you need help, I can build GIT for windows and look at what happens.

Let me know.

**Comment by technoweenie** [comment]
@nbenty you mentioned the processes hang after just running `git lfs`. I ran `GIT_TRACE=1 git lfs`, and see these git commands being run:

```sh
$ GIT_TRACE=1 git lfs
09:20:08.146659 git.c:588               trace: exec: 'git-lfs'
09:20:08.147108 run-command.c:345       trace: run_command: 'git-lfs'
trace git-lfs: run_command: 'git' config -l
```

I this is where we should start looking, so I don't think you need to build Git for windows or anything like that.

**Comment by nbenty** [comment]
I was about to do later today, you saved me some work.
Thanks!

**Comment by tfiner** [comment]
I have the same issue (as do some of my coworkers).  Some of the symptoms: no disk or network IO whatsoever for the parent process, or any of its children (viewable in Process Explorer).

**Comment by ttaylorr** [comment]
@tfiner sorry to hear that, but I'm glad that you were able to confirm that this isn't an isolated issue. Is it possible that you could get the names of which Git commands are being run so I could drill down on the LFS side of things and figure out which processes are being leaked?

**Comment by tfiner** [comment]
Of course, when I go to repro the problem, everything is working fine.  Next time it happens, I'll post something here.

**Comment by ttaylorr** [comment]
> Of course, when I go to repro the problem, everything is working fine. Next time it happens, I'll post something here.

No worries :). Thanks!

**Comment by ttaylorr** [comment]
Hi @tfiner, I am going to close this issue now since it has grown stale, and the problem does not appear to be recurrent. Please let me know if the issue appears again, and I'd be more than happy to take a look.
