### ISSUE TITLE
Chcecking-out a branch shows every lfs-tracked file as modified

### ISSUE THREAD

**Issue by nbenty** [git-lfs/git-lfs#1996]
It doesn't seem to result in an incorrect behavior, but would be nice if those messages could be suppressed.

**Comment by ttaylorr** [comment]
> It doesn't seem to result in an incorrect behavior

Could you let me know a few more details about the state of your repository, and specifically _why_ this isn't incorrect behavior?

**Comment by nbenty** [comment]
Actually, the issue happens with a simple 'git status'.
running 'status' calling 'lfs pull' shows all the lfs-managed files as modified.

I don't know if that's a wrong behavior, just unintuitive. I understand that from Git's POV the files are modified, but if you think of Git+git-lfs as a system, then the files weren't modified.

This actually explains #1997 - we can probably merge those 2 issues.

**Comment by ttaylorr** [comment]
> This actually explains #1997 - we can probably merge those 2 issues.

Good call, and thanks for clarifying. Let's close this one out and then move discussion over there.
