### ISSUE TITLE
Consider alternative man generation format toolchain to drop ronn dependency

### ISSUE THREAD

**Issue by jfkw** [git-lfs/git-lfs#2000]
The git-lfs man pages are provided in .ronn format. When I went to install dev-vcs git-lfs-2.0.0 as packaged on Gentoo Linux, the default configuration builds the documentation. This pulled in a large dependency set for app-text/ronn, including two versions of Ruby, shown below:

I'm not familiar with alternatives, but In light of ronn's dependencies, it may help more users install git-lfs on more systems if ronn were not required to build git-lfs docs. Omitting the documentation is certainly possible, and packagers can help insulate users from the build-time dependencies.

From my POV, once I start using git-lfs even a little bit, I need to also have it installed on every system and OS I have installed git (which is everywhere).

```
% sudo emerge git-lfs -pv
These are the packages that would be merged, in order:
Calculating dependencies  ...... done!
[ebuild  N     ] dev-util/colm-0.13.0.4::gentoo  692 KiB
[ebuild  N     ] app-eselect/eselect-ruby-20161226::gentoo  2 KiB
[ebuild  N     ] dev-util/ragel-7.0.0.9::gentoo  USE="-vim-syntax" 831 KiB
[ebuild  N     ] dev-lang/ruby-2.2.6:2.2::gentoo  USE="gdbm ipv6 jemalloc ncurses readline ssl -berkdb -debug -doc -examples -libressl -rdoc -rubytests -socks5 -tk -xemacs" 10,245 KiB
[ebuild  N     ] dev-lang/ruby-2.1.10:2.1::gentoo  USE="gdbm ipv6 ncurses readline ssl -berkdb -debug -doc -examples -rdoc -rubytests -socks5 -tk -xemacs" 9,146 KiB
[ebuild  N     ] dev-ruby/rubygems-2.6.10::gentoo  USE="-server {-test}" RUBY_TARGETS="ruby21 ruby22 (-ruby20) -ruby23 -ruby24" 748 KiB
[ebuild  N     ] virtual/rubygems-12::gentoo  RUBY_TARGETS="ruby21 ruby22 (-rbx) (-ruby20) -ruby23 -ruby24" 0 KiB
[ebuild  N     ] dev-ruby/minitest-5.10.1:5::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 (-ruby20) -ruby21 -ruby23 -ruby24" 73 KiB
[ebuild  N     ] dev-ruby/power_assert-1.0.1-r1::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 16 KiB
[ebuild  N     ] dev-ruby/test-unit-3.2.3:2::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 (-ruby20) -ruby21 -ruby23 -ruby24" 123 KiB
[ebuild  N     ] dev-ruby/rake-12.0.0::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby21 ruby22 (-ruby20) -ruby23 -ruby24" 115 KiB
[ebuild  N     ] dev-ruby/json-2.0.3:2::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby21 ruby22 -ruby23 -ruby24" 136 KiB
[ebuild  N     ] dev-ruby/rdiscount-2.2.0.1::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 67 KiB
[ebuild  N     ] dev-ruby/mustache-1.0.3::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 40 KiB
[ebuild  N     ] dev-ruby/rake-compiler-1.0.2::gentoo  USE="{-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 33 KiB
[ebuild  N     ] dev-ruby/fast_xs-0.8.0-r2::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 22 KiB
[ebuild  N     ] dev-ruby/racc-1.4.14::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 (-ruby20) -ruby21 -ruby23 -ruby24" 114 KiB
[ebuild  N     ] dev-ruby/kpeg-1.1.0:1::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 57 KiB
[ebuild  N     ] dev-ruby/rdoc-5.1.0::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 686 KiB
[ebuild  N     ] dev-ruby/hpricot-0.8.6-r5::gentoo  USE="-doc {-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 287 KiB
[ebuild  N     ] app-text/ronn-0.7.3-r3::gentoo  USE="{-test}" RUBY_TARGETS="ruby22 -ruby21 -ruby23 -ruby24" 60 KiB
[ebuild  N     ] dev-vcs/git-lfs-2.0.0::gentoo  USE="doc" 615 KiB

Total: 22 packages (22 new), Size of downloads: 24,099 KiB

The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
# required by dev-ruby/json-2.0.3::gentoo[-test,ruby_targets_ruby21]
# required by dev-lang/ruby-2.1.10::gentoo
# required by dev-ruby/rake-12.0.0::gentoo[ruby_targets_ruby21]
# required by dev-ruby/hpricot-0.8.6-r5::gentoo[-test,ruby_targets_ruby22,-doc]
# required by app-text/ronn-0.7.3-r3::gentoo[-test,ruby_targets_ruby22]
# required by dev-vcs/git-lfs-2.0.0::gentoo[doc]
# required by git-lfs (argument)
>=virtual/rubygems-12 ruby_targets_ruby21
```

**Comment by ttaylorr** [comment]
@jfkw thanks for opening this up. This has come up in internal discussions before, and I think it'd be worthwhile to pursue a Go alternative to remove a good number of LFS's dependencies when building from source.

I'm not immediately focused on something like this right now, but I'll leave this open to track progress.

**Comment by technoweenie** [comment]
Is it possible to include the man pages in the packages, so that they don't have to be built at all during installation?

**Comment by carlwgeorge** [comment]
While researching alternatives to ronn, I found [another project that switched from ronn to pandoc](https://github.com/vivien/i3blocks/pull/188).  That may be worth reviewing to see if pandoc is a viable option.

**Comment by ttaylorr** [comment]
@carlwgeorge Thanks for linking that -- I've used `pandoc` before and had great success with it. It's written in Haskell, but distributed with instructions on how to build it everywhere where it'd be needed, so I wrote up [this](https://github.com/git-lfs/git-lfs/compare/ronn-to-pandoc?expand=1) branch to test it out.

I don't have time to dive into this too deeply right now, but if someone wants to test this out on their platform of choice and make sure that the manpages are correctly built, that would be much appreciated.

**Comment by technoweenie** [comment]
One thing to keep in mind is that the man pages in markdown are both readable on the website, and embedded into the `git-lfs` binary. I'd prefer to keep that if possible. Markdown isn't strictly required though, just human readability :)

I think adapting our package building scripts would be a better option. I don't necessarily want our packages to depend on haskell or anything either. I wonder if it'd be possible to build them inside our docker images, so that we can include the man pages in their final form with the packages? That's going to be slightly difficult, as those of us still active on the project are not well versed in linux packaging.

**Comment by carlwgeorge** [comment]
@technoweenie You can leave the man page source in markdown, and pandoc will happily convert it from markdown to man (roff) format.  From a packaging perspective, pandoc is widely available.  I'm actually looking into this to port the Fedora spec file for git-lfs to EPEL so it is available for RHEL/CentOS, and the issue I found is that rubygem-ronn isn't available in RHEL/CentOS or EPEL, while pandoc is.

**Comment by technoweenie** [comment]
Cool, that sounds fine then :+1:

**Comment by ttaylorr** [comment]
@carlwgeorge Thanks for the clarification, this was very helpful for me.

**Comment by ttaylorr** [comment]
HI @carlwgeorge, I thin that Ronn is suiting our needs fine for now, and do not believe that a change is imminently necessary. I agree that the Ruby dependency would be nice to get rid of, so perhaps ASCIIDoc is a good choice, but I do not believe that I have the time to dedicate to this currently.
