### ISSUE TITLE
Manual configuration

### ISSUE THREAD

**Issue by geoffrey4444** [git-lfs/git-lfs#2001]
I cannot install software on my cluster using the package manager; instead, I install from source, manually specifying a prefix each time and then creating a module. This is because my cluster software requires that I install packages in nonstandard places for them to be visible to compute nodes.

Could you please tell me how to install git-lfs from source without using a package manager like yum? I want to do something like ./configure --prefix=/share/apps/git-lfs/2.0.0; make; sudo make install.

Any help would be very much appreciated.

**Comment by technoweenie** [comment]
Git LFS is written in Go, so the build instructions are:

1. Install Go 1.8.
2. Run `go get github.com/git-lfs/git-lfs`

You can also grab a compiled binary for your OS at https://github.com/git-lfs/git-lfs/releases/tag/v2.0.0.
