### ISSUE TITLE
git-lfs-authenticate: command not found after updating to v2.0.0

### ISSUE THREAD

**Issue by DoDoENT** [git-lfs/git-lfs#2002]
During the weekend I updated my CI server nodes from Git LFS v1.5.5 to v2.0.0 and all builds have failed with following error:

```
Fetching HEAD

Git LFS: (0 of 18 files) 0 B / 26.90 MB                                        
batch request: bash: git-lfs-authenticate: command not found: exit status 127
```

Current workaround is to downgrade LFS to v1.5.5 or v1.5.6.

Is this a known issue. Are workarounds available?

**Comment by technoweenie** [comment]
`git-lfs-authenticate` has been used for ssh authentication since LFS's original release. That said, the code was refactored, so perhaps some edge case bug was added.

Can you provide a trace of the output for LFS v1.5.x and v2.0.0 with `GIT_TRACE=1`?

**Comment by DoDoENT** [comment]
When running this manually, it works. I've now added `GIT_TRACE=1` to my CI server script (where originally I got the error) and now have to wait for build to fail :)

**Comment by DoDoENT** [comment]
Hi, here is the trace from our CI server:


```
[core-recognizer-test-data] Running shell script
+ GIT_TRACE=1
+ git lfs fetch
15:51:25.871268 git.c:563               trace: exec: 'git-lfs' 'fetch'
15:51:25.871696 run-command.c:336       trace: run_command: 'git-lfs' 'fetch'
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config -l
Fetching HEAD
trace git-lfs: run_command: git ls-tree -r -l -z --full-tree 873a928a77c7bc86d4389677ef40efe88258a54d
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config branch.HEAD.remote
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-28.jpg [ef877317afd188abd730d89f9f95e6d4c0b09b5c4685fb4e7b66dbd7c131c6cf]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-29 - 1.jpg [67fe89f0966568a2c0ac0c7be974fb9b90e47123b7c3ff67e756632695580f11]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-29.jpg [c1ec35aaf7ade1050a8f6c9d36bcd811fde71b7512693fd4a337f4f2a9721479]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-30 - 1.jpg [205c6b5d388e71f40e5b1383192f379acd5c120a82903b02331246cc425498e9]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-30 - 2.jpg [1282982299c2ac9fa3c6a1fddac52961e56cb231691ec7ea3bb5bd54a8f4cfa1]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-30.jpg [51a2852715e8e8c84ade685a705be5f99906f546bc4d0849dd1f218759e324f5]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-31 - 1.jpg [5dd37d85f56b4d2363c76998e06daca74163f8bab95c46b973ca10213bb2e72a]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-34-31.jpg [ff5ea656892f319ca7d761b1d4c72fbdc56a6f590eccc056a5c23fa524e18057]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-29.jpg [dd3e75cd74c6eb8f6dc18e4b0d717a30fa8d302d21d86134d31380aba0e81fa0]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-30 - 1.jpg [adc2a7d447744b556eb85bab6d755fd1df0345270a946b0d37f728467391fae4]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-30 - 2.jpg [ef4664d71e6953bafeed02aca42bdf19e3c72caefff5044f34d7cca3f91013d4]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-30.jpg [f43b941a947a2270df2f0e748e0205046c61b7f577496707c4ccccba3874e8f1]
trace git-lfs: tq: sending batch of size 100
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-31 - 1.jpg [9815ee715f3aaa60c77c31545a669babc9d27bd3f25a3a58306f221d10230587]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-31 - 2.jpg [dad204c1c4724eb0576234e362271deba54f939fcee1d841d01dd0265d964ce2]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-31.jpg [ccf880bdf3f3e121a7af5df4bddce790fd989d307fd5fef21d2921d10ab0b5c8]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-33 - 1.jpg [5a86c6c17441245d221d614586883e93d7fe15d74b755406cb77785a17ae79e9]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - 2014-02-19 08-35-33.jpg [a9c9076d9a5e72d9e46fa992fa0501095563dce8d48f60e12d965beac0e02275]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1200.39 - 2014-06-16 10-47-58.jpg [4a2ff687d322e1b2f975e2216078d85a9ccf17393e7a70f234f1ebb731369051]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1384.85 - 2014-06-16 10-47-52.jpg [cd5197c141a9394e574093d2efad40765d39a9d1d71cc02b9051450ed79232b8]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1535.91 - 2014-06-16 10-47-55.jpg [1b4ba477a31d7c729d7ffb4b2169a2aabd4fa66cc857ef8ae0efc0d99fd14482]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1593.1 - 2014-06-16 10-47-58.jpg [24c4968fe733a087af5ac255d09708dbc80d156f6a64bc055e5340e2ac72b2b2]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1661.83 - 2014-06-16 10-47-57.jpg [9a1c35ee80d4deb84d4e5baba81dea972fbcf266e508ae2014372d8911399498]
trace git-lfs: ssh: jenkins@rambo.local git-lfs-authenticate /opt/git-lfs/repo/core-recognizer-test-data download
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1702.19 - 2014-06-16 10-47-54.jpg [c7f8a46a775ab40895e98710770f2d1230fc5e66d97d28d3a1f967448fbab8cb]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1709.79 - 2014-06-16 10-47-56.jpg [9df55968022532996d29c995a3154546ec264027ab9a3a96b76a927e58bd564f]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1764.53 - 2014-06-16 10-47-56.jpg [a92942f9ecc5dddd5abf5b4964d88bed443afd0aaa1ac07afc3890bb57aca654]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1770.73 - 2014-06-16 10-47-54.jpg [5aeb954941bd22b7a8dcb7348211ac1f94696fc58eb6f39cc73e97f026085e35]
trace git-lfs: fetch 1Dbarcode/Code128/Kosovo/focusedFrame - Q=1780.65 - 2014-06-16 10-47-59.jpg [313ceacc07cbe3cf2437d5ee16d0e974569724ee07c1b4c7438a8af2ac729119]
trace git-lfs: fetch 1Dbarcode/Code128/Original/MaliPero.png [cfa684b550bb06daec4ba336c04c535699d32e0fb72ffeb503badc86c4d0a38e]
trace git-lfs: fetch 1Dbarcode/Code128/Original/MaliPero2.png [5953486b10ec735c7568d910af2cb9c878a6eb1ffa668380226e59f88f7ae5e6]
trace git-lfs: fetch 1Dbarcode/Code128/Original/MaliPero3.png [0a0dcf6913d34b6ff801b2eb27193fac0a0ba12d54b1f876a9b4c51c9cb8efac]
trace git-lfs: fetch 1Dbarcode/Code128/Original/MaliPero4.png [b7b72c4946a11b692af13224d2b743c1b1be4075ba3c1e0ee05d86ea40726308]
trace git-lfs: fetch 1Dbarcode/Code128/Original/Mid.png [fab768fe5d91ea7480c35d654a229341ed420d0cada00378ce9ff0f70b2ac8fe]
trace git-lfs: ssh: jenkins@rambo.local failed, error: exit status 127, message: bash: git-lfs-authenticate: command not found
trace git-lfs: tq: sending batch of size 100
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-44-53.jpg [8018321a771a131af777087ad022d45bdbb34df945d839cf05d0f5f351367bcc]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-44-54 - 1.jpg [4549aa2d500ddbb4566906c56a6abac1d966e3e899ca6d25a23204f28543442f]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-44-54 - 2.jpg [c4e31bb694ae820c37e1a828e8377800861161f56a9dcefb879025ff1795a27f]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-44-54.jpg [5830dcd13b7edbc93b5c1159de0269240e7df6737c5ec1b8f8ca3162ad0457cb]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-44-55 - 1.jpg [a433d294007297c3060a8867706e125213741fafd2c5273588e62ec5d0753e8c]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-44-55 - 2.jpg [3023a5b7050862f57ed85005a8ebf4e2806f003fdbdc09398b2efd49aff56e46]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-45-00.jpg [8c018b3a459f5642ce8b103de635cd15a9c7aac3ed491464501dfa76cca548b4]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-45-01 - 1.jpg [95d8bbcaa71093b0e80cb3a9672bac0871197148f5d55727ea03d661ac4a7767]
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-45-01.jpg [654ee46c93c3263f6d8c0efc17a3fc9f1063589c02228d09196bce4b64ad40bc]
trace git-lfs: ssh: jenkins@rambo.local git-lfs-authenticate /opt/git-lfs/repo/core-recognizer-test-data download
trace git-lfs: fetch 1Dbarcode/Code128/barrel/focusedFrame - 2014-02-18 15-45-02 - 1.jpg [618e2a490463f2b3b11caea4ca1d5da44fe9461dacc25cc15e69e8f7cb42b4c1]
trace git-lfs: fetch baba/PhotoPayTest_Version_1.7.6b_16/photopay0003/Receiver0060.jpg [1e161169370e122634cc0b540f8c82f847914de0ad82bdd61764e546e65467cc]
trace git-lfs: fetch baba/PhotoPayTest_Version_1.7.6b_16/photopay0003/Reference0053.jpg [c830308fe2d42aeb9d32fc413eaa7953a14ab5a6168887fdb5ccaa7019c8b352]
trace git-lfs: fetch baba/PhotoPayTest_Version_1.7.6b_16/photopay0003/focusedFrame0048.jpg [af570f71cb60ef3a0f1de179e83a3cd85247e5680450d71e59877781edcf5e05]
trace git-lfs: fetch baba/PhotoPayTest_Version_1.7.6b_16/photopay0003/focusedFrame0057.jpg [dedb0aed7dedfaf8a0b619d62dccb803f818282ebbaccba96e5b51cd24284c67]
trace git-lfs: fetch dict/deutf8.dic [43edfb5d46c4234d59b0831f63f45a410dcd3c0592ea46801106a177e6f9de10]
trace git-lfs: ssh: jenkins@rambo.local failed, error: exit status 127, message: bash: git-lfs-authenticate: command not found
trace git-lfs: tq: sending batch of size 80
trace git-lfs: ssh: jenkins@rambo.local git-lfs-authenticate /opt/git-lfs/repo/core-recognizer-test-data download
trace git-lfs: ssh: jenkins@rambo.local failed, error: exit status 127, message: bash: git-lfs-authenticate: command not found

Git LFS: (0 of 29080 files) 0 B / 11.87 GB                                     
batch request: bash: git-lfs-authenticate: command not found: exit status 127
batch request: bash: git-lfs-authenticate: command not found: exit status 127
batch request: bash: git-lfs-authenticate: command not found: exit status 127
batch request: bash: git-lfs-authenticate: command not found: exit status 127
```

**Comment by technoweenie** [comment]
Does your repository have a `.gitconfig` in the working directory? Try renaming it to `.lfsconfig`. My hunch is that something in there is setting a `lfs.url` value which could bypass the ssh auth check.

**Comment by DoDoENT** [comment]
Yes it does. It is required because we want that repository to use non-default LFS hosted on our local machine (LFS data is too big for what BitBucket offers in our plan).

The local machine is ArchLinux with Git LFS test server installed from AUR, version 0.3.0-1.

```
[lfs]
    url = "http://username:password@local-lfs-server.local:9999/"
```

Could this be the cause of problem?

**Comment by technoweenie** [comment]
Yes, rename it to `.lfsconfig`, and you'll be good to go. We renamed that setting, and had deprecation warnings for awhile. I'm assuming you didn't see them since they were on S3. Support for that old file was finally removed in 2.0.

**Comment by DoDoENT** [comment]
Thanks.

**Comment by hluoml** [comment]
Does rename .gitconfig to .lfsconfig fix your problem?

I have the config in .lfsconfig, but still got this "git-lfs-authenticate: command not found". 

My lfs server is artifactory. What kind lfs server are you using?

 If I use https://lfs-server, I get error: 405; if I use ssh://lfs-server, I get this "git-lfs-authenticate: command not found". With git-lfs.1.5.5, everything is fine.

**Comment by DoDoENT** [comment]
> Does rename .gitconfig to .lfsconfig fix your problem?
Yes.
> My lfs server is artifactory. What kind lfs server are you using?
Git LFS test server from [AUR](https://aur.archlinux.org/packages/git-lfs-test-server/).

**Comment by MrShadowGames** [comment]
Hi guys, 
after trying for some hours to integrate git-lfs in my current git project, I can't figure out why local changes cannot be committed on a GitBash on my Win7 machine. It's the same error mentioned in the OP:
Git LFS: (0 of 489 files) 0 B / 333.44 MB
**batch request: sh: git-lfs-authenticate: command not found: exit status 127**

Renamed the "config" file to ".lfsconfig" and also tried "lfsconfig" without the preceeding '.'

Any ideas what else could prevent a successful push? On a side note, I got another repo without using LFS communicating with my GIT server and it works just fine. However, on my LFS git repo it fails.
My "config" file looks like this:
`[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = Apollo@Athena:/volume1/homes/Apollo/git_repos/ProjectX.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = Apollo@Athena:/volume1/homes/Apollo/git_repos/ProjectX.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
[lfs "https://Athena//volume1/homes/Apollo/git_repos/ProjectX.git/info/lfs"]
	locksverify = false
`
Anything that might be wrong in my config?

**Comment by technoweenie** [comment]
Your config looks fine. However, running `git config --list` will give us a better view of your entire git config, than just the `.git/config` file.

I think the problem is that your SSH server doesn't have the `git-lfs-authenticate` command. 

> git-lfs-authenticate: command not found: exit status 127

The [API documentation](https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md#ssh) describes how the command works with the Git LFS client.

**Comment by MrShadowGames** [comment]
Yep, I didn't add that package yet so I'll this done tonight. Thanks so far, mate.

**Comment by nadav-y** [comment]
Hey, 
Thanks for bringing this up, we've been examined it and found an issue in Artifactory with SSH authentication in Git LFS 2.0.0 and up, and it's already set to be fixed with the next version of artifactory.
You can track it here: https://www.jfrog.com/jira/browse/RTFACT-13835

**Comment by nadav-y** [comment]
Hey,
Thanks for bringing this up, we've been examing it and found an issue in Artifactory with SSH authentication in Git LFS 2.0.0 and up, and it's already set to be fixed with the next version of artifactory.
You can track it here: https://www.jfrog.com/jira/browse/RTFACT-13835

**Comment by nadav-y** [comment]
Hey,
Thanks for bringing this up, we've been examining it and found an issue in Artifactory with SSH authentication in Git LFS 2.0.0 and up, and it's already set to be fixed with the next version of artifactory.
You can track it here: https://www.jfrog.com/jira/browse/RTFACT-13835

**Comment by MrShadowGames** [comment]
Sounds great! However, I'm not entirely sure what exact steps will be required for me to do on my server. My GIT server is running on a synology NAS with a debian OS, so I might be restricted in the flexibility that linux operators are usually accustomed to.

**Comment by sudouser2010** [comment]
How exactly does one install the git-lfs-authenticate command?

**Comment by technoweenie** [comment]
@sudouser2010 It's something you have to create on the server. We can't provide one, since we don't control how authentication works. Details on how the command should work are in the [server docs](https://github.com/git-lfs/git-lfs/blob/5703b808220103063ededf5c6149c93201be9e07/docs/api/authentication.md#ssh).

That said, if anyone wants to open source a common `git-lfs-authenticate` implementation for basic git/ssh servers, I'd love to host it on the `git-lfs` org, or at least link to it in our docs :)

**Comment by hluoml** [comment]
@sudouser2010 In my case, we don't see the error after upgrade artifactory to the latest

**Comment by nadav-y** [comment]
@hluoml This issue was resolved in Artifactory 5.3 (May 11, 2017)

**Comment by pthurmond** [comment]
I have one for you. I am trying to push to an Acquia-hosted git repo. Acquia does not support Git LFS. How do I force it to push files that are registered with LFS?

It gives me this error when I try to push to the Acquia repo from my Bitbucket repo:
`batch request: fatal: unrecognized command 'git-lfs-authenticate unitedrentals.git upload': exit status 128`

Thoughts on how to get around this?

**Comment by ttaylorr** [comment]
@pthurmond running `git lfs uninstall` will remove the `prepush` hook that is causing Git LFS to try and execute an upload batch API request. Please let me know if that works, and if you have any additional questions, don't hesitate to open a new issue.
