### ISSUE TITLE
Automatically Restarting the Failed Download

### ISSUE THREAD

**Issue by LadyR0uge** [git-lfs/git-lfs#2009]
Hi,
For the first time since we started using Git LFS, I had to copy our whole project repo on a new computer. The download stopped/crashed multiple times and everytime, I had to hard reset manually to resume the download. I'm fine having to do that 5-6 times, but I had to do it more than 30 times. It would be great to have a feature that automatically restarts the download process if it has failed.

**Comment by ttaylorr** [comment]
👋 @LadyR0uge, thanks for opening up this issue. We do have a few config settings to help with this by automatically retrying object downloads/uploads, as well as verify requests. From `git-lfs-config(5)`<sup>[[1](https://github.com/git-lfs/git-lfs/blob/v2.0.1/docs/man/git-lfs-config.5.ronn#L98-L103)</sup>:

```
* `lfs.transfer.maxretries`

  Specifies how many retries LFS will attempt per OID before marking the
  transfer as failed. Must be an integer which is at least one. If the value is
  not an integer, is less than one, or is not given, a value of eight will be
  used instead.
```

and<sup>[[2](https://github.com/git-lfs/git-lfs/blob/v2.0.1/docs/man/git-lfs-config.5.ronn#L105-L111)</sup>: 

```
* `lfs.transfer.maxverifies`

  Specifies how many verification requests LFS will attempt per OID before
  marking the transfer as failed, if the object has a verification action
  associated with it. Must be an integer which is at least one. If the value is
  not an integer, is less than one, or is not given, a default value of three
  will be used instead.
```

To make use of these, try `git config 'lfs.transfer.maxretries' '30'`. Let me know if you have any further issues!
