### ISSUE TITLE
can not installed git-lfs by chocolatey

### ISSUE THREAD

**Issue by chucklu** [git-lfs/git-lfs#2011]
C:\Users\Administrator>choco install git-lfs
Chocolatey v0.10.3
Installing the following packages:
git-lfs
By installing you accept licenses for the packages.
git-lfs not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is pos
sible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - git-lfs - git-lfs not installed. The package was not found with the source(s)
 listed.
 If you specified a particular version and are receiving this message, it is pos
sible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

**Comment by chucklu** [comment]
I have tried the download link like https://github.com/git-lfs/git-lfs/releases/download/v2.0.1/git-lfs-windows-2.0.1.exe,but the download speed is 0

**Comment by chucklu** [comment]
I can download the zip file git-lfs-windows-amd64-2.0.1.zip from the release page 
but I don't know how to replace the exe file

I am using the old version of git-lfs,the version number is git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
Maybe,you can tell me the location of the old exe file,then I can replace it

**Comment by chucklu** [comment]
2017-03-07 18:25:05,675 [ERROR] - git-lfs not installed. An error occurred during installation:
 The operation has timed out.
2017-03-07 18:25:05,689 [INFO ] - git-lfs package files install completed. Performing other installation steps.
2017-03-07 18:25:05,694 [DEBUG] - No package information as package is null.
2017-03-07 18:25:05,736 [DEBUG] - No package information to save as package is null.
2017-03-07 18:25:05,738 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2017-03-07 18:25:05,739 [ERROR] - The install of git-lfs was NOT successful.

The operation has timed out,
not sure,maybe the blocked by the great-fire in china

**Comment by chucklu** [comment]
find the location for lfs 
C:\Program Files\Git LFS

just replace the exe file with the latest

**Comment by ttaylorr** [comment]
@sschuberth do you know of anything that would be causing this issue on Chocolatey?

**Comment by sschuberth** [comment]
No, but maybe @ferventcoder has an idea?

**Comment by ferventcoder** [comment]
@chucklu looks more like an issue finding the package on the source. Since it is available, it leads me to believe you may have a proxy issue with your setup of Chocolatey. Please see https://github.com/chocolatey/choco/wiki/proxy-settings-for-chocolatey

**Comment by ferventcoder** [comment]
HTH

**Comment by ferventcoder** [comment]
And a super low download speed from github over the web is a good indicator of something like a proxy being the issue.

**Comment by chucklu** [comment]
I am in China,I believe choco was blocked by the government project "[Great Firewall of China](https://en.wikipedia.org/wiki/Great_Firewall)"

**Comment by ferventcoder** [comment]
Thanks for the followup. Proxy or firewall, it still appears to be an issue outside of our control. If it ***is*** being blocked by the government, then o_O.

**Comment by ferventcoder** [comment]
If there is somewhere we could followup, that would be appreciated.

**Comment by ferventcoder** [comment]
We do use CloudFlare, which should cache onto an edge server in China IIRC.

**Comment by chucklu** [comment]
**git-lfs - git-lfs not installed. The package was not found with the source(s) listed.**
so,maybe the problem is choco can not find the package of git-lfs.

**Comment by chucklu** [comment]
https://chocolatey.org/packages/git-lfs
https://chocolatey.org/packages/git-lfs.install
I have searched the package on website chocolatey.org,but I find two packages.
which one is the correct one?

**Comment by chucklu** [comment]
PS C:\Users\Administrator> choco install git-lfs
Chocolatey v0.10.3
Installing the following packages:
git-lfs
By installing you accept licenses for the packages.
git-lfs not installed. An error occurred during installation:
 Unable to resolve dependency 'git-lfs.install (= 2.0.0)'.
git-lfs package files install completed. Performing other installation steps.
The install of git-lfs was NOT successful.
git-lfs not installed. An error occurred during installation:
 Unable to resolve dependency 'git-lfs.install (= 2.0.0)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - git-lfs (exited 1) - git-lfs not installed. An error occurred during installation:
 **Unable to resolve dependency 'git-lfs.install (= 2.0.0)'.**

**Comment by lrinQVQ** [comment]
@chucklu Do you install .NET Framework 4+?

**Comment by chucklu** [comment]
@lrinQVQ yes,I have installed .net fremework 4.6

**Comment by pcast01** [comment]
I found 4 instances of chocolatey in my task manager and I ended all those processes and then I was able to run: choco install git.install -y --verbose --force and it installed git. And then add the C:\Program Files\Git\bin to the Environment variables.
