### ISSUE TITLE
No usage text found after bash script .deb installation

### ISSUE THREAD

**Issue by pronobis** [git-lfs/git-lfs#2013]
I just installed a deb package with the bash script on Ubuntu 16.04 and:
`git lfs help`
gives:
`Sorry, no usage text found for "git-lfs"`

However,  `git  lfs --help` opens man pages as expected.

**Comment by ttaylorr** [comment]
@pronobis: thanks for opening this, and sorry that you're having trouble. It looks like the `commands/mancontent_gen.go` is up-to-date and includes the entire contents of the manpages.

@andyneff do you have any additional insight to what might be going on here?

**Comment by sgen** [comment]
I just encountered this problem on Ubuntu `16.04.2`.

The man pages appear in `/usr/share/man/man1` with their content apparently intact and with the proper permissions `644`.

The man pages can be found via both `man /usr/share/man/man1/git-lfs.1.gz` and `man git lfs`.

However the man pages cannot be found via `git lfs help`.

**Comment by ttaylorr** [comment]
@andyneff I just took a look through the `git-lfs/build-dockers` repo. Is it possible that `dh_golang` isn't running `go generate`, which is required to build the man pagees?

**Comment by ricab** [comment]
Same issue here (also after installing git-lfs package in Ubuntu 16.04.)

Neither `git lfs help` nor `git lfs help <subcommand>` work for me. I can get to the top man page with `git help lfs`. However, `git help lfs <subcommand>` ignores the `subcommand` part and sends me to the top page again. I could only see *sub-pages* with man, e.g.: `man git-lfs-track`.

My versions:
```
$ git lfs version
git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.1)
$ git --version
git version 2.7.4
```

**Comment by ttaylorr** [comment]
(Gently pinging @andyneff 😄).

**Comment by Fitzoh** [comment]
seeing the same issue using chef:
```
remote_file '/citools/downloads/git-lfs-deb.sh' do
  source 'https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh'
end

bash 'install git-lfs package list' do
  user 'root'
  code <<-EOH
      bash /citools/downloads/git-lfs-deb.sh
  EOH
end

apt_package 'git-lfs' do
  action :install
end

bash 'install git-lfs for jenkins user' do
  user 'jenkins'
  environment 'HOME' => '/home/jenkins'
  code <<-EOH
      git lfs install
  EOH
end
```

**Comment by qzmfranklin** [comment]
Is this issue resolved? I have the same issue:
```
14:17 $ git lfs
git-lfs/2.4.0 (GitHub; linux amd64; go 1.8.3)
Sorry, no usage text found for "git-lfs"
```
on a Ubuntu 16.04.4 machine.

**Comment by ttaylorr** [comment]
Another gentle ping for @andyneff 😄.

**Comment by flixr** [comment]
Friendly ping....

This is still an issue with
```
git version 2.20.1
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1)
```
on Ubuntu 18.04.

**Comment by andyneff** [comment]
@ssgelm any ideas?

**Comment by ssgelm** [comment]
Hmm, I'll take a look.  In the past this was an issue with not running `go generate` but I thought it had been fixed.  I know at least on the upstream debian/ubuntu build it's fixed.

**Comment by nigels-com** [comment]
Same problem here

```
$ git --version
git version 2.17.1

$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

$ git lfs
git-lfs/2.7.1 (GitHub; linux amd64; go 1.11.5)
Sorry, no usage text found for "git-lfs"
```
