### ISSUE TITLE
git push broken: endless login loop

### ISSUE THREAD

**Issue by guillaume-chevalier** [git-lfs/git-lfs#2014]
Hi, I followed the instructions as explained here, to track *.jpg files in a private repo: 
https://git-lfs.github.com/

Then, when I do `git push`, I enter in an endless loop of login and password. E.g.: it asks me for login, I enter it, then it asks for the password, I enter it, then it asks again for login, and it goes on. It is stuck and it requires to CTRL+C to cancel the command. I added more than 1000 jpg files at once and I have a GitHub student account with unlimited private repos. The login information I enter can be bad and it will still loop without any error message.

**Comment by ttaylorr** [comment]
Hi @guillaume-chevalier, thanks for opening this and sorry that you're having trouble. This sounds like it could be an issue with your credential helper, and not LFS. Are you able to reproduce the problem with Git LFS not installed on your system? If not, could you run `git lfs env` and post the output here?

**Comment by guillaume-chevalier** [comment]
I tried to reclone the repo from the last good commit, then re-add some things but this time without lfs and without the jpg files, but at least with some other small files added. Then, commiting without lfs worked, but I did not tried to add the almost 4 GB of photos without git lfs. 

Here is the result of a `git lfs env` done from within the broken project folder where I can't push, I have hidden some information about paths to replace it with the "some-private-repo" string : 

```
git-lfs/1.5.5 (GitHub; linux amd64; go 1.7.4; git c2dcd6f5)
git version 1.9.1

Endpoint=https://github.com/guillaume-chevalier/some-private-repo.git/info/lfs (auth=basic)
LocalWorkingDir=/media/gui/some-folders/some-private-repo
LocalGitDir=/media/gui/some-folders/some-private-repo/.git
LocalGitStorageDir=/media/gui/some-folders/some-private-repo/.git
LocalMediaDir=/media/gui/some-folders/some-private-repo/.git/lfs/objects
LocalReferenceDir=
TempDir=/media/gui/some-folders/some-private-repo/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
```
I believe I have not changed any settings of git lfs and it is running default for an Ubuntu 14.04 on which I upgrade many libraries so that it almost matches to an Ubuntu 16.

**Comment by ttaylorr** [comment]
@guillaume-chevalier could you try and upgrade to Git LFS v2.0.1 and see if the problem persists?

**Comment by guillaume-chevalier** [comment]
Hi again @ttaylorr , 

I updated to the most recent version for linux found on: 
https://git-lfs.github.com/

That is, 2.1.1. I am on a different computer than the other time. I still have an endless login loop! 
The login loop happens at the `git push --force` while I followed the instructions listed here, using BGF: 
https://confluence.atlassian.com/bitbucket/use-bfg-to-migrate-a-repo-to-git-lfs-834233484.html

Note: the only thing I did different from the instructions at this link is that the result of the BGF processing asked me to run this afterwards: `git reflog expire --expire=now --all && git gc --prune=now --aggressive`, which I did - and it seemed to do fine.

Would this has to do with where the large files should be pushed? If I understand well, bitbucket is supposed to deal with that automatically since there is nothing special mentionned about where do the files go. 

How come I face this issue again, months later and on another computer and on other projects with another git host service? I would like to solve this. Again, I followed all the steps

**Comment by guillaume-chevalier** [comment]
I found a fix with: 
https://github.com/git-lfs/git-lfs/issues/203

The login loop wasn't endless: it simply asked for every files, or maybe many times for every files.

**Comment by Lyptik** [comment]
Hello guys, sorry to reopen this, but it seems I still have this problem, (one password for every lfs file) is it still related to this post or would it be something else ?
Best.

git version 1.9.1
git-lfs/2.4.0 (GitHub; linux amd64; go 1.8.3)

**Comment by ttaylorr** [comment]
Hi @Lyptik, sorry that you're having trouble! Can you make sure that you're on the latest release of Git, and give this another shot? I don't recall specifically, but it is likely that credential helper interaction has changed in the many releases since 1.9.1.

If the issue persists, please don't hesitate to open a new issue, since this one is quite old. Thanks!

**Comment by Lyptik** [comment]
Hey thanks a lot for the fast answer, I'm going to update and test !

**Comment by dgray16** [comment]
Issue persists.
**Git lfs env**

```
git-lfs/2.8.0 (GitHub; linux amd64; go 1.12.7; git 30af66bb)
git version 2.20.1

Endpoint=https://github.com/dgray/partner-extractor.git/info/lfs (auth=basic)
LocalWorkingDir=/home/developer-vova/IdeaProjects/partner-extractor-github
LocalGitDir=/home/developer-vova/IdeaProjects/partner-extractor-github/.git
LocalGitStorageDir=/home/developer-vova/IdeaProjects/partner-extractor-github/.git
LocalMediaDir=/home/developer-vova/IdeaProjects/partner-extractor-github/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/developer-vova/IdeaProjects/partner-extractor-github/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/developer-vova/IdeaProjects/partner-extractor-github/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by Filimindji** [comment]
May be late, but using Azure Devops, it look like using this config settings is a good fix : 

`git config http.version HTTP/1.1`

(source : https://developercommunity.visualstudio.com/t/git-lfs-push-got-413-error/867488)
