### ISSUE TITLE
git-lfs 2.0.0 got error: batch request: exec request failed on channel 0: exit status 255

### ISSUE THREAD

**Issue by hluoml** [git-lfs/git-lfs#2027]
After I upgraded git-lfs from 1.5.5 to 2.0.0, "git lfs fetch" failed on one of my git repo. git-lfs works fine.

Below are my git config info:
"filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
color.ui=auto
credential.helper=cache --timeout=3600
lfs.concurrenttransfers=30
init.templatedir=~/.git-templates
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
filter.lfs.smudge=git-lfs smudge --skip -- %f
"
Here is the "git lfs fetch" trace output:

"trace git-lfs: fetch my_apps/my_apps.dll [b032ab562cc7cda4fbc252d056f23295882696fc772d5b770e74553110d0af49]
trace git-lfs: ssh: artifactory, error: exit status 255, message: exec request failed on channel 0
trace git-lfs: tq: sending batch of size 100
trace git-lfs: ssh: artifactory git-lfs-authenticate artifactory/my_apps download
trace git-lfs: ssh: artifactory failed, error: exit status 255, message: exec request failed on channel 0
trace git-lfs: tq: sending batch of size 1
trace git-lfs: ssh: artifactory git-lfs-authenticate artifactory/my_apps download
trace git-lfs: ssh: artifactory failed, error: exit status 255, message: exec request failed on channel 0
^MGit LFS: (0 of 201 files) 0 B / 110.50 MB
batch request: exec request failed on channel 0: exit status 255
batch request: exec request failed on channel 0: exit status 255
batch request: exec request failed on channel 0: exit status 255"

**Comment by technoweenie** [comment]
That looks like an issue with Artifactory, or your git config is wrong. If you run `git lfs env`, that'll let us know if your git config is wrong.

**Comment by hluoml** [comment]
If git-lfs 1.5.5. works fine with our artifactory server. Do I need change anything on artifactory side for git-lfs.2.0.0.

Here is my "git lfs env" output:
git lfs env
git-lfs/2.0.0 (GitHub; linux amd64; go 1.8)
git version 2.11.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=30
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_TRACE=0
GIT_CURL_VERBOSE=1
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by technoweenie** [comment]
Can you run `git lfs env` from the repository? This doesn't show any info. 

SSH requests work just fine in Git LFS v2.0. That said, there's a very real chance that 2.0 has some edge case issue that 1.5.5 doesn't. Seeing your config can help us track it down.

Your trace output makes it look like there's a configuration problem, or that you sanitized the output to hide private info. This line especially:

```
trace git-lfs: ssh: artifactory git-lfs-authenticate artifactory/my_apps download
```

When I run this, I see:

```
trace git-lfs: ssh: git@github.com git-lfs-authenticate github/git-lfs-test.git download
```

LFS is essentially running this command:

```
$ ssh git@github.com git-lfs-authenticate github/git-lfs-test.git download
{
  "href": "https://lfs.github.com/github/git-lfs-test",
  "header": {
    "Authorization": "RemoteAuth SECRET"
  },
  "expires_at": "2017-03-13T20:13:59Z"
}
```

If you can't run that, then the problem is on your ssh service. The `git lfs env` command also gives a very big clue to how LFS is parsing your ssh endpoint:

```
Endpoint=https://github.com/github/git-lfs-test.git/info/lfs (auth=none)
  SSH=git@github.com:github/git-lfs-test.git
```

**Comment by technoweenie** [comment]
One shot in the dark: Do you have a `.gitconfig` file in the root of your repository with lfs-specific config commands? The `.gitconfig` file was deprecated in v1.4.x, and removed in 2.0. Rename it to `.lfsconfig` and you should be fine.

**Comment by hluoml** [comment]
We do have both .gitconfig and .lfsconfig files, but .gitconfig does not contain lfs stuff.

I did remove artifactory.mycompany.com from the artifactory host name.

If I run "ssh hluo@artifactory.mycompany.com git-lfs-authenticate artifactory/my_apps download", I got:
"bash: git-lfs-authenticate: command not found"

Below is the output from the root of git repo:
git lfs env
git-lfs/2.0.0 (GitHub; linux amd64; go 1.8)
git version 2.11.0

Endpoint=https://artifactory.mycompany.com/artifactory/my_apps (auth=none)
  SSH=artifactory.mycompany.com:artifactory/my_apps
LocalWorkingDir=/home/mycompany/hluo/ws/git-lfs-200/my_apps
LocalGitDir=/home/mycompany/hluo/ws/git-lfs-200/my_apps/.git
LocalGitStorageDir=/home/mycompany/hluo/ws/git-lfs-200/my_apps/.git
LocalMediaDir=/home/mycompany/hluo/ws/git-lfs-200/my_apps/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/MAGICLEAP/hluo/ws/git-lfs-200/my_apps/.git/lfs/tmp
ConcurrentTransfers=30
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_TRACE=0
GIT_CURL_VERBOSE=1
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by technoweenie** [comment]
> If I run "ssh hluo@artifactory.mycompany.com git-lfs-authenticate artifactory/my_apps download", I got:
"bash: git-lfs-authenticate: command not found"

That is an issue on your SSH server. SSH remotes require a `git-lfs-authenticate` command. The only other workarounds are:

* Use an HTTPS git remote
* Configure `lfs.url` or `remote.{name}.lfsurl` (such as `remote.origin.lfsurl`) to the HTTPS address of an LFS server.

**Comment by hluoml** [comment]
thanks, I will try to fix that first

**Comment by midworld** [comment]
I think I have a similar issue. After updating git-lfs to v2, it cannot fetch any of file.

**Comment by hluoml** [comment]
I tried to use https git remote in .lfsconfig, but got https error: 405

**Comment by hluoml** [comment]
After I updated .lfsconfig from ssh to https, I was able to download.

**Comment by igor-ba** [comment]
Have exactly same sypthoms with corporate artifactory server, but using https instead of ssh is not an option in my case. I did some further investigations and I thing I found out that artifactory need some extra argument for the download command while doing `git-lfs-authenticate` Command line like
`ssh artifactory git-lfs-authenticate artifactory/my_apps download 12345`
 works in my case. Note that you can put instead of `12345` anything else! 
This fully corresponds to artifactory behavior mentioned here at the very bottom: https://www.jfrog.com/knowledge-base/git-lfs-push-not-working-when-using-ssh-authentication/

Now question to @technoweenie: is it possible to put some dummy argument after the download command? It does not sound like a clean solution to me. Maybe artifactory's implementation is somehow out of lfs protocol specification (is there any?) But I know that version 1.5.6 was able to  cope with this behavior somehow.

**Comment by technoweenie** [comment]
The spec for LFS SSH auth is [right here](https://github.com/git-lfs/git-lfs/blob/master/docs/api/authentication.md#ssh).
