### ISSUE TITLE
2.0.1 - Push keeps restarting and won't finish

### ISSUE THREAD

**Issue by erebel55** [git-lfs/git-lfs#2031]
I am trying to make a large push to my repo (gitlab.com) but it keeps restarting from the beginning and never finishing. The point in the upload it gets to is not consistent; I've seen it restart at 200MB - 1.2GB.

I have made plenty of pushes in the past using git lfs, but for some reason I can't get this one to finish (this is probably the largest I've ever done).

This started happening, yesterday. I am using lfs 2.0.1, with git 2.12, on a windows client.

I have let it run over night and it eventually fails with "an existing connection was forcibly closed by the remote host"

I can still make other pushes to the repo. But this push won't complete.

I started thinking that it was peculiar that this started happening on the same night as daylight savings time.

So, I checked the system time difference via https://time.is/ and it said that I was over 4 seconds off.

Therefore, I used w32time to resynchronize my system clock.

`net start w32time`
`w32tm /resync`

This re-synchronized my clock and it is now exact via https://time.is/

However, this didn't fix my issue. My push still won't go through and keeps restarting.

I am seeing some 401 Unauthorized errors in the logs but I am also seeing 200 OK in the logs, so I'm not sure what's up with that.

I set GIT_TRACE and GIT_CURL_VERBOSE to 1 and have attached logs here.

[git_lfs_logs.txt](https://github.com/git-lfs/git-lfs/files/842665/git_lfs_logs.txt)
[git_lfs_logs_2.txt](https://github.com/git-lfs/git-lfs/files/842666/git_lfs_logs_2.txt)

I have also attached the results of `git lfs env`
[git_lfs_env.txt](https://github.com/git-lfs/git-lfs/files/842540/git_lfs_env.txt)

**Comment by ttaylorr** [comment]
> I have let it run over night and it eventually fails with "an existing connection was forcibly closed by the remote host"

This means that GitLab is closing the connection from your LFS client to their storage backend. Could you please open an issue with them?

**Comment by erebel55** [comment]
Taylor, thanks for the reply. That does not explain why the push keeps restarting. Pretty sure the "an existing connection was forcibly closed by the remote host" is just hit because it ran for like 10 hours and eventually was killed. So no, I think this is a lfs issue.

**Comment by ttaylorr** [comment]
> Pretty sure the "an existing connection was forcibly closed by the remote host" is just hit because it ran for like 10 hours and eventually was killed.

I took another look at your logs, and I'm wondering if the complete log for your push was attached. In particular, I'm missing some information from the transfer adapters themselves about why the push was restarted or not completed.

Could you please re-attach the full logs for your push with both `GIT_CURL_VERBOSE=1` and `GIT_TRACE=1` set? If you don't feel comfortable sharing in a public issue, feel free to send them to support@github.com, and they'll get routed to me.

**Comment by erebel55** [comment]
This was a different run than the one that died with "an existing connection was.."

I have tried doing this push around a dozen times.

`GIT_CURL_VERBOSE=1` and `GIT_TRACE=1` were both on in the logs that I attached. So I'm not sure why you are missing anything there.

I will do a new push now and attach the logs again. I'm not going to let it run until death because that would take forever and I need this resolved. I will let it run until it restarts and attach the logs.

**Comment by erebel55** [comment]
@ttaylorr 

I ran the following
`set GIT_TRACE=1`
`set GIT_CURL_VERBOSE=1`

`git push > push.txt 2>&1`

The resulting file is 1.5MB but 99% of that is just the progression of the push (I can remove those lines if you don't want to look at them).

[push.txt](https://github.com/git-lfs/git-lfs/files/845673/push.txt)

It made it all the way to 1.19 GB / 1.33 GB and then threw a 401 Unauthorized and went back down to 853.90 MB / 1.33 GB on line 17346.

It then made it back up to 991.13 MB / 1.33 GB and then threw another 401 Unauthorized and went back down to 495.56 MB / 1.33 GB on line 19259.

Please let me know if you would like me to clean up the log file for you or if it is okay as is. It's pretty easy to navigate, but I just want to make sure.

**Comment by technoweenie** [comment]
It's restarting because your lfs server is returning a 401.  That's something that can only be fixed on the server.

**Comment by zoltanmaric** [comment]
For what it's worth, I was able to resolve a restarting LFS upload by restarting my network connection (`sudo service network-manager restart` on ubuntu)
