### ISSUE TITLE
Cloning failed

### ISSUE THREAD

**Issue by MichalDulemba** [git-lfs/git-lfs#2037]
I'm havving some issues with cloning repository from Github. 
I get "expected json type, got: "" " information (printscreen in the attachment)

![zrzut ekranu 2017-03-16 11 25 23](https://cloud.githubusercontent.com/assets/24190630/23994141/ca36312e-0a43-11e7-9cf9-593ff2c29a30.png)

**Comment by ttaylorr** [comment]
Hi @MichalDulemba, thanks for opening this. Could you re-run your command with the `GIT_CURL_VERBOSE=1` and `GIT_TRACE=1` environment variables? Be sure to remove any information you don't want made public, like any `Authorization:` headers, or filenames that you don't want disclosed.

**Comment by MichalDulemba** [comment]
This is absolutely strange. 
I changed absolutely nothing and now it works... (without those env variables).

**Comment by ttaylorr** [comment]
@MichalDulemba glad that it's working for you, though I'm still curious what was causing the failure in the first place.

I'm going to close this out for now, but if it happens again please don't hesitate to reopen the issue and post a log with those environment flags.
