### ISSUE TITLE
Windows: realloc error when downloading largish file

### ISSUE THREAD

**Issue by damphyr** [git-lfs/git-lfs#2038]
I get a realloc error for a 547MB file.
Windows 7 x86 (that's 32bit, yes it is!)

<img width="567" alt="screen shot 2017-03-16 at 12 57 56" src="https://cloud.githubusercontent.com/assets/96603/23995114/688bb8fe-0a48-11e7-939b-cb1afa9bdf38.png">

**Comment by technoweenie** [comment]
Can you try running `git config --unset filter.lfs.process`? That will turn off the filter process feature that was introduced in Git 2.12.

**Comment by damphyr** [comment]
Yep, that fixes it.
Why? What does filter.lfs.process do?

**Comment by damphyr** [comment]
The workaround worked on one occasion but unfortunately on a similar computer (Win32, same versions etc.) it is ineffective.

Also, in this case there is no log.

I do 

```
git lfs install
git clone
```

this is interrupted with 
```
fatal: Out of memory, realloc failed
warning: Clone succeeded, but checkout failed.
```

Doing ```git config --unset filter.lfs.process``` has no effect, ```git checkout -f HEAD``` exits with the same realloc error.

**Comment by ttaylorr** [comment]
@damphyr some googling reveals that the issue here might be that you have large files committed outside of LFS within your repository. You can view the top `N` biggest with:

```bash
$ git ls-tree -l -r HEAD | awk '{ print $4 "\t" $0 }' | sort -r -n | head -n 3 | column
1069    100644 blob fe6ededa8114e5154392e46a009e8781d3f839dd    1069    LICENSE.md
168     100644 blob 3ba8f4ba1b3ff2197c104b7f0df62e63f4b18030     168    .gitattributes
131     100644 blob 9432f8cd774ec51a0063c483ba01b7cf38ac3007     131    gif/atom-undo.gif
```

or do that across every revision by:

```bash
while read l;
  rev="$(awk '{ print $1 }')";
  git ls-tree -l -r "$rev" | awk '{ print $4 "\t" $0 }'
done < <(git log --oneline -l) \
  | sortn -r -n \
  | head -n 3 \
  | column 
```

**Comment by damphyr** [comment]
@ttaylorr bingo!  Thanks a lot for the tip.

Also: Nice to see awk still in use :) Not much help on a Windows box, but still, it brings back memories :)

**Comment by ttaylorr** [comment]
@damphyr glad I could help? Do you think we can close this issue out for now?

**Comment by damphyr** [comment]
👍
