### ISSUE TITLE
git lfs fatal error

### ISSUE THREAD

**Issue by haibin** [git-lfs/git-lfs#2058]
I got the following error while pushing the commit. Any help?

`git-lfs/1.5.6 (GitHub; darwin amd64; go 1.7.5)
git version 2.6.1

$ git-lfs pre-push origin git@bitbucket.org:zumata_scripts/property-placeid.git
Fatal error: Server error: https://bitbucket.org/%7B%7D/%7B46932647-9e65-4ef0-854c-7d0793442f2d%7D/info/lfs/object/verify?upload_id=d5f79678-648e-45f5-9efa-c2f4331561b8

Fatal error: Server error: https://bitbucket.org/%7B%7D/%7B46932647-9e65-4ef0-854c-7d0793442f2d%7D/info/lfs/object/verify?upload_id=d5f79678-648e-45f5-9efa-c2f4331561b8
github.com/git-lfs/git-lfs/errors.newWrappedError
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/errors/types.go:166
github.com/git-lfs/git-lfs/errors.NewFatalError
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/errors/types.go:210
github.com/git-lfs/git-lfs/httputil.handleResponse
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/httputil/response.go:95
github.com/git-lfs/git-lfs/httputil.doHttpRequest
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/httputil/request.go:78
github.com/git-lfs/git-lfs/httputil.DoHttpRequestWithRedirects
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/httputil/request.go:117
github.com/git-lfs/git-lfs/api.DoRequest
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/api/v1.go:79
github.com/git-lfs/git-lfs/api.VerifyUpload
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/api/verify.go:36
github.com/git-lfs/git-lfs/transfer.(*basicUploadAdapter).DoTransfer
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/transfer/basic_upload.go:121
github.com/git-lfs/git-lfs/transfer.(*adapterBase).worker
	/private/tmp/git-lfs-20170216-63375-fpohq2/git-lfs-1.5.6/src/github.com/git-lfs/git-lfs/transfer/adapterbase.go:148
runtime.goexit
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=/Users/haibin/go/src/bitbucket.org/zumata_scripts/property-placeid
LocalGitDir=/Users/haibin/go/src/bitbucket.org/zumata_scripts/property-placeid/.git
LocalGitStorageDir=/Users/haibin/go/src/bitbucket.org/zumata_scripts/property-placeid/.git
LocalMediaDir=/Users/haibin/go/src/bitbucket.org/zumata_scripts/property-placeid/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/haibin/go/src/bitbucket.org/zumata_scripts/property-placeid/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_WORK_TREE=/Users/haibin/go/src/bitbucket.org/zumata_scripts/property-placeid
GIT_PREFIX=`

**Comment by technoweenie** [comment]
This looks more like a problem with your server, and not Git LFS. I think your best bet is to hit up BitBucket support with this info:

> Fatal error: Server error: https://bitbucket.org/%7B%7D/%7B46932647-9e65-4ef0-854c-7d0793442f2d%7D/info/lfs/object/verify?upload_id=d5f79678-648e-45f5-9efa-c2f4331561b8

If it succeeds after another push command, then it's likely an intermittent error.

**Comment by haibin** [comment]
Yes, you were right. It works now.

**Comment by sanja7s** [comment]
@haibin I am still having the same type of error with GitLab -- can you point me to how you resolved it?

Many thanks
