### ISSUE TITLE
On a bare repo with a number of remotes, fetch --all fails

### ISSUE THREAD

**Issue by barakwei** [git-lfs/git-lfs#2061]
When I create a bare repo, add only one remote and execute `git lfs fetch --all` everything works as expected:
```
Scanning for all objects ever referenced...
✔ 2 objects found
Fetching objects...
Git LFS: (2 of 2 files) 290.00 MB / 290.00 MB
```

When I add another remote, it stops working
```
Scanning for all objects ever referenced...
✔ 5 objects found
Fetching objects...
No default remote
```

If I specify a remote with `git lfs fetch some_remote` I get
`Could not fetch` and the log file shows `Git can't resolve ref: "HEAD"`

git 2.12.0
git-lfs 2.0.1

Also, I expected that `git fetch --all` will also download the lfs files but it didn't happen as well, what's the expected behavior?

**Comment by barakwei** [comment]
So Apparently, `git lfs fetch --all` does a different thing than what I initially thought, (which is what `git fetch --all does). Is there a way to fetch from all remotes?

**Comment by technoweenie** [comment]
According to the [LFS docs](https://github.com/git-lfs/git-lfs/blob/d4354c33bc3833bb5a2804ff523d83789f54fb00/docs/man/git-lfs-fetch.1.ronn#L27-L31):

> Download all objects referenced by any commit that is reachable; this is primarily for backup / migration purposes. Cannot be combined with `--recent` or `--include`/`--exclude`. Ignores any globally configured include and exclude paths to ensure that all objects are downloaded.

`git lfs fetch` does not have a way to download from all refs. You have specify a remote, once per command:  `git lfs fetch --all <remote> <ref>`.

**Comment by barakwei** [comment]
Thanks!
