### ISSUE TITLE
Push fails due to missing LFS objects (old pointers?)

### ISSUE THREAD

**Issue by ikriz** [git-lfs/git-lfs#2062]
`git push --set-upstream origin trouble`
```
Git LFS: (0 of 140 files, 200 skipped) 0 B / 61.78 MB, 84.72 MB skipped        Trying to push "Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD0.asset" with OID 9e9f19ef98f03ac3ec870807689747afa0941bcfba08bdb0f4bcfaecd8ff8ac8.
Not found in .git\lfs\objects\9e\9f.
error: failed to push some refs to 'https://User@myurlredacted:8443/scm/repos/repo.git'
````
`git lfs fsck` gives me this: (also gives same problems when doing a `git lfs fetch --all origin`)
```
Object Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD2.asset (3ac1c1ed4de2ee70cbac27ae040904433a7d3c72482c551dc4e287e2891507fa) could not be checked: The system cannot find the file specified.
Object Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD1.asset (d9307515d08e1bb064fa1029530c058de9f22c872fc173c5435acad1cefa954e) could not be checked: The system cannot find the file specified.
Object Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD0.asset (9e9f19ef98f03ac3ec870807689747afa0941bcfba08bdb0f4bcfaecd8ff8ac8) could not be checked: The system cannot find the file specified
```
`git lfs ls-files` returns different pointers:
```
f8b96f2722 * Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD0.asset
134369cea1 * Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD1.asset
9343421974 * Unity3D/Assets/Time of Day/Assets/Meshes/Stars/Stars_LOD2.asset
```

I believe this occurred while rewriting history to convert a repo to lfs in which a pointer was not pushed to the server and overwritten with a new pointer, thus having an old pointer left in history but no object connected to it? How can i recover from this? all current files are still intact can I change a pointer to reference the current one?

**Comment by ttaylorr** [comment]
@ikriz thanks for opening this, and sorry that you're having trouble.

> How can i recover from this?

Today the best answer is that you should rewrite history to remove any pointers that might be missing from the client/server.

I'd like to improve this as a part of https://github.com/git-lfs/git-lfs/issues/2063 which would allow your push to succeed.
