### ISSUE TITLE
Be more forgiving of missing objects

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#2063]
Currently, if a repository is missing LFS data for older versions of files, it's impossible to push it to a new endpoint. I think the `git lfs push` and `pre-push` commands should spew errors if it can't find an object locally, without halting the push operation early. The commands should still return with a non-zero exit code, but at least the other objects have a chance to be uploaded. This allows repositories with missing objects to be easily fixed without resorting to `git filter-branch`.

This is also a small baby step towards Object Expiration (as described in https://github.com/git-lfs/git-lfs/issues/1101#issuecomment-260769632), which would let repository owners mark certain OIDs as known missing objects. By marking an object as expired, the `push` and `pre-push` commands will just skip the upload attempt, so the commands can return successfully.

Finally, double check that upload retries reset the progress meter properly.

**Comment by ttaylorr** [comment]
👋  (ack-ing out of our internal first responder rotation).

**Comment by ttaylorr** [comment]
Closed via #2078.

**Comment by technoweenie** [comment]
I don't think the push issues were ever addressed. We just decided against an explicit `--strict-mode`.

This is what I'd like for v2.2.0:

* `push` and `pre-push` attempt to upload everything.
* If `lfs.allowIncomplePush` is enabled, return exit code of 0. Otherwise, exit code of 1 if all the objects are not uploaded. This makes it easy to set on a per-repo basis, even in `.lfsconfig`.

**Comment by ttaylorr** [comment]
@technoweenie my mistake on closing this one out early. I think what you're proposing is a good idea, and I opened up #2199 to address/implement. Let me know what you think.
