### ISSUE TITLE
git mv doesn't seem to update .gitattributes

### ISSUE THREAD

**Issue by lbergelson** [git-lfs/git-lfs#2069]
If I move a file tracked by git-lfs using `git mv`, it doesn't seem like the .gitattributes file is updated to account for the move.  I would expect that it would be.

**Comment by ttaylorr** [comment]
`git mv` is a Git command, so we can't change anything about it's behavior from LFS. The manpage for `git mv` doesn't mention anything about updating references to paths that it moves from other files, so your best bet would be either to:

1. Update the `.gitattributes` file yourself (recommended), or...
2. Write a `git-mv` executable that exhibits this behavior, making sure that it is reachable from within your `$PATH` _before_ Git's own version.

**Comment by lbergelson** [comment]
That makes sense, but it seems like an easy way to unexpectedly commit large files to your repo.  Most other basic git commands work mostly seemlessly with git-lfs files, it was surprising to me that `mv` would break things.  

Would it make sense to add a git-lfs move to handle the use case of renaming files under lfs?

**Comment by ttaylorr** [comment]
> Would it make sense to add a git-lfs mv to handle the use case of renaming files under lfs?

I think this would be a good addition to LFS. I don't have time to work on something like this right now, but I'd gladly guide a contributor through making a PR 😄

**Comment by lbergelson** [comment]
If I get time I might take you up on that offer...

**Comment by mathstuf** [comment]
It might be good to have a `pre-commit` hook to look for renamed/copied files and if the old path has the `filter=lfs` attribute set on it, to warn if the new path does not.

**Comment by technoweenie** [comment]
I think going with a `pre-commit` hook is a great idea. I don't think there's a way to hijack `git mv`, and adding `git lfs mv` isn't a complete solution.

**Comment by mathstuf** [comment]
Not to mention that `mv` is just one command. `rm` and `add` in a pair with a `/usr/bin/mv` can't be intercepted either.

**Comment by ttaylorr** [comment]
> I think going with a `pre-commit` hook is a great idea. I don't think there's a way to hijack `git mv`, and adding `git lfs mv` isn't a complete solution.

Totally agree with all of this. I think there are two cases we need to catch:

1. Files moved out of one pattern into another.
2. Files moved out of one pattern and deleted.

In the first case, we can detect if a subset of all index "renames" match a single gitattrs pattern. If so, we can recommend that they add a new pattern.

In the second case, we can check all patterns against all files (with room for optimization) and indicate which patterns are unused. We can use the same subtree culling algorithm that `git-lfs-migrate(1)` uses, which is fast.

This brings me back to a thought I have wherein it would be cool to have a function:

```go
func FilenamesToPattern(fs ...string) (pattern string) { ... }
```

which recommends the most specific pattern that matches _all_ given filenames "`fs`". Doing so would allow us to instead say "Pattern A has n files that were renamed. Consider pattern B (generated) as an alternative."

I don't know of any research that recommends a way to implement this, but I'll put it on my reading list.

**Comment by mathstuf** [comment]
Pattern detection in git-lfs is broken (see #2413). It's better to just query for the `filter=lfs` attribute on the old and new paths. However the developer ends up fixing the new files to be under the right attribute(s) is up to them (or using `commit -n` to skip the check).

**Comment by dideler** [comment]
I have a file that's tracked with git-lfs and renamed it via VSCode to be all lowercase.

E.g. `data/Some_File.pkl.zl.gz` to `data/some_file.pkl.zl.gz`

The rename isn't picked up by git. My `.gitattributes` looks like this and the extension of the file still matches the wildcards.

```
data/*.h5* filter=lfs diff=lfs merge=lfs -text
data/*.pkl* filter=lfs diff=lfs merge=lfs -text
```

How can I have it detect the rename?

**Comment by ttaylorr** [comment]
> How can I have it detect the rename?

You can double check that it is in fact ignoring the rename, by running `git check-attr -a /path/to/file`. If it doesn't show your new file, I think a `git rm --cached` and `git add --force` should clean things up.

**Comment by dideler** [comment]
Thanks @ttaylorr. The new file showed up with `git check-attr --all`, and the removal from cache and re-adding it worked!
