### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by JarrettR** [git-lfs/git-lfs#2076]
Error reporting can be improved in the following three ways:

1. Display the main error cause in the terminal, instead of just the logfile
2. Use Windows-formatted line endings in the log, when necessary
3. In the logfile, add an additional line break in the smudge error

(1)
Requiring the user to check the logfile before seeing the full text of an error seems like an unnecessary extra step that prevents quick troubleshooting. This slight obfuscation of underlying cause of errors also likely leads to [vague issue reports](https://github.com/git-lfs/git-lfs/issues?utf8=%E2%9C%93&q=is%3Aissue%20in%3Atitle%20smudge), which is harder on the maintainers.

(2)
On Windows, checking this logfile with an application that does not support Linux-style line endings results in this, which is unusual even for cross-platform systems:

![image](https://cloud.githubusercontent.com/assets/6027644/24273839/df46a9ba-0fe1-11e7-8750-75e48eb9962f.png)

(3)
After converting the line endings, the relevant error message is way out on the right side of the screen, which significantly hinders reading comprehension for a user trying to parse these for the first time.

![image](https://cloud.githubusercontent.com/assets/6027644/24274012/f2948040-0fe2-11e7-847c-302972e926c8.png)

And extra line break after the second colon of the smudge error would fix this.

**Comment by technoweenie** [comment]
Thanks for the feedback. All valid points.

1. :+1: This is something we try to fix when we notice in specific cases.
2. Great suggestion, easy fix.
3. Not as easy of a fix, because of how the error messages in Go work.

**Comment by ttaylorr** [comment]
I just opened https://github.com/git-lfs/git-lfs/issues/2178, which should address the second and third points of this issue.

Looking at an appropriate way to handle the first concern.
