### ISSUE TITLE
Set `locksverify` based on the host

### ISSUE THREAD

**Issue by rjbell4** [git-lfs/git-lfs#2093]
It appears that enabling/disabling `locksverify` is done on a per URL basis.  We have a lot of repositories in our organization.  Managing a full set of `locksverify=false` settings (in order to prevent warning messages and lots of questions) is going to be a bear.  It would be *highly* preferable instead to disable it for *ALL* repos on a server, in one fell swoop.

**Comment by ttaylorr** [comment]
@rjbell4 thanks for opening this, I think this would be useful to have in the LFS client for situations like yours.

If you have access to the server, you could respond with an HTTP 501 to the `locks/verify` endpoint and the client will [know to ignore that][1].

[1]: https://github.com/git-lfs/git-lfs/blob/v2.0.1/commands/uploader.go#L125-L126

**Comment by rjbell4** [comment]
I am using Artifactory as a server, so I am at their mercy for the server implementation.

**Comment by ttaylorr** [comment]
@rjbell4 I assume that other's are in the same boat as well. Going to milestone this into the 2.1.0 release.

**Comment by technoweenie** [comment]
I think the approach in https://github.com/git-lfs/git-lfs/pull/1912 could be adapted to work with `http.<url>.*` and `lfs.<url>.*` keys.

**Comment by ttaylorr** [comment]
I think getting #1912 merged and then updating the changes in #1951 to work with that would be 👍.

**Comment by ttaylorr** [comment]
👋 @rjbell4, I just pushed up https://github.com/git-lfs/git-lfs/pull/2162 which adds support for this as you originally described. Pending a merge of that pull request into master, this will ship with the next release of Git LFS, v2.1.0.
