### ISSUE TITLE
git lfs force basic auth

### ISSUE THREAD

**Issue by fursu69** [git-lfs/git-lfs#2103]
Hello,

I am working against an older artifactory server (4.16.0)
And it seems there is an bug that makes it impossible to push until the client is refused and the auth=none is set to auth=basic.

I get the error with size = -1 and no error message so the client respond as it was a success. 
```
{
  "objects" : [ {
    "oid" : "47a56aeec14985dec934e8501c1308ae156f349797a307f4ef41733fce27a14c",
    "size" : -1
  } ]
```

https://www.jfrog.com/jira/browse/RTFACT-11955

I have seen some workarounds where access = basic is added in the .lfsconfig under the url but this does not work for me when i check my it's sill set to none.
under 
```
> cat .lfsconfig
>[lfs]
>url = "https://myartifactoryl/abc"
>access = basic

>git lfs env 
Endpoint=https://myartifactoryl/abc (auth=none)
```

I can not change the settings of the server cus of permissions. I managed to find out that the problem is that i try to push as anonymous user and the server is not configured for this. 

Anyone know some way to manually set the client to auth=basic?

**Comment by ttaylorr** [comment]
Hi @fursu69, thanks for opening this issue. To set the default access for a URL, you can use the `lfs.<url>.access` setting (see: [git-lfs-config.5](https://github.com/git-lfs/git-lfs/blob/1274d627bb7621f101e91766f81346bf73947a12/docs/man/git-lfs-config.5.ronn#L199-L205)), so your gitconfig should look like:

```gitconfig
[lfs]
	url = https://myartifactoryl/abc
[lfs "https://myartifactoryl/abc"]
	access = basic
```
