### ISSUE TITLE
Locks command with "--limit" or "-l" does not use limit parameter in server call

### ISSUE THREAD

**Issue by derrickstolee** [git-lfs/git-lfs#2106]
The [List Locks action](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md#list-locks) in the lock API clearly has a "limit" parameter. However, the `git lfs lock --limit #` command performs limiting only on the client-side, not the server-side call. This seems like an easy performance win, if the limit is lower than the number of locks.

On 2.0.1, I run the following commands and get the resulting URLs:
* `git lfs locks -l 2` calls `> GET .../info/lfs/locks HTTP/1.1`
* `git lfs locks -l 2 -i 3` calls `> GET .../info/lfs/locks?id=3 HTTP/1.1`
* `git lfs locks -l 2 -i 3 -p file` calls `> GET .../info/lfs/locks?id=3&path=file HTTP/1.1`

**Comment by ttaylorr** [comment]
Hi @derrickstolee, thanks for opening this. I've opened up #2107 to address, which I'm planning on backporting into the release-2.0 tree to make it apart of 2.0.2.
