### ISSUE TITLE
Incorrect SHA-256 listed for 64-bit *Windows* Git LFS 2.0.2 .zip

### ISSUE THREAD

**Issue by dscho** [git-lfs/git-lfs#2113]
The SHA-256 is actually 1b33c8cb6e2e3238b48c639738d22d755a98f7cb62a994d026bb73c158508689, but that is listed as the hash of the 64-bit *Linux* package at https://github.com/git-lfs/git-lfs/releases/tag/v2.0.2.

**Comment by ttaylorr** [comment]
@dscho Fixed, thanks!
