### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by ccx1024cc** [git-lfs/git-lfs#2114]
when i first push to github,
i got this 'Authentication required: You must have push access to verify locks'

**Comment by ttaylorr** [comment]
@ccx1024cc thanks for opening this issue, and sorry that you're having trouble.

Could you post the output of the same command you ran that produced the error, with a `GIT_TRACE=1 GIT_CURL_VERBOSE=1` in front of it?

I'd also be curious about the output of `git lfs env`.

**Comment by ccx1024cc** [comment]
the information is this:
10:08:10.608485 git.c:344               trace: built-in: git 'push' 'origin' 'master'
10:08:10.608975 run-command.c:334       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/ccx1024cc/name_finder.git'
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.255.113...
* Connected to github.com (192.30.255.113) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: github.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: 
* 	 start date: Thu, 10 Mar 2016 00:00:00 GMT
* 	 expire date: Thu, 17 May 2018 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 Extended Validation Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /ccx1024cc/name_finder.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.7.4
Accept: */*
Accept-Encoding: gzip
Accept-Language: zh-CN, zh;q=0.9, en-US;q=0.8, en;q=0.7, *;q=0.6
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 53
< WWW-Authenticate: Basic realm="GitHub"
< X-Frame-Options: DENY
< X-GitHub-Request-Id: C20E:11AC5:14EB1D:209F38:58DC688B
< 
* Connection #0 to host github.com left intact
Username for 'https://github.com': 1261138729@qq.com
Password for 'https://1261138729@qq.com@github.com': 
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0x16843b0 [can pipeline]
* Hostname github.com was found in DNS cache
*   Trying 192.30.255.113...
* Connected to github.com (192.30.255.113) port 443 (#1)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL re-using session ID
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: github.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: 
* 	 start date: Thu, 10 Mar 2016 00:00:00 GMT
* 	 expire date: Thu, 17 May 2018 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 Extended Validation Server CA
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /ccx1024cc/name_finder.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.7.4
Accept: */*
Accept-Encoding: gzip
Accept-Language: zh-CN, zh;q=0.9, en-US;q=0.8, en;q=0.7, *;q=0.6
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 53
< WWW-Authenticate: Basic realm="GitHub"
< X-Frame-Options: DENY
< X-GitHub-Request-Id: C210:11AC6:1D2647:2D80E4:58DC6896
< 
* Ignoring the response-body
* Connection #1 to host github.com left intact
* Issue another request to this URL: 'https://github.com/ccx1024cc/name_finder.git/info/refs?service=git-receive-pack'
* Couldn't find host github.com in the .netrc file; using defaults
* Connection 0 seems to be dead!
* Closing connection 0
* Found bundle for host github.com: 0x16843b0 [can pipeline]
* Re-using existing connection! (#1) with host github.com
* Connected to github.com (192.30.255.113) port 443 (#1)
* Server auth using Basic with user '1261138729@qq.com'
> GET /ccx1024cc/name_finder.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic MTI2MTEzODcyOUBxcS5jb206Y2MxMDI0Y2N4
User-Agent: git/2.7.4
Accept: */*
Accept-Encoding: gzip
Accept-Language: zh-CN, zh;q=0.9, en-US;q=0.8, en;q=0.7, *;q=0.6
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< X-GitHub-Request-Id: C210:11AC6:1D267C:2D8105:58DC6897
< 
* Connection #1 to host github.com left intact
10:08:23.651655 run-command.c:334       trace: run_command: '.git/hooks/pre-push' 'origin' 'https://github.com/ccx1024cc/name_finder.git'
10:08:23.654715 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin' 'https://github.com/ccx1024cc/name_finder.git'
10:08:23.654788 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'https://github.com/ccx1024cc/name_finder.git'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: HTTP: POST https://github.com/ccx1024cc/name_finder.git/info/lfs/locks/verify
> POST /ccx1024cc/name_finder.git/info/lfs/locks/verify HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Length: 2
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.0.2 (GitHub; linux amd64; go 1.8; git 85e2aec4)
> 
{}trace git-lfs: HTTP: 403


< HTTP/1.1 403 Forbidden
< Content-Length: 154
< Content-Type: application/vnd.git-lfs+json
< Date: Thu, 30 Mar 2017 02:08:24 GMT
< X-Frame-Options: DENY
< X-Github-Request-Id: BFD8:11AC6:1D2708:2D81DA:58DC6898
< 
trace git-lfs: HTTP: {"documentation_url":"https://github.com/contact","message":"You must have push access to verify locks","request_id":"BFD8:11AC6:1D2708:2D81DA:58DC6898"}

{"documentation_url":"https://github.com/contact","message":"You must have push access to verify locks","request_id":"BFD8:11AC6:1D2708:2D81DA:58DC6898"}
Authentication required: You must have push access to verify locks



**_and after git lfs env, i got the this_** 


git-lfs/2.0.2 (GitHub; linux amd64; go 1.8; git 85e2aec4)
git version 2.7.4

Endpoint=https://github.com/ccx1024cc/name_finder.git/info/lfs (auth=none)
LocalWorkingDir=/home/ccx/workspace/name_finder
LocalGitDir=/home/ccx/workspace/name_finder/.git
LocalGitStorageDir=/home/ccx/workspace/name_finder/.git
LocalMediaDir=/home/ccx/workspace/name_finder/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/ccx/workspace/name_finder/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by ttaylorr** [comment]
@ccx1024cc interesting. It appears that LFS isn't filling out the `Authorization: ` header in the `/locks/verify` request. In your trace log, I'd expect to see something like:

> ```
> trace git-lfs: creds: git credential fill ("https", "github.com", "ccx1024cc/name_finder.git")
> ```

Do you have a credential helper that could be broken? Were you prompted for a credential? Do you have `lfs.cachecredentials` turned on?

**Comment by ccx1024cc** [comment]
thanks for answering
how to turn on   on lfs.cachecredentials?
how to resolve the problem? i am in hurry

**Comment by ttaylorr** [comment]
@ccx1024cc Unless you're using a shared computer, I don't think you need to turn `lfs.cachecredentials` on (though you can do that via `git config lfs.cachecredentials true`) as your credential helper should be caching the credentials for you.

**Comment by ttaylorr** [comment]
@ccx1024cc Could you please try an earlier revision of Git LFS (like: [v2.0.1](https://github.com/git-lfs/git-lfs/releases/tag/v2.0.1)) and let me know if you encounter this same issue?

**Comment by ccx1024cc** [comment]
ok，but maybe later. a little busy now

**Comment by ttaylorr** [comment]
@ccx1024cc Is it possible you could give me a timeframe on when you'd be able to run this on an earlier version? I am trying to reproduce this issue locally to figure out whether or not there's a bug in the release.

**Comment by ccx1024cc** [comment]
really sorry, i am not sure now.

**Comment by ttaylorr** [comment]
@ccx1024cc after some investigating, I found and patched an issue on the server-side. Your pushes should go through without issue.

**Comment by stahta01** [comment]
I have the same problem with v2.0.2, v2.0.1, and v1.5.6.
Found a work around with v1.5.6 likely works with later versions.

You need only a single entry in "netrc" that has the valid password and it works.

It also works if "netrc" is empty.

NOTE: On windows, I believe the "netrc" must have LF instead of CRLF to work correctly.

The next two lines is what failed to work for me; I changed the usernames in the lines. It does NOT like to work till I add the passwords after "password".
machine github.com login username1 password
machine bitbucket.org login username2 password

Tim S.

**Comment by stahta01** [comment]
I found the best solution for me if I remove the machine I am pushing to it works.

The next line it what is in my "netrc"; and pushing to github.com works!
machine bitbucket.org login username2 password

Tim S.

**Comment by lukaszgryglicki** [comment]
LOL I have a very old OAuth token stored in `netrc` - normal `git push` uses cache credential, but `git-lfs` was obviously reading `netrc`.
THANKS!
