### ISSUE TITLE
force user to use git lfs

### ISSUE THREAD

**Issue by fursu69** [git-lfs/git-lfs#2116]
Hello,

I think this is mostly common stuff but I don't know what to search for and i did not see any in the git-lfs guide i followed. 
----
We wanna try to use git lfs in one of our projects. I see a problem when a user that have not been informed or just ignore to use the git lfs starts to use same repo. 

scenario 1:
I push binary data with git-lfs. One part goes on lfs and other on git with a pointer to lfs.
Someone else check out my stuff while not using git lfs. He gets pointers that he can't use. Is there some way to raise an alert or prevent this?

scenario 2:
I start using git lfs. Someone else does not know this but see binary files in repo and think it's okey to put them there. He push without lfs and start to pile binarys on git. Is there some way to prevent this?

**Comment by ttaylorr** [comment]
@fursu69 👋, thanks for opening this issue. This isn't something that GitHub currently supports, but I think this is a great idea, and I'll file this suggestion away.
