### ISSUE TITLE
git lfs --version does nothing

### ISSUE THREAD

**Issue by alexbbrown** [git-lfs/git-lfs#2118]
git lfs --help should show a version
git lfs --version should show a version

this will make it easier for me to report issues here, with context.

**Comment by ttaylorr** [comment]
@alexbbrown thanks for opening this. I think the `--version` flag is fairly commonplace, so I think adding it to the next release would be a good idea. I'll add this issue to the 2.1.0 milestone.

In the meantime you can run either `git lfs env` or `git lfs version` to get the version information about LFS. `git lfs help <subcommand>` will also give you information about a particular subcommand.
