### ISSUE TITLE
Unable to get work git-lfs on Raspbian (raspberry pi 3)

### ISSUE THREAD

**Issue by Gergosz2** [git-lfs/git-lfs#2123]
I've read a previous issue about this problem but I think it isn't solved yet.

Since there are no available armhf packages, I  tried to build the source for myself. But this attempt of mine failed, because I am constatly getting errors for  

`go get github.com/github/git-lfs`

which are the following ones:

```
gocode/src/github.com/git-lfs/git-lfs/progress/copycallback.go:48: undefined: io.SeekStart
gocode/src/github.com/git-lfs/git-lfs/progress/copycallback.go:50: undefined: io.SeekCurrent
gocode/src/github.com/git-lfs/git-lfs/progress/copycallback.go:52: undefined: io.SeekEnd
```

Currently I am having go version 1.3.3.

**Comment by ttaylorr** [comment]
Hi @Gergosz2, thanks for opening this issue and sorry that you're having trouble!

> Currently I am having go version 1.3.3.

Git LFS is built against Go 1.8 and uses APIs from that version of Go. You'll need to install the Go 1.8 package and then build again using:

```bash
$ script/bootstrap
```

which will build Git LFS for your operating system and architecture.

**Comment by Gergosz2** [comment]
Thanks!

The outdated go was the problem.
