### ISSUE TITLE
Git Clone is not working for Large Files on MacOS Sierra 10.12.4 

### ISSUE THREAD

**Issue by tbehera** [git-lfs/git-lfs#2132]
git-lfs smudge '....': git-lfs: command not found
error: external filter 'git-lfs smudge %f' failed -1
error: external filter 'git-lfs smudge %f' failed
fatal: ...: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by ttaylorr** [comment]
Hi @tbehera thanks for opening this issue, and sorry that you're having trouble.

> git-lfs smudge '....': git-lfs: command not found

This means that LFS isn't in your `$PATH`, so it is not correctly installed on your system. Since you on macOS, you can install this easily by:

1. `brew update && brew upgrade git-lfs` OR `brew install git-lfs`
2. `git lfs install --system`

**Comment by tbehera** [comment]
Reinstalling is not fixing the issue.

brew install git-lfs
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing dependencies for git-lfs: go
==> Installing git-lfs dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.6.3.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/go-1.6.3.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/tapasbehera/Library/Logs/Homebrew/go/01.make.bash:
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208367088, 0xc2082aa000, 0x200, 0x200, 0xc2082aa000, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc208367088, 0xc2082aa000, 0x200, 0x200, 0x1, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc2082650a0, 0x46e300, 0xc208367088, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x47a7b8, 0xc2082650a0, 0x46e300, 0xc208367088, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc20813f160)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.

**Comment by ttaylorr** [comment]
@tbehera looks like there's an issue installing Go on your version of macOS. Are you running a developer preview?

**Comment by tbehera** [comment]
@ttaylorr yes. I am using MacOS Sierra 10.12.4 .

**Comment by ttaylorr** [comment]
Looks like Go has had problems building on this version of macOS. There's a fix recommended here: https://github.com/golang/go/issues/19734#issuecomment-290153973.

**Comment by tbehera** [comment]
I am not facing the issue anymore while cloning a repository.However, I see the following warning while installing git-lfs 

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.

It seems git-lfs might not work properly always on OS X 10.12 . I tested cloning a repository 10 times. Out of 10 tries, it failed once while cloning.

**Comment by DomT4** [comment]
@tbehera Your Homebrew is _way_ outdated. Try [this](https://github.com/Homebrew/brew#update-bug).
