### ISSUE TITLE
script.deb.sh on packagecloud.io

### ISSUE THREAD

**Issue by nucfisher** [git-lfs/git-lfs#2136]
Fix the deb package list installation script for git-lfs:
https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh

1. Using /etc/issue to detect OS version is incorrect. On proxmox-ve it returns empty value.
Just remove line 64 from script:
 **os=\`cat /etc/issue | head -1 | awk '{ print tolower($1) }'\`**

2. Add check if "os" var is empty after line 74:
**if [ -z "$os" ]; then
    unknown_os
fi**

**Comment by ttaylorr** [comment]
Hi @nucfisher thanks for opening this issue. We use these scripts that Packagecloud generates for us, so there's not much that we can do in the way of modifying them. Packagecloud has a `support@packagecloud.io` email address that you could try sending something to instead.

Sorry!
