### ISSUE TITLE
Smudge error: Error buffering media file: Failed to copy downloaded file: cannot replace..

### ISSUE THREAD

**Issue by neslekkim** [git-lfs/git-lfs#2137]
Is git-lfs really trying to rename an file from one drive to another?

git-lfs/1.5.2 (GitHub; windows 386; go 1.7.3; git 547a06aa)
git version 2.11.0.windows.1

$ git-lfs.exe filter-process
Error downloading object: Libraries/ourlib.dll (94179f85f26d8968314bcb2b59b3c9d3f01fc1355b65de1e5196332cb5f20e91)

Smudge error: Error buffering media file: Failed to copy downloaded file: cannot replace "D:\\Depot1\\proj\\.git\\lfs\\objects\\94\\17\\94179f85f26d8968314bcb2b59b3c9d3f01fc1355b65de1e5196332cb5f20e91" with "C:\\Users\\username\\AppData\\Local\\Temp\\bb-lfs-incomplete\\file-94179f85f26d8968314bcb2b59b3c9d3f01fc1355b65de1e5196332cb5f20e91": rename C:\Users\pba.AD\AppData\Local\Temp\bb-lfs-incomplete\file-94179f85f26d8968314bcb2b59b3c9d3f01fc1355b65de1e5196332cb5f20e91 D:\Depot1\prooj\.git\lfs\objects\94\17\94179f85f26d8968314bcb2b59b3c9d3f01fc1355b65de1e5196332cb5f20e91: The system cannot move the file to a different disk drive.:
github.com/git-lfs/git-lfs/errors.newWrappedError

**Comment by ttaylorr** [comment]
Hi @neslekkim thanks for opening this issue and sorry that you're running into this. I think there are two things that are happening here:

1. When creating a temporary file [`io/ioutil.TempFie()`](https://golang.org/pkg/io/ioutil/#TempFile) chooses a drive independent of where your working copy is.
2. During the smudge operation, via https://github.com/git-lfs/git-lfs/pull/1297 at [`transfer/basic_download.go:L218`](https://github.com/git-lfs/git-lfs/blob/v1.5.2/transfer/basic_download.go#L218), a cross-volume `os.Rename()` occurs which is illegal.

I think there are a few ways we could fix this:

1. Teach `io/ioutil.TempFile()` to pick the same drive as your working copy, or...
2. Implement a wrapped `os.Rename()` that can function cross-volume. 

I think the first option may be more preferable since it wouldn't involve any non-portable syscall stuff, but I'm curious what the rest of @git-lfs/core thinks.

**Comment by ttaylorr** [comment]
@neslekkim some more updates: I found and fixed another instance where we could potentially create a temporary on a different volume than your .git folder or your working copy. That being said, I don't think that instance was related to this one.

Is it possible that your working directory is different than your `.git` dir? The output of `git lfs env` would give us some more details.

**Comment by neslekkim** [comment]
we sadly again, had to revert our try on lfs, we have tried many times, and every time we meet an roadblock like this, even on small projects. So we had to revert lfs, so we could proceed work.
Will try to reproduce in an test repository later.

But. We are using sourcetree and bitbucket cloud, so we always checkout with sourcetree, and workingfolder is same as where .git is, we don't mess around with that, and I'm not sure how we could separate that either?

**Comment by ttaylorr** [comment]
@neslekkim sorry that you are having trouble with Git LFS. Could you please run `git lfs env` in a shell in your repository and post the output here?

**Comment by sschuberth** [comment]
FWIW, I agree option 1. is better, also because option 2. might have performance implications.

**Comment by ttaylorr** [comment]
@neslekkim I patched the only instance of `io/ioutil.TempFile()` that I think could cause any sort of cross-volume copying in #2140. Would you mind giving one of these builds a try and see if it resolves the issue for you?

[git-lfs-darwin-386-2.1.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/911053/git-lfs-darwin-386-2.1.0-pre.tar.gz)
[git-lfs-darwin-amd64-2.1.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/911058/git-lfs-darwin-amd64-2.1.0-pre.tar.gz)
[git-lfs-freebsd-386-2.1.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/911056/git-lfs-freebsd-386-2.1.0-pre.tar.gz)
[git-lfs-freebsd-amd64-2.1.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/911054/git-lfs-freebsd-amd64-2.1.0-pre.tar.gz)
[git-lfs-linux-386-2.1.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/911057/git-lfs-linux-386-2.1.0-pre.tar.gz)
[git-lfs-linux-amd64-2.1.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/911055/git-lfs-linux-amd64-2.1.0-pre.tar.gz)
[git-lfs-windows-386-2.1.0-pre.zip](https://github.com/git-lfs/git-lfs/files/911059/git-lfs-windows-386-2.1.0-pre.zip)
[git-lfs-windows-amd64-2.1.0-pre.zip](https://github.com/git-lfs/git-lfs/files/911060/git-lfs-windows-amd64-2.1.0-pre.zip)

**Comment by ttaylorr** [comment]
Going to close this out for now since there hasn't been any activity in the past week. @neslekkim: if the problem persists, please don't hesitate to re-open this issue!
