### ISSUE TITLE
all: build against Go 1.8.1

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#2141]
Go 1.8.1 was [recently released](https://groups.google.com/forum/#!topic/golang-nuts/KO2t50AYo9I). In the spirit of staying on the latest and greatest Golang, I'd like to build LFS v2.1.0 on this release of Go.

I'd like to give this release a few days to get support in AppVeyor, on Hombrew, and to make sure that there are no new regressions.

Thoughts?

---

/cc @git-lfs/core

**Comment by technoweenie** [comment]
Sounds good :+1:

**Comment by sschuberth** [comment]
Is there any real benefit in upgrading to 1.8.1, or is it only for the sake of being a cool kid and using the latest? If there's no real benefit I don't believe it's worth to switch to 1.8.1 if that means we again have to manually install it in AppVeyor instead of being able to use using Chocolatey.

**Comment by technoweenie** [comment]
Bug fixes in 1.8.1: https://github.com/golang/go/issues?q=is%3Aissue+milestone%3AGo1.8.1+is%3Aclosed

I don't see any reason to mess with the chocolatey code, just to revert it once they update Go. Hopefully Chocolatey is on the latest Go by the time LFS v2.1.0 is ready.

**Comment by sschuberth** [comment]
> Bug fixes in 1.8.1: https://github.com/golang/go/issues?q=is%3Aissue+milestone%3AGo1.8.1+is%3Aclosed

I know the list of fixes. What I meant was if someone checked that we actually do benefit of these in this project. But I've now checked myself and there seem to be some pretty generic compiler / runtime fixes.

Anyway, Chocolately already has [Go 1.8.1](https://chocolatey.org/packages/golang), so from that perspective I have no objections anymore.

**Comment by ttaylorr** [comment]
> What I meant was if someone checked that we actually do benefit of these in this project.

These are good questions. My reasoning for opening the proposal and getting on the latest version of Go was to minimize the gap between current and "next" release. Even if these bug fixes don't benefit us directly, they bring us closer to Go 1.8.x (x > 1) which could have a critical fix that we need to be on. For those necessary upgrades, I want the change in Go version to be as small as possible so that there's less chance for unexpected behavior/interaction with the Go compiler.
