### ISSUE TITLE
--skip-smudge does not work

### ISSUE THREAD

**Issue by rivaros** [git-lfs/git-lfs#2142]
I already run both:
```
 git lfs install --skip-smudge
 git lfs install --skip-smudge --local
```

My local .gitconfig looks like 
```
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge --skip -- %f
        process = git-lfs filter-process --skip
        required = true
```

but when I do ```git merge upstream\master``` to merge commit on which tons of LFS files added, it starts
loading them fully, not just placeholders.

**Comment by rivaros** [comment]
Only when I edit .gitconfig like
```
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge =
        process = git-lfs filter-process --skip
        required = false
```
it starts to work and only placeholders are loaded.

This I took from Atlassian tutorials (Speeding up pulls)
https://www.atlassian.com/git/tutorials/git-lfs

Could someone explain me the difference. What skip SMUGDE is supposed to do at all ???

**Comment by technoweenie** [comment]
The `skip-smudge` option skips downloading missing LFS objects. It will copy them over if they already exist in your `.git/lfs/objects` directory.
