### ISSUE TITLE
Git-lfs on ubuntu/xential

### ISSUE THREAD

**Issue by fir3wall** [git-lfs/git-lfs#2143]
Hello,

I'm stuck after trying to install / update my git-lfs package any hints how to troubleshoot as my git repos now does not work

OS is ubuntu 16.04, tried to purge package etc everything not working

```
╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$ sudo apt-get install git-lfs                                                                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git-lfs is already the newest version (2.0.2).
0 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up git-lfs (2.0.2) ...
Git LFS initialized.
line 1: unexpected token login 
dpkg: error processing package git-lfs (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 git-lfs
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by ttaylorr** [comment]
Hi @fir3wall, thanks for opening this issue and sorry that you're having trouble. I see a few interesting things in your logs:

> ```
> Setting up git-lfs (2.0.2) ...
> Git LFS initialized.
> ```

That "Git LFS initialized" message is the output of running `git lfs install`, so it appears that the `apt-get install` got at least that far.

> line 1: unexpected token login dpkg: error processing package git-lfs (--configure):
>   subprocess installed post-installation script returned error exit status 2

The post installation script that is run on deb packages is defined [here](https://github.com/git-lfs/git-lfs/blob/v2.0.2/debian/postinst), and is equivalent to running a `git lfs install --system`. I'm not sure where that error message would be coming from, but I'm curious what happens when you do the following:

1. Run `git lfs env`,
2. Run `sudo git lfs install --system`
3. `sudo apt-get uninstall git-lfs && apt-get install git-lfs`.

**Comment by fir3wall** [comment]
Hi,
Please find result of request comands below

`╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$ git lfs env
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8)
git version 2.7.4

Endpoint=https://git.dionglobal.eu/ukdevops/salt.git/info/lfs (auth=none)
  SSH=git@git.dionglobal.eu:ukdevops/salt.git
line 1: unexpected token login 
╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$ sudo git lfs install --system                                                                                                                                                                                                         2 ↵
Updated git hooks.
Git LFS initialized.
line 1: unexpected token login 
╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$ sudo apt-get uninstall git-lfs && apt-get install git-lfs.                                                                                                                                                                            2 ↵
E: Invalid operation uninstall
╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$ sudo apt-get remove git-lfs && apt-get install git-lfs.                                                                                                                                                                             100 ↵
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED
  git-lfs
0 to upgrade, 0 to newly install, 1 to remove and 6 not to upgrade.
After this operation, 10.7 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 481957 files and directories currently installed.)
Removing git-lfs (2.0.2) ...
Global Git LFS configuration has been removed.
line 1: unexpected token login 
dpkg: error processing package git-lfs (--remove):
 subprocess installed pre-removal script returned error exit status 2
Git LFS initialized.
line 1: unexpected token login 
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 git-lfs
E: Sub-process /usr/bin/dpkg returned an error code (1)
╭─dariuszn@innocence  ~/repos/ukdevops/salt  ‹master› 
╰─$        
`

**Comment by ttaylorr** [comment]
Hi @fir3wall, can you please let us know if you have resolved the issue? I am going to close this since it is stale, but if you are still encountering troubles with the latest release, please do not hesitate to let me know here and I'd be happy to re-open it.

**Comment by chrisd8088** [comment]
As this particular issue appears to be quite stale, so I'm going to close it now.

(Note that the normal Long-Term Support window for Ubuntu 16.04 (Xenial Xerus) release ended in April 2021, and so the Git LFS project stopped distributing packages for it as of our release version 3.3.0.)
