### ISSUE TITLE
proposal: `migrate` sub-command

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#2146]
## Objective

Make it easier for people to start using Git LFS when they already have large
objects committed into Git repositories.

## Background

One of the common issues that people run into is going along the following path:

1. Start with a Git repository that has large objects in the history
2. `git lfs track *.dat`
3. Attempt to push to a remote, have the push fail a `post-receive` hook, and
stop using Git LFS.

The underlying problem is an expectation that `git lfs track` will convert
previously existing large Git blobs to LFS objects, which it does not do. `git
lfs track` only tracks object within LFS _after_ those changes to the
`.gitattributes` file have been cached.

What we have recommended thus far is to either run `git-filter-branch(1)` or
download an external tool with the same purpose (one example of this is BFG:
https://github.com/rtyley/bfg-repo-cleaner).

## Solution

I would like to make it possible for Git LFS to do this conversion without
needing to run a complicated `git-filter-branch(1)` command or use an external
tool. By implementing this in Git LFS ourselves, we have control of the behavior
of the migration tool, which would allow us to implement features like:

1. Forward and backward (to and from LFS objects) migrations
2. Specific file-path matching
3. Fast, LFS-specific object caching

If we could bundle a migration tool to convert large blobs in Git history to LFS
objects within Git LFS itself, we would also be able to:

1. Make it easier for users to adopt Git LFS
2. Cut down on a class of bug reports where `git lfs track` is run against large
objects that already exist

### Flags

I'd like the `git-lfs-migrate(1)` command to have the following options:

1. `-I`, `-X` (or `--include` and `--exclude`): our standard pattern matching
flags to dictate which objects should and shouldn't be tracked by Git LFS

A non-goal here is `--greater-than=` or `--less-than=` size flags, since this
type of pattern matching is not support in the attributes specification at
https://git-scm.com/docs/gitattributes.

### Sub-commands

At first I thought it would be unnecessary to supply a "reverse" (from LFS
object to Git large object) migration, because the migration command would be
able to build a parallel DAG of commit objects and then do a `git-update-ref(1)`
at the end, producing a `git reflog` like:

```bash
~/example-repo (master) $ git reflog
dc0b3c60 HEAD@{1}: checkout: moving from master-lfs-migrate to master
115a1a1 HEAD@{2}: commit: tools/time_tools: test tools.IsExpiredAtOrIn
...
```

Meaning that the user could do a `git-reset(1)` (with the `--hard`) flag to move
their repository back to its original state.

This approach falls short when dealing with a scenario where the original
repository (with the dangling refs) has been removed. Similarly, it does not
deal with a `git gc` or `git prune --expires=now`. In other words, if the old,
large Git objects are gone, there is no way to restore your repository.

That being said, I'd like to have both a:

1. `git lfs migrate up`, and
2. a `git lfs migrate down`

to go to and from storing objects in LFS respectively.

## Technical Overview

The `git-lfs-migrate(1)` command should build a parallel commit DAG by walking
the history in topological (`--topo`) ordering and then update the refs all at
once at the end.

Step-by-step, this would be (for the forward conversion):

1. For each ref:
  1. For each file in that ref matching the `-I` and `-X` flags:
    1. Iteratively calculate the shasum (256) of that file's contents
    2. Generate (and optionally cache) a pointer corresponding to that file
    3. Write the pointer to disk
    4. Call `git-update-index(1)` to replace that file in the index of the
       current ref.
  2. Call `git-write-tree(1)`, attaching the appropriate parents to the current
     "new" commit.
3. Call `git-update-ref(1)` to move the refs from the old history to the new
   one.

And for the backward conversion:

1. For each ref:
  1. For each file in that ref that is parse-able as a pointer and matches the
     `-I` and `-X` flag(s).
    1. Fetch an `io.Reader` handle on the contents of the file in the cache
    2. Write that file to disk
    3. Call `git-update-index(1)` to replace that file in the index of the
       current ref.
  2. Call `git-write-tree(1)`, attaching the appropriate parents to the current
     "new" commit.
3. Call `git-update-ref(1)` to move the refs from the old history to the new
   one.

### Optimizations

I can think of a few ways to optimize the operation of the `git-lfs-migrate(1)`
command:

1. Instead of a full tree-scan:
  1. Calculate the diff between each pair of consecutive revisions
  2. Replace all pointers from the last revision that were unchanged
  3. Update (or create) all pointers for new or changed files that match the
     `-I` and `-X` flag(s).
2. Instead of reading the entire contents of a file each time, cache it based on
   the OID it has in Git's ODB.
3. Parallelize the tree-walk and re-assemble the DAG in chunks, using the same
   diffing and caching strategies as above.

---

/cc @git-lfs/core for thoughts and/or concerns
/cc @peff for thoughts on the technical overview and additional insight into possible optimizations

**Comment by peff** [comment]
I think this is a good idea and direction.

Regarding the "reverse" migration: I suspect reflogs will generally save you for the first 30 days. But I agree there should be a general way to easily undo the migration, even from a clone which was not the original one to do the forward migration. The operation should be pretty simple; it's just the inverse of the migration, replacing pointers by the actual objects (and fetching them via LFS if need be). And because you're not touching timestamps or anything like that in the commits, a migrate/unmigrate pair should end up with the exact same sha1s as they had originally.

Regarding efficiency: the _most_ efficient way to do it is to replace the blobs, then trees containing them, then trees containing those, and so on, flooding the changes back up to the ref tips (you basically walk over a reverse topo-sorted list of objects in the graph). But that's complicated, and it also makes it really hard to do path-matching (because paths aren't a property of blobs; they're just where the blobs happen to be referenced).

So walking chronologically through history (again, in topological order) is a must. Your intuition about using diffs is correct, but remember that history isn't linear. You have to compare against the parent (and as long as we're topo-sorted, you know we'll already have seen the parent). But you also have to deal with merges. There, I think you are really looking for any entries which aren't contained in _any_ of the parents.

Internally in git, we'd generally do this by just marking each object with a SEEN flag, and not bothering to dig into things we've seen SEEN. In fact, you have to maintain a mapping of old->new anyway. So that works as your SEEN flag (things which don't need rewriting just get a mapping entry of old->old). And effectively memo-izes the tree rewrites.

So your logic is something like:

```
hashmap map

rewrite_tree(tree) {
  if (map.find(tree) != nil)
    return map.find(tree)

  new_tree = []
  for e in tree_entries(tree) {
    if (e.type == tree)
      new_tree += [e.mode, e.path, rewrite_tree(e.sha1)]
    else if (e.type == blob)
      rewrite_blob(e.sha1)
    else
      new_tree += e
  }
  map.insert(tree, rehash(new_tree))
  return map.find(tree)
}

for c in commits_in_reverse_topo_order() {
  c->tree = rewrite_tree(c->tree)
  foreach p in c->parents
    p = map.find(p)
  map.insert(c->sha1, rehash(c))
}

for r in refs() {
  r.update(map.find(r.sha1))
}

```

That's an absurd mix of various programming languages lumped into pseudocode, but hopefully it's understandable.

There's one other optimization you can do, too. In the loop over the tree entries, you can cull any subtrees which can't be part of your pathspec (so if you're limiting yourself to "foo/big", you know that the top-level "bar" is not worth even descending). That doesn't work if you have wildcards, though (like "*.mp4"). So it may not be worth implementing.

And one final note: you'll want to rewrite tags, too (which topo-sort before all commits, but need sorted within themselves, since taags can point to other tags). If the tags are signed, you'll invalidate their signatures, so you have to decide what to do there.

**Comment by technoweenie** [comment]
This sounds like a sane approach to me. A couple random thoughts:

* The `up` and `down` subcommands seem vague. I kind of like convert/revert.
* What does the command look like with multiple `-I` or `-X` flags? 
* When is `.gitattributes` built? I think it'd be cool to slip into the first commit or something.
* How do you know what order to process each ref? If you have branches `master`, `feature1`, and `feature2`, you wouldn't want to re-process the common ancestors of the feature branches.

**Comment by larsxschneider** [comment]
I like this, too! 👍 

If possible I would like to distinguish two cases:

#### CASE A - Fix all history
Rewrite the entire history to move files that match a pattern to Git LFS (I think this is the option you described above). This operation should come with a big warning message that all your team members should push their branches first and that they should re-clone after you force pushed the rewritten result.

### CASE B - Fix *only* recent history
Rewriting the entire history is sometimes not desired or possible. However, rewriting commits that are not yet public is a safe thing to do. For example, if GitHub rejected my commit because I accidentally committed a 500MB file then it would be nice if Git LFS could offer me nice little command to fix that issue without any `rebase` etc invocation. That command would be very useful for my Git/Git LFS users.

**Comment by technoweenie** [comment]
Case B is a great use case too :+1:

**Comment by ttaylorr** [comment]
> And because you're not touching timestamps or anything like that in the commits, a migrate/unmigrate pair should end up with the exact same sha1s as they had originally.

Agree 👍.

> So your logic is something like:

I think we're on the same page, and thanks for sharing such a detailed example of how this could work. The way that it's implemented in #2122 is essentially:

1. For each revision, topologically sorted:
2. Walk through all blobs, recursively, culling out any subtrees that don't match the include/exclude set(s)
3. For each blob that matches:
4. Create a new blob with `git hash-object -w`
5. Update the index at that revision with the new blob with `git update-index --cacheinfo`
6. Write the new commit, attaching it to its parent(s) (if any).

With that approach, my concern is twofold:

- Having to checkout the index at each revision is expensive and makes it impossible to parallelize this.
- Rewriting each matching blob forces us to cache pointers, not trees, which is less intuitive.

> There's one other optimization you can do, too. In the loop over the tree entries, you can cull any subtrees which can't be part of your pathspec [...] That doesn't work if you have wildcards, though (like "*.mp4"). So it may not be worth implementing.

We make a best-effort attempt to do this from the `github.com/git-lfs/git-lfs/filepathfilter` package, which ignores any subtrees listed in any `.gitignore` file. Since we're allowing prefixed wildcards, I don't think we could cull out subtrees in all cases, but certainly in scenarios that match `/^((.*)\/)+/`. 

> but need sorted within themselves, since taags can point to other tags).

Good call.

> If the tags are signed, you'll invalidate their signatures, so you have to decide what to do there.

I think invalidating the signed tags would be fine, though we could allow the user to decide by adding a `--invalidate-signed-tags` or `--no-invalidate-signed-tags` flag.

**Comment by ttaylorr** [comment]
> The `up` and `down` subcommands seem vague. I kind of like convert/revert.

I agree, I think sticking with `convert` and `revert` sounds good to me 👍 .

> What does the command look like with multiple `-I` or `-X` flags?

Each `-I` and `-X` would be OR'd together, I think.

> When is `.gitattributes` built? I think it'd be cool to slip into the first commit or something.

Right now I'm adding a `.gitattributes` entry into the first commit that has any paths matching those in the `-I` or `-X` filter, but this could easily be changed to go anywhere before that point in history. I think my preference would be to delay adding the `.gitattributes` entry until the first commit at which that object appears, since that brings us closer to the 1:1 mapping of old history to new, and to me, is clearer in terms of not having a (potentially) huge `.gitattributes` entry up front.

> * How do you know what order to process each ref? If you have branches `master`, `feature1`, and `feature2`, you wouldn't want to re-process the common ancestors of the feature branches.

By going through the revision history in a topologically sorted order, we can easily eliminate looking at common ancestors.

**Comment by ttaylorr** [comment]
> > So your logic is something like:
> 
> I think we're on the same page, and thanks for sharing such a detailed example of how this could work. The way that it's implemented in #2122 is essentially:
> 
> 1. For each revision, topologically sorted:
> 2. Walk through all blobs, recursively, culling out any subtrees that don't match the include/exclude set(s)
> 3. For each blob that matches:
> 4. Create a new blob with `git hash-object -w`
> 5. Update the index at that revision with the new blob with `git update-index --cacheinfo`
> 6. Write the new commit, attaching it to its parent(s) (if any).

@peff While responding to @technoweenie's comment, I realized why it makes more sense to cache trees, instead of pointers. If we can eliminate a whole unchanged sub-tree, then we don't have to crawl it and recalculate work that's already been done.

I'll just have to figure out a way to do this in Go. We so far haven't used anything like github.com/libgit2/git2go since cgo adds some complications to our build process. I'll do some investigating as it pertains to LFS and see which approach makes sense to go forward with.

**Comment by ttaylorr** [comment]
> #### CASE B - Fix _only_ recent history

@larsxschneider Great call, I think we could make this possible by adding a range argument to the migrate command:

```bash
$ git lfs migrate convert -I "*.dat"
```

would convert all history, whereas:

```bash
$ git lfs migrate convert -I "*.dat" HEAD~5
```

or

```bash
$ git lfs migrate convert -I "*.dat" HEAD~5...HEAD
```

would only touch the last five commits.

**Comment by peff** [comment]
> Having to checkout the index at each revision is expensive and makes it impossible to parallelize this.

Right, loading the index is inherently full-tree. That's what I was trying to show with the recursive tree-rewriting above. You only have to dig into the subtrees you care about, and you only have to touch each subtree once.

**Comment by technoweenie** [comment]
> `git lfs migrate convert -I "*.dat" HEAD~5`

I'd prefer a nicer command, like `git lfs migrate convert -I "*.dat" --unpushed`. I don't want LFS users to have to think about commit ranges too much.

> Right now I'm adding a .gitattributes entry into the first commit that has any paths matching those in the -I or -X filter, but this could easily be changed to go anywhere before that point in history.

I'm personally in favor of slipping it into the initial commit. Shouldn't hurt to specify patterns before they get added to LFS.

**Comment by ttaylorr** [comment]
> > `git lfs migrate convert -I "*.dat" HEAD~5`
> 
> I'd prefer a nicer command, like `git lfs migrate convert -I "*.dat" --unpushed`. I don't want LFS users to have to think about commit ranges too much.
> 
> >

What do you think about having both? My thought with specifying a commit base or range would be that more advanced users would want to have greater control over which commits they were changing. Otherwise, they could just use an `--unpushed` flag to grab over the range of unpushed commits.

**Comment by larsxschneider** [comment]
I agree that the commit ranges can be complicated for users (I am serious).

How about this:

GitHub responds with something like this when you push a file that exceeds the limit:
```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
remote: error: File path/to/large.dat is 542.38 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
```

What if GitHub would respond like this (we would need to find a better wording):
```
remote: error: GH001: Large files detected.
remote: error: If you're using Git LFS, run `git lfs migrate convert -I "*.dat" cf11a67`
remote: error: If you're not using Git LFS then you may want to try it - https://git-lfs.github.com.    
remote: error:    
remote: error: File path/to/large.file is 542.38 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
```

The Git server never saw commit `cf11a67` and every commit after. Therefore it would be safe to rewrite.

**Comment by ttaylorr** [comment]
> What if GitHub would respond like this (we would need to find a better wording):
> 
>     remote: error: GH001: Large files detected.
>     remote: error: If you're using Git LFS, run `git lfs migrate convert -I "*.dat" cf11a67`
>     remote: error: If you're not using Git LFS then you may want to try it - https://git-lfs.github.com.    
>     remote: error:    
>     remote: error: File path/to/large.file is 542.38 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
>     
> The Git server never saw commit `cf11a67` and every commit after. Therefore it would be safe to rewrite.

I really like this idea. @technoweenie: thoughts?

**Comment by technoweenie** [comment]
Sure, that's independent of this feature. We can change that text once this feature ships in Git LFS :)

**Comment by peff** [comment]
> The Git server never saw commit `cf11a67` and every commit after. Therefore it would be safe to rewrite.

Unless `cf11a67` has been pushed somewhere else public. I don't know how much we'd want to care about that case (it's certainly going to be a tiny minority, but the consequences could be nasty).

**Comment by andyneff** [comment]
For the server reply, I think this is a good argument for the `--greater-than` stretch goal. Instead of 

> ```
> remote: error: If you're using Git LFS, run `git lfs migrate convert -I "*.dat" cf11a67`
> ```

Shouldn't we say more

```
remote: error: If you're using Git LFS, run: git lfs migrate convert --greater-than=100MB cf11a67
```

That way the server doesn't have to try and figure out a glob expression for you, and maybe accidentally add a lot of files to LFS you don't want. For example: maybe 1000 files are 1kB, and only one of them is 500MB. 



> > Right now I'm adding a .gitattributes entry into the first commit that has any paths matching those in the -I or -X filter, but this could easily be changed to go anywhere before that point in history. I think my preference would be to delay adding the .gitattributes entry until the first commit at which that object appears, since that brings us closer to the 1:1 mapping of old history to new,
>
> I'm personally in favor of slipping it into the initial commit. Shouldn't hurt to specify patterns before they get added to LFS.

I am actually more inclined to lean towards @ttaylorr's first implementation. I like the idea that the commits before the LFS files are still the same shas, and thus the graphs are topologically connected to each other. I don't know. I just feels good to me ;)

On a more practical note. Some of us call out SHAs specifically (not just in submodules, but for exampled I want to checkout a specific untagged commit in a script, I'll use the sha). So there's a *small* chance that less things will break but not redoing all the commits. Just a thought.

**Love** the idea of git-lfs-migrate, BTW. :)

**Comment by ttaylorr** [comment]
> That way the server doesn't have to try and figure out a glob expression for you, and maybe accidentally add a lot of files to LFS you don't want.

Do you mean that `--greater-than` would have the LFS client walk through tree entries and find ones over `n` bytes, then select patterns that match them? We can't pass this information straight into a `.gitattributes` file, since that only does filepath pattern matching and doesn't know about tree entry meta-information.

**Comment by ttaylorr** [comment]
> > > Right now I'm adding a .gitattributes entry into the first commit that has any paths matching those in the -I or -X filter, but this could easily be changed to go anywhere before that point in history. I think my preference would be to delay adding the .gitattributes entry until the first commit at which that object appears, since that brings us closer to the 1:1 mapping of old history to new,
> > 
> > 
> > I'm personally in favor of slipping it into the initial commit. Shouldn't hurt to specify patterns before they get added to LFS.
> 
> I am actually more inclined to lean towards @ttaylorr's first implementation. I like the idea that the commits before the LFS files are still the same shas, and thus the graphs are topologically connected to each other. I don't know. I just feels good to me ;)

Sorry for the super-threaded comment. @andyneff -- thanks for putting this into words for me. I wasn't exactly sure why I liked the idea of introducing .gitattributes changes at the first matching commit, but the topological connected-ness is a good argument.

@technoweenie what do you think about going with this?

**Comment by technoweenie** [comment]
I agree it seems like the more correct behavior. I think it's worth it if the implementation isn't too complicated.

**Comment by ttaylorr** [comment]
> I think it's worth it if the implementation isn't too complicated.

I think this may be easier, so we should be good.

**Comment by ttaylorr** [comment]
> ```c
> for c in commits_in_reverse_topo_order() {
>  c->tree = rewrite_tree(c->tree)
>  foreach p in c->parents
>    p = map.find(p)
>  map.insert(c->sha1, rehash(c))
> }
> ```

Making a note on this after following up with @peff: `commits_in_reverse_topo_order` implies the same output as: `git rev-list --reverse --topo-order`. Doing so ensures that the parents of each commit will have already been seen, so `p = map.find(p)` is a safe lookup, always.

**Comment by peff** [comment]
> Doing so ensures that the parents of each commit will have already been seen, so p = map.find(p) is a safe lookup, always.

One case where it might not be is if you gave a lower boundary to the traversal (e.g., because you only wanted to rewrite unpushed commits). In that case you'd find that the boundary commits are not in your map, and the correct outcome is to use their sha1s verbatim.
