### ISSUE TITLE
.lfsconfig

### ISSUE THREAD

**Issue by amousa1968** [git-lfs/git-lfs#2149]
1. Installed git lfs client on a local windows 10 
2. Created git lfs repository in artifactory
3. created .lfsconfig file at the root level the git local working directory 
4. copy paste 
[lfs]
url = "https://user_name:API_KEY@
hostname_stage_artifactory.com/artifactory/api/lfs/gitlfs-stage"  

5. Push to origin.

warning: current Git remote contains credentials
Git LFS: (0 of 6 files) 0 B / 178.39 MB                                        warning: current Git remote contains credentials
Git LFS: (2 of 6 files) 1.78 MB / 178.39 MB                                    warning: current Git remote contains credentials
warning: current Git remote contains credentials
Git LFS: (2 of 6 files) 1.93 MB / 178.39 MB                                    warning: current Git remote contains credentials
Git LFS: (2 of 6 files) 2.12 MB / 178.39 MB
LFS: Client error:

Can anyone advice what is wrong?

**Comment by technoweenie** [comment]
Looks like you stripped out the actual error after "LFS: Client error:".

Are you referring to the warning? Storing your creds in a plain text file is not a great security practice. You should be using a Git credential helper or a netrc file. However, you can ignore the warning if you really want to store the API key in `.lfsconfig`.

**Comment by amousa1968** [comment]
Nope, the problem was not because of the url.  I dug more with the errors and it was due to the size being uploaded to git-lfs repo.  I changed the size and seems to resolve the issue for the url.  this can be closed.
