### ISSUE TITLE
Fetched images are 1kb

### ISSUE THREAD

**Issue by AstralProgrammer** [git-lfs/git-lfs#2150]
Its my first time trying out **git lfs** I was able to create and push data as per the tutorial.

The issue came up as I was checking the files after cloning them to a test server. Files are present although they are all showing as 1kb filesize.

GIT LFS ENV:
**Server** 
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8)
git version 2.7.4
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**My Local**
git-lfs/2.0.2 (GitHub; windows amd64; go 1.8; git 85e2aec4)
git version 1.9.5.msysgit.0
Endpoint=https://oxygel@bitbucket.org/lkg/wpapi.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Angel\PHP7\shared\apache2\html\wpapi
LocalGitDir=C:\Angel\PHP7\shared\apache2\html\wpapi\.git
LocalGitStorageDir=C:\Angel\PHP7\shared\apache2\html\wpapi\.git
LocalMediaDir=C:\Angel\PHP7\shared\apache2\html\wpapi\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Angel\PHP7\shared\apache2\html\wpapi\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

already tried running **git lfs fetch** , **git pull**

It returns error like these:
batch request: Unexpected error. If you contact support, include this error ID: 9b9274d34680478fbcf9551e69a13cc0: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: ec5ea1bf980a4a0dac80cd9e744f1844: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 777496b833364813a7b543f39ffec8f4: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: c85ff541a5374f8c8d79a76806d5e8ed: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 882606461f9a4f9ba9b184d8059f6608: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 0c6002cdf05142a69ab672c1f840c7b8: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 85ad9bbe91ea468f942fafe026800260: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: c48d9d5d0de34d9a93a95051aae9563b: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: e4c54c9be76f4d93aaa0eb54dfe5e39b: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 5674a6ebeb1d4bab890803b714b39566: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 9fae3729db404f778c3444092b5fb3d7: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: c88060aaecc74b179374147f7c68a4c2: exit status 1
batch request: Unexpected error. If you contact support, include this error ID: 27c4eca3593942fd854f2da7a67d9a12: exit status 1

**Comment by technoweenie** [comment]
That looks like a server error. Try contacting your LFS host with one of those error IDs.

**Comment by technoweenie** [comment]
@AstralProgrammer This FAQ for LFS on BitBucket may be of help too: https://confluence.atlassian.com/bitbucket/current-limitations-for-git-lfs-with-bitbucket-828781638.html#CurrentlimitationsforGitLFSwithBitbucket-AccesskeysdonotallowaccesstotheGitLFSfiles
