### ISSUE TITLE
Weird Git LFS clone progress output

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#2151]
Hi,

I just cloned a Git LFS repo and got a weird progress output on OSX.
The number of files and the LFS file size summary is ever increasing
(in total the repo has 11 GB in LFS):

```
git-lfs clone --recursive https://xxx/yyy/zzz.git
Cloning into 'zzz'...
remote: Counting objects: 115112, done.
remote: Compressing objects: 100% (41700/41700), done.
remote: Total 115112 (delta 70872), reused 115109 (delta 70871), pack-reused 0
Receiving objects: 100% (115112/115112), 165.94 MiB | 2.83 MiB/s, done.
Resolving deltas: 100% (70872/70872), done.
Checking out files: 100% (66872/66872), done.
Git LFS: (99 of 201 files) 401.16 MB / 746.51 MB
Git LFS: (99 of 201 files) 401.16 MB / 746.51 MB  
Git LFS: (298 of 401 files) 1.02 GB / 1.12 GB 
Git LFS: (298 of 401 files) 1.02 GB / 1.12 GB    
Git LFS: (500 of 701 files) 1.30 GB / 3.46 GB  
Git LFS: (500 of 701 files) 1.65 GB / 3.46 GB
Git LFS: (500 of 701 files) 1.65 GB / 3.46 GB
Git LFS: (500 of 701 files) 1.65 GB / 3.46 GB
Git LFS: (500 of 701 files) 1.65 GB / 3.46 GB  
...
Git LFS: (1128 of 1301 files) 4.08 GB / 4.60 GB
...
```

Noticeable things:
- The repo has no submodules (--recursive is part of a script)
- The repo uses Glob pattens in .gitattributes
   e.g. `*.[Bb][Mm][Pp] filter=lfs diff=lfs merge=lfs -text`
- The repo uses full path patterns with spaces in .gitattributes
    e.g. `/aaa/bbb/ccc[[:space:]]ddd/fff[[:space:]]ggg[[:space:]]hhh/jjj.jpg filter=lfs diff=lfs merge=lfs -text`

Git/Git LFS versions:
```
$ git --version
git version 2.12.2
$ git lfs version
git-lfs/2.0.2 (GitHub; darwin amd64; go 1.8)
```

Any idea how that might happen?

Thanks,
Lars

**Comment by ttaylorr** [comment]
Hey @larsxschneider, I think what you're seeing here is expected LFS behavior where, while cloning, LFS doesn't make subsequent batch calls until it has finished transferring objects from the current batch. This causes the "of <n> files" and "/ <n> GB" parts of the progress meter to monotonically increase while pushing/pulling.

Is the batch being over-counted? That's a known issue with the progress meter when using transfer options other than basic_upload and basic_download.

**Comment by larsxschneider** [comment]
> while cloning, LFS doesn't make subsequent batch calls until it has finished transferring objects
I am not sure I understand your answer. I do *clone* here. If LFS doesn't make subsequent batch calls ... shouldn't I see the correct final file count/size right from the beginning?

**Comment by ttaylorr** [comment]
> > while cloning, LFS doesn't make subsequent batch calls until it has finished transferring objects
> 
> I am not sure I understand your answer. I do _clone_ here. If LFS doesn't make subsequent batch calls ... shouldn't I see the correct final file count/size right from the beginning?

Sorry, I'm just realizing that my original response wasn't clear. What I meant was: "LFS _does_ make batch calls in sequence, but not until _after_ it has completed the first batch."

In other words, this means:

1. Make a batch request to download the first 100 objects
  a. Increment the total number of objects to download in the progress meter by 100
  b. Download those objects.
  c. Retry failed ones until either a fatal error occurs, or the amount of available retries has been exceeded.
2. Make another batch request
  a. If response contains no objects, exit.
  b. Otherwise, see step 1.a.

**Comment by larsxschneider** [comment]
But then the progress meter is always confusing for large repos.

E.g. first I see this and I think "yeah, I am almost there"...
```
Git LFS: (99 of 201 files) 401.16 MB / 746.51 MB
```

... but a bit later LFS surprises me with this and I think "ohh, still a long way to go"
```
Git LFS: (500 of 701 files) 1.65 GB / 3.46 GB  
```

Wouldn't it be better to show "just progress" instead of a wrong y in "x of y files"?

**Comment by ttaylorr** [comment]
> Wouldn't it be better to show "just progress" instead of a wrong y in "x of y files"?

How would you want to format this? I've had some ideas for changes that we could make to the progress meter...

**Comment by larsxschneider** [comment]
Hm... I am running into this over and over again.  Wouldn't it be possible to query the number of GitLFS files from Git *before* running the first batch call? Then we could print the correct "Y" in `Git LFS: (X of Y files)`, no?

If this is not possible then I would rather print `Git LFS: (X files) Z MB` only. Printing a potentially wrong total count seems confusing to me.

**Comment by ttaylorr** [comment]
> Wouldn't it be possible to query the number of GitLFS files from Git _before_ running the first batch call?

This is the way that LFS used to work prior to 2.0.0. This method requires a full tree scan, which is what the new progress meter is trying to avoid. If the root tree is large, LFS would have to spend a noticeable amount of time first scanning the tree to count the objects, and _then_ display the progress meter.

**Comment by larsxschneider** [comment]
That makes sense to me. What do you think about displaying just `Git LFS: (X files) Z MB` in the "batching situation"?

**Comment by ttaylorr** [comment]
> What do you think about displaying just `Git LFS: (X files) Z MB` in the "batching situation"?

Seems reasonable to me. @technoweenie: what do you think?

**Comment by larsxschneider** [comment]
ping 😄

**Comment by technoweenie** [comment]
That sounds fine. Maybe add a spinner that stops once it's finished scanning the history, but still transferring objects. Pretty sure the `fetch` command has a spinner that we can use.
