### ISSUE TITLE
LFS pull very slow with invalid --include path

### ISSUE THREAD

**Issue by shoelzer** [git-lfs/git-lfs#2153]
In my repo, this takes about 15 seconds:

    git lfs pull --exclude= --include="some\valid\path"

While this takes over 8 minutes:

    git lfs pull --exclude= --include="path\that\does\not\exist"

Test conditions:
* Repo with about 10k LFS files that total 16 GB
* Windows 7
* git version 2.12.1.windows.1
* git-lfs/2.0.1 (GitHub; windows amd64; go 1.8; git 678cdbd4)

**Comment by technoweenie** [comment]
Hi, thanks for the bug report. Nothing really stood out to me while looking at the code. I made a custom build with extra tracing info for you:

[git-lfs-windows-amd64-2.1.0-pre.zip](https://github.com/git-lfs/git-lfs/files/922620/git-lfs-windows-amd64-2.1.0-pre.zip)

Can you run `GIT_TRACE=1 git lfs pull --exclude= --include="path\that\does\not\exist"` and send me the output? If you want to keep that data private, feel free to send to https://github.com/contact and mention me so our support team can route the email to me.

Here's what the output looks like on my system:

```sh
$ rm -rf .git/lfs/objects && GIT_TRACE=1 git lfs pull --include=test/foo/bar
11:43:56.450899 git.c:600               trace: exec: 'git-lfs' 'pull' '--include=test/foo/bar'
11:43:56.451445 run-command.c:350       trace: run_command: 'git-lfs' 'pull' '--include=test/foo/bar'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config branch.master.remote
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: run_command: git ls-tree -r -l -z --full-tree 06ef0b8748e43d970819e471fe0ab4a8ae579a11
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} ".gitattributes" (6.17µs)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "README.md" (264ns)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "a.bin" (150ns)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "c.bin" (142ns)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "dup-test444.bin" (153ns)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "dup-test66.bin" (110ns)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "hi" (135ns)
trace git-lfs: inc (*filepathfilter.basicPattern) &{rawPattern:test/foo/bar} "test1.bin" (197ns)
```

This test build is based on 2fb111ef1ba1425d3a9e05856820f99075a8f9bc, with the following diff:

```diff
diff --git a/filepathfilter/filepathfilter.go b/filepathfilter/filepathfilter.go
index aee2616f..378d6d0d 100644
--- a/filepathfilter/filepathfilter.go
+++ b/filepathfilter/filepathfilter.go
@@ -5,6 +5,9 @@ import (
        "path/filepath"
        "regexp"
        "strings"
+       "time"
+
+       "github.com/rubyist/tracerx"
 )

 type Pattern interface {
@@ -38,7 +41,9 @@ func (f *Filter) Allows(filename string) bool {
        if len(f.include) > 0 {
                matched := false
                for _, inc := range f.include {
+                       t := time.Now()
                        matched = inc.Match(cleanedName)
+                       tracerx.Printf("inc (%T) %+v %q (%+v)", inc, inc, cleanedName, time.Since(t))
                        if matched {
                                break
                        }
@@ -50,7 +55,10 @@ func (f *Filter) Allows(filename string) bool {

        if len(f.exclude) > 0 {
                for _, ex := range f.exclude {
-                       if ex.Match(cleanedName) {
+                       t := time.Now()
+                       matched := ex.Match(cleanedName)
+                       tracerx.Printf("exc (%T) %+v %q (%+v)", ex, ex, cleanedName, time.Since(t))
+                       if matched {
                                return false
                        }
                }
```

**Comment by shoelzer** [comment]
@technoweenie Thanks for looking into this! I got the custom build and tried to reproduce the issue but I couldn't. Then I went back to my original version of LFS and still couldn't reproduce the issue. Hmm.

After playing around I did find a different way to trigger a slow down. I run this command every time:

    git lfs pull --exclude= --include=*

If my working dir is the repo root, it is fast (15 seconds). If my working dir is a subfolder 3 levels down it is slow (8 minutes). I ran both ways with `GIT_TRACE=1` but unfortunately the trace messages don't help much. Here's the start of messages from a slow run:

```11:18:07.690627 git.c:596               trace: exec: 'git-lfs' 'pull' '--exclude=' '--include=*'
11:18:07.691627 run-command.c:369       trace: run_command: 'git-lfs' 'pull' '--exclude=' '--include=*'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config branch.develop.remote
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config -l -f C:\Home\repo.git\.lfsconfig
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: run_command: git ls-tree -r -l -z --full-tree a3f2988e9719d4df1e0f7c2b85619c58a5dd2cfa
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: inc (*filepathfilter.pathlessWildcardPattern) &{rawPattern:* wildcardRE:0xc0421ca320} ".gitattributes" (0s)
trace git-lfs: inc (*filepathfilter.pathlessWildcardPattern) &{rawPattern:* wildcardRE:0xc0421ca320} ".lfsconfig" (0s)
...
```

I think Windows timer resolution must be around 1 ms, because almost all files have "0s", and just a few have "1ms". For some reason "rawPattern" is not writing out a string. In a fast run from the repo root, I get `rawPattern:* wildcardRE:0xc04204dea0`. Maybe you can make sense of that. Finally, I will note that there are no "exc" messages from the fast or slow runs, which I think confirms that all LFS files are already up to date.

**Comment by ttaylorr** [comment]
Hi @shoelzer, could you try this scenario again on your repository using the latest version of Git LFS? I have rewritten the implementation of package `filepathfilter`, which is the underlying implementation of things like `--include` and `--exclude`.

It should be significantly faster than previous versions.

If this isn't the case, please do not hesitate to let me know here and I'd be happy to take another look at this.

**Comment by shoelzer** [comment]
I don't know when you revamped `filepathfilter`, but I tested with LFS 2.3.4 (my current install) and it is always fast. Thanks!
