### ISSUE TITLE
GitHub not showing GIT LFS files until the are deleted.?.?.?

### ISSUE THREAD

**Issue by Carracer66** [git-lfs/git-lfs#2155]
Followed instructions here: https://github.com/git-lfs/git-lfs/wiki/Installation
And everything seems ready to go; however, when I add, commit and push large files (~160MB), the command executes successfully:

     git lfs push origin master
     Git LFS: (11 of 11 files) 1.43 GB / 1.43 GB

but the files don't appear on my GitHub webpage.  git lfs on the client thinks they have pushed.  
git lfs status
On branch master
Git LFS objects to be pushed to origin/master:

        registry/centos-7.1503_MAPL-0.25.tar.gz (72.3 MB)
        registry/consul-0.5.2_MAPL-0.25.tar.gz (76.9 MB)
        registry/nginx-1.8.0_MAPL-0.25.tar.gz (114.8 MB)
        registry/rev_algorithm-1.0_MAPL-0.25.tar.gz (159.9 MB)
        registry/rev_algorithmset-1.0_MAPL-0.25.tar.gz (159.8 MB)
        registry/rev_event-1.0_MAPL-0.25.tar.gz (159.8 MB)
        registry/rev_hibernate-base-1.0_MAPL-0.25.tar.gz (159.8 MB)
        registry/rev_postgresql-1.0_MAPL-0.25.tar.gz (96.7 MB)
        registry/rev_preprocess-1.0_MAPL-0.25.tar.gz (159.9 MB)
        registry/rev_publicapi-1.0_MAPL-0.25.tar.gz (153.2 MB)
        registry/rev_service-base-1.0_MAPL-0.25.tar.gz (153.2 MB)

Git LFS objects to be committed:

Git LFS objects not staged for commit:

Try to push them again:

        git lfs push origin master
        Git LFS: (0 of 0 files, 11 skipped) 0 B / 0 B, 1.43 GB skipped

Then if I delete the files, commit, and push, now the files appear on the web page, but they are removed on the client machine and git lfs thinks they are gone.

Okay....   it looks like this has something to do with all of my commits/pushes not being reflected in a timely manner on the GitHub web page.  This morning, the history was not showing a commit that I did 17 hours ago.  I tried clearing my browser cache; no change.  Then, all of a sudden, it is showing two commits from 17 hours ago and my commit from today???

git lfs version
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8; git 85e2aec)

docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by Carracer66** [comment]
Okay.  I figured it out....

After you do a git lfs push origin master, you need to do git push origin master.

git add -A
git commit -m "Comments"
git lfs push origin master
git push origin master

**Comment by technoweenie** [comment]
You should be able to do `git push origin master`. LFS installs a pre-push hook that uploads LFS objects before the Git push.
