### ISSUE TITLE
New user setup - git lfs ls-files is empty while git lfs track is non-empty

### ISSUE THREAD

**Issue by vvasuki** [git-lfs/git-lfs#2157]
I was following https://github.com/git-lfs/git-lfs/wiki/Tutorial , and everything was fine until I got to: "Now, when you run git lfs ls-files, you will see the list of tracked files". Instead, I don't get any output. But, when I run `git lfs track` I get:
```

Listing tracked patterns
    data/quote_db__sa.cblite2 (.gitattributes)
    data/annotation_db__sa.cblite2 (.gitattributes)

```

Is everything as expected (and the tutorial needs to be fixed) or should I do something to fix my setup?

For reference, my git lfs env:
```
git lfs env
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8; git 85e2aec4)
git version 2.9.3

Endpoint=https://github.com/sanskrit-coders/subhAShita-db-sanskrit.git/info/lfs (auth=none)
  SSH=git@github.com:sanskrit-coders/subhAShita-db-sanskrit.git
LocalWorkingDir=/home/vvasuki/subhAShita-db-sanskrit
LocalGitDir=/home/vvasuki/subhAShita-db-sanskrit/.git
LocalGitStorageDir=/home/vvasuki/subhAShita-db-sanskrit/.git
LocalMediaDir=/home/vvasuki/subhAShita-db-sanskrit/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/vvasuki/subhAShita-db-sanskrit/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

**Comment by ttaylorr** [comment]
Hi @vvasuki, thanks for opening this issue. There are a few things that could be going on here with why the files aren't showing up in `git lfs ls-files`.

1. The files don't exist in your working copy. `git lfs ls-files` runs a `git ls-files -r --full-tree` (recursively list all blobs in a repository from the root). If the files that you're looking for don't appear there, then they don't have a chance of making it into the output of `git lfs ls-files`.
2. More likely, the files _do_ exist in your working copy, but aren't parse-able as Git LFS pointers. This can happen if you commit the files as large objects _before_ running `git lfs track <pathspec>`. `git lfs track` only tracks files going forward, so you'd have to convert the history of your repository with a `git filter-branch` command to migrate large Git blobs to LFS. There is some additional work being discussed via #2146 to help with this.

Let me know if any of this helps, and if you have any future issues, please don't hesitate to re-open this issue and comment.
