### ISSUE TITLE
2.0.2 requires Go 1.8+, not 1.7.3

### ISSUE THREAD

**Issue by QuLogic** [git-lfs/git-lfs#2163]
The readme for 2.0.2 states that Go 1.7.3+ is required. However, #2080 (backported in #2094) added the use of `time.Until` which was only [added in Go 1.8](https://golang.org/doc/go1.8#time).

**Comment by technoweenie** [comment]
Thanks for the report. The readme looks fixed in master. Though we should definitely be more cautious about bumping the Go version in a patch series release like 2.0.2.

**Comment by QuLogic** [comment]
Well, yes, but it should be updated on the patch branch unless there are never going to be any updates  coming out of it. Or it could be patched to work with 1.7 again (I can provide a patch.)

**Comment by ttaylorr** [comment]
> unless there are never going to be any updates coming out of it.

Hi, I think this branch introducing a dependency on the Go 1.8+ API was my fault (via https://github.com/git-lfs/git-lfs/pull/2080 & https://github.com/git-lfs/git-lfs/pull/2094), but there won't be any more release coming from the release-2.0 tree, as the next release will be v2.1.0.

If this changes, I'll make sure to patch that tree to be 1.7 compatible.
