### ISSUE TITLE
Pushing to local directory

### ISSUE THREAD

**Issue by githubkusi** [git-lfs/git-lfs#2164]
The current Git LFS API only supports https. This means Git LFS adds a webserver dependency on top of the regular Git workflow. With regular Git, we used to push to another local or mapped network folder. This is unfortunately not possible anymore with Git LFS

It was mentioned in [this issue](https://github.com/git-lfs/git-lfs/issues/479#issuecomment-120740439) that it doesn't have priority in v1. Since v2 is now released, you might consider again this missing feature?

**Comment by technoweenie** [comment]
This isn't something we're planning on, but would love to accept a contribution for it. I even have a rough idea how it could be implemented. The challenge is that Git LFS leans on a public API pretty heavily to abstract the following things:

* Object management (what objects exist, where to upload or download them)
* Object uploads and downloads
* Centralized file locking

I think the [`http.RoundTripper` interface](https://golang.org/pkg/net/http/#RoundTripper) could be used to mimic those APIs for URI schemes like `file://`, without requiring major changes to the rest of the codebase.

**Comment by ttaylorr** [comment]
> I think the [`http.RoundTripper` interface](https://golang.org/pkg/net/http/#RoundTripper) could be used to mimic those APIs for URI schemes like `file://`, without requiring major changes to the rest of the codebase.

I think this is a great approach. As @technoweenie mentioned, this isn't something that's on our roadmap, but I'd be more than happy to help someone through to submitting a pull request.

**Comment by ttaylorr** [comment]
Hi @githubkusi, thanks for holding on this for such a long time! I've been going through old issues and clearing out things that I don't anticipate changing much or have already been resolved. I think that, while this is a great suggestion, I'm not sure it's an appropriate feature for Git LFS, even for the sake of "feature-parity" with upstream Git.

Large files are an inherently "heavy" transfer, whereas Git packs are relatively speaking more lightweight. Therefore, I would defer to options like `lfs.storage`, which allows multiple repositories to use the same on-disk cache with different individual repositories.

Do you think that would be a sufficient alternative? Thanks for holding, again. I am going to close this issue out for now, but if enough people deem this an important feature to add I will happily re-open it.

**Comment by jasonbeach** [comment]
I'm interested in this issue as well.  The problem I'm trying to figure out is how to use git cleanly with binary  files when there is no internet connection...i.e. we're out in the field away from the office with no internet (but do have a small LAN with 3-4 laptops connected).  With straight git, we can just designate one machine as the new "origin" and have all the team members push to it and then once we're back in the office, sync it to the actual origin.   From what I understand of LFS, the one designated machine would have to be running some sort of https git server, which seems pretty heavy handed.  Is there another solution?

**Comment by bk2204** [comment]
There is a plan to add support for an SSH-based LFS protocol, which might meet your needs better than the current HTTPS-based solution, but as of yet one hasn't been implemented.  You'd still need some sort of Git LFS server in that situation, though, to store the LFS objects.

**Comment by kballard** [comment]
The inability to push to a local directory breaks the idiom of `git push . HEAD:foo`. Not only does it break it, but the error message doesn't implicate `git-lfs` at all, so I spent a while digging through the git release notes to try and figure out when they removed support for `git push .` until I realized it only happened in my git-lfs–enabled repo.

Personally, I think that `git-lfs` should simply let me push to any local path without interfering in the slightest. If you're really worried that the user will then delete the source repo in the belief that they pushed their git-lfs blobs, the hook could print a warning saying that git-lfs blobs will not be pushed, though I don't really think that's necessary.

At the very least, `git-lfs` should silently allow pushes to `.`, because pushing to `.` definitely wouldn't need to push any git-lfs blobs anyway.

**Comment by KalleOlaviNiemitalo** [comment]
I too would like to use `git push . HEAD:foo`.  Workarounds:

* `git update-ref refs/heads/foo HEAD`, which is longer to type and does not check whether the operation removes commits
* `git -c core.hooksPath=/dev/null push . HEAD:foo`, which uses /dev/null as a directory but works anyway 😜
* Change the last line of `.git/hooks/pre-push` to
  ```sh
  [ "$2" == . ] || git lfs pre-push "$@"
  ```
  but this has to be done in each repository.

**Comment by chloekek** [comment]
There exists [git-lfs-standalone-file](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-standalone-file.adoc) which, as far as I can tell from the documentation, implements this. But I’m not sure how to use it.

**Comment by bk2204** [comment]
I believe this has been implemented, so I'm going to close this.  It's been implemented well before 3.0.
