### ISSUE TITLE
Git push returns with "batch response: Post https://user-xyz@xyz.mmmm.com/stash/scm/xyz/repo_lfs_test.git/info/lfs/objects/batch: remote error: tls: handshake failure"

### ISSUE THREAD

**Issue by mserfli** [git-lfs/git-lfs#2165]
Hello,
I'm trying to push some LFS blobs to a Bitbucket server with activated LFS. I'm always getting a tls handshake error from the report.
How can I get more feedback from the remote "repo_lfs_test.git/info/lfs/objects/batch" than with :
`
GIT_CURL_VERBOSE=1 git push
...
> POST /stash/scm/xyz/repo_lfs_test.git/info/lfs/objects/batch HTTP/1.1
> Host: xyz.mmmm.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Length: 119
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.0.2 (GitHub; windows amd64; go 1.8; git 85e2aec4)
>
Git LFS: (0 of 1 files) 0 B / 27 B
batch response: Post https://user-xyz@xyz.mmmm.com/stash/scm/xyz/repo_lfs_test.git/info/lfs/objects/batch: remote error: tls: handshake failure
`

**Comment by technoweenie** [comment]
That sounds like a configuration problem between you and your LFS service. Your best bet may be to try contacting Atlassian for the correct SSL settings. One thing to look into is whether Stash requires SSL client certs.

**Comment by mserfli** [comment]
I'm using a self-signed certificate, but http.sslverify is set to false. Also pushing non-LFS files to Stash work without any problem. Does somebody have experiences with the LFS plugin for JFrog Artifactory? Probably I can use this instead of the Atlassian LFS service if this is the problem.

Are there any environment variables for LFS to get more debugging output?

**Comment by mserfli** [comment]
The problem doesn't exist anymore while updating to LFS 2.1.0
