### ISSUE TITLE
LFS does not halt push when lock is held on object

### ISSUE THREAD

**Issue by derrickstolee** [git-lfs/git-lfs#2166]
If someone holds a lock on a file, LFS currently only provides a text warning that the path is locked. The git push succeeds and thus the remote gets in a bad state (it has the LFS pointer object but the LFS object was not pushed). It requires using a `git lfs push [remote] --all` or `git lfs push [remote] --object-id [id]`.

[Here is the line that only warns](https://github.com/git-lfs/git-lfs/blame/13719e4c9387a3c7a07b921dac76f8374f33c064/commands/uploader.go#L330)

It was introduced by #1885 
Due to issue #1884 
And issue #1878 
And adding the failed push apparently was waiting on #1951 and #2093 

Based on the above history, LFS should be ready to fail when pushing a path that is locked by someone else.

In addition: It would probably be good to start warning when pushing an object without owning the lock.

**Comment by technoweenie** [comment]
Good call. That was the point of https://github.com/git-lfs/git-lfs/issues/1884, but I think that crucial step of _failing the push_ got lost somewhere along the way. Should be a relatively easy fix. Thanks for the report!
