### ISSUE TITLE
smudge filter lfs failed when merging a branch

### ISSUE THREAD

**Issue by tonygod** [git-lfs/git-lfs#2173]
$ git merge develop
Updating 6c6ad6d..dafd7b7
error: git-lfs smudge -- 'Assets/PostProcessing/Resources/Bluenoise64/LDR_LLL1_32.png' died of signal 11
error: external filter 'git-lfs smudge -- %f' failed 139
error: external filter 'git-lfs smudge -- %f' failed
fatal: Assets/PostProcessing/Resources/Bluenoise64/LDR_LLL1_32.png: smudge filter lfs failed

I don't know what signal 11 means or "139."

**Comment by ttaylorr** [comment]
This directory structure looks similar to the one reported in #2172. Moving discussion there.

**Comment by tonygod** [comment]
This was because there were two versions of git-lfs on my machine.  after removing the old git-lfs and re-linking the new one, the problem is solved.
