### ISSUE TITLE
git lfs push fails on SSH based remotes on VSTS git repo

### ISSUE THREAD

**Issue by lukka** [git-lfs/git-lfs#2186]
Pushing to an SSH remote (and the repo is on VSTS) gives this error:

```
git lfs push origin master
Git LFS: (0 of 1 files) 0 B / 11.35 KB
batch request: Your Git command did not succeed.
Details:

        Could not find a Command Extension for Command:git-lfs-authenticate: exit status 1
```

while using an HTTPS remote works just fine:

```
git lfs push originhttp master
Git LFS: (1 of 1 files) 11.35 KB / 11.35 KB
```

git version 2.12.2.windows.2
git-lfs/2.0.2 (GitHub; windows amd64; go 1.8; git 85e2aec4)

**Comment by lukka** [comment]
apparently GIT-LFS works only on HTTPS protocol.

**Comment by jacano** [comment]
Hi guys, Are there plan for this feature to be supported?
