### ISSUE TITLE
git push - HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by Pranav02** [git-lfs/git-lfs#2191]
I am facing below issue. HTTP/1.1 403 Forbidden

11:13:52.519135 git.c:350 trace: built-in: git 'push' 'origin' 'LFS-test'
11:13:52.522970 run-command.c:336 trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '''Pranav02/dcos-cassandra-service.git''''
11:13:56.389772 run-command.c:336 trace: run_command: '.git/hooks/pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
11:13:56.395773 git.c:563 trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
11:13:56.396276 run-command.c:336 trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github.com:Pranav02/dcos-cassandra-service.git'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: ssh: git@github.com git-lfs-authenticate Pranav02/dcos-cassandra-service.git upload
trace git-lfs: HTTP: POST https://lfs.github.com/Pranav02/dcos-cassandra-service/locks/verify

POST /Pranav02/dcos-cassandra-service/locks/verify HTTP/1.1
Host: lfs.github.com
Accept: application/vnd.git-lfs+json; charset=utf-8
Authorization: RemoteAuth AHDiXNXLzlqEJvCgWWYLpO6EASekt9MCks5ZBx9_wA==
Content-Length: 2
Content-Type: application/vnd.git-lfs+json; charset=utf-8
User-Agent: git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
{}trace git-lfs: HTTP: 200

< HTTP/1.1 200 OK
< Content-Length: 41
< Content-Type: application/vnd.git-lfs+json
< Date: Mon, 01 May 2017 05:44:00 GMT
< X-Github-Request-Id: 1270:6F20:39C101C:4A4B7FA:5906CB1F
<
trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

{"ours":[],"theirs":[],"next_cursor":""}
trace git-lfs: pre-push: refs/heads/LFS-test e584ca8b106020030a20a31428fc0b8cb84e6436 refs/heads/LFS-test 0000000000000000000000000000000000000000
trace git-lfs: run_command: git rev-list --objects e584ca8b106020030a20a31428fc0b8cb84e6436 --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: sending batch of size 5
trace git-lfs: ssh: git@github.com git-lfs-authenticate Pranav02/dcos-cassandra-service.git upload
trace git-lfs: api: batch 5 files
trace git-lfs: HTTP: POST https://lfs.github.com/Pranav02/dcos-cassandra-service/objects/batch

POST /Pranav02/dcos-cassandra-service/objects/batch HTTP/1.1
Host: lfs.github.com
Accept: application/vnd.git-lfs+json; charset=utf-8
Authorization: RemoteAuth AHDiXBekwEwScU8LO1KideEkLU5tFpVvks5ZBx-HwA==
Content-Length: 478
Content-Type: application/vnd.git-lfs+json; charset=utf-8
User-Agent: git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
{"operation":"upload","objects":[{"oid":"30bf5fbac0cfbc9201cac1d6973dbc96e5f55043ab315eda8c7aeb23df4f2644","size":73676107},{"oid":"bab04ef8ad997197a0e4f02250ed71240f339a44209b8d9f941ee6291130fa9a","size":31027554},{"oid":"6f5468dd8fb8a2cd84fef950ab945bfafaa405edffa5c62fdc1a475e9f86b4ef","size":27721301},{"oid":"363631f4dafcf934b2a33e6919f3db33f0dd5630de62b851424f00ae76e80cb0","size":205},{"oid":"f595019467466ddb8f06c2909f4f59c54f2707a3fd433d4ceea5594dea28bf7a","size":40}]}trace git-lfs: HTTP: 403

< HTTP/1.1 403 Forbidden
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Content-Security-Policy: default-src 'none'
< Content-Type: application/json; charset=utf-8
< Date: Mon, 01 May 2017 05:44:08 GMT
< Server: GitHub.com
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Media-Type: unknown
< X-Github-Request-Id: 1270:6F20:39C153C:4A4B880:5906CB20
< X-Ratelimit-Limit: 3000
< X-Ratelimit-Remaining: 2999
< X-Ratelimit-Reset: 1493617508
< X-Xss-Protection: 1; mode=block
<
trace git-lfs: HTTP: {"message":"@Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service","documentation_url":"https://github.com/contact"}
{"message":"@Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service","documentation_url":"https://github.com/contact"}trace git-lfs: api error: @Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service
Git LFS: (0 of 5 files) 0 B / 126.29 MB
batch response: @Pranav02 can not upload new objects to public fork Pranav02/dcos-cassandra-service
error: failed to push some refs to 'git@github.com:Pranav02/dcos-cassandra-service.git'

**Comment by technoweenie** [comment]
GitHub doesn't allow LFS uploads to a public fork unless source repository uses LFS already. You can [contact support](https://github.com/contact) about detaching your fork for the repository, which will allow you to upload LFS objects.
