### ISSUE TITLE
Need documentation for repository repair or way to actually force a push

### ISSUE THREAD

**Issue by allaryin** [git-lfs/git-lfs#2193]
I have a client with a 30gb repository stored primarily in LFS (via GitLab). If I do a fetch --all, I get 30 gigs of files, plus 404's on 6 of them. But the 6 problematic files all exist on disk and contain valid data - so I am assuming that these 404's are merely for ancient historical versions of the files.

I need to create a full mirror of the repository, but cannot because git bails with "LFS upload failed" on the six files in question (after having successfully uploaded the other 30gb of data to our server).

After fighting this issue for several days, upgrading git-lfs to 2.1.0, and continuing to fight it for two more, I am at a loss. I cannot find any comprehensive documentation on how to simply make this push happen so I can move on to actually using the data. I don't care about losing a little history, just as long as the bulk remains intact.

**Comment by ttaylorr** [comment]
Hi @allaryin, thanks for opening this issue and giving me a detailed look at what you're trying to accomplish. Here are some thoughts:

The behavior that you're encountering was formalized in https://github.com/git-lfs/git-lfs/pull/2082, and is meant to warn users about all missing objects in a push, so they can fix them at once for the next push. This doesn't quite match the behavior you're looking for, which I believe is to just ignore the missing files and go on.

Right now, there's no "blessed" way to do this. We had discussed adding a `--strict-mode` flag (in https://github.com/git-lfs/git-lfs/pull/2078), where the absence of such a flag would allow pushes like the ones that you're describing. Ultimately, this did not make it into master.

The best way to get around the missing data right now is to:

- rewrite the points in history that reference those missing pointers, or
- add the file back to `.git/lfs/objects`

**Comment by allaryin** [comment]
(I'd love to have asked this elsewhere, but the chat room linked from the project page is dead and this appears to be the only place questions get answered)

The man files are spartan, and since you chose recently not to implement a feature that might have actually solved this problem, I stand by my original request for documentation. As it is, most of the leads I've followed have been in the form of ticket history like this... which is frankly kind of sad. A project with this level of visibility needs better formal documentation - especially when issues like this are complete showstoppers for people.

I can't simply replace the files, as I am apparently missing the versions of the files that are missing. But even knowing what the hash you output meant and where it was stored on disk involved reading the protocol specification.

I've seen dozens of people talk about simply going back and deleting history... but 1) isn't that exactly the sort of activity that leads to this sort of problem in the first place, and 2) I haven't found anything explaining how to find the point in git history where a given lfs oid is referenced.

**Comment by technoweenie** [comment]
I think we can revisit the strict-mode option for pushes for v2.2.0. Reopened https://github.com/git-lfs/git-lfs/pull/2078 to discuss this.

Thanks for your feedback. Better documentation is on our roadmap.

**Comment by ttaylorr** [comment]
@allaryin apologies for closing this (and #2063) early. I opened up #2199 to address this and allow you to push by first running:

```
git config lfs.allowincompletepush true
```

I'm hoping to release this as a part of 2.2.0, but I'd be more than happy to provide you with a build once that pull request is merged.

**Comment by allaryin** [comment]
@ttaylorr thanks for taking care of this. I forked and built the patch and:

```
$ git lfs version
git-lfs/2.2.0-pre (GitHub; darwin amd64; go 1.8.1; git fb4fe81b)
$ git config lfs.allowincompletepush true
$ git push -u archive beta
...
Git LFS: (0 of 7 files, 7048 skipped) 0 B / 165.19 MB, 29.22 GB skipped
LFS upload missing objects:
  (missing) Assets/### (18aecaf4fc67af4c7e616f7eb883471ddfd1fd50268c3b4f5ab05cebd339261a)
  (missing) Assets/### (e90b89d4d57ed0ca4164aa048147138a1ba4c4b7637d4a54a390d1d3e058d1d6)
  (missing) Assets/### (725bc03b1c6b64092121ac9a004e536ec094252446a5588fc03f7b9d09b6390d)
  (missing) Assets/### (9f3a79c95f870ea147824cea3d9ec61ee30a6dc1a8f5b91549423316d5359d41)
  (missing) Assets/### (cd56aea58f067cbda0290d9da2b5d4bc0043dde1d6b9484f42bcae6431e6d37f)
  (missing) Assets/### (4c077f7f9775de4163ac12ccc98b8330f604a3c7d5781623de3a1298c63ccf64)
  (missing) Assets/### (cf5deaeb27cb004967a3c7cb76955e2c5bbd6f921e29b114a5289f78a542b04a)
Counting objects: 36567, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18154/18154), done.
Writing objects: 100% (36567/36567), 13.80 MiB | 3.09 MiB/s, done.
Total 36567 (delta 18533), reused 36345 (delta 18353)
remote: Resolving deltas: 100% (18533/18533), done.
To https://git.###.com/###/###.git
 * [new branch]        beta -> beta
Branch beta set up to track remote branch beta from archive.
```
