### ISSUE TITLE
...are linux directions supposed to work?

### ISSUE THREAD

**Issue by mharradon** [git-lfs/git-lfs#2194]
I went through the process of installing git-lfs on my box so I could upload a single 500MB data file to my repo (that should be version controlled).

Now I have to enter my password and username 4 times to do a commit, and I still cannot commit my data file.

These directions did nothing for me, after 5 attempts at installation: https://git-lfs.github.com/

When I `git add` I see:

```
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like 'latest.pkl' that are
removed from your working tree are ignored with this version of Git.

* 'git add --ignore-removal <pathspec>', which is the current default,
  ignores paths you removed from your working tree.

* 'git add --all <pathspec>' will let you also record the removals.

Run 'git status' to check the paths you removed from your working tree.
```

Of course --ignore-removal does nothing. I still see file sizes error messages after 10 minutes of compression. Is it really the end of the world for github to consider file sizes that the real world wants in version control?

What git-lfs has taught me is that I want to commit my data file to version control, and that github clearly doesn't care about my use-case - so I'm going to move off github to my own private git server. If you had never suggested it to me I might have been satisfied with github as-is, but the existence of git-lfs made me realize that my own git server would be far superior. So, thanks, I guess!

**Comment by damnMeddlingKid** [comment]
to add to this. I followed the package cloud instructions and im getting 

```
/usr/local/bin/git-lfs: 1: /usr/local/bin/git-lfs: Syntax error: "(" unexpected
dpkg: error processing package git-lfs (--configure):
 subprocess installed post-installation script returned error exit status 2
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by technoweenie** [comment]
@mharradon Thanks for your feedback. Judging by that error message, you may want to upgrade your version of Git. I've never seen that message from Git before, so I can't help without knowing the state of the repository.

@damnMeddlingKid That error looks like you downloaded LFS for the wrong platform. Can you open a **new thread** with details on how you're installing LFS, and on what platform? Adding on to a totally different issue makes things more difficult, thanks.
