### ISSUE TITLE
push fails because there is no prompt for authentication

### ISSUE THREAD

**Issue by robwiss** [git-lfs/git-lfs#2200]
I wasn't expecting to see an auth prompt when I did a git push and ctrl+c'd it out of habit. Now when I try to push don't get an authentication prompt, I get
```
Authentication required: Authorization error: http://server/scm/pro/project.git/info/lfs/locks/verify
Check that you have proper access to the repository
error: failed to push some refs to 'ssh://git@server/pro/project.git'
```

**Comment by technoweenie** [comment]
What version of LFS are you on?

**Comment by technoweenie** [comment]
Actually, judging by the output, I'd wager you're on 2.0.x. Try upgrading to LFS v2.1.0, as we tweaked that file lock check code a bit. It should still print a warning for you, but shouldn't halt your push.

**Comment by mgracer48** [comment]
I have 2.1.0 and get this
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/itstypicaldevm8/ToontownTheNextLevel'

**Comment by miroslavkovac** [comment]
I still have the warning with 2.2.0 but the push succeeds. The problem is when I use GIU apps like SourceTree and Tower, the push fails there, so after installing Git LFS, I can only push from command line. This is the error from SourceTree:

```
Pushing to ssh://git@repo-url.git
Authentication required: Authorization error: https://repo-url.git/info/lfs/locks/verify
Check that you have proper access to the repository
error: failed to push some refs to 'ssh://git@repo-url.git'
Completed with errors, see above
```

**Comment by gskbyte** [comment]
I have exactly the same problem as @miroslavkovac both when using SourceTree and when executing `git push` in the console. I installed git-lfs using Homebrew on Mac OS X. Passing `--verbose` doesn't provide any extra information.

```
$ git lfs version
git-lfs/2.2.1 (GitHub; darwin amd64; go 1.8.3)
```

**Comment by miroslavkovac** [comment]
Git LFS needs an authentication via HTTPS available, so I was able to solve my issues by switching from SSH to HTTPS for the git remote.

**Comment by zzswang** [comment]
problem +1

```
git-lfs/2.2.1 (GitHub; darwin amd64; go 1.8.3)
git version 2.14.1
```

**Comment by technoweenie** [comment]
> Git LFS needs an authentication via HTTPS available, so I was able to solve my issues by switching from SSH to HTTPS for the git remote.

If your Git host implements the [`git-lfs-authenticate` ssh command](https://github.com/git-lfs/git-lfs/blob/5703b808220103063ededf5c6149c93201be9e07/docs/api/authentication.md#ssh) properly, it should still work with HTTPS api endpoints:

```
$ GIT_TRACE=1 git lfs locks
11:32:45.339580 git.c:560               trace: exec: 'git-lfs' 'locks'
11:32:45.340084 run-command.c:626       trace: run_command: 'git-lfs' 'locks'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: ssh -- git@github.com git-lfs-authenticate github/git-lfs-test upload
trace git-lfs: HTTP: GET https://lfs.github.com/github/git-lfs-test/locks
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"locks":[{"id":"951","path":"LICENSE.md","owner":{"name":"ttaylorr"},"locked_at":"2017-03-21T18:55:55Z"}],"next_cursor":""}
```

If you're still having issues with this, contact your Git host. We have no control how they, or GUI apps like SourceTree function. 

You can also disable locks verification if your Git/LFS host does not support the file locking API. The output from a `git push` should give you the exact `git config` command to run.
