### ISSUE TITLE
Mismatch of LFS version causing trouble (?)

### ISSUE THREAD

**Issue by FredyC** [git-lfs/git-lfs#2204]
I don't want to fill #2202 with irrelevant information. The whole deal is that my coworker is rather inexperienced with Git, not even mentioning LFS (not that I know much about LFS). I went on vacation and he was working alone, pushing stuff.

When I came back I found out that I cannot pull changes. There is a bunch of errors like this for files he changed.

> LFS: Repository or object not found: https://gitlab.com/group/project.git/gitlab-lfs/objects/2dbb7e94eec56de3ec380469bfb7e6bb335cf78dee658dd22fab842c380e07ef
> Check that it exists and that you have proper access to it

So I asked what he did, but he isn't really sure that he did something special except at some point he updated lfs to 2.x. Apparently, those files were not ever pushed to LFS from his side and it's not possible now.

There is also some strange issue regarding locking...

> git lfs push origin master --all
> Remote "origin" does not support the LFS locking API. Consider disabling it with:
>  $ git config 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify' false
> Git LFS: (0 of 193 files, 1817 skipped) 0 B / 139.44 MB, 909.54 MB skipped 

> git config 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify' false
> error: invalid key: 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify'

He has sent me copy of his repo (.git folder including), but I cannot seem to find a way to fix it even on my older `git-lfs/1.5.2 (GitHub; windows amd64; go 1.7.3; git 547a06aa)`. Everything is skipped during push.

Also running `git lfs status` actually shows these missing files in `Git LFS objects to be pushed to origin/master:` and yet running push skips them all.

**Comment by technoweenie** [comment]
I don't think the LFS version mismatch is causing any issues here. Or if so, the issues are likely better described by #2202 or #2201. We'll look into those first, and revisit this if necessary later.

**Comment by technoweenie** [comment]
> There is also some strange issue regarding locking...

```
git lfs push origin master --all
Remote "origin" does not support the LFS locking API. Consider disabling it with:
$ git config 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify' false
Git LFS: (0 of 193 files, 1817 skipped) 0 B / 139.44 MB, 909.54 MB skipped
git config 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify' false
error: invalid key: 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify'
```

That just means that gitlab does not support the LFS file locking API, so LFS is unable to verify that you're not updating a file someone else has locked. Nothing to worry about until gitlab supports the API. The output does give you a git config command to run to hide those warnings, if you wish.

**Comment by FredyC** [comment]
@technoweenie Well if you have noticed, we have tried that git config command and it failed. That's why I call it strange :)

**Comment by FredyC** [comment]
Anyway, I've actually updated to latest lfs (`git-lfs/2.1.0 (GitHub; windows amd64; go 1.8.1; git bd2c9987)`) and suddenly I can fetch/pull the commits coworker has pushed. So I would say there is definitely some version incompatibility happening.

**Comment by technoweenie** [comment]
> Well if you have noticed, we have tried that git config command and it failed. That's why I call it strange :)

Ah, I didn't notice that part. Weird. What version of Git are you on? It works great for me:

```
$ git config 'lfs.https://gitlab.com/group/project.git/info/lfs.locksverify' false
$ git config --list
lfs.https://gitlab.com/group/project.git/info/lfs.locksverify=false
```

I wonder if the single quotes around the key are giving you some difficulties?

`git config lfs.https://gitlab.com/group/project.git/info/lfs.locksverify false`

**Comment by FredyC** [comment]
Confirmed, quotes do not work with that. So perhaps it shouldn't be said in that message to use them. Do you want me to create another issue for it?

And what about that incompatibility of versions, is it possible that pushing in 2.2 has something different that 1.5.2 cannot understand?

**Comment by technoweenie** [comment]
You're working with Git 2.2 and 1.5.2? The main difference, as far as LFS is concerned, is that the `pre-push` hook wasn't supported until Git 1.8.x. So, LFS objects won't be pushed automatically on Git v1.5.2.

If you're talking about LFS 2.2 and 1.5.2, then it's completely irrelevant to how `git config` works. The LFS API added file locking in 2.0+, which accounts for those locking API warning messages you're getting. But that should not be affecting the actual upload of LFS objects.

**Comment by FredyC** [comment]
No no. A coworker has updated to 2.2 and then I tried to fetch on 1.5.2 and it was behaving like those objects are not there at all (see the first post). So it's not the case of `pre-push` hook as there was no pushing on 1.5.2 happening, only fetching/pulling. Only when I updated to 2.2 as well, I could fetch those objects.

> If you're talking about LFS 2.2 and 1.5.2, then it's completely irrelevant to how git config works. The LFS API added file locking in 2.0+, which accounts for those locking API warning messages you're getting. But that should not be affecting the actual upload of LFS objects.

My only concern about locking is now that message the lfs is giving contains quotes. Apparently, that doesn't work on windows (and who knows where else). So I was just suggesting to make a new issue so the quotes are removed from there to avoid confusion.

**Comment by technoweenie** [comment]
> Only when I updated to 2.2 as well, I could fetch those objects.

Strange. Nothing changed in the protocols themselves. The code was refactored though. Assuming the server responses are all correct regardless of the local Git LFS version, my only hunch is something related to authentication. 

I opened an issue to remove the quotes in https://github.com/git-lfs/git-lfs/pull/2206.

Thanks for your feedback!

**Comment by FredyC** [comment]
@technoweenie Looks like that problem is more serious. I and coworker are both using 2.2 now. I've created a fresh new repo and pushed there our content to mitigate the previous issue. It works for me just fine, I can clone it, pull, push. However, a coworker tried to clone and has run into the same issue as me previously...

```
Downloading Content/Environment/Walls/Meshes/Slide-01.uasset (92.96 KB)
Downloading Content/Environment/Walls/Meshes/SlideLarge-02.uasset (95.54 KB)
Downloading Content/Environment/Walls/Meshes/Wall300-01.uasset (126.39 KB)
Downloading Content/Environment/Walls/Meshes/Wall300-01_DM.uasset (2.21 MB)
Error downloading object: Content/Environment/Walls/Meshes/Wall300-01_DM.uasset (d458658): Smudge error: Error downloading Content/Environment/Walls/Meshes/Wall300-01_DM.uasset (d4586586908001b3ac44f8589e0a779691cc7b8effb99990570192f531c119f3): LFS: Repository or object not found: https://gitlab.com/group/project.git/gitlab-lfs/objects/d4586586908001b3ac44f8589e0a779691cc7b8effb99990570192f531c119f3
Check that it exists and that you have proper access to it

Errors logged to D:\Unreal\turo\.git\lfs\objects\logs\20170511T031026.0565819.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/Environment/Walls/Meshes/Wall300-01_DM.uasset: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by technoweenie** [comment]
> Check that it exists and that you have proper access to it

That message makes it look like a server issue. What's in the log file `D:\Unreal\turo\.git\lfs\objects\logs\20170511T031026.0565819.log`?

Also, as pointed out in https://github.com/git-lfs/git-lfs/issues/2202#issuecomment-300069874, there may be some NFS issues on gitlab.

**Comment by FredyC** [comment]
Nothing useful in the log file it seems. Not sure what might be wrong and why it's happening after updating LFS client. I am sure that it is actually pushed to the repo since I can clone it just fine. But for some reason, my coworker cannot access it. Wish there were some way to actually look at the content of LFS storage along with access rights.

```
git-lfs/2.1.0 (GitHub; windows amd64; go 1.8.1; git bd2c9987)
git version 2.11.0.windows.1

$ git-lfs.exe filter-process
Error downloading object: Content/Environment/Walls/Meshes/Wall300-01_DM.uasset (d458658): Smudge error: Error downloading Content/Environment/Walls/Meshes/Wall300-01_DM.uasset (d4586586908001b3ac44f8589e0a779691cc7b8effb99990570192f531c119f3): LFS: Repository or object not found: https://gitlab.com/tauros/turo.git/gitlab-lfs/objects/d4586586908001b3ac44f8589e0a779691cc7b8effb99990570192f531c119f3
Check that it exists and that you have proper access to it

%+v
Smudge error: Error downloading Content/Environment/Walls/Meshes/Wall300-01_DM.uasset (d4586586908001b3ac44f8589e0a779691cc7b8effb99990570192f531c119f3): LFS: Repository or object not found: https://gitlab.com/tauros/turo.git/gitlab-lfs/objects/d4586586908001b3ac44f8589e0a779691cc7b8effb99990570192f531c119f3
Check that it exists and that you have proper access to it
ENV:
LocalWorkingDir=D:\Unreal\turo
LocalGitDir=D:\Unreal\turo\.git
LocalGitStorageDir=D:\Unreal\turo\.git
LocalMediaDir=D:\Unreal\turo\.git\lfs\objects
LocalReferenceDir=
TempDir=D:\Unreal\turo\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_LFS_PATH=C:\Program Files\Git LFS
```
