### ISSUE TITLE
"git lfs help" should write to standard output, not standard error

### ISSUE THREAD

**Issue by lyosha** [git-lfs/git-lfs#2207]
...to be consistent with git.

In addition to consistency, it is annoying to do "git lfs help", see the output scroll by, do "git lfs help | less", see the empty screen and have to do it again with 2>&1.

**Comment by carlwright4** [comment]
(#2207)

**Comment by ttaylorr** [comment]
Hi @lyosha, thanks for opening this. I think this sounds reasonable, as LFS should strive to be as consistent with the behavior of Git as possible. I opened up https://github.com/git-lfs/git-lfs/pull/2210 to address.

**Comment by lyosha** [comment]
Much appreciated!  This was bothering me for the longest time.
