### ISSUE TITLE
git push login loop

### ISSUE THREAD

**Issue by YungQuant** [git-lfs/git-lfs#2209]
I know this is an existing issue. How can I fix this as easily as possible?

**Comment by ttaylorr** [comment]
@YungQuant can you try enabling the LFS in-memory credential cache? To do so:

```shell
$ git config lfs.cachecredentials 1
```

**Comment by YungQuant** [comment]
Command returned nothing, I had tried that before also because I was looking for bug fixes before I opened this issue.

**Comment by guillaume-chevalier** [comment]
Duplicate with: 
https://github.com/git-lfs/git-lfs/issues/2014

**Comment by guillaume-chevalier** [comment]
Doing `git config lfs.cachecredentials 1` did nothing.

**Comment by ttaylorr** [comment]
Moving discussion to #2014.
