### ISSUE TITLE
Support core.sshCommand in gitconfig

### ISSUE THREAD

**Issue by samskiter** [git-lfs/git-lfs#2215]
I have issues with SSH on my corp machine + sourcetree's environment config.

By configuring the git config and setting the sshCommand I can fix this, unfortunately this setting doesn't isn't read by git-lfs

Currently having to do an ugly wrap around git-lfs to get this working

**Comment by Feni13** [comment]
to nie jest komputer korporacji tylko prywatny sprzęt jakie kolwiek dane 
kierowane na ten serwer będą kasowane

pozdrawiam feni13


W dniu 12.05.2017 o 12:48, Sam Duke pisze:
>
> I have issues with SSH on my corp machine + sourcetree's environment 
> config.
>
> By configuring the git config and setting the sshCommand I can fix 
> this, unfortunately this setting doesn't isn't read by git-lfs
>
> Currently having to do an ugly wrap around git-lfs to get this working
>


---
Ta wiadomość została sprawdzona na obecność wirusów przez oprogramowanie antywirusowe Avast.
https://www.avast.com/antivirus

**Comment by ttaylorr** [comment]
@samskiter thanks for opening this. You can use the `GIT_SSH_COMMAND` and `GIT_SSH` environment variables when invoking the `git lfs` command.

Reading the [gitconfig documentation](https://git-scm.com/docs/git-config), I can see that LFS [should also be responding to `core.sshCommand`](https://git-scm.com/docs/git-config#git-config-coresshCommand), so I'll make sure that we add that in the next release.

**Comment by samskiter** [comment]
Thanks so much!

From about 5 Devs in my workplace alone!

**Comment by samskiter** [comment]
@ttaylorr I'm using sourcetree and I don't seem to be able to get git-lfs to use the ssh command, even by using GIT_SSH_COMMAND.

From command line my setup works fine but in sourcetree it seems to default to another SSH. I've even tried configuring the git-lfs binary in sourcetree to point to this script script:

```bash
#!/bin/sh
export GIT_SSH_COMMAND="/usr/local/bin/ssh"
exec env GIT_SSH_COMMAND="/usr/local/bin/ssh" /usr/local/bin/git-lfs ${1+"$@"}
```

But it's still using the wrong one and generating a bunch of errors. Any ideas?

**Comment by ttaylorr** [comment]
@samskiter LFS has a known issue where `GIT_SSH_COMMAND` is not evaluated in a shell and instead used verbatim. I think that's what is going on.

**Comment by ttaylorr** [comment]
> I thought that was only if you had spaces or quotes in your `GIT_SSH_COMMAND` definition?

This was fixed in https://github.com/git-lfs/git-lfs/pull/1962.

> Mine is literally as above.

```sh
exec env GIT_SSH_COMMAND="/usr/local/bin/ssh" /usr/local/bin/git-lfs ${1+"$@"}
```

LFS will not execute this, it will think that your SSH executable is literally `/usr/local/bin/ssh`.

**Comment by samskiter** [comment]
Ahhh ok, thanks for clearing that up. So there is no way of using
GIT_SSH_COMMAND currently either?

**Comment by samskiter** [comment]
This is driving me bananas. How can I help?

**Comment by ttaylorr** [comment]
@samskiter one thing you could do is:

`export GIT_SSH_COMMAND="$(eval "$GIT_SSH")"`

The code that is responsible for handling this resides in [`lfsapi/ssh.go`](https://github.com/git-lfs/git-lfs/blob/v2.1.1/lfsapi/ssh.go#L116-L179). I don't have this on my immediate roadmap, but I'd be more than happy to help you through a contribution to add support for handling `$GIT_SSH_COMMAND` correctly.

**Comment by samskiter** [comment]
@ttaylorr hmm I should try that. I did just find another workaround today, but I would like to contribute still

I will try and find some time to read through that next week

**Comment by Ridha-ELB** [comment]
Hi guys !

Do you have any update on this issue ? Or could you please share the workaround to set lfs the ssh command ?
Thanks in advance.

**Comment by Ridha-ELB** [comment]
@samskiter are you still around ? sorry for spamming :/ but I'm kind of hardly stuck on this.

**Comment by exajuk** [comment]
I don't know what workaround @samskiter uses, but I wrote myself a wrapper script that calls git with my custom ssh command and added it to the repository. It is very simple:

```
#!/bin/sh

GIT_SSH_COMMAND="<YOUR SSH COMMAND HERE>" git "$@"
```

Now instead of executing `git lfs bla` I execute `./git lfs bla` (from the repository root). Ugly, but it works.

**Comment by Ridha-ELB** [comment]
@exajuk thanks for your help ! I will give it a try but seems fine for me.
