### ISSUE TITLE
invalid memory address or nil pointer dereference when pull large objects with poor network connection

### ISSUE THREAD

**Issue by wenyang** [git-lfs/git-lfs#2222]
I have a repo hosted in github with lfs and I tried to pull it from China(with poor connection to US). 
I always failed to pull the repo with errors like the following:

```
Downloading opt/cudnn/cuda/lib64/libcudnn.so.5.1.10 (80.26 MB)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6fe4c5]

goroutine 260 [running]:
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc42000e078, 0xc420626240, 0xc42013cc00, 0xc4201bf1a0, 0xc42000e090, 0x404688, 0xc9a860, 0xc420620200, 0x0, 0x0)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/tq/basic_download.go:116 +0x405
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc42000e078, 0x0, 0x0, 0xc420626240, 0xc42013cc00, 0xc4201bf1a0, 0x0, 0xc)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/tq/basic_download.go:49 +0xbc
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc420620000, 0x0, 0x0, 0x0)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:171 +0x5f2
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:84 +0x331
error: external filter 'git-lfs filter-process' failed
fatal: opt/cudnn/cuda/lib64/libcudnn.so.5.1.10: smudge filter lfs failed


$ git lfs env
git-lfs/2.1.0 (GitHub; linux amd64; go 1.8.1)
git version 2.11.0

Endpoint=https://github.com/blabla/myrepo.git/info/lfs (auth=none)
  SSH=git@github.com:blabla/myrepo.git
LocalWorkingDir=xxx
LocalGitDir=xxx
LocalGitStorageDir=xxx
LocalMediaDir=xxx
LocalReferenceDir=
TempDir=xxx
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

How do I mitigate/workaround this?

Wen.

**Comment by ttaylorr** [comment]
@wenyang thanks for opening this, and sorry that you're having trouble. What you're running into is a code path that occurs when a download fails while in progress, and the transfer adapter attempts to retry.

More specifically, it makes a request to the server to retry the download at the offset. What looks like is happening here is that there was an error connecting to the object server, which is the upstream cause of the nil-pointer dereference.

I'll milestone this for the next minor release, but in the meantime, you could take a look at the following settings:

- `lfs.basictransfersonly` -> `1` to limit your client to only try with the basic adapter
- `lfs.transfer.maxretries` -> `32` to increase the number of retries that your client will attempt to make.

as well as:

- `lfs.dialtimeout` increase this value (default: `30`) to allow the client a longer amount of time to dial a TLS connection
- `lfs.tlshandshake` increase this value (default: `30`) to allow the client a longer amount of time to wait for the TLS handshake
- `lfs.activitytimeout` increase this value (default: `10`) to allow the client a longer amount of time between data being sent over the connection.

**Comment by wenyang** [comment]
@ttaylorr  thanks for help. I'm skipping the large objects with GIT_LFS_SKIP_SMUDGE=1 to work around this error. Looking forward to your fix.

Wen.
