### ISSUE TITLE
Git LFS clone doesn't prompt  credential input for git lfs   and  fail to download LFS with "credential ... not found "

### ISSUE THREAD

**Issue by xming07** [git-lfs/git-lfs#2223]
Our team are  working on a project using Github enterprise and LFS server, and have issue to run "git lfs" command to download lfs tracked files  via https in the windows.
Platform: Windows7/10
Git: 2.12.2
Git LFS: 2.0.2
We use the [git-for-windows](https://git-for-windows.github.io/)  and use wincred as credential.helper.

When we use the "git lfs clone" to clone the repository,  it can clone code successfully. But fail to download LFS tracked files. 

```
LFS: (0 of 3457 files) 0 B / 10.77 GB
batch response: Git credentials for https://........../artifactory/api/lfs/unity-git-lfs not found.
```

Also I can not run  the git credentail fill   command.

```
$ git credential fill
host=github.com
protocol=https
Username for 'https://github.com': error: failed to execute prompt script (exit code 1)`
fatal: could not read Username for 'https://github.com': No error
```

The solution I find would be to set variable  in the git bash. Then it will prompt for username .

```
export DISPLAY=required
export SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
export GIT_ASKPASS=$SSH_ASKPASS
```

It works fine if I use [credential manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows),
Is it an issue for the git-for-windows or wincred? 
Thank you,
Louis

**Comment by ttaylorr** [comment]
> Is it an issue for the git-for-windows or wincred?

I think so, but this isn't my area of expertise. @dscho do you have any thoughts?

**Comment by larsxschneider** [comment]
@xming07 I think there is garbage in your credential helper cache. Try to clean it like this:
```
printf "protocol=https\nhost=github.com\n\n" | git credential-wincred erase
printf "protocol=https\nhost=<YOUR GITHUB ENTERPRISE DOMAIN>\n\n" | git credential-wincred erase
```

**Comment by ttaylorr** [comment]
Hi @xming07, I think that @larsxschneider suggestion is a good one. I'm going to close this issue out since it has grown stale, but if you haven't yet and are unable to resolve the issue after applying @larsxschneider's suggestion, please do not hesitate to contact me here and I'd be happy to re-open it.
