### ISSUE TITLE
git lfs clone for new options in git 2.9

### ISSUE THREAD

**Issue by linquize** [git-lfs/git-lfs#2250]
There are new `clone` options in git 2.9, which is not yet supported in `git lfs clone`
```
--reference-if-able
--shallow-since
--shallow-exclude
--shallow-submodules
--no-shallow-submodules
-j --jobs
```

**Comment by ttaylorr** [comment]
👋 again, @linquize -- thanks for opening this. I went ahead and opened https://github.com/git-lfs/git-lfs/issues/2252 to address this, and milestoned it into the v2.2.0 release, so you should be able to use it once that series is released.

In the meantime, here are some builds that include that range of commits:

[git-lfs-darwin-386-2.2.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1019389/git-lfs-darwin-386-2.2.0-pre.tar.gz)
[git-lfs-darwin-amd64-2.2.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1019390/git-lfs-darwin-amd64-2.2.0-pre.tar.gz)
[git-lfs-freebsd-386-2.2.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1019387/git-lfs-freebsd-386-2.2.0-pre.tar.gz)
[git-lfs-freebsd-amd64-2.2.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1019388/git-lfs-freebsd-amd64-2.2.0-pre.tar.gz)
[git-lfs-linux-386-2.2.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1019391/git-lfs-linux-386-2.2.0-pre.tar.gz)
[git-lfs-linux-amd64-2.2.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1019386/git-lfs-linux-amd64-2.2.0-pre.tar.gz)
[git-lfs-windows-386-2.2.0-pre.zip](https://github.com/git-lfs/git-lfs/files/1019392/git-lfs-windows-386-2.2.0-pre.zip)
[git-lfs-windows-amd64-2.2.0-pre.zip](https://github.com/git-lfs/git-lfs/files/1019393/git-lfs-windows-amd64-2.2.0-pre.zip)
