### ISSUE TITLE
git lfs should return with non-zero exit code when subcommand / option is invalid

### ISSUE THREAD

**Issue by linquize** [git-lfs/git-lfs#2253]
git lfs should return with non-zero exit code when subcommand / option is invalid

for example 1,
`git lfs dd` is an invalid subcommand,
but `echo $?` prints `0`

for example 1,
`git lfs dd` is an invalid subcommand,
but `echo $?` prints `0`

for example 2,
`git lfs fetch -g` has invalid option
again but `echo $?` prints `0`

**Comment by ttaylorr** [comment]
@linquize thanks for opening this. I agree that LFS should fail on unknown subcommands, or unknown flags on know subcommands.

Given that this is a breaking change fixing existing broken behavior, I think milestone-ing it for v2.2.0 is appropriate.
