### ISSUE TITLE
When a repository has a git submodule using LFS, submodule should be cloned with git lfs clone

### ISSUE THREAD

**Issue by mitar** [git-lfs/git-lfs#2254]
I have a normal (non LFS) repository which has a git submodule to a git repository which is a LFS repository. If I do `git clone top-repository` then the initial git submodule cloning is very slow. I think it should be done in parallel using `git lfs clone` or something like that.

**Comment by technoweenie** [comment]
We have no control over how `git clone` works. Try `git lfs clone --recurse-submodules top-repository`, which will efficiently clone the repository and it's submodules, and then download the LFS objects with `git lfs pull`.

**Comment by mloskot** [comment]
@technoweenie 
>  Try `git lfs clone --recurse-submodules`

Is this recommendation still valid after the `git lfs clone` has been deprecated?
Or, is this one of those cases where `git lfs clone` remains superior to `git clone`?

**Comment by mitar** [comment]
So why is then `git lfs clone` deprecated, if it has clearly useful extensions (like `--recurse-submodules` and `-I` and `-E`)?

**Comment by rdd7** [comment]
> So why is then `git lfs clone` deprecated, if it has clearly useful extensions (like `--recurse-submodules` and `-I` and `-E`)?

So should I still use `git lfs clone --recurse-submodules top-repository` now?

**Comment by mloskot** [comment]
Simply, `git clone --recurse-submodules` do the job.
