### ISSUE TITLE
'Pointer file error: Unable to parse pointer' errors appearing on some files

### ISSUE THREAD

**Issue by BrodyB** [git-lfs/git-lfs#2260]
Hi folks,

I've been working with Git LFS on this repo since the beginning, and recently upgraded from LFS 1.4.x to LFS 2.1.0 through Homebrew. I believe this error showed up before I upgraded. I notice when I pull latest on a branch, a few files immediately show as modified, turning from a full file to a pointer.

When I try to reset these files, I get the following error on them: `Pointer file error: Unable to parse pointer at: "Assets/Art/TestArt/model_file.fbx"`. And this shows up for a few files also added and committed using the latest version of Git LFS.

Using `git lfs env` gives me this:
```
git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
git version 2.11.0 (Apple Git-81)

Endpoint=https://BrodyB@gitlab.com/BrodyB/WordsWillDie.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/DiscoveryOne/Documents/Projects/Unity/WordsWillDie
LocalGitDir=/Users/DiscoveryOne/Documents/Projects/Unity/WordsWillDie/.git
LocalGitStorageDir=/Users/DiscoveryOne/Documents/Projects/Unity/WordsWillDie/.git
LocalMediaDir=/Users/DiscoveryOne/Documents/Projects/Unity/WordsWillDie/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/DiscoveryOne/Documents/Projects/Unity/WordsWillDie/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I'm not sure how to address this and searches don't seem to be bringing up my same situation. Any ideas what may be causing this or how to resolve it?

Thanks!

**Comment by ttaylorr** [comment]
Hi @BrodyB, thanks for opening this issue, and sorry that you're having trouble! I think what's going on here is that your repository has been touched by someone who doesn't have LFS installed, so they have committed a large file into Git history directly, not through LFS.

LFS will, upon checkout, try and parse that large object as a pointer, and complain that it can't parse it. Can you run `git add --all . && git lfs status` and paste the output here to confirm?

**Comment by BrodyB** [comment]
Sorry for getting back so late.

This was totally it. I was using GitKraken on one machine (which I later realized currently has no support for LFS) and thus created the issue. Committing the pointer in command line / SourceTree fixed the issue.

**Comment by Salma175** [comment]
@BrodyB  What does this statement exctly means ?
"Committing the pointer in command line / SourceTree fixed the issue." Could you please elaborate

**Comment by BrodyB** [comment]
When I committed some files into my repository that are normally handled by LFS using a git client that does not support LFS (in this case, it was GitKraken), and then, on another computer, pulled latest using a client that DOES support LFS (SourceTree), I saw a number of files show up on my change list relating to those files.

By committing those new files, it fixed the problem, and things went back to being handled properly by LFS.
