### ISSUE TITLE
Releases to extend git server with lfs capabilities

### ISSUE THREAD

**Issue by benelot** [git-lfs/git-lfs#2276]
Hello!

Are there any releases of the lfs capability for a git server? Can I somehow make my own git server handle lfs tasks? Or is there just a proprietary lfs server implementation? I only found this tutorial, but it sounds a bit hacky, since the server says it is not production ready:

http://cubeslam.net/2016/03/18/setting-up-a-simple-custom-git-lfs-server-on-ubuntu/

**Comment by ttaylorr** [comment]
Hi @benelot! Thanks for opening this, let me see if I can provide some useful information:

The LFS server currently runs as a separate process outside of your `git-daemon(1)`. To add LFS support to your own Git server, you'll need to run one of the LFS-compliant servers listed in the [implementations page](https://github.com/git-lfs/git-lfs/wiki/Implementations) of our Wiki.

Let me know if this is roughly what you're looking for, and please don't hesitate to re-open this issue if you have any questions!

**Comment by stefanocrosta** [comment]
Hello @ttaylorr ,

When running `git daemon` to provide a local git server mirror of a cloud one (bitbucket), a git clone will try to download LFS files from the same port:

CLIENT SIDE:
```

git clone git://localhost:2222/test-with-lfs
Cloning into 'test-with-lfs'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 0 (delta 0)
Receiving objects: 100% (9/9), done.
Resolving deltas: 100% (1/1), done.
Downloading google-chrome-stable_55.0.2883.87-1_amd64.deb (44.10 MB)
Error downloading object: google-chrome-stable_55.0.2883.87-1_amd64.deb (15e4445): Smudge error: Error downloading google-chrome-stable_55.0.2883.87-1_amd64.deb (15e44458e0ff667fa0f97f6970df200daf41a671477f8a08cd18b5dbb64b77b3): batch response: Post https://localhost:2222/test-with-lfs.git/info/lfs/objects/batch: EOF

Errors logged to /Users/stefano/tmp/test-with-lfs/.git/lfs/objects/logs/20170613T124947.336308657.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: google-chrome-stable_55.0.2883.87-1_amd64.deb: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

and on the GIT SERVER (DAEMON):

```
fatal: protocol error: bad line length character: ???
```

So clearly in this case running an LFS server separate is complicated, because it should be... on the same port.

Any idea on how to solve this issue?
```

**Comment by stefanocrosta** [comment]
(does not look like i can re-open this issue. If you think it worthwhile I can always create a new one...)

**Comment by ttaylorr** [comment]
> So clearly in this case running an LFS server separate is complicated, because it should be... on the same port.
> 
> Any idea on how to solve this issue?

The LFS test server (https://github.com/git-lfs/lfs-test-server) does not offer this support built in, but I think that you could take one of two approaches:

1. Write (or use) a network proxy that can route based on packet contents.
2. Configure `git config lfs.url`<sup>[[1](https://github.com/git-lfs/git-lfs/blob/v2.1.1/docs/man/git-lfs-config.5.ronn#L22-L30)]</sup> to direct LFS traffic to a different port (the one that your LFS server is running on).

**Comment by stefanocrosta** [comment]
Thanks @ttaylorr,

clearly it would be better to have an all in one solution, but the `git config lfs.rl` can do the trick - did not know the option! 

Note for any other reader: it's a bit cumbersome if you are cloning, because the git clone will fail and instead of having to pull again you actually need to reset.
So you need to do something like:

```
> git clone yourlocalgitserver/repo
> cd repo
> git config lfs.url yourlocallsfserver
> git reset --hard HEAD
```

**Comment by ttaylorr** [comment]
Glad that everything is working!

As a note, you can also specify the `lfs.url` config as an argument to `git clone` via `-c`:

```sh
git -c 'lfs.url=yourlocallfsserver' clone yourlocalgitserver/repo
```
