### ISSUE TITLE
raw file via direct download not in sync with latest version

### ISSUE THREAD

**Issue by erikor** [git-lfs/git-lfs#2282]
I have some files I am tracking with lfs with, for example:

```
git lfs track myfile.rds
git add .
git commit -am "tracking myfile.rds with lfs"
git push
```
I then modify the file and do:

```
git commit -am "modified myfile.rds"
git push
```
Push suceeds.  If I reclone the repository, my updated file is pulled as expected.  However, if I download `myfile.rds` directly via `https://github.com/erikor/myrepo/raw/master/myfile.rds` I get the old file, not the updated one.

On the other hand, if I download via the tree reference (e.g. `https://github.com/erikor/myrepo/raw/8ee33036b7c7e70c362316375970c1c30b2116ca/myfile.rds`) I get the updated file.

How can I get the latest file via the `..../master/myfile.rds` link?  Or does it just take some time for the links to get update?  Or is this not Expected Behavior™?

**Comment by technoweenie** [comment]
Thanks for the report. I'll have to review our cdn settings for raw lfs objects.

Closing this since it's not a Git LFS client issue. If you want to talk further about this, reach us at [GitHub Support](https://github.com/contact).
