### ISSUE TITLE
Breaking change between 2.0.2 <=> 2.1.0 with `git lfs status --porcelain`

### ISSUE THREAD

**Issue by asottile** [git-lfs/git-lfs#2289]
Here's a small setup test bed repository:

```
rm -rf repo
git init repo
cd repo
git lfs install
git lfs track a.bin b.bin
echo hi > a.bin
git add -- .
git commit -am foo
git mv a.bin b.bin
```

Under 2.0.2:

```console
$ git-lfs-2.0.2 status --porcelain
R  a.bin -> b.bin 3
```

Under 2.1.0:

```console
$ git-lfs-2.1.0 status --porcelain
R  a.bin -> b.bin
```

I'm not sure if this is intentional, it's certainly a breaking change though :) (and in a `--porcelain` output!)

This is breaking our tests in pre-commit/pre-commit-hooks: https://github.com/pre-commit/pre-commit-hooks/issues/195

I can try and bisect this if you'd like

**Comment by asottile** [comment]
@ttaylorr This appears to be the culprit: #2042

**Comment by asottile** [comment]
Now that I look at it, the change also breaks `--porcelain` output for not moves too (I just happened to notice / debug my test which exercises moves)

**Comment by technoweenie** [comment]
Would it help if the status command had some low level format that your tests could depend on? Either `--json` (which you can check with `jq`), or even just `--format`, which is common with Git.

**Comment by asottile** [comment]
At least in traditional git, that's what porcelain is supposed to be. json would be great though!

**Comment by asottile** [comment]
(I also don't really care about the size field (I discard it), but I'm unable to consistently parse the two formats)

**Comment by ttaylorr** [comment]
@asottile thanks for pointing this out. There was a breaking change to the `--porcelain` and normal output in https://github.com/git-lfs/git-lfs/pull/2042, and again in https://github.com/git-lfs/git-lfs/pull/2070.

If I remember correctly, we shipped these in 2.1.0 across a `MINOR` version boundary, but the change technically should have warranted a 3.0 release. I can add the information back to `--porcelain` and release those changes in 2.1.2 or 2.2.0, but I think it's possible in shell to parse either version correctly with `cut`.

**Comment by asottile** [comment]
It would be, if files could not contain the space character :)

**Comment by asottile** [comment]
I'm going to take a stab at implementing `--json`

**Comment by ttaylorr** [comment]
> I'm going to take a stab at implementing `--json`

Wonderful! I'm looking forward to taking a look. Please don't hesitate to ping me if you have any questions about how best to implement this.

**Comment by asottile** [comment]
@ttaylorr now looking further into this -- `git lfs status` is now including *non lfs files* (also probably new in 2.1.0).  I guess I'll make another PR to remove those from `--json`

**Comment by asottile** [comment]
This is useful documentation, but I guess no longer actionable? (closing)
