### ISSUE TITLE
GitLFS does not respect Git URL rewrites

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#2298]
`git lfs` seems not to respect Git URL rewrites via Git `insteadof` config.

### Environment
Git LFS 2.1.1 on Windows (Git 2.11.3) and OSX (2.13.0)

### Steps to reproduce

1. Add URL rewrites to your global `.gitconfig`. E.g.:
```
[url "https://github.com/"]
    insteadOf = ssh://git@github.com:
    insteadOf = ssh://git@github.com:/
    insteadOf = git@github.com:
    insteadOf = git@github.com:/
```
2. Remove your SSH key on GitHub if you have one

3. Clone any LFS repo via SSH:
```
GIT_SSH_COMMAND="ssh -vvv" GIT_CURL_VERBOSE=1 git lfs clone git@github.com:any-org/any-repo.git
```

The Git clone operation is performed via HTTPS but Git LFS tries to use SSH for the rest of the work (noticeable by the `debug` SSH statements).

**Comment by technoweenie** [comment]
Looks like support was added in #1443. I wonder if LFS is doing the replacement at the wrong spot, so it's not affecting ssh urls?

**Comment by tardyp** [comment]
Looks like indeed, there is a problem with parsing the gitconfig
```
[url "http://mirror/"]
    insteadOf = https://cloudserver/
    insteadOf = git@cloudserver:
```
does not work

```
[url "http://mirror/"]
    insteadOf = git@cloudserver:
    insteadOf = https://cloudserver/
```
works..


git remote -v produce correct results in both case
git lfs env does not.

**Comment by duaneellissd** [comment]
Confirm - Painful for me :-(  I wish this was fixed.
Cannot recrusively clone git lfs enabled repos
Top level is not git - lfs, but sub-levels are
And insteadof is set in my global config
mapping https//bitbucket.org ->  SSH access.

**Comment by reefbarman** [comment]
I believe I am seeing similar issues to @tardyp and @duaneellissd. Was there a fix for this or a workaround?

**Comment by bk2204** [comment]
I think currently we don't support multiple `insteadOf` aliases. We probably should, though.
