### ISSUE TITLE
Git LFS github limit reached very little feedback to debug

### ISSUE THREAD

**Issue by pvchaumier** [git-lfs/git-lfs#2304]
Hello,

I have added some files that are bigger than the size limit set by github. I tried removing them using `git lfs untrack`, `git rm --cached` and `git filter-branch`. However when I try pushing, I still have this size limit error.

When trying to push I only have the size of the file that is problematic but no more. I inspected the repo and no file has the given size.

One solution would be to revert all changes until reaching the problematic commit but is there a way to have more information such as the file name/path ?

**Comment by ttaylorr** [comment]
Hi @pvchaumier, thanks for opening this issue, and sorry that you're having trouble! Could you help clarify for me what you're trying to do? Running `git lfs untrack`, `git rm --cached` and `git filter-branch` is a combination of commands that would remove a large file from your history entirely (both LFS and Git).

Is this what you're trying to do? As long as your file is tracked in LFS and not stored in Git in all commits in your push, the push should work.

**Comment by pvchaumier** [comment]
Yes that is exactly what I was trying to do. I decided to remove the file to split it in bits staying within the github limit.

**Comment by ttaylorr** [comment]
> I forgot to remove a file but as I have no feedback from the error message I cannot say which one.

I agree that this is a more likely scenario. I have a script in my dotfiles that can show the largest blobs in a repository and which commits they are from: https://github.com/ttaylorr/dotfiles/blob/work-gh/bin/git-largest-blobs.

**Comment by pvchaumier** [comment]
Great, I will look into it next time I have the issue.
In the meantime, I still think giving a feedback saying which file is too big would be helpful and preferable to adding a new custom script.
If you disagree, please close this issue as I do not have much more to say :smile: 
Thank you for helping out !

**Comment by technoweenie** [comment]
Hey @pvchaumier, funny you should mention that. We just shipped Git LFS v2.2.0, which has a new `git lfs migrate` tool. Check out the [v2.2.0 release notes](https://github.com/git-lfs/git-lfs/releases/tag/v2.2.0) and [command documentation](https://github.com/git-lfs/git-lfs/blob/v2.2.0/docs/man/git-lfs-migrate.1.ronn).

I'm closing this issue, but we'd love to hear any feedback you have :)

**Comment by Storageness** [comment]
github developers are fucking idiots. Worse platform ever
