### ISSUE TITLE
git-lfs clone needs to support --reference

### ISSUE THREAD

**Issue by euphxenos** [git-lfs/git-lfs#2306]
When working with large git repositories, we do a "git clone --mirror" of that repository on all of our build systems so users can then add "--reference <that mirror>" to their git clone operations to avoid spending a lot of time, network bandwidth, and disk space downloading additional copies of that large repository.  When using git-lfs clone, lfs objects are retrieved from the remote server instead of from the local repository indicated with --reference.

**Comment by ttaylorr** [comment]
Hi @euphxenos, thanks for opening this.

Right now we support the `--reference` (and a similar `--reference-if-able`) flag in `git-lfs-clone(1)` as far as we pass it to the underlying invocation of `git-clone(1)`. We do not support `--reference` with respect to the large files stored in LFS and in .git/lfs/objects.

I think this would be a great feature to add support for, though I don't have time to add this to my roadmap currently.

For reference, I think that implementing this feature would also make LFS able to support local paths given to `git-lfs-clone(1)` and `git-clone(1)`.

**Comment by Steve-Munday** [comment]
I'd like to add my +1 to this feature request.

I recently discovered `--reference` when trying to improve performance in our Jenkins CI environment, but was disappointed when I learned that git-lfs does not use it.  

We have a large repository (5GB with all LFS objects), and clone/checkout operations are a problem, especially when bringing up new nodes or clean workspaces.  I believe this would have a huge impact on our CI performance.

**Comment by samskiter** [comment]
Just dropping a little +1 in here. We also want to speed up our CI machines and bundle more binaries in our repo.

**Comment by samskiter** [comment]
@ttaylorr After re-reading #1007 are you sure that the lfs objects wouldn't be referenced / copied over (if also using --dissociate) from the referenced repo?

**Comment by ttaylorr** [comment]
> @ttaylorr After re-reading #1007 are you sure that the lfs objects wouldn't be referenced / copied over (if also using --dissociate) from the referenced repo?

That's correct, yes.

**Comment by enmagnus** [comment]
+1. This would improve our CI machine performance a great deal!

**Comment by enmagnus** [comment]
This would be a most wanted feature to speed up our CI system.

**Comment by larsxschneider** [comment]
> Right now we support the --reference (and a similar --reference-if-able) flag in git-lfs-clone(1) as far as we pass it to the underlying invocation of git-clone(1). We do not support --reference with respect to the large files stored in LFS and in .git/lfs/objects.

@ttaylorr I am confused. Isn't that what we test here: https://github.com/git-lfs/git-lfs/blob/a6a5ba2f38d364f60d4f1b4b5361888fa76575bd/test/test-reference-clone.sh#L47-L53

**Comment by ttaylorr** [comment]
@larsxschneider you're absolutely correct, I forgot about this change. I believe that @jlehtnie introduced support for `--reference` (but not `--reference-if-able`) in https://github.com/git-lfs/git-lfs/pull/1007.

**Comment by HemangLavana** [comment]
I would also like to add +1 to this feature request. Any updates on the status of this feature request?

**Comment by ttaylorr** [comment]
Hi everybody, I am going to close this issue since 'git-lfs-clone(1)' is
marked as deprecated. We have marked the command as such since the
process filter makes pure 'git-clone(1)''s just as fast, without the
need for this "wrapper" command.

Since the command is deprecated, we'll be removing it in v3.0.0, and not
updating it between now and then (save for things such as security
vulnerabilities, etc.)

Thanks for your understanding.

**Comment by samskiter** [comment]
Could we add support for --reference-if-able then?
