### ISSUE TITLE
Error: unknown command "post-merge" for "git-lfs" 

### ISSUE THREAD

**Issue by jwvanderbeck** [git-lfs/git-lfs#2307]
I am having some serious issues using git-lfs on Windows 10.  I installed via the binary download and then initialized it as instructed.

Using the Git Console that is installed as part of the GitHub Desktop application, I did a standard git pull and while the progress seemed about as expected, I got an error at the very end:
**Error: unknown command "post-merge" for "git-lfs"** 

D:\Unity Projects\stellar-trail [master ≡]> git pull
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 26 (delta 15), reused 26 (delta 15), pack-reused 0
Unpacking objects: 100% (26/26), done.
From https://github.com/jwvanderbeck/stellar-trail
   80996d2..3f3289d  master     -> origin/master
Updating 80996d2..3f3289d
Fast-forward
 Assets/Scenes/MissionDev.unity                     |  54 +++-
 .../Assemblies/MissionSystem/Actions.meta          |   9 +
 Assets/StellarTrail/Assemblies/UI/PanelA1.anim     | 347 +++++++++++++++++++++
 .../StellarTrail/Assemblies/UI/PanelA1.anim.meta   |   9 +
 .../StellarTrail/Assemblies/UI/PanelA2_Close.anim  | 131 ++++++++
 .../Assemblies/UI/PanelA2_Close.anim.meta          |   9 +
 .../StellarTrail/Assemblies/UI/PanelA2_Open.anim   | 131 ++++++++
 .../Assemblies/UI/PanelA2_Open.anim.meta           |   9 +
 Assets/StellarTrail/Assemblies/UI/UIController.cs  |  54 +++-
 Assets/StellarTrail/UI/UIAnimations.controller     | 263 +++++++++++++---
 .../DisplayFab/Editor/DisplayFabEditor.pdb.meta    |   8 +
 .../DisplayFab/Runtime/DisplayFabRuntime.pdb.meta  |   8 +
 Assets/Terrains.meta                               |   9 +
 13 files changed, 988 insertions(+), 53 deletions(-)
 create mode 100644 Assets/StellarTrail/Assemblies/MissionSystem/Actions.meta
 create mode 100644 Assets/StellarTrail/Assemblies/UI/PanelA1.anim
 create mode 100644 Assets/StellarTrail/Assemblies/UI/PanelA1.anim.meta
 create mode 100644 Assets/StellarTrail/Assemblies/UI/PanelA2_Close.anim
 create mode 100644 Assets/StellarTrail/Assemblies/UI/PanelA2_Close.anim.meta
 create mode 100644 Assets/StellarTrail/Assemblies/UI/PanelA2_Open.anim
 create mode 100644 Assets/StellarTrail/Assemblies/UI/PanelA2_Open.anim.meta
 create mode 100644 Assets/Techooka Labs/DisplayFab/Editor/DisplayFabEditor.pdb.meta
 create mode 100644 Assets/Techooka Labs/DisplayFab/Runtime/DisplayFabRuntime.pdb.meta
 create mode 100644 Assets/Terrains.meta
**Error: unknown command "post-merge" for "git-lfs"
Run 'git-lfs --help' for usage.**

**Comment by jwvanderbeck** [comment]
Additionally now I am looking back on my previous push and noticed I had an error there as well that I didn't notice, and it seems similar to this error just in reverse:

D:\Unity Projects\stellar-trail [master ↑3 +6 ~0 -0 ~]> git commit -am "Started work on UI Controller and animations"
Error: unknown command "post-commit" for "git-lfs"
Run 'git-lfs --help' for usage.
[master 80996d2] Started work on UI Controller and animations
 6 files changed, 555 insertions(+)
 create mode 100644 Assets/StellarTrail/UI/UIAnimations.controller
 create mode 100644 Assets/StellarTrail/UI/UIAnimations.controller.meta
 create mode 100644 Assets/StellarTrail/UI/UIScreen_VehicleAssembly_Close.anim
 create mode 100644 Assets/StellarTrail/UI/UIScreen_VehicleAssembly_Close.anim.meta
 create mode 100644 Assets/StellarTrail/UI/UIScreen_VehicleAssembly_Open.anim
 create mode 100644 Assets/StellarTrail/UI/UIScreen_VehicleAssembly_Open.anim.meta

**Comment by technoweenie** [comment]
I'm betting you have multiple copies of LFS, and a newer one setup hooks for `git lfs [post-commit | post-merge]` commands. An easy fix is to delete `.git/hooks/post-commit` and `.git/hooks/post-merge`.

Those file paths look Unity-related. Are you using the GitHub Unity plugin? That includes LFS v2.x, which implements those new callbacks. What version of GitHub Desktop are you on? What does running `git lfs version` say?

**Comment by jwvanderbeck** [comment]
I am not using any GitHub Unity plugin.  I didn't even know one existed but now I'm curious :)

To the best of my knowledge I have not installed a second git lfs unless I did it a while ago and just forgot about it.  It did install the GitHub Desktop a while back, perhaps it installed its own version?

git lfs version: git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)

**Comment by technoweenie** [comment]
Yes, GitHub Desktop comes with its own version. You should be able to upgrade your regular LFS install to the latest.

**Comment by kachkaev** [comment]
Strange, but I've started seeing this on ubuntu 16.04 since recently. `sudo apt-get update && sudo apt-get upgrade` did not help.

**Comment by technoweenie** [comment]
@kachkaev Can you post details in a new issue? Specifically, what version of LFS you have. Sounds like you have some PATH issues. However, this issue is specifically for GitHub Desktop and Windows, and I'd prefer not to clutter it with other bug reports. Thanks.

**Comment by grantstephens** [comment]
Also just started getting this in Ubuntu.
`git-lfs/1.5.6 (GitHub; linux amd64; go 1.7.4)`
Couldn't find a bug posted by @kachkaev so adding this here for now. Also seems to be after a recent apt update.

**Comment by ttaylorr** [comment]
@grantstephens the `post-merge` command was added in [Git LFS v2.0.0][1], so perhaps this could be the following:

1. Have LFS v2.0.0 or newer installed
2. Initialize repo-level hooks that call `git lfs post-merge`
3. Downgrade to v1.5.6 or earlier
4. Try and execute a merge, fail to find missing `post-merge` command.

Could you try either upgrading to the latest version of LFS (currently v2.2.1), or removing `.git/hooks/post-merge` in your affected repositories. With this route, you'll also have to remove some other hooks.

[1]: https://github.com/git-lfs/git-lfs/releases/tag/v2.0.0

**Comment by grantstephens** [comment]
Thanks, the upgrade seems to have fixed it- don't know why it wasn't upgrading by itself using apt- had to add the packagecloud stuff again.
