### ISSUE TITLE
does git lfs server support interactive query?

### ISSUE THREAD

**Issue by zhiqiangZHAO** [git-lfs/git-lfs#2309]
Hi,

I use arc to generate diff. And everything looks fine.
It's just the jenkins failed to download the file.

I don't know whether it's the problem I didn't upload them, or the jenkins server has something wrong to get them from git lfs server.
So I think if there is a command which can check the status of a single file is great.
Do we have one?

**Comment by ttaylorr** [comment]
You can check the status of which files you have locally by running:

```bash
$ git lfs ls-files | grep "<my-filename>"
```

If the preceding character is a '*', the file is present in your `.git/lfs/objects` directory. If the preceding character is a '-', it is missing.

It looks like there is a discussion thread about including LFS support in the default distribution of Jenkins, but you can alternatively install it yourself and include a script to pull the LFS files. [[source](https://issues.jenkins-ci.org/browse/JENKINS-35687)].

**Comment by zhiqiangZHAO** [comment]
Thank you, @ttaylorr!
Is there a way I can send a curl query to git lfs server to query file status by sha?
I think it will be very useful if git lfs server support this kind of query.
My point is I want to know:
1. either the file is not uploaded to git lfs server
2. we have some issues to download it from git lfs server

**Comment by ttaylorr** [comment]
> Is there a way I can send a curl query to git lfs server to query file status by sha?

Yes, if I understand what you mean by "query file status". To answer the first of your questions, you can run:

```bash
$ curl \
  -X POST \
  -d '{"operation":"download", "objects": [{"oid": "your-oid", "size": your-size}]}' \
  https://lfs-host/<prefix>/batch
```

Where the path I'd include for that request on GitHub is something like: `https://github.com/git-lfs/git-lfs.git/info/lfs/objects/batch`

**Comment by zhiqiangZHAO** [comment]
Thank you, @ttaylorr !
where should I put the file name?
What is the <prefix> should be?
is lfs-host the EndPoint when we run "git lfs env"?
I have something like:
Endpoint=http://:@artifactory.xxx.xxx:4587/artifactory/api/lfs/lfs-local (auth=none)

**Comment by ttaylorr** [comment]
> where should I put the file name?

The LFS API does not store objects by filename, it is instead [content addressable](https://en.wikipedia.org/wiki/Content-addressable_storage). To determine the SHA256 hash of a file, you could run `shasum -a 256 < /path/to/file.ext` and use the output of that command as the `"oid"` value in the JSON you POST from above.

> is lfs-host the EndPoint when we run "git lfs env"?
> I have something like:
> Endpoint=http://:@artifactory.xxx.xxx:1234/artifactory/api/lfs/lfs-local (auth=none)

Correct 😄

**Comment by zhiqiangZHAO** [comment]
I tried. But I got 404 for an existing file:
{
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}
Does the above response mean my path is correct?
Then it's weird why it return 404.

what is the meaning of <prefix>?

**Comment by ttaylorr** [comment]
> I tried. But I got 404 for an existing file:

That could mean that your path is incorrect. Here are some tips 😄 

`<prefix>` would be the value of your remote with the suffix `.git/info/lfs/objects/batch`, for instance:

```
https://github.com/user/repo.git/info/lfs/objects/batch
```

**Comment by zhiqiangZHAO** [comment]
do you mean the result of "git remote -v"?
I got something like:
origin	gitolite@code.xxx:aa/bb (fetch)
origin	gitolite@code.xxx:aa/bb (push)

**Comment by ttaylorr** [comment]
Yes :)

**Comment by zhiqiangZHAO** [comment]
I am a little confused, which one should I use?
"git lfs env" and "git remove -v"
I got 2 different address. And neither works for me.

**Comment by ttaylorr** [comment]
> I am a little confused, which one should I use?

Sorry for the confusion! You should use the one next to `Endpoint=` in the output of `git lfs env`. Can you post the output of your `cURL` command so we can try and figure out why it's not working?

**Comment by zhiqiangZHAO** [comment]
thank you so much!
It's just something like this:
Endpoint=http://:@artifactory.xxx.xxx:1234/artifactory/api/lfs/lfs-local (auth=none)
We use JFrog Artifactory
