### ISSUE TITLE
git-lfs clean dies on signal 11 while squashing commits during a rebase

### ISSUE THREAD

**Issue by paul-tcell** [git-lfs/git-lfs#2326]
My repo had 6 commits, all pushed.   one of those commits was adding/committing some binary files, as per the git-lfs instructions.   That all worked fine.

I ran `git rebase -i HEAD~6` and then picked `squash` for all the commits in the editor except the first one.

the rebase threw this error:
```
error: git-lfs clean -- 'nginx/lib/libtcellagent.so' died of signal 11
error: external filter 'git-lfs clean -- %f' failed 139
error: external filter 'git-lfs clean -- %f' failed
fatal: nginx/lib/libtcellagent.so: clean filter 'lfs' failed
```

I'm on osx 10.12.5 Sierra, git lfs version reports:
`git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)`
my git version is `git version 2.13.1`

**Comment by ttaylorr** [comment]
Hi @paul-tcell, thanks for opening this issue and sorry that you're having trouble! I'm not immediately sure what's going on, but one thing I noticed is that your LFS version is a few behind the latest.

Would you mind upgrading to the latest (v2.1.1) via `brew update && brew upgrade git-lfs` and trying again?

If the problem persists, I'd be more than happy to dive in!

**Comment by paul-tcell** [comment]
weird, `brew` was reporting 2.1.1 was installed.   But apparently Github desktop had an older version in `/usr/local/bin`.   I got rid of that, reinstalled with brew, and my problem went away.
