### ISSUE TITLE
"track --no-modify-attrs" fails on CircleCI, Git 2.0.0

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#2357]
I've observed while writing https://github.com/git-lfs/git-lfs/pull/2353 that after upgrading the minimum Git version to 2.0.0, the CircleCI build using `$MINIMUM_SUPPORTED_GIT_FROM_SOURCE` failed on the `track --no-modify-attrs` test.

I'm not sure yet why this is broken as I cannot reproduce the failure locally. I suspect that Git changed it's "stat-dirty" check somewhere near 2.0.0.

**Comment by bk2204** [comment]
I don't think this is still a problem.  We've moved to Actions and all the tests seem to be working, so I'm going to close this.
