### ISSUE TITLE
File Uploaded But Can't See

### ISSUE THREAD

**Issue by mburaksayici** [git-lfs/git-lfs#2365]
I pushed my 1.8 gb file,  I see all progress bar that showing how many downloaded / 1.8  but now I don't know where it went. Then I committed like "git commit myfile.npy", now it says another progress is going on. To save this,  I tryed to delete index.lock with command line tool but it still says that another progress is ggoing on.

C:\Users\...>git log
commit 3067547085c269168fec4ff4ea34879c7027a919 (HEAD -> master)
Author: my username<my@mail.com>
Date:   Wed Jun 28 20:56:57 2017 +0300

    myfile.npy

**Comment by mburaksayici** [comment]
Okey problem is that I have 1 gigs of capacity, but 1.7 uploaded. Thats why it doesnt show.

**Comment by ttaylorr** [comment]
@mburaksayici it seems like this issue is resolved! If you run into any problems in the future, please be sure to let me know by commenting on this issue.
