### ISSUE TITLE
Endpoints for upload and download

### ISSUE THREAD

**Issue by shuhrat** [git-lfs/git-lfs#2367]
Hi!

Is it possible to configure LFS, to use different endpoints for `upload` and for `downdload`?

We have tons of LFS files, over 50K, and simple command like `git lfs fetch --all` is strongly ddosing our enterprise github.

Want to write caching proxy, only for downloading objects, to overcome this problem.

Simple I want to use
- `enterprise.github.com` to upload
- `caching-proxy.domain.com` to download

**Comment by technoweenie** [comment]
Sure, you can set a custom push url in your git config. The [Server Discovery doc](https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md#custom-configuration) mentions this, but could definitely go into more detail. Here are the git config keys that LFS checks in order of preference. If a key doesn't exist in `git config --list`, then it tries the next one.

* `lfs.pushurl` - LFS server for uploads only, on all remotes
* `lfs.url` - LFS server for all remotes
* `remote.{remote}.lfspushurl` - LFS server for uploads only
* `remote.{remote}.lfsurl` - LFS server
* `remote.{remote}.pushurl` - [Guess](https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md#guessing-the-server) the LFS server based on this git remote for pushes only
* `remote.{remote}.url` - [Guess](https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md#guessing-the-server) the LFS server based on this git remote.

In your case, I'd suggest setting something like this:

```sh
$ git config remote.origin.lfspushurl https://enterprise.github.com/{USER}/{REPO}.git/info/lfs
$ git config remote.origin.lfspushurl https://caching-proxy.domain.com/{USER}/{REPO}.git/info/lfs

**Comment by shuhrat** [comment]
second config from example above is supposed to be 

`$ git config remote.origin.lfsurl https://caching-proxy.domain.com/{USER}/{REPO}.git/info/lfs`?

**Comment by technoweenie** [comment]
Doh yes. Bad copy pasta :)

**Comment by shuhrat** [comment]
@technoweenie thank you!

**Comment by jopasserat** [comment]
Not sure this is worth creating another issue as this is to me an edge case of the same problem:

When `lfs.url` and `lfs.pushurl` point to the same URL, the access method can be changed for both when pushing.
In my case I wanted to be able to `lfs pull` without authentication, but to have `basic` https when pushing.

This works fine for an initial run, but `push` populates the two variables `lfs.<url>.access` and `lfs.<url>.locksverify` as follows:

```
lfs.<url>.locksverify=false
lfs.<url>.access=basic
```

This result in the `basic` authentication being used instead of `none` the next time a `pull` is called.

Not sure there's a way to distinguish between the two URLs from `git-credentials` perspective, but maybe the `git-lfs` client could try without authentication first?

Or am I missing another variable here?

**Comment by technoweenie** [comment]
That's not something that's supported right now. LFS uses the `lfs.<url>.access` value to determine whether it needs authentication. What's the problem with sending an authorization header even if it's not technically needed for fetches? Does git let you do this?

**Comment by jopasserat** [comment]
Skipping the password prompt. 
But I guess that's supposed to be handled by pre-storing credentials.
Not sure about how git does this but I see your point, thanks for your reply!

**Comment by technoweenie** [comment]
> But I guess that's supposed to be handled by pre-storing credentials.

Git uses a personally configured credential helper to store passwords. See https://help.github.com/articles/caching-your-github-password-in-git/ for more info on that. My recommendation is to find one for your platform that stores passwords long term, securely. The basic one that Git ships with stores it in memory for just a short time.

Also, you can use an SSH git remote if you want to get around using username/password credentials.
