### ISSUE TITLE
Debian raspbian/jessie installation script fails

### ISSUE THREAD

**Issue by Davidnet** [git-lfs/git-lfs#2379]
I'm literally following each step of the website installation, it appears that the script is successful in adding repo (packagecloud.io shows in `sudo apt update`), even after running apt-get update or rebooting I cannot seems  to install git-lfs
```bash
pi@kiwi:~ $ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
Detected operating system as raspbian/jessie.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
pi@kiwi:~ $ sudo apt install git-lfs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package git-lfs
```

Any help?

**Comment by Davidnet** [comment]
Also running the .tar.gz provided in the website I encounter:
`/usr/local/bin/git-lfs: 1: /usr/local/bin/git-lfs: Syntax error: Unterminated quoted string`

**Comment by ttaylorr** [comment]
@Davidnet thanks for opening this, I'm glad that it seems like you have things resolved. We don't currently distribute ARM-targeted releases of LFS, though I wouldn't be opposed to start doing that if there was enough desire for it.

That being said, you can cross-compile LFS yourself (so long as you have a Go installation) by running any of:

```bash
$ GOOS=linux GOARCH=arm ./script/bootstrap
$ GOOS=linux GOARCH=arm64 ./script/bootstrap
$ GOOS=<your-os> GOARCH=arm64 ./script/bootstrap
# ...
```

Please let me know if you run into any issues building yourself, and I'd be more than happy to help out.
