### ISSUE TITLE
test: split clone tests into Git 2.2.0+, and others

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#2391]
Merging #2252 caused a bug pointed out in https://github.com/git-lfs/git-lfs/issues/2366 and fixed in https://github.com/git-lfs/git-lfs/pull/2369.

In adding the new `--jobs` flag, it was passed as a flag to whatever Git binary is installed on the system that runs it. This causes an `unknown flag` error to be raised on Git versions earlier than 2.9.0.

In https://github.com/git-lfs/git-lfs/pull/2369#issuecomment-312110393, @technoweenie points out the reason that this wasn't caught in CI:

> The `GIT_EARLIEST_SUPPORTED_VERSION` test _should_ have caught this, but [the clone test requires git 2.2.0+](https://github.com/git-lfs/git-lfs/blob/d65f80119281b1b7f7f650c44324d25087a00484/test/test-clone.sh#L5). Doh. I don't know if it's worth adding to the test matrix though.

---

I'm opening this issue to propose splitting the `test/test-clone.sh` file into tests that do and don't require Git 2.2.0, that way we can catch errors like these in the future.

**Comment by ttaylorr** [comment]
Ack-ing out of our internal first responder rotation.

**Comment by technoweenie** [comment]
Closing this, it's unnecessary since we've deprecated `git lfs clone`.
