### ISSUE TITLE
 Clone without Downloading LFS Files on a System with Git LFS Installed

### ISSUE THREAD

**Issue by sauhaardac** [git-lfs/git-lfs#2405]
I read other posts with skip-smudge, but these didn't seem to work for me. What should I run exactly to get set this up as the system wide default for cloning?

**Comment by ttaylorr** [comment]
Hi @sauhaardac, you enable this behavior system-wide by setting `GIT_LFS_SKIP_SMUDGE=1` in your environ.

Please let me know and don't hesitate to reopen this issue if you have any problems!

**Comment by sauhaardac** [comment]
Still have the problem, I attached a screenshot below. I set that variable and it sill goes about downloading the LFS files.
![screenshot from 2017-07-10 14-55-35](https://user-images.githubusercontent.com/10953031/28041911-fff08804-657f-11e7-911b-9eb607965c1c.png)
