### ISSUE TITLE
Clone without Downloading LFS Files on a System with Git LFS Installed

### ISSUE THREAD

**Issue by sauhaardac** [git-lfs/git-lfs#2406]
Can't reopen #2405 so I just made a new issue, my question is the same. I still have to download the LFS files every time I clone. I attached a screenshot below. I set that variable and it sill goes about downloading the LFS files.

![screenshot from 2017-07-10 14-55-35](https://user-images.githubusercontent.com/10953031/28041911-fff08804-657f-11e7-911b-9eb607965c1c.png)

**Comment by canyou2014** [comment]
Does "GIT_LFS_SKIP_SMUDGE=1 git clone " work?

**Comment by ttaylorr** [comment]
I have the same thought that @canyou2014 has... I think the issue is that although you are setting the value in your environment when you run `GIT_LFS_SKIP_SMUDGE=1`, but it's not making it into the environment of the `git` executable when you run it.

I think either invoking `git` as `GIT_LFS_SKIP_SMUDGE=1 git ...`, or `export(1)`-ing the value by running:

```bash
$ export GIT_LFS_SKIP_SMUDGE=1
$ git ...
```

**Comment by sauhaardac** [comment]
That did it! Thanks for your help.

**Comment by Borda** [comment]
@ttaylorr Hello, I have a repo hosted on bitbucket with allowed LFS and also configured with git lfs, so the traces are:

but I have not found any way how to clone repo without downloading all content (files)... I have tried
- [install without downloading](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-install.1.ronn) `git lfs install --skip-smudge`
- ```
  export GIT_LFS_SKIP_SMUDGE=1
  git clone ssh://git@bitbucket-ssh.....net:7999/vrt/...-datasets.git
  ```
- ```
  git clone -c "lfs.fetchexclude=*"  ssh://git@bitbucket-ssh.....net:7999/vrt/...-datasets.git
  ```

**Comment by Rhuaer** [comment]
@Borda try this:
```bash
export GIT_LFS_SKIP_SMUDGE=1
git clone --filter=blob:none /your/git/repo/url
```

It worked in my project. I just got the small size ref file, not the large size binary file.

**Comment by jhbertra** [comment]
> having done this, how does one induce git-lfs to download the actual data?

@eddiehazel `git lfs pull`
