### ISSUE TITLE
Invalid GOPATH running script/integration with Go 1.8

### ISSUE THREAD

**Issue by olivierIllogika** [git-lfs/git-lfs#2411]
As of Go 1.8, it is no longer required to have a defined GOPATH environment variable (See https://rakyll.org/default-gopath/).

When running script/integration, script/build.go gets the GOPATH from the os environment and assumes it is valid leading to a build error.

Repro steps:
1. Install Go 1.8+
2. Unset GOPATH if any
Note that Go can still build, using is a default GOPATH (See https://rakyll.org/default-gopath/)
3. Launch script/integration

Result:
following build error:
> script/build.go:18:2: cannot find package "github.com/git-lfs/git-lfs/config" in any of:
> 	/usr/local/go/src/github.com/git-lfs/git-lfs/config (from $GOROOT)`
> 	**[path to local git-lfs root]**/test/remote/home/go/src/github.com/git-lfs/git-lfs/config (from $GOPATH)

Workaround:
- set an explicit GOPATH (global or on command invocation)

I'm guessing the best solution would be to add a check in build.go, buildGoEnv() to check if GOPATH is empty and build a default one if it is.

**Comment by ttaylorr** [comment]
@olivierIllogika thanks for pointing this out. I'm going to add this to the backlog for now, since setting a non-empty `$GOPATH` is a valid workaround for now.

**Comment by chrisd8088** [comment]
I'm going to close this as most of the context here has changed (`script/integration` and `script/build.go` are both gone).
