### ISSUE TITLE
Comment `# filter=lfs` in .gitattributes is interpreted by Git LFS

### ISSUE THREAD

**Issue by jokram** [git-lfs/git-lfs#2413]
### Steps to reproduce
1. In the `.gitattributes` put the following lines:
```
# filter=lfs
*.zip	filter=lfs diff=lfs merge=lfs -text
```
2. Call `git lfs track` to list the patterns:
```
$ git lfs track
Listing tracked patterns
    # (.gitattributes)
    *.zip (.gitattributes)
```
3. If you slighlty change the comment in `.gitattributes` to:
```
# filter=lf
*.zip	filter=lfs diff=lfs merge=lfs -text
```
then it works properly:
```
$ git lfs track
Listing tracked patterns
    *.zip (.gitattributes)
```

### Conclusion
It seems that the line starting with the hash will be interpreted by Git LFS, but should be ignored as comment

### Environment
```
git-lfs/2.1.1 (GitHub; windows amd64; go 1.8.1; git 3314e287)
git version 2.13.2.windows.1
```

**Comment by ttaylorr** [comment]
Hi @jokram, thanks for opening this. Good catch pointing out this bug. I think the issue lies [here](https://github.com/git-lfs/git-lfs/blob/v2.2.1/git/attribs.go#L60) (via [this](https://github.com/git-lfs/git-lfs/blob/v2.2.1/commands/command_track.go#L52) call). The easiest change that I can think to make is to apply a diff like:

```diff
diff --git a/git/attribs.go b/git/attribs.go
index 16321b9f..4806c903 100644
--- a/git/attribs.go
+++ b/git/attribs.go
@@ -57,7 +57,7 @@ func GetAttributePaths(workingDir, gitDir string) []AttributePath {
 
 		for scanner.Scan() {
 			line := scanner.Text()
-			if strings.Contains(line, "filter=lfs") {
+			if !strings.HasPrefix(line, "#") && strings.Contains(line, "filter=lfs") {
 				fields := strings.Fields(line)
 				pattern := fields[0]
 				if len(reldir) > 0 {
```

But I wonder if LFS could do something more robust. Given:

```gitattributes
# *.dat filter=lfs diff=lfs merge=lfs -text
```

and:

```bash
$ git lfs track "*.dat"
```

The `.gitattributes` should be rewritten as uncommenting the commented tracked path:

```gitattributes
*.dat filter=lfs diff=lfs merge=lfs -text
```

What do you think we should do in this case?

**Comment by technoweenie** [comment]
I'd prefer just leaving commented lines with your suggested bug fix.

**Comment by jokram** [comment]
Hi @ttaylorr,
in my opinion comments in configuration files are done by humans (normally) and should not be touched by any tool. So I would prefer more the direction you've specified in the diff.

Concerning `strings.HasPrefix(line, "#")` I've one remark where I'm uncertain:
What if the line starts with some spaces and then the hash character comes as comment?
Will this also be skipped then?
Or is this not allowed in `.gitattributes` files, so an invalid use case?

**Comment by mathstuf** [comment]
From `git-config(1)`:

```
The syntax is fairly flexible and permissive; whitespaces are mostly ignored. The # and ; characters begin comments to the end of line, blank lines are ignored.
```

I don't see anything in `gitattributes(5)` about comments, but I imagine they use the same (or at least similar) comment parsing functions. So it should be checking for `#` and `;` after stripping whitespace from the beginning of the line.

**Comment by mathstuf** [comment]
Hmm. This code is also wrong in the abstract. With this `.gitattributes`:

```gitattributes
[attr]lfs  filter=lfs diff=lfs merge=lfs -text

*.png lfs
```

This will never see the `*.png` line, but instead give the (useless) `[attr]lfs` as a "match".

**Comment by technoweenie** [comment]
Ah yes, our parser is incredibly naive. But, it's also not that important to LFS. Git will keep interpreting `.gitattributes` the same way, regardless of how `git lfs track` works. Fixing it would be fantastic though :)

**Comment by jokram** [comment]
Concerning the parser: In another context (also LFS related) we are using the command `git check-attr filter <path>` which helps interpreting the .gitattributes correctly. Maybe it's worth to have a look at that command to know how to correclty parse .gitattributes.

**Comment by mathstuf** [comment]
`git check-attr` can get you the paths that are looked at for the attribute (though it'd be nice if it could be run in verbose mode to say which line gave the attribute to the path). You almost need the internal state of what is matched where that Git uses internally to apply to a given path. Which likely means reimplementing it in Go.

**Comment by bk2204** [comment]
I'm going to close this, since it appears to be fixed.

**Comment by mathstuf** [comment]
Note that there are other issues raised here. I'll file a new issue for that bit.

**Comment by ttaylorr** [comment]
> I'll file a new issue for that bit.

Thank you.

**Comment by mathstuf** [comment]
Ah, should mention it here explicitly: see #1719 for the `[attr]` issue.
