### ISSUE TITLE
git-lfs-migrate(1): packed object reads 

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#2415]
# Goal

Increase the speed at which `git-lfs-migrate(1)` can read packed objects.

## Background

To rewrite history, the `git-lfs-migrate(1)` command has to read blob,
commit, and tree objects from the object database of a repository, usually
inside of `.git/objects`.

This functionality is implemented in the `git/odb` package which can (as of
v2.2.0) read and write loose objects. This works fine, but becomes an issue when
trying to read an object that is packed.

When a packed object is encountered in v2.2.0, we write to a long-running
invocation of `git-cat-file(1) --batch`, which then writes to stdout a (mostly)
correct loose representation of the object whose SHA1 we wrote previously.

This too works fine, but can be improved in two ways:

1. **Parallelization cost**. In order to have more "workers" traversing the
   history graph, we must linearly increase the number of `git-cat-file(1)`
   invocations we have running. Since the output of `git-cat-file(1)` is not
   multiplexed, we can only read one object out of the program at a time.
   Therefore, if we have more than one worker(s) trying to read an object at a
   time, we must either a) synchronize and wait, or b) run more
   `git-cat-file(1)`'s.
2. **Pipe throughput**. As we have experienced with `filter.lfs.process` (and
   friends), the pipe data transfer overhead is non-zero. Moreover, this is
   effect is especially noticeable on the shell that ships with Git for Windows
   (a project which distributes LFS). If we can avoid the pipe data transfer
   overhead, we will increase the speed at which `git-lfs-migrate(1)` can
   rewrite history.

## Proposition(s)

Teach the `git/odb` package how to read packed objects. This will *eliminate
the parallelization costs* (it is cheaper to open a file descriptor than it is
to run a program), and *remove pipe data throughput from the equation*.

I'd like the API to look something like this:

```go
package git/odb/pack

type Index struct { ... }

type IndexEntry struct {
  Name       [20]byte
  PackOffset uint64
  CRC        uint32
}

// Entry returns the a packed object entry for the given name in O(log(n)) time.
func (i *Index) Entry(name [20]byte) *IndexEntry { ... }
```

and:

```go
package git/odb/pack

type Packfile struct { ... }

// Resolve uses the packfile index to find and apply the delta COPY/ADD
// instructions to resolve the object contents for the given name "name".
func (p *Packfile) Resolve(name [20]byte) (io.Reader, error) { ... }
```

lastly:

```go
package git/odb

type ObjectDatabase struct { ... }

func (d *ObjectDatabase) open(sha []byte) (*ObjectReader, error) {
  // 1. Try and read loose object, or ...
  // 2. Try and find pack file, and ...
  //    i. return successfully, or ...
  //    ii. return (nil, err).

  // ...
}
```

## Questions

We have two approaches to reading the `pack-*.idx` file(s):

1. Read the object entries ahead of time, binary search through populated
   entries.
2. Read the entries as they are looked up, binary search through the
   `pack-*.idx` on disk.

I think that there are pros and cons to each of these approaches. The first
approach is perhaps easier to understand the implementation of, but requires a
higher memory usage throughout the lifetime of the LFS process. To better
understand this requirement, I wrote a program ([source][1]) to parse the index
entries ahead of time (for a given set of entries) and print out the total
memory usage:

```bash
$ find ~/github/misc/linux/.git/objects/pack/*.idx |
  xargs go run parse_index_entries.go
System: 117 MB
# ...

System: 490 MB
```

The later approach would inarguably consume less memory, but would instead
require `seek()` calls in order to jump around the index file as needed. [This
too is slow][2], but is an order of magnitude faster than reading packfiles
sequentially.

I think for now it makes sense to run with the first approach, and
benchmark/transition to the second approach if needed.

## Non-goal(s)

* **Packed object writes**. These are expensive; each pack addition requires not
  only recalculating the delta-base chain(s), but also an overflowing change to
  the corresponding `pack-*.idx` file. If this becomes necessary (i.e., so many
  objects are rewritten it becomes impractical to keep them all loose), we can
  pause the migration, shell out to `git-pack-objects(1)`, and then resume. This
  could potentially become it's own project later.

---

/cc @git-lfs/core

[1]: https://gist.github.com/ttaylorr/21d05c2a6f727be00badce4ccd2d2aef
[2]: https://gist.github.com/jboner/2841832

**Comment by ttaylorr** [comment]
@peff wisely points out that I can use [`mmap(2)`][1] in order to avoid the `seek(1)` cost of bouncing around a file on disk. To me, this means that the 2nd option of lazily loading each entry makes more sense, since:

1. We don't have to read continuous sections of the file.
2. We don't have to pay the expensive cost of `seek(1)`.
3. We don't (except in the case of full repository rewrites) need all of the objects in a packfile, so save time parsing it as with 1.  

[1]: https://en.wikipedia.org/wiki/Mmap

**Comment by peff** [comment]
It's also how Git does it.

**Comment by ttaylorr** [comment]
I just opened a series of pull requests to implement v1 and v2 object lookup in index files. I originally wrote this as one pull request, but it is larger than I want to have reviewed in one piece. Instead, I broke the commits into their own branches and created separate PRs to make them hopefully easier to review.

Here's a brief overview of how they come together:

- https://github.com/git-lfs/git-lfs/issues/2420: implement the `*Index`, and `IndexVersion` types. These will house a binary search implementation, and an entry parsing algorithm respectively in the remaining parts of the series.
- https://github.com/git-lfs/git-lfs/issues/2421: implement the object entry parsing algorithm on v1 indexes.
- https://github.com/git-lfs/git-lfs/issues/2422: implement the object entry parsing algorithm on v2 indexes.
- https://github.com/git-lfs/git-lfs/issues/2423: implement a binary search algorithm to find object offsets in packfiles using the above two pull requests.

Here's a technical overview of the changes at a broad scope:

Packfiles compress loose object data by applying deltas to objects that have similar data. In order to find an object in a packfile, it is helpful to use its corresponding index file (what we parse here). Using the index file dictates where an object begins in the packfile.

In order to implement packfile index parsing, we teach the `IndexVersion` type how to either parse or compare an entry at a given location in the index file. We use that information in the `*Index` type in order to binary search through the index to find the matching entry. This entry will contain the offset that we're looking for, which we can use in a later series to parse out of the packfile.

Some notes on the implementation:

Since using `mmap(2)` (see: https://github.com/git-lfs/git-lfs/issues/2415#issuecomment-314919849) the memory footprint of this program is quite small. For example, compressing `torvalds/linux` into one (large) packfile takes about 2.5mb of memory to hold in memory.

Since we take advantage of the fanout table to construct a binary search algorithm, it's also relatively fast to find the object offsets.

---

Next up will be to use the above to reconstruct loose object data from packfiles. Once that's done we can replace [this][1] code and remove our usage of `git-cat-file(1)`.

[1]: https://github.com/git-lfs/git-lfs/blob/v2.2.1/git/odb/object_db.go#L218-L237

**Comment by ttaylorr** [comment]
I just opened the second and final series of pull requests to implement delta-base assembly and resolution for packed objects.

Here's a brief overview of how this series comes together:

- #2550: implements scaffolding for the `Chain`, `*Object` and `PackedObjectType` types.
- #2551: provides an implementation of the `Chain` interface for the base component of delta-base chains.
- #2552: provides a recursive implementation of the `Chain` interface for the delta component of delta-base chains.
- #2553: implements the `*Packfile` type for creating and assembling delta-base chains.
- #2554: implements a `*Set` type for organizing object lookups across multiple packfiles in a single repository.

Cross-posting from #2554, this provides the following speed increase in migrations where the majority of objects are contained in packfiles (packed with the default settings in Git `2.14.1.145.gb3622a4ee`):

> | | commits | time (s) | rate (objs/sec) |
> | --- | --- | --- | --- |
> | git-lfs-2.2.1@[621d1f8][1] | 34,023 | 10min (600sec) | 56.705 |
> | git-lfs-2.3.0@[28e2158][2] | 142,606 | 10min (600sec) | 237.677 |
> | | | |
> | | +108,583 | - | 4.19x faster |
 
[1]: https://github.com/git-lfs/git-lfs/commit/621d1f8
[2]: https://github.com/git-lfs/git-lfs/commit/28e2158
