### ISSUE TITLE
Unable to push tracked files to repository

### ISSUE THREAD

**Issue by DyspC** [git-lfs/git-lfs#2417]
Hello, 

I've recently set up git on a server for me and my friends to edit our common huge folder but when we tried the first clone the server was unable to pack the files. That's why I learnt about git-lfs and tried to use it.

My repository is set up like this :
```
git init
git remote add origin MY_REPO
git lfs install --local

echo > README
git add README
git commit -m "Initial commit"

git push --set-upstream origin master
```

I launched this bash in the folder in which all my files are and then tested adding txt files
```
git lfs track "*.txt"
git add .gitattributes "*.txt"
git commit -m "Test *.txt"
git push
```
and I get this issue :

> Git LFS: (0 of 41 files) 0 B / 238.50 KB
> batch request: ERROR:gitosis.serve.main:Unknown command denied: exit status 1
> error: failed to push some refs to MY_REPO

If I untrack "*.txt" and add them again the push works perfectly.

Is this because my configuration is bad or because I used gitosis or is it something else ?

My git version is 2.1.4 on the server and 2.13.0.windows.1 on my pc

Thanks,

**Comment by technoweenie** [comment]
That looks like a gitosis error. There's nothing we can do about that, unfortunately.

**Comment by DyspC** [comment]
Ok thanks I'll try to reinstall git without it and come back if I still can't push, bye
