### ISSUE TITLE
GIT LFS Push and Lock with GitLab does not work

### ISSUE THREAD

**Issue by GMaggi89** [git-lfs/git-lfs#2424]
Hello @ all.

I am new in this community and I am using GIT now for a while. 
I read about the locking ability of GIT LFS 2.0 and I wanted to test this ability by locking binary files from modification.

I am currently using GitLab CE 9.3.6 that is running on a Virtual Machine.
It is said, that a GIT LFS Server is implemented in GitLab. 
In the GIT Repository on the GitLab Server Web GUI, there is an entry "Git Lab" that is set to "Enable".
I am using an HTTP address to communicate with the GIT Lab Server.

On my client I am using GIT LFS v. 2.2.1 with GIT 2.13.3.windows.1.
I am using the Bash console.

I started a project on the GitLab Server and tracked some PSD Files with GIT LFS with the command
"git lfs track *.psd' lockable".  
A .gitattribure file is created then.

Then I added the files to stage, commited them into my local repository and pushed them to server with 
"git push origin master"
what actually worked.

But, when I am using 
"git lfs push origin --all" 
the following message appears:
>>>
Git LFS: (0 of 1 files) 0 B / 15.46 MB
batch response: Repository or object not found: http://gitserver/user/gitLFStest.git/objects/batch
Check that it exists and that you have proper access to it

---> I see the files on my GitLab Server, but it seems that they were not pushed with LFS. What is the difference between git push and git lfs push?

Then, when I try to lock a file with
"git lfs lock file.psd"
the following message appears:
>>>
Lock failed: Repository or object not found: http://gitserver/user/gitLFStest.git/locks
Check that it exists and that you have proper access to it

When I type 
"git lfs locks"
to see, if something happend, the windows credential manager appears asking for username and password. When I put in my username and password that I am using to log in into GitLab Web GUI, the credential manager window closes and opens every time without that anything happens. 
After closing the window with cancel, git bash gives me the message: 
>>>
Error while retrieving locks: Git credentials for http://gitserver/user/gitLFStest.git not found.

What should I do to get the locking ability work? 
I thought I would do everything as described in the documentation :(.
Am I doing something wrong?

I hope you can help me.

Best regards,
Giuseppe

**Comment by technoweenie** [comment]
You should file this with gitlab, it looks like it doesn't fully support the LFS API. Also, confirm that your URLs and user authentication are correct. If you need help setting up your Git credential cacher, check out the [github help docs](https://help.github.com/articles/caching-your-github-password-in-git/).

> What is the difference between git push and git lfs push?

`git push` calls a `.git/hooks/pre-push` hook, which should run `git lfs pre-push`. This command will scan _only the range of commits that Git is about to push_ for LFS objects, and attempt to upload them. Note: Running `git push` when there are no new Git commits containing LFS objects to push to your Git server will not report any useful information

`git lfs push` will scan the entire history of the given ref or branch for LFS objects to upload.

If you have problems, running with `GIT_TRACE=1` will print out a lot more debug information.

**Comment by GMaggi89** [comment]
Hey Technoweenie. 
I will check this out.

I assume, that GitLab has not the actual LFS Version implemented. 
I will post here, if I have new informations.

Thanks for help!
