### ISSUE TITLE
Cannot upload MIDI files.

### ISSUE THREAD

**Issue by soma11soma11** [git-lfs/git-lfs#2432]
I am trying to upload my MIDI files on Gitbucket using git-lfs, but it stacks and does not complete uploading the data.
Is it because of my data is too huge? I thought, using git-lfs, it is possible to manage huge data.

Any suggestion? My data is around 5GB.
Thank you!

**Comment by technoweenie** [comment]
Git LFS doesn't set any limits on individual object size. It's really up to the LFS server to determine what objects it supports. Can you share the error messages you're getting?

**Comment by technoweenie** [comment]
Hey, I just wanted to let you know that we discovered an issue with Git objects over 4GB on Windows. So, even if we're able to replicate and fix your issue, you will have problems on Windows.

Details: https://github.com/git-lfs/git-lfs/issues/2434#issuecomment-317582466

**Comment by soma11soma11** [comment]
Mhh. But I am using Mac.

**Comment by technoweenie** [comment]
Ah thanks for letting me know. If you send me more details about your problem, I may more help :)
