### ISSUE TITLE
Tracked file patterns having `-filter=lfs` are not listed correclty

### ISSUE THREAD

**Issue by jokram** [git-lfs/git-lfs#2442]
### Steps to reproduce
1. In the `.gitattributes` put the following lines:
```
*.zip filter=lfs diff=lfs merge=lfs -text
*.doc filter=lfs diff=lfs merge=lfs -text
```
2. In a subdirectory `core` put the following `.gitattributes`:
```
*.doc -filter=lfs diff=lfs merge=lfs -text
```
Note that the filter is prepended with "-" to NOT track `*.doc` files in this subdirectory.

3. Call `git lfs track` to list the patterns:
```
$ git lfs track
Listing tracked patterns
    core\*.doc (core\.gitattributes)
    *.zip (.gitattributes)
    *.doc (.gitattributes)
```
=> It is not visible that `core\*.doc` is NOT tracked

4. Add a `*.doc` file in the `core` subdirectory, comit and push to origin
=> The file is not tracked by LFS as desired

### Conclusion
When `.gitattributes` contains `-filter=lfs` the `-` seems not to be respected when listing tracked patterns. But for commiting and pushing the `-` is correctly interpreted.

### Environment
```
git-lfs/2.1.1 (GitHub; windows amd64; go 1.8.1; git 3314e287)
git version 2.13.2.windows.1
```

**Comment by technoweenie** [comment]
Thanks for the bug report.

**Comment by mathstuf** [comment]
See also #2413.
