### ISSUE TITLE
Git LFS File Skipped

### ISSUE THREAD

**Issue by VertXLabs** [git-lfs/git-lfs#2444]
Alright, so our team is using Git/LFS/SourceTree for source/version control with Unreal Engine 4 and every time we try to push our binary/tracked files through LFS, they're skipped. Sometimes the push will go through and the files will get through to our server, but as of late they're failing to push and LFS tries to send them over and over to no avail. 

<a href="http://imgur.com/vyZ4QSK"><img src="http://i.imgur.com/vyZ4QSK.png" title="source: imgur.com" /></a>

Git will do this for hours on end and nothing happens. Not sure what to do here as we're all pretty new to git overall, but we definitely need some help.

**Comment by technoweenie** [comment]
If files are skipped, that means Git LFS thinks it needs to upload that file, but the server is saying it already has it. I think the actual issue is that single file is not successfully uploading. Try running with `GIT_TRACE=1`  to see why it's constantly failing.

**Comment by VertXLabs** [comment]
Sorry for the noob questions, but gotta ask them. How exactly do we run that command to see what's going on? Like do we run it before we push the changes in ST or after? Also, do we need to include the url of our remote repo at the end of that command? Like I said, we're extremely new to Git, so we're sort of clueless right now.

**Comment by ttaylorr** [comment]
@VertXLabs no worries! You can run the command in a command prompt running in the directory of your repository, independently of pushing/not pushing inside of SourceTree. The full command would look like this:

```
GIT_TRACE=1 git push origin master
```

there is no need to add the remote's URL to the end of the command.

Let me know if you have any other questions!

**Comment by VertXLabs** [comment]
Alright, here's the log (we had to stop it cause it just kept trying to do its thing): https://gist.github.com/VertXLabs/94860b7576628c7298c6b105ad49c776

I removed the user's authorization credentials, but that's it.

**Comment by VertXLabs** [comment]
Bumping. Anyone have any ideas as to what the issue is?

**Comment by ttaylorr** [comment]
@VertXLabs Thanks for posting that, and sorry for the brief delay, I think I figured out what's going on:

> ```
> Git LFS: (0 of 2 files, 5 skipped) 168.73 MB / 337.56 MB, 5.02 MB skipped      trace git-lfs: tq: retrying object 4018681d394454e02cad6159d308d01c48895af1365de32581266fa7579b0368: LFS: Put https://vertxlabs.visualstudio.com/_git/ColonyStory/info/lfs/objects/4018681d394454e02cad6159d308d01c48895af1365de32581266fa7579b0368: read tcp 192.168.0.18:55179->104.43.203.175:443: i/o timeout
> trace git-lfs: tq: enqueue retry #1 for "4018681d394454e02cad6159d308d01c48895af1365de32581266fa7579b0368" (size: 177029037)
> Git LFS: (0 of 2 files, 5 skipped) 168.73 MB / 337.56 MB, 5.02 MB skipped      trace git-lfs: tq: retrying object 41d4101a936d571cf6f2a0c30b9e70de3bfa47a8131024e7a1bf4f1b6b3fe154: LFS: Put https://vertxlabs.visualstudio.com/_git/ColonyStory/info/lfs/objects/41d4101a936d571cf6f2a0c30b9e70de3bfa47a8131024e7a1bf4f1b6b3fe154: read tcp 192.168.0.18:55181->104.43.203.175:443: i/o timeout
> trace git-lfs: tq: enqueue retry #1 for "41d4101a936d571cf6f2a0c30b9e70de3bfa47a8131024e7a1bf4f1b6b3fe154" (size: 176930255)
> ```

In particular the `i/o timeout` issue. This can be any number of things, but is usually a connectivity issue. If that's the case, try bumping the `lfs.activitytimeout` setting, which will set a longer period of time before closing the connection.

If the remote host is closing it, you'll have to open an issue with them instead 👍 .
