### ISSUE TITLE
customize post-checkout hook

### ISSUE THREAD

**Issue by masics** [git-lfs/git-lfs#2445]
I have added my own commands into the posh-checkout hook and the gti-lfs showing me message:
Hook already exists: post-checkout

#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove thi
s hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"

$(git rev-parse --git-dir)/hooks/post-checkout.py

What I can do to make it happy?

**Comment by technoweenie** [comment]
Hmm, which commands is it showing you the message?  A lot of them, like `track`?

**Comment by masics** [comment]
This particular is for "checkout".

**Comment by technoweenie** [comment]
`git checkout` or `git lfs checkout` ?

**Comment by technoweenie** [comment]
Assuming `git checkout`, because of [this line](https://github.com/git-lfs/git-lfs/blob/dce20b0d18213d720ff2897267e68960d296eb5e/commands/command_smudge.go#L90). The intention is for it to install any hooks that are missing. But it should only visibly complain if they already exist when running something deliberate like `git lfs install` or `git lfs update`. Should be a relatively easy fix. 

Thanks for the report!

**Comment by masics** [comment]
It happens after "git lfs clone" with global hooks installed (lfs is
applied to it already).

Best regards,
Michael Strelnikov

**Comment by mathstuf** [comment]
It'd be nice if LFS could output the hook contents without any "window dressing" so that a simple redirect can at least put it in a path that can be chained to.

**Comment by masics** [comment]
I would prefer LFS will not output anything at all if the hook already has
all lines required.

Best regards,
Michael Strelnikov

**Comment by mathstuf** [comment]
That works if the hook actually contains that content, but if your hook chains off to elsewhere, then the content isn't there. Maybe it should assume the hook is available if `lfs.hooks.$hook_name` is `true` in the config? Then setups which write the LFS hook to a script and then `exec` it in its hook process can set that and not have LFS be unhappy?

**Comment by masics** [comment]
The hook is definitely has the content:

```
Hook already exists: post-checkout

#!/bin/sh

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
git lfs post-checkout "$@"

$(git rev-parse --git-dir)/hooks/post-checkout.py

```

**Comment by masics** [comment]
Any update on this problem?

**Comment by bk2204** [comment]
I think this issue should be resolved in the latest versions of Git LFS.  We do return an error internally if the hook already exists, but we don't display that error to the user unless they've run `git lfs update`, which is as it should be.

Can y'all confirm that this is indeed fixed in the latest version?

**Comment by bk2204** [comment]
Since I haven't heard back, and I've tested that this works as expected on my system, I'm going to close this issue.

**Comment by mathstuf** [comment]
I don't think the chaining hook issue has been addressed, but I also haven't tested it lately.

**Comment by bk2204** [comment]
I believe if you have hooks that are customized, then Git LFS no longer overwrites them unless you run `git lfs update --force`. That's the behavior I saw in testing, at least. If they are missing altogether, then they'll be replaced.

**Comment by mathstuf** [comment]
I don't think the worry was about LFS overwriting the hook, but warning that it can't prove the hooks are installed properly.

**Comment by bk2204** [comment]
Yeah, we don't print that message anymore unless you manually invoke `git lfs update`. The message doesn't occur automatically; we generate it internally, but it isn't printed to the user unless `git lfs update` is invoked.

I tested `git lfs fsck`, which contains a call to validate hooks, and it doesn't print an error message. I haven't seen it affect any other operations, either.

**Comment by mathstuf** [comment]
Thanks, that sounds good to me.
