### ISSUE TITLE
Test suite modifies global git configuration

### ISSUE THREAD

**Issue by mathstuf** [git-lfs/git-lfs#2448]
I was running a test from the `git-lfs` repository for #2447 and it seems that the test suite changes the user, email, and adds various other bits to the global git configuration. These things should be localized with either `-c` to git or using the `GIT_CONFIG` environment variable.

**Comment by technoweenie** [comment]
The scripts modify `HOME`, so it's supposed to be making those changes to a `.gitconfig` file in a temporary dir somewhere in `./test`. Though `GIT_CONFIG` feels like a better solution than changing `HOME`. 

FWIW, I don't see anything weird in my config. I even removed `user.name` and ran the tests to see if the tests would set their own.

**Comment by mathstuf** [comment]
Ah. I set `XDG_CONFIG_HOME` explicitly. That bypasses usage of `HOME`.

**Comment by mathstuf** [comment]
Why was this closed? I don't see a related change committed to the repo.

**Comment by ttaylorr** [comment]
@mathstuf I thought that your comment (https://github.com/git-lfs/git-lfs/issues/2448#issuecomment-318752791) indicated that the issue was resolved when you set `XDG_CONFIG_HOME`.

**Comment by mathstuf** [comment]
I was explaining why it happened, not that it was fixed :) . Setting `XDG_CONFIG_HOME` bypasses the logic of using `HOME` to determine the config file location. That's why the test suite writes to my config file. See the [git code](https://github.com/git/git/blob/b42b0c09199db794b2a34ae9ce293d6711fb6a4f/path.c#L1324-L1337).

Using `GIT_CONFIG` is the proper fix.

**Comment by ttaylorr** [comment]
@mathstuf thanks for explaining. I'll put this on my list 👍 .
