### ISSUE TITLE
something wrong in `git lfs track`

### ISSUE THREAD

**Issue by canyou2014** [git-lfs/git-lfs#2452]
When I link a git repo path to another path, such as:
```
$ ln -s /document/git-repo /home/git/workspace/
```
Then `git lfs track` file in the link path `/home/git/workspace/git-repo/`:
```
$pwd
/home/git/workspace/git-repo
$git lfs track sd.exe
Tracking "sd.exe"
$cat .gitattributes
sd.exe filter=lfs diff=lfs merge=lfs -text
```
When `git lfs track` the file again , it will not show `"sd.exe" already supported`, but always `Tracking "sd.exe"`, such as:
```
$git lfs track sd.exe
Tracking "sd.exe"
$git lfs track sd.exe
Tracking "sd.exe"
...
```

**Comment by ttaylorr** [comment]
Hi @canyou2014, thanks for opening this and sorry that you're having trouble. I think I fixed the issue you pointed out in #2463 (there's some additional details in there about what went wrong, how we fixed it, etc).

I've scheduled that fix to be released in v2.2.2, but if you want to get your hands on it early, here are a few test builds:
