### ISSUE TITLE
TestClosingAnObjectDatabaseMoreThanOnce fails when not run from git repo

### ISSUE THREAD

**Issue by ssgelm** [git-lfs/git-lfs#2456]
When building git-lfs from a tarball, not a git checkout, the TestClosingAnObjectDatabaseMoreThanOnce test fails.  See output below.  I'm also taking a look at this but I wanted to throw it out there in case anyone else has a quick fix.

```
--- FAIL: TestClosingAnObjectDatabaseMoreThanOnce (0.01s)
        Error Trace:    object_db_test.go:206
	Error:		Expected nil, but got: Error in git cat-file --batch: exit status 128 fatal: Not a git repository (or any of the parent directories): .git

FAIL
FAIL	github.com/git-lfs/git-lfs/git/odb	0.056s
```

**Comment by ttaylorr** [comment]
@ssgelm thanks for opening this. I posted a fix in https://github.com/git-lfs/git-lfs/pull/2457.

**Comment by ssgelm** [comment]
See this is why I asked first. :) Thanks!
