### ISSUE TITLE
[Question] ARM Support

### ISSUE THREAD

**Issue by zafields** [git-lfs/git-lfs#2464]
It appears that you don't release a package for ARM. Is this for technical reasons, or is ARM not on your radar? Do you intend to support ARM sometime in the future? Do you already support ARM and I'm just missing it entirely?

**Comment by ttaylorr** [comment]
@zafields thanks for opening this! Great question. LFS can be built to target ARM and ARM64 architecture (see: `GOOS=linux GOARCH=arm64 script/bootstrap`, and https://github.com/git-lfs/git-lfs/pull/2088), but we don't offer official support or distribution of it.

If there's enough demand in the future, I'd be more than happy to distribute those packages in an official capacity.

**Comment by jjehl** [comment]
+1 for demand on arm architecture

**Comment by Surmeh** [comment]
+1 for demand on arm architecture

**Comment by ttaylorr** [comment]
@andyneff what do you think about this?

**Comment by andyneff** [comment]
@ttaylorr I don't actually know a whole lot about arm or have much opinion on the matter.

If its as simple as just calling the distribution scripts with the arm `TARGET_PLATFORM` now, I say go for it!

**Comment by ttaylorr** [comment]
@andyneff it looks a little more complicated than that; I started work in these two places:

- https://github.com/git-lfs/git-lfs/compare/arm-arm64-distributions
- https://github.com/git-lfs/build-dockers/compare/arm-arm64-distributions

I don't have time to finish this right now, so someone else is more than welcome to take a look. Otherwise, I will try and look at this myself before the next release, which would be v2.5.0.

**Comment by MarekPetr** [comment]
Hi @ttaylorr, have you tried running git-lfs on android's arm? I am developing an app using Termux's git-lfs but I can not make ot track files.

**Comment by bk2204** [comment]
Hey,

Is your question about whether the binary can be compiled or, having compiled it, how to get it to work?  If it's the latter, I think it would probably be better to open a new issue using the template so we can track down what's going wrong.

I don't believe any of the core team use Git LFS on Android ourselves, but we're happy to try to help you figure things out.

**Comment by MarekPetr** [comment]
Thanks for a quick answer. That would be awesome, I can totally open an issue :)
