### ISSUE TITLE
git lfs usage doesn't fail if git lfs hasn't been installed

### ISSUE THREAD

**Issue by ncanning** [git-lfs/git-lfs#2472]
`git lfs pull` will sort of work even if you haven't run `git lfs install`, leading to some confusing behavior. Specifically, it will pull, but the changes will show up as staged changes in your usual git repo.

Instead, running any lfs commands prior to running `git lfs install` should print some sort of warning, telling you that you need to install it first.

**Comment by ttaylorr** [comment]
Good idea; I'll milestone this for the next version. In addition, I'd be more than happy to help someone else through a PR.
