### ISSUE TITLE
Cannot push lfs to GitHub. Getting connection refused.

### ISSUE THREAD

**Issue by deonblaauw** [git-lfs/git-lfs#2474]
**I am getting the following message when pushing to github:**

`dial tcp: lookup lfs.github.com on 127.0.1.1:53: read udp 127.0.0.1:54833->127.0.1.1:53: read: connection refused
`

I'm using lfs v2.2.1. I was using v1.5.5 earlier, thought I should use the latest just in case but no luck.

I also tried setting my remote url to https (was using ssh), but also no luck.

**This is my environment:**

git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.3; git 621d1f82)
git version 2.11.0

Endpoint=https://github.com/Aerovinci/Test_Data.git/info/lfs (auth=none)
  SSH=git@github.com:Aerovinci/Test_Data.git
LocalWorkingDir=/home/deon/Github/Test_Data
LocalGitDir=/home/deon/Github/Test_Data/.git
LocalGitStorageDir=/home/deon/Github/Test_Data/.git
LocalMediaDir=/home/deon/Github/Test_Data/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/deon/Github/Test_Data/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**I deleted the repo, and tried a fresh checkout, then I got this:**

batch response: Post https://lfs.github.com/Aerovinci/Test_Data/objects/batch: dial tcp: lookup lfs.github.com on 127.0.1.1:53: read udp 127.0.0.1:52587->127.0.1.1:53: read: connection refused

Errors logged to /home/deon/Github/Test_Data/.git/lfs/objects/logs/20170803T143526.150136648.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: logs/2016-09-28-003 INDI in the garden/log001.csv: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Running the 'git lfs logs last' command gives**

git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.3; git 621d1f82)
git version 2.11.0

$ git-lfs filter-process
Error downloading object: logs/2016-09-28-003 INDI in the garden/log001.csv (049040d): Smudge error: Error downloading logs/2016-09-28-003 INDI in the garden/log001.csv (049040da8201598e38b7f32f2dc39458e452b4ea6ce75ca96e8f840e7225469f): batch response: Post https://lfs.github.com/Aerovinci/Test_Data/objects/batch: dial tcp: lookup lfs.github.com on 127.0.1.1:53: read udp 127.0.0.1:52587->127.0.1.1:53: read: connection refused

Post https://lfs.github.com/Aerovinci/Test_Data/objects/batch: dial tcp: lookup lfs.github.com on 127.0.1.1:53: read udp 127.0.0.1:52587->127.0.1.1:53: read: connection refused
github.com/git-lfs/git-lfs/errors.newWrappedError
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:170: batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:170: Error downloading logs/2016-09-28-003 INDI in the garden/log001.csv (049040da8201598e38b7f32f2dc39458e452b4ea6ce75ca96e8f840e7225469f)
github.com/git-lfs/git-lfs/errors.newWrappedError
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/errors/types.go:170: Smudge error

ENV:
LocalWorkingDir=/home/deon/Github/Test_Data
LocalGitDir=/home/deon/Github/Test_Data/.git
LocalGitStorageDir=/home/deon/Github/Test_Data/.git
LocalMediaDir=/home/deon/Github/Test_Data/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/deon/Github/Test_Data/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git

**Can anyone help me?**

**Comment by ttaylorr** [comment]
Hi @deonblaauw, thanks for opening this issue and sorry that you're having trouble. It looks like there were some intermittent network issues around the time that you opened this issue. Can you try again, and reopen the issue if you have trouble?

**Comment by deonblaauw** [comment]
Hi @ttaylorr , I tried all day yesterday, tried again this morning, still does not work. Regarding the local DNS issue you mentioned, how can I resolve it?

**Comment by ttaylorr** [comment]
> Regarding the local DNS issue you mentioned, how can I resolve it?

I would recommend using a DNS server other than your ISP's, like Google's `8.8.8.8`. Beyond that, I would recommend you contact your ISP.
