### ISSUE TITLE
lfs fetch ignores valid credentials embedded in lfsurl when access type is unset

### ISSUE THREAD

**Issue by chrisvanderpennen** [git-lfs/git-lfs#2478]
git-lfs version 2.2.1
git 2.12.0.windows.1
windows server 2016

TFS 2017's on-premise build agent provides temporary credentials to git-lfs by embedding them in the URLs `remote.origin.lfsurl` and `remote.origin.lfspushurl`.

Instead of cloning, TFS's build agent: 
* initialises a local repository
* sets remote urls and LFS urls, embedding a token in the LFS url password
* runs `git fetch`
* runs `git lfs fetch origin revisionhashgoeshere`

When `git lfs fetch` runs, it appears to be ignoring the credentials embedded in `lfsurl`.  Instead it seems to detect that NTLM auth is needed, then failing because it can't prompt for credentials.

After this fails, `.git/config` contains the following:
```
[lfs "http://server.domain.local:8080/tfs/path/to/_git/repo.git/info/lfs"]
	access = ntlm
```
Changing access to basic and re-running the build, which provisions new credentials in the same manner, succeeds as expected.

Logs: (urls changed to protect the guilty)
```
##[command]git version
git version 2.12.0.windows.1
##[command]git init "E:\agent-1\_work\24\s"
Initialized empty Git repository in E:/agent-1/_work/24/s/.git/
##[command]git remote add origin http://server.domain.local:8080/tfs/path/to/_git/repo
##[command]git config gc.auto 0
##[command]git config --get-all http.http://server.domain.local:8080/tfs/path/to/_git/repo.extraheader
##[command]git config --get-all http.proxy
##[command]git lfs version
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
##[command]git lfs install --local
Updated git hooks.
Git LFS initialized.
##[command]git config remote.origin.lfsurl http://OAuth:********@server.domain.local:8080/tfs/path/to/_git/repo.git/info/lfs
##[command]git config remote.origin.lfspushurl http://OAuth:********@server.domain.local:8080/tfs/path/to/_git/repo.git/info/lfs
##[command]git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
remote: 
remote:                    fTfs           
remote:                  fSSSSSSSs        
remote:                fSSSSSSSSSS        
remote: TSSf         fSSSSSSSSSSSS        
remote: SSSSSF     fSSSSSSST SSSSS        
remote: SSfSSSSSsfSSSSSSSt   SSSSS        
remote: SS  tSSSSSSSSSs      SSSSS        
remote: SS   fSSSSSSST       SSSSS        
remote: SS fSSSSSFSSSSSSf    SSSSS        
remote: SSSSSST    FSSSSSSFt SSSSS        
remote: SSSSt        FSSSSSSSSSSSS        
remote:                FSSSSSSSSSS        
remote:                  FSSSSSSs        
remote:                    FSFs    (TM)        
remote: 
remote:  Microsoft (R) Visual Studio (R) Team Foundation Server        
remote: 
From http://server.domain.local:8080/tfs/path/to/_git/repo
 * [new branch]      develop    -> origin/develop
 * [new branch]      master     -> origin/master
##[command]git lfs fetch origin 4574e01e2bb1a4649a434064940486c2ae03f655
Fetching 4574e01e2bb1a4649a434064940486c2ae03f655

Git LFS: (0 of 6 files) 0 B / 212.94 MB                                        
Git LFS: (0 of 6 files) 0 B / 212.94 MB                                        
Git LFS: (0 of 6 files) 0 B / 212.94 MB                                        
batch response: Git credentials for http://OAuth:********@server.domain.local:8080/tfs/path/to/_git/repo.git/info/lfs not found:
Git LFS: (0 of 6 files) 0 B / 212.94 MB                                        
Change the GIT_TERMINAL_PROMPT env var to be prompted to enter your credentials for http://server.domain.local:8080.
Git LFS: (0 of 6 files) 0 B / 212.94 MB                                        
error: failed to fetch some objects from 'http://OAuth:********@server.domain.local:8080/tfs/path/to/_git/repo.git/info/lfs'
##[command]git lfs logs last
No logs to show
##[error]Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.
```

**Comment by ttaylorr** [comment]
Hi @chrisvanderpennen, thanks for this. I was wondering if you could clarify:

> When `git lfs fetch` runs, it appears to be ignoring the credentials embedded in `lfsurl`. Instead it seems to detect that NTLM auth is needed, then failing because it can't prompt for credentials.

Is the issue that LFS can't prompt for credentials, or that it doesn't fallback to basic auth and retry the request?

**Comment by chrisvanderpennen** [comment]
Hey @ttaylorr, thanks for getting back.

The issue is that it isn't falling back to basic authentication with the embedded credentials.  I'm not sure if it's attempting authentication at all, but I haven't had a chance to run it through Fiddler yet.  Let me know if that'd be helpful.

**Comment by YawJatah** [comment]
@chrisvanderpennen ,
I am also having the same issue with my on premise TFS 2017 and a build agent.
Setting the access = basic, doesn't seem to work for me.
I had setup the agent to use PAT, and i think that causes a problem with git lfs.
The only way i got it to work, was to setup the agent to use Negotiate, and used the local account to run it as the service. 
I am beginning to suspect that running the agent as a Network Service might be the root of the problem. 
Running the service with local user worked for me (had to run git lfs once on the local machine to save the credentials to the credentials manager).

I am still learning about git and git-lfs, so my assumption might be wrong, but the method described above is how i got my build agent to work with Team Foundation Server 2017.

FYI: my setup is
Windows 10 Enterprise
git version 2.13.3.windows.1
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)

**Comment by ttaylorr** [comment]
> but I haven't had a chance to run it through Fiddler yet. Let me know if that'd be helpful.

@chrisvanderpennen I think that this would be helpful, since it appears that @YawJatah has gotten this to work.

**Comment by chrisvanderpennen** [comment]
Git-lfs is properly passing the embedded credentials to info/lfs/objects/batch. TFS is sending `LFS-Authenticate: NTLM` in response.

Closing, sorry for the trouble.

**Comment by chrisvanderpennen** [comment]
One last update: I can confirm @YawJatah's workaround, running the agent service as an AD account and storing credentials in the git credential store, works - as long as you set `credential.helper` in global and not system.
