### ISSUE TITLE
Can't push to GitHub due to large file constraint with googlemaps file.

### ISSUE THREAD

**Issue by jlbaxter** [git-lfs/git-lfs#2482]
I'm trying to push an Xcode project to a fresh GitHub repository master branch for the first time. I've tried all of these recommendations and nothing's worked. The offending large files are two googlemaps files each 123MB in size. I got git lfs to add one of the files once, but it skipped the other. Now it skips both every time I try. It doesn't matter if I start over in the branch, backup, re-add, track, commit and push...it always skips and errors out. Any recommendations would be appreciated. Thanks!

Here's what I get when I try to push. I've gone through all the other forums and have tried everything recommended that I've read so far. If you have a recommended step, I've probably done it. 

```
Jims-MacBook-Pro:pintip Jim$ git push -u origin master
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 123.08 MB skipped                                                                                                                     Counting objects: 1441, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1280/1280), done.
Writing objects: 100% (1441/1441), 75.53 MiB | 1.24 MiB/s, done.
Total 1441 (delta 472), reused 0 (delta 0)
remote: Resolving deltas: 100% (472/472), done.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: acc3634bb74e4c2efeb912c08a8e8b48
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps is 123.08 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/pintip/pintip.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/pintip/pintip.git'
```

**Comment by jlbaxter** [comment]
Another thing to add is that the Github repository that I'm trying to push to has still never had one file added to it. It is brand new. Not sure if that makes a difference. I'm new to this so bare with me.

**Comment by ttaylorr** [comment]
Hi @jlbaxter, thanks for opening this issue and sorry that you're having trouble. It looks like there are some large files accidentally hanging around in your repository, in particular:

- `Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps`


> ```
> remote: Resolving deltas: 100% (472/472), done.
> remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> remote: error: Trace: acc3634bb74e4c2efeb912c08a8e8b48
> remote: error: See http://git.io/iEPt8g for more information.
> remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps is 123.08 MB; this exceeds GitHub's file size limit of 100.00 MB
> ```

Can you run

```bash
git lfs migrate import --include="Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps"
```

and try your push again?

**Comment by jlbaxter** [comment]
@ttaylorr thanks for the response. It still didn't go. Here's what I got:

Jims-MacBook-Pro:pintip Jim$ git lfs migrate import --include="Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps"
migrate: Sorting commits: ..., done                                                                                                                                                  
migrate: Rewriting commits: 100% (14/14), done                                                                                                                                       
  master	42752b6abb2a8ba2347a2e300532da6511e2b402 -> 4457cdfb5dd9a4eecddf6675d5dbf7c6eec735e4
migrate: Updating refs: ..., done                                                                                                                                                    
Jims-MacBook-Pro:pintip Jim$ git push -u origin master
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 123.08 MB skipped                                                                                                                     Counting objects: 1442, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1281/1281), done.
Writing objects: 100% (1442/1442), 75.53 MiB | 1.24 MiB/s, done.
Total 1442 (delta 473), reused 0 (delta 0)
remote: Resolving deltas: 100% (473/473), done.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: b86b8906dcc9cea93584324a9d38247e
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps is 123.08 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/pintip/pintip.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/pintip/pintip.git'
Jims-MacBook-Pro:pintip Jim$

**Comment by ttaylorr** [comment]
@jlbaxter thanks for sharing the error! You pointed out a bug in the way that the `git lfs migrate` command processes subdirectories. I posted a fix in https://github.com/git-lfs/git-lfs/pull/2485, which I've scheduled for the next release. 

I'd love for you to give it a whirl and see if you're able to migrate your repository after running the same command.

Here are the binaries:

[git-lfs-darwin-386-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1209468/git-lfs-darwin-386-2.3.0-pre.tar.gz)
[git-lfs-darwin-amd64-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1209469/git-lfs-darwin-amd64-2.3.0-pre.tar.gz)

**Comment by jlbaxter** [comment]
Thanks @ttaylorr ! I'll give it a whirl later this evening and let you know how it goes.

**Comment by JaredSartin** [comment]
I just did a migrate with 2.3.0-pre. It didn't seem to work:
```
Git LFS: (0 of 5 files, 150 skipped) 0 B / 191.50 KB, 1.52 GB skipped
LFS upload missing objects:
  (missing) Assets/Demigiant/DOTween/Editor/DOTweenEditor.dll (598c29c34abcc540e099644a337e44bcc8e20d82f1555fa12f110caa371911cf)
  (missing) Assets/Demigiant/DOTween/DOTween46.dll (ff11015d10c3e70d2fd1a77e976b8096860e66e34db5b9880373854068adb32b)
  (missing) Assets/Demigiant/DOTween/DOTween43.dll (a14e8d58c9efe457fe35e141b427b4939721ee47d2ad21d9b5df3e0fff10cf41)
  (missing) Assets/Demigiant/DOTween/DOTween50.dll (e35f31b12baf001b29c87b9c09ac91a025a0f7327e14fe99c8358ec60377d938)
  (missing) Assets/Demigiant/DOTween/DOTween.dll (9a6c4f9011a5abff678764118c8421f212f6b6fd53a797646a3b0847156630cf)
Counting objects: 10231, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10223/10223), done.
Writing objects: 100% (10231/10231), 1.60 GiB | 1.61 MiB/s, done.
Total 10231 (delta 6485), reused 0 (delta 0)
remote: Resolving deltas: 100% (6485/6485), completed with 940 local objects.
remote: warning: File Assets/Models/Rock_Granite_3/Aset_rock_granite_M_qlEdX_High.FBX is 57.18 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/HDRI/sunset_dark.psd is 82.53 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Mega-Fiers/Modifiers/ReflectionProbe-0.exr is 60.52 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Mega-Fiers/Modifiers/ReflectionProbe-1.exr is 60.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Models/Rock_Granite_1/Aset_rock_granite_M_qktcj_High.fbx is 58.14 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Models/Rock_Granite_2/Aset_rock_granite_M_qkwvs_High.fbx is 58.64 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Models/UnderWaterCliff/Aset_rock_volcanic_X_qkbtz_High.fbx is 53.95 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 40cf80f18a71578843212290ec80d1eb
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Assets/HDRI/sunset 1.psd is 184.10 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Assets/HDRI/sunset.psd is 323.89 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Assets/Models/Materials/lotus_foilage.psd is 131.11 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Assets/Models/Lotus/lotus_VRayFastSSS21_Emi.psd is 205.19 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Assets/HDRI/sunset 1.psd is 125.18 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Assets/HDRI/sunset_dark 1.psd is 143.12 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/xxxxx/xxxx-xxx.git
 ! [remote rejected] lfs-mig -> lfs-mig (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/xxxxx/xxxx-xxx.git'
```

before my push, I ran these in the git repo:
```
~/Downloads/git-lfs-2.3.0-pre/git-lfs migrate info --above=30mb --include="*.apk"
~/Downloads/git-lfs-2.3.0-pre/git-lfs migrate info --above=30mb --include="*.psd"
~/Downloads/git-lfs-2.3.0-pre/git-lfs migrate info --above=30mb --include="*.exr"
~/Downloads/git-lfs-2.3.0-pre/git-lfs migrate info --above=30mb --include="*.fbs"
```

each resulting in feedback like:
```
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (3/3), done
*.psd	1.6 GB	9/104 files(s)	9%
```

**Comment by ttaylorr** [comment]
Hi @JaredSartin, thanks for opening this issue. You may be looking to run `git lfs migrate import`, which is what rewrites history in your repository. Can you give that a whirl and let me know if you run into issues?

**Comment by JaredSartin** [comment]
@ttaylorr Doesn't work on stable - does work on 2.3.0-pre. Cheers

**Comment by venkat8a** [comment]
Please refer below link for Repository upload limit in github Enterprises
https://help.github.com/en/enterprise/2.18/admin/installation/setting-git-push-limits
