### ISSUE TITLE
git lfs fails to push/pull when files are stored in artifactory

### ISSUE THREAD

**Issue by Vidhu115** [git-lfs/git-lfs#2484]
Hi,
We are using the following version of git lfs in windows 
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)

Our git server (Stash- 3.11.6) and Artifactory server (4.5.1) are Redhat servers.

When we try to pull lfs files from Artifactory,the following errors are reported.
The issue is that, git lfs doesn't prompt for a username/password for artifactory. I have tried using different credential managers. But nothing helped!

The current .lfsconfig is as this,

[lfs]
   url = "https://xxxx/artifactory/api/lfs/xxx"

But the whole thing works, if I change .lfsconfig this way,
[lfs]
   url = "https://username:password@xxxx/artifactory/api/lfs/xxx"

But this is not acceptable.

$ GIT_TRACE=1 git lfs pull
17:44:26.203229 git.c:558               trace: exec: 'git-lfs' 'pull'
17:44:26.203229 run-command.c:347       trace: run_command: 'git-lfs' 'pull'
trace git-lfs: run_command: 'git' config -l -f C:\Users\xxxx\Desktop\GITREPOS\test_repo\.lfsconfig
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config branch.master.remote
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: run_command: git ls-tree -r -l -z --full-tree e7f5db7714c94fe957ba47f6ae1ece68b8ee77f7
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: fetch Applicable documents.doc [8fd69707900a49d5e5367c1fc0edba1b44f43771fc957d4cf61edc227597d81d]
trace git-lfs: fetch bitmap.doc [1f1ee7ae26faab158fc72994d096c31cb7258250072f1f446d4b3bc71f62a921]
trace git-lfs: fetch second-lfs.doc [777b428c6aeb6c012ae167a6a8d18642b5b59a1d9fb6726e215f0bc2da79318b]
trace git-lfs: fetch test.doc [25f11c9e99d2b6486dd72a7ea97390603821c83e6e797d8133846974b97bf2a3]
trace git-lfs: tq: sending batch of size 4
Git LFS: (0 of 4 files) 0 B / 26.90 KB                                         trace git-lfs: api: batch 4 files
trace git-lfs: creds: git credential fill ("https", "xxxxl", "artifactory/api/lfs/xxx")
trace git-lfs: api error: Git credentials for https://xxx/artifactory/api/lfs/xxx not found.
Git LFS: (0 of 4 files) 0 B / 26.90 KB
batch response: Git credentials for https://xxx/artifactory/api/lfs/xxx not found.
error: failed to fetch some objects from 'https://xxx/artifactory/api/lfs/xxx'

Is there a different way to resolve this issue?

**Comment by ttaylorr** [comment]
Hi @Vidhu115 -- thanks for opening this issue and sorry that you're having trouble. I think this is related to https://github.com/git-lfs/git-lfs/issues/2349 and https://github.com/git-for-windows/git/issues/1192, so I'm going to close this issue for now and move discussion there.

As in the meantime, I don't know of any other work-arounds beyond storing your credentials the way you suggested. I know this isn't work-able, but I am hopeful that we will get the underlying issue resolved quickly.
