### ISSUE TITLE
Only a few hardcoded settings in .lfsconfig are considered, others are ignored

### ISSUE THREAD

**Issue by aleb** [git-lfs/git-lfs#2490]
At the end of [`config/git_fetcher.go`](https://github.com/git-lfs/git-lfs/blob/master/config/git_fetcher.go) there is a list of `safeKeys` which determine what can be read from `.lfsconfig`:
```
var safeKeys = []string{
	"lfs.fetchexclude",
	"lfs.fetchinclude",
	"lfs.gitprotocol",
	"lfs.pushurl",
	"lfs.url",
}
```

It might be useful to:
- print a warning when a setting is ignored, and 
- update [`docs/man/git-lfs-config.5.ronn`](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn) to specify what "safe keys" can be used in `.lfsconfig`.

**Comment by aleb** [comment]
Some repositories have a custom storage server used through a standalone custom-transfer agent. For cases like this it would be useful to be able to have something like this in the `.lfsconfig` file of the repo:
```
[lfs]
	concurrenttransfers = 8
	standalonetransferagent = rsync
[lfs "customtransfer.rsync"]
	args = SERVER:/LFS-PATH/REPO-NAME
	path = git-lfs-rsync-agent
	concurrent = true
```
Would it be ok to relax the rules to allow these in `.lfsconfig`?

**Comment by ttaylorr** [comment]
> Would it be ok to relax the rules to allow these in `.lfsconfig`?

I think I'd prefer not to relax the rules for this use case, since I believe this allows arbitrary programs to be run, correct?

**Comment by JungStar** [comment]
I have a similar request to the one above (Please let me know if I should open a new issue instead).
While I agree some settings are not save, there are others that are but are disabled.
Namely, the remaining fetch settings:
```
lfs.fetchrecentrefsdays
lfs.fetchrecentremoterefs
lfs.fetchrecentcommitsdays
lfs.fetchrecentalways
```
Are there any arguments against adding those to the safe key list?

**Comment by bk2204** [comment]
In general, we prefer people to open new issues rather than following up to closed issues, but I'll respond here.  I don't think these settings are generally applicable to all users of a given repository and are more of per-user settings, so I don't think it makes sense to set them in the repository.

**Comment by JungStar** [comment]
Thanks for the quick reply. I have open issue #4111 and briefly explained our use-case.
