### ISSUE TITLE
"git lfs unlock" does not reset the readonly file system attribute.

### ISSUE THREAD

**Issue by mrbobbybobberson** [git-lfs/git-lfs#2494]
When we check out files that are marked as lfs lockable in .gitattributes, the readonly file system attribute is set.  When we "git lfs lock" the file, the readonly attribute is unset as expected.  But when we "git lfs unlock" a file that was previously locked, its readonly attribute is not set again, which leaves the file writeable (and robs us of the helpful reminder which files should be locked before edit).

I'm on Windows 10 Version 1703 and using git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82).

**Comment by ttaylorr** [comment]
@mrbobbybobberson thanks for opening this issue, it looks like this is having to do with the flag that controls setting files read/write-able not being set anywhere. I fixed that in https://github.com/git-lfs/git-lfs/pull/2514, and have scheduled it for the next release.

**Comment by mrbobbybobberson** [comment]
Thanks, @ttaylorr !  I'll watch for it in the next release.
