### ISSUE TITLE
git lfs lock commands don't respect core.ignorecase=true

### ISSUE THREAD

**Issue by mrbobbybobberson** [git-lfs/git-lfs#2496]
I'm running on a Windows box, and I have core.ignorecase=true set in my git config, but the git lfs lock commands still seem to be case sensitive.

If someone has a lock to someFolder/someFile.txt, I can still take a lock on someFolder/SOMEfile.txt.  If I "git mv lockableFile.txt LOCKABLEfile.txt", I can commit it and push it even if someone has a lock on "lockableFile.txt".

Any idea how feasible it would be to support case-insensitivity?  Thanks!

I'm on Windows 10 Version 1703 and using git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f8).

**Comment by ttaylorr** [comment]
Hi @mrbobbybobberson thanks for opening this issue. I think it raises some interesting questions: should lock paths be case insensitive? If so, should this be configurable by `core.ignorecase`, or should it be guaranteed by the locking API?

My thoughts are this:

Consider user A working on a case sensitive file system, and user B working on a case insensitive file system. User B holds a lock on `big.psd`, and is working on it. If User A executes `git mv big.psd BIG.psd`, User B will be able to pull those changes (so long as User A generated no diff), but at the same time, lose the lock.

I think that this is essentially the situation you have described above. So: what does a proper guarantee look like? We need to protect case sensitive filesystems from case renames on case insensitive filesystems. One way to do this would be to assume the worse, and teach the LFS locking API to ignore case.

Another approach would be to process `git mv`'s as they arrive on Git hosts, and update the lock path.

A third approach would be to not allow this change via the pre-commit hook by doing a case insensitive query against the locking API.

@rubyist @mrbobbybobberson I'm curious what you think the most sensible approach is going forward.

**Comment by mrbobbybobberson** [comment]
That's a tough one.  On principle, I wouldn't want to force every project that uses locking to ignore case.  Is there a concept of options the LFS server or git remote can communicate down to the clients?  If so, that would let all LFS clients locking files against a particular remote know whether or not to ignore case.

On a related note, anyone know what happens when someone on a case-preserving but case-insensitive OS like Windows tries to check out a git commit that has two files with different case, but otherwise identical paths?

**Comment by ttaylorr** [comment]
> Is there a concept of options the LFS server or git remote can communicate down to the clients?

Not currently, and I think I'd like to avoid adding that to the protocol if we don't have to. LFS should offer a consistent experience across different remotes.

@rubyist what do you think?

**Comment by rubyist** [comment]
If a repo has files `foo` and `Foo` on a system where those are different files (e.g. Linux), and you clone that to a system where those are the same file (e.g. OSX) you'll end up with only one file and it will be marked as changed. Git knows about both files, but only one can exist on that file system.

```
$ git clone ssh://black.local:/home/scott/foo
Cloning into 'foo'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (4/4), done.


$ cd foo


$ ls
foo


$ git ls-files
Foo
foo


$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Foo

no changes added to commit (use "git add" and/or "git commit -a")
```

I'm not sure that providing an ignore case option to the locking API would solve the problem. If in that repo you send e.g. `lock:Foo, ignore:true` - which file do you mean?

**Comment by ttaylorr** [comment]
@rubyist very interesting; I think that this example above hints at the actual problem itself: can we support repositories with case-sensitive tree entries? I don't think we can, since locking the file `foo` with files `foo` and `Foo` in a repository on a case-insensitive filesystem is ambiguous.

I think we could do one of two things:

1. Introduce a flow such that in the above situation, the lock server sends back a list of files that match the case-insensitive path (i.e., for "foo", get "foo", "Foo", "foO") and have the client pick the one they want locked.
2. Have the locking server behave as if all filesystems are case sensitive, and disallow the above case.

What do you think, @rubyist?

**Comment by rubyist** [comment]
I think, similar to the issue we had early on with the client sending `\` as a path separator, we have to trust that the client is sending what it means. If a client is on a a system with a case insensitive file system it should resolve the file and path to what is actually on disk. This is probably just a `stat` call or something, but might need to operate on each path segment as well as the name. This should be possible without user interaction.

On a case sensitive file system, the client will already prevent you from locking `FoO` when only `Foo` exists:

```
$ ls
foo  Foo
[scott@black foo]$ git lfs lock FoO
stat /home/scott/foo/FoO: no such file or directory
```

Here, if you lock `Foo` we trust that you meant `Foo` and not `foo`.

In cases where you've got both `foo` and `Foo` and are sharing it on case insensitive file systems, locking isn't the first or biggest problem you're going to hit.

**Comment by ttaylorr** [comment]
> Here, if you lock `Foo` we trust that you meant `Foo` and not `foo`.
> 
> In cases where you've got both `foo` and `Foo` and are sharing it on case insensitive file systems, locking isn't the first or biggest problem you're going to hit.

Agreed, I don't think there is much we can do here.

**Comment by mrbobbybobberson** [comment]
> In cases where you've got both foo and Foo and are sharing it on case insensitive file systems, locking isn't the first or biggest problem you're going to hit.

Yeah, after that discussion, I agree with you both that trying to support core.ignorecase isn't worth the effort.

But, there are a few rough edges that could be polished out by either enforcing casing on the lock command or by normalizing casing on the lock/unlock commands to what git thinks the casing should be.

Here's what I'm observing on Windows (but I'd guess it's the same on any case-preserving, case-insensitive system):

1. Create new file "Foo", commit, and push it.
2. Type "git lfs lock foo" and you're granted a lock on path "foo".
3. Type "git lfs unlock f<tab>" which tab-completes to "git lfs unlock Foo", and it says "no matching locks found".
4. Type "git lfs lock Foo" and you're granted a lock on path "Foo".

So I think if step 2 checked with git, determined that there's exactly one file that could case-insensitively match "foo", and that was "Foo", and took that as the lock path, that would make things smoother.  The unlock command would have to have the same logic.  But come to think of it, perhaps this normalization logic would only kick in if "core.ignorecase" were set.

Or alternatively, if step 2 said it couldn't find a file "foo", that would be OK, too.  We just gotta make sure that two people can't successfully take two differently-cased locks on the same file and both think they're safe to edit it.

@ttaylorr @rubyist , what do you think?

**Comment by ttaylorr** [comment]
> Here's what I'm observing on Windows (but I'd guess it's the same on any
> case-preserving, case-insensitive system):
>
> 1. Create new file "Foo", commit, and push it.
> 2. Type "git lfs lock foo" and you're granted a lock on path "foo".
> 3. Type "git lfs unlock f<tab>" which tab-completes to "git lfs unlock Foo",
>    and it says "no matching locks found".
> 4. Type "git lfs lock Foo" and you're granted a lock on path "Foo".
>
> So I think if step 2 checked with git, determined that there's exactly one
> file that could case-insensitively match "foo", and that was "Foo", and took
> that as the lock path, that would make things smoother.  The unlock command
> would have to have the same logic.  But come to think of it, perhaps this
> normalization logic would only kick in if "core.ignorecase" were set.

This seems like a good approach to me. I'll file it for the list of things that
I want to get done in the 2.4.0 series.
