### ISSUE TITLE
Files marked as "lockable" but not tracked in lfs don't get their readonly file system attribute set.

### ISSUE THREAD

**Issue by mrbobbybobberson** [git-lfs/git-lfs#2497]
In https://github.com/git-lfs/git-lfs/wiki/File-Locking, it says:

> Once file patterns in .gitattributes are lockable, Git LFS will make them readonly on the local file system automatically. This prevents users from accidentally editing a file without locking it first.

But I'm not getting the readonly file system attribute set.  Is it working for others?

I'm on Windows 10 Version 1703 and using git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f8).

**Comment by mrbobbybobberson** [comment]
Something else that's interesting: the "git lfs lock" command works with any path to a file that exists on disk regardless of whether it's marked as lockable in my .gitattributes.  Is that by design?

**Comment by ttaylorr** [comment]
Hi @mrbobbybobberson, thanks for opening this issue. Could you post the steps that you took in order to observe a file that was not marked as read-only? Specifically, I'm looking for something similar to [this](https://github.com/git-lfs/git-lfs/blob/211e8862901a758f9271d411a8d5cc224c9e0746/test/test-track.sh#L427) test case that would indicate the behavior of `git lfs track` or the post-checkout, post-commit (et. al.) hooks would be broken.

**Comment by mrbobbybobberson** [comment]
Sure thing, @ttaylorr . These steps reproduce the issue for me:

1. Manually add the line "*.hardToMergeFile lockable" to your root .gitattributes file, commit, and push the change.
2. Add a new file named "some.hardToMergeFile", commit, and push the change.
3. Check the readonly attribute on "some.hardToMergeFile" in your file system.

At this point, my system shows the file as writeable, but I expected it to be readonly, as [the wiki](https://github.com/git-lfs/git-lfs/wiki/File-Locking) says:

> If you'd like to register a file type as lockable, without using LFS, you can edit the .gitattributes file directly:

> `*.yml lockable`

> Once file patterns in .gitattributes are lockable, Git LFS will make them readonly on the local file system automatically. This prevents users from accidentally editing a file without locking it first.

**Comment by ttaylorr** [comment]
@mrbobbybobberson ⚡️ thanks for pointing this out: you're totally right. I took a stab at fixing this in https://github.com/git-lfs/git-lfs/pull/2528, which I have scheduled to be included in the next release./

**Comment by ysakai2** [comment]
@ttaylorr Has this been fixed? I'm still having trouble getting the files as read-only. (git lfs version: GitHub; linux amd64; go 1.8.3; git d2f6752)

**Comment by ttaylorr** [comment]
@ysakai2 yes, it has been fixed. Can you open a new issue with a set of steps that allows you to reproduce the issue, if you are still having trouble?

**Comment by OneLineTwoBugs** [comment]
I seem to still have this issue with git-lfs 2.7.1
