### ISSUE TITLE
Will there be a `git lfs diff` command?

### ISSUE THREAD

**Issue by canyou2014** [git-lfs/git-lfs#2498]
Hi.
Now it is not convenient to see the changes  between two different versions of Git-LFS object. 
Will there be a command to show the changes?

**Comment by ttaylorr** [comment]
Hi @canyou2014, thanks for opening this, and great question! I don't think that we'll be adding support for a `git diff`-like command, since I don't think that displaying changes in large blobs of binary data will be useful in the majority of cases.

That being said, I think that adding support for difftools would be a good idea. For more, see: https://git-scm.com/docs/git-difftool.

**Comment by canyou2014** [comment]
@ttaylorr .Thanks for your advice. I have this question because I use `git-lfs` managing **large files** but not only binary files : )

**Comment by mingpen** [comment]
Hi @canyou2014   
Do you have a good solution for the diff of not binary & but large files?  
I'm trying to find

**Comment by naamchan** [comment]
@mingpen I can think of Unity's Prefab or Scene which is yml file but large enough to add to lfs.

**Comment by mitar** [comment]
I would also love diff of large text files (CSV anyone)?

**Comment by gary-cowell** [comment]
Same. Multi hundred MB of CSV data in git lfs file, one line changed, can't see which one easily.

The smaller CSVs are not under lfs, and diffs can be seen.

**Comment by ferretnt** [comment]
Between this thread (and the various other top google hits for "git lfs diff") our git-lfs migration experiment died on the lack of diff support. AAA game team leads spend an awful lot of time hunting diffs of binary files. We can't work without this.

**Comment by ttaylorr** [comment]
Hi, all. I don't think that there has been any change in direction regarding adding a 'git lfs diff' command (or similar) to the Git LFS project. That said, here's a script that some of you may find helpful: it takes three (3) arguments, two revisions and one filename and invokes `diff(1)` on their contents:

```bash
oid_to_path() {
  local oid="$1"
  local dir="$(git lfs env | grep LocalMediaDir | cut -d '=' -f 2)"

  echo "$dir/${oid:0:2}/${oid:2:2}/$oid"
}

rev1="$(git rev-parse "$1")"
rev2="$(git rev-parse "$2")"
fname="$3"

oid1="$(git cat-file -p "$rev1":"$fname" | grep oid | cut -d ':' -f 2)"
oid2="$(git cat-file -p "$rev2":"$fname" | grep oid | cut -d ':' -f 2)"

path1="$(oid_to_path "$oid1")"
path2="$(oid_to_path "$oid2")"

diff -U "$path1" "$path2"
```

**Comment by sonnybae** [comment]
From [this post by bk2204](https://github.com/git-lfs/git-lfs/issues/440#issuecomment-501007460) in related issue #440:

> Another option if you want to have diffs is to run `git config diff.lfs.textconv cat`, which will have any files with the `diff=lfs` attribute automatically rendered through Git to show the LFS file instead of the pointer.

**Comment by mitar** [comment]
It looks like `git config diff.lfs.textconv cat` works even with GitHub Desktop app. Nice.
