### ISSUE TITLE
my project is unusable now

### ISSUE THREAD

**Issue by Bdoom** [git-lfs/git-lfs#2503]
```
#<<<<<<< HEAD
version https://git-lfs.github.com/spec/v1
oid sha256:dasdhkjasdghjasjhdasjhd
=======
version https://git-lfs.github.com/spec/v1
oid sha256:dasdasjdk asdhasdjagsdhasdagshdgashdjahsdk
size 12970
>>>>>>> development
```

all of my .cpp files have been replaced with your useless garbage, how do i fix this?

**Comment by Bdoom** [comment]
So for some reason, I am unable to use git lfs pull or git lfs checkout . or git lfs fetch.

When I run all of these commands, it does nothing. Ever since I pushed my last files to github with git lfs, it broke my system and now I cannot compile my C++ files. My files get replaced with stuff like this:

<<<<<<< HEAD
version https://git-lfs.github.com/spec/v1
oid sha256:fab2dcd597fd7d5590e10fc8b0f055b7eeed08adc5c2d3dbd0f36346ece436d8
size 1995
=======
version https://git-lfs.github.com/spec/v1
oid sha256:aaba9d88867f69cca33002caebde571814b58fc760bfd0ffdce154b1cb5c7fa3
size 1997
>>>>>>> development

**Comment by Bdoom** [comment]
I type git lfs fetch --all still nothing

**Comment by ttaylorr** [comment]
Hi @Bdoom, thanks for opening this and sorry that you're having trouble. It looks like there's an unresolved merge conflict hanging around in your history. You can fix this by running a `git filter-branch` or `git rebase` over the affected commits, and fixing them up (or removing them from your history).

We have a `git lfs migrate` tool, but I don't think that will help here since the pointers themselves are corrupt. This would be a good migration mode to support in the future.

**Comment by Bdoom** [comment]
Hello @ttaylorr 
No, thank you. How did you find out? Is there something I could do in the future to check this out?

**Comment by Bdoom** [comment]
Nevermind, spoke to o soon. It's still not fixed. About four of my files (that I have seen so far) are now 1 kb each. One of them should be about 20 kb, and so on.

```
<<<<<<< HEAD
version https://git-lfs.github.com/spec/v1
oid sha256:74f0a1213ad4400648d7a122156fd4b308f67321b3e07a9203403abfc65b0f83
size 588625
=======
version https://git-lfs.github.com/spec/v1
oid sha256:3115e009b9d1131c9aea2108ea271c0f49950e01a4c3ad6e3d6d7d9523e602b0
size 559842
>>>>>>> development

```

This is one of them.

**Comment by Bdoom** [comment]
yeah it looks like as if git lfs has just completely ruined my entire project. im going to have to go in and manually download these files and replace them.

**Comment by Bdoom** [comment]
ive lost an entire 2 days worth of work now.

**Comment by ttaylorr** [comment]
@Bdoom, I'm sorry that you're having trouble and running into these issues. It looks like the pointer that you posted is also malformed, as it contains a merge conflict (indicated by the `<<<< HEAD` and `>>>>> development` lines). You can solve these in the same way as you did before, by either removing or running `filter-branch` the affected commits.

**Comment by Bdoom** [comment]
Could you give me an example of filter-branch and its usage in this instance?

**Comment by ttaylorr** [comment]
A `git-rebase(1)` may be more appropriate here. You can find the affected SHAs, and remove each of them by running:

```bash
git rebase -p --onto SHA^ SHA
```

**Comment by RiberWang** [comment]
version https://git-lfs.github.com/spec/v1
oid sha256:446a6063f3b698c388700d664a5173bd58a2f194808239a2073766021adca0ca
size 9195

My files show this, why?
