### ISSUE TITLE
LFS reports a warning for zero length files

### ISSUE THREAD

**Issue by ninloot** [git-lfs/git-lfs#2504]
We are tracking all files with a *.cdb extension which are typically large files.  However one of the files happens to be a zero length file.  When LFS encounters this file we get the following warning displayed:
Encountered 1 file(s) that should have been pointers, but weren't:
        empty.cdb
If I run `git lfs pointer --file=empty.cdb` it returns nothing whereas a file with content will return a valid pointer file.  
This issue appears to be more of a nuisance since everything seems to work fine except for the warning that is displayed.  Here is the version info:
git-lfs/1.5.6 (GitHub; windows 386; go 1.7.5; git bbd328b1)
git version 2.13.0.windows.1

**Comment by ttaylorr** [comment]
Hi @ninloot, thanks for opening this. The most recent version of LFS does not print this warning, since empty files yield empty pointers in a valid case (#2449, #2458). Please update to the latest version of LFS (v2.2.1).
