### ISSUE TITLE
Investigate SSH auth timeout issues

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#2519]
See: https://github.com/git-lfs/git-lfs/pull/2511#issuecomment-323599680

**Comment by ttaylorr** [comment]
Thanks for opening this, @technoweenie! I took a quick look through `lfsapi/ssh.go` to refresh my memory on how that code works, and on the surface it appears that the SSH cacher, when enabled, should be caching and appropriately dropping entries that have expired.

@larsxschneider can you post the output of the command you ran in https://github.com/git-lfs/git-lfs/pull/2511#issuecomment-323599680 with `GIT_TRACE=1` here? The tracerx output in there should be enough to figure out any subtly that I've missed so far. Thanks!

**Comment by larsxschneider** [comment]
@ttaylorr The repo is public: https://github.com/larsxschneider/lfstest-manyfiles 😄 
Are you not able to reproduce the error with this call?
```
git clone git@github.com:larsxschneider/lfstest-manyfiles.git
```

**Comment by larsxschneider** [comment]
You might need to slow down your Internet connection a bit to reproduce it https://apple.stackexchange.com/a/24078 😉
