### ISSUE TITLE
Git Windows installer contains LFS

### ISSUE THREAD

**Issue by ygoe** [git-lfs/git-lfs#2520]
The official Git Installer for Windows already contains an option named "Git LFS". What is that, does it contain the full LFS software from this project? Do I actually need to download anything from this project separately?

**Comment by technoweenie** [comment]
The Git for Windows team was nice enough to bundle Git LFS for us ❤️ You should be able to run `git lfs version` to see specifically what version it installed. I don't know how often they update the bundled version.

**Comment by ygoe** [comment]
I've found the bundled LFS version in their release notes, just for reference. Seems pretty up-to-date.

https://github.com/git-for-windows/git/releases/
