### ISSUE TITLE
Command sequence to upload without cloning

### ISSUE THREAD

**Issue by ppKrauss** [git-lfs/git-lfs#2521]
Like the online "Upload" button of Github, but in a easy  CLI, like an old `put` command of FTP.

PS: sorry if I not see, but README not offers a link to a fast-guide or "list of non-usual commands, exclusive of LFS".

**Comment by technoweenie** [comment]
I don't know of any way to update a git repository without cloning it first. You could experiment with a [shallow clone](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt) maybe? Shallow clones might only be useful for read-only use cases though, I've never tried it.
