### ISSUE TITLE
Adding origins with missing LFS info won't lead to any complaints, warnings, . and git/git-lfs will happily pull commits with missing LFS storage objects

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#2532]
I just ran into the following situation where I freshly cloned a repo, then added an additional remote (with same repo but slightly different state) and it seems LFS completely borked to fetch the LFS objects on its own for some reason:
```
jonas@cyberman:~/Develop$ git clone https://github.com/tethercode/stdlib ./stdlib-delete
Cloning into './stdlib-delete'...
remote: Counting objects: 5669, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 5669 (delta 6), reused 9 (delta 3), pack-reused 5648
Receiving objects: 100% (5669/5669), 1.28 MiB | 451.00 KiB/s, done.
Resolving deltas: 100% (3886/3886), done.
jonas@cyberman:~/Develop$ cd stdlib-delete/
jonas@cyberman:~/Develop/stdlib-delete$ vim .git/config 
jonas@cyberman:~/Develop/stdlib-delete$ git pull gitlab
warning: redirecting to https://gitlab.com/tethercode/stdlib.git/
remote: Counting objects: 124, done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 124 (delta 75), reused 0 (delta 0)
Receiving objects: 100% (124/124), 22.58 KiB | 7.53 MiB/s, done.
Resolving deltas: 100% (75/75), completed with 16 local objects.
From https://gitlab.com/tethercode/stdlib
 + 767ce25...e3fc7d9 master     -> origin/master  (forced update)
You asked to pull from the remote 'gitlab', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
jonas@cyberman:~/Develop/stdlib-delete$ git pull gitlab master
warning: redirecting to https://gitlab.com/tethercode/stdlib.git/
From https://gitlab.com/tethercode/stdlib
 * branch            master     -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 .gitignore                                   |   1 +
 Makefile                                     |   2 +-
 compiler/errorprint.tc                       |  90 ++++
 compiler/helpers.tc                          |  87 ++++
 compiler/run.tc                              |  31 ++
 compiler/semantics.tc                        |   9 +-
 compiler/tetherasm/instruction.tc            | 623 ++++-----------------------
 compiler/tetherasm/instructiongen.tc         | 597 +++++++++++++++++++++++++
 compiler/tetherasm/tetherasm.tc              | 175 +++++++-
 compiler/tethercc.tc                         | 203 ++-------
 ffi.tc                                       |  25 +-
 misc/highlighting/vim/ftdetect/tetherasm.vim |   3 +
 misc/highlighting/vim/syntax/tetherasm.vim   |  42 ++
 misc/highlighting/vim/syntax/tethercode.vim  |   2 +-
 path.tc                                      |  26 ++
 platform.tc                                  |  12 +
 sys.tc                                       |  10 +-
 tcpm.ini                                     |   2 +
 tools/baseline-runner.py                     |   7 +-
 19 files changed, 1231 insertions(+), 716 deletions(-)
 create mode 100644 compiler/errorprint.tc
 create mode 100644 compiler/helpers.tc
 create mode 100644 compiler/run.tc
 create mode 100644 compiler/tetherasm/instructiongen.tc
 create mode 100644 misc/highlighting/vim/ftdetect/tetherasm.vim
 create mode 100644 misc/highlighting/vim/syntax/tetherasm.vim
jonas@cyberman:~/Develop/stdlib-delete$ gitg .
jonas@cyberman:~/Develop/stdlib-delete$ git push
Username for 'https://github.com': JonasT
Password for 'https://JonasT@github.com': 
Counting objects: 124, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (47/47), done.
Writing objects: 100% (124/124), 19.25 KiB | 19.25 MiB/s, done.
Total 124 (delta 75), reused 122 (delta 74)
remote: Resolving deltas: 100% (75/75), completed with 15 local objects.
To https://github.com/tethercode/stdlib
   767ce25..40cc75e  master -> master
jonas@cyberman:~/Develop/stdlib-delete$ git push gitlab master
warning: redirecting to https://gitlab.com/tethercode/stdlib.git/
open /home/jonas/Develop/stdlib-delete/misc/logo/blender/bg.blend: no such file or directory
error: failed to push some refs to 'https://gitlab.com/tethercode/stdlib'
jonas@cyberman:~/Develop/stdlib-delete$ git lfs fetch --all gitlab
Scanning for all objects ever referenced...
✔ 27 objects found                                                                                          
Fetching objects...
Git LFS: (23 of 23 files) 17.59 MB / 17.59 MB                                                              
jonas@cyberman:~/Develop/stdlib-delete$
```
As you can see, I had to manually fetch them. 

Edit: after more investigation, this seems because I manually edited the .git/config file and added the origin but no "lfs" entry:
```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    url = https://github.com/tethercode/stdlib
    fetch = +refs/heads/*:refs/remotes/origin/*
[remote "gitlab"]
    url = https://gitlab.com/tethercode/stdlib
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
[gitg]
    mainline = refs/heads/master
[lfs "https://github.com/tethercode/stdlib.git/info/lfs"]
    access = basic
[lfs "https://gitlab.com/tethercode/stdlib.git/info/lfs"]
    locksverify = false
    access = basic
```
The strongly expected behavior here would be that git-lfs detects that the remote has LFS enabled (preferably *before* the pull goes through, otherwise at least afterwards with the obvious new LFS file pointers downloaded that point to missing objects there should be some sort of detection that something went wrong) and that git-lfs shows at least some sort of warning that what I just did was incomplete and nonsense, or even better git-lfs blocks the pull entirely until the proper LFS storage was specified as well.

The actual behavior appears to be that it just goes through quietly without any warnings.

**Comment by technoweenie** [comment]
The [server discovery docs](https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md) describe how git lfs chooses the LFS server URL. It doesn't really "detect" a server, but it attempts to guess it by transforming the Git remote URL into an LFS server URL.

Also, LFS won't necessarily download objects when you run `git pull`. It downloads them as files are checked out to your working directory, meaning any past history is not downloaded.

This error during push looks like the pushed commits contain an LFS object that's not in your local `.git/lfs/objects` directory. In a pinch, LFS attempts to look in the working copy for the right file, but this breaks if you added an LFS object, removed it from `.git/lfs/objects`, and then remove the file from Git too.

```
$ git push gitlab master
warning: redirecting to https://gitlab.com/tethercode/stdlib.git/
open /home/jonas/Develop/stdlib-delete/misc/logo/blender/bg.blend: no such file or directory
error: failed to push some refs to 'https://gitlab.com/tethercode/stdlib'
```

I could be wrong on some of this. Running the Git commands with `GIT_TRACE` will give you a better idea of what's causing these issues.

**Comment by JonasT** [comment]
I wrote a bash script which reproduces  the issue 100%. Install git-lfs then run the following in a new empty folder:

```bash
#!/bin/sh

rm -rf ./stdlib-test1
rm -rf ./stdlib-test2
git clone https://github.com/tethercode/stdlib ./stdlib-test1
cd stdlib-test1 && git remote add github https://gitlab.com/tethercode/stdlib && cd ..
mkdir -p stdlib-test2
cd stdlib-test2 && git init . && cd ..
cd stdlib-test1 && touch ./mahfile && git add mahfile && git commit -m "Test" && cd ..
cd stdlib-test1 && git remote add neworigin "`pwd`/../stdlib-test2/" && cd ..
cd stdlib-test1 && git push neworigin master
```
Output:
```shell
jonas@cyberman:~/Develop/git-lfs-bug-delete$ ./test.sh 
Cloning into './stdlib-test1'...
remote: Counting objects: 5793, done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 5793 (delta 73), reused 128 (delta 70), pack-reused 5648
Receiving objects: 100% (5793/5793), 1.32 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (3953/3953), done.
Initialized empty Git repository in /home/jonas/Develop/git-lfs-bug-delete/stdlib-test2/.git/
[master 5b1e3c7] Test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 mahfile
Remote "neworigin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs./home/jonas/Develop/git-lfs-bug-delete/stdlib-test1/../stdlib-test2.git/info/lfs.locksverify false
open /home/jonas/Develop/git-lfs-bug-delete/stdlib-test1/misc/logo/blender/bg.blend: no such file or directory
error: failed to push some refs to '/home/jonas/Develop/git-lfs-bug-delete/stdlib-test1/../stdlib-test2/'
jonas@cyberman:~/Develop/git-lfs-bug-delete$
```

**Comment by technoweenie** [comment]
Okay, here's what I think is happening:

1. You clone a repo from github. LFS only downloads the most recent versions of LFS objects.
2. You add a new remote `neworigin` that points to a local directory.
3. You try to push to `neworigin`. Git determines that `neworigin` has no content, so it has to send over every commit, and every LFS object. But, your local clone only has the most recent versions of LFS objects. Based on the `open` error, that `misc/logo/blender/bg.blend` file existed at one time, but was moved or deleted.

You could get a little further with this:

```diff
rm -rf ./stdlib-test1
rm -rf ./stdlib-test2
git clone https://github.com/tethercode/stdlib ./stdlib-test1
cd stdlib-test1 && git remote add github https://gitlab.com/tethercode/stdlib && cd ..
mkdir -p stdlib-test2
cd stdlib-test2 && git init . && cd ..
cd stdlib-test1 && touch ./mahfile && git add mahfile && git commit -m "Test" && cd ..
-cd stdlib-test1 && git remote add neworigin "`pwd`/../stdlib-test2/" && cd ..
+cd stdlib-test1 && git remote add neworigin "`pwd`/../stdlib-test2/"
+git lfs fetch --all origin && cd ..
cd stdlib-test1 && git push neworigin master
```

That will fetch all of the repositories objects from `origin`, so they can be pushed to `neworigin`. However, `neworigin` is located on a local directory, not a Git server, so LFS can't auto-discover its LFS server. 

A couple ideas that could solve this:

1. Teach the LFS `pre-push` hook to fetch missing LFS objects before pushing. How will LFS know which remote to fetch them from? Should it assume `origin`, if the destination remote isn't `origin`? 
2. Teach LFS how to push to repos on the local filesystem. Do this by one of the following:
  * Emulate the LFS Batch API against the local filesystem.
  * Teach LFS to detect that it's on the local filesystem, and use that repo's `origin` setting. In your case, `stdlib-test2` is an empty repo, so it'd still break.
3. Configure an LFS server for `neworigin` like `git config remote.neworigin.lfsurl <lfs-server>`.

If you're just trying to push the repo to gitlab (this should work to and from any functioning git + lfs host):

```sh
$ git lfs clone https://github.com/tethercode/stdlib
$ cd stdlib
$ git lfs fetch --all
$ git remote add gitlab https://gitlab.com/tethercode/stdlib
$ git push gitlab master
```

Does that help?

**Comment by JonasT** [comment]
I did already manage to fix it locally (simply by adding the LFS info manually and using fetch all to get the LFS objects), also see the edit in the first post.

Sorry if that wasn't clear, but this is really more of a bug report than a support request. I think the script I gave should work, or give a clear concise error at a much earlier point that something went wrong.

**Comment by JonasT** [comment]
Ok, I managed to make a new test case:

```bash
#!/bin/sh

rm -rf ./stdlib-test1
rm -rf ./stdlib-test2
git clone https://github.com/tethercode/stdlib ./stdlib-test1
cd stdlib-test1 && git remote add github https://gitlab.com/tethercode/stdlib && cd ..
mkdir -p stdlib-test2
cd stdlib-test2 && git clone https://github.com/tethercode/stdlib . && git lfs fetch && cd ..
cd stdlib-test1 && touch ./mahfile && git add mahfile && git commit -m "Test" && cd ..
cd stdlib-test1 && git remote add neworigin "`pwd`/../stdlib-test2/" && cd ..
cd stdlib-test1 && git push neworigin master
```

In this case, the target only lacks the new test commit containing the single non-lfs file and definitely *has all lfs objects already there*. Therefore, there is no reason for git-lfs to freak out if it correctly identified what needed to be pushed.

Despite that, it still errors:
```shell
open /home/jonas/Develop/git-lfs-bug-delete/stdlib-test1/misc/logo/blender/bg.blend: no such file or directory
error: failed to push some refs to '/home/jonas/Develop/git-lfs-bug-delete/stdlib-test1/../stdlib-test2/'
jonas@cyberman:~/Develop/git-lfs-bug-delete$
```
This is rather unexpected to me and if it's a bug I think it should be fixed.

**Comment by technoweenie** [comment]
The LFS `pre-push` hook is limited by what Git sends it. If Git sends the entire range of commits, LFS will attempt to upload those S3 objects. `GIT_TRACE` should tell you what Git is sending:

```
rm -rf ./stdlib-test1
rm -rf ./stdlib-test2
git clone https://github.com/tethercode/stdlib ./stdlib-test1
cd stdlib-test1 && git remote add github https://gitlab.com/tethercode/stdlib && cd ..
mkdir -p stdlib-test2
cd stdlib-test2 && git clone https://github.com/tethercode/stdlib . && git lfs fetch --all && cd ..
cd stdlib-test1 && touch ./mahfile && git add mahfile && git commit -m "Test" && cd ..
cd stdlib-test1 && git remote add neworigin "`pwd`/../stdlib-test2/" && cd ..
-cd stdlib-test1 && git push neworigin master
+cd stdlib-test1 && GIT_TRACE=1 git push neworigin master
```

Also, try running `git lfs fetch --all` inside `stdlib-test1` instead of `stdlib-test2`.

**Comment by JonasT** [comment]
Running it inside `stdlib-test1` will most certainly fix things. However, why is it breaking in the first place?

I expect the following git-lfs behavior:

- a new clone will download the LFS objects used in the current working tree of the latest commit on master (apparently NOT happening here)
- a push to another repo not containing any other LFS objects will not fail due to missing LFS objects after a regular clone of the repo given I'm not even changing branches or commits (apparently NOT happening here)

Since both of those things are broken, I suggest they are fixed. Also just to reiterate, you should be able to easily copy the script and reproduce all of this - the repos are public and the script only works on fresh clones and doesn't depend on anything else being present in the system.

**Comment by technoweenie** [comment]
> However, why is it breaking in the first place?

Git LFS only downloads what gets checked out to your working directory. Even if we wanted to allow you to specify that LFS downloads the entire history of LFS objects, Git doesn't offer up any extension points to allow that. So, you can run `git lfs fetch --all` to get them.

**Comment by technoweenie** [comment]
I made a patch (https://github.com/git-lfs/git-lfs/pull/2544), but I also forgot we've deprecated the `git lfs clone` command. It's not going anywhere any time soon, but I also don't want to add to the command. Wrapper commands like that aren't really that useful, and provide extra burden on us to maintain flag parity with the git command.

So, if #2544 is not accepted, you'll have to stick `git lfs fetch --all` into your script. If you have a use case where all of your clones need all of the LFS objects, then you should probably stick to plain Git.

Thanks for the report.

**Comment by JonasT** [comment]
@technoweenie 

> Where is this not happening? I haven't seen any evidence of this in your output.

1. Run the script
2. Open `stdlib-test1/misc/logo/tethercode_icon.xcf`. Here, it has these contents:

```
version https://git-lfs.github.com/spec/v1
oid sha256:9e5a6a917a718eebf7b8c57ad06cdba1f5c3b6e98a0eb1784fa18c7d4bb443fa
size 12573
```
---
Independently of this, I suggest this issue should be reopened. Please let me state again more clearly what the issue is:

- I am `git clone`ing repo twice with full contents. **As shown in this comment above, LFS files are not downloaded even those included in the working tree.** That alone is weird..
- In one of the clones I am making a single commit with just one file. **This commit is the only difference between the entire state of both repos, and it has no LFS files in it**. Still, pushing this commit to the other repo gives the inexplicable, completely unrelated error for an LFS file you just said *has already been deleted* that isn't even part of the commit, *and the repositories have otherwise 100% the same history*. To confirm this, look again at how exactly I am setting up the entire test case:

```
#!/bin/sh

rm -rf ./stdlib-test1
rm -rf ./stdlib-test2
git clone https://github.com/tethercode/stdlib ./stdlib-test1
cd stdlib-test1 && git remote add github https://gitlab.com/tethercode/stdlib && cd ..
mkdir -p stdlib-test2
cd stdlib-test2 && git clone https://github.com/tethercode/stdlib . && git lfs fetch --all && cd ..
cd stdlib-test1 && touch ./mahfile && git add mahfile && git commit -m "Test" && cd ..
cd stdlib-test1 && git remote add neworigin "`pwd`/../stdlib-test2/" && cd ..
cd stdlib-test1 && git push neworigin master

```
Also can you run the script locally? All of what I am writing above is 100% reproducible for me, it happens every time just by running the script.

**Comment by JonasT** [comment]
Again to make this super clear, I wrote this script *purely to reproduce the issues I saw*. I am not looking for a fix of the script or a workaround, I am trying to suggest what results from running it is possibly a git-lfs bug.

**Comment by technoweenie** [comment]
I changed the last command to `GIT_TRACE=1 git push neworigin master`, and got the "open file" error.

> I am git cloneing repo twice with full contents. As shown in this comment above, it appears some of the LFS files of those included in the HEAD working tree aren't downloaded. That alone is weird..

When you run `git clone`, Git specifically tells Git LFS what to download based on its interpretation of `.gitattributes`. My clone output shows it being downloaded:

```
Cloning into './stdlib-test1'...
remote: Counting objects: 5920, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 5920 (delta 60), reused 85 (delta 53), pack-reused 5820
Receiving objects: 100% (5920/5920), 1.34 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (4047/4047), done.
Downloading docs/font/Quicksand-Light.ttf (21 KB)
Downloading docs/font/Quicksand-Regular.ttf (24 KB)
Downloading misc/logo/tethercode_icon.ico (8.3 KB)
Downloading misc/logo/tethercode_icon.xcf (13 KB)
```

Confirmed that specific file is downloaded:

```
~p $ ls -al stdlib-test1/misc/logo/tethercode_icon.xcf
-rw-r--r--  1 rick  staff  12573 Sep 11 16:27 stdlib-test1/misc/logo/tethercode_icon.xcf
~p $ head stdlib-test1/misc/logo/tethercode_icon.xcf
gimp xcf file�B�%B�%
                    gimp-image-grid(style solid)
(fgcolor (color-rgba 0.000000 0.000000 0.000000 1.000000))
(bgcolor (color-rgba 1.000000 1.000000 1.000000 1.000000))
(xspacing 48.000000)
(yspacing 48.000000)
(spacing-unit inches)
(xoffset 0.000000)
(yoffset 0.000000)
(offset-unit inches)
```

Here's the details of the failing push command:

```
16:33:33.467176 git.c:328               trace: built-in: git 'push' 'neworigin' 'master'
16:33:33.468215 run-command.c:626       trace: run_command: 'git-receive-pack '\''/Users/rick/p/stdlib-test1/../stdlib-test2/'\'''
16:33:33.473994 git.c:328               trace: built-in: git 'receive-pack' '/Users/rick/p/stdlib-test1/../stdlib-test2/'
16:33:33.475566 run-command.c:626       trace: run_command: '.git/hooks/pre-push' 'neworigin' '/Users/rick/p/stdlib-test1/../stdlib-test2/'
16:33:33.481779 git.c:560               trace: exec: 'git-lfs' 'pre-push' 'neworigin' '/Users/rick/p/stdlib-test1/../stdlib-test2/'
16:33:33.482327 run-command.c:626       trace: run_command: 'git-lfs' 'pre-push' 'neworigin' '/Users/rick/p/stdlib-test1/../stdlib-test2/'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: HTTP: POST /Users/rick/p/stdlib-test1/../stdlib-test2.git/info/lfs/locks/verify
Remote "neworigin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs./Users/rick/p/stdlib-test1/../stdlib-test2.git/info/lfs.locksverify false
trace git-lfs: pre-push: refs/heads/master 8868a77181ef5dde28dfb81fbd3f0df3ccf933c5 refs/heads/master 384af44e26cd6940f31d39b815398392f5dc55b7
trace git-lfs: run_command: git rev-list --objects 8868a77181ef5dde28dfb81fbd3f0df3ccf933c5 --not --remotes=neworigin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
open /Users/rick/p/stdlib-test1/misc/logo/blender/bg.blend: no such file or directory
error: failed to push some refs to '/Users/rick/p/stdlib-test1/../stdlib-test2/'
```

So, Git is calling `pre-push` with the commit range: `refs/heads/master 8868a77181ef5dde28dfb81fbd3f0df3ccf933c5 refs/heads/master 384af44e26cd6940f31d39b815398392f5dc55b7`. That should be just the new commit.

However, LFS filters out things in the local remote cache. Since there isn't one in your script, it does a full repository scan.

    git rev-list --objects 8868a77181ef5dde28dfb81fbd3f0df3ccf933c5 --not --remotes=neworigin --

This was changed on purpose to ensure your remote has the necessary objects. It's technically doing more work than necessary, but it prevents partial git migrations where only the Git content is moved. Ideally the way it works is:

1. `git rev-list --objects 8868a77181ef5dde28dfb81fbd3f0df3ccf933c5 --not --remotes=neworigin --` runs, scanning the entire history, since there's nothing in `.git/refs/remotes/neworigin/master`.
2. LFS asks the `neworigin` LFS server to upload those files.
3. If the migration to `neworigin` was done correctly, the LFS server should return a response indicating it has every file, so nothing is uploaded.

The open error is happening between steps 1 and 2. You should be able to turn `lfs.allowincompletepush` (added in https://github.com/git-lfs/git-lfs/pull/2199), but it doesn't work for me. I suppose there's another spot that value has to be checked. We can look at that for the upcoming 2.3.0 release this week. I also think `lfs.allowincompletepush` should just be on by default.

**Comment by JonasT** [comment]
That seems wrong though, `lfs.allowincompletepush` should at least a big fat warning for missing objects (I definitely hope it does!) - and I think the script above definitely shouldn't emit such a warning either.

Given your explanations (which I admit I couldn't fully understand) it seems like the problem is the following:

1. Objects being sent:

   1. LFS objects part of the commit are and also outside of the commit to be super cautious are sent to the server (current behavior)

2. Error handling:

   1. If an LFS file part of the commit cannot be sent and `lfs.allowincompletepush` is disabled, the push aborts with an error (current behavior)

   2. If an LFS file part of the commit cannot be sent and `lfs.allowincompletepush` is enabled, the push goes through **but there should be a bit fat warning** (hopefully current behavior)

   3. If LFS object files are NOT part of the commit and cannot be sent, *no error and no warning should be ever shown* and it should always be quietly ignored (not the current behavior!)

Essentially there seems to be an error over something over-cautious that wasn't necessary, can't work anyway (in the specific above test setup anyway) and simply isn't relevant to just pushing the commit and therefore erroring or emitting warnings is just plain confusing and IMHO a bad idea. However, LFS files that are actually a proper part of the commit should still cause proper errors and/or warnings as appropriate.

PS: it is also possible that I fundamentally misunderstood some of the stuff going on here, in which case maybe this comment doesn't make much sense lol :smile:

**Comment by JonasT** [comment]
Important addition: of course I'm just talking about the LFS filter behavior for a regular push, not `git lfs push --all` or something where transferring more than the current commit is explicitly desired.

**Comment by technoweenie** [comment]
> Given your explanations (which I admit I couldn't fully understand) I think this is how things should be

Ha, sorry about the confusion. It's a big sprawling issue, where I somehow got caught up on some other detail when I was looking into it before. Your summary looks correct.

> If LFS object files are NOT part of the commit and cannot be sent, no error and no warning should be ever shown and it should always be quietly ignored (not the current behavior!)

I'd happily accept a patch, but it's not something I personally have time to look at now.

The fixes to `lfs.allowincompletepush` are in https://github.com/git-lfs/git-lfs/pull/2574. However, it will likely fail your script since `neworigin` likely doesn't have a valid LFS server:

```sh
$ git lfs env
git-lfs/2.2.1 (GitHub; darwin amd64; go 1.8.3)
git version 2.14.1

Endpoint=https://github.com/tethercode/stdlib.git/info/lfs (auth=none)
Endpoint (github)=https://gitlab.com/tethercode/stdlib.git/info/lfs (auth=none)
Endpoint (neworigin)=/Users/rick/p/stdlib-test1/../stdlib-test2.git/info/lfs (auth=none)
```

Now, if you setup `neworigin` to a git host that supports LFS (like that gitlab remote), instead of a local path, then it should work fine :+1:

**Comment by JonasT** [comment]
> Now, if you setup neworigin to a git host that supports LFS (like that gitlab remote), instead of a local path, then it should work fine 👍

Actually this initially failed to me with a valid LFS remote :-/ so I'm not sure about that. Did my last comment make any sense to you? I tried to explain there what seems to be the problem, but of course all of that could be wrong since I don't know much about LFS internals..
