### ISSUE TITLE
git-lfs-migrate Does Not Work With Files in Sub-directories?

### ISSUE THREAD

**Issue by StanislawAntol** [git-lfs/git-lfs#2545]
I am trying to clean-up some of our repos that have many large binary files and migrate them to GitHub Enterprise. I've been trying to use `git-lfs-migrate` to convert the repos and haven't had any luck. (I've already done everything I need with `git-fat`, but it seems cleaner to use `git-lfs` if we're already migrating to GitHub enterprise.) 

There seems to be an issue with `git-lfs-migrate` not working with files in sub-directories. To reproduce this issue, you can find a bash script at [this gist](https://gist.github.com/StanislawAntol/b992caa88ec6587656680d4f3034e44d#file-git-lfs-migrate_issue-sh) with the output log at [this gist](https://gist.github.com/StanislawAntol/b992caa88ec6587656680d4f3034e44d#file-git-lfs-migrate_issue_log-txt) (nothing appears in `.git/lfs/objects/logs`). The script first creates a repo with a binary file in the initial directory, which works fine, and then creates a binary file in a sub-directory, which fails to migrate using different commands several `include` glob arguments (`${FILENAME}`, `**/*.${EXT}`, and `*.${EXT}`), though it seems to try on the current file and not any previous versions of it. If the file is Initially tracked at the start of the repo, `git-lfs` works as expected.

Am I calling `git-lfs-migrate` incorrectly or is this a bug?

Thanks!

----
Running on Ubuntu 16.04
`git lfs env` output:
```
git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.1)
git version 2.14.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_TRACE=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
Hi @StanislawAntol, thanks for opening this and posting such detailed reproduction steps! I fixed a bug that reminds me of this in #2485. I am curious if that change fixes your use-case above. I posted some Linux builds of Git LFS including that change that I'd love for you to give a shot:

[git-lfs-linux-386-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1278337/git-lfs-linux-386-2.3.0-pre.tar.gz)
[git-lfs-linux-amd64-2.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/1278338/git-lfs-linux-amd64-2.3.0-pre.tar.gz)

**Comment by StanislawAntol** [comment]
@ttaylorr, the 2.3.0 pre-release that you provided pass my simple test case from my initial post. I also tried running it on my original repo and it seems to also work on that. Though, for my repo, it seems like it doesn't push the LFS objects (for files initially added to the repo or changed months ago) to the server unless I run `git lfs push origin --all`. Is this the expected (default) behavior? Whenever I push my test case to a repo, I don't need a `git lfs push` command.

In light of this, do you have a (rough) target date for 2.3.0? Or do you think there would be any issues if my co-workers use 2.2.1 for repos that I migrated using your pre-release?

Thanks for your help!

**Comment by ttaylorr** [comment]
> it doesn't push the LFS objects (for files initially added to the repo or changed months ago) to the server unless I run `git lfs push origin --all`. Is this the expected (default) behavior?

This is expected behavior.

> In light of this, do you have a (rough) target date for 2.3.0?

I am planning on releasing v2.3.0 sometime early next week 😄

**Comment by cmruffin** [comment]
@ttaylorr if the release is delayed can you also post 2.3.0-pre windows binaries?
