### ISSUE TITLE
standalonetransferagent not used, git lfs always tries to use the url

### ISSUE THREAD

**Issue by silky** [git-lfs/git-lfs#2555]
i have the following setting in my `.git/config`

```
[lfs]
	standalonetransferagent = s3-direct

[lfs "customtransfer.s3-direct"]
	path = lfs-s3-transfer-agent
```

where `lfs-s3-transfer-agent` is from [here](https://github.com/ingenieux/lfs-transfer-s3)

unfortunately, any git push just uses directly the `url` derived from the repo. if i manually set a url as `url = localhost`, git lfs just attempts to use that.

why?

the [documentation implies](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn#L100) that this is exactly what this standalonetransferagent parameter is for; i.e. it should _not_ attempt to use the url. oddly, the very same documentation seems in conflict with itself as, in the below, it says it will need to query the url provided to ensure that the "name" is a known to the server. so i'm confused.

really appreciate some guidance here.

i'd just like to configure a standalone client and not have git talk to a git-lfs server _in any way_. but i can't find a way to do this.

i'd have the same problem with the [rsync](https://github.com/aleb/git-lfs-rsync-agent) plugin of @aleb 

i'm really keen to see if anyone has been able to make one of these custom transfer plugins work without the backend git server needing to be involved in the LFS component.

versions:
```
03:21 PM noon ∈ ~ ♫ git-lfs
git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.1)
Sorry, no usage text found for "git-lfs"
03:21 PM noon ∈ ~ ♫ git --version
git version 2.11.0
```

**Comment by aleb** [comment]
You would need git-lfs master, it's not part of 2.2.1

**Comment by ttaylorr** [comment]
> You would need git-lfs master, it's not part of 2.2.1

@aleb is totally right here. Git LFS v2.3.0 will be released early next week and will contain the standalonetransferagent changes.

**Comment by ttaylorr** [comment]
> You would need git-lfs master, it's not part of 2.2.1

@aleb is totally right here. Git LFS v2.3.0 will be released early next week and will contain the standalonetransferagent changes.
