### ISSUE TITLE
Uploading files to GitHub on an LFS repo doesn't track them

### ISSUE THREAD

**Issue by rgbkrk** [git-lfs/git-lfs#2563]
I thought I was being so crafty in showing a designer they could upload sketch files directly to github with "Upload files". Today I went back to the repo, cloned it and noticed:

```
Encountered 2 file(s) that should have been pointers, but weren't:
	Github_Auth.png
	commuter.sketch
```

Whoops! Is there an easy way to fix this on my end? I'm assuming I should post this as a GitHub support ticket too since it's a change to the GitHub UI, though I do know some maintainers here also work at GitHub. 😄

**Comment by ttaylorr** [comment]
@rgbkrk thanks for opening this issue! There is an easy way to fix this: you can run

```
$ git lfs migrate import --include='*.png' --include='*.sketch' --include-ref=<affected-branch>
```

and LFS will convert the files that should have been pointers into pointers.

Let me know if you have any trouble, and thanks again!
