### ISSUE TITLE
Get the whole LFS object list from a repo

### ISSUE THREAD

**Issue by emericv** [git-lfs/git-lfs#2575]
There is a way to have the whole LFS object sha256 list from a git repo? (like a git-lfs ls-files, but including modified/deleted objects refs of all branchs/tags).

I want to build a LFS object garbage collector system to clean orphan object of my LFS server

**Comment by ttaylorr** [comment]
@emericv thanks for opening this. `git lfs ls-files` takes a `<ref>` argument, so you can do something like:

```sh
git for-each-ref --format='%(refname)' | while read ref; do
  git lfs ls-files "$ref";
done \
  | sort -u \
  | uniq 
```

Alternatively, you can also run `git lfs prune` on your server, but this may not be exactly what you want.

**Comment by technoweenie** [comment]
`git lfs ls-files` always scans the tree, so that snippet won't really dig into the history.

https://github.com/git-lfs/git-lfs/blob/eaf1395a96b7e7a125d36722a3e90d8b7bce7ad6/commands/command_ls_files.go#L63-L65

**Comment by ttaylorr** [comment]
> `git lfs ls-files` always scans the tree, so that snippet won't really dig into the history.

We could teach `git lfs ls-files` to use `ScanRef` given a flag, which would make that snippet work. @technoweenie does this sound like a good idea?

**Comment by technoweenie** [comment]
Possibly. Here's how `ls-files` looks right now, with `ScanTree(ref)`:

```sh
$ GIT_TRACE=1 ~p/git-lfs/bin/git-lfs ls-files master
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: git cat-file --batch
0263829989 - bin/b.bin
98ea6e4f21 - bin/hi.bin
b9f86fab47 - gif/atom-undo.gif
d1c8fab514 - gif/droidtocat.gif
d1c8fab514 - gif/dupe.gif
e1732d149d - jpg/kabuki-tattoo-left.JPG
f026c32cd7 * png/render.png
```

Here it is with `ScanRefWithDeleted()`:

```diff
diff --git a/commands/command_ls_files.go b/commands/command_ls_files.go
index 11c412f1..630286d2 100644
--- a/commands/command_ls_files.go
+++ b/commands/command_ls_files.go
@@ -60,7 +60,7 @@ func lsFilesCommand(cmd *cobra.Command, args []string) {
        })
        defer gitscanner.Close()

-       if err := gitscanner.ScanTree(ref); err != nil {
+       if err := gitscanner.ScanRefWithDeleted(ref, nil); err != nil {
                Exit("Could not scan for Git LFS tree: %s", err)
        }
 }
```

```sh
$ GIT_TRACE=1 ~p/git-lfs/bin/git-lfs ls-files master
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: git rev-list --objects --do-walk master --
trace git-lfs: run_command: git cat-file --batch
0263829989 - bin/b.bin
98ea6e4f21 - bin/hi.bin
b9f86fab47 - gif/atom-undo.gif
d1c8fab514 - gif/droidtocat.gif
e1732d149d - jpg/kabuki-tattoo-left.JPG
f026c32cd7 * png/render.png
55d51edb30 - png/render.png
124733b36d - render.png
```

You can see it adding extra files. `render.png` was deleted, so it didn't show up from `ScanTree()`. `png/render.png` was modified, so now it shows up twice.

Will this output be sufficient? Or, will dupe files make it confusing? I think it'll definitely meet the use case here, but I'm not sure `ls-files` is the best place.
