### ISSUE TITLE
git-lfs does not support negotiate authentication

### ISSUE THREAD

**Issue by capearlman** [git-lfs/git-lfs#2576]
Any chance lfs could use negotiate authentication in addition to basic auth? We use kerberos/sso in front of our GIT server and we currently can't utilize lfs for this reason. When the lfs authentication happens, it just fails as it won't retry authentication with a different method. This would be similar to the fix in the GIT bug:
https://github.com/git/git/commit/4dbe66464b4fd695c5989cc272fa0edd6475037c

**Comment by ttaylorr** [comment]
Hi @capearlman, this is certainly something that LFS can support, though it is not on my roadmap immediately. I or @technoweenie would be happy to help a contributor through their first pull-request to LFS with this task.

**Comment by pascalberger** [comment]
Seems to be related to #2234
