### ISSUE TITLE
Two remote workflow and long time validation checking

### ISSUE THREAD

**Issue by gurugray** [git-lfs/git-lfs#2582]
We have a workflow with two remotes:

upstream — main remote with no write permisons
origin — fork for pull-request proposes

But with this scheme git-lfs always want to check validity of pushing objects:
```
Git LFS: (0 of 196 files, 30516 skipped) 0 B / 3.51 MB, 565.66 MB skipped   
```

And it may be very long time to check all files.
How can we mark second remote as a «full fork» and don't check all fork history?

**Comment by ttaylorr** [comment]
@gurugray thanks for opening this, and great question. I'm not sure exactly by what the term "full fork" means, though my best guess is that (n) forks that share history should not have their common ancestry re-examined.

LFS currently doesn't support behavior like this, but, unlike Git, I think that it should. This isn't something that is immediately on my roadmap, but I think the way that I'd approach this is by changing the nature of `gitscanner.ScanLeftToRemote()`, which is the function that finds LFS pointers in history from a given "left" revision, to the remote "remote".

One way to do this is to change that function's signature to:

```go
func (g *GitScanner) ScanLeftToRemotes(left *git.Revision, remotes ...string) { ... }
```

That function could find the common ancestries between all of the given remotes, and then scan from left to each of those points in history. That would eliminate needless effort to rescan "new" history.

That all said, again, I don't have time to put this on my immediate roadmap, but I do think that this is something that we should address. LFS would also have to know how to mark two remotes as related, but I think that's a smaller issue.

**Comment by gurugray** [comment]
Thanks for your comment!
I'll try to look in code git-lfs and what we can do more efficient in usage our workflow.

**Comment by technoweenie** [comment]
The `pre-push` hook gets the before and after commits for a push, so it's actually quite easy to scan only the specific commits. But we had problems with missing server objects, leading to corrupt repositories. `ScanLeftToRemotes()` was written specifically for to make sure that missing objects are uploaded.

If you had local remote refs that are up to date with the server, it'd skip checking the entire history for LFS objects to upload. Specifically, I'm talking about local refs like `.git/refs/remotes/origin/{ref}`, which are populated when you run `git fetch` or `git pull`.

It's possible that LFS has improved enough that we can go back to scanning between the push's before/after commits. For now, I prefer to be a little over cautious if it means fewer repos are missing LFS objects.
