### ISSUE TITLE
git-lfs clone with blank repository tries to pull HEAD

### ISSUE THREAD

**Issue by shiftkey** [git-lfs/git-lfs#2592]
Version: `2.3.0`
Git Version: `2.14.1.windows.1`
OS: Windows `10.0.15063`

Log file:

```
$ git-lfs clone --recursive --progress -- https://github.com/shiftkey/blank-repo.git C:\Users\shiftkey\Documents\GitHub\blank-repo
Could not pull

Git can't resolve ref: "HEAD"

Current time in UTC:
2017-09-18 02:40:00

ENV:
LocalWorkingDir=C:\Users\shiftkey\Documents\GitHub\blank-repo
LocalGitDir=C:\Users\shiftkey\Documents\GitHub\blank-repo\.git
LocalGitStorageDir=C:\Users\shiftkey\Documents\GitHub\blank-repo\.git
LocalMediaDir=C:\Users\shiftkey\Documents\GitHub\blank-repo\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\shiftkey\Documents\GitHub\blank-repo\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\shiftkey\Documents\GitHub\blank-repo\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_ASKPASS=C:\Users\shiftkey\src\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\static\ask-pass-trampoline.bat
GIT_CONFIG_PARAMETERS='credential.helper='
GIT_EXEC_PATH=C:\Users\shiftkey\src\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\git\mingw64\libexec\git-core
GIT_TERMINAL_PROMPT=0
LOCAL_GIT_DIRECTORY=C:\Users\shiftkey\src\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\git

Client IP addresses:
fdb2:2c26:f4e4:0:24ae:5968:eb4f:e47 fdb2:2c26:f4e4:0:3440:8222:75f8:51cd fe80::24ae:5968:eb4f:e47 10.211.55.20
```

I'd like to understand the behaviour here:

 - the first error is coming from [this panic](https://github.com/git-lfs/git-lfs/blob/master/commands/command_pull.go#L46) which seems deliberate
 - the inner error is [from here](https://github.com/git-lfs/git-lfs/blob/1a1c679186cdd2c60bc043f6132cc87db001bddc/git/git.go#L197-L203), which is also fine
 - it seems like we should check that `HEAD` exists before doing [this `pull`](https://github.com/git-lfs/git-lfs/blob/master/commands/command_clone.go#L95) and maybe log a different message to indicate that we've skipped any post-clone network operations

If that all makes sense, I'd be happy to propose a patch. Alternatively, if this should be addressed further down the stack (to make `pull` a no-op in this situation) I can dig deeper into that.

**Comment by technoweenie** [comment]
Hey @shiftkey :)

> the first error is coming from this panic which seems deliberate

Yep, though I think a panic (spewing a stacktrace with env details) is unnecessary.

> the inner error is from here, which is also fine

Yup :+1:

> it seems like we should check that HEAD exists before doing this pull and maybe log a different message to indicate that we've skipped any post-clone network operations

I like that. It may be worth seeing what that `fetchRef()` call does on an empty repository too:

https://github.com/git-lfs/git-lfs/blob/5703b808220103063ededf5c6149c93201be9e07/commands/command_clone.go#L93

**Comment by shiftkey** [comment]
@technoweenie I'll check `fetchRef` too while I'm in here.

**Comment by savedsince73** [comment]
I HAVE GOTTEN YOUR SIGHT OFF GOOGLE PLEASE HELP ME GET MY GOOGLE BACK
