### ISSUE TITLE
git lfs migrate import doesn't allow multiple --include arguments

### ISSUE THREAD

**Issue by cmruffin** [git-lfs/git-lfs#2593]
When attempting an import operation that uses multiple --include options, only the last option is acted upon.

git lfs migrate import --include="*.bin" --include="*.xml"

To reproduce:

mkdir test-repo
cd test-repo
git init
dir > file.bin
dir > file.xml
git add file.bin file.xml
git commit -m "new files"
git lfs migrate import --include="*.bin" --include="*.xml"
git show master

C:\Q\test>git show master
commit e4731971ab6691513819cc8868771352b8625e1c (HEAD -> master)
Author: Ruffin <ruffin@nowhere.com>
Date:   Mon Sep 18 16:06:28 2017 -0400

    new files

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..14146d1
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1 @@
+*.xml filter=lfs diff=lfs merge=lfs -text
diff --git a/file.bin b/file.bin
new file mode 100644
index 0000000..4f1b470
--- /dev/null
+++ b/file.bin
@@ -0,0 +1,10 @@
+ Volume in drive C is OSDisk^M
+ Volume Serial Number is ACD9-D7F6^M
+^M
+ Directory of C:\Q\test^M
+^M
+09/18/2017  04:06 PM    <DIR>          .^M
+09/18/2017  04:06 PM    <DIR>          ..^M
+09/18/2017  04:06 PM                 0 file.bin^M
+               1 File(s)              0 bytes^M
+               2 Dir(s)  56,075,571,200 bytes free^M
diff --git a/file.xml b/file.xml
new file mode 100644
index 0000000..0e416e4
--- /dev/null
+++ b/file.xml
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:34510fd5ae29e72e58de0864b0f7fa5413e915939ba70741f355f9ba3abba276
+size 377

============================================================
**C:\Q\test>git lfs env**
git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73)
git version 2.13.3.windows.1

LocalWorkingDir=C:\Q\test
LocalGitDir=C:\Q\test\.git
LocalGitStorageDir=C:\Q\test\.git
LocalMediaDir=C:\Q\test\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Q\test\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Q\test\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by technoweenie** [comment]
It works like the other `--include` or `--exclude` flags, which allow a comma separated list. Also, you probably want to include the wildcard `*` too.

```sh
$ git lfs migrate import --include="*.bin,*.xml"
```

**Comment by cmruffin** [comment]
@technoweenie thanks I'll try that.  Seems the documentation for git lfs migrate needs an update if that is the case.  Current documentation references these which imply a one-per-argument model:

`git lfs migrate import --include="*.mp3" --include="*.psd"
`

```
The following configuration:

  --include-ref=refs/heads/my-feature
  --include-ref=refs/heads/master
  --exclude-ref=refs/remotes/origin/master

Would, therefore, include commits: F, E, D, C, B, but exclude commit A.
```

**Comment by discordianfish** [comment]
My 2 cent: To improve the UX I think git-lfs should either support multiple --include arguments or error if they are given. I came here wondering why only some files were included..
