### ISSUE TITLE
GIT_LFS_PROGRESS's <current>/<total files> is wrong

### ISSUE THREAD

**Issue by joshaber** [git-lfs/git-lfs#2599]
Version 2.3.0.

Here are some examples of the progress lines we're getting:

```
download 188/187 16360/32768 005/7.dat
...
download 293/187 400009/1048576 010/4.dat
...
download 372/187 65536/65536 006/16.dat
```

Note that it seems to _start_ at `188` while claiming there are `187` files to download and ends _almost_ 2x the total.

**Comment by technoweenie** [comment]
Posted a fix in https://github.com/git-lfs/git-lfs/pull/2608. Thanks for the report!
