### ISSUE TITLE
Dangling commits and blobs after migrate import

### ISSUE THREAD

**Issue by svendhhh** [git-lfs/git-lfs#2606]
I've run this git lfs migrate command:

    time /cygdrive/c/Program\ Files/git-lfs-windows-amd64-2.3.0/git-lfs migrate import --everything --include="*.psd,*.PSD,*.jpg,*.JPG,*.gif,*.GIF,*.png,*.PNG,*.doc,*.DOC,*.jar,*.JAR,*.dll,*.DLL,*.zip,*.ZIP,*.7z,*.7Z,*.mp3,*.MP3,*.mpg,*.MPG,*.unitypackage,*.UNITYPACKAGE,*.mov,*.MOV,*.avi,*.AVI,*.bmp,*.BMP,*.tga,*.TGA,*.flv,*.FLV,*.gz,*.GZ,*.svg,*.SVG,*.aif,*.AIF,*.ai,*.AI,*.dds,*.DDS,*.eps,*.EPS,*.otf,*.OTF,*.rar,*.RAR,*.wmv,*.WMV,*.ttf,*.TTF,*.tif,*.TIF,*.wav,*.WAV,*.bytes,*.BYTES,*.so,*.SO,*.a,*.A,*.exe,*.EXE"

After `Sorting commits` and `Rewriting commits` were both done, I got a _lot_ of these:

    <branch name>    <hash> -> <hash>

Example:

    master        3d43d133fbbefe154d8f69ed5eb458cbd9e14892 -> 386c2d8111afc40b51ca65bb6051c8609c88e137

I presume this is all "normal", but just explaining it anyway.

After it's completed I ran `git fsck` and it showed a long list of dangling commits and blobs. Example:

    dangling commit 1284e08f8bff6c926b0a57d836502c68491ae691
    dangling blob fe8b00c48b6d0a7ca04a7e8aaf012d57c122c41d

Is this normal? Are they just "backups" of the deleted/changed binaries and commits?
Or is it a sign that something didn't work right?

I've been working with [git-lfs-migrate](https://github.com/bozaro/git-lfs-migrate). It works and seems to remove all binaries (files of the types specified) from history and put them in LFS. However, it takes 6-7 hours to complete. Running the `git lfs migrate` command above completed in only 86 minutes, which made me wonder if it actually did all I would expect. Is it just that much faster than bozaro's tool?

**Comment by technoweenie** [comment]
Dangling git objects is normal after a migration. All migrated blobs are dangling, as well as all commits after the first blob migration. You can run `git prune` to get rid of them, but they also serve as a good backup.

```
master        3d43d133fbbefe154d8f69ed5eb458cbd9e14892 -> 386c2d8111afc40b51ca65bb6051c8609c88e137
```

In the above case, you can reset back to the old state if the import didn't work:

```sh
$ git checkout master
$ git reset --hard 3d43d133fbbefe154d8f69ed5eb458cbd9e14892
```

A safer option may be to create a ref for it:

```sh
$ git checkout 3d43d133fbbefe154d8f69ed5eb458cbd9e14892
$ git branch old-master
```

It looks like `git-lfs-migrate` uses jgit, a git implementation in java. I don't know much about it, other than it's a stable and commonly used git package. So, I find it hard to believe that our version is any faster. I think it'd be worth adding some detailed logging so you can see what files were modified.

**Comment by svendhhh** [comment]
I've been looking at the files migrated:

On the repository output by `git-lfs-migrate`:

    $ git lfs ls-files | wc
    3283    9968  237285

On the repository where I ran `git lfs migrate` (though specifically linking to the git-lfs version provided yourself for issue #2597):

    $ git lfs ls-files | wc
    3301   10027  238539

So it's almost as many files. However, checking the extensions the latter `.wav` and `.zip` which the former is missing, so I'm not sure exactly how it can have more files. I might have to investigate more to verify that the latter has migrated files properly, which I won't have time to do this (4 week) sprint.

But `git lfs ls-files` only shows files in the current checked out commit, right? So I guess it doesn't say much about all binaries in all of history. Anyway, I'll have to leave the conversion project and work on other tasks for a while. Might have another look at this tool when I return, or just continue using `git-lfs-migrate` as I know (pretty certainly) that it works (even if it's slow) :)

Thank you for your feedback and help!

Cheers,
   Svend.

**Comment by technoweenie** [comment]
BTW, you can run `git lfs migrate info` to get a feel for what is still in your repository. It sums up the total size of files by extension. I also experimented with a `--verbose` option to check that the migration is doing its thing: https://github.com/git-lfs/git-lfs/pull/2610. I thought that might help build a little trust that the tool is doing what it should be doing.

Dangling commits and blobs are normal for a migration like this. If there are none, that means you still have refs that point to them, and `git gc/prune` won't ever remove those big files.

**Comment by technoweenie** [comment]
Doh, meant to close this. Sounds like your questions are answered (for now, at least). Feel free to re-comment, or open a new issue later if you have more :wave:
