### ISSUE TITLE
Pushing files fails with "i/o timeout" when file exceed a given size (96MB)

### ISSUE THREAD

**Issue by xenux** [git-lfs/git-lfs#2636]
Pushing on remote server fails with "i/o timeout" when lfs files exceed a given size.

When pushing small files ~1MB, everything works just fine:
[success.txt](https://github.com/git-lfs/git-lfs/files/1347874/success.txt)

When pushing bigger files (here 96MB), it systematically fails:
[io_timeout.txt](https://github.com/git-lfs/git-lfs/files/1347877/io_timeout.txt)

Note: I am using version 2.3.1 of git lfs.

Thank you for the help

**Comment by technoweenie** [comment]
This seems like a network issue connecting to the server. You can try bumping up the timeouts, [as documented here](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn#L32).

**Comment by drowne** [comment]
I have the same issue and it works correctly on lfs 2.2.0. But fails with the io timeout on 2.3.1

**Comment by technoweenie** [comment]
There aren't any significant changes to the HTTP client in LFS 2.3.0. Try bumping some of the timeout settings to see if they help. LFS 2.3.2 will be increasing the default `lfs.activitytimeout` from 10s to 30s: https://github.com/git-lfs/git-lfs/pull/2632.

FWIW: I just completed a full upload and download of a 1GB LFS object with a remote server.

**Comment by drowne** [comment]
I can push large files just fine, in general. But I had the same issue with two specific files. Git will try many times, actually reaching 100% of the upload each time, consistently fail over 6 or 7 attempts.

**Comment by xenux** [comment]
Hi, thanks for the answers.

I tried to bump the timeout, running following cmd `git config -f .lfsconfig lfs.dialtimeout 30` but it doesn't seem to be working. Now I get the following warning:

> WARNING: These unsafe lfsconfig keys were ignored: lfs.dialtimeout

It is the proper way to do?

@drowne I tried to go back to lfs 2.2.0 but unfortunately it didn't solve the problem.

**Comment by technoweenie** [comment]
Try `git config lfs.dialtimeout 30`. Though I'll look at why `lfs.dialtimeout` is considered unsafe too.

**Comment by technoweenie** [comment]
Also, try bumping `lfs.activitytimeout` instead.

**Comment by xenux** [comment]
@technoweenie bumping the activity timeout time with `git config lfs.activitytimeout 30` worked.
Thank you for the help.

**Comment by beac0n** [comment]
I had the same issue, however, the git lfs configs did not work for all cases.
In my case, the problem was an incorrect nginx configuration.

Using
```
proxy_read_timeout      3600;
proxy_connect_timeout   3600;
proxy_redirect          off;
proxy_request_buffering off;
```
in my nginx configuration solved that issue.
It took me a while to figure that out. 
I hope that it will help others who are having the same issue :-).

**Comment by MikeWise2718** [comment]
I am having this issue on about 20 of 1074 files, so I don't want to bump the timeout to 3600 seconds, which seems excessive, and would make testing once a daylong activity. 

It would help to know what the default is, but there is no `lfs.dialtimeout` or `lfs.activitytimeout` value in my config file. So what are the non-configured default values?

**Comment by bk2204** [comment]
The default values for all of these options are [documented in the `git-lfs-config(5)` manual page](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn).

**Comment by smshashi** [comment]
This error was blocking my urgent work, after setting the env variable the issue got resolved: `export GIT_LFS_SKIP_SMUDGE=true`

**Comment by domdorn** [comment]
thx @beac0n, this worked for me!

**Comment by camille-woodside** [comment]
> Also, try bumping `lfs.activitytimeout` instead.

Thank you, yes this `git config lfs.activitytimeout 30` also worked for me too!

**Comment by btsitelashvili** [comment]
> Also, try bumping `lfs.activitytimeout` instead.

Saved my day!
