### ISSUE TITLE
Batch API missing?

### ISSUE THREAD

**Issue by Lantichan** [git-lfs/git-lfs#2638]
Hi, 
today I installed git and git-lfs (2.3.1) managed to get the ssh-authentication working and now am stuck at this issue: 

```
 batch response: Repository or object not found: https://<user>@<server>/var/git/project.git/info/lfs/objects/batch
 Check that it exists and that you have proper access to it
```

Sadly I didn't find anything regarding this issue during an extensive google search, nor did I find any information about the mentioned "batch" object (is it a directory? A file?) in the wiki or any readme, which is why I'm now creating this.

Does anyone has an idea what would be causing this or any hints as to how to solve this? If more info is provided, I'll gladly provide it of course.

**Comment by technoweenie** [comment]
LFS requires an https server to handle requests for storing and retrieving files. By default, it will attempt to guess the LFS server url based on the Git remote. The [server discovery docs](https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md#ssh) have details.

SSH authentication works by writing a custom `git-lfs-authenticate` command that LFS calls through SSH. This is a good spot to return a different URL if you have one setup separately.

**Comment by ttaylorr** [comment]
Hi @Lantichan, I'm going to close this issue since it's been stale for a little while, but please don't hesitate to ping anyone here if you run into further issues in the future and we'd be happy to look into it! ⚡️
