### ISSUE TITLE
"git lfs unlock -i <id>" does not reset readonly file system attribute.

### ISSUE THREAD

**Issue by mrbobbybobberson** [git-lfs/git-lfs#2640]
Hey y'all, our team recently upgraded to git lfs 2.3.0 and are loving the fix for #2494.  Thanks!  A few of my teammates' workflows include unlocking files via id and noticed that unlocking by id doesn't reset the readonly file system attribute.  For example:

1. git lfs lock "foo.png"
    * "foo.png" is now writeable.  Good!
2. git lfs unlock "foo.png"
    * "foo.png" is now readonly.  Good!
3. git lfs lock "foo.png"
    * "foo.png" is now writeable again.  Good!
4. git lfs locks
    * Note down ID of lock.  Let's pretend it's ID:151
5. git lfs unlock -i 151
    * "foo.png" is still writeable.  Not so good.

For now, we're taking the easy workaround of unlocking only by path name, so this isn't very high priority for us, but if a fix for this is feasible, that'd be great!

We're on git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73) and git version 2.14.1.windows.1

**Comment by technoweenie** [comment]
Thanks for the report. Here's a fix: https://github.com/git-lfs/git-lfs/pull/2642, which should go out in LFS 2.3.2 later this week.

**Comment by mrbobbybobberson** [comment]
@technoweenie, that's some fast-fixing.  You rock :)!
