### ISSUE TITLE
"git clone" is slow, but "git lfs clone" makes git think unchanged files are staged or have unstaged changes.

### ISSUE THREAD

**Issue by mrbobbybobberson** [git-lfs/git-lfs#2649]
Hi folks,

I just noticed [2.3.0 release notes](https://github.com/blog/2432-git-lfs-2-3-0-released) say "git clone" with LFS files should be much faster now and that "git lfs clone" is deprecated, but I noticed two things:

1. For me, "git clone" still fetches one LFS'd file at a time in serial, and with 475 or so files, that added up to a long time.

2. Doing "git lfs clone" fetched a handful of LFS'd files at a time in parallel and finished much faster than the regular "git clone" did, but when I was done, doing "git status" showed a whole bunch of staged file edits and a few unstaged file edits.  From what I could tell, the files had populated down correctly from LFS.  I did a "git reset HEAD" and that got "git status" back to normal again.

Any idea if there's a bug here or some sort of user error?

I'm on git version 2.14.1.windows.1 and git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73)

Thanks!

**Comment by technoweenie** [comment]
Yeah, there's a regression with the way `git lfs pull/clone` uses `git update-index` internally. Fix is in https://github.com/git-lfs/git-lfs/pull/2647, and will go out with v2.3.3.

> For me, "git clone" still fetches one LFS'd file at a time in serial, and with 475 or so files, that added up to a long time.

The big changes are dependent on "delay" capabilities being added to Git. I think it'll show up in 2.14.2 or 2.15. At any rate, you're welcome to continue using `git lfs clone`, as it won't be removed until there's a big LFS version jump (to 3.0 or whatever).

**Comment by mrbobbybobberson** [comment]
Cool.  Thanks for the explanation!  I'll go ahead and close this, then.
