### ISSUE TITLE
Files modified after git lfs clone

### ISSUE THREAD

**Issue by nsubiron** [git-lfs/git-lfs#2650]
See sample repo https://bitbucket.org/nsubiron/git-lfs-test

    $ git lfs clone https://bitbucket.org/nsubiron/git-lfs-test
    $ cd git-lfs-test
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes to be committed:
      (use "git reset HEAD <file>..." to unstage)

      modified:   Content/random01.img
      modified:   Content/random02.img
      modified:   Content/random03.img
      modified:   Content/random04.img

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

      modified:   Content/random04.img

When I do a regular clone `git clone ...` everything goes as expected.

On Ubuntu 16.04 (I did git lfs install)

    git-lfs/2.3.2 (GitHub; linux amd64; go 1.8.1)
    git version 2.7.4

**Comment by technoweenie** [comment]
:wave: This is a known issue that started in v2.3.0. Fix is in https://github.com/git-lfs/git-lfs/pull/2647, which will go out with 2.3.3, hopefully today or tomorrow.
