### ISSUE TITLE
smudge error: Error downloading  batch response: Post /objects/batch: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by Morfego** [git-lfs/git-lfs#2652]
Hello i have a problem with downloading. Im using bickbucket and gitextensions. I've merged one branch to master from another pc, and now when i want to checkout to master on main pc I recieve an error:

"C:\Program Files\Git\bin\git.exe" checkout --force -B "master" "MainRepo/master"
Downloading Assets/Scenes/Mission1Enviroment/NavMesh.asset (13.77 KB)
Error downloading object: Assets/Scenes/Mission1Enviroment/NavMesh.asset (f566e3a): Smudge error: Error downloading Assets/Scenes/Mission1Enviroment/NavMesh.asset (f566e3ab8d7a957bea4cc245b58e9ffa2a1c67e5e48abe1a8621f915c07835a1): batch response: Post /objects/batch: unsupported protocol scheme ""

Errors logged to C:\Arena\.git\lfs\objects\logs\20171005T175548.7013448.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Assets/Scenes/Mission1Enviroment/NavMesh.asset: smudge filter lfs failed
Done

Here is log:
[20171005T175548.7013448.log](https://github.com/git-lfs/git-lfs/files/1360068/20171005T175548.7013448.log)

I would be very thankful for help. Cheers

**Comment by technoweenie** [comment]
It looks like your `origin` is not a remote git server (like bitbucket). 

> Post /objects/batch: unsupported protocol scheme ""

You should see something like this:

```sh
$ git lfs env
git-lfs/2.3.2 (GitHub; darwin amd64; go 1.9; git 59a062b1)
git version 2.14.1

Endpoint=https://bitbucket.com/your/repo.git/info/lfs (auth=none)
```

This is a weak point of LFS. A command like `git pull` will eventually call the `smudge` filter during checkout, but without any context of the pull. So, LFS has no idea what remote to use, and defaults to `origin`.

If you have a different setup, you can disable the smudge filter:

```sh
# in your working directory
$ git lfs install --skip-smudge --local
$ git pull
$ git lfs pull # this downloads files and replaces pointers
```
