### ISSUE TITLE
git lfs install

### ISSUE THREAD

**Issue by stevenshine** [git-lfs/git-lfs#2653]
i have finished installing Git  large file on my pc and then how to use   Git  large ?
do u share me more imformations?
i cant start run the softwave on my pc (win 10)
![image](https://user-images.githubusercontent.com/23226663/31308989-c6002546-abb1-11e7-9770-ae56bbfa7b69.png)

**Comment by technoweenie** [comment]
Git LFS is a command line tool that you use in your Git Bash prompt. It's not a windows GUI app, though some (like GitHub Desktop and SourceTree) bundle it.

**Comment by dustinfreeman** [comment]
For the sake of minimizing issue noise, should this issue perhaps be closed?

**Comment by Moustafa-ELwasif** [comment]
lol
