### ISSUE TITLE
Ambiguous refs shouldn't error out

### ISSUE THREAD

**Issue by phord** [git-lfs/git-lfs#2654]
I ran `git-lfs migrate info` on a repo with an ambiguous reference.  Instead of producing anything useful, it only reported "ref ... is ambiguous".

    git lfs migrate info --everything
    ref '66df2eb' is ambiguous...

The problem is that my repo has a ref named `refs/tags/66df2eb`
This seems like it shouldn't be a fatal error.

**Comment by technoweenie** [comment]
Ah, I think this would be solved by including the ref prefixes, disambiguating the ref names.
