### ISSUE TITLE
migrate fails with "argument list too long"

### ISSUE THREAD

**Issue by phord** [git-lfs/git-lfs#2655]
I have a large repo with 45000 refs.  When I first tried to run `git lfs migrate info` on it, it failed with this error:
    $ git lfs migrate info
    migrate: Fetching remote refs: ..., done
    fork/exec /usr/libexec/git-core/git: argument list too long

This is on Ubuntu 17.10 with zsh.

If I include the --everything switch, the command succeeds:
    $ git lfs migrate info --everything
    migrate: Fetching remote refs: ..., done
    migrate: Examining commits:  26% (101830/379598)

**Comment by phord** [comment]
Did some more experimenting.  The error occurs during an internal `git rev-list` command. The difference between the two instances is the one without "--everything" spells out the refs in longhand and includes both tags and tag-treeish references.  For example, the first one does this:

    git rev-list --reverse --topo-order --do-walk ^refs/remotes/origin/master ^refs/tags/sometag1 \
         ^refs/tags/sometag1^{} ^refs/tags/sometag2 ^refs/tags/sometag2^{}  ...

The second one does this instead:

    git rev-list --reverse --topo-order --do-walk master sometag1 sometag2 ...

I don't think "fixing" this by always using the shorter refnames is the right answer, though.  Being smarter about limiting the command line length in general is probably also needed.

**Comment by technoweenie** [comment]
The `info` and `import` subcomands process any unpushed commits when run without any args. That's why the ref prefixes are used. You can run them with `--everything`, or a combination of `--include-ref` and `--exclude-ref` to process or convert only local refs.

That explains why the commands are different. But how can we support an unbound number of refs?

**Comment by phord** [comment]
Well, you could do `git rev-list ... --all` for the `--everything` version, but that still doesn't solve the long-line problem.

You could use `xargs` to automatically limit the arguments to an appropriate size, but there's probably a bit more involved in getting this to work right.

You can break it into multiple invocations keeping your arguments to a shorter length than `kern.argmax`. Or even simpler, just limit it to 1024 or something safe across weirdo OSes and call `git rev-list` a lot.

**Comment by technoweenie** [comment]
Sure, splitting the args for multiple commands is easy. But how can we merge the results into a single list of commits?

Migrating unpushed commits is easier. It wants all commits in reverse topo order that are not in the following refs:

```sh
$ git rev-list --reverse --topo-order --do-walk ^refs/remotes/origin/master
$ git rev-list --reverse --topo-order --do-walk ^refs/tags/sometag1 ^refs/tags/sometag1^{}
$ git rev-list --reverse --topo-order --do-walk ^refs/tags/sometag3 ^refs/tags/sometag4^{}
```

I _think_ it could return just the unique commits from _all_ the commands. 

The `--everything` case is trickier. Each `rev-list` should return a long list of commits that would somehow have to be merged into a single list, retaining the same order.

```sh
$ git rev-list --reverse --topo-order --do-walk master
$ git rev-list --reverse --topo-order --do-walk sometag1 sometag2
$ git rev-list --reverse --topo-order --do-walk sometag3 sometag4
```

Using `git rev-list --all` may be the best solution.
