### ISSUE TITLE
migrate shouldn't fetch or reach out to the remote at all without permission

### ISSUE THREAD

**Issue by phord** [git-lfs/git-lfs#2656]
lfs migrate first tries to `git fetch origin`.  This means it doesn't work at all if I'm offline.

    $ GIT_TRACE=2 git -C pure_tools.git lfs migrate info
     'git' version
     'git' config -l
     'git' ... rev-parse HEAD --symbolic-full-name HEAD
     'git' ... rev-parse master --symbolic-full-name master
     'git' ... fetch origin
     migrate: Fetching remote refs: ..., done

I should be able to run `git lfs migrate info` locally without bothering my remote server.

**Comment by technoweenie** [comment]
Without args, `info` and `import` are processing _unpushed_ commits. The `fetch` is used to ensure you don't rewrite anything already pushed, requiring a force push on your remote.

You can use `--everything` to scan all local refs, or `--include-rev` and `--exclude-ref` to control what refs are analyzed or rewritten.

That said, I'd accept a PR for a flag that disables this check.

**Comment by phord** [comment]
How can I have something in my repo I already pushed if the remote ref is not also updated? Are you worried I pushed it from a different local copy of the repo, or maybe I have something in my repo I imported with git-apply?

Ok, I can see that happening.  But it seems like the unusual use case.
