### ISSUE TITLE
Git can't resolve ref: "HEAD"

### ISSUE THREAD

**Issue by butterpuf** [git-lfs/git-lfs#2662]
Hi

I am trying to clone an old repository. Its giving me the following error on the log:

```
$ git-lfs clone --recursive --progress --progress -- http://git.discretelogix.org/root/flashcards-for-kids-ios-app.git /Users/BAG/Projects/iOS/ESL/flashcards-for-kids-ios-app
Could not pull

Git can't resolve ref: "HEAD"
```

I also tried to download the code from git.discretelogix.org but it gives me the following:

`{"RepoPath":"/home/git/repositories/root/flashcards-for-kids-ios-app.git","ArchivePrefix":"flashcards-for-kids-ios-app-master-710c025d5b5cb986414e0c6992446ba01d7b7459","ArchivePath":"/home/git/gitlab/shared/cache/archive/flashcards-for-kids-ios-app.git/flashcards-for-kids-ios-app-master-710c025d5b5cb986414e0c6992446ba01d7b7459.zip","CommitId":"710c025d5b5cb986414e0c6992446ba01d7b7459"}`

What should I do!!

Regards

**Comment by technoweenie** [comment]
What version of LFS are you on? That error message looks like you're cloning down an empty repository. We fixed that in [v2.3.1](https://github.com/git-lfs/git-lfs/releases/tag/v2.3.1). An empty repository is not a problem -- if that's what you expect. But if you're expecting repository data, and `git lfs clone` isn't fetching it, then you should confirm the content is on your git host.

No idea on that error from your git host, unfortunately. That's not a git error, it looks like it's unique to that service.

**Comment by butterpuf** [comment]
The version is: git-lfs/2.3.3

I have tried git lfs clone. Its saying:

```
fatal: 'root/flashcards-for-kids-ios-app.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error(s) during clone:
git clone failed: exit status 128
```

**Comment by technoweenie** [comment]
Does `git clone` work? This doesn't look like an LFS issue.

**Comment by butterpuf** [comment]
Sorry I was doing a mistake that i am using ssh link and i did not generate the rss key/pair. 

Now used http link and git lfs clone result:

 ```
git lfs clone http://git.discretelogix.org/root/flashcards-for-kids-ios-app.git
Cloning into 'flashcards-for-kids-ios-app'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```

here is git clone:


```
BAG:ESL BAG$ git clone http://git.discretelogix.org/root/flashcards-for-kids-ios-app.git
Cloning into 'flashcards-for-kids-ios-app'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```

Just to make sure i have attached screen of my git console. My repo do have commits and master branch!

<img width="1017" alt="screen shot 2017-10-14 at 8 56 28 am" src="https://user-images.githubusercontent.com/4945978/31572406-e3d6dfbc-b0be-11e7-9635-c9b6f5ce6464.png">

**Comment by butterpuf** [comment]
Any idea why my git is empty?

**Comment by technoweenie** [comment]
It looks like something is wrong on your Git host. You'll have to file an issue with them.

**Comment by butterpuf** [comment]
hmmm. ok Thanks

**Comment by MarkEWaite** [comment]
I had a similar message occur on the agents I was using for continuous integration.  In my case, the solution was to run `git lfs install` so that the LFS configuration entries were added to the `~/.gitconfig` file.  That may be very specific to my case, but I offer it here just in case someone else might benefit from the same relatively simple workaround.
