### ISSUE TITLE
.gitattributes filters don't seem to apply cleanly when a git operation is not run in repo root

### ISSUE THREAD

**Issue by kavehv** [git-lfs/git-lfs#2663]
When you run an operation that touches an LFS file from a directory that is not the git repository's root, it seems to leave LFS files in an unclean state when you run `git status`, even though they have not actually changed.  I've seen the same thing happen when we run `git -C <path>` as well.  It seems that whatever LFS relies on to run its filters seems to do it from the current working directory.

**Comment by kavehv** [comment]
This seems to be fixed in 2.3.3

**Comment by technoweenie** [comment]
Er yup! A change in v2.3.0 disabled the git clean filter on `git update-index` calls, causing this bug. It's fixed in v2.3.3, and the test suite asserts a clean status after `lfs pull` and `lfs clone` commands.
