### ISSUE TITLE
LFS: Authorization error - git-lfs or node-git-lfs at fault?

### ISSUE THREAD

**Issue by oset-bschuhma** [git-lfs/git-lfs#2664]
First - I apologize for creating an "issue" out of this, but I don't know where to find anyone who can help with this.  If there's a better place, please direct me and we can close this.  
Second - thanks for your time!

I'm new to git-lfs and I'm trying to use node-git-lfs to store large files on S3. (Other git-lfs S3 solutions gladly accepted) I believe it's all configured properly and did a push...I'm asked for credentials and I put in my (working) github credentials.  I have 4 files totaling 2.4Gb... they upload, then fail, with this error:

trace git-lfs: tq: retrying object 122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d: LFS: Authorization error: https://github.com/TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d
Check that you have proper access to the repository

So my question... can anyone tell me if this is git-lfs or node-git-lfs causing problems?  Is it a simple config issue where I should've used ssh or https instead of http (yes, I know http is insecure, but apparently I can't even get THAT running).

Thanks,

Bret

Trace, env, etc. below:

Here's a trace:
Git LFS: (0 of 4 files) 0 B / 2.40 GB                              trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526
> PUT /TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526 HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 368050176
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d
> PUT /TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 368050176
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5
> PUT /TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5 HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 369098752
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
trace git-lfs: tq: enqueue retry #1 for "72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5" (size: 369098752)
trace git-lfs: tq: sending batch of size 4
trace git-lfs: api: batch 4 files
trace git-lfs: creds: git credential fill ("http", "localhost:3000", "TrustTheVote-Project/DeviceManager")
Username for 'http://localhost:3000': oset-bschuhma  <<<<<<<<//my github credentials
Password for 'http://oset-bschuhma@localhost:3000': <<<<<<<<//passed through the local lfs server
trace git-lfs: Filled credentials for http://localhost:3000/TrustTheVote-Project/DeviceManager
trace git-lfs: HTTP: POST http://localhost:3000/TrustTheVote-Project/DeviceManager/objects/batch
> POST /TrustTheVote-Project/DeviceManager/objects/batch HTTP/1.1
> Host: localhost:3000
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 403
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
{"operation":"upload","objects":[{"oid":"56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd","size":1469054976},{"oid":"72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5","size":369098752},{"oid":"122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d","size":368050176},{"oid":"e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526","size":368050176}]}trace git-lfs: HTTP: 200

< HTTP/1.1 200 OK
< Content-Length: 1646
< Connection: keep-alive
< Content-Type: application/vnd.git-lfs+json; charset=utf-8
< Date: Thu, 12 Oct 2017 18:20:41 GMT
< Etag: W/"66e-M3/DbJNMjOhmAl8DyegYbQ"
< X-Powered-By: Express
< 
trace git-lfs: HTTP: {"objects":[{"oid":"56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd","size":1469054976,"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd","header":{"Authorization":"TODO"}},"verify":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}},{"oid":"72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5","size":369098752,
{"objects":[{"oid":"56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd","size":1469054976,"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd","header":{"Authorization":"TODO"}},"verify":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}},{"oid":"72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5","size":369098752,trace git-lfs: HTTP: "actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5","header":{"Authorization":"TODO"}},"verify":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}},{"oid":"122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d","size":368050176,"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d","header":{"Authorization":"TODO"}},"verify":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}},{"oid":"e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526","size":368050176,"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526","header":{"Authorization":"TODO"}},"verify":{"href"
"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5","header":{"Authorization":"TODO"}},"verify":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}},{"oid":"122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d","size":368050176,"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d","header":{"Authorization":"TODO"}},"verify":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}},{"oid":"e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526","size":368050176,"actions":{"upload":{"href":"https://github.com/TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526","header":{"Authorization":"TODO"}},"verify":{"href"trace git-lfs: HTTP: :"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}}]}
:"https://github.com/TrustTheVote-Project/DeviceManager/objects/verify","header":{"Authorization":"TODO"}}}}]}trace git-lfs: tq: starting transfer adapter "basic"
Git LFS: (0 of 4 files) 0 B / 2.40 GB                              trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd
> PUT /TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 1469054976
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
Git LFS: (0 of 4 files) 0 B / 2.40 GB                              trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d
trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5
> PUT /TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 368050176
> Content-Type: application/octet-stream
> PUT /TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5 HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 369098752
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
trace git-lfs: HTTP: PUT https://github.com/TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526
> 
> PUT /TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526 HTTP/1.1
> Host: github.com
> Authorization: TODO
> Content-Length: 368050176
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
> 
Git LFS: (0 of 4 files) 55.68 KB / 2.40 GB                         trace git-lfs: HTTP: 413

< HTTP/1.1 413 Request Entity Too Large
< Content-Length: 192
< Content-Type: text/html
< Date: Thu, 12 Oct 2017 18:20:47 GMT
< Server: GitHub.com
< X-Frame-Options: DENY
< X-Github-Request-Id: A766:20FD2:2D3831A:48C88F1:59DFB27F
< 
trace git-lfs: tq: retrying object 56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd: LFS: Client error: https://github.com/TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd from HTTP 413
trace git-lfs: tq: enqueue retry #2 for "56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd" (size: 1469054976)
Git LFS: (0 of 4 files) 1013.24 MB / 2.40 GB                       trace git-lfs: HTTP: 403

< HTTP/1.1 403 Forbidden
< Transfer-Encoding: chunked
< Cache-Control: no-cache
< Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 12 Oct 2017 18:46:28 GMT
< Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
< Server: GitHub.com
< Set-Cookie: _gh_sess=eyJzZXNzaW9uX2lkIjoiMWZlOGUyYmMxNDRhZTEyZDNlZjEyYWIyZDM2MjVhYjgiLCJsYXN0X3dyaXRlIjoxNTA3ODMzOTg4NDIzfQ%3D%3D--d0b990838e40c596785afc4364c20db7c558545e; path=/; secure; HttpOnly
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< Vary: X-PJAX
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Request-Id: B316:20FD5:1D206F8:37E2203:59DFB27F
< X-Request-Id: e3c0e046a74ef5de3d174bbe3a6fda80
< X-Runtime: 0.006159
< X-Runtime-Rack: 0.011655
< X-Ua-Compatible: IE=Edge,chrome=1
< X-Xss-Protection: 1; mode=block
< 
trace git-lfs: tq: retrying object 122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d: LFS: Authorization error: https://github.com/TrustTheVote-Project/DeviceManager/objects/122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d
Check that you have proper access to the repository
trace git-lfs: tq: enqueue retry #2 for "122a68cbff36319b26ed5644a98024030c3a57d631be72d18180faedeefe1a2d" (size: 368050176)
Git LFS: (0 of 4 files) 688.07 MB / 2.40 GB                        trace git-lfs: HTTP: 403

< HTTP/1.1 403 Forbidden
< Transfer-Encoding: chunked
< Cache-Control: no-cache
< Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 12 Oct 2017 18:47:05 GMT
< Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
< Server: GitHub.com
< Set-Cookie: _gh_sess=eyJzZXNzaW9uX2lkIjoiY2JkMjE0OGRjOWM5ZDRhZjBmMDdhYmQ1N2Q5NTgxMDkiLCJsYXN0X3dyaXRlIjoxNTA3ODM0MDI1NTE3fQ%3D%3D--4e17cd6d2b62ad209f7868cd85786b1ffd6653d0; path=/; secure; HttpOnly
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< Vary: X-PJAX
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Request-Id: B318:20FD0:2050196:34F178C:59DFB27F
< X-Request-Id: 2cbf6a4bd0b51ed887e849ee84bae297
< X-Runtime: 0.010017
< X-Runtime-Rack: 0.017644
< X-Ua-Compatible: IE=Edge,chrome=1
< X-Xss-Protection: 1; mode=block
< 
trace git-lfs: tq: retrying object e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526: LFS: Authorization error: https://github.com/TrustTheVote-Project/DeviceManager/objects/e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526
Check that you have proper access to the repository
trace git-lfs: tq: enqueue retry #2 for "e0186ae7e0d47e4494ad030103c04a3960596d0658368fad5cab567015b93526" (size: 368050176)
Git LFS: (0 of 4 files) 352.00 MB / 2.40 GB                        trace git-lfs: HTTP: 403

< HTTP/1.1 403 Forbidden
< Transfer-Encoding: chunked
< Cache-Control: no-cache
< Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 12 Oct 2017 18:47:28 GMT
< Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
< Server: GitHub.com
< Set-Cookie: _gh_sess=eyJzZXNzaW9uX2lkIjoiMjNhNTczNDU5NDc1NDE5OWEzODhiOWJjNDRjNGExYjUiLCJsYXN0X3dyaXRlIjoxNTA3ODM0MDQ4ODg2fQ%3D%3D--4deafb25db995f90c8ea94cca287398b138bc696; path=/; secure; HttpOnly
< Status: 403 Forbidden
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< Vary: X-PJAX
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Request-Id: B314:20FD2:2D38368:48C8975:59DFB27F
< X-Request-Id: ec6c189863aa1db23026faa578d71064
< X-Runtime: 0.006043
< X-Runtime-Rack: 0.012245
< X-Ua-Compatible: IE=Edge,chrome=1
< X-Xss-Protection: 1; mode=block
< 
trace git-lfs: tq: retrying object 72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5: LFS: Authorization error: https://github.com/TrustTheVote-Project/DeviceManager/objects/72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5
Check that you have proper access to the repository
trace git-lfs: tq: enqueue retry #2 for "72673d31d9ba58737fdc23fe7619e0fc2c832df4d2eeccf23ee09541dfc64ec5" (size: 369098752)
trace git-lfs: tq: sending batch of size 4
trace git-lfs: api: batch 4 files
trace git-lfs: creds: git credential fill ("http", "localhost:3000", "TrustTheVote-Project/DeviceManager")
Username for 'http://localhost:3000': 

[bret@OSETDev OSET]$ git config -l
http.postbuffer=157286400
user.email=bret@osetfoundation.org
user.name=Bret Schuhmacher
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.oset-dm.fetch=+refs/heads/*:refs/remotes/oset-dm/*
remote.oset-dm.pushurl=git@github.com:TrustTheVote-Project/DeviceManager
remote.oset-dm.url=git@github.com:TrustTheVote-Project/DeviceManager
branch.master.remote=oset-dm
branch.master.merge=refs/heads/master
lfs.http://localhost:3000.locksverify=false
lfs.https://github.com/TrustTheVote-Project/DeviceManager.git/info/lfs.access=basic
lfs.http://localhost:3000/TrustTheVote-Project/DeviceManager.access=basic

[bret@OSETDev OSET]$ git lfs env
git-lfs/2.3.1 (GitHub; linux amd64; go 1.9; git 01fef48f)
git version 2.13.5

Endpoint=http://localhost:3000/TrustTheVote-Project/DeviceManager (auth=basic)
Endpoint (oset-dm)=https://github.com/TrustTheVote-Project/DeviceManager.git/info/lfs (auth=basic)
  SSH=git@github.com:TrustTheVote-Project/DeviceManager
LocalWorkingDir=/opt/OSET
LocalGitDir=/opt/OSET/.git
LocalGitStorageDir=/opt/OSET/.git
LocalMediaDir=/opt/OSET/.git/lfs/objects
LocalReferenceDir=
TempDir=/opt/OSET/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/opt/OSET/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by technoweenie** [comment]
URLs like this look strange:

> https://github.com/TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd

Based on your config, I'm guessing this is your local node-git-lfs server? If so, that 403 error needs to be resolved on the server end. Ensure your credentials for your node server are correct. This doesn't look like a client side issue.

**Comment by oset-bschuhma** [comment]
Thanks for the reply!  Can you tell me what looks odd about that URL, please?  I don't know what it's missing or should look like, unfortunately.

When you say "on the server end" it's a little confusing - do you mean the node-git-lfs server or the Github.com server?  I know you wrote "Ensure your credentials for your node server are correct.", but I have already checked those.  I've put my github credentials in for that (assuming it's going to pass those to github when the time comes).  I'm also typing my github credentials when prompted by git-lfs. I've tried typing in junk for those creds to see if it's authenticating with github and yes, it does (i.e. appropriate errors when I give junk credentials).

Thanks again! :-)

**Comment by oset-bschuhma** [comment]
Should I be worried about the HTTP 413 errors or is that to be expected?

< HTTP/1.1 413 Request Entity Too Large
< Content-Length: 192
< Content-Type: text/html
< Date: Fri, 13 Oct 2017 13:35:57 GMT
< Server: GitHub.com
< X-Frame-Options: DENY
< X-Github-Request-Id: CAA4:1A2E:3043B7:54CEB5:59E0C13D

Should I be concerned with github closing the connection?
trace git-lfs: tq: retrying object 56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd: LFS: Client error: https://github.com/TrustTheVote-Project/DeviceManager/objects/56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd from HTTP 413
trace git-lfs: tq: enqueue retry #1 for "56a43b04d1461b1d44025c8cc18e9495c1efc6b4dade1fcf21d195908c3e77fd" (size: 1469054976)
Git LFS: (0 of 4 files) 605.54 MB / 2.40 GB                        Connection to github.com closed by remote host.

Why am I talking so much to GitHub?  Seems like I'd be pushing a tiny, pointer file to GitHub and be spending all my time pushing to S3.  I must have node-git-lfs misconfigured...  Unfortunately the documentation for it is minimal and there's no one to talk to. :-(

Thanks!

**Comment by technoweenie** [comment]
> Thanks for the reply! Can you tell me what looks odd about that URL, please? I don't know what it's missing or should look like, unfortunately.

You can't download LFS objects from a URL like that. All LFS API calls will start with `https://github.com/TrustTheVote-Project/DeviceManager.git/info/lfs` (which you can see from your `git lfs env` output). The actual URLs for the objects will be S3 though. It looks like `node-git-lfs` is returning bad urls. You'll have to follow up with that project.

To compare, here's what LFS against GitHub's LFS server looks like:

```
# output cleaned up for clarity:
POST /github/git-lfs-test.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 641
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.3.2 (GitHub; darwin amd64; go 1.9; git 59a062b1)
>
{ "operation":"download",
  "objects": [{
    "oid":"b9f86fab477109565871ced361ba69f2425a91fbe6057fa7a9629a8d536d7c71",
    "size":689867
  }]
}

< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Fri, 13 Oct 2017 15:58:56 GMT
< Server: GitHub.com
< Status: 200 OK
<
{ "objects": [{
    "oid":"b9f86fab477109565871ced361ba69f2425a91fbe6057fa7a9629a8d536d7c71",
    "size":689867,
    "actions": {
      "download": {
        "href":"https://github-cloud.s3.amazonaws.com/alambic/media/111976139/b9/f8/b9f86fab477109565871ced361ba69f2425a91fbe6057fa7a9629a8d536d7c71?X-Amz-Algorithm=AWS4-HMAC-SHA256...",
        "expires_at":"2017-10-13T16:58:56Z",
        "expires_in":3600
      }
    }]
}
```

**Comment by oset-bschuhma** [comment]
Thanks very much (again) for your time! :-)  I appreciate the nudges in the
right direction :-)

Best regards,

Bret


Regards,

Bret
--
Bret Schuhmacher | Sr. Member of Technical Staff | OSET Institute | Mobile:
865.257.9856 | Main: 650.600.1450
