### ISSUE TITLE
warning: filter.lfs.smudge has multiple values

### ISSUE THREAD

**Issue by BruceGreene** [git-lfs/git-lfs#2665]
I upgraded to the new GitHub Desktop app on Windows 7 and now receive this message each time that I start the app...

> Error running git [config --global filter.lfs.smudge git-lfs smudge -- %f]: 'warning: filter.lfs.smudge has multiple values
> error: cannot overwrite multiple values with a single value
>        Use a regexp, --add or --replace-all to change filter.lfs.smudge.' 'exit status 5'
> Run `git lfs install --force` to reset git config.

**Comment by technoweenie** [comment]
Fixed in https://github.com/git-lfs/git-lfs/pull/2659. We'll ship LFS v2.3.4 next week and will notify the GH Desktop team immediately.
