### ISSUE TITLE
cannot spawn .git/hooks/pre-push: No such file or directory

### ISSUE THREAD

**Issue by Morfego** [git-lfs/git-lfs#2667]
Hi folks, im having a little trouble with pushing. I've created new branch, as always form bickbucket, and when I was working on it I had internet problems (I was offline at that time). So I've commited some of my changes and couldn't push it to bickbucket. Then I've made a second local commit and my internet started working again so I've wanted to push my changes to server. Unluckly I had error:

"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "MainRepo" refs/heads/CreatingMission2Gameplay:refs/heads/CreatingMission2Gameplay
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://MyProject@bitbucket.org/MyProject/MyProject.git'
Done 

I've fetched all before trying again still I doesn't work. Thanks for help and cheers.

**Comment by technoweenie** [comment]
Ah, that looks like Git LFS isn't installed properly. What's in `.git/hooks/pre-push`? Is `git-lfs` in your system path? How did you install LFS?

**Comment by Morfego** [comment]
Just by ctrl + G, "git lfs install". But i have problems with it. Like for example after my mate upload his stuff to master i have to open git bash and type "git lfs fetch" to download those files. I dont know if its connected to this problem tho. Should I reinstal LFS in some specific way?

**Comment by technoweenie** [comment]
Yes, that sounds like something isn't set up correctly. You can confirm by checking your git config:

```sh
# this is also shown at the bottom of 'git lfs env'
$ git config --get-regexp "filter.lfs"
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge -- %f
filter.lfs.process git-lfs filter-process
filter.lfs.required true
```

That config means Git will call `git-lfs smudge -- %f` or `git-lfs filter-process` to automatically replace LFS objects when cloning or pulling down changes from your remote. Without those config values, Git will do nothing, and you'll have to run `git lfs pull` manually.

Now, sometimes people will run `git lfs install --skip-smudge` to purposely skip the download. There are some filter performance issues in older versions of git. As of Git v2.14.2 and LFS v2.3.3, you shouldn't need `git lfs install --skip-smudge` anymore.

**Comment by Morfego** [comment]
$ git config --get-regexp "filter.lfs"
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge -- %f
filter.lfs.required true
filter.lfs.process git-lfs filter-process
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge -- %f
filter.lfs.process git-lfs filter-process
filter.lfs.required true
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge --skip -- %f
filter.lfs.process git-lfs filter-process --skip
filter.lfs.required true
This is what i got

**Comment by technoweenie** [comment]
Ok, you're seeing the config values multiple times since they're declared at different configuration levels. For Git, the 3 main ones are:

* system - The config values are set system wide, and require admin privs to change.
* global - The config values are set in your home directory, and affect git operations for just your user account.
* local - The config values are applied to a specific repository locally.

The lower values override higher values, so it looks like you ran `git lfs install --skip-smudge --local`, disabling the smudge filter. If you run `git lfs install --local --force`, it'll fix this right up, so you won't need to run `git lfs pull` after pulling changes down.

Now, back to the original issue :) What's in `.git/hooks/pre-push` in the repository causing problems?

**Comment by technoweenie** [comment]
I saw something similar at https://github.com/desktop/desktop/issues/3067. I think my colleague shiftkey has the answer: https://github.com/desktop/desktop/issues/3067#issuecomment-337134185

> Under the section "WHY WON’T GIT HOOKS WORK ON WINDOWS?", we have this section:
>
>> On Unix-like OS’s, the `#!` tells the program loader that this is a script to be interpreted, and `/bin/sh` is the path to the interpreter you want to use, sh in this case. Windows is definitely not a Unix-like OS. Git for Windows supports Bash commands and shell scripts via Cygwin. By default, what does it find when it looks for sh.exe at `/bin/sh`? Yup, nothing; nothing at all.
What's the fix?
> 
> Fix it by providing the path to the sh executable on your system.
As a workaround, these scripts can directly reference your Git installation, like so:
> 
>     #!C:/Program\ Files/Git/usr/bin/sh.exe

**Comment by Morfego** [comment]
Here is my PrePush, I don't know if its either empty or i dont have program to open it. So I need to type path to sh.exe in PrePush, right?
Btw. thanks for solving my side problem with lfs pull :)
Cheers.

**Comment by technoweenie** [comment]
There's nothing in that file. It should be a small text file that you can open in any text editor. The weird thing is the file takes up 270 bytes, so _something_ is in there. `hexdump` just shows a lot of blank space in it:

```sh
$ hexdump pre-push
0000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000100 00 00 00 00 00 00 00 00 00 00 00 00 00 00
000010e
```

For example, here's the standard hook that LFS installs:

```sh
# contents start at '#!'
$ cat .git/hooks/pre-push
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

Git _should_ ignore an empty `.git/hooks/pre-push` file. It worked just fine on my macbook. This could be something different with Git for Windows. You can run `git lfs update` in your repository directory to fix it.

```sh
# notice how it attempts to show invisible data :)
$ git lfs update
Hook already exists: pre-push



To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.

# Follow the directions...
$ git lfs update --force
Updated git hooks.

# good to go
$ cat .git/hooks/pre-push
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

**Comment by Morfego** [comment]
Thanks a lot for your hard work, I really appreciate your help. It's seems to be working fine for now. Once again big thanks, your best man!

**Comment by technoweenie** [comment]
Cool, glad you got it working. What ended up being the solution?

**Comment by samizzo** [comment]
I was getting this too - my hooks files were full of nothing and SourceTree was failing to install git lfs. I don't know why it happened but I suspect it was something to do with SourceTree. To fix it I removed the hook files, touched them to recreate them as empty files, then re-ran SourceTree and it reinitialised git lfs correctly.

**Comment by Reidond** [comment]
> Cool, glad you got it working. What ended up being the solution?

my solution was `git lfs update --force`

**Comment by sarajujeczka** [comment]
I had the same error when I tried to push some changes through Sourcetree on Windows. 
I had two files in .git/hooks called "pre-push", one without a file extension that Notepad++ couldn't read, and second with a "sample" file extension that Nodepad could read. I deleted the first file (without the extension), and I deleted the extension of the second file. Right now it's working fine.

**Comment by GlassBeaver** [comment]
same here - my problem was a BSOD in windows 10 corrupting some recently used files, among which was pre-push

**Comment by AndyKD** [comment]
If you are using Android studio, its easy, just un-check "Run Git hooks" 

![image](https://user-images.githubusercontent.com/6467643/85266688-d67d1280-b491-11ea-847e-9533931b0e9b.png)

**Comment by AliShug** [comment]
Power outage corrupted my pre-push! Solution for me was `git lfs update --force`

**Comment by EngrEric** [comment]
I solved this issue by navigating to .git/hooks with `cd .git/hooks`
Then remove the existing pre-push with ` rm pre-push`
then run `git lfs update --force`
