### ISSUE TITLE
[[:space:]] seam to prevent Git lfs to work with SourceTree

### ISSUE THREAD

**Issue by thortillas** [git-lfs/git-lfs#2668]
Hi!

We started to use Git lfs some days ago and we wanted to configure it to control which files are selected to go to LFS and which should stay on git.

Here is our test hierarchy:
```
Fake Folder/bigPicture.jpg
Fake Folder/SomeOtherFake/bigPicture.jpg
Fake Folder/SomeOtherFake/LastFake/bigPicture.jpg
Fake Folder/[braketFolder]/bigPicture.jpg
Fake Folder/[braketFolder]/SomeUnderBraket/bigPicture.jpg
```

Let say we want to put on LFS the files under the braketFolder and the ones under SomeOtherFake. But not the one under the other subfolder of "Fake Folder". 

We did try some lfs pathes and the results surprised us:
1) If you remove the space between Fake and Folder on the first folder name, we were able to match any file we wanted (regardless of the braket folder). Our final .gitAttributes should be something like:
```
FakeFolder/[braketFolder]/*.jpg
FakeFolder/[braketFolder]/**/*.jpg
FakeFolder/SomeOtherFake/*.jpg
FakeFolder/SomeOtherFake/**/*.jpg
```

-> We were surprised that we add to add the first line. By reading the documentation we were thinking that ** should also target the file under the braketfolder. Is that normal?

2) As soon as we add the space between Fake and Folder, nothing work anymore. Our gitattributes contains the following lines:
```
Fake[[:space:]]Folder/[braketFolder]/*.jpg
Fake[[:space:]]Folder/[braketFolder]/**/*.jpg
Fake[[:space:]]Folder/SomeOtherFake/*.jpg
Fake[[:space:]]Folder/SomeOtherFake/**/*.jpg
```

Does anybody know why? or what are we doing wrong?

Thanks for reading!

Cheers,
Florian.

**Comment by technoweenie** [comment]
Git requires spaces in `.gitattributes` patterns to be represented as `[[:space:]]`. It's not really mentioned in docs, so the best reference that isn't source code I can find is https://stackoverflow.com/questions/18864698/whitespace-in-gitattributes-patterns.

I did experiment with this setup. The best way to see how Git behaves with these attributes is to try it out:

```sh
$ git lfs track "Fake Folder/[bracketfolder]/**/*.txt"
Tracking "Fake Folder/[bracketfolder]/**/*.txt"
$ git lfs track "Fake Folder/otherfake/**/*.txt"
Tracking "Fake Folder/otherfake/**/*.txt"

$ echo "hi" > Fake\ Folder/hi.txt
$ echo "hi" > Fake\ Folder/\[bracketfolder\]/hi.txt
$ echo "hi" > Fake\ Folder/\[bracketfolder\]/foo/hi.txt
$ echo "hi" > Fake\ Folder/otherfake/foo/hi.txt
$ echo "hi" > Fake\ Folder/otherfake/hi.txt
$ git add .
$ git commit -m "add"
```

After making the commit, run `git show` to see what was added as a Git object, and what was added as an LFS object.

```sh
$ git show
commit 5a44c6fd939236c48f50a03facf05777162e06d2 (HEAD -> master)
Author: rick olson <technoweenie@gmail.com>
Date:   Mon Oct 16 10:57:56 2017 -0600

    add

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..29f1292
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,2 @@
+Fake[[:space:]]Folder/[bracketfolder]/**/*.txt filter=lfs diff=lfs merge=lfs -text
+Fake[[:space:]]Folder/otherfake/**/*.txt filter=lfs diff=lfs merge=lfs -text
diff --git a/Fake Folder/[bracketfolder]/foo/hi.txt b/Fake Folder/[bracketfolder]/foo/hi.txt
new file mode 100644
index 0000000..45b983b
--- /dev/null
+++ b/Fake Folder/[bracketfolder]/foo/hi.txt
@@ -0,0 +1 @@
+hi
diff --git a/Fake Folder/[bracketfolder]/hi.txt b/Fake Folder/[bracketfolder]/hi.txt
new file mode 100644
index 0000000..45b983b
--- /dev/null
+++ b/Fake Folder/[bracketfolder]/hi.txt
@@ -0,0 +1 @@
+hi
diff --git a/Fake Folder/hi.txt b/Fake Folder/hi.txt
new file mode 100644
index 0000000..45b983b
--- /dev/null
+++ b/Fake Folder/hi.txt
@@ -0,0 +1 @@
+hi
diff --git a/Fake Folder/otherfake/foo/hi.txt b/Fake Folder/otherfake/foo/hi.txt
new file mode 100644
index 0000000..90353d7
--- /dev/null
+++ b/Fake Folder/otherfake/foo/hi.txt
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
+size 3
diff --git a/Fake Folder/otherfake/hi.txt b/Fake Folder/otherfake/hi.txt
new file mode 100644
index 0000000..90353d7
--- /dev/null
+++ b/Fake Folder/otherfake/hi.txt
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
+size 3
```

So, based on these patterns added through `git lfs track`:

* `"Fake Folder/[bracketfolder]/**/*.txt"`
* `"Fake Folder/otherfake/**/*.txt"`

Which leads to this `.gitattributes` file:

```
Fake[[:space:]]Folder/[bracketfolder]/**/*.txt filter=lfs diff=lfs merge=lfs -text
Fake[[:space:]]Folder/otherfake/**/*.txt filter=lfs diff=lfs merge=lfs -text
```

These files were stored as LFS objects: 

* `Fake Folder/otherfake/hi.txt`
* `Fake Folder/otherfake/foo/hi.txt`

These were not:

* `Fake Folder/hi.txt`
* `Fake Folder/[bracketfolder]/hi.txt`
* `Fake Folder/[bracketfolder]/foo/hi.txt`

My hunch is the brackets are messing things up. So, I tried escaping the brackets in the `.gitattributes` file, and it tracked all of the files except `Fake Folder/hi.txt`.

```
Fake[[:space:]]Folder/\[bracketfolder\]/**/*.txt filter=lfs diff=lfs merge=lfs -text
Fake[[:space:]]Folder/otherfake/**/*.txt filter=lfs diff=lfs merge=lfs -text
```

Unfortunately, `git lfs track` will convert any `\` to `/`, so you'll have to make this change in `.gitattributes` yourself. LFS makes that conversion so Windows users can add paths like `foo\bar\baz` without having to convert them to forward slashes.

**Comment by thortillas** [comment]
First of all, thanks for the quick answer!

Well, your results really surprised me because we tried quite exactly what you did and nothing worked. 

To test it again, I created a new branch, build up a new fake folder hierarchy and ... I did hit the exact same wall...
And then it occurs to me that you are using the commandline while I try to use SourceTree... Every time I try to stage a "big file", source tree will complain about the size of the file, asking me to put it on LFS instead... So I kept thinking my gitattributes didn't worked...
I tried with the command line and everything worked as intended... of course...

I am going to forward that to Atlassian so they might take a look at it... I guess they have a bug on their side when reading the gitattributes files and trying to help the user! (when the path has some space and bracket in it)

Thanks again for your time!
Cheers!
Florian.

**Comment by iridiculous** [comment]
I also want to add to this for other people struggling with similar bugs that Sourcetrees indication of whether something goes to LFS or not can be wrong in other cases as well. 

Best practice to actually check if a file is in LFS or not: 
- `git lfs status` for uncommitted changes -> you get a list of files and a mention of whether that file points to Git or LFS
- `git lfs ls-files` for committed files -> lists all files that are currently in LFS, if your file is present, its in LFS


A path that did not work correctly for us was 

`Assets/One/UI2D/CustomUI/Plugins/ZFBrowser/Plugins/** filter=lfs diff=lfs merge=lfs -text`
which caused the following and some more LFS files to show as Non LFS files by Sourcetree:
`Assets/One/UI2D/CustomUI/Plugins/ZFBrowser/Plugins/l64/ZFGameBrowser`
`Assets/One/UI2D/CustomUI/Plugins/ZFBrowser/Plugins/m64/BrowserLib.app/Contents/Frameworks/ZFGameBrowser.app/Contents/MacOS/ZFGameBrowser`

Not sure whats the issue about the paths but as they dont contain spaces there must be a second bug causing similar issues as well
