### ISSUE TITLE
Authentification error (403 Forbidden) when trying to download LFS managed file

### ISSUE THREAD

**Issue by lukaswagner** [git-lfs/git-lfs#2675]
When cloning a repository which contains a file managed by LFS, a 403 Forbidden error occurs once LFS tries to download the file: "Check that you have proper access to the repository". Reading from and writing to the repository with the Git LFS hooks removed works fine.

I'm using Git on Windows 10 from the Git Bash. The repository is a private bitbucket repo. While it belongs to a team, I am set as an admin for it and have full rights.  
During cloning, I am asked for my credentials by Git. This works fine, all source files are downloaded without a problem. But Git LFS doesn't seem to use the entered credentials - in fact, it seems to not use any credentials according to the env settings (auth=none).  
Is this a problem with my Git setup or the repo? How can I fix it?

The clone command (with trace enabled), the last log and the LFS env can be found here: [logs_lfs.txt](https://github.com/git-lfs/git-lfs/files/1395577/logs_lfs.txt)

**Comment by technoweenie** [comment]
This looks similar to https://github.com/git-lfs/git-lfs/issues/2658#issuecomment-335508700.

Try running this in your local repository:

```sh
$ git config lfs.https://bitbucket.org/spielkombinat/unityisogame.git.access basic
```

**Comment by lukaswagner** [comment]
It worked! Thank you very much!
