### ISSUE TITLE
Missing fmt.Fprintf parameter

### ISSUE THREAD

**Issue by kainjow** [git-lfs/git-lfs#2677]
I just ran into this error (on Ubuntu oddly enough):

> Encountered %!d(MISSING) file(s) that may not have been copied correctly on Windows:

Looks like the parameter for "%d" is missing on this line:

https://github.com/git-lfs/git-lfs/blob/1cfd9c8dcde0a97d8bc3b61127f74968b970ae2d/commands/command_filter_process.go#L203

**Comment by technoweenie** [comment]
Thanks, that's an easy fix (https://github.com/git-lfs/git-lfs/pull/2678). It's trying to warn about a Git for Windows bug where it can't work with files over 4GB. LFS warns on that limit for everyone in case contributors on multiple OSs are working in the same repository.

That said, it's not attempting to distinguish between a Git for Windows error and other `smudge` errors. Hopefully you saw other error messages too :)

https://github.com/git-lfs/git-lfs/blob/81932e1a7378beb2d7b8d45f42b1eef06ad59b59/commands/command_filter_process.go#L165-L170
