### ISSUE TITLE
Migrate Does Not Update Tags?

### ISSUE THREAD

**Issue by StanislawAntol** [git-lfs/git-lfs#2679]
There seems to be an issue with `git-lfs-migrate` not working to update the tags. To reproduce this issue, you can find a bash script at [this gist](https://gist.github.com/StanislawAntol/9187bfcb699182334d0d752c11e6efa9#file-reproduce_tag_issue-sh) with the output log at [this gist](https://gist.github.com/StanislawAntol/9187bfcb699182334d0d752c11e6efa9#file-output-log) (nothing appears in `.git/lfs/objects/logs`). The script first creates a repo with a binary file in a sub-directory, commits it, adds a tag, changes the binary file, commits it, and then adds a new tag. It shows that the branches are getting updated during the migration, but the tags are not. I have tried using `--everything` and `--include-refs` with the tag references and both seem to fail at migrating the tags.

Is there something wrong with how I'm calling `git-lfs-migrate` or is this a bug?

Thanks!

----
Running on Ubuntu 16.04
```
git version 2.14.2
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
git version 2.14.2

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by technoweenie** [comment]
Git LFS can rewrite tags, they're just refs. But I think there is something funky going on. For example, I'd expect the following command to update just `v1.2.0`:

```sh
$ git lfs migrate import --include="*.exe" --verbose --include-ref=v1.2.0
migrate: Sorting commits: ..., done
migrate: commit 4cab1cdd14fe4013d32bd4be52bb616a22daa2e8: bin/gopack-windows-amd64.exe
migrate: Rewriting commits: 100% (2814/2814), done
  v0.5.0                 	5050f055c1257ec59965064b1ce3386e1c7bf97f -> 533bcd7ced76087aac107a53f1f00ff298d4dc5b
  v0.5.0.pre1                   6d2e84e5cf1ecec55a8f37d48799907ccb0d8bb5 -> 8dbdf9cce29d3c3485df97c47f8bf8018282656b
  v0.5.1                        5e47f06e08e187b8bf74c47efe96d1fa1db17f33 -> e2255fae0bf9dc6668c4eb4a9d207f282a4e053d
  v0.5.1-tracing                9f118cda39d4fadf673a1807adedb539693fd526 -> 0109572e748242ae80468dec85b6ea0ac0526c25
  v0.5.2                        b351a8bf6cec53b520213f47d37693fc4c096e69 -> 1ad24bf6d65706946b0bb50ab5667014dc78a26a
  v0.5.3                        c98bc5be8825b3dbb91315286e7ad1a8a3090474 -> 83d4eec25e2f16eddbecb959f18827a58674025a
  v0.6.0                        183bdc8283212403491fbc044af2f4825b61ccc7 -> 70551402d9588c9323902ccbd302a3bc0d2c3868
  v1.0.0                        7379fa9087b83ebd1f30d0af53320007fe3cc4be -> 11c9ae90e90f65125633395d7e4d79915be7295b
  v1.0.1                        a9991859368a5c7c61cdc574f60410eba8cfa302 -> 2d669695a59831778bea748e2c4f8055fe90a678
  v1.0.2                        05666983c2e19664b8fc47c30b767ec160e3fea5 -> e1e87761b3de81d15be167c237908e17331d96f8
  v1.1.0                        258acf17fc1431312e2560e38b0702e43dbbd57b -> e8fc6c64f0364263616b771d630809a60a6d4173
  v1.1.1                        7de03971de04b8bb8464e1825f73977b3baaafcb -> b9346e8f934f876dd992b6ff82b9823b0a619035
  v1.1.1-pre-push-tracing       6b00ebc996a7cd2b28fdcd027fe527c48975c113 -> 082e8dd49b192f1f7ad4025a67487bd41ebe8e5d
  v1.1.2                        bf6a6c9979791c85dbef63e68b5a9068e8113d36 -> 409d868edcf44049b73a711157f16f08c8ad2d8a
migrate: Updating refs: ..., done
migrate: checkout: ..., done
```

I'll have to dive in to see how it gets that list of refs to update.

**Comment by StanislawAntol** [comment]
@technoweenie, even on my toy repo in the file, the `--include-ref` doesn't seem to be doing anything. From my understanding of the documentation of `--include-ref`, isn't anything in the past history that is reachable by the `--include-ref` supposed to be updated as well? In your example, I would expect that the previous versions would be reachable from a more recent version. But I still can't get it to work on my toy repo.

Thanks for looking into this and adding it to v2.4.0!

**Comment by ttaylorr** [comment]
@StanislawAntol thanks for opening this, and sorry that it has taken me some time to get back to you. Your attached scripts were very helpful, and I think I have an idea of what's going on here:

To the `--include-ref`, your script adds the _name of the tag_, whereas @technoweenie's adds the _name of the reference_ that the tag is attached to. The difference here being, when we build up a table of previous to migrated SHA-1's, the object that is being migrated is stored, but not the tag itself.

As a concrete example, if tag A has OID 1 and points to a commit with OID 2, the migration index will contain OID 2, but not OID 1, since the OIDs aren't resolved down to the objects that they are pointing at.

I think that this requires the following changes:

1. Implementing loose tags parsing (packed tags will work fine due to the design of git/odb and git/odb/pack).
2. Teach `*git/githistory.refUpdater` to update tags when the object that they are pointing at has moved.

As such, I'm removing this from the v2.4.0 milestone, but will plan to fix this soon.

**Comment by StanislawAntol** [comment]
@ttaylorr , I'm glad that my scripts were helpful. I don't think I'm familiar enough with the internals of git to fully understand your explanation, but I'm happy to hear that you have a sense of what is causing this issue and have a plan to fix it soon.

**Comment by ttaylorr** [comment]
:wave: @StanislawAntol, I opened up https://github.com/git-lfs/git-lfs/pull/2778, https://github.com/git-lfs/git-lfs/pull/2779, & https://github.com/git-lfs/git-lfs/pull/2780, which I believe resolves this issue.

I have queued all of these for the next release (which is v2.4.0), but in case you want to give them a spin earlier, I attached some builds here:

[git-lfs-darwin-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1549748/git-lfs-darwin-386-2.3.4.tar.gz)
[git-lfs-darwin-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1549749/git-lfs-darwin-amd64-2.3.4.tar.gz)
[git-lfs-freebsd-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1549750/git-lfs-freebsd-386-2.3.4.tar.gz)
[git-lfs-freebsd-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1549751/git-lfs-freebsd-amd64-2.3.4.tar.gz)
[git-lfs-linux-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1549752/git-lfs-linux-386-2.3.4.tar.gz)
[git-lfs-linux-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1549753/git-lfs-linux-amd64-2.3.4.tar.gz)
[git-lfs-windows-386-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1549754/git-lfs-windows-386-2.3.4.zip)
[git-lfs-windows-amd64-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1549755/git-lfs-windows-amd64-2.3.4.zip)

**Comment by StanislawAntol** [comment]
@ttaylorr , I finally had some free cycles to get around to this. Everything worked like a charm (on our real repos, not just the simple test script :p). Thanks for all of the help!
