### ISSUE TITLE
Checkout specific files Ptr as Data in "local only" repo?

### ISSUE THREAD

**Issue by zezba9000** [git-lfs/git-lfs#2685]
How do you do this checkout a local files data (NOT POINTER) [aka like "git show HEAD:image.bmp > image.bmp.orig"]? Local repo only in short... no remote?

Neither of these work:

> git lfs pull --include "image.bmp" > image.bmp.orig
> git lfs checkout --include "image.bmp" > image.bmp.orig

**Comment by zezba9000** [comment]
I see I can do:
git show HEAD:image.bmp > image.bmp.ptr
cat "lfs" | git image.bmp.ptr smudge >image.bmp

Does git lfs support a single command to "checkout" the last version of the file?

**Comment by technoweenie** [comment]
Yup, that's the only way. You could shorten it to just:

    $ git show HEAD:image.bmp | git lfs smudge > image.bmp

There are no plans to introduce a specific command for this. I would accept a PR adding a command if it came with a good use case.

**Comment by zezba9000** [comment]
One reason might be consistency with "git checkout --theirs image.bmp" for example as that will auto smudge for you.

Maybe there are reasons I'm not thinking of that makes that a bad idea. Anyway tnx for confirmation.
