### ISSUE TITLE
Solutions for caching LFS files at remote site?

### ISSUE THREAD

**Issue by TTimo** [git-lfs/git-lfs#2693]
Hello,

We use git lfs with a distributed team, and our art guys are at a remote site with a slow internet connection.
We have a cloud hosted git lfs server that generally works well and has plenty of bandwidth, but I would like to setup something so LFS data can get cached at the remote site. That way slow transfers are backgrounded and things are sped up between the art team members.

Below are the options I'm considering. Please advise on feasibility?

- Have the git lfs clients at the remote site go through a persistent HTTP(S?) proxy, so I can cache and store on a local server at their site transparently. Would improve gets but not do anything for uploads. Not sure if it's even possible either.

- Run a git lfs server at the remote site, have the art team work against that. Script out a sync and manually work out the occasional conflict. Possibly more work and annoyance to setup and operate than a proxy, likely breaks the locking features (when such time comes that those will actually be useful).

- Other solutions I haven't considered?

Thanks,
TTimo

PS: Apologies if there is a better forum to ask these questions. Afaik this is the only place that is reasonably vendor neutral.

**Comment by technoweenie** [comment]
Is your remote team collaborating with the same cloud-hosted git repository as other "local" team members? If so, that cloud host must be the single source of truth. Git updates should not be pushed until the cloud host LFS server has the objects. The cloud host should also be owner of the lock file status. This ensures that anyone working out of the cloud host always has the LFS files available to them.

Proxying downloads sounds the easiest, as you don't have to worry about data integrity. If a file is lost or corrupted, just fetch it again from the source. I think I'd prefer proxying uploads to syncing them, as the proxied upload won't finish successfully until the server accepts it. An LFS proxy service could also proxy the Lock calls to the cloud host, allowing your remote team's locks to affect your home team working through the cloud host.

Introducing another local Git and LFS repository would work, but could introduce race conditions with locking and pushing.

Unfortunately, we don't have a proxy server, so you may have find or write one :/

**Comment by TTimo** [comment]
A general 'lfs proxy cache server' solution sounds appealing, but that probably involves a dedicated development effort and working against the LFS server APIs.

Nothing particularly worrying about that per se, but deploying a git lfs repository and a few scripts to power a sync against a master cloud server feels more like an IT task and overall less work to get the basics going. So I'll probably do that for now - with the caveat that we may hit the occasional merge conflict.

Thanks!

**Comment by TTimo** [comment]
Nice! We never deployed a caching solution in the end, but with a tool written maybe we could revisit that.

**Comment by saracen** [comment]
@TTimo if you do give it a try, feel free to raise an issue if you find something that could be improved.

@ttaylorr Added :)

Binaries and container have now been built.

**Comment by TTimo** [comment]
I asked the remote team, and it looks like we’ve worked around the problem by investing in a significantly faster internet pipe ..
