### ISSUE TITLE
Understanding paths and pattern matching in .gitattrubutes

### ISSUE THREAD

**Issue by jsilverman-blispay** [git-lfs/git-lfs#2697]
I've been struggling getting git-lfs to work. Primarily, tracked large files weren't being uploaded to my configured LFS server. (I'm using Artifactory). Apologies that the background to set up my questions is long.

I finally got it working, but what worked, and what I've been trying, lead me to some questions

Example git repo dir structure, where "/example/" is the root of the git repo (i.e. the .git/ dir is there)

```
/example/main/src
/example/main/artifacts
/example/main/artifacts/category1
/example/main/artifacts/category2
```

I have a build process which generates artifacts which are all ".dmg" files. They are categorized by the build, and end up in different subdirs as appropriate.

e.g.
```
/example/main/artifacts/category1/package1.dmg
/example/main/artifacts/category1/package2.dmg
/example/main/artifacts/category2/package3.dmg
```

When one runs git lfs track, it creates a .gitattributes file *in the CWD*

When I noticed this, I created a .gitattributes file at /example/.gitattributes

Contents of that file:
`*.dmg filter=lfs diff=lfs merge=lfs -text`

When the build ran, git lfs did seem to pick up on the packages in the subdirectories. However, git lfs did not upload the files into Artifactory (my LFS server)

I cleaned everything out and started over. The .gitattributes file was in the same place, with the same content. I manually placed a .dmg file in the top level directory, next to the .gitattributes file.

I did git add, commit, push, and this time, was asked for credentials to Artifactory and git lfs pushed the binary large file into Artifactory.

Finally, my questions:

- Does there need to be a .gitattributes file in each directory where a large binary lives?
- Or, does the pattern in .gitattributes need to include path information?

**Comment by technoweenie** [comment]
The `.gitattributes` files work the same as `.gitignore`. They can live in any directory, can specify paths in the patterns, or specify wildcards. The docs have more info: https://git-scm.com/docs/gitattributes

One thing to keep in mind with LFS: The `.gitattributes` file with `filter=lfs` means Git will run matching files through LFS before checking out to your working directory, or before being added to Git. This gives LFS a chance to either replace an LFS pointer with the actual contents, or vice versa (depending on whether you're viewing or adding the file). This means that `.gitattributes` changes don't apply to existing files, only new ones added.

```sh
$ command-to-create-dmg-file
$ git add main/artifacts/category1/package1.dmg
$ git lfs track "*.dmg"

# nothing added to LFS yet

$ command-to-create-dmg-file
$ git add main/artifacts/category1/package2.dmg

# package2.dmg is in LFS
```

**Comment by jsilverman-blispay** [comment]
Thanks for this clarification.

Whatever it was that was not working yesterday, is gone. Git LFS + Artifactory is working fine for me today.

I have a feeling I did `git lfs track <file>` and never then did `git add <file>` to the .dmg files. Whereas today, I definitely did that, in that order.
