### ISSUE TITLE
Missing apt repository for Ubuntu 17.10 Artful

### ISSUE THREAD

**Issue by borisvu** [git-lfs/git-lfs#2702]
The repository for the latest Ubuntu is missing
Err:16 https://packagecloud.io/github/git-lfs/ubuntu artful Release                                                       
  404  Not Found [IP: 52.219.24.121 443]

**Comment by technoweenie** [comment]
Ah no problem. I can add an `ubuntu/artful` entry here:

https://github.com/git-lfs/git-lfs/blob/8e9e7d4c0d2478b6b063d9a2103836c61327114f/script/packagecloud.rb#L62

**Comment by sschuberth** [comment]
@technoweenie, any update on this? Looks like #2704 was merged, but no Artful packages have been published yet.

**Comment by ttaylorr** [comment]
@sschuberth my assumption is that Artful packages will be published during the next release.
