### ISSUE TITLE
Checking whether the files in the staging area are git-lfs-tracked

### ISSUE THREAD

**Issue by aleb** [git-lfs/git-lfs#2705]
Currently `git lfs ls-files` by default lists the files at the current HEAD, but excluding the new files in the staging area. This is inconsistent with the behaviour of `git ls-files` which by default lists also the new files in the staging area. 

It would be nice to fix this inconsistency:
```
$ git status
On branch work
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   data/1111111111.png

$ git ls-files | grep 1111111111.png
data/0000000000.png
data/1111111111.png

$ git lfs ls-files | grep 1111111111.png
data/0000000000.png
```

This should also list 1111111111.png, because the git lfs filter has been applied and it will be git-lfs-tracked if a commit is created:
```
$ git cat-file -p :data/1111111111.png
version https://git-lfs.github.com/spec/v1
oid sha256:a0a9a4f2babff2559025c5c41066c056fabc82b6367b1d2ee05d359976e12fb9
size 362141

$ ls -l data/1111111111.png
-rwxr-xr-x  1 ab  staff  362141 Oct 31 12:09 data/1111111111.png
```

It would also be nice if the ls-files help message explains what the second token (`*` in the example below) means:
```
$ git lfs ls-files | head     
793286c8e9 * data/0000000000.png

$ git lfs help ls-files
git lfs ls-files [<ref>]

Display paths of Git LFS files that are found in the tree at the given
reference.  If no reference is given, scan the currently checked-out branch.

Options:

* -l --long:
  Show the entire 64 character OID, instead of just first 10.
```

**Comment by ttaylorr** [comment]
Hey @aleb, thanks as always for this suggestion!

I initially thought that this would require some changing of how the `gitscanner` works, but after reading Git's implementation of the `ls-files` builtin, I think that the only change required was also scanning the cache for any LFS objects.

I implemented this in https://github.com/git-lfs/git-lfs/pull/2794 & https://github.com/git-lfs/git-lfs/pull/2795, which I have scheduled for the next release of Git LFS, v2.4.0.

If you're eager to try these out beforehand, here are some cross-platform builds with these changes included:

[git-lfs-darwin-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1573457/git-lfs-darwin-386-2.3.4.tar.gz)
[git-lfs-darwin-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1573458/git-lfs-darwin-amd64-2.3.4.tar.gz)
[git-lfs-freebsd-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1573459/git-lfs-freebsd-386-2.3.4.tar.gz)
[git-lfs-freebsd-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1573460/git-lfs-freebsd-amd64-2.3.4.tar.gz)
[git-lfs-linux-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1573461/git-lfs-linux-386-2.3.4.tar.gz)
[git-lfs-linux-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1573462/git-lfs-linux-amd64-2.3.4.tar.gz)
[git-lfs-windows-386-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1573464/git-lfs-windows-386-2.3.4.zip)
[git-lfs-windows-amd64-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1573465/git-lfs-windows-amd64-2.3.4.zip)
