### ISSUE TITLE
Don't automatically download LFS objects (for all users)

### ISSUE THREAD

**Issue by jextrevor** [git-lfs/git-lfs#2717]
I've set up Git LFS in a repo I am working on. The repo contains several large files, and several hundred more large files will be added in the future. It is annoying when these files are automatically downloaded as part of git pull.

Is there a config option that I can put in .lfsconfig in our repo that will disable the automatic downloading of LFS files for all users of the repo? Automatic upload is fine, I just want to disable automatic download.

**Comment by technoweenie** [comment]
You can set `lfs.fetchexclude` to `*`:

https://github.com/git-lfs/git-lfs/blob/ac19b5e1ff3853aab07f15ac8f8f6c8f50aacb83/docs/man/git-lfs-config.5.ronn#L163-L173

Keep in mind, this can be overridden by a local git config change or command line flag. The order of preference for this change is:

* `.lfsconfig`
* User Global Git config
* User local Git config
* Command line flag

Here's the command line flags that `git lfs pull` can accept in case they do need some files:

https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-pull.1.ronn#L18-L35

Checking this change in `.lfsconfig` will ensure that users will not download LFS files by default.

**Comment by thomasbiddle** [comment]
@technoweenie 

What does this look like in `~/.gitconfig`

I currently have the following, and it doesn't seem to work:

```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	fetchexclude = *
```

**Comment by ttaylorr** [comment]
@thomasbiddle it should look like the following:

```
[lfs]
	fetchexclude = *
```

(note that `[lfs]` != `[filter "lfs"]`).

**Comment by thomasbiddle** [comment]
@ttaylorr That worked - thanks!

**Comment by ranebrown** [comment]
If using the mentioned setting in `.gitconfig` you then need to use `git lfs pull --exclude= --include "filename"` to pull a single file. Took me a while to figure that one out.

**Comment by camilla11** [comment]
Once I've excluded the files, how do I purposely download them in a specific scenario?

**Comment by bk2204** [comment]
You can use `git lfs fetch --include="filename" --exclude=""` to override the default include and exclude settings and download the given file. You can also replace `filename` with a glob pattern and it will include all files matching that pattern.

**Comment by camilla11** [comment]
hmm that didn't work but 

`git lfs pull --include="*" --exclude=""` did ! 
Thank you

**Comment by horak** [comment]
How do I go about adding this to `.gitattributes`?

When I the recommended above to .gitattributes and then try a fresh clone I'm getting the following output:
```
 is not a valid attribute name: .gitattributes:30
```
with line 30 of my `.gitattributes` looking as follow:

```
...
26 *.xlsx filter=lfs diff=lfs merge=lfs -text
27 *.XLSX filter=lfs diff=lfs merge=lfs -text
28 original/*  filter=lfs diff=lfs merge=lfs -text
29 [lfs]
30 	fetchexclude = *
```

Any idea why that's happening? 

<img width="511" alt="Screen Shot 2021-02-01 at 2 12 41 PM" src="https://user-images.githubusercontent.com/1111424/106512702-91917380-6497-11eb-989c-82b02865f845.png">

**Comment by bk2204** [comment]
Those values don't go in `.gitattributes`.  They should live in your local Git configuration file, such as in `.git/config`.

**Comment by horak** [comment]
I see. Ok this spawns to other questions:

1. Is there no way to have these changes be applied globally via a tracked file such as .gitattributes. The docs indicate .lsconfig, I tried tracking that but ran into errors while pulling as well. 

2. I was hoping on configuring these changes before I clone and pull down files I don’t want. The idea was to add the appropriate global file to the repo via Gitlab’s online GUI and then pull in only the references. Any idea how I can avoid pulling everything in on the initial clone?

**Comment by horak** [comment]
Doh. Thanks!
