### ISSUE TITLE
git status shows all lfs files as modified after git lfs pull 

### ISSUE THREAD

**Issue by Permafacture** [git-lfs/git-lfs#2723]
I've switched to developing on OSX from linux.  Now I've seen this issue multiple times. My steps:

git clone repo-that-uses-lfs
git status  # no modified files, as expected
ls -l my-file1.png  # is an lfs pointer text file
git lfs pull
git status  # all lfs files are modified
ls -l my-file1.png  # is a large binary file
git lfs status

    my-file1.png (LFS: 3758aea -> Git: 3758aea)
    ... (many if not all lfs files listed here)

$ git lfs version
git-lfs/2.3.1 (GitHub; darwin amd64; go 1.9)

These repos all worked just fine for many months for my team and I while I was on Linux.  Any ideas?

**Comment by technoweenie** [comment]
Without seeing the repository, my 2 hunches are: 

* Your `.gitattributes` is behaving differently on linux. Are there filename case issues (such as tracking `*.zip`, with filenames like `FOO.ZIP`)? 
* Was LFS installed properly on Linux, or now on OSX? A lack of `filter.lfs.smudge` `filter.lfs.clean` properties mean LFS won't run automatically after running `git clone`.

**Comment by Permafacture** [comment]
It is possible that it is not installed correctly on my Mac, since IT is managing the installs now. I just ran git lfs install and recloned one of the repos and saw the same issue.  I see lfs commands in some of the hooks.  git lfs env contains the following:

<a bunch of other stuff>
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by technoweenie** [comment]
That looks like a correct install. What about filename case issues in your repository?

**Comment by dustinfreeman** [comment]
Curiously, I saw the same behaviour after lfs-migrating an existing repo. After adding a bunch of files to lfs, a fresh clone would show them as modified. Both the original creation and the clone were on Windows. I should get a reproducible example together.

**Comment by ttaylorr** [comment]
> I should get a reproducible example together.

@dustinfreeman that would be helpful, thanks! There are lots of strange permutations that could be going on in theory, so a reproducible example would be helpful in narrowing things down. Would you mind opening a new issue with this?

**Comment by 2008hsk** [comment]
Did you find a solution? I am experiencing the same
