### ISSUE TITLE
Cannot embed git lfs files in HTML page?

### ISSUE THREAD

**Issue by thebigfootsdad** [git-lfs/git-lfs#2725]
So I recently installed `git-lfs` and it seems that the files are stored (when I do `git lfs ls-files` the file shows up. I am currently storing `.mp4` files in my lfs, but when it comes to using the `<video>` tag in the HTML of my `repositoryname.github.io` page, it shows as "no video with the supported format and MIME type found". 

I've tried everything from `src="../file.mp4"` and `src="file.mp4"` and `src="https://repositoryname.github.io/file.mp4"` and `src="https://github.com/repositoryname/repositoryname.github.io.git/info/lfs"` (where `git lfs env` says the endpoint is) but nothing has worked so far. 

I don't want upload it to a video streaming site and then embed it in the page, and `src="../file.mp4"` and `src="file.mp4"` work for smaller video files that are not in `git lfs`. 

Any possible solutions? I'm not sure if I missed something as to how to link/embed files, but I'm very, very, new to git and git-lfs, so please go easy on me 🙈.

**Comment by technoweenie** [comment]
The GitHub Pages service does not support LFS. You can add a comment to https://github.com/git-lfs/git-lfs/issues/1342, or contact GitHub support to request the feature, and it'll be passed along to the correct team.
