### ISSUE TITLE
Can't get lfs objects from gitlab server

### ISSUE THREAD

**Issue by HosseinAssaran** [git-lfs/git-lfs#2726]
Hi
I've copy one repository and create other repo . Now when I click on lfs binary files I can download them, but when I want to download it with sourcetree or command line in user computers it give error . 
when I import this command:
`git lfs fetch --all`
 I get this error:
```
Scanning for all objects ever referenced...
* 45 objects found
Fetching objects...
Git LFS: (0 of 44 files) 0 B / 384.74 MB
batch response: Git credentials for http://xxx not found.
error: failed to push some objects to 'http://xxx'
```
and  with source tree when I want to checkout to remote branches I got this error:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false checkout -b Fix_bugs --track origin/Fix_bugs
Downloading Debug/Exe/XXX (4.66 MB)
Error downloading object: Debug/Exe/XXX (5efac8154f26d7fc2986e27b0a7c6b5aff2c17c3075266b7a17d2cf2be06b35f)

Errors logged to E:\xxxx
Use `git lfs logs last` to view the log.


error: external filter 'git-lfs filter-process' failed
fatal: Debug/Exe/xxx: smudge filter lfs failed

Completed with errors, see above.
```

**Comment by technoweenie** [comment]
It looks like you may be having some issues logging in. The message "batch response: Git credentials for http://xxx not found." indicates that you don't have anything in your credential helper.

Here are a couple details that could help pinpoint this issue:

1. Run `GIT_TRACE=1 git lfs fetch --all` to get more insight into what LFS is doing.
2. What does `git config credential.helper` return? Do you have a [credential helper](https://help.github.com/articles/caching-your-github-password-in-git/) set up? Are you trying to authenticate through some other method?
3. The source tree error includes the message `Errors logged to E:\xxxx`. Can you post the contents of that file?

**Comment by HosseinAssaran** [comment]
I do the command one and I received this respond:

> 11:52:09.201276 git.c:607               trace: exec: 'git-lfs' 'fetch' '--all'
> 11:52:09.202277 run-command.c:350       trace: run_command: 'git-lfs' 'fetch' '-                          -all'
> trace git-lfs: run_command: 'git' config -l
> Scanning for all objects ever referenced...
> trace git-lfs: run_command: git rev-list --objects --all --
> trace git-lfs: run_command: git cat-file --batch-check
> trace git-lfs: run_command: git cat-file --batch
> * 269 objects found
> Fetching objects...
> trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
> trace git-lfs: run_command: 'git' config branch.hotfix.remote
> trace git-lfs: tq: running as batched queue, batch size of 100
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15587.bin [5efac8154f26d7fc2986e27b0a7c6b5aff2c17c3075266b7a17d2cf2be06b35f]
> trace git-lfs: fetch Debug/Exe/PM.out [ecf80b86eea39318d1b03cded4319d6c690b9e8b9a33e7b2e03aeb5573a1744c]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15537.bin [d29813d09976b5c7b12273fbce9799cadf0d3eb24a05a2dc914ee0b613629146]
> trace git-lfs: fetch Debug/Exe/PM.out [93dddc985fd194d00ebdc836d8b41eeb26d21b038f90f71e0edec6d7f069155c]
> trace git-lfs: fetch Tools/VersionController.exe [aed5b441eb989ea82c82edab59f3a09dd18f6bd4b368884d0657d44b1285e8c4]
> trace git-lfs: fetch Tools/binfile_rename.exe [6048499131c08487a29bc2e6bdabaf7670ad757977c15aadeed741f6281f50d1]
> trace git-lfs: fetch Tools/hex2bin.exe [338655e0f8235d5aecfd0766690540eb79b8c34126dac9855ba34993558c79ba]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.SM2017101515538.bin [0daac846afa88a08acebdc1e03f454d6ce7b074feb8277f7280ee7421da0d37e]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.SM2017101515543.bin [0b91bce69ffadc93894e1b0b1e281f78242053297a30ca18098738afa2588da5]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.SM2017101515552.bin [32d9bb4fb9c96e87e07d7b38c1f2e2b9e18031bcc53965373bada30a11d4c901]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15535.bin [e7912bdeffeb95f45c75a2dd84c9934c40c83836b20b3df3c10c7afa4f118063]
> trace git-lfs: fetch Debug/Exe/PM.out [df71c09b9b5c825c0666cf29e6d8770e9353715953e581ef3408f9e2778879aa]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15542.bin [1fda89181ec702e93c6a09fa46728c2f621435504b69cb06e28bfa6299006c37]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15570.bin [c5406463cc5eec853c6287cede92e93c9446926edd418d6be85197fdd3ded132]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15592.bin [c2032495b55f4461e538b8c9fce41a2ac07c8472a9924bcb4caebe6dfc29348c]
> trace git-lfs: fetch Debug/Exe/PM.out [796514b843e0bf77bc07e0f7cb1ef12eea51ac4398e8ddfa51eed5dec92a3632]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15577.bin [b3bc0e4966cf3d70c03ebbe35e178ffa1cf16dec00247d3636dfd96aae496ce6]
> trace git-lfs: fetch Debug/Exe/PM.out [4bf499d281a8f5153ab02c15644a9fccd9590b77eab36e6010bd46fb49b3ba0b]
> trace git-lfs: fetch Debug/Exe/PM.out [f975ead8ebcee9a141941ec9ee0254e390a01541a5d8fff23225eeb43a4d9095]
> trace git-lfs: fetch Debug/Exe/PM.out [f4f24ae62530b08be37e67977f27fc24606b40434efce41769eaf0c3285aeb60]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15552.bin [dab666f779de4b32fe1f0fe38be8706fc18ad76b6cb23906dd3127d19dc1af5f]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15571.bin [15f63397ed2124387e44883c7cd12b8c52b9948fd19e67ef8f24e4fe223ad06d]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15597.bin [6f17526b09ec77d6cc9fe0f748224d0d8b9cb4a85dacf1a117ede3c385843664]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15604.bin [bed36bd1c3b870a84d57c5ed40a943aec795e8164f42429b962c7f61db08d648]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15634.bin [6c03be352a8791c6ef9f88772a9ff7c2a7cd2900301f5a874379d651a22c2c8b]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15636.bin [4b71b8826c53d769e86f5077769f3569f6871117c27fa0e80390d6769f83eedf]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15641.bin [b5cb72cda01b704c470ae0ad6dcccb9207c380130edfdeeefb098548d1678cc4]
> trace git-lfs: fetch Debug/Exe/PM.out [0bc8cb84a7e7ae52ba4dde190c7846c84abe727d076e46597481a41dab925916]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15639.bin [4f9d7ad118fdb1719cedb95bf8f85117a1bb8956bbd03178eac5e15543b1ac52]
> trace git-lfs: fetch Debug/Exe/PM.out [7ea7b5180cf054af01e1021359f9e964aef53e7dac718bbc38454e6abbbe923c]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15633.bin [7766f5a89fa75ad5b3487be7d7d97189adee74bb1996e3e52ff57b20b8b295ea]
> trace git-lfs: fetch Debug/Exe/PM.out [a1bcf7a4f01fe15bf57eb79ef99565168c5b664b1044c2e7ff7f3c4dc45ee13d]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15627.bin [c7858c915fd9a38cdd580be496d4030bc25bf2a137b8e734a73947f918de4f52]
> trace git-lfs: fetch Debug/Exe/PM.out [740c898ef2661f6e0c9b004bf49eca5f365e744f504c2c38d7c94408a2921371]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15534.bin [60422ab832f8c29cae8c58c35844290f840ed1e0197cb5519b374cd0f24a5f3f]
> trace git-lfs: fetch Debug/Exe/PM.out [b6a230dcb4502393b7f593932829e56c9d29c755e07d5b7d24b2cb536a4feca2]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15533.bin [a0faa0fc7857a532b9664513fc3de8da7ef1e4ebb8acd8847d76be5ddda748f9]
> trace git-lfs: fetch Debug/Exe/PM.out [aee4e8b9e1997ccd1c1ce55f74c62e9c02143e07c866ab3eac3a26b9320d79cc]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.dev15532.bin [c55a3bee81460aee182ba8f3601e14152419009cc6b352c4397e4849d69d206b]
> trace git-lfs: fetch Debug/Exe/PM.out [97e2c8c9a32bf5a4b72ef63382859125a48658146516838542521599eebc218f]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15533.bin [34ca0c2ea50f5d137560d57f6075d14541fa6b0adfe79281be234a6050b2b659]
> trace git-lfs: fetch Debug/Exe/PM.out [d82f7f72dadda772e68c937ec438254bd50581e02583fa25953ca3347aca3ac7]
> trace git-lfs: fetch Debug/Exe/PM_R2.1.13.15532.bin [4eb60adc9b8d852b44a9eb2628dd6beb14b4aa9813c50804d3e56881ea38d190]
> trace git-lfs: fetch Debug/Exe/PM.out [288a19fe13c5a5ab4af4230701b41ffa96439e2a77370447c4327607089303ff]
> trace git-lfs: tq: sending batch of size 44
> trace git-lfs: api: batch 44 files
> trace git-lfs: creds: git credential fill ("http", "192.168.1.81", "pm/all-in-one.git")
> trace git-lfs: api error: Git credentials for http://192.168.1.81/pm/all-in-one.git not found.
> Git LFS: (0 of 44 files) 0 B / 384.74 MB
> batch response: Git credentials for http://192.168.1.81/pm/all-in-one.git not found.
> error: failed to push some objects to 'http://192.168.1.81/pm/all-in-one.git/info/lfs'

and this is inside sourcetree log file:

> git-lfs/2.0.2 (GitHub; windows 386; go 1.8; git 85e2aec4)
> git version 2.11.0.windows.1
> 
> $ git-lfs.exe filter-process
> Error downloading object: Debug/Exe/PatientMonitor.out (ecf80b86eea39318d1b03cded4319d6c690b9e8b9a33e7b2e03aeb5573a1744c)
> 
> Smudge error: Error downloading Debug/Exe/PatientMonitor.out (ecf80b86eea39318d1b03cded4319d6c690b9e8b9a33e7b2e03aeb5573a1744c): batch response: Git credentials for http://192.168.1.81/pm/all-in-one.git/info/lfs not found.
> github.com/git-lfs/git-lfs/errors.newWrappedError
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:166
> github.com/git-lfs/git-lfs/errors.NewSmudgeError
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:252
> github.com/git-lfs/git-lfs/lfs.PointerSmudge
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:68
> github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
> github.com/git-lfs/git-lfs/commands.smudge
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:63
> github.com/git-lfs/git-lfs/commands.filterCommand
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:65
> github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
> github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
> github.com/git-lfs/git-lfs/commands.Run
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/run.go:68
> main.main
> 	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
> runtime.main
> 	C:/Go/src/runtime/proc.go:185
> runtime.goexit
> 	C:/Go/src/runtime/asm_386.s:1629
> 
> ENV:
> LocalWorkingDir=E:\all-in-one-960822-assaran
> LocalGitDir=E:\all-in-one-960822-assaran\.git
> LocalGitStorageDir=E:\all-in-one-960822-assaran\.git
> LocalMediaDir=E:\all-in-one-960822-assaran\.git\lfs\objects
> LocalReferenceDir=
> TempDir=E:\all-in-one-960822-assaran\.git\lfs\tmp
> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> AccessDownload=basic
> AccessUpload=basic
> DownloadTransfers=basic
> UploadTransfers=basic
> GIT_CONFIG_PARAMETERS='color.branch=false' 'color.diff=false' 'color.status=false' 'diff.mnemonicprefix=false' 'core.quotepath=false'
> GIT_DIR=.git
> GIT_LFS_PATH=C:\Program Files\Git LFS
> GIT_PAGER=cat
> GIT_PREFIX=

also I run `git config credential.helper` and I get  `cache`
 then I run `git config --global credential.helper wincred` as included in credential helper but it didn't change anything.

**Comment by ttaylorr** [comment]
It looks like that with `git config --global credential.helper wincred`, LFS will contact your credential helper to authenticate that request, but the credential helper didn't provide a response.

**Comment by technoweenie** [comment]
I'd recommend upgrading Git LFS if you can. I'm not sure how LFS upgrades work with SourceTree. In fact, it may be worth reaching out to Gitlab and Atlassian (for SourceTree) to get their help too, as we don't have much experience with them.

I do recall Gitlab having some auth-related discrepancies with the LFS API spec, leading to some problems. Not sure if it's been fixed yet.

**Comment by HosseinAssaran** [comment]
What do you mean by git lfs upgrade on client system or in git lab server. In client side I tested it with new version of git lfs, but if you mean on the git lab server I don't know how to upgrade  git lfs. also I've upgraded git lab to the last version. but the problem not solved and client computers have problems with. 

I think it's needed to say that my git lab server is on the virtual ubuntu linux over windows 7 by VirtualBox.

**Comment by ttaylorr** [comment]
> but if you mean on the git lab server I don't know how to upgrade git lfs

I think what @technoweenie is referring to is making sure that your server's implementation of LFS covers the current API specification.
