### ISSUE TITLE
Specify SSH Key for remote commands

### ISSUE THREAD

**Issue by Ridha-ELB** [git-lfs/git-lfs#2727]
Hi Everyone,

I have a bash script that run commands on a windows machine (lets call it machine A) to pull a repository on bitbucket (using git) and then run specific programs to work on the pulled content.

I have also a ubuntu machine running Jenkins. On a build step I use the "Publish Over SSH" plugin to run the bash script on the machine A.

Everything goes fine all the times unless git has to pull a commit containing a large file and its fails with this error :

> 
Downloading test x_map.fbx (31 MB) Error downloading object: x_map.fbx (63b3f85): Smudge error: Error downloading x_map.fb x (hash): batch request: git@bitbucket.org: Permission denied (publickey).: exit status 255

The problem is that the LFS part of git doesn't use the SSH key even though I did set the core.sshCommand in git config to use a key for all the ssh commands.

So when I do this : ssh git@bitbucket.org git-lfs-authenticate "reopsitory" downlaod its fails with this message : git@bitbucket.org: Permission denied (publickey)

But it works fine when I run it with the ssh key option : ssh -i "ssh-key-path" git@bitbucket.org git-lfs-authenticate "reopsitory" downlaod

So I was wondering if there was any solution to kind of overload all the LFS ssh commands to use a specific ssh key like the core.sshCommand in git config.

I m hardly stuck on this so I hope you guys have a miraculous solution! Thanks in advance for your help.

EDIT :
adding prior to the git pull command :
eval $(ssh-agent -s)
ssh-add "key-path" makes this command work : [  ssh git@bitbucket.org git-lfs-authenticate "reopsitory" downlaod ] but the git pull still fails with the same error

**Comment by technoweenie** [comment]
You have two options here:

1. Create an [ssh config file](https://linux.die.net/man/5/ssh_config). This [guide](http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/) explains it clearly, and has examples using the `IdentityFile` config option that you want.
2. Try the `GIT_SSH` or `GIT_SSH_COMMAND` environment values. Apparently our support is incomplete, missing support for [`core.sshcommand`](https://git-scm.com/docs/git-config#git-config-coresshCommand) and [`ssh.variant`](https://git-scm.com/docs/git-config#git-config-sshvariant).

IMO option 1 is preferable.

**Comment by Ridha-ELB** [comment]
OMG I should have though about that XD ! Thanks that did the tick (option 1)

**Comment by fabiopicchi** [comment]
Not sure if this has been addressed, but I find the second option preferable. I have gitconfig setup in a way that, depending on the folder I am using in my computer, a different key is used (work/personal setup). To achieve that without much hassle, I setup a custom `core.sshcommand`. In my use case, the hosts are the same so the ssh config file is very annoying to manage.

Is there an issue to support option 2? If so, I would like to try to contribute to that feature

**Comment by bk2204** [comment]
We should support `GIT_SSH`, `GIT_SSH_COMMAND`, `core.sshcommand`, and, as of 3.0, `ssh.variant` and `GIT_SSH_VARIANT`.  Note that we do require substantially more functionality than Git out of the `ssh` variant, including support for `--` and `-oControlMaster`, so you should be sure your script functions correctly if you use that variant (which is the default).

**Comment by krachynski** [comment]
How is this support coming along? I'm trying to use LFS in a CI pipeline where modifying the ssh_config file is not feasible.

**Comment by chrisd8088** [comment]
> How is this support coming along?

As was mentioned in the https://github.com/git-lfs/git-lfs/issues/2727#issuecomment-1021442237 above, Git LFS v3.x supports `GIT_SSH`, `GIT_SSH_COMMAND`, `GIT_SSH_VARIANT`, and the `core.sshCommand` and `ssh.Variant` Git configuration options.

**Comment by krachynski** [comment]
that comment said "should" which suggested to me that somebody thinks it's a good idea but that it wasn't planned yet.

I'll revisit what I've got installed on my build agents because they aren't working using that environment variable today.
