### ISSUE TITLE
SSH config additions

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#2728]
Support the following in 

* [ ] [`core.sshcommand`](https://git-scm.com/docs/git-config#git-config-coresshCommand)
* [ ] [`ssh.variant`](https://git-scm.com/docs/git-config#git-config-sshvariant)

Optimistically adding to v2.4.0, but may get pushed back if we decide that either this isn't a trivial fix, or we decide v2.4.0 has enough changes to ship.

**Comment by ttaylorr** [comment]
I took a stab at this a while ago in [`git-lfs@ssh-command-args`](https://github.com/git-lfs/git-lfs/tree/ssh-command-args), but would love to pick this up for v2.5.0.

**Comment by bk2204** [comment]
I believe we've implemented these for 3.0, and thus I'm closing this.
