### ISSUE TITLE
git lfs push failed even with -c http.extraheader="Authorization .."

### ISSUE THREAD

**Issue by TingluoHuang** [git-lfs/git-lfs#2729]
git version 2.15.0.windows.1
git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)

I don't have git credential manager installed on my box, and i don't plan to install it.

on a repository that doesn't have any LFS object, i can use following command to do `git push`
`git -c http.extraheader="Authorization: Basic Base64EncodedUserPass" push`

however, on a repository that has LFS objects, the same command will fail with error
`LFS: Git credentials fro https://xxxxxxx not found`

I verified `git -c http.extraheader="Authorization: Basic Base64EncodedUserPass" lfs fetch` works fine.

I think this is a bug of how we handle http.extraheader option on `lfs push`.

**Comment by ttaylorr** [comment]
Hi @TingluoHuang, thanks for opening this and sorry that you're having problems!

This looks like a bug to me, so I went ahead and opened up https://github.com/git-lfs/git-lfs/pull/2733 to fix it. If approved and merged, I've scheduled this to be released in 2.4.0, but here are some binaries that you can try in the meantime.

[git-lfs-windows-386-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1480092/git-lfs-windows-386-2.3.4.zip)
[git-lfs-windows-amd64-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1480093/git-lfs-windows-amd64-2.3.4.zip)
