### ISSUE TITLE
LFS breaks when doing clone --bare + clone + reset

### ISSUE THREAD

**Issue by Aketzu** [git-lfs/git-lfs#2731]
Crosspost from chef/cookbook-omnifetch#21

I have git-lfs repo in GitLab and normal clone works over ssh. When trying to do chef policyfile install the git repo export fails. My feeling is that this is due to chef cookbook-omnifetch doing clone --bare first, then cloning from it to another local copy and finally doing reset --hard. But then git-lfs tries to fetch files from first bare clone but there is none (and for some reason it tries to use foo.git directory instead of foo).

I'm not sure whether problem is in git-lfs not working with that double-clone or in the way that cookbook-omnifetch is trying to mangle the repos.

git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)

Log excerpt (full version and git-lfs log in https://gist.github.com/Aketzu/79bafc57d0c276acfe06acfc9b9bf31c)
```
Downloading files/assembly-8.1.0.zip (29 MB)
13:32:10.204952 trace git-lfs: tq: running as batched queue, batch size of 100
13:32:10.205025 trace git-lfs: tq: sending batch of size 1
Error downloading object: files/assembly-8.1.0.zip (70bdc41): Smudge error: Error downloading files/assembly-8.1.0.zip (70bdc4131f0d4be92660574a193053b7c008ade2af0c5cd5a0de74c30b5c0cc6): batch request: missing protocol: "/root/.chefdk/cache/.cache/git/3b3a7b287f96b4a8f60a36fe4b89cece06c17e5a.git/info/lfs"
```

**Comment by ttaylorr** [comment]
Hi @Aketzu -- thanks for opening this issue and sorry that you're having trouble. It looks like twhat's happening here is that the tool you're using is trying to do a local fetch or pull from the `/root/.chefdk/cache` directory, which is something that Git LFS does not currently support.

This is something we're thinking about adding in https://github.com/git-lfs/git-lfs/issues/2164, but for now I am going to close this issue noting another request for local push/pulls.
