### ISSUE TITLE
Cannot correctly create git-lfs-server

### ISSUE THREAD

**Issue by aido93** [git-lfs/git-lfs#2741]
Hello all!

I'm trying to start up git-lfs-server together with kallithea, but git-lfs cannot correctly initialize repository.

Problem (client):
`$ git push origin master
Git LFS: (0 of 1 files) 0 B / 3.65 MB
batch response: Repository or object not found: https://10.72.14.144/test1.git/lfs/objects/batch
Check that it exists and that you have proper access to it
error: failed to push some refs to 'https://git@10.72.14.144/test1.git'
`

Server:
`$ pwd
/home/git/bin_kallithea_repo/test1.git
$ ls
branches  config  description  HEAD  hooks  info  lfs  logs  objects  refs
$ ls lfs
objects  tmp
$ ls lfs/objects/
logs
$ ls lfs/objects/logs
$ git lfs version
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3; git d2f6752)
$ git version
git version 1.8.3.1
$ git config --list
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=true
core.logallrefupdates=true
`

Maybe part of the problem is that kallithea listens on port 443 and does not forward requests to git-lfs batch file? But why batch is not created???

**Comment by technoweenie** [comment]
This repository is for the Git LFS client. Can you submit this to the repository for the server you're using? I don't know anything about kallithea, unfortunately.

**Comment by aido93** [comment]
I'm sorry. I thought that git-lfs could run as server too. Is this list of servers exhaustive? https://github.com/git-lfs/git-lfs/wiki/Implementations

**Comment by ttaylorr** [comment]
@aido93 Git LFS requires a server to implement its API, but is not itself run as a server. Perhaps you could be looking for https://github.com/git-lfs/lfs-test-server instead?
