### ISSUE TITLE
git lfs status shows "(%!s(MISSING))" even though files exist; push fails

### ISSUE THREAD

**Issue by fortytwoish** [git-lfs/git-lfs#2742]
We've done nothing but regular commits and pushes on this repository, on a single branch.
Since my last attempt to commit, this error has been stopping me from being able to push:

git lfs status shows
```
 $ git lfs status
 On branch master
 Git LFS objects to be pushed to origin/master:
 
         [...]
         Content/Maps/Prototypes/Autorunner.umap (%!s(MISSING))
         [...]
```
where in place of MISSING should be the file<->pointer ID pair, as I understand it. The files are exactly where the path points.

git lfs ls-files shows that the mappings exist:
```
$ git lfs ls-files
[...]
b798bb5c28 * Content/Maps/Prototypes/Autorunner.umap
[...]
```

git lfs fsck shows OK.

Pushing has an insane amount of failed attempts (Error 400), which is what causes it to fail:
```
< HTTP/1.1 400 Bad Request
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: application/xml
< Date: Mon, 20 Nov 17 17:05:16 GMT
< X-Amz-Id-2: kBk72rG1256kR8DKaICr4ZOyk9YUiZFRKzmDhO9GZaxhIC3owFc+T+zuIo44ZvcNvfNUAAU/HJq0hqTskx0uBjmONRdRh3Is
< X-Amz-Request-Id: 692689878F25C435
<
18:05:17.535382 trace git-lfs: tq: refusing to retry "3a4e9b5950000b5991682e48f35aaba79dc4d2ff76288aa1377038e424252aa0", too many retries (50)
18:05:17.572029 trace git-lfs: HTTP: 400
```
Upping the retry count didn't work. 

This concerns all lfs tracked files that I have changed locally. 
Anything else I could do to troubleshoot this? It's sadly quite hard to find answers for, since (%!s(MISSING)) can't be googled!

I'm hoping this is an error on my part.

**Comment by ttaylorr** [comment]
Hi @fortytwoish, thanks for opening this issue and sorry that you're having trouble! It looks like the `(%!s(MISSING))` error you pointed out is definitely a bug, and I'll make sure to get that fixed int he next release.

@technoweenie can you shed some light on the 400 HTTP response code?

**Comment by irizzant** [comment]
Hello
I'm having the very same issue here, here's the status of my `git lfs status`:
`
        WebPortalFrameworkJEEWeb/src/main/webapp/resources/sdb/css/icons/warning_64.png (%!s(MISSING))
        WMS/src/main/resources/it/sdb/apps/crmtrk/reports/wms/WmsPackingListByCartonSubReport1.jasper (%!s(MISSING))
        WMS/src/main/resources/it/sdb/apps/crmtrk/reports/wms/WmsWarehouseReceipt.jasper (%!s(MISSING))
        WMS/src/main/resources/it/sdb/apps/crmtrk/reports/wms/WmsXRaysScan.jasper (%!s(MISSING))`

is there any workaround found for this to allow me to push to the remote repo?

**Comment by ttaylorr** [comment]
Hi @irizzant, it looks like there are two things going on here:

1. Please check to make sure that you are running the latest version of Git LFS. This bug was fixed in #2746, which means that it will be present in v2.4.0 or newer.
2. Please make sure that you in fact have all of the LFS objects that you are attempting to push.

**Comment by irizzant** [comment]
Hi @ttaylorr 

1. As far as I can see the last downloadable version is 2.3.4, unless I'm misunderstanding
2. I identified those files were added with a commit to our master 2 days ago and I have them checked out in my filesystem (not the LFS pointer, the actual file content) so I assume they are available in our Nexus LFS server

Thanks

**Comment by ttaylorr** [comment]
> As far as I can see the last downloadable version is 2.3.4, unless I'm misunderstanding

You can download v2.4.0 [here](https://github.com/git-lfs/git-lfs/releases/tag/v2.4.0).
