### ISSUE TITLE
Fatal error: Unable to parse HTTP response for PUT https + files (MISSING)

### ISSUE THREAD

**Issue by yrazin** [git-lfs/git-lfs#2745]
Far from a git expert - I have git-lfs 2.3.4 set up for .fbx files.  Recently, can't do git push because i get the error

        $ git push origin master
        Git LFS: (0 of 1 files, 2 skipped) 0 B / 2.01 MB, 102.77 KB skipped
        Fatal error: Unable to parse HTTP response for PUT https://github.gatech.edu/storage/lfs/40493/objects/41241d5dcdb0189d3eee14208520866df38226ede4e86c135c43111eef131178: unexpected EOF
        error: failed to push some refs to 'https://github.gatech.edu/cec/rosdrive-unity.git'

when i do git lfs status i get

        On branch master
        Git LFS objects to be pushed to origin/master:

        Assets/Resources/Simple Tunnel.fbx (%!s(MISSING))
        Assets/Sports Car Multiple textures/Standard Assets/Environment/Water/Water/Models/WaterPlane.fbx (%!s(MISSING))
        Assets/Sports Car Multiple textures/Standard Assets/Environment/Water/Water4/Models/OceanPlane.FBX (%!s(MISSING))

        Git LFS objects to be committed:

        Git LFS objects not staged for commit:

Those files exist - git status show there is nothing to commit

No useful logs.

        $git lfs env
        git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)
        git version 2.15.0.windows.1

        Endpoint=https://github.gatech.edu/cec/rosdrive-unity.git/info/lfs (auth=basic)
        LocalWorkingDir=C:\dev\rosdrive\ROS Drive Unity
        LocalGitDir=C:\dev\rosdrive\ROS Drive Unity\.git
        LocalGitStorageDir=C:\dev\rosdrive\ROS Drive Unity\.git
        LocalMediaDir=C:\dev\rosdrive\ROS Drive Unity\.git\lfs\objects
        LocalReferenceDir=
        TempDir=C:\dev\rosdrive\ROS Drive Unity\.git\lfs\tmp
        ConcurrentTransfers=3
        TusTransfers=false
        BasicTransfersOnly=false
        SkipDownloadErrors=false
        FetchRecentAlways=false
        FetchRecentRefsDays=7
        FetchRecentCommitsDays=0
        FetchRecentRefsIncludeRemotes=true
        PruneOffsetDays=3
        PruneVerifyRemoteAlways=false
        PruneRemoteName=origin
        LfsStorageDir=C:\dev\rosdrive\ROS Drive Unity\.git\lfs
        AccessDownload=basic
        AccessUpload=basic
        DownloadTransfers=basic
        UploadTransfers=basic
        GIT_LFS_PATH=C:\Program Files\Git\cmd
        git config filter.lfs.process = "git-lfs filter-process"
        git config filter.lfs.smudge = "git-lfs smudge -- %f"
        git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by technoweenie** [comment]
That looks like a server issue. "Unexpected EOF" means the HTTP connection dropped suddenly before a successful HTTP response could be returned. Since you're using GitHub Enterprise, can you have your admin file an official support request? Then we can dig into what's going on with the server.

**Comment by yrazin** [comment]
I'm able to use that server from other computers fine as well as other repos on this computer

**Comment by ttaylorr** [comment]
Hey @yrazin, thanks for opening this issue. I agree with @technoweenie that it seems to be an issue with the server, even if it is localized to that particular repository in question. I have fixed the `%!s(MISSING)` issue (via: https://github.com/git-lfs/git-lfs/pull/2746).

I would also recommend sending in an official support request with your enterprise administrator with this issue.
