### ISSUE TITLE
how to programmatically test if a file is managed by LFS

### ISSUE THREAD

**Issue by kforner** [git-lfs/git-lfs#2748]
Hi,

Suppose for instance that I have a huge file in my repository. 
How to know if it is managed by LFS ? 

Thanks

**Comment by technoweenie** [comment]
You can verify in one of several ways. First, you can use `git lfs ls-files`:

```sh
$ git lfs ls-files | grep png/render.png
55d51edb30 * png/render.png
```

Though, a fool proof way is verifying the blob size in Git. A large file should have a blob size of about 130c:

```
# file is 48k
$ ls -al png/render.png
-rw-r--r--  1 rick  staff  48202 Nov 17 13:08 png/render.png

# only 130 bytes in git
$ git ls-tree master -rl | grep png/render.png
100644 blob ba2f35f8b0ec51d85ffcc973e5297e22682bb2cd     130	png/render.png
```

You can test to see if Git is interpreting your `.gitattributes` correctly too:

```sh
$ git ls-files ':(attr:filter=lfs)' | grep png/render.png
png/render.png
```

If you want to check all files, and not just a single file, remove the `grep` call.

**Comment by kforner** [comment]
Thanks !
Side-question:
Is it possible to check if the file is under LFS in constant time ? 

I mean, the `git lfs ls-files | grep` way is at least proportional to the number of LFS files.

**Comment by ttaylorr** [comment]
> Is it possible to check if the file is under LFS in constant time ?

One other way you can do this via `git-check-attr(1)` as:

```sh
git check-attr --all -- <filename> | grep "filter: lfs" 
```

**Comment by mdmithuislam** [comment]
Llkgfkjifmh.Gruber IHS guo.jtfh
