### ISSUE TITLE
Error fetching LFS file that exists on the server

### ISSUE THREAD

**Issue by thefuntastic** [git-lfs/git-lfs#2752]
An issue where I try to pull from a server (bitbucket) and I get this error message. Thing is the file does exist on the server, verified by successfully fetching into another clone. What happened here was that I had two remotes, and I had change the name of `origin` to `bitbucket`. No matter what I did, trying to reinstall lfs or update hooks or `git lfs fetch bitbucket --all` I could not recover from this state. The only fix I found was to reset `bitbucket` back to `origin`. 

The behaviour was also not consistent with the file that caused the error. In my attempts to reset and try solve the problem, I saw the same behaviour with a different upstream lfs file. Though it seems once one file has hit the error state, it will usually be that file which complains. 

I'm fetching through SSH 

```
Error downloading object: Assets/Plugins/PS4/libfmodL_stub.a (7ac611e): Smudge error: Error downloading Assets/Plugins/PS4/libfmodL_stub.a (7ac611ee2a2f2d8f992c892fd7e2a9be49768d7c945ae154883ca1e7bd6c3d6e): [7ac611ee2a2f2d8f992c892fd7e2a9be49768d7c945ae154883ca1e7bd6c3d6e] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
```

**Comment by technoweenie** [comment]
That's an error message from the server. Are the remote urls consistent and authenticated with a proper user account? Also, you may want to file something with Atlassian, as I can only troubleshoot from the perspective of the client.

**Comment by ttaylorr** [comment]
Hi @thefuntastic, I agree with @technoweenie that you may want to file something with Atlassian, since we can only offer help with the behavior of the Git LFS client. That said, I'd love to keep up-to-date with what goes on on the other end, to see if there's anything that we need to change/improve in the Git LFS client.

I'm going to close this for now, but please don't hesitate to share any updates in this thread.
