### ISSUE TITLE
rebasing an unpushed branch critically messes up the tree

### ISSUE THREAD

**Issue by fhuberts** [git-lfs/git-lfs#2760]
git-lfs can't find the objects (even though I expect it to find them in local storage).
after the failure I can abort the rebase but *can't* reset the tree to its checked-in state.
I can change to another branch (forced) but can't then check out the branch anymore.
Forces me to redo the work.

```
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: TMP DEBUG
Applying: moddev
Downloading <file> (37 KB)
Error downloading object: <file> (8a583f8): Smudge error: Error downloading <file> (8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79): [8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to <logdir>\20171129T121818.2142735.log
Use `git lfs logs last` to view the log.
fatal: <file>: smudge filter lfs failed

<prompt> (tmp|REBASE 2/3)
$ git rebase --abort
Downloading <file> (37 KB)
Error downloading object: <file> (8a583f8): Smudge error: Error downloading <file> (8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79): [8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to <logdir>\20171129T121827.9139467.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: <file>: smudge filter lfs failed

<prompt> (tmp)
$ git reset --hard;git clean -fdx
Downloading <file> (37 KB)
Error downloading object: <file> (8a583f8): Smudge error: Error downloading <file> (8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79): [8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to <logdir>\20171129T122003.0130663.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: <file>: smudge filter lfs failed
```

**Comment by ttaylorr** [comment]
Hi @fhuberts, thanks for opening this up. Is your repository open-source, or do you have a repository that is able to reproduce this issue?

**Comment by fhuberts** [comment]
Not an open repo, sorry.
But I think you can easily reproduce it.

In the meantime I think/guess that I have to push the objects to origin first before doing the rebase. However, it's unclear whether I have to push them to master or to my branch.
And even that seems wrong since my branch is a tracking branch on my 'public' remote, therefore I'd expect the lfs objects to be looked for on the 'public' remote.

**Comment by technoweenie** [comment]
Did you upload the objects to the remote first? The final error message in your output is:

> [404] Object does not exist on the server

**Comment by fhuberts** [comment]
no I did not

**Comment by technoweenie** [comment]
LFS won't download any objects in `.git/lfs/objects` too, so you don't necessarily need another server. The issue you're running into is that `git rebase` uses the internal clean/smudge filters while rebasing (which is the extension point that LFS hooks into). If LFS can't find the object `8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79` in `.git/lfs/objects/8a/58/8a583f803cd919e383db26fde2c9d411e7e3431f18a2ade7d141f9581536bc79`, then it'll ask the server.

**Comment by fhuberts** [comment]
Mmmm I just discovered something.
It's complaining about a file I copied over from another repo. That file appear to be a git-lfs ref file instead of the actual file somehow. After a few short tests that seems to be the actual problem.
Don't know why that file was not the actual file.

So, please accept my apologies for this false alarm.
