### ISSUE TITLE
git lfs ls-files --file option

### ISSUE THREAD

**Issue by kforner** [git-lfs/git-lfs#2761]
I have a use case where I need to able to programmatically and as quickly as possible:
- check if a given file is managed by LFS
- check if it is a pointer or the actual file
- get the pointer info

It seems that `git lfs ls-files` solves my problem, but it outputs the information for all LFS files, so I guess it would be faster if it could work on a single file/path, for example by adding a `--file path` option (like git lfs pointer).

Would it be of interest for the community ?

**Comment by ttaylorr** [comment]
I think that this would be interesting, and potentially useful. Can you post a more detailed specification of what you'd like your new command/option to do?

**Comment by technoweenie** [comment]
How about `--pattern`, which works with any pattern that `.gitignore` or `.gitattributes` supports?

```sh
$ git lfs ls-files
$ git lfs ls-files -p "*.gif"
$ git lfs ls-files -p "foo/*"
$ git lfs ls-files -p "foo/**/*"
$ git lfs ls-files -p "foo/bar/baz.zip"
```

I'm also interested in this idea. If someone knows or wants to learn a bit of Go, I think this would be a great little feature to contribute.

**Comment by ttaylorr** [comment]
> How about `--pattern`, which works with any pattern that `.gitignore` or `.gitattributes` supports?

@technoweenie I like this -- what about our standard `--include`, `--exclude` (which would allow searching for one or many files/directories).

**Comment by technoweenie** [comment]
Sure, consistency and flexibility :+1:

**Comment by ttaylorr** [comment]
Hey @kforner, thanks again for opening this issue and suggesting this great idea. I implemented this in https://github.com/git-lfs/git-lfs/pull/2793.

I built a version of Git LFS that contains these changes, just in case you want to try them out before the next release they are scheduled for, which is Git LFS v2.4.0:

[git-lfs-darwin-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1572507/git-lfs-darwin-386-2.3.4.tar.gz)
[git-lfs-darwin-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1572508/git-lfs-darwin-amd64-2.3.4.tar.gz)
[git-lfs-freebsd-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1572509/git-lfs-freebsd-386-2.3.4.tar.gz)
[git-lfs-freebsd-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1572510/git-lfs-freebsd-amd64-2.3.4.tar.gz)
[git-lfs-linux-386-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1572511/git-lfs-linux-386-2.3.4.tar.gz)
[git-lfs-linux-amd64-2.3.4.tar.gz](https://github.com/git-lfs/git-lfs/files/1572512/git-lfs-linux-amd64-2.3.4.tar.gz)
[git-lfs-windows-386-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1572513/git-lfs-windows-386-2.3.4.zip)
[git-lfs-windows-amd64-2.3.4.zip](https://github.com/git-lfs/git-lfs/files/1572514/git-lfs-windows-amd64-2.3.4.zip)

**Comment by kforner** [comment]
cool. Works great !
Thank you. 
As for parsing the output, would you suggest to use the debug output ? (for example for the exact size)

**Comment by ttaylorr** [comment]
> As for parsing the output, would you suggest to use the debug output ? (for example for the exact size)

Totally! The `--debug` mode has tons of info that should be machine parseable.
