### ISSUE TITLE
adding the file size to git lfs ls-files output

### ISSUE THREAD

**Issue by kforner** [git-lfs/git-lfs#2763]
It would be nice to also have the (actual) file size in the output of `git lfs ls-files`.
We would not need to inspect a pointer file anymore. 
It could be activated via an option if you don't want to modify the output (for downstream parsers)...

**Comment by ttaylorr** [comment]
@kforner Great idea -- I opened https://github.com/git-lfs/git-lfs/pull/2764 to add just this.

**Comment by kforner** [comment]
great !
