### ISSUE TITLE
Mapping of old sha1 to new sha1

### ISSUE THREAD

**Issue by hkrpavan** [git-lfs/git-lfs#2766]
After running git-lfs-migrate how to get mapping of old sha1 to new sha1 of all commits?

Also, what is the file git-lfs-migrate.mapdb? If it has old commit id to new commit id mapping how to dump it to text or csv file?

**Comment by ttaylorr** [comment]
Hi @hkrpavan, thanks for opening this issue, and good question. I can't off the top of my head think of any intuitive ways to find an old<->new SHA-1 mapping for Git objects, but your issue has got me thinking. Beyond tags, I think that it would be useful to retain this information in some format or another.

I propose adding `--object-map=<file>` to the `git-lfs-migrate(1)` 'import' mode, which will create a CSV at the given path, containing the following:

```
previous-oid,current-oid,object-type,previous-oid-type,current-oid-type
# ...
```

The migrate command already shows _reference_ OID changes, but not all of the objects in between. I can imagine scripting with this additional information would be helpful.

/cc @git-lfs/core what do you think?

**Comment by larsxschneider** [comment]
The CSV file sounds like a nice, unintrusive, approach.

Alternatively, we could extend the commit message [similar to cherry-picking](https://github.com/git/git/blob/35f6318d44379452d8d33e880d8df0267b4a0cd0/Documentation/git-cherry-pick.txt#L62-L64) (e.g. append `(Git LFS import from commit ABC123)` at the end of a each commit.

**Comment by technoweenie** [comment]
I like the idea of annotating the commits, since they're being rewritten anyway. A coworker brought up [the trailer format](https://git-scm.com/docs/git-interpret-trailers), which is an existing convention of adding metadata to a commit:

```
Update PSD file.

Signed-off-by: Super Artist <super.artist@example.com>
Migrate-lfs: abc12345656
```

**Comment by ttaylorr** [comment]
@larsxschneider @technoweenie I love these ideas. I think that we could split the difference and have `git-lfs-migrate(1)` accept a `--commit-msg` Go template option when running in 'import' mode.

I pushed a WIP this here: https://github.com/git-lfs/git-lfs/compare/migrate-commit-msg-tmpl.

```
~/src/repository (master) $ git lfs migrate import --everything --commit-msg="{{ original.Message }}\nMigrate-lfs: {{ original.SHA1 }}"
```

**Comment by technoweenie** [comment]
A template like that doesn't quite work. Git trailers should be separated from the commit message by a line break, but can be right next to each other.

Look at how `git interpret-trailers` adds the `Acked-by` trailer to the existing message that includes a trailer:

```sh
$ cat msg.txt
subject

message

Signed-off-by: Bob <bob@example.com>

$ git interpret-trailers --trailer 'Acked-by: Alice <alice@example.com>' --in-place msg.txt
$ cat msg.txt
subject

message

Signed-off-by: Bob <bob@example.com>
Acked-by: Alice <alice@example.com>
```

Also, I like how `git commit` includes the [`--signoff` flag](https://git-scm.com/docs/git-commit#git-commit--s) to include the trailer. I think the `migrate` command should be similar. What do you think about:

```sh
$ git lfs migrate import --everything --map-commits
```

**Comment by ttaylorr** [comment]
> A template like that doesn't quite work. Git trailers should be separated from the commit message by a line break, but can be right next to each other.

That's a good point, though I am not sure I understand why the template as-is wouldn't work. For instance, if the message is:

```
my awesome commit

Signed-off-by A U Thor <me@example.com>
```

Then adding a line break and another trailer will produce:

```
my awesome commit

Signed-off-by A U Thor <me@example.com>

LFS-migrate: 00decaf
```

which Git will still parse.

I think one way that this could be improved is by teaching the migrator to parse trailers as a separate part of the message, making the template:

```
--commit-msg="{{ .Message }}\n\n{{ .Trailers }}\nLFS-migrate: {{ .OriginalSHA1 }}"
```

and would produce:

```
my awesome commit

Signed-off-by A U Thor <me@example.com>
LFS-migrate: 00decaf
```

I am excited about adding this support for templates to the `git-lfs-migrate(1)` command for its flexibility, so I am wondering if the above will work.

**Comment by technoweenie** [comment]
Sure, it'll all _work_, but why force the user to specify it in a template? They'll likely just cargo cult the correct answer. A switch like `--map-commits` means we ensure all migrated repos standardize on the same trailer, and we worry about writing the correct number of `\n`'s to separate content.

**Comment by ttaylorr** [comment]
> [...] why force the user to specify it in a template?

Good question -- my thought was that users would have other interesting use-cases for modifying commit messages during a migration, perhaps including number of objects migrated, etc. This might be too unrealistic of an aspiration, but I think it would be interesting/powerful nonetheless.

Thoughts?

**Comment by hkrpavan** [comment]
Thank you all for your replies. Adding old commit id to git commit message will really help when browsing the history. I still feel the need for csv file generation as part of the import process. This will serve as report for the migration.

**Comment by larsxschneider** [comment]
> modifying commit messages during a migration

@ttaylorr : From my point of view is would be out of scope for the migrator. People could use the regular filter-branch command for this task, no?

**Comment by technoweenie** [comment]
I agree with @larsxschneider, they have tools for that kind of stuff already. Imagine this kind of workflow:

1. User has repository with big objects.
2. User runs `git lfs migrate --map-commits`, adding the trailer to every rewritten commit.
3. User runs filter-branch to further update the commits. Assuming they didn't specifically delete the `migrate` trailers, they'd still point to the original commits from step 1.
4. ???
5. Profit!

**Comment by ttaylorr** [comment]
Closed with https://github.com/git-lfs/git-lfs/pull/2929.

**Comment by pranavrajiv** [comment]
I am using git-lfs 3.3.0 but do not see the --map-commits flag? Is it called something different?
