### ISSUE TITLE
"Git credentials not found" for git-lfs-2.3.3, but work well for git-lfs-2.0.2

### ISSUE THREAD

**Issue by canyou2014** [git-lfs/git-lfs#2768]
Error:
```
$ git-lfs.exe smudge -- feedback/install/component/jdk-8u151-linux-x64.tar.gz
Error downloading object: feedback/install/component/jdk-8u151-linux-x64.tar.gz (c78200c): Smudge error: Error downloading feedback/install/component/jdk-8u151-linux-x64.tar.gz (c78200ce409367b296ec39be4427f020e2c585470c4eed01021feada576f027f): batch response: Git credentials for http://rnd-isourceb.huawei.com/SCP/Feedback.git/info/lfs not found:
exec: "D:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass": file does not exist
```

ENV:
```
windows7
git-lfs/2.3.3
git version 2.6.4.windows.1
```

**Comment by ttaylorr** [comment]
Hi @canyou2014, thanks for opening this and sorry that you're having trouble.

I think what's going on here is that either:

> ```
> exec: "D:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass": file does not exist
> ```

I think that what's going here is either that:

1. Your default credential helper changed between upgrades, or
2. Something moved the location of `git-gui--askpass`, causing the unchanged value for your credential helper to become invalid.

Can you see if either one of these occurred?

**Comment by canyou2014** [comment]
@ttaylorr Thanks for your response. 

I am sure the location of `git-gui-askpass` was right there at that time. 

What do you mean `default credential helper changed between upgrages`?

**Comment by ttaylorr** [comment]
> What do you mean `default credential helper changed between upgrages`?

Sorry, this was a typo -- I meant to ask whether the distribution of Git you're using had changed the credential helper that is uses by default, if one is not explicitly configured.
