### ISSUE TITLE
Migration instructions should include instructions  to clean up .git directory

### ISSUE THREAD

**Issue by dustinfreeman** [git-lfs/git-lfs#2775]
From reading the migration instructions [here](https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs).

After I follow this, I can successfully convert pre-existing git objects to lfs objects. However, the regular objects still persist in the `.git` directory. After searching around, it appears suggestions for cleaning up the `.git` directory are non-trivial, and `git-lfs-migrate` does not do it itself.

Here's what I used successfully:
```
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```

However, I'm not sure if this is standard or recommended. This feels pretty opaque. If this is the best approach, I can issue a pull request to update the documentation.

**Comment by technoweenie** [comment]
That's a great tip! Git will eventually get around to removing those objects, but this just forces the expiration and gc to happen right now. It doesn't affect what is pushed to remotes though.

**Comment by dustinfreeman** [comment]
@technoweenie, it would indeed be nice if, for other remotes, any time the set of lfs files tracked was changed via a pull, then reflog/gc was run locally. At the moment, I don't think there's a way to do this other than telling remote team members to do so. And in the spirit of being cautious, maybe this isn't recommended anyway?

I'm still trying to answer: is the reflog/gc command I wrote the best way to do this at the moment? If so, I'll create a pull request

**Comment by ttaylorr** [comment]
> I'm still trying to answer: is the reflog/gc command I wrote the best way to do this at the moment? If so, I'll create a pull request

I think that this is the best recommended solution that I can come up with for now, so I'd be happy to accept a patch for this.

**Comment by dustinfreeman** [comment]
I just realized anyone could edit the wiki, and a formal pull request isn't required!

Done: https://github.com/git-lfs/git-lfs/wiki/Tutorial#cleaning-up-the-git-directory-after-migrating
