### ISSUE TITLE
Excuse me, how to upload a.Framework file that is larger than 100M through git-lfs?

### ISSUE THREAD

**Issue by sunjinlong123** [git-lfs/git-lfs#2776]
Excuse me, how to upload a .Framework file that is larger than 100M through git-lfs?

**Comment by ttaylorr** [comment]
Hi @sunjinlong123, thanks for opening this issue! Git LFS absolutely supports files larger than 100mb, and you can get started using the guide on our website: https://git-lfs.github.com/.

Please don't hesitate to re-open this issue if you run into any problems.

**Comment by RiberWang** [comment]
I use this method and input git lfs ls-files, but it's not show files of frameworks.

**Comment by RiberWang** [comment]
> Excuse me, how to upload a .Framework file that is larger than 100M through git-lfs?

Are you resolved this problem now?
