### ISSUE TITLE
Download button on github website doesn't fetch LFS files

### ISSUE THREAD

**Issue by ShacharWeis** [git-lfs/git-lfs#2777]
If I download the repo as a zip files directly from github, I get placeholders instead of LFS-tracked files.

**Comment by ttaylorr** [comment]
Hi @ShacharWeis, thanks for opening this issue! I am going to note this suggestion and close this issue for now, since this repository is for Git LFS-related issues and questions, and your comment is GitHub related.

**Comment by borjafac** [comment]
Is this still a thing? I also don't know how to know how much size I do have in LFS files, is there any way to look this value? On Bitbucket there's an option on the project where you can see all the LFS files and their size, I can't see anything like that on github :/

**Comment by ttaylorr** [comment]
> Is this still a thing?

Yes. GitHub Pages does not show the contents of files tracked by Git LFS. The reasoning behind this is that these files can be (by definition) large, and thus unsuitable for the web.

> I also don't know how to know how much size I do have in LFS files

I'm not sure if there is a user-facing way to do this, but GitHub support can certainly see it. Please email support@github.com to ask, and they'll be happy to help you out.
