### ISSUE TITLE
smudge error

### ISSUE THREAD

**Issue by swaingyanranjan** [git-lfs/git-lfs#2787]
Hi Team,
We are facing below error while cloning the repo.

Error downloading object: (): Smudge error: Error downloading (): batch response: Post batch: x509: certificate signed by unknown authority.

```
ENV:
LocalWorkingDir=/data/eme007/gyana3/tetra
LocalGitDir=/data/eme007/gyana3/tetra/.git
LocalGitStorageDir=/data/eme007/gyana3/tetra/.git
LocalMediaDir=/data/eme007/gyana3/tetra/.git/lfs/objects
LocalReferenceDir=
TempDir=/data/eme007/gyana3/tetra/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/data/eme007/gyana3/tetra/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
```

**Comment by ttaylorr** [comment]
Hi @swaingyanranjan, thanks for opening this issue and sorry that you're having trouble. Can you make sure that your system's SSL configuration is set correctly and that the remote you're cloning from has a valid SSL certificate?

**Comment by swaingyanranjan** [comment]
Hi Taylor,
We have another machine, which is using the same artifactory server to pull the libs. But that is not giving any issues, whereas this machine is showing errors.
And our SSL certificate is valid.

**Comment by swaingyanranjan** [comment]
Please help to reopen this issue. Somehow I don't see the option to reopen this issue.

**Comment by ttaylorr** [comment]
Hi @swaingyanranjan; I'm wondering if there is there is any notable difference between the configuration of the two machines you're talking about here. Are they running the same operating system (same version?), do they have different SSL configurations, etc?
