### ISSUE TITLE
After setting lfs.locksverify to False, authentication exits with status 255

### ISSUE THREAD

**Issue by matthiasroder** [git-lfs/git-lfs#2791]
Having added changes and committing every thing seems fine.

`git lfs status`

gives me the files that are supposed to be pushed.

Pushing with

`git push origin development`

I get:

```
Git LFS: (0 of 9 files) 0 B / 612.34 MB
batch request: git@github.com: Permission denied (publickey).: exit status 255
error: failed to push some refs to 'git@github.com:KarajanResearch/musicData.git'
```
What is the problem here?

Some more information:

`git lfs env`

gives me:

```
git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)
git version 2.15.1.windows.2

Endpoint=https://github.com/KarajanResearch/musicData.git/info/lfs (auth=none)
  SSH=git@github.com:KarajanResearch/musicData.git
LocalWorkingDir=C:\Users\m.roeder\codebase\musicData
LocalGitDir=C:\Users\m.roeder\codebase\musicData\.git
LocalGitStorageDir=C:\Users\m.roeder\codebase\musicData\.git
LocalMediaDir=C:\Users\m.roeder\codebase\musicData\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\m.roeder\codebase\musicData\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\m.roeder\codebase\musicData\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

**Comment by ttaylorr** [comment]
Hi @matthiasroder, thanks for opening this up, and sorry that you're having trouble! I think what's going on here is that your SSH agent used by Git is providing a publickey that is no longer valid on GitHub.com. Can you take a look at [this](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) article and try again afterwords?

Feel free to re-open this if the issues persist.

**Comment by matthiasroder** [comment]
Hi @ttaylorr , thanks for your reply. Unfortunately this is not the solution to the problem. I should mention that the key works perfectly on non lfs repos and it has worked on that particular repo before as well.

It seems to be the case that the problem occurs after switching off locksverification.

**Comment by matthiasroder** [comment]
PS: I am not sure how to reopen this issue.

**Comment by ttaylorr** [comment]
@matthiasroder: hm, can you retry that same command that exited uncleanly with `GIT_TRACE=1` and `GIT_CURL_VERBOSE=1` in your environment and post the logs here? Make sure to strip out any `Authorization` headers that will appear in the output first.

**Comment by matthiasroder** [comment]
```
20:51:38.352969 git.c:344               trace: built-in: git 'push' 'origin' 'development'
20:51:38.355971 run-command.c:626       trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '\''KarajanResearch/musicData.git'\'''
Enter passphrase for key '/c/Users/m.roeder/.ssh/id_rsa':
20:51:48.304427 run-command.c:626       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@github.com:KarajanResearch/musicData.git'
20:51:48.472988 git.c:576               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@github.com:KarajanResearch/music
Data.git'
20:51:48.473989 run-command.c:626       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github.com:KarajanResearch/musicData.git'
20:51:48.545171 trace git-lfs: run_command: 'git' version
20:51:48.660616 trace git-lfs: run_command: 'git' config -l
20:51:48.742626 trace git-lfs: tq: running as batched queue, batch size of 100
20:51:50.754130 trace git-lfs: pre-push: refs/heads/development ca8729858d61c67e6785bdd8f01093161eb616a9 refs/heads/deve
lopment be27c8655fd6c5b0692b32d85d37fcab430fe03b
20:51:50.757054 trace git-lfs: run_command: git rev-list --objects ca8729858d61c67e6785bdd8f01093161eb616a9 --not --remo
tes=origin --
20:51:50.990537 trace git-lfs: run_command: git cat-file --batch
20:51:51.044762 trace git-lfs: tq: sending batch of size 9
20:51:51.044762 trace git-lfs: run_command: ssh -- git@github.com git-lfs-authenticate KarajanResearch/musicData.git upload
20:51:53.071198 trace git-lfs: ssh: git@github.com failed, error: exit status 255, message: git@github.com: Permission denied (publickey).
Git LFS: (0 of 9 files) 0 B / 612.34 MB
batch request: git@github.com: Permission denied (publickey).: exit status 255
error: failed to push some refs to 'git@github.com:KarajanResearch/musicData.git'
```

**Comment by ttaylorr** [comment]
@matthiasroder This line:

> ```
> Git LFS: (0 of 9 files) 0 B / 612.34 MB batch request: git@github.com: Permission denied (publickey).: exit status 255
> error: failed to push some refs to 'git@github.com:KarajanResearch/musicData.git'
> ```

Indicates that the public key your ssh_agent is sending to GitHub is invalid. This could be your ssh_agent sending the wrong SSH public key, or one that is invalid.

**Comment by sbmueller** [comment]
I experience the same issue. @matthiasroder did you ever find a solution?

**Comment by escrowdis** [comment]
Hi there,
I succeeded to push local commits to my repo using **Git Bash!!!**. Have no idea why it failed using cmd on Windows 10.

**Comment by hookery** [comment]
you save my ass!using Git Bash can make it !!!thank you! @escrowdis

**Comment by BihtSift** [comment]
I'm having this exact issue.  Switching to https worked for me.  SSH does not work with LFS for me at all.  My public key is fine as it works with all my repos and it worked initially with my repo during init with my .gitattributes which enabled LFS, then failed on the next push.

**Comment by JonasVautherin** [comment]
Same here: switching to HTTPS worked. SSH does not.

**Comment by bk2204** [comment]
Hey,

If you're seeing this problem and non-LFS pushes normally work with that key, please open a new issue, filling out the issue template, and we'll look.  Note that you cannot use the built-in Windows OpenSSH client because it is known to be broken, but the one shipped with Git for Windows is fine.

**Comment by ZhongQiyu** [comment]
You may need to try to bind your login tokens with the LFS so that they will set up.
