### ISSUE TITLE
Git LFS install on Ubuntu 16.04 via package cloud generates warnings

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#2792]
I just installed Git LFS on Ubuntu 16.04 via package cloud:
```sh
$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
$ sudo apt-get install git-lfs
```

Afterwards I noticed this warning on `fstab` / `mtab` calls:
```
$ mtab
WARNING:root:could not open file '/etc/apt/sources.list.d/github_git-lfs.list'
```

Is this a known issue? Is this a Git LFS or package cloud problem? I haven't investigated further, yet.

**Comment by larsxschneider** [comment]
Plus, I get this output:

```
$ git lfs
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
Sorry, no usage text found for "git-lfs"
```

... looks like the man pages are not configured correctly?

**Comment by ttaylorr** [comment]
Hm, that first one seems like an issue with PackageCloud, but the second one is known.
