### ISSUE TITLE
Consecutive asterisks pattern not supported in git lfs migrate?

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#2798]
Hi,

the following, AFAIK valid, `.gitattribute` pattern does not work with `git lfs migrate`:
```
git lfs migrate import --verbose --everything -I '**/*.foo/bar/data/**'
```

[See Git docs for `**` syntax](https://github.com/git/git/blob/936d1b989416a95f593bf81ccae8ac62cd83f279/Documentation/gitignore.txt#L116-L127). I tested with Git LFS v2.3.4 and the [v2.4 pre-release](https://github.com/git-lfs/git-lfs/issues/2679#issuecomment-350896658). Is this considered a bug? If yes, then I am happy to provide more details and a test case.

Thanks,
Lars

BTW: `git lfs migrate` is awesome - insanely fast. 👍👍👍

**Comment by larsxschneider** [comment]
The following workaround seems to work for the most part:
```
git lfs migrate import --verbose --everything -I 'some/path.foo/bar/data/**'
```

However, `git lfs migrate` did not migrate the following files:
```
some/path.foo/bar/data/other/dir/bla.bar/more/dirs/file
```
... my guess is that the `bla.bar` might be the cause.

**Comment by larsxschneider** [comment]
```
git lfs migrate import --verbose --everything -I 'some/path.foo/bar/data/other/dir/bla.bar/more/dirs/*'
```
... doesn't migrate the file either 😢

**Comment by technoweenie** [comment]
Yup, looks like a bug. Thanks for the report.
