### ISSUE TITLE
Redesign CLI progress indicator: Upload size > Total size

### ISSUE THREAD

**Issue by bitinn** [git-lfs/git-lfs#2802]
Even for a successful `git push`, we often see this kind of reports:

```
$ git push
Git LFS: (22 of 22 files, 7 skipped) 227.26 MB / 203.26 MB, 750.98 KB skipped  
Counting objects: 63, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (63/63), done.
Writing objects: 100% (63/63), 2.01 MiB | 280.00 KiB/s, done.
Total 63 (delta 27), reused 0 (delta 0)
remote: Resolving deltas: 100% (27/27), completed with 17 local objects.
```

This line:

> Git LFS: (22 of 22 files, 7 skipped) 227.26 MB / 203.26 MB, 750.98 KB skipped

Unless you know exactly what's going on with Git LFS, you see no explanation for why upload size should exceed total size. After all, didn't we skip some files?

I am sure, there are *many* logically explanations to why upload size can be larger than total size. But I argue none of them matter to end users:

- Git LFS use *(upload size / total size)* as a progress indicator during `git push`.
- Yet upload size often exceed total file size, for an arbitrary amount.
- This is like having a progress bar going beyond its total bar length.
- The end result is users no longer trust this indicator.

----

The situation is worsen, if you are on a slow network, and run into connection problems:

```
$ git push
Git LFS: (7 of 29 files) 148.80 MB / 203.99 MB                                 Connection to github.com closed by remote host.
Git LFS: (7 of 29 files) 265.05 MB / 203.99 MB      
```

```
$ git push
Git LFS: (0 of 22 files, 7 skipped) 147.62 MB / 203.26 MB, 750.98 KB skipped   Connection to github.com closed by remote host.
Git LFS: (0 of 22 files, 7 skipped) 261.66 MB / 203.26 MB, 750.98 KB skipped
...
```

In this case users have no idea: (a) when the upload will be done, and (b) whether the push will be successful.

All they can do are wait.

And boy have I seen some disappointing failed git push. I seldom see subsequent Git LFS *skipping files* actually reduce the upload size.

----

I argue Git LFS could do better by:

A) Just don't use transfer size as a progress indicator.
B) Clarify how "skipped" files actually work.
C) Compare Git LFS to any other file syncing service (like OneDrive), and figure out what users actually want to see?

I wasn't able to convince non-technical coworkers to use Git LFS; now I am half-convinced I can't actually use it myself.

/End of my rant. Wish everyone a merry xmas!

**Comment by technoweenie** [comment]
Thanks for the feedback. There's been some work in the master branch to bring the `migrate` commands more git-like output to the rest of LFS. However, this specific line hasn't been touched yet. One of the challenges we face here is that LFS is being run _by_ Git. LFS has no control over what other output Git may want to send (such as that "Connection to github.com" message).

> Just don't use transfer size as a progress indicator.

What would you suggest? It's granular enough to show actual progress. Would you prefer to see just  a %?

> Clarify how "skipped" files actually work

There is a lot of confusion here. It may be better to leave that part out of the description, and just count that data as already completed. A skipped file is one that already exists on the LFS server.

**Comment by bitinn** [comment]
@technoweenie 

For the progress indicator format:

- If you use `X%`, X should never go over 100.
- If you use `X MB / Y MB`, X should never go over Y.
- Otherwise the progress indicator is not doing much for users: `99 MB / 100 MB` no longer means `git push` will finish soon, as it can go up to `150 MB / 100 MB` and more.

For the progress indicator data:

- It depends on how LFS actually works.
- If LFS is uploading files in sequence, then it should use _(uploaded file size / total file size)_ as an indicator, instead of _(network transfer / total file size)_. At least that's how I interpret it when X goes over Y.
- If LFS is not uploading in sequence, then showing `(0 of 22 files, 7 skipped) 261.66 MB / 203.26 MB, 750.98 KB skipped` is moot. It tells users nothing about actual progress. And I will have to say this line is complete voodoo to me.

**Comment by technoweenie** [comment]
Oh, your beef is the progress is higher than the total! Doh, I totally mis-read the post title. I uh, understand match, but read it as an arrow :/ 

Definitely a bug. I think what's happening is a file transfer is retrying, and some of the re-uploaded bits are being double counted.

Can you run `git lfs env`? That'll tell me what version and what transfer type you're using.

**Comment by bitinn** [comment]
```
$ git lfs env
git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.1)
git version 2.14.1

Endpoint=https://github.com/bitinn/***.git/info/lfs (auth=none)
  SSH=git@github.com:bitinn/***.git
LocalWorkingDir=/Users/df/git/***
LocalGitDir=/Users/df/git/***/.git
LocalGitStorageDir=/Users/df/git/***/.git
LocalMediaDir=/Users/df/git/***/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/df/git/***/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/df/git/***/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
Hi @bitinn, thanks for opening this, and sorry for the slow response on my end. I agree with @technoweenie that this looks like a bug to me: the progress meter should not be counting past 100% (either in percentages, or in `X / Y` likes, but that is a different issue).

Can you attach the output of `GIT_TRACE=1 git push` for an invocation of this command that counts past 100%? My hunch is that this is related to the transfer adapter you're using (basic, in this case) over-counting, and some `GIT_TRACE=1` would help confirm that.

That all said, I think that moving away from the current Git LFS-style progress meter and towards a Git-like one would be sensible. My thought is to have the following format:

```
Transferring LFS objects:  57% (57 MB / 100 MB)
# ...
```

where objects that are already present on the server (and are currently marked as "skipped") would already be counted as having been completed.

I think that we can use this opportunity to remove the "number of files" indicator, since I'm not totally sure if the information it's providing is useful. I think that the main benefit of keeping it is that we retain information like "oh, there is 100mb left, spread over 10 files", or "oh, there is 100mb left, but only in one file". That said, I think the main thing that affects transfer time is the amount of data there is to transfer, not the number of files where that data is present (unless there is an abnormally large number of files, in which case overhead from the batch API would come into play, but this is highly unlikely).

**Comment by bitinn** [comment]
@ttaylorr Thx. I will have to get back to you on that, we have stopped using LFS for very large files, ironically. (100MB ~ 1GB range, this range is quite common for game development by the way.)

**But one thing you can do to simulate our situation: get a network proxy app that simulate slow and bad network.** I am not sure whether `basic` adapter is the default for LFS, but I can confirm we are using proxies (via `git config --global http.proxy`), because our networking routing to GitHub sucks.

Back to the progress indicator design: I think `Transferring LFS objects:  57% (57 MB / 100 MB)` is great, that's all I care about really. Since LFS is counting through network adapter, the % progression will be smooth. And it should be the main indicator, not `(0 of 22 files, 7 skipped)`.

**Comment by technoweenie** [comment]
We have a fix for the race conditions: https://github.com/git-lfs/git-lfs/pull/2807

Also, @ttaylorr is working on some changes to the output too. All of this should make it in v2.4, hopefully in the next week or so. 

Thanks for the report!

**Comment by technoweenie** [comment]
Re-opening until the race condition is fixed. Current PR is https://github.com/git-lfs/git-lfs/pull/2807

**Comment by ttaylorr** [comment]
Moving this issue into #2807.
