### ISSUE TITLE
Ubuntu 17.10 artful repository not found.

### ISSUE THREAD

**Issue by wnoguchi** [git-lfs/git-lfs#2804]
I have installed Git LFS some days ago.
but since yesterday or today ubuntu update fails.

```
wnoguchi@serial:~$ export LC_ALL=en_US.UTF-8
wnoguchi@serial:~$ sudo apt -y update
Hit:1 http://jp.archive.ubuntu.com/ubuntu artful InRelease
Hit:2 http://jp.archive.ubuntu.com/ubuntu artful-updates InRelease
Hit:3 http://jp.archive.ubuntu.com/ubuntu artful-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
Hit:5 http://ppa.launchpad.net/git-core/ppa/ubuntu artful InRelease
Ign:6 https://packagecloud.io/github/git-lfs/ubuntu artful InRelease
Err:7 https://packagecloud.io/github/git-lfs/ubuntu artful Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

https://packagecloud.io/github/git-lfs/ubuntu

is rails 404

i found near issue #2702 .

I temporarily commented out `/etc/apt/sources.list.d/github_git-lfs.list` lines.

```
#deb https://packagecloud.io/github/git-lfs/ubuntu/ artful main
#deb-src https://packagecloud.io/github/git-lfs/ubuntu/ artful main
```

Any ideas?

Thanks.

**Comment by hardsetting** [comment]
Had the same error today.
Thank you @wnoguchi for the temporary fix.

**Comment by technoweenie** [comment]
Artful support was just added, it'll be pushed up with the next release (v2.4).

**Comment by wnoguchi** [comment]
@technoweenie Hmm, I understood !
My local git-lfs version is v2.2.1.
Waiting for next release v2.4.

```
wnoguchi@serial:~$ export LC_ALL=en_US.UTF-8
wnoguchi@serial:~$ apt-cache policy git-lfs
git-lfs:
  Installed: 2.2.1-1
  Candidate: 2.2.1-1
  Version table:
 *** 2.2.1-1 500
        500 http://jp.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status
```

But I'm wonder why my first git-lfs installation success.

Thanks.

**Comment by ttaylorr** [comment]
> But I'm wonder why my first git-lfs installation success.

I think that this older release may have been pushed in error to that target, sorry!

**Comment by wnoguchi** [comment]
Thanks!

**Comment by lemieux** [comment]
`https://packagecloud.io/github/git-lfs/ubuntu` is still returning 404. I'm pretty sure it was working fine last friday.

**Comment by sschuberth** [comment]
Same here, @technoweenie can you please have a look?

**Comment by sschuberth** [comment]
Sorry, I just found [this](https://github.com/git-lfs/git-lfs/issues/2702#issuecomment-350898401) again, saying that we need to wait until the next (2.4.0) release.
