### ISSUE TITLE
Windows defender detects trojan in Git LFS installer

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#2805]
At my workplace we automatically distribute Git LFS. We download the binary from GitHub, check the SHA256, and install it.

Right now we are distributing `v2.3.3` with the hash `30d3a464222a0dd04b79cc2217c6cef46fcf3389994d37fba1b49e7fcf84b586` ([git-lfs-windows-2.3.3.exe](https://github.com/git-lfs/git-lfs/releases/tag/v2.3.3)).

Today, I got a report that Windows Defender detected the Trojan "Win32/Peals.F!cl" in `git-lfs-windows-2.3.3.exe`. [Other applications](https://www.reddit.com/r/sysadmin/comments/7o19q0/trojanwin32pealsfcl_false_positives_in_windows/) seem to experience the same issue.

I don't expect a fix for the problem from the Git LFS folks. I just wanted to document the issue for others.

---

Environment of the affected machine:
```
Microsoft Windows [Version 10.0.14393]
Antimalware Client Version: 4.10.14393.0
Engine Version: 1.1.14405.2
Antivirus definition: 1.259.1117.0
Antispyware definition: 1.259.1117.0
Network Inspection System Engine Version: 2.1.14202.0
Network Inspection System Definition Version: 118.2.0.0
```

**Comment by shiftkey** [comment]
For reference, the VirusTotal results for [`git-lfs-windows-2.3.3.exe`](https://www.virustotal.com/#/url/609900bc6a18646bbf90a7253f4ea9f1a732121211654898bba1394d7bf942de/detection) and [`git-lfs-windows-2.3.4.exe`](https://www.virustotal.com/#/url/3c23b6c308bc9e9974fdeac52a76149cdd1ecbc6ac01f73f0921abbfe25a9c49/detection) seem clean...

**Comment by larsxschneider** [comment]
Updating the Antivirus definitions to the latest version `1.259.1155.0` fixed the issue for us!

**Comment by technoweenie** [comment]
From your reddit thread:

> I spoke with MS about this. They confirmed it was a false-positive coming from the Windows Defender cloud protection service. It has been resolved as of this morning, but if your devices have been unlucky enough to run a scan between last night and this morning, it may have impacted good applications. If a client has the bad definitions cached, you can clear with with the command `C:\Program Files\Windows Defender\MPCmdRun.exe -removedefinitions -dynamicsignatures`. After clearing cache, run a definition update.
