### ISSUE TITLE
Git lfs is didn't working, but used 0/1gb

### ISSUE THREAD

**Issue by TiGRoNdev** [git-lfs/git-lfs#2812]
Hi I've a problem with pushing lfs files to EzComm/CrimePunishment. I have 0/1gb bandwith used and 0/1gb sstorage used but i still cannot push. I've tracked my lfs files but all i get when i push is this error:

batch response: Git LFS is disabled for this repository.

How can i solve that ?

**Comment by ttaylorr** [comment]
Hi, please follow up with `support@github.com` for issues pertaining to pushing to GitHub.com.
