### ISSUE TITLE
Installed Git LFS and gitattributes file - Pushed from gitkraken but no change on remote. 

### ISSUE THREAD

**Issue by nickproud** [git-lfs/git-lfs#2814]
After I installed Git-LFS and set up a gitattributes file for my existing repo, I pushed from gitkraken using the LFS push feature and I am seeing no change in Github. Kraken says that the push was successful for LFS files only. 

I added files which I can see are being tracked for LFS and the push again looked fine in the client but nothing changes in GitHub. 

If I do a normal push, I see the changes as expected. Anybody think this is a gitkraken issue? Or could it be something to do with installing lfs with an existing repo?

**Comment by ttaylorr** [comment]
> If I do a normal push, I see the changes as expected. Anybody think this is a gitkraken issue? Or could it be something to do with installing lfs with an existing repo?

Hi @nickproud, thanks for opening this. GitKraken currently does not support Git LFS, so this is an issue pertaining to GK.

If you wish to push a repository with LFS-tracked files, the command line interface should work just fine.

**Comment by nickproud** [comment]
Excellent. Thanks for your fast response!

**Comment by NeatWolf** [comment]
I guess it does now :)

https://support.gitkraken.com/git-workflows-and-extensions/git-lfs/
