### ISSUE TITLE
Question on client relationship with git lfs repo

### ISSUE THREAD

**Issue by sotbl** [git-lfs/git-lfs#2816]
Does a client need to have LFS installed on their machine if they will be committing changes to the text source files, but not changing any of the files tracked by LFS? 

EX: will a remote repo that is set up to handle LFS integration, properly send the latest large files to all clients, and their local history will allow them to make changes to the non LFS files and if they pull new code, they'll get the newer large files? Maybe that works fine but then they'd have both versions of the binaries and without LFS installed, the pruning wouldnt happen?

**Comment by ttaylorr** [comment]
> Does a client need to have LFS installed on their machine if they will be committing changes to the text source files, but not changing any of the files tracked by LFS?

Hi @sotbl, great question! The answer is no: clients working with copies of the repository need not have LFS installed on their machine, so long as they do not need to work with LFS-tracked files within the repository.

A longer explanation of why this is the case follows: Git LFS works by intercepting large objects _before_ they are committed into the repository, as well as _before_ they are checked out into the working copy. The result is that, for machines using LFS, it would appear as if the large files were checked into the history of the repository using Git, when in fact they are stored elsewhere. So, without Git LFS installed, a user checking out a copy of a repository that _does_ use LFS will not be able to intercept the pointer objects that replace the large blobs, and will have pointer files in place of their large objects.

Like above, if these users do not need to access the contents of the large objects, they will be fine to use an LFS-enabled repository without having LFS installed.

That said, if a user is working as described above, and they commit a large object that should be tracked using Git LFS, users that _do_ have Git LFS installed will get a warning upon checkout saying that the file is modified. They can confirm the object IDs in question using `git lfs status`, and fix the broken history using `git lfs migrate import`.

**Comment by sotbl** [comment]
Thanks for the great clarification @ttaylorr .

So just to clarify, if the clients won't need to update any large files that are tracked with LFS, but they would need the binaries themselves in order to build the app, then they'd need LFS installed so that they have the actual large files rather than the pointers, because if they clone and try to build, without LFS installed, then they'd be trying to build with /some/binary/file.bin that is actually the small pointer file?

**Comment by ttaylorr** [comment]
@sotbl correct, yes.
