### ISSUE TITLE
Is it possible to prevent git client without LFS from pushing code to repo which enable LFS

### ISSUE THREAD

**Issue by herman-chen** [git-lfs/git-lfs#2824]
Hi All,
    I used LFS in our git repo but had one problem. After enable LFS in the repo,  our team member  push the binary file without lfs install.  It will cause the issue which has error tip "Pointer file error: Unable to parse pointer at". My question is if it possible to prevent it happens. Thanks!

**Comment by ttaylorr** [comment]
> My question is if it possible to prevent it happens. Thanks!

Hi @herman-chen, thanks for opening this issue and asking a great question -- here's a few ideas:

1. You can use a Git hook locally (so long as you have a way to ensure that everyone using your repository has the hook installed). The hook (perhaps `.git/hooks/pre-commit`) could do something as follows:

    - For each file in `git diff-index -M HEAD`, run `git check-attr /path/to/file`, and `egrep(1)` the output for `[^\^]filter=lfs`.

    - If any files exist that _are_ tracked using Git LFS, ensure that they are in pointer form. If not, `exit 1` and reject the commit, indicating that the user must install Git LFS. Something like the following may work:

```sh
TOO_BIG=0

git diff-index -M -B -C HEAD |
  while read line; do
    local filename="$(echo "$line" | awk '{ print $6 }')"
    if ! [ -z "$(git check-attr -a "$filename" | grep "filter=lfs")" ]; then
      local sha="$(echo "$line" | awk '{ print $4 }')"
      echo "$sha"
    fi
  done | git cat-file --batch-check | grep -v "blob 130" |
  while read big; do
    TOO_BIG=1:
    echo >&2 "fatal: $big is too large and must use LFS";
  done

if [ $TOO_BIG = 1 ]; then
  exit 1
fi
```

2. An alternative approach would be to do verification on your Git host in the pre-receive pack step to check whether or not there are files in the push that are too large and should be tracked using LFS (according to a similar script as above).
 
    This functionality is not something that GitHub offers currently.

**Comment by naseemkullah** [comment]
https://github.com/ActionsDesk/lfs-warning now has this functionality
