### ISSUE TITLE
unable to push to saml-enabled organization via SSH

### ISSUE THREAD

**Issue by timor-raiman** [git-lfs/git-lfs#2826]
Not able to push:
```
lfs-test$ git remote -v
origin  git@github.com:IntelRealSense/test_git-lfs.git (fetch)
origin  git@github.com:IntelRealSense/test_git-lfs.git (push)
lfs-test$ git push -u origin master
Git LFS: (0 of 2 files) 0 B / 2.00 MB
batch response: Resource protected by organization SAML enforcement. Use a personal token that has been granted access to this organization.
error: failed to push some refs to 'git@github.com:IntelRealSense/test_git-lfs.git'
```
while:
```
lfs-test$ ssh git@github.com git-lfs-authenticate IntelRealSense/test_git-lfs.git upload
{
  "href": "https://lfs.github.com/IntelRealSense/test_git-lfs",
  "header": {
    "Authorization": "RemoteAuth *****************************************=="
  },
  "expires_at": "2018-01-18T19:58:28Z",
  "expires_in": 21599
}
```
I would expect that the authorization token returned by git-lfs-authorize whould be pre-authorized for the sso organization.

If I switch the remote url to https, I'm able to push with an sso-authorized token. The token is stored in the credential store (I'm not asked for it during a second push).
However, once switching back to ssh remote url, the original error is returned.
It would appear the stored credential is not used while the one returned by git-lfs-authenticate is not authorized for the sso organization.

**Comment by technoweenie** [comment]
Hey, this is an internal issue with GitHub, and not an issue with the open source client. I'll open an issue internally, but you may want to hit up support@github.com if you want to talk privately.

**Comment by rcidt** [comment]
I am having the same issue. Did this get resolved for you @timor-raiman ?

**Comment by timor-raiman** [comment]
AFAIK, this is not fixed. @technoweenie, any updates internally - all I know is that an issue has been opened.

**Comment by ttaylorr** [comment]
+cc @bk2204 @rubyist

**Comment by rubyist** [comment]
Greetings! We've deployed a fix today that should address this problem. Because this was not a problem with the LFS client I'm going to close this issue. If you're still having issues with SAML on GitHub feel free to contact GitHub support. Thanks!
