### ISSUE TITLE
Mint Sylvia not in repo

### ISSUE THREAD

**Issue by yfronto** [git-lfs/git-lfs#2827]
After:
```bash
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
```
Running `apt get update` gives:
```
...
Ign:18 https://packagecloud.io/github/git-lfs/linuxmint sylvia InRelease       
Err:19 https://packagecloud.io/github/git-lfs/linuxmint sylvia Release         
  404  Not Found
Reading package lists... Done                                                  
E: The repository 'https://packagecloud.io/github/git-lfs/linuxmint sylvia Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Temporary workaround:**

The following is generated at `/etc/apt/sources.list.d/github_git-lfs.list`:
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/github/git-lfs

deb https://packagecloud.io/github/git-lfs/linuxmint/ sylvia main
deb-src https://packagecloud.io/github/git-lfs/linuxmint/ sylvia main
```
Just s/linuxmint/debian/ and s/sylvia/stretch/ for now.

**Comment by technoweenie** [comment]
We have to manually add these to the release script. Should we add linuxmint/sylvia for the next release here?

https://github.com/git-lfs/git-lfs/blob/e1ccef9712583f20df5a27d6f3bea96e5cdb5693/script/packagecloud.rb#L55-L64

**Comment by yfronto** [comment]
Not sure if that question was directed at me. It aligns with debian/strech and ubuntu/xenial, so that looks like the right group. I'm happy to put in the PR if you like.
