### ISSUE TITLE
Is there any way to treat a directory containing many files as a binary blob?

### ISSUE THREAD

**Issue by samskiter** [git-lfs/git-lfs#2832]
We'd like to check some pretty large libraries into our repo with many little files.These libraries change rarely so would be good candidates for LFS storage.

Is there any way for us to consider an entire directory as a single blob without having to resort to zipping/unzipping the directory (which would slow down our CI on checkout)? I.e. if any file in that directory changes, can we consider that whole blob-directory as changed?

**Comment by ttaylorr** [comment]
> Is there any way for us to consider an entire directory as a single blob without having to resort to zipping/unzipping the directory (which would slow down our CI on checkout)?

Not natively in Git. Trees are treated differently in `.gitattributes`, i.e., if you track `subdir`, it won't actually apply any filters to children of the `subdir` tree, like `subdir/foo.txt`.

Unfortunately, I think that the best thing to do today is to zip/unzip the directory and store _that_ blob as an LFS object.

**Comment by samskiter** [comment]
Could I convert this to a feature request? Would it require a change to git to be feasible?

**Comment by ttaylorr** [comment]
> Would it require a change to git to be feasible?

Yes, so I think that this issue is best raised with the Git mailing list.
