### ISSUE TITLE
bad credential leads to (almost) endless loop retrying auth / request

### ISSUE THREAD

**Issue by gst** [git-lfs/git-lfs#2833]
Hi,

happy new user of git-lfs.

```
$ git-lfs
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
```

if I try to checkout, or push, or anything requiring auth with the lfs https service, but I give a bad credential (login or password), then I see that git-lfs goes into what is a very long retry-loop:

Here is an extract, so I give on purpose invalid/bad credentials..

```
12:57 $ GIT_TRACE=1 git checkout branch_foo
12:57:17.034775 git.c:344               trace: built-in: git 'checkout' 'branch_foo'
12:57:17.036042 run-command.c:334       trace: run_command: 'git-lfs clean -- '\''foobarbaz.DAT'\'''
12:57:17.036460 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs clean -- '\''foobarbaz.DAT'\''' 'git-lfs clean -- '\''foobarbaz.DAT'\'''
12:57:17.044482 trace git-lfs: run_command: 'git' version
12:57:17.050531 trace git-lfs: run_command: 'git' config -l -f /home/gregory.starck/tmp/gst_repo1_using_lfs/.lfsconfig
12:57:17.053392 trace git-lfs: run_command: 'git' config -l
12:57:17.057129 trace git-lfs: Install hook: pre-push, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/pre-push, upgrading...
12:57:17.057770 trace git-lfs: Install hook: post-checkout, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-checkout, upgrading...
12:57:17.058285 trace git-lfs: Install hook: post-commit, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-commit, upgrading...
12:57:17.058754 trace git-lfs: Install hook: post-merge, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-merge, upgrading...
12:57:17.061808 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''data/hugo+isaac.jpg'\'''
12:57:17.062204 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''data/hugo+isaac.jpg'\''' 'git-lfs smudge -- '\''data/hugo+isaac.jpg'\'''
12:57:17.070202 trace git-lfs: run_command: 'git' version
12:57:17.075825 trace git-lfs: run_command: 'git' config -l -f /home/gregory.starck/tmp/gst_repo1_using_lfs/.lfsconfig
12:57:17.078736 trace git-lfs: run_command: 'git' config -l
12:57:17.082542 trace git-lfs: Install hook: pre-push, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/pre-push, upgrading...
12:57:17.083157 trace git-lfs: Install hook: post-checkout, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-checkout, upgrading...
12:57:17.083724 trace git-lfs: Install hook: post-commit, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-commit, upgrading...
12:57:17.084209 trace git-lfs: Install hook: post-merge, force=false, path=/home/gregory.starck/tmp/gst_repo1_using_lfs/.git/hooks/post-merge, upgrading...
Downloading data/hugo+isaac.jpg (354 KB)
12:57:17.084874 trace git-lfs: tq: running as batched queue, batch size of 100
12:57:17.084999 trace git-lfs: tq: sending batch of size 1
12:57:17.085381 trace git-lfs: api: batch 1 files
12:57:17.085442 trace git-lfs: creds: git credential fill ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
Username for 'https://bitbucket.org': xx
Password for 'https://xx@bitbucket.org': 
12:57:20.407310 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.407611 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.672444 trace git-lfs: HTTP: 401
12:57:20.672659 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.685392 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.685406 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.685436 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.728640 trace git-lfs: HTTP: 401
12:57:20.728709 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.738237 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.738264 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.738343 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.780306 trace git-lfs: HTTP: 401
12:57:20.780417 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.795229 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.795271 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.795422 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.836481 trace git-lfs: HTTP: 401
12:57:20.836589 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.851139 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.851173 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.851285 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.890871 trace git-lfs: HTTP: 401
12:57:20.891010 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.905927 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.905961 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.906068 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.947491 trace git-lfs: HTTP: 401
12:57:20.947667 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:20.962379 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:20.962424 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:20.962687 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:21.000348 trace git-lfs: HTTP: 401
12:57:21.000461 trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
12:57:21.015164 trace git-lfs: creds: git credential cache ("https", "bitbucket.org", "gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch")
12:57:21.015199 trace git-lfs: Filled credentials for https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:21.015317 trace git-lfs: HTTP: POST https://bitbucket.org/gst-algolux/gst_main_lfs_data.git/info/lfs/objects/batch
12:57:21.054776 trace git-lfs: HTTP: 401
```

and that continues like that retrying the request in a busy loop for well too long..

any idea how to prevent or mitigate that ? best would be to make it exit != 0 with the first encountered 401 error ?

or could something be bad on my config side ?

Thx for any pointer.

**Comment by ttaylorr** [comment]
Hi, this appears to be an issue with your host's implementation of the Git LFS Batch API. The issue is that `HTTP 401` has the semantic meaning in this API of "your credentials are incorrect but try again", where as `HTTP 403` has "you are absolutely unauthorized to access these objects".

Therefore, when LFS sees a 403 response, it will stop trying immediately. On the other hand, because of the above semantic meaning, when LFS encounters a 401 response, it will try and fill credentials again and reattempt the request.

Because this is the behavior of the specification, I think that this issue is best re-raised with Bitbucket.

**Comment by gst** [comment]
Thx about good info :)

I will check with Bitbucket.

**Comment by ttaylorr** [comment]
Hi @gst, this is the way that it is described in the specification: https://github.com/git-lfs/git-lfs/blob/master/docs/api/batch.md#response-errors.

**Comment by gst** [comment]
Hi @ttaylorr 

I see ; that's a bit a mess : 

>  401 : The authentication credentials are needed, but were not sent.

well, we can see that the credentials are always re-sent (maybe not the first time), but the server always reply with 401 effectively.

on the other hand for 403 it's said:

> 403 - The user has read, but not write access. Only applicable when the operation in the request is "upload."

the operation attempted here isn't upload/write to my knowledge (checkout).. I have the same problem doing a clone too. So to my understanding bitbucket is right: it can't use 403 as it isn't a write ? (and more over it can't return 403 also because bad credentials mean/imply no read access as well to my knowledge)

So in my understanding git-lfs shouldn't indefinitely retry the request while/when it has provided the credentials.. or at worst a couple of times.. (but after first attempt with credential normally it's enough)

what do you think ?

Thank you.

**Comment by ttaylorr** [comment]
> what do you think ?

My understanding is that Git LFS should not retry credential-requiring requests that are responded to with a 401 when credentials were in fact provided? I think that this is a sensible change, but would have to delay until Git LFS v3.0.0 in order to avoid breaking current implementations.

**Comment by gst** [comment]
Yes this the way I see / understand it too :)

When is 3.0 foreseen ?

**Comment by gst** [comment]
But I dont see what it could impact (more than it is actually) :)

**Comment by ttaylorr** [comment]
> When is 3.0 foreseen ?

I do not currently have plans for the LFS v3.0.0 release, but I imagine that it will take place as enough breaking changes like this occur. 😄

**Comment by gst** [comment]
Can you please reopen this then ?

**Comment by gst** [comment]
I could fix this on my side (so I succeeded to compile go code :O (don't ask me how))  and tested it and that makes what we (or all bitbucket users) need:

```
PATH=/home/gregory.starck/go/src/github.com/git-lfs/git-lfs/bin:$PATH git clone git@bitbucket.org:/algolux/crispml-data
Cloning into 'crispml-data'...
remote: Counting objects: 72, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 72 (delta 22), reused 0 (delta 0)
Receiving objects: 100% (72/72), 21.42 MiB | 9.31 MiB/s, done.
Resolving deltas: 100% (22/22), done.
Checking connectivity... done.
Downloading ARM/CC_D50_100cd_processed_ROIs.pickle (20 MB)
Username for 'https://bitbucket.org': fqds
Password for 'https://fqds@bitbucket.org': 
Error downloading object: ARM/CC_D50_100cd_processed_ROIs.pickle (c83e4e4): Smudge error: Error downloading ARM/CC_D50_100cd_processed_ROIs.pickle (c83e4e4577e8da91ecc7e5731ec994619ab1d8058135c500e2511b0bcd117465): batch response: Authentication required: Authorization error: https://bitbucket.org/algolux/crispml-data.git/info/lfs/objects/batch
Check that you have proper access to the repository
```

at least I see Authorization error immediately.

**Comment by m-ric** [comment]
+1 I'm impacted by this issue as well. Can the fix be merged?

**Comment by ttaylorr** [comment]
Hi @gst, can you post your change as a PR if that's something you'd be interested in doing?

**Comment by gst** [comment]
You understood i am quite busy ;)
I can throw the 1 line diff/patch in a branch on my clone if you wish..

**Comment by stffabi** [comment]
@ttaylorr I think this was a bug in `2.3.4` where git-lfs directly added the filled credentials to the credentials-cache.
Git-lfs used for adding the credentials to the cache the creds with `creds["path"]` filled out, but after returning from the credential helper (which asked for the passowrd) it was empty. This was because git-lfs didn't honor `credential.useHttpPath` and set the path in the creds input.
As a result the reject didn't work, because it has used the returned credentials from the helper with an empty path entry. This resulted in an endless loop as the credentials were never removed from the cache.

Version `2.4.0` contains a major rewrite of the credential cache, which now uses a consistent input to the cache. Furthermore since b1a43072543f15e30b094539ac2795c299f20e95 the path part is only used iff it has been activated by `credential.useHttpPath`.

@gst your problem should be fixed with git-lfs `2.4.0`, in your case git-lfs should again ask for the credentials if they are incorrect. Would it be possible for you to give this version a try?

**Comment by stffabi** [comment]
An endless loop could still occur with `2.4.0` if e.g. an unattended credential helper always returns the same credentials. So I would vote for aborting git-lfs operations if an authentication failed with credentials. AFAIK, git has the same behaviour.

**Comment by gst** [comment]
I will try that..

**Comment by gst** [comment]
Hi,

I confirm that with 2.4.0 I don't have the looping problem anymore and the soft correctly re-ask me to enter my credential.

great :)
thx for the complementary explanation @stffabi   it looks like it was a kind of unknown side-effect of some recent change if I understand well.. ;)

so I close.
