### ISSUE TITLE
'git lfs install': Error when locale setup is other than English.

### ISSUE THREAD

**Issue by torfl** [git-lfs/git-lfs#2837]
I've tried to install git lfs under openSUSE 42.3 and got the following output (my system language is set to German):

`$ git lfs install`
`Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)\nStoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).\n"`
`Git LFS initialized.`

The call of 'git rev-parse --git-dir --show-toplevel' fails, because I didn't run 'git lfs install' within a git repository.
When setting the environment variable _LANG=en_EN_ no error message is shown:

`$ LANG=en_EN git lfs install`
`Git LFS initialized.`

Can I ignore the above error message, because Git LFS seems to be successfully installed?

**Comment by ttaylorr** [comment]
> Can I ignore the above error message, because Git LFS seems to be successfully installed?

Yes!
