### ISSUE TITLE
LFS Git credentials not found error

### ISSUE THREAD

**Issue by steveh84** [git-lfs/git-lfs#2841]
I'm new to Git and LFS. I am using GitHub Desktop v1.0.12 with LFS v2.3.4, both installed and setup today 25/1/2018.
I have setup a new repository with LFS, but when I publish I have the error below.

Git credentials for https://github.com/steveh84/GitHubTest.git not found:
exit status 1
error: failed to push some refs to 'https://github.com/steveh84/GitHubTest.git'

I followed advice on other forum posts and ran the commands below, but neither of these worked:

del /f .git\hooks\pre-push
del .git\hooks*

A copy of the trace, from the developer tools is below. Can anyone help ?

16:23:01.397677 git.c:344               trace: built-in: git 'push' 'origin' 'master' '--set-upstream' '--progress'
16:23:01.399679 run-command.c:626       trace: run_command: 'remote-https' 'origin' 'https://github.com/steveh84/GitHubTest.git'
16:23:01.422195 git.c:576               trace: exec: 'git-remote-https' 'origin' 'https://github.com/steveh84/GitHubTest.git'
16:23:01.423196 run-command.c:626       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/steveh84/GitHubTest.git'
16:23:02.590821 run-command.c:626       trace: run_command: 'C:\Users\Steve Harris.GAMES_LAPTOP_1\AppData\Local\GitHubDesktop\app-1.0.12\resources\app\static\ask-pass-trampoline.bat' 'Username for '\''https://github.com'\'': '
16:23:02.768447 run-command.c:626       trace: run_command: 'C:\Users\Steve Harris.GAMES_LAPTOP_1\AppData\Local\GitHubDesktop\app-1.0.12\resources\app\static\ask-pass-trampoline.bat' 'Password for '\''https://steveh84@github.com'\'': '
16:23:03.853654 run-command.c:626       trace: run_command: '.git/hooks/pre-push' 'origin' 'https://github.com/steveh84/GitHubTest.git'
16:23:03.921712 git.c:576               trace: exec: 'git-lfs' 'pre-push' 'origin' 'https://github.com/steveh84/GitHubTest.git'
16:23:03.922212 run-command.c:626       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'https://github.com/steveh84/GitHubTest.git'
16:23:03.966232 trace git-lfs: run_command: 'git' version
16:23:04.068305 trace git-lfs: run_command: 'git' config -l
16:23:04.130349 trace git-lfs: tq: running as batched queue, batch size of 100
16:23:04.130349 trace git-lfs: creds: filling with GIT_ASKPASS: C:\Users\Steve Harris.GAMES_LAPTOP_1\AppData\Local\GitHubDesktop\app-1.0.12\resources\app\static\ask-pass-trampoline.bat Username for "https://github.com/steveh84/GitHubTest.git"
Git credentials for https://github.com/steveh84/GitHubTest.git not found:
exit status 1
error: failed to push some refs to 'https://github.com/steveh84/GitHubTest.git'

**Comment by shiftkey** [comment]
@steveh84 I believe this is a problem with GitHub Desktop. A similar report to this is over here: https://github.com/desktop/desktop/issues/3752.

I think I need to switch Desktop away from using batch files for the `GIT_ASKPASS` environment variable, because it's introduced a myriad of problems with paths and escaping characters correctly on Windows, which I think is also your problem.

**Comment by steveh84** [comment]
Thanks @shiftkey. I read through 3752, but could not understand if there is a solution within that post. Is there anything I can do to solve or workaround this issue? I am stuck with my project until I can get this working.
Thanks.

**Comment by shiftkey** [comment]
@steveh84 I believe it's related to your Windows account name interfering with how batch files are passed to `cmd` on Windows, but I haven't tested that specific case. I need to swap out that batch file for an executable that performs the same behaviour, and I'm not sure of any other ways to address it.

**Comment by ttaylorr** [comment]
Thanks @shiftkey for the explanation. I am going to close this here and instead defer discussion towards https://github.com/desktop/desktop/issues/3752, since this was indicated to be an issue with GitHub Desktop's interaction with Git LFS, not Git LFS itself.

If that's not the case, please don't hesitate to ping me here and I'd be more than happy to re-open the issue!
