### ISSUE TITLE
"Lock Failed" message but it does lock the file

### ISSUE THREAD

**Issue by ArtyMcLabin** [git-lfs/git-lfs#2852]
"git lfs locks" does indicate that the file is being locked after the "git lfs lock" command, even though it output the next message:

> Lock failed: GetFileAttributesEx Content/Props/targets/targetTwo_mesh.uasset: The system cannot find the path specified.

Tried no unlock, then lock again, same thing happens. "git lfs locks" outputs the file after lock, and does not output it after unlock.

**Comment by ttaylorr** [comment]
Hi @ArtyMcLabin, thanks for opening this issue, and sorry that you're having trouble. This sounds like a bug to me. Can you post the output of the `git lfs lock` command with `GIT_TRACE=1` in your environment here? Thanks!

**Comment by ArtyMcLabin** [comment]
Thanks for getting in touch @ttaylorr 
I can't seem to replicate the behaviour. It does work smoothly now.

I will post here if/when i find a similar case, together with GIT_TRACE=1 output.

**Comment by ttaylorr** [comment]
Thanks for getting back to me, @ArtyMcLabin! I'm glad that everything is working well now. Please let me know here if the issue persists in the future, and I'll be happy to reopen this issue.

**Comment by fabiovas** [comment]
A question. When you got the error were you using a VM? was your windows running in a VM?

**Comment by ArtyMcLabin** [comment]
@fabiovas
No VM were used.  The OS was Windows 10 x64
However i used Git-Bash, which probably might have some level of linux path-handling replacing NTFS defaults.

**Comment by yellowtailfan** [comment]
I saw this error using git-lfs/2.1.1 when locking files directly from a sub-folder of my working copy of the repo on Windows. The error did not occur when I ran `git lfs lock` from the top-level folder of the repo.

I have since updated to git-lfs/2.3.4, and the error has gone away even in sub-folders.

**Comment by fabiovas** [comment]
@yellowtailfan 
I am facing this problem on sub-folder and repo root folder and my version is git-lfs/2.3.4

**Comment by ttaylorr** [comment]
Hi @fabiovas, thanks for commenting here. Since it looks like at first blush these are different issues, can you open a new issue and we can debug there? Thanks!
