### ISSUE TITLE
Pushed my code to my repository, but cannot see it

### ISSUE THREAD

**Issue by Lenka72** [git-lfs/git-lfs#2854]
I pushed my code to the repository using the GitHub Desktop and everything shows as having worked, but all I see in the repository under the Code <> tab is the "Quick setup" instructions.  
Why can't I see my code in the repository if the desktop version shows that it's been commuted?

**Comment by shiftkey** [comment]
@Lenka72 thanks for the report!

Could you share a screenshot of the repository in Desktop? It's not clear to me what steps you've performed to publish the repository in Desktop, but we should be able to figure it out.

Also, could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by angkanasoisom** [comment]
#2854

**Comment by ttaylorr** [comment]
Thanks for jumping in, @shiftkey! Moving further discussion on this issue there.

**Comment by Lenka72** [comment]
Thanks everyone.

**Comment by kisfal** [comment]
Could you link the solution of this issue?
