### ISSUE TITLE
Use git-lfs but still cannot push to github. 

### ISSUE THREAD

**Issue by johnny94** [git-lfs/git-lfs#2855]
Hello, I have a repository holding on Github Enterprise which has some branches and tags, and I want to push the repository to Github. But there are some large files (exceed 100MB) I need to convert to git-lfs before pushing it to Github. But after processing the repository with git-lfs I still got errors saying that there are some files exceed 100MB. Here is the comment that I used for processing the repository:

```shell
$ git clone --bare MY_REPOSITORY
$ cd MY_REPOSITORY.git
$ git lfs migrate info --above="50 MB" --everything
$ git lfs migrate import --include="*.sql,*.jar,*.psd" --everything
$ git remote add github NEW_REPOSITORY
$ git push github --mirror
```
Did I miss something so the git-lfs cannot work as expected?
I also used the build provided in #2679, but it cannot work, either.

**Comment by ttaylorr** [comment]
Hi @johnny94, thanks for opening this issue and I'm sorry that you're having trouble. I think that the issue going on here has either to do with the `--bare` clone or the `--mirror`'ed push.

Can you try different combinations mirrored/un-mirrored bare/non-bare and see which ones work and which ones don't?

**Comment by ttaylorr** [comment]
Hi @johnny94, I'm going to close this issue for now since I haven't heard back in a little while. If this is still an issue, please let me know and I'd be more than happy to re-open!
