### ISSUE TITLE
What's the replacement for "git lfs clone -I ..." ?

### ISSUE THREAD

**Issue by ceejatec** [git-lfs/git-lfs#2864]
"git lfs clone" is now deprecated, but regular "git clone" doesn't seem to have anything like the include/exclude filter functionality of "git lfs clone -I / -X". Do we need to resort to various command-line -c options to get that behaviour now? What's the approved way to do this?

**Comment by ttaylorr** [comment]
> Do we need to resort to various command-line -c options to get that behaviour now? What's the approved way to do this?

Yes, this is the preferred way to interact with Git LFS's include/exclude filters on clone.

You can also include a `.lfsconfig` file in the root of your repository and Git LFS will respect the configuration options in there (including `lfs.fetchinclude` and `lfs.fetchexclude`).
