### ISSUE TITLE
smudge filter lfs failed Help!

### ISSUE THREAD

**Issue by TheLandOfKings** [git-lfs/git-lfs#2868]
Soo i am trying to pull this from the server and i keep getting this error:
Downloading Content/AI/testingmap.umap (1.2 MB)
Error downloading object: Content/AI/testingmap.umap (50a46ec): Smudge error: Error downloading Content/AI/testingmap.umap (50a46ec7af1e02f4d3945116c838a8ab176a1676e1884eb4f2a7f6160d0cb685): [50a46ec7af1e02f4d3945116c838a8ab176a1676e1884eb4f2a7f6160d0cb685] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to C:\Users\Mujy\Documents\Unreal Projects\OurMedievalProject\.git\lfs\objects\logs\20180215T072637.8734088.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/AI/testingmap.umap: smudge filter lfs failed

**Comment by ttaylorr** [comment]
Hi @TheLandOfKings, thanks for opening this issue and sorry that you're having trouble! It looks like the object that you are trying to download doesn't exist on the server. Can you make sure that it is pushed to the server and try checking out again?

If that wasn't it, let me know and I'd be more than happy to reopen the issue.
