### ISSUE TITLE
Not all history entries getting migrated

### ISSUE THREAD

**Issue by tarioch** [git-lfs/git-lfs#2882]
I'm trying to migrate a bigger repository and it seems some files are not getting picked up.

The way I'm testing is:

- run script from https://stackoverflow.com/a/42544963 to see which big files are still in the repo and put them into before.txt
- `git lfs migrate import --everything --include='*.doc,*.docx,*.xls,*.xlsx,*.dll,*.exe,*.jar,*.zip,*.pdf,*.rtf,*.ppt,*.pptx,*.PDF,*.bin,*.dmp,*.DMP,*.gz,*.tar,*.rar,*.7z,*.qft,*.jsa,*.xlsm,*.xpdl'`
- `git reflog --expire=now --all; git gc --prune=now --aggressive`
- run script from https://stackoverflow.com/a/42544963 to see which big files are still in the repo and put them into after.txt
- diff before.txt and after.txt

Now I see some strange things:
- some files are not picked up at all (e.g. caffeine/lib_src/poi-src-3.5-FINAL-20090928.zip)
- for some files some of them are picked up but others (with the exact same path) are not picked up

I'm using
git 2.14.1 
git lfs 2.3.4 
linux centos
bare repository without remotes

I tried
- release 2.3.4
- binaries from #2679
- binaries build from wildmatch branch for #2875 

Any ideas how to further debug this?

**Comment by tarioch** [comment]
Closing, stupid mistake on my end. 
Git repo was created by SVN to GIT migration using subgit, this one creates additional refs. Purging the svn migration data fixed it.

**Comment by tarioch** [comment]
The patterns are like *.zip

**Comment by mloskot** [comment]
> Git repo was created by SVN to GIT migration using subgit, this one creates additional refs.

I'm trying out similar migration with SubGit (some other aspects of my story in #3374), then I follow 
the [Migrating existing repository data to LFS](https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs) tutorial and I'm being hit by the same issue: a particular file is not migrated to Git LFS.

In short, here is what I do in short, after SubGit completes translating SVN repo to Git:

1. Pre-LFS inspection: `git lfs migrate info --everything`

2. Migrate to LFS

    ```
    git lfs migrate import --everything --verbose \
        --include="*.7z,*.bz2,*.exe,*.dll,*.gz,*.lib,*.pdb,*.zip" > lfs.log 2>&1
    ```

3. Post-LFS migration clean up

    ```
    git reflog expire --expire-unreachable=now --all
    git gc --prune=now --aggressive
    ```

After the migration, `git sizer`, which reports Git-only objects excl. Git LFS objects,still reports one `472 MB `large file:

```
$ git sizer
Processing blobs: 1138450
Processing trees: 256136
Processing commits: 68372
Matching commits to trees: 68372
Processing annotated tags: 0
Processing references: 71
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Blobs                      |           |                                |
|   * Total size               |  18.1 GiB | *                              |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [1] |  1.96 k   | *                              |
| * Blobs                      |           |                                |
|   * Maximum size         [2] |   472 MiB | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Number of directories  [3] |  13.3 k   | ******                         |
| * Maximum path depth     [4] |    18     | *                              |
| * Maximum path length    [5] |   232 B   | **                             |
| * Number of files        [6] |   910 k   | ******************             |
| * Total size of files    [7] |  4.09 GiB | ****                           |

[1]  d0998a1d64d7c31bfbc2839c4842d5edbb233067 (refs/heads/9.0:Metadata/External/Symbols/hdpi)
[2]  5ac4551a9bf46b0d3e7b030042ddb6d463b444f9 (879dc12fd1b243fc7e66080923f7cd0ae1b0b649:ThirdParty/Direct/lib/vc9/direct.lib)
[3]  4d483d5e818f8a19998268372d0d3d31e7e67841 (7854c7dec44f03869d3ab70f6304ddc57f58fbe3^{tree})
[4]  d363fbdec3b105160afb4bfa1b2235c447d2dba6 (refs/heads/9.0^{tree})
[5]  c98d3aa2c7cffec197e1fbec7b1a4231f06fb309 (75729963c65e8c351f3ecf7f687be982680a367f^{tree})
[6]  7d64daeed7d74a3be42e40a9f8dba35749a0ea7a (53adc11fe7bd4fb3a74a68f798965ebf8cd37483^{tree})
[7]  153d70fbd93e6710ab8348873b623480d85db895 (4066194d75bab29928f953dccdff68630ccffb21^{tree})
```

`git lfs ls-files` confirms this 472 MB big `direct.lib` is not tracked by Git LFS.

> Purging the svn migration data fixed it.

@tarioch What are the svn migration data and how did you clean those up?

-----

@ttaylorr Could you help me to understand why the `direct.lib` file is not migrated to Git LFS?

In the verbose output of `git lfs migrate import` I an see one entry for this file

```
migrate: commit ca0b0a1f6669b397be5ee40bde94c61de4e8a889: ThirdParty/Direct/lib/vc9/direct.lib
```

but I guess there is more commits which have not been migrated for some reason.

I went Lucky Luke mode shooting blindly and tried to run the clean-up also before `git lfs migrate import`

```
git reflog expire --expire-unreachable=now --all
git gc --prune=now --aggressive
```

No difference. The stubborn `direct.lib` is still in Git.

**Comment by tarioch** [comment]
> Did you just run the subgit uninstall --purge REPO_DIR before migrating to Git LFS?
That was exactly the missing step, adding this one fixed things for us.

As far as I remember the data that was around is basically the information about the original svn commit, as this is not "normal" git data it does not get migrated to lfs. Purging this leaves only the "real" git data and that one gets properly migrated to lfs.

**Comment by mloskot** [comment]
@tarioch I'm happy to confirm the `subgit uninstall --purge` was the missing step for me too :)

Thank you for this story here, it helped a lot!

**Comment by mloskot** [comment]
For archive and the story completeness, I'd like to add small but important step for SubGit users who also wish to split large repos using `git filter-branch`. I think it may be helpful.

First, `subgit uninstall --purge REPO_DIR`.
Then, some leftovers clean-up:

```
rm -rf REPO_DIR/refs/svn
rm -rf REPO_DIR/subgit
```

Next, extraction of a directory as a repository (i.e. removal of all history but related to the directory)

```
git filter-branch --prune-empty --subdirectory-filter PATH_TO_EXTRACT -- --all
```

Finally, it is crucial to wipe out the backed up original refs (credit to https://github.com/git-lfs/git-lfs/issues/326#issuecomment-104881826):

```
rm -rf refs/original
```

Now, the (extracted) repo is ready for migration to LFS. Otherwise, the `original`-s may contain entries that will not be migrated and `git sizer` will keep reporting unwanted large Git objects.
