### ISSUE TITLE
LFS Error downloading object, Smudge error

### ISSUE THREAD

**Issue by Peter006** [git-lfs/git-lfs#2885]
git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)
git version 2.16.2.windows.1

$ git-lfs.exe filter-process
Error downloading object: Assets/xxx/Lightmap-0_comp_light.exr (2aa4ca0): Smudge error: Error downloading Assets/xxx/Lightmap-0_comp_light.exr (2aa4ca0c877af845ad69b98856e25b4538247140824e8d63462867c30d2c8cf4): [Lightmap-0_comp_light.exr] LFS: tq: action "download" expires at 26 Feb 18 19:13 PST

[Lightmap-0_comp_light.exr] LFS: tq: action "download" expires at 26 Feb 18 19:13 PST
github.com/git-lfs/git-lfs/errors.Errorf
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:69
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:490
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:348
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197
Error downloading Assets/xx/Lightmap-0_comp_light.exr (2aa4ca0c877af845ad69b98856e25b4538247140824e8d63462867c30d2c8cf4)
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrapf
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.downloadFile
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:96
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:61
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:116
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:256
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:116
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:185
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197

Current time in UTC: 
2018-02-27 19:03:32

ENV:
LocalWorkingDir=C:\Users\1002\Desktop\Git\xx
LocalGitDir=C:\Users\1002\Desktop\Git\xx\.git
LocalGitStorageDir=C:\Users\1002\Desktop\Git\xx\.git
LocalMediaDir=C:\Users\1002\Desktop\Git\xx\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\1002\Desktop\Git\xx\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\1002\Desktop\Git\xx\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_LFS_PATH=C:\Program Files\Git LFS

Client IP addresses:
fe80::4d0b:609b:ff83:b9a6 10.68.12.83

**Comment by larsxschneider** [comment]
👋 @Peter006 ! Did you clone the repo via SSH protocol? Are you using BitBucket Server as Git LFS backend? If yes, then maybe you are running in the problem that #2867 tries to solve?

---
@ttaylorr Can/Should we record the cloning protocol (SSH/HTTPS/plain Git) in `ENV`?

**Comment by Peter006** [comment]
Thanks for your reply. I am using GitBucket as GIT LFS backend. Actually, I just reinstall my OS to solve this issue....

**Comment by ttaylorr** [comment]
> @ttaylorr Can/Should we record the cloning protocol (SSH/HTTPS/plain Git) in `ENV`?

Yes, I think that this is a good idea. Is this a topic that you would be interesting in working on?

**Comment by alexwebr** [comment]
Just FYI, we encounter this problem as well with Bitbucket Server. We'd love to see something like this implemented.

**Comment by ttaylorr** [comment]
Hi @alexwebr, could you please open a new issue describing your problem? I never figured out the root cause of this issue (as it was resolved in https://github.com/git-lfs/git-lfs/issues/2885#issuecomment-369256981), so I'm not sure if you're experiencing something similar or different.

Was the issue resolved by cloning via HTTPS instead of SSH? If so, then please do not feel obligated to open a new issue.

**Comment by alexwebr** [comment]
Hi @ttaylorr; I made a mistake. I saw @larsxschneider's comment about Bitbucket Server and #2867, and wanted to :+1: that particular issue. Sorry!
