### ISSUE TITLE
Smudge error: invalid cross-device link

### ISSUE THREAD

**Issue by nathasm** [git-lfs/git-lfs#2891]
I read that issue #2381 has been fixed, however, I'm still experiencing this issue. I am using rsync for my custom transfer agent but I don't believe that should affect anything since the files are getting to my box. Setting the TMPDIR like in the other ticket does work for me though.

git-lfs/2.3.4 (GitHub; linux amd64; go 1.9.1; git d2f6752f)
git version 2.7.4

Relevant snippets from my .git/config
```
[lfs]
  standalonetransferagent = "rsync"
  locksverify = false
  concurrenttransfers = 8
[lfs "customtransfer.rsync"]
  path = "git-lfs-rsync-agent"
  concurrent = true
  args = "telx-git-lfs:/mnt/lfs"
```

My home and tmp drives are just ext4
```
/dev/mapper/vg-home on /home type ext4 (rw,relatime,discard,stripe=64,data=ordered)
/dev/mapper/vg-tmp on /tmp type ext4 (rw,relatime,discard,stripe=64,data=ordered)
```

And finally the error I'm seeing:

Error downloading object: fat.gz (39c76a4): Smudge error: Error downloading fat.gz (39c76a4facc017dad66a0908a2ded50b17fa4c53784402b907d8ed194c56e8df): Failed to copy downloaded file: cannot replace "/home/nsmith/projects/testing/.git/lfs/objects/39/c7/39c76a4facc017dad66a0908a2ded50b17fa4c53784402b907d8ed194c56e8df" with "/tmp/rsync-agent389156207": rename /tmp/rsync-agent389156207 /home/nsmith/projects/testing/.git/lfs/objects/39/c7/39c76a4facc017dad66a0908a2ded50b17fa4c53784402b907d8ed194c56e8df: invalid cross-device link

**Comment by nathasm** [comment]
Actually, as I see the commit that fixes this, I am guessing that the problem is with the rsync transfer agent still using ioutil.TempFile.

I'm still investigating the best way to fix the transfer agent code. Any suggestions as this is the first time I'm digging into the code.

**Comment by ttaylorr** [comment]
> I'm still investigating the best way to fix the transfer agent code. Any suggestions as this is the first time I'm digging into the code.

@nathasm happy to help! I think that a good function to use would be `ioutil.TempFile` as you suggested, but you can pass `*config.Configuration.TempDir()` as the directory in which to create a temporary file (this will be equal to `.git/lfs/tmp`).

cc: @aleb
