### ISSUE TITLE
Issue cloning repo using git LFS

### ISSUE THREAD

**Issue by JJonesSoundArtist** [git-lfs/git-lfs#2892]
Hey guys, thought I'd post a message here about my issue if anyone's experienced a similar problem before. 

I have a big repository to clone onto my Macintosh machine that seems to not be pulling all the big files down correctly and if I use Github, sourcetree, or even the Terminal application I seem to be getting errors no matter what I try. 

Right now I have a repo cloned that is 'half' working, as in I can get into my project, but a lot of the major large files appear to be missing still. 

I'm not sure what else I can try, but if anyone has any suggestions I'd be open to trying anything - keep in mind I'm definitely very new to all this command-line stuff, so if there is a good solution please try to walk me through it as simply as possible. 

Ideally it would be nice to not have to try to clone all over again from the start as I've already done that a couple times, is there any way to reinitialize the git lfs checkout to run properly somehow? 

Thanks for reading!

**Comment by ttaylorr** [comment]
Hi, @JJonesSoundArtist, thanks for opening this issue, and sorry that you're having trouble! Could you post what error message you're seeing specifically? If you're able to share that information here, I should have a much easier time tracking down the underlying issue.

In the meantime, you can indeed restart a partially finished checkout by running `git lfs fetch && git lfs checkout` in the root of your repository -- this will checkout all of the LFS objects, downloading them if they are missing.

**Comment by JJonesSoundArtist** [comment]
Hi Taylor,

I really appreciate your helpful response! I would like to keep this
information confidential if possible, but I attempted to try your
suggestions using the command lines in Terminal, but to no avail. Git
recommended running a 'git lfs log' command though, which seems to contain
the error I believe. I can't make sense of it though, if you can help me
further that'd be awesome, I can include the error log here in a text file
for you. Thanks again, it is greatly appreciated!




This is the end of this message.

--

**Comment by ttaylorr** [comment]
@JJonesSoundArtist and I discussed and resolved this issue over email.
