### ISSUE TITLE
Flag to not install in current repository

### ISSUE THREAD

**Issue by cancan101** [git-lfs/git-lfs#2893]
The help text for `git lfs install` says:
```
* Install a pre-push hook to run git lfs pre-push for the current repository,
  if run from inside one.
```
But there does not seem to be a flag to prevent this action from happening.

Right now I have to cd out of my current directory to prevent the install from happening. I have to do this because the cwd contains a git repos that is on a read only filesystem.

**Comment by ttaylorr** [comment]
Is `--skip-repo` the flag that you're looking for?
