### ISSUE TITLE
some files are not detected by git lfs migrate info

### ISSUE THREAD

**Issue by johnny94** [git-lfs/git-lfs#2896]
I am using git lfs to check which files are causing the push failure. But it seems that some files are not detected. Here is the command that I used:
```
$ git clone --bare REPOSITORY
$ cd my REPOSITORY.git
$ git lfs migrate info --everything
```
It really detected some files which need to be migrate to git lfs, but failed to detect some files. I don't know is the information helpful or not but the filename that cannot be detected is something like `aa_bb_1000.FBX`.

**Comment by ttaylorr** [comment]
Hi @johnny94, thanks for opening this issue and I'm sorry that you're having trouble! Regarding your point here:

> but failed to detect some files

could you be more specific about the `aa_bb_1000.FBX` file? Is it in a reachable reference, and is the file large enough to warrant migrating? You can make sure that _all_ files are shown by running `--above=0b`. The `--above` flag doesn't categorize files that are strictly less than the given amount, and the default value for this flag in the latest release is 0b, but it was previously higher in past releases. If you're running one of those releases, that might be a reason that the file isn't showing up in your list.

Could you give that a whirl and ping me here if it doesn't work? If that's the case, I'd be more than happy to reopen this issue and dive in further
