### ISSUE TITLE
Cannot install git-lfs, ''lfs' appears to be a git command, but we were not able to execute it'

### ISSUE THREAD

**Issue by Shoopalapa** [git-lfs/git-lfs#2898]
Hello! This is my first time posting an issue so please let me know if I've covered everything.

I've previously installed git-lfs with no issue at all. At some point I received an error message stating that I did not have git-lfs set up while trying to push to Git. I tried reinstalling and now I receive this error when I try:
`fatal: 'lfs' appears to be a git command, but we were not
able to execute it. Maybe git-lfs is broken?`
All I've done so far is download git-lfs-windows.2.3.4.exe, which seemed to have worked with no errors. However I get the same error if I try running 'git lfs install' in my terminal.

Here are my specs:
Computer: Windows Surface Pro 4
OS: Windows 10 Pro 64-bit
Terminal: Bash Ubuntu for Windows
Git version 1.9.1

**Comment by ttaylorr** [comment]
Hi @Shoopalapa, thanks for opening this issue and sorry that you're having trouble! Can you make sure that `git-lfs.exe` is an executable application and that your user has permissions to execute it?

In addition (and this is most likely unrelated) your version of Git is quite old. Perhaps you could try upgrading to 2.16.0?

**Comment by Shoopalapa** [comment]
Ok! I updated Git to version 2.16.2, and checked the permissions for `git-lfs.exe` which turned out to be 555. I was able to execute it and received this as a response:
`git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)`
`git lfs <command> [<args>]...`
I won't print the rest but it just goes through all the possible commands. After updating Git I still received the same error message.


However there's an interesting development... I decided to run `git lfs install` inside my newly updated Git Bash and it worked! I think I'll just be using that from now on for my git needs (instead of Ubuntu for Windows), though I'd love to figure out the source of this issue! Anything else I can try?

**Comment by ttaylorr** [comment]
Hm, I'm not sure -- @larsxschneider @dscho, do either of you know?

**Comment by larsxschneider** [comment]
The "Ubuntu for Windows" shell is a *real* Linux shell. That means it can *only* run Linux executables. I think a Windows executable would produce an error similar to the one you have seen. The "Git Bash" is a Windows shell and can only run Windows executables. You've downloaded the Windows version of Git LFS and therefore that works great in "Git Bash". Does this make sense?

I am no Windows expert. @dscho please jump in if I got something wrong.

**Comment by ttaylorr** [comment]
@larsxschneider thanks for jumping in here; I totally looked past this. @Shoopalapa, can you make sure that you have a Linux build (matching your architecture, which appears to be `amd64`) and try again? 

If that doesn't do the trick, please don't hesitate to comment here and I'll be more than happy to re-open this issue.

**Comment by jdrews** [comment]
I know this is an old thread but this error comes up when searching. All you have to do in your WSL Ubuntu instance is the following to get past the error above.
https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu

> curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install

**Comment by Nichollas96** [comment]
Worked for me @jdrews, thank you very much!

**Comment by Zeratoxx** [comment]
> curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

I didn't need the curl command. Following commands did it for me:
```
sudo apt install git-lfs
git lfs install
```

**Comment by Clev7** [comment]
> I know this is an old thread but this error comes up when searching. All you have to do in your WSL Ubuntu instance is the following to get past the error above. https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu
> 
> > curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
> > sudo apt-get install git-lfs
> > git lfs install

Thank you @jdrews!
