### ISSUE TITLE
`git-lfs` 2.4.0 APT package (from https://packagecloud.io/github/git-lfs/ubuntu) alters the ownership of `~/.gitconfig` to `root:root`

### ISSUE THREAD

**Issue by BanzaiMan** [git-lfs/git-lfs#2903]
As reported in https://github.com/travis-ci/travis-ci/issues/9309.

Before update (with version 2.3.4): https://travis-ci.org/BanzaiMan/travis_production_test/jobs/350824499#L466

After update (with version 2.4.0): https://travis-ci.org/BanzaiMan/travis_production_test/jobs/350827662#L490

**Comment by ttaylorr** [comment]
Hi @BanzaiMan, thanks for opening this issue. I tried this myself on an Ubuntu Trusty image running in Docker, and was unable to reproduce the issue: 

```
ttaylorr@87959cf5db7a:/$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

ttaylorr@87959cf5db7a:/$ whoami
ttaylorr

ttaylorr@87959cf5db7a:/$ git lfs install
Git LFS initialized.

ttaylorr@87959cf5db7a:/$ ls -la ~ttaylorr
total 28
drwxr-xr-x 2 ttaylorr ttaylorr 4096 Mar  8 16:34 .
drwxr-xr-x 1 root     root     4096 Mar  8 16:31 ..
-rw------- 1 ttaylorr ttaylorr   30 Mar  8 16:33 .bash_history
-rw-r--r-- 1 ttaylorr ttaylorr  220 Mar  8 16:31 .bash_logout
-rw-r--r-- 1 ttaylorr ttaylorr 3637 Mar  8 16:31 .bashrc
-rw-rw-r-- 1 ttaylorr ttaylorr  126 Mar  8 16:34 .gitconfig
-rw-r--r-- 1 ttaylorr ttaylorr  675 Mar  8 16:31 .profile
```

Is there anything else that I should try above in order to reproduce the issue?

**Comment by BanzaiMan** [comment]
To think, it seems far-fetched to think that the package is misbehaving. I feel that there is no reason for the APT package to reach in to a user's home directory (one that it does not know anything about).

In fact, I am seeing something else upon further investigation.

I apologize for the noise.
