### ISSUE TITLE
Problem with Github Cloning Repo 

### ISSUE THREAD

**Issue by JJonesSoundArtist** [git-lfs/git-lfs#2905]
The problem I'm experiencing appears to be that I am downloading a very large project file from the repository, and Github is losing its way somewhere with it. My team members recommended to me that I do the entire clone via Github Desktop itself, but in doing so it's presenting an issue.

I'm not sure if the solution is simply to re-instantiate the download/clone again, but it's imperative that I'm able to pull down all the files essentially. 

I grabbed a screencap of the error I was given in Github, please let me know if anyone can think of any solutions for this.

Thank you in advance! 

https://www.dropbox.com/s/x5y8c9rpd2by7b3/Screenshot%202018-03-08%2012.15.09.png?dl=0

**Comment by ttaylorr** [comment]
Hi @JJonesSoundArtist, thanks for opening this. Since it's closed, I am going to assume that the issue is resolved. Please let me know if this is not the case, and if so, I'd be more than happy to take a look with you.
