### ISSUE TITLE
Update CircleCI to V2

### ISSUE THREAD

**Issue by tylerauerbeck** [git-lfs/git-lfs#2907]
CircleCI is deprecating V1 syntax: https://circleci.com/blog/sunsetting-1-0/

git-lfs should update to V2 syntax to avoid running into issue at the deprecation date.

**Comment by ttaylorr** [comment]
Hi @tylerauerbeck, thanks for letting me know! I went ahead and updated the configuration in https://github.com/git-lfs/git-lfs/pull/2928.
