### ISSUE TITLE
Migrate Import doesn't handle spaces in paths properly

### ISSUE THREAD

**Issue by mrackwitz** [git-lfs/git-lfs#2908]
I passed in some quoted paths via `--include`, e.g. `"External/AWS iOS SDK/AWSRuntime.framework/Versions/A/AWSRuntime"`.
This resulted them being written to the `.gitattributes` as:

```
External/AWS iOS SDK/AWSRuntime.framework/Versions/A/AWSRuntime filter=lfs diff=lfs merge=lfs -text
```

Which resulted in the following errors when checking out files:

```
SDK/AWSRuntime.framework/Versions/A/AWSRuntime is not a valid attribute name: .gitattributes:24
```

From issues in this repo, it seems like spaces should be represented as `[[:space:]]` in the `.gitattributes` file. `git lfs migrate import` should take this into account.

**Comment by ttaylorr** [comment]
Hi @mrackwitz! Thanks for pointing this out; interestingly enough, `git-lfs-track(1)` and `git-lfs-untrack(1)` both support this kind of conversion, but `git-lfs-migrate-import(1)` does not. I have opened up https://github.com/git-lfs/git-lfs/pull/2933 to fix this, and have queued it for the next release.

**Comment by mrackwitz** [comment]
Thanks so much for looking into this!
