### ISSUE TITLE
Github generated tarballs change randomly

### ISSUE THREAD

**Issue by bket** [git-lfs/git-lfs#2911]
As the title states, github generated tarballs can change at any point. This creates issues for packaging on systems like [OpenBSD](https://marc.info/?l=openbsd-ports&m=151973450514279&w=2) ports. Would it be possible to get official tarballs created / attached to releases?

**Comment by ttaylorr** [comment]
Hi @bket, thanks for opening this issue. I think that this is a great idea. I've started a branch in `generate-tarballs` (see: https://github.com/git-lfs/git-lfs/compare/generate-tarballs) which adds `--tarball` to `script/build`. It's not done yet, but I will plan to finish this before the next MINOR release and include tarballs in the release page.

**Comment by bk2204** [comment]
I definitely think this would be good to get into v2.6.0.

In the mean time, I believe that the uncompressed tarballs are relatively stable, so @bket, if it's possible to do with your infrastructure, you may want to uncompress the tarball before verifying the hash or signature on it.
