### ISSUE TITLE
Locked file but no write-access

### ISSUE THREAD

**Issue by ArtyMcLabin** [git-lfs/git-lfs#2913]
Once in a while LFS-locked files have no write access, even though they are locked for me.
running "lfs unlock filename" and then "lfs lock filename" again - fixes that.

I am not sure what is causing that behaviour but i get it once in a while so i might come up with more clues and post them here. If you want to make some checks on the bugged files, tell me here and i will run these tests the next time i encounter this :]

Thank you.

**Comment by simba55112** [comment]
Visa card numbers https://www.facebook.com/xplenty/photos/a.414479965278663.95741.393996610660332/1256997864360198/?type=3

**Comment by simba55112** [comment]
Idk what the fuck where you at

**Comment by ttaylorr** [comment]
Hi @ArtyMcLabin, thanks for opening this issue, and I'm sorry that you're having trouble! Without more information, I'm not intuitively sure what might be causing this. That said, if you can come up with a reproducible failure scenario, then please let me know here.

**Comment by ArtyMcLabin** [comment]
@ttaylorr hey and thanks for replying :]
i'm not sure if i will find such a scenario, it seems to happen randomly in my project (obviously nothing is random in programs, but that's the impression.)

Can you think of any tests i should take when i encounter such a behaviour next time?

I doubt i will be able to hold for days and ask that in the next time because i do need these files pretty urgently and can't afford a bottleneck, so i ask beforehead.

**Comment by ttaylorr** [comment]
> Can you think of any tests i should take when i encounter such a behaviour next time?

Without any guiding information, I'm not quite sure where to start. I think that it is safe to close this issue for now, and we can revisit this in the future if the issue crops up again.

**Comment by ArtyMcLabin** [comment]
Okay i have some additional info and clues.

I have been able to reproduce that. This happens when used with UE4 (Unreal Engine 4) with Visual Studio 2015 as a compiler environment for C++.

I am using this plugin to use Git LFS inside UE4: https://github.com/SRombauts/UE4GitPlugin

The behaviour occurs when you hit "compile" in UE4 (which triggers it's own preprocessor and then Visual Studio's MSVC C++ compiler), but then you cancel the compilation before it succeeds or fails. You end up with a read-only file although it's LFS-locked. 

UE4 crashes a lot when building on C++, and most probably it doesn't automatically retrieve write access to the files on crash.

Obviously it's not LFS's fault, but you might use that information to improve the "git lfs lock" command, to check that the file indeed has write access, and only then output "Lock failed: There is an existing lock on this path."
And else at least print a warning with a suggestion to check with other software that might use that file, and use something like "git lfs lock --force" to force write access to already locked files.

**Comment by ttaylorr** [comment]
> Obviously it's not LFS's fault, but you might use that information to improve the "git lfs lock" command, to check that the file indeed has write access, and only then output "Lock failed: There is an existing lock on this path."

Sounds good, and thanks for confirming the issue. I'll follow along in https://github.com/SRombauts/UE4GitPlugin/issues/70 to see if there's anything that I can assist with. 

I like your idea of adding a message to `git lfs lock`'s output. Is this something that you would be interested in working on?

> And else at least print a warning with a suggestion to check with other software that might use that file, and use something like "git lfs lock --force" to force write access to already locked files.

I am inclined not to teach `--force` to `git-lfs-lock(1)`, for a couple of reasons:

1. The LFS API specification does not include a `force` field in the request used to acquire a lock, only the one used to remove the lock. If a user wishes to acquire a pre-existing lock, one way they could do so is:

```
$ git lfs unlock --force /path/to/file
$ git lfs lock /path/to/file
```

This has its drawbacks (namely, it is non-atomic, so the user can _still_ fail to acquire the lock in the second command if someone else grabs it first), so perhaps we should investigate this further as a part of a longer-term change to the LFS API specification in order to support this.

**Comment by ArtyMcLabin** [comment]
Great, thanks :]

Got you about --force. i have forgot this functionality. We could use some flag with another name for that functionality though. 

> I like your idea of adding a message to git lfs lock's output. Is this something that you would be interested in working on?

I might come up to this some time from now and look at the code. Very likely i could do that, just need to find some rare time. I wouldn't like to promise though unfortunately, full-time on unpaid indie :P
