### ISSUE TITLE
Add retry option if SSH auth fails

### ISSUE THREAD

**Issue by stanhu** [git-lfs/git-lfs#2914]
Does it make sense to add retry logic in case the SSH auth fails here? https://github.com/git-lfs/git-lfs/blob/5d18f87f009b1f96d484d216868858083cdd0a13/tq/api.go#L60-L63 I see that there is retry logic here: https://github.com/git-lfs/git-lfs/blob/5d18f87f009b1f96d484d216868858083cdd0a13/tq/api.go#L68 We've seen cases where intermittent SSH failures cause the whole repo download to stop. It'd be nice to be able to specify a retry count.

**Comment by ttaylorr** [comment]
Hi @stanhu, thanks for opening this issue. Those are great places to start looking, though I have a few suggestions. Firstly (for posterity) those two calls are serving different purposes. The first constructs a new `*net/http.Request` and the later call executes it. The later retries the request should it fail, but the first one does not, assuming that any failure is fatal and cannot be recovered from.

I think that this is somewhat true. For example, if you look at the body of `tq/Client.NewRequest()`, note that a failure to convert the body of the request to JSON encoded bytes is treated as an unrecoverable failure. I think that this treatment is correct. However, failing to resolve the SSH endpoint should be a retry-able failure.

What do you think of encoding that retry logic in this call?

https://github.com/git-lfs/git-lfs/blob/v2.4.0/lfsapi/client.go#L31-L41

**Comment by stanhu** [comment]
@ttaylorr Right, that is what I was thinking.

**Comment by ttaylorr** [comment]
@stanhu great, and thanks for the clarification! I think that is a sensible approach and would be happy to guide you or anyone through a patch to the above effect. Is this something that you would be interested in working on?

**Comment by stanhu** [comment]
@ttaylorr #2934 is a first pass at this. No tests yet. How should the max retries variable be set?
