### ISSUE TITLE
git-lfs/2.4.0 no longer detects SSH endpoint

### ISSUE THREAD

**Issue by vermaport** [git-lfs/git-lfs#2915]
I've been using git-lfs/2.3.4 with repositories hosted on bitbucket.org. It's been working fine for a couple of months.

```bash
$ git-lfs env
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
git version 2.16.2

Endpoint=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
  SSH=git@bitbucket.org:tignis/tap.git
Endpoint (upstream)=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
LocalWorkingDir=/home/tignis/workspace/tignis_tap_PR-67-WXNB333I6RCCJG4OETW4JQLBGUH6P6HO4KSP4D6XUETE2YXM47LA
...
```

When I upgraded to git-lfs/2.4.0, it started failing to detect bitbucket.org's SSH endpoint.

```bash
$ sudo apt-get install git-lfs=2.4.0
...
Get:1 https://packagecloud.io/github/git-lfs/ubuntu xenial/main amd64 git-lfs amd64 2.4.0 [2857 kB]
...
Preparing to unpack .../git-lfs_2.4.0_amd64.deb ...
Global Git LFS configuration has been removed.
Unpacking git-lfs (2.4.0) over (2.3.4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up git-lfs (2.4.0) ...
Git LFS initialized.
```

The `SSH=` line disappears from the environment:

```bash
$ git-lfs env
git-lfs/2.4.0 (GitHub; linux amd64; go 1.8.3)
git version 2.16.2

Endpoint (upstream)=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
LocalWorkingDir=/home/tignis/workspace/tignis_tap_PR-67-WXNB333I6RCCJG4OETW4JQLBGUH6P6HO4KSP4D6XUETE2YXM47LA
...
```

And `git lfs pull` fails to use my SSH credentials and asks for HTTPS credentials instead.

```bash
$ GIT_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull
...
00:45:45.233475 trace git-lfs: creds: git credential fill ("https", "bitbucket.org", "")
Username for 'https://bitbucket.org':
```

If I downgrade back to git-lfs/2.3.4, everything works again.

```
$ sudo apt-get install git-lfs=2.3.4
...
Get:1 https://packagecloud.io/github/git-lfs/ubuntu xenial/main amd64 git-lfs amd64 2.3.4 [2815 kB]
...
Preparing to unpack .../git-lfs_2.3.4_amd64.deb ...
Global Git LFS configuration has been removed.
Unpacking git-lfs (2.3.4) over (2.4.0) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up git-lfs (2.3.4) ...
Git LFS initialized.
```

The `SSH=` line comes back.

```
$ git-lfs env
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
git version 2.16.2

Endpoint=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
  SSH=git@bitbucket.org:tignis/tap.git
...
```

And I can pull files again (presumably using my SSH credentials).

```
$ GIT_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull
...
Git LFS: (0 of 2 files) 0 B / 91.24 MB                                                                                                                            00:51:54.102367 trace git-lfs: tq: sending batch of size 2
00:51:54.102697 trace git-lfs: run_command: ssh -- git@bitbucket.org git-lfs-authenticate tignis/tap.git download
00:51:55.048481 trace git-lfs: api: batch 2 files
...
Git LFS: (2 of 2 files) 91.24 MB / 91.24 MB
```

Is this a regression in git-lfs, or a problem on bitbucket.org's end? `.git/config` is pretty ordinary and looks like:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@bitbucket.org:tignis/tap.git
	fetch = +refs/heads/refactor-dash-into-pipelines:refs/remotes/origin/PR-67
[remote "upstream"]
	url = https://bitbucket.org/tignis/tap.git
[lfs "https://bitbucket.org/tignis/tap.git/info/lfs"]
	access = basic
[submodule "test_data"]
	url = git@bitbucket.org:tignis/test_data.git
```

**Comment by ttaylorr** [comment]
Hi @vermaport, thanks for opening this issue, and I'm sorry that you're having trouble. I am curious since the code that determines this hasn't changed dramatically since v2.3.4, which you indicated was working as expected.

Your configuration looks sane to me, but I'm wondering if there was a breaking change in upstream Go between 1.8.1 and 1.8.3. Could you try and built Git LFS v2.4.0 on Go 1.8.1 (instead of 1.8.3) and let me know if the issue persists?

**Comment by schultzern** [comment]
I'm seeing similar behavior on CentOS 7.4. I'm using git-lfs from the "github_git-lfs" repository (https://packagecloud.io/github/git-lfs/el/7/x86_64). Same issue both with _git-lfs 2.3.4_ and _2.4.0_. I'm using _git 2.12.2_. The `SSH=` option is not there from `git lfs env`. I have no problem pulling, but when I try to push I get the following error:

> Git LFS: (0 of 2 files) 0 B / 178.97 KB                                                                                                
batch response: Post https://server/home/novagit/repo/project.git/info/lfs/objects/batch: dial tcp 192.168.1.158:443: getsockopt: connection refused
error: failed to push some refs to 'ssh://user@server/home/novagit/repo/project.git'

**Comment by vermaport** [comment]
The issue seems to be when multiple remotes are defined. The Bitbucket Branch Source Plugin runs a script which adds an `upstream` remote when creating workspaces for Pull Requests. Note that with 2.4.0, `git-lfs env` doesn't list the `origin` remote.

```
$ git-lfs env
git-lfs/2.4.0 (GitHub; linux amd64; go 1.8.3)
git version 2.16.2

Endpoint (upstream)=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
LocalWorkingDir=/home/tignis/workspace/tignis_tap_PR-67-WXNB333I6RCCJG4OETW4JQLBGUH6P6HO4KSP4D6XUETE2YXM47LA
```

If I downgrade to 2.3.4, `git-lfs env` lists both the `origin` and `upstream` remotes:

```
$ git-lfs env
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
git version 2.16.2

Endpoint=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
  SSH=git@bitbucket.org:tignis/tap.git
Endpoint (upstream)=https://bitbucket.org/tignis/tap.git/info/lfs (auth=basic)
LocalWorkingDir=/home/tignis/workspace/tignis_tap_PR-67-WXNB333I6RCCJG4OETW4JQLBGUH6P6HO4KSP4D6XUETE2YXM47LA
...
```

I thought the issue might be that 2.4.0 isn't even seeing the `origin` endpoint. However, even with 2.4.0, `git-lfs pull origin` seems to work. So maybe the issue with 2.4.0 is that `git-lfs pull` does not try to pull from `origin` by default; instead it pulls from the last remote in `.git/config`. Not a huge deal (I can change my script to specify `origin` explicitly), but seems like a regression.

**Comment by ttaylorr** [comment]
@vermaport interesting -- thanks for trying this on a few different versions of Go. My initial inclination was that this was the root cause of the issue, but it appears to be something else.

I am unsure what is the cause right now since we have a passing test (
https://github.com/git-lfs/git-lfs/blob/v2.4.0/test/test-env.sh#L115-L172) that ensures that `git-lfs-env(1)` works with multiple remotes.

Would you mind dumping the output of the following command here to see if there's something else that might be causing it?

- `git remote -v`

**Comment by vermaport** [comment]
```
$ git remote -v
origin	git@bitbucket.org:tignis/tap.git (fetch)
origin	git@bitbucket.org:tignis/tap.git (push)
upstream	https://bitbucket.org/tignis/tap.git (fetch)
upstream	https://bitbucket.org/tignis/tap.git (push)
```

The Bitbucket Branch Source Plugin on Jenkins basically does:

```
git config remote.origin.url https://bitbucket.org/tignis/tap.git
git config remote.upstream.url https://bitbucket.org/tignis/tap.git
```

And then merges changes from the upstream branch into the origin branch, to test the Pull Request.
The Bitbucket Branch Source Plugin doesn't understand git-lfs when it performs the initial checkout, so I run a script later which changes the remote.origin.url to SSH, then runs `git lfs pull`. While Jenkins sets GIT_ASKPASS to something that works for the initial checkout via HTTPS, for some reason, git-lfs doesn't use it correctly.

```
git remote set-url origin git@bitbucket.org:tignis/tap.git
git lfs pull
```

Again, with 2.4.0, `git lfs pull` asks for a password because it seems to be trying the `upstream` endpoint. If I change the script to specify the `origin` endpoint explicitly, e.g. `git lfs pull origin`, it works, even with 2.4.0. It was my understanding that if a remote isn't specified, `origin` should be assumed.

**Comment by ttaylorr** [comment]
> While Jenkins sets GIT_ASKPASS to something that works for the initial checkout via HTTPS, for some reason, git-lfs doesn't use it correctly.

I see; this definitely sounds like a bug. I don't have time to investigate this right now, but I'll put this on my list for before v2.5.0. Thanks!

**Comment by PastelMobileSuit** [comment]
I looked into this and it turns out the problems that @vermaport saw were caused by the fact that `origin` was being explicitly excluded from the list of remotes read from a repo's configuration. I've just opened #3152, which should fix the issue.
