### ISSUE TITLE
Git LFS Problem in Pushing Larger Files

### ISSUE THREAD

**Issue by chandaku** [git-lfs/git-lfs#2916]
![image](https://user-images.githubusercontent.com/16346446/37450588-7aeca33e-2854-11e8-8ccd-86714e9201d5.png)

I am trying to explore git lfs on one of repository I have created on our GHE setup. I have created a repository and enabled LFS on it. After cloning this repository I executed “git lfs install” and provided zip track files so that all files with zip extension should have LFS support.

Now I added one zip file of size 1mb which is committed and pushed successfully and I could see pointer file generated for same. After this I replaced this file with another of size 2.98MB with same name and When I try to push, after adding and committing I am continuously facing following issue. Could you please help me with some clue for the cause of issue.

I already have explored around this issue but had no luck here.

**Comment by ttaylorr** [comment]
Hi @chandaku, thanks for opening this issue, and I'm sorry that you're having trouble!

HTTP 502 means that there was a Bad Gateway [[source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502)], which makes me inclined to believe that there is a network connectivity issue preventing you from pushing.

One way we could confirm this is by checking out some additional information with `GIT_TRACE=1` in your environment. Could you run:

```
GIT_TRACE=1 git push origin master
```

and copy/paste the output here after removing any sensitive information? That will give us a good indicator of whether or not there's a network connectivity issue preventing you from pushing, or there's something else that we should dive into.

**Comment by chandaku** [comment]
@ttaylorr Thanks for Looking at problem, I agree that 502 makes a bad gateway request but this problem persist only with LFS file push. Though I am able to commit and push non-lfs files easily. Here are logs with GIT_TRACE

$ GIT_TRACE=1 git push origin master
08:44:43.306516 git.c:340               trace: built-in: git 'push' 'origin' 'ma                                                                                                                ster'
08:44:43.309548 run-command.c:626       trace: run_command: 'ssh' 'git@13.127.65                                                                                                                .206' 'git-receive-pack '\''GHE-Explorer/light_music.git'\'''
Enter passphrase for key '/c/Users/ckumar/.ssh/id_rsa':
08:44:49.203126 run-command.c:626       trace: run_command: '.git/hooks/pre-push                                                                                                                ' 'origin' 'git@13.127.65.206:GHE-Explorer/light_music.git'
08:44:49.372195 git.c:572               trace: exec: 'git-lfs' 'pre-push' 'origi                                                                                                                n' 'git@13.127.65.206:GHE-Explorer/light_music.git'
08:44:49.373226 run-command.c:626       trace: run_command: 'git-lfs' 'pre-push'                                                                                                                 'origin' 'git@13.127.65.206:GHE-Explorer/light_music.git'
08:44:52.012050 trace git-lfs: run_command: 'git' version
08:44:52.097177 trace git-lfs: run_command: 'git' config -l
08:44:52.150111 trace git-lfs: tq: running as batched queue, batch size of 100
08:44:52.150607 trace git-lfs: run_command: ssh -- git@13.127.65.206 git-lfs-authenticate GHE-Explorer/light_music.git upload
08:45:20.923707 trace git-lfs: HTTP: POST https://13.127.65.206/_lfs/GHE-Explorer/light_music/locks/verify
08:45:21.401849 trace git-lfs: HTTP: 500
08:45:21.401849 trace git-lfs: HTTP: {"documentation_url":"https://github.com/contact","message":"Unable to verify locks","request_id":"6d006bab-2991-11e8-8c8c-27e695663545"}

Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://13.127.65.206/GHE-Explorer/light_music.git/info/lfs.locksverify false
08:45:27.133870 trace git-lfs: pre-push: refs/heads/master 285b109e52da97c4e4b55031e4d89bc546468d9d refs/heads/master 0000000000000000000000000000000000000000
08:45:27.134377 trace git-lfs: run_command: git rev-list --objects 285b109e52da97c4e4b55031e4d89bc546468d9d --not --remotes=origin --
08:45:27.143357 trace git-lfs: run_command: git cat-file --batch
08:45:27.188321 trace git-lfs: tq: sending batch of size 1
08:45:27.188321 trace git-lfs: ssh cache: git@13.127.65.206 git-lfs-authenticate GHE-Explorer/light_music.git upload
08:45:27.188321 trace git-lfs: api: batch 1 files
08:45:27.188321 trace git-lfs: HTTP: POST https://13.127.65.206/_lfs/GHE-Explorer/light_music/objects/batch
08:45:27.354744 trace git-lfs: HTTP: 502
08:45:27.354744 trace git-lfs: api error: Fatal error: Server error: https://13.127.65.206/_lfs/GHE-Explorer/light_music/objects/batch from HTTP 502
Git LFS: (0 of 1 files) 0 B / 49.48 KB
batch response: Fatal error: Server error: https://13.127.65.206/_lfs/GHE-Explorer/light_music/objects/batch from HTTP 502

Errors logged to C:\Users\ckumar\Desktop\light_music\light_music\.git\lfs\objects\logs\20180317T084527.3547442.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'git@13.127.65.206:GHE-Explorer/light_music.git'

**Comment by ttaylorr** [comment]
Hi @chandaku thanks for the response -- you are totally right that this isn't a network connectivity issue. I believe that your installation of GitHub is having difficulty authorizing you. Since I think that this is an issue pertaining to GitHub, and not Git LFS, would you mind opening a `support@` ticket or discussing with your enterprise admin?

**Comment by wenjinghy** [comment]
Hi@ttaylorr when I run git push origin master ,I got this error:
![git lfs](https://user-images.githubusercontent.com/31907394/37883298-329ff2ee-30dc-11e8-9f28-ecb1e099b475.png) 
Thank you in advice.

**Comment by ttaylorr** [comment]
@wenjinghy since you already commented about this in https://github.com/git-lfs/git-lfs/issues/2946, I will continue our discussion there.

**Comment by Sarah-16** [comment]
'GIT_TRACE' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bk2204** [comment]
Hey, @Sarah-16, that command needs to be run in Git Bash or otherwise under a POSIX shell.  If you're still having problems, please open a new issue since this one's closed, and we'll help you theree.

**Comment by park-jeounghan** [comment]
git lfs push error checked request.

![image](https://user-images.githubusercontent.com/48382217/194012467-28079c3a-4bb8-40e5-a6e5-4fe436f82d0a.png)


help me
