### ISSUE TITLE
Uninstall doesn't work

### ISSUE THREAD

**Issue by bootstraponline** [git-lfs/git-lfs#2919]
```bash
#!/usr/bin/env bash
set -ex

git lfs uninstall
rm `which git-lfs`
```

```
error: external filter git-lfs smudge -- %f failed -1
error: external filter git-lfs smudge -- %f failed
```

How do I uninstall git lfs from the CLI? The use case is removing git-lfs on select CI builds, while still leaving the repo configured for regular clones.

**Comment by bootstraponline** [comment]
I've had to zero out the file to avoid smudge errors:

```bash
echo "" > `which git-lfs`
```

**Comment by ttaylorr** [comment]
Hi @bootstraponline, thanks for opening this issue, and I'm sorry that you're having trouble. I think that there are a few things going on here:

1. `git lfs uninstall` removed your Git LFS filters from _a_ global configuration, but it is possible that another git configuration retained that value. Those filters, when present in a configuration file, tell Git to invoke Git LFS, which is why the failures began after you removed the binary. To resolve this, you can see which Git configurations have anything mentioning Git LFS in them via: 

```
~/g/git-lfs (master) $ git config --global --show-origin --get-regexp 'filter.lfs.*'
file:/Users/ttaylorr/.gitconfig filter.lfs.clean git-lfs clean -- %f
file:/Users/ttaylorr/.gitconfig filter.lfs.smudge git-lfs smudge -- %f
file:/Users/ttaylorr/.gitconfig filter.lfs.process git-lfs filter-process
file:/Users/ttaylorr/.gitconfig filter.lfs.required true
```

Removing those sections from each configuration listed above should resolve the issue.

##

If this isn't the case or something else is wrong, however, please do not hesitate to ping me here in the future.

**Comment by bootstraponline** [comment]
I'm trying to figure out how to uninstall git lfs in CI. You can see my attempts here:
https://github.com/bitrise-io/steps-git-clone/issues/75

There doesn't seem to be a clean way of removing lfs. I've had to zero out the binary. If there's a better way, please let me know.

**Comment by bootstraponline** [comment]
LFS is preinstalled on the docker image. It's also installed in the repo being cloned.

We have a mono repo with some large CLI tools that use LFS. The CLI tools are only useful locally. I was hoping that there was an easy way to tell the CI server to not download any LFS files. The bandwidth usage is overwhelming because each build downloads all the LFS files.

Bitrise, the CI vendor, is going to look into it. In my testing, only zeroing out the LFS binary has worked. I wish there was a SKIP_LFS environment variable or a similar non-destructive option.

**Comment by ttaylorr** [comment]
> Bitrise, the CI vendor, is going to look into it.

Sounds great! Please let me know if there is anything I can do to help you or them out.

> In my testing, only zeroing out the LFS binary has worked. I wish there was a SKIP_LFS environment variable or a similar non-destructive option.

You can cause this to occur via:

```
git config --global lfs.fetchexclude '*'`
```

which will cause Git LFS to not operate over any file.

**Comment by bootstraponline** [comment]
Thanks. I'll share that with them.

**Comment by bootstraponline** [comment]
I created a bitrise disable LFS step. It works! Thanks for your help.

- https://github.com/instructure/steps-disable-git-lfs

**Comment by englianhu** [comment]
installed `lfs` to push/pull large size files but unable connect to Github repo, then tried to uninstall still doesn;t work, somebody shade me a light?
https://stackoverflow.com/questions/52769821/removing-git-lfs

**Comment by englianhu** [comment]
https://github.com/git-lfs/git-lfs/issues/910
https://github.com/git-lfs/git-lfs/issues/4137

**Comment by bk2204** [comment]
If your goal is to remove the use of Git LFS from your repository, you'll probably want `git lfs migrate export --everything`.  `git lfs uininstall` doesn't revert the transformation of large files to LFS files in your repository, but it does remove the hooks and configuration.
