### ISSUE TITLE
Clone of repo with lfs files hanging on filtering

### ISSUE THREAD

**Issue by adrianefresh** [git-lfs/git-lfs#2921]
Trying to clone a repo from github (both using github desktop and command line) and keeps hanging on filtering (at about 55%, though exact point keeps changing...). 

```
Vesper$ git clone https://github.com/nickeubank/nc_electioneering.git
Cloning into 'nc_electioneering'...
Username for 'https://github.com':
Password for 'https://adrianefresh@github.com': 
remote: Counting objects: 1717, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 1717 (delta 76), reused 93 (delta 31), pack-reused 1567
Receiving objects: 100% (1717/1717), 295.99 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (536/536), done.
Checking out files: 100% (733/733), done.
Filtering content:  52% (118/226), 3.49 GiB | 100.34 MiB/s    

[COMMAND C]

Exiting because of "interrupt" signal.
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

```

Software:

```
git version 2.16.2
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)

OSX 10.11.6

Github desktop 1.1.0
```

Happy to provide logs with guidance on where to find. `git lfs logs` not generating anything after I kill the process (and have to kill process because just hanging...)

**Comment by adrianefresh** [comment]
Aaaand... suddenly on the ~7th attempt it worked. My guess is a github LFS server issue.

**Comment by ttaylorr** [comment]
Hi @adrianefresh, thanks for opening this issue. I'm glad that you got everything resolved. For posterity's sake, I am going to propose that this was a connectivity issue between your LAN and GitHub.com, but please do not hesitate to ping me here again if the same issue persists in the future.
