### ISSUE TITLE
Consider adding a do-nothing `no-lfs` filter to make LFS exclusions more explicit/easier

### ISSUE THREAD

**Issue by dakotahawkins** [git-lfs/git-lfs#2931]
See [comments](https://github.com/git-lfs/git-lfs/issues/2120#issuecomment-374621468) in #2120 

Example `.gitattributes`

```
# Track .png files with LFS
*.[Pp][Nn][Gg] filter=lfs diff=lfs merge=lfs -text

# Exclude files under .readme-docs from LFS tracking
/.readme-docs/** !filter !diff !merge
```

I think it still might be more usable if git-lfs provided a do-nothing `no-lfs` filter, making the `.gitattributes` exclusion explicit:

```
# Track .png files with LFS
*.[Pp][Nn][Gg] filter=lfs diff=lfs merge=lfs -text

# Exclude files under .readme-docs from LFS tracking
/.readme-docs/** filter=no-lfs diff=no-lfs merge=no-lfs
```

If you think this would be worthwhile I could work on it. If not, I think it would at least be a good idea to document how to write these exclusions properly.

**Comment by ttaylorr** [comment]
Since we already have a thread going in https://github.com/git-lfs/git-lfs/issues/2120, I'm going to close this issue for now.
