### ISSUE TITLE
Bad sources.list permissions after packagecloud.io install on Ubuntu 16.04

### ISSUE THREAD

**Issue by ntc2** [git-lfs/git-lfs#2935]
I just installed Git LFS on Ubuntu 16.04 using

```sh
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo aptitude install git-lfs
```

After this running `aptitude` as non-root user gives permissions errors related to file `/etc/apt/sources.list.d/github_git-lfs.list`, which is only readable to root. Solution was

```sh
sudo chmod a+r /etc/apt/sources.list.d/github_git-lfs.list
```

**Comment by ttaylorr** [comment]
Hi @ntc2, thanks for opening this. That script is auto-generated by PackageCloud, so I think that this is an issue that they would be more well-suited to deal with than myself. Could you open a ticket with them to the same effect?

**Comment by ntc2** [comment]
Hi Packagecloud, I can't find an issue tracker on your website, so I'm
reporting this bug by email. The bug is that a Packagecloud package on
Ubuntu creates a sources.list with the wrong permissions. Please see
https://github.com/git-lfs/git-lfs/issues/2935#issuecomment-377094856 for
details.

---------- Forwarded message ----------

**Comment by capotej** [comment]
hi @ntc2 can you email support@packagecloud.io so we can support you directly? Thanks!

**Comment by ntc2** [comment]
@capotej , done! Above I intended to forward to support@packagecloud.io and CC GitHub, but it seems I only CC'd GitHub :P
