### ISSUE TITLE
How to clone everything when fetchexclude is set to be * in .lfsconfig

### ISSUE THREAD

**Issue by hosnas** [git-lfs/git-lfs#2936]
I'm sorry if this question is asked a hundred time. However I couldn't find the answer. 

I've already added `.lfsconfig` file with the following content in my repository
```
[lfs]
fetchexclude = *
```
I intended to not automatically download lfs files when cloning repository.

Now how should I override this behavior? I want to download every lfs file, regardless of fetchexclude parameter.

**Comment by ttaylorr** [comment]
Hi @hosnas! You can override this with a per-command configuration option, via the globally-supported `-c` flag.

Does this work?

```
git -c "lfs.fetchexclude=" clone $repository
```
