### ISSUE TITLE
Support Artifactory or reverse proxy/redirection (allow access=basic)

### ISSUE THREAD

**Issue by hacki11** [git-lfs/git-lfs#2940]
To support reverse proxies or support Artifactory:
https://www.jfrog.com/jira/browse/RTFACT-11955

one should be able to set `lfs.access = basic`.

please explain how to set this flag (it is ignored declared unsafe).

Our systems does not return a 401, instead a 200 which redirects to a login page (reverse proxy).
If i add my authentication data in lfs url like https://user:pass@host everything works fine. but ofc this is not a solution for a team.
Artifactory is used as storage behind the reverse proxy.

Documentation says it is supported to set the flag, unfortunately its declared unsafe:
https://github.com/git-lfs/git-lfs/blob/39727e8719330a1293329b95460f99d57b7cd565/docs/man/git-lfs-config.5.ronn#L237

**Comment by ttaylorr** [comment]
> please explain how to set this flag (it is ignored declared unsafe).

It is declared unsafe in `.lfsconfig`, for security reasons. You can ensure that this is set by running `git config lfs.access basic`, which will add this configuration to your local on-disk copy of the repository at `.git/config`.
