### ISSUE TITLE
Lfs client portable version

### ISSUE THREAD

**Issue by jflefebvre06** [git-lfs/git-lfs#2944]
Could you please add a portable version of the lfs client

**Comment by ttaylorr** [comment]
Hi @jflefebvre06, thanks for opening this issue! I am wondering if you could clarify what you mean by "portable".

Currently:

- Git LFS distributes Linux, Free BSD, macOS, and Windows binaries for all common architectures in releases [here](https://github.com/git-lfs/git-lfs/releases).
- Git LFS is build-able from source on any operating system and architecture support by Go by setting `GOOS` and `GOARCH` in your environment before running `script/bootstrap`.

    For example, if I want to build Git LFS for Plan 9 on ARM, I could run:

    ```
    GOOS=plan9 GOARCH=arm script/bootstrap
    ```

Does that answer your question?

**Comment by jflefebvre06** [comment]
Hello @ttaylorr 

I meen windows portable edition like git

Git for Windows Portable ("thumbdrive edition")
* 32-bit Git for Windows Portable.
* 64-bit Git for Windows Portable.

![sans titre](https://user-images.githubusercontent.com/2685607/37950652-aed3b86a-3199-11e8-99b2-a50f72579b81.png)

**Comment by ttaylorr** [comment]
> I meen windows portable edition like git

I see; thank you for clarifying! Unlike Git for Windows, Git LFS distributes only a single program, so there is nothing to "slim down" in a thumbdrive edition.

**Comment by scottmwyant** [comment]
@ttaylorr It's not about slimming down, it's the install. We want to be able to get going without needing admin credentials to install. "Portable"usually means you can drag & drop the application root, hit the exe and it still works.

This is an old thread and I'll admit, I haven't done my homework. I need to see for myself if the LFS plug-in requires admin install, maybe not. Either way it would be good to clarify that in this thread.

**Comment by bk2204** [comment]
The Git LFS client does not require administrator privileges.  We provide zip files of signed Git LFS Windows binaries on our releases page that should just work provided they're in `PATH`.  We also provide an installer as well, which may well require privileges, although usually people use the version in Git for Windows itself. 

We do try hard to provide binaries that are independent and relocatable for this reason.

Note that the zip files also contain manual pages; if you don't need or want those, you can simply not copy them.
