### ISSUE TITLE
Docs - missing a quick intro

### ISSUE THREAD

**Issue by andybak** [git-lfs/git-lfs#2951]
There's a YouTube video but there doesn't seem to anything text-based and concise before you hit the formal specs.

This page: https://github.com/git-lfs/git-lfs/tree/master/docs could do with a link to something a bit longer than the intro on https://git-lfs.github.com/ but more concise than the deep dive docs.

**Comment by ttaylorr** [comment]
Hi @andybak, thanks for opening this issue. I recently updated the README.md to give a more detailed overview of getting started than what is found on the website, but less so than the complete specification.
