### ISSUE TITLE
Binary files Autodetection 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [git-lfs/git-lfs#2953]
Is it possible to implement it somehow ? Manual filling .gitattributes during migration from perforce sometimes tediously. May be it will be good to implement same way as it done in perforce. To check first 10k bytes of file and if found at least once non-ASCII symbol then add this file as binary to lfs.  Sorry if it is already done . At least i not found anywhere description of such feature.

**Comment by ttaylorr** [comment]
Hi @jpVm5jYYRE1VIKL, thanks for opening this issue and sharing this suggestion! I think it's an interesting idea, and Git already does a similar kind of binary detection, although there is no current way to attach LFS to files that are detected as binary without rewriting the `.gitattributes` file as you noted above.

**Comment by jpVm5jYYRE1VIKL** [comment]
Sorry to say this. But without this feature git-lfs completely useless. In my current .gitattributes i have already 5 pages and still adding it one by one. Every time doing a copy 67 gigabytes of data. Was force to cancel migration and put it to trash bin.

**Comment by ttaylorr** [comment]
> In my current .gitattributes i have already 5 pages and still adding it one by one.

.gitattributes has flexible pattern matching features, which are described [here](https://git-scm.com/docs/gitattributes), so if you have lots of files in a particular directory, or lots of files that share the same extension then you can grab them all at once.

`git lfs migrate info` can also show you a list of large files in your repository.

**Comment by ygypt** [comment]
has there been any progress on this topic?

**Comment by jpVm5jYYRE1VIKL** [comment]
> has there been any progress on this topic?

Nope . I switched to plasticscm.

**Comment by ygypt** [comment]
> > has there been any progress on this topic?
> 
> Nope . I switched to plasticscm.

lmao, that's my plan as well once our repo hits the 2g limit. have you encountered any issues with plastic? or is it as clean and effortless as the adverts make it out to be

**Comment by jpVm5jYYRE1VIKL** [comment]
> > > has there been any progress on this topic?
> > 
> > 
> > Nope . I switched to plasticscm.
> 
> lmao, that's my plan as well once our repo hits the 2g limit. have you encountered any issues with plastic? or is it as clean and effortless as the adverts make it out to be

Only issue that plasticscm it is not free and also i forced manually unpack client deb packages to make it work under arch (i use it as work station). For now i have 100Gb repo. Server stuff works good . Gui client sometimes have trivial issues like process lock during exit of application. With Cli client never had issues. Using it already 3 years.
