### ISSUE TITLE
git-lfs for Ubuntu Bionic (18.04) on packagecloud.io

### ISSUE THREAD

**Issue by ColinHebert** [git-lfs/git-lfs#2957]
At the moment there isn't a git-lfs package available on packagecloud.io for Ubuntu Bionic.

With the release of the new LTS coming in the next few weeks, it would be good to go ahead and publish git-lfs 2.4.0 for Bionic.

**Comment by ttaylorr** [comment]
Hi @ColinHebert thanks for this suggestion. I just wrote and merged #2961, which updates the script I run to release Git LFS to also push out binaries to Ubuntu Bionic. I rebuilt Git LFS v2.4.0, and pushed it out to PackageCloud just now:

> ```ShellSession
> $ PACKAGECLOUD_TOKEN=... ./script/packagecloud.rb
> Using packagecloud-ruby:1.0.8
> pushing repos/debian/9/git-lfs_2.4.0_amd64.deb to "ubuntu/bionic"
> pushing repos/debian/9/git-lfs_2.4.0_i386.deb to "ubuntu/bionic"
> ```
