### ISSUE TITLE
ssh-command issues

### ISSUE THREAD

**Issue by Garonenur** [git-lfs/git-lfs#2962]
I have a problem using git-lfs with [ccontavalli/ssh-ident](https://github.com/ccontavalli/ssh-ident).
We use a GitHub Enterprise Server and lfs is enabled, except for the lfs-lock which i could not find in the server settings and have not researched further.

first `ssh git@github[…].de git-lfs-authenticate DirkWillrodt/testrepo download`
gives
```
{
  "href": "https://github[…].de/_lfs/DirkWillrodt/testrepo",
  "header": {
    "Authorization": "RemoteAuth […]"
  },
  "expires_at": "2018-04-10T12:16:23Z",
  "expires_in": 599
}%
```
but `GIT_TRACE=1 GIT_SSH_COMMAND=ssh git push`
results in
```
14:11:39.914792 git.c:344               trace: built-in: git 'push'
14:11:39.918550 run-command.c:627       trace: run_command: 'ssh' 'git@github[…].de' 'git-receive-pack '\''/DirkWillrodt/testrepo'\'''
All keys already loaded
14:11:40.472375 run-command.c:627       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@github[…].de:/DirkWillrodt/testrepo'
14:11:40.523968 git.c:576               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@github[…].de:/DirkWillrodt/testrepo'
14:11:40.524371 run-command.c:627       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@github[…].de:/DirkWillrodt/testrepo'
14:11:40.585902 trace git-lfs: exec: git 'version'
14:11:40.888014 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
14:11:41.116429 trace git-lfs: exec: git 'config' '-l'
14:11:41.160058 trace git-lfs: pre-push: refs/heads/master 0130bec5005b35d6728244baf08496020691d2f1 refs/heads/master 988398b9648700a74f3181671543822d0db967ff
14:11:41.836006 trace git-lfs: run_command: ssh -- git@github[…].de git-lfs-authenticate /DirkWillrodt/testrepo upload
14:11:41.947774 trace git-lfs: ssh: git@github[…].de failed, error: exit status 255, message: git@github[…].de: Permission denied (publickey).
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://github[…].de//DirkWillrodt/testrepo.git/info/lfs.locksverify false
14:11:41.947774 trace git-lfs: tq: running as batched queue, batch size of 100
14:11:41.948275 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
14:11:41.954791 trace git-lfs: run_command: git cat-file --batch
14:11:42.018962 trace git-lfs: tq: sending batch of size 1
14:11:42.018962 trace git-lfs: run_command: ssh -- git@github[…].de git-lfs-authenticate /DirkWillrodt/testrepo upload
14:11:42.131763 trace git-lfs: ssh: git@github[…].de failed, error: exit status 255, message: git@github[…].de: Permission denied (publickey).
batch request: git@github[…].de: Permission denied (publickey).: exit status 255
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
error: failed to push some refs to 'git@github[…].de:/DirkWillrodt/testrepo'
```

`ssh` is a symbolic link to `ssh-ident`

If I give `GIT_SSH_COMMAND=/home/dwillrodt/bin/ssh` I get `trace git-lfs: ssh: git@github[…].de failed, error: exec: "/home/dwillrodt/bin/ssh": file does not exist, message:
batch request: exec: "/home/dwillrodt/bin/ssh": file does not exist
`

I tried to use the https-protocol instead of ssh but there the `git push` simply hangs:
```
14:31:55.631065 git.c:344               trace: built-in: git 'push'
14:31:55.632557 run-command.c:627       trace: run_command: 'git-remote-https' 'origin' 'https://github[…].de:/DirkWillrodt/testrepo'
Username for 'https://github[…].de:':
Password for 'https://DirkWillrodt@github[…].de:':
14:32:09.162257 run-command.c:627       trace: run_command: '.git/hooks/pre-push' 'origin' 'https://github[…].de:/DirkWillrodt/testrepo'
14:32:09.237713 git.c:576               trace: exec: 'git-lfs' 'pre-push' 'origin' 'https://github[…].de:/DirkWillrodt/testrepo'
14:32:09.238078 run-command.c:627       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'https://github[…].de:/DirkWillrodt/testrepo'
14:32:09.302982 trace git-lfs: exec: git 'version'
14:32:09.608296 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
14:32:09.830890 trace git-lfs: exec: git 'config' '-l'
14:32:09.873503 trace git-lfs: pre-push: refs/heads/master 0130bec5005b35d6728244baf08496020691d2f1 refs/heads/master 988398b9648700a74f3181671543822d0db967ff

```
Nothing happens after that step, the only file in the repo I have unter lfs-control is a .bmp with 3.1MB which shouldn't take minutes to process.

I can change to a different ssh-key-agent, but ssh-ident is realy handy if one uses more than one ssh-key.
I noticed the difference in the traces between the run-command.c of git and run-command used by lfs, might this be a problem?

I'm happy to provide further information.

**Comment by Garonenur** [comment]
I have to add, I am running cygwin and I get `exec: "/usr/bin/ssh.exe": file does not exist` for non symbolic links, too. How does the check for the `GIT_SSH_COMMAND` work?

**Comment by ttaylorr** [comment]
Hi @Garonenur, thanks for opening this issue. There's a lot here, so let me try my best to break it all down:

> but GIT_TRACE=1 GIT_SSH_COMMAND=ssh git push results in
>
> ```ShellSession
> # ...
> 14:11:41.836006 trace git-lfs: run_command: ssh -- git@github[…].de git-lfs-authenticate /DirkWillrodt/testrepo upload
> 14:11:41.947774 trace git-lfs: ssh: git@github[…].de failed, error: exit status 255, message: git@github[…].de: Permission denied (publickey).
> ```

It looks like Git LFS is respecting your `GIT_SSH_COMMAND`, as I would expect, but your ssh client is responding with an identity that your server does not recognize. I'm not familiar with `ssh-ident` as you mentioned above, but I am inclined to believe that this is an SSH configuration issue above all else.

> If I give `GIT_SSH_COMMAND=/home/dwillrodt/bin/ssh` I get `trace git-lfs: ssh: git@github[…].de failed, error: exec: "/home/dwillrodt/bin/ssh": file does not exist, message: batch request: exec: "/home/dwillrodt/bin/ssh": file does not exist`

This part looks like the `ssh` binary doesn't exist. Is that true?

> I tried to use the https-protocol instead of ssh but there the `git push` simply hangs:

I'm not sure about this, though it is concerning to me. If your repository is open-source, I'd be happy to take a look.

**Comment by Garonenur** [comment]
hi @ttaylorr,

Our Github is not open, sorry - it is a company server and not available for public.

I will try to see if any misconfiguration in ssh-ident or .ssh/config has caused this.

concerning the binaries: yes they exist but it is within cygwin and maybe there is a problem with which environment gets startet with git-lfs because I installed that in windows, not in cygwin.

I could try to install git-lfs from the repo and not the binary for windows  - that would put it in my cygwin environment and maybe fix this problem. I'll report back.

**Comment by ttaylorr** [comment]
Moving to https://github.com/git-lfs/git-lfs/issues/1053.
