### ISSUE TITLE
[OSX] calling git-lfs from ssh doesn't work

### ISSUE THREAD

**Issue by Duobix** [git-lfs/git-lfs#2964]
On OSX I've ecountered a peculiar problem:
If I ssh (interactive) into the machine, I can normally perfrom a git pull with lfs, 
but when I'm just making a simple ssh command it doesn't work, outputing such an error:
git-lfs filter-process: git-lfs: command not found
I've already checked the $PATH, and they were different in case of interactive and comman shh,  and tried exporting the actual  path of LFS to both /usr/local/bin and some location in /Users/user/, but it didn't work. 

FYI: I've performed git lfs install --system previously, and I'm just clueless how to get git-lfs working right now via ssh commands.

**Comment by ttaylorr** [comment]
Hi @Duobix, thanks for opening this. I think this error indicates your problem:

> git-lfs filter-process: git-lfs: command not found

This means that whatever user you are logging into over SSH does _not_ have `git-lfs` in their `$PATH`. Some helpful commands to run could be `whoami` and `echo $PATH`, to observe what user is being logged in and what is on their path.
