### ISSUE TITLE
git lfs push take an hour

### ISSUE THREAD

**Issue by boskiv** [git-lfs/git-lfs#2965]
How I can debug it and increase speed, because it's terrible.
I have an mirror with 30Gb objects.
I have clone it and make first push into my git repo (Running [Gitea](https://github.com/go-gitea/gitea)).

Then I have cron task that do:
```
git fetch --all
git lfs fetch --all
git lfs push gitea-mirror --all
```
In moment push i see in top:

![screen shot 2018-04-12 at 12 34 26](https://user-images.githubusercontent.com/1939783/38669051-07563380-3e4e-11e8-9c64-efcc53ee9661.png)
and in logs:
```
Git LFS: (0 of 2108 files, 10559 skipped) 0 B / 1.79 GB, 28.64 GB skipped
Git LFS: (0 of 48 files, 12600 skipped) 0 B / 3.38 MB, 30.42 GB skipped
Git LFS: (0 of 48 files, 12600 skipped) 0 B / 3.38 MB, 30.42 GB skipped
Git LFS: (0 of 81 files, 13400 skipped) 0 B / 16.53 MB, 30.67 GB skipped
Git LFS: (0 of 81 files, 13400 skipped) 0 B / 16.53 MB, 30.67 GB skipped
Git LFS: (0 of 90 files, 13400 skipped) 0 B / 25.66 MB, 30.67 GB skipped
Git LFS: (0 of 96 files, 13400 skipped) 0 B / 34.28 MB, 30.67 GB skipped
Git LFS: (0 of 8 files, 13500 skipped) 0 B / 21.36 MB, 30.71 GB skipped
Git LFS: (0 of 8 files, 13500 skipped) 0 B / 21.36 MB, 30.71 GB skipped
Git LFS: (0 of 8 files, 13500 skipped) 0 B / 21.36 MB, 30.71 GB skipped
```

Here is my `git lfs env`
```
[root@lu1-v-pixelgit-01 mechwars.git]# git lfs env
git-lfs/2.3.0 (GitHub; linux amd64; go 1.8.3)
git version 2.2.1

Endpoint=http://remote-repo/scm/group/repo.git/info/lfs (auth=none)
Endpoint (gitea-mirror)=http://gitea/group/repo.git/info/lfs (auth=none)
LocalWorkingDir=
LocalGitDir=/opt/tmp_git/repo.git
LocalGitStorageDir=/opt/tmp_git/repo.git
LocalMediaDir=/opt/tmp_git/repo.git/lfs/objects
LocalReferenceDir=
TempDir=/opt/tmp_git/repo.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/opt/tmp_git/repo.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

fetch one file is fast, but push --all takes an hour.
I have tried just push, but it don't push new files, may be it push only master branch.

Please help me to decrease time of incremental push.

**Comment by boskiv** [comment]
Also I have notice another problem:

After 1 hour pushing I have not file in my mirror:
```
➜  mirror git:(master) git checkout mirror_test 
Downloading pic.png (43 KB)
Error downloading object: pic.png (2808636): Smudge error: Error downloading pic.png (2808636d978618101d59459c044c05d8e3fe068367832835a80de5935ca89834): LFS: Repository or object not found: http://gitea/grooup/repo.git/info/lfs/objects/2808636d978618101d59459c044c05d8e3fe068367832835a80de5935ca89834
Check that it exists and that you have proper access to it

Errors logged to /Users/i_skiridomov/projects/group/mirror/.git/lfs/logs/20180412T141847.011102497.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: pic.png: smudge filter lfs failed

```

If I push object by ID
```
[root@gitea repo.git]# git lfs push gitea-mirror --object-id 2808636d978618101d59459c044c05d8e3fe068367832835a80de5935ca89834
Locking support detected on remote "gitea-mirror". Consider enabling it with:
  $ git config lfs.http://gitea/group/repo.git/info/lfs.locksverify true
Git LFS: (1 of 1 files) 41.65 KB / 41.65 KB                                                                                           
```
 it works. 
```
➜  mirror git:(master) git checkout mirror_test 
Branch 'mirror_test' set up to track remote branch 'mirror_test' from 'origin'.
Switched to a new branch 'mirror_test'
```
Why it's happend ? Why --all don't push new objects ?

PS. I have follow by this manual:
 
https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository-that-contains-git-large-file-storage-objects

**Comment by ttaylorr** [comment]
@boskiv thanks for opening this up. Here are some thoughts:

> How I can debug it and increase speed, because it's terrible.

`git lfs push --all` _necessarily_ scans through the entire contents of your repository. There are many degenerate cases that can make this process take a large amount of time, like (1) long histories, (2) deep trees, (3) often-changing trees, etc. If your repository looks like any of these, it may take a long time to scan it.

In addition, `git lfs push` has to contact the remote for every object that it finds. If your repository has 13,000 objects, your Git LFS client will make 130 batch API network round-trips requests.

In essence, there is no "trick" to make `git lfs push --all` _fast_ on a large repository. The upshot is that you will only have to do this once when mirroring a repository, and then `git lfs push` will work for you in all cases in the future.

With regards to https://github.com/git-lfs/git-lfs/issues/2965#issuecomment-380774193, I'm not sure what's going on without having access to your repository.
