### ISSUE TITLE
Share git-lfs server across remotes

### ISSUE THREAD

**Issue by CQCumbers** [git-lfs/git-lfs#2970]
I apologize if I missed something obvious in the documentation, but does git-lfs require a separate server for each remote? I want to use a git push based deployment tool with my lfs repository, which is hosted on github, but do I need to setup a separate lfs server for this or is there some way to share github's? Otherwise, is there any workaround to push lfs repositories to remotes without a running lfs server (without leaving behind the large files)?

**Comment by ttaylorr** [comment]
The specification does not currently provide a "best practice" way for this to occur.

Of course, if you were to implement your own Git LFS server from scratch, this is something that would depend on implementation: mostly if the "shared" server that you are communicating with supports listing/downloading individual files. Git LFS is content-addressable, so this is likely not the case. On GitHub, for instance, we do not expose any way to gather the list of all objects in a repository.
