### ISSUE TITLE
Work with local repositories

### ISSUE THREAD

**Issue by Canxes** [git-lfs/git-lfs#2972]
Hello! 

My problem is: I want to pull and fetch from the local repo, that was configured to support lfs. As far as I understand, there is no such option and git lfs always requires a server to work? I made small reseach on the topic, but just to be sure. 

Also I wonder, is there any way to transfer commits(git bundle) from one machine to another with support of the git-lfs? I have tried, but no success. The best result was just a placeholders instead of files. 

Thanks in advance.

**Comment by ttaylorr** [comment]
Hi @Canxes, thanks for opening this issue. Here are some answers to your questions:

> I understand, there is no such option and git lfs always requires a server to work?

This is correct.

> Also I wonder, is there any way to transfer commits(git bundle) from one machine to another with support of the git-lfs? I have tried, but no success.

This is also the case; Git LFS does not support the archiving functionality via `git-bundle(1)`, as it would require upstream changes to do so. I believe that you can execute this from a non-bare repository when all of the Git LFS files are checked out, but I have not tried this myself.

##

In a larger sense, these are things that I would perhaps like Git LFS to eventually support, but they are large projects and I do not have time to dedicate to this right now.

**Comment by MacroUniverse** [comment]
Will this local feature be added in the future? I recently found that git lfs is a great tool for backing up my large folder, it works like macOs' Time Machine. However, I need to pull the latest commit to other backups to update them. I would like to support you financially if you develop this feature.
