### ISSUE TITLE
Cannot install git.

### ISSUE THREAD

**Issue by Y4shin** [git-lfs/git-lfs#2973]
I tried to install git with Chocolatey in an elevated PowerShell. While it seems to be installed because I can use it, it doesnt show up when I use `choco list --local-only`. I constantly get this error message in the PowerShell:

PS C:\ProgramData\chocolatey\lib\git.install\tools> choco install git
Chocolatey v0.10.10
Installing the following packages:
git
By installing you accept licenses for the packages.

git.install v2.17.0 [Approved]
git.install package files install completed. Performing other installation steps.
Using Git LFS
Installing 64-bit git.install...
git.install has been installed.
git.install installed to 'C:\Program Files\Git'
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Access is denied
  git.install can be automatically uninstalled.
git not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.17.0-64-bit.exe' is denied.
git package files install completed. Performing other installation steps.
The install of git was NOT successful.
git not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.17.0-64-bit.exe' is denied.

Chocolatey installed 0/2 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - git.install (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\git.install\tools\chocolateyInstall.ps1'.
 See log for details.
 - git (exited 1) - git not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.17.0-64-bit.exe' is denied.

EDIT: Moved the log to the attatched file. Didnt know I could do that 🤣 
[chocolatey.log](https://github.com/git-lfs/git-lfs/files/1920755/chocolatey.log)
[chocolatey.log](https://github.com/git-lfs/git-lfs/files/1920758/chocolatey.log)

**Comment by ttaylorr** [comment]
Hi @Y4shin, thanks for opening this issue -- if I'm not mistaken it looks like you are trying to install Git via Chocolatey, but this is the repository for Git _LFS_. Could you send an email to Chocolatey instead? 

Thanks, and sorry for the confusion!

**Comment by Y4shin** [comment]
Oh... I intended to do that, but I had both repos open and accidentally sent it here. Sorry for the inconvenience.
