### ISSUE TITLE
`git lfs push` tops out at 54KB/s

### ISSUE THREAD

**Issue by teebszet** [git-lfs/git-lfs#2981]
Pushing from Hong Kong, but this still seems too slow to be normal. 

How do I debug this?

Using Git Bash on Windows and uploading 1 large file ~150MB

**Comment by ttaylorr** [comment]
Hi @teebszet, thanks for opening this. If you're pushing to GitHub, could you send an email to `support@github.com`? They'd be more than happy to look into any networking issues you might have.
