### ISSUE TITLE
I'm new to this git lfs pls help me out thanks

### ISSUE THREAD

**Issue by gitFJUIM** [git-lfs/git-lfs#2987]
I typed this in my git bash : git lfs install
and it showed this to me 
Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal: not a git repository (or any of the parent directories): .git\n"
Git LFS initialized.
I don't know what to do then.

**Comment by ttaylorr** [comment]
Hi @gitFJUIM, thanks for opening this issue! I'd be more than happy to help you out. Can you make sure that your working directory is a Git repository before running this command?

If you could give that a shot, I think it would solve what's going on here. If the issue persists, please let me know and I'd be more than happy to re-open this issue and help continue troubleshooting!

**Comment by gitFJUIM** [comment]
Excuse me, because I'm just a newbie to this git thing, and I'm from Taiwan I'm not so sure which directory you want me to send.

**Comment by ttaylorr** [comment]
@gitFJUIM I'm sorry -- I meant to suggest that if you're running the `git lfs install` command from a terminal, that you do so from inside any Git repository, like so:

```ShellSession
$ git clone https://github.com/my/repository
$ cd repository
$ git lfs install
# ...
```

**Comment by gitFJUIM** [comment]
Thanks a lot! Very appreciate it! I will ask if I have any questions. Thank you for responding so fast and to help me!!!

**Comment by gitFJUIM** [comment]
Excuse me, @ttaylorr can I ask you something about my Unreal project pushing to git's problem?
I've push everything in my Unreal Project and the website seems to have all the folder so does github desktop, but after I clone the file the content was empty am I missing something or steps?

**Comment by ralvareza** [comment]
hello there, i'm trying to replicate this solutions but its not working for my. My result is:

$ git clone https://github.com/ralvareza/ralvareza.github.com
Cloning into 'ralvareza.github.com'...
fatal: unable to access 'https://github.com/ralvareza/ralvareza.github.com/': Failed to connect to github.com port 443: Timed out

@ttaylorr do you think I can solve it? It seems something about the proxy?  Any commet are welcome

**Comment by ttaylorr** [comment]
> $ git clone https://github.com/ralvareza/ralvareza.github.com
> Cloning into 'ralvareza.github.com'...
> fatal: unable to access 'https://github.com/ralvareza/ralvareza.github.com/': Failed to connect to github.com port 443: Timed out
>
> @ttaylorr do you think I can solve it? It seems something about the
> proxy?  Any commet are welcome

I'm sorry that you're having trouble. I think that this is the result of
a bad connection to GitHub from your network. Can you contact
support@github.com? They should be able to help pin that down.

**Comment by ralvareza** [comment]
You were right, it was all becasue of the proxy:

git config --global http.proxy http://proxyUsername:proxyPassword@proxy.server.com:port

It works for me, thanks a lot! @ttaylorr

**Comment by ttaylorr** [comment]
> You were right, it was all becasue of the proxy:

Great, I'm glad that you were able to sort out the problem. Please don't
hesitate to let us know here or elsewhere if you run into any trouble in
the future; we'd be more than happy to help out.

**Comment by bsutton** [comment]
I've just had this same issue on ubuntu 18.04.

If git lfs install needs to be run in a git repo, then can I suggest a cleaner message such.

'fatal: git lfs must be run from a git repo. Please change directories into a git repo and try again'.

Having said that, the doco I've seen online suggest that you only need to run this once and that it the applies to all repos on your system (otherwise what does the --local switch do).
If that is the case then having to run it from a specific git repo is rather counter-intuitive.
