### ISSUE TITLE
git lfs lock fails if there is a symlink in the repo's parent's path

### ISSUE THREAD

**Issue by jbstewart** [git-lfs/git-lfs#2990]
The git-lfs unlock command fails if there is a symlinked folder in the parent path of the repo.

## Steps to recreate
- `mkdir parent`
- `cd parent`
- `mkdir outer1`
- `git clone https://github.com/jbstewart/git-lfs-symlink-issue.git`
- `ln -s git-lfs-symlink-issue outer2`
- `cd outer2`
- `git lfs lock folder1/folder2/TestImage.png`

## But this works...
- `cd ../outer1/git-lfs-symlink`
- `git lfs lock folder1/folder2/TestImage.png`

### Other details
- macOS 10.13.4
- git version 2.15.1 (Apple Git-101)
- git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)

**Comment by ttaylorr** [comment]
Hi @jbstewart, thank you so much for your very detailed issue. I was able to reproduce the issue myself with a copy of your repository that I mirrored (since I cannot create locks on your copy), and have a fix incoming.

```ShellSession
$ pwd
/Users/ttaylorr/Desktop/parent/outer2

$ pwd -P
/Users/ttaylorr/Desktop/parent/git-lfs-symlink-issue

$ git lfs locks

$ git lfs lock folder1/folder2/TestImage.png
Locked folder1/folder2/TestImage.png

$ git lfs locks
folder1/folder2/TestImage.png   ttaylorr        ID:24512
```
