### ISSUE TITLE
git lfs migrate duplicates the logs

### ISSUE THREAD

**Issue by jomark-t** [git-lfs/git-lfs#2991]
Hi,

After running..

`git lfs migrate import --everything --include="*.exe"`

My branch was diverged. I treid `git pull` and the result is _fatal: refusing to merge unrelated histories_
I googled for answer and tried putting `--allow-unrelated-histories` and it behaves exactly as expected. I fixed the merge conflict and commit it and push it.

The weird thing is the logs got duplicated with the new sha1 and old sha1.

```
jtandog@N-5CG6510RNK MINGW64 ~/Desktop/WORKSPACE/00_GIT/DEMO/artifactory/VX_EMU (master)
$ git log --oneline
d4e3274 (HEAD -> master, origin/master, origin/HEAD) Merge branch 'master' of ssh://<some-awesome-link>
c772705 Edited: added cloud on image 2
9c2628b Edited: added cloud on image 2
8d55b97 Edited image 2
5f2ad3d Edited image 2
1819912 Added image 2
d33b7b6 Added image 2
eb853e1 Edited image
d4ae72c Edited image
14c8ca9 Added .lfsconfig
1199cf9 Added .lfsconfig
0322c00 Initial commit
78d54bb Initial commit

```

Please help ;(

**Comment by ttaylorr** [comment]
Hi @jomark-t, thanks for opening this issue. I think I have an idea of what's going on here: when you give `--everything` to `git lfs migrate`, it writes over all of history. Therefore, if you have pushed a previous state of history to your remote, after the migration is complete, your remote will look entirely different from your history.

In other words, you are producing a _new_ history reassembled locally that your remote does not know about.

To reconcile this, you must tell your remote to drop what it has, and instead accept the new state of the world. This is accomplished by running `git push --force --all origin`, which says "here's everything I have, and get rid of anything that is different".

What happened above is (I assume) the result of migrating and not sending the migrated history to your remote. Thus, when you `git pull --allow-unrelated-histories`, you get two histories, interleaved with one another, where one is the old state of the world, and the other is the new state.

To fix your issue, I would recommend restoring a state of the repository that was either (1) migrated and not yet pulled, or (2) not yet migrated, and either (1) running `git push --force --all origin`, or (2) re-migrating and then running `git push --force --all origin`.

Please don't hesitate to comment here if you have any further issues or questions and I'd be more than happy to help out!

**Comment by jomark-t** [comment]
Hi @ttaylorr thank you for the time reading my issue. I understand now how does `git lfs migrate` works. Thank you for this awesome tool for binary files. Maybe you can improve the documentation a little bit, not the less great job on the project!!! 👍 👍 👍 👍 👍

**Comment by jomark-t** [comment]
Hi @ttaylorr, does --include command supports multiple instances like "*.docx, *.exe". I'm trying it now but I'm not confident its doing its job. Thank you!! What does it looks like --include="*.docx, *.exe, *.hp"

**Comment by jomark-t** [comment]
Hi @ttaylorr sorry I kept bothering you, our project is ready for Artifactory but it seems I encountered some problem.

I fresh cloned the project. Added `.lfsconfig` to master and 3 other branches.
I run `git branch`

`Feature_1
Feature_2
Feature_3
* master`

 Next I run, `git lfs migrate --include="*.exe, *.pdf, *.docx, *.largefiles" --everything`

```
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (4248/4248), done
  Feature_1      643ffc4d16d738d141f7ae1f04e571d7f3ab43fa -> 4f5151fc5a8aaeaccb0790fe34b36aaa205ce17b
  Feature_2         756a543f0bdbc183b2040a884a9d961ede1d8d99 -> 550054a3f19e7a6d49f0530b2b19e533e16fac68
  Feature_3       0f756509b5fccf24f53d74a2bbb7ff9790c2670a -> cd36538a40f61e5c03e9838a19873d50133733c5
  master                27ba4717731535180fa0387b34fe500003d514c4 -> 8a02ebc9ec664e6cb1b8f7304637b779d82fe42c
migrate: Updating refs: ..., done
migrate: checkout: ..., done
```

**Comment by ttaylorr** [comment]
Hi @jomark-t, sorry that you're having trouble. Since you're not seeing any line like: "Uploading Git LFS objects ...", I think that there are one of two things going on:

1. Git LFS is not picking up these files. In which case, I'd like to examine a copy of your repository, or a repository where this example can be reproduced.
2. Git LFS is not installed (c.f., `git lfs install`) and therefore the `pre-push` hook is not running Git LFS.

**Comment by saerosV** [comment]
Hi @ttaylorr. 

I know this is an old issue, but do you know of any methods that would do the same as `git push --force --all origin`, without pushing directly to master?

Thanks in advance.

**Comment by bk2204** [comment]
Hey,

If you're wanting to push all of the LFS objects, you can do `git lfs push --all` without needing to push any of the Git data.
