### ISSUE TITLE
Running `git lfs uninstall` and then `git pull` after reaching quota is very buggy

### ISSUE THREAD

**Issue by tysonzero** [git-lfs/git-lfs#2998]
Specifically the pull dies part way through, leaving the repo in a damaged state with a bunch of uncommitted local changes. Any attempts to remove `git lfs` did not seem to help, just re-breaking the repo's state each time a pull was attempted.

Eventually we just used a different machine that had the repo in a non-bricked state to aggressively delete any and all notion of lfs from the project.

I have no intention of coming back to this software but figured I should at least report my issue. On a side note I really think git lfs should have some well documented fail safes that completely remove it from the project and/or your OS (depending on what's causing the above issues) to restore the repo into a usable state.

**Comment by ttaylorr** [comment]
Hi @tysonzero! Thanks for opening this issue, and I'm sorry that you're having trouble. The case you're experiencing is a known one and is explained by the limited agency that Git LFS has at this point in a `git pull` operation.

By the time that `git pull` invokes Git LFS, all of the _Git_ packs have been downloaded, unpacked, and are being checked out into the working copy. Git invokes Git LFS to "filter" the "clean" blobs from pointers (as they are stored in Git) to large objects (as they are stored in your working copy).

So, if Git LFS fails part of the way through, (i.e., we have checked out `N` of `M > N` objects, the remaining `M-N` objects are in a broken state (under certain circumstances)). The best that Git LFS can do in this situation is to retry the LFS object download as many times as it is configured to do before eventually giving up and leaving the repository in a dirty state.

For telling Git LFS how many times to retry/verify objects, you can look at [`git-lfs-config.5`](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn#L139-L152).

I'll note that this issue should be documented in a User Guide that I am collecting ideas for. In the meantime, we have a wiki page: "Known Limitations", which might be a suitable home for this issue.
