### ISSUE TITLE
Git LFS is disabled for this repository error

### ISSUE THREAD

**Issue by GVinkovic** [git-lfs/git-lfs#2999]
Hello,  

it looks like Git LFS might be disabled on my account, is there a way it gets re enabled?  In billing information it says I'm using 0/1GB now. I would appreciate your help with it.  
Best regards, Goran 

![image](https://user-images.githubusercontent.com/38727804/39810003-c635d54a-5383-11e8-8f3e-ae9cf4face3c.png)

![capture](https://user-images.githubusercontent.com/38727804/39810057-eed465f2-5383-11e8-9df8-8b47c480ec87.PNG)

**Comment by ttaylorr** [comment]
Hi @GVinkovic, thanks for opening this issue! I've re-enabled Git LFS support for your repository. In the future, please note that this repository is for open-source issues pertaining to Git LFS the tool, not Git LFS on GitHub. For the later, `support@github.com` would be more than happy to help.
