### ISSUE TITLE
Removing git-lfs from a repository 

### ISSUE THREAD

**Issue by krassik** [git-lfs/git-lfs#3004]
I would like to proofread the following steps to remove lfs from the repository.
I would like to know if for any reason this procedure may fail.

1. Create a local bare repository by mirroring (this is a switch on the git clone command)
2. Do: git lfs uninstall
3. Create a tree archive (lfsfiles.tar) from the list of files on a working branch from cloned repository. 
4. Clone the repository from 1) then untar the lfsfiles.tar file in the working tree of the master branch and commit the changes.
5. Push the master branch from 4) into 1) 
6. Mirror 1) to a server for everyone to use

**Comment by krassik** [comment]
I did only see errors like on step 6

! [remote rejected]       refs/pull/997/head -> refs/pull/997/head (deny updating a hidden ref)
! [remote rejected]       refs/pull/998/head -> refs/pull/998/head (deny updating a hidden ref)
! [remote rejected]       refs/pull/999/head -> refs/pull/999/head (deny updating a hidden ref)
error: failed to push some refs to <repo location>

Else the resulting project behaves as expected.

**Comment by ttaylorr** [comment]
Hi @krassik, thanks for opening this issue. I have one specific question, but I wanted to chat about your general approach, as well. The method above is inherently "shallow", or in other words it does not "fix" history using Git LFS, it only creates new history on top of it (step (4)), so checkouts of any previous revisions under Git LFS will _not_ include large files, only pointer representations.

(This seems like a good case for `git lfs migrate --no-rewrite`, as discussed previously.)

> 3. Create a tree archive (lfsfiles.tar) from the list of files on a working branch from cloned repository.

I am confused by what you mean when using the phrase "working branch from cloned respository". In step (1), you said that the repository was both bare and mirrored. There is no concept of a checkout under a bare repository, unless I am missing something critical. Creating an archive of the branch checked out in your working copy requires that the repository be non-bare.

Steps 4-6 seem reasonable.
