### ISSUE TITLE
info/lfs/objects/batch not found

### ISSUE THREAD

**Issue by mdurian** [git-lfs/git-lfs#3014]
I'm brand new to git and lfs and am encountering a problem trying to push lfs files to the remote repository.

I've created a local repository and run 'git lfs install' in it. I've lfs tracked some file types, added files and am able to commit successfully. I've also created a remote, bare repository and run 'git lfs install' in it. I've then added a reference to the remote repository using 'git remote add origin https://url'.

I encounter an error when I try to push. Specifically, the error is that '.../info/lfs/objects/batch' does not exist. Sure enough, if I check the filesystem, the '.../info/lfs' directory isn't there. I'm sure I missed some obvious step that would create the directory, but my google searches haven't been fruitful.

Here's my 'git lfs env':
```
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)
git version 2.15.1 (Apple Git-101)

Endpoint=https://my_host/git/my_repo.git/info/lfs (auth=basic)
LocalWorkingDir=/path_to_my_repo
LocalGitDir=/path_to_my_repo/.git
LocalGitStorageDir=/path_to_my_repo/.git
LocalMediaDir=/path_to_my_repo/.git/lfs/objects
LocalReferenceDir=
TempDir=/path_to_my_repo/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/path_to_my_repo/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

And here are some excerpts from a 'git lfs push':
```
Username for 'https://my_host': durian
Password for 'https://durian@my_host': 
Username for 'https://my_host': durian
Password for 'https://durian@my_host': 
> POST /git/my_repo.git/info/lfs/objects/batch HTTP/1.1
> Host: my_host
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 6160
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)
> 
{"operation":"upload","objects":[{"oid":"84fcd39270dbe34ca49a5775ddd02d4c5c319bfe4e2fd66a894dc662c7b6167e","size":1365285}.....,"ref":{"name":"refs/heads/master"}}
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Cache-Control: no-cache, max-age=0, must-revalidate
< Date: Mon, 21 May 2018 17:22:15 GMT
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Server: Apache/2.4.33 (FreeBSD) PHP/5.6.36 mod_wsgi/4.6.4 Python/3.6 OpenSSL/1.0.2k-freebsd
< 
batch response: Repository or object not found: https://my_host/git/my_repo.git/info/lfs/objects/batch
Check that it exists and that you have proper access to it
```

Thanks,
mike

**Comment by ttaylorr** [comment]
👋 @mdurian, thanks for opening this issue and sorry that you're having trouble. Git LFS requires an additional set of specifications to be met that aren't provided by `git-daemon`. If you're running locally (i.e., not with a provider who supports Git LFS) then you have to make sure that you're running a Git LFS server that supports the latest specification

(See \[[1](https://github.com/git-lfs/lfs-test-server)\], \[[2](https://github.com/git-lfs/git-lfs/wiki/Implementations)\] for more).
