### ISSUE TITLE
Error: Failed to call git rev-parse

### ISSUE THREAD

**Issue by EnziinSystem** [git-lfs/git-lfs#3018]
I run commands on Ubuntu 18.04

```
wget https://github.com/git-lfs/git-lfs/releases/download/v2.4.1/git-lfs-linux-amd64-2.4.1.tar.gz

tar -xzvf git-lfs-linux-amd64-2.4.1.tar.gz

cd git-lfs-2.4.1

chmod +x install.sh

./install.sh
```

And I get error

`Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal: not a git repository (or any of the parent directories): .git\n"`

**Comment by ttaylorr** [comment]
Hi, some discussion is ongoing about how to fix this in #3013. For now, you can modify `./install.sh` to change `git lfs install` to `git lfs install --skip-repo`.
