### ISSUE TITLE
SHA-256 checksums mismatch

### ISSUE THREAD

**Issue by dscho** [git-lfs/git-lfs#3020]
The releases list the Windows package as having these checksums:

```
git-lfs-windows-386-2.4.1.zip
bb46dbf7d8976f39b2afaf6357b11cb08b643bac53ac4861d5e970545bdd6ec4

git-lfs-windows-amd64-2.4.1.zip
5a1f355e5df457c7dabbe5577fd49b8284df8b09bd366b63e4501f3a31e84446
```

However, downloading them and then calculating the checksums results in this:

```
887e9927abe79f8c94fe2464578929a8607084b641fdc07f39a4088e93d1a089 *git-lfs-windows-386-2.4.1.zip
ebbab07348dbe71a5c20bfbdfafe4dbbafc8deacea6e6bf4143556721c860821 *git-lfs-windows-amd64-2.4.1.zip
```

That's not even close. What gives? Is the checksumming for Windows packages broken (again)?

**Comment by quincunx** [comment]
@ttaylorr could you clarify, please?

**Comment by ttaylorr** [comment]
@dscho thanks for letting me know, I've updated the release to include the correct signatures for the affected files (both `git-lfs-windows-{amd64,386}-2.4.1.zip` were broken, but the installer was not). Signing the Windows binaries is a manual section of the release process, and is therefore prone to error. I would happily take advice on how to automate this process.

**Comment by dscho** [comment]
Thanks!

> Signing the Windows binaries is a manual section of the release process, and is therefore prone to error. I would happily take advice on how to automate this process.

If I knew more about that process, I could probably suggest how to automate it.

FWIW in Git for Windows, I use [this part of a script](https://github.com/git-for-windows/build-extra/blob/e0012a9aff953dcf7083ebaa7e6734ada12426cf/please.sh#L3824-L3838) to automate this. More automation, less work, less errors ;-)
