### ISSUE TITLE
GitHub Desktop issue "batch response: Git LFS is disabled for this repository"

### ISSUE THREAD

**Issue by MidnightTeam018** [git-lfs/git-lfs#3038]
Hi, I'm having this issue: "batch response: Git LFS is disabled for this repository" every time I try to publish my Unreal Project. How can I fix this?

**Comment by ttaylorr** [comment]
Hi, since this is a repository for supporting Git LFS (and not Git LFS at GitHub), please send this note to `support@github.com`, and we would be more than happy to help there.
