### ISSUE TITLE
github.com LFS error: 'batch requested: missing protocol'

### ISSUE THREAD

**Issue by lauralwd** [git-lfs/git-lfs#3041]
It seems I have some trouble with LFS for a private repository. Previous issues like  #2945 have not helped me to complete trouble shoot this.

I have a private repository on github.com, it is an early stage simple project without any branches and I am the only collaborator for now. Recently I added the LFS package on my local computer and follow the instructions on https://git-lfs.github.com/  

However, when I want to push my changes to github and github lfs, I get the following error

```
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https:lauralwd/metagenomicspractical.git/info/lfs.locksverify false
batch request: missing protocol: "https:lauralwd/metagenomicspractical.git/info/lfs"                     
error: failed to push some refs to 'git:lauralwd/metagenomicspractical.git'
```

In issue #2945, the output of  `git remote -v ` was requested: 

```
origin	git:lauralwd/metagenomicspractical.git (fetch)
origin	git:lauralwd/metagenomicspractical.git (push)
```
Then issue #2945 points me to #1053,  which seems not to apply to my problem.

Any thoughts are much appreciated. 

Extra the output of ` git lfs env` 
```git-lfs/2.4.2 (GitHub; linux amd64; go 1.8.3)
git version 2.17.0

Endpoint=https:lauralwd/metagenomicspractical.git/info/lfs (auth=none)
LocalWorkingDir=/home/laura/gitprojects/metagenomicspractical
LocalGitDir=/home/laura/gitprojects/metagenomicspractical/.git
LocalGitStorageDir=/home/laura/gitprojects/metagenomicspractical/.git
LocalMediaDir=/home/laura/gitprojects/metagenomicspractical/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/laura/gitprojects/metagenomicspractical/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/laura/gitprojects/metagenomicspractical/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by larsxschneider** [comment]
👋 @lauralwd ! It looks like as if your Git remote is a bit off. The Git remote tells your local Git client where to find the right server for the repository. The following command in your Git repo should fix your remote:
```
git remote set-url origin https://github.com/lauralwd/metagenomicspractical.git
```
Afterwards Git LFS should work as expected 👍

**Comment by lauralwd** [comment]
Thanks for your tip @larsxschneider . Unfortunately it was not the solution for me, but it pointed me to the actual problem. I work with git over SSH, and git LFS does not support SSH (yet). See #1044. Hence the `missing protocol` error message now makes sense in hindsight.

**Comment by lauralwd** [comment]
Since both issues of a more meaningful error message #1053 and SSH connectivity #1044 are both existing I will close this issue.

**Comment by larsxschneider** [comment]
Hmm. Git LFS indeed does not work over SSH. But this should generally be no problem because Git LFS will negotiate a secret token via SSH and then use that token to establish a HTTPS connection.

In other words: It should just work ™️ 😄 ... unless there is a bug of course.

If you are still interested, can you try to set this SSH remote and try again?
```
git remote set-url origin git@github.com:lauralwd/metagenomicspractical.git
```

**Comment by ttaylorr** [comment]
> If you are still interested, can you try to set this SSH remote and try again?
> 
> ```
> git remote set-url origin git@github.com:lauralwd/metagenomicspractical.git
> ```

I agree that this is the right way to go: the SSH remote URL that you posted in the original body of this issue is not one that Git LFS will recognize, whereas the one that @larsxschneider posted above is,.

**Comment by spx520** [comment]
PLS install git-lfs v2.5.1

**Comment by Ckandzy** [comment]
only support https? 
Local protocol is also failed.
![tim 20190107145354](https://user-images.githubusercontent.com/18118922/50753242-1e06e300-128c-11e9-856f-c96175f8f77f.png)

**Comment by bk2204** [comment]
Git LFS doesn't currently support cloning from local clones (see #3073 for more details). This error message is due to the fact that we can't resolve your file URL into an HTTP(S) endpoint to make connections against.

**Comment by christian-schlichtherle** [comment]
@bk2204 , thanks for explanation - I was just hit by this bug.

**Comment by builder-main** [comment]
> Git LFS doesn't currently support cloning from local clones (see #3073 for more details). This error message is due to the fact that we can't resolve your file URL into an HTTP(S) endpoint to make connections against.

`LFS error: 'batch requested: missing protocol'`

Same error in my case, wanting to test some local cloning, but does not work with LFS. 
Though to still try some local experimentations LFS can be deactivated : https://github.com/git-lfs/git-lfs/issues/911#issuecomment-169998792

**Comment by bk2204** [comment]
We do now support cloning from file URLs, but you require a suitably new version (2.10.0 and newer for raw paths).

**Comment by skarmesin** [comment]
I'm still seeing a "missing protocol" error with 2.17.1 on Ubuntu, and it happens when using either a file:// URL or directly from the name of the local directory. 

Just like a poster above, I'm planning to push this to a remote repository but wanted to test it first. 

If it matters, this is a large and old repository which I'm converted from subversion. I was able to do the 'git svn' convert without issue, then did the steps to record binaries like executables using LFS

**Comment by bk2204** [comment]
Hey,

The version of Git you're using may be 2.17.1, but Git LFS has never released a version with that version number.  You'll probably wantt o see the version of Git LFS you're using with `git lfs version`.

**Comment by skarmesin** [comment]
Ah, I misunderstood. I'll upgrade git-lfs. Looks like I'll need to do it by hand since `apt` says I'm at the latest it has available at 2.3.4-1

**Comment by bk2204** [comment]
We offer APT repositories you can use linked from the README.

**Comment by skarmesin** [comment]
Yes I see that now. Very easy to use, thank you!

**Comment by Radon8472** [comment]
I got the same error, and I noticed that the reason for me was the name of the remote.

As https://github.com/git-lfs/git-lfs/issues/1053 says, currently git lfs has problems with remote names that are different from `origin`,  maybe this could help so solve the problem for some people.
