### ISSUE TITLE
git-lfs performance without objects

### ISSUE THREAD

**Issue by pimjansen** [git-lfs/git-lfs#3042]
Hey,

I am not using any LFS objects for my repo but due a generic setup git-lfs install runs initially in the dev box setup to ensure when a repo does it is initialized.

The problem now is that when i have a repo with 0 tracked objects and also an empty tmp dir for LFS, the complete GIT command hangs. When i now run `git checkout <myfile>` i see a git-lfs process spiking which consumes all my available CPUs (6 of them) at 100% for about 20 seconds. When git-lfs is uninstalled the checkout command replies within a second.

In my .gitattributes there is also no tracking on any git-lfs files so i am a bit lost in where this insane CPU consumption is coming from. I just updated to the latest 2.4.2 on OSX (via brew) which does exactly the same.

**Comment by larsxschneider** [comment]
👋 @pimjansen ! I am sorry about your trouble with Git LFS. Can you run the following command and share the output?
```
GIT_TRACE=1 git checkout <myfile>
```

I suspect this will reveal that the `git-lfs post-checkout` command runs for 20 seconds. Does your repo contain *a lot* of directories? Then I would further suspect that the command searches for `.gitattribute` files in your tree. Can you also run the following command and share the results:
```
GIT_TRACE=1 git -c lfs.SetLockableReadonly=false checkout amake.bat
```
This config disables the `.gitattribute` search as a side effect. If this setting makes the command faster, then there should be way to fix the problem.

**Comment by pimjansen** [comment]
@larsxschneider you are correct, the trace is scanning my full repo. I wont add the full dump but below a snippet of the output
```
$ GIT_TRACE=1 git checkout README.md 
19:06:32.044738 git.c:344               trace: built-in: git checkout README.md
19:06:32.066164 run-command.c:640       trace: run_command: .git/hooks/post-checkout 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 0
19:06:32.072721 git.c:576               trace: exec: git-lfs post-checkout 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 0
19:06:32.073256 run-command.c:640       trace: run_command: git-lfs post-checkout 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 0
19:06:32.098709 trace git-lfs: exec: git 'version'
19:06:32.113859 trace git-lfs: exec: git 'config' '-l'
19:06:32.119295 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
19:06:32.124823 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
19:06:32.124853 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
19:06:32.124910 trace git-lfs: filepathfilter: rejecting "baseline-ose" via []
19:06:32.124916 trace git-lfs: filepathfilter: accepting "baseline-ose"
19:06:32.124962 trace git-lfs: filepathfilter: rewrite ".env" as "**/.env/**"
19:06:32.124976 trace git-lfs: filepathfilter: rewrite "node_modules/" as "**/node_modules/**"
19:06:32.124989 trace git-lfs: filepathfilter: rewrite "skin/frontend/omnius/default/dist" as "**/skin/frontend/omnius/default/dist/**"
19:06:32.125031 trace git-lfs: filepathfilter: rewrite "dist/" as "**/dist/**"
...
19:07:19.995325 trace git-lfs: filepathfilter: accepting "dev/tests/functional/tests/app/Mage/Catalog/Test/Constraint/AssertCategoryForm.php"
19:07:20.000229 trace git-lfs: filepathfilter: accepting "dev/tests/functional/tests/app/Mage/Adminhtml/Test/Block/Catalog/Product/Edit/Tab/Crosssell"
19:07:20.000407 trace git-lfs: filepathfilter: rejecting "dev/tests/functional/tests/app/Mage/Adminhtml/Test/Block/Catalog/Product/Edit/Tab/Crosssell/Grid.php" via []
19:07:20.013194 trace git-lfs: filepathfilter: accepting "dev/tests/functional/tests/app/Mage/Adminhtml/Test/Block/Catalog/Product/Edit/Tab/Configurable/QuickCreation.xml"
```

This is the .gitattributes file we have:
```
$ cat .gitattributes 
# normalize text files to use lf
text eol=lf
# except these which we want crlf
*.txt eol=crlf
*.svg text=auto
*.png binary
*.jpg binary
*.gif binary
*.eot binary
*.ttf binary
*.woff binary
*.gz binary
*.zip binary
```

Your second command was also executed fast:
```
(19:09:53)[Pims-MacBook-Pro] ~/Repos/baseline-ose [develop]
$ GIT_TRACE=1 git -c lfs.SetLockableReadonly=false checkout README.md 
19:09:59.687157 git.c:344               trace: built-in: git checkout README.md
19:09:59.697957 run-command.c:640       trace: run_command: .git/hooks/post-checkout 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 0
19:09:59.705080 git.c:576               trace: exec: git-lfs post-checkout 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 0
19:09:59.705571 run-command.c:640       trace: run_command: git-lfs post-checkout 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 5d7320140b42ad0e26a42bf2f9728d5aad2ddc61 0
19:09:59.724488 trace git-lfs: exec: git 'version'
19:09:59.737368 trace git-lfs: exec: git 'config' '-l'
```

Curious about a structural solution where i do not expect LFS to scan my repo when there is no tracked file in my gitattributes ofcourse. I do expect it to run like i have in other repos as:
```
/files/mysql/seed.sql.gz filter=lfs diff=lfs merge=lfs -text
```

Thanks a lot!

**Comment by larsxschneider** [comment]
Thanks for the confirmation. If you do not use the Git LFS locking feature, then you can set this global config. Afterwards all your Git LFS commands should be fast:
```
git config --global lfs.SetLockableReadonly false
```

@ttaylorr : Can/should we use this issue to continue the [discussion](https://github.com/git-lfs/git-lfs/pull/1822#discussion_r187200507) or create a new one?

**Comment by pimjansen** [comment]
@larsxschneider thats for the solution. So overall the problem is that `git-lfs` will do a full directory scan to find all available `.gitattributes` files to determine the lfs context?

**Comment by ttaylorr** [comment]
> I think we need to optimize the `.gitattributes` search. This would make the problem go away.

I agree, and thanks for diving in. I'm also interested to see if there is a pathological pattern at play here that is taking `git-lfs/wildmatch` a long time to process. @pimjansen: is your repository open-source?

**Comment by pimjansen** [comment]
@ttaylorr no it is not. But overall it is just a repo with a lot of folders. I think you will notice this on some of the big php frameworks for example that use psr4 namespacing

**Comment by pimjansen** [comment]
I just did some more testing and we now even had to set this setting in our Jenkins-slave where the git checkout took more then 10min to finish. So i think its a pretty urgent issue for git-lfs.

Why the decision to go for a setting in .gitattributes that are stacked? Wont a .gitlfs config on the root do for example without making it recursive?

**Comment by ttaylorr** [comment]
> Why the decision to go for a setting in .gitattributes that are stacked? Wont a .gitlfs config on the root do for example without making it recursive?

It would, but there is a possibility that later `.gitattributes` deeper in the tree might be modified, too.

@larsxschneider what do you think about storing a cache of trees that we have already seen (and therefore don't need to traverse to determine the .gitattributes contents for them)?
