### ISSUE TITLE
git lfs clone aborts with "Skipping object checkout, Git LFS is not installed"

### ISSUE THREAD

**Issue by DavidGriffith** [git-lfs/git-lfs#3048]
Tried to do ```git lfs clone https://github.com/gewtnet/tops10-disks```.  This proceeded to download about 487 megabytes of stuff into ```.git/lfs``` whereupon it aborted with ```Skipping object checkout, Git LFS is not installed.```.  But git LFS **IS** in fact installed.  ```git lfs pull``` also responds with the complaint that Git LFS isn't installed and does nothing else.

**Comment by DavidGriffith** [comment]
Yes, it does.  The instructions I was following didn't mention that step.

**Comment by ttaylorr** [comment]
Hi @DavidGriffith, I'm glad that you were able to resolve this issue. @robobenklein: thanks for stepping in! My apologies for the delayed response, I was out of the office last week and have been catching up on email since.
 
Please don't hesitate to let me know if there is anything else that I can help you out with in the future by sending me a ping here or elsewhere. Thanks!

**Comment by bomgar** [comment]
It would be great to mention `git lfs install` in the error message

**Comment by rkost** [comment]
Another way would be modifying the message to be less ambiguous: `Git LFS is not installed in this repository.` I honestly thought git would not find my LFS extension installation on my system (to be fair, I am completely new to LFS and just came across a repo that uses it).

**Comment by suraj-mathew** [comment]
Another observation i found is that, if we run **git lfs install** using a root user, and if we try to use it from another user (say X) on the same machine, it wont work. User X will end up in the getting the error message "Git LFS is not installed"

To overcome this issue, we need to 

- either run **git lfs install** again from the respective user's terminal (here X's)
- or run **git lfs install --system** from the root user initially

**Comment by Talgin** [comment]
> Does running `git lfs install` again after cloning fix the issue? It's probably talking about the repo-specific installation.

For newbies who met this problem for the first time the order of operation would look like:
- Download and install Git LFS (git-lfs.com)
- Go to your cloned git repo and inside it run `git lfs install`
- Then run `git pull`
- Now you can check the sizes of your files which should be the same as in your git repo (top left corner before the words "Stored with Git LFS").

**Comment by thecadams** [comment]
> It would be great to mention git lfs install in the error message

Hello folks. 5 years later and this is still true.
