### ISSUE TITLE
‘migrate’ subcommand fails with ‘Couldn't find remote ref’

### ISSUE THREAD

**Issue by fedde-s** [git-lfs/git-lfs#3052]
I'm working on a branch that seems to have several un-migrated files, as I received an unhelpful message that they should have been pointers when I switched to the branch. When I try to fix this by running `git lfs migrate info` and `git lfs migrate import`, it fails with an error message like the following:

```Console
Error running /path/to/git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'fetch' 'origin' 'upstream': 'fatal: Couldn't find remote ref upstream' 'exit status 128'
```

…as if it's trying to fetch one of my remote repositories (`upstream`) as a ref inside another remote repository (`origin`). Am I doing something wrong here?

**Comment by fedde-s** [comment]
For completeness: the unhelpful message I mentioned in the first sentence is not my main issue, as that's already being addressed in #2910.

**Comment by fedde-s** [comment]
To me it looks like git-lfs-migrate simply contains a bug in which it omits the `--multiple` flag to git-fetch, though.

**Comment by fedde-s** [comment]
See [my comment](https://github.com/git-lfs/git-lfs/commit/36f3c951717772d2d91b0c91449e49222126e1ef#r29345999) on the code that calls git-fetch in this case.

**Comment by fedde-s** [comment]
Thanks writing a fix! And sorry for bypassing your good practice of providing the parameters in which I observed the issue. It can be very annoying to have someone (who doesn't know the project or even the language it's written in) insist that they already know the cause… But I'm glad I you did have enough information to write a test in this case 🙂

**Comment by ttaylorr** [comment]
> Thanks writing a fix! And sorry for bypassing your good practice of providing the parameters in which I observed the issue.

Not to worry; thanks for letting me know! Don't hesitate to ping me here or elsewhere if you run into trouble in the future.
