### ISSUE TITLE
proxy environment variables override git config (should be the other way around)

### ISSUE THREAD

**Issue by kenyon** [git-lfs/git-lfs#3060]
In Git, the configuration files override environment variables for HTTP proxy configuration, which is how it should be. But Git LFS 2.4.2 is the other way around: environment variables are overriding the git configuration. This was apparently implemented properly in #1358 but was broken with the lfsapi creation, #1787. Please fix so that git config http.proxy overrides environment variables. Thanks.

**Comment by ttaylorr** [comment]
Hi @kenyon, thanks for letting us know. I opened https://github.com/git-lfs/git-lfs/pull/3062 to fix this and restore it to the original behavior released in https://github.com/git-lfs/git-lfs/pull/1358.
