### ISSUE TITLE
`git lfs status` fails if you run it from a subdirectory in the repository

### ISSUE THREAD

**Issue by nuxi** [git-lfs/git-lfs#3071]
`git lfs status` seems to assume it is only run from the top of the repository. If you have unstaged files and run it from a subdirectory you will get a "file not found" error in the "Git LFS objects not staged for commit" section.

1. Set up a git repo and have git-lfs track a file
2. Commit everything
3. Modify the file (do not run `git add` yet!)
4. Run `git lfs status` from anywhere other than the top of the repository

I can reproduce this with git-lfs 2.3.4 + git 2.13.5 and git-lfs 2.4.2 + git 2.17.1

```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../binary

no changes added to commit (use "git add" and/or "git commit -a")
$ git lfs status
On branch master

Git LFS objects to be committed:


Git LFS objects not staged for commit:

open binary: no such file or directory
```

If you run it from the top of the repository its fine:
```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   binary

no changes added to commit (use "git add" and/or "git commit -a")
$ git lfs status
On branch master

Git LFS objects to be committed:


Git LFS objects not staged for commit:

	binary (LFS: 434728a -> File: 4487e24)

```

If you stage the file for commit its fine:
```
$ git add ../binary 
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   ../binary

$ git lfs status
On branch master

Git LFS objects to be committed:

	binary (LFS: 434728a -> LFS: 4487e24)

Git LFS objects not staged for commit:


```

This was a test repository for demonstrating the bug, so the `.gitattributes` file is just the one entry from running `git lfs track binary`:
```
$ cat .gitattributes 
binary filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment]
Hi @nuxi, thanks for opening this. I think that I have a fix ready in https://github.com/git-lfs/git-lfs/pull/3080.
