### ISSUE TITLE
Undocumented behaviour change between 2.3.4 → 2.4.x

### ISSUE THREAD

**Issue by goodtune** [git-lfs/git-lfs#3072]
A recipe I was previously using to selectively fetch objects from the remote LFS server has broken under 2.4.

The documentation states that patterns provided through the `-I` switch will overload the `lfs.fetchinclude` configuration for the single execution. I am identifying the paths I wish to retrieve using our necessary logic, so for example:

```
git lfs fetch -I bin/thing/here,bin/other/thang/is/here
```

When running with `GIT_TRACE=1` set, I now observe the following output which did not previously exist.

```
10:04:30.797796 trace git-lfs: filepathfilter: rewrite "bin/thing/here" as "**/bin/thing/here/**"
10:04:30.797844 trace git-lfs: filepathfilter: rewrite "bin/other/thang/is/here" as "**/bin/other/thang/is/here/**"
```

As a result the two files I want, in my confected example, aren't being retrieved as they don't match the pattern.

It [appears that literal strings will now always receive this treatment](https://github.com/git-lfs/git-lfs/blob/v2.4.1/filepathfilter/filepathfilter.go#L116-L141), and that is entirely unexpected behaviour in my opinion. If I have gone to the trouble to provide you with an exact path, why would you ever modify it?

**Comment by goodtune** [comment]
My interim solution is to be less explicit and munge the preprocessor output to result in:

```
git lfs fetch -I /bin/thing/*,/bin/other/thang/is/*
```

That is sub-optimal though because now I may end up downloading `bin/other/thang/is/reallybigthingidonotwant` as a result.

**Comment by ttaylorr** [comment]
Hi @goodtune, thanks for opening this issue, and leaving such detailed notes for me to read through. 

The `filepathfilter` changes are always tricky to get right, since we replaced the underlying engine in v2.4.0, and there are lots of things to get right and wrong when attempting to match the behavior in previous versions.

I patched this up in https://github.com/git-lfs/git-lfs/pull/3081, which should do the right thing. Can you give it a whirl to make sure that it matches your expectations? Thanks!

**Comment by goodtune** [comment]
Thanks @ttaylorr - are you able to provide build artifacts you want me to test?

**Comment by ttaylorr** [comment]
> are you able to provide build artifacts you want me to test?

Sure, how about these:

[git-lfs-darwin-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/2125853/git-lfs-darwin-386-2.4.0.tar.gz)
[git-lfs-darwin-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/2125854/git-lfs-darwin-amd64-2.4.0.tar.gz)
[git-lfs-freebsd-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/2125855/git-lfs-freebsd-386-2.4.0.tar.gz)
[git-lfs-freebsd-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/2125856/git-lfs-freebsd-amd64-2.4.0.tar.gz)
[git-lfs-linux-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/2125857/git-lfs-linux-386-2.4.0.tar.gz)
[git-lfs-linux-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/2125858/git-lfs-linux-amd64-2.4.0.tar.gz)
[git-lfs-windows-386-2.4.0.zip](https://github.com/git-lfs/git-lfs/files/2125859/git-lfs-windows-386-2.4.0.zip)
[git-lfs-windows-amd64-2.4.0.zip](https://github.com/git-lfs/git-lfs/files/2125860/git-lfs-windows-amd64-2.4.0.zip)

**Comment by ttaylorr** [comment]
Hi @goodtune, I had another chance to look at this issue today after letting it cook over the weekend. I tried to run my test on a modified copy of the v2.3.4 tree, and found that the behavior change you mention isn't a behavior change at all: it's always behaved like this:

```
~/g/git-lfs (v2.3.4!) $ ./test/test-pull.sh
compile git-lfs for ./test/test-pull.sh
commands/mancontent_gen.go
Using go1.10.3
Git LFS: /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/bin/git-lfs
git-lfs/2.3.4 (GitHub; darwin amd64; go 1.10.3; git 9757f3f7)
git version 2.18.0                                                                                                                                                     Git LFS initialized.

HOME: /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/home                                                                                               TMP: /private/var/folders/23/1bpchtnj5y71fdyttct74cs00000gn/T/git-lfs_TEMP.XXXXXX.pXz0DZdx
CREDS: /Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/creds
lfstest-gitserver:
  LFSTEST_URL=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/url
  LFSTEST_SSL_URL=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/sslurl
  LFSTEST_CLIENT_CERT_URL=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/clientcerturl (https://127.0.0.1:59109)
  LFSTEST_CERT=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/cert
  LFSTEST_CLIENT_CERT=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/client.crt
  LFSTEST_CLIENT_KEY=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote/client.key
  LFSTEST_DIR=/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/test/remote
GIT:
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge -- %f
filter.lfs.process git-lfs filter-process
filter.lfs.required true
credential.usehttppath true
credential.helper lfstest
user.name Git LFS Tests
user.email git-lfs@example.com

test: pull (literal --include) ...                                 FAILED
```

With the attached diff:

```diff
diff --git a/test/test-pull.sh b/test/test-pull.sh
index 293a8fde..63a4b665 100755
--- a/test/test-pull.sh
+++ b/test/test-pull.sh
@@ -2,6 +2,42 @@
 
 . "test/testlib.sh"
 
+begin_test "pull (literal --include)"
+(
+  set -e
+
+  reponame="pull-include-literal"
+  setup_remote_repo "$reponame"
+  clone_repo "$reponame" "$reponame"
+
+  mkdir -p a/b/c 2/a/b/c
+  printf "d" > a/b/c/d.dat
+  printf "d" > 2/a/b/c/d.dat
+
+  git lfs track 'a/b/c/*.dat'
+  git lfs track '2/a/b/c/*.dat'
+  git add .gitattributes
+  git add a/b/c/d.dat
+  git add 2/a/b/c/d.dat
+
+  git commit -m "initial commit"
+  git push origin master
+
+  cd ..
+  rm -rf "$reponame"
+  GIT_LFS_SKIP_SMUDGE=1 git clone $GITSERVER/$reponame
+
+  cd "$reponame"
+
+  git lfs pull --include=a/b/c/d.dat
+
+  [ "d" = "$(cat a/b/c/d.dat)" ]
+  [ "d" != "$(cat 2/a/b/c/d.dat)" ]
+)
+end_test
+
+exit 0
+
 begin_test "pull"
 (
   set -e
```

So, my inclination is to let this behavior live on until v3.0.0. I am thinking that this is the right way to go, since (even though this is behavior doesn't seem like the _right_ thing to do) I don't want to break any backwards compatibility for users that are depending on this behaving the way that it does.
