### ISSUE TITLE
pulling from local repository

### ISSUE THREAD

**Issue by MacroUniverse** [git-lfs/git-lfs#3073]
Will LFS support pulling from local repository in the future? I recently found that git LFS is a great tool for backing up my large folder, it works like Apple's Time Machine. However, I need to pull the latest commit to other backups to update them. I would like to support you financially if you develop this feature.

**Comment by ttaylorr** [comment]
Hi @MacroUniverse, thanks for asking this question. Right now, we don't support this feature and do not plan to in the near future. That said, here are two quick thoughts:

1. If any contributor would like this feature and has the time to commit to adding such a feature to Git LFS, I (or anyone else on @git-lfs/core) would be more than happy to mentor them through a pull request or two.

2. You can use the `lfs.storage` configuration option (described in `git-lfs-config(5)`) in the meantime to share a local cache of LFS objects between `>=1` repositories.

**Comment by realtime-neil** [comment]
@ttaylorr what is the workaround you allude to with your mention of `lfs.storage` config option? Could you please demonstrate such a workaround for a `file:///` remote URI?

**Comment by ttaylorr** [comment]
@realtime-neil The `lfs.storage` option allows you to share the local storage between two repositories, but won't allow you to pull between one another. In other words, there does not presently exist a "workaround" for pulling from a `file://` URL.

The `lfs.storage` option is documented in more depth in the `git-lfs-config(5)` manual page.
