### ISSUE TITLE
brew install git-lfs not working on macOS 10.14 (mojave)

### ISSUE THREAD

**Issue by mgcrea** [git-lfs/git-lfs#3079]
I'm encountering an issue with the `ronn` gem while trying to install `git-lfs` from homebrew on a Developer beta of macOS 10.14 (mojave):

```
$ brew install git-lfs
==> Downloading https://github.com/git-lfs/git-lfs/archive/v2.4.2.tar.gz
Already downloaded: /Users/olivier/Library/Caches/Homebrew/git-lfs-2.4.2.tar.gz
==> gem install ronn
Last 15 lines from /Users/olivier/Library/Logs/Homebrew/git-lfs/01.gem:
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
	from extconf.rb:5:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /private/tmp/git-lfs-20180621-7001-1ect0wh/git-lfs-2.4.2/gem_home/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /private/tmp/git-lfs-20180621-7001-1ect0wh/git-lfs-2.4.2/gem_home/gems/rdiscount-2.2.0.1 for inspection.
Results logged to /private/tmp/git-lfs-20180621-7001-1ect0wh/git-lfs-2.4.2/gem_home/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1/gem_make.out

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by ttaylorr** [comment]
HI @mgcrea, thanks for opening this issue. I think that this error is coming from trying to install the `ronn` gem, which is something that we depend upon to install Git LFS. Unfortunately, it appears that there's some sort of issue with installing `ronn` on macOS Mojave.

This repository also does not offer support for pre-release versions of macOS, so I am going to close this issue for now. Please let me know if this is still an issue when macOS Mojave is generally available, and I'd be happy to dig in. Thanks!

**Comment by ftomassetti** [comment]
Still an issue

**Comment by bk2204** [comment]
Hey, @ftomassetti, could you provide the full command you're running and the output you're seeing?  I built and installed git-lfs from Homebrew both yesterday and today, and it appears to work for me, so I'm interested in seeing more information about the error.

**Comment by ttaylorr** [comment]
Hi @ftomassetti, since this has been quiet for a little while, I am going to (optimistically) assume that all has since been resolved. If that's not the case, please don't hesitate to either comment here, or raise an issue upstream with Homebrew (whichever you deem to be more appropriate.) Thanks!
