### ISSUE TITLE
Is it possible to configure different URLs for push and pull?

### ISSUE THREAD

**Issue by vaburov** [git-lfs/git-lfs#3086]
I know, there was a similar question (https://github.com/git-lfs/git-lfs/issues/1647), but mine is different. 

Is it possible to configure different push and fetch URLs for git-lfs in .lfsconfig just like remotes for git?

I am going to use git-lfs with Artifactory which also supports a replication of the repository to remote sites + I have a global balancing mechanism which allows finding the closest site with unified URL. 
It should work fine for fetches: user has a single site-agnostic URL, global balancing redirect to the closest site and that's it. The problem is that for pushes user has to use site-specific URL (since replications are read-only). I.e. URL's for push and pull should be different in my case. 

Thanks!

**Comment by ttaylorr** [comment]
Hi @vaburov, thanks for asking. You can use the following two options in your `.lfsconfig` file:

```
* `lfs.url` / `remote.<remote>.lfsurl`

  The url used to call the Git LFS remote API. Default blank (derive from clone
  URL).

* `lfs.pushurl` / `remote.<remote>.lfspushurl`

  The url used to call the Git LFS remote API when pushing. Default blank (derive
  from either LFS non-push urls or clone url).
```

And you can read more about these options from `git lfs help config`.
