### ISSUE TITLE
cannot push commit after git lfs install

### ISSUE THREAD

**Issue by ousia** [git-lfs/git-lfs#3088]
I have been using Git LFS for two projects without problems.

I only followed steps 2 and 3 from the [website](https://git-lfs.github.com/).

Today, I realized that I had to run `git lfs install`.

After that, I added which files I wanted to track and I added `.gitattributes`. I committed the changes with some code for _Jekyll_.

`git push` prompted four times for my password (and twice for my username [as stated in #2894]), but All I got was:

```
$ git push
WARNING: Authentication error: Authentication required: Access
forbidden. Check your access level.
batch response: Access forbidden. Check your access level.

error: failed to push some refs to 'https://....
```

Excuse me, but besides the issue with the multiple password prompting, I don’t know what do to push that commit to the remote server.

Would you be so kind to help me?

**Comment by ttaylorr** [comment]
> `git push` prompted four times for my password (and twice for my username [as stated in #2894]), but All I got was:

Hm, that doesn't seem right on a few counts. Could you retry this command with `GIT_TRACE=1` and `GIT_CURL_VERBOSE=1` in your environment, and post the output here? Please be sure to remove any sensitive information that might be contained within it.

**Comment by ousia** [comment]
@ttaylorr, sorry but I had to remove the `.git` folder and start again (avoiding Git LFS, since the actual file is not that big).

I might recreate the problem with a sample repo, if you want. But it will take a while.

**Comment by ttaylorr** [comment]
> I might recreate the problem with a sample repo, if you want. But it will take a while.

Sounds good; let me know if you do so. Until then, I'll close this issue.

**Comment by Mebus** [comment]
I ran into the same problem. Is there actually a real solution to this?

**Comment by bk2204** [comment]
I think this message comes from the server side and, from my searching, can indicate that your GitLab instance has LFS disabled for the repository or for the entire server. I recommend contacting your server administrator and asking them to look into the settings.

**Comment by Mebus** [comment]
It was disabled for the individual project. Shame on me :-P

Mebus

**Comment by bk2204** [comment]
Glad you got it working.
