### ISSUE TITLE
Prune deletes files referenced in the current checkout

### ISSUE THREAD

**Issue by shoelzer** [git-lfs/git-lfs#3092]
I think prune behavior changed in a recent version of LFS. It now deletes objects that match "fetchexclude" in .lfsconfig and I don't think it should.

How to reproduce:

1. In a repository with LFS files, run "git lfs pull" to get up to date.
2. Run "git lfs prune". If there are old LFS files they will be deleted.
3. Run "git lfs prune" again. No LFS files are deleted.
4. Edit .lfsconfig and add "fetchexclude = *".
5. Run "git lfs prune". All LFS files are deleted.

I expected the final step to do nothing. [Prune's documentation](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn) says that files will not be deleted if they are referenced from the current checkout. It does not say anything about "fetchexclude". I think prune is being too aggressive.

This seems to be a recent change in behavior. I noticed it on my CI machine after updating to Git for Windows 2.17.1.windows.2 (with LFS 2.4.2). I'm not sure which version of Git or LFS was installed previously, but it was at least a few months old so I'm guessing git 2.16.x with LFS 2.3.x.

This affects me daily because my LFS setup is a bit unusual. In .lfsconfig, I have "fetchexclude = *". Then, when a build is triggered, it uses git commands to checkout the desired commit and runs "git lfs pull --exclude= --include=Data". (All my LFS files live in the Data folder.) Next it runs "git lfs prune" which now deletes all LFS files every time. That did not happen before installing the newer git/LFS versions.

**Comment by ttaylorr** [comment]
Hi @shoelzer, thanks for opening this. This behavior changed in https://github.com/git-lfs/git-lfs/commit/d2221dcecacc6a2ad38ffd2e429fca18805cb4ea, and `git lfs prune` now does delete anything that matches `lfs.fetchexclude=*`. To achieve a similar effect without the new behavior, I would recommend that you `git lfs install --skip-smudge`, which will skip downloading Git LFS objects.

**Comment by shoelzer** [comment]
@ttaylorr Thanks for the info.
