### ISSUE TITLE
git lfs prune hangs after installing newer lfs version

### ISSUE THREAD

**Issue by shoelzer** [git-lfs/git-lfs#3095]
LFS prune started hanging after updating git and LFS. Behavior is similar to #1494 where it seems to freeze while counting/evaluating objects.

This is on a repo and machine that's been using LFS for quite a while. There were no problems until I updated Git for Windows (which came with a newer version of LFS). I eventually got things working again by deleting .git/lfs and then doing git lfs pull.

I'm not sure which version of git or LFS was on the machine before the update. Probably git 2.16.x and LFS 2.3.x. Current version details:

    > git --version --build-options
    git version 2.17.1.windows.2
    cpu: x86_64
    built from commit: a60968cf435951d9411fc0f980a2e362d5cccea2
    sizeof-long: 4
    
    > git lfs --version
    git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
    
    > cmd.exe /c ver
    Microsoft Windows [Version 10.0.15063]

**Comment by ttaylorr** [comment]
Hi @shoelzer, thanks for opening this issue and I'm sorry that you're having problems. Are you able to reproduce the issue? If so, please let me know here and attach the output with `GIT_TRACE=1` in your environment. This will give me a good indication of where things are getting stuck. Thanks!

**Comment by shoelzer** [comment]
@ttaylorr No, I cannot reproduce. I solved my initial issue by deleting .git/lfs and then doing git lfs pull. I have not had any issues since then. I don't want to revert the one machine where it happened because it runs CI for me. I also don't have any other machines that need a LFS update where it might occur again.

Sorry, I'm not much help. Feel free to close this issue.

**Comment by ttaylorr** [comment]
> Feel free to close this issue.

Sounds good, and I'm glad that it's working for now. Please let me know here if it stops working in the future! Thanks again.
