### ISSUE TITLE
git lfs checkout shows lfs-tracked files as modified and git reset --hard shows only file pointers

### ISSUE THREAD

**Issue by jacobblock** [git-lfs/git-lfs#3100]
Hi all,
New to LFS. I've gone through the other closed issues that seem related to this, but haven't really nailed down my problem. My repo is currently at the point where my .gitattributes is

    -*.so filter=lfs diff=lfs merge=lfs -text
    -*.jar filter=lfs diff=lfs merge=lfs -text
    -*.tar filter=lfs diff=lfs merge=lfs -text

My `git lfs ls-files` shows all pointers correctly to all tracked files above. If I reset + clean to head, all of the files I have tracked are shown as pointers (only 1KB files). This doesn't seem right to me, I would expect them to have been replaced with the actual files. `git lfs status` shows no pending changes. `git lfs checkout` immediately updates all pointers to their actual blobs, but now `git lfs status` shows all the lfs tracked files as needing to be committed. `git status` shows all the tracked files as modified. I have pushed these modifications to a new repo and re-cloned it, only to find the exact same issue. I am not a fan of rewriting the history but I gave it a shot to migrate --everything, but my tortoise-git client crashes on any log view. On my stash server I see that the lfs-tracked files are marked as LFS files correctly, so it seems like a history or client-side issue.

My guess at the moment is some issue with the repo's history. I see some recent activity on a --no-rewrite option and thought I would give that a go. I built the `pastelmobilesuit-migrate-export` branch for windows, but I constantly get a `fatal <file>.jar did not match any Git LFS filters in .gitattributes`.

`set GIT_TRACE=1` and `git-lfs migrate import --no-rewrite "<path-to-jar>.jar" *.jar` I can see all files go through the filepathfilter where `<path-to-jar>.jar` is accepted initially, but then it is rejected in the last step:

    07:11:07.741000 trace git-lfs: filepathfilter: rejecting "<path-to-jar>.jar" via [-*.so -*.jar -*.tar]

Any insight would be really appreciated, and I am not sure the --no-rewrite is working as expected?

Thanks

`git version 2.17.1.windows.2`
`git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)` and
`git-lfs/2.4.0 (GitHub; windows amd64; go 1.10.2; git 096959df)` from `pastelmobilesuit-migrate-export`

**Comment by ttaylorr** [comment]
> If I reset + clean to head, all of the files I have tracked are shown as pointers (only 1KB files).

Could you clarify what you mean by "clean"? Are you referring to a manual invocation of `git lfs clean` or `git lfs filter-process`?

> `git lfs checkout` immediately updates all pointers to their actual blobs, but now `git lfs status` shows all the lfs tracked files as needing to be committed.

It sounds like something is misconfigured or wrongly committed in history. This can happen for a variety of reasons. I'd recommend that you run `git lfs install`, and `git lfs migrate import` to fix things up.

**Comment by jacobblock** [comment]
Thanks for the recommendation, but it has the same behavior. Files are still pointers until `git lfs checkout`, and after that all files are marked modified.

Ignore the word clean above, I just meant `git reset --hard HEAD`. I didn't realize git lfs also has a clean command; I have not run this.

**Comment by ttaylorr** [comment]
> Files are still pointers until `git lfs checkout`, and after that all files are marked modified.

Do you have the `lfs` filter configured correctly in your global git configuration?

**Comment by jacobblock** [comment]
I believe so:

.gitconfig:
```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

.gitattributes
```
-*.so filter=lfs diff=lfs merge=lfs -text
-*.jar filter=lfs diff=lfs merge=lfs -text
-*.tar filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment]
OK, that looks correct. Do you by chance have large objects committed in your git history? You can check this with `git-cat-file`. If so, you can run `git lfs migrate` to fix them.

**Comment by jacobblock** [comment]
Closing the issue; git lfs migrate with a force pushes seems to have worked for my colleagues.
Thanks for the help!
