### ISSUE TITLE
git push does not abort if local LFS objects are missing

### ISSUE THREAD

**Issue by jokram** [git-lfs/git-lfs#3105]
## Problem Description
When some local LFS objects in `.git/lfs/objects/` are missing __(see below for such situations)__ then the `git push` will report that missing objects, but will continue the push operation:
```
$ git push -u origin master
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://git-id-test0.conti.de/cds-sqe-lfs/repo_missing_oid.git/info/lfs.locksverify true
LFS upload missing objects: (0/2), 0 B | 0 B/s
  (missing) LFS_File.xxx (06b936c7439c774eca9c8ae27b39311c6b9c9508cd4413f53ff52f4320913b2e)
Uploading LFS objects:   0% (0/2), 0 B | 0 B/s, done
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 786 bytes | 393.00 KiB/s, done.
Total 7 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To git-id-test0.conti.de:cds-sqe-lfs/repo_missing_oid.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
```
The git repository now exists on GitHub, but the referenced LFS file has not been uploaded => data inconsitency

## Possible Situations where local LFS objects are missing
1. User has deleted that object :fearful:
2. Fetch commits containing LFS objects from remote A and push these commits to remote B  
Here is a Perl script which reproduces this use case (you need to adapt some variable at the beginning):  
[ReproduceMissingOID.pl.txt](https://github.com/git-lfs/git-lfs/files/2163554/ReproduceMissingOID.pl.txt)
And here the output of that script:  
[ReproduceMissingOID.log](https://github.com/git-lfs/git-lfs/files/2163555/ReproduceMissingOID.log)
3. Fetch commits containing LFS objects from remote A, cherry-pick some of that commits and push these new cherry-picked commits to remote B  
This use case has led to ca. 200 missing LFS objects in one case :boom:. Fortunately these objects were already on GitHub from remote A.

## Requested Change
The Git LFS pre-push hook shall abort the `git push` operation if some Git LFS objects are missing to avoid that commits can be uploaded to GitHub without the corresponding Git LFS objects.

## Workaround
For the fetch use cases (see 2. and 3. above) after the normal fetch call:  
`git rev-list HEAD..FETCH_HEAD | xargs git lfs fetch <remote A>`
This should download all referenced LFS objects of the fetched commits (if the fetch does not include multiple branches).

## Environment
```
$ git lfs env
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
git version 2.17.1.windows.2

Endpoint=https://git-id-test0.conti.de/cds-sqe-lfs/repo_missing_oid.git/info/lfs (auth=none)
  SSH=git@git-id-test0.conti.de:cds-sqe-lfs/repo_missing_oid.git
LocalWorkingDir=D:\casdev\_test\Missing_LFS_Objects\missing_oid_script\repo_missing_oid
LocalGitDir=D:\casdev\_test\Missing_LFS_Objects\missing_oid_script\repo_missing_oid\.git
LocalGitStorageDir=D:\casdev\_test\Missing_LFS_Objects\missing_oid_script\repo_missing_oid\.git
LocalMediaDir=D:\casdev\_test\Missing_LFS_Objects\missing_oid_script\repo_missing_oid\.git\lfs\objects
LocalReferenceDir=
TempDir=D:\casdev\_test\Missing_LFS_Objects\missing_oid_script\repo_missing_oid\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\casdev\_test\Missing_LFS_Objects\missing_oid_script\repo_missing_oid\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by jokram** [comment]
__IMPORTANT SIDE NOTE:__
When just using git fetch and git push (without any git checkout) e.g. with a bare repository then the Git LFS pre-push hook is NOT installed at all.

**Comment by jokram** [comment]
The workaround is not really working, because it fetches only LFS files of the latest fetched commit. But if there are more commits then these objects are still missing.

**Comment by larsxschneider** [comment]
Thanks @jokram for the report 👍and thanks @terrorobe for confirming it 👍 

---

@jokram : Situation **2** and **3** "mirror" parts of the repo. In these cases your workaround is the right solution but you can even shorten that with the following equivalent call:
```
git lfs fetch --all
```

@jokram @terrorobe : Technically Git LFS warns you about the missing object (` (missing) xyz.bin`). What behavior would you expect? Should the `git push` fail hard? I guess so and that would make sense to me. @ttaylorr ?

**Comment by terrorobe** [comment]
> Technically Git LFS warns you about the missing object ((missing) xyz.bin). What behavior would you expect?  

Given that we already fail hard for failing uploads or batch API errors (in both cases when they exhaust their retries), I'd like to see the same when we know that we can't upload all LFS objects due to them being missing locally.

**Comment by ttaylorr** [comment]
> What behavior would you expect? Should the `git push` fail hard? I guess so and that would make sense to me. @ttaylorr ?

That's the behavior that I'd expect to, and its implemented in #3109 by you! Let's go with that.

**Comment by larsxschneider** [comment]
@jokram : We will change the Git LFS push behavior according to your suggestion with the next version (see #3109).

You can change the behavior for all your users **today** by distributing the following Git config:
```
git config --global lfs.allowincompletepush false
```

**Comment by jokram** [comment]
@larsxschneider:
> Technically Git LFS warns you about the missing object ((missing) xyz.bin). What behavior would you expect? Should the git push fail hard? I guess so and that would make sense to me. 

I agree to fail hard per default.

 ---

> Situation 2 and 3 "mirror" parts of the repo. In these cases your workaround is the right solution but you can even shorten that with the following equivalent call:
> ```
> git lfs fetch --all
> ```
Since in some repositories there are plenty of LFS objects I've tried to reduce the number of LFS objects to those which are referenced by the recently fetched commits. So the strategy is:
- Get a list of commits in the last fetch operation
- Iterate over that list and for each commit download the referenced LFS objects

My solution is not 100%, because I thing in a fetch operation you could specify to fetch multiple branches, but I haven't found a way so far to list all fetched commits.

And additionally we have the cherry-pick use case, so the user might only want the LFS objects referenced in the cherry-picked commits. Is there a way to download all LFS objects for one specific branch incl. it's history (instead of all LFS objects from all branches)?

---

> You can change the behavior for all your users today by distributing the following Git config:
> ```
> git config --global lfs.allowincompletepush false
> ```

That sounds like a good workaround. I will try it out. Is is also possible to put such a setting in the `.lfsconfig` file inside a repository? Then I would not depend on user interaction.

**Comment by larsxschneider** [comment]
@jokram That is true. Would it be an option to evaluate [Enterprise Config for Git](https://github.com/Autodesk/enterprise-config-for-git) (or your equivalent) to roll out a company wide Git config?

**Comment by larsxschneider** [comment]
Once Git LFS 2.4.3 is released, we could check the server logs and identify users that have pre 2.4.3 Git LFS versions installed.

**Comment by ttaylorr** [comment]
> Once Git LFS 2.4.3 is released, we could check the server logs and identify users that have pre 2.4.3 Git LFS versions installed.

That's a great point, @larsxschneider. That said, I'm not sure if we'll make it to v2.4.3 or if we'll be ready enough to ship v2.5.0 instead. Perhaps in general: `s/2.4.3/next version/g`? 😄

**Comment by jokram** [comment]
@larsxschneider:
> Would it be an option to evaluate Enterprise Config for Git (or your equivalent) to roll out a company wide Git config?

I've already checked Enterprise Config for Git. Based on that I've a similar approach, but it's not yet production ready. But that could be used to distribute the central git config.

The only problem I have with that approach is that users are able to overwrite that settings by specifying their own settings after the include statement to the central config file.
