### ISSUE TITLE
migrate import --everything is missing refs

### ISSUE THREAD

**Issue by jtatum** [git-lfs/git-lfs#3118]
I started with a bare `--mirror` clone of a repo from GitLab (important because GitLab keeps refs to their version of pull requests in the repo). I then performed a `git lfs migrate import --everything --include="..."`. The output captures all `/refs/heads/*` and `/refs/tags/*` refs. It's missing over half of the `/refs/merge-requests/*/head` refs. LFS discovers/outputs 493 of 1055. For example, `/refs/merge-requests/1/head` and `/refs/merge-requests/1000/head` are present and migrated, but `/refs/merge-requests/10/head` and `/refs/merge-requests/100/head` are not. All the missing refs do appear in `git for-each-ref`. Once the migration is complete, there are git objects that should have been migrated but were apparently part of the refs that weren't discovered.

git version 2.18.0
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)

**Comment by jtatum** [comment]
Possibly related to #2984?

**Comment by ttaylorr** [comment]
@jtatum thanks for the suggestion, I think that it is related to a similar problem as is described in #2984. I fixed this up in https://github.com/git-lfs/git-lfs/pull/3121.

**Comment by jtatum** [comment]
I took a look at the change... I'm not sure why the logic decided that some of these refs are local at all. That code seems to be pretty broken for bare repositories. In any case, thanks for the change! I'll spin it up today and have a look.

**Comment by jtatum** [comment]
@ttaylorr verified that the PR works. `--everything` sees all refs. Thanks so much for your quick response!

**Comment by ttaylorr** [comment]
> @ttaylorr verified that the PR works. `--everything` sees all refs.
> Thanks so much for your quick response!

Thanks for taking a look; I'm glad that everything works as expected.

I've queued that pull request to be generally available in the next
release, which will be v2.5.0.

**Comment by ttaylorr** [comment]
> I took a look at the change... I'm not sure why the logic decided that
> some of these refs are local at all.

Me either :-).

> That code seems to be pretty broken for bare repositories. In any
> case, thanks for the change! I'll spin it up today and have a look.

Thanks for taking a look. It's possible that there is unknown breakage
for bare repositories, but we try and do as best a job as possible at
detecting when a repository is bare, and acting appropriately (i.e., not
performing worktree operations iff true).

Please don't hesitate to let me know about any breakages, and I (or
another member of @git-lfs/core would be more than happy to help fix, or
guide a contributor through fixing them).

**Comment by ttaylorr** [comment]
> @ttaylorr verified that the PR works. `--everything` sees all refs.
> Thanks so much for your quick response!

Hooray, that's great! Thanks again for testing it out.
