### ISSUE TITLE
I was trying to setup jenkins(linux) with git-lfs. I referred the installation documentation but noticed it says not for Rhel 6. Unfortunately, i am using RHEL 6.9. I am royally stuck because of it. Please let me know if there is a way out of this problem. Any documentation/pointers/details.

### ISSUE THREAD

**Issue by Ankush777** [git-lfs/git-lfs#3129]
I was trying to setup jenkins(linux) with git-lfs. I referred the installation documentation but noticed it says not for Rhel 6. Unfortunately, i am using RHEL 6.9. I am royally stuck because of it. Please let me know if there is a way out of this problem. Any documentation/pointers/details.

Rhel 6.9
Git version 2.13.3

Please provide me with you suggestion.

Regards

**Comment by Ankush777** [comment]
Resolved it.

As a solution, I downloaded the rpm package using wget [here](https://github.com/git-lfs/git-lfs/releases)

Then, i ran 'rpm -i --nodeps git-lfs*.rpm'  on the downloaded artifact.

This worked for me. 

Hence, closing the issue.

**Comment by ttaylorr** [comment]
> Resolved it.

Great; I'm glad to hear that the issue was able to be resolved. Thanks
for posting your work here, I'm hopeful that this issue will be helpful
to others who encounter the same problem.
