### ISSUE TITLE
Quotes in GIT_SSH_COMMAND are (still) not properly handled

### ISSUE THREAD

**Issue by matangover** [git-lfs/git-lfs#3131]
#1895 reported a bug that occurred when GIT_SSH_COMMAND had quotes, e.g.:
```
GIT_SSH_COMMAND="ssh -i '/a path/with spaces'"
```

#1962 fixed this bug, but in an incomplete way. A value with two pairs of quotes still fails, e.g.:
```
GIT_SSH_COMMAND="ssh -i '/a path/with spaces' -o 'Set Some Option'"
```

The bug is in `QuotedFields` (`str_tools.go`) - the regexp is greedy so it catches anything between the outermost pair of quotes. This can be confirmed by adding a line in `TestQuotedFields` (`str_tools_test.go`):
```go
"single quotes twice": {`foo 'bar baz' 'blip blop'`, []string{"foo", "bar baz", "blip blop"}},
```
This test fails.

Unfortunately, there are many other values of GIT_SSH_COMMAND which will work in git, but won't work in git-lfs. Git uses `sh -c "command"` when running the GIT_SSH_COMMAND, which is the only way to support anything that a user may want to put in there. In fact, the documentation [explicitly states](https://git-scm.com/docs/git#git-codeGITSSHCOMMANDcode) that GIT_SSH_COMMAND is "interpreted by the shell".

(Relevant code in git: [fill_ssh_args](https://github.com/git/git/blob/c2c7d17b030646b40e6764ba34a5ebf66aee77af/connect.c#L1182), [prepare_shell_cmd](https://github.com/git/git/blob/e3331758f12da22f4103eec7efe1b5304a9be5e9/run-command.c#L254).)

If git-lfs doesn't want to use "sh -c", or needs some added argument parsing/modification magic, another solution is to use a library for shell string parsing. Some examples from a quick search: [go-shellwords](https://github.com/mattn/go-shellwords), [shlex](https://github.com/google/shlex), [go-shlex](https://github.com/anmitsu/go-shlex), [go-shellquote](https://github.com/kballard/go-shellquote), [shellwords](https://github.com/Wing924/shellwords). Git uses its own [split_cmdline](https://github.com/git/git/blob/c2c7d17b030646b40e6764ba34a5ebf66aee77af/alias.c#L54).

---
For what it's worth, I encountered this when working in TeamCity, which sets GIT_SSH_COMMAND to
```
ssh -i "path/to/key" -o "StrictHostKeyChecking=no"
```
Another user also encountered this on TeamCity, see [report](https://youtrack.jetbrains.com/issue/TW-55655). This only happens on TeamCity when `teamcity.git.use.native.ssh` is set to `true`.

**Comment by ttaylorr** [comment]
> #1895 reported a bug that occurred when GIT_SSH_COMMAND had quotes,
> e.g.:
> ```
> GIT_SSH_COMMAND="ssh -i '/a path/with spaces'"
> ```
>
> #1962 fixed this bug, but in an incomplete way. A value like the
> following would still fail:
> ```
> GIT_SSH_COMMAND="ssh -i '/a path/with spaces' -o 'Set Some Option'"
> ```
>
> The bug is in `QuotedFields` (`str_tools.go`) - the regexp is greedy
> so it catches anything between the outermost pair of quotes. This can
> be confirmed by adding a line in `TestQuotedFields`
> (`str_tools_test.go`):
>
> ```go
> "single quotes twice": {`foo 'bar baz' 'blip blop'`, []string{"foo", "bar baz", "blip blop"}},
> ```
>
> This test fails.

OK. I recall writing this regexp to be greedy, so this problem (and its
description) both make sense to me.

I'm inclined to port the implementation from Git's split_cmdline
function in alias.c, which I think should do what we want (and be much
faster than slurping in package regexp).

> In fact, the documentation explicitly states that GIT_SSH_COMMAND is
> "interpreted by the shell".

Right, this is a known bug. I think that this issue is separate from the
quoting one.

**Comment by matangover** [comment]
Thanks for your prompt answer. I agree. I filed a separate issue for GIT_SSH_COMMAND running as a shell command because I couldn't find an issue documenting it (#3136).

**Comment by matangover** [comment]
Thanks, yes, the issue only occurs with more than one pair of quotes. In my case (TeamCity) I have no control on the `GIT_SSH_COMMAND`.
