### ISSUE TITLE
Push sends to wrong remote when pushRemote is set

### ISSUE THREAD

**Issue by markshep** [git-lfs/git-lfs#3133]
I've been trying to push all LFS-controlled files to the "origin" remote with "git lfs push --all origin", but it wasn't working.  After setting $GIT_TRACE and looking at the resulting log file it shows that git-lfs was actually pushing to the "push" remote instead.  It seems that it was somehow picking this up from the "pushRemote" setting for my branches (which was set to "push") and totally ignoring what I'd told it on the command line :-(.  After commenting out the "pushRemote" setting for each of my branches in the local git project config file it works.

Please can this be fixed so that git-lfs does what I tell it to do and not send my files to a totally different server than the one I specified on the command line?

I'm on a Mac using the current Homebrew packages for git & git-lfs:

    git version 2.18.0
    git-lfs/2.4.2 (GitHub; darwin amd64; go 1.10.2)

**Comment by markshep** [comment]
Note that the same behaviour happens when pushing a single object with ````git-lfs push --object-id origin <oid>````.  Quite why it's picking up branch-specific settings when this operation is inherently branch-agnostic is beyond me.

**Comment by ttaylorr** [comment]
Thanks for the detailed bug report. @PastelMobileSuit, would you be
interested in looking at this?

**Comment by PastelMobileSuit** [comment]
@ttaylorr I'd be happy to take a look at this!

**Comment by PastelMobileSuit** [comment]
@markshep @ttaylorr It looks like there was a bug in the `push` code, I've opened #3139 to fix the issue!

**Comment by ttaylorr** [comment]
> @markshep @ttaylorr It looks like there was a bug in the `push` code,
> I've opened #3139 to fix the issue!

Thanks, @PastelMobileSuit! I reviewed the change and it looks good to
me, so I've merged it into 'master' and will queue it for the next
release.

**Comment by markshep** [comment]
I just tested the code currently in master (a1736293) and it's now working for me.  Thanks for the fix!

**Comment by ttaylorr** [comment]
> I just tested the code currently in master (a1736293) and it's now
> working for me.  Thanks for the fix!

Yay! Glad that these changes are working out well for you. Nice job,
@PastelMobileSuit.
