### ISSUE TITLE
Git LFS not pulling down files in Mac OS X 10.13 High Sierra

### ISSUE THREAD

**Issue by terriyu** [git-lfs/git-lfs#3141]
I tried installing Git LFS on Mac OS X 10.13 High Sierra using both Homebrew and the installer I downloaded directly from the official Git LFS website. I made sure to run `git lfs install` and also `git lfs install --system` after installing Git LFS. I cloned my GitHub repository using the HTTPS protocol, but when I change to the cloned repository directory and run `git lfs pull`, nothing happens.

**Comment by terriyu** [comment]
Thanks for the fast response. I remember that when I used the Homebrew version of Git LFS, it didn't work for some reason. I had tests failing because there were files missing. I just checked and after I installed Git LFS with the official installer, it seems to work. I got confused because on Ubuntu, Git LFS prints out on the command line that it is downloading the files, whereas on Mac OS X, there appears to be no message. It gets confusing when I install Git from Anaconda or Homebrew, since Apple already has Git pre-installed on OS X. Maybe that was the issue -- too many versions of Git floating around.

**Comment by iMonZ** [comment]
> but when I change to the cloned repository directory and run `git lfs pull`, nothing happens.
> OK, I think that everything should be working as intended here. `git lfs pull` downloads Git LFS objects that the local client doesn't have. So, if you ran `git lfs install` and then did a `git clone` of your repository, you should have both all of the Git objects _and_ all of the Git LFS ones, too. Are you missing objects? If so, that is certainly a bug. If not, `git lfs pull` should be a no-op. You can also force Git LFS to scan through more history by running `git lfs fetch --all <remote>`. If none of the above are on track, please let me know here and I (or somebody on @git-lfs/core) would be more than happy to take a further look.

Btw. the command `git lfs install` doesn't exist, so please stop referring to it.
To install git lfs just run `brew install git-lfs`
Then after cloning the repo go into it and run `git lfs fetch --all`
Thats it!
