### ISSUE TITLE
Git lfs Bad gateway error

### ISSUE THREAD

**Issue by thekngmkr** [git-lfs/git-lfs#3142]
git lfs clone ssh://git@abc.com:7999/project/repo.git
Cloning into 'repo'...
remote: Counting objects: 13519, done.
remote: Compressing objects: 100% (7007/7007), done.
remote: Total 13519 (delta 6524), reused 11235 (delta 5596)
Receiving objects: 100% (13519/13519), 4.59 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (6524/6524), done.
Checking connectivity... done.
batch response: Post https://abc.com/scm/project/repo.git/info/lfs/objects/batch: Bad Gateway
error: failed to fetch some objects from 'https://abc.com/scm/project/repo.git/info/lfs'

**Comment by thekngmkr** [comment]
```
 git lfs env
git-lfs/2.4.2 (GitHub; linux amd64; go 1.8.3)
git version 2.7.4

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDir=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

```
git --version
git version 2.7.4

```

**Comment by ttaylorr** [comment]
Hi, sorry that you're having trouble. Could you please make sure that:

  1. You're on the latest version of Git? (At the time of writing,
  that's the 2.18 series).

  2. You re-try this command with `GIT_TRACE=1` in your environment?
  That should hopefully provide a better indication of what is going on.

With the output from `GIT_TRACE=1` in hand, I think we should be able to
narrow down that this is a network problem, and not a problem with Git
LFS.

**Comment by thekngmkr** [comment]
Hi Taylorr,

I have upgrade the git to version 2.18.0

i have a new warning 

> WARNING: 'git lfs clone' is deprecated and will not be updated
>           with new flags from 'git clone'
> 
> 'git clone' has been updated in upstream Git to have comparable
> speeds to 'git lfs clone'.

```
/build$ GIT_TRACE=1 git lfs clone ssh://git@abc.com:7999/project/repo.git
10:06:18.697258 git.c:654               trace: exec: git-lfs clone ssh://git@abc.com:7999/project/repo.git
10:06:18.697324 run-command.c:637       trace: run_command: git-lfs clone ssh://git@abc.com:7999/project/repo.git
10:06:18.700710 trace git-lfs: exec: git 'version'
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'repo'...
remote: Counting objects: 13519, done.
remote: Compressing objects: 100% (7007/7007), done.
remote: Total 13519 (delta 6524), reused 11235 (delta 5596)
Receiving objects: 100% (13519/13519), 4.59 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (6524/6524), done.
10:06:24.424079 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:06:24.424989 trace git-lfs: exec: git 'config' '-l'
10:06:24.425938 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:06:24.426873 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:06:24.427957 trace git-lfs: tq: running as batched queue, batch size of 100
10:06:24.428481 trace git-lfs: run_command: git cat-file --batch
10:06:24.429511 trace git-lfs: filepathfilter: rejecting ".gitattributes" via []
10:06:24.429544 trace git-lfs: filepathfilter: accepting ".gitattributes"
10:06:24.429632 trace git-lfs: filepathfilter: rejecting "path/folder/content.a" via []
10:06:24.429643 trace git-lfs: filepathfilter: accepting "path/folder/content.a"
10:06:24.429667 trace git-lfs: filepathfilter: rejecting "readme.md" via []
10:06:24.429673 trace git-lfs: filepathfilter: accepting "readme.md"
10:06:24.430173 trace git-lfs: fetch path/folder/content.a [<commit id>]
10:06:24.430240 trace git-lfs: tq: sending batch of size 1
10:06:24.430416 trace git-lfs: run_command: ssh -p 7999 -- git@abc.com git-lfs-authenticate project/repo.git download
10:06:26.213766 trace git-lfs: api: batch 1 files
10:06:26.214159 trace git-lfs: HTTP: POST https://abc.com/scm/project/repo.git/info/lfs/objects/batch
10:06:26.677663 trace git-lfs: api error: Post https://abc.com/scm/project/repo.git/info/lfs/objects/batch: Bad Gateway
batch response: Post https://abc.com/scm/project/repo.git/info/lfs/objects/batch: Bad Gateway
error: failed to fetch some objects from 'https://abc.com/project/repo.git/info/lfs'
```

**Comment by thekngmkr** [comment]
Sorry closed the issue by mistake

**Comment by ttaylorr** [comment]
> I have upgrade the git to version 2.18.0

Thanks for doing so. It looks like the error persists below, so I think
that we can safely rule out that this is a problem to do with an older
version of Git.

> i have a new warning
>
> > WARNING: 'git lfs clone' is deprecated and will not be updated
> >           with new flags from 'git clone'
> >
> > 'git clone' has been updated in upstream Git to have comparable
> > speeds to 'git lfs clone'.

Yes, this is because you have a new-enough version of Git that you can
safely use 'git clone' instead of 'git lfs clone' without performance
degradation.

##

It looks like the issue is related to connecting to GitHub.com, which
isn't something that I can help you with here. Would you mind sending an
issue to support@github.com? They will be able to help you diagnose
network connectivity issues into our datacenters.

Thanks!

**Comment by nhatkhai** [comment]
@ttaylorr, I just reach this similar errors. After lost of 3hr sleep, I found that git LFS using http_proxy environment variables, but normal none-lfs git clone do not use that variable. This cause a confuse why it partially work, and not the LFS files. I think this is a behavior issue differently within single "git clone" command. I think either git, or git lfs need to coordinate to give use the similar behavior within the git Eco-system.

**Comment by bk2204** [comment]
Git is documented to use the `http_proxy` and `https_proxy` environment variables, but it only uses `https_proxy` for HTTPS, not `http_proxy`.  This is, unfortunately, not consistent with what some other people tend to do, and also unfortunately, there's no specification for how these environment variables are supposed to behave, so anyone can claim that they're doing the right thing.

In general, you cannot safely set only one of those values without also setting the other.

**Comment by nhatkhai** [comment]
@bk2204, I do not disagree. In the user stand point, unify behavior would make life simple. As I understand, git using SSH exclusively so proxy define in the .ssh/config file. So may be git LFS also doing such that way with SSH protocol in addition with HTTP/(s). And the git core side, may need support HTTP/(s) protocol too. So they can be unify IFF the server setup right. Just a through.

**Comment by nhatkhai** [comment]
@bk2204, Another issue that not the same with this. But the experience of the issue are not unify behavior on the specification of got clone --reference too:
* `git clone ... --reference c:\xyz:` git work, git lfs not
* `git clone ... --reference /c/xyz`: git work, git lfs not
* `git clone ssh://......`: git work, git lfs not using ssh

Because of these, I often pickup the surprise, and try to figure out how to get make both world happy by trial and errors.
