### ISSUE TITLE
Newly LFS-controlled files showed as modified - cannot discard

### ISSUE THREAD

**Issue by amacara1** [git-lfs/git-lfs#3148]
git status lfs returns:
Git LFS objects not staged for commit:
        mybinfile (Git: fec0139 -> File: fec0139)
(the file in lfs/objects/fe/c0... is binary identical to the "real" artifact)

git checkout -- mybinfile and git lfs checkout mybinfile have no effect.

git version 2.17.1.windows.2
git-lfs/2.4.2 (GitHub; windows 386; go 1.8.3; git 6f4b2e98)

This situation happened when:
1. a branch was created from develop
2. a second branch was created from develop and some binary files were added to LFS control
3. this second branch was merged into develop
4. I am trying to merge new develop into the first branch (see 1.) (I check out this first branch, notice warn messages about files expected to be pointers, and then disaster strikes when I'm trying to merge from develop)

If it matters,  git lfs ls-files does NOT list this particular file.

I cannot rewrite history, thus cannot consider using git lfs migrate

**Comment by ttaylorr** [comment]
Hi @amacara1, thanks for opening this issue. I think that this branch topology has problems with Git LFS picking up that there should be files that used to be tracked with Git and are now tracked by Git LFS.

Luckily, you _can_ use `git lfs migrate` with the new `--no-rewrite` mode, which creates _additional_, new commits on top of your existing history without rewriting it. That feature will ship as a part of v2.5.0, which is coming out later today.

Please let me know if that works for you, and if not please don't hesitate to let me know here and I'd be happy to dive in further.

**Comment by amacara1** [comment]
@ttaylorr, thanks for the information!
The changes I make on the 1st branch are not related to files related to LFS, thus, it would be a convenient thing for me to rebase my changes to a moment after all LFS files are "clean". But presently, I cannot to this, as every time I checkout 1st branch I get the "encountered files supposed to be pointers" message. Isn't there an option to somehow circumvent this in order to do my rebase operation? Or a merge from the now-stable develop/ ?

**Comment by ttaylorr** [comment]
No, there isn't a way to disable that without temporarily removing Git LFS, which I do not recommend that you do.
