### ISSUE TITLE
git lfs push is not allowing to upload the existing file.

### ISSUE THREAD

**Issue by guptapraveen2** [git-lfs/git-lfs#3157]
Here are some details.

I have created a feature branch and pushed the lfs artifact in the repository and I verified the artifact in a repository.

After that, I finish the feature in local develop and the trying to push the change the in origin develop branch.
$ GIT_TRACE=1 git lfs push

trace git-lfs: tq: sending batch of size 1
trace git-lfs: api: batch 1 files
trace git-lfs: creds: git credential fill ("https", "company.com", "artifactory/api/lfs/default.gitlfs.local/")
trace git-lfs: Filled credentials for https://company.com/artifactory/api/lfs/default.gitlfs.local/
trace git-lfs: HTTP: POST https://company.com/artifactory/api/lfs/default.gitlfs.local/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {
  "objects" : [ {
    "oid" : "88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7",
    "size" : 80569606,
    "_links" : {
      "upload" : {
        "href" : "https://company.com/artifactory/default.gitlfs.local/objects/88/ea/88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7;sha256=88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7",
        "header" : {
          "Authorization" : "Basic cHJhdmVlbiahksdjfhaksdfhkahsdfuZ2VAMTIzNDU="

trace git-lfs: HTTP: }
      }
    }
  } ]
}
trace git-lfs: tq: starting transfer adapter "basic"
Git LFS: (0 of 1 files) 0 B / 76.84 MB                                         trace git-lfs: HTTP: PUT https://company.com/artifactory/default.gitlfs.local/objects/88/ea/88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7;sha256=88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7
Git LFS: (0 of 1 files) 1.14 MB / 76.84 MB                                     trace git-lfs: HTTP: 404
trace git-lfs: HTTP: {
  "errors" : [ {
    "status" : 404,
    "message" : "Could not locate artifact 'default.gitlfs.local:objects/88/ea/88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7'."
  } ]
}
trace git-lfs: tq: retrying object 88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7: LFS: Repository or object not found: https://company.com/artifacto
trace git-lfs: tq: refusing to retry "88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7", too many retries (8)
Git LFS: (0 of 1 files) 12.00 KB / 76.84 MB
LFS: Repository or object not found: https://company.com/artifactory/default.gitlfs.local/objects/88/ea/88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7;sha256=88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7
Check that it exists and that you have proper access to it
error: failed to push some refs to 'git@git.sami.int.company.com:ipmc/on-premise-motor.git'

@technoweenie Could you please see this issue? I really appreciate.

**Comment by ttaylorr** [comment]
Hi @guptapraveen2, thanks for letting us know. I'd be happy to help out,
but in the future can you please avoid pining @git-lfs/core team members
by name? For example, `@technoweenie` (whom you mentioned below) does
not work on this project anymore, and I would like to avoid sending him
unnecessary email.

> I have created a feature branch and pushed the lfs artifact in the
> repository and I verified the artifact in a repository.

OK, so it sounds like the Artifactory instance already has an object
that you uploaded successfully?

> After that, I finish the feature in local develop and the trying to push the change the in origin develop branch.
> $ GIT_TRACE=1 git lfs push
>
> trace git-lfs: tq: sending batch of size 1
> trace git-lfs: api: batch 1 files
> trace git-lfs: creds: git credential fill ("https", "company.com", "artifactory/api/lfs/default.gitlfs.local/")
> trace git-lfs: Filled credentials for https://company.com/artifactory/api/lfs/default.gitlfs.local/
> trace git-lfs: HTTP: POST https://company.com/artifactory/api/lfs/default.gitlfs.local/objects/batch
> trace git-lfs: HTTP: 200
> trace git-lfs: HTTP: {
>   "objects" : [ {
>     "oid" : "88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7",
>     "size" : 80569606,
>     "_links" : {
>       "upload" : {
>         "href" : "https://company.com/artifactory/default.gitlfs.local/objects/88/ea/88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7;sha256=88ea502c3ef89f82dd2f5d0194ddc17cd726b4cb7",

And then Artifactory sends you the same link to upload the file to
_again_, but complains that it can't be found after Git LFS tries to
upload it.

It sounds like there is a discrepancy between what Git LFS thinks needs
to be uploaded and what Artifactor already has. In any case, it sounds
like the Artifactory instance that you are running shouldn't be sending
an upload _link iff it already has the object in question.

Can you please re-raise this issue with them? It sounds like a but that
they should be aware of.
