### ISSUE TITLE
Download link for 2.5.0 redirects to 404

### ISSUE THREAD

**Issue by antpr** [git-lfs/git-lfs#3162]
Download link for 2.5.0 on https://git-lfs.github.com/ redirects to Octocat Jedi 404. 

https://github.com/git-lfs/git-lfs/releases/download/v2.5.0/git-lfs-windows-v2.5.0.exe

![screenshot 2018-07-31 at 14 11 28](https://user-images.githubusercontent.com/32390570/43478360-b045dbde-94cb-11e8-90e5-0ed26e3b1b75.png)

**Comment by ttaylorr** [comment]
Thanks, for letting me know, Anthony.

There have been a few snafus with the Makefile changes in v2.5.0 related
to naming release artifacts and installers in _slightly_ different ways
than before, and this appears to be one of them.

I fixed this this morning, so I think that we can close this issue for
now. Please don't hesitate to let me know if in the future something
like this breaks for you again. In the meantime, thanks!
