### ISSUE TITLE
git-lfs issue migrating from Bitbucket

### ISSUE THREAD

**Issue by JacobEvelyn** [git-lfs/git-lfs#3166]
I'm trying to move a repo from Bitbucket to GitHub, and the repo has one large file that is tracked via `git-lfs` on Bitbucket. When we set up `git-lfs` on Bitbucket we scrubbed the `git` history for that file's blobs, and I've also tried to see if I can find a commit or branch in the repo that has the file in `git` instead of `git-lfs` and I cannot. So far so good.

However, when I try pushing the repo to GitHub, I see the pre-receive hook error:

```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: ######################
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File <name of the one file we track in LFS> is 141.75 MB; this exceeds GitHub's file size limit of 100.00 MB
```

This happens with both `git push` and `git push --mirror` (for non-mirrored and mirrored clones of the repo, respectively). For what it's worth `git lfs push` works as expected.

I'm not sure what's going wrong here. I tried running

```
git lfs migrate import --include="*.<file extension>"
```

and got this output, which I assume means the file was already correctly set up for LFS:

```
migrate: Fetching remote refs: ..., done                                                                                                                                                                  
migrate: Sorting commits: ..., done                                                                                                                                                                       
migrate: Rewriting commits: 100% (0/0), done                                                                                                                                                              
migrate: Updating refs: ..., done                                                                                                                                                                         
migrate: checkout: ..., done
```

Is there a good way for me to see where the blob that GitHub is complaining about is? (I can't figure out if the `trace` part of GitHub's output is supposed to be useful to me.) Is it possible this is a bug on GitHub's end? Any help would be supremely appreciated!

**Comment by ttaylorr** [comment]
Hi Jacob, thanks for letting us know. I think that the issue (as you
suggest above) is that there is a previous version of the blob buried
somewhere in your history that is larger than GitHub's size limits.

Depending on the topology of your repository's history, there's a good
chance that it may not have been migrated. You can investigate this
yourself; I have posted a few shell scripts throughout the years in
different issues on git-lfs/git-lfs that might be helpful.

Or give the '--everything' flag to 'git lfs migrate' which assumes that
you would like every part of your history migrated. Once you've done
that, make sure to push with `--all --force`, and update other copies of
the repository accordingly. With that, you should be all set :+1:.

If that's not the case, please don't hesitate to let me know here, and I
(or another member of @git-lfs/core) would be more than happy to help
out. Thanks!
