### ISSUE TITLE
Not able to Merge branches after LFS import

### ISSUE THREAD

**Issue by vramaprasad** [git-lfs/git-lfs#3167]
Hi,

I have migrated complete repository including branches from Bitbucket to GitHub using GIT-LFS Import, Migration was successfully done. But i am not able to Merge branches in Master on GitHub. 

When i request for Merge/Pull Request ,I am getting error Like "There isn’t anything to compare."

I am not getting any issue in Bitbucket, if i merge same branches. Seems like my commit history changed or may be something else. Any suggestion ?

Thanks

**Comment by ttaylorr** [comment]
Hi @vramaprasad, thanks for opening this up and letting us know. In
cases like these:

> When i request for Merge/Pull Request ,I am getting error Like "There
> isn’t anything to compare."

It's usually the case that you migrated one side of the potential merge,
and therefore have created two separate lines of history. Hence the
"there isn't anything to compare" message.

Can you make sure that both of the things that you are trying to merge
have undergone a migration? To do so, either (1) make sure that both
branch names show up in the refmove output of 'git lfs migrate', or (2)
re-run the 'git lfs migrate' command with '--everything' to make sure
that you caught all branches and references to be migrated.

If this isn't the case, please don't hesitate to let me know and I would
be more than happy to look in further. Thanks!
