### ISSUE TITLE
cherry-pick failed : add_cacheinfo failed to refresh for path 

### ISSUE THREAD

**Issue by chucklu** [git-lfs/git-lfs#3173]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

 git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.547]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 git cherry-pick 9e3252^..126c0c
```
 - What did you expect to occur after running these commands?

cherry-pick successfully

 - What actually happened instead?

cherry-pick failed

The trace info for cherry-pick is as following:

> 
> $ git_trace=1 gcm_trace=1 git cherry-pick 9e3252^..126c0c
> 09:23:52.160079 exec-cmd.c:236          trace: resolved executable dir: C:/Progr                                                                                                                                                                                               am Files/Git/mingw64/bin
> 09:23:52.171109 git.c:415               trace: built-in: git cherry-pick 9e3252^                                                                                                                                                                                               ..126c0c
> Performing inexact rename detection: 100% (5862848/5862848), done.
> 09:24:04.932967 run-command.c:637       trace: run_command: 'git-lfs filter-process'
> 09:24:05.062300 trace git-lfs: exec: git 'version'
> 09:24:05.203674 trace git-lfs: exec: git 'config' '-l'
> 09:24:05.248795 trace git-lfs: Install hook: pre-push, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\pre-push, upgrading...
> 09:24:05.250808 trace git-lfs: Install hook: post-checkout, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\post-checkout, upgrading...
> 09:24:05.251802 trace git-lfs: Install hook: post-commit, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\post-commit, upgrading...
> 09:24:05.252805 trace git-lfs: Install hook: post-merge, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\post-merge, upgrading...
> 09:24:05.253807 trace git-lfs: Initialize filter-process
> 09:24:05.253807 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
> 09:24:05.309955 trace git-lfs: tq: running as batched queue, batch size of 100
> error: add_cacheinfo failed to refresh for path '/Lib/ICSharpCode.SharpZipLib.dll'; merge aborting.
> fatal: cherry-pick failed
> 09:24:05.321987 run-command.c:46        trace: run_command: running exit handler for pid 20124
> 09:24:05.321987 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
> 09:24:05.321987 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
> 09:24:05.321987 trace git-lfs: filepathfilter: rejecting "tmp" via []
> 09:24:05.321987 trace git-lfs: filepathfilter: accepting "tmp"
>

**Comment by ttaylorr** [comment]
Closing per: https://github.com/git-for-windows/git/issues/1780#issuecomment-411118104.

**Comment by SP-SuperPoney** [comment]
Had the same problem with Git version  :
`git version 2.28.0.windows.1`

Merging a branch give error `error: add_cacheinfo` on random files.

The solution I found was to remove my .gitattributes -> commit -> push -> re-merge.

Can you solve this bug ?

**Comment by bk2204** [comment]
Hey,

I don't think this is a Git LFS issue.  I think this is a Git for Windows issue, possibly with the `core.fscache` functionality, since it appears to occur even without Git LFS.  Therefore, there isn't anything we could do to fix it.
