### ISSUE TITLE
How can I remove git lfs? and get the original file

### ISSUE THREAD

**Issue by chucklu** [git-lfs/git-lfs#3175]
As I mentioned in this issue https://github.com/git-lfs/git-lfs/issues/3173
The cherry-pick feature in git for windows can't work with the git lfs.

For now, I want to remove git lfs to use the cherry-pick feature.
Previously, I just remove the .gitattributes file from git repository, and the cherry-pick of "git for windows" works fine.

Now the problem is, the library I am using **missed file version** which caused my project stop working.
And I have checked the file added to git repository, **the sha-1 is not the same** with the original file.
Is it possible that I can revert the file back to the original one by git lfs?

**Comment by chucklu** [comment]
After reading the conversation in this issue https://github.com/git-lfs/git-lfs/issues/910
I decide to skip the commit contains .gitattributes and files modified by git lfs.

I can create a new branch on the previous commit of the git lfs commit.
Then cherry-pick the useful commits to skip the lfs commits.
Then re-add the library files.

**Comment by caozuba** [comment]
I used `git lfs pull` to download original file then `git lfs uninstall,` after that I removed the `.gitattributes` file and commit again.
