### ISSUE TITLE
git lfs smudge did not work

### ISSUE THREAD

**Issue by chucklu** [git-lfs/git-lfs#3176]
$ git_trace=1 gcm_trace=1 git lfs smudge
11:11:32.752359 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
11:11:32.754864 git.c:654               trace: exec: git-lfs smudge
11:11:32.754864 run-command.c:637       trace: run_command: git-lfs smudge
11:11:32.827568 trace git-lfs: exec: git 'version'
11:11:32.952422 trace git-lfs: exec: git 'config' '-l'
11:11:32.988547 trace git-lfs: Install hook: pre-push, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\pre-push, **upgrading...**
11:11:32.989549 trace git-lfs: Install hook: post-checkout, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\post-checkout, **upgrading...**
11:11:32.990551 trace git-lfs: Install hook: post-commit, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\post-commit, **upgrading...**
11:11:32.991554 trace git-lfs: Install hook: post-merge, force=false, path=C:\Users\clu\source\repos\Test\.git\hooks\post-merge, **upgrading...**

The command git lfs smudge stucked for more than 30 minutes.
What the meaning of the upgrading ?

**Comment by ttaylorr** [comment]
Hi, when Git LFS says that it is "upgrading" a hook, it means that we've
changed the implementation of that hook from a previous known state, and
are rewriting it for you to match the latest implementation.

In other words, if you installed Git LFS at version "X", and are now
using version "Y" (and we've changed the implementation of
.git/hooks/pre-push (or any other hook) between X and Y), we'll
automatically upgrade the hook from version X to the one in version Y
for you.

But, I don't think that's quite what's going on here. Before we dive in
too deeply, can you do the following?

  1. Make sure that you have the latest version of Git LFS installed (at
  the time of writing, that is v2.5.1.

  2. Run `git lfs install --system --force`.

  3. Then, inside of your repository, run `git lfs install --force`.

  4. Then, try the affected command again.

I'm reasonably confident that that ought to be enough to get this
working for you again, so I am going to close this issue in anticipation
of that.

If I'm wrong, please do not hesitate to ping me (or anyone) here and I
(or someone from @git-lfs/core) will be sure to get back to you.

**Comment by chucklu** [comment]
@ttaylorr  Thanks, I find there are two versions of lfs on my computer.
version 2.4.2 was installed with git for windows.
version 2.5.1 was installed by lfs official installer.

When I am using git lfs version command in git bash(which provided by git for windows). The version is 2.4.2.
I just reinstall the git for windows, and unchecked git lfs, to uninstall the version 2.4.2

**Comment by chucklu** [comment]
Hi @ttaylorr ,
    I tried the command 
> C:\Program Files\Git LFS> git lfs install --system --force
> WARNING: current user is not root/admin, system install is likely to fail.
> Git LFS initialized.

I am not sure if the  command `git lfs install --system --force` execute successfully(already in admin model).
![image](https://user-images.githubusercontent.com/3004057/43872787-058cf5a0-9bb6-11e8-8308-833348ce7d4c.png)

Then I try the command `git lfs install --force` in target repository.

Then the affected command 
$ git_trace=1 gcm_trace=1 git lfs smudge
The same problem still exists, the command is stucked at upgrading

**Comment by ttaylorr** [comment]
> Then the affected command
> $ git_trace=1 gcm_trace=1 git lfs smudge
> The same problem still exists, the command is stucked at upgrading

I'm sorry that that didn't fix the problem. Do you have any strace-like
facilities on Windows? I don't use Windows frequently, so I'm not sure
how to debug anything like this on my non-native platform.

Without that, I'm at a loss for what might be going on. It sounds like
that there is something that starts after the "upgrading" phase, but
doesn't announce itself, and _that_ is what is getting stuck. But, that
could be a myriad of things, so I'm not sure where to start.

If you're able to debug any system calls from this process, that would
be a helpful place to start.
