### ISSUE TITLE
.gitattributes presence with lockables does not triggers readonly mode

### ISSUE THREAD

**Issue by margothonore** [git-lfs/git-lfs#3177]
I have several issues with automatically getting a readonly status for lockable files:

When manually creating a .gitattribute file in some git repository, files are not set to readonly. I tried 'git lfs update', and 'git lfs install". It shows "Updated git hooks." but permissions on files are unchanged unless I use 'git lfs track *.ext --lockable'.

This is problematic for me because I use lfs only for its locking ability and I have no need for lfs support for the moment, so '*.ext lockable' is what seems optimal in my .gitattributes file. I would like to create .gitattributes files manually or have git lfs offer a "set lockable" command without lfs tracking. The only way to get the desired behavior for the moment is to call  'git lfs track *.ext --lockable' then edit the .gitattributes file manually, wich is inconvenient to do on many machines.

That leads to my other issue: when pulling a repository that has a .gitattributes file added, I would expect the local repository to be set in readonly mode. But it is not. I got the .gitattributes file. And I need to manually change permissions or generate a new .gitattributes file by using 'git lfs track *.ext --lockable' in order to have an automatic switch to readonly mode.

How can I get a readonly management binded to .gitattributes for my local repos?

To me, it looks like only git lfs track triggers a change of permissions in the local repository. I have not found detailed documentation on the lock feature yet, so I may have missed something in the configuration or workflow. 

My configuration:
Server: Windows Server 2012 R2, git integrated into Team Foundation Server 2017
Clients: git 2.18.0 and git-lfs 2.5.1 for windows x64, on Windows 10 Professional

Thanks for considering this issue.

Margot HONORE

**Comment by ttaylorr** [comment]
> When manually creating a .gitattribute file in some git repository,
> files are not set to readonly. I tried 'git lfs update', and 'git lfs
> install". It shows "Updated git hooks." but permissions on files are
> unchanged unless I use 'git lfs track *.ext --lockable'.

What's happening here is a consequence of your repository's
.gitattribute(s) _not_ being tied to the read- or write-ability of files
in the working copy.

Git LFS manages this state independently during checkout time, and Git
does _not_ update the permissions of files in your working copy based
off of anything in .gitattributes.

That said, Git LFS _will_ respond to you doing things like 'git lfs
pull' or 'git pull' to ensure that you have the most up-to-date set of
locked and unlocked files.

> The only way to get the desired behavior for the moment is to call
> 'git lfs track *.ext --lockable' then edit the .gitattributes file
> manually, wich is inconvenient to do on many machines.

You should not have to do this operation on many machines. Running:

    $ git lfs track "*.ext" --lockable

On one machine and committing/pushing that change to your .gitattributes
file should be sufficient:

    $ git add .gitattributes
    $ git commit -m ".gitattributes: track \"*.ext\" as lockable"
    $ git push origin master

Will (in conjunct with the above) be enough to ensure that all "*.ext"
files are marked as locked by default (and thusly require a "git lfs
lock" to acquire the writing bit on an individual clone.)

> That leads to my other issue: when pulling a repository that has a
> .gitattributes file added, I would expect the local repository to be
> set in readonly mode. But it is not.
>
> How can I get a readonly management binded to .gitattributes for my
> local repos?

Per the above, that should be enough to satisfy what's going on here.
