### ISSUE TITLE
Git LFS lock in Gitlab prevents pushes of new files when unrelated files are locked by other users

### ISSUE THREAD

**Issue by ndelorme** [git-lfs/git-lfs#3178]
Hi there,

I am having trouble with Git LFS locks in Gitlab. Not sure where I should ask the question, so trying my luck here...

Basically the problem is I cannot push new files to the Gitlab repo when other (unrelated) files are locked by other users.

Typical steps triggering the issue (using text files for simplicity):

- create a gitlab project "testprj", enable git LFS support, with members "user1" and "user2"

- define files \*.txt lockable with `git lfs track "*.txt" --lockable`

- user1 creates file test1.txt with `echo "test1">test1.txt`, locks, commits and pushes test1.txt (but does not unlock it)

- user2 creates file test2.txt with `echo "test2">test2.txt`, locks, commits, pulls text1.txt and pushes test2.txt

Then despite no modifications were made to test1.txt, the push fails with:

```
remote: GitLab: The path 'test1.txt' is locked in Git LFS by user1
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@gitlab:testprj.git'
```
Any idea what I am doing wrong?

The only workaround I found so far is to remove all locks from other users with `git lfs unlock -f` and then push. Not ideal. It seems that once the file exists on the gitlab remote then the issue disappears and every user can modify/push freely even when locks on other files exist.

I am running Gitlab CE 11.1.4, git-lfs version 2.4.0, git version 2.14.1.

Thanks

Nicolas.

**Comment by ttaylorr** [comment]
> Then despite no modifications were made to test1.txt, the push fails with:
>
> ```
> remote: GitLab: The path 'test1.txt' is locked in Git LFS by user1
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@gitlab:testprj.git'
> ```
>
> Any idea what I am doing wrong?

Is it possible that there _are_ changes to test1.txt included in your
push? I'm not sure exactly from your description above, but it sounds
like that could be a potential problem.

To diagnose this further, you'd want to look at all of the commits that
this user was pushing and ensure that they don't produce any diff on
test1.txt when compared to what the latest commit present on GitLab is.

If this is the case, then I think that everything is functioning as one
would expect.

If that's not the case, this is a bug with GitLab's implementation of
the Git LFS API specification, and should be sent to their support@
email address.

**Comment by ndelorme** [comment]
Thanks Taylor,

I have checked that there are no changes to test1.txt in the push, so forwarded to GitLab support.

**Comment by ttaylorr** [comment]
> I have checked that there are no changes to test1.txt in the push, so
> forwarded to GitLab support.

Thanks, and do let us know what comes of this. If there's a bug that Git
LFS is responsible for, we would be more than happy to fix it up :-).
