### ISSUE TITLE
fatal: smudge filter lfs failed | [404] Object does not exist on the server

### ISSUE THREAD

**Issue by shaunrandall** [git-lfs/git-lfs#3182]
Solution I found: `git lfs fetch --all`

I'm having problems with a file that someone else has pushed. This might be a bug.

I have tried:
1) Verifying that others can pull and make changes to the file 
2) Having someone else make changes to the file and push
3) git lfs install --force
4) git lfs pull
5) Consistently resetting my commit and pulling again.
6) Setting up a new SSH token on gitlab

I am about to try:
1) Re-cloning the repo

### Gitbash Pull Error
```
Updating dfce1033..6f15f3b0
Downloading Content/BattleRoyale/Maps/AbilityTestMap.umap (1.0 MB)
Error downloading object: Content/BattleRoyale/Maps/AbilityTestMap.umap (75526a0): Smudge error: Error downloading Content/BattleRoyale/Maps/AbilityTestMap.umap (75526a0565bf2eeec3d6c3d1a0f622a988bdfc667f0889acb9580448db3570bc): [75526a0565bf2eeec3d6c3d1a0f622a988bdfc667f0889acb9580448db3570bc] Object does not exist on the server: [404] Object does not exist on the server


Errors logged to C:\Users\shaun\Documents\battle_royale_gas\.git\lfs\objects\logs\20180811T201448.3702388.log
Use git lfs logs last to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/BattleRoyale/Maps/AbilityTestMap.umap: smudge filter lfs failed`
```

### Git LFS Log (funny thing is ttaylor locations appear all over this)
[20180811T203311.5617596.log](https://github.com/git-lfs/git-lfs/files/2280702/20180811T203311.5617596.log)

### Git LFS Env
`Endpoint (gitlab)=https://gitlab.valhalla.team/valhalla/game.git/info/lfs (auth=none)
  SSH=git@gitlab.valhalla.team:valhalla/game.git
LocalWorkingDir=C:\Users\shaun\Documents\battle_royale_gas
LocalGitDir=C:\Users\shaun\Documents\battle_royale_gas\.git
LocalGitStorageDir=C:\Users\shaun\Documents\battle_royale_gas\.git
LocalMediaDir=C:\Users\shaun\Documents\battle_royale_gas\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\shaun\Documents\battle_royale_gas\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\shaun\Documents\battle_royale_gas\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"`

**Comment by shaunrandall** [comment]
So I found a fix:

git lfs fetch --all

I don't know why it fixed it or worked, but now if you have the same problem you have the answer too.

**Comment by ttaylorr** [comment]
I'm sorry that you are having trouble, but I'm glad that you were able
to fix it :-). My apologies for the slower-than-usual response time, I
was out of the office last week and am just catching up on reading my
mail.

One thing that's possible is that you had checked out a commit that
contained a Git LFS pointer that _had_ been removed from the remote,
hence the 404 error code.

This is possible because of culmination of a few things:

  1. 'git lfs pull' pulls Git LFS objects reference-able in the current
      checkout, and does _not_ fetch new commits or new objects since
      your most recent checkout.

That said, it looks like everything is going normally, now. In the
future, I'd recommend:

```ShellSession
$ git pull <origin> <branch>
```

after ensuring that `git lfs install` has been run successfully once.
