### ISSUE TITLE
Git LFS can be installed but new v1.x Github Desktop does not recognize it

### ISSUE THREAD

**Issue by joel-loewenstein** [git-lfs/git-lfs#3186]
Hello,
i have installed LFS on a macOS 10.13.6 using the actual package. I got 'LFS intitalized properly' message after following the instructions for the tar package. Now i could still not see any Git-LFS tab on the repository settings tab within the new atom based 1.x client. I was puzzled and checked the parallel installed old GitHub desktop v223. There i could see the tab.

Is there any way how to enable LFS for the new GitHub Desktop client based on atom.
Is this an install issue with LFS or is it a GitHub Desktop issue?

**Comment by shiftkey** [comment]
@joel-loewenstein GitHub Desktop (Electron version) supports Git LFS, but the UI for managing the files you are tracking is not currently implemented - see https://github.com/desktop/desktop/issues/69 for the tracking issue.

**Comment by joel-loewenstein** [comment]
Thanks. I had not searched using this context but a malfunction ... hence closing.
