### ISSUE TITLE
`lfs track` fails to recognise a previously tracked file if the filename contains escaped chars

### ISSUE THREAD

**Issue by leonid-s-usov** [git-lfs/git-lfs#3189]
`lfs track` fails to recognise a previously tracked file if the filename contains escaped chars

**Reproduce**
* add "file with space.ext"
* repeatedly call `git lfs track "file with space.ext"`
* **Actual** 
identical escaped attribute pattern lines will be added to `.gitattributes` once per every invocation of the command
* **Expected** 
on the second and subsequent invocations the pattern shouldn't be added
***
https://github.com/git-lfs/git-lfs/blob/6e1f0f91882a71dce85b2a6a2bc40a9ff5044d10/commands/command_track.go#L140

looks like the line above must unescape the pattern first
```
delete(changedAttribLines, unescapeAttrPattern(pattern))
```

**Comment by leonid-s-usov** [comment]
I have honestly tried to make a pull request, but just can't manage the testing part. Looks like there's no framework in place to easily test this kind of command logic; should one create a test git repo and run commands on it? Or would one have to introduce injection into the command logic and spoof the responses of the git query core and also spoof the filesystem to check the format of the created `gitattributes`? 

The issue itself seems quite simple though

**Comment by ttaylorr** [comment]
> I have honestly tried to make a pull request, but just can't manage
> the testing part. Looks like there's no framework in place to easily
> test this kind of command logic; should one create a test git repo and
> run commands on it?

We would love a pull request, and I'm so glad that you are interested in
writing one. I'd be more than happy to help point you in the right
direction.

To test this sort of thing, you're definitely on the right track that
what we essentially want to do is run some bash in a repository fixture
that we have created to make sure that it's working as expected.

For that, we have the `t` directory, and within it the `t/t-track.sh`
(and `t/t-untrack.sh`) files, which are effectively those shell scripts.

To add to them, include the following lines:

```
begin_test "track: escaped pattern in .gitattributes"
(
  set -e

  # your test here
)
end_test
```

You can look at prior tests in that file or others for a guideline of
how to get started, as well as the t/README.md file, and asking
questions here.

That all said though, I'm wondering if we _can_ make this change in the
v2.x.y era. I'm inclined to believe that this is breaking behavior,
which means that we technically shouldn't, although I don't suspect that
anyone is depending on this behavior as it manifests itself today.

What do you think?

**Comment by leonid-s-usov** [comment]
Nice, that seems quite manageable this way. On it

**Comment by leonid-s-usov** [comment]
> That all said though, I'm wondering if we _can_ make this change in the
v2.x.y era. I'm inclined to believe that this is breaking behavior,
which means that we technically shouldn't, although I don't suspect that
anyone is depending on this behavior as it manifests itself today.

Well I wouldn't think about it that way at all. To me that doesn't look like anything breaking. Actually, the issue is annoying but doesn't involve side effects apart from an unbound growth of attributes file.

wait I haven't tested how it behaves at `untrack`ing.. Could be that it results in a kind of "nested tracking" so that one would need to call untrack as many times as track :) 

In any case, I don't feel like I have enough context and background to decide here, but I'd vote for fixing it right away.

**Comment by leonid-s-usov** [comment]
just one other question.. how do I run the test? If you could answer now would be helpful.

**Comment by leonid-s-usov** [comment]
found the README :)

**Comment by leonid-s-usov** [comment]
sorry for spamming. I'm almost there, but don't seem to get how the tests in `t` would take the fresh binary of the git-lfs to run the tests agains. It seems like the test is run with my system git-lfs. Is it about PATH management?

**Comment by ttaylorr** [comment]
> sorry for spamming. I'm almost there, but don't seem to get how the
> tests in `t` would take the fresh binary of the git-lfs to run the
> tests agains.

Make sure to run `make` in the root directory of the repository again.
For example:

  $ make -B ./t-track.sh
  $ cd .. && make
  $ cd t

By default, Git LFS tests look in bin/git-lfs (or bin/git-lfs.exe on
Windows) for the binary, and _then_ to $PATH.
