### ISSUE TITLE
core.hooksPath isn't expanded

### ISSUE THREAD

**Issue by ktchen14** [git-lfs/git-lfs#3211]
In my `gitconfig` I have:

```ini
[core]
	hooksPath = ~/.githooks
```

This leads to `git lfs` creating a directory called `~` wherever I attempt to use it. The problem appears to be that the tilde in the hook directory isn't expanded.

**Comment by bk2204** [comment]
Thanks for reporting this.  I can indeed confirm that we're not expanding paths here.

Let me see if I can come up with a fix for this.
