### ISSUE TITLE
Permission denied when trying to git lfs pull

### ISSUE THREAD

**Issue by samfranks** [git-lfs/git-lfs#3216]
Hi,

New to Git LFS as of two days ago, and a fairly new Git user. I'm working on two different machines (home and work), and trying to clone a local repo on my work machine from my remote that contains a large file within my project.

I'm getting the following error on a fresh clone of my remote. I have checked that Git LFS is initialised with `git lfs install` on my work machine.

`Cloning into 'eurobirdportal_euring'...
Enter passphrase for key '/c/Users/samf/.ssh/id_rsa':
remote: Counting objects: 32, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 32 (delta 4), reused 31 (delta 3), pack-reused 0
Receiving objects: 100% (32/32), 5.45 MiB | 523.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.`
`Downloading data/ebp_data/euring_comp.csv (121 MB)
Error downloading object: data/ebp_data/euring_comp.csv (2789f4d): Smudge error: Error downloading data/ebp_data/euring_comp.csv (2789f4d978eab3a6264ca7b98749660fef81b11bebf4669b43e5c7590d241d8f): batch request: ssh_askpass:
 exec(rpostback-askpass): No such file or directory
Permission denied (publickey).: exit status 255
Errors logged to C:\Users\samf\Documents\Git\eurobirdportal_euring\.git\lfs\logs\20180831T124829.6142985.log
Use git lfs logs last to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/ebp_data/euring_comp.csv: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
batch request: ssh_askpass: exec(rpostback-askpass): No such file or directory
Permission denied (publickey).: exit status 255
error: failed to fetch some objects from 'https://github.com/BritishTrustForOrnithology/eurobirdportal_euring.gi
t/info/lfs'`

I have tried [this](https://github.com/git-lfs/git-lfs/issues/911#issuecomment-169998792) solution, still no joy, with the same (ish) error:

`batch request: ssh_askpass: exec(rpostback-askpass): No such file or directory
Permission denied (publickey).: exit status 255
error: failed to fetch some objects from 'https://github.com/BritishTrustForOrnithology/eurobirdportal_euring.gi
t/info/lfs'`

**Comment by ttaylorr** [comment]
Hi, Sam -- thanks for letting us know and I'm sorry that you're having
trouble. It looks like the credential helper that you're trying to
execute ('rpostback-askpass') does not exist.

I'm not familiar with this tool (so you may have to forward this request
back to them) but it's certainly possible that the tool _is_ installed,
but isn't being found correctly.

Can you re-run the command with 'GIT_TRACE=1' in your environment and
post the output here (making sure to remove sensitive details)? That
should help us pin things down.

**Comment by samfranks** [comment]
I solved the problem, by removing the passphrase needed for my ssh key on my work machine. I wasn't having any trouble cloning to a new repo on my home machine, and it didn't have a passphrase, so tried that out and it sorted my issue. I don't need the passphrase, so I should be sorted thanks!

**Comment by lrq3000** [comment]
Please reopen this issue, it is still happening, and using a passphrase is an added security measure, to avoid using my github account password.

**Comment by lrq3000** [comment]
Steps to reproduce:
1. create a git (eg, tested on github) repository with lfs, push a commit
2. try to clone it using the SSH address (not the HTTPS)

The error will be raised at the step of downloading the LFS parts, making the pull fail and preventing any synchronization (push, pull, etc). This error does not happen when using the HTTPS address to clone (or pull/push).

**Comment by bk2204** [comment]
Hey, can you open a new issue for this report, please, @lrq3000, and include the output when you run the command with `GIT_TRACE=1`? That will let us see whether your issue is the same thing or a different issue.

**Comment by EliasCK** [comment]
This is annoying

**Comment by spikegee** [comment]
I have the same issue, when cloning a repo through ssh, when it arrives at the lfs part for some reason it tries to re-authenticate to the same server and fails without prompting for ssh password:
23:48:17.006084 trace git-lfs: run_command: ssh -p 22 -- john@192.168.XX.XX git-lfs-authenticate shareX/git-repositories/myproject.git download

**Comment by bk2204** [comment]
Hey,

If you're seeing a problem with SSH pushes, please open a new issue and fill out the issue template so we can help you more effectively.  Be aware that if you're using the built-in Windows OpenSSH, it's broken and doesn't work; you need to switch to the Git for Windows one.

**Comment by jaaywags** [comment]
I resolved this issue by just using git bash instead of command prompt or powershell. No other changes were needed.

**Comment by ivatilca** [comment]
I am used to work with Powershell... still having this same issue had to use Git Bash :(

**Comment by vidyakamal** [comment]
This was resolved after replacing the ed25519 key with the RSA key.

**Comment by zosrothko** [comment]
Solved on Windows10 by run start-ssh-agent before

**Comment by bk2204** [comment]
`GIT_SSL_NO_VERIFY=1` turns of TLS verification and means that everyone on the network between you and the server can read and modify the data being sent.  It's a completely insecure option.  Please don't recommend that here.

**Comment by xucian** [comment]
> Solved on Windows10 by running the command: start-ssh-agent before git pull

thank you, my friend!

**Comment by Snipe3000** [comment]
Interesting, none of the above seems to help me get around this mess.

**Comment by MGlolenstine** [comment]
> Doesnt work in powershell, no matter what you do, but adding the key through git bash worked

This solved my issue.
PowerShell didn't even start the download (I have about 500MB of LFS data), and it timed out after 5minutes reporting 

```
Error downloading object: bigfile.zip (1b91820): Smudge error: Error downloading bigfile.zip (1b918205f8f53761a3590f18eae9511360f86f1fb13a1fd43a6074f7096334ad): batch request: git@gitlab.com: Permission denied (publickey).: exit status 255
```
But Git bash downloaded all of it in under a minute.

**Comment by tele-bird** [comment]
@gleb-t 's solution pointed me in the right direction.

I had to add my SSH key to **every** git command that could possibly need to interact with git LFS: 

`ssh-agent bash -c 'ssh-add /Users/phadley/.ssh/gitkraken_rsa; git clone git@github.com:MyOrg/myrepo.git'`
`ssh-agent bash -c 'ssh-add /Users/phadley/.ssh/gitkraken_rsa; git checkout dev'`
`ssh-agent bash -c 'ssh-add /Users/phadley/.ssh/gitkraken_rsa; git lfs pull`

**Comment by FingerlessGlov3s** [comment]
From what I can tell I'm having the same issue, when using git outside of the MINGW64, when you do `git lfs pull` it's not prompting for my passphrase for my SSH key. When doing it via MINGW64, a popup windows appears asking for it. If you do `git pull` in either MINGW64 or normal cmd prompt for example, it prompts within the console itself for the passphrase. LFS pull then errors when doing it in CMD, until you do it in MINGW64. which then downloads the files needed. It also errored during the `git clone` about LFS, but took my 3 hours to download this repo under CMD, will take just as long under MINGW64 but I can do it if it's also needed.

![image](https://github.com/git-lfs/git-lfs/assets/3495647/a7e2af8b-6d0f-4518-83f2-7505fe789813)

![image](https://github.com/git-lfs/git-lfs/assets/3495647/76976e0f-f011-4d4f-a409-f9625e4554e8)

**Comment by bk2204** [comment]
The reason you get a popup in Git Bash and not elsewhere is because you haven't set up the `SSH_ASKPASS` environment variable.  That is set up automatically for you in Git Bash and not elsewhere.  If you set it to the path of the `ssh-askpass` program, then you'll get a popup like in Git Bash.

If you'd prefer to just use this for Git and Git LFS and not SSH, then you can use `GIT_ASKPASS` instead.

**Comment by FingerlessGlov3s** [comment]
Is there a way to make it prompt in the CLI itself, like `git` does rather then a seporate prompt window?

Or will I have to set `GIT_ASKPASS` and move to having a prompt window for both `git` and `git lfs`

**Comment by bk2204** [comment]
In theory, yes, but the problem is that #1843 exists, which is a bug in Git for Windows, that prevents it from doing so.

**Comment by FingerlessGlov3s** [comment]
Luckly I don't come across LFS too much but hopefully the big will be fixed soon 👍

**Comment by stephane-archer** [comment]
@ttaylorr can you re-open this issue, looking at how much discussion happened you can see that things have not been solved. removing the passphrase is not a proper solution.

**Comment by ionutgherman** [comment]
I have this issue also, even in Linux, WSL or Windows. Stupid lfs. Cannot upload a big file for a commit. Tried everything, nothing works
