### ISSUE TITLE
Building or using GitLFS on Solaris

### ISSUE THREAD

**Issue by BradPV** [git-lfs/git-lfs#3222]
Hi, I was wondering if anyone has found a way to use Git LFS on a Solaris system? I've tried building from source using go 1.10 and got the following feedback:

```
template: main:1:31: executing "main" at <.Module>: can't evaluate field Module in type *load.PackagePublic
git-lfs: skipping fmt, no goimports found at `goimports` ...
GOOS= GOARCH= go build -ldflags=" -X github.com/git-lfs/git-lfs/config.GitCommit=9f15bf2f -s -w " -gcflags=" " -o ./bin/git-lfs ./git-lfs.go
# github.com/git-lfs/git-lfs/vendor/github.com/olekukonko/ts
vendor/github.com/olekukonko/ts/ts_x.go:19:30: undefined: syscall.SYS_IOCTL
# github.com/git-lfs/git-lfs/vendor/github.com/kr/pty
vendor/github.com/kr/pty/ioctl.go:6:29: undefined: syscall.SYS_IOCTL
vendor/github.com/kr/pty/util.go:26:3: undefined: syscall.SYS_IOCTL
Makefile:199: recipe for target 'bin/git-lfs' failed
make: *** [bin/git-lfs] Error 2
```

The current need is to compile another program which requires GitLFS and up until now I have to use a workaround to not require it.

That was using the files supplied by `go get github.com/github/git-lfs` and have also tried through using a cloned repository and all have failed so far.

**Comment by ttaylorr** [comment]
> Hi, I was wondering if anyone has found a way to use Git LFS on a
> Solaris system?

Thanks for letting us know that this wasn't possible before.
Incidentally, this is the only issue that comes up when I search for
"Solaris" over git-lfs issues :-).

syscall.S_IOCTL is indeed private on the Solaris version of package
syscall, so the compilation failure is expected.

However, it looks like the library that was causing this to fail has
moved upstream to support Solaris, so I've opened a pull request to
vendor that version of the code instead, which should enable you to
build Git LFS on Solaris.

**Comment by BradPV** [comment]
Yeah, I've been searching for a while personally and haven't really found anything too useful, thank you for your helpful reply ttaylorr, hopeful to hear how it goes after that. 👍

**Comment by thewafflecode** [comment]
Not sure #3223 fixes this.    Should this be re-opened or a new issue filed?

Anyway, as originally reported, both `github.com/olekukonko/ts` and `github.com/kr/pty` had problems.  #3223 updated only `ts` but not others.

This is what I am seeing using the system-provided version of Go.  (Note the `sort.Slice` issue as well.)
```
$ go version
go version go1.7.6 solaris/amd64
$ go get github.com/git-lfs/git-lfs
# github.com/git-lfs/git-lfs/vendor/github.com/kr/pty
mygopath/src/github.com/git-lfs/git-lfs/vendor/github.com/kr/pty/ioctl.go:6: undefined: syscall.SYS_IOCTL
mygopath/src/github.com/git-lfs/git-lfs/vendor/github.com/kr/pty/util.go:26: undefined: syscall.SYS_IOCTL
# github.com/git-lfs/git-lfs/vendor/github.com/git-lfs/gitobj/pack
mygopath/src/github.com/git-lfs/git-lfs/vendor/github.com/git-lfs/gitobj/pack/set.go:107: undefined: sort.Slice
$
```

Testing with a private build of the latest Go removed the `sort.Slice` error, but the `syscall.SYS_IOCTL` issue remained.  It would be ideal if git-lfs could work using the system-supplied version of Go and Git.

More version bits from my box:
```
$ pkg info entire | grep Version
       Version: 11.4 (Oracle Solaris 11.4.4.4.0)
$ pkg info golang | grep Version
          Version: 1.7.6.1 (1.7.6-1)
$ pkg info git | grep Version
       Summary: git - Fast Version Control System
       Version: 2.15.3
$ git --version
git version 2.15.3

```

**Comment by bk2204** [comment]
A new issue would be great if you could.
