### ISSUE TITLE
How do I recover the original files in LFS

### ISSUE THREAD

**Issue by dareenzo** [git-lfs/git-lfs#3225]
I was trying to use LFS and did a `git lfs import --everything` (thinking I knew what I was doing). Then pushed force to master on GH and only notticed now that all files have the following content

```
version git-lfs.github.com/spec/v1
oid sha256:6eeca21f5fdefa6879a0840edf976ed219dc5af92d8d507a1a06dd5e8ba2b95f
size 570
```

Is there a way I can recover the original files?

**Comment by dareenzo** [comment]
Used reflog to got back some commits, and recreated the repo on GH.

Thanks

**Comment by ttaylorr** [comment]
> Then pushed force to master on GH and only notticed now that all files
> have the following content

Hi Paulo, we can definitely get that fixed up. Git LFS pushes files in
(2) phases. For a given push,

  1. Push Git LFS objects contained in the push range to the remote Git
     LFS server.

  2. Once that's done, proceed with the normal `git push`.

So, if you have Git LFS installed but haven't run `git lfs install` at
least once from the directory of your repository, then the first stage
won't happen.

I'd recommend that you do the following (in your repository):

  $ git lfs install
  $ git lfs push --all

And see if that fixes things up.

Alternatively, Git LFS migrate will leave the files in your
`.git/lfs/objects` directory. If that fails, run `git reflog` to
checkout a revision before migrating.

**Comment by shivChitinous** [comment]
I have the same issue, except I ended up deleting the repository after this happened. I am currently trying to restore the repository from GitHub (it was not forked). Will I still be able to recover my files?

**Comment by bk2204** [comment]
If you've pushed the LFS files to the remote repository, then yes.  Otherwise, if you haven't and you don't have a copy of them elsewhere, then the answer is no.
