### ISSUE TITLE
Track file without extension

### ISSUE THREAD

**Issue by tcamin** [git-lfs/git-lfs#3234]
On our repo we have several large binary files that have no filename extension. Is there a way to track these files with LFS without having to explicitly list them all?

**Comment by bk2204** [comment]
It’s possible to track files using any filename pattern that Git supports in the `.gitattributes` file, so if the files you want to track are in the same directory or all start with a prefix, you can use that as a pattern:

```sh-session
$ git lfs track 'assets/**'
# or
$ git lfs track 'asset-*'
```

You can see the supported syntax in the `gitattributes` and `gitignore` manpages. 

If there isn't some set of specific patterns that matches them, then you'd have to explicitly list them all.

**Comment by tcamin** [comment]
Thanks for the quick reply!
