### ISSUE TITLE
Migrate Import --fixup returning git/gitattr: malformed attribute: text

### ISSUE THREAD

**Issue by jackknobel** [git-lfs/git-lfs#3254]
Hey there,

Having an issue migrating a repo over to git lfs, after running for over ~19 hours (it's the [UE4 ](https://github.com/EpicGames/UnrealEngine) repo) it fails, reporting:
`git/gitattr: malformed attribute: text0/63083)`

The .gitatrributes contents are the following:
```
# Unreal Engine file types.
*.uasset filter=lfs diff=lfs merge=lfs -text
*.umap filter=lfs diff=lfs merge=lfs -text

# Raw Content file types.
*.fbx filter=lfs diff=lfs merge=lfs -text
*.3ds filter=lfs diff=lfs merge=lfs -text
*.psd filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.xcf filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text

# Jenkins Artifact Types
*.dll filter=lfs diff=lfs merge=lfs -text
*.pdb filter=lfs diff=lfs merge=lfs -text
*.lib filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text

# Other binary blob/content
*.res filter=lfs diff=lfs merge=lfs -text
*.a filter=lfs diff=lfs merge=lfs -text
*.bc filter=lfs diff=lfs merge=lfs -text
*.bz2 filter=lfs diff=lfs merge=lfs -text
*.tar filter=lfs diff=lfs merge=lfs -text
*.pak filter=lfs diff=lfs merge=lfs -text
*.dat filter=lfs diff=lfs merge=lfs -text
*.bin filter=lfs diff=lfs merge=lfs -text
*.manifest filter=lfs diff=lfs merge=lfs -text
*.so filter=lfs diff=lfs merge=lfs -text

# Anything in `/ContentFolders` dir.
RawContent/**/* filter=lfs diff=lfs merge=lfs -text
Content/**/* filter=lfs diff=lfs merge=lfs -text
Binaries/**/* filter=lfs diff=lfs merge=lfs -text
```
The 'text' portion may be indicative of some line ending issues, is that the case?
If not, is there any command I can run to find out what the problem is?

Running this command on lfs 2.5.1

If you need more info please feel free to ask, thanks heaps!

**Comment by ttaylorr** [comment]
Hi @jackknobel, thanks for letting us know. I think that this is to do with the fact that the code that parses `.gitattribute` files (c.f., package `git/gitattr`) did not understand how to parse `text` (which is implicitly treated as `text=true`).

I prepared the changes necessary to fix this bug in https://github.com/git-lfs/git-lfs/pull/3255, and attached pre-compiled release assets below for all platforms that we target by default.

Would you mind giving these a whirl and letting me know if they fix the issue for you?

[git-lfs-darwin-386-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386205/git-lfs-darwin-386-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-darwin-amd64-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386206/git-lfs-darwin-amd64-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-freebsd-386-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386207/git-lfs-freebsd-386-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-freebsd-amd64-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386199/git-lfs-freebsd-amd64-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-linux-386-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386200/git-lfs-linux-386-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-linux-amd64-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386201/git-lfs-linux-amd64-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-linux-arm64-v2.5.0-113-g5a54097c.tar.gz](https://github.com/git-lfs/git-lfs/files/2386202/git-lfs-linux-arm64-v2.5.0-113-g5a54097c.tar.gz)
[git-lfs-windows-386-v2.5.0-113-g5a54097c.zip](https://github.com/git-lfs/git-lfs/files/2386203/git-lfs-windows-386-v2.5.0-113-g5a54097c.zip)
[git-lfs-windows-amd64-v2.5.0-113-g5a54097c.zip](https://github.com/git-lfs/git-lfs/files/2386204/git-lfs-windows-amd64-v2.5.0-113-g5a54097c.zip)

**Comment by jackknobel** [comment]
Hey @ttaylorr, 

Running the command again now, shall let you know how I go.

Thanks heaps!

**Comment by jackknobel** [comment]
Hey @ttaylorr this worked a treat, thanks heaps! (took 26 hours to run 😬)

**Comment by ttaylorr** [comment]
I'm glad that it worked!

> (took 26 hours to run 😬)

I don't have access to the repository in question, but if I did I'd be happy to look at why this is taking so long (other than "it's just a lot of history".) Let me know!

**Comment by jackknobel** [comment]
Our repo is a merge between UE4 and our internal project, the latter of which is verrryyy small in comparison to the former.

If you did want to have a look it's super easy to get access to the UE4 repo by following the steps outlined here:
https://www.unrealengine.com/en-US/ue4-on-github

But honestly no fret if you don't want too, the comment was meant as an explanation for the delay in my reply!
If however you do end up investigating I'm happy to be a guinea pig for any tests you want some more information on 😃 

Either way, thanks heaps for the help!
