### ISSUE TITLE
Following Wiki page install instruction for docker leads to cert errors for later git clones

### ISSUE THREAD

**Issue by SHuang-Broad** [git-lfs/git-lfs#3256]
Hello,

## problem
I'm following the instructions given on this page:
https://github.com/git-lfs/git-lfs/wiki/Installation
Specifically, I followed 
>Docker Recipes
>For Debian Distros, you can use

```
RUN build_deps="curl ca-certificates" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ${build_deps} && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git-lfs && \
    git lfs install && \
    DEBIAN_FRONTEND=noninteractive apt-get purge -y --auto-remove ${build_deps} && \
    rm -r /var/lib/apt/lists/*
```

`git lfs` can be successfully installed on the image.
However, any `git clone` following that `RUN` leads to an error message

```
fatal: unable to access '<HTTPS_PATH_TO_GIT_REPO>': Problem with the SSL CA cert (path? access rights?)
```

## temporary solution
I do find that removing the line

```
# build_deps is defined to be curl and ca-certificates, where the 2nd is probably related to the cert error
DEBIAN_FRONTEND=noninteractive apt-get purge -y --auto-remove ${build_deps}
```
(temporarily?) solves the problem.

**Comment by ttaylorr** [comment]
Hi Steve, thanks for writing in. I'm not sure what's wrong here, but my
hunch is that this error (which comes from libcurl) is to do with
removing curl from your system.

I don't use this recipe to install Git LFS, so I'm not sure that I would
be _that_ useful in helping answer _why_ this works/doesn't work, but
I'll leave this issue open in case someone else is.

**Comment by bk2204** [comment]
I think the error is due to the fact that the SSL certificate authority certificates are no longer installed when `ca-certificates` is removed.  Since there's no trusted roots, HTTPS doesn't work.  I updated the wiki accordingly with a recipe that seems to work for me (by not removing the `ca-certificates` package).

**Comment by bk2204** [comment]
I'm going to close this now, but if the fixed recipe doesn't work for you, please shout and we'll reopen this issue.
