### ISSUE TITLE
`git push origin master` has not finished

### ISSUE THREAD

**Issue by Mocchaso** [git-lfs/git-lfs#3257]
For 'git push origin master' with Git LFS, I tried work described later.  

- - -

1. In normal Command Prompt of Windows 8.1,  
`cd {my local repository}`

2. `git lfs install`  
-> Command `git lfs version` outputted this.  
`git-lfs/2.5.1 (GitHub; windows amd64; go 1.10.3; git e1628484)`  
I think this is OK.

3. Move a large file to my local repository on Windows Explorer.

4. `git add (a large file)`  
`git add .gitattributes`  

5. `git commit -m "test"`  
Commit has finished successfully.

6. `git push origin master`
After inputting correct user name and password, no texts outputted.

- - -

* Question  
Why has not `git push origin master` finished completely ?  
In 4, is execution order related to this problem ?  
kinds of execution order:  
`git add (a large file)` -> `git add .gitattributes`  
`git add .gitattributes` -> `git add (a large file)`

**Comment by Kaukov** [comment]
In your execution order, I don't see you `git lfs track "(large file or **.large file extension**)"`.
Read the **Usage** section of the README

**Comment by Mocchaso** [comment]
@Kaukov , thank you for commenting!

I'm sorry. I forgot to write about `git lfs track`.

* After doing 2. , I inputted `git lfs track (a large file)`.
When I inputted `git lfs track` again, this command outputted like this:
```
Listing tracked patterns
    (a large file) (.gitattributes)
```
* After inputting `git commit -m "test"`, a command `git lfs ls-files` outputted like this:
```
a8e749c4a3 * (a large file)
```

**Comment by ttaylorr** [comment]
Hi, Koki. This problem is usually related to your credential helper not
being configured properly and thus not asking you for your credentials
in a visible way therefore getting "stuck" forever.

Can you run the same command with 'GIT_TRACE=1' in your environment to
see the last thing that Git is doing before it hangs? That should help
us pin this down. Thanks!

**Comment by Mocchaso** [comment]
Hi, @ttaylorr . Thank you for commenting!

I didn't know how to set `GIT_TRACE=1`, but I resolved it.
`git push origin master` with `GIT_TRACE=1` has succeeded.
Thank you so much!
