### ISSUE TITLE
git lfs clone stuck forever

### ISSUE THREAD

**Issue by thekngmkr** [git-lfs/git-lfs#3265]
git log with verbose on

`$ git clone ssh://git@stash-007.eu.abc.com:7999/tool/test.git
11:12:58.036306 git.c:344               trace: built-in: git 'clone' 'ssh://git@stash-007.eu.abc.com:7999/tool/test.git'
Cloning into 'test'...
11:12:58.039444 run-command.c:626       trace: run_command: 'ssh' '-p' '7999' 'git@stash-007.eu.abc.com' 'git-upload-pack '\''/tool/test.git'\'''
11:13:00.378151 pkt-line.c:80           packet:        clone< 9fdbf511fab68ec8502ce72cd0620f1472c26f35 HEAD\0multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-reachable-sha1-in-want symref=HEAD:refs/heads/master agent=git/2.11.4
11:13:00.378189 pkt-line.c:80           packet:        clone< 9fdbf511fab68ec8502ce72cd0620f1472c26f35 refs/heads/master
11:13:00.378198 pkt-line.c:80           packet:        clone< 0000
11:13:00.379054 pkt-line.c:80           packet:        clone> want 9fdbf511fab68ec8502ce72cd0620f1472c26f35 multi_ack_detailed side-band-64k thin-pack ofs-delta deepen-since deepen-not agent=git/2.15.0
11:13:00.379073 pkt-line.c:80           packet:        clone> want 9fdbf511fab68ec8502ce72cd0620f1472c26f35
11:13:00.379079 pkt-line.c:80           packet:        clone> 0000
11:13:00.379095 pkt-line.c:80           packet:        clone> done
11:13:00.401839 pkt-line.c:80           packet:        clone< NAK
11:13:00.401968 run-command.c:626       trace: run_command: 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 19663 on WS2305' '--check-self-contained-and-connected'
11:13:00.402052 pkt-line.c:80           packet:     sideband< \2Counting objects: 6, done.
remote: Counting objects: 6, done.
11:13:00.402290 pkt-line.c:80           packet:     sideband< \2Compressing objects:  25% (1/4)   \15
11:13:00.402325 pkt-line.c:80           packet:     sideband< \2Compressing objects:  50% (2/4)   \15Compressing objects:  75% (3/4)   \15Compressing objects: 100% (4/4)   \15
11:13:00.402359 pkt-line.c:80           packet:     sideband< \2Compressing objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
11:13:00.402397 pkt-line.c:80           packet:     sideband< PACK ...
11:13:00.402421 pkt-line.c:80           packet:     sideband< \2Total 6 (delta 0), reused 0 (delta 0)
remote: Total 6 (delta 0), reused 0 (delta 0)
11:13:00.402448 pkt-line.c:80           packet:     sideband< 0000
11:13:00.404050 git.c:344               trace: built-in: git 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 19663 on WS2305' '--check-self-contained-and-connected'
Receiving objects: 100% (6/6), done.
11:13:00.448165 run-command.c:626       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet' '--progress=Checking connectivity'
11:13:00.449980 git.c:344               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet' '--progress=Checking connectivity'
11:13:00.453039 run-command.c:626       trace: run_command: 'git-lfs filter-process'
11:13:00.453797 pkt-line.c:80           packet:        clone> git-filter-client
11:13:00.453825 pkt-line.c:80           packet:        clone> version=2
11:13:00.453833 pkt-line.c:80           packet:        clone> 0000
11:13:00.459622 trace git-lfs: exec: git 'version'
11:13:00.462970 trace git-lfs: exec: git 'config' '-l'
11:13:00.464693 trace git-lfs: Install hook: pre-push, force=false, path=/home/user007/git/test/.git/hooks/pre-push
11:13:00.464803 trace git-lfs: Install hook: post-checkout, force=false, path=/home/user007/git/test/.git/hooks/post-checkout
11:13:00.464911 trace git-lfs: Install hook: post-commit, force=false, path=/home/user007/git/test/.git/hooks/post-commit
11:13:00.464992 trace git-lfs: Install hook: post-merge, force=false, path=/home/user007/git/test/.git/hooks/post-merge
11:13:00.465063 trace git-lfs: Initialize filter-process
11:13:00.465148 pkt-line.c:80           packet:        clone< git-filter-server
11:13:00.465170 pkt-line.c:80           packet:        clone< version=2
11:13:00.465181 pkt-line.c:80           packet:        clone< 0000
11:13:00.465189 pkt-line.c:80           packet:        clone> capability=clean
11:13:00.465203 pkt-line.c:80           packet:        clone> capability=smudge
11:13:00.465216 pkt-line.c:80           packet:        clone> capability=delay
11:13:00.465229 pkt-line.c:80           packet:        clone> 0000
11:13:00.465352 pkt-line.c:80           packet:        clone< capability=clean
11:13:00.465373 pkt-line.c:80           packet:        clone< capability=smudge
11:13:00.465388 pkt-line.c:80           packet:        clone< capability=delay
11:13:00.465401 pkt-line.c:80           packet:        clone< 0000
11:13:00.465423 pkt-line.c:80           packet:        clone> command=smudge
11:13:00.465438 pkt-line.c:80           packet:        clone> pathname=temp.dump
11:13:00.465452 pkt-line.c:80           packet:        clone> can-delay=1
11:13:00.465465 pkt-line.c:80           packet:        clone> 0000
11:13:00.465479 pkt-line.c:80           packet:        clone> version https://git-lfs.github.com/spec/v1oid sha256:5b0975adef8a72134329150d233586e4351eedec531b2d54b19b91d2655a6484size 495616
11:13:00.465509 pkt-line.c:80           packet:        clone> 0000
11:13:00.465614 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
11:13:00.467602 trace git-lfs: tq: running as batched queue, batch size of 100
11:13:00.467809 trace git-lfs: filepathfilter: rejecting "temp.dump" via []
11:13:00.467822 trace git-lfs: filepathfilter: accepting "temp.dump"
11:13:00.467859 pkt-line.c:80           packet:        clone< status=delayed
11:13:00.467873 pkt-line.c:80           packet:        clone< 0000
11:13:00.467898 pkt-line.c:80           packet:        clone> command=list_available_blobs
11:13:00.467909 pkt-line.c:80           packet:        clone> 0000
11:13:00.467997 trace git-lfs: tq: sending batch of size 1
11:13:00.468150 trace git-lfs: run_command: ssh -p 7999 -- git@stash-007.eu.abc.com git-lfs-authenticate tool/test.git download
11:13:03.179667 trace git-lfs: api: batch 1 files
11:13:03.179959 trace git-lfs: HTTP: POST https://stash-007.eu.abc.com/scm/tool/test.git/info/lfs/objects/batch
> POST /scm/tool/test.git/info/lfs/objects/batch HTTP/1.1
> Host: stash-007.eu.abc.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: JWT <sshkey>
> Content-Length: 160
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.5.2 (GitHub; linux amd64; go 1.10.3; git 8e3c5c93)
>

`
```

git lfs env 

`$ git lfs env
11:16:10.804526 git.c:576               trace: exec: 'git-lfs' 'env'
11:16:10.804583 run-command.c:626       trace: run_command: 'git-lfs' 'env'
11:16:10.809950 trace git-lfs: exec: git 'version'
git-lfs/2.5.2 (GitHub; linux amd64; go 1.10.3; git 8e3c5c93)
git version 2.15.0

11:16:10.811976 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
11:16:10.813470 trace git-lfs: Error loading current ref: Git can't resolve ref: "HEAD"
11:16:10.814964 trace git-lfs: Error running 'git rev-parse': Failed to call git rev-parse --git-dir --show-toplevel: "fatal: Not a git repository (or any of the parent directories): .git\n"
11:16:10.814994 trace git-lfs: exec: git 'config' '-l'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_CURL_VERBOSE=1
GIT_TRACE=1
GIT_TRACE_PACKET=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
11:16:10.821448 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
11:16:10.821468 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
11:16:10.821537 trace git-lfs: filepathfilter: rejecting "tmp" via []
11:16:10.821551 trace git-lfs: filepathfilter: accepting "tmp"
```
`

$ git --version
```
11:16:45.378838 git.c:344               trace: built-in: git 'version'
git version 2.15.0

```
$ git lfs version
```
11:16:53.411652 git.c:576               trace: exec: 'git-lfs' 'version'
11:16:53.411699 run-command.c:626       trace: run_command: 'git-lfs' 'version'
git-lfs/2.5.2 (GitHub; linux amd64; go 1.10.3; git 8e3c5c93)
```

**Comment by ttaylorr** [comment]
Hi thekngmkr, thanks for opening this issue and I'm sorry that you're
having trouble.

From the logs above, it seems that the last thing your Git LFS client
does is try and contact the Git LFS API server by sending an batch API
request. So, it's entirely possible that there is a connection issue
between you and the server, or, that the server isn't responding
properly.

Can you please try and rule out both of those?

**Comment by thekngmkr** [comment]
it was proxy issue fixed it thank you taylorr

**Comment by predatorscan** [comment]
> it was proxy issue fixed it thank you taylorr

Hi thekngmkr,
I have the same issue. Could you please tell me how you resolved the issue?

**Comment by byung-u** [comment]
@thekngmkr  Thank you.

In my case. 
elb security group rule issue.
