### ISSUE TITLE
can't push in git-lfs

### ISSUE THREAD

**Issue by RaphSC2** [git-lfs/git-lfs#3269]
I everyone,

when I try to push in my git-lfs server, I got this error 

Fatal error: Server error: https://"my-lfs-server"/3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51/313738
error: failed to push some refs to 'git@gitlab.server.com/tests.git'

GIT_TRACE=1 git push 
10:29:29.773606 git.c:371               trace: built-in: git 'push'
10:29:29.774546 run-command.c:350       trace: run_command: 'ssh' 'git@gitlab.server.com' 'git-receive-pack '\''tests.git'\'''
10:29:30.592299 run-command.c:350       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@gitlab.server.com:/tests.git'
10:29:30.595451 git.c:600               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@gitlab.tests.git'
10:29:30.595535 run-command.c:350       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@gitlabtests.git'
10:29:30.603273 trace git-lfs: exec: git 'version'
10:29:30.608272 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:29:30.613230 trace git-lfs: exec: git 'config' '-l'
10:29:30.616141 trace git-lfs: pre-push: refs/heads/master 333426bf8c203a0972f8440720ebb1dc5578dfbb refs/heads/master 609eb6823992406a8bef9767c22dcd58ef7090a7
10:29:31.434503 trace git-lfs: run_command: ssh -- git@gitlab.server.com git-lfs-authenticate tests.git upload
10:29:32.289939 trace git-lfs: HTTP: POST https://gitlab.-tests.git/info/lfs/locks/verify
10:29:32.576838 trace git-lfs: HTTP: 200
10:29:32.577019 trace git-lfs: HTTP: {"ours":[],"theirs":[]}
10:29:32.577111 trace git-lfs: tq: running as batched queue, batch size of 100
10:29:32.577276 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
10:29:32.578688 trace git-lfs: run_command: git cat-file --batch
10:29:32.583885 trace git-lfs: tq: sending batch of size 1                                                                                                                                                         
10:29:32.584130 trace git-lfs: ssh cache: git@gitlab.server.com git-lfs-authenticate railway/jenkins/ci-e2e-tests.git upload
10:29:32.584414 trace git-lfs: api: batch 1 files
10:29:32.584583 trace git-lfs: HTTP: POST https://gitlab.server.-tests.git/info/lfs/objects/batch
10:29:32.943722 trace git-lfs: HTTP: 200
10:29:32.943868 trace git-lfs: HTTP: {"objects":[{"oid":"3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51","size":313738,"actions":{"upload":{"href":"https://gitlab.tests.git/gitlab-lfs/objects/3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51/313738","header":{"Authorization":"Basic bWRyZWFudDE6WTdza0h0ZkRZUXp5TG5DbnhkR3JzMlZhLWcySlJYQkMtZExQN21iRi15SmZuZkJjVFE="}}}}]}
10:29:32.944123 trace git-lfs: tq: starting transfer adapter "basic"
10:29:32.944682 trace git-lfs: HTTP: PUT https://gitlab.-tests.git/gitlab-lfs/objects/3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51/313738                  
10:29:33.022428 trace git-lfs: HTTP: 502
10:29:33.022559 trace git-lfs: tq: retrying object 3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51: Fatal error: Server error: https://gitlab.tests.git/gitlab-lfs/objects/3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51/313738 from HTTP 502
10:29:33.022621 trace git-lfs: tq: enqueue retry #1 for "3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51" (size: 313738)
10:29:33.022654 trace git-lfs: tq: sending batch of size 1
10:29:33.022800 trace git-lfs: ssh cache: git@gitlab.expandium.com git-lfs-authenticate railway/jenkins/ci-e2e-tests.git upload
10:29:33.022849 trace git-lfs: api: batch 1 files
10:29:33.022972 trace git-lfs: HTTP: POST https://gitlab.tests.git/info/lfs/objects/batch
10:29:33.319795 trace git-lfs: HTTP: 200
10:29:33.319909 trace git-lfs: HTTP: {"objects":[{"oid":"3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51","size":313738,"actions":{"upload":{"href":"https://gitlab.tests.git/gitlab-lfs/objects/3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51/313738","header":{"Authorization":"Basic bWRyZWFudDE6WTdza0h0ZkRZUXp5TG5DbnhkR3JzMlZhLWcySlJYQkMtZExQN21iRi15SmZuZkJjVFE="}}}}]}
10:29:33.320168 trace git-lfs: tq: starting transfer adapter "basic"
10:29:33.320584 trace git-lfs: HTTP: PUT https://gitlab.-tests.git/gitlab-lfs/objects/3e29f8d5c0b21a9d3f48a8c754eda8d8f1fa221e89f90eb31c9bec41d0fd8a51/313738                  
10:29:33.387259 trace git-lfs: HTTP: 500

Software version

- GitLab 10.5.1
- GitLab Shell 6.0.3
- GitLab Workhorse v3.6.0
 -GitLab API v4
- Ruby 2.3.6p384
- Rails 4.2.10
- postgresql 9.6.5 

Debian 8.11 Kernel 3.16

Thank you,

best regards,
Raphaël

**Comment by bk2204** [comment]
Hi, this looks like you're getting 500 and 502 errors from the server, which indicate some sort of problem on the server side.  The 502 is "bad gateway" indicating some potential problem with the nginx that may be used in GitLab; I'm not sure of the cause of the 500.

Can you check that your GitLab instance is in an okay state and that Git LFS is enabled on the server side (and if necessary, for your repository)?

**Comment by RaphSC2** [comment]
Hi, thank you for your answer.
all repository in my gitlab server work fine. only push in git-lfs repository dosen't work.
I try to gitlab-ctl restart and reconfigure. Reconfigure and restart was ok but it's dosen't solve the problem.

**Comment by bk2204** [comment]
Hey, I understand that this issue only appears for you when using repositories with Git LFS.  However, the response that your Git hosting server (in this case, GitLab) provides isn't within our control.  If you're seeing 500 or 502 errors (which is what it looks like from the output), there's nothing that the client can do to fix that.

I'd suggest you contact GitLab to see if they can help you figure out what's causing these 500 and 502 errors.

**Comment by RaphSC2** [comment]
Hi, I'm the gitlab administrator and Git LFS had work before. An upgrade from GitLab can broke Git LFS?
the server configuration is the same .

thank you,
best regards

**Comment by bk2204** [comment]
It's possible that an upgrade has broken the server-side handling of Git LFS.  I'm not very familiar with GitLab, so I can't say what's going on here.  It _is_ very clear to me, though, that this is an issue on the server side.

**Comment by RaphSC2** [comment]
ok thank you for your answer.

**Comment by RaphSC2** [comment]
ok thank you for your answer.
