### ISSUE TITLE
My LFS file is 1kb

### ISSUE THREAD

**Issue by iliachigogidze** [git-lfs/git-lfs#3273]
I have run command: `git lfs track 'trained_model/*.h5'`
after I run `git lfs ls-files` - it shows 

> 1186855c6a * trained_model/mask_rcnn_plate_0010.h5.

After that I add files, commit and push, but my .h5 file appears 1kb in my repo. What am I doing wrong?

**Comment by bk2204** [comment]
Hey, sorry things aren't working for you.

Can you say a few words about how you determined that your file is 1 kB?  Was it using `ls` or `dir`, or some other way?  Have you run `git lfs install` in your repo?

**Comment by iliachigogidze** [comment]
When I download ZIP of my repo .h5 file is 1 kb there.
I have connected my repo to Heroku. 
When I run my app on Heroku, I get error: `OSError: Unable to open file (file signature not found)`.
I thought if after downloading my files - .h5 is 1kb, maybe that's the case with Heroku as well and that's why my app throws that error (because heroku gets 1kb file, instead of 250mb)

**Comment by bk2204** [comment]
Thanks, that's helpful information.  What you're seeing is #1322.  Basically, `git archive` doesn't include your LFS files in a bare clone, only the pointer files that are used as placeholders in the repository.  So when you download your archive, your LFS files won't be there.

According to the [Heroku documentation](https://devcenter.heroku.com/articles/git#deploying-from-a-branch-besides-master), it doesn't support Git LFS.  You might try reaching out to them to see if they have plans to support it in the future.
