### ISSUE TITLE
help/--help don't work on git-lfs commands

### ISSUE THREAD

**Issue by epitron** [git-lfs/git-lfs#3278]
There are some strange cases where the `help` command or `--help` option fail:

## Primary command:

* `git-lfs help` fails
* `git-lfs --help` fails
* `git lfs help` fails
* `git help lfs` **works**
* `git lfs --help` **works**

## Subcommands:

* `git-lfs ls-files --help` fails
* `git-lfs help ls-files` fails
* `git lfs ls-files --help` fails
* `git lfs help ls-files` fails
* `man git-lfs-ls-files` **works**

**Comment by ttaylorr** [comment]
Hi, Chris -- thanks for writing in. A lot of this behavior for Git LFS
is managed by the third-party library we use to wire up commands:
github.com/spf13/cobra, and github.com/spf13/pflag.

I think that we (@git-lfs/core) should look into this library a little
more and figure out exactly what its behavior is. It has always been a
little mysterious to me.

That said, there are a few that I'm curious about:

> * `git-lfs help` fails
> * `git-lfs --help` fails
> [ ... ]
> * `git-lfs ls-files --help` fails
> * `git-lfs help ls-files` fails

What happens when you run `which git-lfs`, and what does `GIT_TRACE=1
git lfs help` say? This is usually indicating that you have _two_
versions of Git LFS installed (since Git LFS is usually installed as
'git-lfs', and Git expands that by using its extensions mechanism).

**Comment by epitron** [comment]
Thanks for the help, Taylor!

First off, I'd like to say that your response is probably the most humble, understanding, and helpful that I've ever received on github. This is a sterling example of how to treat people who submit issues.

Secondly, I looked deeper into the issue, and it seems that there's a problem with Arch Linux's `git-lfs` package, and not `git-lfs` itself. (I tried your official release binaries, and all of the help commands work perfectly.)

I'll redirect my attention to the Arch packagers, who, I'm sorry to say, are not usually as sunny.

Have a great day!

**Comment by ttaylorr** [comment]
> First off, I'd like to say that your response is probably the most
> humble, understanding, and helpful that I've ever received on github.
> This is a sterling example of how to treat people who submit issues.

Thanks for your kind words, Chris -- I'm glad that we were able to help.

> Secondly, I looked deeper into the issue, and it seems that there's a
> problem with Arch Linux's `git-lfs` package, and not `git-lfs` itself.
> (I tried your official release binaries, and all of the help commands
> work perfectly.)

Sounds good. I suspect that this is similar to these two issues:

  - https://github.com/git-lfs/git-lfs/issues/2013, and
  - https://github.com/git-lfs/git-lfs/issues/3043

And in particular, the later. It looks like the later was closed by
@ssgelm (via 9236a1a3 (Run `go generate` on commands in deb build,
2018-06-22)).

Is it possible that the maintainers of the Git LFS package on Arch Linux
need to also run 'go generate'? That might be potentially helpful
information to share with them if you file an issue there.

**Comment by ssgelm** [comment]
Yeah, that seems to be the problem.  See: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/git-lfs#n23.  @epitron Feel free to point the arch devs my way if I can be of any help here.

I just tested and that seemed to make it work on arch.  Here's a gist with a working PKGBUILD: https://gist.github.com/ssgelm/d118003d86db54a7993c25aa72fc034e

**Comment by epitron** [comment]
Woot! Thanks for the fix.

Side note: could the generate command be part of the default build process?

**Comment by ttaylorr** [comment]
> Side note: could the generate command be part of the default build
> process?

This is a part of the build process (when run with 'make'), but it's
entirely possible that the Arch package maintainers are _not_ using
'make', as support for it in Git LFS was introduced within the last
version.

In other words, running the following will produce the correct artifact:

  $ make

But running the default (from dh_golang, or conventional wisdom from Go)
will not:

  $ go build -o bin/git-lfs -- ./...

If prepended with 'go generate', however, the above would work as
expected.
