### ISSUE TITLE
Can we list Git LFS as a user of tus.io?

### ISSUE THREAD

**Issue by kvz** [git-lfs/git-lfs#3280]
Hi there, sorry for abusing the issue tracker for this question! I noticed that Git LFS supports <https://tus.io> for file uploads. As an LFS user and tus contributor that has got me pretty stoked! Wondering if we can list your project on our homepage?

All the best!

**Comment by bk2204** [comment]
Let me ping @git-lfs/core and see what the consensus on that is.  I don’t personally see a problem with it, but I can’t speak authoritatively for the project.

**Comment by ttaylorr** [comment]
> Let me ping @git-lfs/core and see what the consensus on that is.

I would be more than happy to have Git LFS listed as a user of Tus.io on
the project website. If I am not out of place, I believe that I can
speak authoritatively on this point as the lead maintainer of Git LFS.

I think that in doing so, there are a couple of points to be clear
about:

  1. Git LFS offers several mechanisms by which to upload and download
     files, one of which is through the Tus.io protocol. We also have
     pure HTTP POST/GET, custom transfer adapters, and so on. I mention
     this only to illustrate that Git LFS is not _only_ a Tus.io
     program.

  2. Git LFS is not GitHub, so the implementation that we provide on
     GitHub.com (e.g., the receiving end of a 'git push' when your
     remote is hosted on 'git@github.com') does _not_ support Tus.io.

     Git LFS pushes can be configured to go to a location other than the
     Git remote (e.g., "send my large objects to Artifactory, and my Git
     data to GitHub.com"), so Git LFS users that use GitHub.com to store
     their repositories _can_ use Tus.io, but their large objects won't
     go to GitHub.

**Comment by kvz** [comment]
Thanks team, and thanks also for clarifying @ttaylorr. I'll leave a note here when I've added the logo so you can confirm it's all okay :ok_hand:

**Comment by kvz** [comment]
@ttaylorr it's live now on https://tus.io/ and https://tus.io/blog/2018/09/25/adoption.html, let me know what you think?

**Comment by kvz** [comment]
👌👌
