### ISSUE TITLE
Lock Across Branches

### ISSUE THREAD

**Issue by GuacoIV** [git-lfs/git-lfs#3284]
I've tried to ensure that this is not a duplicate, but forgive me if it is.  Last I checked, locking does not lock a single file across all branches, but only within the current branch.  I'd like to have the ability to lock across all of the branches.  With this ability, I could be confident that someone won't make conflicting binary file changes in work item branches, branched from a release branch, and still allow work item branches to contain non-binary changes.  This would allow for work item branches and pull requests into the release branch.  Instead, currently branch creation is locked and commits for work items on the release branch are either reviewed incrementally (writing down last checked commit hash), or once at the end of the release.  Just for context, the binary files are .docx/Word documentation.

**Comment by GuacoIV** [comment]
Thoughts, anyone?

**Comment by bk2204** [comment]
First, sorry for letting this fall by the wayside.

I think that this is probably a feature that would be useful to a lot of people.  I have a few thoughts:

- Generally, to lock a branch, the server implementation requires that you be able to write to the branch.  In a pull request-based workflow, usually one doesn't have direct write access to the master or release branches, so I'm not sure that it will work for this workflow.
- We would probably want some way to lock a given subset of branches, possibly based on what branch you're on.  I can imagine a lot of people wouldn't want to lock all of the branches, but only some of them.

I'm interested to hear thoughts from other members of @git-lfs/core on this.  I think the first step forward, should we decide to go that direction, would be to add a proposal to `docs/proposals` that outlines what the interface should look like.  There's already some work in that direction, but it isn't very extensive and probably needs updating.

**Comment by ttaylorr** [comment]
There's some really interesting discussion going on about this upstream \[[1](https://public-inbox.org/git/CA+AhR6doYuwoucdcN9aKw7-HxgR-qa6OiN4Dnzcy5rifL8PYvg@mail.gmail.com/)\]. I think that there's an opportunity for a locking semantics that is more broadly applicable than to just Git LFS. I think proposals about how we might integrate that would be really interesting to read, too.

That all said, file locking does currently affect all branches: locks are granted and observed based on the name of the file in question, and are issued without regard to the checked out branch of the caller.

That is to say, if I lock file `A` on branch `B`, and you try to lock `A` on `C`, Git LFS will not let you do so.

**Comment by GuacoIV** [comment]
@bk2204, no problem and sorry about my slow response as well.  I wanted to make sure I could reconcile everything here.  I see what you mean about the subset of branches - that would work.  The concept that this is new does seem to conflict with @ttaylorr's succict statement at the end there:

> That is to say, if I lock file A on branch B, and you try to lock A on C, Git LFS will not let you do so.

So let me try to nail down what's going on here.  I have experienced the quote above to be true, but only when the locking is done by the same user.  The scenario I'm talking about is that I'd like the ability for a lock on file `A` on branch `B` by user `C` to not allow user `D` to take out a lock on file `A` on branch `B` or `E` [any other branch with write access].

**Comment by bk2204** [comment]
That does seem a bit odd.  Can you say what server-side implementation you're using (e.g. GitHub, GitLab, Bitbucket)?  Since this involves the server honoring the locks, that might be relevant.

**Comment by GuacoIV** [comment]
It's being hosted by Microsoft in Azure DevOps/Team Services. When I get the chance I'll restest... just have to get momentary cooperation with another user to do so.

**Comment by GuacoIV** [comment]
I made branches LFSTest1 and LFSTest2 and put a lock on a file while LFSTest1 was checked out.  Then I had a coworker checkout LFSTest2 and try to take a lock out on the same file.  He got "Lock failed: There is an existing lock on this path" which is what I would hope for.  I'm not sure why this didn't work the first time we tried this...maybe our "initialization of" LFS hadn't made it into master yet which caused some effect?  Anyways, I'm glad this worked and I will close out this issue since it seems to be a non-issue after all.

**Comment by kristjanvalur** [comment]
Here I am, requesting the exact opposite semantics.  Being able to lock only one branch is crucial.  Otherwise, people cannot check out their own private branches to work on.  
We should look at locking semantics as they work for Perforce, since for LFS, that is the scenario people will often be coming from.

**Comment by aschmalt** [comment]
> Here I am, requesting the exact opposite semantics. Being able to lock only one branch is crucial. Otherwise, people cannot check out their own private branches to work on.
> We should look at locking semantics as they work for Perforce, since for LFS, that is the scenario people will often be coming from.

I agree that this is a needed feature for our development process.  I can see where a global lock for other development processes would be helpful, but having a branch vs global locking style configuration would be extremely helpful

**Comment by Ecnassianer** [comment]
It sounds like you're asking for the way it works right now? You can git lfs lock a file, and then no one else can commit that file to that branch? Or are you asking for something different?

**Comment by aschmalt** [comment]
Currently the way it works is if User1 locks file A on branch B, and User2 tries to lock file A on branch C, Git LFS will not let you do so as the lock from User1 affects all branches (global lock).   

My request is that it should be configurable to set the locks to be branch specific, so that User1 & User2 can lock the same file as long as they are on different branches.    Therefore running _git lfs locks_ should provide who has the locks on the current branch or all the locks but also include what branch the lock is on so that User2 on a different branch can work on the same file.  

I know some users will think this is a bad idea, but it depends on the work structure your team has chosen to implement.   I can see the value of the global lock in some collaborative instances, but in other cases it would be ideal to have locks be branch specific only.
