### ISSUE TITLE
git-lfs versioned files sporadically showing as modified when cloning with smudge off

### ISSUE THREAD

**Issue by jerick1976** [git-lfs/git-lfs#3287]
I delayed opening this issue because recreating the problem was difficult and I was hopeful that 2.5.1 would fix it.  Unfortunately it has not.  We have a team within our company that is performing git lfs clones with the smudge filter disabled.  They are doing this to separate the cloning processes and provide a way to recover from errors in the git lfs operations independently from the cloning of the original repository.  If lfs controlled files were consistently showing up as modified when smudge was disabled then I could tell them to clone the repo first and then perform a git lfs pull to pull in the lfs files independently but this is not the case.  Which state is the bug?  The one where the files show as modified or the one where the clone shows the files as clean.  This has been tested in 2.1.1, 2.3.4 and 2.5.1 and the issue persists.

>- git clone repo with LFS filters off
    >- git lfs pull to bring in the LFS files
    >
    >Intermittently, LFS tracked objects show up in git status, it varies
    >across the components and sometimes it¹s clean, other times not.
    >
    >Thx, Doug
    >
    >Example for reference:
    >
    >sjc-ads-6017:267> pwd
    >/auto/acmestore/dgh/ngio.lfsissue
    >sjc-ads-6017:268> git reflog
    >5143ab9 HEAD@{0}: checkout: moving from v156_1_s3_sr683505350 to
    >polaris_dev/284
    >f74cafa HEAD@{1}: clone: from
    >https://dscm.esl.cisco.com/git/110/comp-11000429.git
    >sjc-ads-6017:269> git diff
    >sjc-ads-6017:270> git status
    >HEAD detached at polaris_dev/284
    >Changes not staged for commit:
    >  (use "git add <file>..." to update what will be committed)
    >  (use "git checkout -- <file>..." to discard changes in working
    >directory)
    >
    >        modified:   c1100_gfast_fw/c1100_gfast_fw.img
    >        modified:   c1100_shdsl_fw/c1100_shdsl_fw.img
    >        modified:   c1100_vadsl_fw/c1100_vadsl_fw.img
    >        modified:   dreamliner_fw/dm_poe_fpga_fw.bin
    >        modified:   dsp_analogbri_fw/dsp_analogbri_fw.img
    >        modified:   dsp_sp2700_fw/dsp_sp2700_fw.img
    >        modified:   f35_fw/nim_cwan_fw.img
    >        modified:   ngwic_nim_async_fw/nim_async_fw.img
    >        modified:   ngwic_nim_serial_fw/nim_serial_fw.img
    >        modified:   ngwic_nim_ssd_drive_fw/Micron5100MTFDDAK400TCC.pkg
    >        modified:   ngwic_nim_ssd_drive_fw/MicronP400m-MTFDDAK200MAN.pkg
    >        modified:   ngwic_nim_ssd_drive_fw/MicronP400m-MTFDDAK400MAN.pkg
    >        modified:   ngwic_nim_ssd_drive_fw/ST91000640NS.pkg
    >        modified:   ngwic_nim_ssd_drive_fw/UGB88RTB200HE5-CRT-DID.pkg
    >        modified:   ngwic_t1e1_fw/ngwic_t1e1_fw.img
    >        modified:   nim_bri_st_fw/nim_bri_st_fw.img
    >        modified:   nim_ge_fw/nim_ge_fw.img
    >        modified:   nim_shdsl_fw/nim_shdsl_fw.img
    >        modified:   nim_xdsl_fw/nim_xdsl_fw.img
    >        modified:   p_1t_fw/p_1t_fw.img
    >        modified:   sm_10g_fw/sm_10g_fw.img
    >        modified:   sm_1t3e3_fw/sm_1t3e3_fw.img
    >        modified:   sm_async_fw/sm_async_fw.img
    >        modified:   sm_dsp_sp2700_fw/sm_dsp_sp2700_fw.img
    >        modified:   sm_dsp_tilegx_fw/sm_dsp_tilegx_fw.img
    >
    >no changes added to commit (use "git add" and/or "git commit -a")
    >sjc-ads-6017:271> git lfs status
    >On branch HEAD
    >
    >Git LFS objects to be committed:
    >
    >
    >Git LFS objects not staged for commit:
    >
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/c1100_gfast_fw/c1100_gfast_fw
    >.
    >img (LFS: 3bb8a89 -> File: 3bb8a89)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/c1100_shdsl_fw/c1100_shdsl_fw
    >.
    >img (LFS: 056158a -> File: 056158a)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/c1100_vadsl_fw/c1100_vadsl_fw
    >.
    >img (LFS: 07d4add -> File: 07d4add)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/dreamliner_fw/dm_poe_fpga_fw.
    >b
    >in (LFS: a2bbfc5 -> File: a2bbfc5)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/dsp_analogbri_fw/dsp_analogbr
    >i
    >_fw.img (LFS: 234f052 -> File: 234f052)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/dsp_sp2700_fw/dsp_sp2700_fw.i
    >m
    >g (LFS: 240c3d4 -> File: 240c3d4)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/f35_fw/nim_cwan_fw.img (LFS:
    >2736e17 -> File: 2736e17)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_async_fw/nim_async_
    >f
    >w.img (LFS: a17613b -> File: a17613b)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_serial_fw/nim_seria
    >l
    >_fw.img (LFS: f10c6c4 -> File: f10c6c4)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_ssd_drive_fw/Micron
    >5
    >100MTFDDAK400TCC.pkg (LFS: 2a9449d -> File: 2a9449d)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_ssd_drive_fw/Micron
    >P
    >400m-MTFDDAK200MAN.pkg (LFS: e75cc25 -> File: e75cc25)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_ssd_drive_fw/Micron
    >P
    >400m-MTFDDAK400MAN.pkg (LFS: 1d5e865 -> File: 1d5e865)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_ssd_drive_fw/ST9100
    >0
    >640NS.pkg (LFS: 928d069 -> File: 928d069)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_nim_ssd_drive_fw/UGB88R
    >T
    >B200HE5-CRT-DID.pkg (LFS: d7842d7 -> File: d7842d7)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/ngwic_t1e1_fw/ngwic_t1e1_fw.i
    >m
    >g (LFS: a3ce5d1 -> File: a3ce5d1)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/nim_bri_st_fw/nim_bri_st_fw.i
    >m
    >g (LFS: 3d0b53a -> File: 3d0b53a)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/nim_ge_fw/nim_ge_fw.img (LFS:
    >95944b3 -> File: 95944b3)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/nim_shdsl_fw/nim_shdsl_fw.img
    >(LFS: 6969f9a -> File: 6969f9a)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/nim_xdsl_fw/nim_xdsl_fw.img
    >(LFS: de568d3 -> File: de568d3)
    >        ../../../../auto/acmestore/dgh/ngio.lfsissue/p_1t_fw/p_1t_fw.img
    >(LFS: b514c7c -> File: b514c7c)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/sm_10g_fw/sm_10g_fw.img (LFS:
    >0b516c1 -> File: 0b516c1)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/sm_1t3e3_fw/sm_1t3e3_fw.img
    >(LFS: 7571908 -> File: 7571908)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/sm_async_fw/sm_async_fw.img
    >(LFS: 71760cb -> File: 71760cb)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/sm_dsp_sp2700_fw/sm_dsp_sp270
    >0
    >_fw.img (LFS: dba2f88 -> File: dba2f88)
    >        
    >../../../../auto/acmestore/dgh/ngio.lfsissue/sm_dsp_tilegx_fw/sm_dsp_tileg
    >x
    >_fw.img (LFS: d19c38d -> File: d19c38d)
    >

**Comment by jerick1976** [comment]
In this situation the repo in question was created specifically for the purpose of using git-lfs.  There aren't any files with pre-existing non-git-lfs versions in history.  If I read your response correctly though the fact that the files were originally imported with smudge filtering enabled could be causing problems and to fix this issue we would need to redo the import with smudge disabled to permanently clear this issue?

**Comment by ttaylorr** [comment]
> If I read your response correctly though the fact that the files were
> originally imported with smudge filtering enabled could be causing
> problems and to fix this issue we would need to redo the import with
> smudge disabled to permanently clear this issue?

If I'm understanding your response correctly, no. The smudge filter
pertains to checking files out of the index and into your working copy
(i.e., converting from LFS pointer to large object). So having the
smudge filter installed or not shouldn't matter for this purpose.

The clean filter is its dual, and does matter in this case. In any
event, the `git lfs migrate --fixup` command I mentioned earlier should
fix things on your end.
