### ISSUE TITLE
Migration error message

### ISSUE THREAD

**Issue by JamaicanRumCream** [git-lfs/git-lfs#3297]
Hello, I am trying to install LFS and then migrating our repo.
I installed LFS and that was OK.
I added several file types, that appeared OK.
Since our repo is old/mature, I went to migrate the file types I added, and got the below error. The files or types I specified didn't always exist in the app, and certainly not in the 0.0.1 tag (super beta) as the app is now mature.
My question is, what do I do now?
Thanks, Chris

```
paveglioc-mbp:AWKit paveglioc$ git lfs migrate import --include="*.a"
migrate: Fetching remote refs: ..., done                                        
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 128 fatal: bad revision '^refs/remotes/tags/origin/0.0.1'
```

**Comment by bk2204** [comment]
Hey,

So you're not the first person to report this issue; we've seen it in #3281.  We recently put a fix into the `master` branch in pull request #3285.  However, it isn't yet available in any released version.

There has been discussion about v2.6.0 coming out soon, which will include this fix, but in the mean time, you could download the `master` branch and compile your own version if you can't wait.

**Comment by bk2204** [comment]
Unfortunately, I don't.  It's likely going to be sooner rather than later, but I don't have a firm date.  I'll check with other core team members to see what our plans are, since I know there are other issues we've fixed that people would really like to see as well.

**Comment by pbatko** [comment]
I get a very similar error with lfs 2.8.0:
```
(base) pbatko@localhost:~/src/vl/ai (develop) $ git lfs --version
git-lfs/2.8.0 (Fedora 30; linux amd64; go 1.12.7)
(base) pbatko@localhost:~/src/vl/ai (develop) $ git lfs migrate info
migrate: Fetching remote refs: ..., done                                                                                                                                                                                                                                                                                      
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 128 fatal: bad revision '^refs/remotes/origin/1.0.0'                                                                                                                                                                                           

migrate: Sorting commits: ..., done
```

**Comment by apboon** [comment]
Same on most recent version `2.9.2`.

**Comment by bk2204** [comment]
The most recent version is 2.13.2.  Can you try with that version and see if it fixes your problem?
