### ISSUE TITLE
Git LFS is disabled for your instance.

### ISSUE THREAD

**Issue by michaelcw02** [git-lfs/git-lfs#3302]
I am trying to checkout to a branch in which has LFS, but I am getting an error.

Downloading MapAPITests/TestDataConfiguration/MAPBulkImportTestFiles/Contact/Contact_Channel_MAP_QA.xlsm (72 KB)
Error downloading object: MapAPITests/TestDataConfiguration/MAPBulkImportTestFiles/Contact/Contact_Channel_MAP_QA.xlsm (6d2e7f3): Smudge error: Error downloading MapAPITests/TestDataConfiguration/MAPBulkImportTestFiles/Contact/Contact_Channel_MAP_QA.xlsm (6d2e7f3edb6d789b03d4adfed82fd26c1c1f7ebe2f1325a9677a8e4e3f7f83b8): batch response: Git LFS is disabled for your instance.

Errors logged to C:\Users\mchenwan\mapTests\.git\lfs\logs\20181004T113647.1005778.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: MapAPITests/TestDataConfiguration/MAPBulkImportTestFiles/Contact/Contact_Channel_MAP_QA.xlsm: smudge filter lfs failed

Any ideas?

**Comment by michaelcw02** [comment]
Another error message is the following: 

$ git push -u
batch response: Git LFS is disabled for your instance.

**Comment by bk2204** [comment]
Hey, thanks for writing in.  This is a server-side response that means that your implementation (which sounds like it might be a GitHub Enterprise instance) has Git LFS disabled.  You'd need to talk to whomever maintains your implementation about getting that enabled.
