### ISSUE TITLE
MY system crashed

### ISSUE THREAD

**Issue by lms15** [git-lfs/git-lfs#3315]
I have corrupted files in win 10 i have to fix those issue to continue here.
Mamie

**Comment by ttaylorr** [comment]
Hi Mamie, thanks for writing in and sorry that you're having trouble.
Could you describe the nature of the corruption that you're seeing?

If you're seeing files that should be large objects, but are text
pointers, please run:

  $ git lfs install
  $ git lfs checkout .

But if you meant to commit large objects with Git LFS, but didn't, you
can run:

  $ git lfs migrate import --everything --fixup

If neither of those describe the situation that you're in, please let us
know here, and we'd be happy to help out further.

**Comment by lms15** [comment]
Hello, when I login, I issue 1000s of them lol. Does those number of issues means I have already made that many mistakes? I am study code camp and learning what to do. Now I tired and my brain is not working. I will sleep and come back to complete what I started. I did forget to create Hello World. I will change it and delete what I started. Thanks for your guidance.

**Comment by ttaylorr** [comment]
> I issue 1000s of them lol

Oh, no! Could you paste the output of what you're seeing here, so we could narrow down the type of error that you're encountering?

**Comment by ttaylorr** [comment]
Hi @lms15, I'm going to close this issue for now since we haven't heard from you yet. If the problem is resolved, do let us know how you fixed it. If not, please let us know and we'd be more than happy to dive in and figure it out.


Thanks!
