### ISSUE TITLE
smudge filter fails with error: cannot overwrite multiple values with a single value

### ISSUE THREAD

**Issue by sactiw13** [git-lfs/git-lfs#3321]
I have git lfs 2.3.4 version installed on a Ubuntu 16.04 .5 LTS machine, and while applying git patch the smudge filter failed with error: cannot overwrite multiple values with a single value.

It seems this issue was fixed in git lfs version 2.3.4 (#2659) but I am still getting the issue.

admin@ub_16_client:~$ **git lfs env**
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.1)
git version 2.7.4

**Error description:**
```
Checking patch common/container.img...
Applied patch common/container.img cleanly.
warning: filter.lfs.smudge has multiple values
error: cannot overwrite multiple values with a single value
       Use a regexp, --add or --replace-all to change filter.lfs.smudge.

```
**Note:** git version on the machine is pretty old 2.7.4, could that also be a issue?

**Comment by bk2204** [comment]
Can you provide the output of `git config -l` and an example set of commands that triggers the issue for you?

**Comment by sactiw13** [comment]
```
admin@ub_16_client:~/t2$ git config -l
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Mobile Buildbot
url.git://git-mirror-builders:9999/.insteadof=git://git-master:29999/
filter.lfs.process=git-lfs filter-process skip
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip %f
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
admin@ub_16_client:~/t2$

```
The error occurred while running a git apply command:
`admin@ub_16_client:~/t2$git apply -p1 -v ../@master`

Btw, the .gitconfig file doesn't have multiple entry for lfs filter:
```
admin@ub_16_client:~/t2$ grep lfs ~/.gitconfig
[filter "lfs"]
    process = git-lfs filter-process skip
    clean = git-lfs clean -- %f
    smudge = git-lfs smudge --skip %f
admin@ub_16_client:~/t2$
```

**Comment by bk2204** [comment]
Hey,

I'm not able to reproduce this issue on my system, either with Git LFS 2.3.4 and Git 2.7.4 or with the latest master versions of both.  However, there are a couple things we can try to see if we can pin this down.

First, it looks like you have different settings in `~/.gitconfig` (or possibly, the system configuration) for `filter.lfs.smudge` than you do in `.git/config`.  Does this issue still occur if you temporarily remove the settings from the user or system configurations?

Second, it's possible that we've fixed this issue in a newer version without realizing it.  Can you try to see if this is still broken with 2.5.2 or the latest master branch?  There are binaries of 2.5.2 on the releases page.

**Comment by ttaylorr** [comment]
Hey @sactiw13, I'm going to close this issue since we haven't heard from you in a few days. Let us know if you are still having problems. Thanks!
