### ISSUE TITLE
`--skip-repo` option for uninstall

### ISSUE THREAD

**Issue by carlwgeorge** [git-lfs/git-lfs#3322]
Splitting off from discussion in #3013.

`git-lfs install` has an option for `--skip-repo` to skip the local hook setup.  Can this option be added to uninstall as well to skip the local hook removal attempt?  I think that would prevent this rev-parse error in the trace output.

```
# GIT_TRACE=1 ./git-lfs uninstall --system
16:16:56.470721 trace git-lfs: exec: git 'version'
16:16:56.473940 trace git-lfs: exec: git 'config' '--system' '--remove-section' 'filter.lfs'
16:16:56.480570 trace git-lfs: Error running 'git rev-parse': Failed to call git rev-parse --git-dir --show-toplevel: "fatal: not a git repository (or any of the parent directories): .git\n"
Global Git LFS configuration has been removed.
```

**Comment by bk2204** [comment]
Yeah, I think this is totally something we can implement.  I should have a fix available shortly.
