### ISSUE TITLE
misleading uninstall output (global vs system)

### ISSUE THREAD

**Issue by carlwgeorge** [git-lfs/git-lfs#3323]
Splitting off from discussion in #3013.

When running uninstall with the `--system` flag, the output indicates that the global git config (`~/.gitconfig`) was removed, which is inaccurate.  It removes the system config (`/etc/gitconfig`).

```
# ./git-lfs uninstall --system
Global Git LFS configuration has been removed.
```

**Comment by bk2204** [comment]
I agree we should fix this.  I'll see if I can roll something together.
