### ISSUE TITLE
Refactor Git attribute handling to use gitattr package

### ISSUE THREAD

**Issue by bk2204** [git-lfs/git-lfs#3328]
There are currently two different code paths we use to handle attributes.  The first is the the code in `git/attribs.go`, and the newer code path is in `git/gitattr`.  Ideally, we would have one shared code path that is used everywhere.  We should refactor the code to use only the latter for maintainability, implementing any features that we currently lack.

**Comment by tranghoangcz77** [comment]
Khi nào rảnh rỗi thì chạy máy nhé anh đi chơi vui lòng liên hệ số điện thoại di động sản phẩm tự nhiên rất nhiều

**Comment by tranghoangcz77** [comment]
Cứ để có thể thực hiện được những gì mà người khác cho rằng những vụ tự nhiên rất nhiều

**Comment by bk2204** [comment]
I believe this has been done, so I'm closing this.
