### ISSUE TITLE
git-lfs push fails when specifying URL to push to in command

### ISSUE THREAD

**Issue by jerick1976** [git-lfs/git-lfs#3333]
This is fairly easy to reproduce when performing a push using git-lfs 2.5.1 and specifying the push URL our push fails reporting that a file listed in .gitattributes is missing from the branch being pushed.  The file is indeed missing from this branch but it was never there to begin with.  It is present in other branches within the repo.  If I revert to 2.3.4 the problem goes away.  I tested with git 2.18, 2.11 and 2.10.3.  The results were the same.  

sjc-scmtest-v02:95> git lfs version
git-lfs/2.5.1 (GitHub; linux amd64; go devel +bd98a81dc2 Thu Jul 26 17:13:12 2018 +0000; git e1628484)
sjc-scmtest-v02:96> git push --repo ssh://sjc-scmtest-v02/nobackup/joericks-testing/comp-12200050.git

open /nobackup/joericks-testing/native_git_w3.bug/lfs.dat: no such file or directory
error: failed to push some refs to 'ssh://sjc-scmtest-v02/nobackup/joericks-testing/comp-12200050.git'

2.3.4:

sjc-scmtest-v02:98> git lfs version
git-lfs/2.3.4 (GitHub; linux amd64; go 1.9.1; git d2f6752f)
sjc-scmtest-v02:99> git version
git version 2.18.0.dirty
sjc-scmtest-v02:100> git push --repo ssh://sjc-scmtest-v02/nobackup/joericks-testing/comp-12200050.git

Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 1.00 MB skipped                                                                               Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 498 bytes | 249.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0)
To ssh://sjc-scmtest-v02/nobackup/joericks-testing/comp-12200050.git
   9bcc3c19..93fad546    ts_sync_6 -> ts_sync_6

**Comment by ttaylorr** [comment]
@jerick1976 That's very interesting, and thanks for the report. I recall that @bk2204 worked recently on the code that intercepts SSH push URLs, so perhaps he might have some thoughts here? If you have the time to, running a `git bisect` between these two versions would be immensely helpful.

**Comment by bk2204** [comment]
I think what we're seeing here is #1113, which unfortunately we haven't gotten around to fixing yet.  Looking at the output, my guess is that we used to skip uploading files we didn't have on the system and now we don't, and that's triggering this case.

Definitely a bisect would be helpful, as would some reproduction steps.  I'm definitely interested in fixing this if I can find some reproduction steps that I can use with our test repository.

**Comment by ttaylorr** [comment]
Ah, thanks for linking #1113, @bk2204. Let's move discussion about this there.
