### ISSUE TITLE
Push command successful but no changes reflected on Remote Repository file/s

### ISSUE THREAD

**Issue by BunsExynos** [git-lfs/git-lfs#3336]
When trying to clone and revert its says already updated but cannot see any changes on remote repo.

BunsExynos/android_kernel_samsung_exynos7580-common

**Comment by bk2204** [comment]
Hey, sorry you're having issues.  It looks like this is an issue with GitHub and not with Git LFS.  There's a known availability incident going on right now.  The issue should be resolving itself by now, but if you're still having trouble, please reach out to support@github.com for more assistance.
