### ISSUE TITLE
Cannot push using git LFS

### ISSUE THREAD

**Issue by dkalaxdk** [git-lfs/git-lfs#3338]
I cannot push anything when using git LFS.
I have tried uninstalling both git and LFS. Still cannot push any files, nor remove them from LFS.
I have tried reading various issues posted on here, without luck.
I get the following error:

Uploading

 LFS objects: 100% (1/1), 138 MB | 0 B/s, done                         
Counting objects: 22, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (22/22), 10.83 MiB | 1.89 MiB/s, done.
Total 22 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 1 local object.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 995c3324f00928a23357355902b97b39
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File map is 131.75 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/hooolius/p1_pakkelevering.git
 ! [remote rejected] dev -> dev (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/hooolius/p1_pakkelevering.git'

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.  It looks like while you have Git LFS set up, not all of your large files are tracked with Git LFS; some of them (specifically the file `map`) are still blobs in your repo.

If you try `git lfs migrate --include=map`, the file `map` should be rewritten to be a pointer throughout the history of your current branch, which should allow you to push.  If there are other large files, you can migrate them as well like so: `git lfs migrate --include=map,large-file2,*.jpg`.

**Comment by ttaylorr** [comment]
Hi @dkalaxdk, I think that @bk2204 gave some great advice. Since this is a fairly common issue, and I think that the recommendation will work, I'm going to close this for now. If you give that a shot and something still seems amiss, do let us know and we'd be more than happy to re-open this and take a look. Thanks!

**Comment by dkalaxdk** [comment]
This does not seem to work, when using the command given, i am greeted with a list of possible commands, something seems of in the syntax.

**Comment by dkalaxdk** [comment]
Did as you said, still no different regarding the push.
Any way i can just get rid of git LFS at least?
Even after uninitializing it in the git repository, it still pops up and complains about the large file, even tho i have told everything and anything to stop tracking of the map file?

**Comment by pithysr** [comment]
Hi, I tried @bk2204 solution and still get the same message:

       $ git push origin master

       (gnome-ssh-askpass:221991): Gtk-WARNING **: cannot open display:
       error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
       Username for 'https://github.com': 

       (gnome-ssh-askpass:222116): Gtk-WARNING **: cannot open display:
       error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
       Password for 'https://pithysr@github.com':
       Username for 'https://github.com': 
       Password for 'https://pithysr@github.com':
       Username for 'https://github.com': 
       Password for 'https://pithysr@github.com':
       Uploading LFS objects: 100% (6/6), 234 MB | 0 B/s, done
       Counting objects: 54, done.
       Delta compression using up to 80 threads.
       Compressing objects: 100% (37/37), done.
       Writing objects: 100% (37/37), 24.86 MiB | 1.78 MiB/s, done.
       Total 37 (delta 17), reused 0 (delta 0)
       remote: Resolving deltas: 100% (17/17), completed with 8 local objects.
       remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
       remote: error: Trace: 1ec76d367c6eb3e3d5259e3ebb17b802
       remote: error: See http://git.io/iEPt8g for more information.
       remote: error: File fullworks-v2.1.json is 182.93 MB; this exceeds GitHub's file size limit of 100.00 MB
       To https://github.com/pithysr/PPU.git
        ! [remote rejected] master -> master (pre-receive hook declined)
       error: failed to push some refs to 'https://github.com/pithysr/PPU.git'

Last time I faced this problem, I had to re-clone the whole git folder. After that `git lfs track` worked for my files. But once I added this new file I am having the same problem again.
All the large files are tracked:

    $ git lfs track
    Listing tracked patterns
    fullworks.json (.gitattributes)
    fullworks-v2.1.json (.gitattributes)
    fullworks-v2.json (.gitattributes)

**Comment by bk2204** [comment]
If you have existing history with large files, it may be useful to use `git lfs migrate import --everything` along with one or more patterns in order to rewrite history. Perhaps something like `git lfs migrate import --everything --include="*.json"` would work in your particular case.

**Comment by pithysr** [comment]
I had to untrack everything and track again. 
But problem is solved after `git lfs migrate import --everything --include="*.json"`. Thanks.
