### ISSUE TITLE
undefined lfsapi.Endpoint in test suite

### ISSUE THREAD

**Issue by Foxboron** [git-lfs/git-lfs#3372]
Currently encountering `# github.com/git-lfs/git-lfs/t/git-lfs-test-server-api/main.go:163:4: undefined: lfsapi.Endpoint` while attempting to run the test. There is no `lfsapi.Endpoint` in the project, so i assume `lfshttp.Endpoint` is correct. However the test suite doesn't work at all with this change.

**Comment by bk2204** [comment]
Thanks for reporting this.  It looks like it doesn't build automatically, so we didn't notice that our refactors broke it.  I can also confirm that the tests fail against my test instance.  Let me see if I can put something together to fix this.
