### ISSUE TITLE
Q: Are git lfs track and status usable for bare repositories?

### ISSUE THREAD

**Issue by mloskot** [git-lfs/git-lfs#3373]
TL;TR: Do `status` and `track` commands support bare repository, at least for read-only/inspection only?

The `status` command is documented as ["Show the status of Git LFS files in the working tree"](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-status.1.ronn) and it seems to succeed for a bare repository:

```
test.git (BARE:master) $ git lfs status
On branch master

Git LFS objects to be committed:

open .editorconfig: The system cannot find the file specified.
```

The [git lfs track manual](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-track.1.ronn) does not seem to mention any requirement of a working tree, but it apparently, does require it:

```
test.git (BARE:master) $ git lfs track
This operation must be run in a work tree.
```

Could anyone clarify usability of `git lfs status` and `git lfs track` for bare repositories?

**Comment by bk2204** [comment]
Yes, both of these commands require a working tree.  `git lfs status` is meant to mirror `git status`, which requires a working tree.  Both commands show the differences between the working tree and the index, which necessarily requires that the working tree exist.  `git lfs track` modifies `.gitattributes`, which also necessarily requires a working tree.

**Comment by ttaylorr** [comment]
> we should probably error out in the same way that 'git status' does on a bare repository, instead of failing to `os.Open()` a file which does not exist.

I have introduced a series to do just this in 
https://github.com/git-lfs/git-lfs/pull/3378.

**Comment by mloskot** [comment]
@bk2204 Excellent explanation. Thank you!
