### ISSUE TITLE
Incorrect git lfs version

### ISSUE THREAD

**Issue by y4ure** [git-lfs/git-lfs#3375]
I have git lfs 2.6.0 installed but `git lfs version` returns 2.5.2 for some reason and I couldn't figure out why. How to _fix_ the version?

```
PS C:\Program Files\Git LFS> git-lfs version
git-lfs/2.6.0 (GitHub; windows amd64; go 1.11.1; git 93702d75)
PS C:\Program Files\Git LFS> git lfs version
git-lfs/2.5.2 (GitHub; windows amd64; go 1.10.3; git 8e3c5c93)
PS C:\Program Files\Git LFS> gcm git-lfs

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git-lfs.exe                                        0.0.0.0    C:\Program Files\Git LFS\git-lfs.exe

PS C:\Program Files\Git LFS> $env:git_lfs_path
C:\Program Files\Git LFS
PS C:\Program Files\Git LFS> git lfs env
git-lfs/2.5.2 (GitHub; windows amd64; go 1.10.3; git 8e3c5c93)
git version 2.19.1.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey, I think the version that you're seeing here is the version that's shipped with Git for Windows.  That version is placed into `$GIT_EXEC_PATH`, I believe, which takes precedence over the version in `$PATH`.  You probably will want to place the `git-lfs.exe` binary you've downloaded into the `C:/Program Files/Git/mingw64/libexec/git-core` folder, which will replace the version that you had there.

**Comment by ttaylorr** [comment]
+cc @dscho, since I am not sure if he has updated the Git LFS version in GFW.

**Comment by dscho** [comment]
> +cc @dscho, since I am not sure if he has updated the Git LFS version in GFW.

They have. There just has not been any new official Git for Windows version in the meantime, so yes, we ship with Git LFS v2.5.2, still.

> You probably will want to place the `git-lfs.exe` binary you've downloaded into the `C:/Program Files/Git/mingw64/libexec/git-core` folder, which will replace the version that you had there.

I think @ttaylorr recommends `C:\Program Files\Git\mingw64\bin` instead, at least if I remember correctly.

**Comment by mloskot** [comment]
@y4ure if you 1. Install Git for Windows with Git LFS checked 2. Install [Git LFS](https://github.com/git-lfs/git-lfs/releases), then you simply need to manually re-deploy `git-lfs.exe` where `GFM expects it:

```
copy "C:\Program Files\Git LFS\git-lfs.exe" "C:\Program Files\Git\mingw64\bin\git-lfs.exe"
```

which @dscho mentions as recommended indeed.

FYI, Such installation into dedicated directory, i.e. `C:\Program Files\Git LFS`, may differ between Git extensions. For example, if you run [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases) installer, it will deploy the command into `C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager.exe`, so no manual intervention is required.
I don't know which installation mode, into dedicated or GFM directory, is common or recommended though.

**Comment by y4ure** [comment]
Thank you everyone.
