### ISSUE TITLE
Q: git status vs git lfs status

### ISSUE THREAD

**Issue by dashesy** [git-lfs/git-lfs#3380]
Is there any design rationale to keep both `git status` and `git lfs status`? could they be combined so that `git status` would know about lfs updates as well?

That would clear a lot of confusions about which files are lfs and which ones are not.

For example right now `git lfs status` outputs:

    Git LFS objects to be committed:

but then displays files that are not really "Git LFS objects" to be committed (only some are) and `git status` has no idea about lfs objects

**Comment by bk2204** [comment]
Hey, thanks for writing in.  We don't currently have plans for `git status` to learn how to deal with LFS objects.  The technique we use for handling LFS files, which is smudge/clean filters, is designed upstream to deal with formatting changes and not with wholesale replacement of files.  Consequently, it's not very likely that upstream would be interested in accepting a patch that makes core Git know anything about LFS at all, including changes to `git status` (and I say this as a contributor to core Git).

I realize this is inconvenient, and I'm sorry about that, but it's a limitation of the fact that core Git and Git LFS are separate projects.
