### ISSUE TITLE
Locked file shows absolute path and can't be unlocked

### ISSUE THREAD

**Issue by markonius** [git-lfs/git-lfs#3384]
On Windows, in a repository there is a lock with absolute path (I don't know how this happened):

```
$ git lfs locks
C:/users/some.one/Documents/Project/LockTest.png  Some One     ID:2
```

I can't unlock it, I get an error message:
```
$ git lfs unlock -i 2 --force
Git status failed: exit status 128

$ git lfs unlock C:/users/some.one/Documents/Project/LockTest.png --force
Git status failed: exit status 128
```

**Comment by bk2204** [comment]
Hey, sorry to hear you're having problems.

Can you tell us what version of Git LFS you're using and provide the output of `git lfs env`?  We made a change to handle this differently in 2.6.0 (#3277) and I'd like to know if this may have caused the issue or if it may fix it for you.

**Comment by markonius** [comment]
$ git lfs env
git-lfs/2.5.2 (GitHub; windows amd64; go 1.10.3; git 8e3c5c93)
git version 2.19.1.windows.1

Endpoint=http://zelda.croteam.biz/CreamTeam/Panmateria.git/info/lfs (auth=basic)
LocalWorkingDir=C:\git\Panmateria
LocalGitDir=C:\git\Panmateria\.git
LocalGitStorageDir=C:\git\Panmateria\.git
LocalMediaDir=C:\git\Panmateria\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\git\Panmateria\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\git\Panmateria\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by markonius** [comment]
```
$ git lfs env
git-lfs/2.5.2 (GitHub; windows amd64; go 1.10.3; git 8e3c5c93)
git version 2.19.1.windows.1

Endpoint=http://our.server/Project.git/info/lfs (auth=basic)
LocalWorkingDir=C:\git\Project
LocalGitDir=C:\git\Project\.git
LocalGitStorageDir=C:\git\Project\.git
LocalMediaDir=C:\git\Project\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\git\Project\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\git\Project\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Ok, I see I have 2.5.2  
Isn't the latest version of git supposed to include the latest version of git-lfs?

**Comment by bk2204** [comment]
I believe that Git for Windows bundles the latest version of Git LFS at the time of build.  At the time Git for Windows 2.19.1 was released, 2.5.2 was the latest release of Git LFS.  You can download a newer version from our releases page and put it earlier in your `PATH` if you like, or you could wait for a newer version of Git for Windows and see if it fixes things for you.

**Comment by markonius** [comment]
OK. Thanks for the quick response, I'll try the latest version next week and close this issue if it helps. From what I understand, the new version should never let locks like this happen, but I'm interested to see if it can handle a situation where a lock like this already exists.

**Comment by ttaylorr** [comment]
Hi @markonius, since this issue has been quiet for a while, I am going to close it and hope that everything was fixed on your end of things. If that's not the case, please don't hesitate to let us know here and we'd be happy to take another look.
