### ISSUE TITLE
LFS Smudge error when running "git clone"

### ISSUE THREAD

**Issue by sunzhaolin** [git-lfs/git-lfs#3410]
when I try to clone a remote git repo to local by - "git clone remoteURL localPath", it has error - 
Error downloading BI/HRIntelligence.BL/DayforceKey.snk (0ab752072774cb4705180fa63c7d479bd130c620f2d6f572d2d9564f5f847eac): batch response: Expected json type, got: "text/html"

below is the log -
git-lfs/2.6.0 (GitHub; windows amd64; go 1.11.1; git 93702d75)
git version 2.19.2.windows.1

$ git-lfs.exe filter-process
Error downloading object: BI/HRIntelligence.BL/DayforceKey.snk (0ab7520): Smudge error: Error downloading BI/HRIntelligence.BL/DayforceKey.snk (0ab752072774cb4705180fa63c7d479bd130c620f2d6f572d2d9564f5f847eac): batch response: Expected json type, got: "text/html"

Expected json type, got: "text/html"
batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/brian m. carlson/checkouts/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.Wrap
	C:/Users/brian m. carlson/checkouts/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
	C:/Users/brian m. carlson/checkouts/git-lfs/tq/api.go:76
github.com/git-lfs/git-lfs/tq.Batch
	C:/Users/brian m. carlson/checkouts/git-lfs/tq/api.go:40
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	C:/Users/brian m. carlson/checkouts/git-lfs/tq/transfer_queue.go:439
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
	C:/Users/brian m. carlson/checkouts/git-lfs/tq/transfer_queue.go:361
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1333
Error downloading BI/HRIntelligence.BL/DayforceKey.snk (0ab752072774cb4705180fa63c7d479bd130c620f2d6f572d2d9564f5f847eac)
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/brian m. carlson/checkouts/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.Wrapf
	C:/Users/brian m. carlson/checkouts/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.(*GitFilter).downloadFile
	C:/Users/brian m. carlson/checkouts/git-lfs/lfs/gitfilter_smudge.go:110
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
	C:/Users/brian m. carlson/checkouts/git-lfs/lfs/gitfilter_smudge.go:71
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/brian m. carlson/checkouts/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/brian m. carlson/checkouts/git-lfs/commands/command_filter_process.go:118
github.com/spf13/cobra.(*Command).execute
	C:/Users/brian m. carlson/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477
github.com/spf13/cobra.(*Command).Execute
	C:/Users/brian m. carlson/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/brian m. carlson/checkouts/git-lfs/commands/run.go:77
main.main
	C:/Users/brian m. carlson/checkouts/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:201
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1333
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/brian m. carlson/checkouts/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	C:/Users/brian m. carlson/checkouts/git-lfs/errors/types.go:270
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
	C:/Users/brian m. carlson/checkouts/git-lfs/lfs/gitfilter_smudge.go:80
github.com/git-lfs/git-lfs/commands.smudge
	C:/Users/brian m. carlson/checkouts/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
	C:/Users/brian m. carlson/checkouts/git-lfs/commands/command_filter_process.go:118
github.com/spf13/cobra.(*Command).execute
	C:/Users/brian m. carlson/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477
github.com/spf13/cobra.(*Command).Execute
	C:/Users/brian m. carlson/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	C:/Users/brian m. carlson/checkouts/git-lfs/commands/run.go:77
main.main
	C:/Users/brian m. carlson/checkouts/git-lfs/git-lfs.go:35
runtime.main
	C:/Go/src/runtime/proc.go:201
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1333

Current time in UTC: 
2018-12-04 16:23:47

ENV:
LocalWorkingDir=D:\dayforceGit
LocalGitDir=D:\dayforceGit\.git
LocalGitStorageDir=D:\dayforceGit\.git
LocalMediaDir=D:\dayforceGit\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\dayforceGit\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\dayforceGit\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=d:/dayforceGit/.git
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS

**Comment by bk2204** [comment]
From the error you're getting, `Expected json type, got: "text/html"`, it looks like either your Git server or some proxy in the middle is returning HTML instead of JSON.  You may be able to get more information by running with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1` before your `git` invocation.

Regardless, this should be reported to the person maintaining your Git server or your network proxy, if any, because it's a server-side issue which we can't address on the client side.
