### ISSUE TITLE
Installation fails in SUSE 11

### ISSUE THREAD

**Issue by itaranto** [git-lfs/git-lfs#3411]
Installation fails with error:
```
git version >= 1.8.2 is required for Git LFS, your version:
```

But the installed Git version is 2.15 .

Instllation performed with:
```
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | sudo bash
zypper in git-lfs
...
Installing: git-lfs-2.6.1-1.el7 [error]
Installation of git-lfs-2.6.1-1.el7 failed:
(with --nodeps --force) Error: Subprocess failed. Error: RPM failed: git version >= 1.8.2 is required for Git LFS, your version: 
error: %post(git-lfs-2.6.1-1.el7.i686) scriptlet failed, exit status 2
```

This are the added repos:
```
[github_git-lfs]
name=github_git-lfs
baseurl=https://packagecloud.io/github/git-lfs/sles/11.4/$basearch
repo_gpgcheck=1
pkg_gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/github/git-lfs/gpgkey
autorefresh=1
type=rpm-md

[github_git-lfs-source]
name=github_git-lfs-source
baseurl=https://packagecloud.io/github/git-lfs/sles/11.4/SRPMS
repo_gpgcheck=1
pkg_gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/github/git-lfs/gpgkey
autorefresh=1
type=rpm-md
```

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble with the packages.

This message comes from the installation script, which invokes `git-lfs`, which in turn looks for Git in the path.  Could you tell me what the commands `which -a git`, `git version`, and `echo "$PATH"` produce on your system?

**Comment by itaranto** [comment]
```
# which -a git
/usr/bin/git
```
```
# git version
git version 2.15.0
```
```
# echo $PATH
/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin
```

**Comment by bk2204** [comment]
I'm unclear why exactly this is happening. We should be reading the output of `git version` and parsing it, and I've verified that that version string does indeed parse correctly.

@git-lfs/core, do any of you have any ideas about what might be going on here?

**Comment by itaranto** [comment]
It's weird, I wasn't able to reproduce it anymore, I tested both in a amd64 and x86 machines and it worked fine.

I used the following versions:
git-lfs/2.6.0 (GitHub; linux amd64; go 1.11.1; git 93702d75)
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1; git dc072c3e)
git-lfs/2.6.1 (GitHub; linux 386; go 1.11.1; git dc072c3e)

The git version is the same (2.15.0).

**Comment by itaranto** [comment]
Hello, I'm reopening this since I'm experiencing an issue again when installing git-lfs-2.7.1-1.el7 but only in SLES 11.4 x86. This time I got a Go runtime panic.

This is the bug trace:
[git-lfs-sles-11-4.log](https://github.com/git-lfs/git-lfs/files/3085713/git-lfs-sles-11-4.log)

Also, installing an older version (git-lfs-2.6.1-1.el7) does not crash but it fails to install since the Git version is not being detected correctly:
```
Installing: git-lfs-2.6.1-1.el7 [error]
Installation of git-lfs-2.6.1-1.el7 failed:
(with --nodeps --force) Error: Subprocess failed. Error: RPM failed: git version >= 1.8.2 is required for Git LFS, your version: 
error: %post(git-lfs-2.6.1-1.el7.i686) scriptlet failed, exit status 2
```

The Git version is 2.15.0.

This  is the repo file:
```
[github_git-lfs]
name=github_git-lfs
baseurl=https://packagecloud.io/github/git-lfs/sles/11.4/$basearch
repo_gpgcheck=1
pkg_gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/github/git-lfs/gpgkey
autorefresh=1
type=rpm-md
```

**Comment by bk2204** [comment]
This is a very odd problem, and it definitely points to a problem somewhere in the Go runtime:

```
exitsyscall: syscall frame is no longer valid

goroutine 1 [running]:
runtime.throw(0x84a7b29, 0x2d)
        /usr/local/go/src/runtime/panic.go:608 +0x6a fp=0x8c74a40 sp=0x8c74a2c pc=0x806e88a
runtime.exitsyscall()
        /usr/local/go/src/runtime/proc.go:3010 +0x207 fp=0x8c74a58 sp=0x8c74a40 pc=0x8076597
syscall.Syscall(0x3, 0x9, 0x8c74ac4, 0x4, 0x0, 0x4, 0x0)
        /usr/local/go/src/syscall/asm_linux_386.s:39 +0x59 fp=0x8c74a5c sp=0x8c74a58 pc=0x80b69f9
syscall.readlen(0x9, 0x8c74ac4, 0x4, 0x3, 0x8d38000, 0x3b)
        /usr/local/go/src/syscall/zsyscall_linux_386.go:1026 +0x45 fp=0x8c74a84 sp=0x8c74a5c pc=0x80b5c05
syscall.forkExec(0x8c1c5a0, 0x10, 0x8c0c180, 0x2, 0x2, 0x8c74b70, 0x8c4a800, 0x8c1c5d0, 0x0)
        /usr/local/go/src/syscall/exec_unix.go:203 +0x2b0 fp=0x8c74b08 sp=0x8c74a84 pc=0x80afbb0
syscall.StartProcess(0x8c1c5a0, 0x10, 0x8c0c180, 0x2, 0x2, 0x8c74b70, 0x2, 0x4, 0x0, 0x0)
        /usr/local/go/src/syscall/exec_unix.go:241 +0x49 fp=0x8c74b30 sp=0x8c74b08 pc=0x80afe89
os.startProcess(0x8c1c5a0, 0x10, 0x8c0c180, 0x2, 0x2, 0x8c74c30, 0x8c18960, 0x3a, 0x3a)
        /usr/local/go/src/os/exec_posix.go:46 +0x13a fp=0x8c74b98 sp=0x8c74b30 pc=0x80cf69a
os.StartProcess(0x8c1c5a0, 0x10, 0x8c0c180, 0x2, 0x2, 0x8c74c30, 0x0, 0x0, 0x7f)
        /usr/local/go/src/os/exec.go:102 +0x5d fp=0x8c74bc0 sp=0x8c74b98 pc=0x80cf25d
os/exec.(*Cmd).Start(0x8d34000, 0x1, 0x8d20960)
        /usr/local/go/src/os/exec/exec.go:383 +0x362 fp=0x8c74c58 sp=0x8c74bc0 pc=0x8170fe2
```

Are you perhaps attempting to run this version under `qemu-user` by any chance? There's a known issue upstream that may have been fixed that explains this error if so. If not, I'm not sure why this would be happening, and I'm unfortunately unable to spin up an SLES VM (since it's not available without charge).

**Comment by itaranto** [comment]
> Are you perhaps attempting to run this version under `qemu-user` by any chance?

No, this is a fully virtualized Guest running under VMware vSphere.

> and I'm unfortunately unable to spin up an SLES VM (since it's not available without charge).

Unfortunately there's no openSUSE equivalent to this one. You can download a SLES11 trial from here:
https://www.suse.com/products/server/download/

I'll be glad to help, I was taking look at this: https://github.com/git-lfs/build-dockers
Do you use the same Go toolchain for every distro right?

I also noticed you switched from .el6  to .el7 packages for SUSE 11. I don't know what difference it will make using the CentOS 6 compared to the CentOS 7 build.

**Comment by bk2204** [comment]
Yes, we use the same Go toolchain when building each package. I think we were using 1.11.5 for 2.7.1, which requires building custom images. I'll probably switch to 1.12.4 for 2.7.2, though, since we'll be building most of our non-packaged binaries with that version.

**Comment by itaranto** [comment]
I reverted to git-lfs-2.5.2-1.el7 and it installed without problem. I will use this version for now.
