### ISSUE TITLE
Q: Number of uploaded objects for branches and tags

### ISSUE THREAD

**Issue by mloskot** [git-lfs/git-lfs#3427]
I'm pushing a bunch of new repositories, SVN to Git/Git LFS migrated and I noticed a tiny difference in the "Uploading LFS objects" numbers for `git push --tags origin`

- Repo 1 - both numbers match

```
$ git push --all origin
Uploading LFS objects: 100% (756/756), 585 MB | 4.8 MB/s, done

$ git push --tags origin
Uploading LFS objects: 100% (756/756), 585 MB | 0 B/s, done
```

- Repo 2 - both numbers match

```
$ git push --all origin
Uploading LFS objects: 100% (32/32), 306 MB | 2.7 MB/s, done

$ git push --tags origin
Uploading LFS objects: 100% (32/32), 306 MB | 0 B/s, done
```

- Repo 3 - both numbers match

```
$ git push --all origin
Uploading LFS objects: 100% (6019/6019), 36 GB | 6.7 MB/s, done

$ git push --tags origin
Uploading LFS objects: 100% (6019/6019), 36 GB | 0 B/s, done
```

- Repo 4 - numbers do not match as in `158 != 157` and `1.9 != 1.8 GB`

```
$ git push --all origin
Uploading LFS objects: 100% (158/158), 1.9 GB | 4.2 MB/s, done

$ git push --tags origin
Uploading LFS objects: 100% (157/157), 1.8 GB | 0 B/s, done
```

Could anyone explain me what may be the reason behind that differences?

Should I be worried about, expect any objects lost?

**Comment by bk2204** [comment]
I think this depends on the refs that you're pushing. It may be that you have branches in the latter repo that are not reachable from the tags and there's an additional object there. I don't think it's something to be worried about.

If you're concerned, you can do a `git clone` of the new repo and then do a `git lfs fetch --all` and a `git lfs fsck`.

**Comment by mloskot** [comment]
Thank you for the explanation. The `git lfs fetch` is helpful to explain the state of my LFS objects indeed.

```
$ git clone XXX
Cloning into 'metadata'...
remote: Enumerating objects: 646665, done.
remote: Counting objects: 100% (646665/646665), done.
remote: Compressing objects: 100% (639834/639834), done.
remote: Total 646665 (delta 5554), reused 646665 (delta 5554), pack-reused 0
Receiving objects: 100% (646665/646665), 999.96 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (5554/5554), done.
Checking out files: 100% (80371/80371), done.

$ metadata
$ git lfs fetch --all
fetch: 158 object(s) found, done
fetch: Fetching all references...

$ git lfs fsck
Git LFS fsck OK
```

Happy to see `158 object(s) found` :)
