### ISSUE TITLE
lfs path with spaces of framework file not tracked

### ISSUE THREAD

**Issue by codewalkerdan** [git-lfs/git-lfs#3445]
I have a file that is over 108MB that is needed to track (will not be modified very ofter) that is located at path

`unityproject/Assets/ZFBrowser/Plugins/m64/BrowserLib.app/Contents/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework`

so I use the lfs command to track it and this is added to the .gitattributes file

`unityproject/Assets/ZFBrowser/Plugins/m64/BrowserLib.app/Contents/Frameworks/Chromium[[:space:]]Embedded[[:space:]]Framework.framework/Chromium[[:space:]]Embedded[[:space:]]Framework`

But when I try to commit and push I always get the error

`remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 4e8464e4246a99572a2ce71a2247f438
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File unityproject/Assets/ZFBrowser/Plugins/m64/BrowserLib.app/Contents/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework is 106.07 MB; this exceeds GitHub's file size limit of 100.00 MB
`

Is there any step that I am missing.

Thanks for the help

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble, and apologies for the delay. Our team has been on vacation recently.

If you track the file with Git LFS, that doesn't modify the history to remove the old versions of the large file. You probably want to use `git lfs migrate import` (see the documentation for details) to rewrite the history not to have the large file in it so it can be pushed.

**Comment by markgrossnickle** [comment]
@codewalkerdan did you solve this?
@bk2204 This doesn't have anything to do with history. 

I have LFS enabled on a project.  I added the Chromium Embedded Framework.framework.   

I tried to commit but it failed with the error the OP posted. 

I tried to manually add the file to tracking as the OP did and it still gets the error.

I tried the migrate import but there should be no history of this file as it is new and the commit failed.

**Comment by codewalkerdan** [comment]
@markgrossnickle 

I added this line and it worked for me
`unityproject/Assets/External/ThirdParty/ZFBrowser/Plugins/m64/BrowserLib.app/Contents/Frameworks/Chromium[[:space:]]Embedded[[:space:]]Framework.framework/Chromium[[:space:]]Embedded[[:space:]]Framework filter=lfs diff=lfs merge=lfs -text`
