### ISSUE TITLE
Getting a smudge filter error along with rate limit exceeded

### ISSUE THREAD

**Issue by seanscap** [git-lfs/git-lfs#3448]
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
git version 2.14.1.windows.1

$ git-lfs.exe filter-process
Error downloading object: Assets/Animation/Characters/Robot/Clips/Stand--Reaction_S.anim.fbx (a36fd5e): Smudge error: Error downloading Assets/Animation/Characters/Robot/Clips/Stand--Reaction_S.anim.fbx (a36fd5ef473255ce2edc14de81960823bf628ec0da7d3629925535a9ce3d1a03): batch response: Rate limit exceeded: https://github.com/Unity-Technologies/FPSSample.git/info/lfs/objects/batch

Rate limit exceeded: https://github.com/Unity-Technologies/FPSSample.git/info/lfs/objects/batch
github.com/git-lfs/git-lfs/errors.Errorf
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/errors.go:69
github.com/git-lfs/git-lfs/lfsapi.defaultError
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfsapi/errors.go:114
github.com/git-lfs/git-lfs/lfsapi.(*Client).handleResponse
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfsapi/errors.go:51
github.com/git-lfs/git-lfs/lfsapi.(*Client).Do
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfsapi/client.go:80
github.com/git-lfs/git-lfs/lfsapi.(*Client).doWithCreds
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:74
github.com/git-lfs/git-lfs/lfsapi.(*Client).DoWithAuth
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:44
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/tq/api.go:60
github.com/git-lfs/git-lfs/tq.Batch
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/tq/api.go:36
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:286
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:258
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:2197
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:170: batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:170: Error downloading Assets/Animation/Characters/Robot/Clips/Stand--Reaction_S.anim.fbx (a36fd5ef473255ce2edc14de81960823bf628ec0da7d3629925535a9ce3d1a03)
github.com/git-lfs/git-lfs/errors.newWrappedError
	C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/errors/types.go:170: Smudge error

ENV:
LocalWorkingDir=C:\Users\georg\FPSSample
LocalGitDir=C:\Users\georg\FPSSample\.git
LocalGitStorageDir=C:\Users\georg\FPSSample\.git
LocalMediaDir=C:\Users\georg\FPSSample\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\georg\FPSSample\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_LFS_PATH=C:\Program Files\Git LFS

Its says warning clone succeeded, but checkout failed.

Any ideas?

Thanks in advance!

**Comment by bk2204** [comment]
Hey,

This error message means that the server side has rejected your connection because the client made too many requests in too short a period of time. We're tracking a potential improvement in this regard in #3122 to fall back and lower the number of requests. I'd like to keep the discussion there, so I'm going to close this issue.
