### ISSUE TITLE
git lfs migrate info doesn't list all files

### ISSUE THREAD

**Issue by chankruse** [git-lfs/git-lfs#3453]
I have a large file (>100MB) checked into my repo, but when I run the following command it doesn't show up:
` git lfs migrate info --everything --include="GoogleMobileAds"`

The file is located at 
`~/[redacted]/⁨Pods⁩/⁨Google-Mobile-Ads-SDK⁩/Frameworks⁩/⁨frameworks⁩/GoogleMobileAds.framework/GoogleMobileAds`

When I actually do the conversion to LFS using git lfs migrate import... it seems to correctly convert this file as I'm able to upload my cloned repo to GitHub (whereas before the import I get an error message).

But I'm wondering why this file won't show up when I do "... info..."

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Looking at the code, it looks like we skip handling files without extensions specified, which would explain why that file isn't listed with `git lfs migrate info`. This is something we probably should fix in the future, so I'm tagging it as a bug.
