### ISSUE TITLE
git lfs keeps pushing a missing file and fails on newer version (2.6.0+)

### ISSUE THREAD

**Issue by maxime-viargues-serato** [git-lfs/git-lfs#3461]
Hi there,

Our repository got in a weird state after some branch merging and LFS now fails to push with a "missing file" error. This is not failing with LFS 2.4.1, but it is with LFS 2.6.0+

So we have done a migration of some files from a repository A to a repository B and those file were moved to a different location. The history of those files was kept using a branch and merging it to the repository B. The details probably don't matter too much, but the idea is that one of those file was LFS tracked and the LFS content of that file wasn't pushed during the migration. This file lives in `test_resource/EULA.pdf`.

After the migration the git LFS clone was failing as the LFS object couldn't be found. I repushed the missing file (I believe) to fix the error. As this didn't fixed the issue I also removed the LFS tracked file (in the new locatoin) and replaced it by the file content (which was small). Now the clone is working fine.

In our build process we tag each build by creating a tag and pushing it. But this is now failing with a error:
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s                                  
stderr: open /Users/jenkins/workspace/product/framework/test_resources/EULA.pdf: no such file or directory
The file doesn't exist because it's been moved to /product/test/system/framework/test_resources/EULA.pdf and it's looking for it in the old location.

The commands used to create the tag and push are:
git tag -a -f -m "Message" "build/1234"
git push https://tfs.net/Products/_git/product build/1234 -f

I have tried to do a `git lfs fetch --all` from the repo A and push everything to repo B but same problem.
If I do a `git lfs fetch origin --all` in the repository then the push works but it's still uploading the 1.5MB file every time. Every new tag work after that. Still that's not a solution as we can't fetch all the files every time and this file still gets uploaded every single time.

This is the trace when the push fails:
```
08:54:35.747246 git.c:344               trace: built-in: git push https://tfs.net/Products/product-project/_git/product build/0.1.3.1470 -f
08:54:35.753225 run-command.c:640       trace: run_command: GIT_DIR=.git git-remote-https https://tfs.net/Products/product-project/_git/product https://tfs.net/Products/product-project/_git/product
08:54:36.087358 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
08:54:36.094556 trace git-lfs: exec: git 'config' '-l'
08:54:36.105551 trace git-lfs: pre-push: refs/tags/build/0.1.3.1470 ab75d9b49cd12e7eedd0385585bb00502e579a56 refs/tags/build/0.1.3.1470 0ca238e61dd3d562b5a89fefaac17c8b2a2ea1ae
08:54:36.570843 trace git-lfs: HTTP: POST https://tfs.net/Products/product-project/_git/product.git/info/lfs/locks/verify
08:54:36.582746 trace git-lfs: HTTP: 200
...
08:54:36.668710 trace git-lfs: HTTP: {"ours":[],"theirs":[]}
Locking support detected on remote "https://tfs.net/Products/product-project/_git/product". Consider enabling it with:
  $ git config lfs.https://tfs.net/Products/product-project/_git/product.git/info/lfs.locksverify true
08:54:36.670596 trace git-lfs: tq: running as batched queue, batch size of 100
08:54:36.670806 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://tfs.net/Products/product-project/_git/product --
open /Users/user/tmp/product-test/framework/test_resources/EULA.pdf: no such file or directory                                                                                               
error: failed to push some refs to 'https://tfs.net/Products/product-project/_git/product'
```

This is the trace when the push works but uploads the 1.5MB file:
```09:02:51.965475 trace git-lfs: HTTP: {"ours":[],"theirs":[]}
Locking support detected on remote "https://tfs.net/Products/product-project/_git/product". Consider enabling it with:
  $ git config lfs.https://tfs.net/Products/product-project/_git/product.git/info/lfs.locksverify true
09:02:51.965639 trace git-lfs: tq: running as batched queue, batch size of 100
09:02:51.965864 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://tfs.net/Products/product-project/_git/product --
09:02:53.010952 trace git-lfs: tq: sending batch of size 15                                                                                                                                               
09:02:53.016324 trace git-lfs: api: batch 15 files
09:02:53.026662 trace git-lfs: HTTP: POST https://tfs.net/Products/product-project/_git/product.git/info/lfs/objects/batch
09:02:53.040080 trace git-lfs: HTTP: 200
09:02:53.040168 trace git-lfs: HTTP: {"objects":[{"oid":"a9cecbe97b8dd6b4ccb178019cd1c2f5aa07ecca6d4bc95b9981d0f0cf6ea4d3","size":191100},{"oid":"4b36bca46028ecfd91114a8a9fc39bf5d8c25d9f76bb17fe29dbbe7a6905269a","size":182924},{"oid":"0d4318762236997ae29630a2d0d424f7f1c768341ae151505f7709eb5f234f5d","size":152572},{"oid":"bdbe7a771222ba4d1d6d180f1b6b48c1c9a20a8737b385248573f2f14bb95617","size":134592},{"oid":"9ddcd4acefac4d7740267fc923475a27d49f6d9f2c696c75c28677d90ce71e71","size":134060},{"oid":"851035880d42a1eea3f7b907c4e0d9fea9a12591fd02515
09:02:53.040262 trace git-lfs: HTTP: 420d449e5f37c3849","size":126016},{"oid":"8db505d7ee946763c0fd5fbdd9632b85d2638aeaff8176c036801eb04d1a7f0a","size":122868},{"oid":"8971eb70353f9f31e207abd4014966f1de872f9a03dc52783474148e8e986ae2","size":119880},{"oid":"999214fff0d71f45d251aac1605f11060b56a434003d4165f5f9342524f66ee3","size":64398},{"oid":"b02687e56dbef3af19e6b325b66d1c3954602241ace8379aca3d9084fd9a6ac4","size":58253},{"oid":"6dfc8dea49c613f2d0edf9593d24e2cd75d2fc19d7be80782d257c087be4ec62","size":51262},{"oid":"fadb06be3a0766b687447dcd5eef1904089f9bff2568f2eca91f78383a404f4b","size":51183},{"oid":"2c65aeb3f9918bdf9e9d5cc8c46f2bf2fa432fc9867b9aa00f854bd47f82edbd","size":51181},{"oid":"c59722f5fe5cc782b8fe0a7a8d2f070c17603a2678f275d2e21075b0ed21876b","size":25653},{"oid":"69fb05eb7eb63492a45a92196f5276a70cc59228e65cc9f671ba572e2484f9da","size":350}]}
09:02:53.040804 trace git-lfs: tq: starting transfer adapter "basic"                                                                                                                                      
Uploading LFS objects: 100% (15/15), 1.5 MB | 0 B/s, done                                                                                                                                                 
09:02:53.041067 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
09:02:53.041108 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
09:02:53.041218 trace git-lfs: filepathfilter: rejecting "tmp" via []
09:02:53.041235 trace git-lfs: filepathfilter: accepting "tmp"
09:02:53.047556 run-command.c:640       trace: run_command: git send-pack --stateless-rpc --helper-status --thin --progress https://tfs.net/Products/product-project/_git/product/ --stdin
09:02:53.052002 git.c:344               trace: built-in: git send-pack --stateless-rpc --helper-status --thin --progress https://tfs.net/Products/product-project/_git/product/ --stdin
09:02:53.066306 run-command.c:640       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --progress
09:02:53.069508 git.c:344               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --progress
Counting objects: 1, done.
Writing objects: 100% (1/1), 173 bytes | 86.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Analyzing objects... (1/1) (3 ms)
remote: Storing packfile... done (38 ms)
remote: Storing index... done (53 ms)
To https://tfs.net/Products/product-project/_git/product
 + 0ca238e6...ab75d9b4 build/0.1.3.1470 -> build/0.1.3.1470 (forced update)
```

We have several build machine which happen to have different LFS versions and I noticed that the problem only happens from LFS version 2.6.0. Other machines with 2.3.4, 2.4.0, 2.4.1, 2.4.2 are working. Well they don't fail but they are still pushing a file of 1.5MB every time. Also interestingly the original file I thought was the problem is only 57KB so it's not the same file that it is pushing every time. I cannot see any SHA1 it's looking for either.

So how can I remove the LFS reference of this file so it doesn't try to upload it every time? and why is it trying to upload it?
Or what else can I do?

**Comment by maxime-viargues-serato** [comment]
Also a `git lfs ls-files` doesn't show any of the pdf files missing.

**Comment by bk2204** [comment]
So what you're seeing is #1113, which we've improved with a better error message. Essentially, when you're pushing, Git LFS determines which LFS objects need to be provided, and talks to the server via the batch API. The server reports back which items it doesn't have and need to be uploaded, and then Git LFS attempts to upload the ones it's told are needed.

If the LFS object is missing in the local copy, we attempt to create it from where we thought it was on disk and then retry. In this case, the object is missing and it doesn't exist on disk, so the push fails. The fetch causes it to be downloaded and then you can push it.

The server should generally know which objects it already has in the repo and not need them uploaded again, so this issue should only occur once per repo for deleted files.

Prior to v2.5.0, we allowed incomplete pushes by default. We no longer allow that by default because that leads to corrupt repositories.

There are a couple solutions here:
1. You can inquire with your server implementation (which looks like TFS) why they require the object to be uploaded if it's already present (assuming that's the case).
1. You can fetch the object when necessary, either by using `git lfs fetch --all` with the proper remote or by checking out a revision with that LFS object.
1. You can set `lfs.incompletepush` to `true`, knowing that corruption could occur.
1. You can filter out the object, rewriting history in the process, by using a tool such as `git filter-branch` or BFG.

**Comment by maxime-viargues-serato** [comment]
Thanks for the quick reply. I am still trying to make sense where the problem actually lies.

It looks like there is a problem on the server, especially that we found out that doing a `git push origin...` works when `git push https:tfs.net/...` fails. But Unfortunately we don't have control over the push command as it's a Jenkins plug-in.

> You can inquire with your server implementation (which looks like TFS) why they require the object to be uploaded if it's already present (assuming that's the case).

Yes true but inquiring Microsoft will take a while and probably won't be fixed any time soon (if ever).
> You can fetch the object when necessary, either by using git lfs fetch --all with the proper remote or by checking out a revision with that LFS object.

That feels a bit overkilled to pull all the LFS files just to be able to push, and it might take a while over time.
> You can set lfs.incompletepush to true, knowing that corruption could occur.

This doesn't fix the problem
> You can filter out the object, rewriting history in the process, by using a tool such as git filter-branch or BFG.

We can't re-write the history as this repo is used by a lot of people and the commit hashes are used in other places.

I was thinking if the problem is on the server side maybe we can re-create a complete clean repo, push the history (but not the LFS files) and just re-push the valid LFS files. But this didn't work. I tried to re-do the migration from the original repo and having the latest LFS it indeed stopped me to push incomplete files. However even after pushing just the current LFS file using `git lfs ls-files -l | awk '{ print $1 }' | xargs git lfs push --object-id origin` (so no invalid files on the server), then the push still fails.
So what I don't understand is that at this point the server shouldn't know about any missing file as I didn't pushed any. Unless it's getting it from the history itself?

Another thing is if I reset the master branch to "before the problematic merge" then the push works fine, which tells me that there is something in the local repo that LFS is trying to push, isn't it?

I have also tried to re-add the missing file from the old location and uploaded every LFS version of the file one by one but the problem still persists after re-deleting it!

So isn't it a way to fix the repo locally or on the server side without re-writing the whole history?

Also what's the HTTP command I can run on the server to get the files the server is saying is missing (with the batch api)?

**Comment by bk2204** [comment]
> It looks like there is a problem on the server, especially that we found out that doing a `git push origin...` works when `git push https:tfs.net/...` fails. But Unfortunately we don't have control over the push command as it's a Jenkins plug-in.

This is interesting.

I think what's happening here is that when using `origin`, Git knows that there are already some revisions it has, so when it tells Git LFS to push objects, Git LFS need only push objects for a subset of the revisions, ones that don't include the problematic commit. Since Git LFS in that situation assumes that the server will already have LFS objects for revisions it already has, it doesn't ask the server if it needs to upload them, and it succeeds.

I know you said that this isn't easily fixable, but if there is a way to address it, it's likely to be the simplest, most straightforward solution.
 
> So isn't it a way to fix the repo locally or on the server side without re-writing the whole history?

Unfortunately, no. There may be an option on the server side to fix this (you'd have to ask Microsoft), but Git LFS doesn't provide any options (other than `lfs.incompletepush`) to skip pushing objects.

> Also what's the HTTP command I can run on the server to get the files the server is saying is missing (with the batch api)?

You can see the output of the batch API by running your push command as `GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRANSFER_TRACE=1 git lfs push`. The output from the batch API will tell you which objects you need, and then you can see if they can be downloaded from the same URL.

**Comment by maxime-viargues-serato** [comment]
Actually I tried `lfs.allowincompletepush` again and it worked this time, so that might be the easiest option. We will only use it to push tags so it should be safe enough?

> You can see the output of the batch API by running your push command as GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRANSFER_TRACE=1 git lfs push.

I have tried with those options but I cannot see anything. That's all I can see
```09:39:52.278088 trace git-lfs: creds: git credential approve ("https", "tfs.net", "")
09:39:52.300089 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
09:39:52.303088 git.c:418               trace: built-in: git credential approve
09:39:52.304088 run-command.c:643       trace: run_command: 'git credential-manager store'
09:39:52.360085 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
09:39:52.362085 git.c:675               trace: exec: git-credential-manager store
09:39:52.362085 run-command.c:643       trace: run_command: git-credential-manager store
09:39:52.612785 run-command.c:643       trace: run_command: 'git credential-manager store'
09:39:52.666715 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
09:39:52.668715 git.c:675               trace: exec: git-credential-manager store
09:39:52.668715 run-command.c:643       trace: run_command: git-credential-manager store
09:39:52.981444 trace git-lfs: HTTP: {"ours":[],"theirs":[]}
{"ours":[],"theirs":[]}Locking support detected on remote "https://tfs.net/Products/product-project/_git/product.maxime-test-lfs". Consider enabling it with:
  $ git config lfs.https://tfs.net/Products/product-project/_git/product.maxime-test-lfs.git/info/lfs.locksverify true
09:39:52.982443 trace git-lfs: tq: running as batched queue, batch size of 100
09:39:52.986442 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://tfs.net/Products/product-project/_git/product.maxime-test-lfs --
open D:\tmp\product.maxime-test-lfs\framework\test_resources\EULA.pdf: The system cannot find the path specified.
error: failed to push some refs to 'https://tfs.net/Products/product-project/_git/product.maxime-test-lfs'```

**Comment by bk2204** [comment]
> Actually I tried `lfs.allowincompletepush` again and it worked this time, so that might be the easiest option. We will only use it to push tags so it should be safe enough?

If you know your tags are just tags and don't create any new LFS objects, then yes, that's probably safe.
 
> > You can see the output of the batch API by running your push command as GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRANSFER_TRACE=1 git lfs push.
> 
> I have tried with those options but I cannot see anything. That's all I can see

It looks like I misread the code. I had thought we used a channel to queue the items, but we use an array instead, so in this case we never get to the batch operation. We do require that all of the objects be available before querying the server for objects, although as you can see we query locks before push.

It would probably be a nice improvement to defer the check for items we don't strictly need.

**Comment by maxime-viargues-serato** [comment]
Ok then there is no problem on the server side right?

> It would probably be a nice improvement to defer the check for items we don't strictly need.

Yes that would be nice.

**Comment by bk2204** [comment]
> Ok then there is no problem on the server side right?

Yeah, it looks like we don't get to that point, so there's no problem there.

> > It would probably be a nice improvement to defer the check for items we don't strictly need.
> 
> Yes that would be nice.

I've opened #3468 to improve this.

**Comment by maxime-viargues-serato** [comment]
> I've opened #3468 to improve this.

Ok great! I am glad there's a hope for a fix :)

Thank you for your time.

**Comment by dehengxu** [comment]
> So what you're seeing is #1113, which we've improved with a better error message. Essentially, when you're pushing, Git LFS determines which LFS objects need to be provided, and talks to the server via the batch API. The server reports back which items it doesn't have and need to be uploaded, and then Git LFS attempts to upload the ones it's told are needed.
> 
> If the LFS object is missing in the local copy, we attempt to create it from where we thought it was on disk and then retry. In this case, the object is missing and it doesn't exist on disk, so the push fails. The fetch causes it to be downloaded and then you can push it.
> 
> The server should generally know which objects it already has in the repo and not need them uploaded again, so this issue should only occur once per repo for deleted files.
> 
> Prior to v2.5.0, we allowed incomplete pushes by default. We no longer allow that by default because that leads to corrupt repositories.
> 
> There are a couple solutions here:
> 
> 1. You can inquire with your server implementation (which looks like TFS) why they require the object to be uploaded if it's already present (assuming that's the case).
> 2. You can fetch the object when necessary, either by using `git lfs fetch --all` with the proper remote or by checking out a revision with that LFS object.
> 3. You can set `lfs.incompletepush` to `true`, knowing that corruption could occur.
> 4. You can filter out the object, rewriting history in the process, by using a tool such as `git filter-branch` or BFG.

Works for me
