### ISSUE TITLE
git lfs migrate doesn't migrate LFS

### ISSUE THREAD

**Issue by gitbobo** [git-lfs/git-lfs#3462]
My system is centos 7,git-lfs 2.4.2 with git 1.8.3.1.  
Before, I already has git repo cloned from gitlab.After `git lfs install`,I begin to use `git lfs` to track my `jpg`,`gif` files.  
But I found git-lfs doesn't automatically migrate files from `git` to `git lfs`.  
Then, I run :  
```
git lfs migrate import --include="*.jpg"
git lfs migrate import --include="*.gif"
git reflog expire --expire-unreachable=now --all
git gc --prune=now
git lfs push origin master --all
```
The result as below:  
```
[root@localhost www]# git push origin master
Everything up-to-date
[root@localhost www]# git lfs push origin master --all
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://git.yourgitlab.com/dev/yourproject.git/info/lfs.locksverify true
[root@localhost www]#  100% (247/247), 1.4 MB | 0 B/s
``` 
But when I check my gitlab,there's no any push activity.    
Then, `git lfs migrate info` output as below:  
```
[root@localhost www]# git lfs migrate info
migrate: Fetching remote refs: ..., done                                        
migrate: Sorting commits: ..., done                                             
migrate: Examining commits: 100% (0/0), done
```

What's the problem, how to solve it?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

The presence of "Everything up-to-date" is very suspicious here. It looks like for whatever reason, nothing was rewritten. Normally, we'd expect to see a message about needing to force-push in this case.

Can you find a commit that adds or removes a `.jpg` or `.gif` file and then run `git show <commit>`? The file in that commit should look something like the following:

```
version https://git-lfs.github.com/spec/v1
oid sha256:2ee43237d196100210f1786e7b73b57cd140f6013c072c70dbdffd9e9bc695f8
size 6518
```

**Comment by zestyping** [comment]
Are you expecting `git lfs migrate import` to rewrite the history of `master` all the way back to the beginning?

By default, `git lfs migrate import` only modifies commits that exist only on your local machine (i.e. new commits that have not yet been pushed to any other repo).

According to the [git-lfs-migrate manual page](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn), if you want it to rewrite all of the history, then you have to specify a branch with `--include-ref` (for example, `git lfs migrate import --include-ref=refs/heads/master`), or specify `--everything` to include all commits in all branches.  Please be aware that if you do this, you will get a new repo with different commit hashes, incompatible with the existing repo; you will have to ask anyone else who is using a clone of your repo to abandon their repo and clone your new one instead.

The [git-lfs-migrate manual page](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn) seems very confusing on this point.  It certainly gives the impression that `git lfs migrate import` will rewrite all of the history by default; there is no indication that its operates only on unpushed commits until you get all the way down to the "EXAMPLES" section, which is usually not a place that one expects to find critically important new information about what a command will do.

**Comment by jonathan-dufault-kr** [comment]
--everything doesn't change the results for me
