### ISSUE TITLE
external filter 'git-lfs filter-process' failed - object not found

### ISSUE THREAD

**Issue by sprynmr** [git-lfs/git-lfs#3466]
Getting this error when trying to checkout a branch, but only on one of my computers for some reason:
```
[85eb0ea72da524fa6a2fa4aecadfef26700b0bb92f08104e06c449b788ed4f73] Object does not exist on the server: [404]
...
external filter 'git-lfs filter-process' failed
```

Seems similar to this: https://github.com/git-lfs/git-lfs/issues/3245

Trying to use the instructions at the bottom there to fix it, but I'm not getting anything out of this command with the sha I found containing the objectID:
```
git ls-files -s \
      | grep -v "3c590798b22d715cbaee49adc129fb98c9cc7d31" \
      | git update-index --index-info
```

**Comment by sprynmr** [comment]
Tried `git lfs fetch --all` based on https://github.com/git-lfs/git-lfs/issues/3182. Got a bunch of objectIDs that aren't found on the server, and then 
`error: failed to push some objects to 'https://github.com/xxx`

**Comment by bk2204** [comment]
What could be happening here is that you've created some new objects on one of your systems but the object never got pushed.

`git lfs fetch --all` is probably the best choice as a first attempt, although in your case it isn't helping.

It does look like the behavior of `git update-index` is not what we want here. You could try a command like this, which seemed to do the right thing in my testing:

```
git ls-files -s | \
    grep "3c590798b22d715cbaee49adc129fb98c9cc7d31" | \
    awk -F'\t' '{print $2}' | \
    git update-index --force-remove --stdin
```

**Comment by ttaylorr** [comment]
Hi @sprynmr, I think that @bk2204's suggestion is a good one.

Since we haven't heard from you in a couple of weeks, I am going to hope that the issue was resolved on your end, and close this issue in the meanwhile. If that's not the case, and there _are_ still unresolved problems, please don't hesitate to let us know here and we'd be more than happy to take a look at it.

Thanks!
