### ISSUE TITLE
lfs.url config does not work on new or renamed remotes

### ISSUE THREAD

**Issue by zachwhaley** [git-lfs/git-lfs#3469]
According to the LFS URL doc https://github.com/git-lfs/git-lfs/wiki/Tutorial#lfs-url it would seem that if I set lfs.url to some URL, then that URL should be used for all remotes.  But if I add a new remote or rename an existing remote, this URL is not used and/or removed from those remotes.

I've reproduced this with a local set of repos

git version `git version 2.17.2`
git-lfs version `git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1; git dc072c3e)`

First I created a brand new repo with a .lfsconfig file that sets an LFS URL
```
$ git config -f .lfsconfig lfs.url "http://private-lfs-repo.net"
$ git add .
$ git ci -m 'init'
[master (root-commit) f28e181] init
 1 file changed, 2 insertions(+)
 create mode 100644 .lfsconfig
$ git lfs env
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1; git dc072c3e)
git version 2.17.2

Endpoint=http://private-lfs-repo.net (auth=none)
LocalWorkingDir=/home/zacharyw/Code/lfsurl-test
LocalGitDir=/home/zacharyw/Code/lfsurl-test/.git
LocalGitStorageDir=/home/zacharyw/Code/lfsurl-test/.git
LocalMediaDir=/home/zacharyw/Code/lfsurl-test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/zacharyw/Code/lfsurl-test/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/zacharyw/Code/lfsurl-test/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
Then I cloned this repo and checked the LFS URL, which is correct
```
$ cd ../
$ git clone lfsurl-test/.git lfsurl-clone
Cloning into 'lfsurl-clone'...
done.
$ cd lfsurl-clone
$ git lfs env
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1; git dc072c3e)
git version 2.17.2

Endpoint=http://private-lfs-repo.net (auth=none)
LocalWorkingDir=/home/zacharyw/Code/lfsurl-clone
LocalGitDir=/home/zacharyw/Code/lfsurl-clone/.git
LocalGitStorageDir=/home/zacharyw/Code/lfsurl-clone/.git
LocalMediaDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
Then I added a new remote repo to my clone and checked that remote's LFS URL which is not correct or at least is ignoring the lfs.url config.
```
$ git remote add other ../lfsurl-remote/.git
$ git lfs env
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1; git dc072c3e)
git version 2.17.2

Endpoint=http://private-lfs-repo.net (auth=none)
Endpoint (other)=../lfsurl-remote/.git/info/lfs (auth=none)
LocalWorkingDir=/home/zacharyw/Code/lfsurl-clone
LocalGitDir=/home/zacharyw/Code/lfsurl-clone/.git
LocalGitStorageDir=/home/zacharyw/Code/lfsurl-clone/.git
LocalMediaDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
Then I renamed my origin remote and checked the LFS URL, which is now also not correct or at least ignoring the lfs.url config.
```
$ git remote rename origin og
$ git lfs env
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1; git dc072c3e)
git version 2.17.2

Endpoint (other)=../lfsurl-remote/.git/info/lfs (auth=none)
Endpoint (og)=file:///home/zacharyw/Code/lfsurl-test/.git/info/lfs (auth=none)
LocalWorkingDir=/home/zacharyw/Code/lfsurl-clone
LocalGitDir=/home/zacharyw/Code/lfsurl-clone/.git
LocalGitStorageDir=/home/zacharyw/Code/lfsurl-clone/.git
LocalMediaDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/zacharyw/Code/lfsurl-clone/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I believe we do actually honor the URL set in `lfs.url` regardless, at least we do in my testing. I think this is simply a bug in `git lfs env` that causes it to print the wrong URL. Can you confirm that it does indeed push to the place you expect when setting `lfs.url`?

**Comment by zachwhaley** [comment]
It seems like it is not pushing to the correct server, but I'm not positive.  We are having issues with people unable to push due to missing LFS objects in commits they never checked out.  This is the same issue I mentioned in another comment https://github.com/git-lfs/git-lfs/pull/3398#issuecomment-451529507

How would I test this?

**Comment by bk2204** [comment]
The way I would suggest testing this is setting up an additional remote (say, `test`) somewhere and setting `lfs.url` to point to the existing server, then run with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs push test` and verify that the batch requests are pointing to the `lfs.url` location, and not the location of the other repository.

In my testing, I used a repository which doesn't exist for my test remote, so since the operation succeeded, I'm fairly confident that it's honoring `lfs.url`.

**Comment by bk2204** [comment]
Sure. If you want to send the trace log to me, you can use my username at github.com.

I think if you're seeing the issue you mentioned in #3398, and `git lfs fetch --all` fixes your problem, then you may be interested in #3468, to improve the experience when we're pushing objects the server already has. If a `git lfs fetch --all` doesn't fetch the objects, then that usually means that the objects are really missing, and you would need to either recreate them or find them in another copy.

**Comment by bk2204** [comment]
Having looked at the traces, I think the issue you're seeing is that we don't check out objects that aren't in the current revision. You add a file, and then remove it. Then, when that revision is pulled into a new clone, the object isn't pulled down, so when you try to push it to a new remote, it's missing.

I think running `git lfs fetch --all` will fix this issue for you. #3468 may solve your problem when fixed, but it's possible that it won't. It really depends on whether your server de-duplicates objects on a per-repository basis or on a per-fork network basis.

**Comment by zachwhaley** [comment]
Ok thanks.

I figured that is what was happening, and I do hope that #3468 fixes this because running `git lfs fetch --all` before almost every push is going to be a bummer.

As for the `git lfs env` bug, is this issue going to continue tracking that?

Thanks again!

**Comment by bk2204** [comment]
Yes, this is the right issue for the `git lfs env` bug.

**Comment by chodes123** [comment]
I am implementing git lfs solution with s3 backend. What url should we copy in .lfsconfig?

**Comment by bk2204** [comment]
@chodes123 That sounds like a great question for the discussions area.  It doesn't sound like it's related to this issue, which is closed.
