### ISSUE TITLE
Can't run "go generate" on non-Windows

### ISSUE THREAD

**Issue by ssgelm** [git-lfs/git-lfs#3473]
As part of building the git-lfs Debian package, `go generate` must be run to generate the help information.  Dh_golang, the debian build tool for go, has a built in flag `DH_GOLANG_GO_GENERATE` which, if set to `1`, will automatically run `go generate` on the package.

The problem with using this flag is that running `go generate` on git-lfs also attempts to run https://github.com/git-lfs/git-lfs/blob/master/git-lfs.go#L1, which fails because `goversioninfo` is not installed.

One solution could be to package it for Debian but since it's windows-specific that seems to be of questionable value.  I currently have worked around it by patching out that line [1] but that obviously would not be an acceptable solution because it would break Windows builds.  One thing that was suggested was to move the `go generate` to a file with a windows-specific but since there are none of those in the root of the project that may not work based on my reading of the `goversioninfo` docs.

While the git-lfs Makefile works around this by only calling `go generate` on Windows builds, I do think that this is at least a valid bug - one might reasonably expect to be able to run `go generate` successfully regardless of platform.  I will do some testing and see if I can come up with a good solution but I wanted to at least file the issue so you all could be aware of it since you know the codebase better than I do and might have a better idea for how to fix it.

[1] https://salsa.debian.org/go-team/packages/git-lfs/commit/8a4bad783a43ee05c144b96f44671eec62324a77

**Comment by bk2204** [comment]
I think simply creating a `git-lfs_windows.go` file with that header in it is a good idea.

Does something like the `go-generate-windows` branch on my remote work in your situation?

**Comment by ssgelm** [comment]
Yep, seems to work perfectly for me!  I can't confirm that it still works on windows though.

**Comment by bk2204** [comment]
I have a test VM that I'll try it on before submitting. Thanks for verifying.
