### ISSUE TITLE
installation in ubuntu is not working

### ISSUE THREAD

**Issue by AbhishekVermaKT** [git-lfs/git-lfs#3474]
Trying the instruction:
```
abhishek@abhishek:~/ds_development$ sudo add-apt-repository ppa:git-core/ppa
 The most current stable version of Git for Ubuntu.

For release candidates, go to https://launchpad.net/~git-core/+archive/candidate .
 More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.
```
 
yields eventually:
 
```
Get:13 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease [23.2 kB]                                                                 
Err:13 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
Fetched 299 kB in 2s (143 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
Also I have had git lfs in my computer already installed however I was getting same error while `sudo apt update` so tried to uninstall and install again.

**Comment by genieunicorn** [comment]
Same here! issue on ubuntu 16.04

**Comment by bk2204** [comment]
Hey, sorry to hear y'all are having trouble.

As far as I can tell, the key we're using for signatures in the packagecloud repository is different. We don't manually manage that key, so it's possible that they've changed it without us knowing. Unfortunately, without packagecloud providing some sort of archive keyring, there's no way to automatically rotate keys.

I tried to download the key from https://packagecloud.io/app/github/git-lfs/gpg#gpg-apt and then install the repo in an Ubuntu bionic container, and it appears to work for me. Can you confirm that following the steps on that page makes it possible for you to run `apt update` successfully?

**Comment by ScottMcCormack** [comment]
Running the following command looks to have fixed this issue for me:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157`

**Comment by ffes** [comment]
I run into the same problem. I tried the `apt-key` command above and the update still fails. It appears that their key has expired:

```
root@mypc:~# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2014-01-13 [SCEA] [expired: 2019-01-12]
      418A 7F2F B0E1 E6E7 EABF  6FE8 C2E7 3424 D590 97AB
uid           [ expired] packagecloud ops (production key) <ops@packagecloud.io>
```

I snipped all the irrelevant keys that work as expected.

**Comment by bk2204** [comment]
Can you provide the `deb` or `deb-src` line for the repository you're using? It's likely somewhere in `/etc/apt/sources.list.d`.

**Comment by AbhishekVermaKT** [comment]
@ScottMcCormack fix worked for me. Just putting it here for anyone who might benefit.

**Comment by stevencrader** [comment]
I am seeing this issue on Ubuntu 14.04

> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io trusty InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
>
> W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  

I tried the command from @ScottMcCormack and adding the GPG key command shown on https://packagecloud.io/app/github/git-lfs/gpg#gpg-apt but neither works.

Here is the output of /etc/apt/sources.list.d/github_git-lfs.list
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/github/git-lfs

deb https://packagecloud.io/github/git-lfs/ubuntu/ trusty main
deb-src https://packagecloud.io/github/git-lfs/ubuntu/ trusty main
```

**Comment by ffes** [comment]
Here it is:

```
frank@mypc:/etc/apt/sources.list.d$ cat git-lfs.list
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/github/git-lfs

deb https://packagecloud.io/github/git-lfs/ubuntu/ bionic main
deb-src https://packagecloud.io/github/git-lfs/ubuntu/ bionic main
```

When I installed git-lfs (somewhere in the summer) I used the description on the git-lfs website. Once done, I only renamed the file in `/etc/apt/sources.list.d`. I has worked as expected until very recently. As I mentioned above `apt-list list` says the keys has expired on the 12th of January.

**Comment by gkapfham** [comment]
Since there has been some confusion as to whether or not the approach by @ScottMcCormack would work or not, I am writing to report that, for Ubuntu 16.04 LTS this worked correctly for me. I can confirm that after running the suggested command the `sudo apt update` command worked correctly without warning! Many thanks to the creators of this tool and to @ScottMcCormack for suggesting the fix!

**Comment by Gilkshell** [comment]
Running 'sudo apt-get update' issues:

**Comment by Gilkshell** [comment]
I was able to solve my problem with command:  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6B05F25D762E3157.   Note the addition of port 80.  Having got the key the apt-get update works fine.

**Comment by rrmhearts** [comment]
> Running the following command looks to have fixed this issue for me:
> 
> ```
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
> ```

This worked for me. I'm on Ubuntu 16.04.5 LTS

**Comment by abferm** [comment]
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6B05F25D762E3157

I had to use this format on Ubuntu 18.04.1 LTS (bionic).

**Comment by ffes** [comment]
On WSL it fails, but that seems to be a WSL problem in (at least) 1803.  As mentioned in Microsoft/WSL#3696 (dup of MicrosoftDocs/azure-docs-cli#1181) it should be fixed in 1809.

**Comment by mkumar118** [comment]
I am on Debian Stretch and the above command did not work for me (naturally, as the keyring is different).

After some looking around, the following worked for me:
`curl -L https://packagecloud.io/github/git-lfs/gpgkey | sudo apt-key add -`

**Comment by adizhol** [comment]
> I am on Debian Stretch and the above command did not work for me (naturally, as the keyring is different).
> 
> After some looking around, the following worked for me:
> `curl -L https://packagecloud.io/github/git-lfs/gpgkey | sudo apt-key add -`

I got `gpg: no valid OpenPGP data found.
`

**Comment by bk2204** [comment]
You'd probably want to run `curl -LO https://packagecloud.io/github/git-lfs/gpgkey` and verify that the file `gpgkey` looks like an OpenPGP key.  It appears to look fine to me.

**Comment by chuckgregoryACES** [comment]
Is anyone else currently having this issue?
Seems like none of the fixes suggested in this ticket are working right now.

**Comment by bk2204** [comment]
Could you specify what version of Ubuntu you're using?  If it's 21.10, it's currently known that there are no packages for it, and they'll be included in the next release.

**Comment by chuckgregoryACES** [comment]
Turns out it was an issue with package-cloud that was identified in Issue 4792 which is now resolved. Thanks for responding, @bk2204 .

**Comment by CHaNGeTe** [comment]
Happening again?
` GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
W: There is no public key available for the following key IDs:
6B05F25D762E3157  `

**Comment by CHaNGeTe** [comment]
but seems to be failing for Xenial as well

**Comment by CHaNGeTe** [comment]
`Reading package lists...
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease' is not signed.
W: There is no public key available for the following key IDs:
6B05F25D762E3157`

**Comment by CHaNGeTe** [comment]
Seems to be solvable on Travis via "manual" install:
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

**Comment by chuckgregoryACES** [comment]
@CHaNGeTe did you reach out to packagecloud about the problem? They fixed it for me last time.

**Comment by bk2204** [comment]
Okay, it sounds like maybe Travis doesn't have the right key installed.  That would be a thing you'd probably want to discuss with them.

In any event, if you continue to see this issue, please open a new issue, since the old and new issues would be separate problems.

**Comment by LGRwx** [comment]
If I get this matter when I'm using centos7,what should I do? I think the reson is I install the python3.11 from the source code in the root role, and I replace the default python execution, hoping to get the advice from you! I will waiting your reply if you have any expericence about this and I will continue to find the solution to resolve this ,if I get it ,I will shared it on this issue.

**Comment by bk2204** [comment]
The error you're seeing on CentOS is different and doesn't apply here, since this issue is only for Ubuntu.  Please open a new issue and fill out the issue template, including adding the output of running the installation script, including all error messages, as a text block (not an image).

Since folks continue to comment on this closed issue, I'm going to lock it.
