### ISSUE TITLE
Take over go-ntlm?

### ISSUE THREAD

**Issue by QuLogic** [git-lfs/git-lfs#3475]
I'm just pointing out the message in the readme on `go-ntlm`:

> This repository will be removed on December 14th and will no longer be maintained and ownership will also not be transferred. Please fork this repositiory if you wish to continue to use it.

As perhaps the largest user of it (maybe? dunno how to measure), maybe `go-ntlm` can be folded into the `git-lfs` organization like was done with `go-netrc`?

Of course, it didn't actually get removed, only archived...

**Comment by bk2204** [comment]
Hey, thanks for pointing that out.

We definitely do use it, although I'm not sure we're well suited to maintain it on the whole. NTLM is used primarily on Windows, and none of the core developers use NTLM to my knowledge (although we do have one dev using Windows). I do have a copy of the latest version in case it should disappear, in which case we can re-evaluate whether we need to take it over, I think.

**Comment by ttaylorr** [comment]
> We definitely do use it, although I'm not sure we're well suited to maintain it on the whole.

I agree on both counts. Since the repository is likely not to receive new changes upstream, how would others feel about forking `go-ntlm` to `git-lfs/go-ntlm`, vendoring that, and noting in the README that we don't maintain it (promise to fix bug, etc.).

On the broader scale, I'm not sure how many users of NTLM within Git LFS there even are (or how to being to measure such a thing), but it doesn't seem like we could easily remove the feature.

**Comment by bk2204** [comment]
I think that's a good approach.

As for the number of users of NTLM, I think many Windows shops with on-premises TFS servers are likely to use it. Most people using Active Directory for authentication are using either Kerberos or NTLM for single sign-on, and we don't support Kerberos in Git LFS.

**Comment by ttaylorr** [comment]
> I think that's a good approach.

Sounds good. Do you have cycles to do this? Otherwise, I'd be happy to work on it myself.

**Comment by bk2204** [comment]
> Sounds good. Do you have cycles to do this? Otherwise, I'd be happy to work on it myself.

I'm happy to take care of it. I'll likely get to it by the first week of February, although if you'd like to pick it up sooner, please feel free.

**Comment by ttaylorr** [comment]
> > Sounds good. Do you have cycles to do this? Otherwise, I'd be happy to work on it myself.
> 
> I'm happy to take care of it.

That sounds great. I just wanted to make sure that you weren't overloaded and totally unable to fit it in.

**Comment by bk2204** [comment]
The next step is to update the README, which I've done in git-lfs/go-ntlm#1.

**Comment by bk2204** [comment]
I've updated the module declarations in git-lfs/go-ntlm#2; once that merges, I'll open a PR to update all the existing uses in this repo.
