### ISSUE TITLE
Git LFS error missing protocol on push on local network

### ISSUE THREAD

**Issue by eddogniemad** [git-lfs/git-lfs#3487]
Dear,

I setted up a local git lfs server and some tracked files but when I tried to push some files I have this error : 
`git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags origin master:master
Pushing to G:\Git\test.git
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s                                  
batch request: missing protocol: "G:\\Git\\test.git/info/lfs"
error: failed to push some refs to 'G:\Git\test.git'
Completed with errors, see above.`
G: drive is a network mapped drive. I tried with the IP address and netwok path instead but it still the same.
I'm new with git and lfs so I'm sure that there is something I missed but I'm unable to find what.

Thanks a lot for your help

**Comment by ttaylorr** [comment]
Hi @eddogniemad, thanks for opening this issue and asking a good question. It looks like what you're trying to do here is to push to a _local_ Git repository, which is supported by Git, but not by Git LFS.

See:
  - https://github.com/git-lfs/git-lfs/issues/1207,
  - https://github.com/git-lfs/git-lfs/issues/2164

for more. In the meantime, I'm going to close this issue and redirect our discussion to there. Thanks!
