### ISSUE TITLE
Prevent commit a file in LFS if the file is locked on the server

### ISSUE THREAD

**Issue by tardyp** [git-lfs/git-lfs#3489]
Hello,

I am handling the transition to git from other more "traditional" scm with relatively cmdline-un-friendly users.

Users are developing models using model base design tools, which does not support merging well.
Their models are then stored in git lfs, and we will be using git lfs locks in order to prevent people to work on the same model at the same time.

Users are worried that they may commit files by mistake that would have been locked by other users.
There is already the lockable attributes that is putting files in read-only, but our users says it is not enough, as sometimes they would still modify files owned by others for debug purposes.

Then they are worried to forgot about commit the file anyway with git commit -a at the end of day, and discover later their mistake and take a lot of time later to fix their history.

The obvious solution is to deploy a pre-commit hook on every single environment, but I would prefer to avoid that as this looks quite complicated to support maintainance wise.

**Comment by ttaylorr** [comment]
> The obvious solution is to deploy a pre-commit hook on every single environment, but I would prefer to avoid that as this looks quite complicated to support maintainance wise.

I tried to introduce some patches to this effect a couple of years ago (c.f., https://github.com/git-lfs/git-lfs/pull/1816), but we ended up deciding against it because it would require users to be online to commit, which is incompatible with Git's "work anywhere" philosophy.

That all said, I think that it still has applications in settings like yours, where you can guarantee that users are going to be online/connected to an intranet/etc. whenever they committing.

One solution for the `.git/hooks/pre-push` case (which may end up being your best bet) looks like the following:

```bash
#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	against=$(git hash-object -t tree /dev/null)
fi

locked=$(git lfs locks | cut -d '\t' -f 1)
git diff-index --cached $against -- \
  | cut -d '\t' -f 2 \
  | while read file; do
      if [ echo "$locked" | grep "$file" ]; then
        echo >&2 "fatal: $locked is already locked ..."
        exit 1
      fi
    done
```

**Comment by tardyp** [comment]
Hi @ttaylorr 

your script did not work out of the box for me. Not sure on which bash you tested it.
```
#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1; then
  against=HEAD
else
  against=$(git hash-object -t tree /dev/null)
fi

locked=$(git lfs locks | grep -v "$(git config user.name)" | cut -d$'\t' -f 1)
git diff-index --cached $against -- \
  | cut -d$'\t' -f 2 \
  | while read file; do
      if echo "$locked" | grep "$file" >/dev/null; then
        echo >&2 "fatal: $file is already locked ..."
        exit 1
      fi
    done

```
That one worked. 

Another problem of your proposal is that it does not detect if the file is locked by me or by another developer.

So I have to also grep -v "$(git config user.name)"
But I must be sure that users are configuring their user.name exactly the same as the user.name that is configured in gitlab (which is my lfs server)
The user name reported by gitlab is the full name inside gitlab, and not the full name as defined by git config user.name

**Comment by ttaylorr** [comment]
> That one worked.

Ah, thanks for posting it here. I did not test what I posted per-se, but I am glad that you were able to make a version of it work.

I think that this is realistically the best-case scenario we can discuss, irrespective of making more wide-sweeping changes to the protocol. So, in the meantime, I am going to close this issue, but please do not hesitate to comment back here if there is more to do. Thanks!
