### ISSUE TITLE
Custom Transfer Repo Specific Configuration

### ISSUE THREAD

**Issue by sameer** [git-lfs/git-lfs#3497]
I understand that `lfs.customtransfer.<name>.*` is ignored in the .lfsconfig for a repo for safety reasons. 

However, because `lfs.customtransfer.<name>.args` cannot be set on a repo-specific basis, I don't really see a way to store repo-specific configuration other than keeping my own `.customtransferconfig` in the repository.

Is there something I'm missing?

**Comment by bk2204** [comment]
I think it should be possible for you to store this information in the `.git/config` file in your repository. However, it won't be cloned with the repository, as you pointed out.

The usual suggestion for deploying this kind of configuration that Git upstream uses is a `Makefile` target (or equivalent in your language of choice) to set the `.git/config` file using `git config`.
