### ISSUE TITLE
File is shown as modified after fresh clone

### ISSUE THREAD

**Issue by lavinia8** [git-lfs/git-lfs#3504]
A LFS file (file.jar) is shown as modified after fresh clone & checkout. I'm trying to find the root cause: I'm looking for diffs between the latest commits (C2-C1-C0; C0 is the parent of C1; C1 is the parent of C2) and I've noticed something strange related to the way the line ending in pointer file is interpreted by `git diff` 
Please help me read the diffs between these commits:

```
$ git diff C2 C1 file.jar
diff --git a/file.jar b/file.jar
index bf7ec7a..18ceba8 100644
--- a/file.jar
+++ b/file.jar
@@ -1,3 +1,3 @@
 version https://git-lfs.github.com/spec/v1
-oid sha256:3cf599d776...
-size 1573798
+oid sha256:41e2412053...
+size 1567232
\ No newline at end of file
```
```
$ git diff C1 C0 file.jar
diff --git a/file.jar b/file.jar
index 18ceba8..0a049bb 100644
--- a/file.jar
+++ b/file.jar
@@ -1,3 +1,3 @@
 version https://git-lfs.github.com/spec/v1
-oid sha256:41e2412053...
-size 1567232
\ No newline at end of file
+oid sha256:892f0b462a...
+size 1525089
```
```git checkout C1``` => file.jar is seen as modified as shown below
```
$ git diff
diff --git a/file.jar b/file.jar
index 18ceba8..e73d2ca 100644
--- a/file.jar
+++ b/file.jar
@@ -1,3 +1,3 @@
 version https://git-lfs.github.com/spec/v1
 oid sha256:41e2412053...
-size 1567232
\ No newline at end of file
+size 1567232
```
`.gitattributes` looks like this (in C0, C1, C2):
```
*.a filter=lfs diff=lfs merge=lfs -text
*.so filter=lfs diff=lfs merge=lfs -text
*.chm filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
*.dll filter=lfs diff=lfs merge=lfs -text
*.jar filter=lfs diff=lfs merge=lfs -text
*.pdf filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
```
My global git config:
```
...
filter.lfs.required=true  
filter.lfs.clean=git-lfs clean -- %f  
filter.lfs.smudge=git-lfs smudge -- %f 
filter.lfs.process=git-lfs filter-process
...
```
Git version: `git version 2.20.1.windows.1`
Git LFS version: `git-lfs/2.6.1 (GitHub; windows amd64; go 1.11.1; git dc072c3e)`

I've already checked the following issues: https://github.com/git-lfs/git-lfs/issues?utf8=%E2%9C%93&q=modified+in%3Atitle

**Comment by lavinia8** [comment]
I got my answer by running `git cat-file -p :file.jar | od -c`.
I'm still continuing the investigation, but this issue can be closed.

**Comment by ttaylorr** [comment]
@lavinia8 I'm glad that you were able to resolve the issue. What is usually going on in these cases it that someone with write-access to the repository who did not have Git LFS installed/configured correctly pushed a large object where there should have been a pointer instead.

This can happen from time to time, and is sometimes solved with `git lfs migrate import --fixup --everything`.

Let us know if you have any other questions, or run into other difficulties in the future!
