### ISSUE TITLE
GIT_LFS_SKIP_SMUDGE not documented

### ISSUE THREAD

**Issue by mloskot** [git-lfs/git-lfs#3505]
The environment variable `GIT_LFS_SKIP_SMUDGE` seems to be undocumented:

```
git-lfs (master) $ find docs -type f| xargs grep -i GIT_LFS_SKIP_SMUDGE
git-lfs (master) $ find docs -type f| xargs grep -i skip_smudge
git-lfs (master) $
```

The Wiki does not seem to include any related articles either
https://github.com/git-lfs/git-lfs/search?q=GIT_LFS_SKIP_SMUDGE&type=Wikis

Is that intentional?

**Comment by bk2204** [comment]
No, I don't think this was intentional, but more likely just an oversight. I'll tag this so that we can remember to document it for the future.

**Comment by mloskot** [comment]
Thanks! I thought the intention may be to keep it somewhat low-level hidden feature.
