### ISSUE TITLE
Git pollutes working directory during pull on LFS error

### ISSUE THREAD

**Issue by sbmueller** [git-lfs/git-lfs#3507]
When I try to pull from a remote, non-LFS files get checked out.
However, as soon as a LFS file in the pull process is hit, and the pull/checkout of the LFS file fails, the pull is aborted, leaving the working directory partly polluted with files from the remote commits. See the following output:
```
$ git status
On branch master
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
$ git pull origin master
Enter passphrase for key '...':
From [url]
 * branch            master     -> FETCH_HEAD
Updating [hash0]..[hash1]
Downloading [specific file] (26 MB)
Error downloading object: [specific file] (hash1): Smudge error: Error downloading [specific file]([file hash]): batch request: RSA host key for IP address '...' not in list of known hosts.
git@[server]: Permission denied (publickey).: exit status 255

Errors logged to [path]
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: [specific file]: smudge filter lfs failed
Cannot rebase: You have unstaged changes.
Please commit or stash them.
$ git status
[lists plenty of modified files]
```
Before and after I am on the same commit according to `git log`. I won't share the LFS error log since this is not issue I'd like to address here (probably wrong server configuration). However, if some LFS related error occurs during checkout, the working directory should not be polluted with partial files from another commit IMO.
```
git lfs --version
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
```

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I think this is actually a Git issue. The smudge and clean filters are run by Git, and Git doesn't clean up when a checkout fails halfway through, whether that's due to filters or for other reasons.

The best way to get this fixed would be to send a bug report to [the Git mailing list](mailto:git@vger.kernel.org). I suspect, however, that there are existing reasons why Git itself doesn't handle this, such as that if a failure occurred the first time, it may also occur on the attempt to roll back.

**Comment by 8ctopus** [comment]
@bk2204 I've ran in the very same issue sbmueller experienced and was wondering if it would be possible to have a flag that would ignore git lfs download errors in order for git status not be affected by failed download?

**Comment by bk2204** [comment]
There's already `GIT_LFS_SKIP_SMUDGE` which prevents Git LFS from attempting to convert any files so you can later run `git lfs pull`.  That will prevent Git LFS from downloading anything during checkout so no download errors will affect the checkout.

If you're asking specifically for an option to ignore download failures only, no, we don't have one, and I don't think we're likely to add one.  An option like that would be an easy way to cause surprising and hard-to-troubleshoot behavior.
