### ISSUE TITLE
Fail install in ubuntu 16.04

### ISSUE THREAD

**Issue by liujian1990** [git-lfs/git-lfs#3517]
When i run apt-get install git-lfs in Ubuntu 16.04，here's the mistake.
`
Setting up base-files (9.4ubuntu4.7) ...
rmdir: failed to remove '/var/run': Directory not empty
dpkg: error processing package base-files (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 base-files
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

This message looks like it indicates a problem with the Ubuntu `base-files` package. It's true that that may prevent the installation of Git LFS, but that's an issue that should probably be reported to Ubuntu. I think, in fact, that [it already has](https://bugs.launchpad.net/ubuntu/+source/base-files/+bug/874505).

I'm not sure there's anything we (as the Git LFS maintainers) can do in this case.
