### ISSUE TITLE
how to clone local repo with remote repository to upload files larger than 100MB

### ISSUE THREAD

**Issue by syndy1989** [git-lfs/git-lfs#3521]
Hi,

I'm new to Git LFS. I'm able to upload files less than 100MB to git remote repository by cloning th elocal repo with remote repo. Is there any way to upload larger files using Git LFS. If possible , any advise on how to achieve that on windows would be really helpful and a working example would be great. Thanks in advance

**Comment by ttaylorr** [comment]
Hi @syndy1989, thanks for opening this issue and sorry that you're having trouble.

> Is there any way to upload larger files using Git LFS.

The 100 MiB limit that you're referring to is a limit that GitHub imposes when pushing objects that _aren't_ tracked by Git LFS. To "use" Git LFS in your repository, it must be both (1) installed, and (2) told to track some files.

Detailed instructions of how to do this can be found both on [our website](https://git-lfs.github.com), in [our README](https://github.com/git-lfs/git-lfs) and in [our Wiki](https://github.com/git-lfs/git-lfs/wiki/Installation).

If you have already committed files that were larger than 100 MiB, you can _migrate_ them fafter the fact into Git LFS by running `git lfs migrate import --include="/path/to/file" --everything` for each affected file (or you can replace `/path/to/file` with a pattern instead).

Please let us know if you have any further questions and we'd be more than happy to re-open this issue and help you out. Thanks!
