### ISSUE TITLE
git clone -> Object does not exist on the server: [404] Object does not exist on the server

### ISSUE THREAD

**Issue by sevPuch** [git-lfs/git-lfs#3525]
Hi, 
This will seem like a recurrent topic but I browsed every answers and nothing helped me.

On my first workstation everything works, 
On existing project, I ran     git lfs install    
Then every time I uploaded a .FBX :    git add .    git commit -m ""    git push

I did have a lot of lfs-smudge failures during my numerous attempts to upload those .fbx files during development.

I have got a .gitattributes with .fbx mentioned.
The files are correctly mentioned inside my BitBucket project on their website.

But everytime I try to clone the repo on another computer, this error pops out for each .fbx file :

`
C:\Users\pull_\Documents\insomnia\insomnia>git lfs pull
[43a68730661c6c6f9ce49acf95ca2e36914062f57e3e2b725484a77f9eb15909] Object does not exist on the server: [404] Object does not exist on the server
[41ebe82c2f4114cf9524dcb46b69ea6cb673dfee53b5df70f49dfafc6fcbf5ed] Object does not exist on the server: [404] Object does not exist on the server
[ec84b544c1a141d91638833d542ae76460ee91f4681cccc09a7cea0ac438ad79] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://bitbucket.org/sevPuch/insomnia.git/info/lfs'
`

Did I forget a step or did something wrong ?
Thank you

This is my git lfs env output :

`C:\Users\pull_\Documents\insomnia\insomnia>git lfs env
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git [6f4b2e9](https://github.com/git-lfs/git-lfs/commit/6f4b2e98e038530a3e26d26726799832290c61c4))
git version 2.18.0.windows.1`

`Endpoint=https://bitbucket.org/sevPuch/insomnia.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\pull_\Documents\insomnia\insomnia
LocalGitDir=C:\Users\pull_\Documents\insomnia\insomnia.git
LocalGitStorageDir=C:\Users\pull_\Documents\insomnia\insomnia.git
LocalMediaDir=C:\Users\pull_\Documents\insomnia\insomnia.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\pull_\Documents\insomnia\insomnia.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\pull_\Documents\insomnia\insomnia.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f" `

**Comment by sevPuch** [comment]
This is my git lfs env output :

C:\Users\pull_\Documents\insomnia\insomnia>git lfs env
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
git version 2.18.0.windows.1

Endpoint=https://bitbucket.org/sevPuch/insomnia.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\pull_\Documents\insomnia\insomnia
LocalGitDir=C:\Users\pull_\Documents\insomnia\insomnia\.git
LocalGitStorageDir=C:\Users\pull_\Documents\insomnia\insomnia\.git
LocalMediaDir=C:\Users\pull_\Documents\insomnia\insomnia\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\pull_\Documents\insomnia\insomnia\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\pull_\Documents\insomnia\insomnia\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by sevPuch** [comment]
When I fetch --all, it finds the objects but then say they don't exist on the server. They are present in the source files though...

`C:\Users\pull_\Documents\insomnia\insomnia>git` lfs fetch --all`

fetch: 6 object(s) found, done
fetch: Fetching all references...
[43a68730661c6c6f9ce49acf95ca2e36914062f57e3e2b725484a77f9eb15909] Object does not exist on the server: [404] Object does not exist on the server
[41ebe82c2f4114cf9524dcb46b69ea6cb673dfee53b5df70f49dfafc6fcbf5ed] Object does not exist on the server: [404] Object does not exist on the server
[ec84b544c1a141d91638833d542ae76460ee91f4681cccc09a7cea0ac438ad79] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://bitbucket.org/sevPuch/insomnia.git/info/lfs'

**Comment by ttaylorr** [comment]
Hi @sevPuch thanks for opening this issue, and I'm sorry that you're having trouble. It's possible that what is going on here is that the files you were tracking under Git LFS were never pushed to your remote. You can verify this by running `git lfs migrate --info --everything`, which will give you a rough approximation of how much space in your repository is occupied by different file extensions (e.g., if `*.psd` is taking up 1GiB, it's likely that there are PSDs not being tracked under Git LFS).

You can fix any of these with the following:

```ShellSession
$ git lfs migrate import --everything --include="/path/to/file"
$ git push --force --all <remote>
```

Once you do that, all of your files tracked using Git LFS should be present on the remote. Please let us know if you have any other questions here in the future, and we'd be happy to re-open this issue and dive in further.

**Comment by Cliwo** [comment]
@ttaylorr Hi, sorry for bother you but I think it's `git lfs migrate info --everything` not `--info`.
Other people who may see this can be confused so I made this comment with no offense. 

But anyway this information is great! Thank you.

**Comment by MichaelBelousov** [comment]
In case it helps anyone else, I had to explicitly invoke the lfs push like: `git lfs push --all origin`
