### ISSUE TITLE
2.7.0 not available on PackageCloud

### ISSUE THREAD

**Issue by petermarko** [git-lfs/git-lfs#3532]
PackageCloud has still 2.6.1 as latest version 4 days after 2.7.0 was released.
The download links on release page are thus not working.
Could you please upload the new packages?

**Comment by bk2204** [comment]
Hey, thanks for reporting this.

As you noticed, I did forget to upload the packages. They should be uploaded now and available for use. My apologies for forgetting.

**Comment by ttaylorr** [comment]
@bk2204 Do you think that it's possible to integrate this step into your recent build automation work?

**Comment by bk2204** [comment]
Yes, it's likely possible to do. My hope is to make it part of future iterations of the release automation work. Eventually, I plan to have four steps: do Unix work; do Windows work; repackage, upload, and create release; and human sanity-check.
