### ISSUE TITLE
go panic on pull

### ISSUE THREAD

**Issue by godnotking** [git-lfs/git-lfs#3540]
```
$ git lfs pull
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x74d425]

goroutine 500 [running]:
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc0001906c8, 0xc                             00004c300, 0xc000637a70, 0x0, 0xc000628200, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/basic_download.go:124 +0x                             3b5
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc0001906c8, 0                             x0, 0x0, 0xc00004c300, 0xc000637a70, 0x0, 0xc0002389b0, 0xc000238a00)
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/basic_download.go:49 +0xc                             3
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc000778090, 0x6, 0x0, 0x0)
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/adapterbase.go:177 +0x54b
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
```
   

when I download from a unity offical project , the mistake occurs, I don't konw how to handle this, so   help me,plz.

**Comment by ttaylorr** [comment]
I believe that @bk2204 fixed this in https://github.com/git-lfs/git-lfs/pull/3534 and https://github.com/git-lfs/git-lfs/pull/3537, which should be in the new release of Git LFS within the next few days.

**Comment by godnotking** [comment]
em....   thanks for you apply,  I just post more logs blow in case.

`Diego@Diego-PC MINGW64 /e/u3dProjects/fgfg/FPSSample (master)
$  GIT_TRACE_PACKET=1 git lfs pull
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x74d425]

goroutine 396 [running]:
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc000474120, 0xc0004dd9e0, 0xc0004890c0, 0x0, 0xc00008a018, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/basic_download.go:124 +0x3b5
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc000474120, 0x0, 0x0, 0xc0004dd9e0, 0xc0004890c0, 0x0, 0x0, 0x0)
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/basic_download.go:49 +0xc3
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc0005101b0, 0x1, 0x0, 0x0)
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/adapterbase.go:177 +0x54b
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
        C:/Users/brian m. carlson/checkouts/git-lfs/tq/adapterbase.go:90 +0x2b4

`
