### ISSUE TITLE
git lfs fetch fails behind a proxy

### ISSUE THREAD

**Issue by vpoughon** [git-lfs/git-lfs#3551]
I cannot get `git lfs fetch` to work behind my corporate proxy. Same error when it's configured with either the env var `http_proxy` or `git.config http.proxy`.

I looked at the proxy server logs with a sysadmin and it appears git-lfs is not even adressing the proxy, but trying to access the network directly (hence the DNS error). Regular git and other network activities work fine in this configuration.

```
poughov@visu01 ~/git-lfs-test (master) GIT_TRACE=1 GIT_CURL_VERBOSE=1 git lfs fetch
09:34:08.048441 git.c:659               trace: exec: git-lfs fetch
09:34:08.048508 run-command.c:637       trace: run_command: git-lfs fetch
09:34:08.053249 trace git-lfs: exec: git 'version'
09:34:08.057553 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
09:34:08.061509 trace git-lfs: exec: git 'config' '-l'
fetch: Fetching reference refs/heads/master
09:34:08.068258 trace git-lfs: filepathfilter: accepting ".gitattributes"
09:34:08.068353 trace git-lfs: filepathfilter: accepting "binary.jpg"
09:34:08.069900 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
09:34:08.072382 trace git-lfs: tq: running as batched queue, batch size of 100
09:34:08.072416 trace git-lfs: fetch binary.jpg [6fe2e48ef494b7855e6d8f93c59cf38d38350274e304a9ac35102d5c365ee002]
09:34:08.072576 trace git-lfs: tq: sending batch of size 1
09:34:08.073006 trace git-lfs: api: batch 1 files
09:34:08.073336 trace git-lfs: HTTP: POST https://github.com/Schoonology/git-lfs-test.git/info/lfs/objects/batch
> POST /Schoonology/git-lfs-test.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Length: 160
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)
>
09:34:08.150854 trace git-lfs: api error: Post https://github.com/Schoonology/git-lfs-test.git/info/lfs/objects/batch: proxyconnect tcp: dial tcp: lookup http on 10.120.2.10:53: no such host
batch response: Post https://github.com/Schoonology/git-lfs-test.git/info/lfs/objects/batch: proxyconnect tcp: dial tcp: lookup http on 10.120.2.10:53: no such host
error: failed to fetch some objects from 'https://github.com/Schoonology/git-lfs-test.git/info/lfs'
```

Versions:
```
poughov@visu01 ~ git --version
git version 2.19.1
poughov@visu01 ~ git-lfs --version
git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)
```
Test repo:
https://github.com/Schoonology/git-lfs-test

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I _think_ the issue that you're seeing is that your DNS isn't resolvable without the proxy. The `http_proxy` (and `https_proxy`) headers don't control the use of DNS; there isn't an environment variable that can be enabled to force non-HTTP(S) data through the proxy, and Go doesn't do so.

If that's not the case (i.e., you're able to successfully reach the DNS server without the use of the proxy), can you specify the protocol scheme for the proxy URL? I know that Go natively supports proxies with the `http`, `https`, and `socks5` (but not `socks5h`) protocol schemes, and so those should work automatically. It may also be worthwhile to try setting the `https_proxy` environment variable and see if that works for your situation.

**Comment by vpoughon** [comment]
Thanks for the quick reply!

> you're able to successfully reach the DNS server without the use of the proxy

I'm not sure how to test this, but I think I'm able to (let me know if that's not what you mean):

```
poughov@visu03 ~ unset http_proxy
poughov@visu03 ~ unset https_proxy
poughov@visu03 ~ echo $http_proxy

poughov@visu03 ~ echo $https_proxy

poughov@visu03 ~ host github.com
github.com has address 140.82.118.4
github.com has address 140.82.118.3
github.com mail is handled by 10 alt3.aspmx.l.google.com.
github.com mail is handled by 10 alt4.aspmx.l.google.com.
github.com mail is handled by 5 alt1.aspmx.l.google.com.
github.com mail is handled by 5 alt2.aspmx.l.google.com.
github.com mail is handled by 1 aspmx.l.google.com.
poughov@visu03 ~ nslookup github.com
Server:		10.120.2.10
Address:	10.120.2.10#53

Non-authoritative answer:
Name:	github.com
Address: 140.82.118.4
Name:	github.com
Address: 140.82.118.3
```

Here's my proxy (anonymized):

```
http://username:password@host.fr:8050
```

Note that it requires authentication, and that in my case the username contains a backslash (because it's actually a windows username somehow... sigh), might be relevant.

I usually set it with this in my `.bashrc`:

```
export http_proxy=http://user:password@host.fr:8050
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
```

But I also tried with `git config --global http.proxy http://username:password@host.fr:8050` and got the same error.

**Comment by bk2204** [comment]
> Note that it requires authentication, and that in my case the username contains a backslash (because it's actually a windows username somehow... sigh), might be relevant.

I'm wondering if this is related. Does it work for you if you specify the backslashes in the username as `%5C`? If there are any other odd characters in the username or password, does percent-escaping them as well help?

**Comment by vpoughon** [comment]
OMG that's it. It works with `%5C`. https://xkcd.com/1638/ i guess...

**Comment by vpoughon** [comment]
Thank you so much for your quick and efficient help! I'll let you decide if this is a bug or not for git-lfs.

**Comment by bk2204** [comment]
Great, glad it's working for you now.

I think this is a difference between how Go parses URLs in order to implement its proxy support and how glibc and other tools do. The grammar for RFC 3986 implies that backslashes have to be percent-encoded in URLs, so I think what Go is doing is valid here, and I don't think there's a bug. This is a tricky spot where there's likely to be divergence in implementations, though, so I'm not surprised we ran into this issue.
