### ISSUE TITLE
git lfs status shows non-LFS files in "objects to be committed" 

### ISSUE THREAD

**Issue by kuvaldini** [git-lfs/git-lfs#3552]
`.gitattributes  `            
```                                                    
tools.tgz filter=lfs diff=lfs merge=lfs -text
```
`git status`
```
On branch master
Your branch is ahead of 'kuvaldini/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   Dockerfile
```
 `git lfs status `
```
On branch master
Git LFS objects to be pushed to kuvaldini/master:


Git LFS objects to be committed:

        Dockerfile (Git: 5205814 -> Git: 1a00bcf)

Git LFS objects not staged for commit:
```
### Why non-LFS file is show in "to be committed" section? It That normal?

`git --version`
```
git version 2.17.2 (Apple Git-113)
```
`git lfs --version`
```
git-lfs/2.7.1 (GitHub; darwin amd64; go 1.12)
```

**Comment by kuvaldini** [comment]
`git commit`
than
`git lfs ls-files`
```
5ba4a9bdb9 * tools.tgz
```
### Dockerfile was not added as LFS object. So works fine.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I'm inclined to say that it was intentional to include regular Git files, but I'm not sure. @ttaylorr, do you know if this behavior is intentional or an accident?

**Comment by ttaylorr** [comment]
> I'm inclined to say that it was intentional to include regular Git
> files, but I'm not sure. @ttaylorr, do you know if this behavior is
> intentional or an accident?

I think that this is intentional, though it does leave me scratching my
head a bit. The original rationale is in https://github.com/git-lfs/git-lfs/pull/2070:

> 1. Since #2042, we're showing all files (not just those tracked by LFS) in
>    the status output. I think this makes sense since we want to show
>    files that are supposed to be tracked by LFS but aren't.

This behavior is admittedly quite confusing, but since we've been
shipping it since https://github.com/git-lfs/git-lfs/pull/2042, I'm
inclined to leave it as-is.

**Comment by kuvaldini** [comment]
Hello. Thank you responses!

**Comment by kuvaldini** [comment]
```
Git LFS objects to be committed:

        Dockerfile (Git: 5205814 -> Git: 1a00bcf)
```

This means that 'Dockerfile' will be committed as LFS object! And sure, I have no idea to treat this message as "Git LFS can track this file be it is not tracked by Git LFS at the moment"

**Comment by bk2204** [comment]
> This means that 'Dockerfile' will be committed as LFS object! And sure, I have no idea to treat this message as "Git LFS can track this file but it is not tracked by Git LFS at the moment"

No, the “Git” portion of it means that it will be committed as a regular Git object. If it said “LFS”, then it would be committed as an LFS object. It is a bit confusing, but as @ttaylorr pointed out, it is intended.

I agree we should probably update the documentation to reflect this better, so I'll leave this issue open to track that.

**Comment by kuvaldini** [comment]
I understand how does it work. And glad to hear that you agree about messages is not  obvious enough. 

I think we should distinguish 1) files changed and **not** tracked by git-lfs, and 2) files changed and tracked by git-lfs.

I suggest to add one more section to `git lfs status` "Git non-LFS objects to be commited:". 

So user will know what is LFS and what is not.

**Comment by jobh** [comment]
The major problem here is not documentation, but display output. The word LFS is misleading and wrong in these headers, since the listed objects may or may not be tracked by LFS.

```
Git LFS objects to be committed:
Git LFS objects not staged for commit:
````
If it is difficult to separate LFS-tracked objects from plain objects, at least remove the word LFS here.

**Comment by austintraver** [comment]
Some confusion about the output of `git lfs status` brought me here, so I guess I'm not the only one who is a little confused. The current output shows something like this:

I agree with @jobh's suggestion to just remove the word `LFS`, since it confused me as well. After all, if a user wants to know what files are covered under LFS, they see the `(LFS: d21df4f)` tag at the end of a filepath.

If this is a feature that I can work on, I'm happy to help. I'd just need to know where to start.

**Comment by bk2204** [comment]
We'd be happy to accept a patch here that changed things to say just "Objects to be committed" or such.  If you run `git grep` on the codebase, you'll find the text in the appropriate files and tests, which should give you a good idea where to start.  If you have more questions, I'm happy to answer them.
