### ISSUE TITLE
git runs out of memory checking out very large files

### ISSUE THREAD

**Issue by kristjanvalur** [git-lfs/git-lfs#3559]
We have a large asset, around 48GiB.  It has already been synced into .git/lfs/objects.
When doing `git reset --hard master` to the current revision, it would appear that this file is read into "git" memory and possibly also the corresponding file in the workspace.  On my 32GB workstation (windows 10) it failes in realloc() having gobbled up more than 60GiB of virtual ram.  
I"m doing `git reset` rather than `git pull` since I specifically just want a clean slate, and to avoid any binary compares of the files.  The lfs file should really just show up in the workspace, having been copied from the lfs/objects store.

I'm no expert in git or lfs, or smudge filters, but I wonder if it shouldn"t be possible to make smudge filters work with temporary files and renames, rather than having to pipe everything in and out of memory? In this case, git could ask git-lfs to place the smudged file in a temporary location, then perform an on-disc compare of that vs the workspace file.

p.s. I just increased my ram to 64 GiB, and it finally managed to process this particular file, but see how it looks while doing it.  The file it is processing is 48GiB.
![Capture](https://user-images.githubusercontent.com/6009543/54315028-18ec4a00-45d5-11e9-9992-855760a98320.PNG)

**Comment by kristjanvalur** [comment]
I noticed issue https://github.com/git-lfs/git-lfs/issues/2434.  We haven't run into that problem.  Using precompiled win64 windows versions of git/git-lfs, versions 2.21.0 and 2.7.1 respectively.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This is a known issue in Git core that [has been discussed on the upstream list[(https://public-inbox.org/git/20190124003948.GS423984@genre.crustytoothpaste.net/). I'm pretty sure Git LFS is clean in this regard, but the limitation is Git itself, which stores the smudge and clean contents into memory before writing it. Since all smudge and clean operations go through Git, you see this behavior. You can probably use `git lfs checkout` to bypass this issue, since those operations don't go through Git.

I'd recommend reaching out to Git upstream about this issue, since they're better equipped to deal with it. The proposal you suggested, temporary files and renames, has been discussed there, but not implemented.

**Comment by kristjanvalur** [comment]
Right.  After writing this issue, I tried the workaround mentioned in that other defect, --skip-smudge, and it works.  I've been battling this for days, just trying to pull a branch.  But it's not the nicest of solutions, particularly for people that are used to things just working, e.g. in P4.

I realize that the implementation of smudge/clean is not the domain of git-lfs, never the less, git-lfs does enjoy a "special relationship" with git (at least, to an outside observer).  I wanted to raise this issue here since this team might be in a unique position to persuade the GIT devs that a different approach might be needed to implement LFS than the traditional piped smudge filters.

Oh, and I hope git-lfs is 64 bit clean (i.e. using off_t or similar for file access rather than "long int" as the git team seems to have naively done :)

**Comment by bk2204** [comment]
I'll say that other than having two maintainers who are also Git contributors, and being packaged with Git for Windows (which is its maintainer's decision, although one we are grateful for), Git LFS doesn't have that special of a relationship with upstream.

To my knowledge, the only 64-bit cleanliness issue was #3426, which was included in Git LFS 2.7.0. We use Go, not C, for Git LFS, which means that all the system file size types are `int64`, so they work equally well on all platforms.
