### ISSUE TITLE
git push  fail in ubuntu16.04

### ISSUE THREAD

**Issue by yiqisiben** [git-lfs/git-lfs#3562]
git config -l
>16:05:16.847923 git.c:344               trace: built-in: git 'config' '-l'
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/yiqisiben/cc520.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.https://github.com/yiqisiben/cc520.git/info/lfs.locksverify=false

git lfs env
>16:13:30.954748 git.c:561               trace: exec: 'git-lfs' 'env'
16:13:30.954787 run-command.c:334       trace: run_command: 'git-lfs' 'env'
16:13:30.958549 trace git-lfs: exec: git 'version'
git-lfs/2.7.1 (GitHub; linux amd64; go 1.11.5)
git version 2.7.4
16:13:30.959808 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=cat' '-c' 'filter.lfs.clean=cat' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
16:13:30.962745 trace git-lfs: exec: git 'config' '-l'
Endpoint=https://github.com/yiqisiben/cc520.git/info/lfs (auth=none)
LocalWorkingDir=/home/qinjunfeng/cc520
LocalGitDir=/home/qinjunfeng/cc520/.git
LocalGitStorageDir=/home/qinjunfeng/cc520/.git
LocalMediaDir=/home/qinjunfeng/cc520/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/qinjunfeng/cc520/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/qinjunfeng/cc520/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_TRACE_PACKET=1
GIT_TRACE=1
GIT_CURL_VERBOSE=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
16:13:30.964656 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
16:13:30.964670 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
16:13:30.964712 trace git-lfs: filepathfilter: accepting "tmp"

software version:
>git version 2.7.4
git-lfs/2.7.1 (GitHub; linux amd64; go 1.11.5)

error log:
>16:07:21.319541 run-command.c:334       trace: run_command: '.git/hooks/pre-push' 'origin' 'https://github.com/yiqisiben/cc520.git'
16:07:21.321587 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin' 'https://github.com/yiqisiben/cc520.git'
16:07:21.321632 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'https://github.com/yiqisiben/cc520.git'
16:07:21.325380 trace git-lfs: exec: git 'version'
16:07:21.328069 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=cat' '-c' 'filter.lfs.clean=cat' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
16:07:21.331164 trace git-lfs: exec: git 'config' '-l'
16:07:21.332835 trace git-lfs: pre-push: refs/heads/master 736b12443b66a395ca669ceb94729d15cd256e59 refs/heads/master ff1e9d8401f30f473bb1b10032754684c83af858
16:07:23.006513 trace git-lfs: tq: running as batched queue, batch size of 100
16:07:23.006589 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
16:07:23.008106 trace git-lfs: tq: sending batch of size 1
16:07:23.008239 trace git-lfs: api: batch 1 files                                                                                                
16:07:23.008500 trace git-lfs: HTTP: POST https://github.com/yiqisiben/cc520.git/info/lfs/objects/batch
> POST /yiqisiben/cc520.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Length: 159
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.7.1 (GitHub; linux amd64; go 1.11.5)
> 
>16:07:24.231717 trace git-lfs: api error: Post https://github.com/yiqisiben/cc520.git/info/lfs/objects/batch: proxyconnect tcp: EOF
batch response: Post https://github.com/yiqisiben/cc520.git/info/lfs/objects/batch: proxyconnect tcp: EOF
error: failed to push some refs to 'https://github.com/yiqisiben/cc520.git'

What should i do ?

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

It looks like you've configured a proxy, likely using either the `http_proxy` or `https_proxy` environment variables and that proxy is dropping the connection. If you don't want to connect with a proxy, you should unset those environment variables. Otherwise, you should talk to whomever set up the proxy and see if they can help you figure out why you're seeing this issue.

Note that Git LFS can use proxies using the `http`, `https`, and `socks5` protocols, but not `socks5h`. This is a limitation of the Go proxy support that we use.
