### ISSUE TITLE
git rebase xxx/master or git lfs fetch. all failed 

### ISSUE THREAD

**Issue by darbee** [git-lfs/git-lfs#3565]
**Run git rebase xxx/master command failed:**

`Pointer file error: Unable to parse pointer at: "XXXXX.bin"`
`Downloading
  modules/data/poly.png (58 KB)
  Error downloading object: modules/data/poly.png (1de4e61): Smudge error: Error downloading 
  modules/data/poly.png `
  `  (1de4e61f1498209b555d2343afa40089f823297e087bdfbad4c61155fb3a4959): 
      [1de4e61f1498209b555d2343afa40089f823297e087bdfbad4c61155fb3a4959] Object does not 
      exist on the server: [404] Object does not exist on the server`
`Errors logged to /home/dabin/.git/lfs/logs/20190319T164916.940861443.log
  Use `git lfs logs last` to view the log.
  error: external filter git-lfs smudge -- %f failed 2
  error: external filter git-lfs smudge -- %f failed
  smudge filter lfs failed
  could not detach HEAD`

**run git lfs fetch ：**

`fetch: Fetching reference refs/heads/master
  Dwnloading LFS objects:   0% (1/553), 96 MB | 0 B/s`
`[7e432d34f446602bb3f51f36a3a3900d0e7a96ec37fb7d18cf6cfdd2f7747475] Object does not exist 
   on the server: [404] Object does not exist on the server
  error: failed to fetch some objects from 'https://github.com/darbee/expamle.git/info/lfs'`

**Even if I remove the total  repository,  and git clone it again:**
 git clone git@github.com:darbee/expamle.git
  It also report the error same as   git rebase xxx/master.

Only I uninstall git lfs and reinstall git(not install fit lfs) it become normal. 

Please do not hesitate to let me know if you need more information. I need help really, thanks all

**Comment by darbee** [comment]
@ttaylorr @technoweenie

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This error means that the server from which you're cloning the data is lacking one or more of the objects required. You can try doing a `git lfs fetch --all`, or if you or someone you're working with have another copy of the repository, you can try running `git lfs push --all` with that copy to see if you can push any objects you're missing.

If you think you uploaded this object before and it's missing, you may want to reach out to your hosting provider to see if they can help you figure out what's going on. If that's GitHub, you should reach out to support@github.com; this project is only for the client side, and what you're seeing is an issue with the server.

Note that as of recently, GitHub no longer allows you to push Git objects if you haven't pushed the Git LFS objects requires, but older repositories may have missing objects if all of the objects weren't pushed.
