### ISSUE TITLE
error: GH008: Your push referenced at least 22 unknown Git LFS objects

### ISSUE THREAD

**Issue by xing1121** [git-lfs/git-lfs#3574]
I drop my git repository and prepare to make new one for some reasons.
  I commit my file, and use eclipse to push my file to github.But get this:

----
pre-receive hook declined
error: GH008: Your push referenced at least 22 unknown Git LFS objects:
    1c41ce10a20882529bfed0bae82520a6f5916ff5c9937144fe34f33a912a007e
    1ea929fa1e103d91773a9317cb8ad9e6178258db6c1e1520393e78e3a3dc4df5
    a806c673b3a518e8a19bfa329cfb5ab96c9a69a99d729ba4cec96751c83d8e6e
    ...
Try to push them with 'git lfs push --all'.
----

  Then I use windows cmd 'git lfs push --all origin', It doesnt work either. I got 'LFS:Put https://github-cloud.s3.amazonaws.com/alamic/media/xxxxxxxxx...:wsarecv:An existing connection was forcibly closed by the remote host' this time.
  How should I do?

**Comment by xing1121** [comment]
LFS: Put https://github-cloud.s3.amazonaws.com/alambic/media/207297333/39/2e/392
e936d09f8a7b31f0ee82fb6f3cdb720d71d3b12b2932763868c332a604e48?actor_id=30796801:
 read tcp 100.120.5.87:10124->52.216.134.211:443: wsarecv: An existing connectio
n was forcibly closed by the remote host.

**Comment by xing1121** [comment]
Seems my'net has been limited to github-cloud.

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble here.

This looks like an issue with GitHub and the network between you and them. Could you reach out to support@github.com and talk to them? This project is for the Git LFS client, and we're not equipped to handle issues with GitHub itself here.
