### ISSUE TITLE
not seeing progress fro git lfs pull

### ISSUE THREAD

**Issue by kristjanvalur** [git-lfs/git-lfs#3575]
With version 2.7.1, we're not seeing progress when doing git lfs pull.  I've not been able to find any sort of --verbose flag or anything, but I have found several issues mentioning similar things, including issue #3000.

We have a bunch of rather large resources, going into the gigabytes, and a `git lfs pull` just sits there silently for minutes, and then completes.  We are using sourcetree and running in a Mingw shell on windows.  

Separate 'git lfs fetch' and 'git lfs checkout' do produce some output:
```
kristjan@winsys013 MINGW64 /d/git/p126 (master)
$ git lfs checkout
Checking out LFS objects: 100% (899/899), 83 GB | 0 B/s, done

kristjan@winsys013 MINGW64 /d/git/p126 (master)
$ git lfs fetch
fetch: Fetching reference refs/heads/master

kristjan@winsys013 MINGW64 /d/git/p126 (master)
$ git lfs pull

kristjan@winsys013 MINGW64 /d/git/p126 (master)
```

git lfs env:
```
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.21.0.windows.1

Endpoint=https://gitlab.rvx.is//VR/p126.git/info/lfs (auth=none)
  SSH=git@gitlab.rvx.is:/VR/p126.git
Endpoint (github)=https://github.com/RVXStudio/p126.git/info/lfs (auth=none)
  SSH=git@github.com:RVXStudio/p126.git
Endpoint (bitbucket)=https://bitbucket.org/rvxstudio/p126.git/info/lfs (auth=basic)
  SSH=git@bitbucket.org:rvxstudio/p126.git
LocalWorkingDir=D:\git\p126
LocalGitDir=D:\git\p126\.git
LocalGitStorageDir=D:\git\p126\.git
LocalMediaDir=D:\git\p126\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\git\p126\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\git\p126\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_SSH=C:\Program Files\PuTTY\plink.exe
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This works for me on the Mac I use for development. Can you try this inside a Git Bash or Git CMD window and see if it works for you there? I know that there are some differences in how terminals function in a pure Windows environment versus some Unix emulation layers, and as a consequence `isatty` can return false in some cases where a terminal is available. There are some cases where we force progress output on, and some cases where we rely on a TTY, and I'm wondering if you're hitting one of the latter cases.

**Comment by kristjanvalur** [comment]
Right, I found that it works in the windows command prompt, but not in the MINGW64 shell.
I can confirm your hypothesis, in mingw, `python -c "import sys; print(sys.stdout.isatty())"` returns False, whereas in the windows cmd shell it returns True.

git-bash.exe is spawning a mintty.exe, which might be the source of the problem?  Indeed, a quick google gives me this: https://stackoverflow.com/questions/40912072/git-for-windows-mintty-sys-stdout-isatty-returns-false

I wonder if you could add a --tty options to git-lfs?  Also, I notice that you use tty tricks to rewrite lines, but perhaps a more vanilla progress would be useful, just printing out progress lines?

**Comment by bk2204** [comment]
I've looked into this a little more and I think I may have a solution. Our `isatty` library provides support for Cygwin-style TTYs, which may be what's in use here. I have a branch on my remote, `isatty-mingw`, which provides support for these. Would you be willing to test it out?

The steps to do so are essentially these:
1. Install Go 1.11 or 1.12.
1. `git clone https://github.com/git-lfs/git-lfs.git`
1. `cd git-lfs`
1. `git remote add bk2204 https://github.com/bk2204/git-lfs.git`
1. `git fetch bk2204`
1. `git checkout -b isatty-mingw bk2204/isatty-mingw`
1. `make`
1. Copy or link `bin/git-lfs.exe` into your PATH.
1. Test as you would normally.

**Comment by kristjanvalur** [comment]
Sure.  My first foray into go...

- installed go
- installed chocolatey && make
- installed goversioninfo as per instructions found in the net
- added ~/go/bin to my mingw path (for goversioninfo)
- built git-lfs.exe

Tested and it works. :)
p.s. you might want to update windows build instructions for newbies like me.  Cheers!

**Comment by bk2204** [comment]
Okay, glad this is working for you. I'll submit the patch.

I'll try to get some better docs for building on Windows as well.

**Comment by kristjanvalur** [comment]
Super, kudos for quick response to my issues :)
Btw, we've given up on using lfs for parts of the project (hundreds of files, total size 100s of GB) since the integration with git (clean filter) just for git status wasn't scaling :(.

**Comment by aggieNick02** [comment]
I stumbled onto this too. Some quick questions about it:

- Do you know what changed that made the progress indicator go away? With older versions of git/git-lfs, it still showed progress in the git bash window?
- Do you expect this fix to be in the next git lfs release, and if so, will that be soon? :) For now I'll just run my git lfs commands from powershell

**Comment by bk2204** [comment]
I don't usually use Windows, so I'm not sure what made the behavior change. It's possible that it's just an update that came in with Git for Windows that changed the behavior of the TTY that they're using.

I do expect this to be in Git LFS 2.8.0, which should be sometime in June.

**Comment by gingsi** [comment]
FYI there is still no progress shown when using git lfs with windows 10, version `git-lfs/2.12.1 (GitHub; windows amd64; go 1.14.10; git 85b28e06)` git version `2.29.2.windows.2`

Downloads are running as I can tell from the network activity, however the last output from the command line was `Resolving deltas: 100% (777/777), done.`, then git lfs started running silently.
