### ISSUE TITLE
git lfs locks

### ISSUE THREAD

**Issue by Nanorock** [git-lfs/git-lfs#3583]
Hello,

I have an issue getting locks on my computer.

`E:\Galacticare>git lfs locks

17:10:27.561445 git.c:576               trace: exec: 'git-lfs' 'locks'
17:10:27.561445 run-command.c:627       trace: run_command: 'git-lfs' 'locks'
17:10:27.588394 trace git-lfs: run_command: 'git' version
17:10:27.741253 trace git-lfs: run_command: 'git' config -l
17:10:27.758245 trace git-lfs: creds: git credential fill ("https", "github.com", "BrightrockGames/Galacticare")
Error while retrieving locks: Git credentials for https://github.com/BrightrockGames/Galacticare not found.`

But weirdly I have no issue pulling/pushing on the server, it seems to be just with locks.
I did set GIT_TRACE=1 and GIT_CURLY_VERBOSE=1
My colleague does not have this issue.

I'm using smartgit.
We have same git version : 2.16.2.windows.1 , git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)

I'm lost as to what I could do, any help ?

Thanks

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

Could you run the command again with all of `GIT_TRACE=1`, `GIT_TRANSFER_TRACE=1`, and `GIT_CURL_VERBOSE=1` (note that there's no “Y”) and provide the output? Also, as a thought, you could try setting the URL for origin to contain the `.git` portion, in case that helps things, by doing `git remote set-url origin https://github.com/BrightrockGames/Galacticare.git` and then retrying the operation.

**Comment by Nanorock** [comment]
Hello, 
I tried this without much more success:

![image](https://user-images.githubusercontent.com/7002068/55219959-0ccfd180-51fe-11e9-8e13-53a9aded9c5b.png)

As said I can pull normally with smartgit, however there it seems to use a credential.helper, could it be an issue ? I will check if my colleague have it setup in 2h,

**Comment by Nanorock** [comment]
He is using it too, but it's not a problem for him. 
I just setup smartgit to pull locks (https://www.syntevo.com/doc/display/SG/Git-LFS)
And somehow smartgit seems to succeed ?
![image](https://user-images.githubusercontent.com/7002068/55229507-203a6700-5215-11e9-9f4b-7d55bbc7b07f.png)

However if I run myself the git lfs locks through command line (with or without the credential helper) it fails.

The mystery grows !

**Comment by Nanorock** [comment]
I updated git version from 2.16.2 to 2.21.0 , I reset all know credential from SmartGit.
Now it worked by asking me for credentials (everytime ...)
So I used https://stackoverflow.com/questions/11403407/git-asks-for-username-every-time-i-push solution but it seems suboptimal (unencrypted) + now SmartGit doesn't like me having another external credential helper (said a warning about it being potentially problematic).

So I made it work, but I now have a different setup than my colleagues ^^'
