### ISSUE TITLE
Don´t send push with files fls 

### ISSUE THREAD

**Issue by Xavi2019** [git-lfs/git-lfs#3586]
Hello
I have GIT FLS installed, but when I want to push to upload the changes to the repo, it does not allow it. The steps I take are:

1.- git lfs install
2.- git lfs track '* .framework'
3.- git add .gitattributes
3.- git add Example.framework
4.- git commit -m "Update framework"
5.-git push origin master

and send the next error

<img width="562" alt="Captura de pantalla 2019-03-29 a la(s) 16 47 42" src="https://user-images.githubusercontent.com/49080913/55266866-bc2f9700-5244-11e9-8d46-91387a069348.png">

Help me!!!

**Comment by ttaylorr** [comment]
Hi @Xavi2019, thanks for opening this issue and I'm sorry that you're having trouble! It looks like what's going on here is that even though you tracked your large files, they are still _not_ tracked in Git LFS in the historical revisions in your repository.

You can fix this situation by running:

    $ git lfs migrate import --everything --include="*.framework"

and then running

    $ git push --all

and everything should be all set. Please don't hesitate to let us know if you have any other problems, and thanks again for opening this issue!

**Comment by Xavi2019** [comment]
thanks, but I continue with the problem

**Comment by Xavi2019** [comment]
thanks @ttaylorr , but I continue with the problem

**Comment by ttaylorr** [comment]
I'm sorry to hear that the problem has persisted. Can you please
provide:

  - The list of commands that you ran since posting the original issue,
    and

  - The error message that you're seeing?

Those two above should help us get a clearer picture of what is going on
with your repository.

**Comment by Xavi2019** [comment]
Thank you @ttaylorr 
It is already solved, at the time of performing the **git push --all**, I request a reberse since it generated all the previous commits as advanced, and after making the changes, perform a push send the error again.

What he did was solve the reberse and later **git push -f origin master**, although the files were not uploaded, he appeared as if he had never added files to the commit, so he did it again but with a normal **git push** and ready.
