### ISSUE TITLE
git-lfs ls-files fails when run from sub-directory

### ISSUE THREAD

**Issue by johanjeppsson** [git-lfs/git-lfs#3591]
When running git-lfs ls-files from a directory other than the project root directory, i get an error like this:

`Could not scan for Git LFS tree: missing object: 6f31eeb2fdec5041b266778d81e6ed85ae8d1544`

As far as I can tell, the environment looks OK (git-lfs env shows the same result) regardless if the current working directory is the project root or a sub directory.

**Comment by johanjeppsson** [comment]
After some more testing, I think that this might be some weird blob in my repo, and not something that is caused by git lfs.

**Comment by vecbib** [comment]
@johanjeppsson  I am having exact same issue. When I got to root directory (directory that containing .git folder) it lists all the tracked lfs files. But it gives same error `Could not scan for Git LFS tree: missing object: 993m3232l322xxxxx`. Were you able to figure out why it was causing the problem ?

**Comment by johanjeppsson** [comment]
Unfortunately no. I don't know the root cause. It seemed like this was related to some blob that was added when I was adding and removing things to test git-lfs out. After removing it, I haven't run into this issue again. Not very helpful, sorry.

**Comment by vecbib** [comment]
@johanjeppsson  Do you think we should re-open this issue or open a new issue regarding this (I can create a new issue regarding this)? I fine with both.

**Comment by bk2204** [comment]
In general, we prefer you open a new issue.
