### ISSUE TITLE
remote: fatal: Out of memory, malloc failed

### ISSUE THREAD

**Issue by gwerbin** [git-lfs/git-lfs#3595]
Version: `git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)`

Pushing to a GitHub Enterprise instance, I get this error:

```
$ git push
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.REDACTED.git/info/lfs.locksverify true
Uploading LFS objects: 100% (2/2), 633 MB | 288 KB/s, done
Enumerating objects: 83, done.
Counting objects: 100% (83/83), done.
Delta compression using up to 8 threads
Compressing objects: 100% (61/61), done.
remote: fatal: Out of memory, malloc failed (tried to allocate 518756187 bytes)
fatal: sha1 file '<stdout>' write error: Broken pipe
error: remote unpack failed: index-pack abnormal exit
```

Is this a problem with Git LFS, or should I raise an issue with our Github Enterprise support?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This message actually comes from Git itself and isn't related to Git LFS. Since it's coming from the remote side, you were correct when you guessed that raising an issue with GitHub Enterprise support is the best way forward here.

**Comment by AzizOzenir** [comment]
removing and reinstalling git fixed for me
