### ISSUE TITLE
LFS strips nevra data from rpms. 

### ISSUE THREAD

**Issue by KalebHawkins** [git-lfs/git-lfs#3607]
## Problem: 
Can't install RPM pulled down with git-lfs. 

## Testing 
Tested installing the rpm before uploading and pulling down with git-lfs.  
    Works
    After uploading the rpm and pulling the repo with git-lfs yum fails to open the file. Logs indicate that it failed to get nevra information from the RPM.

I guess this data is stripped from the rpm when sent to lfs? I have tested with multiple rpms. Is there a workaround to this? Is anyone else having the same issue?

Thanks in advance.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Git LFS doesn't strip any data from files; it stores them as-is and knows nothing about their type. It's possible that the files you're trying to install weren't checked out for some reason and the pointer files are still in their place.

Can you look at one of the RPMs you're having a problem with using `less` and see if it looks something like the following?

```
version https://git-lfs.github.com/spec/v1
oid sha256:4355a46b19d348dc2f57c046f8ef63d4538ebb936000f3c9ee954a27460dd865
size 2
```

If you see something like this (even though the `oid` and `size` entries may differ), you can fix it by running `git lfs install` and then `git lfs checkout`.

**Comment by KalebHawkins** [comment]
That was it. Thanks so much for the quick response. I wasn't aware I had to do a separate pull. I guess I need to rtfm.  I ended up pulling all the files with a git lfs pull.

**Comment by bk2204** [comment]
> That was it. Thanks so much for the quick response. I wasn't aware I had to do a separate pull. I guess I need to rtfm. I ended up pulling all the files with a git lfs pull.

If you've run `git lfs install`, it should automatically have stored configuration to make Git LFS work into your user-level Git configuration file (usually `~/.gitconfig`), so you shouldn't need to do a separate step: it should just work. If for some reason that configuration isn't there, then it won't automatically check out, and you'll have to run `git lfs install` by hand and then check out the files.
