### ISSUE TITLE
unable to open file(in target "webdriveragentlib" in project  "webdriveragent")(in target "webdriveragentlib")

### ISSUE THREAD

**Issue by sumitgos** [git-lfs/git-lfs#3611]
We are upgrade xcode 9.3 to xcode 10. after update we face this issue. before it's working fine . 
please provide some solution for this .
Xcode 10.
Project : webdriveragent
Step  during build project, we face unable to open file.
issue:- unable to open file(in target "webdriveragentlib" in project  "webdriveragent")(in target "webdriveragentlib")

how can i solve this issue ?

**Comment by bk2204** [comment]
Hey,

I don't think the issue you're seeing is related to Git LFS. I'm not sure what's going on here, but you could try asking on the Apple forums to see if other people are seeing similar issues. Sorry I can't be of more help.
