### ISSUE TITLE
Public key expired

### ISSUE THREAD

**Issue by mcafaro** [git-lfs/git-lfs#3618]
```
$ sudo apt -qq update
237 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Resolved by:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157`

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I think we were originally tracking this in #3474, and to summarize what happened, PackageCloud rotated their keys without telling us. Without some sort of archive keyring from PackageCloud (à la `debian-archive-keyring`), there isn't a way for us to automatically rotate keys, unfortunately.

I think you've already got the solution here, and we are aware of the problem, so I'm going to close this. Thanks for reaching out and making sure we were aware of this.

**Comment by mkumar118** [comment]
I am on Debian Stretch and the above command did not work for me (naturally, as the keyring is different).

After some looking around, the following worked for me:
`curl -L https://packagecloud.io/github/git-lfs/gpgkey | sudo apt-key add -`
