### ISSUE TITLE
Typo in v2.7.2 release notes.

### ISSUE THREAD

**Issue by amcgregor** [git-lfs/git-lfs#3626]
Was checking for updates today, went to review the changelog and noticed a silly and minor detail: "generation" is misspelled: (and silly hard to get autocorrect to not correct here ;)

> * (at)ssgelm for improving the Debian package manpage __geeneration__

**Comment by bk2204** [comment]
Thanks for pointing this out. I've adjusted the release to reflect the correct spelling. I'll update the changelog file when I pull it into `master`.
