### ISSUE TITLE
Lock failed: The specified target is unknown or unreachable

### ISSUE THREAD

**Issue by gilbdev** [git-lfs/git-lfs#3629]
**Repro Steps**
`git lfs lock myfile.fbx` produce the following error message: 
**Lock failed: The specified target is unknown or unreachable**

**More Infos**
myfile.fbx is correctly listed when using `git lfs ls-files`

in `.gitattributes` i have the line :
`*.fbx filter=lfs diff=lfs merge=lfs -text lockable`

**Installation**
remote server is Microsoft Visual Studio Team Foundation Server Version 16.131.28507.4, accessed via a VPN

installed git and git lfs on windows 10 via Git for windows 2.21 x64 (and git lfs 2.7.1)

What am i missing ?
any help appreciated

**Comment by gilbdev** [comment]
Here is the output with GIT_TRACE=1 (i replaced real server address..), so probably an authentication problem. but how can i solve it ?

```
12:11:48.626677 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
12:11:48.628642 git.c:676               trace: exec: git-lfs locks
12:11:48.628642 run-command.c:643       trace: run_command: git-lfs locks
12:11:48.652658 trace git-lfs: exec: git 'version'
12:11:48.737748 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
12:11:48.794120 trace git-lfs: exec: git 'config' '-l'
12:11:48.819101 trace git-lfs: HTTP: GET https://tfs.myserver.com/TFS_Projects/MyProject/_git/MyRepo.git/info/lfs/locks
12:11:49.006790 trace git-lfs: HTTP: 401
12:11:49.007631 trace git-lfs: setting repository access to ntlm
12:11:49.010672 trace git-lfs: exec: git 'config' '--replace-all' 'lfs.https://tfs.myserver.com/TFS_Projects/MyProject/_git/MyRepo.git/info/lfs.access' 'ntlm'
12:11:49.064355 trace git-lfs: api: http response indicates "ntlm" authentication. Resubmitting...
12:11:49.064355 trace git-lfs: creds: git credential fill ("https", "tfs.myserver.com", "")
12:11:49.080270 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
12:11:49.082209 git.c:419               trace: built-in: git credential fill
12:11:49.083209 run-command.c:643       trace: run_command: 'git credential-manager get'
12:11:49.112281 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
12:11:49.114282 git.c:676               trace: exec: git-credential-manager get
12:11:49.114282 run-command.c:643       trace: run_command: git-credential-manager get
12:11:49.615538 trace git-lfs: HTTP: GET https://tfs.myserver.com/TFS_Projects/MyProject/_git/MyRepo.git/info/lfs/locks
12:11:49.770597 trace git-lfs: HTTP: 401
12:11:49.771609 trace git-lfs: HTTP: GET https://tfs.myserver.com/TFS_Projects/MyProject/_git/MyRepo.git/info/lfs/locks
12:11:49.931923 trace git-lfs: HTTP: 401
12:11:49.931923 trace git-lfs: HTTP: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Authorized</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Authorized</h2>
<hr><p>HTTP Error 401. The requested resource requires user authentication.</p>
</BODY></HTML>
```

**Comment by bk2204** [comment]
Hey, thanks for writing in.

It may be useful for you to run with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` to see what type of authentication the remote server is suggesting. The error message that “[t]he specified target is unknown or unreachable” comes from Windows's Kerberos stack. Git LFS doesn't support Kerberos, only NTLM, so you'd want to see if the server allows NTLM authentication.

If you see “Negotiate” as the given authentication type, you'll need to Base64-decode the response after it; you're looking for the first seven bytes to be “NTLMSSP” to verify that it's NTLM, not Kerberos, that the system is looking for.

**Comment by gilbdev** [comment]
Here is some more trace infos :
```
< Www-Authenticate: Bearer
< Www-Authenticate: Basic realm="https://tfs.myserver.com/"
< Www-Authenticate: Negotiate
< Www-Authenticate: NTLM
```
```
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: NTLM TlRMTVNTUAABAAAA........VUA==
```
i have absolutely no idea what that TlRMTVN means :D
does it means it's "Kerberos"? 

can i change something on the client side ? or on the server side ?

strange things is that it's only for the locks that i can't access, all other git and lts seems to works fine :p

**Comment by bk2204** [comment]
Okay, that's good information. The `Bearer` value is OAuth, the `Basic` value is standard username-and-password, `Negotiate` is Kerberos, and `NTLM` is, of course, NTLM. It looks like you're using NTLM, but for whatever reason it's not working.

Right now, our NTLM implementation doesn't use the standard Windows credentials; it only uses the ones you provide on the command line. We're tracking this as #3615.

There are a couple things you might try here. First, you can try using a personal access token and Basic authentication by modifying `.git/config` and changing the `lfs.<url>.access` value to `basic` instead of `ntlm`. If you already have a PAT saved in your credential manager, that will likely help you pick the right type of authentication; you may already be doing this, but if the operation failed, it may have gotten reset. You may need to make sure that the token has all the scopes you require for it to work; I'm not sure how TFS works on scopes.

If that doesn't work, you may want to remove any given credentials from your credential manager and retry to have it prompt you again, possibly resetting the `lfs.<url>.access` value back to `basic`. If you're using the Windows credential manager, it will probably be able to prompt you to create an appropriate token for what you're doing. You could also use your NTLM credentials (probably your Windows domain user and password) and see if it works with NTLM.

**Comment by gilbdev** [comment]
Thanks a lot for the help !

* so replacing ntlm with basic in the config ...
well it's useless, as you can see in the first log
`12:11:49.010672 trace git-lfs: exec: git 'config' '--replace-all' 'lfs.https://tfs.myserver.com/TFS_Projects/MyProject/_git/MyRepo.git/info/lfs.access' 'ntlm'`
as soon as I change it and execute a `git lfs locks` command, the basic is replaced with ntlm in the config file

* i then tried to remove credential from windows credential manager and retry, no more success

* so i tried : `git -c credential.helper= lfs lock myfile.fbx ` to avoid using manager and ...tadam! it worked

=> so problem comes from the git credential manager that does not seems to work correctly with git lfs lock
still, i'm not happy with this solution, as i have to enter my credential each time and do it all from command line ( i was hoping to use a 3rd-party tool, integrated Unity, to be able to lock files from a contextual menu ..)

so my quest will continue on windows git credential manager github i guess :)

**Comment by gilbdev** [comment]
Ok, so final word and solution , + explanation:
- i was using GitHub for Desktop, which has a different way of saving credentials in the Manager, so despite i was able to fetch, pull,etc. from GitHub desktop, it was not working in command line with a simple git fetch :p (and yeah i didn't think about testing that in the first place :/)

- plus, second problem, to have the git credential manager prompting for username and password, it needs to have credential.authority set to basic

so to fix all that :
in command line : `git config --global credential.[<server url>.]authority Basic`
then try any git command to have the credential popup : `git fetch` and fill username and password
then try `git lfs locks`
and check in GitHub for Unity if contextual menu works :)

thanks again for your time
