### ISSUE TITLE
HTTP: 401 Response Sent without Authenticate

### ISSUE THREAD

**Issue by markkohlmann** [git-lfs/git-lfs#3642]
Using Apache as a reverse proxy front end for Jason White's rudolfs LFS server as Apache already implements the necessary authentication for my application.  If I request the URL with a web browser everything downloads fine.  If I turn off authentication then everything works fine.

GIT LFS is sending the Authentication header correctly on the first request but subsequent requests need to be authenticated and GIT LFS is not attempting to re-authenticate after receiving a 401 on the subsequent request.  The credentials are valid so the 401 should result in a response with the credentials.  Using Windows Credential Manager on this machine.  The 401 errors will result in an infinite loop as others have pointed out previously.  Any idea what might cause this or how to resolve?

Full trace:
$ GIT_CURL_VERBOSE=1 GIT_TRACE=1 git lfs pull
23:53:22.328974 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
23:53:22.328974 git.c:676               trace: exec: git-lfs pull
23:53:22.328974 run-command.c:643       trace: run_command: git-lfs pull
23:53:22.377060 trace git-lfs: exec: git 'version'
23:53:22.461144 trace git-lfs: exec: git 'config' '-l'
23:53:22.481090 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
23:53:22.502034 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
23:53:22.521982 trace git-lfs: tq: running as batched queue, batch size of 100
23:53:22.534928 trace git-lfs: filepathfilter: accepting ".gitattributes"
23:53:22.534928 trace git-lfs: filepathfilter: accepting "***"
23:53:22.534928 trace git-lfs: filepathfilter: accepting "***"
23:53:22.534928 trace git-lfs: filepathfilter: accepting "***"
23:53:22.546907 trace git-lfs: fetch *** [8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75]
23:53:22.547880 trace git-lfs: fetch *** [1ca21f2015a215f4f613f880c57ce42e3c70d82033de235f76617a9f4c94be1a]
23:53:22.547880 trace git-lfs: tq: sending batch of size 2
23:53:22.547880 trace git-lfs: api: batch 2 files
23:53:22.547880 trace git-lfs: creds: git credential fill ("https", "***", "")
23:53:22.558851 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
23:53:22.560877 git.c:419               trace: built-in: git credential fill
23:53:22.560877 run-command.c:643       trace: run_command: 'git credential-manager get'
23:53:22.582642 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
23:53:22.582642 git.c:676               trace: exec: git-credential-manager get
23:53:22.582642 run-command.c:643       trace: run_command: git-credential-manager get
23:53:22.793661 trace git-lfs: Filled credentials for https://***/git/git-lfs-test-repo.git
23:53:22.799370 trace git-lfs: HTTP: POST https://***/git/git-lfs-test-repo.git/info/lfs/objects/batch
> POST /git/git-lfs-test-repo.git/info/lfs/objects/batch HTTP/1.1
> Host: ***
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 253
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
>
{"operation":"download","objects":[{"oid":"8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75","size":90251586},{"oid":"1ca21f2015a215f4f613f880c57ce42e3c70d82033de235f76617a9f4c94be1a","size":29264689}],"ref":{"name":"refs/heads/master"}}23:53:23.045652 trace git-lfs: HTTP: 200

< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: application/json
< Date: Mon, 13 May 2019 06:53:23 GMT
< Server: Apache/2.4.29 (Ubuntu)
<
23:53:23.060787 trace git-lfs: creds: git credential approve ("https", "***", "")
23:53:23.073753 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
23:53:23.074748 git.c:419               trace: built-in: git credential approve
23:53:23.075746 run-command.c:643       trace: run_command: 'git credential-manager store'
23:53:23.098505 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
23:53:23.098505 git.c:676               trace: exec: git-credential-manager store
23:53:23.098505 run-command.c:643       trace: run_command: git-credential-manager store
23:53:23.299111 run-command.c:643       trace: run_command: 'git credential-manager store'
23:53:23.330360 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
23:53:23.330360 git.c:676               trace: exec: git-credential-manager store
23:53:23.330360 run-command.c:643       trace: run_command: git-credential-manager store
23:53:23.602494 trace git-lfs: HTTP: {
  "transfer": "basic",
  "objects": [
    {
      "oid": "8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75",
      "size": 90251586,
      "authenticated": true,
      "actions": {
        "download": {
          "href": "https://***/git/git-lfs-test-repo.git/info/lfs/object/8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75",
          "header": null
        }
      }
    },
    {
      "oid": "1ca21f2015a215f4f613f880c57ce42e3c70d82033de235f76617a9f4c94
{
  "transfer": "basic",
  "objects": [
    {
      "oid": "8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75",
      "size": 90251586,
      "authenticated": true,
      "actions": {
        "download": {
          "href": "https://***/git/git-lfs-test-repo.git/info/lfs/object/8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75",
          "header": null
        }
      }
    },
    {
      "oid": "1ca21f2015a215f4f613f880c57ce42e3c70d82033de235f76617a9f4c9423:53:23.602494 trace git-lfs: HTTP: be1a",
      "size": 29264689,
      "authenticated": true,
      "actions": {
        "download": {
          "href": "https://***/git/git-lfs-test-repo.git/info/lfs/object/1ca21f2015a215f4f613f880c57ce42e3c70d82033de235f76617a9f4c94be1a",
          "header": null
        }
      }
    }
  ]
}
be1a",
      "size": 29264689,
      "authenticated": true,
      "actions": {
        "download": {
          "href": "https://***/git/git-lfs-test-repo.git/info/lfs/object/1ca21f2015a215f4f613f880c57ce42e3c70d82033de235f76617a9f4c94be1a",
          "header": null
        }
      }
    }
  ]
23:53:23.602494 trace git-lfs: xfer: Attempting to resume download of "8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75" from byte 0
23:53:23.602494 trace git-lfs: HTTP: GET https://***/git/git-lfs-test-repo.git/info/lfs/object/8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75
> GET /git/git-lfs-test-repo.git/info/lfs/object/8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75 HTTP/1.1
> Host: ***
> User-Agent: git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
>
23:53:23.635107 trace git-lfs: HTTP: 401

< HTTP/1.1 401 Unauthorized
< Content-Length: 472
< Content-Type: text/html; charset=iso-8859-1
< Date: Mon, 13 May 2019 06:53:23 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Www-Authenticate: Basic realm="***"
<
23:53:23.639501 trace git-lfs: HTTP: GET https://***/git/git-lfs-test-repo.git/info/lfs/object/8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75
> GET /git/git-lfs-test-repo.git/info/lfs/object/8896645f8b2a9690cbcc555ba865f3968ebdca97c0d25a560b054663f907ae75 HTTP/1.1
> Host: ***
> User-Agent: git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
>
23:53:23.799761 trace git-lfs: HTTP: 401

< HTTP/1.1 401 Unauthorized
< Content-Length: 472
< Content-Type: text/html; charset=iso-8859-1
< Date: Mon, 13 May 2019 06:53:23 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Www-Authenticate: Basic realm="***"
<

****Infinite 401 loop****

**Comment by bk2204** [comment]
Hey, thanks for writing in and sorry to hear you're having trouble.

I think what's going on here is that your LFS server is setting `"authenticated": true`, which means that the URL itself is intrinsically authenticated (e.g., an Amazon S3 URL with the credentials as part of the query string in the URL). However, in this case, that's not true: you require Basic auth in order to access the URL. You would need to remove that setting so that the Git LFS client will know that it needs to authenticate using some HTTP authentication method when it gets a 401.

**Comment by markkohlmann** [comment]
Thank you bk2204, didn't even see that as I was looking purely at the HTTP headers.  Fairly new to LFS.  I added a rule to Apache to re-write the authenticated json value and all is well!  I'll ask Jason White if there's a parameter to modify the behavior of his server.
