### ISSUE TITLE
my account is disabled

### ISSUE THREAD

**Issue by HHHHHHHHHHHHHHHHHHHHHCS** [git-lfs/git-lfs#3643]
how to able it

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
i delete my repo, but  it is unuse . it tips lfs is disabled again.

**Comment by bk2204** [comment]
Hey,

I'm not sure about what system you're asking. If you're asking why your GitHub account is disabled for LFS, that question would be better asked to GitHub's support team at support@github.com. This project is only for the open source client; we don't have control over why your account may be disabled. If you're using a different service, please contact their support for help instead.
