### ISSUE TITLE
Locks listing doesn't provide ref name

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3646]
It is possible to [list locks](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md#list-locks) without specifying ref name. However, how does user understand what lock belongs to what ref from server output?

**Comment by bk2204** [comment]
As I mentioned in #3645, locks are currently global, and so we won't provide a ref response because it isn't yet meaningful. When we add support for per-ref locks, we'll add a response that indicates what ref, if any, a lock belongs to.
