### ISSUE TITLE
Inconsistent paths in locking API

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3647]
[Create lock request](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md#create-lock) uses path without leading slash. But [create lock response](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md#successful-response) suddenly has a leading slash. Please, make it explicit in documentation whether path must start with a slash or not, and fix inconsistencies.

**Comment by bk2204** [comment]
Hey,

Thanks for pointing this out. The path should be relative to the repository root. I'll get the documentation updated.
