### ISSUE TITLE
git-lfs requires write access to list locks

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3653]
[List locks](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md#list-locks) spec says:

> LFS Servers should ensure that users have at least pull access to the repository.

But in fact:

```
$ GIT_TRACE=1 git lfs locks
15:00:24.147599 git.c:670               trace: exec: git-lfs locks
15:00:24.147621 run-command.c:643       trace: run_command: git-lfs locks
15:00:24.150194 trace git-lfs: exec: git 'version'
15:00:24.151202 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
15:00:24.152904 trace git-lfs: exec: git 'config' '-l'
15:00:24.153889 trace git-lfs: run_command: ssh -- git@github.com git-lfs-authenticate slonopotamus/git-lfs-java.git upload
15:00:24.608683 trace git-lfs: HTTP: GET https://lfs.github.com/slonopotamus/git-lfs-java/locks
15:00:25.270450 trace git-lfs: HTTP: 200
```

Notice that `git-lfs-authenticate` is invoked with `upload` mode. Either spec is wrong and write access is **required** to list locks or git-lfs should fallback to `download` mode instead. In current shape, if user doesn't have write access, he doesn't pass `git-lfs-authenticate` step.

Way to reproduce:

1. Clone any GitHub repo where you only have read access
2. Invoke `GIT_TRACE=1 git lfs locks`
3. Observe that you do not get any locks because `git-lfs-authenticate` fails

**Comment by bk2204** [comment]
Hey,

I think that it's probably fine to downgrade this to `download`, since presumably the HTTP version works with those permissions. I'll try to get this fixed for 2.8.0 and see if we can verify with other implementers that this is okay with them.

**Comment by slonopotamus** [comment]
So, what is your plan? Request `upload` token, if that fails request `download` token and go to list api with whatever token you managed to get? It isn't clear from spec how client needs to behave.

**Comment by bk2204** [comment]
No, I plan to request just a `download` token in this case, since pull permission is all that's required.

@git-lfs/implementers, do you see a problem with this on your end?

**Comment by bk2204** [comment]
@slonopotamus Would you like to be added to that group?

**Comment by slonopotamus** [comment]
1. No, I accept whatever route is taken as long as it is clear from spec what to do so it is possible to write compatible client/server implementations
2. Yes, please. I'm currently maintaining [git-lfs-java](https://github.com/bozaro/git-lfs-java) - Java implementation of Git LFS protocol and also maintaining [git-as-svn](https://github.com/bozaro/git-as-svn) that has LFS server implementation.

**Comment by ashmckenzie** [comment]
>  I plan to request just a download token in this case, since pull permission is all that's required.

Sounds sensible :+1:
