### ISSUE TITLE
Failed to fetch some objects 'git-lfs' pull

### ISSUE THREAD

**Issue by dh-ger** [git-lfs/git-lfs#3658]
I have recently started tracking some large files using git-lfs.
This was an existing repository so I had to use the migrate functionality to re-write local history.
https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn#migrate-local-history

Everything appeared fine after this migration, I was able to execute `git-lfs pull` and all large files were retrieved successfully, The migration and testing was done on alpine linux.

However when moving back to my development machine (Windows 10) I get the following error when executing `git-lfs pull`.
```
[455abb0f261c80c84aa8d782604f11ecf978fbef1b3a5e34ab469759be6b4305] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.mygithub/reponame.git/info/lfs'
```

However the odd behavior here is that if I continue trying to run the command it eventually works. This appears to be an issue in windows only.

Any help with this issue would be greatly appreciated.

**Comment by dh-ger** [comment]
Scratch that, it looks like the same issue is happening in Alpine when I clone to a different directory.

I'm thinking there may have  been an issue with the migration.

**Comment by bk2204** [comment]
Hey, sorry to hear that you're having trouble.

This error message does usually mean that the file wasn't uploaded. You can try to do a `git lfs push --all` on the original rewritten repository, which should help you ensure all the objects are available on the server.

If this is indeed nondeterministic, then that's likely a server-side issue with the storage, and you'd want to address that with GitHub support or the folks hosting your private GitHub instance (if you have one of those instead). GitHub and most recent GitHub Enterprise instances will prevent you from pushing Git data if the LFS data is missing, though.

**Comment by dh-ger** [comment]
Hi,

I'm closing this issue as it was due to my own stupidity.

Turns out the repository was renamed and this was the reason for the 404s.

Have it sorted now. Apologies for wasting any of your time.

Thanks

**Comment by bk2204** [comment]
Great, I'm glad you got it sorted out.

**Comment by fanyu2021** [comment]
I have met this issue, while I can do nothing.
