### ISSUE TITLE
Improve push optimization to work with URL remotes

### ISSUE THREAD

**Issue by bk2204** [git-lfs/git-lfs#3661]
Currently, when we push to a remote specified by a URL, we traverse the entire history in order to discover which LFS objects need to be pushed. However, with a named remote, we use the heads of the remote to exclude objects we know the remote already has.

Since the pre-push hook knows which Git objects are being pushed, we should optimize it by traversing only those Git objects we're pushing, since we can assume that the remote side will also have any LFS objects that are referenced by the Git objects it already has.

This will improve performance in a variety of cases, notably with some JGit and EGit usages where the remote for pre-push hooks will never provide a named remote.

**Comment by Aa88s** [comment]
#3755 Optimize traversal of Git objects with URL remotes
