### ISSUE TITLE
git-lfs doesn't send 'Accept: application/vnd.git-lfs+json' HTTP header for /verify URL

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3662]
LFS spec [says](https://github.com/git-lfs/git-lfs/blob/master/docs/api/basic-transfers.md#verification) that LFS client needs to send both `Accept: application/vnd.git-lfs+json` and `Content-Type: application/vnd.git-lfs+json`. But [verifyUpload](https://github.com/git-lfs/git-lfs/blob/84f47a430beb9695ceb8427443f304e091128edd/tq/verify.go#L16) function only sends `Content-Type`, without sending `Accept` header.

Also see git-lfs/lfs-test-server#85 to fully feel how messed up situation with `/verify` is.

**Comment by slonopotamus** [comment]
Also see git-lfs/lfs-test-server#85.

**Comment by bk2204** [comment]
Yeah, I think you're right here. I'm going to fix this issue and adjust the testsuite to catch any additional failures of this kind in the API.
