### ISSUE TITLE
error: waitpid for .git/hooks/commit-msg failed: No child processes

### ISSUE THREAD

**Issue by Jyonanda** [git-lfs/git-lfs#3670]
Hi folks,I am facing issue  while pushing code from my local to Gerrit using tortoise git with below error.

error: waitpid for .git/hooks/commit-msg failed: No child processes
git did not exit cleanly (exit code 1) (9547 ms @ 5/28/2019 9:18:41 PM)

It was working before 2 days but suddenly facing this issue.

Please suggest some solution for the same.

Thanks.

**Comment by bk2204** [comment]
Hey,

This sounds like an issue with Git core and the `commit-msg` hook that you have installed and not an issue with Git LFS. Assuming you can reproduce this from the command line, you'll probably want to either ask at [the Git for Windows project](https://github.com/git-for-windows/git) or on [the Git mailing list](https://git-scm.com/community).

**Comment by Jyonanda** [comment]
Thanks for your reply.
