### ISSUE TITLE
*.framework pattern not tracking files within

### ISSUE THREAD

**Issue by apontious-pandora** [git-lfs/git-lfs#3678]
I have a small test repository where I am specifying the `*.framework` pattern to match files in the repository for Git-Lfs. (I am also trying the patterns `*.framework/*` and `*.framework/**`) But it is not working as expected. 

I am doing this on a computer running macOS 10.14.5, git 2.20.1 (Apple Git-117), and git-lfs 2.6.1 (GitHub; darwin amd64; go 1.11.2).

During the `git add` step, it looks like Git-lfs is going to track all the files within any directory whose name matches the `*.framework` pattern, but during the actual `git commit` step, it doesn't seem to be tracking them at all.

In my tests, I'm using a Bitbucket server that enforces a 10 MB maximum size for files. As you can see by the below log, the server is still encountering that the > 10 MB files are regular files, not Git-Lfs files. 

If I specify the binaries within the `*.framework` directories via Git-Lfs by specifying their exact names, they are then tracked properly -- I don't show this below, but can easily replicate it and send you another log if you'd like.

[Log.txt](https://github.com/git-lfs/git-lfs/files/3274045/Log.txt)

Before the log starts, I first set up the git tracking patterns, by committing the .gitattributes file for all three repositories -- "test" with the pattern `*.framework`, "test2" with the pattern `*.framework/*` and "test3" with the pattern `*.framework/**`. These files are `tail`'ed at the beginning of the log.

Then, I am taking the `BMWAppKit.framework` folder, which I have already added to the local test repository filesystems but not to git , and `git add`'ing it so that it is staged.

For all 3 repositories, I am then doing `git status` and `git lfs status` to show that things are in the correct state. All the files under the `*.framework` directory do appear to be ready to be tracked.

Then I am committing those staged changed for all 3 repositories.

Then I am attempting to push those commits for all 3 repositories.

It fails in each case, because the > 10 MB file in the *.framework directory, BMWAppKit, was not actually tracked by Git-Lfs.

This seems to be clear evidence that something is going wrong at the Git-Lfs level between the original `track` command and the commit. Am I doing something wrong here? Is this a known issue? Everywhere I look and everyone I talk to, the *.framework pattern is the standard and should be handling this case.

I am also seeing this with larger, real-world repositories, which is how this was originally detected.

Thanks!

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I think the issue is that your gitattributes pattern doesn't match the framework path. I tried a path based off yours (`frameworks/BMWAppKit.framework/a`) and running `git check-attr -a` on that path lists no output. That means that Git won't invoke Git LFS for those paths, and your files will be tracked in Git instead of Git LFS.

You could try a pattern like `frameworks/*.framework/**` or `**/*.framework/**`, both of which should match your files. To verify that this works as expected, you can use `git check-attr -a FILE` to verify that the files have the appropriate attributes set.

Hopefully that's helpful in getting you up and running.

**Comment by ajkerfaisal** [comment]
@bk2204 I owe you my life.
