### ISSUE TITLE
E: Unable to locate package git-lfs

### ISSUE THREAD

**Issue by YDSh510** [git-lfs/git-lfs#3684]
Hi 

I have recently set up git server for my project(team of 4 members) now I am trying to install git-lfs as its an unreal project.

which installing git-lfs (on server machine) I am getting following error "E: Unable to locate package git-lfs".

Can you please help where I am going wrong.

--------------------
yuvdede@WipodSrv1:/home/git$ sudo -E add-apt-repository ppa:git-core/ppa

 The most current stable version of Git for Ubuntu.

For release candidates, go to https://launchpad.net/~git-core/+archive/candidate .
 More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'.
The team named '~git-core' has no PPA named 'ubuntu/ppa'
Please choose from the following available PPAs:
 * 'build-deps':  Backported build dependencies for git
 * 'candidate':  Git release candidates
 * 'ppa':  Git stable releases
 * 'v1.8':  Git 1.8.x old releases

yuvdede@WipodSrv1:/home/git$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
yuvdede@WipodSrv1:/home/git$ sudo apt-get install git-lfs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package git-lfs
yuvdede@WipodSrv1:/home/git$

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

Can you tell me what OS and what version you're using? I'm guessing it's Ubuntu, but knowing the version would be helpful. Also, usually there's some output when you pipe the packagecloud script to bash. If there was, could you provide it? And finally, if there's a file named `/etc/apt/sources.list.d/github_git-lfs.list`, could you provide its contents?

**Comment by YDSh510** [comment]
Hi @bk2204 

I am on Ubuntu 16.04 and there is not file github_git-lfs.list.

I again tried everything with new git user but now its not allowing me to add PPA.

git@WipodSrv1:/home/git$ sudo add-apt-repository ppa:git-core/ppa
Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'.
ERROR: '~git-core' user or team does not exist.

Though I have set the proxy properly

**Comment by bk2204** [comment]
The Git core PPA is separate from Git LFS and if you're having problems with that, it's probably best to contact the maintainers of that project. I can help with Git LFS issues, though.

Can you try downloading and running the script with `curl -O https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh && bash script.deb.sh`? If that fails, can you check that the `http_proxy` environment variable is set correctly (by running `echo $http_proxy`)?

**Comment by ShibalIbrahim** [comment]
Hi, 

I am trying to install git-lfs on a machine i don't have sudo access to. The machine type is x86-64.
I tried running the above command "curl -O https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh && bash script.deb.sh" and get an error that says "Installing /etc/apt/sources.list.d/github_git-lfs.list...script.deb.sh: line 137: /etc/apt/sources.list.d/github_git-lfs.list: No such file or directory". Here is the terminal output:

"curl -O https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh && bash script.deb.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5911    0  5911    0     0   5911      0 --:--:-- --:--:-- --:--:-- 10461
Detected operating system as centos/Core.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...script.deb.sh: line 137: /etc/apt/sources.list.d/github_git-lfs.list: No such file or directory

Unable to run: 
    curl https://packagecloud.io/install/repositories/github/git-lfs/config_file.list?os=centos&dist=Core&source=script

Double check your curl installation and try again."

Can you tell me how to resolve this?

**Comment by bk2204** [comment]
Hey,

If you don't have sudo access, you won't be able to use the prebuilt Debian packages, since those require root access to install. If you're instead trying to install RPMs (which is what you'd want to do on CentOS), you'll probably want to try the RPM script, which may or may not work without privileges.

However, if it doesn't, you're welcome to use the prebuilt binaries that are available from our release page, which should work on most Linux systems, or you can build the package with Go 1.11 or newer yourself.

**Comment by YDSh510** [comment]
Hi @bk2204,

Finally i am able to install git-lfs. thanks for the suggestion.

I have  two doubts.

1. We have server client setup where the server and client are running on two different machines.
 Now since I am working on unreal project which has some asset files so using git-lfs to storing large files. On local host i am able to install git-lfs but on server it gives below error, even after using sudo 

sdv_git@WipodSrv1:~/srv/simulator.git$ git lfs install
open /home/sdv_git/srv/simulator.git/hooks/pre-push: permission denied
To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.

2. In my local machine I can see the project folder but in server machine the folder structure is entirely different and I don't directly see my project then how will I do git lfs track ?
git lfs track "*.psd"

**Comment by bk2204** [comment]
Hey,

It sounds like your server is using a bare repository, in which case it isn't necessary to install Git LFS there, so you needn't run `git lfs install` at all. However, when using a bare repository, you can't really commit, so `git lfs track` isn't something you can run on the server; you'd have to run on a client, and then commit if necessary and push.

**Comment by kafran** [comment]
On Ubuntu Disco I'm getting
```shell
Err:15 https://packagecloud.io/github/git-lfs/ubuntu disco Release                                           
  404  Not Found [IP: 2600:1f1c:2e5:6901:73d3:adc5:3c8:d639 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu disco Release' does not have a Release file.
```

**Comment by YDSh510** [comment]
@bk204 - Thanks for the information. Ok understood so because my server is using a bare repository there it will not have the regular project folder .

I have team of 4 people working on unreal project so all 4 need to install git and git-lfs and start tracking the large asset files on thier local system but on the server its not needed. 

Hope my understanding is correct.

Thanks once again for clearing my doubt.

**Comment by bk2204** [comment]
> @bk204 - Thanks for the information. Ok understood so because my server is using a bare repository there it will not have the regular project folder .
> 
> I have team of 4 people working on unreal project so all 4 need to install git and git-lfs and start tracking the large asset files on thier local system but on the server its not needed.
> 
> Hope my understanding is correct.

Your understanding is correct. Your server will still need some implementation of Git LFS if you want folks to push to it, but most Git hosting tools (GitHub, GitLab, and Bitbucket) all support that natively.

**Comment by bk2204** [comment]
As for the `disco` release, we haven't done a release since it's been out, and we therefore haven't built any packages for it yet. The plan is to do a release this week.

**Comment by Chihaya-Yuka** [comment]
Great
