### ISSUE TITLE
Github still tracks file with git-lfs pointer when git lfs uninstalled

### ISSUE THREAD

**Issue by richardwu** [git-lfs/git-lfs#3688]
I understand this may not necessarily be git-lfs itself and could be on Github's end, but when I removed git-lfs tracking in one of repos (I've tried `git lfs uninstall`, `git lfs prune`, using BFG to remove any references to git-lfs in previous commits, removing `.git/` and re-initializing git, etc.) pushing to a Github repository still ends up replacing the file with the text pointer to the git-lfs file.

I've tried deleting the Github repository and creating a new one with a different name to no avail.

The only way I managed to prevent Github from thinking my files are still LFS files is to remove the `git-lfs` binary from my local machine entirely before pushing up the repo.

I am unsure if this is the intended effect, but it seems counterintuitive that the same file (based on its sha256 I'm guessing) will be pushed up as an LFS file. Could there be some caching issues with `git-lfs` locally that could cause it to think the file is still an LFS file?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Did you remove all the entries from the `.gitattributes` file in your repository that contain `filter=lfs`? That's the thing that tells Git that you want to use Git LFS for that file.

**Comment by richardwu** [comment]
Yes I did. I've also tried removing .git and reinitializing git to no avail.

**Comment by bk2204** [comment]
Hmm, okay.

In your repository, what do the following commands produce?

```console
$ git ls-files | git check-attr --stdin filter | grep lfs
$ git lfs ls-files
```

That should tell us what Git and Git LFS think about what files are using LFS.

**Comment by kwunlyou** [comment]
I have the same issue
- `git ls-files | git check-attr --stdin filter | grep lfs` has empty output 
- `git lfs ls-files` outputs the list of file names that were tracked by git-lfs

**Comment by bk2204** [comment]
Could you provide the output of `git config -l`? Also, is it possible you could post a repository containing this problem somewhere? I'm not sure why this is happening and I'd like to look more at an affected repository.

**Comment by kwunlyou** [comment]
@bk2204 re-cloning the project can solve the problem. It looks like there was a `.lfs` under .`git` which was not removed when uninstalling git-lfs

**Comment by bk2204** [comment]
It's true that we don't destroy LFS objects in the repository when you uninstall Git LFS, but it's also the case that Git should not try to invoke Git LFS if the repository isn't set up for it, regardless of whether there are LFS objects present.

**Comment by bk2204** [comment]
Hey,

It doesn't look like there's been a response to this recently, so I'm going to close it.  If you can provide the additional information we've requested, let us know and we'll reopen.
