### ISSUE TITLE
Unable to push files due to redirects from HTTP to HTTPS

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [git-lfs/git-lfs#3698]
This is a similar issues as discussed in https://github.com/git-lfs/git-lfs/issues/3351#issuecomment-437166407.

I was trying to push some files into a new repo and it fails due to redirects (or so it seems):

```
$ GIT_TRACE=1 git lfs push --all gaips

...

02:16:22.180891 trace git-lfs: tq: retrying object 5c814834b6f1e879705df8faf705a550206a473cb4229dbacd10673853a971ff: LFS: Put https://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/5c814834b6f1e879705df8faf705a550206a473cb4229dbacd10673853a971ff: read /home/ricardo/Documents/Unreal Projects/ThreeMotionDungeon/.git/lfs/objects/5c/81/5c814834b6f1e879705df8faf705a550206a473cb4229dbacd10673853a971ff: file already closed
```

I can put more info if you need. I don't know if it is a misconfiguration on my side or an error on the `git-lfs`. Can you help me?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Can you run the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`? If there are redirects from HTTP to HTTPS, we'd see them there.

If there are redirects happening, what I expect we'll see is that the server is returning an HTTP URL for the batch request, and then redirecting to HTTPS when the put request happens. However, by that point, we've already closed the body. If that's the case, then I think I may be able to come up with a solution.

**Comment by RicardoEPRodrigues** [comment]
The log is 1.5MB because it keeps retrying to send files... so I had to cancel the push. But I think the important log part is this:

```
< HTTP/1.1 302 Found
< Content-Length: 321
< Content-Type: text/html; charset=iso-8859-1
< Date: Mon, 01 Jul 2019 16:06:56 GMT
< Location: https://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6
< Server: Apache
< 
trace git-lfs: api: redirect PUT http://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6 to https://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6
trace git-lfs: HTTP: PUT https://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6
> PUT /Three-Motion-Dungeon.git/info/lfs/objects/98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6 HTTP/1.1
> Host: code.gaips.inesc-id.pt
> Authorization: Basic * * * * *
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
> 
trace git-lfs: xfer: adapter "basic" worker 1 finished job for "98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6"
trace git-lfs: xfer: adapter "basic" worker 1 processing job for "c7f76c15dd847b8ab35a3d4044faea7e3b83f49a47a1ee6337b15687a8caebdc"
trace git-lfs: tq: retrying object 98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6: LFS: Put https://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6: read C:\Users\Ricardo Rodrigues\Documents\Unreal Projects\ThreeMotionDungeon\.git\lfs\objects\98\bd\98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6: file already closed
trace git-lfs: tq: enqueue retry #1 for "98bdd6eeb046952f992392ee5980f29ad2c584f5b6aaad65662fa26286096be6" (size: 4943365)
trace git-lfs: HTTP: PUT http://code.gaips.inesc-id.pt/Three-Motion-Dungeon.git/info/lfs/objects/c7f76c15dd847b8ab35a3d4044faea7e3b83f49a47a1ee6337b15687a8caebdc
> PUT /Three-Motion-Dungeon.git/info/lfs/objects/c7f76c15dd847b8ab35a3d4044faea7e3b83f49a47a1ee6337b15687a8caebdc HTTP/1.1
> Host: code.gaips.inesc-id.pt
> Transfer-Encoding: chunked
> Authorization: Basic * * * * *
> Content-Type: application/octet-stream
> User-Agent: git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
> 
trace git-lfs: HTTP: 302
```

Hope it helps.

[gitlog.txt](https://github.com/git-lfs/git-lfs/files/3346501/gitlog.txt)

**Comment by bk2204** [comment]
Thanks for this information.

The problem here is that your server is producing a 302 in this case. Go's HTTP redirection support changes the request from a PUT to a GET in this case (since that's what web browsers do), so even if we rewound the body, this request wouldn't work, since GET requests can't have a body and the server wouldn't accept the request. You'll need to adjust your LFS server implementation so that it provides the correct URL (one using HTTPS) in the batch request. Git LFS doesn't provide a way to rewrite these requests, since the server is presumed to know where the data should be sent.

If the response were a 307 or 308, we could add support for that in Git LFS, but a 301 or 302 won't work here.
