### ISSUE TITLE
Unable to push files due to 400 error from GH

### ISSUE THREAD

**Issue by Bogdanp** [git-lfs/git-lfs#3700]
Hi there,

I'm not sure if this is exactly the appropriate place for this, but I've just started getting errors while trying to push changes to my project. I've narrowed it down to `git-lfs push`:

```
$ env GIT_TRACE=1 git lfs push --all origin master
17:33:19.544308 git.c:670               trace: exec: git-lfs push --all origin master
17:33:19.544545 run-command.c:643       trace: run_command: git-lfs push --all origin master
17:33:19.563559 trace git-lfs: exec: git 'version'
17:33:19.580773 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
17:33:19.593949 trace git-lfs: exec: git 'config' '-l'
17:33:19.600898 trace git-lfs: Upload refs [master] to remote origin
17:33:21.123980 trace git-lfs: run_command: ssh -- git@github.com git-lfs-authenticate Bogdanp/matchacha.git upload
17:33:22.651422 trace git-lfs: HTTP: POST https://lfs.github.com/Bogdanp/matchacha/locks/verify
17:33:23.043996 trace git-lfs: HTTP: 400
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://github.com/Bogdanp/matchacha.git/info/lfs.locksverify false
Client error: https://lfs.github.com/Bogdanp/matchacha/locks/verify
```

I'm not sure what's causing the 400 response or how to inspect it.  The authenticate command returns a valid JSON object containing my credentials and this was working just fine earlier today.

Feel free to close this if I should be contacting GH directly about this problem.

Thanks!

**Comment by bk2204** [comment]
Hey,

I think this is likely a GitHub problem; it would be great if you could reach out to the GitHub support folks.

**Comment by Bogdanp** [comment]
Thanks! I went ahead and sent them a message. I'll leave this issue open until they manage to resolve the problem, if you don't mind, so others can find it easily (since it looks like I'm not the only one affected).

**Comment by rlig** [comment]
It is a problem with 
![image](https://user-images.githubusercontent.com/32437712/60449504-1830ff80-9c28-11e9-8d0c-d0cea96b7aa7.png)

on cluster 192.30.253.117 it works properly, change Your /etc/hosts files temporarly

**Comment by bk2204** [comment]
Thanks for reaching out to us about this. I've been in contact with other GitHub folks and this issue should be resolved.

If you've changed your `/etc/hosts` file as suggested by @rlig, you should be able to remove that and have things work as normal.
