### ISSUE TITLE
`git lfs track` uses CRLF on Linux

### ISSUE THREAD

**Issue by pickfire** [git-lfs/git-lfs#3702]
https://github.com/git-lfs/git-lfs/pull/1914

> OR the core.autocrlf is true or input

If it's `input`, it should use LF.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This does appear to be broken if the `.gitattributes` is empty or missing. If it's already there, we do appear to preserve the current line ending.

I'll mark this as a bug so we can keep track of it.
