### ISSUE TITLE
error: your push referenced at least 3 unkown Git LFS objects

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [git-lfs/git-lfs#3708]
I have a project/repo with a venodored subrepo/dependency, and the external repo that I've vendored into my own uses `git lfs` to track certain large files. I don't actually need any of those large files, but am now unable to push my own local git repo to my own github due to this git-lfs error. I read through this issue: https://github.com/git-lfs/git-lfs/issues/3231 and tried several things which I thought would solve the problem, but so far I have been unable to resolve this.

Here's how I pulled the external dependency/repo (DeepSpeech/) into my local repo (voice_to_text/):

```
# from ~/voice_to_text/:
DS_COMMIT_HASH=4b29b78832036216b53f59b953639bde7cde7dfe 
mkdir vendor && cd vendor
wget https://github.com/mozilla/DeepSpeech/archive/$DS_COMMIT_HASH.zip
unzip $DS_COMMIT_HASH.zip
mv DeepSpeech-$DS_COMMIT_HASH DeepSpeech  # (mv as rename)
rm $DS_COMMIT_HASH.zip
```
So at this point I have a project structure like:
```
voice_to_text
  - [my code files]
  - vendor
     - DeepSpeech
         - [DeepSpeech stuff]
```
then from `~/voice_to_text` I ran:
```
git remote add origin [new empty repo at my github]
git push origin master
```
but I get the error from the title:
```
remote: Resolving deltas: 100% (682/682), done.
remote: error: GH008: Your push referenced at least 3 unknown Git LFS objects:
remote:     e1fa6801b25912a3625f67e0f6cafcdacb24033be9fad5fa272152a0828d7193
remote:     a5324f06b27c7b4ef88dd2c8bc3d05d4c718db219c2e007f59061a30c9ac7afa
remote:     1991108e83cf86830cad118ac9e061aadfc89b73a909a66fe1755f846def556e
remote: Try to push them with 'git lfs push --all'.
To github.com:MaxPowerWasTaken/voice_to_text.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:MaxPowerWasTaken/voice_to_text.git'
```
So I tried `git lfs push --all` and then `git push origin master`. Same error.

Here's the output of my `git config --list | grep lfs`:
```
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
lfs.https://github.com/MaxPowerWasTaken/voice_to_text.git/info/lfs.access=basic
lfs.allowincompletepush=true
```
and for `git lfs ls-files`:
```
e1fa6801b2 - vendor/DeepSpeech/data/lm/lm.binary
a5324f06b2 - vendor/DeepSpeech/data/lm/trie
```
(Incidentally, I can't understand why that's only two files instead of three, give the "3 unknown GIt LFS objects).

I also tried `git-lfs untrack [those two files from git lfs ls-files]` and then `git push origin master` again but same error. I even tried `git lfs uninstall` which showed:
```
Hooks for this repository have been removed.
Global Git LFS configuration has been removed.
```
but then `git push origin master` still threw the same error. At this point I'm pretty out of ideas, any help would be super appreciated!

Thanks,
Max

**Comment by bk2204** [comment]
Hey,

So what I think is happening here is that you're download an archive of a GitHub repository that uses Git LFS. Those archives don't provide the large files themselves; instead, they just provide the pointer files. When you add those pointer files into your project, you reference those large objects, but your repository doesn't have them, so you can't push them.

What you'd need to do is clone the repository (possibly as a shallow clone if you don't want the history) and then copy those files (e.g. using `cp -R`) into your `vendor` directory. When you do `git add`, those files will then be cleaned into your repo, and things should be pushable.

**Comment by MaxPowerWasTaken** [comment]
Thanks for the answer bk2204! I don't think that quite explains it though. I do already have those files
```
vendor/DeepSpeech/data/lm/lm.binary
vendor/DeepSpeech/data/lm/trie
```
in my filesystem and git. They're visible with both `ls vendor/DeepSpeech/data/lm` and `git ls-files vendor/DeepSpeech/data/lm`. I also tried `git add`'ing them again and trying `git push origin master` but still same error...

**Comment by bk2204** [comment]
When you look at those files (say, with `less`), are they pointer files, or are they actual data files? The archive will have those pointer files, which GitHub will see in the history. When it does see them, it looks to make sure that the LFS objects are present, and when they're not, you see the error above.

The message essentially means that somewhere in your history, you have some pointer files that you don't have LFS objects for, and you'd need to figure out where they are. A helpful technique is to look at the `.gitattributes` files in your repository (in this case, likely within one of the `vendor` directories) and see what files are listed as using LFS. That should give you a hint as to which files you should look at.

For reference, a pointer file looks something like the following:
```
version https://git-lfs.github.com/spec/v1
oid sha256:53c234e5e8472b6ac51c1ae1cab3fe06fad053beb8ebfd8977b010655bfdd3c3
size 2
```

**Comment by MaxPowerWasTaken** [comment]
Thanks for the response and reopening bk2204. The other day a friend helped me solve this in person. You're right, the files on my system were in fact just pointer files.

We ended up hosing my vendor/ subdirectory and pulling it back in via a fresh `git clone`, which solved the problem. Thanks again for the follow-up explanation.
