### ISSUE TITLE
How to use client certificate?

### ISSUE THREAD

**Issue by Lem** [git-lfs/git-lfs#3709]
I'm using a web server which requires a client certificate to interact the software that includes the LFS-API. As I couldn't find anything about that:

How can I configure git-lfs to use a client-certificate for its HTTP calls?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

You can configure Git LFS to use a client cert exactly the same way as for Git: by using the `http.sslCert` and `http.sslKey` options. You can adjust this on a per-domain or per-URL basis as described in `git config --help` (e.g., `http.https://example.com/.sslCert`). I don't believe we support the environment variables at this time, though.
