### ISSUE TITLE
developer signature problem in macos (catalina)

### ISSUE THREAD

**Issue by dankelley** [git-lfs/git-lfs#3714]
I'd like to use git-lfs in my macos catalina machine. I'm aware that catalina is in beta release, but still I wonder what will happen to git-lfs in a few months (?) when catalina is released.

My OS can find the existing git-lfs, i.e.
```
$ which git-lfs
/usr/local/bin/git-lfs
```
but when I try to run it (from the terminal, or in other ways), I get an error message stating that 
```
"git-lfs" can't be opened because Apple cannot check it for malicious software
```

I know that I can get around that with an `xattr -d com.apple.quarantine` command, but I sort of like how apple is being cautious.

I wonder ... is there a chance the binaries could be signed in the future, to avoid this problem?

Again, to emphasize, I'm using Catalina, so it's not what most mac people will have, for a few months at least.

Thanks!!

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Is this `git-lfs` binary one that comes from Homebrew or one that comes directly from us? If the latter, we can certainly look into signing future binaries.

We already do that for Windows, so it shouldn't be significantly more work, and hopefully we can integrate it with CI so those signed builds run automatically.

**Comment by dankelley** [comment]
I believe it came from you.

**Comment by bk2204** [comment]
> I believe it came from you.

Great. We're planning to do a release this week, which won't include signed binaries for macOS, but hopefully we'll get it in for a future release. Do be aware that we typically ensure Git LFS binaries are up to date in Homebrew, so when Homebrew has support for Catalina, that can serve as an alternative resource if we haven't gotten new signed binaries out yet.

**Comment by nievesj** [comment]
Had this same issue. Building for source was my solution.

**Comment by Skjalgsm** [comment]
I encounterd the same problem now with a fresh install from Homebrew

**Comment by Skjalgsm** [comment]
I believe this issue is fixed by doing brew update git-lfs or brew install git-lfs now

**Comment by bk2204** [comment]
As a note, we've requested an Apple developer certificate, and once we've got one, we'll set up the Actions release workflow to automatically sign the macOS binaries for future releases.

**Comment by papple-developer** [comment]
Hi sir,
Any update on this issue, as I am also facing the same issue "~/ git-lfs-darwin-amd64-v2.9.1 % sudo ./install.sh
error: git-lfs died of signal 9

**Comment by bk2204** [comment]
Nope, there isn't an update.  Our request for a developer certificate is still pending.

**Comment by emraz** [comment]
Hi, Any update or still pending?

**Comment by bk2204** [comment]
We're still awaiting a certificate.  When this is fixed, the issue will be closed.

**Comment by wreimers** [comment]
Hi @bk2204 - any news on obtaining a dev cert from Apple?

**Comment by bk2204** [comment]
It looks like we've got access to a developer account, so we should be able to sign future releases.  All that's required now is someone to actually set up the signing process, which I hope to do before the 2.11 release.

**Comment by wreimers** [comment]
Awesome! :)

**Comment by Skjalgsm** [comment]
I've recently went through the hassle of creating a signing script for mac apps. Feel free to reuse
https://gist.github.com/Skjalgsm/5e9090abb4bb6ec140a910df9080061f

It takes 4 parameters
1. Path to app, can be empty string and then it will just use *.app
2. Release or development. This is used for setting the signature to either "Mac Developer: $DEVNAME" or "3rd Party Mac Developer Application: $DEVNAME".
3. Developer name (The same developer name you can see in the top right corner in developer.apple.com when going to certificates tab). This is used to append the signature as $DEVNAME
4. The path to the provisioning profile

example:
./mac_sign.sh "" "release" "MyCompany (342HS586)" "pathToYourProv.provisionprofile"

**Comment by adamscholefield** [comment]
I found a quick workaround until a signed version is released. 

Basically, you want to set "Allow apps downloaded from anywhere" in Settings/Security & Privacy. In Catalina, this option isn't available but you can do it with the terminal command "sudo spctl --master-disable". 

So the basic procedure is as follows:
  1. run "sudo spctl --master-disable" in the terminal.
  2. install git-lfs as normal
  3. Go to settings/security and privacy and select "Allow apps downloaded from App Store and identified developers" (this is optional but probably good practice to restore things back to the default.

**Comment by lasantha57** [comment]
@adamscholefield Thanks for the update. That worked for my Catalina 10.15.3 🙇

**Comment by YosiMass** [comment]
Thanks adamscholefield!  What you suggest worked!  

Just a minor comment - I could not change back the security permissions from the setting/security and privace. However, I run 

"sudo spctl --master-enable"

And it set it back to "App Store and identified developers"

**Comment by bk2204** [comment]
It turns out that we do have access to a developer account and a set of certificates, but don't have the right kind (a Developer ID certificate) to actually get the binaries notarized.  We're working on it, but that won't be a part of 2.11.

**Comment by STOpandthink** [comment]
The situation is slightly easier for OS X Ventura. If you try to use `git lfs` and then go to Settings > Privacy & Security. Then scrolling down you'll see a message that says that "git lfs" was blocked. You can click to allow it anyway.
