### ISSUE TITLE
Provide an environment variable or a gitconfig setting to disable LFS functionality

### ISSUE THREAD

**Issue by andrewshadura** [git-lfs/git-lfs#3721]
Related to #3695, it’s be very useful to have something to disable the LFS functionality e.g. when running `git push` without also disabling any other hooks that may have been set up for this one particular repository.

**Comment by bk2204** [comment]
Hey,

Can you tell me a little more about your use case so that we can look into providing the best solution?

**Comment by andrewshadura** [comment]
Well, the use case was described a bit in #3695, but let me elaborate.

I’m using git-lfs with dgit to build a Debian packaging workflow. Upstream tarballs get stored in LFS (on a separate branch) by pristine-lfs, a git-lfs wrapper I wrote, while the packaging itself happens as usual using only basic git features: two branches, one for upstream source, one for upstream source plus Debian packaging metadata.

dgit is a tool that allows me to build a Debian source package from a Git commit, upload it to Debian and push the Git branch to a dgit repository in one step. dgit verifies branches and tags pushed to it, so it only allows changes related to the real upload go through. When I run `dgit push`, it constructs a Git branch to push from my maintainer’s branch and pushes it to a predefined location unrelated to my normal repository, and it pushes there using the URL; it doesn’t add a new remote. dgit’s server side infra doesn’t support LFS and doesn’t need to, since it only cares about the actual source being uploaded, but not about the tarballs. Storing tarballs in LFS on a separate branch is just a matter of convenience for maintainers, but it’s not relevant to dgit.

What happens now is that once I have used git-lfs (directly or through pristine-lfs) on a repository, it sets up a pre-push hook for the reasons described in #3695. It works all fine as long as I only even push to [Salsa](salsa.debian.org), Debian’s GitLab instance, which has LFS enabled. However, when I’m finished working on the package and I want to upload it to Debian, I want to do that with dgit, and then push fails, since it attempts to push to `git+ssh://…` which 1) wasn’t understood by the hook until recently, 2) would fail anyway since the hook would try to talk to the LFS server-side which isn’t there.

To enable dgit to interoperate with git-lfs, one solution would be to detect that the pre-push hook installed is the git-lfs hook and pass `--no-verify` as you advised, since we want to enable maintainers to potentially use pre-push hooks other that git-lfs’s. However, this may break when you change the hook’s code.

This is where a gitconfig setting or an environment variable (or both) would be helpful — dgit could just run git push as usual, but tell LFS this remote doesn’t care about LFS things and we actually know what we’re doing and we want it. Basically, just like `--no-verify` but *only* targeting LFS and nothing else.

**Comment by bk2204** [comment]
One thing that I usually suggest in this case is to edit the `.git/hooks/pre-push` hook itself to not invoke `git lfs pre-push` except for the remotes you want. For example, you could do something like the following:

```sh
#!/bin/sh -e

[ -n "${2%%*salsa.debian.org*}" ] || git lfs pre-push "$@"
```

which will skip the push unless you're pushing to Salsa. We do install hooks, but we shouldn't overwrite customized hooks, so this technique should continue to work. This is the way we've suggested handling this in similar situations in the past, where people want to push only the Git and not the Git LFS contents. It is also the "I know what I'm doing" approach.

I'm hoping that I can get multiple hook support in Git soon, in which case you'll be able to simply override the hook with a custom one in this case in dgit without affecting other hooks that users may have implemented.

**Comment by andrewshadura** [comment]
Thanks, but I don’t think this can scale; e.g. this assumes LFS-enabled repos can only live on Salsa, while it’s not mandated by any Debian policy at the moment. This means I cannot hard-code this hook into `pristine-lfs`, since it would be e.g. unusable by Debian downstreams/derivatives and require patching there.

**Comment by bk2204** [comment]
Is there a reason why the following hook wouldn't work?

```sh
#!/bin/sh -e

[ -n "$LFS_SKIP_PUSH" ] || git lfs pre-push "$@"
```

Then you could have the environment variable you want in this case. I'm pretty sure Git doesn't filter the environment for hooks, so this should work for you just as well as an option we'd provide. We wouldn't have any need to change the body of the hook, since any changes would simply go into the binary itself, so this should be forward and backward compatible.

**Comment by andrewshadura** [comment]
That would certainly work, but I didn't want to bikeshed an environment
variable’s name only for you to reimplement it at some point with a
different name. If you’re going to implement it in git-lfs itself with the
same name, I can safely start to use it in pristine-lfs already.

**Comment by andrewshadura** [comment]
Andrej Shadura writes ("Re: [git-lfs/git-lfs] Provide an environment variable of a gitconfig setting to disable LFS functionality (#3721)"):
> That would certainly work, but I didn't want to bikeshed an environment
> variable s name only for you to reimplement it at some point with a different
> name. If you re going to implement it in git-lfs itself with the same name, I
> can safely start to use it in pristine-lfs already.

This is a good plan.

> On Wed, 31 Jul 2019, 19:13 brian m. carlson, <notifications@github.com> wrote:
...
>     Then you could have the environment variable you want in this
>     case. I'm pretty sure Git doesn't filter the environment for
>     hooks, so this should work for you just as well as an option
>     we'd provide. We wouldn't have any need to change the body of
>     the hook, since any changes would simply go into the binary
>     itself, so this should be forward and backward compatible.

I can confirm that git does not launder the environment for hooks.
Just as well given the other things I have done this way :-).

Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.

If I emailed you from an address @fyvzl.net or @evade.org.uk, that is
a private address which bypasses my fierce spamfilter.

**Comment by bk2204** [comment]
I don't have an immediate plan for implementing it, but if you want an officially blessed name, it will probably be `GIT_LFS_SKIP_PUSH`. That's consistent with what we use for `GIT_LFS_SKIP_SMUDGE` and it's what I would pick if I did implement it, and I think in this case, this is a good situation for overriding our typical hook.

**Comment by andrewshadura** [comment]
Thanks!
So, I’m putting this into pristine-lfs as the default pre-push hook:
```sh
#!/bin/sh -e

case "$GIT_LFS_SKIP_PUSH" in
    true | on | 1)
        exit 0
        ;;
    *)
        git lfs pre-push "$@"
        ;;
esac
```

**Comment by bk2204** [comment]
Looks great!

**Comment by andrewshadura** [comment]
In this case dgit can already set the environment variable, and in case it detects the git-lfs default hook, it can override it in a different way.

**Comment by andrewshadura** [comment]
Just in case there’s any probability this might get onto your todo list soon, ping :slightly_smiling_face:
