### ISSUE TITLE
git-lfs disabled for private repo 

### ISSUE THREAD

**Issue by rajatmodi62** [git-lfs/git-lfs#3723]
Hi, 
I am unable to use git-lfs with my private repos. 
Github Id: rajatmodi62@gmail.com
Error: batch response: Git LFS is disabled for this repository.
Could you please support?
Thanks 
Rajat

**Comment by bk2204** [comment]
Hey,

The "batch response" indicates that this message comes from the server side. Since this repository is only for the Git LFS client, could you reach out and contact GitHub support at support@github.com? They'd be able to help you figure out why Git LFS is disabled.
