### ISSUE TITLE
Push to a Git repository with Git LFS enabled is timed out?

### ISSUE THREAD

**Issue by SepidehAbadpour** [git-lfs/git-lfs#3725]
I have used the following codes to enable LFS in my git repository

```
git lfs install  
git lfs track "Powerpoint/UAVSAR_Slideshow.pps"  
git add .gitattributes  
git commit -m "Reinstall LFS, Track the file Powerpoint/UAVSAR_Slideshow.pps and add .gitattributes"  
git add .  
git commit -m "Add Powerpoint/UAVSAR_Slideshow.pps"
git push 
```  

**Result**
```
fatal: unable to access 'https://github.com/***/***.git/': Could not resolve host: github.com  
```
**Code:**
```
git lfs status  
``` 
**Result:**  
```
On branch master
Git LFS objects to be pushed to origin/master:

    Powerpoint/UAVSAR_Slideshow.pps (27331eceacff96fb585b5c4a1a7732c2fecd698a01d8404591e32f4f67f4d94b)

Git LFS objects to be committed:


Git LFS objects not staged for commit:
```  
**Code:**  
```
git lfs ls-files  
```
**Result:**  
```
27331eceac * Powerpoint/UAVSAR_Slideshow.pps  
```
**Code:**
```
git lfs push origin master  
```
**Result:**
```
LFS: Put https://github-cloud.s3.amazonaws.com/***: net/http: HTTP/1.x transport connection broken: write tcp ***->***: i/o timeout
Uploading LFS objects:   0% (0/1), 211 MB | 30 KB/s, done
```
What can I do to solve the problem and push the changes to remote repository?
**btw** my pps file is only 92 MB not very big.

**Comment by bk2204** [comment]
Hey,

It sounds like you're having some network issues. The inability to resolve github.com and the fact that you're getting an I/O timeout are indicators of this. You could try from a different network to see if that's the problem. Other than that, it could be an anti-virus program or a corporate filter that is preventing access, in which case you could try uninstalling the anti-virus program or again, connecting from a different network.

I don't really think there's anything that Git LFS could do differently here, but if you're still seeing this issue and having trouble pushing to GitHub, you could try reaching out to GitHub support and see if they can help you track down the issue, although I suspect they're going to have the same suggestions.

Sorry I can't provide any more helpful information.

**Comment by SepidehAbadpour** [comment]
Maybe it was a network issue. I had the same problem for 18 hours since last night while I was able to surf the net easily and even update my repository without LFS objects. I had tried both `git push` and `git lfs push origin master` several times without any result

I had also taken a look to [The initial push to a Git repository with Git LFS enabled takes a long time](https://confluence.atlassian.com/bitbucketserverkb/the-initial-push-to-a-git-repository-with-git-lfs-enabled-takes-a-long-time-951386690.html)
 Fortunately my last try came out as this

```
$ time git push
Uploading LFS objects: 100% (1/1), 94 MB | 446 KB/s, done
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 818 bytes | 409.00 KiB/s, done.
Total 7 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
To https://github.com/SepidehAbadpour/***.git
   dfefbc9..2ff71c0  master -> master

real    4m2.546s
user    0m0.000s
sys     0m0.015s
```

**Comment by bk2204** [comment]
Yeah, at 446 KB/s, 4 minutes sounds about right. Glad it's working for you now.

**Comment by sprakash** [comment]
$ time git push
Enumerating objects: 347, done.
Counting objects: 100% (346/346), done.
Delta compression using up to 8 threads
Compressing objects: 100% (122/122), done.
Writing objects: 100% (288/288), 2.32 GiB | 153.71 MiB/s, done.
Total 288 (delta 219), reused 197 (delta 155)


This hangs again and again. When I run 'git push origin gh-pages --verbose' I get the following line before I hangs :


Pushing to https://github.com/sprakash/sh00bz-web-home.git
Enumerating objects: 347, done.
Counting objects: 100% (346/346), done.
Delta compression using up to 8 threads
Compressing objects: 100% (122/122), done.
Writing objects: 100% (288/288), 2.32 GiB | 155.88 MiB/s, done.
Total 288 (delta 219), reused 197 (delta 155)
POST git-receive-pack (2494017049 bytes)

Also the result is always : 
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

Any ideas ?

**Comment by bk2204** [comment]
Hey,

This error message doesn't involve Git LFS at all and is a plain Git error.  It's likely a network problem that you're seeing.  Since it's not related to this project, could you please either talk to the person responsible for your network or contact GitHub Support if you're certain it's not a problem with your network?

Thanks.

**Comment by sprakash** [comment]
Sorry about that, thanks for your response. I was able to resolve my issue.
