### ISSUE TITLE
Seems like git-lfs is down

### ISSUE THREAD

**Issue by Surmeh** [git-lfs/git-lfs#3726]

**Comment by Surmeh** [comment]
Hello,

I'm trying to pull down release 2.4.0 but the connection seems down. Also most of the newer versions are also not working.
https://github.com/git-lfs/git-lfs/releases/tag/v2.4.1
![image](https://user-images.githubusercontent.com/31482637/61646503-07613000-aca2-11e9-805e-b51f7bbf31af.png)

**Comment by bk2204** [comment]
Hey,

It looks like this is a GitHub issue, judging from https://www.githubstatus.com/. It's probably best to just hold on until the incident is over. If you still see this after the status page says everything is green, we can certainly look into it then.

**Comment by Surmeh** [comment]
Ok, thanks @bk2204, will wait until this incident is over.

**Comment by bk2204** [comment]
Looks like things should be back to normal. Can you confirm that things are working for you now?

**Comment by Surmeh** [comment]
It's working fine for me too, thanks for the update.
