### ISSUE TITLE
git push command hangs

### ISSUE THREAD

**Issue by flokli** [git-lfs/git-lfs#3727]
This might be a duplicate of https://github.com/git-lfs/git-lfs/issues/1520

Server
 - Gerrit 2.16.9 (https://github.com/openfrontier/docker-gerrit)
 - lfs plugin 343efc7eec

Client
 - NixOS 19.03
 - git 2.22.0
 - git-lfs git-lfs/2.7.2

```
$ GIT_TRACE=1 git push origin HEAD:refs/for/master
18:38:51.996263 git.c:439               trace: built-in: git push origin HEAD:refs/for/master
18:38:51.996752 run-command.c:663       trace: run_command: unset GIT_PREFIX; /nix/store/73wg76x4c91q4rpdfgfbq0zd6lrbidjh-openssh-7.9p1/bin/ssh flokli@gerrit.foo 'git-receive-pack '\''/myrepo.git'\'''
18:38:59.887893 run-command.c:663       trace: run_command: .git/hooks/pre-push origin ssh://flokli@gerrit.foo/myrepo.git
18:38:59.893301 git.c:704               trace: exec: git-lfs pre-push origin ssh://flokli@gerrit.foo/myrepo.git
18:38:59.893329 run-command.c:663       trace: run_command: git-lfs pre-push origin ssh://flokli@gerrit.foo/myrepo.git
18:38:59.896043 trace git-lfs: exec: git 'version'
18:38:59.898926 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
18:38:59.901450 trace git-lfs: exec: git 'config' '-l'
18:38:59.902944 trace git-lfs: pre-push: HEAD 087b5eb7b79921a282ebc5269c630e8a9b7d7a34 refs/for/master 0000000000000000000000000000000000000000
```
… and it stalls here.

If I prepend an `echo ` to `.git/hooks/pre-push`, the push goes through.

I can run `git lfs push origin master` to upload lfs objects too (so the `git-lfs-authenticate` dance works) - it's just stalling somewhere in the pre-push hook phase.

cc @ttaylorr

**Comment by bk2204** [comment]
Hey,

Sorry this isn't working for you. I'm interested to know why prepending the `echo` works here, because that shouldn't affect anything.

Could you try to run the command provided in https://github.com/git-lfs/git-lfs/issues/1520#issuecomment-251523332 a couple times and see what it reports back? Specifically, does it also hang, or does it produce useful output every time?

**Comment by flokli** [comment]
Prepending `echo ` (to turn the last line into `echo git lfs pre-push "$@"`) basically disabled executing `git lfs pre-push` entirely, and `git lfs push origin master` seems to have uploaded all my local lfs objects (so a git-lfs powered clone on another machine is able to resolve all references).

Running `git ls-remote --heads --tags -q origin` does work:

```
⇒  git ls-remote --heads --tags -q origin
2b1835e7d4d2a5e017050c6c9ae7e0d66775d7ca	refs/heads/drafts/for/master
595705275f97f03691ef714f2d36c4902d343060	refs/heads/master
ef1fb36134161f702f13300541a5777964a7a298	refs/heads/testjenkins
```

It takes a second or two to return, but that shouldn't be a problem.

**Comment by flokli** [comment]
Hm, `refs/for/master` doesn't exist in that list - Gerrit has a creative way of how remote refs are called - could it be some of the code added in 1.2.0 gets confused by it?

**Comment by bk2204** [comment]
Ah, I misunderstood. I thought you were referring to adding a new line with `echo`, which shouldn't affect anything.

I'm not sure if that code that was added in 1.2.0 is the problem. 1.2.0 was a long time ago, and presumably Git LFS has mostly worked with Gerrit in the mean time. To see if the `git ls-remote` call is the problem, can you build the `gerrit-hang` branch on my remote? Steps look like the following:

1. `go get github.com/git-lfs/git-lfs`
1. `cd $GOPATH/src/github.com/git-lfs/git-lfs`
1. `git remote add bk2204 https://github.com/bk2204/git-lfs.git`
1. `git fetch bk2204 && git checkout -b gerrit-hang bk2204/gerrit-hang`
1. `make`
1. Copy the `bin/git-lfs` binary to somewhere in your PATH and run it again with `GIT_TRACE=1`.

That should tell us if there's a Git command hanging that's causing the problem, or if the issue is perhaps somewhere else.

**Comment by flokli** [comment]
@bk2204 thanks!

It indeed seems to be the `git ls-remote --heads --tags -q origin` command:

```
GIT_TRACE=1 git push origin HEAD:refs/for/master
[...]
00:27:47.010476 trace git-lfs: exec: git 'config' '-l'
00:27:47.012025 trace git-lfs: pre-push: HEAD beb0108bef11fc19ee695554a0341796f8ab6f8f refs/for/master 0000000000000000000000000000000000000000
00:27:47.012061 trace git-lfs: exec: git 'show-ref'
00:27:47.013598 trace git-lfs: exec: git 'ls-remote' '--heads' '--tags' '-q' 'origin'
```

I am able to execute `git ls-remote --heads --tags -q origin` manually (as written above), but it also stalls while the `git push` is in progress:

```
$  GIT_TRACE=1 git ls-remote --heads --tags -q origin
00:30:08.829203 git.c:439               trace: built-in: git ls-remote --heads --tags -q origin
00:30:08.829368 run-command.c:663       trace: run_command: unset GIT_PREFIX; /nix/store/0k56d663cill7jz7f8prdjk7cz1rkv6l-openssh-7.9p1/bin/ssh flokli@gerrit.foo 'git-upload-pack '\''/myrepo.git'\'''
```

Could this be some deadlock situation while handling packs on the server side?

**Comment by flokli** [comment]
This seems to be a gerrit issue indeed. I bumped `sshd.threads` to something > 2, and suddenly it doesn't block anymore :-)

**Comment by flokli** [comment]
Thanks again for helping out! I added https://gerrit-review.googlesource.com/c/gerrit/+/232013 , so others don't run into it that easily.

**Comment by bk2204** [comment]
Great! I'm glad you got it working.

**Comment by Pastel001** [comment]
> This seems to be a gerrit issue indeed. I bumped `sshd.threads` to something > 2, and suddenly it doesn't block anymore :-)
how many do you modify sshd.thread?
does sshd.thread in gerrit.config?

**Comment by flokli** [comment]
I bumped `sshd.threads` to 4, but see https://github.com/GerritCodeReview/gerrit/commit/2a389469be6b48a8d0823a34c86b162496e8bc12 for docs. In recent Gerrit versions, this shouldn't be an issue anymore.

**Comment by amirc2013** [comment]
There is a new update ?
I also have this problem

**Comment by bk2204** [comment]
Hey, if you're still seeing this issue, could you open a new issue and fill out the template so that we can help you effectively?  It's likely a different issue and we'd need more information to assist you.
