### ISSUE TITLE
git checkout with lfs enabled fails if there's only one remote that's not named origin

### ISSUE THREAD

**Issue by flokli** [git-lfs/git-lfs#3730]
In a Jenkins setup, git-lfs fails in a very unintuitive manner:

```
Triggered by Gerrit: https://gerrit.foo.bar/c/myrepo/+/9054
Checking out git ssh://jenkins@gerrit.foo.bar/myrepo.git into /var/jenkins/.jenkins/workspace/Myrepo-CI@script to read jenkins/sanity.jenkinsfile
using credential b4e03898-8743-4d8c-90fd-4e79f94f8275
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository ssh://jenkins@gerrit.foo.bar/myrepo.git
 > git init /var/jenkins/.jenkins/workspace/Myrepo-CI@script # timeout=10
Fetching upstream changes from ssh://jenkins@gerrit.foo.bar/myrepo.git
 > git --version # timeout=10
using GIT_SSH to set credentials jenkins ssh key
 > git fetch --tags --progress ssh://jenkins@gerrit.foo.bar/myrepo.git +refs/heads/*:refs/remotes/gerrit/* # timeout=10
 > git config remote.gerrit.url ssh://jenkins@gerrit.foo.bar/myrepo.git # timeout=10
 > git config --add remote.gerrit.fetch +refs/heads/*:refs/remotes/gerrit/* # timeout=10
 > git config remote.gerrit.url ssh://jenkins@gerrit.foo.bar/myrepo.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from ssh://jenkins@gerrit.foo.bar/myrepo.git
using GIT_SSH to set credentials jenkins ssh key
 > git fetch --tags --progress ssh://jenkins@gerrit.foo.bar/myrepo.git refs/changes/54/9054/25:refs/changes/54/9054/25 # timeout=10
 > git rev-parse refs/changes/54/9054/25^{commit} # timeout=10
 > git rev-parse refs/remotes/gerrit/refs/changes/54/9054/25^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
Checking out Revision 1637d4eafd782dd020317eaf906dd93a5930edcc (refs/changes/54/9054/25)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1637d4eafd782dd020317eaf906dd93a5930edcc # timeout=10
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f 1637d4eafd782dd020317eaf906dd93a5930edcc" returned status code 128:
stdout: 
stderr: Downloading data/… (20 KB)
Error downloading object: data/… (f8486ef): Smudge error: Error downloading data/… (f8486ef14eb8f0638dd03ac85cf259439eaa5c7d7210260936d44460f3f5bb67): batch request: missing protocol: ""

Errors logged to /var/jenkins/.jenkins/workspace/Myrepo-CI@script/.git/lfs/logs/20190724T072106.075293288.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/…: smudge filter lfs failed

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2318)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$900(CliGitAPIImpl.java:81)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2627)
Caused: hudson.plugins.git.GitException: Could not checkout 1637d4eafd782dd020317eaf906dd93a5930edcc
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2651)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1242)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE
```

The remote name in Jenkins was set to `gerrit`. Once I set this to `origin`, it just works.

Is this some default detection logic inside git-lfs that fails here?

**Comment by bk2204** [comment]
Hey,

When you perform a checkout, Git LFS doesn't know what remote you cloned from because Git doesn't pass it that information. All it knows is that a checkout is occurring. In this case, it picks the remote named `origin` as the place to fetch the objects. If that isn't right for your situation, you can set `lfs.url` in your `.git/config` (or in a file called `.lfsconfig` in your repository) to make Git LFS find the proper URL for the LFS server, assuming there's only one.

I do have plans at some point to make us fall back to a different remote based on the reference we're checking out, but that requires first teaching Git to pass that reference along, and I haven't had the time to get to that yet.

**Comment by flokli** [comment]
I can't really influence the fetching process - that's all coded somewhere deep inside Jenkins itself, before parsing any jenkinsfiles. As I'm using declarative pipelines, I also can't enable the `GitLFSPull` option, so am fully relying on the smudge filter during the clone. :-/

I was assuming we could simply make the logic a bit smarter - if there's only one single remote configured, try this one, otherwise fall back to the default (`origin`).

**Comment by bk2204** [comment]
It looks like we do have code that should do exactly that. I'm not exactly sure why it's not working in your case, but I'll take a look.

**Comment by flokli** [comment]
Well, it /could/ be both the `origin` and `gerrit` remotes existed - I now can't say for sure anymore, as I renamed it to origin…

**Comment by gwerbin** [comment]
> It looks like we do have code that should do exactly that. I'm not exactly sure why it's not working in your case, but I'll take a look.
It appears to be not-working in my case as well.

I have exactly one (non-`origin`) remote configured, and pulling from that remote failed with this error message:
```
$ git merge --allow-unrelated url-search/dev
Downloading src/data.xlsx (2.7 MB)
Error downloading object: src/data.xlsx (73756e0): Smudge error: Error downloading src/data.xlsx (73756e03c79231e47a082a7e6cde5f00b309785a02f6c3094b9e0e6dd9a3e2d9): batch request: missing protocol: ""

Errors logged to C:\Users\gwerbin\project\.git\lfs\logs\20190806T125239.6556738.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: src/data.xlsx: smudge filter lfs failed
fatal: read-tree failed
```
The remote configuration is:
```
$ git remote -v
bing-url-search https://git.example.net/url-search (fetch)
bing-url-search https://git.example.net/url-search (push)
```
and `.gitattributes` is:
```
$ cat .gitattributes
*.xlsx filter=lfs diff=lfs merge=lfs -text
```
The failed merge also appears to have left my repository in some kind of indeterminate state, where HEAD was never advanced and no merge is in progress, but files from the remote were added to the work tree (and now have to be cleaned up by hand).

**Comment by bk2204** [comment]
Okay, I've determined what the problem is. Anytime there's no local reference, we ignore the single configured remote and default to `origin`. I've written up a fix and will open a PR when I'm done writing the tests.

The reproduction steps were very helpful, so thanks for those, @flokli.

**Comment by flokli** [comment]
Thanks a lot for fixing this! :tada:
