### ISSUE TITLE
Reduce volume of logs when using include/exclude

### ISSUE THREAD

**Issue by jw3** [git-lfs/git-lfs#3732]
### setup
- Git LFS versions 2.7.2 and 2.8.0
- Nexus 3 and GitLab LFS servers.

### what
I have a repo with ~8000 files, using `--include` / `--exclude` to only fetch a small subset of these.  The checkout operation results in a significant amount of logging written to disk.

The logs appear to be generated by this

https://github.com/git-lfs/git-lfs/blob/v2.8.0/commands/pull.go#L87-L88

which says

> // acceptable error, data not local (fetch not run or include/exclude) 

The operations I perform are

```
git clone -b the/branch https://the.url
git lfs fetch -I'xxx.*'
git lfs checkout
```

The problem is that the `.git/lfs/logs` loads up with significant logging, ~2.7GB for the 8000 file example.  Is there a way to configure a reduction or redirection of this, or some other way to quiet it down?

Thanks

**Comment by jw3** [comment]
### stderr says

```
Errors logged to /tmp/lfs-data-test/.git/lfs/logs/20190725T180017.876437301.log
Use `git lfs logs last` to view the log.
Skipped checkout for "xxxx.xxxx", content not local. Use fetch to download.
```

### git lfs env
```
Endpoint=https://xxxxxxxxxxxxxx.git/info/lfs (auth=none)
LocalWorkingDir=/tmp/lfs-data-test
LocalGitDir=/tmp/lfs-data-test/.git
LocalGitStorageDir=/tmp/lfs-data-test/.git
LocalMediaDir=/tmp/lfs-data-test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/tmp/lfs-data-test/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/tmp/lfs-data-test/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Looking at this, it doesn't seem like we should be printing a log for this case, since this is explicitly requested behavior and not an actual problem. I'll mark this accordingly and see if I can find some time to fix this.

In the mean time, you'll have to clear the logs by hand. It may be possible for you to replace the `.git/lfs/logs` directory with an empty file, which would prevent them from being written, but I'm not sure if that will have any other unpleasant consequences.

**Comment by jw3** [comment]
Thanks @bk2204

I'll be doing something to build for immediate use here, if you have any hints on the right approach I'll do it that way and PR.  Is the _right way_  simply removing that log call?

**Comment by bk2204** [comment]
I think the right approach is just to call the function `Error` instead of `LoggedError` and omit the `err` parameter. If you'd like to try that, feel free; I'm happy to review a PR.
