### ISSUE TITLE
git-lfs fails to build with gccgo due to the use of _C_int in kr/pty

### ISSUE THREAD

**Issue by glaubitz** [git-lfs/git-lfs#3735]
```git-lfs``` currently fails to build with ```gcgo``` because the ```pty``` library uses the invalid type ```_C_int```:

```
github.com/spf13/pflag
golang.org/x/sys/unix
# github.com/kr/pty
src/github.com/kr/pty/pty_linux.go:39:8: error: use of undefined type ‘_C_uint’
  var n _C_uint
        ^
src/github.com/kr/pty/pty_linux.go:48:8: error: use of undefined type ‘_C_int’
  var u _C_int
        ^
github.com/git-lfs/git-lfs/t/cmd
github.com/git-lfs/gitobj/pack
github.com/git-lfs/gitobj/storage
golang.org/x/sync/semaphore
```

Full build log here: https://buildd.debian.org/status/fetch.php?pkg=git-lfs&arch=sparc64&ver=2.8.0-1&stamp=1564065645&raw=0

I initially reported this as a bug in ```gccgo```, but according to @ianlancetaylor, the bug is in github.com/kr/pty and not ```gccgo``` (see: https://github.com/golang/go/issues/33299#issuecomment-515477268). Since the ```kr/pty``` project seems unmaintained these days, it might be an idea to switch to https://github.com/creack/pty.

**Comment by bk2204** [comment]
Hey,

Is the issue fixed in https://github.com/creack/pty? If so, I'm happy to switch. Currently, it looks like there's still several uses of `_C_int` in the new project, although maybe they aren't problematic in the same way. We don't build with gccgo ourselves, but I don't have a problem unbreaking it if that's all that's required.

**Comment by glaubitz** [comment]
According to @ianlancetaylor it could break with Google's Golang compiler in the future as well depending on which version you are using.

**Comment by bk2204** [comment]
Actually, it looks like the code that was using that module is dead and can be removed, so we should be able to just drop the dependency altogether.
