### ISSUE TITLE
Git bash Error: Could not fork child process: There are no available terminals (-1).

### ISSUE THREAD

**Issue by sarvanguru** [git-lfs/git-lfs#3744]
Hi ,

I am getting following error when opening Git bash. 

**Could not fork child process: There are no available terminals (-1)**

GIT version as we are using:
TortoiseGit 2.6.0.0 (C:\Program Files\TortoiseGit\bin)
git version 2.17.0.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\mingw64\etc\gitconfig; C:\ProgramData\Git\config)

Please suggest.

**Comment by bk2204** [comment]
Hey,

This sounds like a Git Bash issue, and not an issue specifically with Git LFS. I'd recommend contacting the [Git for Windows](https://github.com/git-for-windows/git) project, since they're more likely to be the right place for general Git and Git Bash issues on Windows.
