### ISSUE TITLE
how to report security hole?

### ISSUE THREAD

**Issue by joeyh** [git-lfs/git-lfs#3749]
It's not clear to me how I should report a security hole that in git-lfs. Nothing in CONTRIBUTING about it, no published security policy, and I don't see a good way to privately contact the developers aside from picking a random recent committer to email.

**Comment by bk2204** [comment]
Hey,

I'll make sure we get our docs updated. In the mean time, if you'd like to report a security issue, you can do so at https://hackerone.com/github.

**Comment by joeyh** [comment]
Looks like https://hackerone.com/github is for reporting security holes
in github, but I was asking about reporting a security hole in the
git-lfs client, which doesn't look to be in scope of that.

I found the core team list in the README now ... So would be inclined to
email the people listed there if there's no formal process.

-- 
see shy jo

**Comment by bk2204** [comment]
Since all of the core team members are GitHub employees and this project is maintained as part of their work, that's the preferred way to report issues for the moment, even though reports about Git LFS may not be subject to an actual bounty.

**Comment by chrisd8088** [comment]
As a followup to this, the Reporting Security Issues [documentation](https://github.com/git-lfs/git-lfs/blob/master/SECURITY.md#reporting-security-issues) now describes our official policy, which is to simply email (using PGP encryption if possible) the security report to the Git LFS core team members, exactly as noted in https://github.com/git-lfs/git-lfs/issues/3749#issuecomment-517012514 above ... so thank you for the prompt to flesh this out properly!
