### ISSUE TITLE
Need  help for reverting old commits from git after pushing to bitbucket. 

### ISSUE THREAD

**Issue by sarvanguru** [git-lfs/git-lfs#3778]
Hi Team,

Please provide commands and steps for revert old commits from GIT after pushing my changes. 

getting this error while revert for old commit:
$ git revert 47d5bd739cb287917fa0c3c1764d6454d6633b71
**error: could not revert 47d5bd739... MOBDEV-6141 PortInRequest Alignments
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'** 

Thanks,
Saravanan

**Comment by bk2204** [comment]
Hey,

This sounds like a question that's more appropriate for the Git folks, since this is primarily a Git question. Could you ask this question on the git-users mailing list mentioned on the [Git website](https://git-scm.com/community)?
