### ISSUE TITLE
Read-only doesn't set if path in .gitattributes contains slash on Windows

### ISSUE THREAD

**Issue by crazycoderx2** [git-lfs/git-lfs#3781]
1. git clone https://bitbucket.org/crazycoderx/lfs-test.git
2. attrib /S /D *.*
```
A    R               F:\lfs-test\bin\1\1.tga
A                    F:\lfs-test\bin\1\actionadded.ico
A                    F:\lfs-test\bin\1\WhatsApp Image 2018-06-02 at 00.03.01 (4).jpeg
                     F:\lfs-test\bin\1
A    R               F:\lfs-test\bin\1.tga
A                    F:\lfs-test\bin\actionadded.ico
A                    F:\lfs-test\bin\actiondeleted.ico
A                    F:\lfs-test\bin\actionmerged.ico
A                    F:\lfs-test\bin\actionmodified.ico
A                    F:\lfs-test\bin\actionmoved.ico
A                    F:\lfs-test\bin\actionmovereplaced.ico
A                    F:\lfs-test\bin\WhatsApp Image 2018-06-02 at 00.03.01 (4).jpeg
```
Only path without slash worked.

I think the problem is here:
```15:50:43.181278 trace git-lfs: filepathfilter: rejecting "bin/actionmodified.ico" via [bin\** *.tga bin\*.* bin\*]```

git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
[git-trace.log](https://github.com/git-lfs/git-lfs/files/3513040/git-trace.log)

**Comment by bk2204** [comment]
Hey,

While I haven't actually performed the reproduction on my Windows VM, I agree from looking at the repository that this looks like a bug. I'm going to flag it accordingly and hopefully I or someone else will get some time to look at it soon.

**Comment by bk2204** [comment]
I think this may be fixed when #3797 is fixed (e.g., by #3823).  I'm going to wait until a fix for that merges and then re-test.

**Comment by drachs** [comment]
This problem still exists I think.    Testing locking with LFS on Windows this morning with lfs 2.10.0.    Locking/unlocking a file in the root directory of the repo works fine.   Locking/unlocking a file in a subdirectory fails to set the RO bit.

**Comment by Geep1** [comment]
I was considering LFS primarily for its file locking. Not viable unless this gets fixed.

**Comment by Geep1** [comment]
Thanks for the change. Clears the obstacle to trying out LFS.
