### ISSUE TITLE
git lfs track manual page should inform users about special characters

### ISSUE THREAD

**Issue by gdlxn-ibm** [git-lfs/git-lfs#3784]
I've found that Git LFS does not push a large file with square brackets in its name to LFS.  For example, I have local repository with four large files tracked.  Here's a copy of my `.giattributes` file:

```
* -text
git-issue-103-component/200MiB filter=lfs diff=lfs merge=lfs -text
git-issue-103-component/200MiB+1 filter=lfs diff=lfs merge=lfs -text
git-issue-103-component/50MiB+1 filter=lfs diff=lfs merge=lfs -text
git-issue-103-component/55MiB[1].test filter=lfs diff=lfs merge=lfs -text
```

While `git push` pushes the first three large files to LFS, it does not push `git-issue-103-component/55MiB[1].test` to LFS:

```
C:\r2g-wd-git-issue-103\git-issue-103.git>git push --mirror ssh://git@github.ibm.com/zosdevtk/geoff-git-issue-103
Locking support detected on remote "ssh://git@github.ibm.com/zosdevtk/geoff-git-issue-103". Consider enabling it with:
  $ git config lfs.https://github.ibm.com/zosdevtk/geoff-git-issue-103.git/info/lfs.locksverify true
Locking support detected on remote "ssh://git@github.ibm.com/zosdevtk/geoff-git-issue-103". Consider enabling it with:
  $ git config lfs.https://github.ibm.com/zosdevtk/geoff-git-issue-103.git/info/lfs.locksverify true
Uploading LFS objects: 100% (3/3), 472 MB | 22 MB/s, done
Enumerating objects: 33, done.
Counting objects: 100% (33/33), done.
Delta compression using up to 8 threads
Compressing objects: 100% (30/30), done.
Writing objects: 100% (33/33), 195.73 KiB | 325.00 KiB/s, done.
Total 33 (delta 10), reused 0 (delta 0)
remote: Resolving deltas: 100% (10/10), done.
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: File git-issue-103-component/55MiB[1].test is 55.00 MB; this is larger than GitHub Enterprise's recommended maximum file size of 50.00 MB
remote: detect-secrets-stream (beta) ver=156-2177ec46089d3900a2745c58ad965179573c1b50 FAQ: https://ibm.biz/detect-secrets-stream-faq
remote:
remote: Push info collect pre-receive hook failed to finish within 3 seconds with error code 124
To ssh://github.ibm.com/zosdevtk/geoff-git-issue-103
 * [new branch]      git-issue-103-stream -> git-issue-103-stream
 * [new branch]      master -> master
```

I'm running  `git version 2.23.0.windows.1` and a custom built `git-lfs/2.8.0` with the fix for #3748. on Windows 10.  We've also encountered this problem on RHEL 7.5 as well.

**Comment by bk2204** [comment]
Hey,

I think the problem you're seeing is with your `.gitattributes` file.  In a `.gitattributes` file, a bracket introduces a character class, much like in a Unix shell pattern or a regular expression.  So in this case, the pattern `git-issue-103-component/55MiB[1].test` would match only the file `git-issue-103-component/55MiB1.test`.

If you want to literally match the file `git-issue-103-component/55MiB[1].test`, you'd want to escape the brackets, like so: `git-issue-103-component/55MiB\[1\].test`.

There is a change in master (that came in with #3756) that introduces a `--filename` option to `git lfs track` in case you want to add a literal filename.  That change should also be in 2.9.0 when it's released.

**Comment by gdlxn-ibm** [comment]
Brian,  thanks for getting back to me.  I didn't directly create the .gitattributes entry.  Instead, I simply ran ran `git lfs track "git-issue-103-component/55MiB[1].test"` to track the file. I shouldn't have to know how this command works internally.  Rather, I would think that the `git lfs track` to properly escape the entry it adds to .gitattributes.

**Comment by gdlxn-ibm** [comment]
Also, is there a list of the characters in files names that I need  to escape?

**Comment by bk2204** [comment]
`git lfs track` takes a pattern, not a filename.  If we escaped all values, then you wouldn't be able to write `git lfs track "*.png"`, since that would literally refer to the file `*.png`, which, while invalid on Windows, is a valid if bizarre filename on Unix.  That's why we've added the `--filename` option: so you can specify that this isn't a pattern, but a literal filename.

We escape spaces because otherwise the space would be misinterpreted as a separator between the pattern and the list of attributes.

You need to escape any instance of the following characters that you want to be handled literally: `*[]?`.  These are the Unix shell glob characters that are used by Git's wildmatch handling.

**Comment by gdlxn-ibm** [comment]
Thanks for the explanation and list of characters that need to be escaped.  I should be able to easily add that to my code.

**Comment by bk2204** [comment]
I'm going to reopen this and mark it as an improvement, since I think the documentation could stand some improvement here.  We should say what characters require escaping in the manual page so folks don't have to search everywhere for that information.

**Comment by gdlxn-ibm** [comment]
I tried the new `--filename` option added under #3756.  This options works fine if the filename doesn't contain spaces.  But it doesn't work when the filename contain spaces.  I've added specific details to #3756.
