### ISSUE TITLE
Clonefile: Use FICLONE instead of BTRFS_IOC_CLONE on Linux.

### ISSUE THREAD

**Issue by kazuki-ma** [git-lfs/git-lfs#3792]
There are new IO control  command `FICLONE` instead of `BTRFS_IOC_CLONE`.
 http://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html
This supports not only Btrfs but also other copy-on-write support filesystem.

Due to `FICLONE` is introduced Linux 4.5, fallback to `BTRFS_IOC_CLONE` for Btrfs on old kernel.

Other file system example.
========
XFS also potentially support clonefile (a.k.a. `reflink`) by custom format option (`mkfs –reflink`) and that's default since xfsprogs-5.1.0-rc1 (11 Jul 2019) (https://lwn.net/Articles/794288/).

Until default behavior was changed, some distributions trun on by default. Fedora 29 (2018-10-30) case is there: https://bugzilla.redhat.com/show_bug.cgi?id=1650453

So using `FICLONE` instead of `BTRFS_IOC_CLONE`, Fedora 29 <= user will have benefit of CloneFile.

**Comment by bk2204** [comment]
Hey,

I think this is certainly a thing we could do.  We'd probably want someone with an XFS file system to test, though.

**Comment by kazuki-ma** [comment]
Sorry, I miss-understand about `FICLONE`.

Actually FICILONE is equal to BTRFS_IOC_CLONE.

Let me update this issue title.

And https://github.com/git-lfs/git-lfs/pull/3796 is related PR.
