### ISSUE TITLE
Unable to commit my files in GIT since i have modified. 

### ISSUE THREAD

**Issue by sarvanguru** [git-lfs/git-lfs#3795]
we are getting this error while committing 
On release branch "****"  getting below error while committing :

Your branch is up to date with 'origin/branch_name'.

nothing to commit, working tree clean

git did not exit cleanly (exit code 1) (530 ms @ 8/27/2019 5:30:37 PM) 
but i have modified the files

Please suggest.

**Comment by bk2204** [comment]
Hey,

This sounds like an upstream Git issue.  This project is only for Git LFS, the large file extension to Git, and not for Git itself, which is a separate project.  Could you ask this and other questions about Git on the Git user mailing list mentioned [on the Git website](https://git-scm.com/community)?
