### ISSUE TITLE
t-push-bad-dns gets stuck if no network is available

### ISSUE THREAD

**Issue by QuLogic** [git-lfs/git-lfs#3798]
I'm trying to update the Fedora package for git-lfs to 2.8.0, but the tests are getting stuck. With `prove` running in parallel, everything runs except for `t-push-bad-dns.sh`, which seemingly gets stuck somewhere, and never finishes after an hour.

If I run the build in a chroot with networking enabled, then the test works. However, the official builders have no network access, so this is not an acceptable workaround.

So far, I have bisected the problem to 1412d6e47af351d678f50cf9a5d6e0bc9c92c919.

**Comment by bk2204** [comment]
Hey,

Thanks for letting us know about this.  I'll try to take a look and see why this is failing.  I expect it's a deadlock with that same waitgroup of some sort when we hit an error condition.

**Comment by bk2204** [comment]
I've confirmed that this happens by using a Docker container without network.  It appears to be intermittent, no less.  I'm testing a fix for this right now, and it is exactly the problem I thought it was.
