### ISSUE TITLE
New local repo corrupted by gc - "missing object"

### ISSUE THREAD

**Issue by mrshanepaul** [git-lfs/git-lfs#3810]
Been testing this one to try to make it easily reproducible. I have succeeded at this at least.  

NB: I am working with LFS for the first time so excuse me if I have done something stupid.

I would greatly appreciate any help you might be able to provide.

## Problem:
Add and commit files to local repo. If they trigger a "git gc" I end up with the dreaded "missing object" error which from my (many hours) of research is not easily or at all fixable.  
At this point you cannot pull/push/fetch or almost any other operation.

***NOTE:***

On a hunch I tried the process below WITHOUT adding a new file and just running git gc on the freshly cloned repo with lfs installed.  So no add or commit.   
Same problem....same error...

Then I deleted my .gitignore and .gitattributes files and pushed the repo on a fresh clone. That worked.  
Then ran git gc on this repo and same problem. So its not my .gitattributes?

I really am at a loss here.

## What I have tried:
I thought it might be my computer, disk, GitHub,  .gitattributes, or a particular file in my repo so I experimented by removing these one by one.  
I have now managed to reproduce it with a simple Readme.md file on both MS Devops and github repos.   
Correct me if I am wrong but LFS should not even be involved in this process with this file?!

I am assuming this is either a bug or something wrong with my .gitattributes file. 

## Method:

**git clone <URL>**

```
Cloning into '<Project>'...
remote: Azure Repos
remote: Found 10 objects to send. (3 ms)
Unpacking objects: 100% (10/10), done.
```

**git lfs install**

```
Updated git hooks.
Git LFS initialized.
```

**git config lfs.<URL>/info/lfs.locksverify true**

**touch test.txt**

**git add**

**git commit  -m "Test"**

```
[master f1a18db] Test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
```

**Run git fsck and  git lfs fsck**

```
Checking object directories: 100% (256/256), done.
Git LFS fsck OK
```
**git gc --aggressive --prune=now**

*(Note: I did not run this command manually when I initially had the problem - I have discovered this causes it via experimentation)*

```
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (13/13), done.
Total 13 (delta 2), reused 0 (delta 0)
```

## Results:

**Running git fsck and  git lfs fsck**

```
Checking object directories: 100% (256/256), done.
Checking objects: 100% (13/13), done.
---
Error checking Git LFS files

Errors logged to D:\[[Projects]]\SpriteGenerator\.git\lfs\logs\20190906T092507.9008378.log
Use `git lfs logs last` to view the log.
```

### The log file shows:

```
Error checking Git LFS files
missing object: 0ca446aab9d09eac8625b53e3df8da661976c458
```

Git show tells me this file is the Readme.md

## Other Information

git version 2.23.0.windows.1

ENV:

```
LocalWorkingDir=<ProjectDir>
LocalGitDir=<ProjectDir>.git
LocalGitStorageDir=<ProjectDir>.git
LocalMediaDir=<ProjectDir>.git\lfs\objects
LocalReferenceDirs=
TempDir=<ProjectDir>.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=<ProjectDir>.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
```
[My.gitattributes.txt](https://github.com/git-lfs/git-lfs/files/3581320/My.gitattributes.txt)
[My.gitignore.txt](https://github.com/git-lfs/git-lfs/files/3581321/My.gitignore.txt)

**Comment by bk2204** [comment]
Hey,

The reason you're seeing this issue is that we need to traverse Git history in order to find the pointer files and therefore determine what LFS objects are necessary to push.  If we can't find the relevant objects, then we'll complain.

I'm not able to reproduce this issue on my test repo following these steps.  I don't doubt that it's happening and we are tracking this is #3587, but without a repo that we can use to reproduce this issue, we unfortunately aren't able to fix it.  Do you perhaps have a repo I can use to reproduce the problem?

**Comment by mrshanepaul** [comment]
Hi,

I certainly can. This was a blank repo I created on github with a default Readme file.

All I did was clone it and then run:
```
git gc --aggressive --prune=now 
```

This immediately resulted in the above error.

Now I am assuming that because the errors are similar, this is what I was seeing in my original repo. But it may be that this 'shortcut' to this symptom is coincidentally the same.

Unfortunately I do not know the internals of Git enough to work that out.
[Test.zip](https://github.com/git-lfs/git-lfs/files/3588024/Test.zip)

**Comment by bk2204** [comment]
Interesting.  I don't see this on macOS, but let me try it on Windows.  Perhaps we have a bug in our code that's specific to Windows.

**Comment by bk2204** [comment]
I can reproduce this if I put the file in a directory called `[[Projects]]`, whether on Windows or macOS.  I think that's the issue in this case, and I think I know where the problem lies now.

**Comment by mrshanepaul** [comment]
Aha. The dreaded square brackets in directories not properly supported problem.
MS Excel 2016 has the same problem.

Sounds like it will be a relatively easy fix so that is a good thing.

I will update my directory name in the meantime. :)

I can confirm that changing the DIR name immediately resolves the problem so the repo itself was not corrupted.

Thanks a lot for your help on this.

**Comment by michaelheiml** [comment]
I had the exact same issue and after hours of Googleing, I stumbled upon this solution and it works. What I did was renaming the project root folder from "foldername" to "[Project] foldername" and all of a sudden, "missing object" appeared, actually with the first file in the root folder (.gitignore file). Removing brackets from the folder name immediately solved the issue.
