### ISSUE TITLE
Is the 2GB file size limit a limitation of git lfs or a limitation of github's git lfs support?

### ISSUE THREAD

**Issue by TTimo** [git-lfs/git-lfs#3811]
Hello,

I was reading https://help.github.com/en/articles/about-git-large-file-storage after running into problems doing a first import of a repository with a few (>2GB) large files.

With no github remote, I have a local git lfs with those large files imported, and things seem to work fine. So I would like a clarification - is it correct that git lfs on github won't support files > 2GB, but other git lfs implementations might?

Thank you..

**Comment by bk2204** [comment]
Hey,

Currently, the limitation of 2 GB is purely GitHub, and other implementations may support larger files. We fixed the only known issue that prevents using large files (> 4 GB) on 32-bit systems in 2.7.0, and as far as I'm aware 64-bit systems have always supported files greater than 4 GB.

I will just point out that on Windows, while Git LFS works fine with files greater than 4 GB, Git does not, and so using such files will cause corruption when Git truncates them unexpectedly.  You can see https://github.com/git-lfs/git-lfs/issues/2434#issuecomment-436341992 for more details on that.

Outside of that, there are no known limitations on file sizes.
