### ISSUE TITLE
git lfs migrate import --fixup not working; fatal error with "bad revisions"

### ISSUE THREAD

**Issue by soraryu** [git-lfs/git-lfs#3818]
```
herbst@PFC MINGW32 /e/git/project (master)
$ git lfs migrate import --fixup
migrate: Fetching remote refs: ..., done
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 1
28 fatal: bad revision '^refs/remotes/origin/Alpha-0.5'
migrate: Sorting commits: ..., done

$ git lfs version
git-lfs/2.6.1 (GitHub; windows 386; go 1.11.1; git dc072c3e)
```

See #3285 and #3281 which are closed and state that this is supposed to be fixed in lfs 2.6.0.

**Edit:** just updated to git-lfs 2.7.1 but the behaviour stays the same. Git version is 2.21.0.windows.1.

**Comment by bk2204** [comment]
Can you provide the output of `git ls-remote --heads --tags -q origin | grep Alpha-0.5`?  In addition, does the operation work when using the `--skip-fetch` option?

**Comment by soraryu** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/2693840/64886221-ed224d80-d665-11e9-95bc-cf576cc09081.png)

(Note the message about "migrate: override changes in your working copy?" which is new and didn't disappear even after git reset --hard. I'm using SourceTree, and it doesn't show any changes.)

**Comment by bk2204** [comment]
Okay, great.  That's very helpful.  It looks like we're misinterpreting tags in yet another new and exciting way.  I'll mark this as a bug and hopefully we'll be able to get it fixed soon.

**Comment by soraryu** [comment]
Good to know.

Maybe it helps: I tried deleting the tag in question, only to find that the next one in the list was then appearing as "bad revision".

Looking at the output of `git ls-remote --heads --tags -q origin` without grep shows me that basically every tag has two versions, one without and one with trailing `^{}`.

**Comment by bk2204** [comment]
> Looking at the output of `git ls-remote --heads --tags -q origin` without grep shows me that basically every tag has two versions, one without and one with trailing `^{}`.

Yeah, that's normal.  The regular one is whatever the tag points to, usually a tag object.  If it's a lightweight tag, it will usually be a commit.  The one with `^{}` is peeled; that is, it's recursively resolved until you get to a non-tag (usually the commit corresponding to the tag).

It's there as an optimization; if you know you have the peeled object but not the tag, then you only need to download the tag object, not the entire commit series as well.

**Comment by kola-omosebi** [comment]
has this been fixed? I have the same issue

**Comment by bk2204** [comment]
We have not gotten around to fixing it yet.  Patches are, of course, welcome.

**Comment by goyzhang** [comment]
Is there any temporary workaround for this? I can't migrate existing projects and pulls from the CI environment is really painful.

**Comment by HorlogeSkynet** [comment]
@goyzhang I personally opted for [tags deletion](https://blog.samuel.domains/blog/articles/why-did-i-recently-rewrite-my-whole-blog-git-history#migrate-existing-repositories).

**Comment by goyzhang** [comment]
@HorlogeSkynet  Thanks. I thought about it. But unfortunately, maybe I can delete them locally but on the remote. We need the tags in the repo and they are used for some CI events. It would be nice if we can workaround this without changing anything.

**Comment by bk2204** [comment]
In my testing, using `--everything` doesn't seem to trigger the problem, which may work for you.  I'm looking at a solution for this now.

**Comment by norru** [comment]
Why is this closed?

**Comment by slonopotamus** [comment]
Because it is fixed by #4096.

**Comment by hybridherbst** [comment]
Which version this is fixed in?

**Comment by bk2204** [comment]
If you look at the `CHANGELOG.md` file in the root of the repository, it shows that it was fixed in 2.11.0.

**Comment by msams-v** [comment]
@bk2204 I still have this issue in git-lfs/2.13.3, exactly the same as a topic.
I thin the issue for me comes from the branch names or so, for instance I have `BugFix/branchA` and `bugfix/branchB` but on Windows both map to one folder `.git\refs\remotes\origin\BugFix\`.
As a workaround, I deleted the folder and it works now, but I guess it will break again when another commit to branch A or B will happen, right?

**Comment by bk2204** [comment]
There are many places on a case-insensitive file system where using a different case than what was originally provided to Git happens to work, and there are many cases where it does not.  That isn't specific to Git LFS.  You should look at the actual branch name with `git branch -a` and always use the form specified in that output with Git and Git LFS.

If you've done that, and you still see this problem, please open a new issue using the issue template and include reproduction steps on how to trigger this.

**Comment by msams-v** [comment]
Yes, I understand it, thanks! It's definitely related to filesystem first, and I wanted to post it here for other people to know.
I wanted to notice though that I am using different branch for `git lfs migrate` command, and it's not directly connected to those `BugFixes` branches, but somehow it breaks on it

**Comment by bk2204** [comment]
Hey,

What you're seeing is a different issue.  This one involves only tags, and not branches at all.  That's why the CONTRIBUTING documentation says this:

> If you see an old issue that's closed as fixed, but you're still experiencing the problem on your system, please open a new issue. The problem you're seeing is likely different, at least in the way it works internally, and we can help best when we have a new issue with all the information.

It really does help us if people open new issues for things which are supposed to be fixed because we do tend to ignore comments on closed issues.
