### ISSUE TITLE
cannot add files to lfs tracking

### ISSUE THREAD

**Issue by tbagnoli** [git-lfs/git-lfs#3821]
```
git version 2.20.1 (Apple Git-117)
git-lfs/2.8.0 (GitHub; darwin amd64; go 1.12.7)
```
The issue plagues one of my `feature` branches, where - unlike in `master` - some large files are not tracked by lfs. This was due to cloning the repo, checking out to the `feature` branch and committing some changes before remembering to set up lfs to track large files again.

The master branch correctly has these files tracked by lfs, but when I checkout to the `feature` branch, I get:

```
Switched to branch 'feature'
Your branch is up to date with 'origin/feature'.
Encountered 27 file(s) that should have been pointers, but weren't:
...
```

This should be a pretty easy to fix problem, and it's indeed mentioned in the tutorial under

> **Migrating existing repository data to LFS**
> Sometimes files end up committed within your repository when they should have been committed with LFS...

My problem is that the solution proposed there doesn't seem to do anything:
```
$ git lfs migrate import --include="*/data/*" #all files that should be pointers but aren't are in some sub-folder data
migrate: Fetching remote refs: ..., done
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (0/0), done
migrate: Updating refs: ..., done
migrate: checkout: ..., done
```
which as you can see, does absolutely nothing in terms of rewriting commits.

I figured out from other issues that this might be because these files have already been pushed to remote (right?). So I tried to use the `--no-rewrite` option, to avoid rewriting history and just importing these files under lfs as a new commit, but here's what I get:

```
$ git lfs migrate import --no-rewrite --include="*/data/*"
fatal: expected one or more files with --no-rewrite
```
Can anyone explain me this error? How the hell to I make sure that in sub-branch `feature` all files in a `**/data/**` path are again tracked by lfs, as they already are in master? I cannot merge this `feature` branch until this is fixed.

**Comment by bk2204** [comment]
Hey,

It looks like you have two issues here.  One is that your pattern is a little off.  If you want to match all data inside any folder named `data`, your pattern should be `**/data/**`.

The other is that when you use `git lfs migrate import --no-rewrite`, the options change.  In that case, you want to pass the paths on the command line, so you'd write `git lfs migrate import --no-rewrite "**/data**/"` instead.

Does either one of those seem to work for you?

**Comment by tbagnoli** [comment]
Hey @bk2204,
thanks for explaining the different option use - a bit confusing, but anyway.

The error is now the following:

```
$ git lfs migrate import --no-rewrite "**/data/**"
fatal: no Git LFS filters found in .gitattributes
```

which, if I understand correctly, isn't true: see my .gitattributes

```
$ more .gitattributes
**/data/** filter=lfs diff=lfs merge=lfs -text
**/results/** filter=lfs diff=lfs merge=lfs -text
```

**Comment by bk2204** [comment]
I apologize; I made a mistake in the information I told you.  The arguments to `git lfs migrate import --no-rewrite` need to be files, not patterns, and they need to match patterns already present in `.gitattributes`.

**Comment by tbagnoli** [comment]
but I have patterns in gitattributes, and I need to migrate exactly what matches those patterns. Seriously, regardless of whether I'm doing `--no-rewrite` or `--everywhere`, doesn't git lfs have an option to `migrate import` everything that matches the patterns in my `.gitattribute`? Like, how isn't that the most obvious use of this command? -.-'

**Comment by bk2204** [comment]
Yes, there is an option to do that, `--fixup`.  It is, however, incompatible with `--no-rewrite`, so if you don't want to rewrite your history, you won't be able to use it.  In that case, you can use something like the following to perform the rewriting:

```
git lfs migrate import --no-rewrite $(git ls-files | git check-attr filter --stdin filter | awk -F': ' '$3 ~ /lfs/ { print $1 }' | uniq)
```

If you are okay with rewriting history, then `--fixup` should be fine.
