### ISSUE TITLE
Git-lfs cannot access repositories behind Google Cloud Identity-Aware Proxy

### ISSUE THREAD

**Issue by kupson** [git-lfs/git-lfs#3824]
To access service protected by Gcloud IAP a client need to send HTTP cookies (like `GCP_IAAP_AUTH_TOKEN_*`).

Git works fine with it after setting up the `http.cookieFile` configuration option, but git-lfs don't send HTTP cookies at all.

**Comment by bk2204** [comment]
Hey,

I agree that we don't currently send cookies.  I noticed you've already sent in a pull request, which I definitely appreciate.
