### ISSUE TITLE
Invalid port ":<user>" after host

### ISSUE THREAD

**Issue by roipoussiere** [git-lfs/git-lfs#3831]
We have an old GitLab instance (v. 7.7, that doesn't support LFS, [added on v. 8.2](https://docs.gitlab.com/ee/workflow/lfs/manage_large_binaries_with_git_lfs.html#requirements)), and [a git LFS repository on a Nexus server](https://help.sonatype.com/repomanager3/formats/git-lfs-repositories).

We use a self-signed certificate to communicate to the Gitlab instance via https, but I'm used to use git via ssh anyway.

I use git v2.22 and git-lfs v2.8, and my git repo contains a `.lfsconfig` configured to point to the Nexus server, as explained in the tutorial.

Note that I can successfully push to an other, newer GitLab instance that supports Git LFS, but not on the old one. The problem seems to be related to the local configuration of git-lfs when using the Nexus server.

At first I had this warning:

```
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://nexus.example.com/repository/git-lfs/info/lfs.locksverify false
```

So I set `locksverify` to false, but I don't think is related to my problem, because I get the same warning when I push (successfully) to the other GitLab instance. But most importantly, **in both case I have the following error when I push**:

```
batch response: creds: parse //git@gitlab.example.com:johndoe/foo.git: invalid port ":johndoe" after host
error: failed to push some refs to 'git@gitlab.example.com:johndoe/foo.git'
```

Where:
- `nexus.example.eu` is our Nexus instance;
- `gitlab.example.com` is our GitLab instance;
- `johndoe` is my username on both instances;
-  `foo` is the name of my repository.

The `parse //git@gitlab.example.com:johndoe/foo.git: invalid port ":johndoe"`makes me think that git-lfs try to parse the ssh url that I use for GitLab, I don't really understand why.

**Comment by bk2204** [comment]
Hey,

It sounds like you've built your own Git LFS packages using Go 1.12.8 or later (or the equivalent version of Go 1.11).  If so, you'll need to cherry-pick f06492430e8f4a37136c746a29cffb7149beae08 into your version, since the syntax that used to work broke in those versions due to a security fix.  We'll be including that commit in 2.9.0, which is due to be released in early October.

As a workaround, you can switch to using HTTPS URLs if you can't rebuild your Git LFS version.
