### ISSUE TITLE
Question: does squash commit + delete branch releases Git LFS storage?

### ISSUE THREAD

**Issue by bitinn** [git-lfs/git-lfs#3832]
> - If we know git lfs keeps full copies of every version of each binary file being tracked;
> 
> - And that one of our feature branch contains many edits to the same set of large binary files;
> 
> - Then, on squash and merge (eg. merge as a single commit) and deletion of this feature branch, do we finally release storages on remote repo?
> 
> (AFAIK git lfs prune should release local repo storage when binary files are no longer in used; does remote repo know to release storage when there isn't a reference to these older version of binary files?)

I asked this on SO and no one is able to answer it:

https://stackoverflow.com/questions/58022433/does-squash-commit-release-git-lfs-storage

**Comment by bk2204** [comment]
Hey,

Whether an LFS-capable Git hosting provider releases unused objects when they're no longer referenced is up to the individual hosting provider.  GitHub doesn't by default; you'd need to write in to support and ask them to delete the objects for you, or if you're using a GHES instance, you'd want to ask your administrator to delete them.  For other hosting providers, you should ask them.
