### ISSUE TITLE
Error: Git LFS is disabled for this repository

### ISSUE THREAD

**Issue by dmj331** [git-lfs/git-lfs#3836]
Hello, 
I am having problem to "git push" big size file. Please see screenshot,
![image](https://user-images.githubusercontent.com/6643332/65564391-561b9680-df7f-11e9-8848-8eb104a4f134.png)

Can you enable Git LFS support for this repository @ttaylorr @bk2204 ? ThunderSoft-XA/AIProject
Thanks!!

**Comment by bk2204** [comment]
Hey,

If you're having trouble with GitHub, could you write into the GitHub support folks (either using  https://support.github.com/contact or support@github.com)?  This repo is for the open source client and doesn't handle issues with GitHub.

Thanks.
