### ISSUE TITLE
its not work on win10

### ISSUE THREAD

**Issue by theghostbh** [git-lfs/git-lfs#3844]
i try many time and searching for fix the problem i get it its not work any way on win10 how it work ?
i already install software github.com and git lfs but it not work git lfs with github.com

give me way are sure to make it work i want to download source code about 10GB from github.com

thanks for your work to fix all errors and issues

**Comment by bk2204** [comment]
Hey,

Could you copy and paste the text that you're seeing and possibly attach the output of running the relevant Git command with the `GIT_TRACE` environment variable set to `1`?  It's very hard to guess what might be going wrong without that information.

I know we have users who use Git LFS on WIndows 10, so I'm pretty sure that it does at least function on a basic level there.

**Comment by theghostbh** [comment]
look at picure its stoped in here more then 10 houre

https://bh-pcgame.blogspot.com/2019/10/git-lfs-error-or-what.html

this is my blog i add everything i want to show or add in

please help me why it stoped here not say finish or done still on 68%

**Comment by theghostbh** [comment]
i use git clone command its right ??

**Comment by theghostbh** [comment]
i get error in this wen i try 2 time to download it

` git clone https://github.com/Unity-Technologies/FPSSample.git
Cloning into 'FPSSample'...
remote: Enumerating objects: 18652, done.
remote: Total 18652 (delta 0), reused 0 (delta 0), pack-reused 18652
Receiving objects: 100% (18652/18652), 213.75 MiB | 167.00 KiB/s, done.
Resolving deltas: 100% (9780/9780), done.
Updating files: 100% (12731/12731), done.
Downloading Assets/Textures/Generic/Walls/Wall_Metal_Plates_Exterior_A/Wall_Metal_Plates_Exterior_A_Color_A_Albedo.tif (6.2 MB)
Error downloading object: Assets/Textures/Generic/Walls/Wall_Metal_Plates_Exterior_A/Wall_Metal_Plates_Exterior_A_Color_A_Albedo.tif (f915dcd): Smudge error: Error downloading Assets/Textures/Generic/Walls/Wall_Metal_Plates_Exterior_A/Wall_Metal_Plates_Exterior_A_Color_A_Albedo.tif (f915dcd1e48fa2995c062ba711186f4a20a6aea82863941945a3bc1bdb9f4105): batch response: Post https://github.com/Unity-Technologies/FPSSample.git/info/lfs/objects/batch: dial tcp: lookup github.com: no such host

Errors logged to C:\Users\TheGhost\Desktop\New folder\FPSSample.git\lfs\logs\20191006T120722.3269254.log
Use git lfs logs last to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Assets/Textures/Generic/Walls/Wall_Metal_Plates_Exterior_A/Wall_Metal_Plates_Exterior_A_Color_A_Albedo.tif: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by bk2204** [comment]
It's fine to use the `git clone` command; that's the right tool for the job.

It looks like the failure you're seeing is likely a network issue, judging by the `lookup github.com: no such host` error.  Oftentimes folks with otherwise stable network connections see problems with Git LFS because the files are large and a very slightly flaky network can cause a bunch of problems.

It is possible, however, to run `git lfs pull` to download and check out the remaining data, so if you're seeing a failure to clone, you can resume the existing process rather than start a new clone.  That may give you a better chance of success.

**Comment by bk2204** [comment]
Hey,

Since this looks like a DNS issue due to the `dial tcp: lookup github.com: no such host` and there's nothing we can do to fix it, I'm going to close this.
