### ISSUE TITLE
How to upload large files from Colab to GitHub?

### ISSUE THREAD

**Issue by qo4on** [git-lfs/git-lfs#3847]
I'm trying to upload [large files](https://drive.google.com/open?id=1PftQeosXeBnFmtOEaWON5Sm7vvawcuKx) from Colab to GitHub:
![image](https://user-images.githubusercontent.com/35609308/66271541-98df4780-e878-11e9-9c11-ce35c0745266.png)
I install LFS:
```
!curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
!sudo apt-get install git-lfs
!git lfs install

Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  git-lfs
0 upgraded, 1 newly installed, 0 to remove and 139 not upgraded.
Need to get 5,740 kB of archives.
After this operation, 14.0 MB of additional disk space will be used.
Get:1 https://packagecloud.io/github/git-lfs/ubuntu bionic/main amd64 git-lfs amd64 2.8.0 [5,740 kB]
Fetched 5,740 kB in 0s (13.2 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package git-lfs.
(Reading database ... 131187 files and directories currently installed.)
Preparing to unpack .../git-lfs_2.8.0_amd64.deb ...
Unpacking git-lfs (2.8.0) ...
Setting up git-lfs (2.8.0) ...
Git LFS initialized.
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Git LFS initialized.
```
Change current folder and clone git:
```
%cd /content/checkpoints/train
!git clone https://{username}:{password}@github.com/{username}/{project}.git
```
Track folder:
`!git lfs track "/content/checkpoints/train"`
Add files and check status:
```
!git add "/content/checkpoints/train"
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    new file:   .gitattributes
    new file:   train/checkpoint
    new file:   train/ckpt-1.data-00000-of-00002
    new file:   train/ckpt-1.data-00001-of-00002
    new file:   train/ckpt-1.index
    new file:   train/ckpt-2.data-00000-of-00002
    new file:   train/ckpt-2.data-00001-of-00002
    new file:   train/ckpt-2.index
    new file:   train/ckpt-3.data-00000-of-00002
    new file:   train/ckpt-3.data-00001-of-00002
    new file:   train/ckpt-3.index
    new file:   train/ckpt-4.data-00000-of-00002
    new file:   train/ckpt-4.data-00001-of-00002
    new file:   train/ckpt-4.index
```
Do commit:
```
!git commit -m "Uploaded checkpoints"

[master df06e11] Upload checkpoints
 14 files changed, 12 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 train/checkpoint
 create mode 100644 train/ckpt-1.data-00000-of-00002
 create mode 100644 train/ckpt-1.data-00001-of-00002
 create mode 100644 train/ckpt-1.index
 create mode 100644 train/ckpt-2.data-00000-of-00002
 create mode 100644 train/ckpt-2.data-00001-of-00002
 create mode 100644 train/ckpt-2.index
 create mode 100644 train/ckpt-3.data-00000-of-00002
 create mode 100644 train/ckpt-3.data-00001-of-00002
 create mode 100644 train/ckpt-3.index
 create mode 100644 train/ckpt-4.data-00000-of-00002
 create mode 100644 train/ckpt-4.data-00001-of-00002
 create mode 100644 train/ckpt-4.index
```
Change buffer size:
`!git config --global http.postBuffer 3145728000`
And push:
```
!git push origin master

tcmalloc: large alloc 3145728000 bytes == 0x55e488388000 @  0x7fb6c94b11e7 0x55e485b4a825 0x55e485ad273f 0x55e485ad4579 0x55e485ad21ca 0x7fb6c857bb97 0x55e485ad221a
Counting objects: 17, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (17/17), 2.22 GiB | 58.29 MiB/s, done.
Total 17 (delta 3), reused 4 (delta 0)
error: RPC failed; curl 55 Failed sending data to the peer
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```
How can I fix this error? I tried to add these lines before push:
```
!export GIT_TRACE_PACKET=1
!export GIT_TRACE=1
!export GIT_CURL_VERBOSE=1
```
But it didn't change anything.

**Comment by bk2204** [comment]
I think what you're probably seeing here is that your invocation of `git lfs track` isn't correct.  If the top level of your repository is `/content/checkpoints` and `train` is a directory inside it, then you want to go into your repository and run `git lfs track 'train/*` and then add the files.

What you've written tells Git to track anything within the directory `content/checkpoints/train` within your repository, not within the `/content/checkpoints/train` on your system.  (The patterns are for `.gitattributes`, which are like those for `.gitignore`.)  As a result, you probably haven't configured Git to use LFS for any of your files at all.  You can verify which files are properly tracked by running `git ls-files | git check-attr --stdin filter` and making sure that your files are marked with the `lfs` filter attribute; if it says `unspecified`, then they're not being tracked.

Also, the increase in `http.postBuffer` is almost certainly unnecessary unless you know you're behind a broken proxy or talking to a broken Git server (often one that doesn't understand HTTP/1.1).  All it does in this case is cause you to use a lot more memory.

**Comment by qo4on** [comment]
Thank you, bk2204. But it didn't help. `train` is a directory inside the top level directory of my local repository.
I go to my local repository folder and run `git lfs track train/*` with successful `Tracking` status for every file in my local `train` folder.
`!git ls-files` shows only the files in my remote repo.
`!git check-attr --stdin filter` hangs the Colab: after 30 minutes of executing it shows nothing.

**Comment by bk2204** [comment]
Hey,

Sorry for the confusion; I had meant to type `git lfs track 'train/*'` with single quotes around the pattern.  That will track any files that are now or in the future in that directory.

When you're running `git ls-files | git check-attr --stdin filter`, you need to type it at the shell as one unit including the pipe.  If you run `git check-attr --stdin filter` by itself, the process will wait to run until you give it information on standard input, which will make it look like it's hung.

**Comment by qo4on** [comment]
Thank you very much! Can you explain why this line works
`!git lfs track 'train/*'`
But line below with full path doesn't?
`!git lfs track "/content/checkpoints/train"`

Does it mean I must specify path to files, not to folders?

**Comment by bk2204** [comment]
Sure.  The patterns you provide to `git lfs track` are patterns that will be stored in the `.gitattributes` file.  The patterns that are used there are very similar to patterns used in `.gitignore`.  Those patterns are relative to the root of the repository if they start with a slash, so specifying `/content/checkpoints/train` tells Git that it should process files in that path within the repository.  Since a clone of the repository can be located anywhere on a system, Git assumes a leading slash refers to the root of the repository instead of the system root, since a global path wouldn't be likely to be useful.

When you use `git add`, you specify only filenames, so Git will accept any file name that leads to paths within the repository.  Those are filenames, not `.gitattributes` patterns, so the rules are different there.

In general, you want to specify patterns to `git lfs track` that match files; inside a `.gitattributes` file, matching a directory has no effect.  You can see the full set of rules by running `man gitattributes`.
