### ISSUE TITLE
Git lfs lock not working 

### ISSUE THREAD

**Issue by derektan95** [git-lfs/git-lfs#3850]
Hi, 
I've been recently testing out the file locking system and followed the steps on the git lfs manual (https://github.com/git-lfs/git-lfs/wiki/File-Locking). I had these files locked as shown below.

![image](https://user-images.githubusercontent.com/48535336/66361831-55570d00-e94e-11e9-88b8-4968191d11c1.png)

My partner (using the same repo) tried to make modifications on one of these files but he still manages to push the file to master even though it is locked under my name (derektan95). I have tried entering this command but it still doesn't work. 

git config --global lfs.https://github.com/.locksverify true

May I know what other steps I have to do in order to get this working? Thanks!

**Comment by bk2204** [comment]
Hey,

Does your partner also have locking enabled on their repo and the appropriate `lfs.locksverify` value set?  The Git LFS client should fail to allow the user to push if they have locking enabled and attempt to do a normal push.

**Comment by derektan95** [comment]
Hi, 
My partner has the same terminal output when he did git lfs locks. He also set the following command: 

git config --global lfs.https://github.com/.locksverify true

We tried by getting him to modify Player.prefab but he manages to push it through via SourceTree without any issues

**Comment by bk2204** [comment]
Can you try having your partner run the push command from the Git Bash window with `GIT_TRACE=1` and paste the output here as text?  Additionally, the output of `git config -l` on his side would be helpful as well.  That should show us whether we're making the request at all and the response we're getting back.

**Comment by bk2204** [comment]
Ah, yeah, that `false` part of the locksverify option will be the cause.  If you run `git config -l --show-origin`, you'll be able to see the file which sets that value.  You can modify that file with a standard text editor to set the value to `true` without affecting any other files and introducing more settings.

**Comment by derektan95** [comment]
Hi, 
It seems to be working now. Thanks for your help!
