### ISSUE TITLE
Not sure how to migrate a repository while applying lfs migrate

### ISSUE THREAD

**Issue by gjabouley-invn** [git-lfs/git-lfs#3853]
Hello

i am trying to migrate a git repo from Bitbucket to Github.
Repo has a bunch of big files (>100MB, wav/psd/tif) that needs first to be moved to LFS prior to be pushed into Github.

Idea is to:
1. mirror clone locally the Bitbucket repository
1. git lfs migrate offending files
1. mirror push to Github new repository

Here are git commands i ran:
```
git clone --mirror ${BITBUCKET_REPO_URL} local_folder && pushd local_folder
git lfs migrate import --everything --verbose --include="*.wav,*.psd,*.tif"
git reflog expire --expire-unreachable=now --all && git gc --prune=now --aggressive
git push --mirror ${GITHUB_REPO_URL}
```

However, the git push is rejected by Github, yelling:
```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 9520de5428480ee03717e3e30de61664
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Assets/blablabla.psd is 113.27 MB; this exceeds GitHub's file size limit of 100.00 MB
```

Seems my local "mirror" repository is now containing both non-LFS & LFS referencese, and i thought the git reflog/gc would clean it up before the push.

Any help appreciated.

**Comment by gjabouley-invn** [comment]
Could be related to https://github.com/git-lfs/git-lfs/issues/3238 or https://github.com/git-lfs/git-lfs/issues/3568, will investigate

**Comment by bk2204** [comment]
Hey,

I think this is indeed #3238.  I'm going to close in favor of that one, but if you can provide a testcase, we'd love to see one.
