### ISSUE TITLE
get error from git-lfs while pip install

### ISSUE THREAD

**Issue by kaixin-bai** [git-lfs/git-lfs#3855]
when i pip install open3d, got error below. Now i cannot use pip to install package anymore, could someone please help me? Thanks a lot!
HTTPError:404 Client Error: Not Found for url:https://packagecloud.io/github/git-lfs/pypi/simple/git-lfs/

**Comment by bk2204** [comment]
Hey,

It looks like something told your version of pip that there was a pypi version of the git-lfs package, but we don't provide such a package.  I'm not sure why that's happening, though; perhaps you could see if there's a package that's a dependency of open3d that is causing this and contact the maintainer of that package.

Sorry I can't be of more help, but I'm not that familiar with Python tooling and this isn't a package or tooling that we maintain or distribute.

**Comment by kaixin-bai** [comment]
solved by changing file ~/.pip/pip.config

**Comment by anantthebiker** [comment]
> solved by changing the website in '~/.pip/pip.config'

To add to it, I modified the content of pip.config file to: 

[global]
index-url=https://pypi.python.org/simple/
