### ISSUE TITLE
Error Download files stored with GIT LFS

### ISSUE THREAD

**Issue by dachosen1** [git-lfs/git-lfs#3856]
I uploaded a file to GitHub using Git LFS. The file is visible in the git repo, however, when i cloned the repo I received the following message: 

version   https://git-lfs.github.com/spec/v1
oid   sha256:6ec0e9792f6d0b78721e7b241c7fff1ce985e3492855dfeeab2b42d31a45a02a
size 289

Any idea on how to fix this? 

[merged_data_user_level_V2.xlsx](https://github.com/git-lfs/git-lfs/files/3719193/merged_data_user_level_V2.xlsx)

**Comment by bk2204** [comment]
Hey,

Can you verify that you've run `git lfs install` on your system?  Also, can you include the output of `git lfs env` and `git config -l` when run in that repository?

**Comment by dachosen1** [comment]
Hey, I didn't have  git lfs instlalled on my computer, however I was able to fix by installing GIT LFS and recloning the repo. I'm curious is there another way aroud this? 
Thanks for the help.

**Comment by bk2204** [comment]
You'd definitely need to have Git LFS installed and have run `git lfs install` at least once (or had it run for you, as some distro packages do).  You don't technically need to re-clone; you can run `git lfs pull origin master` (or the appropriate remote and branch names) and it will fetch the objects and check them out for you.

**Comment by dachosen1** [comment]
Thanks, that's very helpful.
