### ISSUE TITLE
Cannot push LFS files

### ISSUE THREAD

**Issue by varmanji** [git-lfs/git-lfs#3857]
Hi I've a problem with pushing lfs files.
I've tracked my lfs files but all i get when i push is this error:

batch response: Git LFS is disabled for this repository.

How can i solve that ? I didnt manage to find a solution on google.

**Comment by bk2204** [comment]
Hey,

This sounds like a GitHub issue.  Could you reach out to GitHub support via support@github.com and ask them about this?
