### ISSUE TITLE
Git LFS objects not staged for commit: cannot find in ls-files totally.How to fix?

### ISSUE THREAD

**Issue by AmazingRey** [git-lfs/git-lfs#3858]
`git lfs status`
Git LFS objects to be pushed to origin/feature/RecHistory:

Git LFS objects to be committed:

Git LFS objects not staged for commit:

	Images/Media.xcassets/channel/channel_pause_circle.imageset/channel_pause_circle@3x.png (Git: 574f0ce -> File: 574f0ce)
	Images/Media.xcassets/channel/channel_play_circle.imageset/channel_play_circle@3x.png (Git: 2c4f8ca -> File: 2c4f8ca)
	Images/Media.xcassets/recognizer/recognize_error_clip.imageset/recognize_error_clip@2x.png (Git: cc84dfb -> File: cc84dfb)
	Images/Media.xcassets/recognizer/recognize_failed_clip.imageset/recognize_failed_clip@2x.png (Git: f801e6e -> File: f801e6e)
	Images/Media.xcassets/recognizer/recognize_failed_history_btn.imageset/recognize_failed_history_btn@2x.png (Git: 6a9d74d -> File: 6a9d74d)
	Images/Media.xcassets/recognizer/recognize_failed_rerecognize_btn.imageset/recognize_failed_rerecognize_btn@2x.png (Git: 94c8a48 -> File: 94c8a48)
	Images/Media.xcassets/recognizer/recognize_nonet_clip.imageset/recognize_nonet_clip@2x.png (Git: 1b2d341 -> File: 1b2d341)

Cannot discard theme. Cannot push theme to lfs. Cannot find theme in ls-files.

Appeared when checkout to the specific branch.
So,I cannot checkout to other branch,cause these which are not staged.
What can I do for this status?

**Comment by bk2204** [comment]
Hey,

That message ("Cannot discard theme") doesn't sound like anything that Git or Git LFS produces.  Are you seeing this at the command line or in a program?  If you're seeing this in a GUI frontend, can you try at the command line and paste the exact text you see into this issue (within a code block)?  What operating system, Git version, and Git LFS version are you using?  Do you have any custom hooks?

**Comment by bk2204** [comment]
Hey,

Since there hasn't been a response, I'm going to close this issue.  If you're still seeing this issue and can provide more information so we can track it down, we can reopen the issue.
