### ISSUE TITLE
LFS: method not allowed: PUT

### ISSUE THREAD

**Issue by NaanProphet** [git-lfs/git-lfs#3860]
Hi there! Quick question: Does git-lfs only support PUT requests for uploads?

I was prototyping an implementation Git LFS using Backblaze B2 which only supports POST calls. I'm able to create a pre-signed URL but the error during `GIT_TRACE=1 git push origin master` looks like the following:

```
11:29:00.308082 trace git-lfs: api: batch 1 files
11:29:00.308295 trace git-lfs: HTTP: POST ...
11:29:00.397738 trace git-lfs: HTTP: 200
11:29:00.397850 trace git-lfs: HTTP: {"transfer":"basic","objects":[{"oid":"1eae44fde31ada81387a05a16d20f70b9d2abac1733e4ffefedb0c28ed8f6c9e","size":16272,"authenticated":true,"actions":{"upload":{"href":"https://pod-000-1024-12.backblaze.com/b2api/v2/b2_upload_file/e0920d6e128b819f63d00b1c/c000_v0491024_t0888","header":{},"expires_in":86400}}}]}
11:29:00.458782 trace git-lfs: HTTP: PUT https://pod-000-1024-12.backblaze.com/b2api/v2/b2_upload_file/e0920d6e128b819f63d00b1c/c000_v0491024_t0888
11:29:00.860115 trace git-lfs: HTTP: 405B | 0 B/s                                                                                                        
11:29:00.860290 trace git-lfs: HTTP: {
  "code": "method_not_allowed",
  "message": "method not allowed: PUT",
  "status": 405
}
```

**Comment by bk2204** [comment]
Hey,

The built-in basic transfer adapter only supports `PUT` requests, yes.  It's possible to use a custom (or standalone) transfer adapter that uses a different method, though.  There's documentation in the `docs` directory and we have a standalone transfer adapter for the `file` protocol in `commands/command_standalone_file.go` if you want to see what one looks like.
