### ISSUE TITLE
How to lock all files on current directory?

### ISSUE THREAD

**Issue by baddate** [git-lfs/git-lfs#3867]
i can't use `git lfs lock *.psd` to lock all files on current dir.

**Comment by mohdhanafingah777** [comment]
How to do?

**Comment by mohdhanafingah777** [comment]
I need a help

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you include the contents of your `.gitattributes` file and a code block including the output you're seeing when you try to run the command?

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back, I'm going to close this.  If you can provide additional information, I'm happy to reopen.
