### ISSUE TITLE
Possible to use github.com/google/slothfs alternative?

### ISSUE THREAD

**Issue by ssgelm** [git-lfs/git-lfs#3870]
I am working on updating the upstream Debian git-lfs package.  #3825 added a new dependency on `github.com/google/slothfs` only to use a tiny part of it.  SlothFS is not currently packaged in Debian and at a glance is not trivial to package.  Is there any chance that another, more lightweight alternative exists for this?  Also tagging @kupson on this since they wrote the original PR.

**Comment by bk2204** [comment]
Hey,

I'm definitely open to using something else and would be fine with an alternative.  I'm having a bit of trouble finding a suitable alternative, though, since there are very few Netscape cookie jar libraries and most of them are no longer maintained.

If you can find one, we can switch to it, and I'd even be willing to consider a 2.9.1 release.

**Comment by ssgelm** [comment]
I'll dig around more but at first glance it's possible this would work: https://github.com/juju/persistent-cookiejar

**Comment by ssgelm** [comment]
Oh... that just serializes in JSON so it won't help here.

**Comment by bk2204** [comment]
> Oh... that just serializes in JSON so it won't help here.

Yeah, I looked at that one, and it seemed like a great option except for the JSON format.

**Comment by ssgelm** [comment]
I spiked out a parser for cookiejar files: https://github.com/ssgelm/cookiejarparser/blob/master/cookiejarparser.go.  If you think it's reasonable I will write tests for it.  What do you think?

**Comment by bk2204** [comment]
Seems reasonable to me.

**Comment by ssgelm** [comment]
OK cool.  My cursory testing indicates that it works right.  I'll write up some tests then PR a change to git-lfs to use it.

**Comment by ssgelm** [comment]
Oh, there's also this: https://github.com/kosh04/cookiedisk.  What do you think about using it?

**Comment by bk2204** [comment]
That seems like it should be fine as well.

**Comment by ssgelm** [comment]
Implemented in #3886.  I tried kosh04/cookiedisk and it didn't actually do the harder part of creating the golang cookiejar so I went with the one I wrote.

**Comment by ssgelm** [comment]
@bk2204 Any interest in releasing 2.9.1?  Alternatively I can package 2.9.0 for debian with the patch from #3886.  What would you prefer?

**Comment by bk2204** [comment]
I will do a 2.9.1, but it won't be until at least later this week.  You're welcome to do whatever is most convenient for you.
