### ISSUE TITLE
This works for me also.

### ISSUE THREAD

**Issue by Moscow12** [git-lfs/git-lfs#3872]
hi 
i had the same problem
you might change something in the prime without pushing it to hub
git pull (in prime )
git commit -a (in prime )
git push hub master (in prime )

then

git pull (in local)
git commit  -a (in local)
git push (in local)

it worked for me

_Originally posted by @moqiseh in https://github.com/git-lfs/git-lfs/issues/1114#issuecomment-284139674_

**Comment by bk2204** [comment]
Hey,

It's not clear to me what you're asking for here.  Could you describe the issue you're seeing in a bit more detail?

**Comment by bk2204** [comment]
Hey,

I'm going to close this issue, since it isn't clear what you're asking for.
