### ISSUE TITLE
The Git LFS home page still has 2.8.0 download link even though 2.9.0 has been released 

### ISSUE THREAD

**Issue by gdlxn-ibm** [git-lfs/git-lfs#3879]
The [Git LFS home page](https://git-lfs.github.com/) still includes a 2.8.0 download link, even though the [Git LFS download page](https://github.com/git-lfs/git-lfs/releases/tag/v2.9.0) shows the latest release as 2.9.0.  I would think that the download link on the Git LFS home page should be updated to 2.9.0.

**Comment by bk2204** [comment]
Thanks for pointing this out; I forgot that step when doing our release process.  I've kicked off a commit to update that, and it should be fixed shortly.
