### ISSUE TITLE
git lfs migrate export: any downsides to marking migrated-out files as text?

### ISSUE THREAD

**Issue by benblo** [git-lfs/git-lfs#3909]
So, when using `migrate export` (awesome tool btw!), basically the pattern from `--include` is appended to .gitattributes to counter the LFS-tracking patterns, [like so](https://github.com/git-lfs/git-lfs/issues/3238#issuecomment-419914142):
> *.pdf filter=lfs diff=lfs merge=lfs -text
> ***.pdf -filter -diff -merge=lfs text**

_Side-note: IMO it would be nice to add a migration comment to that line, like:_
> *.pdf -filter -diff -merge=lfs text    **# injected by git lfs migrate export**

\
In my case I used `git lfs migrate export --include="*" --everything` to migrate out of LFS entirely, so I ended up with this line (which btw looks different from the comment I linked above, I guess the pattern changed - I'm on git 2.24.0)
> &ast; text !filter !merge !diff

... that seems brutal 😄 ! Isn't there any side-effects to marking large binaries (or here, everything!) as text? Like git trying to diff them as text instead of blobs or whatever?

**Comment by bk2204** [comment]
Hey,

The exported code should use the `!` to unset the attributes so that they take their default values, so that it's as if nobody set the `filter`, `merge`, or `diff` options at all.  This differs from `-`, which sets them to `false`.  The change to handle that came in with Git LFS 2.5.0, so the comment you linked to is now outdated.

If you're working with large binaries, leaving them as non-text is probably the right thing to do, but you can certainly set a different value if your contents are actually large text files.  Setting the file to be text affects line ending and encoding support and whether Git produces a binary diff or a text-based diff

**Comment by benblo** [comment]
> The exported code should use the `!` to unset the attributes so that they take their default values, so that it's as if nobody set the `filter`, `merge`, or `diff` options at all. This differs from `-`, which sets them to `false`. The change to handle that came in with Git LFS 2.5.0, so the comment you linked to is now outdated.

Ah, thanks for the clarification, I was wondering about `!` vs`-` .
In that case, why doesn't `migrate export` only set 
> &ast; !filter !merge !diff

instead of 

> &ast; **text** !filter !merge !diff

?
If it's just about clearing attributes, why touch the textness at all?

**Comment by bk2204** [comment]
You're right,we probably don't want to set the textness of the files in this case.  I'll open a PR to set the `text` attribute to unspecified just like we do with the others.

**Comment by feinstein** [comment]
@bk2204 why don't you just delete the .gitatrributes entries? Why do we need the `! ` in order to reset them?

**Comment by bk2204** [comment]
In some cases, there can be overlapping patterns where some earlier patterns mark a file in a certain way and then later ones override it.  If you've used the `--include` option, then resetting them is required for correct behavior in these cases.

**Comment by feinstein** [comment]
Can I delete the file then after everyone has pulled the version with the overrides?

Also, where's is documented how the `!` works?

**Comment by bk2204** [comment]
Maybe.  If the patterns contain only files that disable LFS and their binariness is also correctly detected automatically, then yes.  Otherwise, no.  The behavior of `.gitattributes` is documented in the `gitattributes(5)` manual page.
