### ISSUE TITLE
git local clone failed

### ISSUE THREAD

**Issue by nhatkhai** [git-lfs/git-lfs#3914]
```sh
mkdir test
git init
git lfs track *.pdf
git add ngspice-manual.pdf
git commit -m "test"

cd ..
git clone test test2
```

The failure occurred in the last command:
```
(488)$ git clone test test2
Cloning into 'test2'...
done.
Downloading ngspice-manual.pdf (3.2 MB)
Error downloading object: ngspice-manual.pdf (eb4de49): Smudge error: Error downloading ngspice-manual.pdf (eb4de49c0ab6870cafe4cb412179420d89d97872aafbd2fd0fb16554d5451925): batch request: ssh: Could not resolve hostname c: Name or service not known: exit status 255

Errors logged to C:\projects\git\test2\.git\lfs\logs\20191112T144004.7574523.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: ngspice-manual.pdf: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

```

**Comment by nhatkhai** [comment]
Git clone naturally support clone from the local folder as well as via https or ssh. In the cause of the repo that totally local, git clone fail on local repo that has lfs files.

**Comment by bk2204** [comment]
Hey,

Currently, the only form of local clone that's supported is one using an absolute file URL, with `:` escaped as `%3a` if necessary.  We are aware that using local paths is desirable, and it's something we're already tracking.

The problem on Windows is distinguishing a fully qualified local path from an SSH-style remote, since they share the same syntax (`C` could be an SSH host alias, and `\` is allowed in Unix paths as a normal character).

**Comment by nhatkhai** [comment]
I think lucky that Windows only use 1 letter before the colon. So I would think it would be not that hard to do.

**Comment by nhatkhai** [comment]
As of now. What is the work around in my example to make it work? 
Case1) IF I cannot turn of my system LFS hooks ?
Case2) Now turn off the system LFS. Then what next in order to have it work in test2 folder ?

**Comment by bk2204** [comment]
It is possible to specify your remote as an absolute file URL.  So you could say `git clone file:///C%3a/projects/git/test test2`, which should work, assuming you're using 2.9.0.
