### ISSUE TITLE
after git lfs migrate: “Unable to find source for object” when trying to push everything

### ISSUE THREAD

**Issue by ManIkWeet** [git-lfs/git-lfs#3923]
I have an old repository with a decent amount of binary objects.

This repository has had LFS enabled in the past, this has since been disabled and the LFS files are no longer available. Previous .gitattributes contained:
```
*.chm filter=lfs diff=lfs merge=lfs -text
*.pdf filter=lfs diff=lfs merge=lfs -text
*.rte filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
```
I want to migrate this repository to use LFS again, I tried the following:
```
git clone --mirror https://myrepourl MyFolder
cd MyFolder
git lfs migrate import --include="*.pdf,*.chm,*.exe,*.dll,*.[wW]ire[fF]rame[xX],*.bdsarchive,*.[dD][wW][gG],*.rfa,*.rte,*.rft,*.[sS][lL][dD],*.[sS][lL][bB],*.[bB][mM][pP],*.zip,*.ico,*.[pP]rofile[sS]et,*.[lL][iI][bB],*.jpg,*.png,*.docx,*.avi,*.[pP]rofile[sS]et[xX],*.gif,*.idx,*.[nN][tT][fF],*.[hH][lL][pP],*.xls,*.xlsx" --everything --verbose
git push -f --mirror
```
The push fails though, giving the following output:
```
Unable to find source for object 039b6195322b1c187185d9a08470a2f9442aae1153808e12f719b5a9fd52c7ac (try running git lfs fetch --all)
Uploading LFS objects:  99% (9768/9838), 582 MB | 646 KB/s, done.
error: failed to push some refs to 'https://myrepourl'
```
Why is it missing source files when I just migrated it?
How can I fix this issue?
Obviously, the suggested solution doesn't work as the remote server does not have the files generated by migration...

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Did you do a `git migrate export` before migrating it again or use a fresh copy that's never used Git LFS?  If not, the old LFS references are probably still in the repository, which is probably why you're seeing this.

You can find any matching file with `git log -p -S039b6195322b1c187185d9a08470a2f9442aae1153808e12f719b5a9fd52c7ac` in the original repository to see if the original LFS pointer file is there.  If it is, then you have two choices: you can remove that LFS pointer from the history, or you can set the `lfs.allowincompletepush` option and push it anyway, knowing that the repository will be missing history.

**Comment by ManIkWeet** [comment]
I did not do a `git migrate export` beforehand, does this command work when the original LFS source is no longer available?

Your `git log` seems very useful, wish I knew about it sooner.
I will have to try this tomorrow if the export doesn't help.

**Comment by bk2204** [comment]
In general, Git LFS wants to push all the objects from the history that the remote doesn't have, so if you're lacking some of those objects, it will stop and complain.  That's why `lfs.allowincompletepush` exists: so that you can bypass things in cases where you've lost items from your history.

**Comment by ManIkWeet** [comment]
Setting lfs.allowincompletepush was the simplest solution, thank you for your time!
