### ISSUE TITLE
Unable to launch git-lfs-2.9.1 on MacOS Catalina

### ISSUE THREAD

**Issue by isaki** [git-lfs/git-lfs#3933]
It seems that the 2.9.1 build (and possibly older) for macOS is not signed properly.

![image](https://user-images.githubusercontent.com/10616227/69646740-547d5600-1036-11ea-9f1b-28fa28c72a35.png)

**Comment by bk2204** [comment]
Hey,

We're already tracking this as #3714, which has a workaround in it.  We don't currently have an Apple developer certificate, although one has been requested.

Until we acquire the certificate and start signing builds, you can either apply the workaround in #3714 (by invoking `xattr -d com.apple.quarantine` on the file) or use the version from Homebrew, which should not have this problem.

**Comment by isaki** [comment]
I missed the previous issue; sorry for the duplicate and thanks for the workaround.

**Comment by lasantha57** [comment]
This worked for me!
https://github.com/git-lfs/git-lfs/issues/3714#issuecomment-602904431
