### ISSUE TITLE
Error message: "Not in a git repository". LFS issue on a virtual machine.

### ISSUE THREAD

**Issue by RolandDevOps** [git-lfs/git-lfs#3934]
1. Create a Virtual Machine in Azure (used a preconfigured one including VS2019)
2. Installed GIT LFS
3. Istalled an AzureDevOps build agent.
4. Started a AzureDevOps build definition which clones a git repo including lfs files.
5. The following error message show up: "Not in a git repository"
-------------------------------------------------------------
##[command]git lfs install --local
##[debug]Starting process:
##[debug]  File name: 'F:\agent1\externals\git\cmd\git.exe'
##[debug]  Arguments: 'lfs install --local'
##[debug]  Working directory: 'F:\agent1\_work\1\s'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name: utf-8 ; code page: '65001'
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]OOM score adjustment is Linux-only.
##[debug]Process started with process id 7036, waiting for process exit.
**_Not in a git repository._**
##[debug]STDOUT/STDERR stream read finished.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Exited process 7036 with exit code 128
##[debug]Finished process 7036 with exit code 128, and elapsed time 00:00:00.1855160.
##[error]Git-lfs installation failed with exit code: 128
------------------------------------------------------------

If i do the same with the installed mingw64\bin\git.exe it is working.
Any ideas why this is happening?

**Comment by bk2204** [comment]
Hey,

First, are you actually in a repository when you're invoking `git lfs install --local`?  When you use `--local`, you must be in an existing repository.

If you're sure you're in a repository, can you run the command with `GIT_TRACE=1` and include the output, as well as the output of running `git lfs env`?

**Comment by RolandDevOps** [comment]
Hi,

thank you for following up. Here is requested info:
Yes, the command is used in an existing repository.
**Here are the traces:**
F:\agent1\_work\1\s>F:\agent1\externals\git\cmd\git.exe init
11:06:28.847212 exec-cmd.c:236          trace: resolved executable dir: F:/agent1/externals/git/mingw64/bin
11:06:28.847212 git.c:419               trace: built-in: git init
Initialized empty Git repository in F:/agent1/_work/1/s/.git/

F:\agent1\_work\1\s>F:\agent1\externals\git\cmd\git.exe lfs install --local
11:06:47.506054 exec-cmd.c:236          trace: resolved executable dir: F:/agent1/externals/git/mingw64/bin
11:06:47.521683 git.c:676               trace: exec: git-lfs install --local
11:06:47.521683 run-command.c:643       trace: run_command: git-lfs install --local
11:06:47.550347 trace git-lfs: exec: git 'version'
Not in a git repository.

**And here the result of "git lfs env":**
F:\agent1\_work\1\s>F:\agent1\externals\git\cmd\git.exe lfs env
11:09:55.158619 exec-cmd.c:236          trace: resolved executable dir: F:/agent1/externals/git/mingw64/bin
11:09:55.158619 git.c:676               trace: exec: git-lfs env
11:09:55.158619 run-command.c:643       trace: run_command: git-lfs env
11:09:55.194107 trace git-lfs: exec: git 'version'
git-lfs/2.9.1 (GitHub; windows amd64; go 1.12.7; git 7b479cc8)
git version 2.21.0.windows.1

11:09:55.270015 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
11:09:55.295270 trace git-lfs: Error loading current ref: Git can't resolve ref: "HEAD"
11:09:55.357167 trace git-lfs: exec: git 'config' '-l'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=F:/agent1/externals/git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_TRACE=1
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
11:09:55.471006 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
11:09:55.471006 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
11:09:55.471964 trace git-lfs: filepathfilter: accepting "tmp"

**Comment by bk2204** [comment]
Hey,

I think this may be fixed in the latest `master` with #3910, which will be included in 2.9.2.  Can you try with the artifacts built from that CI job for that PR and see if that version fixes the problem for you?

**Comment by RolandDevOps** [comment]
Hello,
yes i can confirm. Using these artifacts fixes the issue. Thank you very much for your help.
