### ISSUE TITLE
Invalid default value of lfs.concurrenttransfers

### ISSUE THREAD

**Issue by ganadist** [git-lfs/git-lfs#3948]
**Describe the bug**
On https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn#transfer-upload--download-settings , it described default value of `lfs.concurrenttransfers` is `8`
But actual implementation is `3`

**To Reproduce**
```
$ git lfs env    
git-lfs/2.9.0 (GitHub; linux amd64; go 1.13.1)
git version 2.24.0

blahblah
ConcurrentTransfers=3
```

**Expected behavior**
```
$ git lfs env    
git-lfs/2.9.0 (GitHub; linux amd64; go 1.13.1)
git version 2.24.0

blahblah
ConcurrentTransfers=8
```

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**

Default value is defined on https://github.com/git-lfs/git-lfs/blob/50fb2a0d3ada46e485b30c84ca1999154afe745e/lfshttp/client.go#L393

But initial value is set on  https://github.com/git-lfs/git-lfs/blob/50fb2a0d3ada46e485b30c84ca1999154afe745e/lfshttp/client.go#L86

And `git lfs env` just shows from Client instance, so initial value must be set to `8`, not `0`

**Comment by bk2204** [comment]
Hey,

Yeah, it does look like we missed a spot when we bumped this value to 8.  And moreover, we're using 8, but reporting 3.  Thanks for pointing this out and sending a patch.
