### ISSUE TITLE
Problem with install no Button show in GitKraken

### ISSUE THREAD

**Issue by ExtremEShiro** [git-lfs/git-lfs#3952]
Hello,

I have installed the GIT LFS installer with Windows.

After I started GitKraken and wanted to link a project, but I didn't see any GIT LFS in the preferences. Maybe someone had an idea?

Screenshot: https://gyazo.com/6f2f004c28bbc79ea4995d32f2d586d0

Thanks in advance

**Comment by bk2204** [comment]
Hey,

I'm not sure why this would be happening.  I don't think any of the current maintainers use Windows or GitKraken, so I'm not sure why it wouldn't be finding Git LFS.  You could try making sure that you can run `git lfs env` from a CMD or PowerShell window to make sure it's in the PATH.  Failing that, your best bet is to look for the GitKraken documentation or reach out to the GitKraken folks and see if they can help you out.
