### ISSUE TITLE
Smudge error: EOF after updating from Git LFS v2.8.0 to Git LFS v2.9.1

### ISSUE THREAD

**Issue by Broxzier** [git-lfs/git-lfs#3956]
**Describe the bug**
Downloading of files from local LFS server gives back a smudge error after having updated from Git LFS v2.8.0 to Git LFS v2.9.1. Nothing on the server has changed (not even rebooted) and it worked fine before. This is the error we're getting:

**Smudge error: Error downloading File (hash): EOF**

Which as far as I understand suggests that the connection to the server does not work. With `GIT_TRACE=1` I do get this log:

```
13:27:27.679807 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:27:27.683302 git.c:439               trace: built-in: git reset --hard origin/develop
13:27:29.638185 run-command.c:663       trace: run_command: 'git-lfs filter-process'
13:27:29.720054 trace git-lfs: exec: git 'version'
13:27:30.037005 trace git-lfs: exec: git 'config' '-l'
13:27:30.069462 trace git-lfs: Install hook: pre-push, force=false, path=C:\PathToRepo\.git\hooks\pre-push, upgrading...
13:27:30.071486 trace git-lfs: Install hook: post-checkout, force=false, path=C:\PathToRepo\.git\hooks\post-checkout, upgrading...
13:27:30.072496 trace git-lfs: Install hook: post-commit, force=false, path=C:\PathToRepo\.git\hooks\post-commit, upgrading...
13:27:30.073993 trace git-lfs: Install hook: post-merge, force=false, path=C:\PathToRepo\.git\hooks\post-merge, upgrading...
13:27:30.075491 trace git-lfs: Initialize filter-process
13:27:30.075978 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
13:27:30.112160 trace git-lfs: tq: running as batched queue, batch size of 100
13:27:30.113174 trace git-lfs: filepathfilter: accepting "OneLargeFile"
13:27:30.127036 trace git-lfs: tq: sending batch of size 1
13:27:30.127139 trace git-lfs: tq: starting transfer adapter "lfs-standalone-file"
13:27:30.528973 trace git-lfs: xfer[git-lfs]: error creating handler: no valid file:// URLs found
13:27:30.536451 trace git-lfs: filepathfilter: accepting "OneLargeFile"
Downloading OneLargeFile (76 KB)
13:27:30.536963 trace git-lfs: tq: running as batched queue, batch size of 100
13:27:30.536963 trace git-lfs: tq: sending batch of size 1
13:27:30.537444 trace git-lfs: tq: starting transfer adapter "lfs-standalone-file"
13:27:30.958412 trace git-lfs: xfer[git-lfs]: error creating handler: no valid file:// URLs found
Error downloading object: OneLargeFile (b19ba81): Smudge error: Error downloading OneLargeFile (b19ba81c208a915c4c3d5f300bad34ec2396efc02908ad4b47dbe1248ea82096): EOF
```

**error creating handler:  no valid file:// URLs found** seemed odd, this was never an issue before. I tried changing the path to our repository to use the file:// protocol, but unfortunately to no avail.

One of my colleagues was still able to checkout new commits without problems after the update. When comparing their git config files with others, we found that their origin was set up with backslashes instead of forward slashes. When we tried that on the machines where it doesn't work anymore, the error was gone and we could download files fine once again. I expect there to still be problems with submodules that use forward slashes in their paths, but I have not tested this.

Here's a log from running the exact same git checkout command but with the remote changed to use backslashes and with `GIT_TRACE=1` gives me this:

```
13:29:39.598993 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:29:39.602487 git.c:439               trace: built-in: git reset --hard origin/develop
13:29:40.960310 run-command.c:663       trace: run_command: 'git-lfs filter-process'
13:29:41.038185 trace git-lfs: exec: git 'version'
13:29:41.341489 trace git-lfs: exec: git 'config' '-l'
13:29:41.375107 trace git-lfs: Install hook: pre-push, force=false, path=C:\PathToRepo\.git\hooks\pre-push, upgrading...
13:29:41.377085 trace git-lfs: Install hook: post-checkout, force=false, path=C:\PathToRepo\.git\hooks\post-checkout, upgrading...
13:29:41.378582 trace git-lfs: Install hook: post-commit, force=false, path=C:\PathToRepo\.git\hooks\post-commit, upgrading...
13:29:41.380081 trace git-lfs: Install hook: post-merge, force=false, path=C:\PathToRepo\.git\hooks\post-merge, upgrading...
13:29:41.381078 trace git-lfs: Initialize filter-process
13:29:41.381578 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
13:29:41.418020 trace git-lfs: tq: running as batched queue, batch size of 100
13:29:41.419018 trace git-lfs: filepathfilter: accepting "OneLargeFile"
13:29:41.432995 trace git-lfs: tq: sending batch of size 1
13:29:41.433512 trace git-lfs: api: batch 1 files
warning: current Git remote contains credentials
13:29:41.444989 trace git-lfs: HTTP: POST http://LOGINSTRING@OURLFSSERVER/objects/batch
13:29:41.597842 trace git-lfs: HTTP: 200
13:29:41.598345 trace git-lfs: HTTP: {"objects":[{"oid":"b19ba81c208a915c4c3d5f300bad34ec2396efc02908ad4b47dbe1248ea82096","size":75520,"actions":{"download":{"href":"http://OURLFSSERVER/objects/b19ba81c208a915c4c3d5f300bad34ec2396efc02908ad4b47dbe1248ea82096","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"}}}]}

13:29:41.600339 trace git-lfs: tq: starting transfer adapter "basic"
warning: current Git remote contains credentials
13:29:41.602335 trace git-lfs: HTTP: GET http://OURLFSSERVER/objects/b19ba81c208a915c4c3d5f300bad34ec2396efc02908ad4b47dbe1248ea82096
13:29:41.624865 trace git-lfs: HTTP: 200
13:29:41.671289 trace git-lfs: filepathfilter: accepting "OneLargeFile"
13:29:41.710726 run-command.c:43        trace: run_command: running exit handler for pid 9684
13:29:41.711225 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
13:29:41.711737 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
13:29:41.712224 trace git-lfs: filepathfilter: accepting "tmp"
```

**To Reproduce**
1. Clone a repository from a network drive using a path like `//MACHINE-NAME/SharedFolder/Git/Repository.git`
2. Checkout a branch for which LFS objects need to be downloaded
3. Be greeted by the EOL error.
4. Change the origin url to `\\\\MACHINE-NAME\\SharedFolder\\Git\\Repository.git` and try again
5. No error - successful checkout! But this workaround seems silly and would require changing of submodule paths.

**Expected behavior**
Git LFS downloads the LFS objects on checkout without problems, no matter if the path to origin uses forward slashes or backslashes.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
```
git-lfs/2.9.1 (GitHub; windows amd64; go 1.12.7; git 7b479cc8)              
git version 2.24.1.windows.2                                                
                                                                            
Endpoint=http://LOGINSTRING@OURLFSSERVER/ (auth=none)           
LocalWorkingDir=C:\Development\DrivingSim                                   
LocalGitDir=C:\Development\DrivingSim\.git                                  
LocalGitStorageDir=C:\Development\DrivingSim\.git                           
LocalMediaDir=C:\Development\DrivingSim\.git\lfs\objects                    
LocalReferenceDirs=                                                         
TempDir=C:\Development\DrivingSim\.git\lfs\tmp                              
ConcurrentTransfers=3                                                       
TusTransfers=false                                                          
BasicTransfersOnly=false                                                    
SkipDownloadErrors=false                                                    
FetchRecentAlways=false                                                     
FetchRecentRefsDays=7                                                       
FetchRecentCommitsDays=0                                                    
FetchRecentRefsIncludeRemotes=true                                          
PruneOffsetDays=3                                                           
PruneVerifyRemoteAlways=false                                               
PruneRemoteName=origin                                                      
LfsStorageDir=C:\Development\DrivingSim\.git\lfs                            
AccessDownload=none                                                         
AccessUpload=none                                                           
DownloadTransfers=basic,lfs-standalone-file                                 
UploadTransfers=basic,lfs-standalone-file                                   
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core                 
git config filter.lfs.process = "git-lfs filter-process"                    
git config filter.lfs.smudge = "git-lfs smudge -- %f"                       
git config filter.lfs.clean = "git-lfs clean -- %f"                         
```

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  I have a few questions so I can understand what's going on here.  Are you using `lfs.url` or some other way of specifying the LFS URL independently, or are you relying on Git LFS to automatically intuit the URL?

I think part of what you're seeing is that in 2.9.0, Git LFS learned support for file URLs, but unfortunately there was a long-standing bug that prevented it from honoring `lfs.url` properly.  That was fixed by #3905, which will be available in Git LFS 2.10.  You can try downloading the CI artifacts from the latest `master` build, which should solve the problem if you are using `lfs.url`.

**Comment by Broxzier** [comment]
Hi bk2204, thanks for your reply.

> Are you using `lfs.url` or some other way of specifying the LFS URL independently, or are you relying on Git LFS to automatically intuit the URL?

Yes, we're using `lifs.url` which is set in our global `.gitconfig` files:
```
[lfs]
	url = http://username:password@1.2.3.4:5678/
```

Do I understand correctly that because the repository's remote path starts with `//`, it added the `file:` prefix, but when it starts with `\\\\` it correctly uses `http:`?

> You can try downloading the CI artifacts from the latest master build, which should solve the problem if you are using `lfs.url`.

I've downloaded the [Windows build artifacts from here](https://github.com/git-lfs/git-lfs/commit/65e90acbe3ce6206d4f2c73c8acf8e79ec526bc0/checks?check_suite_id=355757138) (from 7 days ago), and after replacing git-lfs.exe doing a fresh checkout was successful!

**Comment by bk2204** [comment]
> Do I understand correctly that because the repository's remote path starts with `//`, it added the `file:` prefix, but when it starts with `\\\\` it correctly uses `http:`?

We have some code to recognize local paths that was incomplete in the 2.9 series but is now fixed.  Anything starting with `/` is considered an absolute path and is therefore rewritten into a file URL internally, and in the 2.9 series if a custom transfer agent (like the one for file URLs) is used, `lfs.url` is ignored.  So, essentially, yes. 

In `master`, however, we're doing two things: first, handling the custom transfer case correctly, and second, handling anything that doesn't look like a URL as a local path.  Those together make things work.
