### ISSUE TITLE
git-lfs hang over

### ISSUE THREAD

**Issue by Abbyyan** [git-lfs/git-lfs#3957]
git clone pid strace
```shell
Process 27649 attached
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, ptr=0x2c307d}} ---
rt_sigreturn()                          = 0
read(6, 0x7ffc36dae050, 4)              = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=2895997, p
```

git-lfs strace pid
```shell
Process 28006 attached
[ Process PID=28006 runs in 32 bit mode. ]
futex(0x88b982c, FUTEX_WAIT_PRIVATE, 0, NULL^CProcess 28006 detached
 <detached ...>
```
and it hangs for a while withoutget files. How can i detect what's wrong with it ? Thanks a lot .

**Comment by Abbyyan** [comment]
Here is my git version.
`git-lfs --version` -> `git-lfs/2.7.1 (GitHub; linux 386; go 1.12; git 6b7fb6e3)`
`git version 2.17.0`

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you run the clone with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include the output as an attachment?

**Comment by Abbyyan** [comment]
> Hey,
> 
> Sorry to hear you're having trouble. Can you run the clone with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include the output as an attachment?

Enter the similar problem again. Should I run it with `git clone url GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` where url is the repo address?

**Comment by Abbyyan** [comment]
> > Hey,
> > Sorry to hear you're having trouble. Can you run the clone with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include the output as an attachment?
> 
> Enter the similar problem again. Should I run it with `git clone url GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` where url is the repo address?

Or , should i `export GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 `, and then run the `git clone url` ?

**Comment by chrisd8088** [comment]
Generally you would either set the environment variables before the command, e.g.:
```
GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone <url>
```
which will just set them for the duration of that one `git clone` command.

Or, if you don't mind setting them more permanently, you can do as you mentioned:
```
export GIT_TRACE=1
export GIT_TRANSFER_TRACE=1
export GIT_CURL_VERBOSE=1
git curl <url>
```
but then you would get diagnostic output on *every* subsequent `git` command, until you unset the variables.  So the former method is probably sufficient.

**Comment by Abbyyan** [comment]
I've tried this and it get such error and interrupt early. 

```shell
remote: Finding sources: 100% (125576/125576)
20:05:02.965572 run-command.c:640       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 23816 on VM_6_151_centos' --check-self-contained-and-connected --pack_header=2,125576
20:05:02.967051 git.c:344               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 23816 on VM_6_151_centos' --check-self-contained-and-connected --pack_header=2,125576
* Curl_http_done: called premature == 0 95.20 MiB | 31.73 MiB/s   
* Connection #0 to host git.code.oa.com left intact
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
I've found some solutions and it seems like may be the `http .postBuffer` is not big enough?
https://kb.kutu66.com/git/post_1056664

**Comment by Abbyyan** [comment]
It occurs sometimes, especially when i use multiprocess to clone the repo.  And i find the default config of `http.postBuffer` is 1M. Is the `http.postBuffer` will result in  the git-lfs hang?

**Comment by chrisd8088** [comment]
This does sound like an issue caused by either a slow internet connection and/or a large repository.

A number of sources suggest trying a shallow clone (sometimes referred to incorrectly as a partial clone; that's a different thing).  See, for instance:

https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed/53068021#53068021

Another approach might be to try SSH instead of HTTP, if your Git server supports SSH.

**Comment by Abbyyan** [comment]
> https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed/53068021#53068021

I'll try this . Thanks a lot !

**Comment by Abbyyan** [comment]
> > https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed/53068021#53068021
> 
> I'll try this . Thanks a lot !

It works . Thanks a lot.
