### ISSUE TITLE
Error: Failed to call git rev-parse --git-dir: exit status 128 on ubuntu 18.04

### ISSUE THREAD

**Issue by kouohhashi** [git-lfs/git-lfs#3964]
HI, I'm trying to install git-lfs on my ubuntu server but I couldn't.

my environment:
```
ubuntu: 18.04
git: 2.17.1
```

I downloaded git-lfs-linux-amd64-v2.9.2.tar.gz and ran ./install.sh command.
I also tried to install git-lfs through apt package.

But I got same error 
```
Error: Failed to call git rev-parse --git-dir: exit status 128 
Git LFS initialized.
```

How can I fix this problem?

Could you give me a hint?

Thanks in advance.

**Comment by sekigh** [comment]
I have the same problem as kouohhashi during git-lsf installation. I followed the instructions from https://github.com/git-lfs/git-lfs/wiki/Installation;

	1. curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
	2. sudo apt-get install git-lfs

and got Error: Failed to call git rev-parse --git-dir: exit status 128 during procedure 2.

my environment is also; 

ubuntu: 18.04
git: 2.17.1

Is there any solution ?

**Comment by Frankz** [comment]
Hi! I have same issue following this steps https://help.github.com/es/github/managing-large-files/installing-git-large-file-storage for linux 

```
Error: Failed to call git rev-parse --git-dir: exit status 128
Git LFS initialized.
```


OS: WSL v2 - Ubuntu - 18.04.2 LTS (Bionic Beaver)
Git: 2.17.1

**Comment by Frankz** [comment]
> Hi! I have same issue following this steps https://help.github.com/es/github/managing-large-files/installing-git-large-file-storage for linux
> 
> ```
> Error: Failed to call git rev-parse --git-dir: exit status 128
> Git LFS initialized.
> ```
> 
> OS: WSL v2 - Ubuntu - 18.04.2 LTS (Bionic Beaver)
> Git: 2.17.1

Hi again, sorry, as now I can see, the error message appear when I execute "git lfs install" over a non-versioned directory

kind regards!

**Comment by left4taco** [comment]
The same error here

**Comment by sekigh** [comment]
I confirm that the error shows up when I run git lfs install in the directory where no .git exsits. I want to git clone a new repository to a local directory from a remote and apply lfs to that directory. Is first do "git clone" and then "git lfs install --local" in that directory the right order to follow ?

**Comment by bk2204** [comment]
Hey,

It looks like this is a little bit of fall out from our change to make Git LFS work with 2.25, which will change the way it deals with missing repostories.  You can run `git lfs install --skip-repo`, or just ignore the message: it's harmless.

**Comment by SmallAndSoft** [comment]
Same problem on Debian Buster ARM64.

**Comment by bk2204** [comment]
As you may have noticed, it's already been fixed, and it will be in 2.10.  I'm sure it happens on all platforms.

**Comment by SmallAndSoft** [comment]
Waiting on 2.10 then. Meanwhile can not install Urbit because of this.

**Comment by bk2204** [comment]
The package that produces the error should function just fine.  The message is cosmetic and harmless.

**Comment by philBrown** [comment]
Running git 2.18.0 and still seeing this error

**Comment by bk2204** [comment]
Hey,

The error message comes from Git LFS 2.9 and upgrading to Git LFS 2.10 or newer should fix things.  The version of Git isn't important here.

**Comment by leonidaa** [comment]
https://stackoverflow.com/questions/56283415/how-do-i-clone-a-repository-that-includes-git-lfs-files
git lfs install does two things: it sets up hooks in your local repository, and it adjusts your global (i.e., user-specific) configuration to contain the filter commands necessary for Git LFS to work properly.........

**Comment by PasaOpasen** [comment]
Got same error, but I forgot to initialize the repo

**Comment by ZyCodeR-fb** [comment]
git lfs install --skip-repo
