### ISSUE TITLE
Local clone with LFS file on Windows 10 fails with "smudge filter lfs failed"

### ISSUE THREAD

**Issue by gdlxn-ibm** [git-lfs/git-lfs#3965]
I have a local bare repository on Windows 10 that contains a LFS file.  I ran the following to clone the repository to a new non-bare repository:

```
c:\r2g-wd-git-issue-103>git clone .\git-issue-103.git .\test.git
Cloning into '.\test.git'...
done.
Downloading git-issue-103-component/200MiB (210 MB)
Error downloading object: git-issue-103-component/200MiB (207cd30): Smudge error: Error downloading git-issue-103-component/200MiB (207cd3008457d1eeca9d2613ddad88b8175a57a099b978b3b2683f2d42f5aed0): batch request: ssh: Could not resolve hostname c: Name or service not known: exit status 255

Errors logged to C:\r2g-wd-git-issue-103\test.git\.git\lfs\logs\20200102T080824.3428249.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: git-issue-103-component/200MiB: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

As you can see, the clone of the LFS file failed with `smudge filter lfs failed`.  From

```
Could not resolve hostname c: Name or service not known: exit status 255
```

It looks as though smudge isn't handling the Windows c: drive portion of the path correctly as it is taking it to be a hostname.

**Comment by bk2204** [comment]
Hey,

As of 2.9.0, we support local clones, but only with `file:///` URLs and on Windows, only with the drive colon escaped as `%3a`.  In `master`, we've added support for cloning plain file paths; before that, we treated that form of Windows path as an SSH URL.

The improvement came in with #3918 and will be in 2.10.

**Comment by gdlxn-ibm** [comment]
Brian, thanks for the update.  I had tried using `file:`, but I had syntax wrong.  After fixing the `file:` syntax and replacing the drive colon with %3a, the clone worked.
