### ISSUE TITLE
git lfs checkout path/to/file not as expected

### ISSUE THREAD

**Issue by howardlyliao** [git-lfs/git-lfs#3968]
Hi, I found the rule of filepathfilter.go has being changed.
git lfs checkout path/to/file.lib will being treated as
"\*\*/path/to/file.lib/\*\*"
and cause pattern not matching, thus specified lfs object will be rejected.

Ex: 
$GIT_TRACE=1 git lfs checkout  'path/to/file.lib'
16:57:41.048285 git.c:654               trace: exec: git-lfs checkout path/to/file.lib
16:57:41.048324 run-command.c:637       trace: run_command: git-lfs checkout path/to/file.lib
16:57:41.053878 trace git-lfs: exec: git 'version'
16:57:41.056726 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
16:57:41.058475 trace git-lfs: exec: git 'config' '-l'
16:57:41.060745 trace git-lfs: filepathfilter: rewrite "path/to/file.lib" as "\*\*/path/to/file.lib/\*\*"
....
....
16:57:41.077417 trace git-lfs: filepathfilter: rejecting "path/to/file.lib" via [path/to/file.lib]

Same thing also happen to:
git lfs pull --include=path/to/file.lib

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you say whether `path/to/file.lib` is a file or directory?

**Comment by howardlyliao** [comment]
Hi,  path/to/file.lib  is a file

**Comment by bk2204** [comment]
Hey,

I've done some testing here with my test repo, and I don't see this failure.  The "rejecting" message on the last line of your example output means that for some reason the path `path/to/file.lib` doesn't match the pattern you provided on the command line (`path/to/file.lib`).

In this case, they are literally the same, but I suspect in your real environment they're subtly different.  If you're sure they're not, can you provide a test repo where you see this and the full output of `git lfs env` so we can see what version you're using?

As for the rewrite messages, those are harmless because in the wildmatch implementation used by Git LFS, the patterns are equivalent.  It's a bug we've been wanting to fix, but it's subtly incompatible, so it will take until 3.0 to fix.

**Comment by howardlyliao** [comment]
Hi thank you for checking it. The path of the file I used was actually not path/to/file.lib  I manually replaced the file path in the log with path/to/file.lib because the original file path contains confidential information. I thought it's the rewrite message which cause it. Since it adds '/' in front and behind.

But your testing works fine. I'll try to create a repo with simple file path to test it. If it's still the same, I'll provide git lfs env. 

Thank you :)

**Comment by howardlyliao** [comment]
Hi I've done a simple test like path/to/file.lib  it did work as you said.
I then made another test with a folder name appears twice in the path and it failed:

$ls 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
$rm 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
$GIT_TRACE=1 git lfs checkout 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
15:57:13.934722 git.c:654               trace: exec: git-lfs checkout 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
15:57:13.934806 run-command.c:637       trace: run_command: git-lfs checkout 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
15:57:13.939577 trace git-lfs: exec: git 'version'
15:57:13.943042 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
15:57:13.944936 trace git-lfs: exec: git 'config' '-l'
15:57:13.948368 trace git-lfs: filepathfilter: rewrite "123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib" as "\*\*/123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib/\*\*"
15:57:13.951062 trace git-lfs: filepathfilter: rejecting ".gitattributes" via [123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib]
15:57:13.951113 trace git-lfs: filepathfilter: rejecting "123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib" via [123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib]
...
$ls 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
ls: cannot access 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib: No such file or directory

The information of git lfs env(I've replaced host name & path with xxx to hide confidential info):
$git lfs env
git-lfs/2.9.1 (GitHub; linux amd64; go 1.12.7; git 7b479cc8)
git version 2.18.0

Endpoint=http://xxxxxxxx:8080/test_lfs1.git/info/lfs (auth=none)
LocalWorkingDir=/xxx/xxxxxxxxxx/xxxxxxxx/simpleLFSTest/test_lfs1
LocalGitDir=/xxx/xxxxxxxxxx/xxxxxxxx/simpleLFSTest/test_lfs1/.git
LocalGitStorageDir=/xxx/xxxxxxxxxx/xxxxxxxx/simpleLFSTest/test_lfs1/.git
LocalMediaDir=/xxx/xxxxxxxxxx/xxxxxxxx/simpleLFSTest/test_lfs1/.git/lfs/objects
LocalReferenceDirs=
TempDir=/xxx/xxxxxxxxxx/xxxxxxxx/simpleLFSTest/test_lfs1/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/xxx/xxxxxxxxxx/xxxxxxxx/simpleLFSTest/test_lfs1/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Thanks, this is helpful as an example; I can now reproduce the issue.  I'll try to find a little time over the next few days to figure out what's going on here.

**Comment by howardlyliao** [comment]
I'm really happy to see v2.10.0 being released :) But from the release note I didn't see anything related to this issue. So I just tested it and this issue still exist in v2.10.0  
Any update for this issue?

**Comment by howardlyliao** [comment]
I've written a simple code to test the behavior of git-lfs/wildmatch:

package main
import (
	"github.com/git-lfs/wildmatch"
)

func main() {
	a := wildmatch.NewWildmatch(
		"\*\*/123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib/\*\*",
		wildmatch.SystemCase,
	)

	var included bool
	included = a.Match("123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib")
	println(included)
}

- For git-lfs/wildmatch v1.0.4:
The code above will print 'false'.
Change one of the '123456' to 'abc' will print 'true'.

- For git-lfs/wildmatch master branch HEAD:
The code above will print 'false'.
Change one of the '123456' to 'abc' will print 'false'.

- If I change the pattern into '123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib'
Both v1.0.4 and master HEAD will print 'true'.

It seems to be a problem when using \*\*, it searches from the end of the string towards the beginning trying find '123456' (greedily matches any number of directories ahead). It stops when it found the first 123456. Resulted the path using to match the rest of the pattern being 'Drmpu/Release/mpu_api.lib' but not 'mpu/platform/123456/Drmpu/Release/mpu_api.lib'.

I wonder if this is expected or the rule in the filepathfilter.go should adjust?

**Comment by bk2204** [comment]
No, we don't have any update on this issue.  In general, the wildmatch code is tricky and whoever is going to work on this is going to need to spend a decent amount of time picking through this.  It's my understanding that the extra pattern matching is needed for some cases and can be removed when the rest of the wildmatch code has been fixed to match.

**Comment by howardlyliao** [comment]
I see. Thank you. May I ask when git-lfs v3.0.0 might come out?

**Comment by bk2204** [comment]
We don't currently have plans for a v3.0.0 release.  This may indeed be possible to fix before then, but I don't know when we'll get time to look at it.  In general, if we can say the behavior matches Git's whereas it did not before, I think it's fine to call it a bugfix and not an incompatible change.

**Comment by howardlyliao** [comment]
I agree with you if the behavior matches Git's. So I ran some tests.
With normal file:  aaa/bbb/aaa/ddd/test.txt
And git-lfs file: 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib

with version:
git 2.18.0
git-lfs 2.9.1

- case 1:
//substring(with /) won't expand into greedy match
$git checkout ddd/test.txt
error: pathspec 'ddd/test.txt' did not match any file(s) known to git.

// but git-lfs will expand into greedy match
$git lfs checkout platform/123456/Drmpu/Release/mpu_api.lib
Checking out LFS objects: 100% (1/1), 20 B | 0 B/s, done.
$ls 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib

- case 2:
// specify complete path is as expected
$git checkout aaa/bbb/aaa/ddd/test.txt
$ls aaa/bbb/aaa/ddd/test.txt
aaa/bbb/aaa/ddd/test.txt

// as we already know it's not working in git-lfs due to greedy match
$git lfs checkout 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
[mtk10145@mtkslt0365 test_lfs1]$ls 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
ls: cannot access 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib: No such file or directory

- case 3:
// with just one \* , it is greedy to match anything
$git checkout \*ddd/test.txt
$ls aaa/bbb/aaa/ddd/test.txt
aaa/bbb/aaa/ddd/test.txt

// but for git-lfs with just one \* , it is not
$git lfs checkout \*/platform/123456/Drmpu/Release/mpu_api.lib
$ls 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
ls: cannot access 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib: No such file or directory

- case 4:
// with \*\*/ , Git still match anything
$git checkout \*\*/aaa/ddd/test.txt
$ls aaa/bbb/aaa/ddd/test.txt
aaa/bbb/aaa/ddd/test.txt

// with \*\*/ , git-lfs  has the same behavior
$git lfs checkout \*\*/platform/123456/Drmpu/Release/mpu_api.lib
Checking out LFS objects: 100% (1/1), 20 B | 0 B/s, done.
$ls 123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib
123456/mpu/platform/123456/Drmpu/Release/mpu_api.lib

From Git's behavior it's not treating the string as greedy match. Only when user add \* manually.

I checked the history of git-lfs which made the path string becomes greedy match:
https://github.com/git-lfs/git-lfs/commit/b2eac6ff62

It's for "rewrite more legacy patterns in terms of wildmatch". 
And the test cases in filepathfilter_test.go:
assertPatternMatch(t, "top/sub",
		"top/sub/filename.txt",
		"top/sub/",
		"top/sub",
		"root/top/sub/filename.txt",
		"root/top/sub/",
		"root/top/sub",
	)
clearly it expects it to be greedy match. So I wonder what are the legacy pattern?
Is it safe to remove greedy match to make git-lfs has the same behavior with Git's?

And thank you so much for your time to check this issue :)

**Comment by howardlyliao** [comment]
This issue has being fixed in v3.0.0
