### ISSUE TITLE
Wildcard patterns in NO_PROXY not handled

### ISSUE THREAD

**Issue by BalzGuenat** [git-lfs/git-lfs#3971]
**Describe the bug**
Rules in the environment variable `NO_PROXY` that contain wildcards, e.g. `*.company.com` are not handled correctly. Addresses that match these patterns are still trying to be accessed via proxy.

**To Reproduce**
1. Put yourself behind a proxy
2. Have a git server inside your network, i.e. accessible directly but *not* via the proxy, at an address like `git.company.com`
3. Set up the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables. In `NO_PROXY`, include the pattern `*.company.com`
4. Have a repo with an LFS file, hosted on said server
5. Pull or push changes to the LFS file

This will hang for a long time and eventually result in an error because the server is not accessible.

Unsetting `HTTP_PROXY` and `HTTPS_PROXY` will result in the server being contacted directly and the operation succeeding.

**Expected behavior**
Changes are synced, new LFS file is downloaded or uploaded.

**System environment**
OS: Windows 10
Git LFS executed via Git Bash

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.21.0.windows.1

Endpoint=https://code.company.com/tomas/tomas.git/info/lfs (auth=none)
  SSH=git@code.company.com:tomas/tomas.git
LocalWorkingDir=C:\Users\myusername\PycharmProjects\tomas
LocalGitDir=C:\Users\myusername\PycharmProjects\tomas\.git
LocalGitStorageDir=C:\Users\myusername\PycharmProjects\tomas\.git
LocalMediaDir=C:\Users\myusername\PycharmProjects\tomas\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\myusername\PycharmProjects\tomas\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\myusername\PycharmProjects\tomas\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

Whether to use a proxy or not is determined by `useProxy` here: https://github.com/git-lfs/git-lfs/blob/048948b1d42fe2c2cb89449ccf227aa39be67d36/lfshttp/proxy.go#L104.
It's evident that wildcards (`*`) are not handled.

The comment on that function indicates that this is an adaptation from the Go std lib.
The current version of the adapted function can be found [here](https://golang.org/src/vendor/golang.org/x/net/http/httpproxy/proxy.go?s=4195:4265#L175).
As you can see, it uses `ipMatchers` and `domainMatchers` to handle exactly this case.
They are initialized in the function [here](https://golang.org/src/vendor/golang.org/x/net/http/httpproxy/proxy.go?s=4195:4265#L210).

Looks like either LFS's reimplementation of `useProxy` is outdated or was always incomplete.

**Comment by bk2204** [comment]
Hey,

It does appear that we don't handle wildcards.  Unfortunately, there's no standard definition for these environment variables that we can test against, so it's hard to write an implementation that does everything everyone expects.

I'm working on a fix which I hope to have available for testing soon.

**Comment by bk2204** [comment]
I've opened #3972 to fix this issue.  Can you test with that version and verify that it works for you?  If you need a binary, you can wait until the CI job completes and grab one of the artifacts from it to get one built with those changes.

**Comment by BalzGuenat** [comment]
Wow, that was quick! I tested with the x32 Windows binary and it seems to work. Looking forward to see this in a release soon. Thanks a bunch!
