### ISSUE TITLE
Error: failed to fetch some objects - Can't pull lfs files from private repo

### ISSUE THREAD

**Issue by MrPieGaming503** [git-lfs/git-lfs#3975]
I am trying to pull lfs files from a private repo that my robotics team created, but I keep getting this error:

batch response: Not Found  0% (0/1), 0 B | 0 B/s
error: failed to fetch some objects from 'directory name here'

I'm running Windows 10 Pro and using GitKraken for managing Git on my computer. I'm using IntelliJ as my IDE.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
`Endpoint=https://github.com/FF503/SWAMP_Scouting.git/info/lfs (auth=none)
LocalWorkingDir=C:\Users\MrPieGaming\Google Drive\Coding Related\IntelliJProjects\Frog Force Projects\SWAMP_Scouting
LocalGitDir=C:\Users\MrPieGaming\Google Drive\Coding Related\IntelliJProjects\Frog Force Projects\SWAMP_Scouting\.git
LocalGitStorageDir=C:\Users\MrPieGaming\Google Drive\Coding Related\IntelliJProjects\Frog Force Projects\SWAMP_Scouting\.git
LocalMediaDir=C:\Users\MrPieGaming\Google Drive\Coding Related\IntelliJProjects\Frog Force Projects\SWAMP_Scouting\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\MrPieGaming\Google Drive\Coding Related\IntelliJProjects\Frog Force Projects\SWAMP_Scouting\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\MrPieGaming\Google Drive\Coding Related\IntelliJProjects\Frog Force Projects\SWAMP_Scouting\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"`

I don't know what's going on and I'm not very familiar with Git, so some help would be appreciated. Let me know if you need some more info from me.

**Comment by bk2204** [comment]
Hey,

Usually a Not Found error means that either the remote URL is wrong or you don't have access.  If you're trying to clone a repository with a username and password, you can try switching to a [personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) instead.  It's also possible that you have credentials stored in your credential manager that aren't correct for what you're trying to do or (for a token) don't give you access to private repos.

**Comment by PhillDev-coder256** [comment]
Hy,

It looks like you're having trouble [pulling LFS files](https://git-lfs.com/) from your private repository. Based on the error and the git lfs env output, it seems like the authentication is not correctly set up for accessing the LFS objects. Here's how you can try to resolve the issue:

**Check Git LFS Authentication:**
Ensure that your Git LFS is authenticated properly. Since the auth=none in your output suggests there's no authentication, you may need to configure your Git credentials.

**Run these commands in your terminal to configure your Git credentials:**

```
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=3600'
```

**Then, try to clone or pull again to make sure you enter the correct credentials.**
