### ISSUE TITLE
git push <tag> performance slowdown due to scanning the entire commit history for LFS objects

### ISSUE THREAD

**Issue by dghowlett** [git-lfs/git-lfs#3976]
**Describe the bug**
A git push of a tag ref for a git repos with a large history is extremely slow.  Runtimes up to 60 minutes are seen for larger histories vs what should be a couple seconds.  With GIT_TRACE=1 on, the runtime points to the git lfs pre-push call consuming the cycles.  From diving into the lfs code and adding more debug, the push of a tag is resulting in a git rev-list of the full history relative to the SHA id the tag points to.  For repos with large histories, this can result in LFS upload validation of 1000's of object ids.  Have verified same behavior with 2.5.1, 2.9.0, 2.9.2

**To Reproduce**
Take any repo with some history spanning LFS objects.  Push a git tag with GIT_TRACE on and you'll see it's attempting to iterate over all LFS objects found in the full history.  I would think for a tag push, it should be a no-op with no attempt to push Git LFS objects needed.

> git-lfs version
git-lfs/2.9.2 (unknown; linux amd64; go 1.13.5; git 0274d856)

> time git push origin testing_git_commit/15
Uploading LFS objects: 100% (8237/8237), 222 GB | 0 B/s, done 
Total 0 (delta 0), reused 0 (delta 0)0)
 * [new tag]             testing_git_commit/15 -> testing_git_commit/15
1155.190u 339.693s **24:42.09** 100.8%      0+0k 128+434407640io 1pf+0w

Above it took 25 minutes to push the tag.

With GIT_TRACE=1
> git-lfs version
git-lfs/2.9.2 (unknown; linux amd64; go 1.13.5; git 0274d856)

....
09:55:38.921966 trace git-lfs: exec: git 'version'
09:55:38.927648 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
09:55:38.932679 trace git-lfs: exec: git 'config' '-l'
09:55:38.942267 trace git-lfs: pre-push: refs/tags/testing_git_commit/14 ff7fe17b184a0bcfa3b383db456bd2a30bd37b5d refs/tags/testing_git_commit/14 0000000000000000000000000000000000000000
09:55:39.195240 trace git-lfs: tq: running as batched queue, batch size of 100
09:55:39.195443 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin
 --
09:55:55.927830 trace git-lfs: tq: sending batch of size 100
09:55:55.928307 trace git-lfs: api: batch 100 files
...
09:56:02.059531 trace git-lfs: HTTP: { 
  "objects" : [ {
    "oid" : "aad5173f613a3ed1f169d80ab3eb2d073eaca2841b42a3e2f656a068382d4b2d",
    "size" : 28275405
  }, {
    "oid" : "9b9bfc3a3f85b22a1b5e28112c5fe028b53c5cc69be97cdf969c6df03b5d5197",
    "size" : 28275404
  }, {
    "oid" : "f777603a0ac03decbced862154ca8071ef0b41eef81c16dd275043940351f73e",
    "size" : 28275404
  }, {
    "oid" : "2b1c49a167430ccd56332064e2462ce4c5c094a3e5a62d94bc8bf5d68ea4199b",
    "size" : 28275404
.... for 8000+ OIDS.

Looking at the rev-list call the lfs pre-push makes, the above example would point to an estimate of scanning 8242 OIDS which contain LFS pointers:

% git rev-list ff7fe17b --objects | git cat-file --batch-check='%(objectname) %(objecttype)    8242   24726  513882

If I use --no-verify to bypass the pre-push hook, the tag push completes within a couple seconds.

**Expected behavior**
No attempt to push Git LFS objects should be needed for tag refs that I can think of. I'd expect the same behavior as it currently works for branch deletions where no attempts to push Git LFS objects will be made.

Looking at the LFS code, it seems command_pre_push.go needs to account for tag ref types and the remote SHA value being '0000000000000000000000000000000000000000'.
Under those conditions it should continue and do nothing.
I've added some code in my clone of the source to that effect and it resolves the performance issue.
 
**System environment**
RHEL7

**Comment by bk2204** [comment]
Hey,

You're right that in some cases we do walk the entire history, specifically in some cases when the remote side of the ref doesn't exist.  Unfortunately, we can't assume that pushing a tag itself means we don't have to traverse history, because the tag can point to items which the remote side doesn't have but aren't being pushed.  For example, I can create a branch with lots of LFS objects, tag it, and push the tag but not the branch.

As the trace you've pushed shows, we do attempt to optimize things by not traversing objects which are already in the remote tracking branches for the remote.  In your particular case, are you pushing to an existing named remote, or a remote with a URL?  Also, are you pushing a tag pointing to a branch the remote side already has, or a tag with additional history?  It's possible our optimization is off, although it's very similar to the algorithm Git uses internally for some things.

**Comment by jerick1976** [comment]
Hello Brian,

Dumb question time on my part.  Why does git-lfs want to block a branchless tag if git already allows the same push?

**Comment by dghowlett** [comment]
Hey,

Thanks for the quick reply.
In our use case, we're pushing to a remote using a URL against a tag pointing to a branch and SHA id that the remote side already has. It's just a push of a new tag with no other additional history.  In our use case, the typical workflow is:

- Perform a commit
- Create a new tag against that commit
- Push branch and tag: git push <remote_url> <branch> <tag>

The processing of the branch ref is optimized as the rev-list is scoped correctly to the local SHA and remote SHA delta.  Its the tag ref processing that ends up walking the full history.
I concur that walking the history would be needed for cases where the tag can point to items the remote side doesn't have and are being pushed.  Perhaps the code can optimized to focus on cases where the remote side does have the items, something like:

1. Verify if the tag SHA pointed to already exists on the remote and if so, it's a no-op.
2. In the case where multiple refs are specified on the git push:
    git push <remote_url> <branch> <tag>
    The code could do some pre-processing iterating over all the refs pushed and if the tag ref points to an existing SHA included by a branch ref, it's also a no-op.
    Take for example this one:
    git push <remote_url> dgtest3 dgtest3/17
    ....
trace git-lfs: pre-push: refs/heads/dgtest3 2270078f85fadfddca836feea567d776f72bb68b refs/heads/dgtest3 79b9aace9d5ba197663b9f822af9a309171678bf
trace git-lfs: pre-push: refs/tags/dgtest3/18 2270078f85fadfddca836feea567d776f72bb68b refs/tags/dgtest3/18 0000000000000000000000000000000000000000

Above we know the branch ref pushed matches the same SHA the tag is pointing to as well.

Thoughts?

**Comment by bk2204** [comment]
> Hello Brian,
> 
> Dumb question time on my part. Why does git-lfs want to block a branchless tag if git already allows the same push?

In this case, we don't use the `pre-push` hook to block pushes.  We use it to push the LFS objects that are required by said pushes.  Git by this point has a good idea what it needs to push, and we need to find the LFS objects, which involves walking the changed history to find which objects are referenced.

**Comment by bk2204** [comment]
Hey,

I think what we want to do in this case is optimize this a little bit by walking over all the pushed refs at once.  That will give us the same results as walking over both independently, but we'll traverse fewer objects in your case because we'll have the parents of the commit to exclude.  It also means pushes of many branches to a new remote will be more efficient.

I'll try to see if I can find some time to implement that, but I can't guarantee I'll get to it before the 2.10 release, which will likely happen next week.

**Comment by bk2204** [comment]
Can you try the branch in #3978 and see if it improves things in your case?  If you need binaries to test, the CI system will produce them as artifacts which you can download.

Please note that it's in a very preliminary state, but if it helps in your situation, I'll write it up with a full commit message and tests.

**Comment by dghowlett** [comment]
Sure can, let me validate that branch and update shortly.

**Comment by dghowlett** [comment]
Hi Brain,

Using branch in #3978 is much faster now:

> git-lfs version
git-lfs/2.9.0 (unknown; linux amd64; go 1.13.5; git 0bd8e6ee)
sjc-ads-6017:1175> time git push https://..../repo.git testing_git_commit testing_git_commit/18 
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 392 bytes | 98.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
   a71a2f4cb..0646f4f29  testing_git_commit -> testing_git_commit
 * [new tag]             testing_git_commit/18 -> testing_git_commit/18
0.423u 0.403s 0:02.82 29.0%     0+0k 1360+0io 3pf+0w

With GIT_TRACE on, I can see the exclusion now based off looking at the other refs being pushed:

12:52:46.222025 trace git-lfs: pre-push: refs/heads/testing_git_commit 8a3b26251bf07ebd9ab6efcfaf2f0afffa6760c4 refs/heads/testing_git_commit 183ca401176b49dcc6463b1a4b63ab1eff399c4a
12:52:46.222035 trace git-lfs: pre-push: refs/tags/testing_git_commit/16 8a3b26251bf07ebd9ab6efcfaf2f0afffa6760c4 refs/tags/testing_git_commit/16 0000000000000000000000000000000000000000
12:52:46.457340 trace git-lfs: tq: running as batched queue, batch size of 100
12:52:46.457433 trace git-lfs: Performing rev-list with include=["8a3b26251bf07ebd9ab6efcfaf2f0afffa6760c4"] and exclude=["183ca401176b49dcc6463b1a4b63ab1eff399c4a" "0000000000000000000000000000000000000000"]
12:52:46.457609 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://.../repo.git --
12:52:46.467925 trace git-lfs: tq: running as batched queue, batch size of 100
12:52:46.468024 trace git-lfs: Performing rev-list with include=["8a3b26251bf07ebd9ab6efcfaf2f0afffa6760c4"] and exclude=["183ca401176b49dcc6463b1a4b63ab1eff399c4a" "0000000000000000000000000000000000000000"]
12:52:46.468182 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://.../repo.git --

vs 2.9.2:

> git lfs version
git-lfs/2.9.2 (unknown; linux amd64; go 1.13.5; git 0274d856)
sjc-ads-6017:1191> time git push https://....repo.git testing_git_commit testing_git_commit/19
^Cloading LFS objects:  78% (300/386), 8.1 GB | 0 B/s                                                                                                                                                                                                                                      
Exiting because of "interrupt" signal.
0.055u 0.000s 1:09.09 0.0%      0+0k 0+0io 0pf+0w

Nice work on the quick improvement there.

I notice the perf issue still persists for the standalone git push of a tag. Though even with the above fix, that's a considerable improvement for that scenario which is one of the common use cases we hit.

For the standalone tag, that one is a bit trickier.

If it's a tag against a ref already pushed, then possibly you could check to see if that specific SHA is contained in any existing remote branches:
% git branch --all --contains 183ca401176b49dcc6463b1a4b63ab1eff399c4a
* testing_git_commit
  remotes/origin/testing_git_commit

Our usage of pushing to a direct URL appears to make it more complex though vs an existing tracked remote like origin.
I'll ponder that more, great to see the initial improvement though.

Thx, Doug

**Comment by bk2204** [comment]
Yeah, if you're pushing to a direct URL, we can't use the optimization of checking the remote tracking branches.  In general, it's not safe to read remote tracking branches by looking up the remote for the URL, because there may be multiple URLs or remotes and even when there's not, we don't know that the remote tracking branches are in sync with the URL.

Git has this same problem with some needless submodules pushes with a direct URL.

**Comment by dghowlett** [comment]
Thanks Brain, appreciate the discussion, the optimized pushes for multiple refs #3978 will still give a nice performance win, look forward to the upcoming release on it.

-Doug
