### ISSUE TITLE
Domain user gets locked when running under on-premise TFS

### ISSUE THREAD

**Issue by itsho** [git-lfs/git-lfs#3980]
Following https://github.com/git-lfs/git-lfs/pull/3941

# Bug description
* On premise TFS + Build agents are using Windows Domain Users
* git repository is stored in TFS (TFVC)
* When the build agent is trying to 'git clone' the repo, it causes the windows user to get locked

# Steps to reproduce
I tried to reproduce the issue in various ways: 
 - different users
 - PAT - [Private-Access-Token](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
 - `git-lfs` 2.9.3 - compiled locally from 770719d

But the only way to reconstruct is this:
1. In TFS, create a new build definition from a large git repo.
2. On Build Agent machine, install `Git.exe` 2.24 and `git-lfs` 2.9.2+.
3. On Build Agent machine, set gitconfig `http.version` to `HTTP/1.1`
4. On Build Agent machine, manually edit `ca-bundle.crt` and insert the On-premise TFS self-signed certificate.
5. Queue a new build.
6. The build will run and will get most (?) of the files, but then it will either: get stuck, or - fail.
7. The bad part - The user defined in the Build Agent will **get locked** at the domain level.

 # Expected behavior
The user should not get locked. worse case: the build should fail.

# System environment
OS - Windows Server 2012R2/2016
RAM - 128GB

# Output of `git lfs env`
> git-lfs/2.9.2 (GitHub; windows amd64; go 1.12.7; git 0274d856)
> git version 2.24.1.windows.2
> Error: Failed to call git rev-parse --git-dir: exit status 128
> LocalWorkingDir=
> LocalGitDir=
> LocalGitStorageDir=
> LocalMediaDir=lfs\objects
> LocalReferenceDirs=
> TempDir=lfs\tmp
> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> LfsStorageDir=lfs
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic,lfs-standalone-file
> UploadTransfers=basic,lfs-standalone-file
> GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
> GIT_LFS_PATH=C:\Program Files\Git LFS
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"

# Additional context
I cannot upload the full log(s) here since it contains some private details. If there's an option to share it privately with you - please inform me.

I tried to analyze the logs, and this is my guess so far:

## Case 1
The typical "good" parts in the log look like this:
```
> HTTP/1.1 200 OK
> Content-Length: 31318
> trace git-lfs: fetch **************************** [****************************0b]
> Activityid: 3b6284cf-ac27-4ac0-a9df-45ae381bac73
> Cache-Control: private
> trace git-lfs: fetch **************************** [****************************43]
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> Date: Tue, 14 Jan 2020 13:59:30 GMT
> Lfs-Authenticate: NTLM
> trace git-lfs: fetch **************************** [****************************45]
> P3p: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
> Server: Microsoft-IIS/10.0
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> X-Aspnet-Version: 4.0.30319
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Powered-By: ASP.NET
> X-Tfs-Processid: 524b4609-bf08-401f-b039-dd1647064bde
> X-Tfs-Session: 3b6284cf-ac27-4ac0-a9df-45ae381bac73
> X-Vss-E2eid: 3b6284cf-ac27-4ac0-a9df-45ae381bac73
> X-Vss-Userdata: 84a522e5-06e9-4432-99e9-f51c762ac88b:dff35237-9777-4e3b-bcb0-71459a151edc
```

while the "bad" parts look like this:
```
> HTTP/1.1 401 Unauthorized
> Content-Length: 86
> Activityid: 1e168e1f-abeb-4360-893e-0353090bd4bb
> Content-Type: text/plain; charset=utf-8
> Date: Tue, 14 Jan 2020 13:59:31 GMT
> Lfs-Authenticate: NTLM
> P3p: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
> Server: Microsoft-IIS/10.0
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Www-Authenticate: Bearer
> Www-Authenticate: Basic realm="https://my-tfs/tfs"
> Www-Authenticate: NTLM
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Powered-By: ASP.NET
> X-Tfs-Processid: 0a09103e-3eef-42e4-ad61-76dbc0ae97d5
> X-Tfs-Serviceerror: TF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.
> X-Tfs-Session: 1e168e1f-abeb-4360-893e-0353090bd4bb
> X-Tfs-Soapexception: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
> X-Vss-E2eid: 1e168e1f-abeb-4360-893e-0353090bd4bb
```

So, somehow, we tried to use an anonymous login, and TFS responded with `TF400813: Resource not available for anonymous access. Client authentication required`

## Case 2 
with 770719d4, the log is much shorter:
[git-lfs-293-userLocked.txt](https://github.com/git-lfs/git-lfs/files/4059896/git-lfs-293-userLocked.txt)

# Side note
not sure if it's related, but sometimes when I'm getting `fatal: Authentication failed` 
I was able to solve it by removing **any** stored credentials in Windows (start-> run -> `rundll32.exe keymgr.dll,KRShowKeyMgr`) which are in the following format - "git:https://@my-tfs/"

Thanks in advance.

**Comment by bk2204** [comment]
Hey,

Thanks for opening this issue.  And just to confirm, the user doesn't get blocked if you use the released 2.9.2, only the current unreleased version?

**Comment by itsho** [comment]
Hi.

No, The user gets blocked with any version.

**Comment by itsho** [comment]
After consulting with a few people, the current conclusion is that it's an issue in on-premise TFS and NOT in `git-lfs`.

Thanks
