### ISSUE TITLE
Migrating Git LFS repo from one Artifactory Server to Another Artifactory Server

### ISSUE THREAD

**Issue by darbysobha** [git-lfs/git-lfs#3984]
This is not an issue, but a question.

We are using Artifactory Server for storing LFS files and GitHub 2.17 Enterprise Server for Git Repositories. We are in the process of migrating all our Artifacts including Git LFS objects from our current Artifactory Server to a new instance of Artifactory Server. We have manually migrated all repositories from our Old Artifactory Server to the New Artifactory Server including the Git LFS repositories. 

What next step configuration is required as far as Git Repo is concerned? Since the Git LFS Repo URL is stored ".lfsconfig" file of the repository, we need to change this URL, right? As per my knowledge, the following steps to be performed for each branch of the Repository:

1) git checkout branch-name
2) git config -f .lfsconfig lfs.url https://new.artifactory.abc.com/api/lfs/ABCDEF
3) git config lfs.url https://new.artifactory.com/api/lfs/ABCD (This is to change the URL stored in ~/.git/config  file)
4) git add .lfsconfig
5) git commit -m "Migrate LFS to new Artifactory"
6) git push -u origin branch-name

Here ABCDEF is the Git LFS repository created in the new Artifactory Server https://new.artifactory.abc.com.

Is there anything else I need to complete the process of migration? Are the above steps sufficient to copy all commit histories related to LFS objects

Our Enviroment:
===========
GitHub Enterprise Server 2.17
Artifactory Version 6.13.0.

git lfs env output:
============
$ git lfs env
git-lfs/2.4.2 (GitHub; linux amd64; go 1.9.4)
git version 2.23.0

Endpoint=https://new.artifactory.abc.com/api/lfs/ABCDEF (auth=basic)
LocalWorkingDir=/tmp/net-source
LocalGitDir=/tmp/net-source/.git
LocalGitStorageDir=/tmp/net-source/.git
LocalMediaDir=/tmp/net-source/.git/lfs/objects
LocalReferenceDir=
TempDir=/tmp/net-source/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/tmp/net-source/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/root/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

Unlike Git objects, a clone of a repository using LFS does not contain all LFS objects.  The easiest way to do this would be some Artifactory-specific copying method that copies all objects.

Barring that, you'd want to do a full `git clone` as step 0, do `git lfs fetch --all` between steps 1 and 2, and then do a `git lfs push --all` after step 6.  That should ensure that all of the objects are copied across between the two servers.  Note that if your repository has hidden refs that are not copied, like the ones some Git servers use to store old versions of pull requests, that won't copy LFS objects used by those versions, but it will copy everything else.

Hopefully that's helpful for your use case.

**Comment by darbysobha** [comment]
Thank you bk2204
