### ISSUE TITLE
"Git LFS is disabled for this repository."  How can I solve this problem?

### ISSUE THREAD

**Issue by zoown13** [git-lfs/git-lfs#3987]
**Describe the issue**

![git lfs](https://user-images.githubusercontent.com/41746120/72514317-cb460b00-3891-11ea-83fe-9484cdf248d1.PNG)

As you can see the above image, I can't upload my files to github.

**System environment**
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
credential.helper=manager
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.name=zoown13
user.email=41746120+zoown13@users.noreply.github.com
core.autocrlf=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false

**Output of `git lfs env`**
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
git version 2.23.0.windows.1

Endpoint=https://github.com/zoown13/BountyDash.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\admin\Documents\Unreal Projects\BountyDash
LocalGitDir=C:\Users\admin\Documents\Unreal Projects\BountyDash\.git
LocalGitStorageDir=C:\Users\admin\Documents\Unreal Projects\BountyDash\.git
LocalMediaDir=C:\Users\admin\Documents\Unreal Projects\BountyDash\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\admin\Documents\Unreal Projects\BountyDash\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\admin\Documents\Unreal Projects\BountyDash\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
LOCAL_GIT_DIRECTORY=C:\Users\admin\AppData\Local\GitHubDesktop\app-2.2.4\resources\app\git
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

It looks like you're having a problem with GitHub, but this project is only for the open-source client.  You may want to check that you're not over your data quota, and failing that, contact GitHub support, since they'll be able to help you better.

**Comment by zoown13** [comment]
> Hey,
> 
> It looks like you're having a problem with GitHub, but this project is only for the open-source client. You may want to check that you're not over your data quota, and failing that, contact GitHub support, since they'll be able to help you better.

Aha, thanks.
