### ISSUE TITLE
Windows XP: install from zip file?

### ISSUE THREAD

**Issue by ukuko** [git-lfs/git-lfs#3988]
**Describe the issue**
Windows installer somehow doesnt run on some windows XP test machines we have
https://github.com/git-lfs/git-lfs/releases/download/v2.9.2/git-lfs-windows-v2.9.2.exe

so I downloaded the zip version
https://github.com/git-lfs/git-lfs/releases/download/v2.9.2/git-lfs-windows-386-v2.9.2.zip

now, after unpacking, I tried adding the folder to PATH and later the folder/git-lfs.exe to PATH, but in both cases, I am not able to do: git lfs install.

**System environment**
Windows XP 32 bit (old test machines, still needed to test some old software)
git version 2.10.0.windows.1

**Output of `git lfs env`**

$ git lfs env
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
        flow

**Additional context**
thanks for any help in advance.

**Comment by bk2204** [comment]
Hey,

We currently build with Go 1.12 or Go 1.13, but Go 1.10 was the last version to run on Windows XP.  You're welcome to try using an older version (say, 2.8.0) and compiling it yourself on a newer system, then copying it over to your Windows XP system.  There are directions on the wiki on how to compile from source.

As far as providing a version that's supported on Windows XP, I don't think it will be possible for us to do that.  You're welcome to try the suggestions that I proposed in #3819 as well; hopefully, those will be helpful.

**Comment by ukuko** [comment]
oh ok got it.. can you tell me what is latest WinXP supported version you have? this would be enough to start witth

**Comment by ukuko** [comment]
and if I understand you properly, all windows-386 packages available in newer releases (since when?) are not compatible for windows XP?

**Comment by bk2204** [comment]
We tend to build with the latest version of Go, so the last version which would have been built with Go 1.10 would have been 2.5.0, if I'm looking correctly.  I can't say that it's supported on Windows XP because we've never tested, and Windows XP is no longer supported by Microsoft, but if you want to try an officially produced binary, it's your best bet.

Similarly, I'm not saying that the latest binaries won't work; you can try unzipping them and running `git-lfs.exe`, and they may indeed work just fine, but they may also be totally broken.

**Comment by ukuko** [comment]
fair enough. I can confirm that 2.5.0 works in Windows XP and this is ok for me for now.

the latest binary 2.9.2 didn't work for me and this was the reason for this issue.

actually, if you say also that 386 architecture is no longer supported, you can remove it at all from deliverables (similar as lets say mozilla firefox).

thanks,

**Comment by bk2204** [comment]
It's not that the 386 architecture isn't supported, since the 32-bit binaries will work on 32-bit versions of Windows 7 and newer, but Windows XP itself isn't supported.

**Comment by ukuko** [comment]
oh I understand now... thanks for explanation.
