### ISSUE TITLE
I have only 1 key in github

### ISSUE THREAD

**Issue by kingofthebongo2008** [git-lfs/git-lfs#3996]
Hello,
I have error when using ssh with github

With https it works fine.

Error downloading object: 3rdparty/dxc/x64/d3dcompiler_47.dll (8bdcccc): Smudge error: Error downloading 3rdparty/dxc/x64/d3dcompiler_47.dll (8bdcccc5dd81330d5b5eb22e3dd87f1260d6f9a1b87cd26c1fe469cdd070a5f7): batch request: git@github.com: Permission denied (publickey).: exit status 255

I can access github with the ssh key other repositories are fine

**Comment by kingofthebongo2008** [comment]
exit status 255
git@github.com: Permission denied (publickey).
github.com/git-lfs/git-lfs/errors.newWrappedError
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrap
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/lfsapi.(*Client).NewRequest
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfsapi/client.go:38
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:53
github.com/git-lfs/git-lfs/tq.Batch
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:37
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:426
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:348
runtime.goexit
    C:/Go/src/runtime/asm_amd64.s:2197
batch request
github.com/git-lfs/git-lfs/errors.newWrappedError
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrap
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:55
github.com/git-lfs/git-lfs/tq.Batch
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:37
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:426
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:348
runtime.goexit
    C:/Go/src/runtime/asm_amd64.s:2197
Error downloading 3rdparty/dxc/x64/d3dcompiler_47.dll (8bdcccc5dd81330d5b5eb22e3dd87f1260d6f9a1b87cd26c1fe469cdd070a5f7)
github.com/git-lfs/git-lfs/errors.newWrappedError
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrapf
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.downloadFile
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:96
github.com/git-lfs/git-lfs/lfs.PointerSmudge
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:61
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:116
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
    C:/Go/src/runtime/proc.go:185
runtime.goexit
    C:/Go/src/runtime/asm_amd64.s:2197
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.NewSmudgeError
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:256
github.com/git-lfs/git-lfs/lfs.PointerSmudge
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:116
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
    C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
    C:/Go/src/runtime/proc.go:185
runtime.goexit
    C:/Go/src/runtime/asm_amd64.s:2197

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you paste the output of `ssh -Tv git@github.com` in a code block?  I want to see if this is a problem that prevents all SSH operations or just this particular one.

**Comment by kingofthebongo2008** [comment]
Hello, I have discovered what happened.
We were using git-lfs, but decided to skip it, because it was too much of a
hassle.
And now it is keeping hostage our files. Before discarding it on github we
have removed all files, but we left some small apparently.
You may close the issue. In Github desktop i got the real message which was
that the quota was expired.
Github desktop returns correct message,
command line git returns this message.

**Comment by bk2204** [comment]
Okay, I'll close this.  I don't think the error message and the quota expiration are related, but I'm glad you figured out what your next steps are.
