### ISSUE TITLE
Trojan detected in git-lfs-linux-amd64-v2.10.0.tar.gz

### ISSUE THREAD

**Issue by ClydeHobart** [git-lfs/git-lfs#4004]
**Describe the bug**
When I try to download the "git-lfs-linux-amd64-v2.10.0.tar.gz" distribution, my Avast Antivirus flags it as a Trojan Horse ("ELF:Agent-AEV [Trj]"). The file does give the same sha256 hash that y'all list. When uploading the file to virustotal.com, it says that Avast and AVG both flag it as having the "ELF:Agent-AEV [Trj]" virus.

**To Reproduce**
1. Go to https://github.com/git-lfs/git-lfs/releases
2. Click on the Linux AMD64 download for the v2.10.0 release
3. Save it somewhere (I don't know much about viruses, but to my understanding if I don't run the file, I'm not in any danger?)
4. Go to virustotal.com
5. Drag and drop the recently downloaded distribution, or select it with their file browser

**Expected behavior**
When I do this, it says 2/57 detection services find that Trojan virus.

**System environment**
I'm using Ubuntu 18.04 with WSL, and all my apt-get calls always pull the "amd64" versions of files. I know that this computer uses 64-bit architecture, but I don't know the difference between the different varieties of 64-bit (like those between AMD64 and ARM64).

**Output of `git lfs env`**
```
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
        log
```

**Additional context**
I don't know much about viruses, but I also can't afford deal with a ransom-ware issue right now. Two out of 57 isn't that bad, but it's not 0. Should I be safe to use it?

**Comment by bk2204** [comment]
Hey.

Thanks for writing in.  This is a false positive. Git LFS is written in Go, and [some virus scanners have trouble with Go programs](https://golang.org/doc/faq#virus).  Our release binaries are built on a GitHub Actions VM and it's very unlikely that those have any sort of malware on them.  To test, I built a binary on my Linux laptop which has been recently freshly installed, and virustotal.com reported the same two antivirus programs warning about it.

The binary should be fine to use and you can safely report it as a false positive to your antivirus vendor.  Thanks for letting us know about this.

As a side note, the AMD64 binary is the right one for your system.  ARM processors are a different architecture commonly used in smaller devices like mobile phones, and ARM64 is the 64-bit version of that architecture (also known as AArch64).  A Windows or WSL installation on a typical PC wouldn't be able to run ARM64, only AMD64.

**Comment by ClydeHobart** [comment]
Thanks! Sorry about that

**Comment by bk2204** [comment]
Not a problem at all.  I appreciate you taking the time to inform us of these things in case something was afoot.  At least if someone else has this problem they can find this issue and there will already be an answer.
