### ISSUE TITLE
When using LFS, where is the raw file uploaded?

### ISSUE THREAD

**Issue by Hyeon9mak** [git-lfs/git-lfs#4006]
Hello. Im student, and I studying git & github this time.
I learned about LFS while studying github, and I was curious about the way LFS works.

I understood LFS's basic concept, but don't understood where is the raw file uploaded.

so I maked Two hypotheses.
A. uploading raw file to the server provided by github, and return the github server address pointer.
B. return the location pointer of the original file saved in the local device directly.

each two hypotheses have problems,
A. There will be a limit to much github server can handle.
B. When the local device is powered off, the LFS file becomes unavailable. 

Of course, if use it myself, will know the answer, but I want to know it in terms of study.

thank you.

**Comment by bk2204** [comment]
Hey,

What happens is that the repository stores a pointer file with the SHA-256 hash of the file in it.  When an upload occurs, the Git LFS client makes a [batch request](https://github.com/git-lfs/git-lfs/blob/master/docs/api/batch.md) that contains URL of the location to upload to or download from, plus any credentials that are required to access it.

In the case of github.com, these files are stored directly in Amazon S3 and the user uploads and downloads directly from there.  The URLs in the batch request are signed Amazon S3 URLs.  Other platforms have different storage backends and may store data themselves.

When it comes time for someone to download it, a new request is made for the object ID (SHA-256 hash) of the file, and it's downloaded again.

Hopefully that's helpful in helping you learn more.  We do have some documentation in the `docs` directory which may be interesting to you.  Let us know if there's any other questions you have.
