### ISSUE TITLE
After activating git lfs in a repo, other users experience "error external filter 'git-lfs filter-process' failed fatal smudge filter lfs failed"

### ISSUE THREAD

**Issue by klaus-isbruch-dieboldnixdorf** [git-lfs/git-lfs#4007]
We tried to start using git lfs in one of our repos, but other users, except the one who initialized the repo on his machine don't get the files under lfs resolved, but now have only the pointer files.
Did we miss a step?

Steps taken:
1. Use an exsiting repo, with already existing *.zip files
2. Activate LFS on the Bitbucket server 

First user workstation:
3. Activate LFS (git lfs install, ...) on a user workstation with an already existing clone of that server repo
4. Change some *.zip files in a feature branch and push changes to the server.

Second user workstation
5. Second user workstation also has an already existing clone
6. Does a git pull
7. Finds that the zip archives are these LFS pointer files
8. Uses git lfs install to activate LFS
9. Tries git pull, and git lfs pull, both commands fail with strange error messages and no hint what to do now.

10. Make a new (temporary) clone from the server repo 
11. Attempt to check out feature branch results in a different error message 

Note: I have replaced the user names by user.two and the server names by our-bitbucket-server, also some parts of the repo- and branch names, but I kept the naming structure as is.

--------------------------------------------------------------------
Step 9 git lfs pull (git env: please see further down below):
--------------------------------------------------------------------
user.two@DE-CND82675SY MINGW64 /c/GIT/bp-ourproduct-prepackage (buildMedia/ISSUE-692-solutionbuild4prepackage-ki-200129_2)
$ GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull
18:18:44.188722 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
18:18:44.193708 git.c:702               trace: exec: git-lfs pull
18:18:44.193708 run-command.c:663       trace: run_command: git-lfs pull
18:18:44.546169 trace git-lfs: exec: git 'version'
18:18:45.868958 trace git-lfs: exec: git 'config' '-l'
18:18:45.979834 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
18:18:46.091588 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
18:18:46.208324 trace git-lfs: tq: running as batched queue, batch size of 100
18:18:46.316004 trace git-lfs: filepathfilter: accepting "masterdummy.txt"
18:18:46.480777 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
18:18:46.480777 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
18:18:46.480777 trace git-lfs: filepathfilter: accepting "tmp"
18:18:46.481743 trace git-lfs: filepathfilter: accepting "007667367"
18:18:46.481743 trace git-lfs: Removing invalid tmp object file: C:\GIT\bp-ourproduct-prepackage\.git\lfs\tmp\007667367

--------------------------------------------------------------------
Step 11 git checkout feature branch in a new clone
--------------------------------------------------------------------
user.two@DE-CND82675SY MINGW64 /c/tmp/GIT_temp/bp-ourproduct-prepackage (develop)
$ git checkout feature/ISSUE-692-solutionbuild4prepackage-ki-200117
Updating files: 100% (446/446), done.
Downloading regkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip (356 B)
Error downloading object: regkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip (09e938a): Smudge error: Error downloading prodkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip (09e938a4f9222c1fe763eb5c19f00140fc1fefc196616e016f00e8f11b8d8bb3): batch response: Post https://our.bitbucket-server.com/scm/bbproj/bp-ourproduct-prepackage.git/info/lfs/objects/batch: proxyconnect tcp: tls: first record does not look like a TLS handshake

Errors logged to C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git\lfs\logs\20200129T182309.3876845.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: prodkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip: smudge filter lfs failed

user.two@DE-CND82675SY MINGW64 /c/tmp/GIT_temp/bp-ourproduct-prepackage (develop)

----------------------------------------
Step 11 C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git\lfs\logs\20200129T182309.3876845.log
----------------------------------------
git-lfs/2.9.0 (GitHub; windows amd64; go 1.12.7; git 8ab05aa7)
git version 2.24.0.windows.2

$ git-lfs.exe filter-process
Error downloading object: prodkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip (09e938a): Smudge error: Error downloading prodkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip (09e938a4f9222c1fe763eb5c19f00140fc1fefc196616e016f00e8f11b8d8bb3): batch response: Post https://our.bitbucket-server.com/scm/bbproj/bp-ourproduct-prepackage.git/info/lfs/objects/batch: proxyconnect tcp: tls: first record does not look like a TLS handshake

Post https://our.bitbucket-server.com/scm/bbproj/bp-ourproduct-prepackage.git/info/lfs/objects/batch: proxyconnect tcp: tls: first record does not look like a TLS handshake
batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
	d:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrap
	d:/a/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
	d:/a/git-lfs/git-lfs/tq/api.go:77
github.com/git-lfs/git-lfs/tq.Batch
	d:/a/git-lfs/git-lfs/tq/api.go:40
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	d:/a/git-lfs/git-lfs/tq/transfer_queue.go:520
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
	d:/a/git-lfs/git-lfs/tq/transfer_queue.go:432
runtime.goexit
	C:/Go1.12.7/src/runtime/asm_amd64.s:1337
Error downloading prodkeys/Demo_Product_Key_OurProduct_VXY_R31.xx.zip (09e938a4f9222c1fe763eb5c19f00140fc1fefc196616e016f00e8f11b8d8bb3)
github.com/git-lfs/git-lfs/errors.newWrappedError
	d:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrapf
	d:/a/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.(*GitFilter).downloadFile
	d:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:115
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
	d:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:76
github.com/git-lfs/git-lfs/commands.smudge
	d:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
	d:/a/git-lfs/git-lfs/commands/command_filter_process.go:118
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run
	d:/a/git-lfs/git-lfs/commands/run.go:97
main.main
	d:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	C:/Go1.12.7/src/runtime/proc.go:200
runtime.goexit
	C:/Go1.12.7/src/runtime/asm_amd64.s:1337
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
	d:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	d:/a/git-lfs/git-lfs/errors/types.go:284
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
	d:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:85
github.com/git-lfs/git-lfs/commands.smudge
	d:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
	d:/a/git-lfs/git-lfs/commands/command_filter_process.go:118
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run
	d:/a/git-lfs/git-lfs/commands/run.go:97
main.main
	d:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	C:/Go1.12.7/src/runtime/proc.go:200
runtime.goexit
	C:/Go1.12.7/src/runtime/asm_amd64.s:1337

Current time in UTC: 
2020-01-29 17:23:09

ENV:
LocalWorkingDir=C:\tmp\GIT_temp\bp-ourproduct-prepackage
LocalGitDir=C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git
LocalGitStorageDir=C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git
LocalMediaDir=C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\tmp\GIT_temp\bp-ourproduct-prepackage\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_PREFIX=

Client IP addresses:
fe80::e93f:980c:839d:a257 192.168.16.1
fe80::dcdc:9462:9479:83f6 172.27.56.48
fe80::781c:7b6c:f725:ee5d 192.168.118.1
fe80::b19d:8586:df67:f3ce 192.168.88.1
2003:c5:f40:ab00:f00f:965:a57e:7d4d 2003:c5:f40:ab00:5909:5030:b5ed:345e fe80::f00f:965:a57e:7d4d 192.168.0.121

**Comment by bk2204** [comment]
Hey,

It looks like you're set up to use a proxy.  Is that your intent?  If so, what kind of proxy is it?  What do your proxy settings look like (environment variables and the Git `http.proxy` settings)?  What kinds of authentication does the proxy support, and do you have the credentials in the URL?

**Comment by klaus-isbruch-dieboldnixdorf** [comment]
Hi, thanks for the quick response.
Yes, we have a proxy for providing access to external servers like maven central. 
For the communication between our work computers and the git server (and other servers in the company network) no proxy is required.

We have a proxy config script in our internet browser settings, but for example our gradle proxy settings use some fixed settings, and look like this:
systemProp.http.proxyHost=proxy.ourcompany.com
systemProp.http.proxyPort=81
systemProp.http.nonProxyHosts=*.ourcompany.com|*.ourparentcompany.com|localhost|172.18.*|*.ourparentcompany.com
systemProp.https.proxyHost=proxy.ourcompany.com
systemProp.https.proxyPort=81
systemProp.http.nonProxyHosts=*.ourcompany.com|*.ourparentcompany.com|localhost|172.18.*|*.ourparentcompany.com

We do not have any proxy settings in any git configuration file or in any environment variable.

We do not have credentials in the url (I didn't remove anything in this respect from the logs above), but I myself (who initialized git lfs for this repo) use SSH  (OpenSSH on my computer), and my co worker uses https. The git client in this case uses the windows credentials storage to avoid asking for the server credentials every time a git communication command is used.

Does this answer your questions?

**Comment by bk2204** [comment]
The message `proxyconnect tcp: tls: first record does not look like a TLS handshake` indicates that Git LFS is attempting to use a proxy but the CONNECT request is failing (usually due to an authentication issue).  Even though a proxy is not required, it sounds like one is being used.

Git LFS looks for proxy settings in the `http_proxy`, `HTTP_PROXY`, `https_proxy`, `HTTPS_PROXY`, `no_proxy`, and `NO_PROXY` environment variables, and in the Git config in the `http.proxy` and `http.*.proxy` settings.  Can you run `env | grep -ai proxy` and `git config -l | grep proxy` in Git Bash and include the results here?

**Comment by klaus-isbruch-dieboldnixdorf** [comment]
Yes, you are right, on that other system http_proxy and https_proxy are both set.
The user there told me that this is required for another application to work.

We tried to reset these variables in the git bash window, but get another error now.
What else do we need to do?
Thanks, Klaus

Here the logs from our attempt to reset the proxy variables:

env | grep -ai proxy 
git config -l | grep proxy

user.two@DE-CND82675SY MINGW64 /c/GIT/bp-ourproduct-prepackage (buildMedia/ISSUE-692-solutionbuild4prepackage-ki-200129_2)
$ env | grep -ai proxy
https_proxy=https://proxy.ourcompany.com:81/
http_proxy=http://proxy.ourcompany.com:81/

-------------------------------------------------------------------
new test: 
open git bash window

user.two@DE-CND82675SY MINGW64 /c/GIT/bp-ourproduct-prepackage (buildMedia/ISSUE-692-solutionbuild4prepackage-ki-200129_2)
$ export https_proxy=
$ export http_proxy=
$ git reset --hard origin/buildMedia/ISSUE-692-solutionbuild4prepackage-ki-200129_2
Updating files: 100% (2245/2245), done.
Downloading prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip (356 B)
Error downloading object: prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip (09e938a): Smudge error: Error downloading prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip (09e938a4f9222c1fe763eb5c19f00140fc1fefc196616e016f00e8f11b8d8bb3): batch response: Post https://our.bitbucket-server.com/scm/bbproj/bp-ourproduct-prepackage.git/info/lfs/objects/batch: x509: certificate signed by unknown authority

Errors logged to C:\GIT\bp-ourproduct-prepackage\.git\lfs\logs\20200131T111422.5824908.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip: smudge filter lfs failed




git-lfs/2.9.0 (GitHub; windows amd64; go 1.12.7; git 8ab05aa7)
git version 2.24.0.windows.2

$ git-lfs.exe filter-process
Error downloading object: prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip (09e938a): Smudge error: Error downloading prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip (09e938a4f9222c1fe763eb5c19f00140fc1fefc196616e016f00e8f11b8d8bb3): batch response: Post https://our.bitbucket-server.com/scm/bbproj/bp-ourproduct-prepackage.git/info/lfs/objects/batch: x509: certificate signed by unknown authority

Post https://our.bitbucket-server.com/scm/bbproj/bp-ourproduct-prepackage.git/info/lfs/objects/batch: x509: certificate signed by unknown authority
batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
	d:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrap
	d:/a/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
	d:/a/git-lfs/git-lfs/tq/api.go:77
github.com/git-lfs/git-lfs/tq.Batch
	d:/a/git-lfs/git-lfs/tq/api.go:40
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	d:/a/git-lfs/git-lfs/tq/transfer_queue.go:520
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
	d:/a/git-lfs/git-lfs/tq/transfer_queue.go:432
runtime.goexit
	C:/Go1.12.7/src/runtime/asm_amd64.s:1337
Error downloading prodkeys/Demo_Product_Key_OurProduct_VXY.xx.zip (09e938a4f9222c1fe763eb5c19f00140fc1fefc196616e016f00e8f11b8d8bb3)
github.com/git-lfs/git-lfs/errors.newWrappedError
	d:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrapf
	d:/a/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.(*GitFilter).downloadFile
	d:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:115
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
	d:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:76
github.com/git-lfs/git-lfs/commands.smudge
	d:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
	d:/a/git-lfs/git-lfs/commands/command_filter_process.go:118
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run
	d:/a/git-lfs/git-lfs/commands/run.go:97
main.main
	d:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	C:/Go1.12.7/src/runtime/proc.go:200
runtime.goexit
	C:/Go1.12.7/src/runtime/asm_amd64.s:1337
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
	d:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	d:/a/git-lfs/git-lfs/errors/types.go:284
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
	d:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:85
github.com/git-lfs/git-lfs/commands.smudge
	d:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/commands.filterCommand
	d:/a/git-lfs/git-lfs/commands/command_filter_process.go:118
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run
	d:/a/git-lfs/git-lfs/commands/run.go:97
main.main
	d:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	C:/Go1.12.7/src/runtime/proc.go:200
runtime.goexit
	C:/Go1.12.7/src/runtime/asm_amd64.s:1337

Current time in UTC: 
2020-01-31 10:14:23

ENV:
LocalWorkingDir=C:\GIT\bp-ourproduct-prepackage
LocalGitDir=C:\GIT\bp-ourproduct-prepackage\.git
LocalGitStorageDir=C:\GIT\bp-ourproduct-prepackage\.git
LocalMediaDir=C:\GIT\bp-ourproduct-prepackage\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\GIT\bp-ourproduct-prepackage\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\GIT\bp-ourproduct-prepackage\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_PREFIX=

Client IP addresses:
fe80::e93f:980c:839d:a257 192.168.16.1
fe80::dcdc:9462:9479:83f6 172.27.88.215
fe80::781c:7b6c:f725:ee5d 192.168.118.1
fe80::b19d:8586:df67:f3ce 192.168.88.1
2003:c5:f40:ab00:f00f:965:a57e:7d4d 2003:c5:f40:ab00:fcb0:2117:7df3:538d fe80::f00f:965:a57e:7d4d 192.168.0.121

**Comment by bk2204** [comment]
If those variables are required for other programs to work, you can specify a list of comma-separated domains for which no proxy should be used in the `no_proxy` environment variable while leaving the `http_proxy` and `https_proxy` variables in place.

The error message you're seeing now (“x509: certificate signed by unknown authority”) is that your certificate is not issued by a trusted certificate authority.  Go usually gets the list of system trusted certificates from the system credential store, but if your system doesn't trust the certificate, you can use the standard Git `http.sslCAInfo` and `http.sslCAPath` settings to control which certificates are valid.

**Comment by klaus-isbruch-dieboldnixdorf** [comment]
Thank you very much, that solved it.
http_proxy= and https_proxy= were set but not no_proxy=.
We have set no_proxy=<our git server>, and we disabled http.sslVerify, since we are in a private company network.
I very much appreciate your quick and efficient responses!
With best regards, Klaus.
