### ISSUE TITLE
Paths are not canonicalized in the same way as Git on Windows

### ISSUE THREAD

**Issue by wpdonders** [git-lfs/git-lfs#4012]
I have several repositories on a network path. I am able to use git-lfs on those existing repositories just fine, but I am running into issues when trying to track new files. I'm not sure what triggered the change in behavior. I moved from a Windows 7 to a Windows 10 machine, and am probably running a different version of git and git-lfs than before. I'm not sure of the relevance of this.

Let's say the network drive with UNC path `\\network` is mapped to the drive letter N. 
When I run the following commands from the Windows command shell (`cmd`), 
```
$ N:
$ mkdir repo
$ cd repo
$ git init
$ git lfs install
$ git lfs track *.bin
```
I get an error,
```
Current directory "N:\\repo" is outside of git working directory "\\\\network\\repo"
```
When I run `git lfs env`, I get the following entries for directories directories:
```
git-lfs/2.10.0 (Github; windows amd64; go 1.12.7; git a526ba6b
git version 2.25.0.windows.1

LocalWorkingDir=\\network\repo
LocalGitDir=N:\repo\.git
LocalGitStorageDir=N:\repo\.git
LocalMediaDir=N:\repo\.git\lfs\objects
LocalReferenceDirs=
TempDir=N:\repo\.git\lfs\tmp
(...)
LfsStorageDir=N:\repo\.git\lfs
```
It seems to me the issue arises from the fact that the `LocalWorkingDir` is set to the UNC path, whereas all other `*Dir` entries are set to the mapped drive letter. 

I have no issues in adding/committing changes to files in existing repos as lfs objects (they are already tracked), however, I can no longer track new files in those existing repositires, which I was able to do before just fine. The `git lfs env` shows similar pattern (UNC path on `LocalWorkingDir`, network drive letters on other `*Dir` settings).

edit: small additions

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you provide the output of `git rev-parse --absolute-git-dir --git-dir --git-common-dir --show-toplevel`?  I think what's happening here is that Git is canonicalizing paths differently than we are.

**Comment by wpdonders** [comment]
Thanks for your reply.

The output to the command is (translated to my example):
```
//network/repo
.git
.git
//network/repo
```

**Comment by bk2204** [comment]
Okay, thanks.  This is a limitation in the combination of Go and Git.  Go doesn't provide a function to actually canonicalize paths, only to produce absolute paths and resolve symlinks.  Git, on the other hand, resolves some path names as absolute and resolves some as relative.  As a result, we get absolute paths for one and relative paths for the other, and our attempt to canonicalize them produces different results.

Right now, I don't have a suggestion as to how to solve this problem, but I'll open an issue on the Go repo to get a new function added for canonicalization, and I'll see if I can get Git to provide an option to always produce absolute paths.  The latter is the short-term solution, and the former is the long-term one, but even the latter one will take some time.

**Comment by wpdonders** [comment]
Thanks for clarifying and opening the issue at the appropriate place! I'll try to work this at my end.

**Comment by bk2204** [comment]
The change to Git to support `--path-format=absolute`, which should improve this issue, will be in Git 2.31.0.  Once that's released, we'll look into supporting that in Git LFS.  I can't promise it will fix all the problems, but since Go has steadfastly refused to fix the problem (which was tracked in golang/go#42201), it's the best we can do.

**Comment by wpdonders** [comment]
Thanks a lot for keeping me updated!

**Comment by bk2204** [comment]
Could you check the PR in #4418 and see if it fixes your problems?  If you need a binary, you should be able to download one from [the Actions artfiacts](https://github.com/git-lfs/git-lfs/actions/runs/612016679).
