### ISSUE TITLE
Git LFS is disabled for this repository

### ISSUE THREAD

**Issue by biozhp** [git-lfs/git-lfs#4014]
Hi,I want to submit a file over 100MB using git-lfs.
But I have a trouble.
```
batch response: Git LFS is disabled for this repository.                                                                              
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
error: failed to push some refs to 'https://github.com/biozhp/org.Ta.eg.db.git'
```
What's the problem?

**Comment by bk2204** [comment]
Hey,

It looks like this is a GitHub issue, and this repository is only for the open-source Git LFS project.  I think the most likely problem is that you're over your LFS quota, but if that's not the case, could you reach out to the GitHub support team about this issue?  They'd be able to help you better.
