### ISSUE TITLE
Verifying Binaries 

### ISSUE THREAD

**Issue by james-crowley** [git-lfs/git-lfs#4018]
**Describe the issue**
I am trying to verify the hashes of the binaries posted on the GitHub release page. I am trying to verify them in a systematic way, so I can put the commands in a Dockerfile. 

Usually, I use `sha256sum` to verify the downloads:

```
wget --no-check-certificate --no-cookies http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
    && wget --no-check-certificate --no-cookies http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz.sha512 \
    && echo "$(cat apache-ant-${ANT_VERSION}-bin.tar.gz.sha512) apache-ant-${ANT_VERSION}-bin.tar.gz" | sha512sum -c
```

Or if the file is signed with a GPG I do the following:

```
wget --no-check-certificate --no-cookies https://piccolo.link/sbt-${SBT_VERSION}.tgz \
    && wget --no-check-certificate --no-cookies https://piccolo.link/sbt-${SBT_VERSION}.tgz.asc \
    && curl "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | gpg --import \
    && gpg --verify sbt-${SBT_VERSION}.tgz.asc sbt-${SBT_VERSION}.tgz \
```

But since the file you provide is a combination of the both I am confused on how to verify this systematically. 

Also what key are you using to sign these files? I do not see that mentioned anywhere. When I look around for a key I only see the one mentioned on packagecloud.

**Additional context**
What I want to do is either just download the `sha256` file and verify the hashes. Or import your key and verify the signature. Like how https://github.com/krallin/tini/releases does it.

**Comment by bk2204** [comment]
Hey,

Thanks for writing in.  The releases are signed by a member of the core team, usually me.  You can download the key from https://github.com/bk2204.gpg, and you can verify it [the way we do when we upload](:https://github.com/git-lfs/git-lfs/blob/c3b776db6ee273a6c231f9d5922e3aa3421b7b3e/script/upload#L275-L278)

```
$ gpg -d sha256sums.asc | shasum -a 256 -c
# or 
$ gpg -d sha256sums.asc | sha256sum -c
```

If the signature doesn't validate, `gpg` will output nothing, and the `shasum` or `sha256sum` invocation will fail because the input contains no valid checksum lines.  If you want to check just one download, you can insert a `grep` in the middle to match just the one file.

I'll document the possible keys that can be used to sign a release and provide a way to fetch them programmatically.

**Comment by james-crowley** [comment]
@bk2204 Thanks for your suggestions. I was able to successfully check the hash by issuing:

```
gpg -d sha256sums.asc | grep git-lfs-linux-s390x-v2.10.0.tar.gz | sha256sum -c
```

> I'll document the possible keys that can be used to sign a release and provide a way to fetch them programmatically.

This sounds like a headache to deal with. Not knowing who is signing the packages and having to import X number of keys is a hassle. Is there no way to have a one build lead, like you, only sign the files?

**Comment by bk2204** [comment]
I'm glad it worked for you.

The build is signed by whomever does the release.  Right now that's always me, but I'm trying to make myself not be a single point of failure, so it's possible we'll have other core team members do it. For example, I could be out of the country and an urgent security release might need to be done, so someone else would have to step in.

**Comment by james-crowley** [comment]
Is having a "functional"/"bot" user not an option? I have not gotten a chance to play around with GitHub actions all this much, but I have seen other open source teams have trusted members able to kick off a build. 

Once the build is kicked off, the "functional"/"bot" user handles the signing files and publishing the releases. Thus only having that one key/user always publishing the builds but still having the flexibility of having a group of users able to trigger said build.

**Comment by bk2204** [comment]
We do use GitHub Actions to do our builds, but currently we prefer to have a human sanity-check and sign off on the build instead of blindly trusting the bot to do it.  It's possible we may change things in the future, but that's what we're doing now.
