### ISSUE TITLE
GitHub Desktop (Mac) Support

### ISSUE THREAD

**Issue by benbarry** [git-lfs/git-lfs#4019]
**Describe the issue**
The GitHub Desktop app does not seem to support git-lfs as shown in this video linked from the readme: https://www.youtube.com/watch?v=uLR1RNqJ1Mw

**System environment**
macOS Version 10.14.6
GitHub Desktop Version 2.3.1

**Comment by bk2204** [comment]
Hey,

I think that video is out of date.  I don't use GitHub Desktop, but I believe it does currently support Git LFS.  There shouldn't be any intrinsic reason that it can't, and if there is some reason that it doesn't, you'd be best served by asking the GitHub Desktop folks at https://github.com/desktop/desktop, who would be able to help you better here.

**Comment by benbarry** [comment]
Probably worth removing out of date information from your documentation, or at least providing a disclaimer notice.

**Comment by bk2204** [comment]
By "documentation", are you referring to the video itself, or something else?

**Comment by benbarry** [comment]
I don't really see the distinction. The video is linked in the documentation with the title "How to Work with Big Files". It seems to be represented by the documentation as an accurate source of information—which it clearly isn't anymore.
