### ISSUE TITLE
'git lfs migrate' option '--yes' is not documented

### ISSUE THREAD

**Issue by woopla** [git-lfs/git-lfs#4021]
I had my script waiting for me overnight with `migrate: override changes in your working copy? [Y/n]` :sob: (it takes upwards of four hours to run migrate on this repo, mind you).

I found the option by looking at the code for `commands/command_migrate.go`. I do not see it with `git lfs migrate --help`.

Not a huge issue, but I wanted to get this issue filed to make sure it doesn't fall through the cracks :smile:

**Comment by bk2204** [comment]
Hey,

Thanks for reporting this.  I'll get a PR opened to get this fixed.

**Comment by woopla** [comment]
Thanks for the quick fix @bk2204, much appreciated!
