### ISSUE TITLE
Authorization header added twice when git options override local config

### ISSUE THREAD

**Issue by peter-evans** [git-lfs/git-lfs#4031]
**Describe the bug**
When the git `-c` option is used to override an `extraheader` configuration that already exists in local git config, the header is added twice and causes `git push` to fail.

This behaviour was initially discovered in GitHub actions, but I have managed to reproduce it locally on MacOS.

**To Reproduce**
1. Create a `repo` scoped PAT
2. Create a basic credential for the PAT
   ```python
    import base64
    basic_credential = base64.b64encode(
        f"x-access-token:{github_token}".encode("utf-8")
    ).decode("utf-8")
   ```
3. Execute commands in terminal as follows to reproduce.
   (Basic credential and git repository redacted)
   ```
    mkdir my-repo
    cd my-repo
    # Use the basic cred here to make sure it works
    git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic <basic_credential>" clone https://github.com/owner/my-repo.git .
    # Set the extraheader in local config
    git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic <basic_credential>"
    # Create an lfs tracked file and commit
    git lfs track "*.dat"
    date +%s > a.dat
    git add -A
    git commit -m "test lfs commit"
    # Push to a new ref while overriding the extraheader in local config
    GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic <basic_credential>" push --force https://github.com/owner/my-repo HEAD:refs/heads/lfs-test
   ```
4. The above steps will end with the following error.
   ```
   error: failed to push some refs to 'https://github.com/owner/my-repo'
   ```
   I believe this is due to this request having two `Authorization` headers.
   ```
    19:45:37.345325 trace git-lfs: HTTP: POST https://github.com/owner/my-repo.git/info/lfs/locks/verify
    > POST /owner/my-repo.git/info/lfs/locks/verify HTTP/1.1
    > Host: github.com
    > Accept: application/vnd.git-lfs+json; charset=utf-8
    > Authorization: Basic * * * * *
    > Authorization: Basic * * * * *
    > Content-Length: 38
    > Content-Type: application/vnd.git-lfs+json; charset=utf-8
    > User-Agent: git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
    > 
    {"ref":{"name":"refs/heads/lfs-test"}}19:45:37.558428 trace git-lfs: HTTP: 400
   ```

**Expected behavior**
Expected behaviour is for the `git -c` option to successfully override the local config instead of adding two identical headers. In the above steps, removing the following line allows it to succeed because then only one `Authorization` header will be added.
```
    # Set the extraheader in local config
    git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic <basic_credential>"
```

**System environment**
I've reproduced this behaviour both locally on MacOS and in GitHub Actions (ubuntu vm).

To reproduce in GitHub Actions add a `BASIC_CRED` secret for the basic credential. `actions/checkout` sets the `extraheader` in local config. This workflow attempts to override it and push.
```
on:
  push:
    branches:
      - master
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LFS Test
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-name@users.noreply.github.com'
          git lfs track "*.dat"
          date +%s > a.dat
          git add -A
          git commit -m "test lfs commit"
          GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${{ secrets.BASIC_CRED }}" push --force https://github.com/$GITHUB_REPOSITORY HEAD:refs/heads/lfs-test
```

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
git version 2.20.1 (Apple Git-117)

Endpoint=https://github.com/owner/my-repo.git/info/lfs (auth=none)
LocalWorkingDir=/Users/peter.evans/git/my-repo
LocalGitDir=/Users/peter.evans/git/my-repo/.git
LocalGitStorageDir=/Users/peter.evans/git/my-repo/.git
LocalMediaDir=/Users/peter.evans/git/my-repo/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/peter.evans/git/my-repo/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/peter.evans/git/my-repo/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

**Comment by bk2204** [comment]
Hey,

I can reproduce the problem that you're seeing.  However, I think the situation is a little different.  It looks like before Git LFS sends the header, Git also does a ref lookup, and it also passes both Authorization headers.  However, on GitHub, the main Git service allows multiple Authorization headers and the Git LFS endpoint does not.

Since the behavior here is consistent between Git and Git LFS, and HTTP does allow multiple of the same header (e.g., Set-Cookie), I'm disinclined to change the behavior here.  While one usually does not want multiple Authorization headers (and GitHub's Git LFS endpoint is probably right to reject them), there may be other headers which do merit multiple entries, and of course specifying multiple headers of different types is valid.  It's probably best not to use the extraheader field at all here and instead use a custom credential helper, which you can do with something like this:

```
[credential]
    helper = "!f() { echo username=x-access-token; echo password=$GITHUB_TOKEN; };f"
```

**Comment by peter-evans** [comment]
@bk2204 Thank you for the explanation. Based on this situation, it feels to me that the Git LFS endpoint should match the behaviour of the main Git service. I assume that the main Git service intentionally allows multiple `Authorization` headers exactly because of this issue.

Unfortunately, setting a credential helper won't solve the problem. This is occurring inside a GitHub action that I maintain. The action has to handle the environment as it finds it. The official `actions/checkout` action sets the `extraheader` in local config. My action pushes to git based on a token supplied to it which may, or may not, match the token in local config. Probably my only option here is to somehow disable the extraheader in local config and renable it again after the action finishes.

**Comment by bk2204** [comment]
I don't believe this behavior was intentional on the part of the GitHub Git service.  If there are multiple authorization headers with different tokens, there's no reasonable interpretation of what should happen.  I suspect the behavior could even change over time.

Since this is a GitHub issue, and not a Git LFS client issue, I highly recommend that you reach out to GitHub support on this issue, and ask them if Actions can switch to a custom credential helper for this purpose.  You're welcome to quote me and this issue on this, and direct them to me if they have any questions.

**Comment by peter-evans** [comment]
You're right, and now that I've thought about this some more, the clients are also behaving correctly I think. I wrongly assumed that `git -c "http.https://github.com/.extraheader=...` would overwrite an existing entry with the same name, but it actually makes sense that it adds multiple additional headers for the request.

To fix the issue, I'm now unsetting the extraheader option in local config and restoring it again once the action completes.

I'm going to investigate what would happen if `actions/checkout` used a custom credential helper instead of setting the extraheader. I'm not sure how they work, but it sounds like that could allow actions to override the auth set by `actions/checkout` if git and git-lfs clients treated auth set in an extraheader or directly in the URL with higher precedence. I will follow up at the `actions/checkout` repository if it looks promising.

**Comment by marecabo** [comment]
Thanks for the findings and explanation of this behavior. 

When the Git repo and Git LFS URLs at least differ at some point, sending the authorization header can be limited to the regular git repo requests with this bash line as a workaround:

```bash
#!/bin/bash
git ${GIT_HTTP_ACCESS_TOKEN:+-c http.${repository_url%/*}/.extraHeader="Authorization: Bearer $GIT_HTTP_ACCESS_TOKEN"} clone ${repository_url}
```

**Example**

Git repo: `https://some.bitbucket.server/bitbucket/scm/project/repository.git`
Git LFS: `https://some.bitbucket.server/bitbucket/rest/git-lfs/storage/project/repository/...`

will result in 

```bash
#!/bin/bash
git -c http.https://some.bitbucket.server/bitbucket/scm/project/.extraHeader="Authorization: Bearer <GIT_HTTP_ACCESS_TOKEN>" clone https://some.bitbucket.server/bitbucket/scm/project/repository.git
```
