### ISSUE TITLE
Doc: Getting Started Guide explanation wrong

### ISSUE THREAD

**Issue by ccschneidr** [git-lfs/git-lfs#4032]
**Describe the bug**
The Getting Started section on https://git-lfs.github.com/ explains that for `git lfs install` "You'll need to run this in your repository directory, once per repository." But the [wiki article on installation](https://github.com/git-lfs/git-lfs/wiki/Installation) describes it is needed once per user. Imo the latter one is correct. So the getting started guide should be corrected.

**To Reproduce**
1. Go to 'https://git-lfs.github.com/'
2. See the text after `git lfs install`

**Expected behavior**
Instead the text should read "Each user that intends to use git lfs must run this command."

**System environment**
NA

**Output of `git lfs env`**
NA

**Additional context**
NA

**Comment by chrisd8088** [comment]
Hey, thanks for writing in!  I agree that at first blush, these two sets of instructions appear somewhat contradictory and therefore perplexing.  I'll take a look and try to tune them up appropriately.

**Comment by chrisd8088** [comment]
Closed by git-lfs/git-lfs.github.com#40.
