### ISSUE TITLE
Accidentally I have assigned a value to filter.lfs.required in git config

### ISSUE THREAD

**Issue by ravisrk** [git-lfs/git-lfs#4037]
Accidentally I have assigned a value to filter.lfs.required which took = as the value and you can see as below.

![Issue](https://user-images.githubusercontent.com/44306548/75123831-fd107580-5678-11ea-9587-ba63bdaab45f.PNG)

How can a remove the last row?

Because of this I'm getting errors while doing some operations

**Comment by bk2204** [comment]
Hey,

You'd want to run `git config -l --show-origin` to list all of the config options and where they're located, and then edit the appropriate file to remove the offending entry.  That should work for any Git config option, not just Git LFS ones.

**Comment by ravisrk** [comment]
I think it is originated from --global. Could you please share the procedure on how to "find the location, then editing the appropriate file to remove the offending entry".I'm very new to Git aactually

**Comment by bk2204** [comment]
Sure.  So in this case, I've edited one of my configuration files to have the same entry you have.  I now run the following:

```
$ git config -l --show-origin | grep 'required=='
file:/home/bk2204/.gitconfig    filter.lfs.required==
```

The first line tells me that the source for my configuration setting is in `/home/bk2204/.gitconfig`.  So I fire up my text editor on that file, search for lines matching `required`, and then delete the line that looks something like this:
```
	required = =
```
which will be in a section that looks like the following: `[filter "lfs"]`.

**Comment by ravisrk** [comment]
It worked. Thanks!
