### ISSUE TITLE
git lfs dedup does not handle LFS extensions

### ISSUE THREAD

**Issue by swisspol** [git-lfs/git-lfs#4043]
**Describe the bug**
Looking at the implementation of Git LFS dedup it doesn't appear to handle at all LFS extensions. LFS extensions typically modify the byte stream when copying from LFS blob to worktree, so doing a copy-on-write clone doesn't make sense and results in invalid data in the worktree.

**To Reproduce**
n/a

**Expected behavior**
"git lfs dedup" fails with an appropriate message if any LFS extension if configured .

**System environment**
n/a

**Output of `git lfs env`**
n/a

**Additional context**
n/a

**Comment by chrisd8088** [comment]
Hey, thanks for writing in, and this does sound like something we need to change.  I'll take a look and see if I can craft an appropriate error response for this situation.

**Comment by swisspol** [comment]
For context I’m using an LFS extension to gzip compress blobs, which works nicely, and I just only realized that this would prevent dedup to work.

**Comment by swisspol** [comment]
Shouldn't the issue be closed?

**Comment by chrisd8088** [comment]
No, because #4045 has not been reviewed or merged yet, so until then, this issue should stay open.
