### ISSUE TITLE
There is no man page for "git lfs post-commit" hook

### ISSUE THREAD

**Issue by swisspol** [git-lfs/git-lfs#4048]
**Describe the bug**
There are man pages for all hooks except the "post-commit" one:
https://github.com/git-lfs/git-lfs/tree/master/docs/man

**To Reproduce**
n/a

**Expected behavior**
There is a man page for "post-commit" hook so people can understand what it does.

**System environment**
n/a

**Output of `git lfs env`**
n/a

**Additional context**
n/a

**Comment by chrisd8088** [comment]
Hey, thanks for noticing this.  I agree it's a small gap in the existing help pages, and I'll try to write something up in the next few days.
