### ISSUE TITLE
"should have been pointers" warning incorrectly printed on case-insensitive file systems

### ISSUE THREAD

**Issue by swisspol** [git-lfs/git-lfs#4049]
**Describe the bug**
When cloning a repo on a case-insensitive file system, Git LFS incorrectly prints a warning "files ... should have been pointers" for files which are not tracked by LFS but have a name that matches in a case-insensitive way.

**To Reproduce**
1. Create a repo on Linux on a case-sensitive file system
2. Set up `.gitattributes` to use LFS for `*.psd` files
3. Add some `.psd` and `.PSD` files to the repo, commit and push
4. Clone repo on macOS on a case-insensitive file system
5. You get a warning saying the `.PSD` file should have been a pointer

**Expected behavior**
`.gitattributes` patterns are case sensitive, this warning should not appear.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
git version 2.21.1 (Apple Git-122.3)

Endpoint=(REDACTED)
LocalWorkingDir=/Users/pierre-olivier.latour/Downloads/perforce_test
LocalGitDir=/Users/pierre-olivier.latour/Downloads/perforce_test/.git
LocalGitStorageDir=/Users/pierre-olivier.latour/Downloads/perforce_test/.git
LocalMediaDir=/Users/pierre-olivier.latour/Downloads/perforce_test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/pierre-olivier.latour/Downloads/perforce_test/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/pierre-olivier.latour/Downloads/perforce_test/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
Extension[0]=gzip
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
n/a

**Comment by bk2204** [comment]
Hey,

This appears to be working as intended.  Git matches patterns in `.gitattributes` case-insensitively when `core.ignorecase` is set to true, as is the default on macOS.  So in your case, the `*.psd` pattern matches both `.psd` and `.PSD` files on macOS, but only the former on Linux.  As a consequence, Git LFS, which has the same behavior here, is warning you that on macOS, the `.PSD` files are being run through the filter file even though they are not pointers.
