### ISSUE TITLE
Installation on Linux Mint 19.3 Tricia

### ISSUE THREAD

**Issue by thbeutin** [git-lfs/git-lfs#4056]
I tried to install `git-lfs` following the installation instructions on
`https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu`
and the script finished w/o error(s).

Howerver, the update of the available packages failed:

```
root@tokaido:/etc/apt/sources.list.d# apt-get update
[...]                                                 
Ign:14 https://packagecloud.io/github/git-lfs/linuxmint tricia InRelease                         
Err:15 https://packagecloud.io/github/git-lfs/linuxmint tricia Release      
  404  Not Found [IP: 52.52.73.223 443]
Reading package lists... Done                       
E: The repository 'https://packagecloud.io/github/git-lfs/linuxmint tricia Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by thbeutin** [comment]
Since Linux Mint 19.3 Tricia is based on Ubuntu 18.04 LTS (Bionic Beaver), the fix is changing

```
deb https://packagecloud.io/github/git-lfs/linuxmint/ tricia main
deb-src https://packagecloud.io/github/git-lfs/linuxmint/ tricia main
```
to
```
deb https://packagecloud.io/github/git-lfs/ubuntu/ bionic main
deb-src https://packagecloud.io/github/git-lfs/ubuntu/ bionic main
```
and everything works as expected.

I'll leave the issue open, because it's a bug that should be fixed.

**Comment by bk2204** [comment]
Hey,

Thanks for reporting this.  We don't typically track all of the various distros, so letting us know when we're missing one is helpful.  I'll try to get a patch opened for this so we can update the list of Mint versions.

**Comment by pellcorp** [comment]
Do you think there will there be any progress on this in the near future?   

Both mint 19.2 (Tina) and 19.3 (Tessa) are missing, would make life a whole lot easier if at least 19.3 were available.

I understand there are probably higher priorities, but this perhaps is a very low hanging fruit :-)

**Comment by bk2204** [comment]
I plan to fix this before the next release (hopefully today), but we don't build back versions for new OSes, since they're built and uploaded as part of the release process.  Our next release will likely be in early to mid April.

**Comment by sixtyfive** [comment]
Also just stumbled over this and found the Issue when googling. That's really confusing, any chance it'll get fixed eventually?

**Comment by bk2204** [comment]
The code has been merged to support these distros.  We're waiting on doing a release until we can get macOS signing in place, but we hope to do one this month.
