### ISSUE TITLE
The git-lfs command fails to interpret --help

### ISSUE THREAD

**Issue by austintraver** [git-lfs/git-lfs#4057]
**Describe the bug**
* The `git-lfs` command is unable to interpret the `--help` argument
* The `git lfs` command, on the other hand, has no problem interpreting the `--help` command.

**To Reproduce**

```sh
git-lfs asdf
# Error: unknown command "asdf" for "git-lfs"
# Run 'git-lfs --help' for usage.

git-lfs --help
# Sorry, no usage text found for "--help"
```

**Expected behavior**
* `git lfs --help` currently works fine, expected behavior occurs.
* `git lfs --help` does not, returns `Sorry, no usage text found for "--help"`

**System environment**
macOS Catalina v. 10.15.3 (latest
`git-lfs` v. 2.10.0

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
git version 2.25.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Additional Information**
(Tried on multiple users on macOS, tried on `bash` and `zsh`, tried on macOS and on Ubuntu, same result in all cases.

**Comment by bk2204** [comment]
Hey,

Thanks for reporting this, and I agree this output is unhelpful.  I'll be opening a PR shortly that fixes this, but in the mean time, if you want to view the help, `git lfs help` will display it for you.
