### ISSUE TITLE
git lfs migrate's .gitattributes entry for excluded files does not revert to Git's default EOL detection behaviour

### ISSUE THREAD

**Issue by woopla** [git-lfs/git-lfs#4067]
If I run `git lfs migrate import --include '*.pdf' --exclude 'foo/**'`, I'll end up with the following `.gitattributes`:
```
*.pdf filter=lfs diff=lfs merge=lfs -text
foo/** text -filter -merge -diff
```
If I now add, for example, a PNG file to foo and checkout that repository, Git will complain about CRLF/LF conversion.

If I change the last line in `.gitattributes` to:
```
foo/**/*.pdf text -filter -merge -diff
```

I'm not getting the warnings, but that still changes the behavior, only for PDF files this time around.

Could you guys change the `text` to `text="unspecified"` when creating the `.gitattributes` file? [According to the docs](https://git-scm.com/docs/gitattributes#_code_text_code), that should revert it to its default behavior.

Thanks,

Clément

**Comment by bk2204** [comment]
Hey,

I think it should be possible for us to write `!text` to make the attribute unspecified, but that of course comes with its own problems.  If the user has a filter higher up that does `* text=auto`, then of course that won't be applied.  Still, I think that's a better option.

**Comment by woopla** [comment]
At least that solves *my* simple case of no other `.gitattributes`, so I'm good :) Thanks!
