### ISSUE TITLE
Is it safe to upgrade the client

### ISSUE THREAD

**Issue by madsteer** [git-lfs/git-lfs#4069]
**Describe the issue**
I have git-lfs version 1.4.3, and git version 2.21.0 installed on my workstation.  I've been managing a personal git lfs repo using it.  Recently I went to pull down another repo that was set up with git lfs.  I got the error `error: external filter 'git-lfs smudge -- %f'` and based on issue #3614 I'm assuming it's a client version mismatch.  **My question is** can I update to a newer version of git-lfs, like say version 2.10.0, without breaking access to my current repo that's working fine with version 1.4.3?  I'd like to be able to use the newer repo but I can't break my existing repo.

**System environment**
macOS 10.14.6 Mojave

```
credential.helper=osxkeychain
filter.media.clean=git media clean %f
filter.media.smudge=git media smudge %f
filter.media.required=true
core.excludesfile=/Users/<user>/.gitignore_global
core.autocrlf=input
core.longpaths=true
core.whitespace=cr-at-eol
alias.mr=!sh -c 'git fetch $1 merge-requests/$2/head:mr-$1-$2 && git checkout mr-$1-$2' -
alias.lg=log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
alias.authors=! for branch in `git branch -r | grep -v HEAD`;do echo `git show --format="%ai %ar by %an" $branch | head -n 1`   $branch; done | sort -r
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
url.https://github.com/.insteadof=git@github.com:
credential.helper=osxkeychain
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
submodule.active=.
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

**Output of `git lfs env`**
```
git-lfs/1.4.3 (GitHub; darwin amd64; go 1.7.1; git 57234cb)
git version 2.21.0 (Apple Git-122)

LocalReferenceDir=
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
remote git server is a local install of gitlab for my company's enterprise

**Comment by bk2204** [comment]
Hey,

I just checked, and the file format should be the same, so your files should continue to work just fine across the upgrade.  Once you've done the upgrade, you'll probably want to re-run `git lfs install` so you can use the filter process, which is much faster.

However, without seeing more of the error you're getting, I can't tell you whether that will fix the error or not.  There are many reasons the filter can fail.  It will be much easier to troubleshoot if you're using the latest version, however, since 1.4.3 is quite old.

**Comment by madsteer** [comment]
initially, it seems to be fine to have upgraded.

**Comment by bk2204** [comment]
Great.  I'm going to close this since it seems to be working, but feel free to let us know if you continue to have problems and we'll reopen.
