### ISSUE TITLE
File size differences between GitHub desktop and azure

### ISSUE THREAD

**Issue by Krikisss** [git-lfs/git-lfs#4071]
When cloning the repository using GitHub Desktop, file size is not the same as it was uploaded. When downloading directly from azure, the file size is correct and the file is not corrupted, but with GitHub Desktop the problem appears like this:
` version https://git-lfs.github.com/spec/v1
oid sha256:c16523597d1e2d85b379fae287fa6c2e018494e47fe6239d3c9e155247c64cf4
size 4361285557
oid sha256:16fcf71ac647f0617c922ce2b427bf259813910bc3a26a971461a3104e9bbb29
size 66318261`

The git lfs is installed and all exceptions added, it was possible to upload this file from different computer, but when cloning repository on another computer, the problem appears and eventually the file is corrupted.

I am new to all this and not advanced at all but help would be much appreciated.

Not sure if relevant, but here are some info about the config
`$ git lfs env
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.25.1.windows.1
Endpoint=https://_Repo_@dev.azure.com/_Repo_/AB7/_git/AB7.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\_User_\GitHub\AB7
LocalGitDir=C:\Users\_User_\GitHub\AB7\.git
LocalGitStorageDir=C:\Users\_User_\GitHub\AB7\.git
LocalMediaDir=C:\Users\_User_\GitHub\AB7\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\_User_\GitHub\AB7\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\_User_\GitHub\AB7\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`

`$ git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
user.name=_user_
user.email=_user_@_page_
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.postbuffer=5000m
http.maxrequestbuffer=5000m
core.compression=0
core.repositoryformatversion=0
core.filemode=false
core.bare=false
`

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you try cloning this repository from the command line (say, Git Bash)?  It looks like your version of Git should be set up properly, so it would be great to see if any warnings or errors pop up when you try from the command line.

**Comment by Krikisss** [comment]
Hey,

Thanks for the suggestion. Cloned the repository using Git Bash and now got 2 files with problems. Here is the text that was shown on Git Bash:

`_User_@_computer_ ~/GitHub/AB7
$ git clone -b AR https://_Repo_@dev.azure.com/_Repo_/AB7
Cloning into 'AB7'...
remote: Azure Repos
remote: Found 77 objects to send. (222 ms)
Unpacking objects: 100% (77/77), 214.34 MiB | 753.00 KiB/s, done.
Updating files: 100% (18/18), done.
git lfs pull

Filtering content: 100% (15/15), 17.16 GiB | 4.40 MiB/s, done.
Encountered 2 file(s) that may not have been copied correctly on Windows:
        _File1_.nwd
        _File2_.7z

See: git lfs help smudge for more details.`

**Comment by bk2204** [comment]
Hey,

Thanks for this information.  On Windows, Git is limited to processing objects that are less than 4 GiB in size, and because Git LFS is by default invoked by Git, you'll end up with files that aren't properly checked out if you use the standard checkout process.

You can, however, use `git lfs pull` to check these files out, which it looks like you did here.  This message just means that it's not possible to check these files out automatically on Windows due to this limitation in Git.

If you're only seeing this with GitHub Desktop, you could ask them to automatically run `git lfs pull` if the repository is using Git LFS on Windows, which should fix the problem you're seeing.  You'd want to file that issue over in the `desktop/desktop` repository, though.
