### ISSUE TITLE
Using sudo only where needed in installation scripts

### ISSUE THREAD

**Issue by dHannasch** [git-lfs/git-lfs#4072]
Currently, https://github.com/git-lfs/git-lfs/wiki/Installation requires running the entire installation script with `sudo`. This means running many commands with privileges they don't need. (And causes miscellaneous headaches like the user's `.curlrc` configuration being ignored, so the script fails in any unusual network setup requiring a `.curlrc`.)

https://github.com/dHannasch/git-lfs-install-scripts/commit/66c06659bfc4ef1deea6a88da1fbfff8decc40ee shows how we can apply sudo only to the commands that require it.
(I'd open a pull request, but the installation scripts (https://packagecloud.io/github/git-lfs/install) don't appear (?) to be in version control.)

The shown `sudo tee` is a standard practice for when the only operation that needs privileges is the file writing, as seen in e.g. https://help.ubuntu.com/lts/serverguide/serverguide.pdf .

**Comment by bk2204** [comment]
Hey,

These installation scripts are a generic packagecloud.io installation script that is maintained by them.  We don't have any way to modify them or adjust them.  You're welcome to reach out to them and ask if they'll make changes.

However, one note: while I am familiar with the preferred approach, I will also note that it is possible to force `sudo` to always prompt for a password, in which case your proposed changes will require multiple password entries.

You can also extract the URL produced by the script and write that directly into a file in `/etc/apt/sources.list.d` (or the `yum` equivalent) if you'd rather avoid running `sudo` altogether.
