### ISSUE TITLE
Issue pushing Git LFS files to GitLab CE Server

### ISSUE THREAD

**Issue by Xenixi** [git-lfs/git-lfs#4074]
Unable to push lfs files to GitLab  server.
Getting this error:
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
LFS: Put http://git.example.com:9998/games.devoid/Devoid.git/gitlab-lfs/objects/d9a5b8fde1e0e6918ae6775d258ce582dd96665506dfe3f9d42785660b713e33/23964160: dial tcp ...:9998: connectex: No connection could be made because the target machine actively refused it.
error: failed to push some refs to 'http://git.example.com:9998/games.devoid/Devoid.git'

Port 9998 is open and accessible, and lfs is enabled for the repo.

**Comment by bk2204** [comment]
Hey,

It looks like you're on Windows, and this message usually means that there's a firewall in place that's preventing the connection.  Can you try disabling (and if it's a third-party firewall, completely uninstalling) your firewall and trying again?  If you have antivirus software other than Windows Defender, can you do the same with it as well?

**Comment by Xenixi** [comment]
> Hey,
> 
> It looks like you're on Windows, and this message usually means that there's a firewall in place that's preventing the connection. Can you try disabling (and if it's a third-party firewall, completely uninstalling) your firewall and trying again? If you have antivirus software other than Windows Defender, can you do the same with it as well?
Thanks, I ended up solving the problem. It had something to do with a dns config that wasn't properly setup. After resetting the dns settings and starting again, I was able to access the server without a problem. Closing this issue.
