### ISSUE TITLE
"Fatal Error: Server Error" on git push

### ISSUE THREAD

**Issue by Xenixi** [git-lfs/git-lfs#4075]
Trying to commit about 674 bytes of files tracked by git lfs with this command: GIT_TRACE=1 git push
Excerpt from console output:

`891469e265d0136d9b004a081ecd811a/258562
15:51:30.490069 trace git-lfs: HTTP: 500
15:51:30.490069 trace git-lfs: HTTP: 500
15:51:30.490069 trace git-lfs: tq: refusing to retry "721fdf16dfff3f0a667cc134bb9a5eef6b3a454123af40f871e78ac00ef83e42", too many retries (8)
15:51:30.490069 trace git-lfs: tq: refusing to retry "721fdf16dfff3f0a667cc134bb9a5eef6b3a454123af40f871e78ac00ef83e42", too many retries (8)
15:51:30.490069 trace git-lfs: tq: refusing to retry "803a18e05866967f4325528e90bd22ebe2e94a53cf01098062c1f9ca151b69c2", too many retries (8)
15:51:30.490069 trace git-lfs: tq: refusing to retry "803a18e05866967f4325528e90bd22ebe2e94a53cf01098062c1f9ca151b69c2", too many retries (8)
15:51:30.492066 trace git-lfs: HTTP: 500
15:51:30.492066 trace git-lfs: tq: refusing to retry "a25e29c6bae9a29a092a996e2b0a0aa8a147a4f207e2b5a6061a7f1c99ab7c2f", too many retries (8)
15:51:30.492066 trace git-lfs: tq: refusing to retry "a25e29c6bae9a29a092a996e2b0a0aa8a147a4f207e2b5a6061a7f1c99ab7c2f", too many retries (8)
15:51:30.632068 trace git-lfs: HTTP: 500
15:51:30.633067 trace git-lfs: tq: refusing to retry "65d5eacc55e42b167aca6b50a5688af03d2e60321697b2aa29c6bab6a25ed2ff", too many retries (8)
15:51:30.633067 trace git-lfs: tq: refusing to retry "65d5eacc55e42b167aca6b50a5688af03d2e60321697b2aa29c6bab6a25ed2ff", too many retries (8)
15:51:30.635066 trace git-lfs: HTTP: 500
15:51:30.635066 trace git-lfs: tq: refusing to retry "21e028d539f26ae104f2d0d59ca17da55b7a9e1b0073becc398c564b022bcede", too many retries (8)
15:51:30.635066 trace git-lfs: tq: refusing to retry "21e028d539f26ae104f2d0d59ca17da55b7a9e1b0073becc398c564b022bcede", too many retries (8)
15:51:30.637067 trace git-lfs: HTTP: 500
15:51:30.637067 trace git-lfs: tq: refusing to retry "2b67f47129e2abc64d3c466af6597601228900f3ff753b8b9b6a6cc467a70c2e", too many retries (8)
15:51:30.637067 trace git-lfs: tq: refusing to retry "2b67f47129e2abc64d3c466af6597601228900f3ff753b8b9b6a6cc467a70c2e", too many retries (8)
15:51:30.705071 trace git-lfs: HTTP: 500KB | 30 KB/s
15:51:30.705071 trace git-lfs: HTTP: 500
15:51:30.734068 trace git-lfs: tq: refusing to retry "f47e92b4c8807794a6df0a9b0b96a0291e6f0330d6a93a04d6d275dc18e8c621", too many retries (8)
15:51:30.734068 trace git-lfs: tq: refusing to retry "f47e92b4c8807794a6df0a9b0b96a0291e6f0330d6a93a04d6d275dc18e8c621", too many retries (8)
15:51:30.734068 trace git-lfs: tq: refusing to retry "37833b82bfafd81e06f2365b3b1b01f8891469e265d0136d9b004a081ecd811a", too many retries (8)
15:51:30.734068 trace git-lfs: tq: refusing to retry "37833b82bfafd81e06f2365b3b1b01f8891469e265d0136d9b004a081ecd811a", too many retries (8)
Uploading LFS objects:   0% (0/22), 336 KB | 30 KB/s, done.
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/94ba818b5cf7a2eaf555d4c51b4f4b8ee084829a75892f84e0efb0976c4c4d9e/3006111
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/7ec2cc4d72d92a1faf7771c3053cae70e2c88c5b6676053c216acd80f2a6d39d/1884776
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/2cccf2515c41db3de787a6d8b8688e7cfc6755c22856a39e93ce44ba44baeb69/2088450
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/00605a254664cfae8611b91a8e3d6f1a2f6b54b29f30e4a500eba075f72a7736/2982540
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/7b840592716b95ab332925ab75b37e56d5999a3c9b11492a954742dd7d2b012e/2253480
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/ae4652c1beabe499b75e17afd0963e2f3fe99b938c2712a5b37ca02f67f68b57/1806467
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/eb8d25b2c78ac83b8a9b8c69fa626ec844fdfc029801fcda2b215be6156d33e6/1859857
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/0a92fbbbb4ad4f682c4835e15dcdf7d71f26e7c64a7f1f4c24a591192a46f687/2084611
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/17bf0ecfed2cc094802ec0dc0684a56d269642e12707d44bee82192db45fb4ef/1802347
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/58fde8455889e52bfd91aff37ad93d7dfe7c4e9b464dfec354cf69e244933179/1693478
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/48bd2f64af7b3dae6871f7e54d86b922a3c6bfa65f0fd70411d1c08ef1fe7045/1681909
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/8ed5f5a405aeac50f5b0fead678bb489f2359890e5cb7b3cdb01261bfc6ed7bc/1801411
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/939e6f4866ed8376024385cb131427ccdbd22653f1b0a89a88e07b4bb4b5d38a/1534253
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/b424b06467b1c48c099ca937d6ef23a662f88224f6828cf06500be3b16b2d614/1605028
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/721fdf16dfff3f0a667cc134bb9a5eef6b3a454123af40f871e78ac00ef83e42/1429524
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/803a18e05866967f4325528e90bd22ebe2e94a53cf01098062c1f9ca151b69c2/1549880
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/a25e29c6bae9a29a092a996e2b0a0aa8a147a4f207e2b5a6061a7f1c99ab7c2f/1425933
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/65d5eacc55e42b167aca6b50a5688af03d2e60321697b2aa29c6bab6a25ed2ff/1232218
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/21e028d539f26ae104f2d0d59ca17da55b7a9e1b0073becc398c564b022bcede/1388294
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/2b67f47129e2abc64d3c466af6597601228900f3ff753b8b9b6a6cc467a70c2e/1205716
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/f47e92b4c8807794a6df0a9b0b96a0291e6f0330d6a93a04d6d275dc18e8c621/1200880
Fatal error: Server error: http://server.example.com:9998/DevoidDevelopment/Devoid.git/gitlab-lfs/objects/37833b82bfafd81e06f2365b3b1b01f8891469e265d0136d9b004a081ecd811a/258562
error: failed to push some refs to 'http://server.example.com:9998/DevoidDevelopment/Devoid.git'`

**Comment by bk2204** [comment]
Hey,

The message `Server error` means that the remote side sent an HTTP 500 error, which indicates that it had some sort of internal error.  This isn't a bug in Git LFS, but rather a problem with the server.  You should probably contact the server administrator and ask them to look at the logs and figure out what went wrong.
