### ISSUE TITLE
`git push` will upload LFS objects even if no LFS file was changed

### ISSUE THREAD

**Issue by ptarjan** [git-lfs/git-lfs#4076]
**Describe the bug**
After doing a `git lfs install`, whenever a user does a `git push` they will be greeted with a 10 second prompt that results in:
```
Uploading LFS objects: 100% (8211/8211), 1.0 GB | 0 B/s, done.
```

Is there a way to make `git lfs` only do this song and dance when a file being changed has the `lfs` attribute?

Having read https://github.com/git-lfs/git-lfs/blob/a5e6104da92bcefb87b66447a8a63c04311b0785/commands/command_pre_push.go#L36-L37 I'm guessing this is because we use phabricator and `arc diff` creates a new branch for every diff push. Is there any way around this?

**System environment**
```
$ git version
git version 2.25.1
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
git version 2.25.1

Endpoint=https://github.com/<dir>.git/info/lfs (auth=none)
  SSH=git@github.com:<dir>.git
LocalWorkingDir=/Users/paul.tarjan/<dir>
LocalGitDir=/Users/paul.tarjan/<dir>/.git
LocalGitStorageDir=/Users/paul.tarjan/<dir>/.git
LocalMediaDir=/Users/paul.tarjan/<dir>/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/paul.tarjan/<dir>/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/paul.tarjan/<dir>/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.25.1/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

We have several optimizations here that can help avoid this.  If you use a named remote, anything reachable from the named remote's remote tracking branches is excluded from consideration.  Additionally, if you're pushing multiple refs, we consider all of the objects the server already has for all of the refs we're pushing, so we don't need to crawl them all multiple times.

If you're using a URL remote, then there isn't really anything we can do here, since we need to know what the remote side has, and if you're creating a new branch, then we know nothing about that, so we must crawl the entire history.  We will avoid requiring LFS objects locally that the remote side already has, but that's the only safe optimization we can use.

I don't know what type of remote `arc diff` is using, but if it's using a URL and it can be switched to use a named remtoe, that will likely solve the problem.

**Comment by ptarjan** [comment]
Thanks for getting back to me so fast! I'm happy to hear there are actual mitigations.

Here seems to be what `arc diff` is doing: https://github.com/phacility/arcanist/blob/master/src/workflow/ArcanistDiffWorkflow.php#L2828-L2953

When you say a named remote, do you mean that instead of using a `$staging_uri` here https://github.com/phacility/arcanist/blob/master/src/workflow/ArcanistDiffWorkflow.php#L2866 I should patch it to do a `git remote add staging $staging_uri` and then push to `staging` instead (with a `git remote rm staging` after)?

I guess the surprising thing to me is that it has to walk ALL the `lfs` files instead of just the ones that are new to my change. I think `arc` pushes two tags, one being the base branch and then one for my diff ontop. So in theory I'd love to only inspect and push the `lfs` files between those two branches, since the `base` branch's sha is already on the server, we are just making a new tag for it.

Thanks again. I'm happy to try to upstream patches to phabricator based on your recommendations or just fork it internally for us.

**Comment by ptarjan** [comment]
To make it more concrete, here is the current command that `arc diff` runs:

```
git push -- git@github.<repo>.git ef759f60624d9a96bb2583b698041793a79ecbcf:refs/tags/phabricator/base/426348 2418ad0c6262b1b3f4dc69980160eec42023be91:refs/tags/phabricator/diff/426348
```

**Comment by bk2204** [comment]
> Thanks for getting back to me so fast! I'm happy to hear there are actual mitigations.
> 
> Here seems to be what `arc diff` is doing: https://github.com/phacility/arcanist/blob/master/src/workflow/ArcanistDiffWorkflow.php#L2828-L2953

Yup, that looks like the problem.
 
> When you say a named remote, do you mean that instead of using a `$staging_uri` here https://github.com/phacility/arcanist/blob/master/src/workflow/ArcanistDiffWorkflow.php#L2866 I should patch it to do a `git remote add staging $staging_uri` and then push to `staging` instead (with a `git remote rm staging` after)?

Yes, that's exactly what I mean.

> I guess the surprising thing to me is that it has to walk ALL the `lfs` files instead of just the ones that are new to my change. I think `arc` pushes two tags, one being the base branch and then one for my diff ontop. So in theory I'd love to only inspect and push the `lfs` files between those two branches, since the `base` branch's sha is already on the server, we are just making a new tag for it.

The way the `pre-push` hook (which is what we use to push LFS objects) works is that we get the local and remote refs and object IDs.  If we're creating a new branch, the old object ID is all zeros, and we don't know anything about what the server has unless the remote is named, in which case we can assume we have have all of the objects that the remote tracking branches have.

When we crawl the history with `git rev-list`, we therefore have to walk every object in the history of your branch, because we have no stopping points.

> Thanks again. I'm happy to try to upstream patches to phabricator based on your recommendations or just fork it internally for us.

I would definitely recommend using a named remote here.  It's possible that we could use existing remote tracking branches if a remote exactly matches the push URL of a named remote, but we don't currently do that.

**Comment by ptarjan** [comment]
Thanks again for the context.

I tried your suggestion and sadly it didn't help, the upload was still going through even if it was a named remote. I originally made a unique name for the remote for each diff to avoid collisions (e.g. `phabricator-staging-12345`) but then I thought that might bust the cache so I re-used the same name (e.g. `phabricator-staging`) and it still didn't help.

Could this be because phabricator is using tags and not branches for everything? When I run `arc diff` it pushes two tags, one for `base` and one for `diff`. Is there something I should try changing into branches which would make your caches hit? Should I just convert all the tag pushes to branches (and is there any downside to that)?

**Comment by ptarjan** [comment]
Dang, I tried switching from tags to branches and it still keeps walking the full lfs tree on every `arc diff`, even if the shas don't change.
```
-    $base_tag = "refs/tags/{$prefix}/base/{$id}";
-    $diff_tag = "refs/tags/{$prefix}/diff/{$id}";
+    $base_tag = "refs/heads/{$prefix}/base/{$id}";
+    $diff_tag = "refs/heads/{$prefix}/diff/{$id}";
```

**Comment by bk2204** [comment]
Have you run a `git fetch` on that remote?  If you don't fetch the remote, the remote-tracking branches won't be populated, so we won't have any references to consider as roots of our walk.

**Comment by ptarjan** [comment]
Great idea! Yes! And indeed I was not, and once I started doing that it worked! No more 30 second long lfs walks on every push.

Here is my proposed change to `arc diff`: https://secure.phabricator.com/D21041

Do you see anything wrong with this new process? I'm thinking the extra `git fetch` might be more expensive for folks that don't have `git lfs` and I don't know the overhead of branches vs tags.

**Comment by bk2204** [comment]
As far as Git LFS is concerned, branches and tags are indistinguishable, so you don't need to change that unless there are no remote branches to fetch.

You may want to do the `git fetch` only if the remote doesn't have any remote items, which you can determine by an empty value from `git for-each-ref refs/remotes/phabricator-staging`.  Doing the fetch unconditionally can break some features such as `git push --force-with-lease` that expect those values not to be updated implicitly, but that wouldn't be a problem if no remote heads are available.

**Comment by ptarjan** [comment]
> As far as Git LFS is concerned, branches and tags are indistinguishable, so you don't need to change that unless there are no remote branches to fetch.

Staging repos for phabricator actually don't usually have any branches at all (and even often have a `master` pointing at an orphaned root not related to the stuff you're diffing). In this case do we have to use branches or is there another recommendation?

> You may want to do the git fetch only if the remote doesn't have any remote items, which you can determine by an empty value from git for-each-ref refs/remotes/phabricator-staging. Doing the fetch unconditionally can break some features such as git push --force-with-lease that expect those values not to be updated implicitly, but that wouldn't be a problem if no remote heads are available.

Thanks! I updated the diff to do that.

**Comment by ptarjan** [comment]
the author of phabricator pushed back on the suggestion and instead  was suggesting doing two pushes, one where `git lfs` isn't involved and then another to update an existing tag in a way that `git lfs` should be able to tell what to push.

I was trying that but I can't seem to find a way to disable `git lfs` during a push, is there a way? He was suggesting `GIT_LFS_SKIP_SMUDGE=1` but that seems to only be for fetching.

And if his suggestion isn't feasible, do you have another proposal which might be more palatable? Thanks!

**Comment by bk2204** [comment]
Remote tracking branches are, well, only for branches, not tags.  So if you don't have any branches on the remote to fetch, then the remote optimization just won't work for you at all.

You can skip the `pre-push` hook with `git push --no-verify`, so you could do the push by pushing the head tag to be the same as the base tag at first with that option and then push the head tag to have the new value, which will allow the traversal to only consider new objects.  However, that will simply disable any `pre-push` hook, including any additional items that the user may have added themselves.

**Comment by ptarjan** [comment]
Ok! So your suggestion worked like a charm, thanks so much. Phabricator will just uploaded the base branch with `--no-verify` and then push an update to the tag with the commit, and `git-lfs` understands the caching behavior now.

I'll close my issue since I'm personally resolved, but if you want to leave something open to cache for URLs instead of named things I can make another one for you if you want.

Thanks again for your help!
