### ISSUE TITLE
Read .lfsconfig from repository if absent from working tree

### ISSUE THREAD

**Issue by matti-cujo** [git-lfs/git-lfs#4077]
**Describe the bug**

`git clone` doesn't honor the `lfs.url` setting from `.lfsconfig` for some files. By the looks of it the problem is with files that are sorted alphabetically prior to `.lfsconfig` itself.

**To Reproduce**
Steps to reproduce the behavior, let's say with a GitHub repo but requiring also a different LFS server:
1. Create a new repo in GitHub with a `.lfsconfig` pointing to a different Git LFS server
2. Create and push an LFS-tracked file called `.abigfile`: `git lfs track .abigfile && echo "hello world" > .abigfile && git add -A && git commit -m test && git push`
3. `git clone git@github.com:your-repo` and observe the error:

```
[..]
Receiving objects: 100% (5/5), done.
Downloading .abigfile (12 B)
Error downloading object: .abigfile (a948904): Smudge error: Error downloading .abigfile (a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447): [a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447] Object does not exist on the server: [404] Object does not exist on the server
[..]
```

4. Verify that the file is actually available: `git lfs pull && git checkout -f HEAD && cat .abigfile` produces "hello world" as expected
5. Move it to a different path (remove leading `.`): `git mv .abigfile abigfile && git lfs untrack .abigfile && git lfs track abigfile && git commit -am test2 && git push`
6. `git clone git@github.com:your-repo` now reports no errors and `cat abigfile` produces "hello world" as expected

Using `GIT_TRACE=1` shows that in step 3 it's trying to get it from `lfs.github.com` instead of the URL specified in `.lfsconfig`, whereas in step 6 it uses the correct URL.

The `GIT_TRACE=1` outputs diverge here:

```
[..]
Receiving objects: 100% (8/8), done.
09:39:22.258562 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs '--progress=Checking connectivity'
09:39:22.263653 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs '--progress=Checking connectivity'
09:39:22.298787 run-command.c:663       trace: run_command: 'git-lfs filter-process'
07:39:22.336627 trace git-lfs: exec: git 'version'
07:39:22.347550 trace git-lfs: exec: git 'config' '-l'
07:39:22.353481 trace git-lfs: exec: git 'config' '-l' '-f' '/tmp/test-lfs-2/.lfsconfig'
[..]
```

The last line is not present when the LFS file is called `.abigfile`.

**Expected behavior**
The URL specified in `.lfsconfig` should always be used when fetching LFS files.

**System environment**
Arch Linux but I don't think it's relevant. I don't think I have any configurations that could affect this.

**Output of `git lfs env`**
From within one of the test repos:
```
git-lfs/2.10.0 (GitHub; linux amd64; go 1.14)
git version 2.25.2

Endpoint=<the expected one>
LocalWorkingDir=/tmp/test-lfs
LocalGitDir=/tmp/test-lfs/.git
LocalGitStorageDir=/tmp/test-lfs/.git
LocalMediaDir=/tmp/test-lfs/.git/lfs/objects
LocalReferenceDirs=
TempDir=/tmp/test-lfs/.git/lfs/tmp
ConcurrentTransfers=32
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/tmp/test-lfs/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

I fully expect that this is the case, since we read the `.lfsconfig` file from the working tree, regardless of whether or not it's actually a part of the repository.  In this way, it's much like `.gitattributes`.

Currently our limitation on doing something different is that checkout happens before `HEAD` is set, and consequently, we don't know during a `git clone` what revision is being checked out.  We therefore can't inspect the repository and query for the appropriate file.  There are patches currently sitting in Git's `next` branch that will allow us to do this, so once those are available, we can consider improving this.
