### ISSUE TITLE
Fail to install git-lfs package on Ubuntu 16.04 

### ISSUE THREAD

**Issue by jeeloo** [git-lfs/git-lfs#4078]
It seems the repository for Ubuntu Xenial is not working I get the following message when trying to do "apt update" now. 

```
Reading package lists... Done
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
It have worked fine previously, don't know when it stopped working exactly. I have the following file that specifies the repo to use. 

```
$ cat /etc/apt/sources.list.d/github_git-lfs.list 
deb https://packagecloud.io/github/git-lfs/ubuntu xenial main
```

**Comment by bk2204** [comment]
Hey,

I'm not sure why you're seeing this.  Putting that line in an Ubuntu xenial Docker container does seem to work for me, and it's substantially similar to the one that's newly generated.  I also verified that at least at the moment, there are both `Release` and `InRelease` files there. 

Can you tell me more about your setup?  Are you using a bare system or a container?  Is it up to date with the latest version of xenial?  Are you perhaps using a proxy or some sort of MITM certificate device?  Are the `ca-certificates` and `apt-transport-https` packages installed?

**Comment by jeeloo** [comment]
Hi,
Looks like it working again on my end, don't know what has changed. But probably related to the proxy then, I was misbehaving for a bit last week.
