### ISSUE TITLE
git-lfs (still) hangs on checkout

### ISSUE THREAD

**Issue by mdeisher** [git-lfs/git-lfs#4079]
This bug seems to be back:
https://github.com/git-lfs/git-lfs/issues/3801

At the end of a clone or checkout, git-lfs hangs.  To reproduce:
GIT_CURL_VERBOSE=1 git checkout -f

The relevant output is:

14:38:54.559952 trace git-lfs: api error: Post [URL REMOVED]/info/lfs/objects/batch: net/http: TLS handshake timeout
14:38:54.559952 trace git-lfs: tq: sending batch of size 100

This is on Windows using Git-2.26.0-64-bit.exe.  Each time I kill after hang (using CTRL-C in the shell), the git-lfs process does not die.  I have to manually go into task manager and kill it.

Expected behavior:  checkout should succeed they way it always has (for years) on this repository.

System:  Windows 10 64 bit, Git 2.26.0

Environment:
$ git lfs env
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.0.windows.1

Endpoint=https://[PATHNAME REMOVED]/info/lfs (auth=none)
  SSH=git@[PATHNAME REMOVED]
LocalWorkingDir=D:\[PATHNAME REMOVED]
LocalGitDir=D:\[PATHNAME REMOVED]\.git
LocalGitStorageDir=D:\[PATHNAME REMOVED]\.git
LocalMediaDir=D:\[PATHNAME REMOVED]\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\[PATHNAME REMOVED]\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\[PATHNAME REMOVED]\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

I think your problem is this line:
```
14:38:54.559952 trace git-lfs: api error: Post [URL REMOVED]/info/lfs/objects/batch: net/http: TLS handshake timeout
```

This message means that Git LFS tried to make a connection to the remote host but couldn't because the TLS connection handshake couldn't be established.  If you fix that, things will likely work.  You'd probably want to figure out if there's a network, proxy, or MITM TLS device issue, or alternately, contact the administrator of the server and ask them what's going on.

You could also try setting `lfs.tlstimeout` to something higher than 30 (the default in seconds) and see if that helps.

**Comment by mdeisher** [comment]
It turned out that changing the Windows Git Bash client to use native Windows Secure Channel library instead of OpenSSL solved this.  It is pretty strange since OpenSSL worked just fine here for years.

**Comment by bk2204** [comment]
Hey,

I'm not sure why changing the crypto library would fix this, since Go has its own crypto and TLS library that doesn't use either SChannel or OpenSSL.  But I'm glad that it's working for you now, and since this appears to be working, I'm going to close this issue.
