### ISSUE TITLE
git lfs push: file already closed

### ISSUE THREAD

**Issue by golyalpha** [git-lfs/git-lfs#4085]
**Describe the bug**
I have three files that are handled by LFS, all of them report the `read [filepath]: file already closed` error

**To Reproduce**
Running on Windows 10
1. Create a new repository add a remote with LFS support and a file to track with LFS
2. `git lfs install`
3. `git lfs track [file]`
4. `git push` or `git lfs push`, filepath in the error will point to the lfs object file

**Expected behavior**
Successful push

**System environment**
Win10 Pro 1909

**Output of `git lfs env`**
```
> git lfs env
git-lfs/2.9.2 (GitHub; windows amd64; go 1.12.7; git 0274d856)
git version 2.25.0.windows.1

Endpoint=https://[REDACTED]/namespace/repo.git/info/lfs (auth=basic)
LocalWorkingDir=[REDACTED]
LocalGitDir=[REDACTED]\.git
LocalGitStorageDir=[REDACTED]\.git
LocalMediaDir=[REDACTED]\.git\lfs\objects
LocalReferenceDirs=
TempDir=[REDACTED]\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=[REDACTED]\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_TRACE=0
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
The server is running GitLab CE (or rather EE in the Core tier) with the requests to upload, as far as I can tell, not reaching past the nginx reverse proxy it's behind. I've done some investigation, and here's the output from nginx's error logs after enabling the info error log level:
```
2020/03/28 15:46:03 [info] 30072#30072: *68278 client prematurely closed connection, client: [REDACTED], server: [REDACTED], request: "PUT /namespace/repo.git/gitlab-lfs/objects/8b5ba7bf6cf9eb884ffa96f3f7e66c67be099463e79202d2bed11838ec8d830a/69625003 HTTP/1.1", host: "[REDACTED]"
```
The request is not being terminated with error 413(Request Body Too Large), but with error 400 (Bad Request), which is in line with the client (git-lfs) terminating the connection too early.

**Comment by golyalpha** [comment]
So, I just checked, uploaded to GitLab.com, and there it worked fine, not entirely sure what's up, but I did already check that there isn't a file upload limit in the site configuration for the GitLab proxy, and I did confirm once more that the request is not getting passed along to the GitLab server.

**Comment by golyalpha** [comment]
Another update. I've disabled request and response buffering, so everything from git-lfs should be immediately forwarded to the gitlab application, but it seems that LFS is (most of the time) closing the connection sooner than nginx can establish connection with gitlab. And when it does reach it, GitLab just complains about the same thing nginx does - that the connection got closed by the client prematurely.

**Comment by bk2204** [comment]
Hey,

This message usually comes when the request fails in a certain way and we need to retry the operation.  I believe this was fixed #4042, which will be in the next release.  In the mean time, you can try building the latest `master` branch (or pulling the binaries from the CI job artifacts) and seeing if that works for you or if you get a different error.

**Comment by golyalpha** [comment]
Heh, building from source on Windows... This is gonna be fun...

I'll see what I can do, and will post an update later.

**Comment by bk2204** [comment]
As mentioned, you can also pull from the artifacts by going into one of the CI job pages.  For example, the latest `master` has binaries for Windows at https://github.com/git-lfs/git-lfs/runs/549378830 which you can use, although of course they aren't signed.

**Comment by golyalpha** [comment]
It seems the issue has in fact been fixed in the newer build of git-lfs. Thanks for the help.

**Comment by ZitRos** [comment]
I spent a lot of time on kubernetes and ingress to finally land here. Waiting for the new git-lfs release! :)

**Comment by dehengxu** [comment]
May be this is useful : https://github.com/git-lfs/git-lfs/issues/3698

**Comment by PasaOpasen** [comment]
Try to just upgrade your `git-lfs`

On Ubuntu 20 it's too old by default and must be upgraded by 
```sh
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt install git-lfs
```
