### ISSUE TITLE
complain "missing protocol" when clone a repo with "ext::ssh" URL

### ISSUE THREAD

**Issue by cherrot** [git-lfs/git-lfs#4086]
**Describe the bug**
I have a git repo in my local network. I plan to use a remote URL like `ext::ssh -t -J JumpHost MyHost %S repo/worklog.git` to access to this repo in a public network, according to https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-remote-ext.html

I tried to make a fresh clone then I got the following errors:

```
Downloading image.png (692 KB)
Error downloading object: image.png (b5d0032): Smudge error: Error downloading image.png (b5d..lang..hash): batch request: missing protocol: "ext::ssh -t -J JumpHost MyHost %S repo/worklog.git/info/lfs"

Errors logged to /private/tmp/worklog/.git/lfs/logs/20200330T185939.266187.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
```

**To Reproduce**
1. Setup a git repo on a ssh host. Commit some `git-lfs` files to it.
2. On the same host, run the following command:
``` shell
git config --global protocol.ext.allow user
git clone 'ext::ssh -t -J localhost localhost %S path/to/repo.git' sample
```

**Expected behavior**
Clone successfully.

**System environment**
output of `git config -l` under the broken cloned repo. (System: MacOS 10.15)
```
credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=cherrot
user.email=myemail@gmail.com
diff.tool=vimdiff
merge.tool=vimdiff
core.ignorecase=false
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
protocol.ext.allow=user
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.precomposeunicode=true
remote.origin.url=ext::ssh -t -J home nas %S repo/worklog.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
git version 2.26.0

Endpoint=ext::ssh -t -J home nas %S repo/worklog.git/info/lfs (auth=none)
LocalWorkingDir=/private/tmp/worklog
LocalGitDir=/private/tmp/worklog/.git
LocalGitStorageDir=/private/tmp/worklog/.git
LocalMediaDir=/private/tmp/worklog/.git/lfs/objects
LocalReferenceDirs=
TempDir=/private/tmp/worklog/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/private/tmp/worklog/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.26.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

It's pretty much by design that we don't support external helpers or foreign types of remotes.  Because the protocol substantially differs between SSH, HTTP, and standalone transfer helpers, there isn't a way that we can automatically determine which one to use for an external helper.  With plain Git, the protocol is similar enough that it's obvious which protocol to use.

There are some options, however.  You can specify something like the following in your `~/.ssh/config`:
```
Host nas
    RequestTTY force
    ProxyJump home
```
and then use the URL `ssh://nas/repo/worklog.git`.  You could also specify an `lfs.url` field in your local configuration pointing to a suitable URL, or you could use a standalone transfer adapter to push (there's documentation in `doc/` on how to write one).

**Comment by cherrot** [comment]
Thank you for the quick response and detailed explanation! 

Adding the following config into my `~/.ssh/config` solves my problem perfectly.

```ssh
Host nas
    RequestTTY yes
    ProxyJump home
```
