### ISSUE TITLE
Unable to parse HTTP response for POST https://gerritgitltst.com:443/demo-lfs/info/lfs/objects/batch: EOF

### ISSUE THREAD

**Issue by AnishAnil** [git-lfs/git-lfs#4093]
**Describe the issue**
Unable to push to Git LFS

**System environment**
All RHEL System 
We are trying to push it from the gerrit master itself.
git clone and followed all instructions.

**Output of `git lfs env`**
git lfs env
git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4; git a526ba6b)
git version 2.18.2

Endpoint=https://gerritgitltst.com/demo-lfs.git/info/lfs (auth=none)
  SSH=abcdef@gerritgitltst.com:demo-lfs
LocalWorkingDir=/tmp/test/demo-lfs
LocalGitDir=/tmp/test/demo-lfs/.git
LocalGitStorageDir=/tmp/test/demo-lfs/.git
LocalMediaDir=/tmp/test/demo-lfs/.git/lfs/objects
LocalReferenceDirs=
TempDir=/tmp/test/demo-lfs/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/tmp/test/demo-lfs/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
 

**Additional context**
 git push
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://gerritgitlfstst.com/demo-lfs.git/info/lfs.locksverify false
batch response: Unable to parse HTTP response for POST https://gerritgitltst.com:443/demo-lfs/info/lfs/objects/batch: EOF
error: failed to push some refs to 'ssh://abcdef@gerritgitltst.com:29418/demo-lfs'

**Comment by bk2204** [comment]
Hey,

This message, `EOF`, means that we expected to get a JSON blob as a response but for whatever reason we didn't get one.  That could be for a lot of reasons, all of which are server related.  An example could be a dropped connection before reading headers.

You can try running your push with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`, which should provide some helpful debugging output and possibly information about what data you actually are getting from the server, if any.

**Comment by bk2204** [comment]
Hey,

It doesn't look like there's been a response to this recently, so I'm going to close it.  If you can provide the additional information we've requested, let us know and we'll reopen.
