### ISSUE TITLE
Using minio object storage server for LFS 

### ISSUE THREAD

**Issue by sarats** [git-lfs/git-lfs#4094]
I am interested in setting up LFS to store files in a MinIO object storage server (https://min.io/). 

I noticed that there is support for using MinIO in Gitlab: https://docs.gitlab.com/ee/administration/lfs/index.html
However, I wish to understand if it is feasible to use my standalone MinIO instance along with a Git repository in Github+LFS. I apologize if this is related to Github backend support as it was unclear if LFS pointers can point to custom servers on client side.

**System environment**
CentOS 7.7

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.10.0 (Fedora %{fedora}; linux amd64; go 1.13.6)
git version 1.8.3.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

The pointer files are the same regardless of the server being used.  In the typical case, they consist of a version identifier, an object ID (that is, a SHA-256 hash of the object), and a size.  In fact, you can push exactly the same LFS pointers to multiple LFS servers, and people often do this if they're working with LFS and multiple repositories.

As for the server, there are two things that you need for an LFS server: some sort of storage and an API server.  github.com always uses S3 for storage, and GitHub Enterprise server always uses its own internal object storage.  However, you can use a GitHub server with an independent LFS server if you like, and you can check out the [Implementations page on the wiki](https://github.com/git-lfs/git-lfs/wiki/Implementations) for options that may support MinIO.  The `lfs.url` option may be useful to you in this case.
