### ISSUE TITLE
git push --tags doesn't complete/work

### ISSUE THREAD

**Issue by provegard** [git-lfs/git-lfs#4098]
**Describe the issue**

We have recently moved origin, and we have ~4000 tags that we want to push to the new origin. The visual effect is that `git push --tags` "hangs".

Running `GIT_TRACE=1 git push --tags` reveals that the reason it takes time are these operations that repeat over and over again:

```
21:00:42.993433 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:42.995488 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:43.185693 trace git-lfs: HTTP: 200
21:00:43.186897 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

21:00:43.192691 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:43.194810 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:43.380386 trace git-lfs: HTTP: 200
21:00:43.380869 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

21:00:43.386556 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:43.387557 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:44.010412 trace git-lfs: HTTP: 200
21:00:44.011562 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

21:00:44.019159 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:44.021163 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:44.323342 trace git-lfs: HTTP: 200
21:00:44.323552 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

21:00:44.326483 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:44.327348 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:44.524786 trace git-lfs: HTTP: 200
21:00:44.525806 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

21:00:44.534110 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:44.535959 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:44.796667 trace git-lfs: HTTP: 200
21:00:44.797778 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}

21:00:44.802860 trace git-lfs: ssh cache: git@github.com git-lfs-authenticate (org)/(repo).git upload
21:00:44.804229 trace git-lfs: HTTP: POST https://lfs.github.com/(org)/(repo)/locks/verify
21:00:45.445509 trace git-lfs: HTTP: 200
21:00:45.446505 trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}
```

Organisation and repository are replaced with (org)/(repo).

After letting the command run for a while, it ends with:

```
21:20:15.251633 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:15.252609 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:15.305634 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:15.306612 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:15.358651 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
21:20:15.358651 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
21:20:15.359608 trace git-lfs: filepathfilter: accepting "tmp"
```

Running it again ought to be more or less a no-op, but the locks/verify operations start repeating again.

We haven't tried `--no-verify`, as we're not sure if that would cause any problems.

**System environment**

Windows 10, 18363.
Same behavior if I run from Git Bash or Powershell.
Same behavior if a colleague runs from OSX.

Output of `git config -l` (remotes and branches omitted):

```
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
user.name=Per Roveg<C3><A5>rd
user.email=per@rovegard.se
submodule.recurse=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
diff.wserrorhighlight=all
```

**Output of `git lfs env`**

```
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.1.windows.1

Endpoint=https://github.com/(org)/(repo).git/info/lfs (auth=none)
  SSH=git@github.com:(org)/(repo).git
LocalWorkingDir=C:\kod\(path)
LocalGitDir=C:\kod\(path)\.git
LocalGitStorageDir=C:\kod\(path)\.git
LocalMediaDir=C:\kod\(path)\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\kod\(path)\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\kod\(path)\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Again, org/repo and paths have been replaced here.

**Comment by bk2204** [comment]
Hey,

The locking API is designed to check for locks for each individual ref.  In your case, you're pushing 4000 refs, so that's not going to be very efficient.  I'd recommend you turn off lock verification with `git config lfs.https://github.com/(org)/(repo).git/info/lfs.locksverify false`.

What you may be seeing with the latter issue is that when we push, we need to walk the history to determine what LFS objects need to be pushed.  We have several optimizations, but if you're pushing to `origin`, specifying that remote explicitly by name (not URL) and doing a fetch beforehand can dramatically speed up the push.  We can eliminate from consideration any object that we know is referenced by a remote tracking branch with the given named remote, which for a typical repository will be most objects if you're just pushing tags.

Can you try those things and see if they speed things up for you?

**Comment by provegard** [comment]
Hi! Not sure what you mean by "specifying that remove explicitly by name". I tried:

    git push --tags origin master

But the same thing happened. Fetching before also did nothing; my local repo was already up to date.

I tried the `.../lfs.locksverify false` setting. When I run `GIT_TRACE=1 git push --tags` now, I don't get the locks/verify calls, but I do get a very long run of:

```
21:20:21.868710 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:21.876661 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:22.032717 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:22.037155 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:22.164148 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:22.168136 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:22.290106 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:22.293992 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:22.419452 trace git-lfs: tq: running as batched queue, batch size of 100
21:20:22.423385 trace git-lfs: run_command: git rev-list --stdin --objects --
21:20:22.553759 trace git-lfs: tq: running as batched queue, batch size of 100
```

With long run, I mean several minutes - not just repeated 40 times as you'd expect (since 40*100 = 4000). After completion, I push tags again and the pattern repeats itself. The remote doesn't get the tags.

**Comment by bk2204** [comment]
Hey,

I mean explicitly specifying the remote as `origin`.

> Hi! Not sure what you mean by "specifying that remote explicitly by name". I tried:
> 
> ```
> git push --tags origin master
> ```

What I meant was what you did: explicitly specify the remote name as `origin`.
 
> But the same thing happened. Fetching before also did nothing; my local repo was already up to date.

And just to check, you have the normal remote tracking branches listed when you do `git for-each-ref | grep refs/remotes/origin`?
 
> ```
> 21:20:21.868710 trace git-lfs: tq: running as batched queue, batch size of 100
> 21:20:21.876661 trace git-lfs: run_command: git rev-list --stdin --objects --
> 21:20:22.032717 trace git-lfs: tq: running as batched queue, batch size of 100
> 21:20:22.037155 trace git-lfs: run_command: git rev-list --stdin --objects --
> 21:20:22.164148 trace git-lfs: tq: running as batched queue, batch size of 100
> 21:20:22.168136 trace git-lfs: run_command: git rev-list --stdin --objects --
> 21:20:22.290106 trace git-lfs: tq: running as batched queue, batch size of 100
> 21:20:22.293992 trace git-lfs: run_command: git rev-list --stdin --objects --
> 21:20:22.419452 trace git-lfs: tq: running as batched queue, batch size of 100
> 21:20:22.423385 trace git-lfs: run_command: git rev-list --stdin --objects --
> 21:20:22.553759 trace git-lfs: tq: running as batched queue, batch size of 100
> ```

Yeah, this looks like it's traversing every object in history.  We'd expect to see the command be this: `git rev-list --stdin --objects --not --remotes=origin --`.  Can you run the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and attach the output as a text file?  You can abort it once it starts running the `rev-list` commands, but I'd like to see more about how the `pre-push` hook is being invoked.  You'll want to strip out any Authorization headers before attaching, though.

Also, is your repository using a `lfs.url` setting in an `.lfsconfig` file in your repository?

**Comment by provegard** [comment]
I don't have a `.lfsconfig` file.

I ran `git for-each-ref | grep refs/remotes/origin` and get about 250 branches (there's a lot of old branches that need to be removed). Not sure what I'm looking for there, but master is among them.

I ran `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push --tags origin master` but there's no additional output compared to what I've seen before. Could you give an example of what output you're expecting? Some `pre-push` lines (they were there before also):

```
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.1 8aba6e5b2d48cd1a4f7490f52177d4971f70d880 refs/tags/build-1.0.0.1 0000000000000000000000000000000000000000
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.100 64bc3eeae046ec3d95a6701bff36003ac9c351ca refs/tags/build-1.0.0.100 0000000000000000000000000000000000000000
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.101 0559336745ed6ac98d163b67dd37b92bc9758285 refs/tags/build-1.0.0.101 0000000000000000000000000000000000000000
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.102 4dfd774d4d50ecc9235dd41b8f55dc9d37ad3973 refs/tags/build-1.0.0.102 0000000000000000000000000000000000000000
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.103 e0cd53ef5d4f6d167f46a2b2f6d96891fe9ef7b0 refs/tags/build-1.0.0.103 0000000000000000000000000000000000000000
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.104 ce867c83dc44b6b7b81f8ffdd2a5d8e364106480 refs/tags/build-1.0.0.104 0000000000000000000000000000000000000000
09:05:39.377689 trace git-lfs: pre-push: refs/tags/build-1.0.0.105 0a7c08e586f097403e0afce4bc648598ca91463f refs/tags/build-1.0.0.105 0000000000000000000000000000000000000000
```

**Comment by bk2204** [comment]
I was hoping to take a look through the output and see why we're not getting the proper rev-list output.  The output from Git about how it's invoking the pre-push hook is usually interesting in this regard, since it contains information about which remote is being used, which in turn affects which objects are traversed.

You may also want to take a look at #4103 (and possibly grab one of the build artifacts) to see if it fixes your problem, since it can improve this situation in some cases.

**Comment by provegard** [comment]
Update: I temporarily disabled Git-LFS, pushed tags, then enabled it again - and now pushing tags works as expected. Feel free to close this issue.

**Comment by minhui-foxtel** [comment]
Using `git push --tags --no-verify` as a workaround.

**Comment by bk2204** [comment]
If you do that, you won't be pushing LFS objects for those tags, so your server will be missing objects.  You probably don't want to do that.
