### ISSUE TITLE
Size limit for git lfs?

### ISSUE THREAD

**Issue by vymao** [git-lfs/git-lfs#4101]
I am trying to upload a few files to Github that are over 5 GB in size. I downloaded git lfs for Linux but get this error message when I try to push to Github: 

```
Username for 'https://github.com': vymao
Password for 'https://vymao@github.com': 
Username for 'https://github.com': vymao
Password for 'https://vymao@github.com': 
[e749bc0e0958aa3889066fd9dc7ea17891b455e8a0dc151e477df34e691d911d] Size must be less than or equal to 2147483648: [422] Size must be less than or equal to 2147483648
[6c3181b71f0530ca126e784053c03e54540b2cd3498bff2bdb8d282b09445a8d] Size must be less than or equal to 2147483648: [422] Size must be less than or equal to 2147483648
error: failed to push some refs to 'https://github.com/vymao/SNVCurate.git'
```

It seems I was able to add track, add, and commit all files without error (I only got the warning message `Possibly malformed conversion on Windows, see `git lfs help smudge` for more details.`). 

I see [here](https://github.com/git-lfs/git-lfs/issues/1493) that there could be a file size restriction based on the server I am uploading from. Is there a guide to how to resolve this using tus.io? Or is there another solution?

**Comment by bk2204** [comment]
Hey,

Git LFS itself supports any file size that can fit in a signed 64-bit integer.  However, GitHub does have lower limits, which you can read more about in [their documentation](https://help.github.com/en/github/managing-large-files/about-git-large-file-storage).

If the file is larger than the size limit, you can split it into multiple files and combine them as a build step, or you can use an external LFS server if you'd prefer that.

**Comment by andreabosisio** [comment]
How can one know what are the files associated to e.g., e749bc0e0958aa3889066fd9dc7ea17891b455e8a0dc151e477df34e691d911d?

**Comment by chrisd8088** [comment]
@andreabosisio --

> How can one know what are the files associated to e.g., `e749bc0e0958aa3889066fd9dc7ea17891b455e8a0dc151e477df34e691d911d` ?

Try `git lfs ls-files --all --long` and `grep` for your Git LFS OID.  Or, if you want to look for the commit which introduced that Git LFS object, something like `git rev-list --all | xargs git grep "<oid>"` should work.

In the future, if possible, please consider opening a new [discussion](https://github.com/git-lfs/git-lfs/discussions) for questions like this, and anyone from the community can help provide an answer!  That way we avoid having to address comments on old and closed issues.  Thank you, and good luck with Git LFS!
