### ISSUE TITLE
git-lfs package for Ubuntu Focal (20.04 LTS)

### ISSUE THREAD

**Issue by vaccarium** [git-lfs/git-lfs#4107]
Hi,

At the moment there isn't a git-lfs package available on [packagecloud.io](https://packagecloud.io/app/github/git-lfs/search?dist=ubuntu%2Ffocal) for Ubuntu Focal. With Focal expected to be released on April 23, having packages available would be really great.

**Comment by bk2204** [comment]
Hey,

I believe support for focal was added in #4080.  However, we only upload packages when doing a release, so they won't be available immediately upon release.  We've planned to do a release this month, but are trying to work out macOS signing issues at the moment.

So hopefully it'll be available a little later this month.

**Comment by kvz** [comment]
FYI I just had a focal server install git lfs and then report that there was no focal repo upon running `apt update`

To reproduce:

```bash
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt update
```

**Comment by bk2204** [comment]
Yes, as mentioned, it will be updated when we do a release, which we have not done since #4080 was merged.  It's something we're working on, and it should be fixed when the next release comes.

Since packages are built only as part of the release process, they can't be updated outside of doing a release.

**Comment by arghanath007** [comment]
Is it added now?

**Comment by bk2204** [comment]
There is presently a package for Ubuntu focal, yes.

**Comment by arghanath007** [comment]
Can you link it please? How to install and use it?
