### ISSUE TITLE
[already possible] Feature request: a way to merge two unrelated LFS-backed repositories

### ISSUE THREAD

**Issue by sietse** [git-lfs/git-lfs#4108]
**Describe the issue**
I have two separate git repositories, both LFS-backed, that I want to merge into one repository.

If they were not LFS-backed, I could do
```
cd repoA
git remote add repoB url/to/repoB
git fetch repoB
git checkout repoB/master

# and eventually merge the DAGs with `git checkout master; git merge repoB/master`,
# but the problem already occurs when checking out repoB/master
```

Now that the repositories are LFS-backed, however, `git checkout repoB/master` gives a '404 object does not exist on the server' error. (Full example message below.)

I presume that this error arises because LFS is looking for a file from repo B in the LFS store of repo A.

**Existing information**

[Contributing.md](https://github.com/git-lfs/git-lfs/blob/master/CONTRIBUTING.md#feature-requests) mentions this;
> Users can access different Git LFS servers like they can with different Git remotes.

I have been unable, however to find any intructions on how to add multiple Git LFS server

**Possible fixes**

* If this is already possible and I just couldn't find out how, I would be happy to write additionals docs full of searchable phrases like "merge unrelated histories" and "combine LFS stores".

* #3344 "Support multiple lfs.url configuration options" would fix this, I think? If that would allow LFS to look in repoB's store if an object is not found in repoA's store.

* Another option might be an explicit command that means 'Git LFS, please add the contents of the store at URL A to the store at URL B.' 

* For discoverability, Git LFS could suggest combining the stores whenever a "[404] Object does not exist on the server" error occurs in a repository with multiple Git remotes.

**System environment**
Linux Minut 19.3 Tricia atop Ubuntu 18.04 LTS

**Output of `git lfs env`**
```
Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal: not a git repository (or any of the parent directories): .git\n"
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)
git version 2.17.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

Steps to reproduce this use case:

* create two LFS-backed repositories, let's call them Aremote and Bremote.
* go to your local clone of Aremote
* `git remote add Bremote https://git.example.com/Bremote`
* `git fetch Bremote`
* `git checkout Bremote/master`

That results in an error that looks like this:

> Error downloading object: myfile.pdf (20561ec):
> Smudge error:
> Error downloading myfile.pdf
> (20561ec37a8a7518480bb39d44a76ba86fa7800c382046310708abef993ac3f4):
> [20561ec37a8a7518480bb39d44a76ba86fa7800c382046310708abef993ac3f4]
> Object does not exist on the server or you don't have permissions to access it:
> [404] Object does not exist on the server or you don't have permissions to access it

**Comment by bk2204** [comment]
Hey,

This is a little tricky, but it is possible to do.  You can run `git lfs fetch repoB master`, which will bring in the objects from `repoB/master` to your repository and then check out the branch.  When you're ready to merge the histories, you'll need to do `git lfs fetch --all repoB` to pull all of the LFS objects for repoB into your tree so that when you push, they can all be pushed to the repoA server.

**Comment by sietse** [comment]
Hi, my sincere apologies for being so late to reply. Your suggestion worked well, and I am very grateful that you took time out of your day last month to help me out.

Kind regards,

Sietse

**Comment by sietse** [comment]
Since the workaround is so easy, I've marked the issue title as 'this is already possible', and I'm closing this issue. Feel free to reopen the issue if you want to keep it open; but you've already solved my problem, many thanks!

**Comment by toralMevada** [comment]
> Hey,
> 
> This is a little tricky, but it is possible to do. You can run `git lfs fetch repoB master`, which will bring in the objects from `repoB/master` to your repository and then check out the branch. When you're ready to merge the histories, you'll need to do `git lfs fetch --all repoB` to pull all of the LFS objects for repoB into your tree so that when you push, they can all be pushed to the repoA server.

When tried these steps, at time of executing "git lfs fetch --all test_lfs_repo_to_be_merged" getting error
$ git lfs fetch --all test_lfs_repo_to_be_merged
fetch: 12 object(s) found, done.
fetch: Fetching all references...
EOFnloading LFS objects: 100% (12/12), 566 MB | 0 B/s
error: failed to fetch some objects from 'file://<dir_path>/test_lfs_repo_to_be_merged/.git/info/lfs'

**Comment by th0ger** [comment]
> Hey,
> 
> This is a little tricky, but it is possible to do. You can run `git lfs fetch repoB master`, which will bring in the objects from `repoB/master` to your repository and then check out the branch. When you're ready to merge the histories, you'll need to do `git lfs fetch --all repoB` to pull all of the LFS objects for repoB into your tree so that when you push, they can all be pushed to the repoA server.

Unfortunately not working here.

```
$ git lfs repoB last
   git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.3)
   git version 2.39.2

   $ git-lfs fetch doc master
   Invalid ref argument: [master]

   Git can't resolve ref: "master"
```

```
$ git branch -a | grep branchB
remotes/branchB/master
```
