### ISSUE TITLE
How do you remove files from git lfs?

### ISSUE THREAD

**Issue by jackcorfield** [git-lfs/git-lfs#4115]
As I was still new to using github I didn't know how to properly create repositories for Visual Studio projects and so I used git lfs to store all the large files that wouldn't uploaded normally. As a result I am currently paying for a data pack that I no longer need as I can avoid using it. The problem I have is that I can't stop paying for the datapack if the space is still full, would anyone be able to tell me how i can empty it?

**Comment by bk2204** [comment]
Hey,

This is more a question about GitHub, but the Git LFS client doesn't provide a way to delete objects, and I'm not aware of any way to do this through GitHub.  You'd have to check with GitHub Support to be sure, but I believe you can delete and recreate the repo and that will prune the objects.

Note that you'd want to make sure your repository doesn't contain any LFS objects (possibly by ignoring the relevant files or rewriting history) to make sure that you don't accidentally push them up again.  You could use `git migrate export` to do that if you haven't already, or perhaps a different tool if you want to ignore them altogether..

Sorry that I can't be of more help.

**Comment by FullStackForger** [comment]
@bk2204  `git migrate export`
produces
`git: 'migrate' is not a git command. See 'git --help'.`

**Comment by chrisd8088** [comment]
I think that was intended to be `git lfs migrate export`.

**Comment by jfcarp-bfg** [comment]
Hello. During my search attempting to find a solution for a contenttype related issue, I ran across this one and figured I would try to help.

That is. we have been using and testing lfs in our migrations from on-prem to GitHub and it seems even if the objects are no longer referenced, GitHub will not remove them from LFS storage. This can be seen under billing, as the storage will remain the same. The only way I have found at present, is to delete the entire repository and recreate it, per the GitHub reference below; which is not ideal, but works. That is, after using the above git lfs migrate to prune the history of these objects as well, or you will simply push them to the new repository. Cheers.

https://help.github.com/en/github/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository

**Comment by edgarschnfld** [comment]
Deleting and recreating the repository is a terrible solution. There should be another way.

**Comment by bk2204** [comment]
If you have questions about GitHub and how GitHub manages objects, please contact GitHub Support.  I believe they do have a way to remove LFS objects from storage, but this project is for the Git LFS open source client, not GitHub, and so we can't help with GitHub issues here.

**Comment by Malix-off** [comment]
Please see https://github.com/orgs/community/discussions/128695
