### ISSUE TITLE
Smudge error: Error downloading ... batch request: missing protocol: "<unknown>"

### ISSUE THREAD

**Issue by eroller** [git-lfs/git-lfs#4117]
I get this error when merging a branch. It only happens when I set the origin url using the following url format:

`https://eroller:mypassword@git.mydomain.com/git-lfs/git-lfs`

If I use the normal format and enter my password manually or through git cache it works properly:

`https://git.mydomain.com/git-lfs/git-lfs`

This is using git on centos 7.

```
[]$ git lfs env
git-lfs/2.10.0 (GitHub; linux amd64; go 1.12.7; git a526ba6b)
git version 2.13.5

LocalReferenceDirs=
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I know this may be possibly related to the git LFS server and not the git-lfs client and if so we can close this issue, but I figured it would still be nice to document this issue in case others run into the same error. 

I don't think there is anything unique about the git enterprise setup being used so it may be something that others run into. I will post back if there is any resolution on the server side of things.

**Comment by eroller** [comment]
Found the underlying issue was that the password contained reserved characters. Encoding them properly in the url fixed the error.

https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

**Comment by AutismPatient** [comment]
> 发现潜在的问题是密码包含保留字符。在 url 中正确编码它们修复了错误。
> 
> https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

Thank you. You saved my life
