### ISSUE TITLE
git lfs migrate import --everything doesn't migrate tags whose name matches that of a branch

### ISSUE THREAD

**Issue by karlhendrikse** [git-lfs/git-lfs#4120]
**Describe the bug**
When migrating a repository to LFS, any tags that have the same name as a branch are not migrated. Presumably this is because somewhere inside LFS tags are referred to in am ambiguous way as `<name>` rather than `refs/tags/<name>`.

**To Reproduce**
```
git init .
git lfs install --local
echo "hello" > hello.txt
git add hello.txt
git commit -m "Add hello.txt"
git branch release_42
git tag release_42
git tag release_other
git lfs migrate import --everything --include="*.txt"
```

**Expected behavior**
Both branches (master and release_42) and both tags (release_42 and release_other) should all point to the same new, migrated commit.

**Observed behaviour**
The two branches and the release_other tag point to the same new, migrated commit. But the release_42 tag still points to the old, unmigrated commit.

**System environment**
Windows 10, Git Bash environment.

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.2.windows.1

LocalWorkingDir=C:\Data\Code\repro
LocalGitDir=C:\Data\Code\repro\.git
LocalGitStorageDir=C:\Data\Code\repro\.git
LocalMediaDir=C:\Data\Code\repro\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Data\Code\repro\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Data\Code\repro\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I can confirm the behavior you've mentioned.  We've reports of this happening in #3238, but haven't been able to get reproduction steps, so thanks for providing some here.  I'm not sure that this is the entirety of #3238, but I think fixing this will likely fix at least some of those issues.

I'll see if we can get a fix here soon.
