### ISSUE TITLE
"Your push was rejected due to missing or corrupt local objects" when tracking two remote repos

### ISSUE THREAD

**Issue by JamieFristrom** [git-lfs/git-lfs#4127]
**Describe the issue**
I've been using the technique from here - https://24ways.org/2013/keeping-parts-of-your-codebase-private-on-github/ - to share most of my codebase but keep a private branch in a private remote repo. So I do most of my work in the public origin repo, but also have an originprivate repo which has a single 'private' branch. I'd been working this way a while without a hitch but just now it stopped working for me - after a rebase of private onto origin/master and an attempt to git push --force from my private branch which tracks privateorigin/private I see 
```
LFS upload failed:cts:  50% (1/2), 1.5 MB | 0 B/s
  (missing) rbxl/DungeonLifeOpenTemplate.rbxl (8c4445d497766469b98c63146154de6e88189f2eefee009d9835e63e056082e4)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: 'git config lfs.allowincompletepush true'
error: failed to push some refs to 'git@github.com:JamieFristrom/dungeonlifeprivate.git'
```
I have the whole file, not just the pointer, in my directory.
I tried this:
```
$ git lfs push privateorigin --all
LFS upload failed:cts:  94% (15/16), 19 MB | 535 KB/s
  (missing) rbxl/DungeonLifeOpenTemplate.rbxl (8c4445d497766469b98c63146154de6e88189f2eefee009d9835e63e056082e4)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: 'git config lfs.allowincompletepush true'
```
but it gives the same error message as you can see.

**System environment**
Windows 10, using git bash

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.9.2 (GitHub; windows amd64; go 1.12.7; git 0274d856)
git version 2.25.0.windows.1

Endpoint (privateorigin)=https://github.com/JamieFristrom/dungeonlifeprivate.git/info/lfs (auth=none)
  SSH=git@github.com:JamieFristrom/dungeonlifeprivate.git
Endpoint (origin)=https://github.com/JamieFristrom/dungeonlife.git/info/lfs (auth=basic)
LocalWorkingDir=D:\repos\dungeonlife
LocalGitDir=D:\repos\dungeonlife\.git
LocalGitStorageDir=D:\repos\dungeonlife\.git
LocalMediaDir=D:\repos\dungeonlife\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\repos\dungeonlife\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\repos\dungeonlife\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by JamieFristrom** [comment]
<git fetch --all> fixed it. I guess I was behind in one or the other repo and didn't realize?

**Comment by bk2204** [comment]
If you're still seeing this problem, please open a new discussion.  This message isn't a bug, but we're happy to help you out in the Discussions area.

**Comment by chbrandt** [comment]
@Hagar-Usama I guess Jamie forgot 'lfs' in his comment:
```bash
git lfs fetch --all
```
should do the trick.

**Comment by yuyedaidao** [comment]
@chbrandt  when I perform `git lfs fetch -all`, it show message:
`Object does not exist on the server: [404] Object does not exist on the server
`
Of course, because I did failed to push the file.

**Comment by c6supper** [comment]
> 
met the same problem , might be due to my cancelation the previous lfs pushing.

**Comment by Taha2000587814** [comment]
> @chbrandt when I perform `git lfs fetch -all`, it show message: `Object does not exist on the server: [404] Object does not exist on the server ` Of course, because I did failed to push the file.

Am facing your same issue here , did you managed to get a solution
