### ISSUE TITLE
missing file when change branch 

### ISSUE THREAD

**Issue by siplo** [git-lfs/git-lfs#4131]
**Change branch from master to any feature branch**
Hi sorry for really basic question but I don't understand how to use it. We have problem (probably with understanding) with lfs when we switch from develop branch to another branch. Instead of real files we have only .gitaatributes. Question is how to "download" these files. My understanding is that these files is still in ".git/lfs/objects". 

Standard scenario:
git clone OUR_REPO  -- after clone everything is as I expected
When I check list of files I got this
```
git lfs ls-files                                                                                                                   
ea7444b4ee * deployment/java/linux/jre1.8.0_172.zip
378905e9c5 * deployment/java/windows/jre1.8.0_172.zip
```
Then I switch to branch 
git checkout feature/whatever
and when I check 
```
git lfs ls-files  -- no files
```
but output of git lfs track is still here :

```
git lfs track
Listing tracked patterns
    kt-backbone/src/test/resources/stresstest/200000000002*.zip (kt-backbone/src/test/resources/stresstest/.gitattributes)
    deployment/java/windows/jre1.8.0_172.zip (deployment/java/windows/.gitattributes)
    deployment/java/linux/jre1.8.0_172.zip (deployment/java/linux/.gitattributes)
Listing excluded patterns
```

But when I switch back to develop everything is there:
```
git checkout develop
git lfs ls-files
ea7444b4ee - deployment/java/linux/jre1.8.0_172.zip
378905e9c5 - deployment/java/windows/jre1.8.0_172.zip
```
I tried also git  lsf fetch and git lsf checkout on feature branch but nothing happened. 

**Output of `git lfs env`**
```
it-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)
git version 2.25.1

Endpoint=https://my-secret-repo/api/lfs/project (auth=basic)
LocalWorkingDir=/home/siplo/tmp/project
LocalGitDir=/home/siplo/tmp/project/.git
LocalGitStorageDir=/home/siplo/tmp/project/.git
LocalMediaDir=/home/siplo/tmp/project/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/siplo/tmp/project/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/siplo/tmp/project/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

**Comment by nhatkhai** [comment]
I think this sound like a fundamental misconception about git branches which had nothing to do with git lfs.

**Comment by siplo** [comment]
Maybe I explained it wrong. But I expected if I created branch from for example master then also files which are handled by lfs will be there. 

And yes this branch was created from branch where binary files are handled by lfs. 
Then please can you explain me how to use this. Because it doesn't works.

**Comment by bk2204** [comment]
Hey,

If you create a branch from `master` and `master` has LFS files, then it should indeed work.  It's possible that your branch is based off a version which doesn't have a valid `.gitattributes` file, so Git LFS and Git don't know that those files are supposed to be LFS files.

Can you provide the output of any `.gitattributes` files in your repository on both branches?

**Comment by siplo** [comment]
Hi, guys thanks for replay. I was out last week then I have to try it this week and let you know. Thanks

**Comment by siplo** [comment]
Hi guys, 

I was wrong.  Accidentally I created branch from branch where these files was not handled by lfs. Mea culpa.
