### ISSUE TITLE
git-lfs without root

### ISSUE THREAD

**Issue by slitvinov** [git-lfs/git-lfs#4134]
I want to fetch files which are managed by git-lfs on a system where I do not have root. git is installed but there is no git-lfs. Is there any way to have a stand-alone script which downloads files?

**Comment by bk2204** [comment]
Hey,

There isn't a standalone script which downloads LFS files, but you can install the `git-lfs` binary somewhere in your `PATH` (like `$HOME/bin`) and just run `git lfs install`.  We do have binaries available from the releases page and you only need the binary.

I actually use a very similar approach when developing Git LFS and no root access is involved.

**Comment by ziyuhuang123** [comment]
How to install it? I download it https://github.com/git-lfs/git-lfs/releases here and put it anywhere, and use git lfs install. and meet this:
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
        log

**Comment by emjay73** [comment]
1. go to https://github.com/git-lfs/git-lfs/releases
2. find the corresponding tar file from the asset section.
3. untar the file
```
tar -xvf [asset name].tar.gz
```
4. go to the extracted folder
```
cd [extracted folder]
```
5. place the git-lfs file by typing the following
```
install git-lfs [wherever the dir path that you place the git-lfs]/git-lfs
```
6. add path 
```
export PATH="${PATH}:[wherever the dir path that you place the git-lfs]"
```
