### ISSUE TITLE
git clone hangs at resolving deltas

### ISSUE THREAD

**Issue by omerasif57** [git-lfs/git-lfs#4138]
**Specs**
Ubuntu 18.04.4
git 2.26.2 [latest-stable]
git-lfs 2.11.0 [latest-stable]

**cloning repo**: https://github.com/mozilla/deepspeech

**Issue**
Cloning the repository stuck at `resolving deltas` if cloned with `git clone`

**Observations**
1. Cloning the repo with `git-lfs clone` works fine and it downloads LFS objects. (It warns that git-lfs is deprecated)

2. Cloning with `git clone` get stuck at `resolving delta` then Ctrl+C to terminate it and then using `git-lfs pull` to download LFS objects.

**Comment by onnodb** [comment]
Observed the same, but it seems more like there's just a lack of progress reporting (and there appear to be a bunch of issues open on that topic). If I monitor the size of the local `.git` directory while `git-clone` is still running, I see the size increasing.

Specs for me: Ubuntu 19.10, git 2.26.2, git-lfs 2.11.0

**Comment by bk2204** [comment]
Hey,

Can you paste the output of running with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` (after stripping out any credentials)?  I want to see if the failure is on the Git side (which would happen if the “Resolving deltas” output doesn't say “done”) or if there might be a problem on the Git LFS side (which would happen if it did say “done”).

**Comment by omerasif57** [comment]
What I observe that 
1. there is no "downloading lfs file prompt" in case of `git clone 'repo'`. Hence, It is being assumed that It is getting stuck. _(which is due to slow speed or bandwidth of the internet connection, in my case)_.
2. In case of `git-lfs pull`, There is a prompt showing downloading files with size progress. 

I created a _google colab_ file to test this behavior and git clone works fine and does not stuck at `resolving deltas. (some number) done.`

> if there might be a problem on the Git LFS side (which would happen if it did say “done”)

It says, `done` in fact.
 
Closing this issue as it does not seems to be an git-lfs issue. Please advise, otherwise.
