### ISSUE TITLE
Upload to github is slower than expected

### ISSUE THREAD

**Issue by sammo** [git-lfs/git-lfs#4144]
**Describe the issue**
I followed the instructions to install git lfs, added two large pickle files (1.5GB and 200MB), committed and pushed to github.
The upload is way too slow. I have 300Mbps connection. My upload speed is around 70 Mbps. Git lfs transfer rate is 508 KB/s.
_Uploading LFS objects:  50% (1/2), 404.1 MB | 508 KB/s_
Is there something I can do to speed it up?

**System environment**
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
Python 3.8.3
git version 2.17.1
git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.1; git 48b28d97)

**Output of `git lfs env`**
Endpoint=https://github.com/pv-data-science/geras.git/info/lfs (auth=none)
  SSH=git@github.com:pv-data-science/geras.git
LocalWorkingDir=/home/sam/github/geras
LocalGitDir=/home/sam/github/geras/.git
LocalGitStorageDir=/home/sam/github/geras/.git
LocalMediaDir=/home/sam/github/geras/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/sam/github/geras/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/sam/github/geras/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

Usually this is some sort of network problem.  In the GitHub case, you're uploading directly to Amazon S3 (I believe in `us-east-1`), so if you have greater than expected latency or packet loss to the destination, you'll see poorer connection speeds than you might expect.  The Git LFS client should be capable of a reasonable upload speed if the network connection is stable and fast.

**Comment by sammo** [comment]
Hmm ok thanks Brian.
I've been wanting to use git-lfs since four years ago but the speed the only thing that's stopping me...
I appreciate your help.
