### ISSUE TITLE
Can't push with GIT LFS 

### ISSUE THREAD

**Issue by wacimehadrich** [git-lfs/git-lfs#4146]
**Describe the issue**
I can't push when i have an LFS file to push.
`$ git push origin dev
batch response: Git LFS is disabled for this repository.
error: failed to push some refs to 'https://github.com/wacimehadrich/EvacENSI.git'`

**System environment**
`$ git config -l
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
core.autocrlf=true
core.fscache=true
core.symlinks=false
user.name=Wacime Hadrich
user.email=wacime.hadrich@ensi-uma.tn
core.autocrlf=true
http.postbuffer=2097152000
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/wacimehadrich/EvacENSI.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.dev.remote=origin
branch.dev.merge=refs/heads/dev
branch.dev-bkp.remote=origin
branch.dev-bkp.merge=refs/heads/dev-bkp
lfs.https://github.com/wacimehadrich/EvacENSI.git/info/lfs.access=basic
 ESC[D
credential.helper=manager
core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
core.autocrlf=true
core.fscache=true
core.symlinks=false
user.name=Wacime Hadrich
user.email=wacime.hadrich@ensi-uma.tn
core.autocrlf=true
http.postbuffer=2097152000
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/wacimehadrich/EvacENSI.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.dev.remote=origin
branch.dev.merge=refs/heads/dev
branch.dev-bkp.remote=origin
branch.dev-bkp.merge=refs/heads/dev-bkp
lfs.https://github.com/wacimehadrich/EvacENSI.git/info/lfs.access=basic
 ESC[D
credential.helper=manager
core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
core.autocrlf=true
core.fscache=true
core.symlinks=false
user.name=Wacime Hadrich
user.email=wacime.hadrich@ensi-uma.tn
core.autocrlf=true
http.postbuffer=2097152000
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/wacimehadrich/EvacENSI.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.dev.remote=origin
branch.dev.merge=refs/heads/dev
branch.dev-bkp.remote=origin
branch.dev-bkp.merge=refs/heads/dev-bkp
lfs.https://github.com/wacimehadrich/EvacENSI.git/info/lfs.access=basic`

**Output of `git lfs env`**
`$ git lfs env
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.2.windows.1

Endpoint=https://github.com/wacimehadrich/EvacENSI.git/info/lfs (auth=basic)
LocalWorkingDir=E:\PCD\EvacENSI
LocalGitDir=E:\PCD\EvacENSI\.git
LocalGitStorageDir=E:\PCD\EvacENSI\.git
LocalMediaDir=E:\PCD\EvacENSI\.git\lfs\objects
LocalReferenceDirs=
TempDir=E:\PCD\EvacENSI\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=E:\PCD\EvacENSI\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
LOCAL_GIT_DIRECTORY=C:\Users\TheNooBPRO\AppData\Local\GitHubDesktop\app-2.5.0\resources\app\git
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"`

**Comment by bk2204** [comment]
Hey,

As you may have mentioned in #2481, it sounds like this is an issue with GitHub due to your account being over quota.  Since this repository is only for the Git LFS open source project, you'd probably want to talk to GitHub Support about fixing this.
