### ISSUE TITLE
Help with removing git lfs refs

### ISSUE THREAD

**Issue by gerjandev** [git-lfs/git-lfs#4148]
## Problem
Sorry for opening an issue but I need some help.

We have a very large, and very old repository and I am trying to migrate this from bitbucket to github. 

However, I get LFS errors when I try to push the repository.

```
error: GH008: Your push referenced at least 10 unknown Git LFS objects:
```

So this prevents me from migration to github.

## Whats the context
I know that maybe 1 year ago we _tried_ to use git lfs with bitbucket but we failed in that attempt. So we did several attempts, made commits, pushed lfs objects etc etc.
But we had so many problems (I cannot remember anymore) that we did a 'rollback'.
I think we still have pain and remainders from this attempt but maybe I am wrong and theres just something wrong or misconfigured.

## What I already tried
- When I do `git lfs ls-files` it does not return any file. So it seems there are no lfs files anymore right?
- I already tried `git lfs uninstall`
- I've searched trough several config files and removed all lfs configs / references
- I deleted the .git/lfs folder
- I cloned a complete new repository in order to check that my repo was in a wrong state

## Question
So the question is: how can I remove ALL LFS objects? I do not want to use LFS at the moment.

**Comment by bk2204** [comment]
Hey,

It sounds like you have some LFS objects somewhere in your history even though they're not in the `HEAD` of your branch.  GitHub will let you push a repository without the LFS blobs if and only if have no existing LFS blobs.  If you have any existing LFS blobs, then it will check to make sure you have all of them.

If you want to remove the LFS objects from your history entirely, then you need to use `git lfs migrate export` (probably with the `--everything` option), which will rewrite all of your history to remove the LFS blobs.  That will, of course, require that you have the LFS blobs, so you'll want to be sure that you run `git lfs fetch --all` before destroying the old repository.  If you lack the LFS objects, then you'll have to use `git filter-branch` to filter all of your branches and tags to remove the pointer files.  Either one of these options involves rewriting history, which is unavoidable.

If you just want to leave things as they are and push the LFS blobs that you have without creating new ones, then you can do a `git lfs fetch --all` on the old repository (specifying the remote name if necessary) and then do a `git lfs push --all github` (assuming `github` is your new remote name).

**Comment by gerjandev** [comment]
git lfs migrate export --include="*" --everything` did fix my issues, thank you so much @bk2204

**Comment by devBabinski** [comment]
This worked for me:

git lfs uninstall
git lfs uninstall --local
git rm --cached -r .        
git push origin main
