### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by bPavenko** [git-lfs/git-lfs#4150]
**Describe the bug**
When i clone my repo from github, i see error:
![image](https://user-images.githubusercontent.com/15121305/83744675-2459e400-a665-11ea-8cdb-8379f9fef3a8.png)

**To Reproduce**
1. install Git-2.27.0-64-bit
2. install git-lfs
3. clone repo
4. see error

**Expected behavior**
i want clear clone my repo without error

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.
![image](https://user-images.githubusercontent.com/15121305/83744936-7ef34000-a665-11ea-8ee2-7cc00e315b5c.png)

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
![image](https://user-images.githubusercontent.com/15121305/83744967-8d415c00-a665-11ea-9b54-e0cdf6eacebb.png)

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Sorry to hear that you're having trouble.  It sounds like you `.gitattributes` file may not be syntactically valid.  Could you provide that file (as a code block, not an image) in the version you're checking out?  It should be available in your tree, even if the checkout failed part of the way through.

**Comment by bPavenko** [comment]
i uninstalled git 2.27 and install 2.12 and it's working for me. Thanks!

**Comment by bk2204** [comment]
I'm glad you got it working, but I'd recommend against using an old version of Git for Windows because those versions have security vulnerabilities.  So I'm happy to work with you to figure out what the problem is and how it can be fixed.

**Comment by bPavenko** [comment]
in version 2.12 i can't push commits and new branches =(

**Comment by bPavenko** [comment]
my .gitattributes
![image](https://user-images.githubusercontent.com/15121305/84045017-f94af980-a9b0-11ea-84e9-379cc7ac98b0.png)

**Comment by bPavenko** [comment]
but i don't see this error in this version https://github.com/git-for-windows/git/releases/tag/v2.20.1.windows.1
and see in 2.21 - 2.27 versions

**Comment by bk2204** [comment]
The problem is that your `.gitattributes` file has an error.  The portion that says `[[:space]]` should be `[[:space:]]`; that is, it's missing its second colon.  If you fix that and commit, everything should work.

**Comment by bPavenko** [comment]
yes, its working for me. Thanks!
