### ISSUE TITLE
git lfs install does not support `--worktree` option

### ISSUE THREAD

**Issue by nagisa** [git-lfs/git-lfs#4152]
**Describe the bug**

Git supports setting configuration on a per-worktree basis such as this:

```
git config --worktree --add filter.lfs.clean 'git-lfs clean -- %f'
git config --worktree --add filter.lfs.smudge 'git-lfs smudge -- %f'
git config --worktree --add filter.lfs.process 'git-lfs filter-process'
git config --worktree --add filter.lfs.required 'true'
```

however running 

```
git lfs install --worktree
```

does not work.

**To Reproduce**
1. `git lfs install --worktree`

**Expected behavior**

Running `git lfs install --worktree` should install the filters for the worktree only.

**System environment**
N/A

**Output of `git lfs env`**
N/A

**Additional context**
N/A

**Comment by chrisd8088** [comment]
Hey, thanks for the suggestion; this does seem like a good idea!  I don't want to promise anything, but I will try to take a look at this in the next while as it doesn't seem like it should be too difficult to implement.
