### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by bk2204** [git-lfs/git-lfs#4153]
There's been discussion recently about the [problematic use of `master` and `slave`](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) in technology.  Similar to what GitHub Desktop (desktop/desktop#6478) and other projects have done, it would be a good idea to rename our default branch to something different, and do this across all of our repositories.

For consistency with what [Git for WIndows is doing](https://github.com/git-for-windows/git/issues/2674), I propose `main`, although we can discuss other names as well.

This issue doesn't track the replacement of this terminology in the codebase, which I think should be split out into another issue.

There are some technical issues to discuss on this that would need doing:

- [ ] Create the new branch in each repository.
- [ ] Set it as the default branch.
- [ ] Update the release howto to reflect the new name.
- [ ] Update the docs link on the website to reflect the new name.
- [ ] Remove the old CI job files that refer to the old default branch, and make sure Actions is set up for the subsidiary repositories if need be.
- [ ] Remove the old `master` branches to avoid confusion.

/cc @git-lfs/core

**Comment by fcharlie** [comment]
The economic foundation determines the superstructure. To fight for equal rights, it is necessary for the disadvantaged groups to get rich and have more political, economic and cultural rights. Can changing the vocabulary alone solve the problem?

**Comment by bk2204** [comment]
I have a `to-main` branch on my remote which updates all of the links and functional documentation (e.g., howtos, contributing, readme) to use `main` instead.  It also will remove the old CI files that refer to `master`.  I know there are some outstanding PRs which we'd want to merge first to let the branch settle, and then we can rename and change the default branch.

**Comment by raaaaay-c** [comment]
**Stop renaming** 
In git concept master has to be understood as the 'original', the 'master copy', the 'first-ever copy'. 
There is no association with master and slaves. 
There is no git slave branch concept, and it's not a slavery-origin terminology. 

In some projects the initial branch is not the main branch. But it will always be the first ever branch, the original branch.

To show black people our respect and solidarity we do not have to rename everything that is called master or black as long as there is no association with master & slave or black as something bad.

If we rename all the things this tends to have the opposite effect, if we always associate master with slavery and when the word "black" in our minds is something bad that we have to rename directly. 

We would be the ones who created racism, not terms.

**Comment by bNobo** [comment]
and what do you think about "root" ? It could also be a good alternative to "master", especially when we are talking about branches.

**Comment by bk2204** [comment]
> In git concept master has to be understood as the 'original', the 'master copy', the 'first-ever copy'.
> There is no association with master and slaves.
> There is no git slave branch concept, and it's not a slavery-origin terminology.

There is debate on this point. As others have mentioned elsewhere, the question is whether it has an impact on people, especially Black people, that causes them to be reminded of slavery and oppression, regardless of the actual origin of the word.  I think multiple folks have said that it does, and so we'd like to make a change because that's not the experience we'd like people to have of Git or Git LFS. `main` is more accurate and, from feedback from non-native speakers, is also more intuitive for folks who aren't fluent in English.

I think we also want to try to follow what Git does here, so that's why I selected `main` instead of `root` or my original suggestion, `development`.  It also has all of the great muscle memory tab-completion benefits of the old name.

Regardless, most of the work here has to be done anyway because Git upstream is going to be doing a renaming, whether we do or not, and our codebase and testsuite need to be prepared to work with any version of Git, including those versions that are coming out with a new name.  The work required to do the actual rename is a few patches and is already done, so there's little reason not to do it.

**Comment by Siccity** [comment]
> There is debate on this point. As others have mentioned elsewhere, the question is whether it has an impact on people, especially Black people, that causes them to be reminded of slavery and oppression, regardless of the actual origin of the word.

I've been following this discussion since it started, and I've yet to see one single black person state any form of unease with the term. On the contrary, I can link you plenty of sources on black people who disagree with the change https://dev.to/assertnotnull/comment/10cma.

I wouldn't mind changing to `main` had it been for any other reason, but this white guilt virtue signalling really gets under my skin.

**Comment by Beilog** [comment]
Its only white people who want to showcase (not show) their allyship that think like this. If you want to support Black people, how about stop talking over and for them all the time? If this was an actual concern the Black community had - sure. But none of this is coming from them. The master and slave terms have nothing to do with racism and slavery. Not in this case, at least. It's YOU who's uncomfortable with it, and you should think about why that is instead of wasting time coming up with ridiculous ideas and speaking up for Black people when nobody even asked you to.

**Comment by bk2204** [comment]
I'd like to make sure we keep this discussion within our code of conduct and avoid potentially loaded terms like "virtue signalling".  I don't think those are contributing to a positive and welcoming community.  Certainly people have strong feelings here, but we want to keep the conversation considerate and respectful.  If that doesn't happen, I'll have to lock the conversation.

Here's an example of where some Black folks have weighed in and are about evenly split: https://twitter.com/ssaamv/status/1272594772960489477.  I definitely don't want to speak for people who aren't me here, but it appears there are folks who see it as a problem worth changing.  I've also received feedback from colleagues who don't think it's great.  Clearly there are others who disagree that it's a problem, and that's definitely their right and prerogative.  Reasonable people within a community can and do disagree over language.

We do want to use a branch name and language that is generally unoffensive.  Since Git is making this change, and there are options which appear to be better than the status quo, such as `main`, we'd like to make the change as well.  As previously mentioned, the majority of the work is doing things we need to do anyway for compatibility with Git.

**Comment by dscho** [comment]
> Here's an example of where some Black folks have weighed in and are about evenly split: https://twitter.com/ssaamv/status/1272594772960489477. I definitely don't want to speak for people who aren't me here, but it appears there are folks who see it as a problem worth changing. I've also received feedback from colleagues who don't think it's great. Clearly there are others who disagree that it's a problem, and that's definitely their right and prerogative.

Sure, everybody can disagree.

However, the only people with potentially valid objections would be the ones affected by this rename, which amounts to the contributors to this here project. That does not even include future contributors, as they would simply clone with a new default main branch name and start from there.

@bk2204 Is there a way to lock this conversation to past contributors to git-lfs only?

**Comment by bk2204** [comment]
There is not; that option is restricted to the entire repository, and I don't think that step is appropriate for right now.  I've chosen to lock the conversation for now to folks with write access and will consider unlocking it in about 24 hours to see if things cool down.

**Comment by GarrettRathke** [comment]
Ughh.. gross.. I find GitHub's and (insert nearly any big tech name here) pompousness revolting and sad. Being fully convinced of the goodness of ones own world-view, while claiming to tolerate other world-views, yet swiftly shutting down disagreement - how is that not pompous? Google should follow its own advice and "not be evil" by getting out of politics and just letting people work.

**Comment by bk2204** [comment]
I realize that not everyone may like the fact that I suspended discussion here, but because this is potentially controversial and there's been a lot of heated discussion around similar topics on the Git list, including some discussion which is outright offensive, I'm keeping the discussion on this issue on an extremely short leash to make sure it stays firmly within our [Code of Conduct](https://github.com/git-lfs/git-lfs/blob/master/CODE-OF-CONDUCT.md).  I have no problems with suspending discussion further if things become out of control, and I urge everyone to give careful consideration to their words and avoid escalating things.

I don't think it's possible for a software project to avoid taking any political stances, especially since free software and open source are political movements, albeit slightly different ones.  Projects also make decisions about how they want to create communities around their software and how they want to use language, and those are also unavoidable political decisions.  As mentioned, there are a decent number of Black folks who see the current name as a problem, and there are others that don't.  My reading of the consensus on the Git list is that the name “master” was, in retrospect, suboptimal, and if the decision were being made today, we'd have chosen a different name. Since the cost to us doing this is very minor and we aim to be a welcoming community for people of all backgrounds, the core team is generally in agreement that we do want to do this.

Not everyone has to agree, and that's okay.  As the core team, we certainly make decisions about things that not everyone is going to like, but we have to do what we think is best for the project and the community as a whole.

I do appreciate that this issue has lagged; I've been looking at other things recently, and I hope to get some time to come back to it soon.

**Comment by GarrettRathke** [comment]
> I don't think it's possible for a software project to avoid taking any political stances
Everyone is entitled to their opinion. My opinion, and clearly that of many, many others, is that a political stance of "classical liberalism" - shall we call it - is the best stance, meaning don't impose your opinions on others.

> especially since free software and open source are political movements
Free software and open source are political movements.
GitHub promotes free software and open source.
Certain controversial current events are also political movements.
Therefore, GitHub also promotes certain controversial current events.

> there are a decent number of Black folks who see the current name as a problem, and there are others that don't. 
Fallacious argument from authority: in order for one's opinion to be valid, one must have the proper credentials. In this case, the credential is having an arbitrary amount of melanin in the skin. Those who don't satisfy the melanin credentialing have invalid or less valid opinions. And those who do satisfy the melanin credentialing but who don't agree with GitHub's controversial identity politics also have invalid or less valid opinions.

> we aim to be a welcoming community for people of all backgrounds
...except backgrounds of differing opinion

This is so disappointing. False humility and a fake smile don't promote unity. If you truly believed what you just wrote, that it's ok for people to have different opinions, then you wouldn't be defending a policy that puts words into people's mouths, or command lines as the case may be. For many who have an individualist, classical liberal world-view (as opposed to a collectivist, postmodern leftist one), changing language benefits no one. It is a slippery slope of tit-for-tat politics. Trying to sandwich it in between nice words doesn't make it taste any better.

**Comment by bk2204** [comment]
This has been completed.  Closing.

**Comment by dscho** [comment]
FWIW I agree with @bk2204.

It strikes me as a wise decision to empathize with those who feel the toll of this harmful language, daily, and I fail to see that changing that language bears much cost.

I went through this exercise with Git for Windows' repositories, and the fallout has been negligible at best.
