### ISSUE TITLE
SSH alias does not work without user

### ISSUE THREAD

**Issue by bj0** [git-lfs/git-lfs#4162]
**Describe the bug**
I am trying to clone a repo from a gitlab server that has lfs files in it.  I have the server aliased in ~/.ssh/config and am using ssh key authentication, and when I try to clone with:

git clone gitlab:/path/to/repo.git test

it fails with the error:
Error downloading object: file.jar (4b79f08): Smudge error: Error downloading file.jar (4b79f08b4d5ebb0f96d2c69ec5b56d991cdda720ce3ae8d10af239e7676778b8): batch request: remote: 
remote: ========================================================================
remote: 
remote: The project you were looking for could not be found.
remote: 
remote: ========================================================================
remote:: exit status 1

Errors logged to /mnt/data/code/android/test/.git/lfs/logs/20200616T122916.941877223.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: file.jar: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
 

when I clone with a user:
git clone git@gitlab:/path/to/repo.git test

it works fine.

I saw this merge request which says that it fixed the issue in version 2.6:
https://github.com/git-lfs/git-lfs/pull/3230

But I am updated to version 2.11.0

git lfs env shows this wrong looking endpoint:
Endpoint=https://gitlab////path/to/repo.git/info/lfs (auth=none)
  SSH=gitlab:///path/to/repo.git

**System environment**
Ubuntu 20.04 x64
git version 2.25.1
git-lfs/2.11.0 (GitHub; linux amd64; go 1.13.4)

server is gitlab ce 12.10.3
```
Endpoint=https://gitlab////path/to/repo.git/info/lfs (auth=none)
  SSH=gitlab:///path/to/repo.git
LocalWorkingDir=/mnt/data/code/android/test
LocalGitDir=/mnt/data/code/android/test/.git
LocalGitStorageDir=/mnt/data/code/android/test/.git
LocalMediaDir=/mnt/data/code/android/test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/mnt/data/code/android/test/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/mnt/data/code/android/test/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Are you using a leading slash as part of your path in the SSH URL?  If so, does it work if you remove it?

I think what's happening here is that the Git endpoint and the Git LFS endpoint for GitLab handle the leading slash differently.  They do for GitHub as well: `ghtest:git-lfs/test-repo.git` works for me, but `ghtest:/git-lfs/pull-bug.git` fails with an error from the server that the repository is invalid.

**Comment by bj0** [comment]
Yes, I normally use the leading slash.  It looks like removing the leading slash does make it work correctly.

**Comment by bk2204** [comment]
Okay, great.  Since this seems like the remote side being unhappy in this case and there isn't anything we can do about that, I'm going to close this.
