### ISSUE TITLE
Git-lfs update not visible

### ISSUE THREAD

**Issue by tedvanhaalen** [git-lfs/git-lfs#4163]
Hi,

I have a machine with git-lfs v2.7.1 on it as part of a git v2.21.0 installation. I wanted to update git-lfs and therefor I have installed git-lfs v2.11.0. However, it looks as if v2.7.1 is still used.

**Output of `git config -l`:**
```
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslbackend=schannel
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
http.sslverify=false
http.sslbackend=schannel
https.sslverify=false
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
```

**Output of `git lfs env`**
```
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.21.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_SSL_NO_VERIFY=true
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

As you can see the `GIT_LFS_PATH` environment variable exists pointing to the folder with git-lfs v2.11.0 in it. This folder is also in the `PATH` system environment variable. But output from `git lfs version` still gives `git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)`.

Is there something I still need to do? Change the git configuration?

**Comment by bk2204** [comment]
Hey,

Git for Windows installs the Git LFS binary into `GIT_EXEC_PATH`, if I remember correctly, which makes it take precedence over the elements of `PATH`.  We're currently tracking this as #4002, which has workarounds, but we have nobody knowledgeable about the installer to make it replace the Git for Windows binary.
