### ISSUE TITLE
**Only LFS files** show as modified in WSL Linux 

### ISSUE THREAD

**Issue by dkao-roblox** [git-lfs/git-lfs#4164]
**Describe the bug**

**Only** files that go through git-lfs would show up as modified in WSL but not modified in Windows.

For non-LFS regular text files, I have gone through the `git config core.autocrlf` true and `git config core.fileMode` false exercise and those non-LFS files work without issues. This is not the usual Windows-CRLF-Linux problem (well, unless the LFS files are also subject to the same issue and needs a separate set of configuration; then I need to learn how to configure it for LFS).

**To Reproduce**

A snippet from my work's lfs filter in .gitattributes

*.[pP][nN][gG] filter=lfs diff=lfs merge=lfs -text
*.[jJ][pP][gG] filter=lfs diff=lfs merge=lfs -text
*.[jJ][pP][eE][gG] filter=lfs diff=lfs merge=lfs -text
*.[gG][iI][fF] filter=lfs diff=lfs merge=lfs -text
*.[iI][cC][oO] filter=lfs diff=lfs merge=lfs -text
*.[bB][mM][pP] filter=lfs diff=lfs merge=lfs -text
... (more omitted)

basically, we only put files like images and dlls through LFS

If I run `git status` in Windows, it generates a .git/index file that would show no files modified (indeed I made no changes).

But `git status` in WSL, would show all the LFS files as modified.

For non-LFS regular text files, I have gone through the `git config core.autocrlf` true and `git config core.fileMode` false exercise and they work as expected; not modified in both Windows and WSL Ubuntu land.

Only for files that go through git-lfs, that it would show up as modified in WSL but not modified in Windows.

**Expected behavior**

Given the same git repo, `git status` should show the same output for both Windows command line and WSL Bash.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

Windows 10 Pro, installed WSL Ubuntu, access /mnt/c/gitrepo that's shared with the "host" Windows.

```
$ git config -l
user.name=dkao
user.email=<redacted>
credential.helper=store
core.autocrlf=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.autocrlf=true
<... company specific info omitted>
```

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

```
$ git lfs env
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)
git version 2.25.1

Endpoint=<redacted>/info/lfs (auth=basic)
LocalWorkingDir=/mnt/c/git1/web-platform
LocalGitDir=/mnt/c/git1/web-platform/.git
LocalGitStorageDir=/mnt/c/git1/web-platform/.git
LocalMediaDir=/mnt/c/git1/web-platform/.git/lfs/objects
LocalReferenceDir=
TempDir=/mnt/c/git1/web-platform/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/mnt/c/git1/web-platform/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Additional context**

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  What does the `git diff --ws-error-highlight=all` output look like when you have files that are modified?

**Comment by dkao-roblox** [comment]
a bunch of

diff --git a/<directory path>/favicon.ico b/<directory path>/favicon.ico
index 94a71520fd..9e9bf3fca3 100644
Binary files a/<directory path>/favicon.ico b/<directory path>/favicon.ico differ

PS: all <directory path> are same; I edited them out.
PS: other suffixes using LFS, like png and dll, all have the same messages.

I tried getting the MD5 sum just now. They are the same in powershell and in WSL:

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             D1DDE0CC072CE657CD3A5456FABE05DC                                       C:\<path>\searchIcon.png



$ md5sum /mnt/c/<path>/searchIcon.png
d1dde0cc072ce657cd3a5456fabe05dc  /mnt/c/<path>/searchIcon.png


I also tried opening the png file using vi in GitBash and in WSL. Turn on :setlist to view line-endings, and as far as the **eye** can tell, they are the same. In both worlds, the first line has `89>PNG^M$`, while the rest don't have any `^M`

**Comment by bk2204** [comment]
Hey,

The problem here is that these files haven't been checked in as LFS files.  It's likely that either the person who committed them didn't have Git LFS installed properly or the `.gitattributes` file was added without running `git add --renormalize .`.  The easiest way to fix this is to do `git add --renormalize .` and then do a commit, which should turn them all into LFS files.

If you do that, they should be properly checked out on both systems.  Note that there are additional steps you may have to take to share a repository between systems, as outlined [in this StackOverflow answer](https://stackoverflow.com/a/58566594).

**Comment by dkao-roblox** [comment]
Thank you for the answer. For the other readers, that link to **StackOverflow answer** was really helpful.
