### ISSUE TITLE
Should lockable gitattribute be specific to Git LFS?

### ISSUE THREAD

**Issue by jamesramsay** [git-lfs/git-lfs#4168]
`git-lfs` appears to treat the `lockable` attribute as exclusively an attribute used by Git LFS. By way of example, add another pattern that does not use `lfs`.

```
*.png filter=lfs diff=lfs merge=lfs -text lockable
*.txt lockable
```

This results in all files matching this pattern having write permissions removed.

@ttaylorr do you think it would be reasonable for `git-lfs` to check that at least one of filter/diff/merge are set to `lfs` before considering the `locable` attribute?

I ask because GitLab has a concept of file locking that can be used for any file. This is primarily for files where conflicts can be resolved, which means that it applies only to the default branch so that collaborators can still push feature branches and merge once the lock has been removed. However, for large file workflows this is unsuitable, and the global write lock approach is ideal.

With partial clone possibly being a plausible alternative for Git LFS, I was thinking maybe GitLab could also use the `lockable` attribute to switch between these two locking modes to be consistent with LFS locking. However, if I was to proceed with this approach there seem to be compatibility problems.

**Comment by bk2204** [comment]
Hey,

I don't think we currently require files to be LFS files before being lockable, and certainly there are some folks who rely on that.  In fact, I seem to remember that there are folks who use Git LFS for locking only and not large file support.  I could imagine this being useful for small images that don't really need to be stored in LFS but of course can't be logically merged.

**Comment by jamesramsay** [comment]
> I seem to remember that there are folks who use Git LFS for locking only and not large file support

Thanks @bk2204 - that's very helpful feedback. I'll close this issue since it seems this behaviour is intended and depended on. :+1:

**Comment by ttaylorr** [comment]
> certainly there are some folks who rely on that

I know that originally (maybe with @kdaigle? I can't remember) we talked about maybe shipping a binary that was _just_ the `git lfs lock` and `git lfs locks` command(s), without the rest of Git LFS. This might be something worth revisiting, especially since there are a lot of unresolved questions on the server-side of how to store large blobs in Git itself.

**Comment by jamesramsay** [comment]
> maybe shipping a binary that was just the git lfs lock and git lfs locks command(s), without the rest of Git LFS

@ttaylorr that would be an interesting future improvement. As you say, lots of other problems to work out yet with storing large files server-side without LFS.

**Comment by jamesramsay** [comment]
A follow up question, it appears that `lockable` only controls if the file is marked as read only by default, and that GitHub does not validate if the file is `lockable`. This allows an exclusive lock to be taken for any file at all.

Since file locks can be quite disruptive, is this intentional?

**Comment by bk2204** [comment]
At least for GitHub, the lock server need not know anything about the actual repository.  Users can and do use external LFS servers (e.g., Artifactory) without having access to the repository.  So without some way of communicating between the two, it doesn't appear that we can add validation.
