### ISSUE TITLE
Unlocking a file that is not `lockable` should not make the file read only

### ISSUE THREAD

**Issue by jamesramsay** [git-lfs/git-lfs#4169]
**Describe the bug**

If a file is locked (doesn't need to be tracked by LFS) and is not `lockable`, when unlocking the file it will be marked read only until the user manually corrects the permissions.

**To Reproduce**

```
# Setup a clean repo
mkdir lfs-repro
cd lfs-repro
git init
echo "# LFS test" > README.md
git add README.md
git commit -m "Init"

# Add a remote that supports LFS locking
git remote add origin https://github.com/jamesramsay/lfs-repro.git

# Lock and unlock
git lfs install
git lfs lock README.md
git lfs unlock README.md

# Observe read-only permissions
ls -la README.md
```

As far as I can tell, Git LFS never changes the permissions again, so they are stuck as read only until manually resolved.

**Expected behavior**

Since the file is not marked `lockable`, the file should not be set to read only when unlocked.

**System environment**

macOS 10.15.5

<details><summary>**Output of `git lfs env`**</summary>

```
git-lfs/2.11.0 (GitHub; darwin amd64; go 1.14.2)
git version 2.27.0

Endpoint=https://github.com/jamesramsay/lfs-repro.git/info/lfs (auth=none)
  SSH=git@github.com:jamesramsay/lfs-repro.git
LocalWorkingDir=/Users/jramsay/GitLab/temp/lfs-repro
LocalGitDir=/Users/jramsay/GitLab/temp/lfs-repro/.git
LocalGitStorageDir=/Users/jramsay/GitLab/temp/lfs-repro/.git
LocalMediaDir=/Users/jramsay/GitLab/temp/lfs-repro/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/jramsay/GitLab/temp/lfs-repro/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/jramsay/GitLab/temp/lfs-repro/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.27.0/libexec/git-core
GIT_TRACE2_PARENT_NAME=_run_dashed_
GIT_TRACE2_PARENT_SID=20200625T025724.504881Z-H0bad8183-P00002d11
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

</details>

**Comment by jamesramsay** [comment]
This is related to my question about the reverse https://github.com/git-lfs/git-lfs/issues/4168#issuecomment-649164439 on the server side: if a file is not lockable, should the server allow me to take the lock?

If the server didn't allow me to take the lock because the file isn't lockable, then this bug probably wouldn't exist because I wouldn't have been able to lock it in the first place.

**Comment by bk2204** [comment]
Hey,

Yeah, we probably should not mark the file read only if it's not lockable.  We do need to be able to unlock files which no longer exist because sometimes the `.gitattributes` file changes or files are deleted.

It is intentional that the LFS server doesn't know about the current state of the repository, as mentioned in #4168. Even if it did, locks apply across branches, so it would be hard to determine where the `lockable` attribute should be set, since it could apply to any revision.
