### ISSUE TITLE
LFS Put url different from endpoint url (Put url wrong)

### ISSUE THREAD

**Issue by zardini123** [git-lfs/git-lfs#4172]
**Describe the bug**
When uploading my Git LFS objects to a Gitea server, it will attempt to Put the object, but for some ungodly reason the Put command url is an old url of the repo.  It exits upload and throws an error that states the *new* url.  See here:

```
LFS: Put "https://<old url>/.../...git/info/lfs/objects/<hash>": dial tcp <old url>: connect: connection refused
error: failed to push some refs to 'http://<new url>/.../...git/'
```

I cleaned out my git config of all the ifs config, along with reseting my remote origin url, and this still happens.  Is the fact that I changed from a *https* to a *http* url have to do with this issue?  How would one even change the Put url?

**To Reproduce**
To be honest I have no idea.

**Expected behavior**
For the Put url's base to be the same as the endpoint's base.

**System environment**
MacOS Git LFS installed via Homebrew:  git-lfs/2.11.0 (GitHub; darwin amd64; go 1.14.2)

**Output of `git lfs env`**
```
Endpoint=http://<new url>/.../...git/info/lfs (auth=basic)
LocalWorkingDir=...
LocalGitDir=...
LocalGitStorageDir=...
LocalMediaDir=...
LocalReferenceDirs=
TempDir=...
ConcurrentTransfers=20
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=...
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

This URL comes from the server side.  If you moved your Gitea server to a new address or hostname but didn't update the configuration, then it will still be using the old hostname when it generates URLs.  You can see what the URL you're getting is by running your push command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`.  That will show you the output from the `/objects/batch` endpoint, which provides the `PUT` URLs.
