### ISSUE TITLE
Git lfs not uploading to my repo

### ISSUE THREAD

**Issue by Vthechamp22** [git-lfs/git-lfs#4184]
I cannot upload my files to my repository, even though I installed git-lfs, initialised it and followed the steps:
![image](https://user-images.githubusercontent.com/61617820/86781268-4cc96980-c07b-11ea-8ac5-917fd0bf17a3.png)
I do not know why this is not happening. I had once previously uploaded a file using lfs, which was 394 MB, but this file is only 160 MB. Please help if you can.
Thanks in advance

**Comment by bk2204** [comment]
Hey,

It looks like in this case that the file that's supposed to be tracked is already committed, so it's not being handled by Git LFS, but by Git itself.  It's important to run `git lfs install` and `git lfs track` before you commit anything.

If you have only one commit or you added the large file only in the most recent commit, then you can do `git add --renormalize . && git commit --amend --no-edit` and that should fix your file.  If you've modified things earlier on, you can run `git lfs migrate import --everything --include="*.csv"` and that should rewrite your history such that it contains only LFS objects for `.csv` files.
