### ISSUE TITLE
Authentication issue  

### ISSUE THREAD

**Issue by renzosilv** [git-lfs/git-lfs#4185]
**Describe the issue**
My git lfs setup seems to be crashing during the https verification.

This is what I think is where it is going wrong. 
05:28:31.420546 trace git-lfs: run_command: ssh -- git@gitu git-lfs-authenticate renzosilva/lfs-test.git upload
05:28:32.307395 trace git-lfs: HTTP: POST https://unity.marvell.com:4433/renzosilva/lfs-test.git/info/lfs/locks/verify
> POST /renzosilva/lfs-test.git/info/lfs/locks/verify HTTP/1.1
> Host: unity.marvell.com:4433
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 36
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.11.0 (GitHub; linux amd64; go 1.13.4; git 48b28d97)
> 
{"ref":{"name":"refs/heads/master"}}05:28:33.452041 trace git-lfs: HTTP: 401

Any assistance would be greatly appreciated. 

**System environment**
git config -l
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=renzosilva
user.email=renzosilva@marvell.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=store
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://unity.marvell.com:4433/renzosilva/lfs-test.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.https://unity.marvell.com:4433/renzosilva/lfs-test.git/info/lfs.access=basic
lfs.https://unity.marvell.com:4433/renzosilva/lfs-test.git/gitlab-lfs/objects/.access=basic
lfs.https://gitu/renzosilva/lfs-test.git/info/lfs.access=basic
http.sslverify=false

**Output of `git lfs env`**
bash-4.2$ git lfs env
git-lfs/2.11.0 (GitHub; linux amd64; go 1.13.4; git 48b28d97)
git version 1.8.3.1
Endpoint=https://unity.marvell.com:4433/renzosilva/lfs-test.git/info/lfs (auth=basic)
LocalWorkingDir=/nas/pnp/renzo/lfs-test
LocalGitDir=/nas/pnp/renzo/lfs-test/.git
LocalGitStorageDir=/nas/pnp/renzo/lfs-test/.git
LocalMediaDir=/nas/pnp/renzo/lfs-test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/nas/pnp/renzo/lfs-test/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/nas/pnp/renzo/lfs-test/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey, 

The 401 means that you're likely not authorized to access that repository.  I'm not sure what hosting platform you're using, but it looks like that the server has accepted your credentials over SSH but then gave you credentials for HTTPS that didn't work.  Normally a user should have push permissions both to upload files and verify locks and so having one set of permissions should be sufficient to do both.

I'd reach out to your server administrator and ask them about this problem, since it's the server side that's reporting the 401 to the client.
