### ISSUE TITLE
Migrate export messed the project (probably): "refusing to merge unrelated histories"

### ISSUE THREAD

**Issue by Romaleks360** [git-lfs/git-lfs#4187]
**Describe the issue**
Hello everyone. I've decided to remove LFS from my repo because I don't want to pay for a data plan (it's 2GB - 5$ already).

I followed these steps: https://stackoverflow.com/a/57681990, but there's nothing stated on what to do next. 

Pulling gives an error `fatal: refusing to merge unrelated histories`.

git status says: 
```
On branch master
Your branch and 'origin/master' have diverged,
and have 104 and 103 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```
I'm a bit scared now. What should I do next? I'm very bad at using Github and command line stuff...
There are a few ways to get rid of LFS on the internet, but all of them look too complicated. It would be great to have a straightforward official guide, so other dummies like me could do that.
Also, how do I fully delete LFS from my PC?
Thank you!

**System environment**
Windows 10

**Output of `git lfs env`**
```
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
git version 2.23.0.windows.1

Endpoint=https://github.com/Romaleks360/Jumpy-Quads.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\Tom\Desktop\Jumpy Quads\Jumpy Quads
LocalGitDir=C:\Users\Tom\Desktop\Jumpy Quads\Jumpy Quads\.git
LocalGitStorageDir=C:\Users\Tom\Desktop\Jumpy Quads\Jumpy Quads\.git
LocalMediaDir=C:\Users\Tom\Desktop\Jumpy Quads\Jumpy Quads\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\Tom\Desktop\Jumpy Quads\Jumpy Quads\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\Tom\Desktop\Jumpy Quads\Jumpy Quads\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Once you've run `git lfs migrate export`, the repository should have its commits completely rewritten.  You should be able to force-push with Git, by running something like `git push origin +master`, and that will push your newly rewritten repository to the remote.

You don't want to perform a merge, since that will end up having a large number of conflicts, and you'll still have the LFS pointers in your history, which you don't want.
