### ISSUE TITLE
Can ibm cloud object store be used as git lfs third party server

### ISSUE THREAD

**Issue by sandeep-sarkar** [git-lfs/git-lfs#4188]
While going through https://docs.github.com/en/enterprise/2.19/admin/installation/configuring-git-large-file-storage-to-use-a-third-party-server

1) Created cloud object store in IBM Cloud
2) `git config -f .lfsconfig remote.origin.lfsurl https://mybucketfortesting.s3.jp-tok.cloud-object-storage.appdomain.cloud/lfstest/`

After this when I am trying to do git push it is not pushing to this location. Also I do not see any error message. What shall I do ?

**Comment by bk2204** [comment]
Hey,

It's not possible to use any cloud storage bucket as a server without an additional API server or custom transfer adapter.  You can see what the APIs look like at https://github.com/git-lfs/git-lfs/tree/master/docs/api.

It is possible to add an API server and use a cloud storage bucket for the URLs that the batch API gives out; this is how the GitHub implementation works.  It's also possible to use a [custom transfer adapter](https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md) to transfer directly to your cloud storage bucket if you like.
