### ISSUE TITLE
remote: error: GH008: Your push referenced at least 1 unknown Git LFS object: remote:  Try to push them with 'git lfs push --all'.

### ISSUE THREAD

**Issue by nickk2002** [git-lfs/git-lfs#4190]
**Issue**
Hi exceeded the git lfs limit of free use and I want to remove the large files from my repo so that I can continue to work and push on origin in order for others to get my work and so on.

When I write `git push` I get this error saying that there is an unknown git lfs object

**Error**
Enumerating objects: 404, done.
Counting objects: 100% (404/404), done.
Delta compression using up to 8 threads
Compressing objects: 100% (333/333), done.
Writing objects: 100% (340/340), 799.04 KiB | 14.02 MiB/s, done.
Total 340 (delta 249), reused 1 (delta 0)
remote: Resolving deltas: 100% (249/249), completed with 48 local objects.
remote: error: GH008: Your push referenced at least 1 unknown Git LFS object:
remote:     19b36b9439fa92b7a60fa788b6366c87b013212c49bc68a157fdfd432204ef47
remote: Try to push them with 'git lfs push --all'.
To https://github.com/nickk2002/AI-Covid-19.git
 ! [remote rejected] IBehaviour_Implementation -> IBehaviour_Implementation (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/nickk2002/AI-Covid-19.git'

Running `git lfs push --all origin master` says it can't find an animation
```
Unable to find source for object b86f2fbf21654f34d45516b477a5611998051a676d1e763664d320bd5187788f (try running git lfs fetch --all): open E:\Quick access\Documents\Info\GitHub\AI-Covid-19\AI Covid 19\Assets\Ani
mations\Defeated.fbx: The system cannot find the file specified
```
Running this `git lfs fetch --all`
I get ```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/nickk2002/AI-Covid-19.git/info/lfs'
```


I have seen that there are others issues similar to mine posted here but I could not understand what I should actually do to solve my problem.
I saw this git command `git config --list | grep lfs` but It gives a unknown command error
'grep' is not recognized as an internal or external command,
operable program or batch file.

So, I am quite confused about how to solve this issue without buying more data.

**The git config -l**

```
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
credential.helper=manager
user.name=nickk2002
user.email=nicolae.filat@yahoo.com
gui.recentrepo=E:/Quick access/Documents/GitHub/AI-Unity
difftool.sourcetree.cmd='C:/Program Files/Unity/Editor/Data/Tools/UnityYAMLMerge.exe' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd='C:/Program Files/Unity/Editor/Data/Tools/UnityYAMLMerge.exe' merge -p $BASE $REMOTE $LOCAL $MERGED
mergetool.sourcetree.trustexitcode=true
core.autocrlf=true
core.safecrlf=false
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
```

**Output of `git lfs env`**

```
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.21.0.windows.1

Endpoint=https://github.com/nickk2002/AI-Covid-19.git/info/lfs (auth=none)
LocalWorkingDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19
LocalGitDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git
LocalGitStorageDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git
LocalMediaDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git\lfs\objects
LocalReferenceDirs=
TempDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I deleted my entire index folders using `git rm . -r --cached` And then added only the code base and just that. But there is a git lfs lying somewhere there. I tried running `git lfs uninstall` but it did not help either. Any Help will be apprecated

**Comment by bk2204** [comment]
Hey,

If you want to remove the support for Git LFS, you should use the `git lfs migrate export` command.  You probably want to use the `--everything` option to rewrite the entire history.  Note that this does rewrite the history, and therefore you'll have to force-push.

If your files are actually large and you want to remove them, then you'll need to use something like `git filter-branch` to remove them from your repository totally instead of just converting them from LFS objects to Git objects, as `git lfs migrate export` does.  You may also want to update the `.gitattributes` file to not use `filter=lfs` as part of the same process.
