### ISSUE TITLE
.lfsconfig URL is ignored when pushing a bare clone after migration

### ISSUE THREAD

**Issue by Tristan107** [git-lfs/git-lfs#4192]
**Describe the bug**
.lfsconfig URL is ignored when pushing a bare clone after migration

`git push` tries to upload to my Gitlab server instead of using the customized lfs URL pointing to some Nexus repository.

**To Reproduce**
1. git clone --mirror https://my-gitlab-server.fr/projet.git
2. Setup upload URL for LFS objects on default branch (master) :
```
git clone projet.git projet-workspace
cd projet-workspace
git config -f .lfsconfig lfs.url https://my-nexus-server.fr/repository/projet-gitlfs/info/lfs
git lfs env #To check Endpoint is correctly set
git add .lfsconfig
git commit -m "setup LFS URL" && git push
```
3. Start migration
cd ../projet.git
`git lfs migrate import --verbose --include='*.bz,*.gz' --everything`

4. Push the result
```
$ git push
Uploading LFS objects:   0% (0/101), 0 B | 0 B/s, done.
batch response: Git LFS is not enabled on this GitLab server, contact your admin.
batch response: Git LFS is not enabled on this GitLab server, contact your admin.
batch response: Git LFS is not enabled on this GitLab server, contact your admin.
```
Note : This "batch response" is the correct response from Gitlab Server since Git LFS is disabled on this server. What is wrong is the URL used by git lfs.

**Expected behavior**
lfs pointers are pushed to Gitlab and lfs objects are uploaded to Nexus, respecting the URL in .lfsconfig

**System environment**
Windows 10
Git bash 2.25.0.windows.1

```
$ git config -l # In bare directory
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Dev/tools/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=false
core.fscache=true
core.symlinks=false
core.editor="C:\\Dev\\tools\\npp\\notepad++.exe"
core.longpaths=true
credential.helper=manager
user.name=Johnny Halliday
user.email=Johnny@heaven.fr
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://si-devops-gitlab.edf.fr/dvs-integration/support/talend-odr-rh-gitlfs.git
remote.origin.fetch=+refs/*:refs/*
remote.origin.mirror=true
#Wrong URL, not the one from .lfsconfig on master :
lfs.https://my-gitlab-server.fr/projet.git/info/lfs.access=basic
lfs.https://my-gitlab-server.fr/projet.git/info/lfs.locksverify=false
```

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.9.2 (GitHub; windows amd64; go 1.12.7; git 0274d856)
git version 2.25.0.windows.1

Endpoint=https://my-gitlab-server.fr/projet.git/info/lfs (auth=basic)
LocalWorkingDir=
LocalGitDir=C:\Dev\projects\accompagnement\projet.git
LocalGitStorageDir=C:\Dev\projects\accompagnement\projet.git
LocalMediaDir=C:\Dev\projects\accompagnement\projet.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Dev\projects\accompagnement\projet.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Dev\projects\accompagnement\projet.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Dev/tools/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
In a regular clone, the LFS URL is correct and is visible in git lfs env.

**Comment by Tristan107** [comment]
After some experimentations, I can make it work by copying my .lfsconfig file from master branch to my bare directory, which is just weird : if I put this .lfsconfig here, it's just not comitted and no one can ever clone the resulting git repository since they don't know where the LFS objects are.

Are we supposed to duplicate the .lfsconfig manually in all branches and in bare repositories ?

**Comment by bk2204** [comment]
Hey,

The `.lfsconfig` file is currently known to be read only from the working tree, not from the repository at all.  This is much like the behavior of `.gitattributes`.  We're currently tracking this as #4077, but for now, you'll need to have a working tree if you want it honored.

**Comment by Tristan107** [comment]
Hi, thanks for your quick answer.
Can you tell me what is the recommended process after `git lfs migrate import --verbose --include='*.bz,*.gz' --everything` on a mirror clone, in the current state of git lfs ?

**Comment by bk2204** [comment]
In general, we don't recommend you do that on a bare clone right now if you need to use `.lfsconfig` and that you check out some revision in the working tree.  Alternatively, if you're pushing to an LFS server associated with a remote, you can just push using the name or URL of the remote and let autodetection happen.

**Comment by Tristan107** [comment]
> we don't recommend you do that on a bare clone right now if you need to use .lfsconfig
However, it seems to work to create this file in a bare git repository before pushing, what is the drawback you are seeing here (besides the fact .lfsconfig is not tracked which can be compensated by adding it to master branch) ?


> we recommend (...) that you check out some revision in the working tree.
Sure if I have only one branch it's fine, not if I have multiple branches

>  if you're pushing to an LFS server associated with a remote
I guess remote are only for git servers and we push on nexus server

**Comment by bk2204** [comment]
> > we don't recommend you do that on a bare clone right now if you need to use .lfsconfig
> 
> However, it seems to work to create this file in a bare git repository before pushing, what is the drawback you are seeing here (besides the fact .lfsconfig is not tracked which can be compensated by adding it to master branch) ?

It may work, but we don't guarantee that it will work in the future.  That it works at all is an accident and, I would argue, a bug.  We shouldn't be reading working tree files directly from bare repositories.

> > we recommend (...) that you check out some revision in the working tree.
> 
> Sure if I have only one branch it's fine, not if I have multiple branches

You can check out any revision and then push multiple branches at once.

> > if you're pushing to an LFS server associated with a remote
> 
> I guess remote are only for git servers and we push on nexus server

Yeah, then I suspect it won't work for you.

**Comment by Tristan107** [comment]
Ok, thanks for these details it's more clear now.

> You can check out any revision and then push multiple branches at once.

This is probably the way to go but I don't get it (maybe lack of knowledge about git) :  
If I do the first steps described in "To reproduce" above, then I push from my projet-workspace which is a local checkout, as far as I know it pushes only the main branch (master). The only way I know to fetch then push multiple branches is with a mirror clone.

**Comment by bk2204** [comment]
No, I'm suggesting that you do `git worktree add` to add a worktree and then run your command there.  The `mirror` flag should still be set for that remote.

**Comment by Tristan107** [comment]
Ok, this actually works when pushing from a directory created with `git worktree add`, it pushes all branches and respect the .lfsconfig, that's nice.

Now, what also works (and should continue to work) for this "push multiple branches after git lfs migration" use case is to use : 
`git config lfs.url https://my-nexus-server.fr/repository/projet-gitlfs/info/lfs` in my bare repository

What will not work, on the other hand, is the "push" from any branch other than "master" from developer clones. Except if there is some mechanism which checks the existence of ".lfsconfig" on master branch (is it what is considered in #4077 cause I don't see the word "master") ?
