### ISSUE TITLE
Is there any method for the lfs-server to get the file extensions through LFS api?

### ISSUE THREAD

**Issue by xzy57369** [git-lfs/git-lfs#4197]
**Describe the issue**
Hi, I am working on the developing of a LFS server, which interact with git-lfs client through the [API](https://github.com/git-lfs/git-lfs/blob/master/docs/api/basic-transfers.md). The binary files were stored on AlibabaCloud Object Storage Service.

We want to provide a management dashboard on the website, showing the information of the files tracking by lfs. The information including  oid, size and file types(jpg, pdf,...). We planed to insert a record into the database at some particular point through the interaction(say, batch or verify). 

The problem is that when using the LFS API, there is no way for the lfs-server to know the file types. The server only knows the oid and size of each file. We have checked the lfs-client code, but did not find any configurations to send file type informations to the server.

We have also checked the AlibabaCloud Object Storage Service's ability, unfortunately the filename was set to oid,  and content-type is oct-stream, still no information can be used.

So, is there any method or configuration to let the lfs-server know the file types or any detail we have been missed? Any suggestion is appreciated!

**Comment by xzy57369** [comment]
@bkeepers  Could you please give any suggestions?

**Comment by bk2204** [comment]
Hey,

No, there isn't any way for the LFS server to know such a thing.  That information is stored only in the Git repo, not in the LFS server.  The Git LFS client will usually provide a `Content-Type` header in newer versions, which may be helpful for your purposes, although sometimes it will provide `application/octet-stream`, especially in older versions.
