### ISSUE TITLE
lfs url not honored from "git lfs fetch", before files are populated

### ISSUE THREAD

**Issue by jeschu1** [git-lfs/git-lfs#4198]
**Describe the bug**
The Azure Devops Build agent, uses fetch in the checkout task before the files are put on disk as shown in the repro steps.
When `git lfs fetch origin commitId` is run it goes against the remote url, not the configured lfs url.
We have logs that appear to show this working in a previous version and user feedback to that effect.

**To Reproduce**
Create an lfs repository where the objects are hosted outside of the repo
i.e.
D:\lfs_test\z\z_clone\z>more .lfsconfig
[remote "origin"]
        lfsurl = http://my-pc/DefaultCollection/my/_git/z2/info/lfs

[lfs]
        url = http://my-pc/DefaultCollection/my/_git/z2/info/lfs

D:\lfs_test\z\z_clone\z>git remote -v
origin  http://my-pc/DefaultCollection/my/_git/z (fetch)
origin  http://my-pc/DefaultCollection/my/_git/z (push)

Note the use of z versus z2 in the urls

1. Create a new Directory
2. git init .
3. git remote add origin http://my-pc/DefaultCollection/my/_git/z
4. git config gc.auto 0
5. git config --get-all http.http://my-pc/DefaultCollection/my/_git/z.extraheader
6. git config --get-all http.proxy
7. git lfs install --local
8. git fetch --force --tags --prune --progress --no-recurse-submodules origin
9. git lfs fetch origin commitId
10. git checkout --progress --force commitId

Step 9 fails because it attempts to hit the endpoint http://my-pc/DefaultCollection/my/_git/z/info/lfs not http://my-pc/DefaultCollection/my/_git/z2/info/lfs

**Expected behavior**
Step 9, should succeed and go against z2

**System environment**
Windows

**Output of `git lfs env`**
After checkout
D:\lfs_test\z\z_clone\z>git lfs env
git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git 08a08ae0)
git version 2.27.0.vfs.0.0

Endpoint=http://my-pc/DefaultCollection/my/_git/z2/info/lfs (auth=ntlm)

However the Endpoint is the other url at step 9

**Additional context**
Questions:
1. Should doing "git lfs fetch" like this work?
2. Do you know if this ever worked?
3. Is the "git lfs fetch" needed in Step 9?

**Comment by bk2204** [comment]
Hey,

I think what you're seeing is #4077.  If there are files that sort lexicographically before `.lfsconfig`, then they will not honor the URL in that file.  Can you confirm that your test repository has such a file?

I'm currently working on a fix for this as time permits, and I hope to have it in before 2.12.0, although I can make no guarantees.

**Comment by jeschu1** [comment]
Hi @bk2204 ,

  The test file i used for lfs was called "abc.txt".  I  don't believe it would sort before .lfsconfig.

**Comment by jeschu1** [comment]
@bk2204 I think this is different because I tested with a file called `abc.txt` and that should sort after `.lfsconfig`

I believe these are the answers to my questions above.  Can you confirm?


> 1. Should doing "git lfs fetch" like this work?

Not if the repo remote != lfs endpoint

> 2. Do you know if this ever worked?

From the code it doesn't appear this ever worked for cases where repo remote != lfs endpoint

> 3. Is the "git lfs fetch" needed in Step 9?

 Since the `git checkout` fetches and checks out the files, you shouldn't need Step 9.  However, we need the fix for #4077 for full support.

**Comment by bk2204** [comment]
Yes, I don't think this approach will work.  With your approach, the only place we have the `.lfsconfig` file at step 9 is in remote tracking branches, and there's no way that could possibly function.  As far as I can tell, we've never read `.lfsconfig` from anywhere except the working tree, so this would never have worked.

Step 9 is not needed, and will likely fail.  A `git checkout` should work just fine here, since it should fetch and check out the LFS files as part of the operation, provided they sort after `.lfsconfig`.

With the fix I'm proposing for #4077, all files will work, regardless of file name, because if the file is missing from the tree, we'll check the index, and then `HEAD`.

**Comment by bk2204** [comment]
I'm going to close this since #4200 should have addressed a lot of this and I think we've answered the rest of the question here.

**Comment by Feuervogel81** [comment]
> **Describe the bug**
> The Azure Devops Build agent, uses fetch in the checkout task before the files are put on disk as shown in the repro steps.
> When `git lfs fetch origin commitId` is run it goes against the remote url, not the configured lfs url.
> We have logs that appear to show this working in a previous version and user feedback to that effect.
> 
> **To Reproduce**
> Create an lfs repository where the objects are hosted outside of the repo
> i.e.
> D:\lfs_test\z\z_clone\z>more .lfsconfig
> [remote "origin"]
> lfsurl = http://my-pc/DefaultCollection/my/_git/z2/info/lfs
> 
> [lfs]
> url = http://my-pc/DefaultCollection/my/_git/z2/info/lfs
> 
> D:\lfs_test\z\z_clone\z>git remote -v
> origin http://my-pc/DefaultCollection/my/_git/z (fetch)
> origin http://my-pc/DefaultCollection/my/_git/z (push)
> 
> Note the use of z versus z2 in the urls
> 
>     1. Create a new Directory
> 
>     2. git init .
> 
>     3. git remote add origin http://my-pc/DefaultCollection/my/_git/z
> 
>     4. git config gc.auto 0
> 
>     5. git config --get-all http.http://my-pc/DefaultCollection/my/_git/z.extraheader
> 
>     6. git config --get-all http.proxy
> 
>     7. git lfs install --local
> 
>     8. git fetch --force --tags --prune --progress --no-recurse-submodules origin
> 
>     9. git lfs fetch origin commitId
> 
>     10. git checkout --progress --force commitId
> 
> 
> Step 9 fails because it attempts to hit the endpoint http://my-pc/DefaultCollection/my/_git/z/info/lfs not http://my-pc/DefaultCollection/my/_git/z2/info/lfs
> 
> **Expected behavior**
> Step 9, should succeed and go against z2
> 
> **System environment**
> Windows
> 
> **Output of `git lfs env`**
> After checkout
> D:\lfs_test\z\z_clone\z>git lfs env
> git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git [08a08ae](https://github.com/git-lfs/git-lfs/commit/08a08ae065e78b1aa18b7b3cab373ce486af5bc5))
> git version 2.27.0.vfs.0.0
> 
> Endpoint=http://my-pc/DefaultCollection/my/_git/z2/info/lfs (auth=ntlm)
> 
> However the Endpoint is the other url at step 9
> 
> **Additional context**
> Questions:
> 
>     1. Should doing "git lfs fetch" like this work?
> 
>     2. Do you know if this ever worked?
> 
>     3. Is the "git lfs fetch" needed in Step 9?
