### ISSUE TITLE
Confusing error message on stale push to remote

### ISSUE THREAD

**Issue by quicknir** [git-lfs/git-lfs#4201]
Not a bug, but the error message that you get when the branch you're pushing to has commits you're missing, is very confusing. This is a very common scenario of course; you try to push master to origin/master, but someone else has pushed something to origin/master that you don't have locally. When this happens you get an error message like this:

```
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://<redacted>.git/info/lfs.locksverify true
ref master:: Error in git rev-list --stdin --objects --not --remotes=origin --: exit status 128 fatal: bad object 04d0e51e3a7a8eca6aa175a3e2c0975bbda849d2

error: failed to push some refs to 'git@<redacted>.git'
```

So far, nobody who's seen this error message on my team has realized that the problem is only that they need to git pull --rebase. For comparison, here's the error message that vanilla git gives you:

```
To <redacted>.git
 ! [rejected]            master -> master (non-fast-forward)
error: failed to push some refs to 'git@<redacted>.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

This scenario is so common, and the difference in error message so significant, I feel like as it stands this is basically a trap that everyone who uses git lfs is guaranteed to fall into once. Maybe providing a better error message is very difficult for technical reasons, but if it's not too bad it may be worth it.

I'm using git 2.17.1 and git-lfs 2.10.0.

Cheers!

**Comment by bk2204** [comment]
Hey,

I think this should be fixed in 2.11.0.  Can you try and verify that it is indeed fixed for you in this case?

**Comment by bk2204** [comment]
To be more specific, I believe we've fixed this issue so you no longer get that message and instead we push the objects you'd normally upload, and Git then provides the error message you'd expect.  Since this is also the message you used to get with force-pushes and we can't tell the difference in the `pre-push` hook, I think this is the best we can do in this case.

**Comment by quicknir** [comment]
Ah wow, that's great news :-). I can't instantly install 2.11.0 because of my work environment. I'll put in a request to have it made available and check it out. I'll close this issue; if I see it in 2.11.0 I can always reopen. Thanks very much!

**Comment by real-human-male** [comment]
Still happening in 2024
