### ISSUE TITLE
How to install lfs in macOS 10.11

### ISSUE THREAD

**Issue by YSUN-coder** [git-lfs/git-lfs#4204]
**Describe the issue**
 'brew install git-lfs' 
==> Installing dependencies for git-lfs: go
==> Installing git-lfs dependency: go
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.14.6/bin/go instal
==> go build
🍺  /usr/local/Cellar/go/1.14.6: 9,453 files, 424.8MB, built in 2 minutes 31 seconds
==> Installing git-lfs
==> gem install ronn
==> make vendor
==> make
Last 15 lines from ~/Library/Logs/Homebrew/git-lfs/03.make:
2020-08-02 09:30:05 -0600

make

go generate github.com/git-lfs/git-lfs/commands
git-lfs: skipping fmt, no goimports found at `goimports` ...
GOOS= GOARCH= go build -ldflags=" -X github.com/git-lfs/git-lfs/config.GitCommit= -s -w " -gcflags="all=-trimpath="$HOME" " -asmflags="all=-trimpath="$HOME"" -trimpath -o ./bin/git-lfs ./git-lfs.go
# github.com/git-lfs/git-lfs/tools
tools/util_darwin.go:21:10: fatal error: 'sys/clonefile.h' file not found
#include <sys/clonefile.h>
         ^
1 error generated.
make: *** [bin/git-lfs] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

**System environment**
macOS 10.11

**Output of `git lfs env`**
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log

**Comment by bk2204** [comment]
Hey,

I think you'll need to adjust the formula to use `CGO_ENABLED=0`.  I believe Homebrew strips all environment variables, so you really do need to do it inside the formula.

**Comment by bk2204** [comment]
I should also note that you don't want to apply this in all situations because it prevents `git lfs dedup` from being functional, so if you're going to make a PR against Homebrew, you'll want to limit it to versions before 10.12.  We're not planning to do so, since as Homebrew has mentioned, that version is no longer supported with security updates and as a result we don't consider whether Git LFS builds or runs there.
