### ISSUE TITLE
git lfs track hangs indefinitely

### ISSUE THREAD

**Issue by rphodges** [git-lfs/git-lfs#4205]
**Describe the bug**
git lfs track hangs indefinitely

`[sjc-ads-3131:build-mdata]$ git lfs track -v
12:58:46.828007 git.c:659               trace: exec: git-lfs track -v
12:58:46.828060 run-command.c:637       trace: run_command: git-lfs track -v
12:58:46.837187 trace git-lfs: exec: git 'version'
12:58:46.842829 trace git-lfs: exec: git 'config' '-l'
12:58:46.844695 trace git-lfs: exec: git 'config' '-l' '-f' '/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_41003/platforms/common/build-mdata/.lfsconfig'
12:58:46.846462 trace git-lfs: Install hook: pre-push, force=false, path=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_41003/platforms/common/build-mdata/.git/hooks/pre-push
12:58:46.847596 trace git-lfs: NewLsFiles: running in /nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_41003/platforms/common/build-mdata git ls-files -z --others --cached --exclude-standard
12:58:46.850401 trace git-lfs: findAttributeFiles: located .gitattributes
Listing tracked patterns
    *.bin (.gitattributes)
    *.so (.gitattributes)
    *.tar (.gitattributes)
    *.tgz (.gitattributes)
    *.tar.gz (.gitattributes)
    *.gz (.gitattributes)
    *.out (.gitattributes)
    *.mrlpp (.gitattributes)
    *.so (.gitattributes)
Listing excluded patterns
12:58:46.850569 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
12:58:46.850578 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
^C`

**To Reproduce**
Run git lfs track 
You may or may not have to add new files to trigger the hang

**Expected behavior**
I expect git lfs track to finish listing the track patterns

**System environment**
`[root@sjc-ads-3131 xrwfbot]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)`

**Output of `git lfs env`**
git lfs env seems to hang as well:
`[sjc-ads-3131:build-mdata]$ git lfs env
10:22:42.782101 git.c:659               trace: exec: git-lfs env
10:22:42.782166 run-command.c:637       trace: run_command: git-lfs env
10:22:42.791722 trace git-lfs: exec: git 'version'
git-lfs/2.10.0 (GitHub; linux amd64; go 1.12.7; git a526ba6b)
git version 2.19.1

10:22:42.794387 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:22:42.798344 trace git-lfs: exec: git 'config' '-l'
10:22:42.800219 trace git-lfs: exec: git 'config' '-l' '-f' '/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata/.lfsconfig'
Endpoint=https://gitlfs.cisco.com/artifactory/api/lfs/sb-137-UNRSTD-1 (auth=none)
LocalWorkingDir=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata
LocalGitDir=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata/.git
LocalGitStorageDir=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata/.git
LocalMediaDir=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata/.git/lfs/objects
LocalReferenceDirs=
TempDir=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/nobackup/jenkins/xr_commit/CSCvv21716-main-asr9k_superblocks_initial_commit_50694/platforms/common/build-mdata/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/cisco/packages/git/2.19//libexec/git-core
GIT_TRACE=1
GIT_TRANSFER_TRACE=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
10:22:42.804486 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
10:22:42.804503 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"`

**Additional context**
I've copied the repository to another machine and to another directory on the same machine.  Running git lfs commands in the copied repositories do not trigger the hang.  I think this hang only happens in repositories where files are added but that may because our tools only call git lfs track when new files are added.

Here is the strace log:
[strace.log](https://github.com/git-lfs/git-lfs/files/5030247/strace.log)

**Comment by rphodges** [comment]
I was able to run git lfs track and git lfs env as the owner of the workspace successfully.  I only experienced the hang when running the commands as a non-owner.   I've heard second-hand that running the commands as the owner may set up the workspace in such a way that non-owners can run the command successfully.

Unfortunately, the workspace that in which I could reproduce the hang has been removed so I couldn't verify the last statement.

**Comment by bk2204** [comment]
Hey,

It sounds like this is a permission issue, and the `EACCES` in the strace confirms this.  Are you setting `core.sharedRepository` in any way, including with `git init --shared`?  If not, there's no way that any Git repository can be used other than in a read-only mode, since files won't be written properly and users generally won't have permissions to write in the repository.

If the two users don't have the same default group, you may also need to create the initial working tree directory (before running `git init` in it) with the setgid bit on the directory, since that will make sure that the proper group is created on the subsequent directories.

So that should fix your problem right now.  I agree that we shouldn't hang in this case, and running the following for me does produce the hang:

```console
$ cd /tmp
$ git clone https://github.com/bk2204/dotfiles.git
$ sudo chown -R nobody:nogroup dotfiles
$ cd dotfiles
$ git lfs track
```

I think I know which mutex we're deadlocking on, so it's just a matter of figuring out why the contention is occurring.

**Comment by rphodges** [comment]
Thanks for the timely response.  No,  I don't think we are setting the sharedRepository flag, but we're mainly only interested in "other"  users running read-only commands like git diff and git lfs track.   I don't remember the details (I'll look them up) but I believe  read-only commands will sometimes create an LFS tmp directory with possibly restricted permissions (based on the user's umask) which would prevent other users from running similar read-only commands that also need to write to that tmp directory.  In response we modified our tools to completely open up the permissions of the LFS tmp object directory.  I can open up a separate issue ( if someone on my team hasn't already ) if you think the sharedRepository flag won't help in this situation.

**Comment by bk2204** [comment]
The `sharedRepository` flag should indeed help in this situation if you're using a reasonably modern version of Git LFS.  It is true that Git LFS will sometimes create directories in the repository, much like `git status` will try to refresh the index, so setting that option when creating the repo and making sure that all users share the same group for operations on that repo should fix it.
