### ISSUE TITLE
How do you get your CHANGELOG.md to appear in the GitHub Releases tab?

### ISSUE THREAD

**Issue by MarkCallow** [git-lfs/git-lfs#4210]
**Describe the issue**
I want to have release notes for a release in my project displayed when the release is displayed in the GitHub Releases tab as this project is doing.

**System environment**
n/a

**Output of `git lfs env`**
n/a

**Additional context**
I've looked at the script you use to generate the CHANGELOG.md. 2 pieces I haven't found, despite looking over the scripts, is how you add the introductory section to CHANGELOG.md and, the one I'm really interesting in, how you get the content of CHANGELOG.md to appear along with the release in the Releases tab.

I do hope that the answer is not that you copy and paste the content into the Description field of the GitHub Web GUI for Releases. I am hoping for something more automated that can be done when the assets are deployed.

**Comment by bk2204** [comment]
Hey,

We do generate the changelog with `script/changelog`, and then copy the output into the changelog.  We write the preface to the entry ourselves (mentioning folks who have contributed).  Once that's done, the automation will build assets and invoke `script/upload`, which uploads them and updates the draft release text with the appropriate contents using the API.  We then, after all the builds are done, sanity-check and sign the upload with `script/upload --finalize` and publish the release.

So to answer your question, we add the introductory section to the changelog by hand, and the release text is automated by `scripts/upload` using the API.

**Comment by MarkCallow** [comment]
Thank you for the information. Very helpful.

**Comment by yashsway** [comment]
@bk2204 how do you show the `CHANGELOG.md` link in the package details page for GitHub packages?

**Comment by chrisd8088** [comment]
> how do you show the `CHANGELOG.md` link in the package details page for GitHub packages?

We don't use GitHub Packages in this project.  You might want to consult GitHub's documentation and, if desired, contact their Support team for advice.
