### ISSUE TITLE
Controlle owner test only get

### ISSUE THREAD

**Issue by samuel-velazquez** [git-lfs/git-lfs#4212]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

It doesn't look like you filled in any of the information and the description doesn't describe the problem.  As a result, I'm going to close this issue.  Feel free to edit the original description and issue to better describe your problem and reproduction steps and mention that you've done so, and we'll reopen the issue.
