### ISSUE TITLE
git lfs track does not honor GIT_WORK_TREE and GIT_DIR

### ISSUE THREAD

**Issue by Mr-Tao** [git-lfs/git-lfs#4213]
**Describe the bug**
`git lfs track` does not honor `GIT_WORK_TREE` nor `GIT_DIR` environment variables as well as `--git-dir` and `--work-tree` options.

**To Reproduce**
```
mkdir foo bar
export GIT_WORK_TREE=foo GIT_DIR=bar
git init
git lfs track '*.xz'
```
`.gitattributes` file is produced in current directory and error message is printed:
> Tracking "*.xz"
> Error changing lockable file permissions: Error in git ls-files -z --others --cached --exclude-standard: exit status 128 fatal: not a git repository: 'bar'
>
> Errors logged to <…>/testtwo/bar/lfs/logs/20200814T181926.04705318.log
> Use `git lfs logs last` to view the log.

**Expected behavior**
`.gitattributes` file in `foo` directory.

**System environment**
Linux, git version 2.28.0, git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.4)

**Output of `git lfs env`**
```
git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.4)
git version 2.28.0

LocalWorkingDir=/home/hideo/testtwo/foo
LocalGitDir=/home/hideo/testtwo/bar
LocalGitStorageDir=/home/hideo/testtwo/bar
LocalMediaDir=/home/hideo/testtwo/bar/lfs/objects
LocalReferenceDirs=
TempDir=/home/hideo/testtwo/bar/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/hideo/testtwo/bar/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_DIR=bar
GIT_EXEC_PATH=/usr/lib/git-core
GIT_NOTES_REF=refs/notes/build
GIT_WORK_TREE=foo
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for reporting this.  It looks like there are a couple of bugs here:

* We don't handle relative paths properly, although we handle absolute paths.
* We don't change directories to the working tree if we're not inside it.

I'll see if we can get a patch in sometime soon.

**Comment by prokher** [comment]
While the fix seems to take into account `GIT_WORK_TREE`, it looks like it still does not honor `GIT_DIR`.

**Comment by bk2204** [comment]
Hmmm, using `GIT_DIR` appears to work just fine for me, and it was included in the patch.  Can you provide the output of `git lfs env` and a shell script that reproduces the problem?
