### ISSUE TITLE
Modify LFS tracked file on remote.

### ISSUE THREAD

**Issue by yaxili96** [git-lfs/git-lfs#4220]
**Describe the issue**
I updated a git-lfs tracked file directly on remote and then pull the changes into local computers. When I ran `git status`, it shows an uncommitted change to the file like the following:

> \- [the original content of the file]
>+oid sha256:abcdergxxxx
> +size 12345

I guess the cause of this problem is that when we do remote change to lfs tracked file, the file itself was somehow treated as a normal file tracked by git instead of git-lfs. Am I correct? 

**System environment**
Windows + Azure DevOps

**Comment by bk2204** [comment]
Hey,

That does sound like it's probably the case.  The remote side probably doesn't have Git LFS installed, or if it is, `git lfs install` hasn't been run.  I'd make sure that whatever system you're doing work on has Git LFS installed and properly configured.
