### ISSUE TITLE
Does git lfs work over http ?

### ISSUE THREAD

**Issue by sandeep-sarkar** [git-lfs/git-lfs#4222]
**Describe the issue**
I have few queries over git lfs. 
- Does git lfs work over http ?
- If yes then is that communication encrypted ?
- If the large file is transferred over http is it in clear text ?

**Comment by chrisd8088** [comment]
To answer your questions, briefly, in order:

- Yes, Git LFS works over HTTP.  More specifically, the Git LFS [API](https://github.com/git-lfs/git-lfs/tree/4f70d99979082b2a0a5f82b233c911a0ec1a6e49/docs/api) uses HTTP/S.
- Yes, Git LFS will use HTTPS (the encrypted version of HTTP) if it is configured with a remote that uses HTTPS.
- As with any data transferred using HTTP or HTTPS, it will be in clear text if using HTTP, and encrypted if using HTTPS.

So it depends on which LFS server you're using.  GitHub's LFS support uses HTTPS exclusively, as do most other primary providers.  But there are other ways of using LFS, including strictly locally, where you might not need HTTPS.

You can also use Git LFS with SSH remotes, but the actual large file transfer occurs over HTTP/S; for more details on that, see https://github.com/git-lfs/git-lfs/issues/1044#issuecomment-656354589 and the discussion there.
