### ISSUE TITLE
Expected OID errors for GitLFS v2.9.0 and above

### ISSUE THREAD

**Issue by rogerhu** [git-lfs/git-lfs#4229]
**Describe the bug**
We have 30MB files in GitLFS that are somehow triggering expected OID errors intermittently.  The failures are happening a lot more regularly on the latest GitLFS version (2.12.0-1.el7 CentOS RPM).  We think somehow these lines are being triggered before the entire file is being downloaded.

```
[2020-09-03 09:05:26] expected OID eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7, got 2aa791189fa2ae8ebf2256830a1dbc417a327c730bbd4c6a695cc01db921c1d1 after 9870854 bytes written
[2020-09-03 09:05:26] expected OID a6a0e1ea9b8df51765b0b821ef633c162689bdeb5f70bf26952ce3793bdfab07, got bd9b1eea49aa624ef788c0a591329c9a387bff8bdbc6789e6652429e96f84af0 after 18308614 bytes written
[2020-09-03 09:05:26] expected OID d00a9bab96f305c708bc556503c31975a70f145b66417e9cbcbcc5ae9426c308, got 75d8e3daaa7a28b21edd592beef35d58c7809c81607b4212b938e5fc74ce555c after 15621638 bytes written
```

**To Reproduce**
1. Use GitLFS 2.12.0-1.el7

(still trying to get repro case - this happens very consistently on 2.12.0.  We are reverting back to 2.7.2 until we can identify the root cause).

**Expected behavior**
No expected OID errors happening.  

When using GIT_ENV=1 we can see the total size of the file.  Somehow the error shows a smaller file being downloaded.

```
"oid":"eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7","size":25170450,"actions":{"download":{"href":"https://git.sqcorp.co/rest/git-lfs/storage/ANDROID/register/eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7"
```

**System environment**
CI - CentOS 7

**Output of `git lfs env`**
```
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""

```

**Additional context**

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  We're definitely interested in fixing this, but we'd need some sort of reproduction steps.  Since 2.7.2 and 2.12.0 have a decent amount of changes (588 commits) between them, it's a little hard for us to figure out what might be going on here.

Can you try also running with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and attaching the logs here (after removing any Authorization headers)?

**Comment by rogerhu** [comment]
I tried several times but could not repro.  However, I did find that the partial checksum checks are resolving to the right value.  For instance, these errors:

```
expected OID eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7, got eed32f912de831cf6d55aed1ea26e05935af1b130ed6be71bb6ea791935000c4 after 15695367 bytes written
```

If I fetch the file and then truncate it to the bytes written, it works:
```
wget https://git.mycompany.com/rest/git-lfs/storage/ANDROID/register/eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7
>>> x = open("eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7", "rb")
>>> y = x[:15695367]
>>> open("/tmp/truncate", "w").write(y)
```

Which matches:
```
openssl sha256 /tmp/truncate 
SHA256(/tmp/truncate)= eed32f912de831cf6d55aed1ea26e05935af1b130ed6be71bb6ea791935000c4
```

I've checked in these cases and confirmed the partial checksum issue.  Reading through the new download code, I thought it was supposed to download the file in its entirety or not complete.  Is there problematic error handling (e.g. connection drops) that are not being detected in the new download approach?

**Comment by bk2204** [comment]
@rogerhu: Can you confirm that your LFS server supports the `Range` header properly?  What LFS server implementation are you using?

@slonopotamus: I think this is related to the retry refactor that you did.  Any ideas on what might be going wrong here?

**Comment by slonopotamus** [comment]
This is OK that `expected OID A, got B after N bytes written` says less bytes than full file because it only counts bytes that were downloaded _after_ download resuming.

I"m not understanding yet why resumed downloads end up with only initial part of file being hashed. I guess we need verbose log in order to trace what's going on there.

**Comment by rogerhu** [comment]
We are on Bitbucket's on-premise server (5.16.10).

We see in our server logs:

```
020-09-02 22:30:48,000 INFO  [http-nio-7990-exec-3683] @PO6JG0x1350x71144757x6 192.168.19.5,127.0.0.1 "GET /rest/git-lfs/storage/ANDROID/register/eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7 HTTP/1.0" c.a.s.i.w.filters.StreamGuardFilter The remote client has aborted the connection
```

**Comment by rogerhu** [comment]
I also confirmed inside the GitLFS JAR file that this version supports `Range`

```java
  @Nonnull
  public static Optional<HttpRange> parseRange(@Nullable String range) {
    if (range != null) {
      Matcher matcher = RANGE_PATTERN.matcher(range);
      if (matcher.matches() && matcher.groupCount() == 2) {
        try {
          long start = Long.parseLong(matcher.group("start"));
          long end = Long.parseLong(matcher.group("end"));
          return Optional.of(new HttpRange(start, end));
        } catch (NumberFormatException e) {
          return Optional.empty();
        } 
      }
    } 
    return Optional.empty();
  }

```

And the code:

```java
    Optional<HttpRange> parsedRange = HttpRange.parseRange(rangeHeader);
    if (rangeHeader != null && !parsedRange.isPresent()) {
      log.debug("HTTP range format invalid or unsupported");
    }
    
    ObjectStreamingOutput stream = this.storeService.readObject((new ReadObjectRequest.Builder(repository, oid))
        
        .range((HttpRange)parsedRange.orElse(null))
        .build());
```

**Comment by rogerhu** [comment]
Am I reading this commit right?

https://github.com/git-lfs/git-lfs/commit/662a6248198594a59c5a652b1ab543d8948c302a#diff-efe2711da98b4f5e10a7364980839720R40-R42

```
return retry.Do(
		func() error {
			return os.Rename(oldpath, newpath)
		},
``

**Comment by rogerhu** [comment]
@slonopotamus the error message show the hash computed matches after the first N bytes calculated, which seems to suggest no Range queries are used?   On a normal trace, the curl call looks like:

```
2020-09-11 19:44:27] < HTTP/2.0 200 OK
[2020-09-11 19:44:27] < Connection: close
[2020-09-11 19:44:27] < Cache-Control: private, no-cache
[2020-09-11 19:44:27] < Cache-Control: no-cache, no-transform
[2020-09-11 19:44:27] < Content-Type: application/octet-stream
[2020-09-11 19:44:27] < Date: Fri, 11 Sep 2020 19:44:27 GMT
[2020-09-11 19:44:27] < Pragma: no-cache
[2020-09-11 19:44:27] < Server: nginx
[2020-09-11 19:44:27] < Strict-Transport-Security: max-age=15768000
[2020-09-11 19:44:27] < Vary: X-AUSERNAME
[2020-09-11 19:44:27] < Vary: X-AUSERID
[2020-09-11 19:44:27] < Vary: Cookie
[2020-09-11 19:44:27] < X-Arequestid: @PO6JG0x1184x96922938x6
[2020-09-11 19:44:27] < X-Asen: SEN-9389975
[2020-09-11 19:44:27] < X-Asessionid: mfc5ru
[2020-09-11 19:44:27] < X-Auserid: 7963
[2020-09-11 19:44:27] < X-Content-Type-Options: nosniff
[2020-09-11 19:44:27] < 
```

We also see on the server side client side disconnects related to the times these issues occurred.  Has something changed that would cause an unexpected situation where no error is detected as a result of these client side glitches and the partial file is downloaded and the partial checksum is computed?

**Comment by rogerhu** [comment]
Also confirmed range queries work on partially downloaded files.  I do think the problem is showing up though on clean pulls.

```
> GET /rest/git-lfs/storage/ANDROID/register/a6a0e1ea9b8df51765b0b821ef633c162689bdeb5f70bf26952ce3793bdfab07 HTTP/1.1
> Host: git.sqcorp.co
> Authorization: JWT <JWT token>
> Range: bytes=8510989-31760321
> User-Agent: git-lfs/2.12.0 (GitHub; darwin amd64; go 1.15)
>
06:45:57.156579 trace git-lfs: HTTP: 206

< HTTP/2.0 206 Partial Content
< Connection: close
< Cache-Control: private, no-cache
< Cache-Control: no-cache, no-transform
< Content-Range: bytes 8510989-31760321/*
< Content-Type: application/octet-stream
< Date: Wed, 23 Sep 2020 13:45:57 GMT
< Pragma: no-cache
< Server: nginx
< Strict-Transport-Security: max-age=15768000
< Vary: X-AUSERNAME
< Vary: X-AUSERID
< Vary: Cookie
```

**Comment by rogerhu** [comment]
I'm also looking at this diff inside `basic_download.go` -- does this suggest when there is a download and an error occurs, we don't return the error?

```
+       err = a.download(t, cb, authOkFunc, f, fromByte, hash)
+
        if err != nil {
                f.Close()
-               return nil, 0, nil, err
+               // Rename file so next download can resume from where we stopped.
+               // No error checking here, if rename fails then file will be deleted and there just will be no download resuming
+               tools.RobustRename(f.Name(), a.downloadFilename(t))
        }
-       tracerx.Printf("xfer: Attempting to resume download of %q from byte %d", t.Oid, n)
-       return f, n, hash, nil
 
+       return err

```

**Comment by slonopotamus** [comment]
Do I understand you correctly that you used git-lfs 2.7.2 running multiple concurrent git-lfs processes using the same lfs storage directory? I insist that such use case didn't work properly _at all_ for reasons described in #2825, even on Linux.

**Comment by slonopotamus** [comment]
WRT single-process download resuming, git-lfs has tests for that and I assume they work both before and after my changes. The only thing that neither git-lfs testsuite nor my production setup tests is _concurrent_ download by multiple git-lfs processes to the same lfs storage _with download resuming_. But, as I said, I believe it diidn't properly work in 2.7 era. I don't see the flaw in current download logic by studying source code, so https://github.com/git-lfs/git-lfs/issues/4229#issuecomment-686581152 is right, we need verbose log output to diagnose the problem. Possivly you can enable them for some period of time and wait until one of downloads fails?

**Comment by rogerhu** [comment]
Just saw the same issue with 2.11.0.  Tried to do a GIT_TRACE but the second time it didn't appear.

Still see things like this - it seems if the client aborts the connection, something happens...

```
2020-10-11 06:31:20,250 INFO  [http-nio-7990-exec-2832] @1VI1BCWx390x21589987x8 192.168.19.5,127.0.0.1 "GET /rest/git-lfs/storage/ANDROID/register/eb86c100f9412d5265106b0c34b4c0fa60ee9a14653b8b0a914bb007c27967e7 HTTP/1.0" c.a.s.i.w.filters.StreamGuardFilter The remote client has aborted the connection
2020-10-11 06:31:24,326 INFO  [http-nio-7990-exec-2594] @1VI1BCWx390x21589982x3 192.168.19.5,127.0.0.1 "GET /rest/git-lfs/storage/ANDROID/register/d00a9bab96f305c708bc556503c31975a70f145b66417e9cbcbcc5ae9426c308 HTTP/1.0" c.a.s.i.w.filters.StreamGuardFilter The remote client has aborted the connection

```

**Comment by rogerhu** [comment]
Finally got it with the full trace (with GitLFS 2.11.0) -- again, this is simply running a full git lfs download (single process):

```
07:30:55.445917 trace git-lfs: tq: starting transfer adapter "basic"
07:30:55.445925 trace git-lfs: xfer: adapter "basic" Begin() with 8 workers
07:30:55.445934 trace git-lfs: xfer: adapter "basic" started
07:30:55.445937 trace git-lfs: xfer: adapter "basic" worker 2 starting
07:30:55.445948 trace git-lfs: xfer: adapter "basic" worker 3 starting
07:30:55.445955 trace git-lfs: xfer: adapter "basic" worker 2 waiting for Auth
07:30:55.445957 trace git-lfs: xfer: adapter "basic" worker 3 waiting for Auth
07:30:55.445946 trace git-lfs: xfer: adapter "basic" worker 0 starting
07:30:55.445967 trace git-lfs: xfer: adapter "basic" worker 0 processing job for "a6a0e1ea9b8df51765b0b821ef633c162689bdeb5f70bf26952ce3793bdfab07"
07:30:55.445968 trace git-lfs: xfer: adapter "basic" worker 7 starting
07:30:55.445955 trace git-lfs: xfer: adapter "basic" worker 1 starting
07:30:55.445989 trace git-lfs: xfer: adapter "basic" worker 1 waiting for Auth
07:30:55.445979 trace git-lfs: xfer: adapter "basic" worker 7 waiting for Auth
07:30:55.445959 trace git-lfs: xfer: adapter "basic" worker 4 starting
07:30:55.446000 trace git-lfs: xfer: adapter "basic" worker 4 waiting for Auth
07:30:55.445954 trace git-lfs: xfer: adapter "basic" worker 5 starting
07:30:55.446005 trace git-lfs: xfer: adapter "basic" worker 5 waiting for Auth
07:30:55.445958 trace git-lfs: xfer: adapter "basic" worker 6 starting
07:30:55.446046 trace git-lfs: xfer: adapter "basic" worker 6 waiting for Auth
7:30:55.445967 trace git-lfs: xfer: adapter "basic" worker 0 processing job for "a6a0e1ea9b8df51765b0b821ef633c162689bdeb5f70bf26952ce3793bdfab07"

> GET /rest/git-lfs/storage/ANDROID/register/a6a0e1ea9b8df51765b0b821ef633c162689bdeb5f70bf26952ce3793bdfab07 HTTP/1.1
> Host: git.sqcorp.co
> Authorization: JWT **REMOVED**
> User-Agent: git-lfs/2.11.0 (GitHub; linux amd64; go 1.14.1; git 48b28d97)
>
07:30:55.471810 trace git-lfs: HTTP: 200
< HTTP/2.0 200 OK
< Connection: close
< Cache-Control: no-cache, no-transform
< Content-Type: application/octet-stream
< Date: Sun, 11 Oct 2020 07:30:55 GMT
< Server: nginx
< Strict-Transport-Security: max-age=15768000
< Vary: X-AUSERNAME
< Vary: X-AUSERID
< Vary: Cookie
< X-Arequestid: @1VI1BCWx450x21651162x0
< X-Asen: SEN-9389975
< X-Content-Type-Options: nosniff
<
```

There are no signs of disconnects.  However, on the server side, we see:

```
2020-10-11 07:31:38,648 INFO  [http-nio-7990-exec-2808] @1VI1BCWx450x21651162x0 192.168.19.5,127.0.0.1 "GET /rest/git-lfs/storage/ANDROID/register/a6a0e1ea9b8df51765b0b821ef633c162689bdeb5f70bf26952ce3793bdfab07 HTTP/1.0" c.a.s.i.w.filters.StreamGuardFilter The remote client has aborted the connection
```

**Comment by rogerhu** [comment]
Able to see on User-Agent: git-lfs/2.9.1 (GitHub; linux amd64; go 1.12.7; git 7b479cc8) as well.

**Comment by rogerhu** [comment]
Using a compiled version of v2.9.0, I see the issue.  It's fairly reproducible on my end -- 1-2 or tries I can see the issue esp for large GitLFS files (> 30 MB): 

Resetting my LFS setup:

```bash
git lfs uninstall
git lfs ls-files -n | xargs rm
rm -rf .git/lfs
git restore .
git lfs install
```

Then I run:

```
set -euo pipefail

export GIT_TRACE=1
export GIT_TRANSFER_TRACE=1 
export GIT_CURL_VERBOSE=1

~/Development/git-lfs/bin/git-lfs  pull >& /tmp/git-lfs10
```
 
Reverting 1edb976a92e07cb8fcc021693f97accb8fc8b624,  01bc6a687ead07b50aa0c5b789bf67a221e17052, 28edeb7d4330c6e3d3da4149cf961006ade16fed, and 9e4a7f4c39057dc918f1ff9eb18e9167423f7025 didn't solve it (I still see connection aborts).    I'm checking again to see if v2.8.0  has any issues.

**Comment by rogerhu** [comment]
Just realized the major difference is HTTP/1.1 200 is used in GitLFS v2.8.0 but GitLFS v2.9.0 uses HTTP/2.0

https://github.com/git-lfs/git-lfs/commit/a0a2815d40c1027ae3f5d26646a3a1bf9cd562fb

**Comment by rogerhu** [comment]
Looks like the problem may be between Nginx and our Git server.  Golang seems to handle HTTP/2 transparently so the GitLFS upgrade merely exposed this issue.  Closing for now.

**Comment by rogerhu** [comment]
FYI - pinpointed the problem to the 30 second git lfs activitytimeout.  Seems like once the HTTP/2 changes got made, it causes this timeout to be triggered - increasing to 90 seconds seems to resolve the issue (and assuming nginx has the same setting).  I don't see the problem pre HTTP/2 changes.

**Comment by EpochGamesGitHub** [comment]
> FYI - pinpointed the problem to the 30 second git lfs activitytimeout. Seems like once the HTTP/2 changes got made, it causes this timeout to be triggered - increasing to 90 seconds seems to resolve the issue (and assuming nginx has the same matching setting). I don't see the problem pre HTTP/2 changes.

@rogerhu Could you explain how I'd go about doing this myself? My development team is receiving a `smudge error` when they try to pull our Project, and I was told _your_ solution might resolve the issue.

1. How do I set `git lfs activitytimeout` to `90`? Is this something I setup on my GitLab VM or on my Local Machine?
2. I have a GitLab VM that is reverse proxying through an Nginx VM on our Server. What else would I need to do?
