### ISSUE TITLE
Flash content does not play properly when stored using LFS.

### ISSUE THREAD

**Issue by radzo73** [git-lfs/git-lfs#4235]
**Describe the bug**
Downloading a .swf hosted by Git LFS works normally, but trying to display it on a webpage does not work as intended.

**To Reproduce**
1. Upload a .swf to your repo using Git LFS
2. Try to display it. (e.g displaying it in a .html via GitHub Pages)
3. Stare at the white screen. 

**Expected behavior**
I expect the .swf to run like any other (e.g https://radzo73.github.io/fparchive/FPAW1.html), but instead, it's a black screen. (e.g https://radzo73.github.io/fparchive/FPAW3.html)

**System environment**
Windows 10 18363 Build 18363

**Output of `git lfs env`**
```Endpoint=https://github.com/radzo73/fparchive.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\radzo\Documents\GitHub\fparchive
LocalGitDir=C:\Users\radzo\Documents\GitHub\fparchive\.git
LocalGitStorageDir=C:\Users\radzo\Documents\GitHub\fparchive\.git
LocalMediaDir=C:\Users\radzo\Documents\GitHub\fparchive\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\radzo\Documents\GitHub\fparchive\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\radzo\Documents\GitHub\fparchive\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
The only other place I could find this question is https://community.netlify.com/t/flash-file-swf-git-lfs-file-not-properly-served/10331, but they use Netlify, and I'm using GitHub Pages.

**Comment by bk2204** [comment]
Hey,

GitHub Pages doesn't support Git LFS.  In order for the data to be downloaded as part of the repository, the Git LFS client needs to be installed, and it isn't installed in the build environment for GitHub Pages.  This isn't a bug in Git LFS, but just a design decision on the part of GitHub.  If you'd like to give them feedback about that, please let their Support folks know.

**Comment by radzo73** [comment]
well then
