### ISSUE TITLE
git lfs not automatically added to previous un-pushed commits

### ISSUE THREAD

**Issue by avani17101** [git-lfs/git-lfs#4236]
I added the git lfs later when my commit got rejected, but I want my previous commits to be pushed too. Is there any way or if not I really request to add git lfs to previous large commits too automatically. 
Currently, it only works after we add lfs and then add large files, commit, and push. 
I really need to push my large file's commits before lfs was added.

**Comment by bk2204** [comment]
Hey,

You can do this by rewriting history using `git lfs migrate import`.  For example, if you wanted to migrate all of the `.mp3` files in your repository, you could do `git lfs migrate import --everything --include="*.mp3"` (note the quotation marks).  You can see more in the documentation about how to invoke it and add additional options to meet your needs.
