### ISSUE TITLE
Jenkins pipeline - smudge filter lfs failed

### ISSUE THREAD

**Issue by GouravIN** [git-lfs/git-lfs#4248]
Getting the following error during my git lfs after checkout step.

Started by user Gourav Pattnaik
Checking out git git@github.com:XXXXX into /var/jenkins_home/jobs/in-ci-pipeline-dev/workspace@script to read Jenkinsfile
using credential XXXXXX
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:XXXXXX # timeout=10
Fetching upstream changes from git@github.com:XXXXXX
 > git --version # timeout=10
using GIT_SSH to set credentials XXXXXXXXX SSH user
 > git fetch --tags --progress -- git@github.com:XXXXXX +refs/heads/*:refs/remotes/origin/*
 > git rev-parse XXXXX^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/XXXXXXX^{commit} # timeout=10
Checking out Revision 438b9cbb48f1c2cceeb54300753bb608dccc24c6 (refs/remotes/origin/XXXXXXXX)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 438b9cbb48f1c2cceeb54300753bb608dccc24c6
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f 438b9cbb48f1c2cceeb54300753bb608dccc24c6" returned status code 128:
stdout: 
stderr: Downloading app-new/config/browscap.ini (88 MB)
Error downloading object: app-new/config/browscap.ini (ba81f69): Smudge error: Error downloading app-new/config/browscap.ini (ba81f6956fa350f2837ec9d3b61842719e8b984dbec3fd54140b66df0cf7e13d): batch request: Repository not found.: exit status 1

Errors logged to /var/jenkins_home/jobs/in-ci-pipeline-dev/workspace@script/.git/lfs/logs/20200914T144748.824480105.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: app-new/config/browscap.ini: smudge filter lfs failed

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2174)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1000(CliGitAPIImpl.java:78)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2473)
Caused: hudson.plugins.git.GitException: Could not checkout 438b9cbb48f1c2cceeb54300753bb608dccc24c6
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2497)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1242)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:69)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  What kind of SSH key are you using to perform this clone (personal or deploy key)?  Does it work if you don't enable sparse checkout?  What OS is this on, and what version of Git LFS are you using (`git lfs env`)?  What is `GIT_SSH` set to?  Does it use OpenSSH under the hood or something different?

**Comment by GouravIN** [comment]
@bk2204 
root@jenkins:/# git lfs env
git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)
git version 2.11.0

OS: Debian
Does it work if you don't enable sparse checkout? No
What kind of SSH key are you using to perform this clone (personal or deploy key)? Personal, we created a set of private and public key and are using it.
What is GIT_SSH set to? Does it use OpenSSH under the hood or something different? Using the SSH method of Github.

**Comment by bk2204** [comment]
Can you show us the program you're using for `GIT_SSH`?  I'm wondering if we're failing to handle some invocation with that properly and that might be the cause of the issues you're seeing.

**Comment by GouravIN** [comment]
@bk2204 I'm using the Git plugin of Jenkins. Below is my code.

pipeline {
    agent none
    triggers { cron('H H(2-4) * * *') }
    parameters {
        string(defaultValue: 'NEXT', description: '', name: 'BRANCH_NAME', trim: false)
        //Here NEXT is not a branch name or a tag, but it is a string used to get the value of next deployable branch from the microstage api.
        booleanParam(name: 'HOTFIX', defaultValue: false, description: 'Is this a hotfix')
    }
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '15', numToKeepStr: '100')
    }
    stages {
        stage('Deploy Branch Init') {
            agent { label 'master' }
            options { timeout(30) }
            steps {
                echo "Running on node: ${env.NODE_NAME}"
                script {
                    currentBuild.displayName = "#" + currentBuild.number + "-" + "${params.BRANCH_NAME}"
                    buildParameter()
                }
            }
            post {
                success {
                    updateGithubCommitStatus("SUCCESS")
                }
                failure {
                    updateGithubCommitStatus("FAILURE")
                }
                cleanup {
                    cleanWs(patterns: [[pattern: '.git/objects/pack/tmp_pack*', type: 'INCLUDE']])
                }
            }
        }
    }
}


def checkoutStep(branchname, repo, targetdir = "") {
    checkout changelog: false, poll: false,
            scm: [$class                           : 'GitSCM',
                  branches                         : [[name: "${branchname}"]],
                  browser                          : [$class: 'GithubWeb', repoUrl: "http://github.com/InterNations/${repo}"],
                  doGenerateSubmoduleConfigurations: false,
                  extensions                       : [[$class: 'CleanCheckout'],
                                                      [$class: 'CleanBeforeCheckout'],
                                                      [$class: 'RelativeTargetDirectory', relativeTargetDir: "${targetdir}"],
                                                      [$class: 'CloneOption', depth: 0, noTags: true, reference: '', shallow: false],
                                                      [$class: 'GitLFSPull']],
                  submoduleCfg                     : [],
                  userRemoteConfigs                : [[credentialsId: 'github-internations-jenkins', url: "git@github.com:InterNations/${repo}.git"]]]
}

def buildParameter() {
    if ("${params.BRANCH_NAME}" == 'NEXT') {
        final url = "https://staff.internations.org/microstages/api/host/stage.internations.org"
        final String response = sh(script: "curl -s ${url}", returnStdout: true).trim()
        checkoutStep(response, 'in')
    } else {
        checkoutStep("${params.BRANCH_NAME}", 'in')
    }
    sshagent(['github-internations-jenkins']) {
        withAnt() {
            sh "ant build-parameters"
        }
    }
    def props = readProperties file: 'ci.properties'
    env.GIT_APP_REVISION = props['GIT_APP_REVISION']
    env.GIT_APP_BRANCH = props['GIT_APP_BRANCH']
    env.GIT_SOLR_REVISION = props['GIT_SOLR_REVISION']
    env.GIT_SOLR_BRANCH = props['GIT_SOLR_BRANCH']
    env.GIT_OMS_REVISION = props['GIT_OMS_REVISION']
    env.GIT_OMS_BRANCH = props['GIT_OMS_BRANCH']
    env.GIT_CMS_REVISION = props['GIT_CMS_REVISION']
    env.GIT_CMS_BRANCH = props['GIT_CMS_BRANCH']
    env.GIT_FRONTEND_REVISION = props['GIT_FRONTEND_REVISION']
    env.GIT_FRONTEND_BRANCH = props['GIT_FRONTEND_BRANCH']
    env.NIGHTLY_BUILD = props['NIGHTLY_BUILD']
    env.MICROSTAGE = props['MICROSTAGE']
    env.MICROSTAGE_HOST = props['MICROSTAGE_HOST']
    env.HUMAN_STAGE_NAME = props['HUMAN_STAGE_NAME']
    env.DEPLOY = props['DEPLOY']
    env.NEXT = props['NEXT']
    env.HOTFIX = params.HOTFIX
}

**Comment by bk2204** [comment]
Hey,

I'm not sure what's going on here, but it seems like you're seeing some sort of authentication problem with GitHub using this key.  It's not clear to me what the problem is, though.  If you can create a set of reproduction steps as a shell script, it should be possible for us to look at this to see if it's a Git LFS issue, but I don't know anything about Jenkins and can't help debug the problem there.

**Comment by GouravIN** [comment]
@bk2204 I will recreate the steps and get back to you.

**Comment by GouravIN** [comment]
@bk2204 So far this is the thing I have figured out.

The authentication to the Github Repo works, but it doesn't work with GITLFS both via SSH and HTTPS method.

Checking out git https://github.com/XXXXXXX into /var/jenkins_home/jobs/in-ci-pipeline-dev/workspace@script to read Jenkinsfile
using credential XXXXXXXXXX
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/XXXXXXX# timeout=10
Fetching upstream changes from https://github.com/XXXXXXX
 > git --version # timeout=10
using GIT_ASKPASS to set credentials internations-jenkins credentials for the web
 > git fetch --tags --progress -- https://github.com/XXXXXXXX +refs/heads/*:refs/remotes/origin/*
 > git rev-parse dev/in-ci-jenkinsfile^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/dev/in-ci-jenkinsfile^{commit} # timeout=10
Checking out Revision ffc2f625856285fe418ee344c46291fbb6c03b35 (refs/remotes/origin/dev/in-ci-jenkinsfile)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ffc2f625856285fe418ee344c46291fbb6c03b35
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f ffc2f625856285fe418ee344c46291fbb6c03b35" returned status code 128:
stdout: 
stderr: Downloading app-new/config/browscap.ini (88 MB)
Error downloading object: app-new/config/browscap.ini (ba81f69): Smudge error: Error downloading app-new/config/browscap.ini (ba81f6956fa350f2837ec9d3b61842719e8b984dbec3fd54140b66df0cf7e13d): batch response: Bad credentials

From the stderr output: You can see here that it has already got inside the repo, and when it is trying to pull the file  which is of 88 MB using gitlfs, it throws error.

Via: HTTPS it throws Bad Credential error
Via: SSH it throws repo not found error.

And the most strange thing is that, this only happens when I'm using the Jenkinsfile in a pipeline, but when I use it a scripted method, it works completely fine.

**Comment by bk2204** [comment]
Hey,

I don't know why this is happening, but I suppose it's possible that you're setting `GIT_ASKPASS` or `GIT_SSH` only for the fetch and not for the checkout.  If so, that won't work, because Git LFS won't be invoked as part of the fetch, but as part of the checkout.  Beyond that, I don't have any ideas about why this isn't working.  If you can't reproduce this with a shell script, I'd reach out to the Jenkins folks and ask them what's going on.

**Comment by GouravIN** [comment]
@bk2204 You can close this issue. I have figured out that it was an issue from Jenkins side. Which I have fixed it.

**Comment by jeffreyssmith2nd** [comment]
Sorry to revive a closed thread that's not exactly related to this repo, but @GouravIN can you share what you changed in Jenkins to make things work?

**Comment by GouravIN** [comment]
@jeffreyssmith2nd The GitLFS option was not enabled on the job config. So when it was trying to download the files it was failing.

**Comment by jeffreyssmith2nd** [comment]
Thanks @GouravIN, we ended up solving our issue by following the recommendation [here](https://hodari.be/posts/2019_10_04_checkout_issues_git_lfs_jenkins/) and setting `GIT_LFS_SKIP_SMUDGE=1`

**Comment by Ezward** [comment]
I know I am commenting is a closed issue, but it is worth noting for others that this workaround means that the initial checkout will not checkout your LFS files.  So that is not exactly a fix.

**Comment by idemax** [comment]
> Thanks @GouravIN, we ended up solving our issue by following the recommendation [here](https://hodari.be/posts/2019_10_04_checkout_issues_git_lfs_jenkins/) and setting `GIT_LFS_SKIP_SMUDGE=1`

This didn't work for me. 

My error was:

```
hudson.plugins.git.GitException: Command "git checkout -f 63a19cdee48f1a0a22ffdf2ce240e1e0f8fc84df" returned status code 128:
stdout: 
stderr: Downloading SomeVideo.mp4 (112 MB)
Error downloading object: SomeVideo.mp4 (59d2b45): Smudge error: Error downloading SomeVideo.mp4 (59d2b45323ff6c46863ea59135889467842391ed47450fc897b240776200629c): batch request: git@github.com: Permission denied (publickey).: exit status 255
```

BTW: git --version # 'git version 2.43.0.windows.1'

It was a very weird error. This begun when the command `git add --renormalized .` was executed and some new extensions were added to `.gitattributes`.

I fixed trying disabling extensions one by one until it works.

Still don't know the route cause and how to prevent it.

Is someone aware about it?

**Comment by AsocPro** [comment]
@idemax I saw this same error you are seeing and fixed it by adding the  gitLFSPullTrait() to the traits in the gitLabSCMSource section of the failing job config.

**Comment by FaitAccompli** [comment]
@idemax, what worked for me was there was one file I didn't do a `git add --renormalize` on and it was failing on checkout. This happens when you track an existing large file, and you simply did a `git add` instead of a `git add --renormalize` (https://github.com/git-lfs/git-lfs/issues/874) which causes your large file to be modified every time it gets checked out. What I did to resolve the issue was ... 

1) `git lfs untrack "*.some_extension"`
2) `git lfs track "*.some_extension"`
3) `git add --renormalize .`
4) `git commit` and `git push`
