### ISSUE TITLE
failed to call git rev-parse --show-toplevel: exit status 128

### ISSUE THREAD

**Issue by suzfsr** [git-lfs/git-lfs#4254]
Hi,
When I try to lock a file, I get the following error:

![image](https://user-images.githubusercontent.com/15670605/93464455-790a2d80-f8e9-11ea-9015-f245820d69d7.png)

GIT LFS VERSION:
git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)

What could be the problem?

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Could you provide the version of Git by running `git lfs env`?  Could you also run `git rev-parse --show-toplevel --absolute-git-dir`, providing both of those as code blocks instead of images?

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back, I'm going to close this.  If you can provide the information requested, we can look into this further.
