### ISSUE TITLE
Getting a GH008 error when doing a push from gitlab -> github

### ISSUE THREAD

**Issue by sbonar** [git-lfs/git-lfs#4255]
Our project current mirrors from a gitlab repo to a github repo and both have lfs.
Yesterday the mirror stopped working because it appears that new lfs objects were added to gitlab but since they are not in github's lfs information the push fails.

We tried reverting the changes that caused the new lfs objects but that did not work since the objects are still part of git's history so git lfs still has a record of them.

Any help is greatly appreciated.

**Comment by sbonar** [comment]
I'm going to close this for now.  I did not notice that on gitlab's page to enable mirroring they have this comment:
Git LFS objects will be synced in pull mirrors if LFS is enabled for the project. They will not be synced in push mirrors.

Of course we are doing a push mirror

**Comment by sbonar** [comment]
Reopening to ask for input.  Since doing a push mirror from gitlab -> github does not sync LFS objects does anyone have suggestions for making that sync occur?  We are currently stuck because gitlab has objects that github does not so therefore github is rejecting the push.

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  If you have the hooks installed by using `git lfs install`, that should push the objects from your local copy.  If you don't have the objects in your local copy, you can download them with `git lfs fetch --all`, which should pull them into your local copy so you can push them.  If you want to download fewer things, you could try `--recent` instead of `--all`.

**Comment by sbonar** [comment]
I think the issue though, as I mentioned first, the issue is with the mirroring between gitlab to github.
The up to date lfs objects on in gitlab and I need to get them into github outside of gitlab because the mirroring does not sync the lfs objects when pushing.
I hope that makes since?
I mean I could copy the files in question over to my local github and lfs push them but will that give me the same hash for the objects so when gitlab syncs again the objects are now there?

**Comment by bk2204** [comment]
If you're using some sort of built-in mirroring between GitLab and GitHub, then you'd have to reach out to whomever is responsible for that and ask them to sync the LFS objects as well.  If you're using GitHub's LFS storage, then it won't let you push any revisions that refer to LFS objects without the objects being uploaded first.

If you do the mirroring manually, downloading the objects manually and pushing them will result in the same behavior with the same objects and hashes as doing it automatically.

**Comment by sbonar** [comment]
I was able to get things sync'd and mirroring again by manually updating the LFS objects in github.
Thx
