### ISSUE TITLE
Add support for socks5h proxies

### ISSUE THREAD

**Issue by ChrMa** [git-lfs/git-lfs#4258]
I have started using git-lfs recently, and found, that accessing repositories through a socks5h server has become quite a headache. Git itself supports both socks5 and socks5h without problem, trying to resolve host names locally for socks5 and forwarding them to the socks server for socks5h. For what I'm doing, I need the latter, so I used to specify a socks5h proxy.
For some reason, golang chose not to support proxy URL starting with socks5h, only with socks5, but if you give it a socks5 URL, it actually does things the socks5h way and forwards all host names to the socks server. I found bug reports and change proposals to remedy this situation in golang, that were written two years ago. So I don't expect the situation to improve any time soon.
In the meantime, would it be possible to implement a workaround in git-lfs, that replaces socks5h URLs with socks5 URLs before handing them off to golang? Then I could set HTTPS_PROXY to socks5h://server:port and both git and git-lfs would do the same thing.

**Comment by bk2204** [comment]
Hey,

I think this should be possible.  Can you try the PR in #4259 and verify that it works for you?  CI should build (unsigned) binaries if you need some to test.

**Comment by ChrMa** [comment]
Thank you for the quick response. This patch is exactly what I had in mind.

I compiled your commit on an ubuntu 16.04 machine with go1.10.4 (the newest one available on apt) and tested it against openssh's builtin socks server, which is actually what I need this feature for.

The result: everything worked flawlessly. Again, thank you very much.
