### ISSUE TITLE
Migration with `import --everything` affects only the current branch

### ISSUE THREAD

**Issue by halcyon22** [git-lfs/git-lfs#4264]
**Describe the bug**
`git lfs migrate import --everything` migrates only the current branch.

**To Reproduce**
Assumes a linux system.
1. Create a repository for the demonstration.
2. Download https://github.com/halcyon22/lfs-everything-demo-1/blob/master/reproduce.sh
3. Run `./reproduce.sh <your demo repo URL>`

The script will clone the provided URL as `lfs-everything-demo` and commit/push that repo to put it in a state that demonstrates the end state of a migration with multiple branches.

The command used is:
```
git lfs migrate import --everything --verbose --include="*.jp*g"
```

**Expected behavior**
I expected files matching the provided file pattern to be migrated on all branches.

Please let me know if I misunderstood the intended behavior of the `--everything` flag, or if more information is needed.

**System environment**
* CentOS Linux release 7.8.2003 (Core)

**Output of `git lfs env`**
```
git-lfs/2.12.0 (GitHub; linux amd64; go 1.14.7; git dad7b9e6)
git version 2.24.3

Endpoint=...
LocalWorkingDir=...
LocalGitDir=...
LocalGitStorageDir=...
LocalMediaDir=...
LocalReferenceDirs=
TempDir=...
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=...
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report, and sorry to hear you're having trouble.  However, I'm not able to reproduce the problem with your reproduction script.  I modified it to add the `--yes` argument to the `git lfs migrate import` invocation so it would run noninteractively and then ran this:

```
$ rm -fr test-repo lfs-everything-demo && git init --bare test-repo && ./reproduce.sh test-repo
```

When I go into `lfs-everything-demo`, I notice that using `git log -p` on both branches shows all of the `.jpg` files being LFS files.  Is there something that I'm doing differently that might cause a different behavior?  I'm using a different default branch name (`dev`), but I find it very unlikely that that's causing a relevant difference.

If there's a problem here, we'd love to fix it, but I'm having trouble finding out where things aren't working.

**Comment by halcyon22** [comment]
Thanks very much for the response! Your response helped me understand what I was doing wrong - it turns out I just needed to include `--all` in `git push --force` to push all branches.

**Comment by bk2204** [comment]
Great, I'm glad you figured out what's going on.
