### ISSUE TITLE
tq: refusing to retry . . . error: failed to push some refs to . . .

### ISSUE THREAD

**Issue by dagrawa2** [git-lfs/git-lfs#4270]
Hello,

I am getting an error when trying to push to github with LFS, and I have not seen this exact error message elsewhere.

For a minimal working example, I created a test repo at https://github.com/dagrawa2/test-repo. I initialized the repo with a README. I cloned the repo onto my machine, and I then created a small file called data.csv. I then ran the commands:

git lfs track "*.csv"
git add .gitattributes
git commit -m "Add .gitattributes."
git push

All of the above worked. Then I tried

git add data.csv
git commit -m "Add data."
git push

and I got an error. For troubleshooting, I ran

GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push

and I got the output in the attached file [dump.txt](https://github.com/git-lfs/git-lfs/files/5337959/dump.txt).

I see that git retries to upload the csv file 8 times and then gives up, but I have no idea what could be causing it. Any help would be appreciated.

Also, here is the version of git I am running:

git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
git version 2.18.0.windows.1

**Comment by chrisd8088** [comment]
Hey, I'm sorry to hear you're having trouble.  The error I see in your log file looks like this:
```
LFS: Put https://github-cloud.s3.amazonaws.com/...: x509: certificate signed by unknown authority
```
which to me implies that your system is not configured to accept the certificate presented by Amazon's servers when Git LFS tries to push the contents of your `data.csv` file to AWS (which is where GitHub stores users' LFS data).

You might want to look at what `git config -l` reports, in case you have some existing settings there for `http.sslCAPath` and `http.sslCAInfo`, or have the `GIT_SSL_CAPATH` or `GIT_SSL_CAINFO` environment variables set.  (The output of `git lfs env` might help here too.)  Can you connect to `https://github-cloud.s3.amazonaws.com/` in a regular Web browser, or do you get an error there too?

**Comment by dagrawa2** [comment]
Hi, thanks for your response. I ran git config -l, and here is the output: [git_config_l.txt](https://github.com/git-lfs/git-lfs/files/5351562/git_config_l.txt).

I also ran git lfs env, and here is the output: 
[git_lfs_env.txt](https://github.com/git-lfs/git-lfs/files/5351567/git_lfs_env.txt)
.

When I try to connect to 
https://github-cloud.s3.amazonaws.com/
in Chrome, I get the following message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>66669AD7F5461A6E</RequestId>
<HostId>SPpU81CwjPjbDNzt7b6cMejTrxTZ/9TgdkxPgB8n6vtxiwaeA3vxVW01Rq0sjtH8F2Kn3WQezSQ=</HostId>
</Error

One thing I tried is the following: I transferred the repo to a Linux machine and tried to push my files from there. "git push" still didn't work, but the error message suggested I try "git lfs push origin main --all". I tried that, and I didn't get an error message, but my CSV file still wasn't showing up on github. I then followed up that command with one more "git push", and then it worked.

I tried to do "git lfs push origin main --all" from my local Windows machine too, but it didn't work. So I guess either the issue is related to Windows vs Linux, or my local machine and the remote machine respond differently to the Amazon certificate.

I tried to access the Amazon cloud using the above URL on the remote linux machine with wget, and I got "Error 403: Forbidden". So I'm still not sure exactly what's going on.

For now, transferring files to the remote Linux machine and pushing from there (first with git lfs push --all and then just git push) is a sufficient workaround, but if there's a simple solution to the problem, I'm still interested.

**Comment by chrisd8088** [comment]
It sounds like you're not being blocked by a firewall or something on your Windows machine, at least.  But I see in your output from `git config -l` the following lines:
```
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
```

As I noted above, those lines tell Git (and Git LFS) to verify SSL certificates against the list of certificate authorities in your `C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt` file, whereas your browser is using whatever current CA list it has installed for itself.  So it's able to talk to AWS (even if it gets a 403) while Git LFS is rejecting the SSL handshake because it's not finding the authority for Amazon's certificate in your `ca-bundle.crt` file.

I would recommend updating that file, using whatever upstream source it came from in the first place; or changing your Git configuration so it's using the CA list from Windows instead of a custom one you've got installed locally.  Anyway, I believe that's the source of your problem, so I'm going to close this issue.
