### ISSUE TITLE
[Q] How does git LFS handle duplicate files?

### ISSUE THREAD

**Issue by NightMachinary** [git-lfs/git-lfs#4271]
Are there some docs on this?

My primary question is, what happens if I add a duplicate file to my repo with a different name? Will this double the storage used?

```
cp someBigFile someBigFile2
# How will LFS handle this?
```

**Comment by bk2204** [comment]
Hey,

Git LFS, like Git, stores objects by hash.  Therefore, if you have two identical files, then they'll have the same hash and Git LFS will store only one copy.

Note that you'll still have two independent copies in the tree unless you run `git lfs dedup`, which may or may not be available on your system.
