### ISSUE TITLE
git add is adding files to git lfs tracking which it should not

### ISSUE THREAD

**Issue by elenzil** [git-lfs/git-lfs#4273]
**Describe the bug**

Despite only tracking a small handful of filetypes extensions, LFS seems to be claiming all filetypes.

**To Reproduce**

1. I have an existing repository with say no .exe files and no .ps1 files.
2. git lfs track "*.exe"
3. git add .gitattributes
4. copy over a bunch of .exe and .ps1 files into Subdir
5. git add Subdir
6. git lfs status
    --> includes the .txt files and the .exe files with an "(LFS: #######)" indication.
    --> only .gitattributes has a "(Git: #######)" indication.

**Expected behavior**
git lfs status would either not show the .txt files, or would show them with a "Git" indication.

**System environment**
Windows, Git 2.27.0, LFS 2.10.0. Powershell.

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.27.0.windows.1

Endpoint=<redacted>
LocalWorkingDir=<redacted>
LocalGitDir=<redacted>\.git
LocalGitStorageDir=<redacted>\.git
LocalMediaDir=<redacted>\.git\lfs\objects
LocalReferenceDirs=
TempDir=<redacted>\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=<redacted>\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_TR2_CONFIG_PARAMS=gvfs.*,remote.origin.url,user.*
GIT_TR2_EVENT=\\.\pipe\git-c780ac06-135a-4e9e-ab6c-d41e2d265baa
GIT_TRACE2_CONFIG_PARAMS=gvfs.*,remote.origin.url,user.*
GIT_TRACE2_EVENT=\\.\pipe\git-c780ac06-135a-4e9e-ab6c-d41e2d265baa
GIT_TRACE2_PARENT_NAME=_run_dashed_
GIT_TRACE2_PARENT_SID=20201007T224553.177125Z-Hda7c65a5-P00008dd0
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Any other relevant context about the problem here.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble, and thank you for the detailed notes.  Unfortunately I don't yet seem able to reproduce the problem.  I'm also trying with Git LFS 2.10.0, albeit on macOS and not Windows.  Here's my series of steps and their output:

```shell
$ git init exebug
$ cd exebug
$ touch foo.txt
$ mkdir bar && touch bar/123.txt
$ git add .
$ git commit -m initial

$ git lfs track "*.exe"
$ git add .gitattributes
$ cat .gitattributes
*.exe filter=lfs diff=lfs merge=lfs -text

$ mkdir subdir
$ echo abc > subdir/abc.exe
$ echo def > subdir/def.exe
$ touch subdir/foo.txt
$ touch subdir/bar.txt
$ git add subdir

$ git lfs status
On branch master

Objects to be committed:

	.gitattributes (Git: 224a1cd)
	subdir/abc.exe (LFS: edeaaff)
	subdir/bar.txt (Git: e3b0c44)
	subdir/def.exe (LFS: da1464f)
	subdir/foo.txt (Git: e3b0c44)

Objects not staged for commit:
```

Out of interest, what does that sequence produce for you?  And if it's still not working as expected, would you be able to include the output of `git config -l` (with any private data redacted, of course)?

**Comment by elenzil** [comment]
Hi -
many thanks for your amazingly quick reply and for looking into this so much already.

well, I can't reproduce it with a clean repository like this.
I thought perhaps it was due to the presence of a submodule, but it still doesn't repro.

I think I'll need to close this as CNR.
I was able to setup LFS on the actual repo in question using `git lfs migrate --import --include`,
on a branch which already had the .exe's in it, and now adding new .exe and .txt files behaves as expected.

For what it's worth, here's a powershell version of your test script which includes a submodule.
I think the syntax should be bash-compatible except for the '-force' on the `rm`.

Thanks again for taking the time.

```
echo 'Setting up git repo etc'

rm -r -force exebug
git init exebug
cd exebug
ls > foo.txt
mkdir bar
ls > bar/123.txt
git add .
git commit -m 'initial'

# add a submodule
mkdir extern
git submodule add https://github.com/ReneNyffenegger/cpp-base64.git extern/cpp-base64
git commit -m 'submodule'


git lfs track '*.exe'
git add .gitattributes
cat .gitattributes

mkdir subdir
echo 'abc' > subdir/abc.exe
echo 'def' > subdir/def.exe
echo 'pqr' > subdir/pqr.txt
echo 'stu' > subdir/stu.psm1
git add subdir

git lfs status
```

**Comment by elenzil** [comment]
cannot reproduce
