### ISSUE TITLE
Remote changes remain as modified files after git pull fails due to certificate error

### ISSUE THREAD

**Issue by ChristophSchmid** [git-lfs/git-lfs#4274]
**Describe the bug**
In my project, we recently migrated our old SVN repositories to Git. Since there are a number of large binary files in our repositories, we use Git LFS with Git for Windows. Further we need to be able to lock some of those files to serialise work on these. Our repository is hosted on Bitbucket Server. Unfortunately, our Bitbucket server is using a self-signed certificate for the moment, which we cannot change currently. We set up our local repositories using SSH keys.
To make everything work, we initially set up our repositories with the git configuration parameter http.sslCAInfo set to a path to a local copy of the certificate in .pem format. This originally solved the "x509 certificate signed by unknown authority" errors we got. However, after a while working with the new set-up, we occasionally still observe these x509 errors. We don't know why they occur, but when they do during a git pull, we observe a behaviour that we believe might be a bug in Bitbucket LFS. After the git pull fails due to the certificate error, the local repository contains all changes that were pulled from the remote branch, but they appear as uncommitted, locally modified files and can be seen as such in the output of git status. These changes must then be reverted before a new try with git pull can be done, since git pull will give an error about the local changes that would be lost during merging.

**To Reproduce**
Steps to reproduce the behaviour:
1. On a Bitbucket server with self-signed certificate make changes to a repository.
2. Pull those changes to a local repository, which should produce a x509 error.

**Expected behaviour**
If a certificate error occurs, the pulled changes should be reverted to leave the local repository as it was before.

**System environment**
Windows 10 1909
Git version 2.20.1.windows.1
Git LFS version 2.6.1

**Output of `git lfs env`**
`
$ git lfs env                                                                            
git-lfs/2.6.1 (GitHub; windows amd64; go 1.11.1; git dc072c3e)                           
git version 2.20.1.windows.1                                                             
                                                                                         
Endpoint=https://bitbucket[...].git/info/lfs (auth=none)      
  SSH=git@bitbucket[...].git                                  
LocalWorkingDir=[...]                                           
LocalGitDir=[...]\.git                                                       
LocalGitStorageDir=[...]\.git                                                
LocalMediaDir=[...]\.git\lfs\objects                                         
LocalReferenceDirs=                                                                      
TempDir=[...]\.git\lfs\tmp                                                   
ConcurrentTransfers=3                                                                    
TusTransfers=false                                                                       
BasicTransfersOnly=false                                                                 
SkipDownloadErrors=false                                                                 
FetchRecentAlways=false                                                                  
FetchRecentRefsDays=7                                                                    
FetchRecentCommitsDays=0                                                                 
FetchRecentRefsIncludeRemotes=true                                                       
PruneOffsetDays=3                                                                        
PruneVerifyRemoteAlways=false                                                            
PruneRemoteName=origin                                                                   
LfsStorageDir=[...]\.git\lfs                                                 
AccessDownload=none                                                                      
AccessUpload=none                                                                        
DownloadTransfers=basic                                                                  
UploadTransfers=basic                                                                    
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core                              
git config filter.lfs.process = "git-lfs filter-process"                                 
git config filter.lfs.smudge = "git-lfs smudge -- %f"                                    
git config filter.lfs.clean = "git-lfs clean -- %f" 
`

**Additional context**
I am aware that there might be an issue on the Atlassian side with the SSL verification. However, it seems to me a bug on the lfs side, since after an error, the local repository does not clean up and revert to the original state.

![certificate error](https://user-images.githubusercontent.com/41045953/95455633-7772d900-096e-11eb-8a4f-44c7d7352a8c.png)

![modified files](https://user-images.githubusercontent.com/41045953/95455608-704bcb00-096e-11eb-90cc-76f088c39583.png)

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble with this.  Unfortunately, I'm not sure there's anything Git LFS can really do here, as what's happening is controlled by Git itself when it tries to run Git LFS's smudge filter and that filter process bumps into your SSH certificate verification problem and has to exit with an error.

At this point, there's no controlling Git LFS process which could step in and try to fix things back up again to leave you in a clean state.  Rather, control is returned to Git (the `git pull` process you initiated) and Git's behaviour in this case is to exit with an error.  You can observe this with a simple test case, leaving Git LFS out of the picture entirely:

```
>smudger.sh cat <<EOF
#!/bin/bash
while read line; do
  if [ "\$line" = "whoops" ]; then
    >&2 echo "\$line" && exit 1
  fi
  echo "\$line"
done
exit 0
EOF

chmod 755 smudger.sh

git init source
cd source
echo '*.txt filter=smudger' > .gitattributes
git add .
git commit -m initial

cd ..
git clone source smudge

cd source
echo ok > first.txt
echo whoops > second.txt
git add .
git commit -m data

cd ../smudge
>>.git/config cat <<EOF
[filter "smudger"]
        required = true
        smudge = $(pwd)/../smudger.sh
EOF

git pull || echo "Pull Error"
echo --------------------
git status
echo --------------------
git pull
```

Here's the output on my system; the final output from `git status` and the second `git pull` match yours, in that one file has been successfully pulled and placed into the working tree (`first.txt`) but the second one triggered the smudge filter to die, and so that's where things stop and you end up with an incomplete pull.  That's really just the consequence of the way Git calls the smudge filter:
```
Initialized empty Git repository in /tmp/source/.git/
[master (root-commit) cf639bf] initial
 1 file changed, 1 insertion(+)
 create mode 100644 .gitattributes
Cloning into 'smudge'...
done.
[master d107b65] data
 2 files changed, 2 insertions(+)
 create mode 100644 first.txt
 create mode 100644 second.txt
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 308 bytes | 154.00 KiB/s, done.
From /tmp/source
   cf639bf..d107b65  master     -> origin/master
Updating cf639bf..d107b65
whoops
error: external filter '/tmp/smudge/../smudger.sh' failed 1
error: external filter '/tmp/smudge/../smudger.sh' failed
fatal: second.txt: smudge filter smudger failed
Pull Error
--------------------
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        first.txt

nothing added to commit but untracked files present (use "git add" to track)
--------------------
Updating cf639bf..d107b65
error: The following untracked working tree files would be overwritten by merge:
        first.txt
Please move or remove them before you merge.
Aborting
```

So while I certainly encourage you to try to sort out the SSH certificate verification error, this is just how things have to be with Git LFS given how Git handles errors which occur while running filters during operations like `git pull`.  So I'm going to close this issue as there's not really anything we can do on the Git LFS side of things.

Good luck with solving the SSH errors and if that turns out to be due to a bug in Git LFS, please do open a fresh issue for the problem!
