### ISSUE TITLE
Add --above parameter to git-lfs migrate import

### ISSUE THREAD

**Issue by EliRibble** [git-lfs/git-lfs#4275]
**Describe the issue**
Currently `git-lfs migrate info` has a parameter, `--above=<size>` which only considers files whose individual filesize is above a given size. `git-lfs migrate import` does not have this parameter but relies instead on `--include` and `--exclude` file paths. For very large repositories this can be too onerous to specify. Instead it would be useful to simply migrate all files over a specific size, say 100K or 1M.

**System environment**
N/A

**Output of `git lfs env`**
N/A

**Comment by chrisd8088** [comment]
Resolved in #4276 ... thanks again for all the work on the patch submission, it's very much appreciated!

**Comment by EliRibble** [comment]
Thank you, I'm extremely impressed at how you managed the process with care, respect and kindness.
