### ISSUE TITLE
Cannot see the csv raw file on github again

### ISSUE THREAD

**Issue by Soot3** [git-lfs/git-lfs#4278]
I used lfs to upload a csv file of over 100mb about 3 weeks ago. It has been corrupted. My colab files using the link stopped working. On checking the github, I am getting this in place of the csv file
version https://git-lfs.github.com/spec/v1
oid sha256:df219bbcf0e8233f33eb83454ef9b3451adf471db29618acfb36d2dacc40ed3f
size 175385569

**Comment by FeliciaXmL** [comment]
![Screenshot_20201011-225122](https://user-images.githubusercontent.com/70836598/95710570-d017cf80-0c15-11eb-8e6a-b498bfdd0066.png)
![Screenshot_20201011-225127](https://user-images.githubusercontent.com/70836598/95710573-d0b06600-0c15-11eb-8824-b7a6f054e95e.png)
![Screenshot_20201011-224945](https://user-images.githubusercontent.com/70836598/95710576-d148fc80-0c15-11eb-8db1-4d627a67389c.png)
![Screenshot_20201011-225116](https://user-images.githubusercontent.com/70836598/95710579-d1e19300-0c15-11eb-8675-2f7db173b744.png)
![Screenshot_20201011-225132](https://user-images.githubusercontent.com/70836598/95710582-d1e19300-0c15-11eb-9026-1a2790a3c023.png)

**Comment by bk2204** [comment]
Hey,

This is the pointer file that Git LFS uses to point to the actual LFS object.  If you're seeing this in the web interface, then the LFS object hasn't been uploaded.  Have you run `git lfs install` in this repository before pushing?  If not, you can do so and then run `git lfs push --all` to upload all your LFS files.

**Comment by FeliciaXmL** [comment]
Thanks .

I love it very helpful

**Comment by Soot3** [comment]
It was working when i first set it up. Pushed again to the same error When I trying re-cloning, got this 'batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access'. Probably just need to try something else. Thanks.
