### ISSUE TITLE
![Screenshot_20201011-225122](https://user-images.githubusercontent.com/70836598/95710570-d017cf80-0c15-11eb-8e6a-b498bfdd0066.png)

### ISSUE THREAD

**Issue by FeliciaXmL** [git-lfs/git-lfs#4279]
![Screenshot_20201011-225122](https://user-images.githubusercontent.com/70836598/95710570-d017cf80-0c15-11eb-8e6a-b498bfdd0066.png)
![Screenshot_20201011-225127](https://user-images.githubusercontent.com/70836598/95710573-d0b06600-0c15-11eb-8824-b7a6f054e95e.png)
![Screenshot_20201011-224945](https://user-images.githubusercontent.com/70836598/95710576-d148fc80-0c15-11eb-8db1-4d627a67389c.png)
![Screenshot_20201011-225116](https://user-images.githubusercontent.com/70836598/95710579-d1e19300-0c15-11eb-8675-2f7db173b744.png)
![Screenshot_20201011-225132](https://user-images.githubusercontent.com/70836598/95710582-d1e19300-0c15-11eb-9026-1a2790a3c023.png)

_Originally posted by @FeliciaXmL in https://github.com/git-lfs/git-lfs/issues/4278#issuecomment-706886244_

**Comment by bk2204** [comment]
This appears to be spam.
