### ISSUE TITLE
Git LFS file not shown

### ISSUE THREAD

**Issue by GitZinger** [git-lfs/git-lfs#4280]
**Describe the issue**
tried to search this question, did not find the answer.
in my project, there are several large files, but the source code files are not that large, on github, it says Git LFS file not shown.. how can I see the source code on github?

thank you so much!

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

win 10

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
`git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git ---)
git version 2.28.0.windows.1

Endpoint=....git/info/lfs (auth=basic)
LocalWorkingDir=D:**
LocalGitDir=D:....git
LocalGitStorageDir=D:...git
LocalMediaDir=D:....git\lfs\objects
LocalReferenceDirs=
TempDir=D:....git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:....git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

The reason this is showing up is because you haven't pushed the LFS objects to the server.  Did yo run `git lfs install` after installing Git LFS?  Are you using a separate Git LFS server different from GitHub?

**Comment by GitZinger** [comment]
> Hey,
> 
> The reason this is showing up is because you haven't pushed the LFS objects to the server. Did yo run `git lfs install` after installing Git LFS? Are you using a separate Git LFS server different from GitHub?

I think I run 'git lfs install';
I don't know about that. I did not control where the files goes to. I just simply push.

**Comment by bk2204** [comment]
Can you try running `git lfs install` and then `git lfs push --all` and see if that fixes the problem?

**Comment by GitZinger** [comment]
> Can you try running `git lfs install` and then `git lfs push --all` and see if that fixes the problem?

No! 
it is not that I did not install the lfs nor the push.
it is because of it is pushed by lfs so it cannot be display

**Comment by bk2204** [comment]
If that's the case, then it sounds like this is a problem with GitHub and not the Git LFS client.  This repository is only for the Git LFS open source client.  Can you please contact GitHub Support about this issue instead?
