### ISSUE TITLE
git clone hangs on windows 10 for lfs enabled repo when ssh-agent is otherwise working well

### ISSUE THREAD

**Issue by sig9** [git-lfs/git-lfs#4285]
**Describe the bug**
When I clone a lfs enabled repository from github using a git@github.com:user/repo.git url it hangs.

**To Reproduce**
1. set up windows 10 to use ssh-agent 
2. add your pub key to github
3. veirfy that you can clone a non git-lfs repo in powershell without being prompted for a password.
4. clone a git repo that has lfs objects in it.  It hangs for me

**Expected behavior**
Git clone should not hang

**System environment**
Windows 10,  built in ssh-agent configured.   keys in ~/.ssh/id_rsa  
git invoked from powershell running in Windows Terminal

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

``` bash
❯ git lfs env
git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)
git version 2.27.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
xGIT_SSH=C:/Windows/System32/OpenSSH/ssh.exe
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Using process explorer I was able to capture the command line for the sub process that was hung.

![image](https://user-images.githubusercontent.com/2271605/96059470-e656a300-0e42-11eb-8fe9-9cb84176d23c.png)

Same issue in CMD shell.  When I enable GIT_TRACE=1 the last trace line to print is this:

``` cmd
17:41:13.576917 trace git-lfs: run_command: sh -c 'C:\WINDOWS\System32\OpenSSH\ssh.exe' -- git@github.com 'git-lfs-authenticate xxxx/xxxx.git download'
```

**Comment by bk2204** [comment]
Hey,

This sounds like #3779, which is due to a bug in the Windows OpenSSH implementation that prevents it from working properly with Git LFS (PowerShell/Win32-OpenSSH#147).  You can instead use the OpenSSH shipped with Git for Windows, which should work.  If having this fixed is important to you, please let the Microsoft folks know that this is a problem.
