### ISSUE TITLE
Git lfs prune hangs on windows

### ISSUE THREAD

**Issue by jflefebvre06** [git-lfs/git-lfs#4288]
**Describe the bug**
When running git lfs prune with lfs version > 2.10.0, the process freeze

![image](https://user-images.githubusercontent.com/2685607/96893101-a3bc4880-148a-11eb-8c06-535bbe1a6fea.png)

![image](https://user-images.githubusercontent.com/2685607/96893155-b171ce00-148a-11eb-85c9-d2e6167a1108.png)

The only solution is to kill the GIT-LFS process. `CTRL+C` does not works.

**To Reproduce**
`git lfs prune --no-verify-remote --verbose`

Works fine with 2.10.0, breaks with 2.11 and 2.12

**System environment**
Windows 10

**Output of `git lfs env`**

```
D:\@WAC>git lfs env
git-lfs/2.12.0 (GitHub; windows amd64; go 1.14.7; git dad7b9e6)
git version 2.29.0.windows.1

Endpoint=https://XXX@YYY/wac.git/info/lfs (auth=none)
LocalWorkingDir=C:\@WAC
LocalGitDir=C:\@WAC\00.git
LocalGitStorageDir=C:\@WAC\00.git
LocalMediaDir=C:\@WAC\00.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\@WAC\00.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\@WAC\00.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  I'm not seeing this behavior, and I don't see any changes between 2.10 and 2.11 that look like obvious culprits.  Do you have a repository that you can share or a set of reproduction steps that we can use to reproduce this behavior?

**Comment by jflefebvre06** [comment]
Hello @bk2204 
Sorry but I can't, I will try to create another repo with reproduction. I there a way to reduce the number of git process during the prune ?

**Comment by bk2204** [comment]
No, there isn't.  It's already throttled to restrict the number of threads to twice the number of CPUs.

**Comment by jflefebvre06** [comment]
hello @bk2204 

I can reproduce the problem with that repository : http://slazdepwac04.francecentral.cloudapp.azure.com/test/test.git

![image](https://user-images.githubusercontent.com/2685607/98081185-f298b380-1e76-11eb-9872-bebfa006e18b.png)

**Comment by jflefebvre06** [comment]
Hello @bk2204 can you reproduce ?

**Comment by bk2204** [comment]
Hey,

Sorry for the delay.  I don't see this problem either on my Linux box or a Windows box.  To reproduce, I did the following:

```
$ git clone http://slazdepwac04.francecentral.cloudapp.azure.com/test/test.git
$ cd test
$ git lfs prune --no-verify-remote --verbose
```

And I don't see the issue.  Is there a step that I'm missing?

**Comment by jflefebvre06** [comment]
If you execute git lfs prune --no-verify-remote --verbose
Is the command always finish ?

**Comment by bk2204** [comment]
Yes, I've run the command multiple times and it finishes each time.  I'm testing on Windows 10 as well as Linux.

**Comment by jflefebvre06** [comment]
cannot reproduce with `git version 2.29.2.windows.1`, any idea?

**Comment by bk2204** [comment]
I'm not sure.  If you're talking about the difference between Git LFS 2.12.0 and 2.12.1, there shouldn't be any relevant difference.  It's not clear to me why you're seeing this on some versions and not others, but I'm not able to produce it with the latest development branch.

**Comment by mastercoms** [comment]
I can reproduce this on Git LFS 2.13.1.

**Comment by mastercoms** [comment]
Looking into it, it happens when you have stash entries. I had stash entries, and had the problem, and then I ran `git stash clear`. After that, I no longer had the hanging issue.

**Comment by chrisd8088** [comment]
Several folks have noted this may be related to stashed Git entries.  The Git LFS v2.13.0 release *does* include a change (#4209) whereby `git lfs prune` tries to avoid deleting objects referenced by stashes, but the original bug report here specifically mentions v2.11 and v2.12 and so couldn't be affected by that particular change.

If anyone can generate a small test case which reproduces the issue, that would be very handy.

**Comment by slonopotamus** [comment]
Given that there's no testcase here, I'd pretend that this is a duplicate of #4401 unless there's some evidence that it is a separate issue.

**Comment by mastercoms** [comment]
I no longer experience this issue with v2.13.3.

**Comment by bk2204** [comment]
Great.  I'll close this, then.
