### ISSUE TITLE
Can template projects work with lfs-stored files?

### ISSUE THREAD

**Issue by jquentin-lion** [git-lfs/git-lfs#4293]
I have a template project with 3 large files stored through git-lfs. It seems to work, it says "Stored with Git LFS" when looking at them in github. 
But when I use it as template to create a new project, this new project seems confused about these files. On Github, they don't have the "Stored with Git LFS" message, they still show "70.4 MB" for size, but then they seem to be just 3 lines of text:
`version https://git-lfs.github.com/spec/v1`
`oid sha256:xxxxxxxxxxxxxxxxxxxx etc`
`size 73807592`
Then when I clone this new project, the files are just empty Zero bytes files, and show up immediately as changed in Sourcetree, and when trying to Reset them, I get "[404] Object does not exist on the server" errors.
Is there a way to get it to work, or these 2 features are just incompatible?

**Comment by bk2204** [comment]
Hey,

I'm not sure about the answer to this, and it's a question about GitHub and not the Git LFS open source project, so could you ask this question to the GitHub support folks?  They'd be able to give you a more definitive answer.

Thanks.
