### ISSUE TITLE
Getting Started page is misleading or wrong

### ISSUE THREAD

**Issue by adizhol** [git-lfs/git-lfs#4296]
The getting starting page shows an example to push with git lfs as a simple git push, but it won't work for big files that need lfs.
It should be 
`git lfs push origin master
`

**Comment by bk2204** [comment]
Hey,

I think the explanation is correct.  If you've run `git lfs install`, then the `pre-push` hooks should be installed to push LFS objects automatically.  Can you explain the steps that you took and the result you got?

**Comment by adizhol** [comment]
I basically followed the steps in the getting started.
I saw the .gitattributes was updated with the file extension.

The second time I ran git lfs track *.ext and then the push worked...

I guess I'll close this issue
