### ISSUE TITLE
Self Balancing Robot

### ISSUE THREAD

**Issue by Maclain272** [git-lfs/git-lfs#4297]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
While the idea of a self-balancing robot is very interesting, it doesn't really have much to do with Git LFS, and this issue doesn't appear to contain any actionable information, so I'm closing it.
