### ISSUE TITLE
Recover files from git lfs

### ISSUE THREAD

**Issue by gnohgnol** [git-lfs/git-lfs#4302]
**Describe the issue**
I track binaries files using git lfs. Several weeks later, I have found that it is no need to use lfs since the files have already been compacted by other technologies. I untrack the lfs files, but cannot get the files back to my repo..

**System environment**
Windows 10. Git. Git-lfs.

**Output of `git lfs env`**
LocalWorkingDir=C:\Users\********\*******Projects\*******_lab
LocalGitDir=C:\Users\*******\*******Projects\*******_lab\.git
LocalGitStorageDir=C:\Users\*******\*******Projects\*******_lab\.git
LocalMediaDir=C:\Users\*******\*******Projects\*******_lab\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\*******\*******Projects\*******_lab\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\*******\*******Projects\*******_lab\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_HOME=C:\Program Files\Git
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
All the commands I have entered comes from https://git-lfs.github.com/

**Comment by bk2204** [comment]
Hey,

We have a tool called `git lfs migrate export` that can rewrite your history to remove the use of Git LFS if you like.  Running `git lfs migrate export --help` should show you how to use it.  I recommend the `--everything` option in addition to `-I`.
