### ISSUE TITLE
'git lfs fetch --all' doesn't fetch all LFS files as documentation says

### ISSUE THREAD

**Issue by yurivict** [git-lfs/git-lfs#4310]
The log below shows that after ```git clone``` and ```git lfs fetch --all``` a particular LFS file is still not fetched, that is apparently not what the documentation says:
> Download all objects that are referenced by any commit reachable from the refs provided as arguments. If no refs are provided, then all refs are fetched.

```
[yuri@yv /usr/ports/graphics/opentoonz]$ git clone  https://github.com/opentoonz/opentoonz.git
Cloning into 'opentoonz'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 45919 (delta 52), reused 26 (delta 13), pack-reused 45817
Receiving objects: 100% (45919/45919), 96.88 MiB | 10.35 MiB/s, done.
Resolving deltas: 100% (32753/32753), done.
Updating files: 100% (11202/11202), done.
[yuri@yv /usr/ports/graphics/opentoonz]$ cd opentoonz
[yuri@yv /usr/ports/graphics/opentoonz/opentoonz]$ git lfs fetch --all
fetch: 81 object(s) found, done.                                                                                                                                                              
fetch: Fetching all references...
[yuri@yv /usr/ports/graphics/opentoonz/opentoonz]$  MB/s                                                                                                                                      
[yuri@yv /usr/ports/graphics/opentoonz/opentoonz]$ cat thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_2015_64.lib
version https://git-lfs.github.com/spec/v1
oid sha256:931554a80f424a46e248c3f7f95ac3ee039b3f54e0f379ef1aab04462e715f86
size 6227900
[yuri@yv /usr/ports/graphics/opentoonz/opentoonz]$ 
```

It starts with no ~/.gitconfig file.

OS: FreeBSD 12.2
git-2.28.0
git-lfs-2.12.0

**Comment by bk2204** [comment]
Hey,

If you want LFS files checked out in the working tree, you should run `git lfs install` on your system first before you clone.

If you don't do that and you still clone, then `git lfs fetch --all` will download the LFS objects, but it doesn't place them in the working tree.  You need to use the `git lfs pull` command to both download and check the files out in the working tree, or, if you've already run `git lfs fetch --all`, you can also run `git lfs checkout`, which will check out the files that you've already downloaded.
