### ISSUE TITLE
Git push says “Everything up-to-date” but the files are not appearing in github repository

### ISSUE THREAD

**Issue by ronaldorawat** [git-lfs/git-lfs#4320]
**Describe the issue**

I initiated git to push things in repo. I entered the commands in below order:-

**1-  git init
2-  git add .
3-  git status**
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   form.css
        new file:   form.html

**4- git commit -m "Commit for the Submit form"**

[master (root-commit) 51ccb20] COmmit for the Submit form
 2 files changed, 414 insertions(+)
 create mode 100644 form.css
 create mode 100644 form.html

**5- git remote add origin https://github.com/ronaldorawat/FreeCodeCamp-Form.git**

**6-  git push -u origin master**

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 2.71 KiB | 694.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0       
remote: 
remote: Create a pull request for 'master' on GitHub by visiting:
remote:      https://github.com/ronaldorawat/FreeCodeCamp-Form/pull/new/master
remote:
To https://github.com/ronaldorawat/FreeCodeCamp-Form.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.

**7-  git push -u origin master**

Everything up-to-date
Branch 'master' set up to track remote branch 'master' from 'origin'.

**System environment**

windows 10

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**git-lfs/2.12.0 (GitHub; windows amd64; go 1.14.7; git dad7b9e6)
git version 2.29.2.windows.1**

**Additional context**
 This has happened second time. When files were not added by running but bash, I had to select the files using add files option in Github REPO. The only file was READ Me which I wanted while creating the repo.

![REPO](https://user-images.githubusercontent.com/31548338/100126488-0054be00-2ea4-11eb-85fb-67c23d2e917d.PNG)

**Comment by bk2204** [comment]
Hey,

First of all, this doesn't sound like a problem with Git LFS, but a more general Git and GitHub problem.  I'm going to try to help you out, but I recommend you contact GitHub Support if you're still having trouble with GitHub.

In your case, the branch you're working on is called `master`.  However, the default branch in your GitHub repository is called `main`.  If you push to a different branch, then your data won't appear on the main page in GitHub.  If you want to change your repository's default branch, you can do that in the repository settings, and if you want to change the name of your branch in your local repository, you can use `git branch -m main`.

**Comment by ronaldorawat** [comment]
Thanks Brian, I got it now. I am wondering why I wasn't getting an option to switch to master branch earlier. The issue is resolved.

However I received an error while trying: 

git push origin main
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/ronaldorawat/FreeCodeCamp-Form.git'

**Comment by Mechelle101** [comment]
Hey so I had a similar problem here's mine.... 
 create mode 100644 public/staff/admin/employee_list.php
 create mode 100644 public/staff/admin/images.php
 create mode 100755 public/staff/admin/index.php

I started git, did my first commit on master, created a dev branch, worked from there, a new commit my changes still on dev branch, then created repository on github, pushed to that repository, nothing went to github, and then the output above. Also, it wouldn't let me see status or exit and wouldnt show what branch i was on... nothing. 

What did I do and how can I fix it? is it the same as your comment above?

**Comment by vempadaravi** [comment]
gitlab push says everythin is upto date but while refreshing and checking in repository project is not opening it is showing error
