### ISSUE TITLE
Developer can push lockable file after disable readonly flag.

### ISSUE THREAD

**Issue by IXOFIXOF** [git-lfs/git-lfs#4322]
**Describe the issue**
Process:
I need change something in lockable file, let's say some .sql file. I can't change anything, because someone else has lock on file. This is correct. So I go to file properties and disable readonly flag. I would like only check something. I recognize, that my changes are needed so I will commit and push changes. But I forgot, that I should have lock on file. I would expect some message: "To push file %s you need have lock of them. Lock file %s and try push again". Something like that will prevent me to make conflict with developer, which has lock on file and think, that nobody else can change file on remote.
It is possible? 

We're using windows 10 and self-hosted gitlab.
```
MLI@MLI MINGW64 /e/test (master)
$ git --version
git version 2.29.2.windows.2

MLI@MLI MINGW64 /e/test (master)
$ git lfs --version
git-lfs/2.12.1 (GitHub; windows amd64; go 1.14.10; git 85b28e06)
```
```
MLI@MLI MINGW64 /e/test (master)
$ git lfs env
git-lfs/2.12.1 (GitHub; windows amd64; go 1.14.10; git 85b28e06)
git version 2.29.2.windows.2

Endpoint=http://gitlab.in-poz.local/MLI/test.git/info/lfs (auth=basic)
LocalWorkingDir=E:\test
LocalGitDir=E:\test\.git
LocalGitStorageDir=E:\test\.git
LocalMediaDir=E:\test\.git\lfs\objects
LocalReferenceDirs=
TempDir=E:\test\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=E:\test\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

MLI@MLI MINGW64 /e/test (master)
$
```

**Comment by IXOFIXOF** [comment]
And also second question. When I try lock file, but it is locked by someone else, I get only message, that file is already locked, but in message in my opinion, miss who already locked file.
I know, that i can use 
`git lfs locks`
to check that, but maybe is some chance to show, who has lock during locking file?

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Your second question is I think already described in #3788 -- that issue describes a feature request to enhance the error message when a file is already locked.

As for your first question, I'm not 100% sure I follow your exact process.  Are you saying you are able to push a file when someone else has an active lock on it?  If so, can you provide a full example session, showing the sequence of commands from both developers?

Or do you just mean that you are expecting to be asked to lock a lockable file before you push it, in case another developer was also trying to change that file?  This sounds like #4292 where there is some explanation of what's going on in https://github.com/git-lfs/git-lfs/issues/4292#issuecomment-719751507: Git LFS locks are advisory and the locks are normally checked only by the client in a `pre-push` hook and not by the server.  So if you push a file that is marked lockable but doesn't happen to be actually locked by someone else at the time you push it, that's acceptable according to the design.  The client `pre-push` hook should only warn you if someone else has an active lock on the file at that time.

If you are able to do that -- push to a locked (not just lockable) file where the lock is held by someone else -- it would be good if you could provide a complete reproducible example.

**Comment by IXOFIXOF** [comment]
Hey,
During preparing full example for you, I recognized, that I was logged to git batch console as the same user in both session. It was reason, why I could push not locked file, it was locked by me in other session. When in other session I logged to git via other user, everythnig works good. I'm sorry for wasting your time :/
It was not clear for me, that LFS only checks if file is locked by someone else, not by me, but now I see that this idea has sense.

About my second question, I understand, that feature #3788 is task for gitlab team, to improve server implementation?

**Comment by chrisd8088** [comment]
That great, I'm glad you sorted things out!

As for the feature request in #3788, I believe the idea is that the server would provide more information in a 409 response so that the client could do what you suggested, namely, to show who has a lock on a file already if you try to lock an already-locked file.  It sounds like this feature request would require a bit more work on the both client and server sides if it was to work that way; otherwise perhaps the client could do more work and automatically try to retrieve additional lock information when it encountered a locked file.  Either way, I think the idea is captured in #3788, so I'm going to close this issue for now.
