### ISSUE TITLE
It doesn't work, I have no clue what is the problem

### ISSUE THREAD

**Issue by pawelusc** [git-lfs/git-lfs#4323]
**Describe the issue**
I have installed it with 
`sudo snap install liveforspeed`
I have executed it with
`$ liveforspeed`
I got an error
`
Unable to init server: Could not connect: Connection refused
(yad:7742): Gtk-WARNING **: 02:47:09.013: cannot open display: :0
wine: Bad EXE format for Z:\tmp\LFS_S3_6T_setup.exe.
removed '/tmp/LFS_S3_6T_setup.exe'
/snap/liveforspeed/11/bin/sommelier: line 114: cd: /home/pawel/snap/liveforspeed/common/.wine/drive_c/LFS: No such file or directory
wine: cannot find '/home/pawel/snap/liveforspeed/common/.wine/drive_c/LFS/LFS.exe'
`
I honestly have no idea what went wrong.

**System environment**
Ubutnu 20.10

**Output of `git lfs env`**
Git says that `lfs` is not a command.

**Additional context**
I am willing to provide all helpful data

**Comment by pawelusc** [comment]
Ooops. I have just realized that LFS != liveforspeed. 
Sorry guys, and have a great day!

**Comment by chrisd8088** [comment]
No worries, glad you figured it out.
