### ISSUE TITLE
lfs

### ISSUE THREAD

**Issue by shuangyichen** [git-lfs/git-lfs#4325]
**Describe the bug**
I am using lfs to uplode files following the rules. including 
git lfs track **
git add .gitattributes
git add .
git commit
After I commit, I use git lfs ls-files, the files I want to upload did not show. 
When I use git lfs status, nothing is under Git LFS objects to be pushed to..
when I use git lfs track, files I want to upload show

And I failed uploading using lfs 
`shuangyichen@minfer3-desktop:~/dele/m-quant/m-quant$ git push origin csy/plusxavier_stage1
Username for 'https://gitlab.momenta.works': hugang1
Password for 'https://hugang1@gitlab.momenta.works':
Username for 'https://gitlab.momenta.works': hugang1
Password for 'https://hugang1@gitlab.momenta.works':
Username for 'https://gitlab.momenta.works': hugang1
Password for 'https://hugang1@gitlab.momenta.works':
对象计数中: 9, 完成.
Delta compression using up to 16 threads.
压缩对象中: 100% (9/9), 完成.
写入对象中: 100% (9/9), 342.66 MiB | 7.13 MiB/s, 完成.
Total 9 (delta 2), reused 0 (delta 0)
remote: GitLab: File "thirdparty/xavier/lib/libcudnn.so.7.5.1" is larger than the allowed size of 100 MB
To https://gitlab.momenta.works/m-adaptor/m-quant.git
 ! [remote rejected] csy/plusxavier_stage1 -> csy/plusxavier_stage1 (pre-receive hook declined)
error: 无法推送一些引用到 'https://gitlab.momenta.works/m-adaptor/m-quant.git'
`

**Output of `git lfs env`**
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)
git version 2.17.1

Endpoint=https://gitlab.momenta.works/m-adaptor/m-quant.git/info/lfs (auth=none)
LocalWorkingDir=/home/shuangyichen/dele/m-quant/m-quant
LocalGitDir=/home/shuangyichen/dele/m-quant/m-quant/.git
LocalGitStorageDir=/home/shuangyichen/dele/m-quant/m-quant/.git
LocalMediaDir=/home/shuangyichen/dele/m-quant/m-quant/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/shuangyichen/dele/m-quant/m-quant/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/shuangyichen/dele/m-quant/m-quant/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Could you show us the contents of your `.gitattributes` file as a code block?  That would help us figure out what's going on here.

**Comment by shuangyichen** [comment]
> Hey,
> 
> Sorry to hear you're having trouble. Could you show us the contents of your `.gitattributes` file as a code block? That would help us figure out what's going on here.

`thirdparty/fp32_onnx_forward/minfer-compile filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn.so.8 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn_cnn_infer.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn_cnn_infer.so.8 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn_cnn_infer.so.8.0.1 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn_ops_infer.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libcudnn_ops_infer.so.8 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libminfer.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libmyelin.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libmyelin.so.1 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libmyelin.so.1.1.0 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libnvinfer.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libnvinfer.so.7 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libnvinfer.so.7.1.3 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libnvparsers.so filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libnvparsers.so.7 filter=lfs diff=lfs merge=lfs -text
lib/xavier/x86_64-linux-gcc5.4-cuda10.2/libnvparsers.so.7.1.3 filter=lfs diff=lfs merge=lfs -text
thirdparty/xavier/lib/libcudnn.so.7.5.1 filter=lfs diff=lfs merge=lfs -text
thirdparty/xavier/lib/libminfer.so filter=lfs diff=lfs merge=lfs -text
thirdparty/xavier/lib/libnvinfer.so.5.1.4 filter=lfs diff=lfs merge=lfs -text
thirdparty/xavier/lib/libnvparsers.so.5.1.4 filter=lfs diff=lfs merge=lfs -text
`


the last four are files I want to upload this time. Thank you!

**Comment by bk2204** [comment]
Hey,

These contents look reasonable.  Did you add these files to the repository before adding the `.gitattributes`?  If so, you'll need to rewrite the history with `git lfs migrate import --everything` (and an appropriate `--include` option).

What GitLab is telling you is that somewhere in the history, the file `thirdparty/xavier/lib/libcudnn.so.7.5.1` is being stored as a Git object instead of an LFS object.  Which files get filtered through Git LFS is a function of the `.gitattributes` file at the time you add them.

**Comment by bk2204** [comment]
Hey, since we haven't heard back on this, I'm going to close it.  We can reopen it if you still need assistance if you comment.
