### ISSUE TITLE
Faisalalanzi 

### ISSUE THREAD

**Issue by faisalalzni** [git-lfs/git-lfs#4329]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This issue doesn't contain any description of the bug.  This seems like another unhelpful contribution.  Please test on your own repos.

I'm closing this.  If you can't participate helpfully, please refrain from participating at all.

Thanks.
