### ISSUE TITLE
The token supplied to the function is invalid

### ISSUE THREAD

**Issue by astenman** [git-lfs/git-lfs#4340]
**Describe the issue**
In order to evaluate git-lfs I have created a repo on our Nexus server. Nexus runs in a container behind a nginx proxy container. However, when I try to push from "git for windows", I get the following error "trace git-lfs: api error: The token supplied to the function is invalid". Any thoughts what might cause this?

**System environment**
Nexus/nginx running in containers. Git for windows on Windows 10.

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
git version 2.23.0.windows.1

Endpoint=https://artifacts.niradynamics.se/repository/tire-health/info/lfs (auth=ntlm)
LocalWorkingDir=C:\Users\anste\LFS-test
LocalGitDir=C:\Users\anste\LFS-test\.git
LocalGitStorageDir=C:\Users\anste\LFS-test\.git
LocalMediaDir=C:\Users\anste\LFS-test\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\anste\LFS-test\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\anste\LFS-test\.git\lfs
AccessDownload=ntlm
AccessUpload=ntlm
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

I'm not certain, but it sounds like this is probably an authentication error of some sort.  If you want to take a look, you can run with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and see what the HTTP error code is like.

This sounds like it may be an NTLM issue, and if so, I'd strongly encourage you to adopt a different authentication technique.  As outlined in #4247, nobody is willing to maintain NTLM support, and it will be dropped in the next minor release after 2.13.0 unless someone steps up to maintain it.  I'd recommend Basic or Kerberos (Negotiate) instead.

**Comment by astenman** [comment]
Thank you for your response. I tried Kerberos instead and then it worked. I also had to do a change in the nginx config.
