### ISSUE TITLE
Change -u to -z in %forgemeta when there is no %forgemeta in the spec file?

### ISSUE THREAD

**Issue by Umeaboy** [git-lfs/git-lfs#4349]
**Describe the issue**
If I run sudo urpmi git-lfs.spec to install all the build requirements I get a warning about the use of -u being deprecated in %forgemeta, but I don't see the usage of %forgemeta in said spec file.

**System environment**
OS: Mageia 7.1
Arch: x86_64
Linux kernel: 5.7.19-desktop-3.mga7
git config -l:
user.name=Kristoffer Grundström
user.email=lovaren@gmail.com
color.ui=auto

**Output of `git lfs env`**
git-lfs isn't installed.

**Comment by bk2204** [comment]
Hey,

I'm not sure why you're seeing this, but I don't see that macro anywhere in our repository or in the standard RPM locations for a Mageia 7 install.  I assume this dependency comes in from somewhere else on your system or some other tooling, but I don't think it's a problem with Git LFS.  If you look in `/etc/rpm/macros.d` and `/usr/lib/rpm/macros.d` and find the macro on your system, you should be able to find the party who put it there and then file a bug report with them.

Sorry I can't be of more help.

**Comment by Umeaboy** [comment]
Which one of these should I look in?

20build.macros   21cauldron.macros  Default.macros    qt5.macros         rubygems.macros  spec-helper.macros
20common.macros  cmake.macros       multiarch.macros  rpm-helper.macros  ruby.macros

**Comment by Umeaboy** [comment]
ls /usr/lib/macros.d shows:

macros.dist    macros.forge                    macros.jpackage    macros.perl           macros.python   macros.python-mga   macros.systemd
macros.dwz     macros.go-srpm                  macros.mono-srpm   macros.pkgconf        macros.python2  macros.python-srpm  macros.valgrind-srpm
macros.filter  macros.javapackages-filesystem  macros.ocaml-srpm  macros.pybytecompile  macros.python3  macros.rust-srpm

**Comment by Umeaboy** [comment]
Here's our src.rpm if you want to inspect it as well: http://rpm.pbone.net/results_srodzaj_2_search_git-lfs-2.12.1-1.mga8.src.rpm.html

**Comment by bk2204** [comment]
I did a `grep -R forgemeta` in each directory, so I looked in all of them.  I suspect `macros.forge` is going to be your guilty party, though.
