### ISSUE TITLE
Smudge error: The pipe has been ended on 32-bit system

### ISSUE THREAD

**Issue by tommyvct** [git-lfs/git-lfs#4352]
**Describe the bug**
`Smudge error: Error reading from media file: write /dev/stdout: The pipe has been ended.: write /dev/stdout: The pipe has been ended.`
This behaviour is consistent on Windows 32-bit binaries, regardless of main architecture.

**To Reproduce**
`git clone https://github.com/walbourn/directxtexmedia.git`
The following combinations give this result:
- Windows ARM64 + ARM 32-bit git-lfs
- Windows ARM64 + 386 git-lfs
- Windows x64 + 386 git-lfs

![image](https://user-images.githubusercontent.com/7903172/103197383-89984f80-48ab-11eb-8f60-c1a265bc9b1c.png)

**Expected behavior**
Windows x64 + x64 git-lfs
![image](https://user-images.githubusercontent.com/7903172/103197354-82714180-48ab-11eb-9f09-cd5bd16923ae.png)

**System environment**
1. Windows 10 20H2 x64 running 386 `git-lfs.exe` binary that comes with the latest Git for Windows.
2. Windows 10 20H2 ARM64 running 386 `git-lfs.exe` binary that comes with the latest Git for Windows, AND self-compiled 2.13.1 ARM 32-bit binary (compiled on Surface Pro X SQ1 using Ubuntu WSL2, using official Go compiler for Linux ARM64, with `GOOS=windows` and `GOARCH=arm` environment variable set).

**Output of `git lfs env`**
- Windows x64 + 386 git-lfs
```
git-lfs/2.12.1 (GitHub; windows 386; go 1.14.10; git 85b28e06)
git version 2.29.2.windows.3

Error reading git config: error running C:\Program Files (x86)\Git\mingw32\libexec\git-core\git.exe 'rev-parse' '--is-bare-repository': 'fatal: not a git repository (or any of the parent directories): .git' 'exit status 128'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files (x86)/Git/mingw32/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

- Windows ARM64 + 386 git-lfs
```
git-lfs/2.12.1 (GitHub; windows 386; go 1.14.10; git 85b28e06)
git version 2.29.2.windows.3

Error reading git config: error running C:\Program Files (x86)\Git\mingw32\libexec\git-core\git.exe 'rev-parse' '--is-bare-repository': 'fatal: not a git repository (or any of the parent directories): .git' 'exit status 128'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files (x86)/Git/mingw32/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

- Windows ARM64 + ARM 32-bit git-lfs
```
git-lfs/2.13.1 (GitHub; windows arm; go 1.15.6)
git version 2.29.2.windows.3

Error reading git config: error running C:\Program Files (x86)\Git\mingw32\libexec\git-core\git.exe 'rev-parse' '--is-bare-repository': 'fatal: not a git repository (or any of the parent directories): .git' 'exit status 128'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files (x86)/Git/mingw32/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""

```

**Additional context**
https://github.com/git-for-windows/git/issues/2346#issuecomment-751395418
[x64+386.log](https://github.com/git-lfs/git-lfs/files/5746304/386.log)
[arm64+386.log](https://github.com/git-lfs/git-lfs/files/5746319/20201227T225007.1819653.log)
[arm64+arm.log](https://github.com/git-lfs/git-lfs/files/5746321/20201228T004907.0184041.log)
[arm binary](https://github.com/git-lfs/git-lfs/files/5746326/git-lfs-windows-amd64.zip)

**Comment by bk2204** [comment]
Hey,

I think your problem is the one outlined in #4353: that you're running out of memory using 32-bit binaries.  Since this is being addressed there by us hopefully providing an ARM64 binary, I'm going to close this in favor of that issue.
