### ISSUE TITLE
Go mod vendor not adding LFS pointers to tree on mirror (in a circular go.mod)

### ISSUE THREAD

**Issue by SpectralHiss** [git-lfs/git-lfs#4354]
**The issue**

I am compiling a large golang project, which includes some circular dependencies (dependencies that import prior versions of itself), this repo was initially in bitbucket.org with LFS enabled on some large assets and has been mirrored in gitlab.com.
To make things simple we can follow this example file: `api/swagger/bindata.go` which was in LFS from before the migration in this remote bitbucket repo.
 
Initially encountered some 404s for some of the blobs which weren't in gitlab so I ran `git fetch -a remoteA && git push -a remoteB` It seemed to work.

Later, in my branch on the mirror i have enabled vendoring ( through `go mod vendor`).  Among the vendored dependencies it got this older version of the repo itself, which go mod seems to **keep lfs pointers as pointers** (eg `api/swagger/bindata.go` is an LFS pointer on checkout).

Naturally I wanted to track vendor to save space but also thinking that as soon as i track "vendor/**" it would add the lfs pointers to it's tree. 
Now it seems i can't git-lfs checkout the file locally to run my tests.
when i run `git cat-file --filters HEAD:vendor/bitbucket.org/somecompany/org/api/swagger/bindata.go`
**I see the file locally expanded as output with the warning at the bottom**:
`Encountered 1 file(s) that should have been pointers, but weren't:
	vendor/bitbucket.org/somecompany/org/api/swagger/bindata.go`

But then if i `git-lfs checkout` **i don't see anything but the pointer file**:
`version https://git-lfs.github.com/spec/v1
oid sha256:71af0fe5463b1bde7ee04f8fef0dae40f42e89e41953aeeb3b86e574dd5175d0
size 597456
`
Now note that this file isn't considered part of this commit's tree: `git lfs ls-files HEAD -l | grep 71af0fe5463b1bde7ee04f8fef0dae40f42e89e41953aeeb3b86e574dd5175d0`
but it is on master (since it has been mirrored correctly I think):
```
git lfs ls-files -l master | grep 71af0fe5463b1bde7ee04f8fef0dae40f42e89e41953aeeb3b86e574dd5175d0
71af0fe5463b1bde7ee04f8fef0dae40f42e89e41953aeeb3b86e574dd5175d0 * api/swagger/bindata.go
```
Is there a way to make lfs aware of this "flat" pointer file which was added by the vendoring process? what am i doing wrong?
Here's my .gitattributes (you can see some failed experiments there :))
```
/vendor/**[[:space:]] filter=lfs diff=lfs merge=lfs -text
/api/*/*.pb*.go filter=lfs diff=lfs merge=lfs -text
/api/swagger/* filter=lfs diff=lfs merge=lfs -text
vendor/ filter=lfs diff=lfs merge=lfs -text
vendor/bitbucket.org/REDACTED/REDACTED/api/swagger/bindata.go filter=lfs diff=lfs merge=lfs -text
```
**System environment**
`git version
git version 2.28.0`
`git-lfs version
git-lfs/2.12.0 (GitHub; linux amd64; go 1.15.2)
`

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
git lfs env
git-lfs/2.12.0 (GitHub; linux amd64; go 1.15.2)
git version 2.28.0

Endpoint=https://gitlab.com/COMPANY/backend/COMPANY/REDACTED.git/info/lfs (auth=none)
  SSH=git@gitlab.com:COMPANY/backend/REDACTED/REDACTED.git
Endpoint (REDACTED)=https://bitbucket.org/COMPANY/REDACTED.git/info/lfs (auth=none)
  SSH=git@bitbucket.org:REDACTED/REDACTED.git
LocalWorkingDir=/home/houssem/code/gitlab/REFACTED
LocalGitDir=/home/houssem/code/gitlab/REDACTED/.git
LocalGitStorageDir=/home/houssem/code/gitlab/REDACTED/.git
LocalMediaDir=/home/houssem/code/gitlab/REDACTED/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/houssem/code/gitlab/REDACTED/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/houssem/code/gitlab/REDACTED/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
GIT_HOSTING=git@git.domain.com
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

I can reproduce exactly if i delete all of vendor/ and revendor the bindata file is a pointer (there are a few like this) and so it's unusable.

**Comment by SpectralHiss** [comment]
Seems to work now, not sure what happened ..

**Comment by chrisd8088** [comment]
Glad to hear it's working for you now ... I spent some time trying to understand what was going on, but couldn't come up with any advice as of last night except to experiment with `git show HEAD:vendor/bitbucket.org/.../path/to/file.go` to see exactly what Git has stored for the blobs in the repo (and not the working tree) and whether it has pointer data or actual binary data.  But if it's working now, that's great, and good luck!
