### ISSUE TITLE
"$git push origin main" instead of "$git push origin master"

### ISSUE THREAD

**Issue by vickar** [git-lfs/git-lfs#4356]
**Describe the bug**
In the home page at [git-lfs](https://git-lfs.github.com/), the last command in the documentation doesn't work by using master, it is throwing error **error: src refspec master does not match any**, rather it is working if main is used as the last word

**To Reproduce**
use **$ git push origin main** instead of **$ git push origin master**

**Expected behavior**
push my local commit to my remote GitHub repo

**System environment**
Windows version 10.0.18363 Build 18363

**Output of `git lfs env`**
`$ git push origin master`
`error: src refspec master does not match any`
`error: failed to push some refs to 'url of my repo on GitHub'`

**Additional context**
Any other relevant context about the problem here.

**Comment by chrisd8088** [comment]
Hey, thanks for pointing this out.  I've proposed a small PR which updates the example in git-lfs/git-lfs.github.com#43.

**Comment by Krishnkumar20** [comment]
$ git push origin main
error: src refspec main does not match

**Comment by LombokITAcademy** [comment]
I have the same problem
