### ISSUE TITLE
packagecloud key is expired since 2019-01-12

### ISSUE THREAD

**Issue by fkusei** [git-lfs/git-lfs#4357]
Hello,

The GPG key delivered by https://packagecloud.io/github/git-lfs/gpgkey expired in January 2019. Is there a new Key available?

**Comment by bk2204** [comment]
Hey,

I don't see that key as having an expiration.  To me it doesn't appear to expire, according to GnuPG.  Are you sure you're looking at the right key?  The one I see has fingerprint `6D398DBD30DD78941E2C4797FE2A5F8BDC282033`.

**Comment by fkusei** [comment]
`6D398DBD30DD78941E2C4797FE2A5F8BDC282033` is what apt-key shows me, which is listed as expired on 2019-01-12. However, importing the key into my gpg keyring *doesn't* list that key as expired?

I'm confused ...
