### ISSUE TITLE
Git LFS with Azure Git

### ISSUE THREAD

**Issue by sriharshanc** [git-lfs/git-lfs#4358]
**Describe the issue**
I want to push files with Git LFS tracking into Azure Git without a different server/storage location for Large files. 
What i expect to see is the file pointer on my Azure Git web interface rather than the file itself. 
When I have a separate storage for large files (Endpoint=https://localhost:8080/, for instance the GO-implemented Git Lfs Server, I see the pointer files. 
Did I miss something in understanding how Git Lfs works or is it Azure? On Github, I see "Git LFS file not shown" message, but in Azure, I can preview the file.

**System environment**
Using Azure Git and Git LFS on Windows 

**Output of `git lfs env`**
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.2.windows.1
Endpoint=https://xxxxxxxxxxx@dev.azure.com/xxxxxxxxxxx/hrhrhrhr/_git/git-lfs-test.git/info/lfs (auth=basic)
LocalWorkingDir=D:\git-lfs-test
LocalGitDir=D:\git-lfs-test\.git
LocalGitStorageDir=D:\git-lfs-test\.git
LocalMediaDir=D:\git-lfs-test\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\git-lfs-test\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\git-lfs-test\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

I'm not exactly sure how Azure is supposed to work here.  If your question is about how Azure displays the code, you'd have to ask them; I don't know the answer, and this project is only for the open source Git LFS client.  If your question is different and I've misunderstood, please let me know.
