### ISSUE TITLE
Option to Ignore When Checkout Turns Pointer into File Object

### ISSUE THREAD

**Issue by rweickelt** [git-lfs/git-lfs#4359]
- Add a .gitattributes entry to track files with a certain suffix by lfs
- Turn a binary file with that suffix into a lfs pointer in one branch
- Check out another branch where the file is still a file object
- Run `git status`

Git status will show the file as modified and the checkout warns about it. This is annoying. For various reasons we have to convert an existing repo containing binary files to lfs, but we cannot rewrite the history.

It would be more convenient if git lfs would silently ignore the file change in such a case. I guess it is caused by the post-checkout hook.

**Comment by bk2204** [comment]
Hey,

Just so I understand the problem, can you show me what the `.gitattributes` file looks like in a branch that does have this problem and one that doesn't, and what the name of an affected file looks like?  I think I know what the issue is, but that would help me get a better grasp on the behavior you're seeing.

**Comment by rweickelt** [comment]
Every branch contains the following entry 

    *.png filter=lfs diff=lfs merge=lfs -text

The problem is that there are png files in the repo that are not tracked by lfs, but the .gitattributes file mandates that they are. The entry in .gitattributes was added some time ago and populated to all branches, but now after converting actual .png files in master to lfs, the problem occurs when switching to a branch were the file is not tracked by lfs yet. Hence I need to merge master into these branches or rebase them or what not.

However, it will affect all engineers in the team and not everyone understands what is going on.

Hence my suggestion to simplify this a bit.

**Comment by bk2204** [comment]
Hey,

This is indeed the issue I thought it was, and this is a limitation of Git, not Git LFS.  When you specify in `.gitattributes` that `*.png` files are `filter=lfs`, those files are considered by Git to be handled by Git LFS, and Git will ask Git LFS to run them through the clean filter.  When that happens, they'll be turned into pointer files, and those will differ from actual PNGs, so Git will consider them to be modified.

This is unfortunately just how Git works and there's nothing we can do on the Git LFS side to change it.  We have no way of determining when Git asks us to filter a file why it's asked us to do so, and so we can't distinguish the case of someone adding a new or updated LFS file with `git add` versus this particular case.  It also happens with various other filter situations which don't involve Git LFS at all, including working tree encodings and line endings.

The best solution that I can offer you is to fix those branches by running `git add --renormalize .` and committing.  That essentially needs to be done as soon as you add the files to `.gitattributes` if you're not using `git lfs migrate import`, or this will happen.

Sorry there isn't a better solution for this.

**Comment by rweickelt** [comment]
@bk2204, thank you for the explanation. Looks indeed like we have to migrate all branches.
