### ISSUE TITLE
credential loop

### ISSUE THREAD

**Issue by brainlescoder** [git-lfs/git-lfs#4361]
Git lfs keeps on looping askin for the credentials.
I lookedup through the community but didn't work for me at all. Couldn't find the proper solution.
I am using Ubuntu 20.04

Need help.

**Comment by bk2204** [comment]
Hey,

Could you please fill out the issue template so that we can see the settings and configuration you're using, please?  That's why we have it, since it's hard for us to answer this question without knowing more about it.

**Comment by brainlescoder** [comment]
![lfserror](https://user-images.githubusercontent.com/67377885/104086329-e5d07b80-527c-11eb-922e-10d5be4b4729.png)

**Comment by bk2204** [comment]
Hey,

Git LFS should normally cache credentials that are being used.  However, if you have incorrect credentials that are being provided, you could be prompted multiple times.  Can you try running your operation with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and attaching the output as a text file here, after removing the contents of any `Authorization` headers beyond the `Basic` or other method name?

**Comment by brainlescoder** [comment]
ok, I'll try that 
thankyou for your time man...
