### ISSUE TITLE
Allow unrestricted pruning

### ISSUE THREAD

**Issue by Pierre-Bartet** [git-lfs/git-lfs#4367]
The default git lfs prune is really restricted, as a result one often has to:

1. Find out what combinations of options are needed among:
    lfs.fetchrecentrefsdays
    lfs.fetchrecentremoterefs
    lfs.fetchrecentcommitsdays
    lfs.fetchrecentalways
    lfs.pruneoffsetdays

2. Deal with the fact that these options have no effect when used in .lfsconfig

3. Notice that the current checkout is never prune, so that the only solution is to create a dummy empty branch, prune, then come back to the original branch

Can a simple option be added to allow unrestricted pruning ?
By unrestricted, I mean without any heuristic (time, current checkout, ...), but keeping the current pushed / remote verification logic.

**Comment by bk2204** [comment]
Hey,

Yes, I think we could add such an option, probably something like `--force` to override those values.  I hope to have some time to look at this soon.

**Comment by Pierre-Bartet** [comment]
Nice!
I don't know any Go but I'll try to add some tests here https://github.com/git-lfs/git-lfs/tree/master/t if it helps when you make a pull request.
