### ISSUE TITLE
With xonsh shell, --include= doesn't fully work unless = is removed

### ISSUE THREAD

**Issue by maresb** [git-lfs/git-lfs#4372]
There seems to be a bad interaction between `xonsh` and `git-lfs-migrate`. I'm not sure on which side the problem is, so I'm opening an issue in both projects. (Apologies in advance to the innocent.)

**Describe the bug**

Running from within the xonsh shell, the following command works as expected:
```bash
git lfs migrate import --everything --include "*.txt"
```
This command fails to add any files to LFS (note the `=` after `--include`):
```bash
git lfs migrate import --everything --include="*.txt"
```

**To Reproduce**

On Ubuntu 20.04 with git 2.26.2 and git-lfs 2.13.2, in a xonsh 0.9.24 shell run the following commands:
```bash
mkdir lfs-migrate-test
cd lfs-migrate-test/
git init
echo "hi" > data.txt
git add data.txt
git commit -m "initial"
git lfs migrate import --everything --include="*.txt"
git lfs ls-files
```

The produced output is
```
[master (root-commit) c179352] initial
 1 file changed, 1 insertion(+)
 create mode 100644 data.txt
migrate: Sorting commits: ..., done.                                                                                                   
migrate: Rewriting commits: 100% (1/1), done.                                                                                          
  master	c179352fa45b356ba60f0ece741a48fef22b1b30 -> a15998703a84e9577aac1ce38f0b91542582f237
migrate: Updating refs: ..., done.                                                                                                     
migrate: checkout: ..., done.                                                         
```
Note that the output of `git lfs ls-files` is empty. Further inspection shows that the git history contains `.gitattributes` but no LFS files.

In contrast, running
```bash
cd ..
rm -rf lfs-migrate-test
mkdir lfs-migrate-test
cd lfs-migrate-test/
git init
echo "hi" > data.txt
git add data.txt
git commit -m "initial"
git lfs migrate import --everything --include "*.txt"
git lfs ls-files
```
produces the expected output of
```bash
Initialized empty Git repository in /home/mares/repos/lfs-migrate-test/.git/
[master (root-commit) ce20a7d] initial
 1 file changed, 1 insertion(+)
 create mode 100644 data.txt
migrate: Sorting commits: ..., done.                                                                                                   
migrate: Rewriting commits: 100% (1/1), done.                                                                                          
  master	ce20a7da34a60c6a6140dee20b630313d73c9817 -> b5a1c9b536448f8f5bde956d7af8971f5969d47c
migrate: Updating refs: ..., done.                                                                                                     
migrate: checkout: ..., done.                                                                                                          
98ea6e4f21 - data.txt
```
with `data.txt` being in the output of `git lfs ls-files`.

**Expected behavior**

I expect that `--include` should work properly with the `=`-sign, as per [the documentation](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn). By "work properly" I mean that in addition to managing the historical `.gitattributes` files, the matching files should be moved to the LFS store.

**System environment**

The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

```
$ git config -l
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Ben Mares
user.email=CENSORED
cola.spellcheck=false
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
diff.context=3
diff.tool=meld
difftool.nbdime.cmd=git-nbdifftool diff "$LOCAL" "$REMOTE" "$BASE"
difftool.prompt=false
mergetool.nbdime.cmd=git-nbmergetool merge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
mergetool.prompt=false
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
```

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

```
$ git lfs env
git-lfs/2.13.2 (GitHub; linux amd64; go 1.15.5)
git version 2.26.2

LocalWorkingDir=/home/mares/repos/lfs-migrate-test
LocalGitDir=/home/mares/repos/lfs-migrate-test/.git
LocalGitStorageDir=/home/mares/repos/lfs-migrate-test/.git
LocalMediaDir=/home/mares/repos/lfs-migrate-test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/mares/repos/lfs-migrate-test/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/mares/repos/lfs-migrate-test/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Since the `--include="*.txt"` option works as expected on other shells, like Bash, I wonder if xonsh is trying to expand the glob or otherwise mangling the option.

What do you get if you try:
```
$ echo --include="*.txt"
```

On Bash, that produces `--include=*.txt`; that's pretty much what I imagine the `git-lfs` command would see as well in place of the `echo`.

You might also try experimenting with a simpler command than `git-lfs` to see how command-line arguments get handled, for instance something along these lines (note that I tried this with Bash; I don't know if xonsh supports here-documents, but you could construct the little script another way too):
```
$ cat <<EOF >foo.sh
#!/bin/bash
echo $@
EOF
$ chmod 755 foo.sh
$ ./foo.sh abc --include="*.txt" '*.dat'
abc --include=*.txt *.bar
```

**Comment by maresb** [comment]
In xonsh,
```bash
$ echo --include="*.txt"
--include="*.txt"
```
Also, with `foo.sh` containing
```bash
#!/bin/bash
echo $@
echo $0
echo $1
echo $2
echo $3
```
I am getting in bash
```bash
$ ./foo.sh abc --include="*.txt" '*.dat'
abc --include=*.txt *.dat
./foo.sh
abc
--include=*.txt
*.dat
```
however xonsh produces
```bash
$ ./foo.sh abc --include="*.txt" '*.dat'
abc --include="*.txt" *.dat
./foo.sh
abc
--include="*.txt"
*.dat
```
#### Note how xonsh fails to strip the `"` around `*.txt`.

Thanks so much for the quick response! This looks very promising in terms of identifying the root of the problem. I'll cross-post to my xonsh issue to ask if this behavior is expected.

**Comment by maresb** [comment]
I have become convinced that this is an issue with xonsh, not git-lfs. Thanks so much for your help in diagnosing this problem!
