### ISSUE TITLE
How do I "fix" a missing lfs pattern, and rewrite history?

### ISSUE THREAD

**Issue by quicknir** [git-lfs/git-lfs#4376]
At some point I discovered that my git lfs repo was missing a pattern in the .gitattributes file I thought I added. As a result, for some time (a few months), a whole bunch of files were being tracked by normal git instead of git lfs, which was obviously quite bad. So, I'm now trying to fix the issue, retroactively as well so that this repo isn't jammed full of the historical tracking of these binary files in regular git.

So, the first step obviously is I made a commit where I added the missing pattern to .gitattributes. That fixes the problem in the present (or rather, it should?), but I want to fix the problem going back. So, now I do an interactive rebase and I bring back the commit that adds the pattern to .gitattributes to a point before any of the files have been added. When I kick off the interactive rebase, I eventually hit an error:

```
Could not apply 60eafe1e580... <commit name here>
Encountered 97961 file(s) that should have been pointers, but weren't:
<list of the problem files>
```

Clearly, my approach isn't working, which doesn't shock me since my mental model of git lfs is quite poor. Can you provide any suggestions on how I should proceed? Happy to provide more details.

**Comment by bk2204** [comment]
Hey,

The easiest way to fix this is to use the `git lfs migrate import` command (which has documentation as part of the man pages and help output).  That should help you rewrite the history effectively without needing to do a rebase like this.

**Comment by quicknir** [comment]
Thanks for the info!

**Comment by gladishd** [comment]
`git lfs track *`
`git lfs migrate import`
@bk2204 :)

**Comment by DWishR** [comment]
So, what is mentioned above by @gladishd is terrible. Even if you don't do the `track *` first! The `git lfs migrate import` command, without other options, moves _everything_ into lfs. Even without the track command first. Here is what you actually want:

```
git lfs track *.png *.otherbigthings
git lfs migrate import --fixup
```

**Comment by astaech** [comment]
If someone stumbles upon this, here's the correct way to do it:

```bash
git lfs migrate import --include="*.png,*.jpg,*.bin"
```

This command will:
- Add or update the `.gitattributes` file in the first commit of your tree
- Migrate all matching blobs to LFS by rewriting the entire commit history

**Comment by DWishR** [comment]
Thanks @astaech, presuming that works it only took 4 years and 4 tries to get it correct
