### ISSUE TITLE
Your push was rejected due to missing or corrupt local objects

### ISSUE THREAD

**Issue by piranha771** [git-lfs/git-lfs#4383]
**Describe the bug**
I get 

> Your push was rejected due to missing or corrupt local objects.

With certain files. Only these files are affected.

**To Reproduce**
1. Download the attached example folder wich will cause the behaviour
2. Create a repo. SVDTest as the root folder.
3. Do `git lfs install`

`LFS upload failed:cts:  56% (10/18), 979 KB | 0 B/s
  (missing) Assets/SVD/Interactive/CarSim/Models/Car06.mtl (1367a433847b4a2fdbc599d00eeaa80b3a92d9d57f5ada3679db559ca7249228)
  (missing) Assets/SVD/Interactive/CarSim/Models/Bike01.mtl (4411c3875e4f82054dd8ac938cd27e5105827b36aa803ee046e470265419a31e)
  (missing) Assets/SVD/Interactive/CarSim/Models/Truck01.obj (03a0fd02a332b0bfc144467fb525045da16250fe4b2f01341c9ca4982a62da66)
  (missing) Assets/SVD/Interactive/CarSim/Models/Tank01.obj (611b6cd919b208d59ef9b73741199f1b3054d5d46708b9d7cfbb4a6bc457dddc)
  (missing) Assets/SVD/Interactive/CarSim/Models/Bike01.obj (8f4742ae4b8c2fcd2bb8e380186a57941ecf3afc512b41224541692955d707c0)
  (missing) Assets/SVD/Interactive/CarSim/Models/Car06.obj (02eee64fbc932a384a6ce8cb45dbc5199b4bea7077076c767534885b2cb90b75)
  (missing) Assets/SVD/Interactive/CarSim/Models/Tank01.mtl (e618b3ce8e4ffc5dea5bf57bad5691329497827b5d5575405ff273bcc8b2b763)
  (missing) Assets/SVD/Interactive/CarSim/Models/Truck01.mtl (ee2b23c528ce0edd59150f5d749dcbba01da785b3e7f353f8b9f0dbeaf3e0db9)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: 'git config lfs.allowincompletepush true'`

**Expected behavior**
LFS will work

**System environment**
Windows 10 20H2
git version 2.27.0.windows.1
git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)

**Output of `git lfs env`**
`git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)
git version 2.27.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Users/Piranha/scoop/apps/git/2.27.0.windows.1/mingw64/libexec/git-core
GIT_INSTALL_ROOT=C:\Users\Piranha\scoop\apps\git\current
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"`

**Additional context**
Only these files are affected.
[SVDTest.zip](https://github.com/git-lfs/git-lfs/files/5875490/SVDTest.zip)

**Comment by bk2204** [comment]
Hey,

Thanks for writing in.  The reason you're seeing this is because those files are not large files, but Git LFS pointer files.  When you create a repository with them, you're asking Git LFS to refer to the objects specified in the pointer file rather than turning the pointer file into an LFS object.  As a result, you're getting an error because the large objects they point to don't exist.  You can verify this by viewing them with a text editor.

You'd need to find the LFS objects that they point to in order to push.
