### ISSUE TITLE
Does locking applies to all remotes?

### ISSUE THREAD

**Issue by roozbehid-ic** [git-lfs/git-lfs#4389]
I have a repo with some files with lock attributes.
I am wondering if I push to another remote repo other than "origin" does it also replicate locks in that repo too?

The reason is we have developers who want to still be able to push in their own branches for backup purposes, even if there are locks. I was thinking maybe having another remote for backup for them would help.

**Comment by chrisd8088** [comment]
Hey, thanks for the question!  I believe the answer is no, there's no replication of locks across remotes if you push to other remotes than the one where the lock was recorded.

The various Git LFS lock commands all take an optional `-r` (or `--remote`) [option](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-lock.1.ronn#options) which allows you to specify a remote other than the default.

In a little testing of my own, when I use `git lfs lock <file>` it's then listed only on my default remote by `git lfs locks`; if I try `git lfs locks -r <other-remote>` it's not there.  Which aligns with my understanding of how lock and unlock requests are handled.

Please do give it a try and if you run into difficulties, by all means open an issue describing the problem in detail -- and good luck!
