### ISSUE TITLE
gitconfig http proxy values should be honored for https traffic even if proxy url does not start with https

### ISSUE THREAD

**Issue by bhilton** [git-lfs/git-lfs#4392]
Currently, gitconfig http proxy values are only honored for https if the proxy url starts with https.

Code snippet from proxy.go:

```
if strings.HasPrefix(gitProxy, "https://") {
  httpsProxy = gitProxy
}
```

However, some corporate IT environments configure https proxies to use http:// URLs. Ideally, if an http proxy rule is defined for a given LFS url, it would be honored regardless of the protocol of that proxy URL.

For example, in .gitconfig:

[http "https://lfs.github.com"]
  proxy = http://hostname.domain.com:PORT

In this case, we are being explicit that the given proxy should be used for HTTPS traffic going to lfs.github.com. It shouldn't matter that the proxy URL starts with http://.

In lfshttp/proxy.go, I would suggest examining the target URL rather than the proxy URL to determine if httpsProxy should be set.

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I agree this probably wasn't intended to work this way and should be changed.  I will admit that I'm not excited about supporting more plain HTTP proxies, but I do think we should at least be compatible with what Git does.  I'll mark this accordingly.

**Comment by bhilton** [comment]
Thanks for the speedy resolution - very much appreciated!
