### ISSUE TITLE
Recover git lfs storage

### ISSUE THREAD

**Issue by yiqiangjizhang** [git-lfs/git-lfs#4393]
I started to use git lfs, but then I realized that there was a storage limit quota. Now I wanted to recover git lfs storage. I tried removing git lfs and deleting .gitattributes but it still shows in my account that I have half storage used out of 1 GB.

Is there any way to recover that space?

If I reinitalize the repo, I would like to maintain my commits history. How can I do that?

Thank you all for the support!

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You don't mention which LFS service you're working with, but I would suggest reaching out to their support teams to provide more detailed steps in terms of recovering your
storage space.  For instance, GitHub's help documentation [suggests](https://docs.github.com/en/github/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository) deleting the repository and re-creating it, although that of course would eliminate any pull request history.

**Comment by yiqiangjizhang** [comment]
Thanks @chrisd8088. Yeah, I finally reached out github support and they reset my git lfs storage. I used `rm -rf .git` and reinitialized everything and push to the server. I lost history commits but my last commit was saved.

**Comment by chrisd8088** [comment]
OK, good to hear they were able to help.  I'm going to close this issue then, but feel free to open another if you bump into a problem with the LFS client.
