### ISSUE TITLE
How to download a file during pip installation?

### ISSUE THREAD

**Issue by soerendip** [git-lfs/git-lfs#4397]
I wonder how I can access the files stored in git-lfs other than using git. Is there a URL that I can use with the browser and how can I download that file during the installation process with pip? I did not find any explanations regarding this. Any pointers are very appreciated.

**Comment by bk2204** [comment]
Hey,

Some hosting sites may have a URL that you can use, but it depends on the site.  There's not a standard way way to access raw files other than speaking the protocol, which is documented in `docs/api`.  If the site you're using has an archive endpoint and LFS is enabled, you could use that as well.  And finally, you could also host the large file elsewhere (e.g., on a CDN) and pull them from there.
