### ISSUE TITLE
git LFS locking - repo with no LFS files does not set lockable files permissions as read only 

### ISSUE THREAD

**Issue by UKAlberto** [git-lfs/git-lfs#4400]
**Describe the bug**
When checking out a repository with a single lockable file (non LFS) the file is checkout as writeable when it is expected to be read only
**To Reproduce**
1. Create an empty repository 
2. In the repository, create the text file "mifile.txt" 
3. In the repository, create the  file ".gitattributes" 
4. Edit .gitattributes and add the line "mifile.txt lockable"
5. Save .gitattributes
6. Commit both file.
7. Checkout the repository from windows 
8. Check the permission of "mifile.txt"
9. Error: file is writeable

**Expected behaviuor**
File is expected to be READ ONLY being a "lockable" file, regardless of an LFS file present in the repository
If we add an LFS file to the repo, track it as LFS and commit the changes the file permissions start to work correctly but as soon as the LFs file is removed the checkouts of the repo are always with the lockable file as writeable

**System environment**
Windows 10 pro, using bash script

GIT:
git version 2.30.0.windows.2
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)

**Output of `git lfs env`**
$ git lfs env
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
git version 2.30.0.windows.2

Endpoint=https://-----------/pct/project-control-tooling.git/info/lfs (auth=none)
 SSH=git@------------:pct/project-control-tooling.git
LocalWorkingDir=C:\Users\amedina.fs\PE-977\project-control-tooling
LocalGitDir=C:\Users\amedina.fs\PE-977\project-control-tooling\.git
LocalGitStorageDir=C:\Users\amedina.fs\PE-977\project-control-tooling\.git
LocalMediaDir=C:\Users\amedina.fs\PE-977\project-control-tooling\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\amedina.fs\PE-977\project-control-tooling\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\amedina.fs\PE-977\project-control-tooling\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by UKAlberto** [comment]
![git_config](https://user-images.githubusercontent.com/79207430/108345775-9021b400-71d6-11eb-9071-a53a89f49add.png)

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  This sounds quite similar to #3555 and #3830, where @bk2204 [commented](https://github.com/git-lfs/git-lfs/issues/3830#issuecomment-534172129):

> I think this is an artifact of how clones without large files work.  Git LFS needs to install some hooks in order to make files read only.  It does this whenever it's invoked.  However, if your repository contains no large files, Git LFS isn't invoked by Git during the checkout process and therefore no hooks are installed.  This is a limitation of how Git LFS works with Git and can't really be avoided.
>
> There are a couple of workarounds that you can try:
>
> - Use `git lfs clone` instead of `git clone`.
> - Run `git init` and `git lfs install`, and then add a remote and pull.
> - Use a global set of hooks with `core.hooksPath`.

So I'm going to close this issue, but if this is actually different from those previous reports, please do re-open it and provide more detail on what is novel in this case.
