### ISSUE TITLE
git lfs prune calls external diff tools ang hangs

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#4401]
**Describe the bug**

We found out that `git lfs prune -d -v` started to hang on one of our Windows boxes. Analysis showed that:

1. There's main `git lfs prune -d -v` process
2. There's a child process: `git -c filter.lfs.smudge= -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.required=false log --branches --tags --not --remotes=origin -G "oid sha256:" -p -U12 "--format=lfs-commit-sha: %H %P"`
3. There's a subchild process: `"C:\Program Files\Git\mingw64\bin\antiword.exe" -m UTF-8 C:\Users\CUCUMB~1.ONL\AppData\Local\Temp\2/LM9YyF_classes_No_Name.dot`

It turns out that `git log -G` command runs external diff tools. [AntiWord is set up to diff `*.dot` files in Git for Windows](https://github.com/git-for-windows/build-extra/blob/git-sdk-1.0.8/git-extra/astextplain#L15). But if you pass it something that is not a Word file, AntiWord logs to stderr: `C:\Users\MEA71~1.RAD\AppData\Local\Temp/EJNcO8_1.dot is not a Word Document.`

Now, the **final and most important piece** of this problem is [parseScannerLogOutput](https://github.com/git-lfs/git-lfs/blob/v2.13.2/lfs/gitscanner_log.go#L122-L144) function that doesn't properly read subprocess stderr and is able to deadlock if `git log` process writes enough data to stderr and blocks on I/O buffer availability.

**Almost a way to reproduce**

I'm not yet sure how to fully reproduce this within a `git lfs prune` context, but can clearly see that `git log` invoked in the same way DOES write to stderr. Within a Git Bash:

```
$ mkdir foo
$ cd foo/
$ git init
$ echo "I cho?" > 1.dot
$ git add 1.dot 
$ git commit -am "initial"
$ git log --branches --tags --not -G "cho" -p -U12 "--format=lfs-commit-sha: %H %P"
C:\Users\MEA71~1.RAD\AppData\Local\Temp/EJNcO8_1.dot is not a Word Document.
```

**Expected behavior**

At least, `git lfs prune` is not supposed to hang. So, [parseScannerLogOutput](https://github.com/git-lfs/git-lfs/blob/v2.13.2/lfs/gitscanner_log.go#L122-L144) needs to be fixed to properly consume both stdout/stderr. Second, I'm not sure whether it is correct that `git lfs prune` invokes `git log` in such a way that it involves external diff tools, possibly this is a bug too. Third, I'm not sure whether it is correct that Git for Windows writes to stderr when one does `git log -G` and its output happens to include `*.dot` files.

**System environment**

```
$ git --version
git version 2.26.0.windows.1

$ git lfs version
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
```

**Output of `git lfs env`**

```
$ git lfs env
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.0.windows.1
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=C:\lfs-cache\objects
LocalReferenceDirs=
TempDir=C:\lfs-cache\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\lfs-cache
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I haven't attempted to reproduce, but I agree that this sounds like it would be an undesirable thing to have happen.  I'll try to reproduce either today or early next week and then see if I can come up with a fix.

**Comment by slonopotamus** [comment]
It looks like that in order to trigger the hang recent repo history needs to contain enough `*.dot` files so that AntiWord would fill up stderr buffer.

**Comment by slonopotamus** [comment]
Here's the repro:

1. Windows
2. Git Bash
3. Run these commands
```
$ mkdir foo
$ cd foo/
$ git init
$ for n in {1..1000}; do (echo $n > $n.dot) done
$ git add .
$ git commit -am "initial"
$ git lfs prune # Hangs, in processes you can observer AntiWord.exe
```

**Comment by bk2204** [comment]
My guess is that adding `--no-ext-diff` is going to fix this, but I haven't looked yet.

**Comment by bk2204** [comment]
I can reproduce this problem on Linux with the following script (and antiword):

```
#!/bin/sh -e

REPO=xyzzy

rm -fr "$REPO"
git init "$REPO"
cd "$REPO"

git config diff.word.textconv 'f() { antiword -m "UTF-8" "$@" || cat "$@"; };f'
echo "*.dot diff=word" >.git/info/attributes

for n in $(seq 1000); do (echo "$n" > "$n.dot") done
git add .
git commit -am "initial"
git lfs prune
```

Adding `--no-ext-diff` and `--no-textconv` fixes it.  Patch incoming shortly.

**Comment by slonopotamus** [comment]
If you're gonna make a test for this, AntiWord can be replaced by anything that writes to stderr, I think. Like, `echo 'brrrrrr" >&2`

**Comment by bk2204** [comment]
It also fails if the `textconv` process returns nonzero, so that's what I'm implementing in the test.  The goal is that we don't want to invoke these processes at all, not just that we don't want to fail if stderr gets full.
