### ISSUE TITLE
Fail to push lfs files to SSL git server

### ISSUE THREAD

**Issue by Scorpio86** [git-lfs/git-lfs#4405]
**Describe the issue**
We met similar issue with https://github.com/git-lfs/git-lfs/issues/3698.
When try to push lfs files to SSL server, the url which server telling to put objects is incorrect, it starts with http, instead of https.

push command : git lfs push --all origin

**System environment**
gerrit version : 2.16.7
git-lfs/2.12.0 (GitHub; linux amd64; go 1.14.7; git dad7b9e6)
git version 2.28.0

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  The URL which the server directs the client to use is up to the server and isn't controllable by the client.  Which server are you using?  You should be able to configure it to use the proper scheme so a redirect isn't necessary.

**Comment by Scorpio86** [comment]
Hi,

Thank you for reply.
Could you tell me how to config SSL redirect with lfs? Maybe it need to be configed on server.

**Comment by bk2204** [comment]
You haven't mentioned which server you're using, so it's hard for me to say.  The only server I can speak authoritatively on is the git-lfs/lfs-test-server repository; otherwise, you'll need to to consult the documentation for the software you're using or ask the authors.

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back from you on this, I'm going to close this issue.
