### ISSUE TITLE
Question about adding LFS support without doing an LFS migration

### ISSUE THREAD

**Issue by windwalker78** [git-lfs/git-lfs#4414]
Hello,

   We are using submodules for some of our projects and we need to enable LFS on them. Doing an lfs migration is not an option, because we want to preserve our commit ids. I would like to know the experts' opinions, on whether it is possible to simply enable lfs filter (i.e. git lfs track "*.png") for certain filetypes, having in mind some of them are already blobs in the git repository? What could possible go wrong when merging, checking out old commits with "png" as blob files in them and etc. 

Regards

**Comment by bk2204** [comment]
Hey,

Yes, you can do this with `git lfs import --no-rewrite`, or simply with the combination of `git lfs track` and `git add --renormalize .`  Note that you do need the `git add --renormalize .` or you'll end up with perpetually modified files.

If you're doing a merge and the file has changed on both sides, then you'll get a conflict, but then again, you would have gotten one anyway (if they were plain blobs).  Otherwise, merges should work fine, as should checking out old commits.  Git will do the right thing in both cases.

**Comment by windwalker78** [comment]
Hi, Brian,

Thank you very much for the quick and helpful feedback! I wanted to ask four Yes/No questions :)
1. Will this command migrate all existing commits:
`git lfs import --everyting --no-rewrite -m "LFS migration commit" --include="*.png,*.jpg"`  
2. From what I understand, there will be one new commit called  "LFS migration commit", which will hold all LFS objects, passed in the include parameter, right?
3. Will the png and jpg blobs be removed from the git repo, so ".git/objects" folder is reduced size?
4. If we go for the other option you suggested:
`git lfs track "*.png"`
`git lfs track "*.jpg"`
`git add --renormalize .`
Should we do the `git add --renormalize .` command for each branch as well?

Kind regards

**Comment by bk2204** [comment]
1. `git lfs migrate import --no-rewrite` specifies only files, not wildcards.  It also affects only the current branch.  You probably want to read the manual page to understand how it works and how it should be invoked.
2. You need to do all three commands for each branch you want to affect.  You don't need to modify any branch you don't want to change, though.
3. No.  Any large files stored as Git blobs in the history (and not LFS files) will remain in the history, but new PNG and JPEG files will be added as LFS objects instead.  Removing objects as Git blobs requires rewriting the history.

**Comment by windwalker78** [comment]
Thank you very much, for the good explanations!
