### ISSUE TITLE
git lfs pull --exclude="" ambiguous behavior 

### ISSUE THREAD

**Issue by Ragnoroct** [git-lfs/git-lfs#4425]
Some of my lfs files are ignored through the `.lsconfig`
```
[lfs]
    fetchexclude = "my/path/to/large/files/*"
```

I know that `--exclude=""` overrides the config and downloads those files. This is what I want for CI and production builds.

Initially I thought that `--exclude` would recursively join with the file config, not override it. It was kind of unclear and took a while to figure out. 

I'm also afraid that eventually someone might ask them to be applied together and then production builds will be missing important binaries.

**Comment by Ragnoroct** [comment]
`git lfs fetch --all` is also not what I want since it downloads everything not just the current commit files.

**Comment by bk2204** [comment]
Hey,

This is definitely an intentional behavior.  We do intentionally have the command-line arguments override the configured setting specifically so you can do things like this.  Otherwise, there'd be no way to pull down those files at all, which would make the feature rather useless.
