### ISSUE TITLE
Possibility to have "git lfs install" include a pre-commit hook to automatically pass binary files through lfs?

### ISSUE THREAD

**Issue by jerkstorecaller** [git-lfs/git-lfs#4431]
It's error-prone to write lfs filters based on a file pattern. 

Extensions are only meaningful for popular file types, I've personally seen extensions in the same project that were for binary files from a design tool, and also text project files for a coding tool. Also binaries on Linux don't even have extensions, so then we're adding /path/to/binary/file manually.

Why not have lfs provide a setting like "automatically detect binary files and track them: true/false"? Then the precommit hook would check newly-added files, and if they're binary automatically track them. 

If that's complicated, then even this is an improvement:  a setting to "automatically untracked detect binary files and reject commit". Precommit hook detects binary files, sees they're not tracked by any of the lfs filters, and aborts the commit with the message "File /path/to/xyz is an untracked binary file. Add it to git-lfs first.".

I don't know how easy binary/ascii detection is in Go, but from bash, this one-liner detects binary files (and I'm sure there's an easier way):
`find . -type f | perl -lne 'print if -B'`
 
Since it's a  major change, it can be optional.  But IMO, it should be the default, or at least heavily advertised in the README.

(P.S. I know precommit.com has a "check for large files" hook, that doesn't help if someone is committing 100Kb binary files over and over)

**Comment by jerkstorecaller** [comment]
Could you please give me an example of binary files people would want in their git repo? 

I'm relatively new to git, coming from svn which has no issues with large binary files. During my repo's migration I ran a script to detect every binary file, and added it to git-lfs's --include filter (by file extension where it made sense, and by filepath if the file had no extension). 

I thought I was doing what every git-lfs user would be doing.

**Comment by bk2204** [comment]
Sure, I can give you some examples.  One thing I store in some of my repos are test binary OpenPGP keys or test DER certificates which are just tracked in the repo.  I've also worked on repos that had small (2 MB) Git repositories embedded for testing.

In both of these cases, the files are relatively small and don't change frequently, so bloating the repository isn't really a concern.  The problem tends to come when you have very large files, compressed files, or moderately sized files (e.g., images) that change frequently, not specifically binary files.  For example, some users have giant YAML files that are a good fit for Git LFS, even though they are text files.

What you've done isn't necessarily bad, but it's also not required.
