### ISSUE TITLE
Failure to clone project using GitHub Desktop/lfs

### ISSUE THREAD

**Issue by jtse321** [git-lfs/git-lfs#4443]
Repository fails to clone every time I try. Files all make it to the destination, but the repository is not created locally.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

Using Windows 10 and the most recent version of github desktop. This is the error message I get when trying to clone:
```
Cloning into 'D:\585Project\Moba_fix\MOBA\MOBA'...
remote: Enumerating objects: 205, done.        
remote: Counting objects: 100% (205/205), done.        
remote: Compressing objects: 100% (167/167), done.        
remote: Total 205 (delta 28), reused 203 (delta 26), pack-reused 0        
Receiving objects: 100% (205/205), 7.64 MiB | 47.15 MiB/s, done.
Resolving deltas: 100% (28/28), done.
Downloading Content/Geometry/Meshes/1M_Cube.uasset (75 KB)
Error downloading object: Content/Geometry/Meshes/1M_Cube.uasset (349245b): Smudge error: Error downloading Content/Geometry/Meshes/1M_Cube.uasset (349245bef4ee3ebbf1922aabdaf5a098a7f26f0625d48f3dfcaeb3bb2e650415): [349245bef4ee3ebbf1922aabdaf5a098a7f26f0625d48f3dfcaeb3bb2e650415] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to D:\585Project\Moba_fix\MOBA\MOBA\.git\lfs\logs\20210316T151926.551392.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/Geometry/Meshes/1M_Cube.uasset: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Would you like to retry cloning ?
```

`C:\Users\Justin>git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
user.email=jtse321@users.noreply.github.com
user.name=Justin Tse
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true`

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

`C:\Users\Justin>git lfs env
git-lfs/2.9.1 (GitHub; windows amd64; go 1.12.7; git 7b479cc8)
git version 2.24.1.windows.2

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"`

**Comment by bk2204** [comment]
Hey,

The error message above says this: `Object does not exist on the server: [404] Object does not exist on the server`.  That means exactly that: the LFS object you requested doesn't exist, probably because nobody uploaded it.  If you know who committed that change, you could ask them to do `git lfs push --all` to upload it.  Otherwise, that revision isn't going to be able to be checked out with LFS because the file can't be found.

Normally Git LFS will push objects if the hooks are correctly installed, but sometimes people bypass them or don't have Git LFS correctly configured (e.g., haven't run `git lfs install`) and therefore sometimes things like this happen.
