### ISSUE TITLE
I upload a file with 244 MB but this not work

### ISSUE THREAD

**Issue by louzeiro** [git-lfs/git-lfs#4447]
Hello guys, I have a file with the weights of a neural network with 244 MB. I sent this file to my github using GIT LFS, but when I try to load it on a colab notebook this file comes with only 104 KB. I'm new to git, I need help.
thank you for your help

**Comment by ilya-kozyr-gismart** [comment]
Do you have git lfs installed on the notebook where you have an issue?

**Comment by louzeiro** [comment]
Thank you for responding.
No, in my notebook colab did not install git lfs, I just try to access the file with:
  wget file.weights

So, this is the issue?

**Comment by louzeiro** [comment]
> Do you have git lfs installed on the notebook where you have an issue?

Thank you for responding.
No, in my notebook colab did not install git lfs, I just try to access the file of my github with:
wget file.weights

So, this is the issue?

**Comment by ilya-kozyr-gismart** [comment]
Probably yes. In the github repo there is only text file, pointed to the file in the gitlab lfs storage. Not sure it will be easy to obtain file directly from the github lfs storage.

**Comment by louzeiro** [comment]
> Probably yes. In the github repo there is only text file, pointed to the file in the gitlab lfs storage. Not sure it will be easy to obtain file directly from the github lfs storage.

Got it, thanks

**Comment by bk2204** [comment]
Hey,

It sounds like you don't have Git LFS installed on Google Colab.  Have you tried installing it before checking out your notebook?  If not, you can probably do `sudo apt-get update && sudo apt-get -y install git-lfs` before and things should work.

**Comment by minhduc19** [comment]
> Hey,
> 
> It sounds like you don't have Git LFS installed on Google Colab. Have you tried installing it before checking out your notebook? If not, you can probably do `sudo apt-get update && sudo apt-get -y install git-lfs` before and things should work.

thanks

**Comment by bk2204** [comment]
Hey, since we haven't seen a response here, I'm going to close this.
