### ISSUE TITLE
*Question*: Command to list files that are unsmudged

### ISSUE THREAD

**Issue by samaursa** [git-lfs/git-lfs#4452]
I am wondering if there is a command that I can use to list the files that were left as pointers. This will be useful when I deliberately get certain files as pointers only and then later want to get the unsmudged version of those files.

Because there could be hundreds/thousands files like the above, I am looking for an automated way.

**Comment by bk2204** [comment]
Hey,

We don't have an automated tool for that, but unless you have things that are not pointer files but look very much like them, you could try this:

```
$ git ls-files -z | xargs -0 grep -l '^version https://git-lfs.github.com/spec/v1$'
```

That would list all the files with that line in them, which will almost certainly be only pointer files.  If you're on a system that doesn't support `-z` and `-0`, you can omit them, with somewhat less flexibility to handle names with unusual characters.

**Comment by samaursa** [comment]
Thanks @bk2204, I'll try that
