### ISSUE TITLE
Problem with sharing interactive plots on Github using git-lfs and Github-pages

### ISSUE THREAD

**Issue by RuneTheander** [git-lfs/git-lfs#4456]
hey people,

I have created an interactive map using folium and exported the map from python to a .html file on my desktop.
Clicking the .html file on my desktop opens a brower window on my computer with the interactive map, as expected.

The problem is when i uploade the .html file to github using git lfs, 
and then open the .html file using the link (https://runetheander.github.io/Maps/map.html) from github pages  the browser loads the pointer file from git lfs and not the map as it did on my desktop.

<img width="937" alt="Skærmbillede 2021-03-29 kl  20 26 21" src="https://user-images.githubusercontent.com/77341464/112882296-0f0ae600-90cd-11eb-88e4-f1241df1ceee.png">

My procedure for uploading the .html file  to my Github repository is to first create a new GitHub repository, then clone the github repository to my local dekstop using Github desktop application.
Then i access the repository with the terminal and write the commands..: 

1. git lfs install

2. git lfs track "*.html"

3. git add .gitattributes

4. git add file.html

5. git commit -m "map"

6. git push origin main

When i go back to the repository on GitHub the file is uploaded and it says the uploaded file have the same size as it have on my computer.  Here is a link to my repository https://github.com/RuneTheander/Maps
but when i access the html file using the link from github-pages it's show's the pointer file. 

What am i doing wrong here ? does anyone have a procedure for uploading the .html fil so i can render it using the link from githubpages ?.  

Using drag and drop to the repository works fine, i have uploaded a map with a smaller size to the page and it renderes from the link fine (https://runetheander.github.io/Maps/test_map.html).

Cheers Rune Theander

**Comment by bk2204** [comment]
Hey,

This isn't really a problem with Git LFS, but it's a common situation when the software you're using (in this case, GitHub Pages) doesn't have Git LFS installed.  In this case, that's because GitHub Pages doesn't support LFS, and last I checked, didn't plan to (although plans could have changed).

Since this is an issue with GitHub and not the open source Git LFS client, if you have questions or feedback about it, please contact GitHub Support.

**Comment by RuneTheander** [comment]
bk2204 thanks for the quick answer !
