### ISSUE TITLE
lfs version for gerrit 2.16.7

### ISSUE THREAD

**Issue by Scorpio86** [git-lfs/git-lfs#4459]
This is not an issue, just query.

I want to install lfs plugin with gerrit 2.16.7, is there any relationship between lfs version and gerrit version?
Please suggest what the lfs version is for gerrit 2.16.7, if there is.

Thank you.

**Comment by bk2204** [comment]
Hey,

We don't maintain the LFS plugin for Gerrit, so I don't know what version it requires.  The command-line interface and the interaction with Git have not changed much over the years, so it's likely that whatever version you have will work fine.

However, it looks like the LFS plugin for Gerrit is actually a server-side component and just implements the LFS API, and if that's the case, it may not require a version of Git LFS at all.  Many providers do offer Git LFS support without using Git LFS at all.

Hopefully that's at least somewhat useful for you, and sorry I couldn't be of more help.

**Comment by Scorpio86** [comment]
> Hey,
> 
> We don't maintain the LFS plugin for Gerrit, so I don't know what version it requires. The command-line interface and the interaction with Git have not changed much over the years, so it's likely that whatever version you have will work fine.
> 
> However, it looks like the LFS plugin for Gerrit is actually a server-side component and just implements the LFS API, and if that's the case, it may not require a version of Git LFS at all. Many providers do offer Git LFS support without using Git LFS at all.
> 
> Hopefully that's at least somewhat useful for you, and sorry I couldn't be of more help.

Thank you for the kindly explaination. I will query to LFS plugin.
