### ISSUE TITLE
Can't push even after git lfs track *filename*

### ISSUE THREAD

**Issue by vidarsumo** [git-lfs/git-lfs#4462]
I'm using git lfs for the first time. I followed the instruction on the lfs website. This is what I did:

git lfs track 01_data_clean/data_clean.csv
git add .gitattributes
git add 01_data_clean/data_clean.csv

When I try to push I get this error:
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 615f664588f877ac8b775e90ba05a936ab58f45324db0a64bb31c8ab5da1a888
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File 01_data_clean/data_clean.csv is 258.34 MB; this exceeds GitHub's file size limit of 100.00 MB

If I check which files are being tracked, this file is in the list:

$ git lfs ls-files
```
882deadb11 * 01_data_clean/data_clean.csv
76015fa2ec * 02_models/catboost_top50_30032021.rds
15b66d996e * 02_models/glmnet_top50_30032021.rds
2507318f81 * 02_models/mars_top50_30032021.rds
8373098427 * 02_models/prophet_boost_top50_30032021.rds
cbe2a1cb3f * 02_models/svmrbf_top50_30032021.rds
606c9d955f * 02_models/xgboost_top50_30032021.rds
```

Is there anything I did wrong? I'm not sure how to solve this.

**Comment by bk2204** [comment]
Hey,

Can you include the output of `git lfs env` as requested in the issue template?  Also, it would be helpful to know if this file existed in the repository before you ran `git lfs track`.

**Comment by vidarsumo** [comment]
Yes sorry about that, here it is.
(I removed the name of the company I'm working for to **company_name**)

The file existed in the local repository before I ran git lfs track.

```
$ git lfs env
git-lfs/2.13.1 (GitHub; windows amd64; go 1.14.12; git e896fc7a)
git version 2.30.0.windows.1

Endpoint=https://github.com/vidarsumo/company_name.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\vidar\Documents\Rwd\company_name
LocalGitDir=C:\Users\vidar\Documents\Rwd\company_name\.git
LocalGitStorageDir=C:\Users\vidar\Documents\Rwd\company_name\.git
LocalMediaDir=C:\Users\vidar\Documents\Rwd\company_name\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\vidar\Documents\Rwd\company_name\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\vidar\Documents\Rwd\company_name\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

**Comment by bk2204** [comment]
Okay, thanks this is helpful.

The problem is that your file existed in the repository before you ran `git lfs track`, and that file is larger than 100 MB, which is GitHub's limit.  Running `git lfs track` doesn't rewrite existing history to remove large files.  For that, you'll need to use `git lfs migrate import` (see [the manual page](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.1.ronn#migrate-local-history)) to remove the large files from your history and be able to upload.
