### ISSUE TITLE
i/o timeout only happened to certain large models

### ISSUE THREAD

**Issue by jcwchen** [git-lfs/git-lfs#4470]
**Describe the issue**
I saw there are quite a few issues related to i/o timeout, but I could not find a concrete solution... All of the answers point it to "network issue". In my case, I can successfully `git lfs push` smaller models (10MB - 400MB), yet it keeps failing with a larger one (634MB)... I did use GIT_TRACE=1 to check detailed message, but they are not helpful. `git lfs push` will keep retrying to upload the model and fail in the end. Although we have tested it in 5 different machines and network, we still bumped into the same timeout error by uploading the same model.

Short error message is as follows:
```
16:29:46.878324 trace git-lfs: tq: refusing to retry "12fbb1ec2d2d70c8ebd21a290a348a4109447b98582af64c6f93b6526d5c8f35", too many retries (8)
LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/158171734/12/fb/12fbb1ec2d2d70c8ebd21a290a348a4109447b98582af64c6f93b6526d5c8f35?actor_id=14194980&key_id=0&repo_id=296404643": read tcp 192.168.1.7:57722->52.217.85.188:443: i/o timeout
```

The full log is here: 
[log.txt](https://github.com/git-lfs/git-lfs/files/6282255/log.txt)

We spent much time on this, but we still cannot find a way to solve it... Is it also caused by "network issue"? Is there anything we can do to git lfs push this large file successfully? Thank you for your assistance!

**System environment**
Windows 10 with git-lfs 2.11.0 or 2.13.2

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
16:38:36.276065 exec-cmd.c:237          trace: resolved executable dir: C:/Users/jacky/Desktop/cmder/vendor/git-for-windows/mingw64/bin
16:38:36.278101 git.c:704               trace: exec: git-lfs env
16:38:36.278101 run-command.c:663       trace: run_command: git-lfs env
16:38:36.555146 trace git-lfs: exec: git 'version'
git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)
git version 2.28.0.windows.1

16:38:36.637675 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
16:38:36.969012 trace git-lfs: exec: git 'config' '-l'
16:38:37.006998 trace git-lfs: exec: git 'config' '-l' '-f' 'D:\github\models\.lfsconfig'
Endpoint=https://github.com/jcwchen/models.git/info/lfs (auth=basic)
Endpoint (upstream)=https://github.com/onnx/models.git/info/lfs (auth=none)
LocalWorkingDir=D:\github\models
LocalGitDir=D:\github\models\.git
LocalGitStorageDir=D:\github\models\.git
LocalMediaDir=D:\github\models\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\github\models\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\github\models\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
FetchExclude=*
GIT_EXEC_PATH=C:/Users/jacky/Desktop/cmder/vendor/git-for-windows/mingw64/libexec/git-core
GIT_INSTALL_ROOT=C:\Users\jacky\Desktop\cmder\vendor\git-for-windows
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_TRACE=1
GIT_VERSION_USER=2.18.0.windows.1
GIT_VERSION_VENDORED=2.28.0.windows.1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
16:38:37.051982 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
16:38:37.051982 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
16:38:37.051982 trace git-lfs: filepathfilter: accepting "tmp"
```

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This is almost certainly some sort of network issue.  The S3 bucket that GitHub currently uses for LFS files may not be located conveniently to you on the network, which may be why you're seeing this.  You can try adjusting `lfs.activitytimeout` to a higher value to see if that can help you upload the larger objects.  The default is 30 seconds, so you could try setting it to 60 or 120 to see if that will make things work for you.

Other than that, I'd suggest contacting your network admin or ISP to see if they can help you troubleshoot the problem.
