### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by SinEstresOrrantia** [git-lfs/git-lfs#4474]
Thanks everyone who contribute these for us beginners![image_c78b0127-e959-465f-b8bc-168b81b0e86620210406_142413.jpg](https://user-images.githubusercontent.com/78077841/114285743-90e10480-9a27-11eb-8efe-9b303e3de3f5.jpg)

**Comment by chrisd8088** [comment]
The sentiment is lovely, but as there's no description of a bug or other issue here, I'm going to close this.
