### ISSUE TITLE
Procedure to back up a git repo that uses git-lfs?

### ISSUE THREAD

**Issue by jerkstorecaller** [git-lfs/git-lfs#4477]
I'm setting up a weekly backup script for my repos, just in case. My goal is to avoid losing my git history if something happens, like if my repo or account is suspended. I'd like to be able to easily move my data to another host if this happens.

With pure git, doing a full backup is as simple as cloning the repo. That gives a full snapshot of the repo which I could upload to any other remote/host.

git-lfs changes the equation. As I understand it, a clone will only download some lfs files (the "current" ones, so likely the files referenced in the head of master I just checked out) in order to provide the best performance.

What command could I run so that all files in git lfs are downloaded when I'm doing my backup? From reading the doc, I believe I can use ```git lfs migrate export --everything``` to turn my local clone into a plain git repo, but is this the right way? Or is there an approach that would preserve the existing git-lfs metadata/configuration/whatever, ready to be uploaded to a new provider that supports git-lfs?

**Comment by bk2204** [comment]
Hey,

There's a pretty easy command for that: `git lfs fetch --all`.  That should download all of the objects for the repository and you can then push them to a new place with `git lfs push --all`.  That's what we recommend to folks who are switching providers, so it should work for a backup, too.
