### ISSUE TITLE
Custom data in body of the upload POST request

### ISSUE THREAD

**Issue by remkonoteboom** [git-lfs/git-lfs#4483]
I have a custom Git-LFS server (separate from the Git server) which ends up uploading the file to an AWS S3 repository.  However, I would like to be able to put multiple repositories in the same bucket (using "folders" as a namespace separator for each Git repository). 

Is it possible to send custom metadata through the POST request in the body?

I can see that there is body.operation and body.objects in the request body, but I can't find a mechanism whereby I can add, for example, my own "name" for the repository so that my handler can put the file in the appropriate spot in the LFS server.

**Comment by bk2204** [comment]
Hey,

No, it isn't possible to send custom metadata.

What you may wish to do instead is to serve a set of endpoints (e.g., `/<repo>/info/lfs`) with the LFS server and then use that to create custom signed upload or download URLs to different locations in the same bucket based on the `repo` portion of the URL.  This is very similar to how GitHub's implementation works, so it is a viable approach.

**Comment by remkonoteboom** [comment]
I thought I might have to do that.  However, you can only do this is you have complete control over parsing the URLs.  In my current case, I am using serverless implementation which has AWS lambda functions that are mapped to API Gateways.  In order to parse this, I would need to be able to tell AWS Gateway to ignore <repo> and map /objects/batch part of the url to the lamda function.  I am not sure if that is possible.

It would work if I could map a query string into the .lfsconfig file:

[remote "origin"]
    lfsurl = https://XYZ.execute-api.us-east-1.amazonaws.com/common?repo=my_repo

but, of course, LFS seems to append the "/objects/batch" at the end of the querystring.  (Maybe it should recognize that there a query string at the end of "lfsurl"?)

I will try to see if the AWS Gateway will allow more complex configuration of URLs or I will have to create a solution which can handle the entire URL programatically.







but that is effectively the same as

**Comment by remkonoteboom** [comment]
So, for those that are also trying to do something like this, you can configure an AWS API Gateway with a {proxy+} gateway.  Make sure that under the "Integration Request" section, you have "Use Lambda Proxy integration" selected.  This will allow your handler to have complete control of the request path and have AWS pass the complete path to your handler.

At this point, you can parse the path and retrieve the repo at the beginning of the URL and act accordingly.  This is cleaner than trying to put variables in query strings.
