### ISSUE TITLE
git lfs pull does now bring file content

### ISSUE THREAD

**Issue by sihnatse** [git-lfs/git-lfs#4495]
After merge conflicts, the pointer file has been modifies in a text editor and then `git lfs pull` does not replace it with actual file. It worked before.

1. Make a change in a file under lfs
2. `git pull`
3. Fix conflict in a text editor
4. `git lfs pull` and still pointer file. No any message in terminal.

A full large original file should be in place instead of tiny pointer file.

MacOS. Terminal. Vim. `git config -l` takes too much space. If you want it please specify what is needed specifically.

```
***:*** sergey$ git lfs env
git-lfs/2.12.1 (GitHub; darwin amd64; go 1.15.3; git 85b28e06)
git version 2.24.3 (Apple Git-128)

Endpoint=***.git/info/lfs (auth=basic)
LocalWorkingDir=***
LocalGitDir=***.git
LocalGitStorageDir=***.git
LocalMediaDir=***/.git/lfs/objects
LocalReferenceDirs=
TempDir=***/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=***/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

`***` replaces unnecessary information

**Comment by sihnatse** [comment]
@br2204 I don't understand you answer. The file is under git repository. By manually editing the pointer file I command explicitly which version is wanted. Of course, file will modified. The whole idea of version control is to keep track of modifications. Modification cannot be a reason for "because that could blow away the changes in your working directory". Note that I am talking about a file, not directory. Your argument is like: A car engine would not start because you may crash the car. - If I start engine I take full responsibility for whatever happens. Engine can't decide whether to start or not.

Let me state the problem another way. There is pointer file. A valid pointer file. `git lfs pull` needs to replace the pointer file with real content.

BTW, in your proposal there is a flaw - there is no content file. No content file on computer. None. That is the problem. I don't have a content file. And I need `git lfs pull` to bring it. All the information to do that it is known to `git lfs`.

**Comment by sihnatse** [comment]
@bk2204 Your explanation is based on internal implementation. It may use revision, tree, index, whatsoever. I don't really care and don't want the internal details. Sorry. The idea of fixing merge conflict is to make appropriate changes in a file and then `git add`. But I cannot fix conflict, because what I literary have is a pointer file. Either from current branch or from which the merge is requested. Before `git add` I need that large file. Large binary file that I can open and fix. It's uasset-file in Unreal Engine, if that matters. That real file I can modify in UE Editor, and then, having it correct, issue `git add`. 

From your answer I see that I can choose a pointer file either from current branch or from which the merge is requested. Note that none of them is correct.

Is there any command, per file maybe, to restore full large original content file?

**Comment by bk2204** [comment]
> @bk2204 Your explanation is based on internal implementation. It may use revision, tree, index, whatsoever. I don't really care and don't want the internal details. Sorry. The idea of fixing merge conflict is to make appropriate changes in a file and then `git add`. But I cannot fix conflict, because what I literary have is a pointer file. Either from current branch or from which the merge is requested. Before `git add` I need that large file. Large binary file that I can open and fix. It's uasset-file in Unreal Engine, if that matters. That real file I can modify in UE Editor, and then, having it correct, issue `git add`.

What you're looking for may be `git lfs fetch` followed by `git lfs checkout --to`, which is described in the manual page.

> Is there any command, per file maybe, to restore full large original content file?

If you want to turn an arbitrary pointer file into a large object, you can pipe it to `git lfs smudge`, but note that you shouldn't overwrite the file this way; that is, you should use a different file for writing the output than the input.
