### ISSUE TITLE
git lfs push --all does not push all objects

### ISSUE THREAD

**Issue by KBasener** [git-lfs/git-lfs#4497]
Hello everybody, 

appreciate the work you do on git-lfs. Currently i have discovered a strange behauvoir. I am not sure if this a missunderstanding on my side or maybe a bug. I am trying to bring git lfs from one server to another. 

I am cloning repo from original-server and doing afterwards
`git lfs fetch --all
fetch: 69 object(s) found, done.
fetch: Fetching all references...`

Afterwards i am adding the new server and try to push all the objects to the new server. 

`git lfs push --all newserver
Uploading LFS objects: 100% (8/8), 136 MB | 0 B/s, done.`

Apparently it only pushes the objects which are in ref of the current branch. 

If I am checking out an branch which has new objects and redoing the push command, i got additional objects. 

`git lfs push --all newserver
Uploading LFS objects: 100% (13/13), 147 MB | 1.0 MB/s, done.`

I have looked at the help from git lfs push and it says 

`* --all:
    This pushes all objects to the remote that are referenced by any commit
    reachable from the refs provided as arguments. If no refs are provided, then
    all refs are pushed.`
    
 For me this says my push would be a no ref push and in this case every ref should be pushed. Is there a missunderstanding on my side? Can someone help me with that?
 
 regards 
 
 Kai-Uwe Basener

**Comment by KBasener** [comment]
```
git lfs --version
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You might try with `GIT_TRACE=1 git lfs push --dry-run --all <remote>` to see what exactly is being pushed, as a starting point.

Would you also mind supplying the output of `git config -l` (with any private info redacted) and the full output of `git lfs env`?  

If there's a way to create a small reproduction test case, that would be lovely.

**Comment by KBasener** [comment]
` GIT_TRACE=1 git lfs push --all --dry-run newserver
10:02:47.187688 git.c:703               trace: exec: git-lfs push --all --dry-run newserver
10:02:47.187738 run-command.c:663       trace: run_command: git-lfs push --all --dry-run newserver
10:02:47.220422 trace git-lfs: exec: git 'version'
10:02:47.236009 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:02:47.239130 trace git-lfs: exec: git 'config' '-l'
10:02:47.241719 trace git-lfs: Upload refs [] to remote newserver
10:02:47.953581 trace git-lfs: run_command: ssh -p 7999 -- git@OLD_SERVER_BASE_URL git-lfs-authenticate wall/wallbox-modelling.git upload
10:02:48.425050 trace git-lfs: HTTP: POST https://OLD_SERVER_BASE_URL/scm/wall/wallbox-modelling.git/info/lfs/locks/verify
10:02:48.691451 trace git-lfs: HTTP: 200
10:02:48.691551 trace git-lfs: HTTP: {"ours":[],"theirs":[]}
10:02:48.693409 trace git-lfs: ssh cache: git@OLD_SERVER_BASE_URL git-lfs-authenticate wall/wallbox-modelling.git upload
10:02:48.693562 trace git-lfs: HTTP: POST https://OLD_SERVER_BASE_URL/scm/wall/wallbox-modelling.git/info/lfs/locks/verify
10:02:48.733830 trace git-lfs: HTTP: 200
10:02:48.733950 trace git-lfs: HTTP: {"ours":[],"theirs":[]}
10:02:48.734549 trace git-lfs: tq: running as batched queue, batch size of 100
10:02:48.734709 trace git-lfs: run_command: git rev-list --stdin --objects --do-walk --
push f1c79766c3b58ea817aa3bbe327616225b90aea1f8ca9e8ca8344cf5bac19921 => system-refactoring.eap
push 111ac1d9d9b74ed017976fbc67b405005194f12f742fe873c178a417c6ce49ce => system.eap
push 2236bef2346224dafc78d136fcdfe11eec9bdf4563fa59135c0359eafe3dcde1 => system.eap
push 252dbb1e9bdd7c96dd2c9b901ffb680406c6c7bf4f4dea6cacac050833ead4f1 => system.eap
push 1f80f70b7ff17f770859988a8395cd378628dcf11ef2821f28cab1e4ab1205df => system.eap
push 86d4ad22edf0c75e3954ca9b33304413fc623d9aceba3e11aefd4f90e8cb9d67 => system.eap
push b4532e0df88267ac189d6a7b6c7b6ec8585b215d661886b692ccfa03c327ffeb => system.eap
push 6c00047da69bde20b39226ac65b9fb589a376c88a3a884b19976dc25150f25a3 => system.eap
10:02:48.741410 trace git-lfs: tq: running as batched queue, batch size of 100
10:02:48.741571 trace git-lfs: run_command: git rev-list --stdin --objects --do-walk --
push 23c5b97b30734f17a827796bcb122353941678b53bc567d44705a77b97479941 => system.eap
push ed61f0a92c5f379671283d2b71af2b2366543301a041f3bb49c924c107989e45 => system.eap
push 184cb085c0e1147198f472895c2a0ffd73cb7314c7af287b39b4780b7ce3c5bd => system.eap
push 317ec09c09b92ce3ecba7eac67c85e9820ba465003bd45bec0110befd753ff55 => system.eap
push 1fc611f9d7b45479efcdad585d5f21e4ddf3d47cf281820a68af2236692181f8 => system.eap
10:02:48.747977 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
10:02:48.748014 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
10:02:48.748094 trace git-lfs: filepathfilter: accepting "tmp"
`

This is the commands which are used by git lfs push. It seems like the script is using git rev-list. Which only get the revision reachable by the parrent. Feature Branches which are not reachable will be not used to transfer objects, right?

**Comment by KBasener** [comment]
Git config -l 

`

git config -l | cat
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.email=MY_EMAIL
user.name=MY_USER
color.ui=auto
core.editor=vim
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=ssh://git@NEW_SERVER_BASE_URL:7999/wall/wallbox-modelling.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
remote.newserver.url=ssh://git@OLD_SERVER_BASE_URL:7999/wall/wallbox-modelling.git
remote.newserver.fetch=+refs/heads/*:refs/remotes/newserver/*
lfs.https://OLD_SERVER_BASE_URL/wall/wallbox-modelling.git/info/lfs.locksverify=true
branch.feature/P50031-98-aktualisierung-systemkontext.remote=origin
branch.feature/P50031-98-aktualisierung-systemkontext.merge=refs/heads/feature/P50031-98-aktualisierung-systemkontext`

**Comment by KBasener** [comment]
git lfs env 

` git lfs env
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.25.1

Endpoint=https://NEW_SERVER_BASE_URL/wall/wallbox-modelling.git/info/lfs (auth=none)
  SSH=git@NEW_SERVER_BASE_URL:wall/wallbox-modelling.git
Endpoint (newserver)=https://OLD_SERVER_BASE_URL/wall/wallbox-modelling.git/info/lfs (auth=none)
  SSH=git@OLD_SERVER_BASE_URL:wall/wallbox-modelling.git
LocalWorkingDir=/home/basen001/projects/migrationsscript/wallbox-modelling
LocalGitDir=/home/basen001/projects/migrationsscript/wallbox-modelling/.git
LocalGitStorageDir=/home/basen001/projects/migrationsscript/wallbox-modelling/.git
LocalMediaDir=/home/basen001/projects/migrationsscript/wallbox-modelling/.git/lfs/objects
LocalReferenceDirs=
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.email=MY_EMAIL
user.name=MY_USER
color.ui=auto
core.editor=vim
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=ssh://git@NEW_SERVER_BASE_URL:7999/wall/wallbox-modelling.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
remote.newserver.url=ssh://git@OLD_SERVER_BASE_URL:7999/wall/wallbox-modelling.git
remote.newserver.fetch=+refs/heads/*:refs/remotes/newserver/*
lfs.https://OLD_SERVER_BASE_URL/wall/wallbox-modelling.git/info/lfs.locksverify=true
branch.feature/P50031-98-aktualisierung-systemkontext.remote=origin
branch.feature/P50031-98-aktualisierung-systemkontext.merge=refs/heads/feature/P50031-98-aktualisierung-systemkontext
...skipping...
TempDir=/home/basen001/projects/migrationsscript/wallbox-modelling/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/basen001/projects/migrationsscript/wallbox-modelling/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`

**Comment by chrisd8088** [comment]
> It seems like the script is using git rev-list. Which only get the revision reachable by the parrent. Feature Branches which are not reachable will be not used to transfer objects, right?

I believe that's a secondary step in this case.  The `git rev-list` is run by [`revListShas()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/lfs/gitscanner_refs.go#L103-L106) for each "include" ref passed to [`https://github.com/git-lfs/git-lfs/blob/v2.9.2/lfs/gitscanner_refs.go#L46()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/lfs/gitscanner_refs.go#L46), which happens in [`ScanRefWithDeleted()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/lfs/gitscanner.go#L124-L128) where the "exclude" refs are set to `""`.  That's called in [`uploadLeftOrAll()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/commands/uploader.go#L53) from [`uploadForRefUpdates()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/commands/uploader.go#L39) for each ref to update; that's called in [`uploadsBetweenRefAndRemote()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/commands/command_push.go#L72) where the list of refs to update is derived by calling [`lfsPushRefs()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/commands/command_push.go#L66) which calls [`LocalRefs()`](https://github.com/git-lfs/git-lfs/blob/v2.9.2/commands/command_push.go#L109) which gets the list of local refs by [running](https://github.com/git-lfs/git-lfs/blob/v2.9.2/git/git.go#L351), in the case of Git LFS v2.9.2,  `git show-ref --heads --tags`.

More recent versions of Git LFS since #3876 which removed the `--heads` and `--tags` options to the `git show-ref` call.

You might try `git show-ref` versus `git show-ref --heads --tags` and see if there's a difference in the list of local (not remote) refs.  If there is, that might be the problem, and perhaps an update to a newer Git LFS version would help.

**Comment by KBasener** [comment]
Thanks again for your answer! 

This is quite interesting! 

I tried `git show-ref`. The result were all revisions from local and origin. The `git show-ref --heads --tags` filtered this output. Only the local heads were shown! The complete origin revisions were not shown. Your theory should be right! 
In this case my script could only see the default branch and not the other branches which are present on the origin!

I will try a newer Version of GIT LFS in the next days which therefore should work properly!

**Comment by chrisd8088** [comment]
As we haven't heard anything more on this issue, and it should be resolved in newer Git LFS versions, I'm going to close this issue.
