### ISSUE TITLE
Error I cannot push

### ISSUE THREAD

**Issue by gasilva** [git-lfs/git-lfs#4506]
**Describe the issue**
I cannot push files in to my repo

**System environment**
```
SUSE SLES 15.2

**Output of `git lfs env`**
git-lfs/2.10.0 (GitHub; linux amd64; go 1.14.2)
git version 2.26.2

Endpoint=https://github.com/gasilva/dataAndModelsCovid19.git/info/lfs (auth=basic)
LocalWorkingDir=/home/ats4i/Desktop/corona/dataAndModelsCovid19
LocalGitDir=/home/ats4i/Desktop/corona/dataAndModelsCovid19/.git
LocalGitStorageDir=/home/ats4i/Desktop/corona/dataAndModelsCovid19/.git
LocalMediaDir=/home/ats4i/Desktop/corona/dataAndModelsCovid19/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/ats4i/Desktop/corona/dataAndModelsCovid19/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/ats4i/Desktop/corona/dataAndModelsCovid19/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

```
LFS upload missing objects: (3697/3707), 2.2 GB | 0 B/s                                    
  (missing) countries/initialConditions_YaboxNew_v11.ipynb (f91f919ee5306f9cad8c4424c17a388fa4ec1b9e70fc0fddb695aac2e631225c)
  (missing) countries/countries_Covid19_v8.ipynb (87ed9f6316f0639645aae607f97c4c947b73025df5922845d226e21cbbbbbfe4)
  (missing) countries/.ipynb_checkpoints/initialConditions_YaboxNew_v11-checkpoint.ipynb (3e9b9e626f11d47937734f144445257b4d41b32d8c82df4e5850d7dbf9f96805)
  (missing) countries/Untitled.ipynb (62504664ffd1c378a1dc229514eca555f9b785fc6542ab9a5d4dca3e16916ed5)
  (missing) countries/.ipynb_checkpoints/countries_Covid19_v8-checkpoint.ipynb (4d2cbfc64508dd56b52a298ff2c50b1f0610a7ec38dcc76d8218031b33b87ed1)
  (missing) countries/covidPlots.ipynb (ca605ad1f09a82299bab583b72a4791d43d602edc4b13867ff270616d9bff365)
  (missing) countries/historyIC_v2.ipynb (025bf697a67bbde678bddbe8112cdb14e99977813d2f3b194af3c6306a659afc)
  (missing) countries/deadFitting.ipynb (bce976d5e077bbe73c7da8ead0ebb92b890b98272655af01d3ccece1c5656f74)
  (missing) countries/.ipynb_checkpoints/historyIC_v2-checkpoint.ipynb (4a6428cb65e7a4035753589d2f3af12f6441ba89b3712134006b0cb38134b983)
  (missing) countries/.ipynb_checkpoints/covidPlots-checkpoint.ipynb (25b74c60ba87ffc7e6d24da2ecffbc98e90833e890742d5d06f7d7fa8fbc1b96)
Uploading LFS objects: 100% (3697/3707), 2.2 GB | 0 B/s, done.
Enumerating objects: 6185, done.
Counting objects: 100% (6185/6185), done.
Delta compression using up to 36 threads
Compressing objects: 100% (4359/4359), done.
Writing objects: 100% (4370/4370), 343.75 MiB | 11.75 MiB/s, done.
Total 4370 (delta 48), reused 4198 (delta 10), pack-reused 0
remote: Resolving deltas: 100% (48/48), completed with 31 local objects.
remote: error: GH008: Your push referenced at least 10 unknown Git LFS objects:
remote:     4d2cbfc64508dd56b52a298ff2c50b1f0610a7ec38dcc76d8218031b33b87ed1
remote:     25b74c60ba87ffc7e6d24da2ecffbc98e90833e890742d5d06f7d7fa8fbc1b96
remote:     4a6428cb65e7a4035753589d2f3af12f6441ba89b3712134006b0cb38134b983
remote:     ...
remote: Try to push them with 'git lfs push --all'.
To https://github.com/gasilva/dataAndModelsCovid19.git
 ! [remote rejected]   HEAD -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/gasilva/dataAndModelsCovid19.git'
```

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  In this case, the message, which comes from GitHub, indicates that there are some Git LFS files which you haven't pushed, and without which your repository would be corrupt.  You might want to try pushing them with `git lfs push --all`, as the message recommends.

If that doesn't work, then you'll need to find the objects somewhere on your system if they're still present.  That might be in some other location where you were working, or in a backup.  You can do a normal `git lfs fetch --all OTHER-PATH` in your repository to pull them in.  Otherwise, they're probably lost, and you'll need to rewrite your history to remove the missing objects before you can push to GitHub.

If you're working in a directory synced by a cloud syncing service, like Dropbox, that can also be the cause of this, since those services are known to corrupt repositories.  We recommend you don't use those services for syncing repositories.

**Comment by gasilva** [comment]
I did all this. Nothing works.
I do not have cloud service in this computer.

Guilherme A. Lima da Silva, Dr.



Em qua., 19 de mai. de 2021 às 17:23, brian m. carlson <
***@***.***> escreveu:

**Comment by bk2204** [comment]
Okay, if you don't have the objects somewhere else, then you've somehow lost data, and you'll need to use `git rebase -i` to edit the commits with the broken objects and re-add them into your working tree and then run `git add` on the files, or to squash the commits that introduce missing files so that they're gone.

You can find the problematic commits by doing `git rebase -x "git lfs ls-files | grep -qs ' - ' && { printf "broken: "; git rev-parse HEAD; }" origin/master`.  That will print out the revisions, and once you check them out, you can run `git lfs ls-files | grep ' - '` to find the files which are broken.

I will point out that you probably don't need the Jupyter Notebook checkpoints files checked into your repository, so if you just remove those files from your history (and add `.ipynb_checkpoints` to `.gitignore`), then that will solve at least some of your problems.

**Comment by gasilva** [comment]
git rebase -x "git lfs ls-files | grep -qs ' - ' && { printf "broken: ";
git rev-parse HEAD; }" origin/master

fatal: It seems that there is already a rebase-apply directory, and

I wonder if you are in the middle of another rebase.  If that is the

case, please try

git rebase (--continue | --abort | --skip)

If that is not the case, please

rm -fr ".git/rebase-apply"

and run me again.  I am stopping in case you still have something

valuable there.


I cannot push files to my repo anymore.

And I am paying the data pack.


(base) ***@***.***:~/Desktop/corona/dataAndModelsCovid19> git push origin
HEAD:master

Username for 'https://github.com
<https://signaldmain.website/click?redirect=https%3A%2F%2Fgithub.com&dID=1622556924948&linkName=https://github.com>':
***@***.***

Password for ***@***.***@github.com
***@***.***@github.com>
':

LFS upload missing objects: (3697/3707), 2.2 GB | 0 B/s


  (missing) countries/.ipynb_checkpoints/covidPlots-checkpoint.ipynb
(25b74c60ba87ffc7e6d24da2ecffbc98e90833e890742d5d06f7d7fa8fbc1b96)

  (missing)
countries/.ipynb_checkpoints/countries_Covid19_v8-checkpoint.ipynb
(4d2cbfc64508dd56b52a298ff2c50b1f0610a7ec38dcc76d8218031b33b87ed1)

  (missing) countries/covidPlots.ipynb
(ca605ad1f09a82299bab583b72a4791d43d602edc4b13867ff270616d9bff365)

Uploading LFS objects: 100% (3697/3707), 2.2 GB | 0 B/s, done.

  (missing) countries/initialConditions_YaboxNew_v11.ipynb
(f91f919ee5306f9cad8c4424c17a388fa4ec1b9e70fc0fddb695aac2e631225c)

  (missing) countries/deadFitting.ipynb
(bce976d5e077bbe73c7da8ead0ebb92b890b98272655af01d3ccece1c5656f74)

  (missing) countries/countries_Covid19_v8.ipynb
(87ed9f6316f0639645aae607f97c4c947b73025df5922845d226e21cbbbbbfe4)

  (missing)
countries/.ipynb_checkpoints/initialConditions_YaboxNew_v11-checkpoint.ipynb
(3e9b9e626f11d47937734f144445257b4d41b32d8c82df4e5850d7dbf9f96805)

  (missing) countries/Untitled.ipynb
(62504664ffd1c378a1dc229514eca555f9b785fc6542ab9a5d4dca3e16916ed5)

  (missing) countries/.ipynb_checkpoints/historyIC_v2-checkpoint.ipynb
(4a6428cb65e7a4035753589d2f3af12f6441ba89b3712134006b0cb38134b983)

  (missing) countries/historyIC_v2.ipynb
(025bf697a67bbde678bddbe8112cdb14e99977813d2f3b194af3c6306a659afc)

Enumerating objects: 6448, done.

Counting objects: 100% (6447/6447), done.

Delta compression using up to 36 threads

Compressing objects: 100% (4613/4613), done.

Writing objects: 100% (4631/4631), 495.85 MiB | 10.08 MiB/s, done.

Total 4631 (delta 90), reused 4288 (delta 17), pack-reused 0

remote: Resolving deltas: 100% (90/90), completed with 46 local objects.

remote: *warning*: GH001: Large files detected. You may want to try Git
Large File Storage - https://git-lfs.github.com
<https://signaldmain.website/click?redirect=https%3A%2F%2Fgit-lfs.github.com&dID=1622556924948&linkName=https://git-lfs.github.com>
.

remote: *warning*: See http://git.io/iEPt8g
<https://signaldmain.website/click?redirect=http%3A%2F%2Fgit.io%2FiEPt8g&dID=1622556924948&linkName=http://git.io/iEPt8g>
for more information.

remote: *warning*: File countries/historyIC_v2.ipynb is 89.84 MB; this is
larger than GitHub's recommended maximum file size of 50.00 MB

remote: *error*: GH008: Your push referenced at least 10 unknown Git LFS
objects:

remote:     4d2cbfc64508dd56b52a298ff2c50b1f0610a7ec38dcc76d8218031b33b87ed1

remote:     25b74c60ba87ffc7e6d24da2ecffbc98e90833e890742d5d06f7d7fa8fbc1b96

remote:     4a6428cb65e7a4035753589d2f3af12f6441ba89b3712134006b0cb38134b983

remote:     ...

remote: Try to push them with 'git lfs push --all'.

To https://github.com/gasilva/dataAndModelsCovid19.git
<https://signaldmain.website/click?redirect=https%3A%2F%2Fgithub.com%2Fgasilva%2FdataAndModelsCovid19.git&dID=1622556924948&linkName=https://github.com/gasilva/dataAndModelsCovid19.git>

 ! [remote rejected]   HEAD -> master (pre-receive hook declined)

error: failed to push some refs to '
https://github.com/gasilva/dataAndModelsCovid19.git
<https://signaldmain.website/click?redirect=https%3A%2F%2Fgithub.com%2Fgasilva%2FdataAndModelsCovid19.git&dID=1622556924948&linkName=https://github.com/gasilva/dataAndModelsCovid19.git>
'

Guilherme A. Lima da Silva, Dr.
CEO
fone: +55-11-4119-5549
celular: +55-11-982-088-565
Av. Pompéia, 634 cj. 113 - São Paulo - SP - 05022-000
ats4i.com.br
<https://signaldmain.website/click?redirect=http%3A%2F%2Fwww.ats4i.com.br&dID=1622556924948&linkName=ats4i.com.br>



Em qua., 19 de mai. de 2021 às 18:42, brian m. carlson <
***@***.***> escreveu:

**Comment by bk2204** [comment]
It sounds like you're actually in the middle of another rebase, as Git has mentioned, so you'd want to either `git rebase --abort` or remove the directory as specified with `rm -fr ".git/rebase-apply"`.
