### ISSUE TITLE
POST Request to info/lfs/objects/batch with https returns http links

### ISSUE THREAD

**Issue by JPAhnen** [git-lfs/git-lfs#4507]
**Describe the issue**
We're trying to resolve an (possible authentication) issue within our TFS, and could narrow it down to git lfs returing the wrong url for the file download.

A HTTP Post to our server with URL `https://tfsserver:8081/tfs/TFSName/Project/_git/MainRepo.git/info/lfs/objects/batch`
with the body
```
// POST https://lfs-server.com/objects/batch
// Accept: application/vnd.git-lfs+json
// Content-Type: application/vnd.git-lfs+json
// Authorization: Basic ... (if needed)
{
  "operation": "download",
  "transfers": [ "basic" ],
  "ref": { "name": "refs/heads/main" },
  "objects": [
    {
      "oid": "0a81a66c54436592e96fbd9f7fdeebcb766eb818e52c1bb186b3ec8441abba91",
      "size": 123
    }
  ]
}
```
and using bearer authentication returns
```
{
    "objects": [
        {
            "oid": "0a81a66c54436592e96fbd9f7fdeebcb766eb818e52c1bb186b3ec8441abba91",
            "size": 770048,
            "actions": {
                "download": {
                    "href": "http://tfsserver:8080/tfs/TFSName/Project/_git/MainRepo/info/lfs/objects/0a81a66c54436592e96fbd9f7fdeebcb766eb818e52c1bb186b3ec8441abba91",
                    "header": {
                        "Accept": "application/vnd.git-lfs"
                    }
                }
            }
        }
    ]
}
```
The URL in `href ` is wrong (`http` instead of `https` and wrong port), and the `authorization` header is missing (maybe because the url is wrong?).
When TFS does a checkout, the TFS checkout works, and the call to `https://tfsserver:8081/tfs/TFSName/Project/_git/MainRepo.git/info/lfs/objects/batch` works too, but all subsequent calls for actually downloading the files fails because the missing authentication header.
What I'd like to know is how I can make LFS to return the correct url (or pass the authentication header along).

The files were actually posted using HTTP, and we have many client using HTTP. In this special case it's about a new build agent which communicates via HTTPS.

**System environment**
Azure Devops Server 2019 with Git version 2.31.1.windows.1 with LFS version 2.13.3

**Output of `git lfs env`**
```git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.31.1.windows.1

Error reading git config: error running C:\Program Files\Git\mingw64\libexec\git-core\git.exe 'rev-parse' '--is-bare-repository': 'fatal: not a git repository (or any of the parent directories): .git' 'exit status 128'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""```

**Additional context**
Any other relevant context about the problem here.

<!--
Please note: if you're receiving a message from the server side (including a
`batch response` message), it's probably best to contact your Git hosting
provider about the problem.  Also, this repository is for the Git LFS client
only; problems with GitHub's server-side LFS support should be reported to them
as described in the `CONTRIBUTING.md` file.
-->

**Comment by bk2204** [comment]
Hey,

The URLs are generated on the server side (that is, by your Azure DevOps server), and the configuration for these URLs is decided by the server, so you'd need to configure it appropriately to use HTTPS.  I'm not sure how to do that with an Azure DevOps server, though.

If you can't get it working, you can instead set `lfs.transfer.enablehrefrewrite` and use the standard `http.*.insteadOf` to rewrite your URLs.  So maybe something like this:

```shell
$ git config lfs.transfer.enablehrefrewrite true
$ git config http.https://tfsserver:8081/tfs/TFSName/Project/_git/MainRepo/info/lfs/.insteadOf \
  http://tfsserver:8080/tfs/TFSName/Project/_git/MainRepo/info/lfs/
```

**Comment by JPAhnen** [comment]
Thanks, that makes sense!
But why does LFS not use the credentials passed to the `git lfs pull` command for the file downloads? They fail because no credentials were provided.

**Comment by bk2204** [comment]
That's probably because your credential helper doesn't have credentials for the HTTP version of the protocol.  Git segments credentials by scheme as well as by domain, so Git LFS won't use the same credentials for HTTP just because there are credentials for HTTPS.  For example, I never want to send credentials over plain HTTP, since it's insecure, so my credential helper won't emit the ones I've stored for HTTPS.
