### ISSUE TITLE
A malformed server response to lock causes nil pointer deference 

### ISSUE THREAD

**Issue by trobol** [git-lfs/git-lfs#4508]
**Describe the issue**
When response from a server to the lock creation doesn't include "lock" or "message", `lockRes.lock` is nil when it is derefrenced [locking/locks.go:118](https://github.com/git-lfs/git-lfs/blob/c7c6901893c3712f0910421fab454a4f87d3f126/locking/locks.go#L118)

**System environment**
Debian, buster

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  Do you have an example server that demonstrates this case?

**Comment by bk2204** [comment]
Also, can you verify that #4509 fixes the problem for you?  If you need artifacts, CI will have built them and they'll be in the Actions tab.

**Comment by trobol** [comment]
I ran into the issue when I was building a server and I didn't wrap the lock object. The response what something like this:
```
{"id":"e5a9a62e00131280d567c99a5d3a0d8fd6a88dbe0188bac1d23e6210e5bb23ed","locked_at":"2021-05-25T14:07:01+00:00","path":"text.txt","owner":{"name":"trobol"}}
```
The PR fixes the problem, thank you for the speedy response.
