### ISSUE TITLE
Error downloading object: ... : Smudge error: Error downloading ... (...): EOF

### ISSUE THREAD

**Issue by pawelsopensource** [git-lfs/git-lfs#4514]
hi,
i've a builder machine based on fedora-30 that periodically clone+checkout the project from bare git mirror and build the project from scratch. basically the builder executes two initial steps:
`git clone --shared /some/path/to/bare-project-mirror.git project`
`git -C project checkout --detach --force some-hash-on-some-branch`

it works fine on old fedora-30 with following packages:
`git-2.21.0-1.fc30.x86_64`
`git-lfs-2.8.0-2.fc30.x86_64`

recently i've installed ubuntu-server-20.04.2-lts on the new machine and newer git-lfs reports an error during checkout:
`(...)`
`Updating files: 100% (57938/57938), done.`
`Downloading (...)/...7z (452 MB)`
`Error downloading object: (...)/...7z (...): Smudge error: Error downloading (...)/...7z (...): EOF`
ubuntu provides following packages:
`git 1:2.25.1-1ubuntu3.1`
`git-lfs 2.9.2-1`

afaics there's a minor difference in `git lfs env` output between machines (diff fc30->ubuntu):
`-DownloadTransfers=basic`
`-UploadTransfers=basic`
`-GIT_EXEC_PATH=/usr/libexec/git-core`
`+DownloadTransfers=basic,lfs-standalone-file`
`+UploadTransfers=basic,lfs-standalone-file`
`+GIT_EXEC_PATH=/usr/lib/git-core`

the lfs server is located in local network and uses some "go" implementation (htop shows go/lfs/test-server-process).

**Comment by bk2204** [comment]
Hey,

Can you include the full output of `git lfs env` both before and after?  I'm looking to see whether you're using an HTTP LFS server or trying to use the bare repository as your LFS remote.  Also, can you try the latest version?  I think what you're seeing here is that 2.9.2 supports only file URLs, not local paths, so if you're not using an HTTP server here, you'll need to either use a file URL or upgrade so things work.

**Comment by pawelsopensource** [comment]
> Hey,
> 
> Can you include the full output of `git lfs env` both before and after? I'm looking to see whether you're using an HTTP LFS server or trying to use the bare repository as your LFS remote.

i'm using a remote http lfs server in the project:
`$ cat .lfsconfig`
`[lfs]`
`	url = http://user:pass@lan_server:9999`

here's the full env dump @ubuntu:
`$ git lfs env`
`git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)`
`git version 2.25.1`
`Endpoint=http://user:pass@lan_server:9999 (auth=none)`
`LocalWorkingDir=/home/builder/temp/project`
`LocalGitDir=/home/builder/temp/project/.git`
`LocalGitStorageDir=/home/builder/temp/project/.git`
`LocalMediaDir=/home/builder/temp/project/.git/lfs/objects`
`LocalReferenceDirs=`
`TempDir=/home/builder/temp/project/.git/lfs/tmp`
`ConcurrentTransfers=3`
`TusTransfers=false`
`BasicTransfersOnly=false`
`SkipDownloadErrors=false`
`FetchRecentAlways=false`
`FetchRecentRefsDays=7`
`FetchRecentCommitsDays=0`
`FetchRecentRefsIncludeRemotes=true`
`PruneOffsetDays=3`
`PruneVerifyRemoteAlways=false`
`PruneRemoteName=origin`
`LfsStorageDir=/home/builder/temp/project/.git/lfs`
`AccessDownload=none`
`AccessUpload=none`
`DownloadTransfers=basic,lfs-standalone-file`
`UploadTransfers=basic,lfs-standalone-file`
`GIT_EXEC_PATH=/usr/lib/git-core`
`git config filter.lfs.process = "git-lfs filter-process"`
`git config filter.lfs.smudge = "git-lfs smudge -- %f"`
`git config filter.lfs.clean = "git-lfs clean -- %f"`

> Also, can you try the latest version? I think what you're seeing here is that 2.9.2 supports only file URLs, not local paths, so if you're not using an HTTP server here, you'll need to either use a file URL or upgrade so things work.

i'll try the latest version asap...

**Comment by pawelsopensource** [comment]
hi, the latest stable release v2.13.3  works fine.
