### ISSUE TITLE
git lfs push --all hangs

### ISSUE THREAD

**Issue by nicolasmanic** [git-lfs/git-lfs#4515]
**Describe the bug**
I have a repository hosted in a managed GitLab instance, I also have various forks I need to update periodically in the same gitlab instance. 

I use `git lfs push --all` to push all lfs objects to each fork, it works well but it hangs at the end and it takes a couple of hours to finish.

Here are the debug logs:
```
$ GIT_TRACE=1 GIT_TRACE_PACKET=1 GIT_TRACE_PERFORMANCE=1 GIT_TRACE_SETUP=1 GIT_CURL_VERBOSE=1 GIT_TRANSFER_TRACE=1 git lfs push --all git@my_server.com:my_project/repo.git

...
13:37:51.758244 trace git-lfs: HTTP: POST https://my_server.com:my_project/repo.git/info/lfs/objects/batch
> POST /com:my_project/repo.git/info/lfs/objects/batch HTTP/1.1
> Host: my_server.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 8918
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
>
{"operation":"upload","objects":[{ .....}]}


< HTTP/2.0 200 OK
< Connection: close
< Cache-Control: max-age=0, private, must-revalidate
< Content-Type: application/vnd.git-lfs+json; charset=utf-8
< Date: Wed, 02 Jun 2021 13:37:51 GMT
< Page-Title: GitLab
< Permissions-Policy: interest-cohort=()
< Referrer-Policy: strict-origin-when-cross-origin
< Server: nginx
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: DENY
< X-Permitted-Cross-Domain-Policies: none
< X-Runtime: 0.080473
< X-Ua-Compatible: IE=edge
< X-Xss-Protection: 1; mode=block
<
13:37:51.844741 trace git-lfs: HTTP: {"objects":[.....]}
###  stuck here cmd is still running but nothing is printing ###
```

**To Reproduce**
See error (but maybe not reproducible)

**Expected behavior**
Terminate the cmd and not let it hang either with an error or with a success.

**System environment**
Ubuntu 20.04.2 LTS
git version 2.31.1
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5) (but also tested 2.10 & 2.13)

**Output of `git lfs env`**
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.31.1

Endpoint=https://my_server.com/my_project/repo.git/info/lfs (auth=none)
  SSH=git@my_server.com:cds/com:my_project/repo.git

LocalWorkingDir=
LocalGitDir=/workdir/my_project
LocalGitStorageDir=/workdir/my_project
LocalMediaDir=/workdir/.lfs-cache/objects
LocalReferenceDirs=
TempDir=/workdir/.lfs-cache/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/workdir/.lfs-cache
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by nicolasmanic** [comment]
An update I was able to skip this step. I was missing some LFS objects and was just hanging there (still not the best experience). Now I have the following:
```
trace git-lfs: run_command: git rev-list --stdin --objects --do-walk --
trace git-lfs: tq: running as batched queue, batch size of 100
.
.
.
trace git-lfs: run_command: git rev-list --stdin --objects --do-walk --
trace git-lfs: tq: running as batched queue, batch size of 100
```

This repeats for 1-2 hours again what is going on anyone can help?

FYI the repo has ~500 tags if that matters

**Comment by nicolasmanic** [comment]
A few more details in case it helps:

- The repo has many commits and ~500 tags
- When I run `lfs push --all` with git-lfs 2.10  I get a loop of the following:
```

```
This is not the case for 2.13 or 2.9

**Comment by nicolasmanic** [comment]
closed by mistake sorry.
When I updated to the latest git lfs version I get a slightly different loop of messages:
```
.
.
.
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: run_command: git rev-list --objects --do-walk --stdin --
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'cat-file' '--batch-check'
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
race git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: run_command: git rev-list --objects --do-walk --stdin --
trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'cat-file' '--batch-check'
race git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
trace git-lfs: tq: running as batched queue, batch size of 100
.
.
.
```

**Comment by nicolasmanic** [comment]
I think I have the same issue as here: https://github.com/git-lfs/git-lfs/issues/4350 should I close that and continue in the other ticket?

**Comment by chrisd8088** [comment]
It does sound plausible that this is the same as the existing ticket, so if you're willing to close this one and add a comment on #4350, that would be great, thank you!
