### ISSUE TITLE
Shell tilde & glob patterns do not work as expected with locking & unlocking

### ISSUE THREAD

**Issue by turion** [git-lfs/git-lfs#4529]
**Describe the bug**

Using paths containing `~` or `*` does not work as expected.

**To Reproduce**
1. Take a repo with several files, store it at `~/my_repo`
2. Execute `git lfs lock *`
3. The _first_ file for which the glob matches is locked
4. `git lfs lock ~/my_repo/some_file`
5. A lock for a nonexistent file with a broken path like `/home/my_user/my_repo/home/my_user/my_repo/some_file` is created

Similar behaviour occurs for `git lfs unlock`.

**Expected behavior**

`git lfs` resolves `~`, `*` and other typical shell expansions locally before performing lock operations. Or at least it prints a warning/error pointing to some documentation where it is explained that this is currently unsupported.

**System environment**

NixOS unstable
```
$ git lfs --version
git-lfs/2.13.3 (2.13.3; linux amd64; go 1.16.3; git v2.13.3)
$ git --version
git version 2.31.1
```

**Output of `git lfs env`**
(This contains some personal information which I don't share on the internet. Do you need to know any specific setting?)

**Comment by KalleOlaviNiemitalo** [comment]
`git lfs lock a b c` on git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851) likewise locks only `a`, so this part does not seem specific to globbing. I guess it should just report an error saying that only one path is allowed. Supporting multiple paths might require changing the `git lfs lock --json` output format.

Are you using Git LFS against GitHub or some other server?

**Comment by turion** [comment]
> `git lfs lock a b c` on git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git [a5e6585](https://github.com/git-lfs/git-lfs/commit/a5e658518e749c70a2f488e754e2d73d49c2d154)) likewise locks only `a`, so this part does not seem specific to globbing.

Good point. Then probably the `*` works and it just uses the first result.

For `~` it is probably a separate issue: It expands the path to an absolute one, incorrectly interprets that as a _relative_ path, and "locks" it, (although the file doesn't exist, which the server can't know, but the client could).

> Are you using Git LFS against GitHub or some other server?

GitLab.

**Comment by bk2204** [comment]
Hey,

It is the case that we lock only one file at a time, but I agree we could print an error message if an attempt were made to lock multiple items.

In your case, is `~/my_repo` the repo you're currently in or is it another repo?  We always canonicalize the paths and turn them into relative paths, but it may be that that isn't working for whatever reason.  Note that it is permissible to lock and unlock files that don't exist since files may exist in a different branch than the one the user is currently on and locking those files should be possible.

**Comment by turion** [comment]
> It is the case that we lock only one file at a time, but I agree we could print an error message if an attempt were made to lock multiple items.

That would be great. Being able to lock multiple files would be even better of course :) after all, other git commands like add work like that as well.

> In your case, is `~/my_repo` the repo you're currently in or is it another repo?

It is the same repo.

> We always canonicalize the paths and turn them into relative paths, but it may be that that isn't working for whatever reason.

Yes, that seems to be the case here. Is there some debug mode that can be turned on to find out what's going on?

> Note that it is permissible to lock and unlock files that don't exist since files may exist in a different branch than the one the user is currently on and locking those files should be possible.

That makes sense, thanks.

**Comment by KalleOlaviNiemitalo** [comment]
> Is there some debug mode that can be turned on to find out what's going on?

Setting the GIT_TRACE environment variable adds some debug output but perhaps not enough. I tried GIT_TRACE_CURL=1 in addition but this did not make `git lfs lock a` display the body of the HTTP request.

**Comment by turion** [comment]
`GIT_TRACE` is helpful! It seems that the path is expanded locally to a full absolute path `/home/my_user/my_repo/some_file`, and then the HTTP request contains this full path without the leading `/`, resulting in a GET message like:

```
HTTP: {"locks":[{"path":"home/my_user/my_repo/some_file" [...]
```

**Comment by bk2204** [comment]
I have a patch for both of these issues and I hope to submit it later today.  It's possible that I won't get to it, though, so in the mean time, I've pushed a branch up to my fork called `locking-improvements` in case you want to test the code.  It needs better commit messages and some tests.

**Comment by KalleOlaviNiemitalo** [comment]
@bk2204, thank you. I hope the code recognizes Windows paths that start with a different drive letter as being outside the repository. I don't see any specific check for that in <https://github.com/bk2204/git-lfs/commit/282e3e11b4e5e4a965259ba6f29520a8745425fe> but perhaps `filepath.Rel(repo, abs)` takes care of it.

**Comment by bk2204** [comment]
According to the Go docs for `filepath.Rel`:

> An error is returned if `targpath` can't be made relative to `basepath` or if knowing the current working directory would be necessary to compute it.

So I think that should work just fine on Windows with different drives.  At least, I don't think we're any worse off now with this code than we were before, since we used to use `filepath.Rel` before as well.
