### ISSUE TITLE
Release schedule option `git lfs prune --force`

### ISSUE THREAD

**Issue by hueypark** [git-lfs/git-lfs#4537]
The `git lfs prune --force` option was merge at 15 Jan, but was not included in the v2.13.3(27 Mar).
May I know when this option will be released?

**Comment by chrisd8088** [comment]
I believe the current intent is to release v3.0 in the next few months; because it's a major release, with non-backwards-compatible features, it's taking a bit longer to prepare and test.

**Comment by hueypark** [comment]
Thank you!
