### ISSUE TITLE
stops at git push -u origin main, and does not upload my code

### ISSUE THREAD

**Issue by rafusanjani** [git-lfs/git-lfs#4542]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Could you please fill out the issue template with full details, including your operating system and Git and Git LFS versions?  I suspect this is actually github/git-for-windows#3294 if you're on Windows, but it's impossible for me to tell since you haven't included any additional information.

**Comment by bk2204** [comment]
Since we haven't heard back, I'm going to close this.
