### ISSUE TITLE
Clean the git lfs history on remote

### ISSUE THREAD

**Issue by taherbs** [git-lfs/git-lfs#4543]
Hi,
we are looking for a way to clean the `git lfs` files on remote repo on Gitlab and only keep the 3 latest versions of the file for example.
I have checked the documentation regarding git-lfs-prune but it seems to be cleaning on local repos only.  
Thank you

**Comment by bk2204** [comment]
Hey,

Git LFS doesn't offer a standard way to delete data on the remote.  It's possible that your hosting provider, who in this case is GitLab, has a way for you to do this, but it would be specific to their implementation and not part of the regular client.
