### ISSUE TITLE
add FAQ entry for git-diff on large text files on a per file/extension (.gitattributes entry) basis

### ISSUE THREAD

**Issue by m27315** [git-lfs/git-lfs#4551]
Please consider merging the following change into the wiki for the FAQ:

https://github.com/m27315/git-lfs-wiki/tree/diff-individual-large-files-types

This documents how to use the recommended solution to see diffs of large text files on a per entry basis of the `.gitattributes` files.  For example, people can diff large `*.patch` or `*.json` files as plain text files - even though tracked in LFS - while maintaining conventional behavior for "binary" formats.

Without this new entry, the existing solution forces all LFS tracked files to be treated either as all text or all binary files, which is unfortunate for repos with mixed LFS content (i.e., some large text files, some large binary files).

This new entry is based on the existing FAQ entry, #440, and this doc:

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

Suggested Changes:
```
diff --git a/FAQ.asciidoc b/FAQ.asciidoc
index 5fdc48a..557dc42 100644
--- a/FAQ.asciidoc
+++ b/FAQ.asciidoc
@@ -59,6 +59,31 @@ How do I enable git diff to work on LFS files?:::
   You can run `git config diff.lfs.textconv cat`, which will normal diffs if
   your files are text files.
 
+How do I enable git diff to work on LFS files based on extension or path?:::
+  If the above solution is too broad, each entry in the `.gitattributes` file
+  can be customized by creating a custom global converter:
++
+[source,shell-session]
+----
+$ git config --global diff.lfstext.textconv cat
+----
++
+Any given `.gitattributes` entry for large text files can be customized to use
+this global text converter (e.g., patch files), whereas binary formats can
+continue to use the conventional lfs diff tool, like so:
+[source,shell-session]
+----
+$ cat .giattributes
+...
+*.bin filter=lfs diff=lfs merge=lfs -text
+*.patch filter=lfs diff=lfstext merge=lfs -text
+...
+----
++
+Be advised that all developers sharing this repo with such a modified
+`.gitattributes` file must have similarly configured the `lfstext` text
+converter, whether globally or on per repository basis.
+
 How do I switch from large objects to pointer files in the working tree?:::
   If your working tree is clean, you can run
   `GIT_LFS_SKIP_SMUDGE=1 git read-tree -u --reset HEAD` to switch back to

```

**Comment by bk2204** [comment]
Hey,

This sounds like a nice change.  Our wiki is open for public editing, so you can add this yourself.  If you still want us to add it on your behalf, we can, though.

I will just point out two nits: `cat .giatrributes` is missing a "t" in "git", and you need a blank line before the `[source,shell-session]` block header.  I can fix those up if I do the edit, though.

**Comment by m27315** [comment]
Sounds good.  I added the new tip with this change:

https://github.com/git-lfs/git-lfs/wiki/FAQ/00d8e18c0b585d7f0f64db9d06a4da875708e26d

Thanks!  :smile:
