### ISSUE TITLE
Q: pointer blob size?

### ISSUE THREAD

**Issue by naseemkullah** [git-lfs/git-lfs#4563]
I am trying to have my CI system detect if lfs tracked files were accidentally committed (user has not installed git-lfs locally).

To achieve this i run git cat-file on checked in files that are lfs tracked, i get back their blob size.

I've seen pointers have  size of `131`, though I've seen `130` [elsewhere](https://github.com/git-lfs/git-lfs/issues/2824#issuecomment-359124406).

Is there a surefire way to know a file is a pointer based on the blob size?

**Comment by bk2204** [comment]
No, there isn't a way to do this based solely on the blob size.  You actually have to parse the file in order to know.

Note that in the upcoming Git LFS 3.0.0, we'll support a mode of `git lfs fsck` that checks to make sure all files that are supposed to be pointer files are indeed pointer files.  That will be able to be done with `git lfs fsck --pointers`.

**Comment by naseemkullah** [comment]
> No, there isn't a way to do this based solely on the blob size. You actually have to parse the file in order to know.

is checking for the string `"version https://git-lfs.github.com/spec/v1"`  in files sufficient to determine that they are a pointer?

> Note that in the upcoming Git LFS 3.0.0, we'll support a mode of `git lfs fsck` that checks to make sure all files that are supposed to be pointer files are indeed pointer files. That will be able to be done with `git lfs fsck --pointers`.

great to hear

**Comment by KalleOlaviNiemitalo** [comment]
I implemented something a bit similar and decided not to check the `/v1` part of the version line. If Git LFS format version 2 is ever published, then I hope my code will recognise its pointer files too; the code does not try to parse the subsequent lines of the pointer files or even assume that they are text, so it should be OK even if the v2 format is quite different.

**Comment by bk2204** [comment]
> > No, there isn't a way to do this based solely on the blob size. You actually have to parse the file in order to know.
> 
> is checking for the string `"version https://git-lfs.github.com/spec/v1"` in files sufficient to determine that they are a pointer?

There are some legacy strings that can be used instead.  Piping them to `git lfs pointer --check --stdin` would be better.  In version 3.0.0, you should also add `--strict`.
