### ISSUE TITLE
Package for Debian 11, Bullseye

### ISSUE THREAD

**Issue by kdumontnu** [git-lfs/git-lfs#4589]
**Describe the issue**
There is no git LFS build for Debian 11, Bullseye, which is now the latest stable Debian release.

**System environment**
Debian 11, Bullseye

**Additional context**
My apologies if this is already being worked on.

(For SEO) For those running images recently updated to Debian 11, you will see the following error:
```
curl: (22) The requested URL returned error: 404
Installing /etc/apt/sources.list.d/github_git-lfs.list... 

Unable to download repo config from: https://packagecloud.io/install/repositories/github/git-lfs/config_file.list?os=debian&dist=11&source=script
This usually happens if your operating system is not supported by
packagecloud.io, or this script's OS detection failed.  

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.
```

**Comment by bk2204** [comment]
Hey,

I think we can definitely do this.  I'll look into building a suitable Docker container next week and then we'll include the package as part of the 3.0.0 release which we're planning to do soon.
