### ISSUE TITLE
Syncing established remote Git LFS repository around existing local files

### ISSUE THREAD

**Issue by claabs** [git-lfs/git-lfs#4612]
**Describe the issue**
I already have ~50 GB of files locally on my system. I also have a remote Git LFS repository with those exact files existing on the `master` branch.

I'd like to create a local repository around those pre-existing local files without redownloading them, and then be able to navigate the repo as normal, like checkout older tags and such.

**System environment**
Windows 10 client, Gitea 1.15.0 (Docker) server

**Output of `git lfs env`**
```
Endpoint=https://gitea.example.com/claabs/my-repo.git/info/lfs (auth=none)
LocalWorkingDir=C:\Users\charl\win-projects\my-repo
LocalGitDir=C:\Users\charl\win-projects\my-repo\.git
LocalGitStorageDir=C:\Users\charl\win-projects\my-repo\.git
LocalMediaDir=C:\Users\charl\win-projects\my-repo\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\charl\win-projects\my-repo\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\charl\win-projects\my-repo\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
The goal here is to not re-download the files I already have to save time and data. I could easily just `git clone` the repo and be done with it, but LFS's download progress indicator isn't the most encouraging for this much data, especially when I already have it locally. I'd also like to not clone-then-move the large files, because there's many files and quite a few subfolders to navigate.

I'm not creating a new project repo from scratch, nor importing any new LFS files to an existing one. 

My attempt at this use-case was the following set of commands:
```shell
git init
git remote add origin https://gitea.example.com/claabs/my-repo.git
git fetch
GIT_LFS_SKIP_SMUDGE=1 git checkout origin/master -b master --force
```

Unfortunately, the checkout overwrites the existing files with LFS pointer files. 

I think I'm missing a couple steps that are something like:
1. download all the non-LFS files, which is required to get the `.gitattributes` and `.gitignore`. 
2. hash the existing files to let LFS know they're what we expect

For 1, I enabled the `git clone --filter=blob:none` feature in Gitea, but filtering blobs just downloaded the pointer files anyway.
For 2, I assume that it's something like `git add .`, but nothing should be staged because there are no changes

After the repo is setup, I plan on using Git and Git LFS to swap between tags (e.g. `git checkout v1.0.0`) and use LFS to cache the latest version until needed later.

I'm pretty stumped on this, and I appreciate if anyone can give nudge in the right direction.

**Comment by KalleOlaviNiemitalo** [comment]
You could run `git lfs clean < FILE` to copy the file to the appropriate directory within `.git/lfs/objects/`.  It outputs the Git LFS pointer but you can redirect that to the null device.

In contrast, `git lfs pointer --file=FILE` hashes the file but does not copy it into `.git/lfs/objects/`.

If you have the `.gitattributes` or `.git/info/attributes` set up for Git LFS already, you could even use `git hash-object` to run the Git LFS clean filter without saving the Git LFS pointer blob to `.git/objects/` and without modifying the index.

**Comment by claabs** [comment]
It turns out this doesn't require any LFS-specific commands at all. I think I can achieve this with just:
```shell
git init
git remote add origin https://gitea.example.com/claabs/my-repo.git
git fetch
git checkout origin/master -- .gitignore .gitattributes
git add .
git checkout master --force
```

Using `git checkout` with a `<pathspec>` lets me pull just the .gitignore/.gitattributes, and `git add` does all the hashing I need.
