### ISSUE TITLE
error converting ".git" to absolute: EvalSymlinks: too many links

### ISSUE THREAD

**Issue by lucaraki** [git-lfs/git-lfs#4627]
Thank you for filling out a Git bug report!
Please answer the following questions to help us understand your issue.

What did you do before the bug happened? (Steps to reproduce your issue)
> Attempted push operation

What did you expect to happen? (Expected behavior)
> push operation success, no error message

What happened instead? (Actual behavior)
> Push operation failed with error message:
```
Error: error converting ".git" to absolute: EvalSymlinks: too many links
ref feature/feature_name:: EvalSymlinks: too many links
error: failed to push some refs to 'https://my_server_name/my_project.git'
```

In addition, ```lfs/``` directory was created in project folder instead of ```.git``` folder.

What's different between what you expected and what actually happened?
> Did not expect lfs/ directory to be created in project folder. Don't expect error on push operation.

Anything else you want to add:
> After reading issues #4050 and #4012, attempted:
`git lfs env` and got output:
```
git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.33.0.windows.2

Error: error converting ".git" to absolute: EvalSymlinks: too many links
Endpoint=https://my_server_name/my_project.git/info/lfs (auth=basic)
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I realized that the project folder was in Box drive folder (see [www.box.com/drive](www.box.com/drive)), set to keep a local copy of my project space on my local hard disk. Based on issues #4050 and #4012, I decided to try moving the project folder to a different local location.
I copied entire project directory our of Box folder, then re-ran `git
lfs env` and got output:
```
git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.33.0.windows.2

Endpoint=https://my_server_name/my_project.git/info/lfs
(auth=basic)
LocalWorkingDir=C:\Users\username\myProject
LocalGitDir=C:\Users\username\myProject\.git
LocalGitStorageDir=C:\Users\username\myProject\.git
LocalMediaDir=C:\Users\username\myProject\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\username\myProject\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\username\myProject\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I noticed that `LocalGitDir` looked correct and was no longer blank.
Re-tried `git push` from new project location and push operation succeeded.

Please review the rest of the bug report below.
You can delete any lines you don't wish to share.

```
[System Info]
git version:
git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
uname: Windows 10.0 19042
compiler info: gnuc: 10.3
libc info: no libc information available
$SHELL (typically, interactive shell): <unset>

[Enabled Hooks]
post-commit
post-checkout
post-merge
pre-push
```

**Comment by lucaraki** [comment]
```git rev-parse --git-dir --absolute-git-dir --show-toplevel --is-inside-work-tree``` returned the path to project as expected.

**Comment by bk2204** [comment]
Unfortunately, this is likely due to using a Box folder.  It's never safe to put a regular repository into a folder operated by a cloud syncing service, since those can corrupt the repository.  So while it's possible that we could make some changes that would fix this, I don't think this is a use case we want to support.  We can accept a patch if someone comes up with one and it's minimally invasive, but otherwise we won't be fixing this.
