### ISSUE TITLE
Purging LFS repository

### ISSUE THREAD

**Issue by tcamin** [git-lfs/git-lfs#4639]
We use git-lfs to store cached build artifacts to reduce build times of our application. This works great and provides a pleasant developer experience since everything is hidden behind `git pull`. The only downside is that over the years we accumulated lots of build artifacts which resulted in a significant amount of space being used on LFS.

Since build artifacts can be regenerated anytime is it safe to purge all LFS objects (from the admin panel "Purge LFS objects")? When checking out older revisions we'll probably get an error for the LFS objects that no longer exists remotely which can be regenerated and pushed up again, beside that should we be worried of something else?

**Comment by chrisd8088** [comment]
This sounds like you're not asking about the `git lfs prune` that cleans up older Git LFS objects on your local repository, but something you can run on your Git LFS service provider's system (you mentioned an "admin panel", for instance).  So I think this is a question best taken up with their support team, as this project is only for the open-source command line client.

That said, you might want to experiment with a small test repository and see what happens in the situation you describe and given your specific tooling and LFS service.

**Comment by tcamin** [comment]
My question is how git lfs behaves when it doesn't find remote objects. Empirically trying on a simple repo might not cover all edge cases.

**Comment by chrisd8088** [comment]
The server should reply with a 404 for the object (not the request as a whole), as [defined](https://github.com/git-lfs/git-lfs/blob/cdfa3fff3acb6d78b1392ce6bcb1774908ebe432/docs/api/batch.md#successful-responses) in the batch API, and the CLI client should respect that and report it as a per-object error.
