### ISSUE TITLE
lfs.allowincompletepush not working when LFS files have not been fetched

### ISSUE THREAD

**Issue by xclaesse** [git-lfs/git-lfs#4640]
GStreamer git repository uses LFS for test assets that most developers does not need. To avoid useless downloads, the git repository has `.lfsconfig`:

```
[lfs]
fetchexclude = *
allowincompletepush = true
```

When cloning that repo it will skip download of all LFS files which is what we want. However, when I then push to my personal fork of gstreamer repository on gitlab, that does not have LFS files neither, it is rejected because I'm missing LFS files:
```
remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
To https://gitlab.freedesktop.org/xclaessens/gstreamer.git
 ! [remote rejected]       main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://gitlab.freedesktop.org/xclaessens/gstreamer.git'
```

I was hoping that `lfs.allowincompletepush` would make that workflow work, is there any other trick  could use?

**Comment by KalleOlaviNiemitalo** [comment]
This would have to be configured at the GitLab server side.

**Comment by xclaesse** [comment]
@KalleOlaviNiemitalo Do you know if that's something we can configure in gitlab, or do you mean it should be reported as a gitlab issue?

**Comment by KalleOlaviNiemitalo** [comment]
I'm not too familiar with GitLab but clearly it's recognising your Git LFS pointers at the server side and checking whether the referenced LFS objects exist. <https://docs.gitlab.com/ee/topics/git/lfs/#hosting-lfs-objects-externally> says that, if you disable Git LFS support in the project settings in GitLab, you can then push Git LFS pointers without GitLab trying to verify the LFS objects.

**Comment by xclaesse** [comment]
Thanks for your help. I'm the end we decided to move lfs files into a dedicated git repository as submodule, and it does the trick. Closing since it's not git-lfs issue but rather gitlab.
