### ISSUE TITLE
Release process fails on Windows ARM64

### ISSUE THREAD

**Issue by bk2204** [git-lfs/git-lfs#4642]
Our Windows release CI job is [failing on ARM64](
https://github.com/git-lfs/git-lfs/runs/3701266790) due to a bad relocation in `resource.syso`.  This is preventing us from doing a release.

I've tried removing the `resource.syso` file before rebuilding the ARM64 binaries, but that doesn't fix the problem.  If we can't figure out how to solve this before Monday, I'll need to revert the Windows ARM64 support until such time as it builds properly in CI.

Note that this problem does not occur when building the binaries on Linux.

/cc @dennisameling as the original submitter

**Comment by dennisameling** [comment]
@bk2204 I can have a look tomorrow, will let you know 👍🏼 thanks for the mention

**Comment by dennisameling** [comment]
Fixed in https://github.com/git-lfs/git-lfs/pull/4647 👍🏼
