### ISSUE TITLE
git-lfst v3.0.0 doens't provide linux binaries files and  signed SHA-256 hashes

### ISSUE THREAD

**Issue by mangin** [git-lfs/git-lfs#4650]
**git-lfst v3.0.0 dosen't provide linux binaries files and  signed SHA-256 hashes**
In the previous releases git lfs used to provided linux binaries files and signed SHA-256 hashes.
In the new release (v3.0.0) git-lfs provides only sources. 

Could you please provide other files too?
 
 Links:
 [gi-lfs v3.0.0](https://github.com/git-lfs/git-lfs/releases/tag/v3.0.0)
 [git-lfs v2.13.3](https://github.com/git-lfs/git-lfs/releases/tag/v2.13.3)

**Comment by KalleOlaviNiemitalo** [comment]
At <https://github.com/git-lfs/git-lfs/actions/runs/1270252625>, it says "Main Release Assets" was skipped for the 3.0.0 release, I think because "Build Windows Assets (1.17.x)" failed.

**Comment by KalleOlaviNiemitalo** [comment]
The Windows build failure may be <https://github.com/git-lfs/git-lfs/issues/4642>.

**Comment by bk2204** [comment]
Hey,

The 3.0.0 release process failed.  We'll be doing a 3.0.1 today or tomorrow, but there's unfortunately at the moment no way to stage the entire process to abort if part of the process fails.  There's also a potential bug that we may need to fix as well.

**Comment by mangin** [comment]
Thank you for the fast response!
