### ISSUE TITLE
Empty files causes git-lfs 3.0.0 to fail pulling

### ISSUE THREAD

**Issue by elgehelge** [git-lfs/git-lfs#4657]
**Describe the bug**
When using git-lfs 3.0.0 I am not able to do a `git lfs pull`. This is caused by empty files in the repo it seems.

The error I am getting is `[e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855] Object does not exist on the server: [404]` and it seems to be caused by some empty files in the repository (eg. `__init__.py` files which is often empty)

**To Reproduce**

1. Pull a repo with an empty file
2. Install git-lfs=3.0.0 on the machine and in your repo
3. Try to run `git lfs pull`

**To Reproduce (in details)**

1. Assuming you run ubuntu:18.04 (eg. `docker run -it --rm ubuntu:18.04 bash`)
2. Run the following commands
```
apt-get update
apt-get install git
git clone https://github.com/elgehelge/empty-file.git
cd empty-file/
apt-get install curl
curl -sS https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt-get install git-lfs
```
3. Verify you got git-lfs version 3.0.0
4. Then run
```
git lfs install
git lfs pull
```
5. See the error:
```
[e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/elgehelge/empty-file.git/info/lfs'
```

**Expected behavior**
I inspected to be able to pull my git-lfs tracked files without any errors.

**System environment**
ubuntu:18.04 using Docker
`docker run -it --rm ubuntu:18.04 bash`

**Output of `git lfs env`**
```
git-lfs/3.0.0 (GitHub; linux amd64; go 1.17)
git version 2.17.1

Endpoint=https://github.com/elgehelge/empty-file.git/info/lfs (auth=none)
LocalWorkingDir=/empty-file
LocalGitDir=/empty-file/.git
LocalGitStorageDir=/empty-file/.git
LocalMediaDir=/empty-file/.git/lfs/objects
LocalReferenceDirs=
TempDir=/empty-file/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/empty-file/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

This was already reported in #4645, which has already been fixed in #4654, which will be in the 3.0.1 release that's scheduled for today.

**Comment by elgehelge** [comment]
Amazing. Thanks!

**Comment by elgehelge** [comment]
Guess I should also have scrolled through the closed issues then.
Maybe closing them _after_ a fix have been deployed would save a lot of developers a lot of time? :)

**Comment by bk2204** [comment]
We will frequently fix features, non-essential issues, and minor bugs in a minor release and may not do such a release in a month or more, so that would leave a large amount of issues open that would need to be closed later on.  So that's currently impractical, and we ask users to instead see if their issue is already fixed by searching the issue tracker instead.  That's especially important since many people use a release other than the latest one (e.g., one their distro provides).
