### ISSUE TITLE
git lfs not installed

### ISSUE THREAD

**Issue by chrisbing89** [git-lfs/git-lfs#4664]
im trying to push a large file which is tracked by lfs and getting this error every time

batch response: Git LFS is disabled for this repository.
Uploading LFS objects:   0% (0/24), 0 B | 0 B/s, done.
error: failed to push some refs to 'https://github.com/chrisbing89/UV-4.26.git'

thanks

**Comment by bk2204** [comment]
Hey,

This message comes from the server side, and it means that the server has disabled Git LFS for this repository.  You'd want to contact the administrator of that repository or the support folks for your hosting provider.  There's nothing we can do here because this is decision of the server.
