### ISSUE TITLE
Git push don't don't show the evidence of push

### ISSUE THREAD

**Issue by eze1er** [git-lfs/git-lfs#4669]
Hi,
After push command I have this message : Everything up-to-date

this is how it look. 
vagrant [git_basics]> git push origin add-eze1er
Username for 'https://github.com': eze1er
Password for 'https://eze1er@github.com': 
Everything up-to-date

vagrant [git_basics]> git-it verify
Verifying "REMOTE CONTROL"...

ACTUAL                             EXPECTED
------                             --------
"No evidence of push."          != "Bingo! Detected a push."      
""                                 ""                             
# FAIL

**System environment**
MacOs 11.4
git version 2.7.4

Thank you for help

**Comment by eze1er** [comment]
How can I do that my Git-it can recognized the push is made?

**Comment by chrisd8088** [comment]
Hey, I think you may be asking about a different project, [Git-it](http://jlord.us/git-it/).  This is the Git LFS client project and isn't connected with Git-it, so I'm going to close this issue, but I would suggest filing an issue in either the older https://github.com/jlord/git-it or newer https://github.com/jlord/git-it-electron projects instead.  Good luck!
