### ISSUE TITLE
git lfs has an extra / now, breaking artifactory

### ISSUE THREAD

**Issue by jmberg** [git-lfs/git-lfs#4672]
**Describe the bug**
Version 3.0.1 of git lfs that I just installed, will call ssh in the following way:

`ssh -- my-artifactory-server.example.com 'git-lfs-authenticate /artifactory/my-artifactory-repo download'`

got obtain a bearer token. This fails with the current version of artifactory I have, it simply doesn't return anything and ssh exits with a non-zero exit status.

Older versions of git lfs, I installed now 2.13.3, will instead call

`ssh -- my-artifactory-server.example.com 'git-lfs-authenticate artifactory/my-artifactory-repo download'`

(note the / difference), which works with artifactory.

Current artifactory version here is 6.16.0.

**To Reproduce**

Try to `git lfs fetch` on a new checkout of a repository which uses artifactory, with different versions of git lfs.

**Expected behavior**
Expect git lfs to be able to authenticate with artifactory.

**System environment**
Nothing really special, normal Linux, tried Fedora and Ubuntu.

**Output of `git lfs env`**
```
git-lfs/2.13.3 (GitHub; linux amd64; go 1.16.2)
git version 2.31.1

Endpoint=https://my-artifactory-server.example.com/artifactory/my-artifactory-repo (auth=none)
  SSH=my-artifactory-server.example.com:artifactory/my-artifactory-repo
LocalWorkingDir=...
LocalGitDir=...
LocalGitStorageDir=...
LocalMediaDir=...
LocalReferenceDirs=
TempDir=...
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=...
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Yes, this is documented in the changelog for 3.0.0: https://github.com/git-lfs/git-lfs/blob/main/CHANGELOG.md.  It's an intentional change that we made to support the `git-lfs-transfer` binary working the same way as the `git-lfs-authenticate` call.

You'll probably need to work with Artifactory to get an updated version if they have one available.

**Comment by bk2204** [comment]
You can't write a URL with a colon as a separator here.  The Go URL code thinks of that as a port and that's not allowed because it has negative security implications.

What you can do is write an SSH non-URL, like so:

```
[lfs]
url = my-artifactory-server.example.com:artifactory/my-artifactory-repo
```

That should work across versions and systems, and it should be a supported syntax for both Git and Git LFS.

**Comment by jmberg** [comment]
Yes, indeed, that appears to work at least with 2.13.3, but presumably with 3.x as well since it has no extra / there. Thanks!

**Comment by jmberg** [comment]
I guess I'll close this - not completely happy with the backward-incompatible change, but easy enough to work around (and commit the workaround so nobody else needs to think about it :-))

**Comment by DoctorObvious** [comment]
This could be a big deal for my organization. Here's (hopefully) relevant information:

No URL in lfsconfig.

` >> git remote -v`
`origin	ssh://git@my.server.com:7999/uapkg/my-repo.git (fetch)
origin	ssh://git@my.server.com:7999/uapkg/my-repo.git (push)`

```
 >> git lfs env
git-lfs/2.13.3 (GitHub; darwin amd64; go 1.16.2; git a5e65851)
git version 2.23.0

Endpoint=https://my.server.com/uapkg/my-repo.git/info/lfs (auth=none)
  SSH=git@my.server.com:uapkg/my-repo.git
LocalWorkingDir=/Users/mphillips/tree/packages/my-repo
LocalGitDir=/Users/mphillips/tree/packages/my-repo/.git
LocalGitStorageDir=/Users/mphillips/tree/packages/my-repo/.git
LocalMediaDir=/Users/mphillips/tree/packages/my-repo/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/mphillips/tree/packages/my-repo/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/mphillips/tree/packages/my-repo/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
FetchExclude=audio/ref/**, audio/in/**, **/audio/ref/**, **/audio/in/**
GIT_EXEC_PATH=/usr/local/git/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

```
>> git config --get-regexp lfs
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge -- %f
filter.lfs.process git-lfs filter-process
filter.lfs.required true
lfs.repositoryformatversion 0
```

**Comment by KalleOlaviNiemitalo** [comment]
@calle2010, [git-lfs-config.5](https://github.com/git-lfs/git-lfs/blob/v3.0.1/docs/man/git-lfs-config.5.ronn#general-settings) lists `lfs.url` / `remote.<remote>.lfsurl`, so this should work:

```
[remote "origin"]
lfsurl = my-artifactory-server.example.com:artifactory/my-artifactory-repo
```

**Comment by timotei** [comment]
FYI, the workaround seems to work fine with port-based URLs as well:
```
[lfs]
    url = user@artifactory.internal.lan:1339:artifactory/test-lfs
```
