### ISSUE TITLE
git lfs fsck --pointers doesn't respect GIT_OBJECT_DIRECTORY

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#4685]
**Describe the bug**

I'm trying to use `git lfs fsck --pointers <new-sha>` in a pre-receive hook to check that pushed commits have proper LFS pointers. The problem is that `git lfs fsck --pointers` dies with `missing object: <sha>` error for files that are being pushed. Note that those files are even not LFS.

When pushing commits to git repo, `GIT_OBJECT_DIRECTORY` points to the temporary dir where just-uploaded pak file resides. Original `.git/objects` dir is referred by `GIT_ALTERNATE_OBJECT_DIRECTORIES` variable.

Example:

```
GIT_OBJECT_DIRECTORY=/repo/.git/objects/incoming-bgwlLj
GIT_ALTERNATE_OBJECT_DIRECTORIES=/repo/.git/objects
```

I suspect that git library that git-lfs uses under the hood, simply doesn't undersand `GIT_OBJECT_DIRECTORY` at all.

**Expected behavior**

`git lfs fsck --pointers <new-sha>` works properly when called from a pre-receive hook.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**

```
git-lfs/3.0.1 (GitHub; linux amd64; go 1.17.1)
git version 2.20.1

LocalWorkingDir=
LocalGitDir=/workdir/.git
LocalGitStorageDir=/workdir/.git
LocalMediaDir=/workdir/lfs/objects/objects
LocalReferenceDirs=
TempDir=/workdir/lfs/objects/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/workdir/lfs/objects
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_ALTERNATE_OBJECT_DIRECTORIES=/workdir/.git/objects
GIT_EXEC_PATH=/usr/lib/git-core
GIT_OBJECT_DIRECTORY=/workdir/.git/objects/incoming-U1A21e
GIT_PUSH_OPTION_COUNT=
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

I agree that we don't support `GIT_OBJECT_DIRECTORY`.  The handling is typically in Git LFS itself, so it should be simple enough to add it in the two places in Git LFS where we have support for `GIT_ALTERNATE_OBJECT_DIRECTORIES`.
