### ISSUE TITLE
not file upload

### ISSUE THREAD

**Issue by rasel2020nipa2014** [git-lfs/git-lfs#4725]
**Describe the bug**

1. git init '.
Reinitialized existing Git repository in /home/rasel/Desktop/New/.git/'
2. git add . 
3.  git commit -m "frist mess" 
On branch main
nothing to commit, working tree clean 
4. git branch -M main
5.git remote add origin https://github.com/username/repository Name.git
**fatal: remote origin already exists.**
6. git push -u origin main '' Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Delta compression using up to 2 threads
Compressing objects: 100% (22/22), done.
Writing objects: 100% (23/23), 914.79 KiB | 9.53 MiB/s, done.
Total 23 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/rasel2020nipa2014/not_responsive__Nipa.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'. ''
7.git status
''On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean''

**Comment by KalleOlaviNiemitalo** [comment]
If you wanted to use Git LFS for some files, shouldn't you run some `git lfs track` commands before `git add`?

**Comment by bk2204** [comment]
Hey,

Yes, I think in this case you'll want to make sure you've tracked files with `git lfs track` and that you've run `git lfs install` on your system.  If you still see problems after doing that and you can create a shell script that reproduces the problem, please let us know.
