### ISSUE TITLE
Repo size not reduced where there are multiple branches with tags & open/closed PRs

### ISSUE THREAD

**Issue by amarun22** [git-lfs/git-lfs#4732]
**Describe the bug**
Repo size not reduced where there are multiple branches with tags & open/closed PRs. Running on GHES 3.2.x hosted on Linux Environment

**To Reproduce**
Steps to reduce the repository size by converting existing large files to LFS for 
- [x] Single branch repositories
- [x] Repositories that have multiple branches, tags without any pull request.

- Step 1:  Bare clone the repository

  - git clone --bare repository-link

- Step 2:  Install git LFS

  - git lfs install

- Step 3:  Get the large files details in the repository

  - git lfs migrate info --everything

- Step 4: Convert all the large files with extensions found from above command to LFS on all the branch in repository

  - git lfs migrate import --include="*.doc,*.jar,*.pdf" --everything 

- Step 5: Run GC on repository

  - git reflog expire --expire=now --all
  - git gc --aggressive --prune=now 

- Step 6: Force push the repository

  - git push origin --force --all
  - git push origin --force --tags
  
- Step 7: Login to SSH terminal

- Step 8: Inspect the repository size using ghe-repo command

  - ghe-repo org-name/repo-name du -sh objects

- Step 9: Run gc command on the same repository

  - ghe-repo-gc org-name/repo-name --prune
  
- Step 10: Inspect the repository size again

  - ghe-repo org-name/repo-name du -sh objects 

**Expected behavior**
| Sl No. | Scenario | Expected Result |  Actual Result |
| --- | --- | --- | --- | 
| 1. | Single branch (with or without tags) | Repo Size should be reduced | Repo Size was reduced |
| 2. | Multiple branches, tags without any pull request | Repo Size should be reduced | Repo Size was reduced |
| 3. | Multiple branches, tags & Open Pull Request | Repo Size should be reduced  | Repo Size was NOT reduced  |
| 4. | Multiple branches, tags & Closed Pull Request | Repo Size should be reduced  | Repo Size was NOT reduced  |

**System environment**
Running on Linux environment

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  It sounds like you are using GitHub's Enterprise Server, and that the concern is with the repo size on that system.  As this project is just for the open-source Git LFS client, I would strongly recommended getting in touch with GitHub Support and asking for their help, as they can likely provide you with advice specific to the GHES product.

From your description it sounds like a pull request in GHES introduces references that prevent the `ghe-repo-gc` command being as aggressive as you are expecting, and that's something the GHES Support people can probably provide more insight into.
