### ISSUE TITLE
"Object does not exist on the server" and I can't restore or delete it

### ISSUE THREAD

**Issue by cstout16** [git-lfs/git-lfs#4735]
**Describe the bug**
There is an object that is being reported as missing when I try to pull, and I cannot delete or restore that object. It's not an important file so if there is a way to simply delete it I would be happy with that.

When I run `git lfs pull` on my repo I see the following response:
```
[~/Documents/...rojects/Olympus](main)$ git lfs pull
[f7239efaeefbd82de33ebe18518e50de075ea4188a468a9e4991396433d2275f] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.ford.com/UnrealEngineAssets/Olympus.git/info/lfs'
[~/Documents/...rojects/Olympus](main)$ 
```

When I run `git lfs fetch --all` I see this response:
```
[~/Documents/...rojects/Olympus](main)$ git lfs fetch --all
fetch: 1 object(s) found, done.                                                                  
fetch: Fetching all references...
[f7239efaeefbd82de33ebe18518e50de075ea4188a468a9e4991396433d2275f] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.ford.com/UnrealEngineAssets/Olympus.git/info/lfs'
[~/Documents/...rojects/Olympus](main)$ 
```

And if I try to push the file up to lfs at this point I see this:
```
[~/Documents/...rojects/Olympus](main)$ git lfs push --all origin main
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://github.ford.com/UnrealEngineAssets/Olympus.git/info/lfs.locksverify true
LFS upload failed:cts:   0% (0/1), 0 B | 0 B/s                                                   
  (missing) Unreal/CarlaUE4/Plugins/QSAIPlugin/Resources/Icon128.png (f7239efaeefbd82de33ebe18518e50de075ea4188a468a9e4991396433d2275f)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: 'git config lfs.allowincompletepush true'
[~/Documents/...rojects/Olympus](main)$ 
```

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication). 
I'm running Ubuntu 20.04.2 LTS

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
[~/Documents/...rojects/Olympus](main)$ git lfs env
git-lfs/2.13.3 (GitHub; linux amd64; go 1.16.2)
git version 2.25.1

Endpoint=https://github.ford.com/UnrealEngineAssets/Olympus.git/info/lfs (auth=none)
  SSH=git@github.ford.com:UnrealEngineAssets/Olympus.git
LocalWorkingDir=/home/cstout16/Documents/UnrealProjects/Olympus
LocalGitDir=/home/cstout16/Documents/UnrealProjects/Olympus/.git
LocalGitStorageDir=/home/cstout16/Documents/UnrealProjects/Olympus/.git
LocalMediaDir=/home/cstout16/Documents/UnrealProjects/Olympus/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/cstout16/Documents/UnrealProjects/Olympus/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/cstout16/Documents/UnrealProjects/Olympus/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
[~/Documents/...rojects/Olympus](main)$ 
```

**Additional context**
Other posts from people who have had similar problems but were apparently able to resolve them
- https://stackoverflow.com/questions/64316551/git-push-was-rejected-due-to-missing-or-corrupt-local-objects-git-lfs/65869776#65869776
- https://stackoverflow.com/questions/62852772/error-when-getting-git-lfs-files-object-does-not-exist-on-the-server-404-obj

**Comment by chrisd8088** [comment]
Hey, sorry you're having trouble.  The situation where a Git LFS file is missing on the server sometimes results from a user pushing without having the Git LFS client installed on their machine.  If you can determine, perhaps from your Git repo's history, which commit added the file to the repo, you might be able to track down someone who has a copy (i.e., the person who made the commit) and who can then install Git LFS and push again to add the file to the server, or give you a copy of the file to do the same.

On the other hand, if no one has a copy of the file, you may need to remove it from your Git repo's history, and then force-push to the server.  Of course, that will change the history for everyone, so please be cautious and make sure you understand the consequences of changing the repo history.  There are some guides to doing this online, such as [here](https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history) and [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository).

I hope that helps a bit!

**Comment by paulphatngo** [comment]
Hello all,

We recently encounter an issue with git-lfs.  Here is our situation at the moment.  We migrated our code repo to GitLab from SVN a few years ago.  At the time, our GitLab didn't turn on LFS.  Our project has been working fine.  A couple of weeks ago, GitLab admin decided to turn on LFS globally and turned it on for our project as well.  After he turned it on, we have never been able to clone the project as we had been able to do in the past.  Then after we realized that we couldn't clone the project, we turned that LFS for our project off.  But we still can not clone the project.  The error we got is the following:

Downloading Deployment/Jenkins/jenkins.war (69 MB)
Error downloading object: Deployment/Jenkins/jenkins.war (9b7d9d1): Smudge error: Error downloading Deployment/Jenkins/jenkins.war (9b7d9d1fd6dce1077599a31468b1ef2ebe7b849f6d2f52f943541b944d9c29f9): LFS: Repository or object not found: https://gitlab.senate.gov/TranSAAct/transaact.git/gitlab-lfs/objects/9b7d9d1fd6dce1077599a31468b1ef2ebe7b849f6d2f52f943541b944d9c29f9
Check that it exists and that you have proper access to it

Errors logged to C:\release-lfs\transaact\.git\lfs\logs\20220202T071602.9029216.log

**Comment by bk2204** [comment]
Hey,

This isn't a bug in Git LFS.  This indicates that the data likely isn't present on your server.  That means that if you don't have that data in some clone, then the data is probably lost.  You'd want to reach out to the maintainer of the server to see if the data exists and talk to them about the next steps here.

I'm going to close this issue since it isn't a bug and involves your server returning a 404 error.

**Comment by nitinsinghit** [comment]
> 

Hi @bk2204 I would like to add few things to @paulphatngo issue. I can clone the project but git-lfs pull is not getting the files from the server. My understanding is that after enabling GitLFS and pointing to a new storage the path is changed but at the same time when i turned off the git-lfs for this particular project I am seeing the same issue. If I go back to the timeline before I enable git-lfs and clone the repo I see pointers in the jar file but not pointing anymore to previous storage. I see response above from @chrisd8088 that seems like a similar issue.

**Comment by bk2204** [comment]
Hey,

The message you're seeing above says that the server is returning a 404 error, which means that the object is not found.  This isn't an issue in Git LFS: the server said it didn't have the object and there's nothing we can do to make it hand it over.  It may really have the object and be stating that falsely, or it may really not have it at all.  But regardless, you'd need to reach out the server maintainer and talk to them about it.

**Comment by contentfree** [comment]
This does seem like a Git LFS problem. 

Trying to do a `git lfs pull` with a subrepo is returning `[945efe249b95cab5e35c311a24192161c415943e80a87458d2a6917f53119beb] Object does not exist on the server: [404] Object does not exist on the server` (for an example file)

In the original clone, `git lfs ls-files` reveals the file in question is fine: `945efe249b - hi/zulma.wav`

Looking at the Git repo (on bitbucket) shows the file exists with that OID: 
<img width="590" alt="image" src="https://github.com/git-lfs/git-lfs/assets/10958/93c16e7d-292d-4ee9-8d28-64550a4f79d6">

So… what do?

**Comment by contentfree** [comment]
_Possibly related_ is that my directory structure had a directory with parenthesis in it… `cd`ing into the directory before doing the `git lfs pull` fixed it. 🤷
