### ISSUE TITLE
Check files on remote after push

### ISSUE THREAD

**Issue by amichuda** [git-lfs/git-lfs#4745]
Is there some way to check that large files uploaded correctly after a push to a remote?

**Comment by bk2204** [comment]
Hey,

Usually that is supposed to be done by the server in the verify endpoint, if one is provided, or by the upload endpoint.  For example, GitHub's implementation currently uses Amazon S3, which checks the SHA-256 hash automatically, and it verifies the size is correct.

If you want to do a manual check, you can do a bare clone of the repository and then do `git lfs fetch --all`, which will download all of the objects, but there is no other way to do this from the client side.
