### ISSUE TITLE
when i use :git lfs pullGit can't resolve ref: "HEAD" 

### ISSUE THREAD

**Issue by zhenghan408** [git-lfs/git-lfs#4749]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by zhenghan408** [comment]
when i use :git lfs pull

Git can't resolve ref: "HEAD"

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You'll need to fill out the issue template more completely for us to offer any help.  Specifically, you need to give the output of `git lfs env` and `git config -l` (with any private information removed!)

Looking at #2662 this may be a problem on your host side of things.  Can you clone the repository?  What you do get when you run `git rev-parse HEAD`?

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back on this in a while, I'm going to close this.  If you can provide more information on what's going on, we can reopen it.
