### ISSUE TITLE
Pulling data from local git lfs repository.

### ISSUE THREAD

**Issue by antoimau** [git-lfs/git-lfs#4755]
Hello,
I have a local git lfs directory in which we have a very large dataset.
To work on it, I clone it in another place skipping the smudges:
```
$ GIT_LFS_SKIP_SMUDGE=1 git clone /data/RND/Users/antoine/data/Test /data/RnND/Users/antoine/data/bspcore-data
```

After modifying something inside `bspcore-data`, adding and committing the modification, I'd like to pull the changes from the central repository. I already added the cloned repository to the remote using `git remote add remote_1 file:///data/RnND/Users/antoine/data/bspcore-data`
```
$ /data/RND/Users/antoine/data/Test
$ git pull remote_1 master
```

However, the last command would trigger an error: `batch request: missing protocol: ""`
From the issues: https://github.com/git-lfs/git-lfs/issues/3073 https://github.com/git-lfs/git-lfs/issues/1207 or https://github.com/git-lfs/git-lfs/issues/3438 it seems this is not supported by git-lfs right?
However, it seems there are workarounds like defining a [custom transport documentation](https://github.com/git-lfs/git-lfs/issues/3438#issuecomment-448364884) or tweaking the `lfs.storage` [configuration](https://github.com/git-lfs/git-lfs/issues/3073#issuecomment-398116523) option perhaps?
I tried to understand the other issues but it's blurry for me. I don't have a lot of experience with git. If my question is not relevant, I'm sorry for that.

My question would be: Is `git-lfs` could be used to perform that kind of operation? Perhaps I'm trying to use the wrong tool.

**Git-lfs env**
```git-lfs/2.13.3 (GitHub; linux amd64; go 1.16.2)
git-lfs/2.13.3 (GitHub; linux amd64; go 1.16.2)
git version 2.24.0

Endpoint=file:///data/RND/Users/antoine/data/Test/.git (auth=none)
LocalWorkingDir=/data/RnD_Users/antoine/data/bspcore-data
LocalGitDir=/data/RnD_Users/antoine/data/bspcore-data/.git
LocalGitStorageDir=/data/RnD_Users/antoine/data/bspcore-data/.git
LocalMediaDir=/data/RnD_Users/antoine/data/bspcore-data/.git/lfs/objects
LocalReferenceDirs=
TempDir=/data/RnD_Users/antoine/data/bspcore-data/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/data/RnD_Users/antoine/data/bspcore-data/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Using a `file:///` remote is indeed supported in recent versions of Git LFS (I believe since 2.10.0).  Your `git lfs env` output didn't include the Git LFS version, so it's hard to tell what version you're using.  If it's not the latest version, you could try using that, and see whether it works for you.

**Comment by antoimau** [comment]
> Hey,
> 
> Using a `file:///` remote is indeed supported in recent versions of Git LFS (I believe since 2.10.0). Your `git lfs env` output didn't include the Git LFS version, so it's hard to tell what version you're using. If it's not the latest version, you could try using that, and see whether it works for you.

Yeah indeed, I forgot to include it. It's fixed now and the version is `2.13.3` so I should be able to make it work right?

**Comment by bk2204** [comment]
Hey,

Yes, this should work in 2.13.3.  Right now, Git LFS has an assumption that there's a single central repository, so if you have multiple different remotes, Git LFS isn't currently able to pull from other automatically.  You can fix this by running `git lfs pull remote_1 master` after the fact.

If you have just the one remote and it's still not working, can you run the `git pull` command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1` and include the output here as a code block (or, if it's large, an attached text file) so we can see what's going on?

**Comment by antoimau** [comment]
Hey,

Thank you for your reply. Given your answer, I found a solution. So inside the local central repository, I can pull from my local repository by doing:
`$ GIT_LFS_SKIP_SMUDGE=1 git pull remote_1 master`
`$ git lfs pull remote_1 master`

The first would pull the data tree but not download the files and the second would download the files. So it is what I was looking for.

Thank you again for your help.

**Comment by bk2204** [comment]
Fantastic.  Glad you got it sorted out.
