### ISSUE TITLE
Push size exceeds file size but does not end

### ISSUE THREAD

**Issue by linG5821** [git-lfs/git-lfs#4756]
![image](https://user-images.githubusercontent.com/33996782/144217597-390949fa-b71c-4676-aaf7-a81f9c282eb8.png)

**Comment by linG5821** [comment]
My file size is only 100.22 MB

**Comment by bk2204** [comment]
Hey,

Git LFS will retry when an upload fails, up to 8 times.  That will cause the issue you see here.  You can either wait for it to fail to find out what the failure is or run it with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` to see what the error is.

I'll see what I can do to add this to the FAQ.
