### ISSUE TITLE
Migrate import above size does not update .gitattributes if file is moved

### ISSUE THREAD

**Issue by jrcmramos** [git-lfs/git-lfs#4770]
**Description**
While using the migrate import tool with `--above` option, `.gitAttributes` is not updated properly if file is moved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup a repository:
    1.1. Containing 1 file with more than 1MB
    1.2. In one of the commits the same file is moved
2. Run the migrations:
```
git lfs migrate import --above=1Mb --everything --yes
```
3. Only the initial location of the file is added to the `.gitAttributes`

**Expected behavior**
`.gitAttributes` should be updated if the file is moved

**System environment**
MacOS 11.3.1
Git 2.31.1
Git LFS 3.0.1

**Comment by bk2204** [comment]
Hey,

Is the file when moved still larger than 1 MB?  We don't currently perform rename detection when moving for a couple reasons:

* We don't call out to Git to walk the history.
* Rename detection is quadratic and can fail on large repositories with many files.
* Rename and copy detection isn't always accurate and can reflect files as being renames or copies in situations when humans wouldn't agree.

If they are still larger than 1 MB, please try 3.0.2, as we've recently fixed a bug that prevents identically named files in different directories from being updated, which could be the cause of your problem.  If not, then this is behaving as expected.

**Comment by jrcmramos** [comment]
Hey @bk2204 ! 
Thanks for your comment.
Replying to your question, yes the file is still bigger than 1MB. It was just moved to other directory.
Currently we cannot use the 3.0.2 due to the performance issue, but I will retry in the next update.

**Comment by bk2204** [comment]
Since we haven't heard back here, I'm going to close this.
