### ISSUE TITLE
Permissions issue after pulling changes inside local git lfs repository

### ISSUE THREAD

**Issue by antoimau** [git-lfs/git-lfs#4775]
Hello Everyone,

It is a generic question but I couldn't find an answer on the Internet.
My team and I are using a local git lfs repository to store our test data. When a user makes a clone of it, adds data to their clone and commits it, a superuser goes into the original repository to pull the changes by doing.
```
# As superuser
$ cd <path_original_repository>
$ GIT_LFS_SKIP_SMUDGE=1 git pull <username> master
$ git lfs pull <username> master
```
It would work correctly but after both commands finish, we have weird permissions issue when we are inside the repository. If a user wants to go into the original repository we would have that kind of errors:
```
# As normal user
$ cd <path_original_repository>
Error cleaning LFS object: open <path_original_repository>/.git/lfs/tmp/207987611: permission denied
error: external filter 'git-lfs filter-process' failed
fatal: <path_to_specific_folder_in_the_repo>: clean filter 'lfs' failed
```
Note that the commands would work inside the repo but we'll keep having this message as well in the terminal.
However, we found a fix to that behavior which is to let the superuser run `git status` inside the original repository and the permissions issues would go away.

I thought it was perhaps an interesting behavior to raise here. Perhaps the workflow we're doing is somewhat wrong. 
I was wondering if someone else came across the same behavior or had any ideas of what is currently happening here?

Best,
antoimau

**Comment by bk2204** [comment]
Hey,

The best way to handle this is to set `core.sharedRepository` to `0664`, put all of the users into a single group, chown all the files to that group, chmod any existing files to have the group read and write bits, and then, if you're on Linux, to set the set-gid bit on all of the directories in the repository (but not the files).

That will cause Git and Git LFS to always create files with user and group able to read and write, and setting the setgid bit on directories means that new files and directories created inside are created with the directory's group.  (This is the default behavior on BSD and macOS, I believe, so you should only use setgid directories on Linux, where this behavior is not the default).  That should fix your permissions problems.
