### ISSUE TITLE
GH009: Git LFS object integrity could not be checked

### ISSUE THREAD

**Issue by franksNVDA** [git-lfs/git-lfs#4787]
I tried to create a branch of UE to my repo. but encounter this error. I don't know what's wrong with it.

The branch I want to clone is https://github.com/EpicGames/UnrealEngine/tree/5.0.
I cloned the branch to my local successfully but failed to push to my own repo.

I get the following error:
git push [myrepo] 5.0:UE5.0
Enumerating objects: 464754, done.
Counting objects: 100% (464753/464753), done.
Delta compression using up to 64 threads
Compressing objects: 100% (160229/160229), done.
Writing objects: 100% (447545/447545), 1.01 GiB | 12.88 MiB/s, done.
Total 447545 (delta 316913), reused 402312 (delta 281718)
remote: Resolving deltas: 100% (316913/316913), completed with 13524 local objects.
remote: Checking connectivity: 447545, done.
remote: error: GH009: Git LFS object integrity could not be checked. Please contact GitHub support.
To https://github.com/[XXXXX]/UnrealEngine.git
 ! [remote rejected]         5.0 -> Nanite/UE5.0 (pre-receive hook declined)

Can anyone helps me?

**Comment by bk2204** [comment]
Hey,

This message comes from GitHub and it means that something went wrong on their end.  You'll want to contact GitHub support as directed to see if they can help you figure out what's wrong.

**Comment by haowang1013** [comment]
@franksNVDA I'm having the same problem with UE5 now. Did you finally resolve it?

**Comment by Mercytt** [comment]
Hello, I know it is late, but I encountered this error in the last few days. Perhaps my response can help others resolve the problem. The issue arises when pushing commits containing files stored in Git LFS.

These were the steps I followed:

Switched to a new branch.

Made the desired changes in the branch.

Committed the changes.

Used the command: git lfs migrate export and included Git LFS files where changes were made:

git lfs migrate export --include="file1.ext,file2.ext,file3.ext"

Committed the changes.

Reverted the changes to the ".gitattributes" file, as it would be affected after executing the git lfs migrate export command.

Committed the new changes to .gitattribute.

Pushed all the changes.

**Comment by tigger0jk** [comment]
Adding my own experience - I ran push 3 times, first time never completed, second time gave me a GH010 warning (only validated some of the LFS objects) and a GH009 error (LFS object integrity could not be checked), third push seemed to work.

```
$ git lfs migrate import --include="*.mp4" --include="*.wav" --verbose --everything

$ git push --force
Uploading LFS objects: 100% (12108/12108), 2.1 GB | 0 B/s, done.
Enumerating objects: 21621, done.
Counting objects: 100% (21621/21621), done.
Delta compression using up to 12 threads
Compressing objects: 100% (20510/20510), done.
Writing objects: 100% (21621/21621), 811.00 MiB | 12.70 MiB/s, done.
Total 21621 (delta 2047), reused 16366 (delta 1090), pack-reused 0

# push seems to not be doing anything anymore, stalls for 20 minutes, I cancel it

$ git push --force
Uploading LFS objects: 100% (12108/12108), 2.1 GB | 0 B/s, done.
Enumerating objects: 21621, done.
Counting objects: 100% (21621/21621), done.
Delta compression using up to 12 threads
Compressing objects: 100% (20510/20510), done.
Writing objects: 100% (21621/21621), 811.00 MiB | 18.30 MiB/s, done.
Total 21621 (delta 2046), reused 16366 (delta 1090), pack-reused 0
remote: Resolving deltas: 100% (2046/2046), done.
remote: warning: GH010: Your push referenced at least 12108 Git LFS objects, but we only validated a random sample of 10000. It is very likely that the remaining files have been uploaded successfully too.
remote: error: GH009: Git LFS object integrity could not be checked. Please contact GitHub support.
To https://github.com/<my repo>
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/<my repo>'

$ git push --force
Uploading LFS objects: 100% (12108/12108), 2.1 GB | 0 B/s, done.
Enumerating objects: 21621, done.
Counting objects: 100% (21621/21621), done.
Delta compression using up to 12 threads
Compressing objects: 100% (20510/20510), done.
Writing objects: 100% (21621/21621), 811.00 MiB | 14.27 MiB/s, done.
Total 21621 (delta 2047), reused 16366 (delta 1090), pack-reused 0
remote: Resolving deltas: 100% (2047/2047), done.
remote: warning: GH010: Your push referenced at least 12108 Git LFS objects, but we only validated a random sample of 10000. It is very likely that the remaining files have been uploaded successfully too.
To https://github.com/<my repo>
 + 91bed550...d5b1710f main -> main (forced update)
```
