### ISSUE TITLE
Backwards compatible .lfsconfig for version 3.0 to handle leading / issue

### ISSUE THREAD

**Issue by Egwor** [git-lfs/git-lfs#4799]
Hi
I'm using bitbucket and they've not added the support for the removal of the leading / from the repo. Some users are using GIT LFS 3 and others are using GIT LFS 2.x and we need a way to support both versions until Bitbucket provides fixes and they're rolled out.

I initially added a .lfsconfig file into the repo which contained:
```
[lfs]
   url = server.hostname.com:port:project/repo
```

This worked for GIT-LFS 3.0 but for the 2.x clients this caused errors (`batch request: missing protocol`). I tried adding the `https://` prefix but that lead to `Repository or object not found` errors).

Is there a recommended way to work around this issue that is backwards compatible with GIT LFS 2.x?

**Comment by chrisd8088** [comment]
Hey, sorry you're having trouble.  I'm not aware of any alternatives, myself, since this is an incompatible change between major versions, but you could check through some pre-existing issues like #4672 and see if any tips there are of use.
