### ISSUE TITLE
`git-lfs migrage export` doesn't work on git-lfs 3.0.2

### ISSUE THREAD

**Issue by AngelOnFira** [git-lfs/git-lfs#4805]
**Describe the bug**
On git-lfs 3+, I can't run `git-lfs migrate export` on a large codebase. I use this to remove all LFS pointers to push a mirror to Github, since Github has limits on LFS usage, and we've been told by Github to just check in the files instead.

This used to work fine in [an Action](https://github.com/veloren/veloren/blob/7bb038e47435b0786781d6062bd7ddb6e35eaad7/.github/workflows/mirror.yml), but stopped working on December 2nd. I did

Related repo: https://github.com/veloren/veloren

**To Reproduce**
1. Make sure you have git-lfs 3.0.2
2. (Not sure if this is needed, but I have it in my CI script) in an empty directory, run `git lfs install`
2. Clone `https://gitlab.com/veloren/veloren.git` (the main repo) into this empty directory
3. Enter the directory, run `git lfs uninstall`
4. Run `GIT_TRACE=1 git lfs migrate export --include="*" --everything`

**Expected behavior**
This shouldn't complete, yet will show it working on the same files multiple times. Our CI runners would time out after 6 hours due to this

**System environment**
Github Actions on `ubuntu-20.04`

**Output of `git lfs env`**
```
 git-lfs/3.0.2 (GitHub; linux amd64; go 1.17)
git version 2.34.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Additional context**
We resolved this by [manually installing `git-lfs`](https://github.com/veloren/veloren/blob/master/.github/workflows/mirror.yml)

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Would you mind trying with Git LFS 3.0.1 as well, in case this is the same issue as #4750?  Or did you already try that?

**Comment by Ashsegov23** [comment]
No I didn’t 

Ashley Segovia

**Comment by AngelOnFira** [comment]
> Hey, I'm sorry you're having trouble. Would you mind trying with Git LFS 3.0.1 as well, in case this is the same issue as #4750? Or did you already try that?

I'll give this a try :+1:

**Comment by AngelOnFira** [comment]
Yup, looks like 3.0.1 works just fine. Will close in favor of #4750.
