### ISSUE TITLE
git lfs migrate import --everything ignores malformed references silently

### ISSUE THREAD

**Issue by wuhaochen** [git-lfs/git-lfs#4810]
**Describe the bug**
We were trying to migrate a repo to git lfs which had a malformed local reference:
`refs/head/some-description` instead of `refs/heads/some-description`
After running `git lfs migrate import everything` that reference was ignored silently. Then when we tried to push it to the remote, it failed because we still have files larger than the size limit in that reference.

**Root cause**
In this part of the code https://github.com/git-lfs/git-lfs/blob/ee3088d4804bd2b699eb6a76aa1318d1d2283ed6/commands/command_migrate.go#L193-L213
The reference was recognized as `RefTypeOther` and got skipped because it doesn't fit the `case "merge-requests", "pull", "pull-requests"`

**Questions**
I understand this is more of an user issue that caused by crazy input but when we are trying to automate things and migrate code bases in batch, errors like this is very hard to debug.
Would be better to give some warnings on the refs that was ignored?
Also is there any concern to just try to migrate all the refs with `RefTypeOther`?

**Comment by bk2204** [comment]
Hey,

I think my preference here would be to just migrate everything that isn't a special ref to Git (that is, everything that has at least three levels that's not `refs/notes`, `refs/bisect`, or `refs/replace`), since that's what we've documented our behavior to be for `--everything`.  I'm a little concerned that we may be missing some sort of special ref to Git and then we'd end up with undesirable behavior, though.

Thoughts on the best approach here, @git-lfs/core?

**Comment by wuhaochen** [comment]
I would agree with migrating everything.
I'm not familiar with all the special refs in git but I'm also not sure if migrating special ref to git is actually going to cause any issue.   Even if so, what if these special refs include large files? Is that possible to also support them?
I would even suggest not to have the three levels constraint, the refs being filtered are returned from `git for-each-ref` from https://github.com/git-lfs/git-lfs/blob/ee3088d4804bd2b699eb6a76aa1318d1d2283ed6/git/git.go#L1217, if git decides to return a ref that are not three levels, it probably should also be processed.

The other option could be to introduce more parameters to differentiate actually migrating everything vs migrating currently what `--everything` is doing.

**Comment by chrisd8088** [comment]
I wondered at first whether we could output interactive prompts ("do you want to migrate ...?") but that might break the workflow of folks who are using the migration command in scripts.

I would also agree that `--everything` should migrate, well, everything, if it possibly can.

I don't know if `refs/stash` is considered a "special ref", but it's maybe worth nothing here too.

So I guess my instinct is that we ought to migrate as much as possible, and that might mean simply going through *all* refs, regardless of whether they have some special meaning to Git.  For instance, notes blobs are [documented](https://git-scm.com/docs/git-notes#_examples) to be regular blobs and potentially binary, even if that means normal Git tools won't support them and custom tools would be needed.  So arguably we should be handling those as well.

Alternatively, if we hit too many hurdles trying to support all refs, we could and should just document that `--everything` actually means only refs matching specific patterns.

**Comment by capyvara** [comment]
Any news on that?

**Comment by bk2204** [comment]
This hasn't been implemented, but it is planned for 3.3.0.  We're of course happy to accept a patch if folks would like to see it fixed sooner.

**Comment by bk2204** [comment]
I believe this has been fixed in #5045 and it will be included in the next release.
