### ISSUE TITLE
git-lfs for AIX

### ISSUE THREAD

**Issue by Crucialer** [git-lfs/git-lfs#4812]
**Describe the issue**
Does git lfs only work on AIX 7.2 and above?
Is there a git lfs installation package running on AIX7.1?

**System environment**
AIX7.1

**Comment by bk2204** [comment]
Hey,

We require Go 1.13 at the moment, so [according to the Go 1.12 release notes](https://go.dev/doc/go1.12), only AIX 7.2 and up are supported.  You could _try_ compiling with gccgo, but I don't think the runtime will be sufficiently correct for AIX 7.1, so I think it's unlikely that it will work.

Sorry for the bad news.
