### ISSUE TITLE
bigfile error always

### ISSUE THREAD

**Issue by zkailinzhang** [git-lfs/git-lfs#4816]
**Describe the bug**
https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage
git lfs track "*.psd"
git add path/to/file.psd
git commit -m "add file.psd"

D:\code\>git push
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 1
info: please complete authentication in your browser...
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 104.73 MiB | 1010.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: Trace: e00cbf675efc908b5282dd3ea5cb1b38f0074f6c5768
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File xxx-boot-system-2.2.0.jar is 116.31 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/xx.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/xx.git'

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Looking at this it seems to me that you might not be adjusting the example setup instructions to suit your actual repository contents.

You're getting a reply from GitHub that your repo contains a too-large file, `xxx-boot-system-2.2.0.jar`.  But in your notes above you just quote the example command `git lfs track "*.psd"`, which would only make Git LFS track `*.psd` files, not `*.jar` files.

Also, you don't mention whether this file already exists in your repository, or if you're adding it later.  If you're trying to add Git LFS to an existing repository with a Git commit history that includes large files, you'll need to "migrate" your repository and its history before trying to push it up to a server that requires Git LFS for large files.  See the instructions in the `git-lfs-migrate` [manual page](https://github.com/git-lfs/git-lfs/blob/ee3088d4804bd2b699eb6a76aa1318d1d2283ed6/docs/man/git-lfs-migrate.1.ronn) for some advice there.

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back on this issue, I'm going to close it.  If you can provide more information about the problem you're seeing, we can reopen it if necessary.
