### ISSUE TITLE
This doesn't look like a helpful pull request, and there's no description, so I'm going to close it.

### ISSUE THREAD

**Issue by Filipova96** [git-lfs/git-lfs#4818]
This doesn't look like a helpful pull request, and there's no description, so I'm going to close it.

_Originally posted by @chrisd8088 in https://github.com/git-lfs/git-lfs/issues/4817#issuecomment-1013630667_

**Comment by chrisd8088** [comment]
Again, this is not a helpful issue report.  If you continue with these submissions we may have to block your ability to create them, which would be a shame and is not an action we want to take.  Please stop submitting or commenting without adding anything of value.
