### ISSUE TITLE
Possibility to track specific files regardless of folder location?

### ISSUE THREAD

**Issue by Hoodad** [git-lfs/git-lfs#4824]
**Describe the issue**
Is there a way to track specific file regardless of folder? The example file could be called _LightningData.asset_ and I want to treat each  specific filename the same regardless of what folder it happens to recide in.

**Additional context**
Example folder structure

/Scenes/Test/LightningData.asset  // Should be tracked
/Settings.asset                              // Not tracked using Git-LFS
/Scenes/Foo/LightningData.asset  // Should be tracked

**Comment by bk2204** [comment]
Hey,

You can already do this by specifying `LightningData.asset` as the pattern to track.  If the path has no slashes in it, then it applies to files anywhere in the repository.
