### ISSUE TITLE
How to download a data set based on a pointer file

### ISSUE THREAD

**Issue by silkekaiser** [git-lfs/git-lfs#4830]
My problem is very basic - I have obtained a pointer file with the information
version: https://git-lfs.github.com/spec/v1
oid: sha256:919dc2c227228(folllowed by other numbers)
size: 330454481

I am new to git and all I want to, is to download this data set. What are the commands that I would have to type in order to do this or which steps to follow?

I am thankful for any advice!

**Comment by bk2204** [comment]
Hey,

If this is in a repository, you should be able to run `git lfs install` on your system and then check out the files by using `git lfs pull`.  In the future, LFS files will be pulled down automatically after you've run `git lfs install` once.

If it's not in a repository, then you'll have to find the LFS server and [make your own API request](https://github.com/git-lfs/git-lfs/tree/main/docs/api) to download it.  The pointer file doesn't tell you anything about the server on which the LFS file is located, only the object that's being referenced.

**Comment by ShaoTengLiu** [comment]
Could you please tell me how to find the LFS server?

**Comment by bk2204** [comment]
There's no way to determine that from the contents of the repository.  You'd need to know that information out of band.

**Comment by wurunbiao162** [comment]
I run this code phyla1 <- readRDS("git_ASV_table.RDS") in my R software, it says unknown input format.

**Comment by bk2204** [comment]
If you've cloned the repository, you need to run `git lfs install` and then `git lfs pull` to update the code and check out the large files.  (That requires that you've installed Git LFS already.)  If you're getting the file from somewhere else, you need to clone the repository instead of acquiring the plain file, or get a version that has the large LFS files instead of the pointer file.

If you're still having a problem, please open a discussion instead of commenting on a closed issue.

**Comment by KPavan754** [comment]
> My problem is very basic - I have obtained a pointer file with the information version: https://git-lfs.github.com/spec/v1 oid: sha256:919dc2c227228(folllowed by other numbers) size: 330454481
> 
> I am new to git and all I want to, is to download this data set. What are the commands that I would have to type in order to do this or which steps to follow?
> 
> I am thankful for any advice!

Bro did you got the solution
