### ISSUE TITLE
no choice for mac arch type on git-lfs.github.com

### ISSUE THREAD

**Issue by tecandrew** [git-lfs/git-lfs#4836]
**Describe the bug**
Only `darwin-amd64.zip` is listed as the only option on https://git-lfs.github.com

**To Reproduce**
1. Go to https://git-lfs.github.com/ while on Mac (M1)
2. Click download
3. Check `.zip` file to see it is `amd64`

**Expected behavior**
A choice between `darwin-arm64` and `darwin-amd64`

**System environment**
macOS Apple M1

**Comment by chrisd8088** [comment]
Hey, thanks for pointing this out.  From my limited knowledge, there isn't a handy way in JavaScript to detect whether a Mac is running on Apple Silicon or not, so we may not be able to offer the correct download option, only a choice as you suggest.

That said, I'm not sure we have anyone in the Git LFS core team who are proficient enough in Web scripting and CoffeeScript to quickly make the necessary changes.  I believe the relevant bits in the Web site code are [here](https://github.com/git-lfs/git-lfs.github.com/blob/a909816fd0509efabfaddabfc9d7c21d44da8dc0/_includes/home/hero.html#L10-L16) and [here](https://github.com/git-lfs/git-lfs.github.com/blob/a909816fd0509efabfaddabfc9d7c21d44da8dc0/js/_scripts/main.coffee#L11-L15).

If anyone happens to have a patch for that repo, that would be great; in the meantime, we'll keep this on the backlog.
