### ISSUE TITLE
git lfs not working as it should to push complete folder to github?

### ISSUE THREAD

**Issue by pratikchhapolika** [git-lfs/git-lfs#4837]
I have a project folder in my local having Deep learning models inside it. I want to push it to `GitHub` by creating new repository.

Here are the steps that I have taken:

Went to my GitHub account and created New Repo with name `DeepL_models` and only selected `ReadMe` and `Private` repository.

Then I cloned this repo using:

`git clone ssh_link`

After this step I went inside this `cloned folder` and dragged and dropped my model folder inside it:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/umacl.png

The commands that I type after this are:

    pc@LM-BGL-40510 Model % git remote
    origin
    pc@LM-BGL-40510 Model % git branch
    * master

    git lfs install
    Updated git hooks.
    Git LFS initialized.

    git push -u origin master
    Branch master set up to track remote branch master from origin.
    Everything up-to-date

**But why I am getting `Everything up-to-date`?**

To track the complete folder `model` :
    
    git lfs track *

    git commit -m "Adding Model"  
    git push origin master

Locking support detected on remote "origin". Consider enabling it with:

    Counting objects: 170, done.
    Delta compression using up to 16 threads.
    Compressing objects: 100% (166/166), done.
    Writing objects: 100% (170/170), 1.30 GiB | 1.88 MiB/s, done.
    Total 170 (delta 99), reused 0 (delta 0)
    remote: Resolving deltas: 100% (99/99), done.

    remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
    remote: error: File Model/exports/dl_model/flax_model.msgpack is 475.54 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
    remote: error: File Model/exports/dl_model/pytorch_model.bin is 475.57 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
    remote: error: File Model/exports/unbiased-toxic-roberta/pytorch_model.bin is 475.62 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
    remote: error: Please contact github_support@***.com
    To github.****.pc/Model.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'git@github.***.pc/Sexually_Explicit.git'

I have installed `git lfs ` but still getting this error.
**Also I have been asked password many times?**

**Comment by bk2204** [comment]
Hey,

There are a couple issues here.  First, you don't actually want to track all files like that, because that will result in your `.gitattributes` being tracked, which is likely to be a problem.

Second, you need to add the files after using `git lfs track` to track files.  If they're already in your history, running `git lfs track` doesn't rewrite your history.  To do that, you need to do `git lfs migrate import --everything --include="Model/"` (if what you want to track is things under `Model/`; otherwise, change it to whatever you want).

**Comment by pratikchhapolika** [comment]
> Model/exports/dl_model/flax_model.msgpack

Thank you @bk2204 

If I get you right then first I need to do `track files` using `git lfs track` and then add those files to folder. By add you mean `git add . `

If I need to track particular file: `Model/exports/dl_model/flax_model.msgpack`

I can write: `git lfs migrate import --everything --include="Model/exports/dl_model/flax_model.msgpack/"`

**Comment by bk2204** [comment]
You first need to track files, then add, yes.  `git add .` will be sufficient.  If you need to track a particular file, you can do by specifying that name in `--include`, but you should not suffix it with a slash, since that won't match files.

In your case, since these files are already committed, you should do this:

```
$ git lfs migrate import --everything --include="Model/**"
```

That will match all your model files.

If you had done this before committing, you could have done this:

```
$ git lfs track "Model/**"
$ git add .
$ git commit
```

**Comment by pratikchhapolika** [comment]
> You first need to track files, then add, yes. `git add .` will be sufficient. If you need to track a particular file, you can do by specifying that name in `--include`, but you should not suffix it with a slash, since that won't match files.
> 
> In your case, since these files are already committed, you should do this:
> 
> ```
> $ git lfs migrate import --everything --include="Model/**"
> ```
> 
> That will match all your model files.
> 
> If you had done this before committing, you could have done this:
> 
> ```
> $ git lfs track "Model/**"
> $ git add .
> $ git commit
> ```

I followed your steps but was not able to see files in Github repo after push.

```
pc@40510941 tcm_se % git push origin master

Enter passphrase for key '/Users/pc/.ssh/id_ed25519': 
Enter passphrase for key '/Users/pc/.ssh/id_ed25519': 
Enter passphrase for key '/Users/pc/.ssh/id_ed25519': 
Enter passphrase for key '/Users/pc/.ssh/id_ed25519': 
Enter passphrase for key '/Users/pc/.ssh/id_ed25519': 
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://github.****.com/CSP/tcm_se.git/info/lfs.locksverify true
Connection to github.****.com closed by remote host.                                                                                                                                                                                                        
Uploading LFS objects: 100% (9/9), 999 MB | 387 KB/s, done.        
```

**Comment by pratikchhapolika** [comment]
> It's probably because when you ended up `git lfs migrate import`, it rewrote history, and that generally requires a force push.

Thank you @bk2204 . One last issue is why its asking`Enter passphrase for key` 5 times. How can I disable it?

**Comment by bk2204** [comment]
You can start an ssh-agent and add your key.  That would look like this (in a POSIX shell):

```
eval $(ssh-agent -s)
# Replace the following with the path to your private key if it differs.
ssh-add ~/.ssh/id_ed25519
```

Then you won't be prompted.

If you're using a different type of shell (e.g., PowerShell on Windows), you'll have to search for that case.
