### ISSUE TITLE
BitBucket with git-lfs: HTTPs (and perhaps SSH) prompts password multiple times... and eventually succeeds...

### ISSUE THREAD

**Issue by ChameleonDevil** [git-lfs/git-lfs#4840]
**Describe the bug**
I don't know where to report/ask advise for BitBucket specifically.  I am reporting it here, perhaps someone can assist me that also work with BitBucket and git-lfs.

A new repository that uses Large files (and `git install lfs` and LFS files tracked) successfully logs in on `git pull` before LFS files are there, but any `git push -u <remote> <branch>` prompts for password, and on the 4th prompt of typing the password again again the repository will start pushing the files to LFS.

I tried this after always giving up after two tries, and assuming it doesn't want to authenticate, even though the same login will work for non-lfs repositories immediately.

I would like to know why it 'ignores' the first 3 logins, and the 4th login passes?
Is there anything I need to specifically do to make `git-lfs` work with BitBucket?

**To Reproduce**
1. Clone the BitBucket repository.
2. Install lfs : `git lfs install`
3. Track LFS files you want to push: `git lfs track *.tar.gz`
4. `git checkout -b NewBranch`
4. Add generated `.gitattributes`: `git add .gitattributes`
5. Add LFS file: `git add <file.tar.gz?>`
6. `git commit -m "Added LFS files"
7. `git push -u <remote> NewBranch`
8. Prompt for password ... _fails_
9. Prompt for password ... _fails_
10. Prompt for password ... _fails_
11. Prompt for password ... **_SUCCEEDS!!_**

_Prompts below:_
````
Password for 'https://<x>@bitbucket.org':
Password for 'https://<x>@bitbucket.org':
Password for 'https://<x>@bitbucket.org':
Password for 'https://<x>@bitbucket.org':
Uploading LFS objects: 100% (4/4), 987 MB | 8.5 MB/s, done.
````

**Expected behavior**
A successful first login of BitBucket when using git-lfs.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**

- New added **(after first commit)** files to be pushed will ask 2/3/4 times for login

- Followed these articles:
[Use git lfs with BitBucket](https://support.atlassian.com/bitbucket-cloud/docs/use-git-lfs-with-bitbucket/)
[Troubleshooting LFS with BitBucket](https://support.atlassian.com/bitbucket-cloud/docs/troubleshoot-git-lfs-in-bitbucket/)

**Comment by bk2204** [comment]
Hey,

Could you run the push like so: `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push <remote> NewBranch` and include the output here as a text file attachment?  That will help us figure out what's going on.

Also, can you run `git lfs env` and include the output here as a text block so we know what version of Git and Git LFS you're using?  That's often very important in our case, since it impacts how credentials get loaded.  `git config -l` is also helpful since it tells us if you have any credential helpers set up.

**Comment by bk2204** [comment]
Also, you may want to see if setting `lfs.cachecredentials` to `true` works for you in this case as outlined in https://github.com/git-lfs/git-lfs/issues/3318#issuecomment-430803103.

**Comment by ChameleonDevil** [comment]
Hi, thank you for the replies, I have only noticed these now sorry :(  Once I work with that LFS repo again I will have a look and report back.

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back on this in over a month, I'm going to close it.  If you can provide the required information, we can look into it further.
