### ISSUE TITLE
Enabling GitLFS causing build breaks/ LFS files on download giving 404 on existing repository

### ISSUE THREAD

**Issue by nitinsinghit** [git-lfs/git-lfs#4845]
**Describe the issue**
We have a repository with `.gitattributes ".jar, .war and .zip"` on premise GitLab. When this repo was created, GitLFS was not enabled. After I enabled GitLFS, all these files in `.gitattributes ".jar, .war and .zip"` are marked as LFS. Issue we are facing that none of these files are pointing to the previous path and our builds are failing. When we click on any of the LFS file we get `404 error`. Can some guide how I can fix this? I tried disabling GitLFS for that specific repository but that is also not working.

**System environment**
`Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)`
`CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos`
`Kernel: Linux 4.18.0-348.2.1.el8_5.x86_64`
`Architecture: x86-64`
 We are using Gitlab version 14.1.2 using omnibus installation

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; darwin amd64; go 1.17.2)
git version 2.34.1

Endpoint=https://gitlab.senate.gov/TranSAAct/transaact.git/info/lfs (auth=none)
  SSH=git@gitlab.senate.gov:TranSAAct/transaact.git
LocalWorkingDir=/Users/nitinsingh/projects/transaact
LocalGitDir=/Users/nitinsingh/projects/transaact/.git
LocalGitStorageDir=/Users/nitinsingh/projects/transaact/.git
LocalMediaDir=/Users/nitinsingh/projects/transaact/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/nitinsingh/projects/transaact/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/nitinsingh/projects/transaact/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/Cellar/git/2.34.1/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
As I mentioned above before in Gitlab 14.1.2 version GitLFS was disabled by default so existing repository using git attributes files must have been stored like others. Enabling must have caused the pointers mess up. This is my first time dealing with LFS. Any help will be very appreciated.

**Comment by bk2204** [comment]
Hey,

I'm not that familiar with GitLab, but it sounds like you may not have pushed the LFS files to the server.  If that's the case, then you'd want to do `git lfs push --all` to make sure that any LFS files that are on your local system have been pushed, and if others have been contributing and not pushed their files, then they should also do the same.

You can see if the files really are LFS files by running `git lfs ls-files` on your repo, which will show a `*` for a full Git object and a `-` for an LFS pointer.  If they're full objects but your `.gitattributes` marks them as `filter=lfs`, then you should either convert them with `git lfs migrate import --no-rewrite` or remove those entries in the `.gitattributes` file.

**Comment by nitinsinghit** [comment]
> 

Hi @bk2204 developer did commit and pushed all the files before the GitLFS was enabled (with new storage path). I am not sure how GitLFS work if repository containes `.gitattributes` and files like `war, jar and zip`. Assuming if LFS is not enabled they will get treat as normal files. Problem started as soon as we enable GitLFS on repo which contained LFS files and `.gitattributes`. is there a way that developer can untrack gitLFS files and re commit to the new lfs-storage path?

**Comment by bk2204** [comment]
Hey,

Git LFS doesn't actually care what the files are in `.gitattributes`.  Any suitable patterns are acceptable.  Now, `war, jar, and zip` is not a valid pattern; I assume what you have in your `.gitattributes` is something like this:

```
*.jar filter=lfs diff=lfs merge=lfs -text
*.war filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
```

I don't know what happens if Git LFS is not enabled on a GitLab server, since I don't use GitLab.  On GitHub, it fails with an error message saying that LFS files are not enabled and the push should fail.

If the problem is that you've enabled Git LFS for the first time on your GitLab server, then, in conjunction with the fact that you're receiving a 404 error, it sounds like a server problem, and you'd need to talk to the party who maintains your server.  The client is merely receiving a message that the server doesn't have the object and reporting the error in that case; there's nothing we can do to force the server to return the object to us.
