### ISSUE TITLE
--skip-smudge: files stay as pointer when checkout-ed

### ISSUE THREAD

**Issue by dhedde** [git-lfs/git-lfs#4852]
Hi !

**Describe the issue**
I have installed lfs with --skip-smudge. According to the doc it disables auto-downloading of files when cloning/pulling. So I issue `git lfs pull` to download files.
But then what I observe is when I change branches (`git checkout`), lfs tracked files are checkout-ed as pointers and I need to issue git `lfs pull` also to replace them by files (even if that does not download anything because I've already downloaded them previously).
Is that the expected behavior ?

I tried to remove the `--skip` in the config `filter.lfs.process`, which seem to work. But I don't know if that's really a solution ?
Also is there a command which display the fact that a lfs tracked file lies as pointer in the working tree ? (AFAIK `git lfs status` does not tell anything about that)

**System environment**
archlinux

**Output of `git lfs env`**
(several remotes and it is a submodule)
```
git-lfs/3.0.2 (GitHub; linux amd64; go 1.17.2)
git version 2.34.1

Endpoint (foo)=https://foo.example.com/foo.git/info/lfs (auth=none)
  SSH=git@git.example.com:foo.git
Endpoint (origin)=https://git.example.git/bar/info/lfs (auth=none)
  SSH=git@git.example.com:bar.git
LocalWorkingDir=/work/vp
LocalGitDir=/work/.git/modules/vp
LocalGitStorageDir=/work/.git/modules/vp
LocalMediaDir=/work/.git/modules/vp/lfs/objects
LocalReferenceDirs=
TempDir=/work/.git/modules/vp/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/work/.git/modules/vp/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
Thanks for any feedback,
Damien

**Comment by bk2204** [comment]
Hey,

This is expected.  The `--skip` option tells Git LFS not to check out LFS files when Git invokes it.  Git invokes it any time it's going to check out files in the working tree, whether that's after a clone or fetch, or whether it's after a checkout.  If you don't want that behavior, then you want to remove the `--skip` flag so that when Git LFS is invoked by Git it downloads them and checks them out.  If you already have the objects on disk, then no downloads will occur in this case.

Hopefully that explains what's going on here.
