### ISSUE TITLE
`git checkout-index` doesn't honor `GIT_LFS_SKIP_SMUDGE=1` or `--skip`

### ISSUE THREAD

**Issue by danny0838** [git-lfs/git-lfs#4858]
**Describe the bug**
`GIT_LFS_SKIP_SMUDGE=1` and `--skip` for smudge and filter-process are ignored for `git checkout-index`.

**To Reproduce**
1. Download and unzip the reduced test repo: [test - git-lfs filter-process.zip](https://github.com/git-lfs/git-lfs/files/8008170/test.-.git-lfs.filter-process.zip)
2. CD to the work tree.
3. Run `git checkout-index -fa`, and `myfile1.txt` and `myfile2.txt` are **actual contents**. Remove `myfile1.txt` and `myfile2.txt`. 
4. Run `GIT_LFS_SKIP_SMUDGE=1 git checkout-index -fa`, and `myfile1.txt` and `myfile2.txt` are **actual contents**. Remove `myfile1.txt` and `myfile2.txt`. 
5. Run `git checkout -- .`, and `myfile1.txt` and `myfile2.txt` are **pointer files**. Remove `myfile1.txt` and `myfile2.txt`. 
6. Run `git config --local filter.lfs.smudge ''; git config --local filter.lfs.process ''; git config --local filter.lfs.required false; git checkout-index -fa`, and now `myfile1.txt` and `myfile2.txt` are **pointer files**.

The results of steps 3 and 4 are unexpected. The checkout files are expected to be pointer files instead.

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.35.1.windows.2

LocalWorkingDir=D:\Projects\test\git\test - git-lfs filter-process
LocalGitDir=D:\Projects\test\git\test - git-lfs filter-process\.git
LocalGitStorageDir=D:\Projects\test\git\test - git-lfs filter-process\.git
LocalMediaDir=D:\Projects\test\git\test - git-lfs filter-process\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\Projects\test\git\test - git-lfs filter-process\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\Projects\test\git\test - git-lfs filter-process\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  It looks like `git checkout-index` doesn't use the delayed smudge and clean functionality, and as a result, we'll try to smudge the data in the working tree if it already exists on disk.  This would only be seen in this case or or ancient versions of Git.

I think I have a patch, which I'll try to submit relatively soon.  Be aware that even when I do so, `git checkout-index` will necessarily be slower than `git checkout` since the delayed checkout code isn't used.

**Comment by danny0838** [comment]
@bk2204 Does this patch fix the issue that the command line arguments `--skip` in the config be ignored?

**Comment by bk2204** [comment]
> @bk2204 Does this patch fix the issue that the command line arguments `--skip` in the config be ignored? (as step 2 has illustrated)

Yes, it does.  The value is set the same way outside of the code I've mentioned, so it does indeed work correctly.
