### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by TheKidLu5** [git-lfs/git-lfs#4861]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

bugs closed

**Comment by bk2204** [comment]
Hey,

It doesn't look like you filled out the issue template to describe the problem, so I'm going to close this.  If you edit this issue to fill out the issue template fully, we can reopen it.
