### ISSUE TITLE
Avoid overwriting unchanged hooks

### ISSUE THREAD

**Issue by RuxandraM** [git-lfs/git-lfs#4865]
**Describe the issue**
We came across a timestamp issue regarding git hooks. We have a custom set-up for our git repository, where we changed `.git/hooks` to be a symlink pointing to a tracked folder inside the repository. This is because we want to track the differences to the hooks in the repo. When `filter-process` is triggered, git-lfs is trying to overwrite the hooks. The files are identical, so git-lfs is overwriting them with the same contents, resulting in a timestamp change. This is picked up as a difference by commands like `git diff-files`. Normally, this is not a problem because we update the index, however, I've seen cases of the `filter-process` being triggered right after `git update-index --refresh`, or after `git status`. So we noticed that we were updating the index, then immediately saw differences that were not expected, because the timestamp of the hook files was changed.

I tried to reproduce this [here](https://github.com/RuxandraM/lfs_hooks) 

Any thoughts? Is it possible to skip writing the hook files if they are identical? I understand git-lfs checks for the contents anyway (for not overwriting custom hooks).

**System environment**
Running on MacOS, git-lfs/2.13.3, git version 2.23.0

**Comment by bk2204** [comment]
Hey,

Yes, we can look into such a change.  Typically, the reason we haven't considered this case in the past is that Git intentionally doesn't allow hooks to be shipped as part of the repository for a few reasons:

* This configuration allows arbitrary code execution on every developer system by every user who can write to the repository.  Therefore, it's only a suitable configuration if all such users are trusted by all developers.
* This disallows users from using custom hooks, such as `commit-msg` hooks, to help them write their commit messages or do other tasks.
* If you're trying to use hooks to prevent users from making certain changes, [they can be trivially bypassed](https://git-scm.com/docs/gitfaq#restrict-with-hooks).  If you want to perform tests or checks on the code, those changes belong in a CI system or a server-side `pre-receive` hook.

However, if you're certain none of these issues apply to your case, it might be okay to do this.

In the meantime, before we get around to this, you can fix the problem by simply adding a newline to your hooks (at neither the beginning nor end of the hook).  If the hooks don't match any existing hook, they won't be overwritten without `--force`.

**Comment by RuxandraM** [comment]
Thanks for the reply!

Unfortunately, none of those cases apply to us. We have a custom repository setup, and the hooks are doing functional changes to the repository that cannot be done on the server. In some ways, the hooks are used to allow the user to make changes to the repository, which is why it is important for us to keep them tracked.

The new line mid-file works great, thanks! I had tried adding an empty line at the end of the file, but, as you said, that didn't work!
