### ISSUE TITLE
Question(s) about locking in Git LFS compared to non-DVCS

### ISSUE THREAD

**Issue by jdx-john** [git-lfs/git-lfs#4882]
Coming from a background of TFS/TFVC and SVN, locking is something that I'm used to being managed on the central server. You lock a file on the server, everyone else can see it's locked, the server manages locks on the repo.

So how does this translate to a DVCS like Git, with Git LFS? The thing we all get used to with Git is that nothing you do on your repo affects another repo until you push upstream. But it doesn't seem like I have to push after I lock a file... in fact I tested by cloning the same repo twice onto my PC and I can see locking a file in one repo affects the other when I run `git lfs locks`. 

How does this actually work, that lock status is communicated then? I'm guessing that when I run `lock`/`unlock`/`locks` it checks the upstream repo first, then makes changes. I have tested locking in Repo1 then trying to lock the same file in Repo2 and I got this perplexing error - I'm glad it fails but why this message:

```
>git lfs lock Test.png
Locking Test.png failed: Client error &{%!!(string=http) %!!(string=) %!!(*url.Userinfo=<nil>) %!!(string=<redacted>:8080) %!!(string=/tfs/<redacted>/_git/gitlfstest.git/info/lfs/locks) %!!(string=) %!!(bool=false) %!!(string=) %!!(string=) %!!(string=)}s(MISSING) from HTTP 409
```

We have some binary files that are frequently modified and it's imperative two people do not work on them at the same time, or work will be lost. So I'm keen to understand the way locking works and how strict it is, in order to document the process as we move from TFVC to Git+LFS for these files.
It's not helped that as far as I can see, our Git host (Azure DevOps) does not provide any way to see which files are locked from the server (I think GitHub does show this?)

**Comment by bk2204** [comment]
Hey,

The typical way that this is done with Git LFS is with the `lockable` flag.  You can track the files with `git lfs track --lockable` (or edit `.gitattributes` to add the `lockable` attribute to the file patterns).  Once you've done that, assuming you haven't set `lfs.setlockablereadonly` to false, files with that attribute will be read-only until you've locked them, at which point they'll be read-write, and then they'll be read-only once unlocked.

Git LFS will use the `pre-push` hook to ensure that users don't try to push files locked by other users before the push starts, so if the user has modified the permissions, they'll be prevented from pushing.  However, this check is done on the client side, so it's purely advisory unless the server also happens to enforce it (which most implementations do not).

The error you're seeing is a 409 Conflict, which is the expected result when you try to lock a file that's already locked.  It looks like we have a bug somewhere that causes the string printed to be incorrect; normally the server should produce an error like this: “Locking a.bin failed: Lock exists”.  It may be in this case that the server failed to provide a message (which would be a bug in the server), but we should still not dump what looks like a URL to the output in that way.

Hopefully that answers your questions.

**Comment by jdx-john** [comment]
Very helpful, thanks. I am still curious how the locked state of a file is 'transmitted' between repositories when I lock/unlock a file. When I run `lock` does that send an update to the server immediately? What happens if I am working offline making changes on my local repo and I try to lock a file?

**Comment by bk2204** [comment]
The Git LFS protocol doesn't specify whether locking applies to all repositories in a fork network or not.  GitHub doesn't do that, but it's possible that Azure DevOps does.

When you run `git lfs lock`, that talks to the server and acquires the lock or rejects the operation.  If you're offline, then that won't be possible and the operation will fail.  Note that checking out a different branch will also try to contact the remote server to fetch teh LFS blobs and will also fail in that case.

**Comment by jdx-john** [comment]
> When you run `git lfs lock`, that talks to the server and acquires the lock or rejects the operation. If you're offline, then that won't be possible and the operation will fail. 

OK that's clear. Thankyou. No further questions so I'll close :)
