### ISSUE TITLE
git appears to get stuck after a crash

### ISSUE THREAD

**Issue by OmarWKH** [git-lfs/git-lfs#4905]
**Describe the issue**
I had a crash while running a git operation (I think pull or checkout, it was during the lfs stage). Now whenever I run pull or checkout git says `Updating files: 100%` and gets stuck. Meanwhile the git lfs process is showing high network activity, but shows no sign of progressing. I had to terminate the operation because I don't know if it's making progress or just using up bandwidth.

```
$ git checkout new_underground
Updating files: 100% (199/199), done.

Exiting because of "interrupt" signal.
```

**System environment**
Windows 10.0.19044
git version 2.35.1.windows.2
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
```
$ git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=input
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
user.name=Omar Khashoggi
user.email=10570290+OmarWKH@users.noreply.github.com
core.editor="C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
core.longpaths=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
mergetool.unityyamlmerge.trustexitcode=false
mergetool.unityyamlmerge.cmd="C:\Program Files\Unity\Hub\Editor\2020.3.16f1\Editor\Data\Tools\UnityYAMLMerge.exe" merge -p $BASE $REMOTE $LOCAL $MERGED
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
lfs.repositoryformatversion=0
remote.origin.url=git@github.com:OmarWKH/VRIF_URP.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.gh-resolved=base
branch.main.remote=origin
branch.main.merge=refs/heads/main
```

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.35.1.windows.2

Endpoint=https://github.com/OmarWKH/VRIF_URP.git/info/lfs (auth=none)
  SSH=git@github.com:OmarWKH/VRIF_URP.git
LocalWorkingDir=C:\Users\Asus\Offline\Projects\VR\UnityVRSetup\VRIFrameworkURP-WT4
LocalGitDir=C:\Users\Asus\Offline\Projects\VR\UnityVRSetup\VRIFrameworkURP\.git\worktrees\VRIFrameworkURP-WT4
LocalGitStorageDir=C:\Users\Asus\Offline\Projects\VR\UnityVRSetup\VRIFrameworkURP\.git
LocalMediaDir=C:\Users\Asus\Offline\Projects\VR\UnityVRSetup\VRIFrameworkURP\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\Asus\Offline\Projects\VR\UnityVRSetup\VRIFrameworkURP\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\Asus\Offline\Projects\VR\UnityVRSetup\VRIFrameworkURP\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
I got notified by GitHub that I'm about to run out of lfs data. I don't know if I was already using a lot of data or if this issue pushed my usage way up.

**Comment by OmarWKH** [comment]
This could be a non-issue. I cloned the repo and checked out a branch. It seemed to get stuck like before. But after a while it showed the lfs progress (`Filtering content`) and completed successfully.

**Comment by bk2204** [comment]
Hey,

The best way to see what's going on here is to run with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and then look at the trace output to see what's taking so long.  If you're still seeing that, could you run your operation with those environment variables (e.g., by prefixing them to your command in Git Bash) and then providing the output here, either inline or as a text file attachment?

**Comment by OmarWKH** [comment]
I did run it with `GIT_TRACE=1` but I lost the output. It seemed to be downloading LFS files.

For context, this happened after two very large files were pushed. 2 GB each. I removed these files so I no longer see the issue on updated branches.

I could checkout a commit that had these files to reproduce the issue, but I'm hesitant to do so as it would eat up my bandwidth quota.

**Comment by bk2204** [comment]
Okay.  We're happy to look into the problem if you can reproduce it, but my guess here is that it's just slow.  GitHub presently hosts its LFS data in an Amazon S3 bucket in us-east-1, which takes a different route from regular Git data, so it can end up being slow sometimes for various reasons due to connections between you and that endpoint.

If you think it's something else, such as a bug in the client (which I doubt), we'd need the appropriate trace output in order to proceed.

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back from you in a while, I'm going to close this.  If you can provide the requested output, we'll look into this further.
