### ISSUE TITLE
Is there a commit message hook?

### ISSUE THREAD

**Issue by demonguy** [git-lfs/git-lfs#4907]
When i run `git lfs migrate`. I want to hook original commit message. Keep the original message, but add one more line which is the previous commit hash. Which allow me to find a commit corresponding to previous commit hash.

Is it possible?

**Comment by bk2204** [comment]
Hey,

There isn't any commit message hook when migrating.  If you'd like to modify the commit message at the same time as migrating, you'd want to use another tool to perform the migration, such as `git filter-branch` or `git filter-repo`.
