### ISSUE TITLE
problems with tracked symlinks on windows

### ISSUE THREAD

**Issue by dieterstueken** [git-lfs/git-lfs#4908]
I tracked a whole file tree with many binary files into LFS (it was a jdk-12 for Linux) on my Linux host.
This tree also contained some symbolic links. May be it does not make too much sense, to track symbolic links, but it worked seamless.
When checked it out on Windows (git version 2.31.1.windows.1), those links turn into regular files, but the flags still show them up as symlinks.

> $ git ls-files -s  inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
> 120000 76b7b2f26b60c984c7e827e3b1c80698f66d7a75 0       inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO

After migration to Windows 11 I suddenly got:

>  $ git diff inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
> diff --git a/inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO b/inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
> index 76b7b2f26b..5c95129132 120000
> --- a/inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
> +++ b/inst/jre12/linux-x64/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
> @@ -1 +1,3 @@
> -../java.base/ADDITIONAL_LICENSE_INFO
> \ No newline at end of file
> +version https://git-lfs.github.com/spec/v1
> +oid sha256:e0fa2589f69ee66ddb1e70ab1a6d4601c0fde4541d3f280204d90fae5054d12c
> +size 36

Seems the diff does not resolve the git pointer any more.

I removed the files and checked them out again, but the problem remains the same.
Finally I created a new worktree and checked out the same head (as a new branch) and the problem disappeared.
No diff any more!

So, I try to investigate what it going wrong here, but I don't have any idea.
Even after an upgrade to git `version 2.35.1.windows.2` the problem remains the same, and I don't think its related to Windows 11.
But it may be related to some tweaks on git-lfs.exe  for windows.

Any idea how to track this down?

**Comment by bk2204** [comment]
Hey,

So here's what I think is happening.  On Windows, symlinks require elevated privileges to create unless you're in Developer Mode.  As a result, if symlinks aren't available, Git sets `core.symlinks` to false and checks those files out as regular files.

Git doesn't normally process symlinks through Git LFS (and it is Git's choice whether to do this), but it does do that for things which are currently checked in as symlinks but are written as files in the working tree.  So if you modify the file somehow in the working tree, then Git will try to clean the file into an LFS file.

Essentially, if you're working with a repository with symlinks, then you need to turn on Developer Mode on Windows, grant yourself carte-blanche to create symlinks, or use WSL, all of which will fix this problem and avoid this weird behavior from Git.

Hopefully that helps.

**Comment by bk2204** [comment]
Hey,

Your original clone probably still has `core.symlinks` set to false.  If you have Developer Mode on, then you should be able to do (on an otherwise clean working tree _only_) `git config core.symlinks true` and then `git reset --hard`.

**Comment by dieterstueken** [comment]
Hi Brian,

after hours of investigation this night, I created a sample repository to explain the problem I observed:

https://github.com/dieterstueken/git-links

Dieter.
