### ISSUE TITLE
After cloning I get only pointers to files

### ISSUE THREAD

**Issue by eliasnas** [git-lfs/git-lfs#4911]
I am trying to clone a repository which includes submodules that include packages of type GIT LFS. I am doing so in two ways, and failing in both:

1) I create a new folder and run `git-lfs install` and then I run the cloning command, at the end I don't get the full sized packages, just pointers.

2) After cloning I run `git-lfs install` and then `git-lfs pull` inside the folder of one submodule called `pytm_win`. In this case the pulling starts with this message: "Downloading LFS objects" and I get stuck at 0% for a while, and then I get these errors:
`batch request: exec request failed on channel 0: exit status 255`
`Failed to fetch some objects from '<The server URL>'` 

I am trying to do so on Windows Server 2012 R2, and other team members who work on the same server cloned the whole packages successfully, so I am not sure if it is a problem with the client or the server itself.

When running `git lfs env` inside the submodule `pytm_win` this is the output:

```
git-lfs/3.1.2 (GitHub; windows amd64; go 1.17.6)
git version 2.31.1.windows.1

Endpoint=<The server URL> (auth=none)
SSH=<The server URL>
LocalWorkingDir=D:\Workarea\Users\eliasnas\GIT\PyTM\titan-pytm-tests\.pytm_framework\dist\pytm_win
LocalGitDir=D:\Workarea\Users\eliasnas\GIT\PyTM\titan-pytm-tests\.git\modules\.pytm_framework\modules\dist\pytm_win
LocalGitStorageDir=D:\Workarea\Users\eliasnas\GIT\PyTM\titan-pytm-tests\.git\modules\.pytm_framework\modules\dist\pytm_win
LocalMediaDir=D:\Workarea\Users\eliasnas\GIT\PyTM\titan-pytm-tests\.git\modules\.pytm_framework\modules\dist\pytm_win\lfs\objects
LocalReferenceDirs=
TempDir=D:\Workarea\Users\eliasnas\GIT\PyTM\titan-pytm-tests\.git\modules\.pytm_framework\modules\dist\pytm_win\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\Workarea\Users\eliasnas\GIT\PyTM\titan-pytm-tests\.git\modules\.pytm_framework\modules\dist\pytm_win\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Users\eliasnas\AppData\Local\Programs\Git LFS
GIT_SSH=C:\Program Files\Git\usr\bin\ssh.exe
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I would like to know if anybody has some suggestions to solve this issue.

Thanks in advance,
Elias

**Comment by chrisd8088** [comment]
Hey, thanks for opening a fresh issue, and I'm sorry you're still having trouble.

One minor thing first, which is that I typically you should not need to run `git lfs install` more than once, as it updates the Git configuration in your `$HOME` directory, the one that applies "globally" to all your Git repositories.  That is to say, you shouldn't need to run it in each repository.

But that doesn't seem like it's the source of your particular issue, though.  I would try narrowing down the likely source of problems, if you can, by trying to clone something without submodules, first of all.  (Maybe that already works for you and you didn't mention it?)  If you haven't tested that, I would try to clone a repo on your server that uses Git LFS directly -- maybe try downloading one of the submodule repos on its on?

If that too fails, you might try cloning an open source project with LFS objects in it from, say, GitHub; a bit of searching should turn up some examples.

If you're getting failures across all of these, then I'd be suspicious of third-party antivirus or other security programs, or a network or firewall issue.

Please also try running with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` to get more debugging output on what's going on and, with luck, what's failing.

And if it's just a problem with the submodules, it would be ideal if there's a way to create a reproducible test case you could share.

I hope that provides some ideas, at least, to experiment with.  Good luck!

**Comment by eliasnas** [comment]
Thanks for the reply.

I tried cloning a repo without any submodules, with git-lfs, and got the same issue.

And this is what I get when running with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`:

![trace](https://user-images.githubusercontent.com/101345468/158016553-7a4e2686-929f-4b21-b231-56a90fc158e5.PNG)

I am not sure if it is a firewall issue. because other team members working on the same server can clone successfully the whole full sized packages.

**Comment by chrisd8088** [comment]
That suggests you have some kind of SSH configuration or network issue.  You might try with `GIT_SSH_COMMAND='ssh -vvv'` to see what SSH thinks is the problem.

**Comment by eliasnas** [comment]
I tried running with: ` GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 GIT_SSH_COMMAND='ssh -vvv' `, this is what I am getting:

![5](https://user-images.githubusercontent.com/101345468/158045639-dccd67e3-5887-4527-86ef-e82d67d60336.PNG)

**Comment by eliasnas** [comment]
UPDATE:
I used https instead of ssh, and cloned successfully!! 
Although this doesn't solve the ssh errors, but for me this issue can be closed!

Thanks for the help :)
