### ISSUE TITLE
error: git-lfs died of signal 9

### ISSUE THREAD

**Issue by dingsboms** [git-lfs/git-lfs#4912]
Hi, I'm trying to upload my git repository to github but some of my zip files exceed the 100mb limit. 

The problem now is when I try to use;

git lfs migrate import --everything --include="*.zip" --verbose

i get the "error: git-lfs died of signal 9".

It's really frustrating, I don't really know what I'm doing, and I've spent a lot of money on the github subscription and data packs to no avail.. Any help would be appreciated. 

**Operating System**
Ubuntu

**Output of `git lfs env`**
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.25.1

Endpoint=https://github.com/dingsboms/GangarNettHub.git/info/lfs (auth=basic)
LocalWorkingDir=/home/ubuntu/GangarNett1.01
LocalGitDir=/home/ubuntu/GangarNett1.01/.git
LocalGitStorageDir=/home/ubuntu/GangarNett1.01/.git
LocalMediaDir=/home/ubuntu/GangarNett1.01/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/ubuntu/GangarNett1.01/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/ubuntu/GangarNett1.01/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**

**Comment by MarkEWaite** [comment]
> git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
> git version 2.25.1

The most recent release of git-lfs is 3.1.2.  It is available for download from this repository in [releases](https://github.com/git-lfs/git-lfs/releases/tag/v3.1.2).  Remove the `git-lfs` that is installed from the Ubuntu package manager and install the git lfs 3.1.2 to see if it resolves the issue.

**Comment by dingsboms** [comment]
Hi, thanks for the reply! I had not noticed.

I installed the later version, but unfortuneately got the same error. 

Perhaps I need to bump up the RAM of the virtual machine..

**Comment by bk2204** [comment]
Hey,

The "died of signal 9" means that the process got the SIGKILL signal.  That means that either you or some other process on the machine sent it that signal, which is always fatal, or you ran out of memory and the OOM (out-of-memory) killer killed the process.  So I'd think trying to bump the memory here would be a good idea.

**Comment by dingsboms** [comment]
Thank you guys. The problem was resolved by bumping up the memory. :)
