### ISSUE TITLE
git lfs fetch v3.0.2 reports an error "lookup <IP4address>: dnsquery: DNS name does not exist."

### ISSUE THREAD

**Issue by davehecker66** [git-lfs/git-lfs#4918]
**Describe the bug**
Cloning a repository succeeds, but checkout fails when attempting to retrieve files managed by GIT LFS, reporting the error `lookup <IP4address>: dnsquery: DNS name does not exist.` (I originally added to [issue 4853](https://github.com/git-lfs/git-lfs/issues/4853) but I was asked to create a separate issue.)

In Git Bash doing **git fetch** and **git pull** succeed, but doing **git lfs fetch** reports `lookup <IP4address>: dnsquery: DNS name does not exist.` which suggests that GIT LFS has successfully looked up the repository's domain name (an https url) to get _IP4address_, but then later it's attempting to look up that _IP4address_, which results in "DNS name does not exist" (because _IP4address_ is not a domain name).

**To Reproduce**
I installed Git-2.35.1.2-64-bit.exe (selecting the option to also install GIT LFS) and then I did the following in GIT BASH:
**$ set GIT_TRACE=1
$ set GIT_TRANSFER_TRACE=1
$ set GIT_CURL_VERBOSE=1
$ git clone https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName c:\Test**
```
Cloning into 'c:Test'...
remote:
remote:                    fTfs
remote:                  fSSSSSSSs
remote:                fSSSSSSSSSS
remote: TSSf         fSSSSSSSSSSSS
remote: SSSSSF     fSSSSSSST SSSSS
remote: SSfSSSSSsfSSSSSSSt   SSSSS
remote: SS  tSSSSSSSSSs      SSSSS
remote: SS   fSSSSSSST       SSSSS
remote: SS fSSSSSFSSSSSSf    SSSSS
remote: SSSSSST    FSSSSSSFt SSSSS
remote: SSSSt        FSSSSSSSSSSSS
remote:                FSSSSSSSSSS
remote:                  FSSSSSSs
remote:                    FSFs    (TM)
remote:
remote:  Microsoft (R) Visual Studio (R) Team Foundation Server
remote:
Receiving objects: 100% (358870/358870), 498.40 MiB | 12.00 MiB/s, done.
Resolving deltas: 100% (319013/319013), done.
Updating files: 100% (9290/9290), done.
Downloading Extras/LSADataAdapterSolution/lib/Filename.llblgenproj (77 KB)
Error downloading object: Extras/LSADataAdapterSolution/lib/Filename.llblgenproj (5e4f888): Smudge error: Error downloading Extras/LSADataAdapterSolution/lib/Filename.llblgenproj (5e4f888baf46329f841612572a39fd9d3a5c803b5c051fcb8548cbaeadce5333): batch response: Post "https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName.git/info/lfs/objects/batch": lookup <IP4address>: dnsquery: DNS name does not exist.

Errors logged to C:\Test\.git\lfs\logs\20220327T165541.3737981.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Extras/LSADataAdapterSolution/lib/Filename.llblgenproj: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
**$ cd c:\test**

**$ git fetch**

**$ git pull**
Already up to date.

**$ git lfs fetch**
```
fetch: Fetching reference refs/heads/master
batch response: Post "https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName.git/info/lfs/objects/batch": lookup <IP4address>: dnsquery: DNS name does not exist.
error: failed to fetch some objects from 'https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName.git/info/lfs'
```

**The error log 20220327T165541.3737981.log**
```
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.35.1.windows.2

$ git-lfs.exe filter-process
Error downloading object: Extras/LSADataAdapterSolution/lib/Filename.llblgenproj (5e4f888): Smudge error: Error downloading Extras/LSADataAdapterSolution/lib/Filename.llblgenproj (5e4f888baf46329f841612572a39fd9d3a5c803b5c051fcb8548cbaeadce5333): batch response: Post "https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName.git/info/lfs/objects/batch": lookup 216.115.169.22: dnsquery: DNS name does not exist.

Post "https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName.git/info/lfs/objects/batch": lookup 216.115.169.22: dnsquery: DNS name does not exist.
batch response
github.com/git-lfs/git-lfs/v3/errors.newWrappedError
	D:/a/git-lfs/git-lfs/errors/types.go:225
github.com/git-lfs/git-lfs/v3/errors.Wrap
	D:/a/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/v3/tq.(*tqClient).Batch
	D:/a/git-lfs/git-lfs/tq/api.go:95
github.com/git-lfs/git-lfs/v3/tq.Batch
	D:/a/git-lfs/git-lfs/tq/api.go:43
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor
	D:/a/git-lfs/git-lfs/tq/transfer_queue.go:558
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1
	D:/a/git-lfs/git-lfs/tq/transfer_queue.go:452
runtime.goexit
	go/src/runtime/asm_amd64.s:1581
Error downloading Extras/LSADataAdapterSolution/lib/Filename.llblgenproj (5e4f888baf46329f841612572a39fd9d3a5c803b5c051fcb8548cbaeadce5333)
github.com/git-lfs/git-lfs/v3/errors.newWrappedError
	D:/a/git-lfs/git-lfs/errors/types.go:225
github.com/git-lfs/git-lfs/v3/errors.Wrapf
	D:/a/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/v3/lfs.(*GitFilter).downloadFile
	D:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:119
github.com/git-lfs/git-lfs/v3/lfs.(*GitFilter).Smudge
	D:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:78
github.com/git-lfs/git-lfs/v3/commands.smudge
	D:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/v3/commands.filterCommand
	D:/a/git-lfs/git-lfs/commands/command_filter_process.go:122
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/v3/commands.Run
	D:/a/git-lfs/git-lfs/commands/run.go:105
main.main
	D:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	go/src/runtime/proc.go:255
runtime.goexit
	go/src/runtime/asm_amd64.s:1581
Smudge error
github.com/git-lfs/git-lfs/v3/errors.newWrappedError
	D:/a/git-lfs/git-lfs/errors/types.go:225
github.com/git-lfs/git-lfs/v3/errors.NewSmudgeError
	D:/a/git-lfs/git-lfs/errors/types.go:311
github.com/git-lfs/git-lfs/v3/lfs.(*GitFilter).Smudge
	D:/a/git-lfs/git-lfs/lfs/gitfilter_smudge.go:87
github.com/git-lfs/git-lfs/v3/commands.smudge
	D:/a/git-lfs/git-lfs/commands/command_smudge.go:127
github.com/git-lfs/git-lfs/v3/commands.filterCommand
	D:/a/git-lfs/git-lfs/commands/command_filter_process.go:122
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/v3/commands.Run
	D:/a/git-lfs/git-lfs/commands/run.go:105
main.main
	D:/a/git-lfs/git-lfs/git-lfs.go:33
runtime.main
	go/src/runtime/proc.go:255
runtime.goexit
	go/src/runtime/asm_amd64.s:1581

Current time in UTC: 
2022-03-27 20:55:41

ENV:
LocalWorkingDir=C:\Test
LocalGitDir=C:\Test\.git
LocalGitStorageDir=C:\Test\.git
LocalMediaDir=C:\Test\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Test\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Test\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_DIR=C:/Test/.git
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS

Client IP addresses:
fd6f:ceb3:d044:1:fc6e:cfb4:5b12:726 fd6f:ceb3:d044:1:81a9:621b:3a78:9c96 fd6f:ceb3:d044:1:943e:d9c4:9144:4eb4 fe80::fc6e:cfb4:5b12:726 10.0.0.25
```

**Expected behavior**
I expected the files managed by LFS to be downloaded to my local drive.
FYI in `C:\Program Files\Git\mingw64\bin\` I replaced git-lfs.exe (v3.0.2 from the GIT install) with the gif-lfs.exe v2.5.1 file from a standalone install of LFS, and then **git fetch** succeeds without reporting the `lookup <IP4address>: dnsquery: DNS name does not exist.` error.

**System environment**
Test captured under Windows 10, but got same results under Windows 7. I don't know the detail of the TFS server.

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.35.1.windows.2

Endpoint=https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName.git/info/lfs (auth=negotiate)
LocalWorkingDir=C:\Test
LocalGitDir=C:\Test\.git
LocalGitStorageDir=C:\Test\.git
LocalMediaDir=C:\Test\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Test\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Test\.git\lfs
AccessDownload=negotiate
AccessUpload=negotiate
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

It might be helpful to get the trace output.  In your case, the commands you've given with `set` don't actually set the environment variables, since bash works differently from CMD and PowerShell.  You'd want to write this instead:

```
$ GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName c:/Test
```

You can then copy the output and attach it to this issue, stripping out any `Authorization` headers.

It's also helpful to know the output of `nslookup tfs.company.com`.

It's possible that this is also due to trying to use Kerberos, but where your IP address is not in any domain, and hence, it can't do automatic lookup in DNS of the Kerberos server.  Is that the case here?

In any event, you won't want to use Git LFS 2.5.1, because that has known security issues on Windows.

**Comment by davehecker66** [comment]
>copy the output and attach it to this issue

Sorry, I searched and only found the "set" syntax...I repeated the clone using:
```
cd /c
GIT_TRACE=1 GIT_TRANSFER=1 GIT_CURL_VERBOSE=1 git clone https://tfs.company.com/tfs/PDSI/HRS2/Learning/_git/ProductName Test
```
but could only copy the end part of the process (see [Partial_clone_log.txt](https://github.com/git-lfs/git-lfs/files/8364061/Partial_clone_log.txt) -- note that "company", "ProductName", "IP4address", and "Filename" are just placeholders).

I tried adding ` > "c:\folder1\folder2\clone_log.txt"` to try to pipe the full results to a file, but just ended up with a zero-byte file. If you need the full log please LMK which tool to use and the commands to execute to capture the full log.

>It's also helpful to know the output of `nslookup tfs.company.com`

Immediately before doing the clone (while on my home network, not connected to any VPN):
```
nslookup tfs.company.com resolves to the <IP4address>
Name:    tfs.company.com
Address:  <IP4add
[Partial_clone_log.txt](https://github.com/git-lfs/git-lfs/files/8364791/Partial_clone_log.txt)
ress>
```
And `nslookup <IP4address>` reports "Non-existent domain"

>you won't want to use Git LFS 2.5.1, because that has known security issues on Windows

Agreed I don't "want" to, but currently "need" to because it works. But your comment made me go check https://github.com/git-lfs/git-lfs/releases where I saw there were newer LFS releases after the v3.0.2 that's installed by Git-2.35.1.2-64-bit.exe

I tried copying v3.1.2 of git-lfs.exe into the mingw64 folder and repeated the clone. With that version the clone also succeeds, but then instead of getting the `lookup <IP4address>: dnsquery: DNS name does not exist.` error I am getting the behavior described in the other Issue, where I'm repeatedly/endlessly prompted to enter my credentials (which "clone" didn't prompt for). 

I also tried cancelling the Windows dialog, and also canceled the "Git for Windows" dialog, so in the Git Bash window I'm prompted with `Username for 'https://tfs.company.com': ` I then submitted MyDomain\MyId and the "Git for Windows" dialog prompts: Password for 'https://MyDomain\MyId@tfs.company.com': -- I entered my correct password and it failed.

Somewhere in that process ?git-lfs? is deleting my saved "git" Windows Credentials so if I ctrl-C to break out of the cycle, then back at the Git Bash prompt I do `git fetch` I'm prompted for credentials. Entering MyDomain\MyId and my password is accepted, my Windows Credentials are stored (git:https://MyDomain\MyId@tfs.company.com and git:https://tfs.company.com - each with User Name MyDomain\MyId and my Password).

Random thought: **IF** the backslash in MyDomain\MyId needs to get encoded to https://MyDomain%5CMyId@tfs.company.com then perhaps that's not happening, or perhaps it's happening more than once (i.e. MyDomain\MyId encoded once is MyDomain%5CMyId, and a second encoding would be MyDomain%255CMyId, which wouldn't decode to the correct userid).

Thanks,
--Dave

**Comment by bk2204** [comment]
Okay, so if this is not occurring in 3.1.2, then I'm going to close this.  That means that it is trying to use Kerberos, which is not properly configured in your environment, and then it's falling back to Basic in 3.1.2, which it didn't do in 3.0.2.

What you're seeing is that Git is trying to use NTLM and Git LFS is trying to use Kerberos, and Kerberos is not supported.  Git LFS no longer supports NTLM, so if your TFS server requires NTLM, then you'll need to contact Microsoft for an updated version or use a PAT with Basic authentication if that's possible.  I strongly suggest addressing this with Microsoft, though, because they really need to fix this issue.

I should point out that Git LFS versions before 2.13.3 have an arbitrary code execution vulnerability (which, technically, is due to a bug in Go which the maintainers of that project refuse to acknowledge as a vulnerability), so if you use 2.5.1, you're vulnerable to that just by cloning a repository.
