### ISSUE TITLE
git lfs push always fails with MISSING 503 

### ISSUE THREAD

**Issue by j-p-e** [git-lfs/git-lfs#4919]
**Describe the bug**
cannot push a single lfs file to a github server for one particular repo (repos with less lfs history seem ok)  

**To Reproduce**
have 34 pruned lfs files in one repo locally, as full files not stubs, with git lfs ls-files all looking normal  
try and push lfs files to a nominally empty github remote repo. I say nominally empty as it has no source but seems to have strong views on lfs objects it wants.
$ git lfs push upstream master  
\# get exactly 34 messages back all like the following : 

Fatal error: Server error &{%!!(string=https) %!!(string=) %!!(*url.Userinfo=<nil>) %!!(string=[the remote server URL]) %!!(string=/storage/lfs/207381/objects/deca65f3094943a1af148cf64fd6c0deb503219d12de0e172b7f948d07a8e6a8) %!!(string=) %!!(bool=false) %!!(string=) %!!(string=) %!!(string=)}s(MISSING) from HTTP 503

\# dig further into one file : 
$ ls -lA .git/lfs/objects/de/ca/deca65f3094943a1af148cf64fd6c0deb503219d12de0e172b7f948d07a8e6a8
-rw-rw-r-- 1 user group 1399 Mar 29 11:45 
\# ok. File exists locally and is not a stub. confirmed with 'more' that it has content.  
$ git lfs push upstream --object-id deca65f3094943a1af148cf64fd6c0deb503219d12de0e172b7f948d07a8e6a8
\# one message this time, seemingly telling me I can't push the missing file because it is... missing 
Fatal error: Server error &{%!!(string=https) %!!(string=) %!!(*url.Userinfo=<nil>) %!!(string=[the remote server URL]) %!!(string=/storage/lfs/207381/objects/deca65f3094943a1af148cf64fd6c0deb503219d12de0e172b7f948d07a8e6a8) %!!(string=) %!!(bool=false) %!!(string=) %!!(string=) %!!(string=)}s(MISSING) from HTTP 503

**Expected behavior**
git-lfs can push files   

**System environment**
git-lfs --version
git-lfs/3.1.2 (GitHub; linux amd64; go 1.17.6)
git --version
git version 2.35.1
uname -r 
5.13.0-37-generic

**Output of `git lfs env`**

Endpoint=https://[local gitlab].git/info/lfs (auth=basic)
Endpoint (upstream)=https://[remote github trying to push to].git/info/lfs (auth=basic)
LocalWorkingDir=[project]
LocalGitDir=[project]/.git
LocalGitStorageDir=[project]/.git
LocalMediaDir=[project]/.git/lfs/objects
LocalReferenceDirs=
TempDir=[project]/.git/lfs/tmp
ConcurrentTransfers=50
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=0
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=false
PruneOffsetDays=0
PruneVerifyRemoteAlways=true
PruneRemoteName=upstream
LfsStorageDir=[project]/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
The 'other side' has tried completely deleting and recreating the remote repo, no change 
The lfs files have definitely been messed around with locally, but all stemming from trying to fix this issue. Most recently all files were removed from lfs using lfs migrate export. That also failed to push as one file is 1% over the remote size limit, with a suggestion that we should use lfs. That one filetype (which has 34 files) has been added back into lfs locally.  

Have also tried git lfs fetch --all, git lfs push --all, dry runs (which seem to make sense until I involve the remote), setting FetchRecentRefsDays=0, FetchRecentCommitsDays=0 locally, and also not setting them to 0 locally (in case the server thinks something different). Also tried not pruning, not pruning, FetchRecentRefsIncludeRemotes true and false, PruneVerifyRemoteAlways true and false, PruneRemoteName origin and upstream

**Comment by bk2204** [comment]
Hey,

The `MISSING` entry is actually a bug here in the rendering of the URL and doesn't indicate that the file is missing.  The HTTP 503 is the problem: that indicates that the remote side has returned a 503 Connection Refused error.  Like all 500-series errors, this indicates a problem that is a server-side problem and there's nothing that the client can do that will change that.  You'd need to talk to the maintainer of the server to figure out why things are broken; they can look at the logs and tell you more.
