### ISSUE TITLE
[Feature Request] Separate tracked listing versus excluded

### ISSUE THREAD

**Issue by OdinVex** [git-lfs/git-lfs#4921]
Two projects I use have been developed to parse `git-lfs` output, such as `git-lfs tracked` and they're unable to differentiate the output of tracked items versus excluded due to the uncertainty of localization.

Perhaps the tracked/excluded could be listed separately, or a guaranteed output delimiter could be used? A double-newline, perhaps?

**Comment by bk2204** [comment]
Hey,

We could certainly add a machine-readable output, which would probably be JSON, considering what other commands do.  In the mean time, you could invoke Git LFS with `LC_ALL=C` or `LC_ALL=C.UTF-8`, which will ensure that we always output data in English.

**Comment by OdinVex** [comment]
I don't think it is entirely necessary to add an output, perhaps the categories could be separated by a double-newline for now?

Example:
```
Listing tracked patterns
    Tracked/** (.gitattributes)
    *.tracked (.gitattributes)

Listing excluded patterns
    Untracked/** (.gitattributes)
    *.untracked (.gitattributes)
```

It'd at least alleviate the need for an extra output and I feel it'd be a bit more readable, too.

**Comment by bk2204** [comment]
My preference is to avoid having people parse output formats which are not intentionally machine readable.  Even if we added a double newline, we wouldn't guarantee that wouldn't change in the future, so I'd rather add an explicitly machine readable format than try to make parsing of human-readable text easier.

Git takes this same approach and has explicitly changed human-readable data in the past, and when possible, we try to follow the same approach as Git for consistency.

**Comment by OdinVex** [comment]
> My preference is to avoid having people parse output formats which are not intentionally machine readable. Even if we added a double newline, we wouldn't guarantee that wouldn't change in the future, so I'd rather add an explicitly machine readable format than try to make parsing of human-readable text easier.
> 
> Git takes this same approach and has explicitly changed human-readable data in the past, and when possible, we try to follow the same approach as Git for consistency.

Sensible, nice. For builds currently centered around this human output, is it safe to assume both categories of output have entries prepended by spaces?
