### ISSUE TITLE
A missing file found with 'git lfs fsck' cannot be restored easily, not even if you have a backup available

### ISSUE THREAD

**Issue by abelbraaksma** [git-lfs/git-lfs#4927]
If you run `git lfs fsck` you get a list of missing files (which ought to be empty). While I don't know what caused the file to be missing, more importantly it isn't clear how to proceed from here.

**To Reproduce**
1. Force a missing file situation (i.e., remove any OID-file in the `.git\lfs\objects` dir)
2. Run `git lfs fsck`, you'll now get output like:
    ```text
    objects: openError: Tests/codegen/unicode9a.xml (0a5b70d4a7c5bcbec30a0e7759665d761970318d02eef9003e42830817cd1361) could not be checked: The system cannot find the file specified.
    objects: repair: moving corrupt objects to D:\Projects\MyProject\.git\lfs\bad
    ```
3. Establish that `.git\lfs\bad` is empty
4. Attempt to restore the file (this is where I'm at a loss) 

**Expected behavior**
Perhaps an expected destination filename? If `fsck` were to show `.git\lfs\objects\fa\b1\<some-oid>` I can simply take a backup copy and place it in that location, but such location is not given, only the bare OID is given.

Btw, I'm not complaining that there's a missing file, that just happens, I'm merely looking for a way to (manually) restore it.

**System environment**
Latest versions of git and lfs, Windows 10 (though I think the issue can be replicated on any system).

**Additional context**
While this may not be a common scenario, it happened to me after doing a `migrate import`. It should be noted that the file is also absent on the remote server. I can see the `xml` file with the `OID` in it, but it cannot be found when cloning from the server. I have no idea how to manually verify the locations on the git lfs server as I think this information is hidden somewhere and not easily accessible.

**Workaround**
Use `git rebase` to edit the history manually with the original file and run `git lfs migrate import` again, or if the history is not important, simply re-commit the file.

**Side issue**
There appears to be no way to enumerate the exact relation between the OID-files (i.e., the bin files replaced with the OID pointer in it) and the actual locations on either the remote server or the local `objects` dir. The latter appears to have some kind of semi-random structure (like `.git\lfs\objects\<HH>\<HH>\<some-oid>`), but it isn't clear to me how the algorithm works for locating a file there (other than just searching the whole dir), let alone recreating a file for which I do not know what LFS likes to have as location in `objects`.

**Comment by KalleOlaviNiemitalo** [comment]
If you track a text file containing "demo" in Git LFS, then it results in the following Git LFS pointer blob:

```
version https://git-lfs.github.com/spec/v1
oid sha256:2a97516c354b68848cdbd8f54a226a0a55b21ed138e207ad6c5cbb9c00aa5aea
size 4
```

where `2a97516c354b68848cdbd8f54a226a0a55b21ed138e207ad6c5cbb9c00aa5aea` is the SHA-256 hash of the file content, i.e. the four characters `demo`. The data should then be at `.git/lfs/objects/2a/97/2a97516c354b68848cdbd8f54a226a0a55b21ed138e207ad6c5cbb9c00aa5aea`, where `2a` and `97` are the first four digits of the hash. That's how it works here, anyway; I'm not sure whether Git LFS might use a shallower or deeper directory layout if there were fewer or more LFS files.

**Comment by KalleOlaviNiemitalo** [comment]
If you copy the correct file content to the worktree, at any path tracked by Git LFS, and run `git add` on it, then that should invoke the `git lfs clean` filter to compute the SHA-256 hash and copy the content to the correct directory and name in `.git/lfs/objects/`. After that, other operations on identical Git LFS pointers should find the LFS file from there all right.

**Comment by abelbraaksma** [comment]
> where `2a` and `97` are the first four digits of the hash. 

@KalleOlaviNiemitalo That's the part that eluded me! Thanks! This sounds like some info that would be well worth adding to the manual for `lfs fsck`, so that people can actually do manual recovery in cases like these.

> If you copy the correct file content to the worktree, at any path tracked by Git LFS, and run `git add` on it, 

Yes, but that would make it a new commit in the history, afaict. But I'll first try to manually create that file and see what happens (I already saw that the generated SHA-256 hash was equal with the backup file, I just couldn't figure out the location to store it).

**Comment by KalleOlaviNiemitalo** [comment]
No, `git add` does not make a commit.

**Comment by abelbraaksma** [comment]
Let's close this. Thanks for the help. For all us out there that aren't too savvy with git commands, it may still be a good idea to add this solution to the docs though.
