### ISSUE TITLE
Colab to Github Permissioning Not Working

### ISSUE THREAD

**Issue by loewenm** [git-lfs/git-lfs#4933]
Hi - Any help on this permissioning issues between Google Colab and Github would be greatly appreciated.

Oddly, running the same commands from my local machine to Github does not result in an error and I can upload no problem... This only occurs when trying to attempt this from the Colab environment.

Importantly, this git repo was cloned from Github, which was originally pushed with appropriate LFS hooks and .gitattribute file from my local computer. So, when I pulled the repo to Colab, the .gitattributes file did pull into the hosted colab repo... Not sure what else I need to do here...

**Describe the issue**
Attempting to push LFS files to Github from Google Colab results in a permissioning error:

`fatal: cannot exec '.git/hooks/pre-push': Permission denied`

**How to Reproduce?**

```
!curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
!sudo apt-get install git-lfs
!git lfs install

>Detected operating system as Ubuntu/bionic.
>Checking for curl...
>Detected curl...
>Checking for gpg...
>Detected gpg...
>Running apt-get update... done.
>Installing apt-transport-https... done.
>Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
>Importing packagecloud gpg key... done.
>Running apt-get update... done.
>
>The repository is setup! You can now install packages.
>Reading package lists... Done
>Building dependency tree       
>Reading state information... Done
>git-lfs is already the newest version (3.1.2).
>0 upgraded, 0 newly installed, 0 to remove and 96 not upgraded.
>Updated Git hooks.
>Git LFS initialized.
```

```
!git config --global user.name "{username}"
!git config --global user.email "{user_email}"
!git add .
!git commit -m 'adding gitattributes'
!git push origin

>On branch master
>Your branch is ahead of 'origin/master' by 1 commit.
>  (use "git push" to publish your local commits)
>
>nothing to commit, working tree clean
>fatal: cannot exec '.git/hooks/pre-push': Permission denied
>^C
```

The above error simply hangs (thinking) until I force-quit the cell.

**System environment**
Pushing LFS files from Google Colab to Github

**Output of `git lfs env`**
```
git-lfs/3.1.2 (GitHub; linux amd64; go 1.17.6)
git version 2.17.1

Endpoint=https://{username}:{auth_key}@github.com/{username}/gics_sectors.git/info/lfs (auth=none)
LocalWorkingDir=/content/gdrive/MyDrive/gics_sectors
LocalGitDir=/content/gdrive/MyDrive/gics_sectors/.git
LocalGitStorageDir=/content/gdrive/MyDrive/gics_sectors/.git
LocalMediaDir=/content/gdrive/MyDrive/gics_sectors/.git/lfs/objects
LocalReferenceDirs=
TempDir=/content/gdrive/MyDrive/gics_sectors/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/content/gdrive/MyDrive/gics_sectors/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_PAGER=cat
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Checking git LFS status**

```
!git lfs status

>On branch master
>Objects to be pushed to origin/master:
>
> List of files to be pushed...
> *.svg
> *.svg
> *.csv
> *.csv
>
>Objects to be committed:
>
>
>Objects not staged for commit:
```

**Attempting to LFS push**

```
!git lfs push origin master
Uploading LFS objects: 100% (22/22), 3.3 MB | 0 B/s, done.
```

Shows that there's 22 files to push to LFS. I'm not sure if it completed the 3.3 MB because it shows 0 B/s done... These files certainly don't show up on Github however...

**Comment by bk2204** [comment]
Hey,

The error you're getting for the Git LFS hook is `EACCES`, and that likely means that you're on a file system that's `noexec`, which prevents the hooks from working.  You can verify that by running `mount` and `pwd`.  If so, then you'll need to avoid running `git lfs install` and will need to run `git lfs push --all` before pushing with Git the normal way.

You may also want to reach out to Google and ask them not to place your repository on a `noexec` partition.

**Comment by loewenm** [comment]
Thanks for the reply @bk2204. I am working in a subfolder in `/content/gdrive/`.

In fact, every time that login, I follow this proceedure:

```
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)
%cd /content/gdrive/MyDrive/{project folder}
```

When I print the working directory (pwd), it indeed shows: `/content/gdrive/MyDrive/{project folder}`

Should I be hosting my working directory somewhere else? Am I missing something here?

Alas, by not running `git lfs install`, Colab doesn't recognize LFS and will throw an error. 

If I do install LFS and then run `!git lfs push origin master` I get the output at the bottom on my original message above...

I will contact Google to ask to be placed on a `noexec` partition, but they have never responded to my emails in the past (i.e. tried twice in the past), so I'm cautious there as well.

Any other thoughts?  Do you have an example notebook that shows successful communication between Colab and Github LFS that I can look at?

**Comment by bk2204** [comment]
Hey,

You definitely don't ever want to store a Git repository in a Google Drive instance.  It's known that Google Drive and other cloud syncing services can corrupt repositories without notice.  That's almost certainly why your partition is effectively `noexec`, because it probably doesn't contain the relevant metadata to store the executable bit.

You should use a repo that is not located on a Google Drive or any other cloud syncing service, and instead use a regular Linux or macOS partition.

I unfortunately can't be otherwise of great help here, because I've never used Colab.

**Comment by loewenm** [comment]
When I run simply `mount`, I get the following message:

```
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/{a giant list of directories with random alphanumeric strings}/diff,workdir=/var/lib/docker/overlay2/{random_alphanumeric_string}/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup type cgroup2 (ro,nosuid,nodev,noexec,relatime,nsdelegate)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5989376k)
/dev/dm-0 on /sbin/docker-init type ext2 (ro,relatime)
tmpfs on /var/colab type tmpfs (rw,nosuid,nodev,noexec)
/dev/sda1 on /etc/resolv.conf type ext4 (rw,nosuid,nodev,relatime,commit=30)
/dev/sda1 on /etc/hostname type ext4 (rw,nosuid,nodev,relatime,commit=30)
/dev/sda1 on /etc/hosts type ext4 (rw,nosuid,nodev,relatime,commit=30)
tmpfs on /var/colab/shared type tmpfs (rw,nosuid,nodev,noexec)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime)
tmpfs on /sys/firmware type tmpfs (ro,relatime)
drive on /content/gdrive type fuse.drive (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```

**Comment by loewenm** [comment]
Yeah - I'm starting to realize the limitations of using Colab... 

I've been using it as a cost-effective cloud compute option, but the process of organizing files and version control is extremely limited.

My process has been to collect data using my local machine/laptop, use Git for version control and push to Github as the remote _origin master_. I'd then git pull into GDrive and mount into the Colab environment. This works like a charm for regular Git repos. However, as soon as I attempt to use LFS everything falls apart due to _hooks_ permissioning. I have *.csv files that are pushing 500 MB, so LFS is necessary for this project. I guess that I'm SOL.

**Comment by bk2204** [comment]
Hey,

As I mentioned, as a core Git contributor, I would really strongly recommend against using Google Drive for your repository whether or not it's using Git LFS because of the risk of corruption.  If you clone the repository fresh from GitHub into your Colab instance outside of Google Drive, it will probably work just fine, but it won't have this problem since it isn't in Google Drive.  That's what I would recommend here.

**Comment by loewenm** [comment]
I hear yah man. Thank you for the insight. 

In the future I'll be simply downloading the resulting _output files_ generated in Colab and host primarily on Github.
