### ISSUE TITLE
Does Git LFS support directory locking, if so what is the command.

### ISSUE THREAD

**Issue by hackerrank2** [git-lfs/git-lfs#4940]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by hackerrank2** [comment]
What is the command for Git LFS to support directory locking.

I tried this command:

git lfs lock <directory-name>/*.yaml

Only first file got locked, remaining did not get locked.


Also sometimes I get the following error message : Lock failed: missing protocol: ""

**Comment by bk2204** [comment]
Hey,

Could you provide the output of `git lfs env` as requested?  That would tell us if you're using a version which should support locking multiple files or not.

**Comment by bk2204** [comment]
Since we haven't heard back here, I'm going to close this.
