### ISSUE TITLE
Can't commit to main - "cannot add to the index - missing --add option?"

### ISSUE THREAD

**Issue by saja2196** [git-lfs/git-lfs#4944]
**Describe the issue**
I'm unable to "commit to main" via Github Desktop. I created a folder A (called CO) on the github website, cloned that, I copy pasted folder B (called Banner_Scripts) into folder A 

**System environment**
OS: Windows 10 Education

**Error**
`error: invalid path 'Banner_Scripts/'
error: Banner_Scripts/: cannot add to the index - missing --add option?
fatal: Unable to process path Banner_Scripts/` 

**Additional context**
![image](https://user-images.githubusercontent.com/102328670/163452557-b7198c22-876f-43fb-b8a4-625e2a056fee.png)

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I think you might be looking for support with GitHub Desktop, while this project is Git LFS, an open source client for the Git LFS protocol.

There's some [advice](https://github.com/desktop/desktop#i-have-a-problem-with-github-desktop) in the GitHub Desktop repository on getting help with issues using it, if that helps.  Good luck!
