### ISSUE TITLE
Proposal: add a `--file` flag to `git lfs install` in order to write the filter configuration to an arbitrary file

### ISSUE THREAD

**Issue by matteocoder** [git-lfs/git-lfs#4947]
**Describe the issue**
Currently, `git lfs install` only supports setting the smudge and clean filters globally by writing to the `~/.gitconfig` file.
Git itself also supports reading its global configuration from the `~/.config/git/config` file, if the user wishes to keep their home directory clean.
Adding a `--file` flag would allow such user to set the filters in their config file of choice, thus avoiding the presence of multiple global git configs.
**System environment**
git version 2.35.2.windows.1, Microsoft Windows [Version 10.0.22000.556]

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.35.2.windows.1
```

**Comment by chrisd8088** [comment]
Hi, thanks for the idea of supporting `$XDG_CONFIG_HOME/git/config`, `$HOME/.config/git/config` as a default for that option.  It would be a nice enhancement, so I'm marking it as such, and if anyone feels like contributing a patch, those are always extremely welcome!  Thanks again!
