### ISSUE TITLE
Git-lfs migrate doesn't migrate all tags 

### ISSUE THREAD

**Issue by danycosta23** [git-lfs/git-lfs#4952]
Hello everyone, I'm having a problem migrating a repo using git-lfs.  I'm following these steps:

```
git clone --mirror git_to_mirror.git 
git lfs install 
git lfs migrate import --everything include="*.tar.xz"
git remote add upstream git@github.com_new_repo
git push --mirror 
```
I already used this steps to mirror other repos and it worked fine! The thing is that this repo that I'm trying to mirror is very big and has more than 56k commits. Everything works fine until I try to push to the new remote, I'm not sure, but I think the git lfs migrate import is not migrating all tags, and there are some refs that are still poiting to old commits with those files bigger than 100 MB.

**Comment by danycosta23** [comment]
When I try to push to the remote I receive the following error:
![imagem](https://user-images.githubusercontent.com/99989506/163990751-9340e961-dc3a-4a74-85a4-867e2c896e9f.png)
This just says that the files were not fully removed from the the repo history. In the end I get all the refs where the files are still being referenced , these is just an example:
![imagem](https://user-images.githubusercontent.com/99989506/163990687-e37ca841-f117-4306-947a-1566094d9fd4.png)

**Comment by bk2204** [comment]
Hey,

What I think you're seeing is #4810, which is that we only process `refs/heads` and `refs/tags`. plus a few other sets of references.  We plan to fix that in v3.2.0.  Since this looks to be a duplicate, I'm going to close it in favour of that issue.

**Comment by danycosta23** [comment]
Hey @bk2204 thank you for your reply, what is your suggestion? Try to migrate every ref with include-ref?

**Comment by bk2204** [comment]
You can specify `--include-ref` to handle other refs if you'd like.  You could also try BFG instead, which may work better until we fix the `--everything` option.
