### ISSUE TITLE
Corrupted tbz2 files

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [git-lfs/git-lfs#4955]
**Describe the bug**
After adding tbz2 files of around 1GB, and performing normal git operations (squash, rebase), files appear corrupted on decompression.

**To Reproduce**
1. Add https://developer.nvidia.com/embedded/l4t/r32_release_v5.2/t186/tegra_linux_sample-root-filesystem_r32.5.2_aarch64.tbz2 to a commit
2. Add other files
3. Squash or rebase
4. Decompress the original file

**Expected behavior**
No corruption

**System environment**
Ubuntu 20.04

**Output of `git lfs env`**
```
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.25.1

Endpoint=https://github.com/xxx/xxx.git/info/lfs (auth=basic)
LocalWorkingDir=/home/xxx/Documentos/xxx/xxx
LocalGitDir=/home/xxx/Documentos/xxx/xxx/.git
LocalGitStorageDir=/home/xxx/Documentos/plantium/xxx/.git
LocalMediaDir=/home/xxx/Documentos/xxx/xxx/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/xxx/Documentos/xxx/xxx/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/xxx/Documentos/xxx/xxx/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Are you seeing this problem with Git LFS or with just plain Git?  I don't see any mention of tracking LFS files or any of the contents of `.gitattributes`.  Could you provide your `.gitattributes` file in this case?  Also, it would be helpful if you could provide a shell script that reproduces the problem using a fresh repository.  That would help us reproduce it on our end.

**Comment by Emmanuel-Messulam** [comment]
This was a problem with the RAM of the device.
