### ISSUE TITLE
"git lfs fetch upstream" no fetch lfs objects from upstream

### ISSUE THREAD

**Issue by wanachengwang** [git-lfs/git-lfs#4967]
**Describe the bug**
"git lfs fetch upstream" no fetch lfs objects from upstream and cause merge failure

**To Reproduce**
1. Fork a downstream repo from http://xxxx/tstupstream.git
2. Add a lfs file (chrome.dll) and commit into http://xxxx/tstupstream.git
3. In downstream repo, "git remote add upstream http://xxxx/tstupstream.git"
4. "git lfs fetch upstream" ("git lfs fetch -a upstream" would cause stuck with message "Dowloading LFS objects: 0%(0/1), 0B|0B/s")
5. "git merge upstream/master" would report error
    
         error downloading object: chrome.dll (6debf91): Smudge error: Error downloading chrome.dll (6debf91f1b53acc79ff63b4edaa1c44f0f82a90ff4843d99a4246c809f22156a): 
         [6debf91f1b53acc79ff63b4edaa1c44f0f82a90ff4843d99a4246c809f22156a] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it

**Expected behavior**
git lfs fetch upstream can fetch lfs objects from upstream and merge successfully.

**System environment**
Windows10

**Output of `git lfs env`**

    $ git lfs env
    git-lfs/3.1.4 (GitHub; windows amd64; go 1.17.8)
    git version 2.36.0.windows.1

    Endpoint=http://xxxx/tst-downstream.git/info/lfs (auth=basic)
    Endpoint (upstream)=http://xxxx/tstupstream.git/info/lfs (auth=basic)
    LocalWorkingDir=F:\tst-downstream
    LocalGitDir=F:\tst-downstream\.git
    LocalGitStorageDir=F:\tst-downstream\.git
    LocalMediaDir=F:\tst-downstream\.git\lfs\objects
    LocalReferenceDirs=
    TempDir=F:\tst-downstream\.git\lfs\tmp
    ConcurrentTransfers=8
    TusTransfers=false
    BasicTransfersOnly=false
    SkipDownloadErrors=false
    FetchRecentAlways=false
    FetchRecentRefsDays=7
    FetchRecentCommitsDays=0
    FetchRecentRefsIncludeRemotes=true
    PruneOffsetDays=3
    PruneVerifyRemoteAlways=false
    PruneRemoteName=origin
    LfsStorageDir=F:\tst-downstream\.git\lfs
    AccessDownload=basic
    AccessUpload=basic
    DownloadTransfers=basic,lfs-standalone-file,ssh
    UploadTransfers=basic,lfs-standalone-file,ssh
    GIT_EXEC_PATH=D:/Program Files/Git/mingw64/libexec/git-core
    git config filter.lfs.process = "git-lfs filter-process"
    git config filter.lfs.smudge = "git-lfs smudge -- %f"
    git config filter.lfs.clean = "git-lfs clean -- %f".

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having problems.  I think the way this is supposed to work is that you specify `git lfs fetch upstream` and then a ref to pull something other than the default branch that you're on.  In that case, you'd need to first run `git fetch upstream` and then run `git lfs fetch upstream upstream/master` to fetch the objects, and then you can run `git merge upstream/master`.

If you don't run `git fetch upstream` first, then Git LFS doesn't have the Git objects to look at to determine which LFS objects are in use.  Once you have those, you can ask to use `git lfs fetch upstream upstream/master` to look through the history of `upstream/master` and download the objects from `upstream`.

Hopefully this is helpful.

**Comment by wanachengwang** [comment]
yes, it works. thank you!

**Comment by wanachengwang** [comment]
yes, it works. thank you!
