### ISSUE TITLE
Extracting Lock Behavior

### ISSUE THREAD

**Issue by jasonnicholson** [git-lfs/git-lfs#4978]
**Describe the issue**
We have trouble merging Simulink files in a large team. Simulink files are code but in graphical form. The file type is XML in our repos; an XML diff makes no sense. We need to do all the regular things such as diff and merge Simulink files. The trouble is fixing conflicts across branches is the most painful thing we do. MathWorks has a diff and merge tool for Simulink files. However, the experience is still lacking compared to a textual three-way merge. This is where LFS locks seem to fit. Putting Simulink files into LFS should work such that we can use locks. However, I struggle to convince a giant enterprise team to do this. Instead, the current way of doing things is not to put Simulink files in LFS. Therefore, what do you think if I extracted the locking behavior from LFS into a stand-alone item that works via githooks? Is this even a good starting place?

**Comment by jasonnicholson** [comment]
After looking into LFS locks closer, GitLab documents that I can lock files that aren't in LFS. That is what I am looking for! **Is there a reason this is not more clear in the LFS documentation?** I have been through documentation many times but admit I still may have missed it. Pointing out my error is appropriate if that is the case.
https://docs.gitlab.com/ee/user/project/file_lock.html
![image](https://user-images.githubusercontent.com/1058191/165951566-a545383b-ad5e-484f-b7de-f92b93b2a020.png)

**Comment by bk2204** [comment]
Hey,

You can indeed lock files that aren't in LFS, which should probably meet your needs here.  We've got an issue open to improve the documentation in #4881.
