### ISSUE TITLE
How to fix incorrect repository path?

### ISSUE THREAD

**Issue by horato** [git-lfs/git-lfs#4979]
**Describe the issue**
Hi, I have updated my visual studio 2019 to version 16.11.13 and these popped up in the pending changes window.
![obrazek](https://user-images.githubusercontent.com/5708354/165934524-ef001dc9-37b5-4711-8cdc-6a48a8d6f124.png)
I've seen this bug being somewhat solved in newer releases, but git version 2.30.2 (which includes LFS 2.13.2) is the newset version I can use due to NTLM support being removed from LFS. I use basic auth to connect to our company's TFS server and with the NTLM support missing it just keeps going back and forth with 401s on negotiate auth, completely ignoring basic auth as the server considers NTLM/negotiate the "safer" choice. Kerberos isn't configured for us on the TFS server.

Is there any way (environment variable, config, etc) to make LFS use the correct path to .git folder on the git/lfs version I am using?

Thanks

**System environment**
Windows 10
TFS server Version 15.117.27414.0,
```$ git config -l
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager-core
core.editor="C:\\Program Files (x86)\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Name Surname
user.email=name.surname@company.cz
core.autocrlf=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.http://tfs-server:8080.provider=generic
credential.helper=manager
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=http://tfs-server:8080/tfs/Team/_git/Repo
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.http://czcskdp-tfs2:8080/tfs/Team/_git/Repo.git/info/lfs.access=ntlm
gui.wmstate=normal
gui.geometry=1383x631+260+260 300 196
```

**Output of `git lfs env`**
```$ git lfs env
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
git version 2.30.2.windows.1

Endpoint=http://tfs-server:8080/tfs/Team/_git/Repo.git/info/lfs (auth=ntlm)
LocalWorkingDir=C:\Repo\Repo
LocalGitDir=C:\Repo\Repo\.git
LocalGitStorageDir=C:\Repo\Repo\.git
LocalMediaDir=C:\Repo\Repo\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Repo\Repo\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Repo\Repo\.git\lfs
AccessDownload=ntlm
AccessUpload=ntlm
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
```$ git version
git version 2.30.2.windows.1```

**Comment by bk2204** [comment]
Hey,

We made some changes in 3.0 that changed how we canonicalize paths that may have fixed this.  There's no way to customize the path detection on Git LFS, although you could try setting `GIT_DIR` in the environment, which should affect both Git and Git LFS.  You should also know that we've put out a security release, Git LFS 3.1.4, which affects all earlier versions on Windows.

So if you'd prefer to stay on 2.13, which we don't recommend, there isn't a way to control this other than the standard Git environment variables.

**Comment by horato** [comment]
Hi,
Thank you for the suggestion. It seems that setting core.worktree (which should be the non-global equivalent of GIT_DIR) did the trick. The git plugin in VS is still terribly broken, but at least it doesn't add any folders and git can be managed through command line.

I don't wish to stay at 2.13, but I really have no other choice. Not until kerberos is configured.

**Comment by Suraj-pandey12** [comment]
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
:
