### ISSUE TITLE
question: gzip enconding/transport on upload

### ISSUE THREAD

**Issue by axkibe** [git-lfs/git-lfs#4985]
Hi, I'm currently writing yet another LFS server implementation (in node.js)

One thing that isn't clear to me, (how) can I get the lfs client to gzip the data when it uploads an object with a PUT request?

I see it sets the "'accept-encoding': 'gzip'" header, so I guess the server reply could be gzipped (which is empty on a PUT request anyway). I tried suggesting to the client to use gzip encoding by setting "Content-Encoding: gzip" in the "header" object of the batch API upload reply and while it reproduces the header on the PUT request it's not actually gzipped (as far as I can tell, I'm not 100% sure tough not something within node automatically unzips it for me without asking). But maybe I'm also messing up the accept-encoding thing on my part on the put request.

I want to store the objects gzipped on disk, would be no biggie to gzip the stream while it is incoming, but IMO it would be better if the transport already happens gzipped and I just stream it to disk verbatim.

Long question short, should the lfs client upload PUT streams with gzip compression when everything is done correctly on the server part, or doesn't it just do it (also okay for me, just don't want to invest time to figure it out, if it currently can't)

**Comment by KalleOlaviNiemitalo** [comment]
Previous discussion in <https://github.com/git-lfs/git-lfs/issues/3683#issuecomment-744681153> indicates compression is not supported for upload

**Comment by axkibe** [comment]
Thanks for the info.

(Then I'll just gzip it on server side on upload)
