### ISSUE TITLE
Issue when pushing to origin: batch response: Post "https://admin@server.com.git/info/lfs/objects/batch": dial tcp: lookup server.com.git: no such host

### ISSUE THREAD

**Issue by tmielsch** [git-lfs/git-lfs#4986]
When I want to push a git LFS tracked file I get this response. It seems like somehow there is a "/" missing, between the server address and the rest of the path. But I have no idea how to fix that. 

I should add, I'm running the remote on a private server. Standard git works without issues with the same configuration.

The server is configured using git --bare init, so it is just a folder /var/www/repo.git/ - this folder is forwarded to from the url https://server.com/ to end up in https://server.com/var/www/repo.git/

So the host URL should be rather https://admin@server.com/info/lfs/objects/batch" than "https://admin@server.com.git/info/lfs/objects/batch" I assume. But even then, when I go to that location, there is no info/lfs - it is 

/info
/lfs
//objects

EDIT: Apparently it is my apache config file that is the issue. https://stackoverflow.com/questions/69578430/git-lfs-and-http-client-authentication - I don't know what is wrong with it though

```
DavLockDB /usr/local/apache/var/DavLock



<IfModule mod_ssl.c>
<VirtualHost server.com:443>
        ServerAdmin admin@your_domain
        ServerName your_domain
        ServerAlias your_domain
        DocumentRoot /var/www/repo.git
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLCertificateFile /etc/letsencrypt/live/server.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/server.com/privkey.pem

        Include /etc/letsencrypt/options-ssl-apache.conf

        Alias /LO86.git /var/www/repo.git

        <Directory /var/www/repo.git>
                DAV On
                AuthType Basic
                AuthName "Git"
                AuthUserFile /etc/apache2/passwd.git
                Require valid-user
        </Directory>

</VirtualHost>
</IfModule>
```

I understand that this is probably going beyond this issue tracker, but still -
Any help is appreciated. Thanks!

**Comment by B00merang** [comment]
> Hey,
> 
> You can't use a bare repository with DAV for Git LFS data. You need a server-side component, such as https://github.com/git-lfs/lfs-test-server/ to make this work. You'll want to proxy the data to the LFS server with a directive like `ProxyPass`.

Do you know of a tutorial or guide that explains how to do this step by step?

**Comment by bk2204** [comment]
I don't.  I have something like this working, but it's highly specific to my Kerberos-based testing setup and is not generally useful.

**Comment by tmielsch** [comment]
Thank you for clarifying! I hope I can figure out where to go from there.

**Comment by bk2204** [comment]
I think we've answered this as well as possible, so I'm going to close this.
