### ISSUE TITLE
fetchexclude no longer works for directories in 3.0.2

### ISSUE THREAD

**Issue by bartlomiej-dawidow** [git-lfs/git-lfs#4994]
**Describe the bug**
The following notation properly excluded a directory in version pre 3.0:
```
[lfs]
	fetchexclude = /ExcludedDir/
```

After upgrading to 3.0.2, it no longer works. Git LFS downloads the contents of ExcludedDir.

**To Reproduce**
1. Create an empty repo.
2. Create an ExcludedDir directory inside the repo.
3. Create a `.lfsconfig` file with the following contents:
```
[lfs]
	fetchexclude = /ExcludedDir/
```
5. Create a `.gitattributes` file with the following contents:
```
* text=auto
*.jpg filter=lfs diff=lfs merge=lfs -text
```
6. Add any jpg image file to ExcludedDir.
7. Add all three files to git, commit and push.
8. Clone the repository to a different folder.

**Expected behavior**
The cloned directory should not include the binary jpg file, only the placeholder link file.

**System environment**
n/a, tested on both Windows and macOS

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; darwin amd64; go 1.17.2)
git version 2.32.0 (Apple Git-132)

Error reading git config: error running /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git 'rev-parse' '--is-bare-repository': 'fatal: not a git repository (or any of the parent directories): .git' 'exit status 128'
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Additional context**
Unity Cloud Build has recently upgraded git-lfs on their macOS build agents. The problem is likely affecting a large number of their customers.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I suspect this is the same bug as #4945, which is fixed in #4951 and should be included in v3.2.0 (which is not yet released).

Can you try with a build from the tip of `main` and see if that resolves your problem?

**Comment by bartlomiej-dawidow** [comment]
Hi and thank you, it does appear to be the same problem as #4945. Unity Cloud Build is a fully managed build service and we cannot change the configuration of their build agents. But we worked around the problem by using the following notation:
```
[lfs]
	fetchexclude = /ExcludedDirectory/**
```

It seems to work with both 3.0.2 and pre-3.0 versions of git-lfs.

**Comment by chrisd8088** [comment]
Great, then I'll close this issue.
