### ISSUE TITLE
Installed Git LFS & Followed Steps But Still Getting Exceeds Filesize of 100 MB Error 

### ISSUE THREAD

**Issue by pinzhi000** [git-lfs/git-lfs#4998]
**Describe the issue**
I cloned my github repo to a folder in my local machine.  Then I followed a series of steps to try and upload / push a large 134MB file (produced from saved tensorflow model) file to my github repo.  Please see the exact command line inputs and results in my screen shot below.  

![image](https://user-images.githubusercontent.com/7343257/167510170-7f0aa710-ec08-4dfc-bdb4-55b1558a2841.png)

**System environment**
Windows 10

**Comment by chrisd8088** [comment]
Does your large file already exist in your repository's history?  Then you need to run `git lfs migrate import` to rewrite your Git history so that the file has always been tracked by Git LFS.  Here's the manual [page](https://raw.githubusercontent.com/git-lfs/git-lfs/main/docs/man/git-lfs-migrate.1.ronn) for that command.

**Comment by pinzhi000** [comment]
the large file has never been in my repository ...

**Comment by chrisd8088** [comment]
OK, I think I see the problem -- you are missing a wildcard `*` character in the pattern in your `git lfs track` command.  It should be `git lfs track *.data-00000-of-00001`, not `git lfs track .data-00000-of-00001` which will only match a file literally named `.data-00000-of-00001` and nothing else.

After you run that and `git add .gitattributes variables.data-00000-of-00001` and then `git commit`, you should be able to confirm that Git LFS is now tracking your file by doing `git lfs ls-files`, `git lfs status`, or `git show HEAD:variables.data-00000-of-00001`.

**Comment by chrisd8088** [comment]
I'm pretty certain that's the problem, so I'm going to close this issue, but please reopen it if that's not the case.

**Comment by chrisd8088** [comment]
@iiakshat -- As you're reporting a different issue, please open a new issue and fill out the all the sections in the issue template, rather than comment on a closed issue.  Thanks!

**Comment by paragg2005** [comment]
not able to push even after migrate command please i need help im not comfortable with github i am unable to push binary file with 136 mb size

**Comment by paragg2005** [comment]
![Screenshot 2023-12-30 141356](https://github.com/git-lfs/git-lfs/assets/146827827/86f50954-54b2-407f-b0c1-3077253b6d68)
![Screenshot 2023-12-30 141356](https://github.com/git-lfs/git-lfs/assets/146827827/d410c89e-d1b6-45ec-8e78-7d0790cef36f)
going for infinite uploading
