### ISSUE TITLE
I can't find the lfs object i pushed on my github repo

### ISSUE THREAD

**Issue by BILY5354** [git-lfs/git-lfs#4999]
Below is the command that i pushed lfs object to Github repo. The lfs Object is called LeavesDiseaseClassification220327.pth, its size is 256MB.

```
git lfs install

git lfs track model_data/LeavesDiseaseClassification220327.pth

 git add .gitattributes

git add model_data/LeavesDiseaseClassification220327.pth

git commit -m "add Lea.pth"

 git push github master # but failed

 git config lfs.https://hua/view-33/Detection-of-plant-leaves-diseases.git/info/lfs.locksverify false

git push  git push github master # this time upload done
```
![image](https://user-images.githubusercontent.com/46767838/167588160-df7b0929-a38c-4b9d-9391-2599015d0b77.png)

Then, i can't find LeavesDiseaseClassification220327.pth in my github repo? I wonder kown what is the problem, thanks.

**Comment by bk2204** [comment]
Hey,

Can you explain what you mean by the statement that you can't find that file in your GitHub repo?  Note that by default, GitHub names the default branch `main`, and on your system it looks like Git defaults to `master`.  It's likely that if you change the branch to `master` in the UI that you'll see your file.

**Comment by BILY5354** [comment]
@bk2204 
Thanks help, i think i probably found out the problem why can't see the LFS file in my repo because i didn't used the '''" "''' when i '''track''' the LFS file. 
Now, it works and i see the LFS file in my repo.
