### ISSUE TITLE
install option for fullpath to lfs

### ISSUE THREAD

**Issue by anatawa12** [git-lfs/git-lfs#5012]
**Describe the issue**
the `git lfs install` command will install `filter.lfs` settings based on `git-lfs` will always be on PATH. 
however, with forge

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

```
$ git lfs env
git-lfs/3.1.4 (GitHub; darwin arm64; go 1.18.1)
git version 2.32.1 (Apple Git-133)

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "/opt/homebrew/bin/git-lfs filter-process"
git config filter.lfs.smudge = "/opt/homebrew/bin/git-lfs smudge -- %f"
git config filter.lfs.clean = "/opt/homebrew/bin/git-lfs clean -- %f"
$ 
$ 
$ 
$ git config alias.lfs
!/opt/homebrew/bin/git-lfs
```

**Additional context**
Any other relevant context about the problem here.

I've changed filter.lfs to fullpath manually so in `git lfs env`, `git config filter.lfs.process` is long.

**Comment by anatawa12** [comment]
I'm not a user of go but I think`os.Executable` can be used.

**Comment by bk2204** [comment]
Yes, but unfortunately, as the docs for it mention, there's no way to know whether that's a symlink or the real path, and in general, it's impossible to know which the user wanted.  For example, I believe the path you've specified is a symlink, not the real binary, and if macOS provided the real binary, it might break when Homebrew upgraded it.  There are definitely OSes where it will be the real binary and where that will definitely not work (e.g., a NixOS environment on Linux).

I also suspect `os.Executable` is likely to be broken on Windows, if my experience with other Go primitives (e.g., `filepath.EvalSymlinks`) is correct.  And it also won't work on Cygwin.

So I think this is probably not a thing we're going to implement.

**Comment by anatawa12** [comment]
I mean if OS returns path to symlink, We shouldn't read symlink (resolve realpath). and on macOS (main target of this feature), it returns a path (not realpath).

**Comment by bk2204** [comment]
I don't think this would only be valuable for macOS.  This would work on Linux, but it would return the real path, not the symlink, and that would result in different behaviour across systems which we'd like to avoid.  And it also isn't guaranteed that users _wouldn't_ want to resolve the path: just because you don't want to doesn't mean that others won't want that behaviour.
