### ISSUE TITLE
Git - "Your push was rejected due to missing or corrupt local objects"

### ISSUE THREAD

**Issue by rick-gwu** [git-lfs/git-lfs#5024]
I created a **new** repo in github and initialized it with a Readme file.
Then I cloned the repo: `git clone https://github.com/abcxyz`
After that I copied a linux odbc driver (linODBC-2.1.tar.gz) from another repo into the new repo at: `drivers/linux`.
Then configured lfs:

```
git lfs install 
git lfs track "*.gz" 
git add .gitattributes
git commit -m " add linux driver"
```

`git push origin master` showed:

```
new file:   .gitattributes
new file:   drivers/linux/linODBC-2.1.tar.gz
```

So I proceeded to do a regular git push:

```
git add .
git commit -m "add file"
git push
```

At this point, I get the error:

```
Git LFS upload failed:   0% (0/1), 0 B | 0 B/s                                                                          
  (missing) drivers/linux/linODBC-2.1.tar.gz (1v6b012622fd7aba242031c4885707e5feb696b3131e4b66080799ee756kj4bd)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: `git config lfs.allowincompletepush true`
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
error: failed to push some refs to 'https://github.com/ukhc/abcxyz-svc.git'
```

`git lfs status` shows:

```
On branch master
Objects to be pushed to origin/master:

    drivers/linux/linODBC-2.1.tar.gz (1v6b012622fd7aba242031c4885707e5feb696b3131e4b66080799ee756kj4bd)

Objects to be committed:


Objects not staged for commit:
```

`git lfs ls-files` shows:

`1v6b012622 - drivers/linux/linODBC-2.1.tar.gz`

How can I resolve this?
`git lfs fetch` won't help, because the file doesn't exist on the server. Well it exists in github, but in a different repo.
`git add --renormalize path/to/file` didn't help either.

- - - - - - - - - -
_OS: MacOS Monterey 12.3.1
Git Version: 2.36.1_
[git_push_info.txt](https://github.com/git-lfs/git-lfs/files/8766214/git_push_info.txt)

**Comment by bk2204** [comment]
Hey,

It looks like the message "Git LFS upload failed" is interesting.  Could you go ahead and run your `git push` command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include the output here (probably as an attachment)?

**Comment by rick-gwu** [comment]
> Hey,
> 
> It looks like the message "Git LFS upload failed" is interesting. Could you go ahead and run your `git push` command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include the output here (probably as an attachment)?

Attachment added.

I just replaced: _https://github.com/private_company/private_repo.git_
With: _https://github.com/abcxyz.git_
Lines: 2, 3, 4, 105, 106, 107, 122, 125, 157, 158, 240

Replaced: _/private_company/private_repo.git_
With: _/abcxyz.git_
Lines: 199, 200

**Comment by bk2204** [comment]
Hey,

Did you copy the pointer file from the other repo, or the actual large file?  It sounds like you might have done the former, in which case, you'd need to copy the large file itself and then run `git add .`.  In order to push the file, it needs to exist in this particular repository.

**Comment by rick-gwu** [comment]
After doing what I mentioned above, when I run `git lfs fsck`, it states that the object that I'm trying to upload is corrupt, then it gets moved to _.git/lfs/bad_:

```
objects: corruptObject: drivers/linux/linODBC-2.1.tar.gz (1v6b012622fd7aba242031c4885707e5feb696b3131e4b66080799ee756kj4bd) is corrupt
objects: repair: moving corrupt objects to /Users/UserName/Dev/project/.git/lfs/bad
```

**Comment by rick-gwu** [comment]
_linODBC-2.1.tar.gz_ is still in _drivers/linux/_

I removed it, copied/pasted it again, but I got the same error.

That's not the real object ID, it is not a valid one. I just replaced with a random string for demo purposes. But I'm using what what shown in the original error message. Is that not the correct object ID here?

```
Git LFS upload failed:   0% (0/1), 0 B | 0 B/s                                                                          
  (missing) drivers/linux/linODBC-2.1.tar.gz (1v6b012622fd7aba242031c4885707e5feb696b3131e4b66080799ee756kj4bd)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: `git config lfs.allowincompletepush true`
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
error: failed to push some refs to 'https://github.com/ukhc/abcxyz-svc.git'
```

**Comment by bk2204** [comment]
Hey,

Can you find the original file in the original repository and run `sha256sum -a 256 linODBC-2.1.tar.gz` in that directory (changing the name if need be) and provide the output?  And can you also do that in the working tree for this repository as well?

**Comment by rick-gwu** [comment]
Well, I have it working now. I followed the same exact steps on a Windows machine and just it worked.

```
Windows 10 amd64
git version 2.25.0
git-lfs version 2.9.2
```

I tried on two Mac computers, but I can't get it to work anymore (although it used to).

```
Mac #1:
MacOS Monterey 12.3.1
git version 2.36.1
git-lfs version 3.1.4
```

```
Mac #2:
MacOS Monterey 12.3.1
git version 2.32.0 (Apple Git-132)
git-lfs version 3.1.4
```

**Comment by bk2204** [comment]
Hey,

I can't really tell what the relevant difference there is because you have many factors: a different OS, a different Git version, and a different Git LFS version.  Also, it may be that using the UI to copy and paste works differently on a Mac versus on Windows.

It would really help if you could provide the output of running `shasum -a 256` on the files on the Mac, which would tell us if they have the expected hash.  The hash is not sensitive.  Additionally, you may find that things work better for you if you copy via `cp` on the command line rather than through the UI.

**Comment by rick-gwu** [comment]
I tried both ways on the Mac, copy/paste via UI and `cp`.

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back from you on this, I'm going to close it.  If you can provide the information requested, we can look into this further.

**Comment by patriotyk** [comment]
I have exactly the same error.

```
Git LFS upload failed:   0% (0/2), 0 B | 0 B/s                                                                                                                                                            
  (missing) data/back.webm (d127c966e991ed84442df5449c1b3c16af5d2da0517fcc2f8a8d8043d5e406a2)
  (missing) data/svdreams.vtt (b6543ca624b7b27e171085dd54818c3c01331a6241639c2ba5bb3e06d851c1b5)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: `git config lfs.allowincompletepush true`

```

```
shasum -a 256 data/back.webm                           
3cc23e09af8d87e4752bcd61ed7b6d8c13f70ca7e07cc2c007a0b0b41ba554da  data/back.webm
```

```
git-lfs --version
git-lfs/3.3.0 (GitHub; darwin arm64; go 1.19.3)
```

```
cat .gitattributes
*.wav filter=lfs diff=lfs merge=lfs -text
*.webm filter=lfs diff=lfs merge=lfs -text
```

Files are correct. Also as you can see it tracks .vtt file as LFS file but should not. I added them with `git add data`

**Comment by bk2204** [comment]
Hey,

Could you please open a new issue, including that information and filling out the issue template, and including the steps you've taken (which you can find in your shell history) to get into this situation?  I suspect you're seeing something different than the original user here.

**Comment by patriotyk** [comment]
Ok, will do it later.

**Comment by soundasleep** [comment]
I worked out why I was getting this error (may help others): I was trying to push up objects that were lfs pointers (the ~100 byte reference files), not the actual files themselves. Check the size of the files you're trying to push too.

**Comment by patriotyk** [comment]
I have found that instead of correct content of files each file contains such text:

```
version https://git-lfs.github.com/spec/v1
oid sha256:b6543ca624b7b27e171085dd54818c3c01331a6241639c2ba5bb3e06d851c1b5
size 25184
```

Who did this and how it happens I don't know. I just started over.

**Comment by l0d0v1c** [comment]
Exactly the same error and the content of the file is replace by 
`version https://git-lfs.github.com/spec/v1
oid sha256:...`
On mac `(torch) pro@UmaxLuc % git version
git version 2.39.3 (Apple Git-145)
(torch) pro@UmaxLuc % git lfs version
git-lfs/3.3.0 (GitHub; darwin arm64; go 1.19.3)`

**Comment by tsei902** [comment]
Same here, the pytorch_model.bin contained version https://git-lfs.github.com/spec/v1
oid sha256:c13a92271cf0c42c17cbd10e5f9477221e0abbdc58970f836f3091492f0e3b35
size 891626129

**Comment by bk2204** [comment]
As requested above, please open a new issue, including any relevant information and filling out the issue template.  This is a different problem from what the original user reported.
