### ISSUE TITLE
`git lfs fetch --all` aborts on first error instead of trying to fetch from all remotes

### ISSUE THREAD

**Issue by hybridherbst** [git-lfs/git-lfs#5025]
**Describe the bug**
We're using multiple remotes that each have their own LFS storage. When one of those gains a new LFS file, `git lfs fetch --all` fails depending on the order of remotes that a local user has. It looks like it aborts on the first file not being found (which would be expected) instead of actually fetching from all remotes (which would result in the correct files being there).

**To Reproduce**
1. Have two server repositories each with LFS enabled
2. Have one working copy (CopyA) with only RemoteA
3. Have one working copy (CopyB) with RemoteB and RemoteA
4. Push a FBX file from CopyA (assuming .fbx is in .gitattributes as LFS file type)
5. Run `git lfs fetch --all` from CopyB

**Expected behavior**
File is found on LFS in RemoteA and downloaded
Actual: `fetch --all` aborts because as expected it can't find the file on RemoteB and never even tries to fetch from RemoteA. This is counterintuitive.

**Workaround**
As a workaround, one can explicitly run
`git lfs fetch --all RemoteA`
`git lfs fetch --all RemoteB`
to actually have all LFS files. But I think it would be better if `fetch --all` didn't simply abort.

**Output of `git lfs env`**
```
git-lfs/3.1.4 (GitHub; windows amd64; go 1.17.8)
git version 2.36.1.windows.1
```

**Comment by bk2204** [comment]
Hey,

This is working as designed.  `git fetch --all` fetches from all remotes, but `git lfs fetch --all` is designed to fetch all objects from the given remote (or the default remote if none is given), not all remotes.  They're not designed to do the same thing, so it's expected that you have to specify multiple remotes if you want to fetch more than one remote.

**Comment by hybridherbst** [comment]
I think it's pretty confusing that similar-sounding commands do entirely different things... thanks for clarifying though.
