### ISSUE TITLE
Hey,

### ISSUE THREAD

**Issue by Aleeca91** [git-lfs/git-lfs#5029]
Hey,

Is that the real object ID?  That's not a valid object ID: it has to be a hex value, so there's something incorrect about the OID you're using if that's what you're really seeing.

What I'd try to do here is copy the file into the working tree again and run `git add .` and then `git commit --amend` to re-add the pointer file to the commit.

_Originally posted by @bk2204 in https://github.com/git-lfs/git-lfs/issues/5024#issuecomment-1137496870_

**Comment by chrisd8088** [comment]
This doesn't seem like a meaningful issue description, so I'm going to close the issue.
