### ISSUE TITLE
git-lfs help contradicts the documentation

### ISSUE THREAD

**Issue by rpgoldman** [git-lfs/git-lfs#5041]
**Describe the bug**

When I type `git lfs help` to the shell, I see (among other things) the following:

```
Examples
--------

To get started with Git LFS, the following commands can be used.

 1. Setup Git LFS on your system. You only have to do this once per
    repository per machine:

        git lfs install
```

However, when I look at [the documentation page](https://git-lfs.github.com/), I see this:

> Download and install the Git command line extension. Once downloaded and installed, set up Git LFS for your user account by running:

> `git lfs install`

> *You only need to run this once per user account.* [italics mine]

So one of these two must be wrong: either you need to install in each working copy, or you only need to install once for your user account on whatever machine you are working on.

**To Reproduce**

`git lfs help`

**Expected behavior**

Help string agrees with documentation (or documentation is revised)

**System environment**

MacOS Monterey

git-lfs from Homebrew

```
$ git-lfs --version
git-lfs/3.2.0 (GitHub; darwin arm64; go 1.18.2)
```

**Comments**

This is related to #4032, which seems to have *partially* fixed the problem, but it seems like the out-of-date wording persists in at least one location

When I search for "per repository" I find it [here](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs.1.ronn) in the source code for the man page, in "Examples".

I don't know what the relationship is between the man page and the help text.

**Comment by rpgoldman** [comment]
@bk2204 Probably enough to just replace "repository" in that sentence with "user."

If you'd like, I can probably make a PR for that. Assuming that would fix the `help` command as well, because it pulls from that man page?

**Comment by bk2204** [comment]
Normally, I'd absolutely say yes to a PR fixing that.  And yes, we pull from the manual page.

However, right now, I'm in the middle of converting the documentation from one format to another, and such a change would likely be lost in the shuffle, so I'd like to avoid that.  I plan to go through all the docs issues and fix as many of them as possible before merging that, so it should be relatively soon.
