### ISSUE TITLE
error: failed to push some refs to '/home/git/xxx'

### ISSUE THREAD

**Issue by kemin711** [git-lfs/git-lfs#5042]
**Describe the bug**
After starting a new branch, one binary file updated, commit fine, but push got error message:
`
EOFoading LFS objects: 100% (1/1), 247 MB | 0 B/s                                                                                                 
error: failed to push some refs to '/home/git/dspkg'
`

**To Reproduce**
1. Set up lfs as instructed
2. create a new branch the usual way
3. changed binary file on local repos, the push in one of the branches

**Expected behavior**

should finish push.

**System environment**
Linux, latest version of lfs

**Output of `git lfs env`**

`git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
git version 2.36.1.299.gab336e8f1c

Endpoint=file:///home/git/dspkg (auth=none)
LocalWorkingDir=/home/kzhou/dspkg
LocalGitDir=/home/kzhou/dspkg/.git
LocalGitStorageDir=/home/kzhou/dspkg/.git
LocalMediaDir=/home/kzhou/dspkg/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/kzhou/dspkg/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/kzhou/dspkg/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`
**Additional context**
Any other relevant context about the problem here.

**Comment by kemin711** [comment]
Not sure my following fixed the problem:
git pull origin master
git pull origin 1.7.1
then it fixed the above problem.

**Comment by kemin711** [comment]
Now the above is no longer working.

`git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 5 commits.
  (use "git push" to publish your local commits)

git push
EOFoading LFS objects: 100% (1/1), 3.7 MB | 0 B/s                                                                               
error: failed to push some refs to '/home/git/dspkg'
`

**Comment by bk2204** [comment]
Hey,

Can you please run the failing push as `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push` (including any necessary arguments) and then attach the output here?

**Comment by kemin711** [comment]
GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push
08:35:27.767557 git.c:460               trace: built-in: git push
08:35:27.768327 run-command.c:654       trace: run_command: unset GIT_PREFIX; 'git-receive-pack '\''/home/git/dspkg'\'''
08:35:27.772397 git.c:460               trace: built-in: git receive-pack /home/git/dspkg
08:35:27.773994 run-command.c:654       trace: run_command: .git/hooks/pre-push origin /home/git/dspkg
08:35:27.778346 git.c:749               trace: exec: git-lfs pre-push origin /home/git/dspkg
08:35:27.778414 run-command.c:654       trace: run_command: git-lfs pre-push origin /home/git/dspkg
08:35:27.785299 trace git-lfs: exec: git 'version'
08:35:27.788975 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote' '-v'
08:35:27.792280 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
08:35:27.795550 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
08:35:27.798911 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
08:35:27.802102 trace git-lfs: exec: git 'config' '--includes' '-l'
08:35:27.805139 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
08:35:27.808165 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
08:35:27.811624 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
08:35:27.815751 trace git-lfs: pre-push: refs/heads/master 3e70a4ef583fbf932a6c2cbcb65d78e5d276e8e3 refs/heads/master adeb01ab4b222feeaa5d4bc08f69310f3c25f870
08:35:27.815913 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
08:35:27.819772 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' 'origin'
08:35:27.828796 trace git-lfs: tq: running as batched queue, batch size of 100
08:35:27.829002 trace git-lfs: run_command: git rev-list --objects --ignore-missing --stdin --
08:35:27.829023 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-list' '--objects' '--ignore-missing' '--stdin' '--'
08:35:27.829729 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'cat-file' '--batch-check'
08:35:27.830408 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
08:35:27.834528 trace git-lfs: tq: sending batch of size 1                                                                             
08:35:27.834621 trace git-lfs: tq: starting transfer adapter "lfs-standalone-file"
08:35:27.834642 trace git-lfs: xfer: adapter "lfs-standalone-file" Begin() with 1 workers
08:35:27.834659 trace git-lfs: xfer: starting up custom transfer process "lfs-standalone-file" for worker 0
08:35:27.834903 trace git-lfs: exec: sh '-c' 'git-lfs standalone-file'
08:35:27.835529 trace git-lfs: xfer: Custom adapter worker 0 sending message: {"event":"init","operation":"upload","remote":"origin","concurrent":false,"concurrenttransfers":8}
08:35:27.842791 trace git-lfs: xfer[git-lfs]: 08:35:27.842642 trace git-lfs: exec: git 'version'
08:35:27.846088 trace git-lfs: xfer[git-lfs]: 08:35:27.845975 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
08:35:27.848908 trace git-lfs: xfer[git-lfs]: 08:35:27.848823 trace git-lfs: exec: git 'config' '--includes' '-l'
08:35:27.852083 trace git-lfs: xfer[git-lfs]: 08:35:27.852004 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
08:35:27.854996 trace git-lfs: xfer[git-lfs]: 08:35:27.854913 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
08:35:27.858234 trace git-lfs: xfer[git-lfs]: 08:35:27.858151 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
08:35:27.861425 trace git-lfs: xfer[git-lfs]: 08:35:27.861342 trace git-lfs: exec: git 'rev-parse' '--git-dir'
08:35:27.864543 trace git-lfs: xfer[git-lfs]: error creating handler: failed to call `git rev-parse --git-dir`: exit status 128
08:35:27.865336 trace git-lfs: xfer: Aborting worker process: 0
EOFoading LFS objects: 100% (1/1), 3.7 MB | 0 B/s                                                                                      
error: failed to push some refs to '/home/git/dspkg'

**Comment by bk2204** [comment]
Hey,

It sounds like you're trying to push into a directory, but that directory isn't a Git repository.  You'll probably want to run `git init` in the destination directory first to make it a Git repository.

**Comment by kemin711** [comment]
That directory is a git repo, 
git remote -v
origin	/home/git/dspkg (fetch)
origin	/home/git/dspkg (push)
/home/git/dspkg$ ls -a
.  ..  branches  config  description  HEAD  hooks  info  lfs  objects  refs

**Comment by bk2204** [comment]
Hey,

The reason this is failing is because `git rev-parse --git-dir` is failing.  What does running `(cd /home/git/dspkg && git rev-parse --git-dir)` print?

**Comment by kemin711** [comment]
If logged in as git, then cd to /home/git/dspkg, the command is fine: 
`git rev-parse --git-dir
.
`
The output is '.'

**Comment by kemin711** [comment]
After executing the following command
`git config --global --add safe.directory /home/git/dspkg
`
Then push can be done successfully.  I am not sure this is the best solution.  Tanks for coaching me on the basics of git.

**Comment by mohammedALhakmy** [comment]
I have this is errors 
How can answer this problem?
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/mohammedALhakmy/website_news_v1.git'
