### ISSUE TITLE
LFS is not working: Cannot push large file with activated LFS and paid for extra storage

### ISSUE THREAD

**Issue by k8s-gpubuilder-markus** [git-lfs/git-lfs#5056]
I'm using LFS, installed it

bought 50 GB of extra storage and bandwidth on github (as this seems to be a requirement to use LFS at all)
git lfs install

told it to track the file (300 mb), 

git lfs track "*.log"

added .gitattributes
committed and then when I try to push I get this message:

36-22.log is 320.09 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.  

This is the third time I get this error and I'm obviously wasting a lot of transfer bandwidth every time.

I did everything by the instructions, yet it does not work. Is LFS broken? Does anybody have this working? Why is github requiring such a convoluted mess of a proceedure just to store such small files? Considering that we pay for the service, files over 100 mb should not be a problem.

**Comment by bk2204** [comment]
Hey,

As [mentioned in the FAQ](https://github.com/git-lfs/git-lfs/wiki/FAQ), if your file is already in the repository, then `git lfs track` isn't going to be sufficient here.  You'll need to use some variant of `git lfs migrate import` to rewrite the history.  The FAQ provides examples.

Also, just to assuage your fears, uploads to GitHub for Git LFS don't count against your bandwidth: it's only downloads that are charged.

**Comment by k8s-gpubuilder-markus** [comment]
Thanks for the clarification. One thing I don't understand though is: which repository do you mean? it is not github, it is not uploading it, as it is rejecting it, so it's not in the repository yet, right?

**Comment by k8s-gpubuilder-markus** [comment]
I used git lfs migrate import --everything --include="*.log", but now I can't push anymore, as it asks me to merge changes. Merge is not possible, because of "unrelated histories"

**Comment by bk2204** [comment]
`git lfs migrate import` rewrites the entire history of the project, so you'll need to force push (that is, use `git push -f`) to push your data, which should make things work as long as you don't have any protected branches.

**Comment by MyLegIsPotato** [comment]
> `git lfs migrate import` rewrites the entire history of the project, so you'll need to force push (that is, use `git push -f`) to push your data, which should make things work as long as you don't have any protected branches.

Thank you!!! Working fine!

**Comment by stephaneWeb** [comment]
you save my life

**Comment by rishabhkp28** [comment]
> `git lfs migrate import` rewrites the entire history of the project, so you'll need to force push (that is, use `git push -f`) to push your data, which should make things work as long as you don't have any protected branches.

bro i dont know how to thank you i have been trying uploading it since yesterday and it wasnt getting uploaded,
I dont know why this is working but it did

**Comment by hfuatkarahan** [comment]
> `git lfs migrate import` rewrites the entire history of the project, so you'll need to force push (that is, use `git push -f`) to push your data, which should make things work as long as you don't have any protected branches.

Hey, you don't realize what a big favor you've done! I can't thank you enough 🙏

**Comment by dxlorean** [comment]
> `git lfs migrate import` rewrites the entire history of the project, so you'll need to force push (that is, use `git push -f`) to push your data, which should make things work as long as you don't have any protected branches.

thanks so much man!

**Comment by dayeeen** [comment]
> `git lfs migrate import` rewrites the entire history of the project, so you'll need to force push (that is, use `git push -f`) to push your data, which should make things work as long as you don't have any protected branches.

I found it helpful, thank you.
