### ISSUE TITLE
Deleting remote object files

### ISSUE THREAD

**Issue by tcamin** [git-lfs/git-lfs#5058]
We've been successfully using Git LFS to store build caches to improve compilation times in one of our project. Everything works great except for disk utilization on our GitHub Enterprise LFS instance that is currently taking a considerable amount of space. Since the build caches can be regenerated any time we were thinking to completely delete the remote lfs objects, regenerate the required ones in all branches HEADS and `git lfs push --all`. Is this a viable approach? Are there any side effects we should be aware of? From the documentation I wasn't able to understand how Git LFS handles the missing remote object situation.

**Comment by bk2204** [comment]
Hey,

Git LFS will produce an error message if the file you want to download doesn't exist.  However, it will do that only if you check out a revision that needs a missing file.  If you don't check out a broken revision, then it won't complain.

As a general rule, build products of any sort don't belong in a repository, whether that's with plain Git or Git LFS, so my recommendation is to adopt a different approach altogether.  Git LFS also doesn't provide a way to delete objects, but it may be that your GitHub Enterprise instance does.

**Comment by tcamin** [comment]
Thanks for the quick reply. Just to double check: if we delete one or more lfs object files remotely (we can do this from the admin panel of GH Enterprise) can we push these files again from a dev machine using `git lfs push --all`? Will the command check with the remote which file exists and which not pushing the missing ones?

While I agree that build products shouldn't below in the repo the integration of Git LFS is so nice hiding lots of complexity behind a simple `git pull` so it would be nice to be able to prune the artifacts from time to time keeping lfs usage at acceptable levels.
