### ISSUE TITLE
How to downlaod single lfs file from a repository

### ISSUE THREAD

**Issue by r-xiumu** [git-lfs/git-lfs#5073]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

We don't provide an API to access just a single file.  However, [the API is documented](https://github.com/git-lfs/git-lfs/tree/main/docs/api) and you can write a suitable API request to download it.
