### ISSUE TITLE
Health check api for lfs server

### ISSUE THREAD

**Issue by SankarBhagawanPalla** [git-lfs/git-lfs#5083]
I’m writing to ask if you have any plans to implement a health check api for git Lfs 

**System environment*
I’m using git-lfs/3.2.0 

**Additional context**
Having a health check api helps a user to understand the state of the lfs server

**Comment by bk2204** [comment]
Hey,

We don't currently have a plan to implement such an API.  Individual implementations may choose to implement such an API if they'd like.

In general, those APIs are typically not exposed publicly, so it's unlikely we would document any standard approach as part of the official API.  That is, most implementations would expose such an API only internally, so the existence of that API or its contents would be appropriate for the particular deployment in question.
