### ISSUE TITLE
URL in label:mcve-required is outdated

### ISSUE THREAD

**Issue by n8felton** [git-lfs/git-lfs#5084]
While viewing issues, I noticed the current URL ([https://stackoverflow.com/help/mcv](https://stackoverflow.com/help/mcv)) for [label:mcve-required](https://github.com/git-lfs/git-lfs/labels?q=mcve-required) results in a 404. It appears to have been moved to https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by bk2204** [comment]
Thanks for the report.  I've removed the URL, since that URL is too long for the label field.
