### ISSUE TITLE
git pull do nothing

### ISSUE THREAD

**Issue by miditator** [git-lfs/git-lfs#5085]
Hello.
I'm new to using git lfs and I'm having a problem downloading files from a repository.
I followed the instructions and apparently everything works, but I can’t download the files.
Help please.
This is result of 
$ git lfs env

git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)
git version 2.37.1.windows.1

Endpoint=https://github.com/miditator/bp3restore.git/info/lfs (auth=basic)
LocalWorkingDir=E:\UE Project\Learn project\gitTemp\bp3restore
LocalGitDir=E:\UE Project\Learn project\gitTemp\bp3restore\.git
LocalGitStorageDir=E:\UE Project\Learn project\gitTemp\bp3restore\.git
LocalMediaDir=E:\UE Project\Learn project\gitTemp\bp3restore\.git\lfs\objects
LocalReferenceDirs=
TempDir=E:\UE Project\Learn project\gitTemp\bp3restore\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=E:\UE Project\Learn project\gitTemp\bp3restore\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

What do you mean when you say you can't download the files?  Is it that the files in the working tree aren't updated from pointers to LFS files?  Have you run `git lfs install` already?  What's the output from running `git lfs pull` (as a text block)?

**Comment by miditator** [comment]
git lfs works well
output from running git lfs pull - emty 
As far as I understand, the files are not downloaded separately, but are replaced .. only for some reason this is not visible in the file modification date in windows,
If you delete the lfs file and execute "git lfs pull" , then it appears again - so everything seems to be working ok
Thank you for answer

**Comment by bk2204** [comment]
Hey,

The files are supposed to be replaced when you run `git lfs pull`.  Can you run `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull` instead and include the output as a code block or an attachment?  Can you also provide the `.gitattributes` file for your repo as a code block?

**Comment by hannesa2** [comment]
> Can you run `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull`

Interesting ! I also see no output with `git lfs pull `, even when something was downloaded.
How to do this verbose by default ?

**Comment by bk2204** [comment]
Git LFS normally provides output to standard error to indicate progress.  However, in some cases on Windows, for whatever reason, the detection of the terminal doesn't work (I believe this is a Git for Windows problem) and no output occurs.  That's being tracked as #3704.

Since `git lfs pull` is working for most people and we haven't heard back from the original submitter, I'm going to close this.

**Comment by hannesa2** [comment]
I use macOS 12.6 with zsh. No Windows is involved there. Please accept it as an issue !

**Comment by bk2204** [comment]
Then please open a separate issue, filling out the issue template and providing the trace information requested.  This issue is about a Windows machine where no output is occurring, which is essentially a duplicate of #3704, and your situation is different and should be handled differently.
