### ISSUE TITLE
Receiving pre-push hook error in RStudio on M2 Mac (Apple silicon)

### ISSUE THREAD

**Issue by jamesrco** [git-lfs/git-lfs#5087]
I got a new Macbook Air M2 (Apple silicon) and I am trying to get some repositories working in RStudio. I installed R and RStudio, then installed git-lfs using homebrew. I then cloned one of my repos from Github. This repo has never given me any trouble, but then again I've been working on my old Mac MBP Retina with Intel silicon. 

I am now receiving the following error when using Git within RStudio in a git-lfs enabled repo:
 
`This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.`

Note that I can push and pull with no error (including all files being tracked with git-lfs) when using Git from the command line within the same repo. So it appears to be something having to do with RStudio and git-lfs on an Apple silicon Mac. Importantly, on the new M1/M2 Macs, git-lfs installs to `/opt/homebrew/bin/git-lfs` and not `/usr/local/bin/git-lfs` as previously on Intel silicon.

**To Reproduce**
1. Commit, then push any changes to a git-lfs enabled repo from RStudio (using the RStudio GUI's "Git" tab)2. 
2. Receive the error noted above. This prevents the changes on the latest commit from being pushed.

**System environment**
I am running Mac OS 12.5 on a brand-new MacBook Air M2. RStudio version: 2022.07.1 Build 554. Latest stable version of R, latest version of git-lfs (just installed this morning using brew). 

**Output of `git lfs env`**
```
git-lfs/3.2.0 (GitHub; darwin arm64; go 1.18.2)
git version 2.37.0 (Apple Git-136)

Endpoint=https://github.com/jamesrco/global-trawling-CO2.git/info/lfs (auth=none)
  SSH=git@github.com:jamesrco/global-trawling-CO2.git
LocalWorkingDir=/Users/jamesrco/Code/global-trawling-CO2
LocalGitDir=/Users/jamesrco/Code/global-trawling-CO2/.git
LocalGitStorageDir=/Users/jamesrco/Code/global-trawling-CO2/.git
LocalMediaDir=/Users/jamesrco/Code/global-trawling-CO2/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/jamesrco/Code/global-trawling-CO2/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/jamesrco/Code/global-trawling-CO2/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Again, importantly, I receive **no error** when committing and then pushing directly from the command line, in the same repo.

**Comment by bk2204** [comment]
Hey,

This is likely because the `PATH` value set by RStudio isn't correct.  I don't use that tool, so I'm not sure how you'd configure it, but you'd want to adjust RStudio to include `/opt/homebrew/bin` in the `PATH` that's used.

Alternately, you can change your `~/.gitconfig` to use an absolute path for the `filter.lfs.process`, `filter.lfs.smudge`, and `filter.lfs.clean` variables.

**Comment by jamesrco** [comment]
Thanks @bk2204 ... I opened an issue on the RStudio GitHub repo.
