### ISSUE TITLE
Remote "origin" does not support the LFS locking API. Consider disabling it with:

### ISSUE THREAD

**Issue by rajesh-kmp** [git-lfs/git-lfs#5089]
Hi All,

Could you please help me to fix this issue am facing on 
-- am not able to push the file to git hub server as getting this error below --
****$ git push origin main
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': 
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://github.com/********/info/lfs.locksverify false
Git credentials for https://github.com/I******.git not found.
error: failed to push some refs to 'https://github.com/******.git'****

**Comment by bk2204** [comment]
Hey,

Could you provide the output of `git lfs env` as requested in the issue template, as well as the output of `git config -l`, both as a code block?

**Comment by rajesh-kmp** [comment]
Hi @bk2204 ,
Please find the output for git lfs env and git config -l 
$ git lfs env
git-lfs/2.2.1 (GitHub; windows 386; go 1.8.3; git 621d1f82)
git version 2.14.1.windows.1

Endpoint=https://github.com/****/****.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\****\Github\test\****
LocalGitDir=C:\Users\****\Github\test\******\.git
LocalGitStorageDir=C:\Users\****\Github\test\l*****\.git
LocalMediaDir=C:\Users\******\Github\test\********\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\****\Github\***********\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Users\*****\AppData\Local\Programs\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

-- $ git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process
pack.packsizelimit=2g
credential.helper=manager
user.name=****
user.email=****
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/****/*****.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
lfs.repositoryformatversion=0
lfs.https://github.com/****t/****.git/info/lfs.access=basic

**Comment by bk2204** [comment]
Hey,

I think this message means that you're using a very old version of the Git Credential Manager for Windows.  For some reason, it needs to make an HTTPS request, and it's not capable of supporting TLS 1.2, which is the minimum version that GitHub supports.

You should be able to fix this by upgrading to the latest version of Git for Windows, which should fix this problem.

**Comment by rajesh-kmp** [comment]
Sure! will install the latest version and check 
Thanks @bk2204
