### ISSUE TITLE
Can't reset phantom file: `that should have been a pointer, but wasn't`

### ISSUE THREAD

**Issue by wyattPD** [git-lfs/git-lfs#5092]
**Describe the bug**
I run `git status` and this file shows up as modified, it's a giant binary blob and, as far as I know I haven't modified it. Regardless, I don't _want_ to modify it. So I `git reset --hard` to blow it away, expecting to arrive at a clean slate. Instead I see `Encountered 1 file that should have been a pointer, but wasn't`. No matter what I try I can't get rid of this modified file!

I tried `git checkout -f origin/develop` to get a _totally_ clean slate but that doesn't work either because I still get this `should have been a pointer, but wasn't` error message. How do I get rid of this thing?

This has happened once before and I came across #1939 and the uninstall/reset/reinstall routine described partway down worked before. But it didn't work this time.

**System environment**
- macOS Monterey on M1 16-inch 2021 Macbook Pro
- git version 2.32.1 (Apple Git-133)

**Output of `git lfs env`**
I had to obscure some stuff (name of the repo, my name, etc), shouldn't be relevant though:
```
git-lfs/3.2.0 (GitHub; darwin arm64; go 1.18.2)
git version 2.32.1 (Apple Git-133)

Endpoint=https://github.com/--/--.git/info/lfs (auth=none)
  SSH=git@github.com:--/--.git
LocalWorkingDir=/Users/--/Data/--
LocalGitDir=/Users/--/Data/--/.git
LocalGitStorageDir=/Users/--/Data/--/.git
LocalMediaDir=/Users/--/Data/--/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/--/Data/--/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/--/Data/--/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
I _really_ need a short-term fix here, I just want to get rid of this pending change so `git status` shows up clean.

Also: other people in my company use the exact same repo and do not appear to be having this issue. Most of them are not on M1 so it might be an M1 problem?

**Comment by bk2204** [comment]
Hey,

This is [outlined in the FAQ](https://github.com/git-lfs/git-lfs/wiki/FAQ).  The short answer is that this is due to a limitation in Git and there is no short-term fix; you really have to fix the files and commit.  If you don't, Git will continue to trigger the problem.

If you're using Git LFS 3.0 or newer, you may want to use `git lfs fsck --pointers` in your CI job to avoid this problem in the future.
