### ISSUE TITLE
Issue with the Home page of the Wiki

### ISSUE THREAD

**Issue by icom85** [git-lfs/git-lfs#5099]
It looks like there is an issue with the Wiki page, following this change: https://github.com/git-lfs/git-lfs/wiki/Home/32f8117647c1766194e088f5c32e76382afc01b1.

I accidently hit the revert button when comparing the above change with the previous one. It looks like the Installation and Tutorial pages are gone.

**Comment by bk2204** [comment]
Hey,

Thanks for letting us know.  I've used the Git command line to roll back to an earlier revision, and things should be back to normal.
