### ISSUE TITLE
Git LFS not working in folder containing {}

### ISSUE THREAD

**Issue by micko189** [git-lfs/git-lfs#5105]
When repository is cloned to a folder containing { } (e.g. c:\{folder}) git lfs commands does not work.
E.g.
C:\SnapVolumesTemp2\{folder}\TestRepo>git lfs track
Error: The system cannot find the path specified.
This operation must be run in a work tree.

The command git rev-parse --show-toplevel --absolute-git-dir returns following:
C:/SnapVolumesTemp2/{folder}/TestRepo
C:/SnapVolumesTemp2/{folder}/TestRepo/.git

This same repository works fine when cloned to a folder without {}

System environment:
git --version
git version 2.37.2.windows.2
git lfs --version
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)
OS:
Windows 10 Enterprise LTSC 1809

Output of git lfs env:

C:\SnapVolumesTemp2\{folder}\TestRepo>git lfs env
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)
git version 2.37.2.windows.2

Error: The system cannot find the path specified.
Endpoint=https://(I have deleted the endpoint for security reasons)/TestRepo.git/info/lfs (auth=none)
LocalWorkingDir=
LocalGitDir=C:\SnapVolumesTemp2\{folder}\TestRepo\.git
LocalGitStorageDir=C:\SnapVolumesTemp2\{folder}\TestRepo\.git
LocalMediaDir=C:\SnapVolumesTemp2\{folder}\TestRepo\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\SnapVolumesTemp2\{folder}\TestRepo\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\SnapVolumesTemp2\{folder}\TestRepo\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PA

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  My guess is that this is the same issue as #4829 and that addressing that will address this.  I'll tag it for the v3.3.0 milestone to see if we can get a fix in for both things.

I'll note that this doesn't reproduce for me on Linux, so I think it's likely that this is a Windows-only issue.

**Comment by micko189** [comment]
When is v3.3.0 expected to be released?

**Comment by bk2204** [comment]
Currently the plan is October, but it really depends on when we get the things we'd like to get done done.
