### ISSUE TITLE
Change the URL the Batch LFS API returns

### ISSUE THREAD

**Issue by preissC** [git-lfs/git-lfs#5116]
I have one instance of gitlab with LFS support enabled setup.
Infront of this instance is a nginx reverse-proxy. the direct http access to the gitlab via port `:80` is blocked with the reverse proxy. The idea is that you can only access LFS specific URLs via the port `:81` in my case.

My problem is that understandably the gitlab LFS Batch API still returns the URL without my port `:81`.

Can i configure the LFS Batch API in a way that it will return the URL with the correct port :81. How would I go about doing that, with `gitlab.rb`?

The issue only happen on `git clone` and `git pull`, `git push` works as expected.

This is the current response of the API
```
{
  "objects":[
    {
      "oid":"88293b9207c0a4a164a772630623e1defb2db238b70ed1807bb92e08332f53e3",
      "size":311515056,
      "actions":{
        "download":{
          "href":"http://my.gitlab.instance/gitlab-instance-7c2e323a/Monitoring.git/gitlab-lfs/objects/8829...",
          "header":{
            "Authorization":"Basic cm9vdDpleUpoYkdjaU9pSklVekkxTmlJc0lu..."
          }
        }
      }
    }
  ]
}
```

My goal is that the `"href"` value in `"download"` ends up being `http://my.gitlab.instance:81/gitlab-instance-7c2e323a/Monitoring.git/gitlab-lfs/objects/88293b9207c0a4a164a772630623e1defb2db238b70ed1807bb92e08332f53e3`.

Im happy to provide further logs, but hope this is enough for the start.

**Comment by chrisd8088** [comment]
Hey, sorry you're having trouble.

That's an interesting question, but unfortunately a bit off-topic for this project, which is just about the Git LFS client itself.  I would strongly suggest asking GitLab Support your question, and also maybe investigating what kinds of on-the-fly rewriting a proxy might be able to do.  But neither is going to be something we have experience with on this project, so I'm going to close this issue.  Good luck finding a solution!
