### ISSUE TITLE
Using google cloud storage as server

### ISSUE THREAD

**Issue by lappazos** [git-lfs/git-lfs#5118]
Hi,

How can i use GCS bucket as server for git lfs files?

**Comment by chrisd8088** [comment]
Hi, thanks for the question.  I think you'd need to have your Git hosting service, if you use one, support this, or if you're running your own Git LFS API service, you'd want to write it to send files to GCS.  See the Git LFS batch API [documentation](https://github.com/git-lfs/git-lfs/blob/52d47f085ba5ae534dd26ba76d010a537ddbdc8e/docs/api/batch.md) on how that works with the Git LFS client.

The client by itself, which is what this project is about, simply uploads and downloads to whatever URLs are provided by the Git LFS batch API for individual objects.  So you'd need your API service to work with GCS.  I hope that helps, and good luck!
