### ISSUE TITLE
should adding the entry "*.txt lockable" to .gitattributes not make the files matching the pattern readonly?

### ISSUE THREAD

**Issue by noop99** [git-lfs/git-lfs#5122]
I am trying to use the lfs file locking feature without actually enabling any large file features
I add the line:

*.txt lockable

to .gitattributes

however I see no changes to the filesystem permissions:

ls layout.txt -al
-rwxr-xr-x 1 user users 64676 Sep 22 08:39 file.txt

Have I missed a step?  What action triggers the permission change?

The wiki says:

> Once file patterns in .gitattributes are lockable, Git LFS will make them readonly on the local file system automatically. This prevents users from accidentally editing a file without locking it first.<

**Comment by bk2204** [comment]
Hey,

The permission change occurs when using `git lfs pull`, `git lfs checkout`, `git clone`, or `git checkout`.  Simply modifying `.gitattributes` (either directly or using `git track`) doesn't do that because Git LFS can't know when `.gitattributes` is intrinsically changed.

**Comment by noop99** [comment]
Once again thanks so much for your time.
