### ISSUE TITLE
[Question] Cleaning up the store ? 

### ISSUE THREAD

**Issue by StephaneKazmierczak** [git-lfs/git-lfs#5125]
Hello, 

How would you go on removing files from the remote lfs store ?
I am using a self host gitlab and I noticed after deleting the lfs tracked file from my test repo (local and remote) 
then the lfs store was still keeping the lfs files. 
Can I delete them by hand, if there any tools to check what they are, deleting then or getting back the original name ?

**Comment by bk2204** [comment]
Hey,

The Git LFS protocol doesn't provide a way to delete objects.  It's possible that GitLab may provide such a way, but I'm not sure what it is if it exists.  I can't say whether it's safe to delete them from the server, but my guess is that they have an entry in a database somewhere, so you'd want to find an approved way to delete them if possible.

Note that there's no special form for Git LFS objects, so you can simply look at them in `less` or run `file` on them if you want.
