### ISSUE TITLE
Git Clone is not resolving LFS files with specific lfs gitconfig order

### ISSUE THREAD

**Issue by ak-ldube** [git-lfs/git-lfs#5127]
**Describe the bug**
Git clone is not resolving the LFS files when the filter "lfs" gitconfig has a specific order.

**To Reproduce**
1. Go to your gitconfig file containing your lfs settings (for us it was in the user folder)
2. Open the gitconfig file
3. Change your [filter "lfs"] to the following:
```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge --skip -- %f
	process = git-lfs filter-process --skip
	required = true
```
5. Make a clone of a repository with LFS files. They should not resolve (IE, the file should contains the LFS information rather than the actual file)
6. Change your config back to
```
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
```
7. Perform another brand new clone and it should now resolve

**Expected behavior**
Regardless of the order in the filter "lfs" field, I would expect git lfs to behave normally

**System environment**
Windows using git for windows version 2.35 as well as 2.37

**Output of `git lfs env`**
See above gitconfig modifications

**Additional context**
I know this sounds crazy, but I did multiple attemps or before/after modification and it was 100% repro

**Comment by bk2204** [comment]
Hey,

Whether Git LFS is invoked by Git in a clone operation is a matter for Git to decide.  Therefore, if Git LFS isn't getting invoked, it's probably the case that Git doesn't think the config is correct.

Can you provide the output of `git config -l` for both situations, and, if possible, the actual config files as attachments to this issue?

**Comment by ak-ldube** [comment]
Hi, I ran the `git config -l` command, the output is the same regardless of the .gitconfig file and I also attached the gitconfig files I used

[broken_git_config_l.txt](https://github.com/git-lfs/git-lfs/files/9657618/broken_git_config_l.txt)

[working_git_config_l.txt](https://github.com/git-lfs/git-lfs/files/9657619/working_git_config_l.txt)

This gitconfig file provided me with broken git-lfs files
[broken_gitconfig.txt](https://github.com/git-lfs/git-lfs/files/9657646/broken_gitconfig.txt)

This gitconfig file provided me with resolved git-lfs files
[working_gitconfig.txt](https://github.com/git-lfs/git-lfs/files/9657641/working_gitconfig.txt)


Note: I think you are correct in thinking that git-lfs is just not called.
When it is not resolving, I don't see the "Filtering content" in the git log

**Comment by ak-ldube** [comment]
Hi, I ran the `git config -l` commands with a working config and a failing one, but they're the same. I also attached gitconfig files.

[broken_git_config_l.txt](https://github.com/git-lfs/git-lfs/files/9657693/broken_git_config_l.txt)
[broken_gitconfig.txt](https://github.com/git-lfs/git-lfs/files/9657694/broken_gitconfig.txt)
[working_git_config_l.txt](https://github.com/git-lfs/git-lfs/files/9657695/working_git_config_l.txt)
[working_gitconfig.txt](https://github.com/git-lfs/git-lfs/files/9657696/working_gitconfig.txt)


(I modified the name/email field)

**Comment by bk2204** [comment]
Hey,

This isn't an ordering issue.  The reason you're seeing this not work is because you're specifying the `--skip` parameter, which prevents Git LFS from checking out the files in the working tree.  This used to be useful on Windows because Git for Windows didn't support files larger than 2 or 4 GB, but it isn't very useful now.  If you want LFS files in the working tree, don't provide the `--skip` option in the config.

**Comment by ak-ldube** [comment]
Well, you see me flabbergasted that I missed that 🤦 

Thanks for helping a young goat see the light!
