### ISSUE TITLE
git lfs pull is silent on MacOS and zsh

### ISSUE THREAD

**Issue by hannesa2** [git-lfs/git-lfs#5154]
When I do `git lfs pull` I see no output, even when it downloads something. I've to do it sometimes, when I change branches.
I use zsh shell.
```
zsh --version               
zsh 5.9 (arm-apple-darwin21.3.0)
```

```
git lfs env
git-lfs/3.2.0 (GitHub; darwin arm64; go 1.18.2)
git version 2.37.1

Endpoint=https://gitlab.com/alexa-auto/group/labs.git/info/lfs (auth=none)
  SSH=git@gitlab.com:alexa-auto/group/labs.git
Endpoint (upstream)=https://github.com/alexa/alexa-auto-sdk.git/info/lfs (auth=none)
  SSH=git@github.com:alexa/alexa-auto-sdk.git
LocalWorkingDir=/Users/hannes/git/alexa-auto-sdk.gitlab
LocalGitDir=/Users/hannes/git/alexa-auto-sdk.gitlab/.git
LocalGitStorageDir=/Users/hannes/git/alexa-auto-sdk.gitlab/.git
LocalMediaDir=/Users/hannes/git/alexa-auto-sdk.gitlab/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/hannes/git/alexa-auto-sdk.gitlab/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/hannes/git/alexa-auto-sdk.gitlab/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/opt/homebrew/Cellar/git/2.37.1/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  Can you help me understand about how long the `git lfs pull` process runs typically when it's downloading?  In some cases, the meter may not always kick in right away, since there's typically some precomputation to find objects before the meter kicks in for downloads.

Also, do you see progress if you set `GIT_LFS_FORCE_PROGRESS` to `1` in the environment?  If so, that tells us that maybe the TTY detection is failing.

**Comment by hannesa2** [comment]
> Can you help me understand about how long the `git lfs pull` process runs typically when it's downloading?

Some seconds. (3-5 seconds)

Sorry, no output
<img width="789" alt="image" src="https://user-images.githubusercontent.com/3314607/198310040-2379ac44-a42b-4ab1-8ac7-fcd290ba0365.png">

**Comment by bk2204** [comment]
Can you run the operation with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and provide the output here (probably as an attachment), stripping out any `Authorization` headers?  That way we'd be able to see what's taking so long.

Also, can you provide the output of `git config -l` to help us see if there's anything that might be causing things to take an especially long time?

**Comment by hannesa2** [comment]
Here are the requested outputs, unfortunately there is no `Authorization` at all
 
[setting.log](https://github.com/git-lfs/git-lfs/files/9893079/seting.log)
[output.log](https://github.com/git-lfs/git-lfs/files/9893080/output.log)

**Comment by hannesa2** [comment]
Yes, it's huge.
Even when there is something to download, it prints out nothing. So I see not diff, if it does something, or not.
A normal `git pull` prints out `Already up to date.` when nothing was done and because there is no `--dry-run` or similar, it's not that straight forward to reproduce it.
I will try ....

**Comment by hannesa2** [comment]
Maybe you know, how to force git to require a `git lfs pull` ?
With a deletion of some files and do `git reset --hard` all is fine, even when I do a `git checkout <an other branch>` all is fine too. 
But sometimes, on an unknown reason, I've to do a `git lfs pull` to make my build work. I guess here a zip file is not downloaded. But how to force this ?

**Comment by bk2204** [comment]
Hey,

You can probably do `git lfs prune -f` and then `git checkout` a different branch with a change to one of the LFS files.  The former command will make sure that the cached LFS files are not present and then the checkout will make them be downloaded.

**Comment by hannesa2** [comment]
Ok, I followed your suggestion 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/3314607/199029890-996d09ff-87b5-4920-8b38-3cb1829a51d1.png">
[output2.log](https://github.com/git-lfs/git-lfs/files/9902146/output2.log)

I did it several times, and with your forced command, I see shortly an output ! That's new for me. 
When you don't look **always** on your screen, you don't see any output.

https://user-images.githubusercontent.com/3314607/199036554-213f3aaf-bef4-4c73-bec3-2765bf7f173f.mov
