### ISSUE TITLE
git lfs dedup not supported on windows 11?

### ISSUE THREAD

**Issue by s0updev** [git-lfs/git-lfs#5161]
I want to get rid of lfs duplicate, but I get  `This system does not support de-duplication.`

```
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)
git version 2.37.3.windows.1
```

Is there a workaround? My repo is 100+gb and I don't need to switch between branches, I'd probably even disable lfs caching, if I can

**Comment by bk2204** [comment]
Hey,

Whether `git lfs dedup` is supported is a matter of file system support.  The system must support copy-on-write behaviour for files, and NTFS doesn't do that.  Windows does offer an experimental file system called ReFS, which does, but it's not the default.

Similarly, many Linux systems use ext4, which does not support copy-on-write semantics, but there is a file system, btrfs, which does.  macOS is the only operating system I'm aware of where the default file system (APFS) supports this out of the box.

If you want to remove the files in the LFS store once they've been downloaded, you can run `git lfs prune -f` to do so, but there's no way to avoid downloading objects to the local file system.  In general, doing so is non-trivial and it hasn't been implemented yet.

**Comment by s0updev** [comment]
For anyone wondering apperantly ReFS works only on Enterprice and Workstation versions of Windows
