### ISSUE TITLE
How to remove Git Lfs from an existing local and remote repository

### ISSUE THREAD

**Issue by Stophface** [git-lfs/git-lfs#5176]
**Describe the issue**
I got a warning from `git lfs` that I exceeded my storage limit. Searching how to remove files from `git lfs` I came accross this site https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage which recommended using `$ git lfs uninstall`.

I run `$ git lfs uninstall` locally on my machine as well as `git lfs untrack`. I changed the `.gitattributes` file and commented everthing that has to do with  `git lfs`. I then `git add -A` and tried to push changes made to my code to my remote repo on GitHub. However, this gives me 

    batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
    Uploading LFS objects:   0% (0/2), 0 B | 0 B/s, done.
error: failed to push some refs to 'https://github.com/....git'

How would I remove `git lfs` from my repository, but not the files it tracked? I do not really need it anymore, so there is no need to track the files. However, I need to keep the files! Not being able to push to my remote repo unti I buy more storage is, well, a bit harsh I'd say...

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
```
git-lfs/3.2.0 (GitHub; darwin amd64; go 1.18.2)
git version 2.37.1 (Apple Git-137.1)

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Comment by bk2204** [comment]
Hey,

If you want to remove the usage of Git LFS from a repository, you need to use `git lfs migrate export` (probably with the `--everything` flag, but see the manual page for details).  That will turn the LFS objects into Git objects, and you'll no longer have a need to use Git LFS.

However, note that if you have files over 100 MB, GitHub will not let you push those unless they're LFS files.  I also believe that the batch API will fail until such time as you add data packs, so you'll need to wait for your usage to reset before the export will succeed unless you happen to have all of the LFS objects locally.  If all of the LFS objects are local, then that isn't necessary.

Note that the billing policy for GitHub (and GitHub itself) are off-topic for this repository, which covers the open source Git LFS client only.  Comments and issues about GitHub should be directed to GitHub's support page.
