### ISSUE TITLE
--exlude everything in a directory?

### ISSUE THREAD

**Issue by theoryshaw** [git-lfs/git-lfs#5186]
`git lfs migrate import --include="*.mp4" --exclude="C:/Path/To/Excluded_Directory"`

Would a command like this work?

That is, all .mp4's will be added, but any .mp4's in `Excluded_Directory` and any subdirectories within that, will not?

**Comment by chrisd8088** [comment]
That should almost work, but you would want to use a path for the `--exclude` option which is local to the repository, not from the root of your machine, and you would want to add the `/**` suffix to match everything inside that directory with infinite depth, so something like `--exclude=/in/repo/path/to/dir/**`.

See also the `gitattributes(5)` manual [page](https://git-scm.com/docs/gitattributes) and the `gitignore(5)` manual [page](https://git-scm.com/docs/gitignore) for details on path-matching options; `git lfs migrate` follows the `gitatttributes(5)` rules for its `--include` and `--exclude` options, so as it says in that manual page:

> patterns that match a directory do not recursively match paths inside that directory (so using the trailing-slash `path/` syntax is pointless in an attributes file; use `path/**` instead)

(Other `git lfs` commands' `--include` and `--exclude` options follow `gitginore(5)` path matching rules, but not `git lfs migrate`, as noted in the `git-lfs-migrate(1)` manual [page](https://github.com/git-lfs/git-lfs/blob/4e767fd9540426ecd31a297ac6ece539dbbff8a3/docs/man/git-lfs-migrate.adoc#include-and-exclude).)

As an example:
```
$ git init test
$ cd test
$ echo foo >foo.mp4
$ mkdir foo
$ echo bar >foo/bar.mp4
$ mkdir foo/bar
$ echo baz >foo/bar/baz.mp4
$ mkdir foo/bar/baz
$ echo sub >foo/bar/baz/sub.mp4
$ git add *
$ git commit -m init
$ git ls-files
foo.mp4
foo/bar.mp4
foo/bar/baz.mp4
foo/bar/baz/sub.mp4

$ git lfs migrate info --include "*.mp4" --exclude "/foo/bar/**"
migrate: Fetching remote refs: ..., done.                                       
migrate: Sorting commits: ..., done.                                            
migrate: Examining commits: 100% (1/1), done.                                   
*.mp4	8 B	2/2 files	100%

$ git lfs migrate import --include "*.mp4" --exclude "/foo/bar/**"
migrate: Fetching remote refs: ..., done.                                       
migrate: Sorting commits: ..., done.                                            
migrate: Rewriting commits: 100% (1/1), done.                                   
  master	b85988c938780b74a48a9709fb0ba6acfb0b946f -> c41f4ff74ab414b757ee122f74fcfe57025b82a3
migrate: Updating refs: ..., done.                                              
migrate: checkout: ..., done. 

$ git lfs ls-files
b5bb9d8014 - foo.mp4
7d865e959b - foo/bar.mp4

$ git show HEAD:foo.mp4
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4

$ git show HEAD:foo/bar.mp4
version https://git-lfs.github.com/spec/v1
oid sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730
size 4

$ git show HEAD:foo/bar/baz.mp4
baz

$ git show HEAD:foo/bar/baz/sub.mp4
sub
```

**Comment by theoryshaw** [comment]
Thank you kindly! very clear.
