### ISSUE TITLE
Bmo

### ISSUE THREAD

**Issue by Gabzygreen11** [git-lfs/git-lfs#5198]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by Gabzygreen11** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **System environment**
> The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.
> 
> **Output of `git lfs env`**
> The output of running `git lfs env` as a code block.
> 
> **Additional context**
> Any other relevant context about the problem here.
> 
> 
> 

- _![Screenshot_20221125-144153_Samsung Internet.jpg](https://user-images.githubusercontent.com/99345520/204065389-8e6a68de-bf81-43f7-9262-feaf8fa259e2.jpg)~~~~_

**Comment by chrisd8088** [comment]
Hey, this doesn't look like a useful contribution, so I'm going to close this.
