### ISSUE TITLE
Improvements to the 'getting started' documentation or FAQs around handling of SSL/HTTPS certificates

### ISSUE THREAD

**Issue by spiderscode** [git-lfs/git-lfs#5201]
I am new to git-lfs but it looks like an elegant solution to my use-case. As a test, I managed to use one machine to track some binary files and then push them to github.com. I then tried to clone the repo to a different machine. I am able to pull everything *but* the files managed by git-lfs due to a '*smudge error*' and '*x509: certificate signed by unknown authority*'.

It seems that others also hit this road block, assuming git-lfs will default to use whatever credential management method their regular git instance is using. I found some other issues/tickets, such as [this](https://github.com/git-lfs/git-lfs/issues/3709), that mention something about meddling with my git config, but the solution doesn't actually explicitly give examples of what to do.

Perhaps a single paragraph added to the 'getting started' wiki page, or the FAQ, which walks new users through configuring their git-lfs environment to just do whatever git is doing with their remote (e.g. github.com) would be worthwhile?

**Comment by bk2204** [comment]
Hey,

We can certainly specify some improvements in the FAQ.  We're about to do a v3.3.0 release, so those will come in after the fact.

Can you mention specifically what operating system and the versions of Git and Git LFS you're using (or provide the output of `git lfs env`)?  The reason I ask is that the advice we give you is going to be somewhat specific to your operating system.  For example, the invalid certificate authority issue is typically not expected when working with GitHub (and generally indicates a security problem between you and GitHub), but could indicate that some sort of proxy or non-default antivirus, firewall, or monitoring software is in use, often on Windows.  We'd want to document the appropriate behaviour here and provide examples of how to deal with this.
