### ISSUE TITLE
git-trace=1: not found

### ISSUE THREAD

**Issue by unarsiyaki** [git-lfs/git-lfs#5224]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This issue doesn't describe anything except an error message, and from just that, we can't solve any problems.  If you fill out the issue template as directed, we'll look into the problem if there is one.
