### ISSUE TITLE
Hooks don't work on windows

### ISSUE THREAD

**Issue by stefanlada** [git-lfs/git-lfs#5229]
We have to use a git repositoy that utilizes git-lfs on windows gitlab_runners. But now we ran into problems, with git-lfs, as it automatically installs git hooks. Now when I look into content of the generated git hooks

`command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
git lfs post-commit "$@"`

It might be obvious that especially `/dev/null` is not available on Windows. 

Side note: We call Git from a python script using GitPython.

Versions used:
 - Windows 11
 - Powershell 5.1.19041.1682
 - gitlab-runner 14.9.0
 - git version 2.34.1.windows.1
 - git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
 - GitPython 3.1.29

My prefered solution was, to somehow tell git-lfs to not install hooks at all.

Output of `git lfs env` (filtered):
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.34.1.windows.1

ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Can you run `git lfs install` from outside any repository?  That should avoid it trying to install any hooks; it only does that if it's run from inside a Git repository.

**Comment by bk2204** [comment]
Hey,

Git for Windows does indeed support `/dev/null` in its bash version, so this should work just fine on Windows as I've tested.

Since we haven't heard back with any more details on this, I'm going to close it, since it does appear to be working just fine in the general case.  If there's more details about what's going wrong here with detailed error messages, I think we can reopen and look into this further.
