### ISSUE TITLE
Git LFS 3.2.0 and 3.3.0 not installing on 32bit OS

### ISSUE THREAD

**Issue by metaad** [git-lfs/git-lfs#5231]
Git LFS 3.3.0 and 3.2.0 installer giving the below error on 32bit OS, while 3.1.4 installing fine.

![image](https://user-images.githubusercontent.com/106653425/208598500-60495e53-4912-41b8-89e7-a05f5ab10b89.png)

Please confirm that the latest version (3.2.0 and 3.3.0) for x64 OS only? OR is there any update to fix the issue?

Thanks and Regards,
Rama

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  This sounds like it might stem from the introduction of the use of the `commonpf64` variable into the Inno Setup installer script in commit a5b751f541abb52e30b60aebe530f9dbd72838df of PR #4925.

I'll mark this as a bug and we can see if we can get a fix into the next minor release, at least.

In the meantime, you might be able to use the 32-bit binary `git-lfs.exe` which is in the `Windows 386` Zip archive release asset on the [releases page](https://github.com/git-lfs/git-lfs/releases/tag/v3.3.0).

/cc @dscho as co-author of PR #4925

**Comment by dscho** [comment]
@metaad once the build has finished, could I ask you to test the installer in the `windows-latest` artifact of https://github.com/git-lfs/git-lfs/actions/runs/4024142745#artifacts? I do not have a 32-bit Windows to test...

**Comment by metaad** [comment]
[dscho](https://github.com/dscho)
Sorry for the late response from us,
Thanks for providing the latest build, 

However i have taken over this application again and revalidating the application. Hence i have downloaded and installed with your latest build (3.3.0) which you have provided in January. Now it is getting installed/upgrading without any issue. so now can i use this installer as stable Or you will officially release it? 

Regards,
A

**Comment by dscho** [comment]
> so now can i use this installer as stable Or you will officially release it?

I am a mere contributor to the Git LFS project. None of my builds are official.

**Comment by metaad** [comment]
Do you have any plans to fix this bug in next release?

**Comment by chrisd8088** [comment]
> Do you have any plans to fix this bug in next release?

Yes, it will be included in the next release, as #5266 has been merged into the main branch.
