### ISSUE TITLE
git rev-parse exit status 128

### ISSUE THREAD

**Issue by davekds** [git-lfs/git-lfs#5238]
I try to install the git lfs with 
 **$ git lfs install** 

but i get this error:

**Error: Failed to call git rev-parse --git-dir: exit status 128**

Version: 
git-lfs/2.9.2 (GitHub; linux arm64; go 1.13.5)

**Comment by davekds** [comment]
Thanks for the information :)

I installed git lfs from https://packagecloud.io/github/git-lfs/install.
I will try a new version and come back to you 


my git version: 2.25.1

**Comment by bk2204** [comment]
Hey,

It would also be helpful for you to tell us what `git rev-parse --git-dir` prints on your system as well.  That would let us figure out why this error is occurring.

**Comment by bk2204** [comment]
Hey, since we haven't heard back from you on this, I'm going to close this issue.  If you can provide the information requested, we can look into this more.
