### ISSUE TITLE
.rpm file not support

### ISSUE THREAD

**Issue by amidevous** [git-lfs/git-lfs#5244]
please solve rpm file not work

```
git lfs track "*.rpm"
"*.rpm" already supported
```

.deb file work and .rpm file not work please solve

**Comment by bk2204** [comment]
Hey,

This message means that your repository is already tracking `*.rpm` as a pattern and it doesn't need to track them a second time.  Can you show us the contents of any `.gitattributes` files in your repository to confirm that?

**Comment by bk2204** [comment]
Hey, since you haven't replied back, I'm going to close this issue.  We can reopen if you can provide the information requested.
