### ISSUE TITLE
File: /storage/emulated/0/Download/27440683-7b620cd8-5739-11e7-97e4-595b3c0106c8.png

Size: 377.9KB
Title: 27440683-7b620cd8-5739-11e7-97e4-595b3c0106c8
Width: 1024
Height: 684

### ISSUE THREAD

**Issue by Bladez1756** [git-lfs/git-lfs#5249]
Download BFast BFree From PlayStore and Earn Free BITCOINS. https://play.google.com/store/apps/details?id=com.bfast.bfree My Referal Code is: DEAT28

**Comment by chrisd8088** [comment]
This doesn't look like a useful issue, so I'm going to close it.  If you continue to open spurious issues and PRs, we'll have to block your account, which we would prefer not to do, so please stop creating unhelpful submissions.
