### ISSUE TITLE
git pull not failing on git-lfs conflicts when using wildcard in .gitattributes

### ISSUE THREAD

**Issue by yonylevy** [git-lfs/git-lfs#5268]
Way to reproduce:
1. mark entire directory as git-lfs, .gitattributes for example:
lsf/** filter=lfs diff=lfs merge=lfs -text

2. from local repo push lfs/file1 to remote

3. from local2 repo pull the remote, remove lfs/file1 and add lfs/file2, then commit and push to remote

4. from local repo, remove lfs/file1 and add lfs/file3, than run git pull --rebase

Expected - the pull should fail since step4 remove file1 that not exist in remote head.
Actual - The pull succeeded and file3 remain as untracked file in the repository.

Moreover, pushing to remote from local2 also succeeded.

Git show on head after step4:

diff --git a/lfs/file1 b/lfs/file1
deleted file mode 100644
index 1afab5f..0000000
--- a/file1
+++ /dev/null
@@ -1,3 +0,0 @@

I think this one is critical as an automated flows of git pull / git push will succeed in this case and break the repository

**Comment by bk2204** [comment]
Hey,

The decision for how a merge or rebase works (such as in a `git pull`) is completely up to Git unless you're using the custom merge driver extension (which in this case would not affect things).

In this case, your change is already upstream, and Git says this:

```
dropping 58478aeacf2a895f3410dc6cee9958d986fd577c Step 4 -- patch contents already upstream
```

In any event, this is a policy of Git and not Git LFS.  Git LFS can't affect this in any way, so if you don't like this behaviour, you should write to the Git mailing list (with a shell script that can reproduce the behaviour).  Note that you need to use a plain text email.
