### ISSUE TITLE
Brew install error: Failed to download resource "git-lfs_bottle_manifest"

### ISSUE THREAD

**Issue by aSemy** [git-lfs/git-lfs#5269]
**Describe the bug**

When I try and install git-lfs using homebrew, the installation fails

**To Reproduce**

```
$ brew update
Already up-to-date.
$ brew install git-lfs
==> Fetching git-lfs
==> Downloading https://ghcr.io/v2/homebrew/core/git-lfs/manifests/3.3.0
curl: (22) The requested URL returned error: 500                              
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
curl: (22) The requested URL returned error: 500                              
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
curl: (22) The requested URL returned error: 500                              
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
curl: (22) The requested URL returned error: 500                              

Error: git-lfs: Failed to download resource "git-lfs_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/git-lfs/manifests/3.3.0
```

**Expected behavior**

brew install git-lfs` installs git-fls

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This sounds like a problem with accessing the archive for Homebrew packages.  While they're a good way to install Git LFS, we don't manage those packages, and you'll need to talk to the Homebrew team about what's going on.
