### ISSUE TITLE
Where do those files go ?

### ISSUE THREAD

**Issue by deejinng** [git-lfs/git-lfs#5286]
Please I'll like to know where those files are stored because I'll like to access them, Thanks!

**Comment by deejinng** [comment]
> The Git LFS client stores files in `.git/lfs/objects/` as described in https://github.com/git-lfs/git-lfs/blob/v3.3.0/docs/spec.md#intercepting-git.
> 
> Where the server stores files is not specified in this repository and depends on the server software.

I just want to access those files and link to where I needed to.

Is that not possible as well ??

**Comment by bk2204** [comment]
Hey,

If your goal is to link directly to the LFS files on the server, then there's no direct way to do that.  Usually those files require some sort of authentication, which may be relatively short lived, so it's unlikely that the server will expose them publicly.

If you want to access them programmatically, then [there are API docs which you can use](https://github.com/git-lfs/git-lfs/tree/main/docs/api).  You'd start off by making a batch request, and then download the objects you'd like with the URLs provided.

**Comment by bk2204** [comment]
I think this has been answered, so I'm going to close this, but if things are still unclear, let us know and we can reopen.
