### ISSUE TITLE
git-lfs process hangs with high cpu load during git clone after unpacking objects - mac m1

### ISSUE THREAD

**Issue by yyahav** [git-lfs/git-lfs#5292]
**Describe the bug**
When trying to clone a repo from huggingface on mac m1, git-lfs hangs, showing high cpu load on activity monitor.

**To Reproduce**
Steps to reproduce the behavior - on mac m1:
1. run 'git lfs install'
2. run 'git clone https://huggingface.co/lllyasviel/ControlNet'
<img width="744" alt="image" src="https://user-images.githubusercontent.com/88027106/220998427-4c302911-90a1-431b-878f-683f3db99792.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/88027106/220998961-7a56cc67-60f8-4029-b454-16425f55deb9.png">

**Expected behavior**
The repo should have been cloned successfully (as many users report they have been succeeding in)

**System environment**
Mac M1 8GB - MacOS Ventura v13.2.1
git config
```
credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=xxxxx
user.email=xxxxx
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=https://huggingface.co/lllyasviel/ControlNet
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
lfs.repositoryformatversion=0
```

**Output of `git lfs env`**
```
git-lfs/3.3.0 (GitHub; darwin arm64; go 1.19.3; git 77deabdf)
git version 2.39.0

Endpoint=https://huggingface.co/lllyasviel/ControlNet.git/info/lfs (auth=none)
LocalWorkingDir=/Users/xxx/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ControlNet
LocalGitDir=/Users/xxx/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ControlNet/.git
LocalGitStorageDir=/Users/xxx/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ControlNet/.git
LocalMediaDir=/Users/xxx/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ControlNet/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/xxx/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ControlNet/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/xxx/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ControlNet/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/opt/homebrew/Cellar/git/2.39.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
I thought it might be related to an external volume issue but it happens on local storage too.
I tried adding "access = basic" to the lfs config but it didn't help.

**Comment by bk2204** [comment]
Hey,

I'm in the process of trying this out on my Linux box, and while the progress bar isn't showing for some reason, it does appear to be downloading data.  My guess is that this is just slow, since the repository is well over 40 GB in size.  When you do a `du -sh ControlNet` in another terminal periodically, does it appear to be increasing when you're attempting to clone?

**Comment by yyahav** [comment]
Hi,
I've let it run for about 15 minutes but the only thing I can see is that the folder structure is created but no files are actually downloaded, all folders are empty, not including even the md file.

Would git lfs download files much slower than a browser direct download? 
On a browser the large files (5GB) take up to 15 mins each, while downloading them simultaneously.

I'll let it run longer and have the `du` command run periodically as you suggested, and update. Thanks!

**Comment by yyahav** [comment]
Hi @bk2204,
You are correct.
After more than an hour the clone finished successfully.

Thank you! closing...
