### ISSUE TITLE
Help needed on how to use this to download a repo properly

### ISSUE THREAD

**Issue by darranis** [git-lfs/git-lfs#5297]
how do I download something using this as downloading this https://github.com/Oulu-UCC/3D_City_fbx or this https://github.com/Oulu-UCC/3D_citymodels as a zip and unpacking doesn't allow for use of the 3d model files and i'm not understanding how to use it as they stated

Any help would be appericated

System OS: Win 10

**Comment by chrisd8088** [comment]
Hey, sorry you're having trouble.  At least one of these repositories does use Git LFS for some of its assets, so you would want to follow the Windows installation [instructions](https://github.com/git-lfs/git-lfs#getting-started) for Git LFS and then clone the repository as usual (`git clone https://github.com/Oulu-UCC/3D_citymodels`).

Beyond that, I would suggest getting in touch with author of the repositories regarding how to use the contents of them.
