### ISSUE TITLE
What files are stored in .git/lfs?

### ISSUE THREAD

**Issue by htcml** [git-lfs/git-lfs#5298]
The model files in huggingface are very large and they all require run git clone lfs before actually git clone <repo>. I found .git/lfs has many large objects. Are those objects pertaining to old files/models? 

I removed the objects under .git/lfs and still can load the model from the local downloaded repo folder. So this makes me wonder if I just want to use current version of models, the objects under .git/lfs can safely be removed to save some disk space.

**Comment by chrisd8088** [comment]
This is similar question to the one in #5294, so I would refer you to the answers there.  I wouldn't recommend deleting anything in `.git/lfs` manually, but you can use the `git lfs prune` command to control what is cached and what is not; see also the [manual page](https://github.com/git-lfs/git-lfs/blob/91bac118ed88bc858612f4df69c35c342332b427/docs/man/git-lfs-prune.adoc) for the command for more details.

**Comment by htcml** [comment]
Can you explain why after removing the objects under .gif/lfs, models still can be loaded? I tried several huggingface models and this always works. Here are a few examples:
[https://huggingface.co/stabilityai/stable-diffusion-2-1-base/tree/main](https://huggingface.co/stabilityai/stable-diffusion-2-1-base/tree/main)
[https://huggingface.co/facebook/bart-large/tree/main](https://huggingface.co/facebook/bart-large/tree/main)

**Comment by chrisd8088** [comment]
I don't know anything about the models or how you're using them, so I can't comment on that.  But as noted in https://github.com/git-lfs/git-lfs/discussions/5294#discussioncomment-5120177, there's a difference between Git's working tree -- what ref you have checked out -- and the contents of your `.git` folder.  So if you have checked out a particular branch, the Git LFS client will usually populate your working tree with the relevant Git LFS objects.  But that's not *all* of what's in the Git repo, of course; there are other revisions, branches, etc., and the Git LFS objects for those will be cached in `.git/lfs/objects`.

I would recommend reading up on how Git and its index and working tree operate, and again, in general, removing `.git/lfs` will lead to unexpected and unhappy results.
