### ISSUE TITLE
Warning about Git LFS locking API is printed to stdout

### ISSUE THREAD

**Issue by graywolf-at-work** [git-lfs/git-lfs#5306]
**Describe the bug**

When running with origin that does not support locking API, following warning is printed:

```
Remote "origin" does not support the Git LFS locking API. Consider disabling it with:
  $ git config lfs.https://phabricator.showmax.cc/diffusion/PFC/pf-core.git/info/lfs.locksverify false
```

However, this is printed to stdout. That messes with shell scripting. The logical place to print this to would be stderr.

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I think this should be an easy change to make.
