### ISSUE TITLE
install git-lfs on linux, the git clone can't work again

### ISSUE THREAD

**Issue by tianlm** [git-lfs/git-lfs#5308]
I just installed git-lfs according https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md. 
After that, I run: git-lfs install and saw the export: "Git LFS initialized."
The I use "git clone" to clone svlsimulator git, the it was hung:
Below is the output:

git clone  https://github.com/lgsvl/simulator.git
Cloning into 'simulator'...
remote: Enumerating objects: 36497, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 36497 (delta 15), reused 0 (delta 0), pack-reused 36470
Receiving objects: 100% (36497/36497), 41.36 MiB | 3.35 MiB/s, done.
Resolving deltas: 100% (28363/28363), done.

There is no output again, and the content in the simulator folder is incorrect.
Does anyone know this issue?

Thx

**Comment by bk2204** [comment]
Hey,

Could you provide the information requested in the issue template, including the output of `git lfs env`?  Can you run the clone command as `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://github.com/lgsvl/simulator.git` and provide the output of standard error as an attachment (text file)?  That would let us figure out what's going wrong here.

Also, are you using any sort of proxy or TLS MITM device?  What distro are you using?  Is it installed on hardware, in a VM, or in WSL?  All of that would be helpful in figuring out what's going on.

**Comment by bk2204** [comment]
Hey, since we haven't heard back, I'm going to close this.  If you can provide the information requested, we can reopen it.
