### ISSUE TITLE
git lfs migrate info counts empty files as pointers

### ISSUE THREAD

**Issue by kohtala** [git-lfs/git-lfs#5321]
**Describe the bug**
Running `git lfs migrate info` on a repository reports "LFS Objects" entry with "0/n files", where n>0 and equal to number of zero length files. It seems to think zero length files are pointers.

**To Reproduce**
```sh
$ mkdir t
$ cd t
$ git init
Initialized empty Git repository in /home/kohtala/t/.git/
$ touch foo
$ git add .
$ git commit -m Initial
[main (root-commit) d9c243a] Initial
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo
$ git lfs migrate info
migrate: Fetching remote refs: ..., done.
migrate: Sorting commits: ..., done.
migrate: Examining commits: 100% (1/1), done.
LFS Objects     0 B     0/1 file        0%
$ touch bar
$ git add .
$ git commit -m Second
[main 070048b] Second
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 bar
$ git lfs migrate info
migrate: Fetching remote refs: ..., done.
migrate: Sorting commits: ..., done.
migrate: Examining commits: 100% (2/2), done.
LFS Objects     0 B     0/2 files       0%
$ git lfs version
git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.3)
```

**Expected behavior**
List no pointers.

**System environment**
Ubuntu 20.04.6 LTS and Windows 11. On Ubuntu I installed latest git-lfs deb from GitHub releases to test.

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.3)
git version 2.40.0

LocalWorkingDir=/home/kohtala/t
LocalGitDir=/home/kohtala/t/.git
LocalGitStorageDir=/home/kohtala/t/.git
LocalMediaDir=/home/kohtala/t/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/kohtala/t/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/kohtala/t/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

**Comment by bk2204** [comment]
Hey.

Zero-length files are in fact pointers.  The pointer for the empty file is itself, so this information is correct.

**Comment by kohtala** [comment]
There is ambiguity, because while empty file could be a pointer, it could also be an empty file that is not a pointer. These files were not pointers. They were empty files.

Since a checkout is correct without entries in .gitattributes for these blobs, I think it is not useful but harmful to resolve the ambiguity on the side of treating them as pointers for `git lfs migrate info`. Except if it found `.gitattributes` defining a filter for these files.

It gives a false alarm that the repository would have pointers while there is no `.gitattributes`. It is difficult to find those alarming files and see why it thinks they are pointers.

We also wanted to see if we would expect to have objects in the lfs storage (as we expected a pointer would point to something in the storage). The output was confusing because it listed pointers that do not have objects in storage.

Is there some useful reason to list them as pointers in the `git lfs migrate info`?

**Comment by kohtala** [comment]
`git lfs ls-files -a` does not list empty files.
