### ISSUE TITLE
Git LFS Documentation in git-for-windows

### ISSUE THREAD

**Issue by jasonnicholson** [git-lfs/git-lfs#5323]
**Describe the issue**
 In windows, `git lfs --help` is supposed to open an html file called git-lfs.html. I have opened a ticket with the git-for-windows/git team (linked below). I want to know how you intended the html files to be used that are included with git-lfs. 

https://github.com/git-for-windows/git/issues/4327

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

I use both git bash and cmd.

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.2604]
```

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.39.2.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

You can indeed ship the HTML files as documentation.  We don't put them in any particular location because, except for the installers, all of our data is designed to be relocatable and we don't in general have permissions to modify the Git for Windows installation.

However, note that if you call `git-lfs pull --help` (for example), we will not open the manual page, but we instead embed the text in the binaries.  However, I believe `git lfs pull --help` should indeed cause Git to open a manual page if you want.

**Comment by jasonnicholson** [comment]
From what I can tell, `git lfs --help` opens an HTML page on windows if the HTML page exists. However, `git lfs pull --help` outputs the embedded text to the console. If we wanted the HTML page for git-lfs-pull.html to open, do we need updates in git-for-windows or git-lfs?
