### ISSUE TITLE
"Skipping object checkout, Git LFS is not installed for this repository." even when lfs is indeed installed

### ISSUE THREAD

**Issue by NickHeiner** [git-lfs/git-lfs#5329]
**Describe the bug**
When I run `git lfs install; git lfs pull`, I get the following error message:

```
Skipping object checkout, Git LFS is not installed for this repository.
Consider installing it with 'git lfs install'.
```

However, I have already run `git lfs install` and confirmed that Git LFS is installed for the repository. (I see the updated contents in the git hooks.) I have also tried reinstalling Git LFS with the `--force` flag, but the issue persists.

For a brief moment, `git lfs pull` shows a progress indicator that appears to be ticking upwards. But then it's erased and replaced with the message above.

**To Reproduce**
1. Clone my repo (which unfortunately I can't share)
2. `brew install git-lfs`
3. `git lfs install`
4. `git lfs pull`

**Expected behavior**
The pull works

**System environment**
* macOS Ventura 13.2.1 (Apple M2)
* git 2.40.0

**Output of `git lfs env`**
```
git-lfs/3.3.0 (GitHub; darwin arm64; go 1.19.3)
git version 2.40.0

Endpoint=https://github.com/fixie-ai/fixie.git/info/lfs (auth=none)
  SSH=git@github.com:fixie-ai/fixie.git
LocalWorkingDir=/Users/nth/code/fixie
LocalGitDir=/Users/nth/code/fixie/.git
LocalGitStorageDir=/Users/nth/code/fixie/.git
LocalMediaDir=/Users/nth/code/fixie/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/nth/code/fixie/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/nth/code/fixie/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/opt/homebrew/Cellar/git/2.40.0/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""

```

**Additional context**

**Comment by bk2204** [comment]
Hey,

Sorry to hear this isn't working for you.  The problem here looks like this:

```
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

Can you share the output of `git config -l`, because I suspect that the configuration here will be enlightening and tell us why Git LFS thinks that these values are not set properly?

**Comment by NickHeiner** [comment]
Yep! 

```
credential.helper=osxkeychain
user.name=Nick Heiner
user.email=nick.heiner+github@gmail.com
push.default=simple
pull.ff=only
alias.timeline=log --graph --oneline --decorate
core.pager=diff-so-fancy | less --tabs=4 -RFX
core.editor=code --wait
core.ignorecase=false
core.excludesfile=~/.config/.gitignore_global
rerere.enabled=true
rerere.autoupdate=true
merge.conflictstyle=diff3
color.ui=true
diff-highlight.oldnormal=red bold
diff-highlight.oldhighlight=red bold 52
diff-highlight.newnormal=green bold
diff-highlight.newhighlight=green bold 22
diff.meta=yellow
diff.frag=magenta bold
diff.commit=yellow bold
diff.old=red bold
diff.new=green bold
diff.whitespace=red reverse
diff.tool=default-difftool
difftool.default-difftool.cmd=code --wait --diff $LOCAL $REMOTE
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=git@github.com:fixie-ai/fixie.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
lfs.repositoryformatversion=0
submodule.third_party/elementai/spider.active=true
submodule.third_party/elementai/spider.url=https://github.com/elementai/spider
submodule.third_party/elementai/test_suite_sql_eval.active=true
submodule.third_party/elementai/test_suite_sql_eval.url=https://github.com/elementai/test-suite-sql-eval
submodule.third_party/open-mmlab/mmdetection.active=true
submodule.third_party/open-mmlab/mmdetection.url=https://github.com/open-mmlab/mmdetection.git
branch.nth/onboarding-fixes.remote=origin
branch.nth/onboarding-fixes.merge=refs/heads/nth/onboarding-fixes
branch.nth/fe-format.remote=origin
branch.nth/fe-format.merge=refs/heads/nth/fe-format

```

Also, curiously, of the ~10 times I've run this command, it did work one time. Then it failed on subsequent attempts.

**Comment by bk2204** [comment]
Well, that definitely explains what's going on, since the `filter.lfs.*` keys are missing.  Could you try running `GIT_TRACE=1 git lfs install`?  That should produce output to standard error, which would be interesting to have here to look at.

My guess is that it will print something like the following, in which case, running the commands from the shell that include `--replace-all` would be helpful to figure out what's going on:

```
18:52:45.400629 trace git-lfs: exec: git 'version'
18:52:45.401842 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.clean'
18:52:45.402931 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.clean' 'git-lfs clean -- %f'
18:52:45.404551 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.smudge'
18:52:45.406022 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.smudge' 'git-lfs smudge -- %f'
18:52:45.407821 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.process'
18:52:45.409211 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.process' 'git-lfs filter-process'
18:52:45.416228 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.required'
18:52:45.418056 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.required' 'true'
```

Perhaps there's something that's causing Git to not write this in the expected location, and knowing what Git thinks the problem is would be very helpful to figure that out.

Just to help me track down any potential causes of this, do you have `XDG_CONFIG_HOME` set to anything in particular, and do you have more than one per-user gitconfig file (e.g., both `~/.gitconfig` and `~/.config/git/config`)?  Also, do you have any sort of configuration, permissions, or environment that you think might be potentially relevant here (say, any sort of includes directives, uncommon file systems, or anything just a little unusual)?  The sooner we figure out what's going on, the sooner we can get it fixed.

Note that to unblock yourself, you can also add something like this to your `.git/config`:

```
[filter "lfs"]
	clean = git-lfs clean -- %f
	process = git-lfs filter-process
	smudge = git-lfs smudge -- %f
```

That will provide the necessary entries for `git lfs pull` to continue and we can then troubleshoot the problem in a different copy of the repository to figure out what might be going on.

**Comment by NickHeiner** [comment]
Here we go:

```
GIT_TRACE=1 git lfs install
13:44:10.034206 git.c:725               trace: exec: git-lfs install
13:44:10.034772 run-command.c:655       trace: run_command: git-lfs install
13:44:10.041799 trace git-lfs: exec: git 'version'
13:44:10.046251 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.clean'
13:44:10.050584 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.clean' 'git-lfs clean -- %f'
13:44:10.055123 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.smudge'
13:44:10.058866 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.smudge' 'git-lfs smudge -- %f'
13:44:10.062751 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.process'
13:44:10.066451 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.process' 'git-lfs filter-process'
13:44:10.070515 trace git-lfs: exec: git 'config' '--includes' '--global' 'filter.lfs.required'
13:44:10.073863 trace git-lfs: exec: git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.required' 'true'
13:44:10.077456 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
13:44:10.080971 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
13:44:10.084320 trace git-lfs: exec: git 'config' '--includes' '--local' 'lfs.repositoryformatversion'
13:44:10.087393 trace git-lfs: exec: git 'config' '--includes' '-l'
13:44:10.090353 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
13:44:10.093446 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
13:44:10.096603 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
13:44:10.100335 trace git-lfs: Install hook: pre-push, force=false, path=/Users/nth/code/fixie/.git/hooks/pre-push, upgrading...
13:44:10.100547 trace git-lfs: Install hook: post-checkout, force=false, path=/Users/nth/code/fixie/.git/hooks/post-checkout, upgrading...
13:44:10.100699 trace git-lfs: Install hook: post-commit, force=false, path=/Users/nth/code/fixie/.git/hooks/post-commit, upgrading...
13:44:10.100779 trace git-lfs: Install hook: post-merge, force=false, path=/Users/nth/code/fixie/.git/hooks/post-merge, upgrading...
Updated Git hooks.
Git LFS initialized.
13:44:10.100820 trace git-lfs: filepathfilter: creating pattern ".git" of type gitignore
13:44:10.100829 trace git-lfs: filepathfilter: creating pattern "**/.git" of type gitignore
13:44:10.100871 trace git-lfs: filepathfilter: accepting "tmp"
```

Thanks for your fast response times on this!

**Comment by bk2204** [comment]
Okay, that's what I expected.  Does trying to run `git 'config' '--includes' '--global' '--replace-all' 'filter.lfs.process' 'git-lfs filter-process'` on your system produce any errors, or does it succeed?  If it succeeds, does it affect the output of `git config -l`?

**Comment by NickHeiner** [comment]
That command succeeds. It does not change the output of `git config -l`.

**Comment by bk2204** [comment]
Okay, then that would be the problem, since Git has succeeded and not done what we expected.  Can you include the output of `~/.gitconfig` and `~/.config/git/config` (if any) as an attachment (just drag and drop on the issue body) in case there's some sort of syntax error or weird byte problem?

**Comment by NickHeiner** [comment]
Here you go!

[.gitconfig](https://github.com/git-lfs/git-lfs/files/11173360/gitconfig.txt)

**Comment by bk2204** [comment]
I don't see anything here that should prevent this from working.  Are you storing your home directory within a folder used by a cloud syncing service or on a network drive, or do you have a tool (maybe an editor, a Git frontend, or [a dotfile tool](https://github.com/mathiasbynens/dotfiles)) that might be changing this file back under the hood?

As you might have imagined, if invoking Git isn't resulting in a change here, there's not much we can do, and that isn't really a bug in Git LFS.  I think it's likely that this is an environmental issue, since I feel like people would have noticed if `git config` weren't working, and I haven't seen such a mention on the Git list.

**Comment by NickHeiner** [comment]
That was it! My own dotfiles tool clobbers the existing `gitconfig` every time I open a shell. :smile: I guess I need something more sophisticated there.
