### ISSUE TITLE
Hosting a public file server which doubles as a Git LFS server?

### ISSUE THREAD

**Issue by QuantumToasted** [git-lfs/git-lfs#5331]
Hello. I have just currently started on a [project](https://github.com/OpenFastDL/OpenFastDL) on GitHub, with the goal of avoiding storing any large files on GitHub's servers, and instead using my [public file server host](http://openfast.download/) to hold its files, which happen to be mirrored identically to the repo's structure (as a simple file list displayed via nginx).

My intent, at least right now, is to have ONE physical file represent the file on the public file server, as well as the LFS file on the repo. GitHub's issues and PR system is extremely useful for a community-contributed public file server in my opinion, as a user can submit an issue or PR requesting or implementing custom content for a game which supports "FastDL", and then I (or another org manager) can vet, upload, and track the file in the repo so future contributions are made aware that "this content has already been added".

Is this something that can be accomplished at all?

I was, admittedly, doing some very not-to-git-LFS-spec stuff with a custom server implementation, where an LFS file's `oid` was actually representing its actual file location. (The one file on the file host at this moment, `http://openfast.download/tf/maps/koth_wubwubwub_remix_vip.bsp.bz2`, would have its `oid` as `tf/maps/koth_wubwubwub_remix_vip.bsp.bz2`). This would have allowed me to have the file host pull double duty, where LFS would ask for a file with an `oid` of "`tf/maps/koth_wubwubwub_remix_vip.bsp.bz2`", and the server would go "oh ok, here you go, it's located at "`http://openfast.download/tf/maps/koth_wubwubwub_remix_vip.bsp.bz2`".

I realized this is a dumb idea, so for the time being that has been scrapped because I'm sure there's some way I can create a mapping of `oid` to the actual file's location on the web host, but I am too unfamiliar with git-lfs (and git as a whole) to do so.
I think my confusions stem from not understanding how to map `oid` -> file location in a way that is usable by both my file server and git-lfs. So, to wrap this up with simple questions after all this preface nonsense:

**Is it possible to utilize a custom Git LFS server in such a way that it could double as a public file directory on a web host?** (And if so, how would one go about accomplishing this?)

Also, this might be a stupid question, but I see in the API spec that an upload batch request returns an `upload` action with the URL to...upload to? How does git-lfs attempt to actually upload the file when committing/pushing? Does it simply do as the API says, where it will try to POST to the URL with the specified headers and append the file data? That's something that was confusing to me when trying to spec up my own server/API implementation.

**Comment by bk2204** [comment]
Hey,

The Git LFS protocol is dynamic and queries for the places to upload and download, so currently it's not possible to use a completely static location as an LFS server.  This contrasts with Git, which can use any WebDAV server for access.  #4193 proposes to provide static access for files, but that has yet to be implemented.  However, with the status quo, you can refer to static files for downloads if you want, and with some work, for uploads with a custom LFS server.

The easiest way is to have a database for the LFS server that preserves the mapping.  However, you could also have a JSON file in a fixed location that your LFS server reads to perform the mapping from OID to URI.

When you perform the `upload` request, it's a PUT request with the specified file data and the given headers.  If you want inspiration, there's [a test server implementation you can look at](https://github.com/git-lfs/lfs-test-server).

**Comment by QuantumToasted** [comment]
Appreciate the quick and insightful response!

Taking a look at the linked issue, it does seem like a viable proposal that may partially or fully satisfy my use case. Depending on how things proceed from here and if I'm able to get something working with git-lfs in its current state, I may chime in to see if there's anything I could do to to help as far as proposals & specs.

> However, with the status quo, you can refer to static files for downloads if you want, and with some work, for uploads with a custom LFS server.

Downloads already make perfect sense to me with your suggestion of an oid → file location database. Request a download URL for oid `sha256:0d81701a691e734b8f080b2837cd949893c72463956ac7f21e524a45d85be35c`, size `11502`, and the server will know to point to `http://example.com/path/to/file.zip`. Uploading, however, is a mystery to me: If my understanding of the spec is right, an LFS server is wholly unaware of the filename or path of the file I'm requesting a URL for uploading. It works just like downloading: I tell the server "Hello, I'd like to upload a file with oid `sha256:da92dae0012f4bf105ead5d3e558d052976f8301cc32811173d74a9600a2a2fc`, size `50616`", the server will respond with...what? It has no knowledge of the file I'm trying to upload as it's not in the database yet. 

`git lfs ls-files --all` Actually will list a mapping of OIDs to file location like so:

```
$git lfs ls-files -all
9d1fb6974415217ed276c193e3879d43e653acd80bbb084f4af1b6bff0168b8f * tf/maps/koth_wubwubwub_remix_vip.bsp.bz2
```
I feel like I'm very close to the mental breakthrough I need to make the server aware of the filename, but...

As for the `upload` request, just so I don't ask more questions that could easily be answered by reading existing documentation or code in the future: Where exactly is this behavior defined? I assume it's directly in the git-lfs client? To my understanding, the API is simply meant to return the URL to upload to, and the headers you should supply with the request. I didn't see anywhere in the [spec](https://github.com/git-lfs/git-lfs/blob/main/docs/spec.md) that specifies this behavior, such as how the file is appended to the PUT request (`multipart/form-data` maybe?) when uploading to the `upload` action `href` URL.

**Comment by bk2204** [comment]
I think if you want to create a server like this, then you need to come up with some schema for new files.  Thus, your server would need to decide on a file name, synthesize a location, update the JSON location (probably with something like an ETag or WebDAV locking for atomicity), and then also send a verify endpoint to verify that the file had been uploaded correctly.  Note that the protocol doesn't provide a file name, since there can be duplicates of the same file, and acquiring that information would make pushing much more expensive.

When you're performing the `PUT`, you just pass the raw bytes without any sort of specific type.  [The API documentation](https://github.com/git-lfs/git-lfs/blob/main/docs/api/basic-transfers.md) outlines this.
