### ISSUE TITLE
Change git hook shebang from `!#/bin/sh` to `!#/usr/bin/env sh` for portability

### ISSUE THREAD

**Issue by p-rogalski** [git-lfs/git-lfs#5334]
**Describe the issue**
The shebang `!#/bin/sh` of Git-LFS's git hooks introduces trouble when using Git-LFS alongside the [pre-commit framework](https://pre-commit.com/) on Windows:

    An unexpected error has occurred: ExecutableNotFoundError: Executable `/bin/sh` not found

More information can be found in the issue pre-commit/pre-commit#1588.

The author of the framework proposes, that Git-LFS should use `!#/usr/bin/env sh` instead of `!#/bin/sh` for portability reasons.

**System environment**
- Windows 11 (22H2)

**Output of `git lfs env`**
```
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.40.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
- Wikipedia article about portability of shebangs: https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)#Portability

**Comment by bk2204** [comment]
Hey,

I don't think we're going to make this change.  `#!/bin/sh` is the standard way to write a Bourne-compatible shell on a wide variety of Unix systems (and, to my knowledge, _all_ known open-source Unix operating systems), and using this syntax works just fine with Git for Windows, which is the provider of that shell on most Windows systems, as well as (I believe) Cygwin and MINGW.  `/usr/bin/env` may be on a different file system and may not always be available, whereas `/bin/sh` typically is on the root partition and must be present.  `env` is also not always present in `/usr/bin`, either, so there is no one way to write a shebang that works everywhere, and at least someone will need to make changes.  That's just how it is.

In addition, making changes to hooks can cause incompatibilities between versions and break `git lfs install` or automatic hook installation if a user uses an older version of Git LFS, so we try to avoid making unnecessary changes to them.

You are, of course, free to edit the hooks as you see fit or change them.
