### ISSUE TITLE
question: exclude all refs except a few while executing git lfs migrate

### ISSUE THREAD

**Issue by harshit-mehtaa** [git-lfs/git-lfs#5347]
**Describe the issue**
We have a use case where we need to execute `git lfs migrate` where we have a total of **195732** ref's and of all these only 9 need to be included in the migration and all the rest needs to be excluded. 
Is there a way to handle this?

**System environment**
OS: Linux 4.15.0-135-generic # 139-Ubuntu x86_64 GNU/Linux

**Output of `git lfs env`**
```bash
git-lfs/3.1.4 (GitHub; linux amd64; go 1.17.8)
git version 2.30.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDirs=
TempDir=
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment]
Hey, thanks for the question.  I would suggest using the `--include-ref` option to `git lfs migrate import`, as [documented](https://github.com/git-lfs/git-lfs/blob/bea0287cdd3acbc0aa9cdf67ae09b6843d3ffcf0/docs/man/git-lfs-migrate.adoc#include-and-exclude-references) in the manual page.

You can test this with `git lfs migrate info --include-ref=<ref1> --include-ref=<ref2> ...` to see if that catches all the files you need converted to Git LFS objects, and then run the `git lfs migrate import` command with the same `--include-ref` options.

**Comment by harshit-mehtaa** [comment]
Does this mean that if I pass 10 refs in `--include-ref` then all the rest 195722 (out of 195732) will automatically be part of `--exclude-ref`?

**Comment by chrisd8088** [comment]
> Does this mean that if I pass 10 refs in `--include-ref` then all the rest 195722 (out of 195732) will automatically be part of `--exclude-ref`?

Yes, that should be the case.  More specifically, all commits reachable from all refs listed using `--include-ref` will be considered, where "reachable" means "can be found by traversing backwards from commit to parent commit(s)".  The refs you supply to each `--include-ref` are just single commits, of course, because they are whatever those refs point to; then the command will walk backwards from those commits to their parent commits, and so forth, until all reachable commits have been considered.

If you also supply `--exclude-ref` options, then any commits reachable from those will be ignored.  So the set of commits considered will be those reachable from all the `--include-ref` refs, minus all those reachable from the `--exclude-ref` refs.  If you don't supply any `--exclude-ref` options, then it's just all commits reachable from all the `--include-ref` refs.

 I would recommend experimenting with `git lfs migrate info` to make sure you understand what your command options will specify before running `git lfs migrate import`.

**Comment by harshit-mehtaa** [comment]
it will be nice to have a new feature where we can specify a command line parameter as **`--exclude-ref-other`** or **`--exclude-ref=all`** which can be used along with `--include-ref`. This is help solve the case where we want to include a specific list of refs but want to exclude all others, except the ones included. This will help to avoid passing all exclusion refs list manually by using `--exclude-ref`

WDYT?

**Comment by chrisd8088** [comment]
> it will be nice to have a new feature where we can specify a command line parameter as **`--exclude-ref-other`** or **`--exclude-ref=all`** which can be used along with `--include-ref`. This is help solve the case where we want to include a specific list of refs but want to exclude all others, except the ones included. This will help to avoid passing all exclusion refs list manually by using `--exclude-ref`

I'm not entirely sure how that would change the situation.  As I tried to explain, if you don't supply `--exclude-ref`, all that is considered are the refs you list with `--include-ref` options.  So by default, `--include-ref` means "only this ref"; you don't need to exclude other refs for that to work.

But what I was hoping to convey is that you may want to understand what it means to "include a ref".  It doesn't mean "include only the single commit pointed to by the ref".  It means "include all commits reachable from the ref".

I'm not sure what you're trying to achieve, but if, for instance, you wanted to include only a specific commit you could likely do so with `--include-ref=foo --exclude-ref=foo^`.

```
$ git init test
$ cd test
$ echo foo >foo.bin
$ git add foo.bin
$ git commit -m foo
$ echo bar >bar.bin
$ git add bar.bin
$ git commit -m bar
$ git lfs migrate import --include-ref=HEAD --exclude-ref=HEAD^ --include="*.bin"

$ git show HEAD^:foo.bin
foo

$ git show HEAD:foo.bin
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4
$ git show HEAD:bar.bin
version https://git-lfs.github.com/spec/v1
oid sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730
size 4
$ git show HEAD:.gitattributes
*.bin filter=lfs diff=lfs merge=lfs -text
```

That may not be what you are trying to do, though.
