### ISSUE TITLE
Upgrade golang version to 1.20

### ISSUE THREAD

**Issue by aman-harness** [git-lfs/git-lfs#5348]
**Describe the issue**
1.19.3 was released a while ago. Is there any plan to move to the latest golang version? if yes, can anyone please share the timeline for the same. 

**System environment**

**Output of `git lfs env`**

**Additional context**
The golang version being used in 1.19.3. We should move to the latest version.

**Comment by bk2204** [comment]
Hey,

We build Git LFS when we do a release, but not in between.  We'll likely do one around May or June, at which point, we'll update to the latest version of Go.  If you need a newer version in the meantime, you're welcome to build it yourself.

**Comment by bk2204** [comment]
This was fixed in #5392 and will be included in the next release.
