### ISSUE TITLE
Fetch LFS objects on demand

### ISSUE THREAD

**Issue by msedi** [git-lfs/git-lfs#5351]
Currently we have stored our source and reference datasets for unit tests on a network share. The problem is that for each team member I have to grant access and the network connection is not always the best. Additionally the source and reference data are not following version control and each team member needs to take care of it - which mostly no one really does or understand what to do.

Therefore we had the idea to put the data into our repo directly next to our unit tests or data tests folders. But the data is large several 100GB and not every unit test has to run on the client, it could also be performed during a pull request on the server. If I would use GIT-LFS in the current state all data would be downloaded to the client even if not needed.

Also when working remotely and your connection is not good you would get the data and have to wait for unneeded things

So the question is, if there is some support for "on-demand" or "on-access" fetch for large GIT-LFS data.
Maybe also configurable so that data up to lets say 2MB are always download but the rest isn't.

Or, is there a better way or how do other GIT-LFS users do it?

**System environment**
Currently we are running on Windows using Azure DevOps.

**Comment by msedi** [comment]
@KalleOlaviNiemitalo: Thanks for the info. I haven't heard of it so far and will take a look.

**Comment by pmartindev** [comment]
One option I can think of is to set your global git config to exclude all test files in a specific directory:
```
[lfs]
        fetchexclude = large-tests/*
```
You could separate your test data by size into different directories, then developers could pick and choose which file(s)/directories to pull.

`git lfs pull --include "large-tests/*`
or
`git lfs pull --include "large-tests/test.dat"`

**Comment by bk2204** [comment]
If you want to never download the LFS objects except on demand, you can use `git lfs install --skip-smudge` to leave the pointers in the tree and then run `git lfs pull` to download the objects on demand.

**Comment by msedi** [comment]
@bk2204: Thx. I think I still have to learn more about this. I need both some files are necessary for the "daily routine" and some are only for unit and data tests. Nevertheless I will keep an eye on your suggestion.

**Comment by bk2204** [comment]
I think this has been answered to the best of our abilities, so I'm going to close this.  If there are more questions, please open a new discussion and we can help further there.
