### ISSUE TITLE
Amazon Linux 2 x86_64 packagecloud.io repo has 0 packages available for install

### ISSUE THREAD

**Issue by shaunmansell** [git-lfs/git-lfs#5356]
**Describe the issue**
The Amazon Linux 2 yum package repository for `x86_64` is empty and contains no packages that can be installed which is preventing us boostrapping EC2 AMIs with git-lfs.

This repo was working previously on April 25th and appears to have broken between then and the 1st of May when we first saw install failures in our image build process.

We're using the script on https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh to init the repo on instances.

Is there something wrong with the repo?

## Additional Context
Repo definition on an EC2 instance hitting this issue
```
# cat /etc/yum.repos.d/github_git-lfs.repo
[github_git-lfs]
name=github_git-lfs
baseurl=https://packagecloud.io/github/git-lfs/amazon/2/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/github/git-lfs/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[github_git-lfs-source]
name=github_git-lfs-source
baseurl=https://packagecloud.io/github/git-lfs/amazon/2/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/github/git-lfs/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

yum repolist output showing 0 packages being available
```
# yum repolist github_git-lfs -v
...
Repo-id      : github_git-lfs/x86_64
Repo-name    : github_git-lfs
Repo-status  : enabled
Repo-updated : Mon Jan 21 23:42:12 2019
Repo-pkgs    : 0
Repo-size    : 0
Repo-baseurl : https://packagecloud.io/github/git-lfs/amazon/2/x86_64
Repo-expire  : 300 second(s) (last: Tue May  2 02:00:46 2023)
  Filter     : read-only:present
Repo-filename: /etc/yum.repos.d/github_git-lfs.repo

repolist: 0
```

OS release content
```
# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by shaunmansell** [comment]
Thanks @bk2204, I can confirm we were previously getting el7 packages on our AL2 builds, and initialising the repo with `os=el dist=7` has enabled us to continue installing the same packages as before.

**Comment by bk2204** [comment]
Fantastic.  Since we don't control the script used here and can't change it, I'm going to close this, since it sounds like the problem has been solved in the best way possible.

**Comment by tmokmss** [comment]
In Amazon Linux 2023, I successfully installed git-lfs by the following command:

```sh
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | os=fedora dist=36 bash
dnf install git-lfs
```

Not sure if `os=fedora dist=36` is the best choice though.

Alternatively you can install it from binary ([doc](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage)).
