### ISSUE TITLE
Getting issues while fetching objects from LFS server

### ISSUE THREAD

**Issue by Jamesj001** [git-lfs/git-lfs#5363]
Have configured LFS on a repo few months back things were working fine 
Few days back added `.lfsconfig` file in the same repo to add some customized configurations while doing git lfs pull
But its causing issues on CI giving : 
`error transferring "47b5d70538d6f5b8d1*******": [0] remote missing object 47b5d70538d6f5b8d1**********`
for multiple LFS files

So thought to revert my previous PR i.e.basically removal of `.lfsconfig` file but in doing so I have started to get errors like : 
```
batch request: Host key verification failed.: exit status 255
batch request: Host key verification failed.: exit status 255
Failed to fetch some objects from 'https://127.0.0.1/stash/****/my-repo.git/info/lfs'
```
Not sure what's the issue there

**Comment by Jamesj001** [comment]
@bk2204 would appreciate if any insight you could share on this ?

**Comment by bk2204** [comment]
Hey,

The first message here indicate that you're trying to download an object and it's not present on the server.  Usually that means that nobody has pushed it there, and if someone has that object, they can push with `git lfs push --all`.

The second message means that you're attempting to push over SSH and the host key isn't correct.  If you're using GitHub, then the host key has recently changed, and [you can use this StackOverflow answer](https://stackoverflow.com/questions/75836484/rsa-ssh-host-key-from-github-changed) to help solve the problem.

However, you haven't included the information in the issue template, including the output of `git lfs env`, and we'd need that, plus your `.lfsconfig` and the output of `git config -l` from within your repository to help out further.

**Comment by Jamesj001** [comment]
@bk2204 its only happening when I try to revert a commit which incudes removal of lfsconfig file repo not happening in other cases which is a bit weird to debug for its exceptional behviour to that revert
Sure would also share the info you asked for

**Comment by bk2204** [comment]
It's likely due to the fact that the `.lfsconfig` that you've reverted contains an `lfs.url` that changes where the requests go.  That's why it would be helpful to see the `.lfsconfig` both before and after.

**Comment by Jamesj001** [comment]
this is how `.lfsconfig` file looks
```
# To avoid automatic pulling of lfs files and just fetch corresponding pointers

[lfs]
    fetchexclude = *
```
We are just trying to either manually delete this file or  via revert command so basically whenever we are trying to change anything wrt current configuration it throws above error `batch request: Host key verification failed.: exit status 255` but if we try to add any config in lfsconfig file( rather than removing older config i.e fetchExclude or trying to delete itself `.lfsconfig` file ), it does not cause any failure

**Comment by Jamesj001** [comment]
Output of git lfs env:

**Comment by Jamesj001** [comment]
Output of git lfs env on CI:
Endpoint=https://<url>/info/lfs (auth=none)
SSH=<url>
LocalWorkingDir=/buildeng/bamboo-agent-home/xml-data/build-dir/***
LocalGitDir=/buildeng/bamboo-agent-home/xml-data/build-dir/***/.git
LocalGitStorageDir=/buildeng/bamboo-agent-home/xml-data/build-dir/***/.git
LocalMediaDir=/buildeng/bamboo-agent-home/xml-data/build-dir/***/.git/lfs/objects
LocalReferenceDirs=
TempDir=/buildeng/bamboo-agent-home/xml-data/build-dir/***/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/buildeng/bamboo-agent-home/xml-data/build-dir/***/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
FetchExclude=*
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = ""
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
So the reason this used to work without doing complaining about the host key was because you'd excluded all the objects, so Git LFS wasn't fetching anything.  Now, you're not, so you're seeing the attempt to connect over SSH, but that's failing because the host key isn't set.

Typically, that means that your SSH host key isn't trusted by the machine in question, so you should find the host key for the server you're connecting to and add it to `~/.ssh/known_hosts` in an initial step in CI.  For example, you could do something like the following:

```
echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts
```

You should of course substitute your server name and its host key rather than GitHub's.  If you're using GitHub, then you should add all of the keys at https://api.github.com/meta, not just the one I specified.  I don't recommend using `ssh-keyscan` for this purpose, because all that tells you is what the host key is now, not what it's supposed to be, and as a result, using that can allow a MITM attack.

**Comment by bk2204** [comment]
I think we've answered this, so I'm going to close this.
