### ISSUE TITLE
Git LFS work-flow documentation

### ISSUE THREAD

**Issue by TimePrinciple** [git-lfs/git-lfs#5369]
**Describe the issue**
I'm currently trying to implement a Git LFS http server-side using Rust. I wish I could be told where can I find the work-flow of this Git LFS client, I mean, the `Request URLs` will be sent so I can accordingly design the routers in my server-side.

**Comment by bk2204** [comment]
Hey,

We're happy to provide this documentation.  We have [an entire directory](https://github.com/git-lfs/git-lfs/tree/main/docs/api) full of API documentation.  Typically, once the server discovery is complete, one will make one or more batch requests to find where to upload or download objects and then perform the upload to or download from the locations specified in the batch request.  There's also a locking API, which is typically called before the batch API.

If you have more questions, please let us know, and we'll be happy to answer them.
