### ISSUE TITLE
How to delete previous commits using gitlfs.

### ISSUE THREAD

**Issue by rohithleor** [git-lfs/git-lfs#5371]
My Gitlab is over sized so i used gitlfs to push my old file to miniIO, after using we pushing our file using gitlfs, then how to remove previous commits. and how to check my repo storage size.

anyone could you help me please.

**Comment by chrisd8088** [comment]
Hey, thanks for the questions.  This project is for the open-source Git LFS client, so you may also want to ask GitLab's Support team for help, as they can provide information on how to reduce storage in their system.

As for the question of how to remove commits, there are good tutorials on Git elsewhere, but as a general suggestion I would expect that you want to use `git rebase` to rewrite your Git history and then `git push --force` to update it on the server.  You will need to connect with GitLab Support, though, to find out whether such changes are propagated to their object storage, particularly if you are using minIO.

**Comment by chrisd8088** [comment]
As we haven't heard anything more regarding this issue, and it appears not to be related to the Git LFS client itself, I'm going to close the issue.
