### ISSUE TITLE
Where in the source code Git LFS replace the file with pointer file?

### ISSUE THREAD

**Issue by TimePrinciple** [git-lfs/git-lfs#5377]
**Describe the issue**
I acknowledged that the `Git LFS` replaced the original file (Miniconda installation script) with a pointer file in my second commit. But when did this behavior takes place? Is the pointer file of original file was added during `git add`? Or during the `git lfs post-commit` hook? Can I be told where can I reference this replacing with pointer file in commit in the `git-lfs` source code?
![image](https://github.com/git-lfs/git-lfs/assets/52569592/118f2272-19bf-4e9d-8010-eadc9b2108b2)

**System environment**
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Output of `git lfs env`**
git-lfs/2.13.2 (GitHub; linux amd64; go 1.15.9)
git version 2.30.2

LocalWorkingDir=/home/ruoqinghe/Desktop/1
LocalGitDir=/home/ruoqinghe/Desktop/1/.git
LocalGitStorageDir=/home/ruoqinghe/Desktop/1/.git
LocalMediaDir=/home/ruoqinghe/Desktop/1/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/ruoqinghe/Desktop/1/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/ruoqinghe/Desktop/1/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

This operation is done in the clean filter.  When `git add` is invoked, Git cleans the large file into a pointer file by invoking Git LFS's clean filter (either as `git lfs clean`, or, on most modern versions, through `git lfs filter-process`).  When the file is checked out, Git smudges the file (which is the reverse) either using `git lfs smudge`, or, more commonly, `git lfs filter-process`.

So if you want to look at the code, you can start at https://github.com/git-lfs/git-lfs/blob/main/commands/command_clean.go and trace down.
