### ISSUE TITLE
git lfs fetch for all commits on a branch - useful for pushing to new repo

### ISSUE THREAD

**Issue by jasonnicholson** [git-lfs/git-lfs#5384]
**Describe the issue**
Currently, the only way to have all of the lfs objects available so I can push to a new repo is `git lfs fetch origin --all`. I want a command something like `git lfs fetch origin --branch-all myBranch` that gets all the lfs objects for all commits associated with a branch. This would allow me to push to a new repo without having to `git lfs fetch origin --all`.

**System environment**
Any

**Output of `git lfs env`**
Not important because this is a feature request.

**Additional context**
NA

**Comment by chrisd8088** [comment]
Hey, thanks for the question!  According to the manual [page](https://github.com/git-lfs/git-lfs/blob/2bdd529dbb2c0f38fbf327abd963fc673137a74f/docs/man/git-lfs-fetch.adoc) for `git-lfs-fetch(1)`, the `--all` option can be used with one or more refs, e.g., `git lfs fetch --all origin myBranch`.

The docs give this example:

> - Fetch all the LFS objects from the default remote that are referenced by any commit in the main and develop branches
>
> `git lfs fetch --all origin main develop`

Would that work for your use case?

The `--all` options means the Git history reachable from the given refs (or all refs, if none are provided) will be traversed and all Git LFS objects encountered will be fetched, as opposed to just the Git LFS objects in the specific commits identified by the given refs:
> Download all objects that are referenced by any commit reachable from the refs provided as arguments. If no refs are provided, then all refs are fetched.

**Comment by jasonnicholson** [comment]
Thank you for pointing out how the `-all` option worked with refs. I missed that. It's exactly what I needed.
