### ISSUE TITLE
Can I use the api alone without using the git lif client?

### ISSUE THREAD

**Issue by sjkim2322** [git-lfs/git-lfs#5405]
Is there any way to use the batch api alone without using git lfs ?

I am using the enterpirse version of github, but if I call the lfs batch api directly, I get a 404 error.

Can you tell me how to call the batch api to see if it works normally?

https://git-server.com/foo/bar.git/info/lfs/objects/batch

**Comment by bk2204** [comment]
We have [documentation for the batch API](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md).  There are also other files in that directory discussing other parts of the API.  In your case, it's likely that you're unauthenticated, and on a GitHub Enterprise Server instance, it's very likely that authentication is required for all access.
