### ISSUE TITLE
Certificate problem with self singned certificate and Git LFS on local Gitlab-Server

### ISSUE THREAD

**Issue by tmko13** [git-lfs/git-lfs#5406]
Im trying to set up a local gitlab server on a debian system. 
The debian is running as guest in a Virtual Box on Windows 10 host.

The last part i strugling with is to enable git lfs to work with self signed certificates. 

I have set up a self signed certificate on the server with the follwing commands:

```
//create a new file for the certificates
mkdir /etc/gitlab/ssl

//set permission for this directory
chmod 755 /etc/gitlab/ssl/

//enter ssl-dir and create certificates
cd /etc/gitlab/ssl
openssl req -x509 -newkey rsa:4096 -keyout Gitlab_Prototyp.key -out Gitlab_Prototyp.crt -days 10000 -sha256 -nodes


Contry Name: DE
Locality Name: SomeCity
Organization Name: SomeCompany
Common Name: 192.168.56.1
```

And change the gitlab.rb as follow to use the certificate:

```
external_url 'https://192.168.56.1'

//change and comment in 
nginx['enable'] = true
nginx['redirect_http_to_https'] = true                       
nginx['redirect_http_to_https_port'] = 80

nginx['ssl_certificate'] = "/etc/gitlab/ssl/Gitlab_Prototyp.crt"
nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/Gitlab_Prototyp.key"

nginx['ssl_ciphers'] = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256"

nginx['ssl_prefer_server_ciphers'] = "on" 
nginx['ssl_protocols'] = "TLSv1.2 TLSv1.3“
nginx['ssl_session_cache'] = "shared:SSL:10m"
nginx['ssl_session_timeout'] = "5m"
nginx['hsts_max_age'] = 31536000
nginx['hsts_include_subdomains'] = true
         
```
after that i have done a 

```
gitlab-ctl reconfigure
gitlab-ctl restart
```

after that i open up the gitlab website on the host system in the browser(in my case 192.168.56.1) and download the PEM-Certificate and safe it at 
C:\Program Files\Git\mingw64\ssl\192-168-56-1.pem

than i configure a git-repo to use the certificate as follow: 

```
git config --global http."https://192.168.56.1/".sslCAInfo "C:\Program Files\Git\mingw64\ssl\192-168-56-1.pem"
```

and do a initial push to the new project in gitlab with 

```
git push -uf --all origin
```

So far it work fine. Git is working with the self singned certificate.

But when i now add a file to git lfs and do git push -uf --all origin i get te following error: 

```
Remote "origin" does not support the Git LFS locking API. Consider disabling it with:
  $ git config lfs.https://192.168.56.1/gitlab-instance-0fc1769d/testgitproject.git/info/lfs.locksverify false


//I counter this error by executing
git config lfs.https://192.168.56.1/gitlab-instance-0fc1769d/testgitproject.git/info/lfs.locksverify false

```

Whit the next git push -uf --all origin try i get the following error

```
batch response: Post "https://192.168.56.1/gitlab-instance-0fc1769d/testgitproject.git/info/lfs/objects/batch": x509: certificate relies on legacy Common Name field, use SANs instead
```

I tried and look something around and come to the following sollution by creating a new certificate on the server as follow (as suggested e.g. [here](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28841):

```
cd /etc/gitlab/ssl

openssl req -x509 -newkey rsa:4096 -keyout NSI_Gitlab_Prototyp.key -out NSI_Gitlab_Prototyp.crt -days 10000 -sha256 -nodes -addext "subjectAltName = DNS:192.168.56.1"

gitlab-ctl reconfigure
gitlab-ctl restart

```
after that i open up the gitlab website again on the host system in the browser(in my case 192.168.56.1) and download the PEM-Certificate, safe it at 
C:\Program Files\Git\mingw64\ssl\192-168-56-1.pem and execute again

```
git config --global http."https://192.168.56.1/".sslCAInfo "C:\Program Files\Git\mingw64\ssl\192-168-56-1.pem"
```

When i now run git push -uf --all origin I get the following error: 

```
fatal: unable to access 'https://192.168.56.1/gitlab-instance-0fc1769d/testgitproject.git/': SSL: no alternative certificate subject name matches target host name '192.168.56.1'
```

How can I get Git LFS run on a local gitlab-server with active SSL?

PS: 
I know the sollution to deactivate SSL in Git (e.g. with git config http.sslVerify false) but thats not what I`m looking for. 
The server should finaly run in the whole local network, not only on the host-machine.

**Comment by bk2204** [comment]
Hey,

I believe your problem is that you're using `DNS:` with an IP address when it should be `IP:` or `IpAddr:` instead (which one I'm not sure).  The certificate you're issuing isn't valid for the IP address you've mentioned.

Here's [a blog post](https://medium.com/@antelle/how-to-generate-a-self-signed-ssl-certificate-for-an-ip-address-f0dd8dddf754) about how you can go about this with a configuration file, which might be the right thing to do here.

**Comment by tmko13** [comment]
Thankyou for the answer - it works for me 

before creating the certificte i create the file san.cnf in the ...gitlab/ssl file with the following content:

`[req]
default_bits  = 2048
distinguished_name = req_distinguished_name
req_extensions = req_ext
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
countryName = XX
stateOrProvinceName = N/A
localityName = N/A
organizationName = Self-signed certificate
commonName = 192.168.56.1: Self-signed certificate

[req_ext]
subjectAltName = [@alt_names](http://twitter.com/alt_names)

[v3_req]
subjectAltName = [@alt_names](http://twitter.com/alt_names)

[alt_names]
IP.1 = 192.168.56.1`

Then i execute the creation of the SSL certificate as followed: 

`openssl req -x509 -newkey rsa:4096 -keyout Gitlab_Prototyp.key -out Gitlab_Prototyp.crt -days 10000 -sha256 -nodes --config san.cnf`

This clear all problems. After downloading the certificate in the Browser an adding it to Git with 

`git config --global http."https://192.168.56.1/".sslCAInfo "C:\Program Files\Git\mingw64\ssl\192-168-56-1.pem"`

I also haven't the other problems any more and can use Gitlab with git LFS
