### ISSUE TITLE
git lfs track --filename "/[2023-06-23]/1.tset" "/[2023-06-23]/2.aaaa" fail to execute in win 10

### ISSUE THREAD

**Issue by zhoushaokun** [git-lfs/git-lfs#5409]
**Describe the bug**

As git lfs track doc said，we can use `--filename` to set path with special character such as `[ ] * ?`. But when I do this in my win 10 computer, it went wrong.

**To Reproduce**
1. In win 10, New two files named: "/[2023-06-23]/1.tset" "/[2023-06-23]/2.aaaa" in dir `[2023-06-23]` in any installed git lfs repo's root folder.
2. Open git bash command execute `git lfs track --filename "/[2023-06-23]/1.tset" "/[2023-06-23]/2.aaaa"`
3. See error
![image](https://github.com/git-lfs/git-lfs/assets/32841670/65a005e8-13fc-4a9e-8955-7ebc66b2c53f)

And the `.gitattributes` file will add one line config which is wired, because it has already ended with error. Why should have some effect on really disk file?

**Expected behavior**

using `--filename` for paths with special character  and worked as [doc](https://github.com/git-lfs/git-lfs/blob/300f4ed3e5f9f4f0d42d326d95e7ca418ce61891/docs/man/git-lfs-track.adoc#L4) said 

**System environment**

git-lfs/3.3.0 (GitHub; windows amd64; go 1.19; git e815aff5)
git version 2.36.1.windows.1

![image](https://github.com/git-lfs/git-lfs/assets/32841670/b4f822c4-c3fb-4e97-94e2-c0a6ee24e542)

**Additional context**

Alse, I tried execute `GIT_TRACE=1 git lfs track --filename "/[2023-06-23]/1.tset" "/[2023-06-23]/2.aaaa"`, the execution details follwoing:

![image](https://github.com/git-lfs/git-lfs/assets/32841670/bd8c9efc-f939-46be-8072-b9fea419d845)

From the details, I guess it may related to the `git 'ls-files' '--cached' '--' '\[2023-06-23\]/1.tset'`，because when i execute the comand longly in my git bash it show that:
![image](https://github.com/git-lfs/git-lfs/assets/32841670/f3d46255-38cb-4328-ac11-fd9cc44dbfb6)

**Comment by chrisd8088** [comment]
Hey, thanks for the report, and I'm sorry you're having trouble.  I've tried to reproduce this locally without success, but that's because I believe it's a Windows-specific issue.  Unfortunately my Windows dev environment is not working right now, but once I get it going again, I'll take a look at this.

Thanks for your patience, and for reporting the problem!

**Comment by zhoushaokun** [comment]
@chrisd8088  Sorry to not put all information. I have also tried in my mac machine, it works quite well.
Thanks for your reply.

**Comment by bk2204** [comment]
I can reproduce this on my test Windows VM and I think I have a fix.  I'll link a PR shortly.
