### ISSUE TITLE
LFS Pointers line ending

### ISSUE THREAD

**Issue by nick-kanakis** [git-lfs/git-lfs#5410]
**Describe the issue**

We have a system that mirrors changes from a GitHub instance to a Gitlab instance, and recently we had an issue that certain LFS files failed to be pushed to our GitLab instance. After some investigation, we came to the conclusion that this is related to how Gitlab and Github handle LFS pointers differently.

In our case, we had one LFS file pointed by multiple pointers, but not all pointers had the same line ending. That caused having 2 different objects that were basically the same LFS pointer just with different line endings. This is in contrast to the specs that state:
> Pointer files are unique: that is, there is exactly one valid encoding for a pointer file.

It seems that GitHub is ok with violating the rule while [gitlab is not](https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/checks/lfs_integrity.rb#L27). It would be great if the specifications were clear on the correct formatting of pointers.

According to an answer in another [open issue](https://github.com/git-lfs/git-lfs/issues/4881#issuecomment-1041581286):
> pointer files must have LF endings and must not be subject to line-ending conversion

But there is no reference that LF ending is required in the [specs doc](https://github.com/git-lfs/git-lfs/blob/main/docs/spec.md).

**System environment**

**Output of `git lfs env`**

**Additional context**

**Comment by nicolasmanic** [comment]
> I'm curious about what software generated the Git LFS pointer blobs with incorrect line endings.

I have reached out to the dev that added the rogue pointer. I will let you know.

Here are the problematic pointers.
pointer A: `4855fdbd638a0856f80b5d9ddc48b1dbe6ea791d`
```
0000000    v   e   r   s   i   o   n       h   t   t   p   s   :   /   /
0000020    g   i   t   -   l   f   s   .   g   i   t   h   u   b   .   c
0000040    o   m   /   s   p   e   c   /   v   1  \n   o   i   d       s
0000060    h   a   2   5   6   :   b   6   6   f   6   6   e   8   a   d
0000100    4   8   8   4   c   5   a   1   3   b   e   1   8   3   2   d
0000120    5   f   3   1   6   4   9   8   8   b   6   f   6   f   a   1
0000140    5   7   5   0   8   1   4   6   7   b   b   f   c   f   1   6
0000160    1   5   d   0   d   6  \n   s   i   z   e       2   3   0   4
0000200    0   0   9   7   1  \n  \n
0000207
```
pointer B: `735d786010836e926e52e8af546dd168bcb25f1c`
```
0000000    v   e   r   s   i   o   n       h   t   t   p   s   :   /   /
0000020    g   i   t   -   l   f   s   .   g   i   t   h   u   b   .   c
0000040    o   m   /   s   p   e   c   /   v   1  \n   o   i   d       s
0000060    h   a   2   5   6   :   b   6   6   f   6   6   e   8   a   d
0000100    4   8   8   4   c   5   a   1   3   b   e   1   8   3   2   d
0000120    5   f   3   1   6   4   9   8   8   b   6   f   6   f   a   1
0000140    5   7   5   0   8   1   4   6   7   b   b   f   c   f   1   6
0000160    1   5   d   0   d   6  \n   s   i   z   e       2   3   0   4
0000200    0   0   9   7   1
0000205
```

You see both point to the same LFS file: `b66f66e8ad4884c5a13be1832d5f3164988b6f6fa1575081467bbfcf1615d0d6` but they don't follow the same line ending one has `\n  \n` while the other nothing.

Both pointers were accepted by Github but Gitlab rejected them. But reading the specs again it seems you are correct from what I understand both those pointers should have been rejected by github.

**Comment by bk2204** [comment]
`git lfs fsck` does indeed detect the error when used with `--pointers`, and it's accurate that these are malformed.  `git lfs pointer --check --strict` will also reject these.

I agree that the spec is pretty clear about this, but if you don't agree, we'd be happy to accept suggestions on what to change in the docs.

**Comment by nick-kanakis** [comment]
> Does `git lfs fsck` detect the error?

Yes it does.

> I agree that the spec is pretty clear about this, but if you don't agree, we'd be happy to accept suggestions on what to change in the docs.

No, it's clear I will reach out to GitHub to understand more on how those malformed got accepted. 

I will close the issue but will make an update to @KalleOlaviNiemitalo about how those pointers where introduced in the first place thanks for the explanation everyone

**Comment by nick-kanakis** [comment]
So according to the dev that introduced those pointers, there was nothing out of the ordinary on his setup. He is using Windows with the latest git-LFS installed, the process to add those objects was just by using `git add ...`. Not sure where to go from here :/

**Comment by bk2204** [comment]
The code to encode pointers hasn't changed really since 2016, and it always uses a single LF ending.  It's possible that a conflict occurred and that somebody ended up resolving it by hand, in which case the pointer might have ended up with incorrect line endings.  Could that have occurred in your case?

**Comment by nick-kanakis** [comment]
Sorry for the late response I was away. Not according to the dev, in the mean time we added some github action checks to catch those cases.
