### ISSUE TITLE
command "git lfs fetch" uses incorrect URL to download objects when behind proxy

### ISSUE THREAD

**Issue by gh-user-2022** [git-lfs/git-lfs#5411]
**Describe the bug**
GIT LFS does not work through HTTP proxy.
Not sure whether this is bug on side of GIT LFS or Gitea.
I try to use the GIT 2.41.0 and GIT LFS 3.3.0 to work with a repository hosted in Gitea v1.19.3.
It works correctly (both GIT and GIT LFS) without proxy.

However, when I use proxy
`    http://proxy:20000/`
forwading to
`    https://gitea-server:443/`
which can be configured e.g. in nginx like
```
    server {
        listen 20000;
        location / {
            proxy_pass	https://gitea-server:443/;
        }
    }
```

The GIT itself works correctly (Clone/Fetch/Pull/Push works OK) with such proxy.
But GIT LFS does not work correctly:
The command "git lfs fetch" fails.

If we debug it with "GIT_CURL_VERBOSE=1 git lfs fetch", we can see that it first makes request

`    POST http://proxy:20000/ORG_NAME/REPO_NAME.git/info/lfs/objects/batch`

respose of which contains entries like

`    ... "download":{"href":"https://gitea-server:443/ORG_NAME/REPO_NAME.git/info/lfs/objects/...", ...} ...`

And then it makes requests like

`    GET https://gitea-server:443/ORG_NAME/REPO_NAME.git/info/lfs/objects/...`

using the original server's URL.

**To Reproduce**
Steps described in the "Describe the bug" section above.

**Expected behavior**
It should work behind such HTTP proxy.
That is, when GIT LFS fetches the objects, it should use the same root URL as when it makes request to ".../info/lfs/objects/batch".
The possible fix is to have relative URLs like
`    ... "download":{"href":"/ORG_NAME/REPO_NAME.git/info/lfs/objects/", ...} ...`
If this is already supported, then the bug is probably at side of Gitea.

**System environment**
Gitea server is run on official docker container.
GIT LFS client is run on Windows 10.

**Output of `git lfs env`**
```
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.41.0.windows.1

Endpoint=http://proxy:20000/ORG_NAME/REPO_NAME.git/info/lfs (auth=basic)
LocalWorkingDir=C:\_test_repo
LocalGitDir=C:\_test_repo\.git
LocalGitStorageDir=C:\_test_repo\.git
LocalMediaDir=C:\_test_repo\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\_test_repo\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\_test_repo\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
I redacted the real URLs here, because the names are private and are not relevant.

**Comment by bk2204** [comment]
Hey,

If you're using a reverse proxy, you need to configure your Gitea server to produce the correct URLs.  There should be a configuration option to do so, and if not, you should reach out to Gitea and ask for one to be added.

Git LFS can't always use the same root URL because the files are not always uploaded to or downloaded from the same server as the LFS server.  For example, with GitHub, the files are uploaded to a different server.

You can also rewrite these URLs with `http.*.insteadOf` as outlined in the Git configuration provided you also set the option `lfs.transfer.enablehrefrewrite` to true.  That's the option that Git LFS provides for you to rewrite these URLs if you can't control the server.

**Comment by gh-user-2022** [comment]
Thanks for info about `lfs.transfer.enablehrefrewrite`.

The following did work in my case:

```
git config lfs.transfer.enablehrefrewrite true
git config url.http://proxy:20000/.insteadOf https://gitea-server:443/
```
