### ISSUE TITLE
pptx not uploaded via browser anymore

### ISSUE THREAD

**Issue by CHRitsch** [git-lfs/git-lfs#5416]
Can not upload .ppts file via browser

Previously I could upload a large file (pptx) and so update it easyly into a specific repo.
Now I wanted to do it again, but I get this message now.

> The following files are configured to be stored in Git LFS and must be pushed using the Git command line with Git LFS installed: 01_Supporting_Process/05_Presentation/UseCases/test.pptx  ``

**Expected behavior**
I would like to add the file onto the repo within the browser as usual.

**System environment**
uidg9834@UULBDG7W MINGW64 /d/Git_LOCAL/SaFu/01_Supporting_Process/05_Presentation/UseCases (master)
$ git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor=nano.exe
pull.rebase=false
init.defaultbranch=master
merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
diff.guitool=beyondcompare4
difftool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
user.name=CRitscher
user.email=christina.ritscher@continental-corporation.com
difftool.beyondcompare4.path=C:/Program Files/Beyond Compare 4/bcomp.exe
difftool.beyondcompare4.cmd="C:/Program Files/Beyond Compare 4/bcomp.exe" "$LOCAL" "$REMOTE"
:...skipping...
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor=nano.exe
pull.rebase=false
init.defaultbranch=master
merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
diff.guitool=beyondcompare4
difftool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
difftool.beyondcompare4.path=C:/Program Files/Beyond Compare 4/bcomp.exe
difftool.beyondcompare4.cmd="C:/Program Files/Beyond Compare 4/bcomp.exe" "$LOCAL" "$REMOTE"
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd=''
mergetool.sourcetree.trustexitcode=true
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
gui.recentrepo=D:/Git_LOCAL/SaFu
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github-am.geo.conti.de:ADAS/SaFu.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.repositoryformatversion=0

**Output of `git lfs env`**
$ git lfs env
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)
git version 2.37.1.windows.1

Endpoint=https://github-am.geo.conti.de/ADAS/SaFu.git/info/lfs (auth=none)
  SSH=git@github-am.geo.conti.de:ADAS/SaFu.git
LocalWorkingDir=D:\Git_LOCAL\SaFu
LocalGitDir=D:\Git_LOCAL\SaFu\.git
LocalGitStorageDir=D:\Git_LOCAL\SaFu\.git
LocalMediaDir=D:\Git_LOCAL\SaFu\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\Git_LOCAL\SaFu\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\Git_LOCAL\SaFu\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This isn't a Git LFS issue.  What you're seeing is a change in behaviour for GitHub, and this repository is only for the Git LFS open source project.

As I understand it, this change happened because previously the file was not uploaded as a Git LFS file, but as a regular Git file, and that can cause problems with files appearing perpetually modified [as outlined in the FAQ](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-faq.adoc).

In any event, this is an issue that would best addressed with GitHub support, since there's nothing we can do about it in this project.
