### ISSUE TITLE
CRITICAL: Wiki pages deleted

### ISSUE THREAD

**Issue by PMooreWand** [git-lfs/git-lfs#5420]
**Describe the issue**
Wiki pages at https://github.com/git-lfs/git-lfs/wiki have been destroyed. looking through the revision history on each page shows same user deleted the remaining pages 5 days ago. (5th July 2023)
https://github.com/git-lfs/git-lfs/wiki/Home/_history 

Looking at the page from my own account this appears to be due to the WIKI access rules being open to all users, as I have ability to edit and add new pages without being part of the project.

![image](https://github.com/git-lfs/git-lfs/assets/45370130/53536791-cf79-4b90-a9f4-8c07d487b7bb)

Revisions prior to this users interaction should be restored and Wiki write access appropriately restricted.

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I've rolled back those changes.  We do generally want people to be able to edit things in good faith to add implementations and such, so I'll plan to leave it open, although I'll discuss the possibility of restricting access with the other core team members.
