### ISSUE TITLE
New patch release to fix pure-SSH on macOS

### ISSUE THREAD

**Issue by aymanbagabas** [git-lfs/git-lfs#5422]
It's been a while since the last release (3.3.0), I'm specifically waiting on 83fdf8efd536d0879f74cc201ad5b5b155bb92cf to be released in a new _patch_ release. Otherwise, the pure-SSH LFS transfer is unusable on macOS.

**Comment by chrisd8088** [comment]
As mentioned in #5403, we are looking to try to get a release out in July, if at all possible.  I don't think it will be a patch release, though, as have feature changes as well which need to be released also.

Thank you again for the several fixes which will be in the next release!
