### ISSUE TITLE
Downloading git lfs files

### ISSUE THREAD

**Issue by bykovam** [git-lfs/git-lfs#5424]
This is very much a beginner issue, but I can't find out how to fix the problem otherwise. I am interested in downloading files in a github repository (https://github.com/Jakobsson-Lab/TBI_Garza_2023), and a lot of those files, after I've cloned them onto my Windows 10 laptop through Git Bash, are in the format

version https://git-lfs.github.com/spec/v1

oid sha256:

size 

(they're not blank, the files are filled in with hash values and the actual size). I'm really not sure how to proceed, and a lot of the advice I do see seems to be aimed at more expert users than me. Thanks in advance for any help!

**Comment by bykovam** [comment]
I'm probably not doing something correct, being it's claiming "Not in a Git repository."

**Comment by bk2204** [comment]
For the first command, you can run `git lfs install --skip-repo`, which will set up Git LFS correctly regardless of whether or not you're in a repository.  For `git lfs pull`, you do need to be in a repository.

Are you in the directory you've cloned?  If so, what does `git rev-parse --show-toplevel --git-dir` print?  If it's an error, can you tell me what command you used to clone the repository?

**Comment by bykovam** [comment]
The command I used was git clone https://github.com/Jakobsson-Lab/TBI_Garza_2023.git. I'll run your suggestions and see how they work, and update the results. Thanks so much!

**Comment by bykovam** [comment]
`git rev-parse --show-toplevel --git-dir`

C:/Users/BYKOVAM/Documents/TBI_Omics/Differentially_Expressed_Genes/TBI_And_Concussion/Git_Clone_Garza/TBI_Garza_2023
.git

`git lfs pull`

[b3df30ff3e05bc1f1ca856285eda67127f0eab0cd4bfec049d285d78d8f623b8] Object does not exist on the server: [404] Object does not exist on the server
[3da36f8b7f08b67373326c5bddc60b8477d2da180248348f6d77593745d06ebc] Object does not exist on the server: [404] Object does not exist on the server

And continuing on for pages. Last sentence is "Failed to fetch some objects from 'https://github.com/Jakobsson-Lab/TBI_Garza_2023.git/info/lfs'"

**Comment by bykovam** [comment]
I see the issue. I sent an email to the authors of the github. Thanks so much for your help!
