### ISSUE TITLE
Explicitly use git-lfs-transfer

### ISSUE THREAD

**Issue by aymanbagabas** [git-lfs/git-lfs#5440]
Is there a way to explicitly use `git-lfs-transfer` or `git-lfs-authenticate` and fail if the method fails?

**Comment by bk2204** [comment]
Hey,

No, there is not.  We always attempt `git-lfs-transfer` and fall back to `git-lfs-authenticate` if that fails.  This is the behaviour that is most compatible and will work in the greatest number of cases.  We will, however, accept a patch to force the use of one or the other if someone wants to send one.
