### ISSUE TITLE
it doesn't allow me to download

### ISSUE THREAD

**Issue by G10Rg10C** [git-lfs/git-lfs#5441]

**Comment by bk2204** [comment]
Hey,

Could you fill out the issue template and explain in detail the problem you're seeing, including the error messages, and what you expected to happen?  Unfortunately, there's not enough information here for us to know what problem you're seeing and therefore we can't say how to fix it.

**Comment by G10Rg10C** [comment]
unfortunately I used another method to download and  I downloaded directly from bash file after some problem there too, but thank you for the help, if it's important for the community I can try again and report the error

**Comment by bk2204** [comment]
Okay, I'm going to close this, then, but if you see the problem reoccur, please open a new issue, filling out the issue template including reproduction steps, and we'll try to help out.
