### ISSUE TITLE
Shit 

### ISSUE THREAD

**Issue by samloe123** [git-lfs/git-lfs#5456]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by samloe123** [comment]
/
/
Duplicate of #

**Comment by chrisd8088** [comment]
As this doesn't appear to be a useful contribution or question, I'm going to close it.  Please refrain from using impolite language in any future issues in this project.
