### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0  goroutine 27

### ISSUE THREAD

**Issue by wa1one** [git-lfs/git-lfs#5464]
**Describe the bug**
`git lfs fetch` shows panic runtime error (goroutine 27).

**To Reproduce**
1. Go to 'some cloned repo folder'
2. Run `git lfs fetch`
3. Enter HTTP auth/passwd (using security tokens)

**Expected behavior**
`git lfs fetch` runs successfully

**System environment**
Ubuntu 22.04

**Output of `git lfs env`**
```
panic: runtime error: index out of range [0] with length 0

goroutine 27 [running]:
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).getCreds(0xc00045bb60, {0xc000380200, 0x6}, {{0xc000380285, 0x5}, {0xc00039fe30, 0x2e}}, 0xc0000f6100)
	github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:165 +0x798
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).doWithAuth(0xc00045bb60, {0xc000380200, 0x6}, {{0xc000380285, 0x5}, {0xc00039fe30, 0x2e}}, 0xc0000f6100, {0x0, 0x0, ...})
	github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:63 +0xd8
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoWithAuth(0xc00045bb60, {0xc000380200, 0x6}, {{0xc000380285, 0x5}, {0xc00039fe30, 0x2e}}, 0xc0000f6100)
	github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:26 +0x79
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoAPIRequestWithAuth(0xc00045bb60, {0xc000380200, 0x6}, 0xc0000f6100)
	github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:57 +0x147
github.com/git-lfs/git-lfs/v3/tq.(*tqClient).Batch(0xc000384b60, {0xc000380200, 0x6}, 0xc0004b85a0)
	github.com/git-lfs/git-lfs/v3/tq/api.go:94 +0x3fe
github.com/git-lfs/git-lfs/v3/tq.Batch({0xb5c298, 0xc00003b400}, 0x1, {0xc000380200, 0x6}, 0x1?, {0xc00049aa80, 0x64, 0x64})
	github.com/git-lfs/git-lfs/v3/tq/api.go:45 +0x2c8
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc0000f6200, {0xc00049a000, 0x64, 0x0?})
	github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:581 +0x30d
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1()
	github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:470 +0x8b
created by github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches
	github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:463 +0x2bb

```

**Additional context**
Any other relevant context about the problem here.

**Comment by chrisd8088** [comment]
Hi again, @wa1one!  We'd like to track this down, and if you are able to supply some more info like the output of `git lfs env`, `git config -l`, and `GIT_TRACE=1 git lfs fetch`, that would be great!

**Comment by bk2204** [comment]
Hey,

I think I may have a fix for this in #5490.  Could you try it and see if it fixes your problem?

**Comment by BabaqKakRanshe** [comment]
Did not help. I did everything you described, the error remained the same.
![image](https://github.com/git-lfs/git-lfs/assets/49144675/c7605b9b-356d-4f12-a954-1825231ed23d)

**Comment by bk2204** [comment]
If folks are still seeing this problem, we'll need some reproduction steps.  We're not seeing this problem and from all the tracebacks I've seen, the affected line should have been fixed by #5490.  Without reproduction steps, we won't be able to address this.

**Comment by manig28** [comment]
i was able to find a pattern. If remote does not allow lfs locking, and **lfs.locksverify** is set to true , then git-lfs will crash (when used with credential manager). after setting lfs.locksverify to false, git-lfs commands work fine. I hope it helps you to reproduce the issue and fix it.

**Comment by chrisd8088** [comment]
I've been able to reproduce this as follows on a Windows system with Git LFS 3.4.0, after cloning a private GitHub repository with a Git LFS object in it.  The first steps assume that the Git Credential Manager for Windows will pop up and allow one to enter a GitHub credential.  This was run in a Bash terminal after installing the latest Git for Windows.

```
$ git clone https://github.com/chrisd8088/example.git
$ cd example
$ git show HEAD:test.bin
version https://git-lfs.github.com/spec/v1
oid sha256:4e955fea0268518cbaa500409dfbec88f0ecebad28d84ecbe250baed97dba889
size 4

# remove object from working tree and local cache
$ rm test.bin .git/lfs/objects/4e/95/4e955fea0268518cbaa500409dfbec88f0ecebad28d84ecbe250baed97dba889

# erase GCM credentials
$ printf "protocol=https\r\nhost=github.com\r\n\r\n" | git credential-manager erase

# store GCM credentials with empty password
$ printf "protocol=https\r\nhost=github.com\r\nusername=chrisd8088\r\npassword=\r\n\r\n" | git credential-manager store

# check GCM credentials with empty password
$ printf "protocol=https\r\nhost=github.com\r\n\r\n" | git credential-manager get
protocol=https
host=github.com
username=chrisd8088
password=

$ GIT_TRACE=1 git lfs pull
...
11:44:52.998041 trace git-lfs: fetch test.bin [4e955fea0268518cbaa500409dfbec88f0ecebad28d84ecbe250baed97dba889]
11:44:53.014967 trace git-lfs: tq: sending batch of size 1
11:44:53.015155 trace git-lfs: api: batch 1 files
11:44:53.015155 trace git-lfs: creds: git credential fill ("https", "github.com", "")
11:44:53.015860 trace git-lfs: exec: git 'credential' 'fill'
11:44:53.405652 trace git-lfs: Filled credentials for https://github.com/chrisd8088/example
panic: runtime error: index out of range [0] with length 0
 
goroutine 53 [running]:
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).getCreds(0xc0000867e0, {0xc0001789d5, 0x6}, {{0xc000178a79, 0x5}, {0xc0002635c0, 0x37}}, 0xc00023d200)
        github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:165 +0x798
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).doWithAuth(0xc0000867e0, {0xc0001789d5, 0x6}, {{0xc000178a79, 0x5}, {0xc0002635c0, 0x37}}, 0xc00023d200, {0x0, 0x0, ...})
        github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:63 +0xd8
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoWithAuth(0xc0000867e0, {0xc0001789d5, 0x6}, {{0xc000178a79, 0x5}, {0xc0002635c0, 0x37}}, 0xc00023d200)
        github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:26 +0x79
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoAPIRequestWithAuth(0xc0000867e0, {0xc0001789d5, 0x6}, 0xc00023d200)
        github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:57 +0x147
github.com/git-lfs/git-lfs/v3/tq.(*tqClient).Batch(0xc00015d410, {0xc0001789d5, 0x6}, 0xc000087b00)
        github.com/git-lfs/git-lfs/v3/tq/api.go:94 +0x3fe
github.com/git-lfs/git-lfs/v3/tq.Batch({0x1047c38, 0xc00009cc80}, 0x1, {0xc0001789d5, 0x6}, 0x1?, {0xc000098540, 0x1, 0x1})
        github.com/git-lfs/git-lfs/v3/tq/api.go:45 +0x2c8
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc00023c100, {0xc000127c00, 0x1, 0xc000030dad?})
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:581 +0x30d
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1()
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:470 +0x8b
created by github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:463 +0x2bb
```

I'll try next with the latest Git LFS binary to see if PR #5490 resolves the problem, as we expect it to.

**Comment by chrisd8088** [comment]
As expected, PR #5490 did resolve this problem.  Replacing the `git-lfs` binary provided with Git for Windows with a recent build causes the same `git lfs pull` command, after an empty password is entered into GCM, to not crash while running Git LFS, but instead launch GCM to prompt for a valid set of credentials, as desired.

(For reference, `git lfs version` reports `git-lfs/3.4.0 (GitHub; windows amd64; go 1.21.4; git f3820d5c)` when running the binary I downloaded from a recent CI [build](https://github.com/git-lfs/git-lfs/actions/runs/7010775893).  The stock Git LFS installed with Git for Windows is instead the v3.4.0 release version, `git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)`.)

**Comment by chrisd8088** [comment]
The same crash can also be simulated on macOS and Linux; that corresponds with the original report in this issue where the problem was seen on an Ubuntu Linux system.  On macOS, for example, with the same setup as described above:
```
$ printf "protocol=https\nhost=github.com\n\n" | git credential-osxkeychain erase
$ printf "protocol=https\nhost=github.com\nusername=chrisd8088\npassword=\n\n" | git credential-osxkeychain store
$ git lfs pull
panic: runtime error: index out of range [0] with length 0
```

**Comment by EMRAN-TA** [comment]
hi,
not solved the issue.
I removed git and Lfs, then I installed git then installed Lfs from https://github.com/git-lfs/git-lfs/actions/runs/6511855208
But The issue hasn't gone away.

$ git push
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).getCreds(0xc000186360, {0xc0000280d8, 0x6}, {{0xc0003344c4, 0x5}, {0xc0001bcd80, 0x5f}}, 0xc0001b8900)
github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:165 +0x7a5
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).doWithAuth(0xc000186360, {0xc0000280d8, 0x6}, {{0xc0003344c4, 0x5}, {0xc0001bcd80, 0x5f}}, 0xc0001b8900, {0x0, 0x0, ...})
github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:63 +0xd8
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoWithAuth(0xc000186360, {0xc0000280d8, 0x6}, {{0xc0003344c4, 0x5}, {0xc0001bcd80, 0x5f}}, 0xc0001b8900)
github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:26 +0x79
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoAPIRequestWithAuth(0xc000186360, {0xc0000280d8, 0x6}, 0xc0001b8900)
github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:57 +0x147
github.com/git-lfs/git-lfs/v3/locking.(*httpLockClient).SearchVerifiable(0xc0001a00a0, {0xc0000280d8, 0x6}, 0x145d8bf?)
github.com/git-lfs/git-lfs/v3/locking/api.go:287 +0x155
github.com/git-lfs/git-lfs/v3/locking.(*genericLockClient).SearchVerifiable(0xc0001a5f80?, {0xc0000280d8, 0x6}, 0xc0000bf8d8?)
github.com/git-lfs/git-lfs/v3/locking/api.go:368 +0x4c
github.com/git-lfs/git-lfs/v3/locking.(*Client).SearchLocksVerifiable(0xc0003928c0, 0x0, 0x0)
github.com/git-lfs/git-lfs/v3/locking/locks.go:273 +0x412
github.com/git-lfs/git-lfs/v3/commands.(*lockVerifier).Verify(0xc000392140, 0xc0001a5f80)
github.com/git-lfs/git-lfs/v3/commands/lockverifier.go:60 +0xbe
github.com/git-lfs/git-lfs/v3/commands.verifyLocksForUpdates(0xc0003b6000?, {0xc0001a0080, 0x1, 0xc0000bfc10?})
github.com/git-lfs/git-lfs/v3/commands/lockverifier.go:28 +0x34
github.com/git-lfs/git-lfs/v3/commands.uploadForRefUpdates(0xc0003b6000, {0xc0001a0080?, 0x1, 0x1}, 0x0?)
github.com/git-lfs/git-lfs/v3/commands/uploader.go:27 +0xde
github.com/git-lfs/git-lfs/v3/commands.prePushCommand(0xc00016c900?, {0xc0002041a0, 0x2, 0x2?})
github.com/git-lfs/git-lfs/v3/commands/command_pre_push.go:62 +0x1df
github.com/spf13/cobra.(*Command).execute(0xc00016c900, {0xc000204140, 0x2, 0x2})
github.com/spf13/cobra@v1.6.0/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004c00)
github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.6.0/command.go:968
github.com/git-lfs/git-lfs/v3/commands.Run()
github.com/git-lfs/git-lfs/v3/commands/run.go:154 +0x4ad
main.main()
github.com/git-lfs/git-lfs/v3/git-lfs.go:34 +0xe5
error: failed to push some refs to " "

**Comment by EMRAN-TA** [comment]
> Hi @bk2204
> 
> i was able to find a pattern. If remote does not allow lfs locking, and **lfs.locksverify** is set to true , then git-lfs will crash (when used with credential manager). after setting lfs.locksverify to false, git-lfs commands work fine. I hope it helps you to reproduce the issue and fix it.

Hi,
it worked for once then Back to crash

**Comment by EMRAN-TA** [comment]
> @EMRAN-TA -- Can you make sure to include the output of `git lfs version` here so we can be certain what build of the Git LFS binary you are using?
> 
> The reason this is important is that your stack trace shows the following:
> 
> ```
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 1 [running]:
> github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).getCreds(0xc000186360, {0xc0000280d8, 0x6}, {{0xc0003344c4, 0x5}, {0xc0001bcd80, 0x5f}}, 0xc0001b8900)
> github.com/git-lfs/git-lfs/v3/lfsapi/auth.go:165 +0x7a5
> ```
> 
> which means there's an attempt to read index position 0 from an array with no elements at line 165 in `lfsapi/auth.go`, which is this [code](https://github.com/git-lfs/git-lfs/blob/v3.4.0/lfsapi/auth.go#L165) in the Git LFS v3.4.0 release:
> 
> ```go
> 			setRequestAuth(req, credWrapper.Creds["username"][0], credWrapper.Creds["password"][0])
> ```
> 
> However, in a recent build of Git LFS that code literally no longer exists; instead it [looks](https://github.com/git-lfs/git-lfs/blob/6c94277c6c725b1c72c211dc9f145e37c0e0bcad/lfsapi/auth.go#L165) like this:
> 
> ```go
> 			setRequestAuth(req, creds.FirstEntryForKey(credWrapper.Creds, "username"), creds.FirstEntryForKey(credWrapper.Creds, "password"))
> ```
> 
> There is no longer an attempt to index at position 0 of an array; instead there are calls to a new subfunction, `creds.FirstEntryForKey()`. Since that subfunction's name does not appear in your stack trace, you must somehow be using the v3.4.0 version of the Git LFS binary, I believe. Hence it's important to see what `git lfs version` outputs.

$ git lfs version
git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)

**Comment by chrisd8088** [comment]
@EMRAN-TA -- OK, that's as I suspected; you're still running the official v3.4.0 release (note the `d06d6e9` and the `go 1.20.6`).

Once you fully install a replacement build, `git lfs version` will show something different.  For instance, as I noted in https://github.com/git-lfs/git-lfs/issues/5464#issuecomment-1836830898, the build I've tested which resolves the crash bug shows `git-lfs/3.4.0 (GitHub; windows amd64; go 1.21.4; git f3820d5c` (note the `go.1.21.4` in particular).

**Comment by EMRAN-TA** [comment]
> @EMRAN-TA -- OK, that's as I suspected; you're still running the official v3.4.0 release (note the `d06d6e9` and the `go 1.20.6`).
> 
> Once you fully install a replacement build, `git lfs version` will show something different. For instance, as I noted in [#5464 (comment)](https://github.com/git-lfs/git-lfs/issues/5464#issuecomment-1836830898), the build I've tested which resolves the crash bug shows `git-lfs/3.4.0 (GitHub; windows amd64; go 1.21.4; git f3820d5c` (note the `go.1.21.4` in particular).

I Downloaded Git lfs from  https://github.com/git-lfs/git-lfs/actions/runs/7010775893 but still version **d06d6e9e**
 $ git lfs version
git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)
how I can download the new version?

**Comment by EMRAN-TA** [comment]
> > how I can download the new version?
> 
> @EMRAN-TA -- From a CI build such as the [run](https://github.com/git-lfs/git-lfs/actions/runs/7010775893) you mentioned, click on Summary at the top of left-hand pane, then the Artifacts at the bottom of the right-hand pane, and choose the appropriate Zip archive for your OS (Windows, macOS, Linux). For instance, if I choose `windows-latest`, a Zip archive downloads, which contains four binaries:
> 
> ```
> git-lfs-arm64.exe
> git-lfs-windows-3.4.0.exe
> git-lfs-x64.exe    
> git-lfs-x86.exe
> ```
> 
> In my case, I needed the x64 version for Windows, so I used `git-lfs-x64.exe`.
> 
> If you're on Linux, the `ubuntu-latest` Zip archive contains a set of `*.tar.gz` files, which need to be further unpacked:
> 
> ```
> git-lfs-linux-386-v3.4.0-138-gf3820d5c.tar.gz  
> git-lfs-linux-amd64-v3.4.0-138-gf3820d5c.tar.gz  
> git-lfs-linux-arm-v3.4.0-138-gf3820d5c.tar.gz  
> ...
> ```
> 
> Unpacking any of those will output a bunch of files in a subdirectory, and you'd be looking for the `git-lfs` binary, such as:
> 
> ```
> git-lfs-3.4.0-138-gf3820d5c/git-lfs
> ```
> 
> Once you have the binary appropriate for your OS and hardware, you need to replace the `git-lfs` binary you're currently using, or make sure the new one is located first in your `PATH`. Since I only needed to do this for testing purposes, I just made sure the replacement binary was in a directory that appeared earlier in my `PATH` than the system-provided `git-lfs` binary.
> 
> So for example on Windows, using the Bash terminal provided by Git for Windows, I checked my `PATH` (`echo $PATH`) and then copied the `git-lfs-x64.exe` file into the first location, which was `/c/Users/<username>/bin` in my case, and made sure the file was named `git-lfs.exe`, not `git-lfs-x64.exe`. Running `command -v git-lfs` it then shows `/c/Users/<username>/bin/git-lfs`, meaning that is the program that's found and will be run when the system is looking for a `git-lfs` binary. Running `git lfs version` will let you confirm you're running the replacement. (On Linux and macOS you can use the same commands.) You could also find the system-provided binary with `command -v git-lfs` and then move that file to another name or location, and replace it with the binary you've downloaded.


chrisd8088 thank you for your help.
I tried  to Solve the issue and follow your instructions, but I Can't.

I did the next:
1.Remove Git and Git LFS 
installed Git Without  checked Git LFS (Large File Support)
2. go https://github.com/git-lfs/git-lfs/actions/runs/7010775893
3.click on Summary at the top of left-hand pane
4.then Click the Artifacts at the bottom of the right-hand pane
5. I choose Windows
6.Extract  windows-latest .zip
7. Files
git-lfs-arm64.exe
git-lfs-windows-3.4.0.exe
git-lfs-x64.exe    
git-lfs-x86.exe

8. I Can't Find  bin file   on Windows  "C:\Users\<username>"

$ echo $PATH
/c/Users/<username>/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/<username>/bin:/c/Program Files/Oculus/Support/oculus-runtime:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files/Git LFS:/c/Program Files/dotnet:/cmd:/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/<username>/.dotnet/tools:/usr/bin/vendor_perl:/usr/bin/core_perl

Command  not found.
$ -v git-lfs
bash: -v: command not found.


9.Added  git-lfs-x64.exe   with replace name to   git-lfs.exe     to C:\Program Files\Git\mingw64\bin

10.Version 
$ git lfs version
git-lfs/3.4.0 (GitHub; windows amd64; go 1.21.4; git f3820d5c) 


10. when I try Push   suspend.
$ git push
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s

**Comment by chrisd8088** [comment]
@EMRAN-TA -- I think this is getting a little off-topic of the actual bug, so I'll keep my comments brief.  First of all, you've successfully replaced your Git LFS binary, since you're now seeing `git-lfs/3.4.0 (GitHub; windows amd64; go 1.21.4; git f3820d5)`.  So that's a success.  But it sounds like you may have introduced some other problems along the way, possibly by removing Git and Git LFS and/or by installing Git for Windows _without_ Git LFS.  I'd suggest you try `git lfs install` to see if that helps, and if not, please open a new issue and put all your details there.  Good luck!

**Comment by bk2204** [comment]
I believe the plan is to do a v3.4.1.  @chrisd8088 is one of the core team members and will likely be responsible for the release, although plans could change.

**Comment by bk2204** [comment]
I believe this has been fixed.
