### ISSUE TITLE
Getting "Bad Credentials" trying to `git lfs fetch` for public repo

### ISSUE THREAD

**Issue by the-real-adammork** [git-lfs/git-lfs#5473]
**Describe the bug**
One of our CICD jobs is unable to `git lfs fetch` from a public repo. We initialize the submodule, the file pointers are there. Ive used `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs fetch` to see more details about the failing request. If I re-make the request without the `Authorization` header, it will succeed. 

If theres a way to remove or replace the authorization header I think that will solve my problem, but all the things Ive tried:

`git config --system http.emptyAuth true` 
`git config --system credential.authority basic`
`git config --system http.extraHeaders="Authorization <something else>"`

had no effect

update: This CircleCI repo/job is configured with a deploy-key. We have another repo/job that is configured with a user-key, and it has no problems.

**To Reproduce**

not working
```
curl -X POST "https://lfs.github.com/mobilecoinofficial/libmobilecoin-apple-artifacts/objects/batch" \\n     -H "Host: lfs.github.com" \\n     -H "Accept: application/vnd.git-lfs+json" \\n     -H "Authorization: RemoteAuth gitauth-v1-grrWojBQSb_************" \\n     -H "Content-Length: 781" \\n     -H "Content-Type: application/vnd.git-lfs+json; charset=utf-8" \\n     -H "Github-Deploy-Key: 51208876" \\n     -H "User-Agent: git-lfs/3.2.0 (GitHub; darwin amd64; go 1.18.2)" \\n     --http1.1 \\n     -d '{ "operation": "download", "objects": [ {"oid": "f5976ca9c95b40028ff5011a3b24316f25c5f4b87e11e0b558513003ea2c761c","size": 117187344}, {"oid": "7c2de7d2dfbc88210995d2cb17e35352647ca59d48876c56a99ef1a19d8b3e19","size": 112873616}, {"oid": "40bcb4a13cef1fde3d6145a963e16c364b39c06ed10d7d07f02c5439dbac61a2","size": 61379896}, {"oid": "bf20cc840ebdef250482a1bf9d04698ecb693c6d7ba724415103ceef8d620880","size": 61165696}, {"oid": "9c330b1d22fcd99df2209d786f53658f29074e77cc11c04f3c988cc3499d1158","size": 58837840}, {"oid": "f1dc053aee84d53c6c480d029aa14dba34c65eec291b5979df1be59d03dd3f10","size": 58349456}, {"oid": "97e5c38995f85a49efa946e4dc12b286395b1201ee1f87564796d4c6f2d5f715","size": 51493672} ], "transfers": ["basic", "ssh", "lfs-standalone-file"], "ref": {"name": "refs/heads/master"} }'\n
```

working:

```
curl -X POST "https://lfs.github.com/mobilecoinofficial/libmobilecoin-apple-artifacts/objects/batch"      -H "Host: lfs.github.com"      -H "Accept: application/vnd.git-lfs+json"      -H "Content-Type: application/vnd.git-lfs+json; charset=utf-8"      -H "Github-Deploy-Key: 51208876"      -H "User-Agent: git-lfs/3.2.0 (GitHub; darwin amd64; go 1.18.2)"           --http1.1      -d '{ "operation": "download", "objects": [ {"oid": "f5976ca9c95b40028ff5011a3b24316f25c5f4b87e11e0b558513003ea2c761c","size": 117187344}, {"oid": "7c2de7d2dfbc88210995d2cb17e35352647ca59d48876c56a99ef1a19d8b3e19","size": 112873616}, {"oid": "40bcb4a13cef1fde3d6145a963e16c364b39c06ed10d7d07f02c5439dbac61a2","size": 61379896}, {"oid": "bf20cc840ebdef250482a1bf9d04698ecb693c6d7ba724415103ceef8d620880","size": 61165696}, {"oid": "9c330b1d22fcd99df2209d786f53658f29074e77cc11c04f3c988cc3499d1158","size": 58837840}, {"oid": "f1dc053aee84d53c6c480d029aa14dba34c65eec291b5979df1be59d03dd3f10","size": 58349456}, {"oid": "97e5c38995f85a49efa946e4dc12b286395b1201ee1f87564796d4c6f2d5f715","size": 51493672} ], "transfers": ["basic", "ssh", "lfs-standalone-file"], "ref": {"name": "refs/heads/master"} }'
```

**Expected behavior**
GIT-LFS should be able to make this request successfully, its a public repo.

**System environment**
CircleCI macOS 

**Output of `git lfs env`**

```
git-lfs/3.2.0 (GitHub; darwin amd64; go 1.18.2)
git version 2.38.1

Endpoint=https://github.com/mobilecoinofficial/libmobilecoin-apple-artifacts.git/info/lfs (auth=none)
  SSH=git@github.com:mobilecoinofficial/libmobilecoin-apple-artifacts.git
LocalWorkingDir=/Users/distiller/libmobilecoin-apple-artifacts
LocalGitDir=/Users/distiller/libmobilecoin-apple-artifacts/.git
LocalGitStorageDir=/Users/distiller/libmobilecoin-apple-artifacts/.git
LocalMediaDir=/Users/distiller/libmobilecoin-apple-artifacts/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/distiller/libmobilecoin-apple-artifacts/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/distiller/libmobilecoin-apple-artifacts/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/Cellar/git/2.38.1/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

**Comment by bk2204** [comment]
Hey,

This doesn't sound like a problem with the Git LFS open source project.  It sounds like we're correctly sending the `Authorization` header that the SSH authorization endpoint provided us.  I believe it's true that for GitHub that invalid authentication generally prevents access, even to public repositories, but that's not a fault of the Git LFS open source client.

We don't provide a way to replace or delete the `Authorization` header that's provided by the SSH endpoint, and in general you should not use `http.extraheader` for `Authorization` headers because it _always_ adds the header, which is almost never the right approach for Git LFS.  The server's SSH endpoint is supposed to only issue valid tokens, which is why we don't second-guess it.

I'd suggest you contact GitHub Support about this issue, and they can help you troubleshoot why the credentials aren't working.  Obviously, if the deploy key is for a different repository, then that would explain why it doesn't work.  In such a case, you could use HTTPS instead, since authentication isn't required for fetching public repositories over HTTPS, whereas authentication is always required for SSH.

**Comment by the-real-adammork** [comment]
ya, I agree its a `git` config thing. thank you for the swift reply.
