### ISSUE TITLE
Can anyone who gets the pointer file be able to download the corresponding large file? 

### ISSUE THREAD

**Issue by DeqiangXIA** [git-lfs/git-lfs#5474]
**Describe the issue**
Hi, I want to know that can anyone who gets the pointer file be able to download the corresponding large file?

**Comment by DeqiangXIA** [comment]
@KalleOlaviNiemitalo Thanks for your reply.

**Comment by bk2204** [comment]
I think this should answer the question adequately, so I'm going to close this.  Let us know if there's more information needed.
