### ISSUE TITLE
Uploading LFS objects stops after a while and eventually raises an error.

### ISSUE THREAD

**Issue by ChangHChen** [git-lfs/git-lfs#5497]
**Describe the issue**

I've trying to push my model file to huggingface.
I believe the huggingface account is set, lfs support is installed because the uploading process actually starts and keep running for a small amount of time.
But the uploading gets stuck after a while and eventually the process stops with an error.
```
EOFoading LFS objects:  50% (1/2), 407 MB | 9.2 MB/s
error: failed to push some refs to 'hf.co:HCZhang/SOLAR-0-70b-4bit-GPTQ
```
I'm pretty sure this is not a bug of git or git-lfs but rather something wrong with my settings or environment.
So I apologize if someone already reported similar issues and found the solution. But I've tried all the solutions I could find, the uploading still stops.
Thank you.

**System environment**
output of `git config -l`
```
credential.helper=!f() { /root/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /tmp/vscode-remote-containers-a1604a00-3a2a-4703-a2db-6254358a4499.js git-credential-helper $*; }; f
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=ChangHChen
user.email=zhcgithub.gmail.com
credential.helper=!f() { /root/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /tmp/vscode-remote-containers-a1604a00-3a2a-4703-a2db-6254358a4499.js git-credential-helper $*; }; f
safe.directory=/docker
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@hf.co:HCZhang/SOLAR-0-70b-4bit-GPTQ
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
lfs.customtransfer.multipart.path=huggingface-cli
lfs.customtransfer.multipart.args=lfs-multipart-upload
lfs.https://hf.co/HCZhang/SOLAR-0-70b-4bit-GPTQ.git/info/lfs.locksverify=false
user.name=HCZhang
user.email=u023353c@ecs.osaka-u.ac.jp
lfs.activitytimeout=180
lfs.repositoryformatversion=0
lfs.contenttype=false
```

**Output of `git lfs env`**
 ```
git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
git version 2.42.0

Endpoint=https://hf.co/HCZhang/SOLAR-0-70b-4bit-GPTQ.git/info/lfs (auth=none)
  SSH=git@hf.co:HCZhang/SOLAR-0-70b-4bit-GPTQ
LocalWorkingDir=/models/SOLAR-0-70b-4bit-GPTQ
LocalGitDir=/models/SOLAR-0-70b-4bit-GPTQ/.git
LocalGitStorageDir=/models/SOLAR-0-70b-4bit-GPTQ/.git
LocalMediaDir=/models/SOLAR-0-70b-4bit-GPTQ/.git/lfs/objects
LocalReferenceDirs=
TempDir=/models/SOLAR-0-70b-4bit-GPTQ/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/models/SOLAR-0-70b-4bit-GPTQ/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,multipart,ssh
UploadTransfers=basic,lfs-standalone-file,multipart,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Can you try pushing from the command line by prefixing your command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and redirecting standard error to a file with `2>stderr.txt`, and then attach the `stderr.txt` here?  That should tell us what the failure is.

**Comment by ChangHChen** [comment]
> 

Hello, I've generated the log file like you suggested.
I attach the file here.
Thank you so much.
[stderr.txt](https://github.com/git-lfs/git-lfs/files/12554811/stderr.txt)

**Comment by bk2204** [comment]
Hey,

It looks like you're using a custom transfer adapter that's part of the Hugging Face CLI, and that's what's failing.  I'd recommend that you reach out to them about the problem and see if they can help you, since there's nothing we can do to address that custom adapter.  The `stderr.txt` file you generated may be helpful for them, though, so I'd pass it along to them.
