### ISSUE TITLE
I found an error for github push , please help

### ISSUE THREAD

**Issue by gilangwokeh** [git-lfs/git-lfs#5501]
remote: error: Trace: 55dcba23e96b45158226cdd4723c3ebb3cde7c72b6fec49f16636a640ff7e70e
remote: error: See https://gh.io/lfs for more information.
remote: error: File emulator/lib64/qt/lib/libQt5WebEngineCoreAndroidEmu.so.5 is 106.61 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/rekberin/rekberin-mobile.git

**Comment by bk2204** [comment]
Hey,

[The FAQ](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-faq.adoc) outlines how to perform a migration of a repository such that it uses Git LFS.  If you still have problems after following those steps, please open a discussion, and we can help you there.
