### ISSUE TITLE
Cloned  lfs .png files cannot be opened.

### ISSUE THREAD

**Issue by az1494** [git-lfs/git-lfs#5502]
**Describe the issue**
We have a BitBucket repo that uses lfs for .png files. (*.png filter=lfs diff=lfs merge=lfs -text in the .gitattributes file). We can clone it to our local developer machine without problem.

However, when we try to clone it in our publishing machine for deployment, all the .png files cannot be opened, saying 

![image](https://github.com/git-lfs/git-lfs/assets/138694679/ea787ca7-7e15-4cd2-b920-725315f95147)

**System environment**
The publishing server's OS is Windows Server 2019, Version 1809. We installed git-lfs windows v3.4.0. And git version is 2.36.1.windows.1

$ git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=az1494
user.email=az1494@princeton.edu
gui.recentrepo=D:/Projects/GitRepos/Cub
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
:...skipping...
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=az1494
user.email=az1494@princeton.edu
gui.recentrepo=D:/Projects/GitRepos/Cub
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://az1494@bitbucket.org/puappdev/campaigns.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.Campaigns-net48.remote=origin
branch.Campaigns-net48.merge=refs/heads/Campaigns-net48
lfs.repositoryformatversion=0
~
~
~
~
~
(END)

**Output of `git lfs env`**
$ git lfs env
git-lfs/3.1.4 (GitHub; windows amd64; go 1.17.8)
git version 2.36.1.windows.1

Endpoint=https://az1494@bitbucket.org/puappdev/campaigns.git/info/lfs (auth=none)
LocalWorkingDir=C:\GitRepos\campaigns-net48
LocalGitDir=C:\GitRepos\campaigns-net48\.git
LocalGitStorageDir=C:\GitRepos\campaigns-net48\.git
LocalMediaDir=C:\GitRepos\campaigns-net48\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\GitRepos\campaigns-net48\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\GitRepos\campaigns-net48\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=D:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Are you running `git lfs pull` to check out the files on the publication machine?  I ask because I notice that you've used the `--skip` command in the filter configuration, which means that you'll just check out the pointer files and not the actual PNG files themselves.  If you want those files to be checked out automatically, you should remove the `--skip` option from the configuration options, or you'll need to run `git lfs pull` before continuing.

If you've done that and are still seeing the problem, can you look at the contents of one of the files and see if they look like a pointer file?  As an indicator, they'd typically be text files starting with a line that says, `version https://git-lfs.github.com/spec/v1`.

**Comment by az1494** [comment]
Thank you for your response. 

I used TortoiseGit to clone the repo. Sorry, I should have mentioned that in the description.

At beginning, I got smudge errors:

Downloading Princeton.Development.Campaigns.Application/Content/marchchallenge/assets/css/grabbing.png (116 B)
Error downloading object: Princeton.Development.Campaigns.Application/Content/marchchallenge/assets/css/grabbing.png (1d23140): Smudge error: Error downloading Princeton.Development.Campaigns.Application/Content/marchchallenge/assets/css/grabbing.png (1d2314051fac5fdc37afc9cc275e5840dba27c3a94c207a37ba882e466393970): LFS: Get "https://api.media.atlassian.com/file/dad98cc3-ca15-4b2c-a94c-01666de227d1/binary": read tcp 140.180.220.104:51384->104.192.142.17:443: wsarecv: An existing connection was forcibly closed by the remote host.

One suggestion googled online is to run  git lfs install --skip-smudge, and I did.

I will try what you said. Thank you!

**Comment by bk2204** [comment]
Hey,

That particular error probably means that either there's a network problem causing the connection to be closed or you have an overly aggressive firewall (or sometimes, an antivirus).  A proxy or TLS MITM device are also a possibility, but perhaps less likely.  If you can address whatever problem that is, your clone and any subsequent `git lfs pull` operations will likely be successful.  However, it may take some investigation to figure out what the problem actually is.

**Comment by az1494** [comment]
Thank you!

We have other applications on the same publishing machine. All others have no problems when we clone repos. The difference is that:  Only this app uses lfs, while all other apps don't.

**Comment by bk2204** [comment]
I appreciate that.  Git LFS is a Go application, and Go applications sometimes have an unusual structure which causes antiviruses to falsely trip.  It also uses the Go TLS stack, which is different from other TLS stacks.  In addition, sometimes companies have allowlisting and denylisting for domains or sites, and allowlist the main domain or IPs for a forge, but not subsidiary domains or IPs which are used for LFS.  There are lots of reasons Git LFS might function differently than other software on the same machine, including Git, and they aren't intrinsically a bug in Git LFS.

The message `wsarecv: An existing connection was forcibly closed by the remote host` indicates a network problem, which on Unix we would refer to as `ECONNRESET` ("connection reset").  Git LFS works in general for the vast majority of people, so there's likely a problem with your environment that causes this to occur.  I don't know what that is or why it happens, so you'll have to investigate to figure it out.  I'm sorry I can't be more helpful here, but that's what the error message means.  If you do figure out what the relevant factor is, please let us know, and we may be able to provide some tips on how to make things work better for you, but at this point, all we know is that your connection got hung up on somewhere.

If you are using some sort of proxy, [the FAQ contains some information](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-faq.adoc) about what variants we support and tips for having it work well.

**Comment by az1494** [comment]
Good morning,

This problem is solved. We happened to have our scheduled new publishing server ready today. I then tried to clone this project on that new server. Everything works fine.

Not sure why it happened before, but the problem is no longer an issue.

**Comment by az1494** [comment]
Thank you!
