### ISSUE TITLE
Update packagecloud.io distros

### ISSUE THREAD

**Issue by nekohacker591** [git-lfs/git-lfs#5508]
i am running linux mint

Unable to download repo config from: https://packagecloud.io/install/repositories/github/git-lfs/config_file.list?os=LinuxMint&dist=victoria&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this

**Comment by bk2204** [comment]
Hey,

packagecloud.io [doesn't support Linux Mint victoria](https://packagecloud.io/docs) right now.  However, when we do a 3.5.0 release, we'll make a pass through the distros we support and update them, and we can use this issue to track doing that.

In the mean time, you can probably use `os=ubuntu distro=jammy`, and that should work for you for the moment.

**Comment by Foxsenrubas** [comment]
https://github.com/git-lfs/git-lfs/issues/5508#issue-1896948475

**Comment by bk2204** [comment]
For 3.5.0, we included Linux Mint victoria as a supported distro, so I'm closing this as completed.
