### ISSUE TITLE
Add shell completion files in future releases

### ISSUE THREAD

**Issue by holgersson32644** [git-lfs/git-lfs#5520]
Hi,

would you mind to add the generated completion files to future release artifacts?
This would save us a few steps of running `./git-lfs completion <shell> > output` when packaging for downstream distributions (Gentoo/Linux in this case).

best regards,
Nils

**Comment by bk2204** [comment]
Hey,

We can certainly consider this as a future improvement.  Right now, it's a little tricky since we aren't guaranteed to have built the binary for the system during the release process (for example, one can build binaries on, say, a FreeBSD RISC-V system and the release process never builds such a binary).

I'm not certain that you'll actually use our compiled binaries, though, and we wouldn't include it in the source tarball since those are built automatically by `git archive`.

**Comment by holgersson32644** [comment]
Hi, sorry for my delayed response and thanks for your clarifications.

Yes, on Gentoo our package is built from sources and we don't use your precompiled binaries at all. So if I understand you correctly, there is no easy way on your side to add the files to releases.

I also had the thought to ask you to add the files directly into the repo, but that would probably break your assumption of the *generated* completion files as build time artifacts.

So, I guess we will stay at the status quo until something changes in your release process somewhere in the future. If that does, it would be nice if you could remember this request.

Please handle this issue as it fits best to your workflow (e.g. close as wontfix for now and reopen if applicable).

**Comment by chrisd8088** [comment]
> I also had the thought to ask you to add the files directly into the repo, but that would probably break your assumption of the _generated_ completion files as build time artifacts.

In case it helps you, there are copies of the generated completion files in the repository in the `t/fixtures/completions` [directory](https://github.com/git-lfs/git-lfs/tree/196691687bb4c56293db731a5bb11a863e8050f4/t/fixtures/completions).

We'll keep these up-to-date as we have very simple CI [tests](https://github.com/git-lfs/git-lfs/blob/196691687bb4c56293db731a5bb11a863e8050f4/t/t-completion.sh#L5-L27) which use them to confirm that the output of `git lfs completion <shell>` is the expected shell script of each flavour.  So you'd be OK to use those files in the `t/fixtures/completions` directory directly if you want to package them; they should always match what the command would output.

**Comment by holgersson32644** [comment]
I think this already solves this issue! Thanks, somehow I didn't see these.
