### ISSUE TITLE
0x6E5e17B29365AF1637234Fe7fb813f59d845122d

### ISSUE THREAD

**Issue by Falehfaleh** [git-lfs/git-lfs#5521]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This doesn't appear to contain any information about the problem, and thus, I'm going to close it.
