### ISSUE TITLE
git lfs migrate import doubles the size of remote repository

### ISSUE THREAD

**Issue by mmagnesium** [git-lfs/git-lfs#5525]
## Describe the issue 
So, at the moment I'm trying to clean a repository that we use at work for a project. It's gotten large (1GB), an huge portion of this _(now I know that its approximately 600MB)_ are deleted large files stored in history and other like 400MB are some huge .csvs and html files related to python reports and stuff.

**So, my first was goal** is to clean the repo's history by removing large deleted files from it.

**I managed to do this by utilizing git-filter-repo:** tried this in a couple of ways, but my final run was using this guide from [gitlab ](https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html). 

Basically, I git cloned the repo  with `--bare` and `--mirror` and then removed all deleted files and directories from the repo's history.

In total,  I managed to removed 600 MB worth of blobs, so now I have 422MB. After that I created a new fresh remote and `git push --force` all the heads and tags into this new remote.

**The second goal** was to migrate some report related csvs and htmls to git LFS. 

I tried to use migrate info first:

```bash
git lfs migrate info --everything --include="analys/**/*.html,*.csv
```

The output showed that it takes in total approx. 400MB of space. Then I tried to migrate all this in every branch by:

```bash
git lfs migrate import --everything --include="analys/**/*.html,*.csv" --verbose
```

Then I pushed all the heads and tags once again. This resulted in all the files that i wanted now marked as LFS. And my repo now has 400+MB of LFS files. **However**, the Repository weight itself is now effectively doubled, because all the files are now on LFS, but looks like they are still in the repos history as regular files, so Repository portion in storage is now 422MB and also LFS portion is now 480MB, so 900MB in total.

What's the mistake? I just cannot understand. `git lfs migrate` is supposed to rewrite the repos history by default, am I correct?

## System environment

- System: WSL v2 2.0.1 Ubuntu
- Repo is hosted on my work gitlab domain

## Output of `git lfs env`
```
Endpoint=***
  SSH=***
LocalWorkingDir=
LocalGitDir=**.git
LocalGitStorageDir=**.git
LocalMediaDir=**/git/lfs/objects
LocalReferenceDirs=
TempDir=****
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=***.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_ASKPASS=*****
GIT_EXEC_PATH=/usr/lib/git-core
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=*****
VSCODE_GIT_ASKPASS_NODE=****
VSCODE_GIT_IPC_HANDLE=*****
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  May I ask, when you say that the "Repository portion in storage is now 422MB and also LFS portion is now 480MB", how are you determining those sizes?  Can you provide the commands you're using to calculate the totals?

One thing to take note of, just in case it's relevant, is that if you have a working tree (as is typical in Git usage, unless you are using a "bare" Git repository), Git LFS will try to ensure that all any Git LFS objects in your current working tree are replaced with the actual file contents.  So on your local disk you will generally have at least one and sometimes two copies of the Git LFS objects -- one in the `.git/lfs/objects` cache, and if a Git LFS pointer to that object is in the currently checked-out branch, another in your working tree.

There are ways to avoid populating the working tree with copies of the full Git LFS objects (such as cloning with `GIT_LFS_SKIP_SMUDGE=1`), but this will leave the files in the working tree as short Git LFS pointer files, which may not be convenient if you expect to be able to view or edit the corresponding actual file contents.

**Comment by mmagnesium** [comment]
> Hey, I'm sorry you're having trouble. May I ask, when you say that the "Repository portion in storage is now 422MB and also LFS portion is now 480MB", how are you determining those sizes? Can you provide the commands you're using to calculate the totals?
> 
> One thing to take note of, just in case it's relevant, is that if you have a working tree (as is typical in Git usage, unless you are using a "bare" Git repository), Git LFS will try to ensure that all any Git LFS objects in your current working tree are replaced with the actual file contents. So on your local disk you will generally have at least one and sometimes two copies of the Git LFS objects -- one in the `.git/lfs/objects` cache, and if a Git LFS pointer to that object is in the currently checked-out branch, another in your working tree.
> 
> There are ways to avoid populating the working tree with copies of the full Git LFS objects (such as cloning with `GIT_LFS_SKIP_SMUDGE=1`), but this will leave the files in the working tree as short Git LFS pointer files, which may not be convenient if you expect to be able to view or edit the corresponding actual file contents.

On gitlab it is possible to view storage breakdown of the repository on the web. I attached such a breakdown down below:
![image](https://github.com/git-lfs/git-lfs/assets/48142538/4ecf9cae-aa77-4852-83e4-8344d6d09d7b)

Before using `git fls migrate` and `git push --force 'ref/heads*'` +   `git push --force 'ref/tags*'` it was 422MB in repository but LFS was empty.

As for the working tree, ill try it, but actually when i created the clone I'm working in right now, i used `git clone --bare --mirror` but then i also used `git config --unset remote.origin.mirror` to allow myself to force push the changes after using `git filter-repo`. After that i just started `git lfs migrate` stuff in the same local copy of the repo.

**Comment by mmagnesium** [comment]
So finally I managed to pull this all together. I removed all the files I wanted to migrate to LFS with `git filter-repo` and then manually copied them back after clean-up with as new files with LFS enabled.

**Comment by chrisd8088** [comment]
OK, I'm glad you found a solution.  My comments about the working tree and so forth were just in case you were measuring local disk storage with, say, `du`, but it sounds like the issue was something else to do with how GitLab stores the data, so I'd have to refer you to their Support team if you need further assistance.  But it sounds like you've worked something out already.

**Comment by mmagnesium** [comment]
Ok, makes sense. I will try to figure this out with our ITS or gitlab support team. Closing the issue
