### ISSUE TITLE
Can I overwrite git lfs pre-push hook with my own?

### ISSUE THREAD

**Issue by artsmvch** [git-lfs/git-lfs#5532]
**Describe the issue**
`git lfs` adds its own git pre-push hook.

But I want to overwrite it with my own hook. 

So the question is: is it safe to remove the `git lfs` pre-push hook and replace it with my own? Won't it break anything?

**Comment by bk2204** [comment]
Hey,

Git LFS will not overwrite your hook if you replace it with a new one.  However, Git LFS uses that hook to push LFS files, so if you don't call the `git-lfs` binary, then you won't get your objects pushed unless you do it manually.  That's almost certainly going to cause data loss eventually.

Thus, you probably need to do both what you want and call `git-lfs` at the same time, like so:

```
#!/bin/sh

while read -r lref loid rref roid
do
  # Do whatever you want with the variables here.
  printf "%s %s %s %s\n" "$lref" "$loid" "$rref" "$roid" | git-lfs pre-push "$@"
done
```
