### ISSUE TITLE
Pure SSH protocol deadlocks when SSH multiplexing is enabled

### ISSUE THREAD

**Issue by KyleFromKitware** [git-lfs/git-lfs#5535]
**Describe the bug**
When using the pure SSH `git-lfs-transfer` protocol, upon ending the session, `git-lfs` deadlocks unless `lfs.ssh.automultiplex` is set to `false`. This is because `git-lfs` tries to terminate the master ssh instance first, which never ends because it's waiting for all the other multiplexed connections to end.

**To Reproduce**
1. `git lfs push` to a remote that supports the pure SSH protocol
2. See that `git lfs` deadlocks while waiting for its ssh instances to end

**Expected behavior**
`git lfs push` should not deadlock. The deadlock goes away when `lfs.ssh.multiplex` is set to `false`.

**System environment**
Ubuntu 20.04 with an in-development GitLab Shell SSH server

**Output of `git lfs env`**
```
git-lfs/3.4.0 (GitHub; linux amd64; go 1.21.1)
git version 2.25.1

Endpoint (gitlab/ssh)=https://localhost/root/lfs-test.git/info/lfs (auth=none)
  SSH=git@localhost:/root/lfs-test.git
LocalWorkingDir=
LocalGitDir=<REDACTED>/lfs-test.git
LocalGitStorageDir=<REDACTED>/lfs-test.git
LocalMediaDir=<REDACTED>/lfs-test.git/lfs/objects
LocalReferenceDirs=
TempDir=<REDACTED>/lfs-test.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=<REDACTED>/lfs-test.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Additional context**
Note that I encountered this while working on adding `git-lfs-transfer` support to GitLab. I don't know if this is reproducible with other SSH servers.

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I haven't tried reproducing this problem yet, but I agree it sounds like something we need to fix.  I've noticed that you have a PR open, which I'll try to take a look at today or tomorrow (although it seems that CI is failing for reasons I haven't looked at yet).

**Comment by KyleFromKitware** [comment]
> (although it seems that CI is failing for reasons I haven't looked at yet).

I've already addressed the CI failures and further shored up the test infrastructure to account for the new way of doing things.
