### ISSUE TITLE
Can't checkout GitHub files while using Authentication Token as auth (Lowercase URL??)

### ISSUE THREAD

**Issue by Svalorzen** [git-lfs/git-lfs#5536]
**Describe the bug**
I have access to a private repository that uses LFS to store some files. If I clone the repo using ssh and my private key, everything is cloned correctly.

An alternative I have to use is GitHub auth tokens. If I clone the repository using https, then I get asked about my username and password; if I insert my username and my auth token, everything works correctly (I have to insert my credentials over and over for each file). However, if I setup my token in my `.gitconfig`, then I do not get asked my username and password anymore; the repo clones successfully but I get a 403 error as soon as Git LFS tries to download a file. Note that unfortunately I have to make this method of authentication work for company reasons.

*IMPORTANT NOTE* While I was gathering debugging information about this problem I noticed in the full log that the URL that Git LFS tries to access is fully lowercase; while my access key contains uppercase characters. Could this be the reason why I am getting an authentication error? If so, is there a way to tell Git LFS to not lowercase the URL? As in, when running the command:
```
GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://github.com/[MY_REPO].git
```
There is a line inside:
```
trace git-lfs: HTTP: POST https://svalorzen:[my_key]@github.com/[MY_REPO].git/info/lfs/objects/batch
```
where `[my_key]` is my key but all lowercase, which I guess is incorrect.

**To Reproduce**
Clone the repository using https, having added to `.gitconfig` the line

```
[url "https://svalorzen:[MY_KEY]@github.com"]
	insteadOf = https://github.com
```

I get a 403 error on accessing the lfs files, while the rest of the repository clones successfully.

**Expected behavior**
Cloning should just work, no 403 error.

**System environment**
Lubuntu 22.04

**Output of `git lfs env`**
```
git-lfs/2.0.0 (GitHub; linux amd64; go 1.8; git 540e90b5)
git version 2.34.1

Endpoint=https://svalorzen:[MY_KEY]/[MY_PRIVATE_REPO].git/info/lfs (auth=none)
LocalWorkingDir=/home/svalorzen/Tests/tmp/[MY_REPO]
LocalGitDir=/home/svalorzen/Tests/tmp/[MY_REPO]/.git
LocalGitStorageDir=/home/svalorzen/Tests/tmp/[MY_REPO]/.git
LocalMediaDir=/home/svalorzen/Tests/tmp/[MY_REPO]/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/svalorzen/Tests/tmp/[MY_REPO]/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by Svalorzen** [comment]
It seems this was an older issue. Upgrading from git lfs 2.0 to 3.0 seems to have resolved it. I'll close this but won't delete it in case someone ever finds a similar problem :)

**Comment by bk2204** [comment]
Hey,

I'd definitely suggest upgrading to a newer version.  Git LFS 2.0 precedes my time on the project, so I can't say how it does or doesn't work or what changes we would have made that would have resolved this.

In general, I'd recommend against putting the token in the URL and instead suggest a credential helper instead, as [mentioned in the Git FAQ](https://git-scm.com/docs/gitfaq#http-credentials).
