### ISSUE TITLE
"file is not a database" when switching sqlite3 files to git lfs

### ISSUE THREAD

**Issue by creolio** [git-lfs/git-lfs#5572]
**Describe the issue**
After switching to git lfs, my sqlite3 database on Railway no longer works. Is this because only the pointer file is uploaded?
Exception Type:	DatabaseError
Exception Value:	file is not a database
![image](https://github.com/git-lfs/git-lfs/assets/85093210/8b74e286-cbcf-4eb8-b54d-f61c81859909)

I switched to git lfs because my main sqlite3 database file just exceeded 100MB.
I ran all this locally on my existing repo:
git lfs install
git lfs track "*.sqlite3"
git lfs migrate import --include="*.sqlite3" --everything
git add .
git commit -m "git lfs"
git push

**System environment**
Windows 11

**Output of `git lfs env`**
git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.32.0.windows.1

Endpoint=https://github.com/creacher-creolio/creacher-backend.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\jonkn\dev\creacher\creacher-backend
LocalGitDir=C:\Users\jonkn\dev\creacher\creacher-backend\.git
LocalGitStorageDir=C:\Users\jonkn\dev\creacher\creacher-backend\.git
LocalMediaDir=C:\Users\jonkn\dev\creacher\creacher-backend\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\jonkn\dev\creacher\creacher-backend\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\jonkn\dev\creacher\creacher-backend\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_ASKPASS=c:\Users\jonkn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
I think @KalleOlaviNiemitalo is correct here.  Apparently you can use a Dockerfile to build as well, which may allow you to install Git LFS in the container as part of the build process and run `git lfs pull` if you can get the credentials imported inside.

In any event, I don't think this is a bug in Git LFS.

**Comment by creolio** [comment]
Thank you!
