### ISSUE TITLE
git lfs fetch crash the system by stuck everything to ram

### ISSUE THREAD

**Issue by JoonSumisu** [git-lfs/git-lfs#5579]
**Describe the bug**
By using git lfs fetch for downloading those huge llm models, the git fetch/pull will keep stuck data into my ram, and at certain point, it will crash my pc. 

reinstall the git and git-lfs does not work

**To Reproduce**
cd to target folder
git lfs fetch
starting the download process
Downloading LFS objects:   0% (0/15), 25 MB | 5.7 MB/s   
0/15 won't change but the data size keeps increasing
ram usage increasing
when the usage took all my 64g ram, the system crashed and rebooted

**Expected behavior**
download normally as usual

**System environment**
WSL2 Ubuntu

**Output of `git lfs env`**
git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)
git version 2.34.1

Endpoint=https://www.modelscope.cn/TigerResearch/tigerbot-70b-chat-v2.git/info/lfs (auth=none)
LocalWorkingDir=/home/racia/ai/text-generation-webui/models/tigerbot-70b-chat-v2
LocalGitDir=/home/racia/ai/text-generation-webui/models/tigerbot-70b-chat-v2/.git
LocalGitStorageDir=/home/racia/ai/text-generation-webui/models/tigerbot-70b-chat-v2/.git
LocalMediaDir=/home/racia/ai/text-generation-webui/models/tigerbot-70b-chat-v2/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/racia/ai/text-generation-webui/models/tigerbot-70b-chat-v2/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/racia/ai/text-generation-webui/models/tigerbot-70b-chat-v2/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

We haven't heard back from you on this, so I'm going to close this.  If you can provide the information requested, we can reopen this issue.
