### ISSUE TITLE
gerrit lfs configuration of master-slave mode——It works fine on the master, but does not take effect on the slave.

### ISSUE THREAD

**Issue by gyrshining** [git-lfs/git-lfs#5582]
**Describe the issue**
I met a problem on gerrit lfs in master-slave environment.
The object has been successfully uploaded to S3 via master server, but fail to download it with the slave server:
Downloading pic2.jpg (202 KB)
Error downloading object: pic2.jpg (09bc75c): Smudge error: Error downloading pic2.jpg (09bc75c9aac30d55xxx): batch response: Repository or object not found: http://slave.cn/projectxxx/info/lfs/objects/batch
Check that it exists and that you have proper access to it

Errors logged to '/Users/xxx/workspace/gerrit-lfs/local/xxx/slave/common/.git/lfs/logs/20231128T201436.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: pic2.jpg: smudge filter lfs failed

I'm sure that my slave uses the same lfs storage as the master, however,  it works fine on the master, but does not take effect on the slave.
The specific configuration is as follows:

1、gerrit.config:
[lfs] 
        plugin = lfs

The only difference between the slave and the master is
 [container] 
    slave = true 

2、The content of my lfs.config is as below:
[storage]
    backend = s3
[s3]
    hostname = xxx.fds.xxx.net
    region = s3-cnbj.xxx-fds.net
    bucket = tv-lfs
    accessKey = xxxxxx
    secretKey = xxxxxx

3、The config of All-Projects:
[lfs "^.*"]
    enabled = true
    maxObjectSize = 900m

When I run command of "curl http://localhost:8088/a/projects/All-Projects/lfs:config-global -u admin:pwd", 
master says "{"default_backend_type":"S3","backends":{},"namespaces":{"^.*":{"enabled":true,"max_object_size":0,"read_only":false}}}", 
while slave says "Not Found". 

I wonder why the slave's lfs configuration does not work.

The slave cannot download any object on S3 unless I specify the lfs.url=master/project/info/lfs.

**System environment**
Linux version 4.4.0-64-generic (buildd@lgw01-56) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017

**Output of `git lfs env`**
git-lfs/3.1.1 (GitHub; linux amd64; go 1.17.6)
git version 2.30.1
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
When I run command of "curl http://localhost:8088/a/projects/All-Projects/lfs:config-global -u admin:pwd", master says "{"default_backend_type":"S3","backends":{},"namespaces":{"^.*":{"enabled":true,"max_object_size":0,"read_only":false}}}", while slave says "Not Found". I wonder why the slave's lfs configuration does not work.

The slave cannot download any object on S3 unless I specify the lfs.url=master/project/info/lfs.

**Comment by bk2204** [comment]
Hey,

This doesn't sound like a bug in Git LFS.  Git LFS knows nothing about Gerrit or any other particular server implementation, and it merely tries to connect to the requested host.  In this particular case, your object is not present on the second server, and you're getting a 404 as a response as a result.

Unfortunately, I don't use Gerrit, so it's not possible for me to assist here.  I might recommend contacting the Gerrit project through their preferred approach and asking how to configure this so it works in this environment.

**Comment by gyrshining** [comment]
Got it！Thanks for ur patient reply.
