### ISSUE TITLE
I cannot delete the files in LFS storage

### ISSUE THREAD

**Issue by mesut-unal** [git-lfs/git-lfs#5585]
**Describe the issue**
I tried LFS for the first time. I pushed more files than the quota (1.1/1.0 GB) that eventually prevents me to push my updates unless I pay for a premium plan. I don't need to fill up 1.0 GB, I want to empty the remote storage and push something smaller to LFS storage. I tried everything written on the documentation (bfg clean, migrate, cancel all the commits etc.), but I still see my LFS storage full. Now I cannot use my repository without deleting it entirely. What should I do? How can we delete the files on LFS storage? 

**System environment**
Mac Ventura 12.6.2.

**Output of `git lfs env`**
```
git-lfs/3.4.0 (GitHub; darwin arm64; go 1.20.6)
git version 2.39.3 (Apple Git-145)

Endpoint=https://github.com/mesut-unal/super_resolution_microscopy_viz.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/munal/Desktop/DNN_projects/super_resolution_microscopy_viz
LocalGitDir=/Users/munal/Desktop/DNN_projects/super_resolution_microscopy_viz/.git
LocalGitStorageDir=/Users/munal/Desktop/DNN_projects/super_resolution_microscopy_viz/.git
LocalMediaDir=/Users/munal/Desktop/DNN_projects/super_resolution_microscopy_viz/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/munal/Desktop/DNN_projects/super_resolution_microscopy_viz/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/munal/Desktop/DNN_projects/super_resolution_microscopy_viz/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  It looks like you are using GitHub as your Git LFS hosting service.  According to their [documentation](https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository), deleting the repository on their systems is the only way to reduce your storage use:

> After you remove files from Git LFS, the Git LFS objects still exist on the remote storage and will continue to count toward your Git LFS storage quota.
>
> To remove Git LFS objects from a repository, delete and recreate the repository.

If you have more questions, I'd suggest reaching out to GitHub's Support team for assistance, as this project is just for the open-source Git LFS client itself.
