### ISSUE TITLE
Linux installation instructions no longer works due to script not following http redirect

### ISSUE THREAD

**Issue by jesse-topcu** [git-lfs/git-lfs#5596]
**Describe the bug**
The instructions for installing on Linux have the command `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash` which includes a curl request to an apt config url with http protocol. This url is now returning http 301 redirect. The curl command in the script does not have the -L argument to follow the redirect which results in a malformed file on disk.

**To Reproduce**
1. Try to install using the installation instructions for Linux here https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md
2. Run apt-get install git-lfs
3. Error thrown:
```
E: Malformed line 1 in source list /etc/apt/sources.list.d/github_git-lfs.list (type)
E: The list of sources could not be read.
```

**Expected behavior**
git-lfs installs correctly

**System environment**
Ubuntu/jammy

**Output of `git lfs env`**
N/A

**Additional context**
N/A

**Comment by RobinDuhan** [comment]
Facing the same issue. Please update the file.

**Comment by chrisd8088** [comment]
This script is provided by Packagecloud for all customers and is not specific to Git LFS, and isn't something provided by this project.  For instance, https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh and https://packagecloud.io/install/repositories/Computology/packagecloud-test-packages/script.deb.sh are the same script, just with the package details differing.  They also mention this script in their [documentation](https://packagecloud.io/docs#unable_to_download_repo_config).

If there is a problem with the script, that's something which will affect multiple Packagecloud customers, and will need to be reported to their Support team.  I've passed the message on as best I can, but I would encourage others to do so as well.

As it's not something we can fix just for the Git LFS client, though, I'm going to close this issue.

**Comment by davidjb** [comment]
Facing the same issue; this breaks any builds that depend on it (like [CircleCI's base images](https://github.com/CircleCI-Public/cimg-base/blob/05b55933f03d402331a23d0bdc8713fda0825096/Dockerfile.template#L101)). I've emailed Packagecloud support about it - given how wide-reaching this is, hopefully a fix is forthcoming.

I also pointed out that installation instructions shown at pages https://packagecloud.io/github/git-lfs for both Debian and RPM both display curl commands that use `http://`. Piping to `sudo bash` is a security concern at the best of times, but piping an insecure web request is just asking for trouble from a MITM attack.

Just for note, changing to `curl -L` isn't the solution to the original issue as this just perpetuates the man-in-the-middle vulnerability when used with a `http://` URL. The script's URLs should all be updated to `https://` and ideally validate the downloaded file contents before proceeding.

**Comment by chrisd8088** [comment]
For reference, Packagecloud Support replied to me that they believe they have addressed the problem for all their customers by updating their common script and their documentation to both use `https://` URLs throughout.

**Comment by davidjb** [comment]
Echoing @chrisd8088's comments, they also replied to me with the same. I confirmed the online documentation (e.g. at https://packagecloud.io/github/git-lfs) and URLs in the scripts have been updated to https://, and the repo setup script runs successfully now (at least on Ubuntu).
