### ISSUE TITLE
Git push for LFS upload speed really slow 

### ISSUE THREAD

**Issue by UnsignedCoder** [git-lfs/git-lfs#5598]
**Describe the issue**
A clear and concise description of why you wrote in today.
I recently installed git lfs to use with unreal engine for version control and everything seems to work fine except when i try to push changes to the remote repo. once i push my upload speed is really slow about 20KBps to 30KBps. I have tried deleting and reinstalling, trying different networks, even reconfiguring my ssh even though i don't see why that could be a problem. I use a windows machine with unreal engine 5.2 and the latest release of both git and git lfs.

``` .gitattribute
Content/** filter=lfs diff=lfs merge=lfs -text
# UE file types
*.uasset filter=lfs diff=lfs merge=lfs -text
*.umap filter=lfs diff=lfs merge=lfs -text

# Raw Content types
*.fbx filter=lfs diff=lfs merge=lfs -text
*.3ds filter=lfs diff=lfs merge=lfs -text
*.psd filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.xcf filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
```

these are the files it is meant to track

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You didn't provide the output of `git lfs env` we ask for in the issue template, so we don't know what Git LFS hosting service you're trying to use, if any (GitLab?  GitHub?  Local Git LFS server?), or how your client is configured.  So if you can provide that output, plus the output of `git config -l` with any sensitive information redacted, that would be great.

You can also try your uploads with the `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` environment variables set, which should show you which requests are taking the most time.  You may need to investigate whether you have any kind of firewall or other security software which might interfere, as we [recommend against](https://github.com/git-lfs/git-lfs/blob/baf40ac99850a62fe98515175d52df5c513463ec/docs/man/git-lfs-faq.adoc#configuration) those.  Depending on what hosting service you're using, you may also need to investigate your connection speeds to their Git LFS object hosting service.

**Comment by UnsignedCoder** [comment]
Oh i'm sorry i use GItHub as my lfs hosting service and here is the git config output 

```
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=UnsignedCoder
user.email=<redacted>
safe.directory=D:/Unreal Projects/Shooter
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=<redacted>
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
lfs.repositoryformatversion=0
branch.master.remote=origin
branch.master.merge=refs/heads/master
 ESCOC

path=true

s

r

dCoder/Shooter-Project.git
emotes/origin/*

 ESCOD
core.symlinks=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=UnsignedCoder
user.email=<redacted>
safe.directory=D:/Unreal Projects/Shooter
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=<redacted>
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
lfs.repositoryformatversion=0
branch.master.remote=origin
branch.master.merge=refs/heads/master
 ESCOD
<redacted (repeated content)>
```

i used the command to see if there was something making it take an absurd amount of time but there doesn't seem to be and is just generally slow.


....well i just tried to push it again and suddenly its working fine, network speed picked up for some reason and i haven't changed a thing. I've been having this issue for close to two months and it just miraculously solves itself. At least i won't have to use SVN i really hate that thing

**Comment by chrisd8088** [comment]
> well i just tried to push it again and suddenly its working fine, network speed picked up for some reason

I'm glad things seem to be better.  I'll close this issue for now, but if the problem returns, I'd recommend looking at the output of a push command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` to see if you're seeing delays talking to GitHub or to AWS S3, which is where GitHub stores their LFS object data.

**Comment by UnsignedCoder** [comment]
Alrigjt thanks
