### ISSUE TITLE
batch request: bash: line 1: git-lfs-authenticate: command not found: exit status 127

### ISSUE THREAD

**Issue by kemin711** [git-lfs/git-lfs#5599]
**Describe the issue**
I have two identical servers running Ubuntu 22. One of the them I can host the shared git lfs without any problem. The other one shared (as server) can push and pull from the local git (git client on the same computer), but when doing cloning from a remote host, say foo, will emit the error stated on the title.  The only difference is that the one with the problem, does not have https port enabled.  The server without any problem, also had both http and https configured with apache2 for other purposes.

I spent several days, including the Christmas holiday and could not figure out where is the problem. Please give some hits as to whether it is server side or client side.  I check many internet hosting, the more I read the more I got confused.

**System environment**

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

On the server side:

```
git config -l
user.email=myuid@foobar.com
user.name=code writer
core.editor=vim
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
push.default=simple
credential.helper=cache
pull.rebase=false
lfs.contenttype=0
safe.directory=/home/git/testlfs
```

On the remote computer side:

CentOS Linux release 7.9.2009 (Core)

```
user.email=myuid@foobar.com
user.name=code writer
credential.helper=cache
pull.rebase=false
lfs.batch=false
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
safe.directory=*
```
All of the nodes are on a local network not exposed to the internet. So we tends to be relaxed on the security side.
The purpose is mainly for local software development on several computers.  

**Output of `git lfs env`**

On the computer served as server

```
git-lfs/3.4.1 (GitHub; linux amd64; go 1.20.11; git 0898dcbc)
git version 2.43.0.174.g055bb6e996

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

 On the remote (client side). Look identical to the server side.

```
git-lfs/3.4.1 (GitHub; linux amd64; go 1.20.11; git 0898dcbc)
git version 2.43.0.174.g055bb6e996

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Any other relevant context about the problem here.

The full output of the git clone:

```
 git clone git@colinger:testlfs
Cloning into 'testlfs'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (5/5), done.
Downloading component/molbar-1.8.0.tar.gz (4.2 MB)
Error downloading object: component/molbar-1.8.0.tar.gz (c865f8d): Smudge error: Error downloading component/molbar-1.8.0.tar.gz (c865f8d29a377ddfbf61a7d8e3b8249e36c96db9b9e318003f13dacd6b7979f4): batch request: bash: line 1: git-lfs-authenticate: command not found: exit status 127

Errors logged to '/prednet/home/keminz/tmp/testlfs/.git/lfs/logs/20231225T135942.75674702.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: component/molbar-1.8.0.tar.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  The `git-lfs-authenticate` command is what the Git LFS client requests the server to execute when it connects over SSH and the server has announced that doesn't support the pure-SSH Git LFS transfer protocol.  The `git-lfs-authenticate` command is expected to return an HTTP URL and some HTTP headers, which the Git LFS client will then use for all subsequent communication with the server.

You can read about this process in the [documentation](https://github.com/git-lfs/git-lfs/blob/baf40ac99850a62fe98515175d52df5c513463ec/docs/api/server-discovery.md#ssh).

As of Git LFS v3.0, before attempting the `git-lfs-authenticate` command, the client will first check to see if the server supports the pure-SSH Git LFS transfer protocol by asking the server to run the `git-lfs-transfer` command, as [described](https://github.com/git-lfs/git-lfs/blob/baf40ac99850a62fe98515175d52df5c513463ec/docs/proposals/ssh_adapter.md) in the proposal for that transfer protocol.

So the sequence is:
1. Git LFS client detects an SSH URL is configured, either from the Git remote's URL or from a specific Git LFS configuration directive like `lfs.url`.
2. The client connects to the server over SSH and requests the server run the `git-lfs-transfer` command.  If that succeeds, all subsequent communication is over SSH only, using the pure-SSH Git LFS transfer protocol.
3. However, if the server doesn't understand the `git-lfs-transfer` command, the client asks the server to run the `git-lfs-authenticate` command, expecting to get back an HTTP URL and set of HTTP headers it will then use for all subsequent communication with the server; no further SSH communication will occur.

You don't mention what Git LFS server-side hosting software you are trying to use, but if you want the Git LFS client to function, you'll need to have something running on the server that supports the Git LFS protocols.  You'll need to refer to that software's documentation for details on whether it supports any type of SSH communication.  There are a lot of different [implementations](https://github.com/git-lfs/git-lfs/wiki/Implementations) of Git LFS hosting software to choose from.

If you're trying to use the `lfs-test-server`, for instance, it doesn't support SSH at all, to my knowledge.  So you would need to allow the client to use HTTP for that service.  But other Git LFS service software supports at least the `git-lfs-authenticate` command, to let the client fall back to HTTP, and some supports the SSH-only Git LFS transfer protocol.  Again, you'll have to choose hosting software which meets your needs.  You say:

> The only difference is that the one with the problem, does not have https port enabled.

If you don't want the Git LFS client to use HTTP(S) at all, you'll need to choose some Git LFS hosting software that supports the pure-SSH transfer protocol (i.e., the `git-lfs-transfer` command) and can work without HTTP entirely.

As this doesn't appear to be a problem with the Git LFS client or its configuration, I'm going to close this issue, but if you are having a problem with the client, please re-open the issue and explain the issue.
