### ISSUE TITLE
t-credential.sh fails when building with lower level of parallelism

### ISSUE THREAD

**Issue by opohorel** [git-lfs/git-lfs#5609]
**Describe the bug**
When building the test suite with `make -C t PROVE_EXTRA_ARGS="-j40 -v"`, the tests pass. However, when turning the parallelism down to -j4, the t-credentials.sh fails consistently on test [13 - credentials with bad netrc creds will retry](https://github.com/git-lfs/git-lfs/blob/badde878a38fa2e37898ada0cbb007e7d6bb118b/t/t-credentials.sh#L457)

**To Reproduce**
1. make tests with `make -C t PROVE_EXTRA_ARGS="-j4 -v"`
2. see how they fail

**Expected behavior**
Passing test suit, same as when running with `-j40`

This issue occurred, when building git-lfs for CentOS Stream. We use `make -C t PROVE_EXTRA_ARGS="-j$(getconf _NPROCESSORS_ONLN) -v"` to get the number of physical cores present on the build system. When building in Koji, we can't see the issue, because by default we use -j40, however Zuul CI running on MR in our GitLab uses -j4, which then fails.
I was able to reproduce this locally in mockbuild environment. 

As I don't really know the test suite of git-lfs, I don't know what is the root cause of the problem.

**Comment by QuLogic** [comment]
I've noticed that `NETRCFILE` is set here:
https://github.com/git-lfs/git-lfs/blob/badde878a38fa2e37898ada0cbb007e7d6bb118b/t/t-credentials.sh#L341-L345
outside of any `begin_test`/`end_test` pair. This means it should be using `HOME` from the previous test, I think, and isn't updating for each one?

**Comment by bk2204** [comment]
Hey, thanks for the report, and my apologies about the delay in responding.  I can confirm this on my laptop.  Let me look into this a little more and see if I can figure out what's wrong.

**Comment by bk2204** [comment]
I've got #5616 opened to fix this test.

The `NETRCFILE` value is not related, because `$HOME` is consistent among a single test, so setting it once across the test should not be a problem.
