### ISSUE TITLE
File is in LFS and not at the same time

### ISSUE THREAD

**Issue by saltstack-admin** [git-lfs/git-lfs#5620]
**Describe the bug**
LFS does not find file, while it exists in the repository.

**To Reproduce**
1. Add new big file to repository
2. Use git add, commit and push to update the repository
3. Try to create Pull-Request, it ends in an error

**Expected behavior**
LFS works and allows me to create Pull-Requests.

**System environment**
- OS: AlmaLinux 9.2
- Git Version: git-2.39.3-1.el9_2.x86_64
- Git LFS Version: git-lfs-3.2.0-1.el9.x86_64
- SCM: Forgejo newest

**Output of `git lfs env`**
`08:35:54.852841 git.c:750               trace: exec: git-lfs env -- /var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/
08:35:54.852928 run-command.c:655       trace: run_command: git-lfs env -- /var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/
08:35:54.857907 trace git-lfs: exec: git 'version'
git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.9)
git version 2.39.3`

`08:35:54.862460 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'`
`08:35:54.867536 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'`
`08:35:54.870977 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir'`
`08:35:54.873376 trace git-lfs: exec: git 'config' '--includes' '-l'`
`08:35:54.875595 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'`
`08:35:54.880053 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'`
`08:35:54.882154 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'`
`Endpoint (remote_mirror_Redacted)=https://redacted/myorg/myrepo.git/info/lfs (auth=none)`
`Endpoint (remote_mirror_Redacted)=https://redacted/deployment2/myrepo.git/info/lfs (auth=none)`
`08:35:54.883916 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'`
`08:35:54.885766 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'`
`LocalWorkingDir=`
`LocalGitDir=/var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git`
`LocalGitStorageDir=/var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git`
`LocalMediaDir=/var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/lfs/objects`
`LocalReferenceDirs=`
`TempDir=/var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/lfs/tmp`
`ConcurrentTransfers=8`
`TusTransfers=false`
`BasicTransfersOnly=false`
`SkipDownloadErrors=false`
`FetchRecentAlways=false`
`FetchRecentRefsDays=7`
`FetchRecentCommitsDays=0`
`FetchRecentRefsIncludeRemotes=true`
`PruneOffsetDays=3`
`PruneVerifyRemoteAlways=false`
`PruneRemoteName=origin`
`LfsStorageDir=/var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/lfs`
`AccessDownload=none`
`AccessUpload=none`
`DownloadTransfers=basic,lfs-standalone-file,ssh`
`UploadTransfers=basic,lfs-standalone-file,ssh`
`GIT_CONFIG_PARAMETERS='protocol.version'='2' 'lfs.locksverify'='false' 'credential.helper'='' 'filter.lfs.required'='' 'filter.lfs.smudge'='' 'filter.lfs.clean'=''`
`GIT_CURL_VERBOSE=1`
`GIT_EXEC_PATH=/usr/libexec/git-core`
`GIT_TRACE=1`
`GIT_TRACE_PACKET=1`
`GIT_TRACE_PACKFILE=1`
`GIT_TRACE_PACK_ACCESS=1`
`GIT_TRACE_PERFORMANCE=1`
`GIT_TRACE_SETUP=1`
`GIT_TRACE_SHALLOW=1`
`GIT_TRANSFER_TRACE=1`
`git config filter.lfs.process = "git-lfs filter-process"`
`git config filter.lfs.smudge = ""`
`git config filter.lfs.clean = ""`
`08:35:54.887895 trace git-lfs: filepathfilter: creating pattern ".git" of type gitignore`
`08:35:54.887947 trace git-lfs: filepathfilter: creating pattern "**/.git" of type gitignore`
`08:35:54.888065 trace git-lfs: filepathfilter: accepting "tmp"`
`08:35:54.889367 trace.c:411             performance: 0.036917530 s: git command: /usr/bin/git -c protocol.version=2 -c lfs.locksverify=false -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= lfs env -- /var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/`

**Additional context**
With "git lfs fsck" I get this error:
`objects: openError: roles/myrole/files/mybigfile.bin (eb664590a4156fe9d837c8999dda396d2caecfd73bf4405b39b00b58ff1cd090) could not be checked: no such file or directory`
`objects: repair: moving corrupt objects to /var/local/lib/forgejo/data/forgejo-repositories/myorg/myrepo.git/lfs/bad`

Nothing can be found in the directory "bad".

I contacted the Forgejo devs beforehand, but there was no additional help after I did the update:
https://codeberg.org/forgejo/forgejo/issues/2096#issuecomment-1418482

**Comment by bk2204** [comment]
Hey,

Sorry you're having trouble.  Are you trying to use Git LFS on the backend storage of Forgejo?  If so, that probably isn't going to work.  The reason is that in a local repository, the Git data is stored under `.git/lfs`, but most forges don't have the LFS objects stored there and store them elsewhere instea.  You'd need to clone the repository through the forge first.

If you're using a separate clone, can you specify the `git lfs env` data, the OS information, and the results of your attempt to push with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` before the command?

**Comment by saltstack-admin** [comment]
Hello,
I don't understand, I already gave the output of "git lfs env" in the opening post.

**Comment by bk2204** [comment]
It looks like from that output that you're running `git lfs env` on the Forgejo instance under `/var/local/lib/forgejo`.  As I mentioned, that sounds like the backend storage location for repositories Forgejo.  Is that accurate?

If it is, then I don't believe that's a repository you can use the Git LFS client on.  When you use the Git LFS client, the LFS data is stored under `.git/lfs`, but I don't know of any forge which uses that location for the Git LFS data.  Most of them store it differently and you have to use HTTP or SSH to access your repository correctly.

If you want to use the Git LFS client, then you need to do a separate clone from the Forgejo storage and work with that separately.  You also need to clone and push using the normal HTTP or SSH techniques and not directly from the repositories in `/var/local/lib/forgejo`.

**Comment by saltstack-admin** [comment]
Hi,

okay, I understood now what you meant.
In that case I am closing this issue, seems to be a problem from forgejo.
