### ISSUE TITLE
git-lfs-transfer.. oh bummer, no gzip?

### ISSUE THREAD

**Issue by axkibe** [git-lfs/git-lfs#5623]
**Describe the issue**
I just noticed there is no way for gzipped transfer of data?

IMO for downloads this is a large downgrade from https mode (for uploadds it always had to be verbatim if I recall correctly due to https limits in this regard), which in many cases may defeat any gains from using the SSH protocol.  

Could we please at least for downloads implement a comparable handshake where the client says on the get-object requst what coding it will accept and the server choses then its favorite from that?

I suggest an argument like accept-encoding for the get-object e.g. accept-encoding=identity,gzip request and encoding=[identity|gzip] for the reply. If none are present both would assume identity for backward compatibility

For now I guess I gonna stop my git-lfs-transfer project here, because any gains by reusing the ssh connection via control master would be eaten up by verbatim transport instead of gzip as is the standard on https (not only network, but server cpu as well, I store all objects as gzip)

**Comment by bk2204** [comment]
Hey,

This should already be possible as `GIT_SSH_COMMAND=`ssh -c``, which makes the entire protocol compressed.  That provides the equivalent of gzip encoding if both sides support it.  We could add an option to pass `-oCompression=yes` if the user is using something compatible with OpenSSH, though.

Note that while your particular data may compress well, that isn't guaranteed in general.  For example, lots of people store things like images in Git LFS, and those are usually already compressed.  Thus, it's really up to the user to determine whether their data is likely to compress well.

I'm not opposed to an extension to the protocol that supports per-object compression, but I'm not likely to get to it anytime soon.  You're welcome to open a pull request for a proposal, and once it's implemented in Scutiger as the reference implementation, we can implement it in the client as well.

**Comment by axkibe** [comment]
GIT_SSH_COMMAND=ssh -c

Oh I see, that is a sensible rational. (Double compressing would be stupid).

About images, I know, I compress everything by default, since big gain on some files, and little loss on others, and with https on serverside not my issue, that way I can just stream it "verbatim" (as in the way it stored in disk). But yes an implementation that would check which is smaller and then use the smaller version.

PS: In https protocol mode I noticed the git client optionally turning on gzip for the whole protocol after a certain request size.. which was an issue back then after the first repo got enough branches for it to trigger and I didn't yet know how to handle it and the git protocol offered me no option to tell the client not to.

**Comment by axkibe** [comment]
Anyway, I will go with the ssh -c route. makes a lot of sense. Thanks!
And with that i even get compressed uploads something https was never able to :)
