### ISSUE TITLE
Timing for release v3.5.0?

### ISSUE THREAD

**Issue by ashmckenzie** [git-lfs/git-lfs#5627]
Hello from GitLab 👋🙂

Am hoping you might be able to share your thoughts @chrisd8088, @bk2204 on when v3.5.0 might be released? More accurately, when the PRs from https://github.com/git-lfs/git-lfs/pulls?q=is%3Apr+author%3AKyleFromKitware will make it into a release, presumably v.3.5.0?

Thanks in advance! ❤️

**Comment by bk2204** [comment]
We haven't discussed such a timeline, but I expect it will be soon, since you're not the first person to request this.  #5630 absolutely has to merge first because we can't sign Windows binaries without that, but I think we can do a release relatively shortly after that.

**Comment by ashmckenzie** [comment]
Thanks both for the update and of course the excellent work 👍

**Comment by bk2204** [comment]
Our _tentative_ plan is to do a release Wednesday, February 28.

**Comment by chenrui333** [comment]
@bk2204 looks like the tag got created, but the release did not get made, any reason why? Thanks!

<img width="510" alt="image" src="https://github.com/git-lfs/git-lfs/assets/1580956/64a30300-9f0e-4454-a333-6fd165a482c3">

**Comment by chrisd8088** [comment]
> looks like the tag got created, but the release did not get made, any reason why? Thanks!

See the notes in https://github.com/git-lfs/git-lfs/pull/5660#issuecomment-1969919567.  There were unexpected changes to the Windows environment in the Actions runners on the day of release, which caused the release to not succeed fully.  We are expecting to release v3.5.1 shortly now that we've addressed those issues.

**Comment by chenrui333** [comment]
Got you, make sense.

**Comment by bk2204** [comment]
We've released v3.5.1, so I'm closing this.

**Comment by ashmckenzie** [comment]
Thank-you @bk2204, sorry I didn't close it earlier! 💜

**Comment by viceice** [comment]
what about the release notes for v3.5.0?

**Comment by bk2204** [comment]
The release notes are in the changelog, but unfortunately the release failed due to some of the assets not building.  Thus, the release of that version wasn't successful and we didn't provide a partial release.
