### ISSUE TITLE
fsck corrupt pointers exits with 0 code

### ISSUE THREAD

**Issue by unity-emilk** [git-lfs/git-lfs#5631]
**Describe the bug**
When running `git lfs fsck` in a repo with corrupt pointers, git lfs fsck exits with code 0, and the message:
```
pointer: unexpectedGitObject: "xyz" (treeish 49bf67e92368449330644dc5dd941127a12d0c56) should have been a pointer but was not
```

**To Reproduce**
1. In a repository with a file that should have been a pointer according to .gitattributes but is not
2. run `git lfs fsck`

**Expected behavior**
I would expect a non-zero exit code

**System environment**
MacOS 14.2.1
git version 2.39.2
git-lfs/3.4.1 (GitHub; darwin arm64; go 1.21.5)

**Output of `git lfs env`**
```
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/opt/homebrew/Cellar/git/2.39.2/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  I can't reproduce this, unfortunately; I tried the following shell script and it exits nonzero.  

```shell
#!/bin/sh -e

REPO="test-repo"

rm -fr "$REPO"
git init "$REPO"
cd "$REPO"
git lfs track '*.bin'
git add .gitattributes
echo abc >abc.bin
git add abc.bin
echo def >def.bin
git -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.smudge= add def.bin
git commit -m +
git lfs fsck HEAD
```

It also exits nonzero if I omit the `HEAD` and just run `git lfs fsck`.

My output looks like this:

```
% ./repro
Initialized empty Git repository in /tmp/user/1000/test-repo/.git/
Tracking "*.bin"
[dev (root-commit) 0b2f5ca] +
 3 files changed, 5 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 abc.bin
 create mode 100644 def.bin
pointer: unexpectedGitObject: "def.bin" (treeish 0b2f5cac47d7c51913c6ac83e6ad7a68d2df1aa7) should have been a pointer but was not
```

Can you help me understand more about the context that you're running this in?  Is there a repository that I can look at that triggers this for you, or maybe a shell script that shows the behaviour you see?

**Comment by unity-emilk** [comment]
My bad, this was an issue in my development environment, I'll close the issue.
