### ISSUE TITLE
Git push large files from local to remote (Azure web app) throw error: `json: cannot unmarshal string into Go value of type lfshttp.ClientError`

### ISSUE THREAD

**Issue by mstxsun** [git-lfs/git-lfs#5640]
**Describe the issue**
Git push large files from local to remote (Azure web app) throw error as below:
`batch response: Unable to parse HTTP response for POST https://lfstestapp.scm.azurewebsites.net:443/lfstestapp.git/info/lfs/objects/batch: json: cannot unmarshal string into Go value of type lfshttp.ClientError
error: failed to push some refs to 'https://lfstestapp.scm.azurewebsites.net:443/lfstestapp.git'`

How to reproduce: 
1. Create an Azure webapp, then select local git in deployment center which will create a simple git server on it.
2. Run git clone on the URL created by webapp. 
3. Then run code: 
     1) git lfs install
     2) git lfs track "*.zip"
     3) git add .gitattributes
     4) git add file.zip
     5) git commit -m "Add design file"
     6) git push origin master

and the error mentioned above shown  

**System environment**
Local env: Microsoft Windows 11 Enterprise 10.0.22631 N/A Build 22631
Remote env: Microsoft Windows NT 10.0.20348.0

**Output of `git lfs env`**
git-lfs/3.4.1 (GitHub; windows amd64; go 1.20.11; git 0898dcbc)
git version 2.43.0.windows.1

Endpoint=https://lfstestapp.scm.azurewebsites.net:443/lfstestapp.git/info/lfs (auth=basic)
LocalWorkingDir=C:\test\lfstestapp
LocalGitDir=C:\test\lfstestapp\.git
LocalGitStorageDir=C:\test\lfstestapp\.git
LocalMediaDir=C:\test\lfstestapp\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\test\lfstestapp\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\test\lfstestapp\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
I understand you guys may for client only, but could you guys please provide insights about why this error `json: cannot unmarshal string into Go value of type lfshttp.ClientError` 
is thrown if you guys have any, thanks

**Comment by bk2204** [comment]
Hey,

It's almost certainly the case that the remote server simply doesn't support Git LFS.  The client is attempting to push LFS data and it's getting back a response that doesn't provide a JSON body with error information.  Git LFS expects that if the batch API fails, there's a JSON response that includes at least the `message` key.

If you want to see what's being sent and received, you can run the client with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and you can see the HTTP request and response headers and bodies.  This will likely indicate that the response isn't a JSON response at all, which would mean the server didn't support Git LFS.
