### ISSUE TITLE
Proposal: Add a --safe option to LFS prune

### ISSUE THREAD

**Issue by jochenhz** [git-lfs/git-lfs#5642]
**Describe the issue**
My motivation:
While working on https://github.com/git-lfs/git-lfs/pull/5637 I figured that prune is not secure enough for our use cases. Our git client is used by game developers, so the LFS cache is (force) pruned very regularly to significantly reduce the size of the project folder. This is necessary for git (LFS) to be a valid competitor to e.g. perforce.
The one thing that version control must prevent is data loss, and git LFS prune may be very destructive as it does not take the reflog or indexed files into account, for example. Beside https://github.com/git-lfs/git-lfs/pull/5637, there is also this open issue https://github.com/git-lfs/git-lfs/issues/4593.

My proposal:
In this commit https://github.com/Anchorpoint-Software/git-lfs/commit/749af8b50063ad0642bcf8ccdfda0fbb52c461b4 I've added a `--safe` option to LFS prune that only prunes objects that are 100% on the remote server. So in contrast to `--verify-remote`, `--safe` does not exit if a file is not available on the remote and orphan commits and indexed files are not pruned.

I am curious to hear what you think about this?

**Comment by bk2204** [comment]
Hey,

I think such a feature is useful and welcome.  I would say that I don't love the name `--safe` and might call this feature `--verify-continue` or some such, but I'm interested to hear what @chrisd8088 thinks, since he's often better at naming things than I am.

**Comment by chrisd8088** [comment]
I'd agree such a feature addition would be valuable.  We should add a matching configuration option to the `lfs.pruneVerifyRemoteAlways` setting as well, to be consistent with how `--verify-remote` is implemented.

My own instinct, FWIW, might be to add an option (and config setting) which requires `--verify-remote` or `lfs.pruneVerifyRemoteAlways` to be set, and then controls whether or not to [exit](https://github.com/git-lfs/git-lfs/blob/195fff823fecdcbd950942b8cc838bcd0c48015e/commands/command_prune.go#L245-L247) when a problem is detected.

I'm not great with naming things either, and I've struggled to come up with anything that's both succinct and self-explanatory in this case, where I think we're trying to express, "When there are locally prunable objects, and some can be verified to exist on the remote, but others can not, either prune nothing, or prune only the objects that were verified to exist on the remote."  Which is quite a mouthful.

Thinking about the configuration setting first, all I came up with is something like `lfs.pruneVerifyRemoteRequireZeroUnverified` or `lfs.pruneVerifyRemoteRequireNoUnverified`, or maybe one of those without the `VerifyRemote` part.  (The default setting would be `true`, to match the current behaviour of `lfs.pruneVerifyRemoteAlways`.)

For the command-line options, those configuration settings might translate as something like `--verify-remote --require-zero-unverified`; so you'd say `--verify-remote --[no]-require-zero-unverified` , with the `--no-require-zero-unverified` providing the new "safe" behaviour.  I find that unsatisfyingly verbose, though.

The only other thing I came up with was `--when-unverified=halt|continue`, with `halt` the default and `continue` the new behaviour.

I'm not sure if any of that is very helpful.

**Comment by bk2204** [comment]
I think there should be a separate option to control whether we delete unreachable objects as well instead of overloading it with the new option.  So we'd have `--verify-unreachable` in addition.

**Comment by jochenhz** [comment]
I like that!
if these improvements are desired, I can work on a pull request

**Comment by bk2204** [comment]
I think these improvements are very much desired and we'd be delighted if you wanted to work on them.
