### ISSUE TITLE
Some tests are functionally disabled due to `if $TRAVIS`

### ISSUE THREAD

**Issue by bk2204** [git-lfs/git-lfs#5658]
We have some tests in our testsuite that are functionally disabled because they run `if $TRAVIS`, which is always true if the `TRAVIS` environment variable is not set (fun shell fact!).  Many of these deal with our TLS certificate handling, and they are broken in CI for various reasons depending on the OS.

We should probably investigate what's wrong and how to fix it, since these tests are never run unless `TRAVIS` is set to a shell command returning false.  I should note that at least some of them pass on my Ubuntu 23.10 laptop, so simply reproducing on Linux is not sufficient to trigger the problem.

**Comment by chrisd8088** [comment]
I've discovered that `if $TRAVIS` problem myself in the past and have a stale set of updates to the test suite to remove the variable, but it's been about 18 months since I looked at it, so let me dust that off.

**Comment by bk2204** [comment]
I had discovered it in the past as well and tried to open a PR (#5615), but got distracted with other things after everything got angry and red.  I very much appreciate any assistance you can offer here.

I anticipated you might inquire about it in #5657, which adds a more abbreviated adjacent test, so I thought I'd document it so we didn't lose track of it in the PR comments.

**Comment by Elhazinforever** [comment]
Thanks I would like to thank you for supporting actually I appreciate small things but you did little not as friend or brother this important date to me and personally hope others people respect personal even behind you thanks keep always behind me as I can destroy all websites for don’t imagine it’s hard to explain even I feel you are my spying on me every wear but all respect im straight person but after anger and more disturbing I disappear then big bub………… for proudly of his badness person support me don’t be like manager of your site

**Comment by Elhazinforever** [comment]
But prices is high some people need do some work urgently but prices so high example me every time i find idea start making it stop in middle you need to pay money no have now your project did  every time and they take money from visiting the website so reduce payment and hosting more visitors ✌🏻
