### ISSUE TITLE
Wrong PUT Host IP

### ISSUE THREAD

**Issue by Mezo1234-beep** [git-lfs/git-lfs#5663]
Hello,

I have a physical server that hosts Gitea and is assigned an IP address, making it accessible from anywhere. However, it does not have HTTPS configured. I've configured a new Git project and added LFS files, and everything appears to be in order until I attempt to push my first commit containing those LFS files.

it stuck with (no changes at all for over 7min):

> $ git push -u origin master
> Uploading LFS objects:   0% (0/299), 0 B | 0 B/s

After debugging with the following commands:

> `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push -u origin master`

Here's a portion of the log:

> ```
> 14:50:04.241579 trace git-lfs: xfer: adapter "basic" worker 0 finished job for "..."
> 14:50:04.241579 trace git-lfs: xfer: adapter "basic" worker 0 processing job for "..."
> 14:50:04.241579 trace git-lfs: tq: retrying object ...: LFS: Put "http://localhost:3000/....git/info/lfs/objects/...": dial tcp [::1]:3000: connectex: No connection could be made because the target machine actively refused it.
> 14:50:04.241579 trace git-lfs: tq: enqueue retry #1 after 0.25s for "..." (size: 22621900)
> 14:50:04.242091 trace git-lfs: HTTP: PUT http://localhost:3000/....git/info/lfs/objects/...
> > PUT /....git/info/lfs/objects/... HTTP/1.1
> > Host: localhost:3000
> > Authorization: Basic * * * * *
> > Content-Length: 21786205
> > Content-Type: text/plain; charset=utf-8
> > User-Agent: git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)
> ```

As you can see, the Host is set to localhost instead of the actual IP address.

Here are my .git configurations:

> ```
> [core]
> 	repositoryformatversion = 0
> 	filemode = false
> 	bare = false
> 	logallrefupdates = true
> 	symlinks = false
> 	ignorecase = true
> [remote "origin"]
> 	url = http://IP:3000/....git
> 	fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "master"]
> 	remote = origin
> 	merge = refs/heads/master
> [lfs]
> 	repositoryformatversion = 0
> 	timeout = 30
> 	url = http://IP:3000/....git/info/lfs
> 
> [lfs "http://IP:3000/....git/info/lfs"]
> 	access = basic
> 	locksverify = true
> ```

Here's the environment configuration:

> ```
> $ git lfs env
> git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)
> git version 2.43.0.windows.1
> 
> Endpoint=http://IP:3000/....git/info/lfs (auth=basic)
> LocalWorkingDir=...
> LocalGitDir=...
> LocalGitStorageDir=...
> LocalMediaDir=...
> LocalReferenceDirs=
> TempDir=...
> ConcurrentTransfers=8
> TusTransfers=false
> BasicTransfersOnly=false
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> LfsStorageDir=...
> AccessDownload=basic
> AccessUpload=basic
> DownloadTransfers=basic,lfs-standalone-file,ssh
> UploadTransfers=basic,lfs-standalone-file,ssh
> GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"
> ```

Lastly, the Gitea version is 1.13.0, and Go version is 1.15.5 **(Server Side)**.
**Note: Git itself works flawlessly with any other repositories that do not contain LFS files.**
So, what is the issue, and is it originating from my local PC or the remote server? How can I resolve it?

**Comment by bk2204** [comment]
Git LFS, unlike Git, uses multiple requests to upload and download objects.  These are managed via the batch API, which takes a request that indicates which objects are to be uploaded or downloaded and returns URLs appropriate for doing so.  However, that requires that the server know what hostname and port to put in the URL.

In your particular case, you need to configure Gitea appropriately so that it puts the proper hostname in the URL, which would be a server-side configuration.  I'm unsure how to do so, though, so you'll probably need to look through the documentation to figure out how.

**Comment by Patronics** [comment]
@Mouaz-Alnouri did you find the fix to configure this for Gitea? I'm running into a similar issue with Forgejo (a fork of Gitea), where the server is accessible on multiple networks with different IP addresses, and the client is being given the wrong one.
