### ISSUE TITLE
Any news on ssh/sftp support ?

### ISSUE THREAD

**Issue by lapinott** [git-lfs/git-lfs#5664]
Is ssh/sftp support in the works ? I'd love to see support for it.

**Comment by bk2204** [comment]
Git LFS already supports SSH using the hybrid protocol (where authentication happens over SSH but transfers happen over HTTPS) and the pure SSH protocol (where everything happens over SSH).  However, some forges, such as GitHub, only currently support the hybrid protocol.  If you want to know what a particular forge is planning to do, you should reach out to them to ask.

As for SFTP support, we have no intention of supporting it directly, although you can use SSHFS to mount an SFTP remote as a local file system and then work with the remote repository as a local remote.  The reason SFTP isn't planned is that there are easy workarounds using SSHFS and it's extremely difficult to implement efficiently in the typical forge, since every access to the remote must be checked, instead of checking access once at the beginning of the operation.

**Comment by lapinott** [comment]
Hello, thank you for your quick reply. I have my own server for hosting git repositories. I just posted my issue here : https://serverfault.com/questions/1155467/git-lfs-is-giving-me-a-locking-api-error-when-i-try-to-push-to-the-server

When pushing I get the following error message:

batch request: missing protocol: "<unknown>"/s

Any fix welcome.

**Comment by bk2204** [comment]
If you're using Git LFS with the pure SSH protocol (which you will want to if you're not running a separate forge), you'll need a `git-lfs-transfer` binary on the server side, such as from [Scutiger](https://github.com/bk2204/scutiger), which is our reference implementation.  With a suitable version of Rust on the server, you should be able to built it with `cargo install scutiger-lfs`.

But I think this error message indicate that your URL isn't of the correct form.  In `ssh://<...>:/<path..>/test_repo`, you don't want the second colon.  You can either use a format like `bk2204@example.com:/srv/scm/git/foobar` or you can use `ssh://bk2204@example.com/srv/scm/git/foobar`, but if you use the URL syntax, the separator is a slash and not a colon.

**Comment by lapinott** [comment]
I modified the url, the error is now:

> batch request: bash: line 1: git-lfs-authenticate: command not found: exit status 127

**Comment by bk2204** [comment]
You can run the command with `GIT_TRACE=1` to see the output, because it sounds like you're failing to use the pure SSH protocol and things are falling back to the hybrid protocol.  That's probably because you don't have the required `git-lfs-transfer` binary in `PATH` on the server; that is necessary for it to work.

**Comment by lapinott** [comment]
> You can run the command with GIT_TRACE=1
How do I do that in Windows Powershell ?

> That's probably because you don't have the required git-lfs-transfer binary
How do I install it ? My server is running under Debian bookworm and I can't find no `git-lfs-transfer` package in apt.

**Comment by bk2204** [comment]
> > You can run the command with GIT_TRACE=1
> 
> How do I do that in Windows Powershell ?

In Git Bash, you add an environment variable to a command by prepending the command with it, so something like this: `GIT_TRACE=1 git push origin main`.  I'm not sure how you do that in PowerShell, but [this article seems to explain it](https://stackoverflow.com/questions/714877/setting-windows-powershell-environment-variables).

> > That's probably because you don't have the required git-lfs-transfer binary
> 
> How do I install it ? My server is running under Debian bookworm and I can't find no `git-lfs-transfer` package in apt.

It's not packaged for Debian.  As I mentioned above, you'll need to install Rust (which, on Debian, would be the `rustc` and `cargo` packages) and then run `cargo install scutiger-lfs`.  You can specify `--root` to install it in a given location (e.g., with root access, `/usr/local`).

**Comment by lapinott** [comment]
Hello,

So I installed `scutiger-lfs` with `cargo install scutiger-lfs`. This installs the `git-lfs-transfer` binary, *not* the `git-lfs-authenticate` binary!

When I push, I get the same error message. With `GIT_TRACE=1`:

> 13:06:08.674132 trace git-lfs: run_command: ssh <host...> git-lfs-authenticate <path...> upload
> 13:06:08.676003 trace git-lfs: exec: ssh '<host...>' 'git-lfs-authenticate <path...> upload'
> 13:06:09.341149 trace git-lfs: ssh: <host...> failed, error: exit status 127, message: bash: line 1: *git-lfs-authenticate: command not found* (try: .../6)

The `git-lfs-authenticate` binary doesn't exist on the server, how do I install it ?

If I look into `~/.cargo/bin`, there is the `git-lfs-transfer` there (I added a link to it in `/usr/bin`.

Thanks for any info.

**Comment by bk2204** [comment]
Okay, so what does `ssh user@host git-lfs-transfer /path/to/repo upload` print?  Note that you'll need to replace the `user@host` and `/path/to/repo` with the proper values.

**Comment by bk2204** [comment]
Okay, that looks correct.  The process is spawning and announcing its version, which is expected.

Does it also work for you if you run it as `ssh -oControlMaster=auto -oControlPath=C:\Users\jumat\AppData\Local\Temp\sock-1403213111\sock-%C user@host git-lfs-transfer /path/to/repo upload`?  In addition, are you using the Git for Windows OpenSSH or the Windows OpenSSH?

**Comment by lapinott** [comment]
I am using git bash right now so I can easily push env. variables. I don't know what ssh binary git bash uses. But that's just for the sample commands you gave me here.

Generally speaking I use the ssh shipped with Windows using PowerShell or the old Cmd.

The command you just gave me gives the same output:

> 000eversion=1
> 0000
> 
> 
> 
> malformed or unknown pkt-line header

**Comment by bk2204** [comment]
Okay, all of that seems normal.  There's something going wrong with running the process on the remote side that's getting an EOF.  I've opened #5674 to improve the logging here, and when CI is done, a set of Windows binary builds (labeled `windows-latest`) will appear [on the Actions page](https://github.com/git-lfs/git-lfs/actions/runs/8195166376).  You should download it, take the binary for your architecture (not the `-windows` one), and place it in a place you have access to.  For now, let's assume that's `C:\Users\bk2204\git-lfs-x64.exe`.

Then, in Git Bash, I want you to switch into your repository and run `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE_PACKET=1 /c/Users/bk2204/git-lfs-x64.exe push --all`.  That is, you're going to take the absolute path to your binary, you're going to change the `C:\` to `/c/`, and change all the backslashes to slashes, and use that.  Then include the output here.

That will include some additional logging which will tell us what output we're getting from the remote side.

**Comment by lapinott** [comment]
I will do that on monday. Can I download `windows-latest` already ?

**Comment by bk2204** [comment]
> I will do that on monday. Can I download `windows-latest` already ?

Yes, that archive is available now.

**Comment by lapinott** [comment]
Hello, sorry I am late.

I had to slightly modify the command you gave me and it actually worked this time!

Command used (executed in git bash on Windows 11):

`$ GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE_PACKET=1 /c/usr/local/bin/git-lfs-x64.exe push origin master --all`

Output:

> $ GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE_PACKET=1 /c/usr/local/bin/git-lfs-x64.exe push origin master --all
> 12:39:49.737459 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
> 12:39:49.832533 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
> 12:39:49.847032 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
> 12:39:49.860572 trace git-lfs: exec: git 'config' '--includes' '-l'
> 12:39:49.874484 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
> 12:39:49.888015 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
> 12:39:49.905040 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
> 12:39:49.920222 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir'
> 12:39:49.932879 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
> 12:39:49.945361 trace git-lfs: attempting pure SSH protocol connection
> 12:39:49.945361 trace git-lfs: spawning pure SSH connection
> 12:39:49.945361 trace git-lfs: run_command: ssh debian@turtlespeak.net git-lfs-transfer /home/debian/test_repo upload
> 12:39:49.946562 trace git-lfs: exec: ssh 'debian@turtlespeak.net' 'git-lfs-transfer /home/debian/test_repo upload'
> 12:39:50.651458 trace git-lfs: packet 00 < version=1
> 12:39:50.652594 trace git-lfs: packet 00 < 0000
> 12:39:50.652594 trace git-lfs: packet 00 > version 1
> 12:39:50.652594 trace git-lfs: packet 00 > 0000
> 12:39:50.675403 trace git-lfs: packet 00 < status 200
> 12:39:50.675403 trace git-lfs: packet 00 < 0001
> 12:39:50.675403 trace git-lfs: packet 00 < 0000
> 12:39:50.675403 trace git-lfs: pure SSH connection successful
> 12:39:50.675951 trace git-lfs: Upload refs [master] to remote origin
> 12:39:50.676518 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
> 12:39:50.691614 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
> 12:39:50.706811 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' 'origin'
> 12:39:51.311877 trace git-lfs: tq: running as batched queue, batch size of 100
> 12:39:51.312410 trace git-lfs: run_command: git rev-list --objects --do-walk --stdin --
> 12:39:51.312410 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-list' '--objects' '--do-walk' '--stdin' '--'
> 12:39:51.315551 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'cat-file' '--batch-check'
> 12:39:51.317647 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
> 12:39:51.334840 trace git-lfs: tq: sending batch of size 2
> 12:39:51.334840 trace git-lfs: api: batch 2 files
> 12:39:51.334840 trace git-lfs: packet 00 > batch
> 12:39:51.334840 trace git-lfs: packet 00 > transfer=ssh
> 12:39:51.334840 trace git-lfs: packet 00 > hash-algo=sha256
> 12:39:51.334840 trace git-lfs: packet 00 > refname=refs/heads/master
> 12:39:51.334840 trace git-lfs: packet 00 > 0001
> 12:39:51.334840 trace git-lfs: packet 00 > 51a3c67bf504a08204c039edb9fc05412f8f336b3570fa4f0f410bde183deabf 41
> 12:39:51.334840 trace git-lfs: packet 00 > 654b93f61054e4ce90ed203bb8d556a6200d5f906cf3eca0620738d6dc18cbed 28
> 12:39:51.334840 trace git-lfs: packet 00 > 0000
> 12:39:51.359517 trace git-lfs: packet 00 < status 200
> 12:39:51.359517 trace git-lfs: packet 00 < 0001
> 12:39:51.360384 trace git-lfs: packet 00 < 51a3c67bf504a08204c039edb9fc05412f8f336b3570fa4f0f410bde183deabf 41 upload
> 12:39:51.360384 trace git-lfs: packet 00 < 654b93f61054e4ce90ed203bb8d556a6200d5f906cf3eca0620738d6dc18cbed 28 upload
> 12:39:51.360384 trace git-lfs: packet 00 < 0000
> 12:39:51.360384 trace git-lfs: tq: starting transfer adapter "ssh"
> 12:39:51.360384 trace git-lfs: xfer: adapter "ssh" Begin() with 1 workers
> 12:39:51.360384 trace git-lfs: xfer: adapter "ssh" started
> 12:39:51.360384 trace git-lfs: xfer: adapter "ssh" worker 0 starting
> 12:39:51.360384 trace git-lfs: xfer: adapter "ssh" worker 0 processing job for "51a3c67bf504a08204c039edb9fc05412f8f336b3570fa4f0f410bde183deabf"
> 12:39:51.364752 trace git-lfs: packet 00 > put-object 51a3c67bf504a08204c039edb9fc05412f8f336b3570fa4f0f410bde183deabf
> 12:39:51.364752 trace git-lfs: packet 00 > size=41
> 12:39:51.364752 trace git-lfs: packet 00 > 0001
> 12:39:51.365362 trace git-lfs: packet 00 > 0000
> 12:39:51.382960 trace git-lfs: packet 00 < status 200
> 12:39:51.382960 trace git-lfs: packet 00 < 0000
> 12:39:51.383745 trace git-lfs: packet 00 > verify-object 51a3c67bf504a08204c039edb9fc05412f8f336b3570fa4f0f410bde183deabf
> 12:39:51.383745 trace git-lfs: packet 00 > size=41
> 12:39:51.383745 trace git-lfs: packet 00 > 0000
> 12:39:51.424005 trace git-lfs: packet 00 < status 200
> 12:39:51.424005 trace git-lfs: packet 00 < 0000
> 12:39:51.424296 trace git-lfs: xfer: adapter "ssh" worker 0 finished job for "51a3c67bf504a08204c039edb9fc05412f8f336b3570fa4f0f410bde183deabf"
> 12:39:51.424296 trace git-lfs: xfer: adapter "ssh" worker 0 processing job for "654b93f61054e4ce90ed203bb8d556a6200d5f906cf3eca0620738d6dc18cbed"
> 12:39:51.429077 trace git-lfs: packet 00 > put-object 654b93f61054e4ce90ed203bb8d556a6200d5f906cf3eca0620738d6dc18cbed
> 12:39:51.429077 trace git-lfs: packet 00 > size=28
> 12:39:51.429077 trace git-lfs: packet 00 > 0001
> 12:39:51.429077 trace git-lfs: packet 00 > 0000
> 12:39:51.461419 trace git-lfs: packet 00 < status 200
> 12:39:51.461419 trace git-lfs: packet 00 < 0000
> 12:39:51.461419 trace git-lfs: packet 00 > verify-object 654b93f61054e4ce90ed203bb8d556a6200d5f906cf3eca0620738d6dc18cbed
> 12:39:51.461419 trace git-lfs: packet 00 > size=28
> 12:39:51.461419 trace git-lfs: packet 00 > 0000
> 12:39:51.480537 trace git-lfs: packet 00 < status 200
> 12:39:51.480537 trace git-lfs: packet 00 < 0000
> 12:39:51.480537 trace git-lfs: xfer: adapter "ssh" worker 0 finished job for "654b93f61054e4ce90ed203bb8d556a6200d5f906cf3eca0620738d6dc18cbed"
> 12:39:51.480537 trace git-lfs: xfer: adapter "ssh" End()
> 12:39:51.480537 trace git-lfs: xfer: adapter "ssh" worker 0 stopping
> 12:39:51.480537 trace git-lfs: xfer: adapter "ssh" stopped
> 12:39:51.480537 trace git-lfs: shutting down pure SSH connection
> 12:39:51.480537 trace git-lfs: terminating pure SSH connection (1 -> 0)
> 12:39:51.480537 trace git-lfs: packet 00 > quit
> 12:39:51.480537 trace git-lfs: packet 00 > 0000
> 12:39:51.513973 trace git-lfs: packet 00 < status 200
> 12:39:51.513973 trace git-lfs: packet 00 < 0000
> Uploading LFS objects: 100% (2/2), 69 B | 0 B/s, done.
> 12:39:51.524971 trace git-lfs: filepathfilter: creating pattern ".git" of type gitignore
> 12:39:51.525096 trace git-lfs: filepathfilter: creating pattern "**/.git" of type gitignore
> 12:39:51.525633 trace git-lfs: filepathfilter: accepting "tmp"

**Comment by bk2204** [comment]
Okay, then that means that this is probably somehow fixed in a newer version, probably v3.5.1, which was just released.  I'm not sure why it wouldn't have been working in an older version, since I'm not aware of anything missing in v3.3.0 that should cause this to fail to work.

You can try upgrading to the latest Git for Windows, which should have v3.4.0, which may solve your problem.  If not, you can instead reinstall that version of Git for Windows without Git LFS, and then install Git LFS [using the installer from the v3.5.1 release assets page](https://github.com/git-lfs/git-lfs/releases).  Note that if you don't disable the use of Git LFS when you install Git for Windows, you'll end up with the Git for Windows version and the version you've installed directly won't be used.

**Comment by lapinott** [comment]
Just a quick note : git lfs doesn't use the same convention with git for `ssh://` paths.

Git accepts a semicolon (`:`) before the path, git lfs doesn't.

For example I would add a remote with git as : `git remote add origin ssh://user@host:/path/to/repo`. So far so good.

Then if I start tracking some files locally with git lfs, I can't push/pull to the repo anymore. I have to edit the `.git/config` file and edit the path to the repo there, i.e. remove the semicolon from the path. After that, git and git lfs are happy with it...

Just a little inconsistency I guess...

**Comment by lapinott** [comment]
I just checked rfc 3986 (https://www.rfc-editor.org/rfc/rfc3986#section-3.2.3) and the colon character is reserved to specify a **port** number. I don't know if an empty port is valid tho, as in `ssh://user@host:/some/path`.

**Comment by chrisd8088** [comment]
> Just a quick note : git lfs doesn't share the same convention with git for `ssh://` paths.
> Git accepts a <strike>semi</strike>colon (`:`) before the path component of the ssh url, git lfs doesn't.

That's likely related to the way Git LFS attempts to parse "bare" SSH connection strings and the oddities which arise from that, as described in #5184.  I'll make a note there of this issue as well.
