### ISSUE TITLE
`checkout` does not respect files which have been staged for removal with `git rm`

### ISSUE THREAD

**Issue by richard-fine** [git-lfs/git-lfs#5669]
**Describe the bug**
Using `git lfs checkout` to apply LFS files in a working copy where some LFS files have been removed with `git rm` incorrectly attempts to check out the removed files, failing because the pointer file is no longer present on disk.

**To Reproduce**
1. Clone a repository that uses LFS entries with `--skip-smudge` so that LFS files are not checked out.
2. Run `git lfs fetch` to acquire all LFS files into the local cache.
3. Stage one of the LFS pointer files for deletion using `git rm`.
4. Run `git lfs checkout`. Observe that the checkout reports an error about failing to check out the removed file.

**Expected behavior**
Git LFS should check out all LFS files corresponding to the pointer files present in the working copy, and should ignore files which have been staged for deletion with `git rm`.

**System environment**
Windows 11

**Output of `git lfs env`**
```
git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)
git version 2.43.0.windows.1

Endpoint=https://github.cds.internal.unity3d.com//unity/neutron.git/info/lfs (auth=none)
  SSH=git@github.cds.internal.unity3d.com:/unity/neutron.git
LocalWorkingDir=C:\UnitySrc\neutron
LocalGitDir=C:\UnitySrc\neutron\.git
LocalGitStorageDir=C:\UnitySrc\neutron\.git
LocalMediaDir=C:\UnitySrc\lfs\objects
LocalReferenceDirs=
TempDir=C:\UnitySrc\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\UnitySrc\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
My team is working on collectively resolving conflicts in a very large merge, which is why we have files that are staged for deletion but that cannot yet be committed. We'd like to be able to use `git lfs checkout` to check out the files that we have so far resolved, in order to use them in building/verifying parts of the codebase that we've resolved so far.

**Comment by bk2204** [comment]
Hey,

Thanks for the report, and apologies for the delay in responding.  I think what we want to do here is what `git checkout` does, and in that case, it does ignore the file, so I'd agree your proposed behaviour makes sense.

I have a patch, which you can see [here](https://github.com/git-lfs/git-lfs/compare/main...bk2204:git-lfs:checkout-ignore-missing?expand=1), but I have yet to write a test for it, which I hope to do next week.  However, I've provided it in case you're interested in building your own copy in the meantime.

**Comment by bk2204** [comment]
Okay, looking at this some more, it looks like we have specific tests that files which have been deleted manually (but are not staged for deletion) are replaced.  We'll need to preserve that behaviour, but change the behaviour for staged deletions.  It will therefore take me a little more time to sort through this, and I'll have to try another tactic.
