### ISSUE TITLE
Windows: runtime VirtualAlloc failed with Out Of Memory despite 20GB+ free commit & Physical RAM

### ISSUE THREAD

**Issue by liam-baker-sm** [git-lfs/git-lfs#5675]
**Describe the bug**
When performing a `git lfs fetch`, I receive a `fatal error: out of memory` despite having 90% free memory and commit, reasonable paged and nonpaged pool usage. In other words, there is absolutely no reason for the dynamic allocation to fail.

**To Reproduce**
1. Install git in a fresh Server 2022 AMI on AWS
2. Install git lfs
3. Clone a large repository (2 million objects, 1000+ branches, 11000 lfs objects)
4. Run the command `git lfs fetch --recent --prune`
5. See error with 22000 lines of text, staring with 
```
runtime: VirtualAlloc of 8192 bytes failed with errno=1455
   fatal error: out of memory

   runtime stack:
     runtime.throw({0xc514ff?, 0xc00197c000?})
             runtime/panic.go:1047 +0x65 fp=0xff59fff9f0 sp=0xff59fff9c0 pc=0x697aa5
     runtime.sysUsedOS(0xc00197c000, 0x2000)
             runtime/mem_windows.go:83 +0x1c5 fp=0xff59fffa50 sp=0xff59fff9f0 pc=0x678385
     runtime.sysUsed(0x10d51a0?, 0x2e9c1f9fe58?, 0xc000034100?)
             runtime/mem.go:77 +0x25 fp=0xff59fffa70 sp=0xff59fffa50 pc=0x677e85
     runtime.(*mheap).allocSpan(0x10d51a0, 0x1, 0x0, 0x63?)
             runtime/mheap.go:1340 +0x455 fp=0xff59fffb08 sp=0xff59fffa70 pc=0x6882f5
     runtime.(*mheap).alloc.func1()
             runtime/mheap.go:961 +0x65 fp=0xff59fffb50 sp=0xff59fffb08 pc=0x687ac5
     runtime.systemstack()
             runtime/asm_amd64.s:496 +0x48 fp=0xff59fffb58 sp=0xff59fffb50 pc=0x6c4fe8
```

**Expected behavior**
I expected files used in about 400 recent branches (last 7 days) to be downloaded to the reference repository.

**System environment**
The OS is Windows Server 2022 from an official AWS AMI. 
The repository is hosted on github enterprize 
The number of recent branches is about 400

```
PS C:\Users\Administrator> git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.longpaths=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
```

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
PS C:\Users\Administrator> git lfs env
git-lfs/3.4.1 (GitHub; windows amd64; go 1.20.11; git 0898dcbc)
git version 2.44.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
The reason I think this is a bug is the system had, according to Windows, 28GB of Available RAM.
I reran this command with the task manager open in a remote desktop session. I observed the memory use was stable for two hours at about 10% (or 3GB-3.5GB) of both Physical RAM and commit charge. These were the conditions reported in resource manager and Task Manager after a few hours running the command. The system has 32GB of RAM installed
![image](https://github.com/git-lfs/git-lfs/assets/137257416/13284758-3dc7-486b-b108-141eb2a4d0d8) 
Even after the error occurred, there was never a spike in physical memory or commit charge shown in the resource monitor.

What is odd `errno=1455` is a Windows error code for out of commit space (i.e. Windows Virtual memory), but I am nowhere near out of Virtual or Physical memory. Either there is heap corruption going on, msys2 is reporting the wrong error code, or this is some memory management bug specific to Windows Server 2022. 

![image](https://github.com/git-lfs/git-lfs/assets/137257416/78c40b82-e544-4954-91dd-712777c486a3)
Resource monitor just after I replicated the crash a second time. No spike shown in Physical or Commit memory.

**Comment by liam-baker-sm** [comment]
[Uploading lfs fetch error.txt…]()

**Comment by liam-baker-sm** [comment]
[lfs fetch error.txt](https://github.com/git-lfs/git-lfs/files/14535690/lfs.fetch.error.txt)
The full test of the error, about 23300 lines of go stack trace.
Note: this was running in powershell via `ansible.windows.win_command`

**Comment by Elhazinforever** [comment]
Hello third party at last seen who damaged my life and still all my family data you are such as fat pig

**Comment by liam-baker-sm** [comment]
After some more testing, it would appear that the root cause is a limit in WinRM.
https://github.com/ansible/ansible/issues/39327
