### ISSUE TITLE
macos-latest CI with latest Git is failing

### ISSUE THREAD

**Issue by bk2204** [git-lfs/git-lfs#5700]
Any of our recent attempts to run CI on the macos-latest target with the latest Git has caused the Git server to start crashing in some cases, which of course prevents the testsuite from running to completion.  It's not clear to me what the cause is, but I'll just note that this is the macOS build that uses SHA-256 repositories in case that's relevant.

I have occasionally seen cases where this test passes on a subsequent run, but it's not very frequent.

/cc @chrisd8088 as the core team member with an 🍎

**Comment by chrisd8088** [comment]
I haven't yet been able to reproduce this, at least on a local dev instance with a slightly older macOS version.  Will keep looking.

**Comment by chrisd8088** [comment]
So far I've narrowed down the culprit to a [test](https://github.com/git-lfs/git-lfs/blob/19a702e780c0ad93f0e02d9c96adbf5fd7da70bb/t/t-path.sh#L27-L147) we've had trouble with before, the `"does not look in current directory for git with credential helper"` test in `t/t-path.sh`.

It seems as though something about the temporary [creation](https://github.com/git-lfs/git-lfs/blob/19a702e780c0ad93f0e02d9c96adbf5fd7da70bb/t/t-path.sh#L82-L83) of a "fake Git", even though it's followed by an immediate removal, leads our `lfstest-gitserver` command, when it responds to the subsequent Git [push](https://github.com/git-lfs/git-lfs/blob/19a702e780c0ad93f0e02d9c96adbf5fd7da70bb/t/t-path.sh#L87), to get a non-response when it tries to [run](https://github.com/git-lfs/git-lfs/blob/19a702e780c0ad93f0e02d9c96adbf5fd7da70bb/t/cmd/lfstest-gitserver.go#L121-L122) `git http-backend`.  From the `remote/gitserver.log` file:
```
#    2024/04/09 23:06:12 [44042ae2-444d-3a6f-7309-160cba3f07f6] git http-backend POST /t-path-credentials/git-receive-pack
#    fatal: the remote end hung up unexpectedly
#    2024/04/09 23:06:12 exit status 1
```

Once the `lfstest-gitserver` has stopped, most subsequent tests and any ones running concurrently fail too.

**Comment by chrisd8088** [comment]
CI seems to be back to normal.  I suspect the issue here was outside our control, and some kind of security feature in GitHub Actions and/or macOS was detecting binaries (maybe unsigned binaries?) being sent to a socket over HTTP and shutting down the connection, so both sides just saw nothing, and then our `lfstest-gitserver` would, correctly, exit, causing most subsequent tests to fail.

That's purely a guess based on what I was seeing, but I'm inclined to close this and re-open it if the problem comes back.

**Comment by bk2204** [comment]
Yup, that seems appropriate.  I'll close this for now.
