### ISSUE TITLE
I can to connect my account Facebook admin page allowing public access all people see one public Facebook "share _like" a lot more than people

### ISSUE THREAD

**Issue by SMEY011** [git-lfs/git-lfs#5701]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This appears to be another off-topic issue.  This project has nothing to do with Facebook.  Please stop posting off-topic material to our issue tracker or other project fora.  If you don't, we'll block you.
