### ISSUE TITLE
<callback><?|&>amount=<amount_msats>

### ISSUE THREAD

**Issue by dav4545** [git-lfs/git-lfs#5713]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

It doesn't look like you've filled out the issue template with any information, so I'm going to close this.  If, in the future, you provide a helpful issue title and fill out the issue template, we can reopen this.
