### ISSUE TITLE
gitscanner_log Freezes When 'git log' Outputs to STDERR

### ISSUE THREAD

**Issue by jochenhz** [git-lfs/git-lfs#5720]
**Describe the bug**
The scanner defined in `gitscanner_log.go` freezes on `s.r.ReadString` if git log receives an error through stderr. This only happens on Windows and cannot be reproduced on macOS. I've tried to come up with a fix myself, but I am puzzled why this is happening, as I am not that familiar with go. My guess is that the stderr buffer of cmd is running full but I am not sure.

**To Reproduce**
Took me quite some time to come up with a 100% reproduction. I have created a shell script that creates a test repo on GitHub using the CLI and that creates a corrupted .gitattributes file so that an error is printed on git log. So far, we had 2 different users stumbling upon and reporting this issue, so I guess it might happen quite often. In essence, the script is doing the following:

1. Create a repo on GH and clone it
2. Create a .dat file and track it with LFS
3. Append many bad lines to the .gitattributes (to provoke a long stderr)
4. Push to GitHub
5. Invoke prune with some config (see attached shell script) and observe a freeze on Windows

See (and maybe run) attached [issue.sh](https://github.com/git-lfs/git-lfs/files/15041352/issue.sh.zip). Note: The script requires gh cli and will create and **delete** a test repository on your GitHub account.

**Expected behavior**
The script should not freeze, but print "prune done". Of course, this is user error due to a corrupted .gitattributes file being committed, but git LFS should not break because of this. Also, I guess there might be other scenarios where errors are printed on git log causing logscanner to freeze in LFS.

**System environment**
Windows 11

**Output of `git lfs env`**
```
git-lfs/3.4.1 (GitHub; windows amd64; go 1.20.11; git 0898dcbc)
git version 2.44.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
This sounds relatively familiar, since I think we've had a similar problem in the past.  I'm wondering if something like the code on [this branch](https://github.com/bk2204/git-lfs/tree/log-scanner-stderr) works for you.

I haven't run the reproduction script yet, and I'll soon be unavailable until about Wednesday, but since I won't be able to poke around on my Windows VM until then, I thought I'd offer a potential quick solution here.

**Comment by Foxsenrubas** [comment]
> **Опишите ошибку.** Сканер, определенный в `gitscanner_log.go`параметре, зависает, `s.r.ReadString`если git log получает ошибку через stderr. Это происходит только в Windows и не может быть воспроизведено в macOS. Я пытался найти решение самостоятельно, но не понимаю, почему это происходит, поскольку я не очень хорошо знаком с go. Я предполагаю, что буфер stderr cmd заполнен, но я не уверен.
> 
> **Воспроизведение** Мне потребовалось немало времени, чтобы добиться 100% воспроизведения. Я создал сценарий оболочки, который создает тестовый репозиторий на GitHub с помощью CLI и создает поврежденный файл .gitattributes, чтобы в журнале git печаталась ошибка. На данный момент у нас было два разных пользователя, которые столкнулись с этой проблемой и сообщили об этой проблеме, поэтому я думаю, что это может случаться довольно часто. По сути, скрипт делает следующее:
> 
> 1. Создайте репозиторий на GH и клонируйте его.
> 2. Создайте файл .dat и отслеживайте его с помощью LFS.
> 3. Добавьте много плохих строк в .gitattributes (чтобы спровоцировать длинный поток ошибок)
> 4. Отправить на GitHub
> 5. Вызовите prune с некоторой конфигурацией (см. прикрепленный сценарий оболочки) и наблюдайте зависание Windows.
> 
> См. (и, возможно, запустите) прикрепленный [файл Issue.sh](https://github.com/git-lfs/git-lfs/files/15041352/issue.sh.zip) . Примечание. Для сценария требуется gh cli, и он создаст и **удалит** тестовый репозиторий в вашей учетной записи GitHub.
> 
> **Ожидаемое поведение.** Сценарий не должен зависать, а печатать «обрезка выполнена». Конечно, это ошибка пользователя из-за фиксации поврежденного файла .gitattributes, но из-за этого git LFS не должен сломаться. Кроме того, я предполагаю, что могут быть и другие сценарии, когда ошибки печатаются в журнале git, что приводит к зависанию logscanner в LFS.
> 
> **Системная среда** Windows 11
> 
> **Выход`git lfs env`**
> 
> ```
> git-lfs/3.4.1 (GitHub; windows amd64; go 1.20.11; git 0898dcbc)
> git version 2.44.0.windows.1
> 
> LocalWorkingDir=
> LocalGitDir=
> LocalGitStorageDir=
> LocalMediaDir=lfs\objects
> LocalReferenceDirs=
> TempDir=lfs\tmp
> ConcurrentTransfers=8
> TusTransfers=false
> BasicTransfersOnly=false
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> LfsStorageDir=lfs
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic,lfs-standalone-file,ssh
> UploadTransfers=basic,lfs-standalone-file,ssh
> GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"
> ```

**Comment by Foxsenrubas** [comment]
git-lfs/3.4.1 (GitHub; windows amd64; go 1.20.11; git 0898dcbc)
git version 2.44.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
I've reproduced this successfully and I have a series that should fix the problem.

**Comment by jochenhz** [comment]
Nice! Thanks a lot for this very quick fix!
