### ISSUE TITLE
Big `.git` folder -- can we delete lfs objects without losing key functionality?

### ISSUE THREAD

**Issue by bbartoldson** [git-lfs/git-lfs#5725]
### Discussed in https://github.com/git-lfs/git-lfs/discussions/5294

I am using `git lfs pull` to download 40 TB of data from a remote repo, but I don't have space for the git lfs objects and the data (80 TB total because all the data gets duplicated in`.git/lfs/objects/*`). Is there a way to keep the data AND get the assurance that I have grabbed all the data from the repo (which I think `git lfs` provides) without permanently storing the files in `.git/lfs/objects/*`?

[Discussion 5294](https://github.com/git-lfs/git-lfs/discussions/5294) suggests that `git lfs dedup` could be another alternative to just deleting the lfs objects, but I am not sure if this deduplication can be applied progressively, which is needed for my use case (see below).

For example, currently I have 20 TB of data downloaded, and I am using 40 TB of disk space because of git lfs objects. I want to download the next 20 TB of data, but I will run out of disk space (I only have 50 TB of space total) in the process. My plan is to remove the git lfs objects for the existing data (or use `dedup`) to free up space for new data, but this introduces two concerns:

1. Once I have all the data and have deleted all their associated git lfs objects, will git be able to assure me that I have all the data downloaded? For example, I would hope that running `git restore --source=HEAD :/` would suggest that everything is downloaded. If not, then perhaps applying `dedup` after each object's download would work?
2. Will all of the data be usable without the associated git lfs objects? I know I may lose some git functionality by not having these objects, but I am only concerned about using the data and keeping git's ability to tell me that I have downloaded all the data. Here, `dedup` seems safer.

**Comment by bk2204** [comment]
Hey,

In general, you cannot just delete data from `.git/lfs/objects`.  In addition to the objects that are downloaded, we also store objects that have yet to be pushed there, and deleting that folder will delete them.  If you want to prune objects, you can use one of the `git lfs prune` options.

If you want to just check out the objects as if you were using `git lfs dedup`, you can set up the repository by cloning it with `GIT_LFS_SKIP_SMUDGE=1`.  You won't have the LFS objects until you run `git lfs pull`, at which point they should be written into the tree using copy-on-write if the system supports that (note that it does with APFS on macOS and btrfs on Linux, but not on NTFS or ext4).  That means that as long as you don't modify the contents of the working tree, only one copy of each files will be stored on the system.  If you do modify one or more files, then only those files should end up duplicated.

If you download the files and remove all of the stored Git LFS objects with `git lfs prune -f`, whatever's in the working tree will still be present and usable.  We won't have deleted anything unpushed and you should be able to manipulate the files as normal.
