### ISSUE TITLE
@technoweenie I think I may be misunderstanding something, because I would expect the command to be:

### ISSUE THREAD

**Issue by xuchys-jeffyP-gewvi0** [git-lfs/git-lfs#5733]
@technoweenie I think I may be misunderstanding something, because I would expect the command to be:

```
$ git lfs track "*.unity" --merge=unityyamlmerge
```

To then add in

```
*.unity filter=lfs diff=lfs merge=unityyamlmerge -text
```

?

Also, as strich said. Unity YAML scene files can 100mb or more. They are also files that the user does not really need to see inside of, on GitHub or other. So having them be treated as binary and put onto LFS may be a good idea.

What I was curious to know is. If I put a merge value on an entry which has filter=lfs. Does it know to merge the actual files, and not the text pointer files?

_Pubblicazione originale di @rygo6 su https://github.com/git-lfs/git-lfs/issues/604#issuecomment-140163665_

**Comment by chrisd8088** [comment]
This look to be an unhelpful contribution copied from an old issue.  If it this is a real concern, please open a new issue and fill out the requested information (`git lfs env`, etc.) and explain the problem in your own words, with a reproduction case.

In the meantime, I'm going to close this issue.

**Comment by xuchys-jeffyP-gewvi0** [comment]
@chrisd8088
