### ISSUE TITLE
fatal: active `post-checkout` hook found during `git clone`:

### ISSUE THREAD

**Issue by arch-btw** [git-lfs/git-lfs#5754]
Does anyone know how to fix this?

> fatal: active `post-checkout` hook found during `git clone`:

It's possible to disable the check completely but that would be a strange way to go about it.

**Comment by chrisd8088** [comment]
Thanks, @KalleOlaviNiemitalo -- that is indeed the known problem, introduced by a recent Git update, so I'm going to close this issue in favour of #5749.

As a short-term workaround while the Git project decides how to resolve the issue, you can use `GIT_CLONE_PROTECTION_ACTIVE=false`, but note that it disables the new defence-in-depth measures in Git.
