### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by noelportillo** [git-lfs/git-lfs#5780]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

Please also mention the usage of any proxy, including any TLS MITM device or non-default antivirus or firewall.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

If you're having problems trying to push or pull data, please run the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include it inline or attach it as a text file.  In a bash or other POSIX shell, you can simply prepend this string and a space to the command.

**Comment by bk2204** [comment]
Hey, it doesn't look like you've opened a helpful issue here.  Please refrain from opening test issues on this repository, and if you're experiencing a real issue, please fill out the issue template completely.  I'm going to close this.
