### ISSUE TITLE
[FEATURE REQUEST] Compression Flag

### ISSUE THREAD

**Issue by Malix-off** [git-lfs/git-lfs#5805]
# Feature Request

## Description

A Compression Flag with some options, for example:

- `.tar.xz`
- `.tar.gz`
- `.7z`
- `.zip`
- …

Also featuring a compression level option

**Comment by bk2204** [comment]
Hey,

What exactly is it that you want compressed?  The LFS blobs in the repository?  Archives containing LFS objects?  Something else?  Can you describe what you're looking for in more detail?

**Comment by Malix-off** [comment]
Hey @bk2204!

Sorry for the mislead,

What I think would be very interesting is to be able to easily compress and decompress files in the LFS objects in the remote storage

**Comment by bk2204** [comment]
So, to clarify, are you asking about transport compression (e.g., `Content-Encoding` or `Transfer-Encoding`), or are you wanting Git LFS to automatically compress files as part of the upload process?

**Comment by Malix-off** [comment]
@bk2204 I was originally thinking about a flag to compress files as part of the upload process, or maybe a documentation on how it is recommended to do so

_But transport compression is also interesting for sure_

**Comment by bk2204** [comment]
In general, creating archives for files on upload will make uploads pretty slow, in some cases very computationally expensive, and unreproducible, which we typically won't want to do.  In addition, many people store objects like Word documents, images, or textures in Git LFS, in addition to things that compress well, so in general, it's not safe to have one setting for all kinds of data.

I'm going to close this in favour of #260, which discusses storing data compressed in the `.git folder, but also discusses some other aspects of compression, and #5015, which discusses transport compression.  I think those are approaches that we could well implement and would perform adequately in many cases.

**Comment by Malix-off** [comment]
Sure!

Thanks for those redirect

Have a great day :heart:
