### ISSUE TITLE
pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF

### ISSUE THREAD

**Issue by fadhil-riyanto** [git-lfs/git-lfs#5820]
**Describe the issue**
HI everyone, I have issue.. I want to push pdfs file. the biggest is about 50 MB, when trying git push, my ssh asking several times repeadly
i was trying

`git config lfs.cachecredentials true`, `export GIT_LFS_SKIP_SMUDGE=1`, `export GIT_TRACE=1`

**System environment**
<pre>kernel: 6.9.6-arch1-1
archlinux x86_64</pre>

**Output of `git lfs env`**
<pre>
git-lfs/3.5.1 (GitHub; linux amd64; go 1.22.1)
git version 2.45.2

Endpoint=https://github.com/fadhil-riyanto/personal-books.git/info/lfs (auth=none)
  SSH=git@github.com:fadhil-riyanto/personal-books.git
LocalWorkingDir=/home/fadhil_riyanto/docs/personal-books
LocalGitDir=/home/fadhil_riyanto/docs/personal-books/.git
LocalGitStorageDir=/home/fadhil_riyanto/docs/personal-books/.git
LocalMediaDir=/home/fadhil_riyanto/docs/personal-books/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/fadhil_riyanto/docs/personal-books/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/fadhil_riyanto/docs/personal-books/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
GIT_TRACE=0
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""

</pre>

**Additional context**
here is git trace output
<pre>
23:51:10.235404 git.c:465               trace: built-in: git push
23:51:10.235990 run-command.c:657       trace: run_command: unset GIT_PREFIX; ssh git@github.com 'git-receive-pack '\''fadhil-riyanto/personal-books.git'\'''
Enter passphrase for key '/home/fadhil_riyanto/.ssh/id_ed25519':
23:51:16.990750 run-command.c:657       trace: run_command: .git/hooks/pre-push origin git@github.com:fadhil-riyanto/personal-books.git
23:51:16.996801 git.c:750               trace: exec: git-lfs pre-push origin git@github.com:fadhil-riyanto/personal-books.git
23:51:16.996940 run-command.c:657       trace: run_command: git-lfs pre-push origin git@github.com:fadhil-riyanto/personal-books.git
23:51:17.014574 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote' '-v'
23:51:17.017744 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
23:51:17.020882 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name'
'HEAD'
23:51:17.023426 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
23:51:17.026435 trace git-lfs: exec: git 'config' '--includes' '-l'
23:51:17.029264 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
23:51:17.032509 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
23:51:17.035420 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
23:51:17.039453 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir'
23:51:17.042388 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
23:51:17.045026 trace git-lfs: attempting pure SSH protocol connection
23:51:17.045045 trace git-lfs: spawning pure SSH connection
23:51:17.045092 trace git-lfs: run_command: ssh -oControlMaster=yes -oControlPath=/run/user/1000/sock-952345493/lfs.sock git@github.com git-lfs-transfer fadhil-riyanto/personal-books.git upload
23:51:17.045158 trace git-lfs: exec: ssh '-oControlMaster=yes' '-oControlPath=/run/user/1000/sock-952345493/lfs.sock' 'git@github.com' 'git-lfs-transfer fadhil-riyanto/personal-books.git upload'
Enter passphrase for key '/home/fadhil_riyanto/.ssh/id_ed25519':
23:51:30.038155 trace git-lfs: pure SSH connection successful
23:51:30.038191 trace git-lfs: pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF
23:51:30.038568 trace git-lfs: pre-push: refs/heads/master fe1caddeeff3f65383fe599064cf70107408e7a1 refs/heads/master ae92def1a97adb611db13032def210f6529f97b9
23:51:30.038712 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
23:51:30.041553 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' 'origin'
Enter passphrase for key '/home/fadhil_riyanto/.ssh/id_ed25519':
23:51:39.711162 trace git-lfs: attempting pure SSH protocol connection
23:51:39.711215 trace git-lfs: spawning pure SSH connection
23:51:39.711272 trace git-lfs: run_command: ssh -oControlMaster=yes -oControlPath=/run/user/1000/sock-2776935958/lfs.sock git@github.com git-lfs-transfer fadhil-riyanto/personal-books.git upload
23:51:39.711469 trace git-lfs: exec: ssh '-oControlMaster=yes' '-oControlPath=/run/user/1000/sock-2776935958/lfs.sock' 'git@github.com' 'git-lfs-transfer fadhil-riyanto/personal-books.git upload'
Enter passphrase for key '/home/fadhil_riyanto/.ssh/id_ed25519':
23:51:44.502622 trace git-lfs: filepathfilter: creating pattern ".git" of type gitignore
23:51:44.502750 trace git-lfs: filepathfilter: creating pattern "**/.git" of type gitignore
23:51:44.502900 trace git-lfs: filepathfilter: accepting "tmp"

Exiting because of "interrupt" signal.
</pre>

Thanks again for your time and effort

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You can reach out to GitHub Support for assistance, since you're using their Git LFS hosting service.  This project is for the open-source Git LFS client, so we can't always help with problems connecting to a given hosting service.

That said, the message you're reporting (`pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF`) is normal, in and of itself.  GitHub doesn't yet support the pure SSH version of the Git LFS protocols, so it declines the client's check to see if that is supported, and that's the message you'll see in the trace logs.  In fact, in a normal trace with an SSH GitHub remote you may see it twice.

Are you using a YubiKey or something of that nature?  One known issue with the Git LFS client, reported in #5784, pertains to the use of hardware authentication devices and repeated requests for credentials.

**Comment by fadhil-riyanto** [comment]
First, thanks for explaining the issue, I get it now. This is a hosting service issue and i was open the question on github discussion

Additional report: gitlab also has the same issue with ssh, but works if you use normal authentication. Anyway.. I never use Yubikey or smillar hardware authentication...
