### ISSUE TITLE
Impossible to control git-lfs setup on git clone process.

### ISSUE THREAD

**Issue by jmfrancois** [git-lfs/git-lfs#5827]
**Describe the bug**
I am using git-lfs on a repository in github. This feature is free under a certain limit. I have discovered today I have no way to restrict git-lfs to the CI as dev do not need to have access to the files in my use case.

Anyone with git-lfs installed who clone the repository will have the file fetched. And bandwidth is billed after a certain amount. I am sure this is not limited to github but to anyone with cloud provider behind to store the files.

**To Reproduce**
1. ensure you have git-lfs installed
2. git clone repository-with-git-lfs files
3. check the files are present and the hooks are setup
4. error: receive a bill because too many devs has clone your repository

**Expected behavior**

I know it reads the `.lfsconfig` file to get the possible remote-url so we should be able to add the env `GIT_LFS_SKIP_SMUDGE` in this file for example so we get the following expected workflow.

1. git clone repository
2. only pointers are here
3. git-lfs pull // to get the real files

**Comment by chrisd8088** [comment]
Hey, thanks for the suggestion.  By coincidence, I think this is almost exactly what was just proposed in #5825, so I'm going to close this issue in favour of that one.  If I'm mistaken, please re-open this issue, though!

**Comment by larsxschneider** [comment]
@jmfrancois Maybe I misunderstand your question... but wouldn't the following work for you?

```
$ git -c filter.lfs.process= -c filter.lfs.required= clone $REPO
$ cd $REPO_DIR
$ git lfs pull
```
