### ISSUE TITLE
filter-process initialization: strconv.ParseInt: parsing "\ufeff0": invalid syntax

### ISSUE THREAD

**Issue by lucianm** [git-lfs/git-lfs#5831]
Hello, I don't think this is a git lfs issue in the first place, but maybe somebody can help, or give some hint what I should try.

I want to make git-tfs (which is written in C# and based on LibGit2Sharp) LFS aware. I think I basically succeeded, with the help of a gist containing an implementation of a `git lfs process-filter` which only needs to be registered to LibGit2Sharp, then git and git-lfs would do what ever needs to be done (the process-filter is even spawned invisibly, performing whatever clean/smudge it's being told to do, depending on data flow direction, and all goes really well, as long I execute the commands manually in the console).

The trouble arises with the `git tfs rcheckin` command when scripted in the GitExtensions GUI, it would fail with the following console output, please observe the line coming from git-lfs process-filter, `filter-process initialization: strconv.ParseInt: parsing "\ufeff0": invalid syntax`:

```
"D:\Src\Git.OSS\_mine\git-tfs\src\GitTfs\bin\Debug\net48\git-tfs.exe" rcheckin
Found matching Visual Studio version at C:\Program Files\Microsoft Visual Studio\2022\Professional
Working with tfs remote: default => $/non-Product/Dev/Git-LFS_Testing_2
Fetching changes from TFS to minimize possibility of late conflict...
Starting checkin of e7fd5e1d 'added a copy of an already checked in *.raw file on git side'
LFSFilter Initialize
LFSFilter Create path = '.git\~w\PassThroughFilter.raw', root = 'D:\Src\Git-Tfs\Git-LFS_Testing_2\', mode = 'Smudge'
LFSFilter F E: reading filter-process initialization: strconv.ParseInt: parsing "\ufeff0": invalid syntax
LFSFilter Complete path = '.git\~w\PassThroughFilter.raw', root = 'D:\Src\Git-Tfs\Git-LFS_Testing_2\'
Sequence contains no elements
All the logs could be found in the log file: C:\Users\murelu9p\AppData\Local\git-tfs\git-tfs_log.txt
Done

Press Enter or Esc to close console...
```

What could be causing this?

For wondering about the `.git\~w` path, that's how git-tfs works, basically it always creates a temporary TFS workspace in that folder, in which it either checks out git commits to subsequently check them in to TFS, or the other way around, it fetches changesets from TFS in order to commit them to git.

My git-lfs env output:

```
$ git lfs env
git-lfs/3.5.1 (GitHub; windows amd64; go 1.21.7; git e237bb3a)
git version 2.45.2.windows.1

LocalWorkingDir=D:\Src\Git-Tfs\Git-LFS_Testing_2
LocalGitDir=D:\Src\Git-Tfs\Git-LFS_Testing_2\.git
LocalGitStorageDir=D:\Src\Git-Tfs\Git-LFS_Testing_2\.git
LocalMediaDir=D:\Src\Git-Tfs\Git-LFS_Testing_2\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\Src\Git-Tfs\Git-LFS_Testing_2\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\Src\Git-Tfs\Git-LFS_Testing_2\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_TFS_CLIENT=2022
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

For those interested in trying out the modified **git tfs**, [here is my fork](https://github.com/lucianm/git-tfs/commits/git-lfs/).

Below you can see how I "embedded" the command in the GitExtensions UI:

![2024-07-23 00_44_08-Settings - Scripts](https://github.com/user-attachments/assets/533794db-0415-4022-a52d-942c32daa16b)

**Comment by lucianm** [comment]
You @KalleOlaviNiemitalo my friend, saved me, I've been spending few hours with this, thank you very much!

**Comment by KinKiero** [comment]
Remove chat content 
 Byulling harrasment Phychycal abuse
Group' chat https://m.me/j/Abb5KdnEeJl2-8C_/

**Comment by KinKiero** [comment]
https://m.me/j/Abb5KdnEeJl2-8C_/

**Comment by KinKiero** [comment]
https://m.me/j/Abb5KdnEeJl2-8C_/

**Comment by KinKiero** [comment]
https://m.me/j/Abb5KdnEeJl2-8C_/
