### ISSUE TITLE
GitHub knows my public key but I can't use LFS, why?

### ISSUE THREAD

**Issue by stephane-archer** [git-lfs/git-lfs#5832]
```
git lfs push --all origin main
Uploading LFS objects:   0% (0/3), 0 B | 0 B/s, done.
batch request: git@github.com: Permission denied (publickey).: exit status 255
```
but
```
ssh -T git@github.com
Enter passphrase for key 'C:\Users\*****':
Hi stephane-archer! You've successfully authenticated, but GitHub does not provide shell access.
```
so GitHub knows my public key but I can't use LFS, why?

I'm on Windows and `git lfs push --all origin main` does not ask for my passphrase

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  As this project is just for the open-source Git LFS client, you may also want to contact GitHub's support team, as they can provide advice specific to GitHub's services.

That said, if you give us some more detail, we may be able to help.  See our "other issue" [template](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/.github/ISSUE_TEMPLATE/other-issue.md) for the things we usually ask for:

- The output of `git lfs env`, when run within the working tree of the repository you're using.
- The output of `git config -l` may be helpful as well; just make sure to remove any private information first.

I would also recommend providing the output (with any private information removed) when running your `git lfs push` command with the environment variables `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` set.

**Comment by chrisd8088** [comment]
As we haven't heard anything more regarding this issue, I'm going to close it, but if you're still having a problem we can help with, please re-open the issue and provide some of the details I mentioned above.

You might also want to take a look at some of the recent discussion in #5784, just in case the `lfs.ssh.autoMultiplex=false` setting would help you here too.

**Comment by war1025** [comment]
FYI the reason this happened for me is that cmd was using OpenSSH ssh.exe  and git was using mingw ssh.exe

Had to set: `git config --global core.sshCommand ...` to the path returned by `where ssh` 
I had to swap the direction of the slashes to get it to work.
