### ISSUE TITLE
error: external filter 'git-lfs filter-process' failed

### ISSUE THREAD

**Issue by x-o-i-o-x** [git-lfs/git-lfs#5837]
Hello everybody
I got an error trying to clone one of my github repositories (of a unreal engine project) from github using github desktop and got the error below.
The repository was set up using unreal engine and then uploaded to github with github desktop.
It uses LFS for ".uasset" and ".umap" files. In a previous project cloning worked just fine.
The Tutorial I used: [www.youtube.com/watch?v=n3x1fErlmYA](https://www.youtube.com/watch?v=n3x1fErlmYA)
Sorry if I ask this at the wrong place.
Help much appreciated!

```
Cloning into 'D:\UE_5.4_Projects\MultiplayerShooter'...
remote: Enumerating objects: 581, done.
remote: Counting objects: 100% (581/581), done.
remote: Compressing objects: 100% (559/559), done.
remote: Total 581 (delta 5), reused 580 (delta 4), pack-reused 0
Receiving objects: 100% (581/581), 75.51 KiB | 2.60 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Downloading Content/FPWeapon/Audio/FirstPersonTemplateWeaponFire02.uasset (306 KB)
Error downloading object: Content/FPWeapon/Audio/FirstPersonTemplateWeaponFire02.uasset (a795536): Smudge error: Error downloading Content/FPWeapon/Audio/FirstPersonTemplateWeaponFire02.uasset (a79553601bdadcb7f7430150268f8250e0a846feb8e1a9214c7a281dcbd2ec95): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'D:\UE_5.4_Projects\MultiplayerShooter.git\lfs\logs\20240730T193117.6573262.log'.
Use git lfs logs last to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/FPWeapon/Audio/FirstPersonTemplateWeaponFire02.uasset: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**System environment**
Windows 11
Github Desktop 3.4.2 (x64)
Git v2.45.2
Unreal Engine 5.4.3

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  The error reported here is:
```
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

That's from GitHub, which offers a certain amount of free Git LFS storage and bandwidth, and then bills for anything above those limits.  You'll need to contact GitHub Support to get help setting up an account and the appropriate billing details for it.  Their documentation also provide some information about their current and future Git LFS billing models:
- [About storage and bandwidth usage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage)
- [LFS to Metered Billing FAQ](https://github.com/orgs/community/discussions/61362)

As this project is just for the open-source Git LFS client, there's nothing we can do here, so I'm going to close this issue, but if you have a different problem, by all means open a new issue!  Thanks, and good luck!
