### ISSUE TITLE
How to get the actual file content or directory

### ISSUE THREAD

**Issue by wxfred** [git-lfs/git-lfs#5845]
I want to use git or git-lfs commands to get the file content like **git cat-file** dose. But with **git cat-file**, I only get the file pointer like below
```
version https://git-lfs.github.com/spec/v1
oid sha256:714190de04383bccb5d129f95580f457160cfdc661bd7490a353d2fcd73d8fbd
size 2455122
```

What I want is a command like
`git-lfs cat-file <hash>:<filename>`
return
`whole file content`

or

`git-lfs file-dir <hash>:<filename>`
return 
`C:\xxxxx\lfs\objects\71\41\714190de04383bccb5d129f95580f457160cfdc661bd7490a353d2fcd73d8fbd`

Any plan to add new api? Or is there already a command can do this?

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.

I think this is a similar issue to the one discussed in #2427, and as noted in https://github.com/git-lfs/git-lfs/issues/2427#issuecomment-541855829, one can use `git cat-file --filters <hash>:<filename>` to achieve your first objective of returning the smudged full file contents.  For example:

```
$ git init test
$ cd test
$ git lfs track '*.bin'
$ echo foo >foo.bin
$ git add foo.bin .gitattributes
$ git commit -m init

$ git cat-file -p HEAD:foo.bin
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4

$ git cat-file --filters HEAD:foo.bin
foo
```

So I'm inclined to close this issue as I think there's a simple way to achieve your goal, but if you disagree, we can leave it open for now.  Hope that helps!

**Comment by chrisd8088** [comment]
As for your secondary goal, I'd probably just do something like:
```
$ git cat-file -p HEAD:foo.bin | grep ^oid | sed -E 's#^oid sha256:((..)(..).*)$#.git/lfs/objects/\2/\3/\1#'
.git/lfs/objects/b5/bb/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
```

**Comment by wxfred** [comment]
> As for your secondary goal, I'd probably just do something like:
> 
> ```
> $ git cat-file -p HEAD:foo.bin | grep ^oid | sed -E 's#^oid sha256:((..)(..).*)$#.git/lfs/objects/\2/\3/\1#'
> .git/lfs/objects/b5/bb/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
> ```

Seems not work for windows

**Comment by wxfred** [comment]
I think use custom scripts to generate a directory is a temporary workaround, if the lfs rule is changed, suppose comes out a v2 like below
```
version https://git-lfs.github.com/spec/v2
oid sha256:714190de04383bccb5d129f95580f457160cfdc661bd7490a353d2fcd73d8fbd
size 2455122
```
and the file of this pointer is saving in `.git/lfs/v2/objects/71/41/90/de/714190de04383bccb5d129f95580f457160cfdc661bd7490a353d2fcd73d8fbd`

So, we need to change our command to fit all kinds of versions.

Maybe the git-lfs could provide a simple api because nobody knows the rule better than itself.

**Comment by chrisd8088** [comment]
In general, we discourage folks from trying to manage files in the internal Git LFS object cache directly, so I don't think we're going to make it a priority to provide tools which encourage people to examine or tinker with the cache directly.

If you have a specific use case you're trying to deal with by reading or writing files in the Git LFS object cache, I would suggest trying to find a way to avoid that approach, and if there's a gap in Git LFS's functionality which you are working around by reading the cache, writing up an issue which describes it in detail.

(Or, even better, creating a PR with a patch that implements the functionality you need plus some tests that verify the new behaviour.  We always appreciate such contributions!)

**Comment by wxfred** [comment]
Thanks for reply guys.
﻿
@KalleOlaviNiemitalo 
The  four-level directory sharding is just a example, it can be any format in the future if git lfs wants. And you mentioned that
`If the .git/lfs/ directory layout is ever changed, I expect the more likely reason is that Git LFS starts compressing the files there.`, so, using script to fetch the lfs file becomes more risky. Instead something like **git-lfs file-dir**, why not provide a **git-lfs cat-file** to extract the file content whatever the file is compressed or not or dynamic moved to other directories by git lfs.
﻿
@chrisd8088 
Hi, I'm writing a backend tool to fetch one single file managed by git lfs, and view it on web frontend, what is your recommand to do this? Using **git checkout** to move the file to a temporary directory, then read it, finally delete the temporary directory? I want the whole process simple and fast.

**Comment by chrisd8088** [comment]
> Hi, I'm writing a backend tool to fetch one single file managed by git lfs, and view it on web frontend, what is your recommand to do this? 

I don't know exactly what your requirements are here, but from what I gathered, I would think you might want to try cloning and/or checking out branches using `GIT_LFS_SKIP_SMUDGE=1`, to prevent Git LFS from fetching any objects, and then when you want to fetch a single Git LFS object, run `git lfs pull -I <path>` to fetch and smudge just the one file path into the working tree.

You might also investigate whether any of the other implementations of Git LFS might work for your purpose, maybe one [listed](https://github.com/git-lfs/git-lfs/wiki/Implementations) in the wiki.  Perhaps there's a library in your programming language of choice which can help you make a call to the Git LFS Batch API to [request](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/docs/api/batch.md#requests) the URL for a given object, and then you can parse the JSON [response](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/docs/api/batch.md#successful-responses) and make a second request to retrieve the Git LFS object data directly from the remote Git LFS storage host.  That's more work in one way, of course, but if you don't actually need a local copy of the Git repository at all, it might be cleaner.  (When you view a Git LFS object in the Web UI of various major hosting services, like GitHub, it likely works this way.)

**Comment by wxfred** [comment]
> I don't know exactly what your requirements are here, 

@chrisd8088 

I'm writing a git file viewer app, users can view the file content on website while the server is responsible for reading git files and send them to the browser. In the server side, i can invoke **git cat-file** in a nodejs child_process to get the normal file's content, but if the file is a git lfs file, I can only get a sha256 format file pointer.

All the file is managed by git (**bare** repository) in the local of server. It seems there is no URL i can get (maybe I'm not aware), so i'm wondering whether there is a git lfs command to get the local file path or directly get the local file content.

**Comment by chrisd8088** [comment]
In a bare repository, you can still use `git lfs fetch -I <path>` to fetch a specific Git LFS object file for a given file path.  You'd then need to read the file out of `lfs/objects` using the kind of filename manipulation I suggested in https://github.com/git-lfs/git-lfs/issues/5845#issuecomment-2299769802, but adjusted for whatever language or OS you're using.  Or you could just search in `lfs/objects` for a file with the name of the Git LFS OID.

As I said before, though, we're not likely to encourage people to read (or write) directly from the Git LFS cache like this by providing a command which gives you the internal cache path.  On the other hand, I think it's extremely unlikely these cache paths will change anytime in the foreseeable future, so you should be pretty safe figuring them out yourself.

But, that all said, I'll repeat what I suggested before, given that you're managing the Git content on an intermediate system already with some kind of server-side software.  Presumably your Node.js system fetches the Git content from some Git remote which also provides Git LFS hosting.  (If that's not how your program works, then I don't understand where you expect to get the Git LFS object contents from.)

I would recommend looking into whether you can just query the upstream remote's Git LFS Batch API with the Git LFS OIDs you want to retrieve, parse the JSON it sends back, and then make the individual HTTP requests to fetch the Git LFS content.  That's going to be fully supported since you would be using the public Git LFS Batch API specification, which is intended for this kind of purpose.
