### ISSUE TITLE
File not marked as read-only when unlocked while open during file locking

### ISSUE THREAD

**Issue by steamb23** [git-lfs/git-lfs#5852]
**Describe the bug**

We are considering managing MS Office documents such as Excel files in our Git repository within our team. However, we've noticed an issue: when we unlock a file while it's closed, it switches to read-only mode, but when we unlock a file while it's open, it doesn't switch to read-only mode.

When this situation occurs, even if we close the file and enter commands like `git pull`, `git fetch`, or `git lfs pull`, the file doesn't update to read-only mode.

As I have only tested this on Mac so far, I haven't been able to verify whether the same phenomenon occurs on Windows as well.

**To Reproduce**
1. Lock the file.
2. Open the file.
3. Unlock the file.
4. Close and reopen the file.
5. The file is not marked as read-only.

**Expected behavior**
When updating the local repository, such as by executing the `git pull` command, the file reading status should be refreshed.

**System environment**
```
git-lfs/3.5.1 (GitHub; darwin arm64; go 1.22.1)
```

config:
```
lfs.{Organization repository address}.locksverify=true
lfs.{Organization repository address}/info/lfs.access=basic
```

**Output of `git lfs env`**
```
git-lfs/3.5.1 (GitHub; darwin arm64; go 1.22.1)
git version 2.46.0

Endpoint={Organization repository address}/info/lfs (auth=basic)
LocalWorkingDir=/Users/steamb23/Documents/Repos/test-docs
LocalGitDir=/Users/steamb23/Documents/Repos/test-docs/.git
LocalGitStorageDir=/Users/steamb23/Documents/Repos/test-docs/.git
LocalMediaDir=/Users/steamb23/Documents/Repos/test-docs/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/steamb23/Documents/Repos/test-docs/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/steamb23/Documents/Repos/test-docs/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/opt/homebrew/opt/git/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by steamb23** [comment]
It seems there was an error during the test. I will conduct further testing and report back again.

**Comment by steamb23** [comment]
Sadly, I discovered that including Korean characters in file names causes malfunctions on Mac. It seems I need to test it again to confirm the mechanism and report the issue later. :(

**Comment by chrisd8088** [comment]
> Sadly, I discovered that including Korean characters in file names causes malfunctions on Mac. It seems I need to test it again to confirm the mechanism and report the issue later.

OK, thank you for investigating!  Let us know what you find, particularly if it appears to be a problem with the Git LFS client itself.
