### ISSUE TITLE
Othiss

### ISSUE THREAD

**Issue by ShineZaw123** [git-lfs/git-lfs#5853]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by chrisd8088** [comment]
This doesn't look like a useful report of an issue, so I'm going to close it, along with #5854 and PR #5855.  If there is a genuine problem, please fill out the report in full and re-open the issue.

As well, please refrain from opening any other spurious issues, PRs, or discussions, or we will have block your ability to contribute to this project in the future.
