### ISSUE TITLE
Crash during pure SSH object transfer with multiple objects

### ISSUE THREAD

**Issue by chrisd8088** [git-lfs/git-lfs#5880]
**Describe the bug**
When cloning a repository with multiple Git LFS objects using the "pure" SSH version of the Git LFS transfer [protocol](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/docs/proposals/ssh_adapter.md), the client may crash due to a `nil` pointer reference.

**To Reproduce**
To reproduce the behaviour we can use a modified version of the `batch transfers with ssh endpoint (git-lfs-transfer)` [test](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/t/t-batch-transfer.sh#L166-L192) in the `t/t-batch-transfer.sh` test script.

```shell
begin_test "batch transfers with ssh endpoint and multiple objects (git-lfs-transfer)"
(
  set -e

  setup_pure_ssh

  reponame="batch-ssh-transfer-multiple"
  setup_remote_repo "$reponame"
  clone_repo "$reponame" "$reponame"

  git lfs track "*.dat"
  printf "test1" >test1.dat
  printf "test2" >test2.dat
  git add .gitattributes test*.dat
  git commit -m "initial commit"

  sshurl=$(ssh_remote "$reponame")
  git config "lfs.url" "$sshurl"

  # this is required to avoid a bug with our lfs-ssh-echo.go utility
  git config "lfs.ssh.automultiplex" "false"

  git push origin main

  cd ..

  git clone "$sshurl" "$reponame-2"
)
end_test
```

Running this test script results in the following crash and stack trace:
```
Cloning into 'batch-ssh-transfer-multiple-2'...
Downloading test2.dat (5 B) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10307df04]

goroutine 86 [running]:
github.com/git-lfs/git-lfs/v3/ssh.(*PktlineConnection).Lock(...)
        github.com/git-lfs/git-lfs/v3/ssh/protocol.go:23
github.com/git-lfs/git-lfs/v3/tq.(*SSHBatchClient).batchInternal(0x14000569a30?, {0x14000510080, 0x3, 0x4}, {0x14000500240, 0x1, 0x1}) 
        github.com/git-lfs/git-lfs/v3/tq/ssh.go:32 +0x64
github.com/git-lfs/git-lfs/v3/tq.(*SSHBatchClient).Batch(0x140004226f0, {0x103895878?, 0x60?}, 0x140005481e0)
        github.com/git-lfs/git-lfs/v3/tq/ssh.go:66 +0x3bc
github.com/git-lfs/git-lfs/v3/tq.Batch({0x10339d9b8, 0x140000c1bc0}, 0x1, {0x14000206b60, 0x6}, 0x14000518300, {0x14000560008, 0x1, 0x1}) 
        github.com/git-lfs/git-lfs/v3/tq/api.go:45 +0x228
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0x1400052e100, {0x14000532708, 0x1, 0x0?})
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:581 +0x25c
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1()
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:470 +0x74
created by github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches in goroutine 85
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:463 +0x228
error: external filter 'git-lfs filter-process' failed
fatal: test2.dat: smudge filter lfs failed
```

**Expected behaviour**
All Git LFS objects should be cloned successfully.

**System environment**
The examples above were performed on macOS, but should behave the same way on any platform.

**Output of `git lfs env`**
```
git-lfs/3.5.0 (GitHub; darwin arm64; go 1.23.1; git 8b2882b7)
git version 2.46.0
```

Note that this is a custom build from the current `HEAD` of our `main` development branch, for the `3.5.x` release series.

**Additional context**
This crash may be one which prompted the development of PR #5063.

This problem may also be the source of the issue described in https://github.com/git-lfs/git-lfs/pull/5816#issuecomment-2207214023.

---

The issue appears to stem from the fact that we [shut down](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/transfer_queue.go#L974) our SSH connections when the `Wait()` method of our `TransferQueue` structure runs, and [set](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/transfer_queue.go#L975) the `SSHTransfer` field of the associated `Manifest` structure to `nil`, but a pointer to the same structure has been [saved](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/manifest.go#L250) in the `SSHBatchClient` structure in the manifest, and so when the manifest is [reissued](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/commands.go#L64-L69) by the `getTransferManifestOperationRemote()` function, there is still a non-`nil` reference to the `SSHTransfer` structure that now has a `nil` array of connections, and that is what is [used](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/api.go#L45-L51) for the next batch transfer operation.

Specifically, we [call](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/command_filter_process.go#L106-L111) `NewTransferQueue()` once when smudging in our `git lfs filter-process` command, and [pass](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/command_filter_process.go#L112) the transfer queue to our `infiniteTransferBuffer()` function.  To construct the `manifest` argument of `NewTransferQueue()`, we [call](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/command_filter_process.go#L108) `getTransferManifestOperationRemote()`, which constructs the `Manifest` for the first time.  

We subsequently also [call](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/command_filter_process.go#L131) the `smudge()` function, which also [calls](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/command_smudge.go#L128) `getTransferManifestOperationRemote()`.  That second call will return the existing `Manifest` object created by the previous call; however, at this point the `list_available_blobs` filter [command](https://github.com/git/git/blob/90fe3800b92a49173530828c0a17951abd30f0e1/Documentation/gitattributes.txt#L627-L648) has been received from Git, so we have [called](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/command_filter_process.go#L153) `Wait()` on the transfer queue.  That method, because the manifest has been upgraded to a concrete one with a non-`nil` `SSHTransfer` field, [calls](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/transfer_queue.go#L974) `Shutdown()` on that `SSHTransfer`, which [sets](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/ssh/connection.go#L200) the SSH connection count to zero, which results in the `conn` array being [set](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/ssh/connection.go#L192) to `nil`.

When the manifest is reused to process the batch of objects to be downloaded, `Connection(0)` is [called](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/ssh.go#L28) on the `SSHTransfer` structure pointed to by the `SSHBatchClient` structure, which [returns](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/ssh/connection.go#L103) `nil, nil` because zero is equal to `len(tr.conn)` when `tr.conn` is `nil`.  Since a `nil` is returned for the error value, no error is [reported](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/ssh.go#L29-L31) and instead the code tries to [call](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/tq/ssh.go#L32) `Lock()` on the `nil` pointer, which causes a panic condition.

---

One immediate corrective will be to return a non-`nil` error when `tr.conn` is `nil`.  (A wrinkle here is that we'll also need to rename the `tr` receiver variable to something else so it doesn't override our imported `tr` package name.)  That alone, however, will still result in a failed clone, just not due to a program crash.

Ultimately, we may want to avoid trying to shut down our SSH connections at the end of individual batch operations, and do some analysis of the preferred lifetime for them.  (Among other issues, when pushing, we create two separate `ControlMaster=yes` connections, one for locking operations and another for batch operations; it would be nice to avoid this duplication.)

Shutting down SSH connections cleanly at the end of the entire Git LFS process may also entail some refactoring of how we cause the program to exit.  Right now, we make a token effort at [closing](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/commands/run.go#L155) resources associated with our API clients, but really that just amounts to [closing](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/lfshttp/client.go#L205) our logger, and when we call `os.Exit()` in several dozen places, that step is skipped and we let Go take care of closing open I/O handles.  If we want to always gracefully close multiple open SSH connections by [sending](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/ssh/protocol.go#L39) a `quit` message, though, we may have to refactor these `os.Exit()` calls into a common exit routine.

**Comment by chrisd8088** [comment]
As a quick side note, the comment in the reproduction example test above which alludes to a bug in our `lfs-ssh-echo` program refers to the fact that when it is called with a `ControlMaster=no` argument, it fails to [open](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/t/cmd/lfs-ssh-echo.go#L84) the temporary file it expects to exist and exits with an error code.  This is due to the fact that when it is first called with a `ControlMaster=yes` argument, it [creates](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/t/cmd/lfs-ssh-echo.go#L76) the temporary file with file permissions of `0` instead of a more conventional value such as `0666`.  As a result, subsequent invocations are unable to open the file, even though it does exist.

We'll need to address this problem when we want to have a PR that introduces a working test to push and fetch multiple Git LFS objects over the SSH object transfer protocol.

**Comment by chrisd8088** [comment]
Solely for my own future benefit, I thought I'd draw up a loose diagram of how the different structures and interfaces involved in the SSH object transfer protocol are related to each other.  At the moment, these include:

- `tq.TransferQueue` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/transfer_queue.go#L184-L219)
- `tq.Adapter` [interface](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/transfer.go#L223-L253)
- `tq.adapterBase` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/adapterbase.go#L16-L35)
- `tq.transferImplementation` [interface](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/adapterbase.go#L37-L53)
- `tq.SSHAdapter` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/ssh.go#L151-L155)
- `ssh.SSHTransfer` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/ssh/connection.go#L16-L25)
- `ssh.PktlineConnection` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/ssh/protocol.go#L14-L20)
- `tq.Manifest` [interface](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/manifest.go#L20-L38)
- `tq.lazyManifest` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/manifest.go#L40-L46)
- `tq.concreteManifest` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/manifest.go#L129-L146)
- `lfsapi.Client` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/lfsapi/lfsapi.go#L13-L22)
- `tq.BatchClient` [interface](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/api.go#L54-L58)
- `tq.SSHBatchClient` [structure](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/tq/ssh.go#L22-L25)

This may need to be edited, of course, if my first draft isn't entirely accurate.  I've left out many details in the interest of trying to capture the principal functions of each component and the key relationships between them.

The main observation I wanted to highlight was that we [create](https://github.com/git-lfs/git-lfs/blob/df0afdd19eaf422651b6d131e4ae8a83f6399981/lfsapi/lfsapi.go#L52-L76) `ssh.SSHTransfer` structures in our `lfsapi` package using a method of the `lfsapi.Client` structure; however, we then reference those `SSHTransfer` structures through multiple structures of the `tq` package.  Ultimately, we end up with at least three references to each `SSHTransfer` structure, in the `SSHAdapter`, `concreteManifest`, and `SSHBatchClient` structures.

That's not necessarily a problem, but there may be other ways to manage the lifetimes of the underlying SSH connections which would arise from a refactoring of some of these packages.

```mermaid
classDiagram
class `tq.TransferQueue` {
    ~tq.Adapter adapter
    ~tq.Manifest manifest
}

class `tq.Adapter` {
    <<Interface>>
    +Name() string
    +Direction() Direction
    +Begin()
    +Add(...*Transfer transfers) TransferResult
    +End()
}

class `tq.adapterBase` {
    ~tq.transferImplementation transferImpl
    +Name() string
    +Direction() Direction
    +Begin()
    +Add(...*Transfer transfers) TransferResult
    +End()
}

class `tq.transferImplementation` {
    <<Interface>>
    +WorkerStarting(int workerNum)
    +WorkerEnding(int workerNum)
    +DoTransfer()
}

class `tq.SSHAdapter` {
    ~*ssh.SSHTransfer transfer
    +WorkerStarting(int workerNum)
    +WorkerEnding(int workerNum)
    +DoTransfer()
}

class `ssh.SSHTransfer` {
    ~string operation
    ~[]*PktlineConnection conn
    +Connection(int n) *ssh.PktlineConnection
    +ConnectionCount() int
    +SetConnectionCount(int n)
    +Shutdown()
}

class `ssh.PktlineConnection` {
    ~io.ReadCloser r
    ~io.WriteCloser w
    ~*subprocess.Cmd cmd
    +Start()
    +End()
    +SendMessage(string command, []string args)
    +ReadStatus() int
}

class `tq.Manifest` {
    <<Interface>>
    +APIClient() *lfsapi.Client
    +MaxRetries() int
    +NewAdapterOrDefault(name string, dir Direction) tq.Adapter
    +Upgrade() *tq.concreteManifest
    ~batchClient() tq.BatchClient
}

class `tq.lazyManifest` {
    ~*lfsapi.Client apiClient
    ~string operation
    ~string remote
    ~*concreteManifest m
    +APIClient() *lfsapi.Client
    +MaxRetries() int
    +NewAdapterOrDefault(name string, dir Direction) tq.Adapter
    +Upgrade() *tq.concreteManifest
    ~batchClient() tq.BatchClient
}

class `tq.concreteManifest` {
    ~*lfsapi.Client apiClient
    ~int maxRetries
    ~*ssh.SSHTransfer sshTransfer
    ~tq.BatchClient batchClientAdapter
    +APIClient() *lfsapi.Client
    +MaxRetries() int
    +NewAdapterOrDefault(name string, dir Direction) tq.Adapter
    +Upgrade() *tq.concreteManifest
    ~batchClient() tq.BatchClient
}

class `lfsapi.Client` {
    ~lfshttp.Context context
    +Context() lfshttp.Context
    +SSHTransfer(string operation, string remote) *ssh.SSHTransfer
}

class `tq.BatchClient` {
    <<Interface>>
    +Batch(string remote)
    +MaxRetries() int
    +SetMaxRetries(int n)
}

class `tq.SSHBatchClient` {
    ~int maxRetries
    ~*ssh.SSHTransfer transfer
    +Batch(string remote)
    +MaxRetries() int
    +SetMaxRetries(int n)
}

`tq.TransferQueue` *-- `tq.Adapter`
`tq.TransferQueue` *-- `tq.Manifest`
`tq.Adapter` <|.. `tq.adapterBase`
`tq.adapterBase` *-- `tq.transferImplementation`
`tq.transferImplementation` <|.. `tq.SSHAdapter`
`tq.SSHAdapter` *-- `tq.adapterBase`
`tq.SSHAdapter` <-- `ssh.SSHTransfer`
`ssh.SSHTransfer` *-- `ssh.PktlineConnection`
`tq.Manifest` <|.. `tq.lazyManifest`
`tq.Manifest` <|.. `tq.concreteManifest`
`tq.lazyManifest` <-- `lfsapi.Client`
`tq.lazyManifest` *-- `tq.concreteManifest`
`tq.concreteManifest` <-- `lfsapi.Client`
`tq.concreteManifest` <-- `ssh.SSHTransfer`
`tq.concreteManifest` *-- `tq.BatchClient`
`tq.BatchClient` <|.. `tq.SSHBatchClient`
`tq.SSHBatchClient` <-- `ssh.SSHTransfer`
```

**Comment by neris** [comment]
I'm actually getting this crash on my existing repositories after moving them to the pure SSH LFS protocol.
If someone has a workaround that would be great.

```
Cloning into 'XXXXX'...
remote: Enumerating objects: 6629, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6629 (delta 2), reused 0 (delta 0), pack-reused 6623 (from 1)
Receiving objects: 100% (6629/6629), 7.49 MiB | 4.41 MiB/s, done.
Resolving deltas: 100% (4792/4792), done.
Downloading YYYYY (1.7 MB)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0xe9bfd9]

goroutine 68 [running]:
github.com/git-lfs/git-lfs/v3/ssh.(*PktlineConnection).Lock(...)
        github.com/git-lfs/git-lfs/v3/ssh/protocol.go:23
github.com/git-lfs/git-lfs/v3/tq.(*SSHBatchClient).batchInternal(0xc000147a40?, {0xc00019a8c0, 0x3, 0x4}, {0xc000032b40, 0x1, 0x1})
        github.com/git-lfs/git-lfs/v3/tq/ssh.go:32 +0xb9
github.com/git-lfs/git-lfs/v3/tq.(*SSHBatchClient).Batch(0xc00002def0?, {0x60?, 0x60?}, 0xc00005bd40)
        github.com/git-lfs/git-lfs/v3/tq/ssh.go:66 +0x4d9
github.com/git-lfs/git-lfs/v3/tq.Batch({0x11822b8, 0xc00019ab00}, 0x1, {0xc0001f47a0, 0x6}, 0x1?, {0xc00004e090, 0x1, 0x1})
        github.com/git-lfs/git-lfs/v3/tq/api.go:45 +0x2b3
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc0003a2200, {0xc000333c00, 0x1, 0x0?})
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:581 +0x2fe
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1()
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:470 +0x85
created by github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches in goroutine 67
        github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:463 +0x29b
error: external filter 'git-lfs filter-process' failed
fatal: YYYYY: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```


```
>git lfs env
git-lfs/3.5.1 (GitHub; windows amd64; go 1.21.7; git e237bb3a)
git version 2.47.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_TRACE=0
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by Joexu76** [comment]
@neris I'm in a similar situation to you, please try to downgrade your git version to v2.46.2.windows.1.

**Comment by Joexu76** [comment]
I have encountered a little bit different situations, from GEO primary, normal git clone,  but secondary node fails,

**Secondary Node Error Message:**

> Cloning into 'xxxxxx'...
> remote: Enumerating objects: 692872, done.
> remote: Counting objects: 100% (1222/1222), done.
> remote: Compressing objects: 100% (446/446), done.
> remote: Total 692872 (delta 961), reused 916 (delta 736), pack-reused 691650 (from 1)
> Receiving objects: 100% (692872/692872), 9.40 GiB | 20.23 MiB/s, done.
> Resolving deltas: 100% (439353/439353), done.
> Updating files: 100% (204829/204829), done.
> Downloading qsdk/chroot_host/lib/libprotoc.a (94 MB)0 KiB/s s 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x847cd9]
> 
> goroutine 149 [running]:
> github.com/git-lfs/git-lfs/v3/ssh.(*PktlineConnection).Lock(...)
>         github.com/git-lfs/git-lfs/v3/ssh/protocol.go:23
> github.com/git-lfs/git-lfs/v3/tq.(*SSHBatchClient).batchInternal(0xc0005d1a40?, {0xc0005ba040, 0x3, 0x4}, {0xc0002141b0, 0x1, 0x1})
>         github.com/git-lfs/git-lfs/v3/tq/ssh.go:32 +0xb9
> github.com/git-lfs/git-lfs/v3/tq.(*SSHBatchClient).Batch(0xc000384060?, {0x60?, 0x60?}, 0xc0001ca540)
>         github.com/git-lfs/git-lfs/v3/tq/ssh.go:66 +0x4d9
> github.com/git-lfs/git-lfs/v3/tq.Batch({0xb48f10, 0xc00021f880}, 0x1, {0xc0002bc410, 0x6}, 0x1?, {0xc000554030, 0x1, 0x1})
>         github.com/git-lfs/git-lfs/v3/tq/api.go:45 +0x2b3
> github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc0002a4900, {0xc000151880, 0x1, 0xc00020f080?})
>         github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:581 +0x2fe
> github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1()
>         github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:470 +0x85
> created by github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches in goroutine 148
>         github.com/git-lfs/git-lfs/v3/tq/transfer_queue.go:463 +0x29b
> error: external filter 'git-lfs filter-process' failed
> fatal: qsdk/chroot_host/lib/libprotoc.a: smudge filter lfs failed
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

**Primary Node successed:**

> Cloning into 'xxxxxx'...
> remote: Enumerating objects: 692872, done.
> remote: Counting objects: 100% (1224/1224), done.
> remote: Compressing objects: 100% (460/460), done.
> remote: Total 692872 (delta 960), reused 869 (delta 724), pack-reused 691648 (from 1)
> Receiving objects: 100% (692872/692872), 9.46 GiB | 47.94 MiB/s, done.
> Resolving deltas: 100% (439170/439170), done.
> Updating files: 100% (204829/204829), done.
> Filtering content: 100% (1858/1858), 1.39 GiB | 9.95 MiB/s, done.

**Comment by chrisd8088** [comment]
For those watching this issue, I expect to have a draft PR soon which will address both the crash bug and the bug in our `lfs-ssh-echo` test utility, and do some other related cleanup work at the same time.  We'll include any such fixes in the next release, which we're expecting to make sometime in November.
