### ISSUE TITLE
Git LFS push. LFS: Client error  from HTTP 405

### ISSUE THREAD

**Issue by hugo-spp** [git-lfs/git-lfs#5899]
**Describe the issue**
I have set up GitLab using Docker on my NAS. Pulling and pushing for the project works normally. However, I encounter the following error when pushing LFS.
<img width="450" alt="Snipaste_2024-10-29_18-10-51" src="https://github.com/user-attachments/assets/d075e1e3-88bb-48a9-a72e-b7d621de3e5b">

**System environment**
Git's config file
<img width="496" alt="Snipaste_2024-10-29_18-15-37" src="https://github.com/user-attachments/assets/fdb93216-d8dc-416b-93b2-4d78ab84aafa">

**Output of `git lfs env`**
```
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.39.2.windows.1

Endpoint=https://192.168.100.155/unreal-project/unreal_test.git/info/lfs (auth=none)
  SSH=git@192.168.100.155:/unreal-project/unreal_test.git
LocalWorkingDir=D:\coding\Unreal\unreal_test
LocalGitDir=D:\coding\Unreal\unreal_test\.git
LocalGitStorageDir=D:\coding\Unreal\unreal_test\.git
LocalMediaDir=D:\coding\Unreal\unreal_test\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\coding\Unreal\unreal_test\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\coding\Unreal\unreal_test\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Could you run the following command in Git Bash: `GIT_TRACE=1 GIT_TRANSPORT_TRACE=1 GIT_CURL_VERBOSE=1 git push origin sq-Test10` and include the output here as a text file by including it as an attachment?  You should be able to redirect the output to a text file by adding something like ` 2>log.txt` to the end of the command and then dragging and dropping your `log.txt` into the issue comment box.  (It will be too voluminous and too hard to search to leave it as an image.)

It may also be useful to look at [this discussion](https://github.com/git-lfs/git-lfs/discussions/5190), which describes the same problem which a user had running GitLab in a Docker container.

**Comment by hugo-spp** [comment]
Yes, it's an issue with the LFS access port. Currently, I've solved it using port forwarding with OpenWrt. I'll see if I can change the startup port as you suggested. Thank you very much.

**Comment by hugo-spp** [comment]
It was caused by me forgetting to modify the port.
When configuring GitLab's configuration file (container location: `/etc/gitlab/gitlab.rb`), change the HTTP(S) port number to match the port number mapped out by Docker:
```
external_url 'IP:port'
```
Or modify the Nginx startup port:
```
nginx['listen_port'] = port
```
