### ISSUE TITLE
basictransfersonly seems to have disappeared

### ISSUE THREAD

**Issue by CoachRDeveloper** [git-lfs/git-lfs#5922]
**Describe the bug**
Setting lfs.basictransfersonly still allows batch requests

**To Reproduce**
1. git config basictransfersonly true
2. Host your .git folder behind NGINX, allowing only GET.
3. git lfs fetch
4. See error: fetch: Fetching reference refs/heads/main
batch response: Client error &{%!!(string=https) %!!(string=) %!!(*url.Userinfo=<nil>) %!!(string=mydomain) %!!(string=/.git/info/lfs/objects/batch) %!!(string=) %!!(bool=false) %!!(bool=false) %!!(string=) %!!(string=) %!!(string=)}s(MISSING) from HTTP 405

**Expected behavior**
No mention of batch

**System environment**
Windows 11

**Output of `git lfs env`**
git-lfs/3.5.1 (GitHub; windows amd64; go 1.21.7; git e237bb3a)
git version 2.47.0.windows.2

Endpoint=https://blabla/.git/info/lfs (auth=none)
LocalWorkingDir=C:\somewhere
LocalGitDir=C:\somewhere\.git
LocalGitStorageDir=C:\somewhere\.git
LocalMediaDir=C:\somewhere\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\somewhere\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\somewhere\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_CURL_VERBOSE=1
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_TRACE=
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
I also don't see where it would ever be used in the code any more. I see when it was added, but that code was refactored, and, I guess lost?

**Comment by chrisd8088** [comment]
Hey, thanks for the question!  The `lfs.basicTransfersOnly` configuration option was added in PR #1299, and it's purpose is to limit the list of upload and download adapters to the "basic" HTTP one, not to disable the use of the Git LFS Batch API by that adapater.

You can see the difference in the `git lfs env` output:
```
$ git init test
$ cd test
$ git lfs env | grep '\(Basic\|Download\|Upload\)Transfers'
BasicTransfersOnly=false
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh

$ git config lfs.basicTransfersOnly true

$ git lfs env | grep '\(Basic\|Download\|Upload\)Transfers'
BasicTransfersOnly=true
DownloadTransfers=basic
UploadTransfers=basic
```

Note that the `ssh` and `lfs-standalone-file` adapters are removed the when the option is enabled.  Those adapters transfer Git LFS objects over non-HTTP protocols, but the "basic" HTTP one always uses the Git LFS Batch API.  As the `git-lfs-config(5)` manual page [states](https://github.com/git-lfs/git-lfs/blob/6340befc60876f4f039f215479d9d5a945f817e1/docs/man/git-lfs-config.adoc?plain=1#L133-L136):

> If set to true, only basic HTTP upload/download transfers will be used, ignoring any more advanced transfers that the client/server may support.

The meaning of "advanced transfers" here is one which either doesn't use HTTP at all, or uses some other custom HTTP-based Git LFS protocol other than the default one which implements the Batch API.

**Comment by chrisd8088** [comment]
I'm going to close this issue, as I think I've answered the question fully, but please re-open it if there's more to discuss!
