### ISSUE TITLE
Gematriagroup.com

### ISSUE THREAD

**Issue by AW239490** [git-lfs/git-lfs#5923]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

Please also mention the usage of any proxy, including any TLS MITM device or non-default antivirus or firewall.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

If you're having problems trying to push or pull data, please run the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and include it inline or attach it as a text file.  In a bash or other POSIX shell, you can simply prepend this string and a space to the command.

**Comment by chrisd8088** [comment]
This doesn't look like a useful contribution, so I'm going to close this issue.

**Comment by AW239490** [comment]
Im Gegenteil, diese Domäne gehört mir und ich interessiere mich sehr dafür, aber Sie sind diejenigen, die sich mit der Schwere der Sache befassen, oder Sie sind schwerwiegender als sieIch habe alle falschen Rechnungen erhalten und sie wurden ohne mein Wissen von meinem Konto abgebucht, und was ich heute habe, ist eine Ergänzung zu einer anderen Firma, und sie wollten, dass ich weitere 7,5 Euro bezahle Ich hatte Angst zu schlafen, weil sie Hacker waren.

**Comment by AW239490** [comment]
Leider stand auf der letzten Rechnung, die ich von Check Domain erhalten habe, dass ich 7 Euro und Cent zahlen müsste, aber ich hatte Angst, dass es sich um Hacker handelte. Aus diesem Grund möchte ich sie nicht bezahlen, weil sie...Ich habe ihnen gesagt, wenn Sie echt sind, können Sie den Betrag, der ohne mein Wissen von meiner Karte abgebucht wurde, von der Zusatzrechnung abziehen und zurückerstatten. Das ist eine sehr schlechte Sache, wenn ohne Ihre Zustimmung Geld von Ihnen abgebucht wird, nur weil Sie es getan haben Ich habe mich bei dieser Firma versichert und Ihre Versicherungskarte hineingelegt. Dann war ich nach einer Weile überrascht, dass sie mir einen Betrag in Höhe von ca.Wenn sie echt sind, ziehen sie die Rechnung vom Add-on ab und mein Dimon, der sie auf schlechte Weise abgezogen hat, wird mir Rechnungen schicken und ich zahle, zahle, zahle, das ist eine sehr schlechte Sache.
