### ISSUE TITLE
Hello, I've noticed that when adding files to a git repository after running `git lfs install` and having the file types tracked in `.gitattributes`, the `.git` folder has a size equal to the sum of the files in the directory.

### ISSUE THREAD

**Issue by thanachotnual** [git-lfs/git-lfs#5927]
Hello, I've noticed that when adding files to a git repository after running `git lfs install` and having the file types tracked in `.gitattributes`, the `.git` folder has a size equal to the sum of the files in the directory.
Looking more closely, the blobs are stored in the `.git/lfs/objects/...` folder and are a copy of the objects.

Is this expected behavior ? When having big repos (think over a TiB), this can be cumbersome and feels like a waste of space. It may be that there's just some sort of symbolic link, but usually when running `ls` you have that information, when here you do not.
I'm basing my question on running `du -h -d 1 .` inside the git folder.

_Originally posted by @McPatate in https://github.com/git-lfs/git-lfs/discussions/5294_

**Comment by chrisd8088** [comment]
Yes, in brief, that's the expected behaviour.  As there is already a full discussion of this topic in #5294 and this appears to be just a copy of that discussion's question, I'm going to close this issue.
