### ISSUE TITLE
LFS doesn't consider all files after merge

### ISSUE THREAD

**Issue by NiklasRosenstein** [git-lfs/git-lfs#733]
We have a repository we can safely set off anew from its current state and did a squashed pull into a new repository to support Git LFS from the start. After the merge, `git lfs status` didn't list all files (22 of 184).

```
git pull --squash ../horror-survival
git lfs status
```

After unstaging all files and adding them again, it recognized all files.

```
git reset HEAD
git add .
git lfs status
```

**Comment by technoweenie** [comment]
Hi, I'm replying to old issues I've missed. This looks like a valid LFS issue, though I'm not sure how much control we have over how git merges things. Any more details, like `git lfs env` and your `.gitattributes` file would help. Also, a sample repository that we can use to replicate the issue would be amazing too.

**Comment by ttaylorr** [comment]
Hi @NiklasRosenstein! I'm going to close this issue out for now. If you're still having any problems related to this, please don't hesitate to re-open this issue. Thanks!
