### ISSUE TITLE
Windows installer is missing man pages

### ISSUE THREAD

**Issue by bitshifter** [git-lfs/git-lfs#810]
There appear to be man pages for the git-lfs command in the git repo, but no documentation is included in the Windows installer.

**Comment by technoweenie** [comment]
You can use "git lfs help <cmd>" to pull up the man page for a specific command. While man page support would be nice for Windows (and if you or someone knows how to do this, I'd really appreciate the help), but the Windows cmd has no concept of man pages AFAIK. I'm open to suggestions or especially PRs from someone with Windows experience here.

**Comment by bitshifter** [comment]
Actually, you should probably just ignore this, as it's peculiar to my setup.

The "official" [Git for Windows](https://git-for-windows.github.io/) is built on top of [MSYS2](https://msys2.github.io/), a Cygwin (POSIX emulation layer) derived distro which uses Arch Linux's pacman package management. So Git for Windows comes with a bash shell and some standard Unix stuff. However, the the Git for Windows package doesn't include man pages and the git help command will actually open html files in a web browser - I guess it might be nice to integrate up git lfs help like this, but I have no idea how it's done.

I use MSYS2 and install git using pacman rather than using the Git for Windows installer. This means I have a pretty standard Unix experience, including man pages, but it's probably not the way that most people are using Git on Windows. As an aside, for MSYS2 users it would be nice if git-lfs could be installed using pacman. But again, I'm not that familiar with pacman, and also I don't believe golang is available under MSYS2 so I'm not sure it would be possible to build from source under MSYS2.

**Comment by TT--** [comment]
I'm also using **Msys2** and noticed there was no `man` command.  I got very close by using the [answer posted here](https://superuser.com/a/634889/279136) which said to install `groff` (available via pacman) and then use the [script here](http://www.mingw.org/wiki/ManScript) which has at its core the call to `groff -Tascii -mandoc -P-c`.

But I could not get it to work on my man pages which are in `/usr/share/man` _unless I uncompressed the gz files first_!

This was not an acceptable solution, so I looked further and found that by running `pacman -Ss -man` that there are three packages (currently) that have the "man-" prefix.  ([see them here](https://github.com/alexpux/msys2-packages)).

I tried the one called **man-db**, and it worked, now I have ability to run `man`!

**Comment by ttaylorr** [comment]
@sschuberth could you look into this?

**Comment by sschuberth** [comment]
Solving this depends on Git for Windows to ship with a `man` executable (for which the Git LFS installer could then install its man pages), but [the current Git for Windows maintainer made pretty much clear that's not going to happen](https://github.com/git-for-windows/git/issues/696).

**Comment by ttaylorr** [comment]
> Solving this depends on Git for Windows to ship with a `man`
> executable (for which the Git LFS installer could then install its man
> pages)

OK, that makes sense.

> but [the current Git for Windows maintainer made pretty much clear
> that's not going to happen](https://github.com/git-for-windows/git/issues/696).

Fair enough. It sounds like we can +cc @dscho for another vote that a
manpage viewer would be helpful, but close this for now.

**Comment by dscho** [comment]
`man` is a foreign concept to Windows users. As such, the end user-facing Git for Windows would not provide any benefit if it bundled the man pages. We bundle the HTML pages instead.

If you want to have `man` pages, you are looking for a Linux-like system like [MSYS2](https://msys2.github.io/), and Git for Windows' SDK is a derivative of that.

But quite frankly, I would need volunteers to take care of the MSYS2 part if that is a wish that is supposed to be fulfilled somehow.
