### ISSUE TITLE
git lfs track fails when git dirpath contains symlinks

### ISSUE THREAD

**Issue by difro** [git-lfs/git-lfs#811]
git lfs track fails with `a.gif is outside repository` if current working dir(=gitdir) contains symlinks.

Steps to reproduce.

``` bash
$ mkdir /tmp/real
$ cd /tmp/
$ ln -sf real sym
$ cd sym
$ git init . ; git lfs init
# copy any binary file to this dir
$ git lfs track a.gif
a.gif is outside repositor
```

git lfs env output

```
git-lfs/1.0.2 (GitHub; linux amd64; go 1.5.1; git 9a9ab0386672)
git version 2.6.1

LocalWorkingDir=/tmp/real
LocalGitDir=/tmp/sym/.git
LocalGitStorageDir=/tmp/sym/.git
LocalMediaDir=/tmp/sym/.git/lfs/objects
TempDir=/tmp/sym/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

**Comment by technoweenie** [comment]
Ah, this is because [the `init()` function](https://github.com/github/git-lfs/blob/b0318b25350b9abfe56af0afb01913a9b2ed56a4/lfs/lfs.go#L196-L209) uses [`git rev-parse`](https://github.com/github/git-lfs/blob/b0318b25350b9abfe56af0afb01913a9b2ed56a4/git/git.go#L450-L476) to get the working directory. We may need to use that as the base for all of the other directories too. I'll add this to the list for v1.1.0, but I personally won't be able to work on that too much for a little while.

**Comment by difro** [comment]
Well, simplest solution would be cleaning paths with filepath.EvalSymlinks() for all the directories before we use/compare them.  
Maybe I can have a go at it. Would this approach be ok?

**Comment by technoweenie** [comment]
@difro: Yeah, that'd be great. Ideally, there's a shell integration test using symlinks too in [test-env.sh](https://github.com/github/git-lfs/blob/master/test/test-env.sh). I can help out there if you don't feel like writing some shell code too though :)

**Comment by difro** [comment]
yeah, skimmed over test-env.sh and I feel it's better that you take a look at it :)

git lfs env after applying #816 
```
$ git lfs env
git-lfs/1.0.2 (GitHub; linux amd64; go 1.5.1; git 386c03db5009)
git version 2.6.1

Endpoint=https://github.com/difro/test.git/info/lfs (auth=basic)
LocalWorkingDir=/tmp/real
LocalGitDir=/tmp/real/.git
LocalGitStorageDir=/tmp/real/.git
LocalMediaDir=/tmp/real/.git/lfs/objects
TempDir=/tmp/real/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

**Comment by ttaylorr** [comment]
Hi @difro, just a quick ping to let you know that this issue is fixed in https://github.com/git-lfs/git-lfs/pull/818.
