### ISSUE TITLE
Public go packages for LFS management

### ISSUE THREAD

**Issue by rasky** [git-lfs/git-lfs#813]
I'm currently in the process of expanding a Go application that does some basic management on git repositories to add LFS support. The current code navigates a git repository using `git ls-tree` and reads file contents using `git cat-file blob` (so, spawning the `git` binary). Something really simple, like for instance:

``` go
// Read the contents of a file, given its hash
func (r *Repo) ReadFile(hash string) io.ReadCloser {
    return r.gitCommandOutput("cat-file", "blob", hash)
}
```

I need to be able to expand this code to support LFS. So I would say I would need at least the following functionalities available through a package:
- Sniffing/parsing of a pointer file
- Batch downloading
- Managing of a local cache to avoid downloading the same files multiple times.

I'm opening this issue (as discussed on gitter) to track progresses and clarify which kind of API I would need from exported packages.

**Comment by technoweenie** [comment]
To be clear, the `github.com/github/git-lfs/lfs` package is technically a publicly exported Go package. However, it's not intended to be used in 3rd party go apps, and is not at all what I'd consider a well designed Go package. 

I would love to have well designed Go packages. Two of your three suggestions are covered by existing issues:

* Batch downloading: See #779
* Managing of a local cache to avoid downloading the same files multiple times: See #778

The first item ("Sniffing/parsing of a pointer file") looks easy, but could turn into a situation where you have to import 3 packages and wire them up together to implement that `ReadFile()` function (which is basically what our `smudge` command does).

Just to be clear: while I am in favor of this idea, I can't say it's a priority of _mine_ right now. Refactoring for uses like this has to take a back seat to the needs of core git-lfs users.

**Comment by rasky** [comment]
Wiring 3 packages would be OK for me, and it's what I would expect. A single higher-level package would probably not give me enough flexibility after all. And of course, even just one package for one of the above tasks is still better than nothing :)

**Comment by ttaylorr** [comment]
Hi @rasky, thanks for opening this. I am circling back through old issues and responding to some old topics that could use some love. Git LFS makes no promise about the backwards compatibility of exported Go packages, but `tq`, and `lfs` (useful for downloading/caching respectively) should be dependable for now (without specifically defining dependable).

I don't think that the project is in a state where we can make promises about the backwards compatibility of new changes to exported Go packages for now. That said, I think certainly that most of our Go code should be usable outside of LFS, in that it conforms to the agreed-upon Go conventions.
