### ISSUE TITLE
Using 'git add" with LFS and 3.76GB causes fatal error

### ISSUE THREAD

**Issue by datalogics-bhaugen** [git-lfs/git-lfs#817]
First time experimenting with LFS, trying to add a large PDF to my repository though and it fails when running _git add_ with

> error: read from external filter git-lfs clean %f failed
> error: cannot feed the input to external filter git-lfs clean %f
> error: external filter git-lfs clean %f failed
> fatal: pdfs/pdf-large/MillionPages.pdf: clean filter 'lfs' failed

On Mac OS X El Capitan, any thoughts? Is the file just to large for it to handle?

**Comment by technoweenie** [comment]
There should be more details printed somewhere. Does anything show up from `git lfs logs last`? If you have more detailed log that you don't want public here, feel free to send it to https://github.com/contact, or send me a private message on our [gitter chat room](https://gitter.im/github/git-lfs).

Also, GitHub sets a 2GB limit on individual LFS objects. This isn't a factor _here_, but will cause another error once it's solved. If not, then don't worry about it :)

**Comment by datalogics-bhaugen** [comment]
````git lis logs last```` results in

> brandons-mbp% git lfs logs last
No logs to show

Does GitHub Enterprise have the same 2GB limit?

**Comment by technoweenie** [comment]
Yes. Again, based on what I can see, that issue is not affecting you here. This seems to be coming from the Git LFS client code. If I can see a better error, I can help track it down.

**Comment by datalogics-bhaugen** [comment]
@technoweenie what is the best way to share the file with you so you can see if you can reproduce the issue/get a better error message?

**Comment by technoweenie** [comment]
In addition to what I mentioned above, you can send it in an email to support@github.com. If it mentions "LFS" in the subject, it'll land in my inbox.

**Comment by ttaylorr** [comment]
Hi @datalogics-bhaugen, I'm going to close this issue out for now since it's been a little while. Please don't hesitate to drop a comment here if you have any trouble with this in the future!
