### ISSUE TITLE
Lfs Track Doesn't Respect Line-Ending Settings

### ISSUE THREAD

**Issue by WillHipschman** [git-lfs/git-lfs#824]
On windows systems when git is set to use CLRF as line endings git lfs track creates an attributes file with LF line endings. We should respect whatever the git setting is.

**Comment by technoweenie** [comment]
LFS was designed for binary objects, so I didn't really plan on people throwing massive json dumps in LFS or whatever. That said, since it IS happening, I'll accept a patch for it :+1:

**Comment by ttaylorr** [comment]
Support for this was added in https://github.com/git-lfs/git-lfs/pull/1914.
