### ISSUE TITLE
Tracking an object with "git lfs track .\filename.ext" does not track the file

### ISSUE THREAD

**Issue by zite** [git-lfs/git-lfs#825]
When using tab completion on the github cli for windows (powershell) it autocompletes filenames to .\filename.ext. This creates a .gitattributes file like the following entry:

.\filename.ext filter=lfs diff=lfs merge=lfs -text

When later adding that file to a commit it is not processed as a git-lfs tracked file.

**Comment by technoweenie** [comment]
Thanks, that's something the track command can clean up. However, you don't normally want to track individual files. If the extension is something that you always want included in Git LFS, track it with:

    # with the quotes
    git lfs track "*.ext"

If you really want the filename, simply change the `.gitattributes` file to `filename.ext filter=lfs diff=lfs merge=lfs -text`.
