### ISSUE TITLE
`git lfs pull` only pulls 100 files

### ISSUE THREAD

**Issue by stolpeo** [git-lfs/git-lfs#829]
In my git lfs repository there are more than 200 files. If I perform a `git lfs pull` in a fresh git clone, it only processes 100 files and then hangs (I have to break the run manually). To get all my files, I have to execute the pull 3 times:

```
$ git lfs pull
Username for 'https://github.com': ocs7474505
Password for 'https://ocs7474505@github.com': 
(0 of 219 files) 0 B / 1.59 GB                    U
(100 of 219 files) 902.58 MB / 1.59 GB            ^C

Exiting because of "interrupt" signal.
$ git lfs pull
Username for 'https://github.com': ocs7474505
Password for 'https://ocs7474505@github.com': 
(0 of 219 files) 0 B / 1.59 GB                    U
(100 of 219 files) 535.83 MB / 1.59 GB            ^C

Exiting because of "interrupt" signal.
$ git lfs pull
Username for 'https://github.com': ocs7474505
Password for 'https://ocs7474505@github.com': 
(19 of 219 files) 187.27 MB / 1.59 GB
$
```

**Comment by technoweenie** [comment]
How is your git credential helper setup? I notice you're entering your password each time. I wonder if that's causing problems? Can you run `GIT_TRACE=1 git lfs pull` ?

If you have nothing to pull anymore, you can do the following:

1. Rename the `.git/lfs/objects` directory to `.git/lfs/objects2`.
2. Run `GIT_TRACE=1 git lfs fetch`
3. Remove `.git/lfs/objects` and rename `.git/lfs/objects2` back to `.git/lfs/objects`.

**Comment by ocs7474505** [comment]
Mh, I didn't use any credential helper. The repository is private, I don't know if this has an impact. Thanks for your support! ... here we go:

```
trace: exec: 'git-lfs' 'fetch'
trace: run_command: 'git-lfs' 'fetch'
trace git-lfs: run_command: 'git' rev-parse --abbrev-ref HEAD
trace git-lfs: run_command: 'git' config branch.master.remote
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' config -l -f .git/config
Fetching master
trace git-lfs: run_command: git rev-list --objects --no-walk 94dfb0b510834ad8f12403c3be0d32deca37cab1
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: fetch XXX
.... list of 219 files ...
trace git-lfs: tq: sending batch of size 100
trace git-lfs: api: batch 100 files
Username for 'https://github.com': ocs7474505
Password for 'https://ocs7474505@github.com': 
trace git-lfs: HTTP: POST https://github.com/XXX.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: api: batch 100 files
(0 of 219 files) 0 B / 1.59 GB
....
trace git-lfs: HTTP: 200
trace git-lfs: NEW HASHING READER
(100 of 219 files) 902.58 MB / 1.59 GB
```

**Comment by ocs7474505** [comment]
Ah, setting the credentials solves the problem! Thanks for that hint!

**Comment by technoweenie** [comment]
Ok, my hunch is that it asked you for your credentials again, and is hanging while waiting for your reply. Clearly you should be seeing that, though. I think this gives us enough to go on. Thanks.

**Comment by ocs7474505** [comment]
Perfect, glad I could help :-)

**Comment by autious** [comment]
I have the same issue, every 100 files the fetch stops. 
Based on the hint here, blindly entering my credentials and pressing enter again allows it to continnue for another 100 files.

I have no password manager installed.

**Comment by ocs7474505** [comment]
I typed
```
git config --global credential.helper cache
```
and this did the trick, at least for some time.

**Comment by larsxschneider** [comment]
I ran into the same issue on OSX. This happens if no credentials helper is installed and Git-LFS can't find credentials. 
@technoweenie Do you see a way to throw a more obvious error message?

**Comment by mewmew** [comment]
The same issue happens for `git push`. Gets stuck after 100 files have been uploaded. Caching credentials was a successful workaround.

```
eval `ssh-agent`
ssh-add ~/.ssh/id_rsa
```

**Comment by kaidoe** [comment]
Same issue here, stuck on `git push` at 100 (of 3948) files on `git version 2.5.4 (Apple Git-61)`

Running `git config --global credential.helper cache` as mentioned by @stolpeo temporarily resolves the issue. Thanks!

**Comment by roobottom** [comment]
Same here on push. Thanks to @stolpeo I've temporarily solved it, but is there a more permanent solution?

**Comment by Gfurst** [comment]
Same thing here, thanks for reminding me of the credential.helper trick, on a fresh install

**Comment by ttaylorr** [comment]
For the credential helper issue, LFS now offers a `lfs.cachecredentials` option via `git config` which emulates `credential.helper cache`.
