### ISSUE TITLE
github app crashes when tracking symlinks using git-lfs

### ISSUE THREAD

**Issue by dangold1138** [git-lfs/git-lfs#832]
After I clone a repo using LFS, the github desktop app crashes and i get the following error

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: gitLFSInfo != nil'

**Comment by shiftkey** [comment]
Is this a public repository?

**Comment by dangold1138** [comment]
No it's not.

**Comment by dangold1138** [comment]
It seems to be related to symlinks. When i track *.png files they are fine, but as soon as I add a symlink to  a .png in the repo, it crashes the github app.

**Comment by scuffedshoe** [comment]
I'm seeing this same crash as well.

**Comment by paulborza** [comment]
+1

**Comment by JoostvDoorn** [comment]
+1, It crashes for me every time I try to open the app now.

**Comment by dangold1138** [comment]
I'm not sure if this is a bug related to the github app, or if it is a bug in git-lfs itself. I tried to file an issue on the github app tracker too, but couldn't find it.

**Comment by JoostvDoorn** [comment]
I reported this issue to Github directly, with a link to the issue here. They asked me for a crash report. So I assume they will be looking into it.

**Comment by AlessandroBorges** [comment]
I'm also having problems with symlinks and github app

**Comment by DanielAsher** [comment]
+1
Any progress on this? How can I reset Github Desktop?

**Comment by pradojrr** [comment]
Same issue here, MacOS, GitHub desktop, crashes with:
```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: gitLFSInfo != nil'
terminating with uncaught exception of type NSException
abort() called
```

When can this be fixed? It prevents people in my team from using GitHub Desktop.

**Comment by ttaylorr** [comment]
👋  I went ahead and opened an internal issue to see what next steps to debug this are.

**Comment by ttaylorr** [comment]
Hi everybody. It sounds like this was an issue with GitHub Desktop, which has released a new MAJOR version since this issue was originally opened and now is open-source.

Since this appears to be an issue with GitHub Desktop, you can open a new issue there, if the problem persists: https://github.com/desktop/desktop
