### ISSUE TITLE
Git LFS installs don't work on Ubuntu

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#840]
An ubuntu user reported to me that installs from package cloud don't work on Ubuntu when installing through packagecloud:

```
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
```

It doesn't output any obvious errors, but doesn't actually install anything. Luckily, you can workaround it by [downloading a specific deb](https://packagecloud.io/github/git-lfs/packages/debian/jessie/git-lfs_1.0.2_amd64.deb) and installing it with `dpkg -i path/to/git-lfs.deb`.

How can we get this to work for Ubuntu users?
1. Update our [packagecloud distro map](https://github.com/github/git-lfs/blob/e2060f1482cd63e2ca27762ccd915db18a869cac/script/packagecloud.rb#L21-L28) to upload the debs for ubuntu versions?
2. Provide the deb/rpm downloads on [the latest release page](https://github.com/github/git-lfs/releases/tag/v1.0.2) so users with alternative OSs can get them? 

/cc @andyneff

**Comment by rubyist** [comment]
FWIW that curl command doesn't install git lfs itself, it installs sources so the package manager knows where to get it. You still have to `apt-get install git-lfs`, in this case. The packagecloud installation page isn't very clear about this.

IMO we should do both 1 and 2.

**Comment by technoweenie** [comment]
So is it possible that it works just fine on Ubuntu if they just run `apt-get` right after? If so, I think we could just skip step 1.

**Comment by rubyist** [comment]
No, it doesn't work on ubuntu. We still need ubuntu packages on packagecloud for it to work. The script essentially just installs some packagecloud deps and writes a sources file, it doesn't check that any packages for that distro exist in the repo. The failure comes when you try to install them with the package manager.

**Comment by technoweenie** [comment]
@ssgelm just suggested adding packages for the supported ubuntu versions: precise, trusty, vivid, and wily.  I'll add those when I ship Git LFS v1.1.

**Comment by ttaylorr** [comment]
We support all currently available distributions of Ubuntu in [`packagecloud.rb`](https://github.com/git-lfs/git-lfs/blob/master/script/packagecloud.rb), so I believe that this issue can be safely closed.
