### ISSUE TITLE
Inconvenients uploading proyect

### ISSUE THREAD

**Issue by edwinb24** [git-lfs/git-lfs#852]
I keep having difficulties with the upload. In the installation process, do I need to do a step in between installing the software (1) and and putting the command in Git Bash (2)? 
![error 5](https://cloud.githubusercontent.com/assets/14187141/11318947/6b290298-902c-11e5-8a8a-7a3b5837973b.png)

**Comment by technoweenie** [comment]
It needs to be installed somewhere in your system path. It's designed to work after installing Git for Windows or GitHub Desktop without any custom paths. If you have custom paths for your git installation, you'll have to tell Git LFS during its installation.

**Comment by edwinb24** [comment]
When installing Git LFS the path I have by default is my desktop.  I have reinstall both GitHub Desktop and Git Bash with their default locations. Should I put Git LFS in my C:\Users\edwinb24\AppData\Local\Programs\Git folder where git-bash.exe is?

**Comment by technoweenie** [comment]
GitHub Desktop already installed it for you. It should be available through the "GitHub Shell" icon that it installs. 

You should put the path to "git.exe" in the installer. By default that should be: "C:\Program Files \Git\mingw64\bin", which is auto detected [here](https://github.com/github/git-lfs/blob/fbbfd7d9caa393edc99da6e5f5eb0626ecd7bd9a/script/nsis/installer.nsi#L21-L35).

**Comment by edwinb24** [comment]
I put the following path in the installer and now have git.exe and LFS in the same folder. Now, how do I use Git LFS through Git Shell? Thanks in advance for all the help, technoweenie. I really appreciate it!
![installating](https://cloud.githubusercontent.com/assets/14187141/11346138/caa82c84-91e0-11e5-818c-9ba29574916a.png)
![installating2](https://cloud.githubusercontent.com/assets/14187141/11346139/caa934e4-91e0-11e5-9fe1-663c82ff5f74.png)

**Comment by ttaylorr** [comment]
Provided that an executable named `git-lfs.exe` is in your `$PATH`, Git will detect and execute it faithfully. The Git LFS installer on Windows does this correctly, as does the Git for Windows installer.
