### ISSUE TITLE
Question: What happens if a contributor clones & pushes without Git-LFS?

### ISSUE THREAD

**Issue by strich** [git-lfs/git-lfs#867]
I'm just wondering whether it might be possible for a contributor to accidentally put the repository into an inconsistent state if they either:
1. Cloned and push/pulled work without ever installing Git-LFS.
2. Had Git-LFS installed at the time of cloning but for whatever reason no longer has it installed, and pushes content.

Is there any protection against accidentally pushing binary content into the repository without Git-LFS installed and therefore pushing the binary content into Gits default binary-unfriendly backend?

**Comment by technoweenie** [comment]
Nope. A good spot to do this would be a pre-commit hook, installed locally. I think this could be a great addition. The thing about git hooks though, is that you can only have one setup for your repository at a time. So I think it'd have to go like this:

1. Add a command, like `git lfs pre-commit`.
2. Teach [`lfs.InstallHooks()`](https://github.com/github/git-lfs/blob/24166bd0068f96d0c109a77d176d61b8b9e19587/commands/command_track.go#L33) how to install it.
3. If the hook exists, print a message like "add 'git lfs pre-commit' to your existing pre-commit hook".

**Comment by strich** [comment]
> A good spot to do this would be a pre-commit hook, installed locally.

As in, the local Git server? What if the one is using a hosted solution ie GitHub? If you meant the local machine, then one might as well ensure LFS is installed in the first place.

**Comment by technoweenie** [comment]
No, your local repository, in `.git/hooks`. However, if the person never installed Git LFS, then of course they won't have the hook either. It may be up to the server to reject pushes with files added without LFS.

**Comment by strich** [comment]
Bummer. Will have to watch out for that. Could be painful for any of the more public LFS projects.

**Comment by ttaylorr** [comment]
> No, your local repository, in `.git/hooks`. However, if the person never installed Git LFS, then of course they won't have the hook either.

`@technoweenie` is completely correct; Git LFS _requires_ that you have it installed correctly in order to work, provided that there are already Git LFS objects on the remote.

Creating a merge conflict between a binary and a Git LFS pointer is certainly possible, and I can't think of anything that Git LFS could do in order to prevent this without more information from Git.

That said, the recent addition of `git lfs migrate` makes recovering from these types of errors very easy.

**Comment by jomark-t** [comment]
Hi,

Additional info, if you try to clone without GIT LFS installed. The files tracked with GIT LFS will be only pointer files(sha256) with a size of 4.0KB.
