### ISSUE TITLE
if git-credential does not exist, git push fails to upload LFS files

### ISSUE THREAD

**Issue by tpdownes** [git-lfs/git-lfs#878]
On a computing cluster running Debian 7, which has git 1.7 by default. It turns out that git 1.7 as packaged for Debian 7 does not include a git-credential binary.

Without realizing this, I setup a credential helper (globally) to help https operations. Normal git operations were not affected by this vestigial configuration. I didn't notice it wasn't working because my operations were less frequent than the timeout.

```
[credential]
        helper = cache --timeout 900
```

But... with this configuration, git push in a repository with LFS tracking files fails to even attempt a file upload.

In some sense, this is user error since the config has a section that can't help, but git LFS should fail gracefully to interactive prompts when git-credential fails so the bug may have wider applicability. I was able to resolve the error by installing a backported version of git 1.9 which includes the git-credential binary.

```
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1)
git version 1.7.10.4

$ git-lfs smudge large/git-lfs_1.1.0_amd64.deb
Error accessing media: large/git-lfs_1.1.0_amd64.deb (b4403d3b939557fa802c09b3b27d0e6cc80a34798a8c6f35cfe84167e0b49208)

Git credentials for https://my.host/my-name/lfs-test.git not found:
'git credential fill' error: exit status 1

goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f3eff4451e8, 0xc820144078, 0x7f3eff4471a8, 0xc8204603a0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7f3eff4471a8, 0xc8204603a0, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7f3eff4471a8, 0xc8204603a0, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f3eff4471a8, 0xc8204603a0, 0x95d2c0, 0x1e, 0xc82011fc98, 0x2, 0x2)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0xb5a1e0, 0xc820011a70, 0x1, 0x1)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd89
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb5a1e0, 0xc8200119c0, 0x1, 0x1, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb5b220, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=/home/tpdownes/repos/lfs-test
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git/lfs/objects
TempDir=.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
GIT_PREFIX=
GIT_INTERNAL_GETTEXT_SH_SCHEME=gnu
GIT_SSH=/usr/bin/gsissh
GIT_REFLOG_ACTION=pull
```

**Comment by tpdownes** [comment]
This possibly impacts RHEL6-derived platforms without access to git 1.9.4 from the SCL 1.2 release. The included version of git on RHEL6 is 1.7.11.1 and it does not have a /usr/libexec/git-core/git-credential binary. Git 1.9.4 does have such a binary.

**Comment by technoweenie** [comment]
Git LFS requires Git v1.8.2+. It's unlikely we'll support such old Git versions due to their lack of `git-credentials` and `pre-push` hook support.

**Comment by tpdownes** [comment]
I believe you have just eliminated the version of git that comes with 3 of the 5 linux platforms for which you package git-lfs. Not that there aren't workarounds - but the pages aren't exactly screaming "you must find a backport"

**Comment by tpdownes** [comment]
Recall my claim is that git LFS should fail more gracefully, not that you should necessarily support older versions. Possible solutions, not necessarily at odds:

* packages depend on installation of git >= 1.8.2, otherwise do not install.
 * On RedHat you would want to depend on EITHER git >= 1.8.2 OR the presence of the git19 package from SCL (major/minor version number in package name).
 * On debian/ubuntu, you simply depend on git >=1.8.2.
* error check for git version, better existence of binaries being used. These error checks should be reflected in the logs and in stderr output.

**Comment by technoweenie** [comment]
I think both of those are great ideas. :+1:

/cc @andyneff/@ssgelm Re: packages

Regarding error checks -- I could see adding a check in `git lfs install`, `git lfs env`, and any time the CLI tool blows up. Maybe `git lfs track` too.

**Comment by ssgelm** [comment]
I thought the debian package _did_ have that dependency.  I must have done that when working on submitting to debian but forgotten to submit upstream.  I'll do that now.

**Comment by ssgelm** [comment]
No, it is already there: https://github.com/github/git-lfs/blob/master/debian/control#L5.  I set it to 1.8.0 though so maybe worth changing.

**Comment by andyneff** [comment]
@tpdownes The git-lfs rpm used to `Require: git>=1.8.2`, however it was removed because other wise the ONLY yum solution was installing a git rpm. Now I personally (and I'm sure MANY other people) just clone git, make install, can call it done. This gives me a FAAAR newer git than the packages allow. This is why it was discussed and finally removed as a dependency requirement for centos.

Centos 6 (still relevant) only had a really old git which was too old. (Centos 5 ironically had no git, and epel's was recent enough, though still quite old) I didn't look at scl's, but I think that would work

The point was that the Requires was decided to be too limiting and removed for Centos/Rhel

The options were

1. Limit to the yum accessible git rpm. This could confused people who don't know how to find the right repo to get a newer git, or use a specific version for which no one has written an rpm for. There are new features in newer git that would justify having a newer version of git
2. Put the requirement in there, and expect them to figure out they could download it and run `rpm -i --nodep git-lfs.rpm` to force it... ehhhh....
3. Put a nice clear message in the README.md saying that git 1.8.2 is required and let them figure out how to get it there ;)
4. (Not really discussed, but...) create a dummy git package that can be installed to make 1 work with a custom install... this is pretty hacky...

Do we want to go back to option 1. And if that doesn't work for someone, they just download the exe and install it manually?

There is no perfect solution ;)

**Comment by andyneff** [comment]
@ssgelm the https://github.com/github/git-lfs/blob/master/debian/control#L5 is the `Build-Depends` line

https://github.com/github/git-lfs/blob/master/debian/control#L10 actually just says git (I think? DH VOODOO!!!)

**Comment by tpdownes** [comment]
@ssgelm @andyneff I don't know about master, but I can confirm that the version I downloaded from your release page only has:

```
[pcdev3:~] apt-cache depends git-lfs
git-lfs
  Depends: libc6
  Depends: git
```

**Comment by tpdownes** [comment]
at all: wow quick response! Thanks.

@andyneff I undetstand your problem. I would enthusiastically make the opposite choice.

1. A major point of packaging systems is to enforce known dependencies. When I yum/apt-get install and get exit code 0 it is telling me that the code should work. Obviously I don't expect you to handle the unknown, but if you're making a package, you're telling me it should work with other known packages. This does not.
2. The world of people who build their own git probably has 100% overlap with people who can build their own git-lfs. It probably has very high overlap with someone who can figure out how to force a package installation on either platform.
 * If you were to better document on the web that the default git for 3 of your 5 platforms won't work, and provide basic instructions on how to handle that situation, you'd be in better shape.
  * RHEL5
    * install git and git-lfs from source (?)
  * RHEL6
   * install git19 from SCL (RHEL7 includes git 1.8.3) and git-lfs from package
   * install git and and git-lfs from source
  * Debian 7
   * install git from wheezy-backports and git-lfs from your package
 * Related point: I believe the following statement is true: neither git-lfs.github.com, nor any page it directly links to, notes the dependence on git >= 1.8.2. I think it only shows up in the markdown for the main page of the git-lfs github repo. git-lfs.github.com links to a subdirectory of the repo.

**Comment by ssgelm** [comment]
@andyneff @tpdownes My bad, I was looking at the build dependencies.  This is fixed in #879.

**Comment by tpdownes** [comment]
An example in favor of your choice: the docker package reasonably enough chooses not to enforce the kernel >= 3.10 requirement in its packaging as many people probably choose to compile their own kernels. As the administrator of a computing cluster, I choose to rely on highly-visible-and-patched OS kernels rather than get into the kernel packaging business.

But...

* Docker's web pages are incredibly clear on the kernel requirement (they used to point users to wheezy-backports)
* I'm guessing if you were to run docker it would print only a few lines to stderr telling you why it failed

Docker virtualization is a pretty big outlier compared to your typical package, though. I'm inclined to interpret "yum install exited code 0 == the developers are telling me it should work."

**Comment by andyneff** [comment]
Side note,`yum install good_pacakge_name bad_packagename` has an exit code of 0. :) And yes, that detail annoys me to no end. Lesson: YOU CAN'T USE YUM EXIT CODES!

- I agree with the documentation issue, it can always be better ;)
- Is https://www.softwarecollections.org/en/scls/rhscl/git19/ accurate? I have to install something first, install a repo for git19, install git19, then `enable` it in some scl version of alternatives? Sorry, never used scl before, just trying to understand what it is.

**Comment by tpdownes** [comment]
Yes, that is the rough picture of how to use SCL. The point is to allow a newer copy to live side-by-side with the original packages in a totally different path (under /opt I think). A user would call on it explicitly with scl enable. Point being: the system tools in an enterprise environment might have very strict version requirements on, say, Python, that would annoy an actual user.

It's closer to "modules" than to Debian's alternatives: http://modules.sourceforge.net

**Comment by tpdownes** [comment]
PS. Not suggesting you document the beginning-to-end of SCL, but a 1 sentence-fragment version of how I should approach installation on each platform. "RHEL5: from source only". My default assumption when I see a package is "perfect: I don't have to think" whether or not that is ultimately true.

Again, thanks for your help. I'm sure you'll pick a solution that works for you. I'm pushing my team to use SCL on RHEL6 since we already use it in one other case.

**Comment by andyneff** [comment]
Ah modules... So you have to `scl enable` every bash session?

As it stands now, I have tested:

- CentOS 5 using epel git
- CentOS 6 using... ok, I was stupid enough to make my own git rpm https://packagecloud.io/github/git-lfs/packages/el/6/git-2.4.5-1.el6.x86_64.rpm. Yes, another one of those undocumented things, also a poor idea, I now admit
- CentOS 7 using official git

So as far as special cases are concerned, we are really just talking about RHEL6

I'll look into SCL some this weekend. It also has ruby2... } : - )

**Comment by tpdownes** [comment]
I think the real world solution for a shared environment would be to add scl enable under /etc/profile.d. But, yes, you have to scl enable every bash session by hook or by crook.

Packages in [EPEL cannot overlap with packages in the RHEL they're tied to](https://fedoraproject.org/wiki/EPEL/FAQ#Does_EPEL_replace_packages_provided_within_Red_Hat_Enterprise_Linux_or_layered_products.3F) thus the bizarro situation you have with RHEL5 and 6.

Googling found me this:

https://ius.io/IUSvsSCL/
https://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/repoview/development.tools.group.html

**Comment by andyneff** [comment]
The situation is JUST RHEL6, RHEL5-base had no git package, which is why EPEL git is available and works.

**Comment by tpdownes** [comment]
I got it (bizarro meaning a reversion in support from 5 to 6).

Check out the IUS option. Might be the easiest one to explain. Gives you git 2.6.2 in a package under /usr/bin according to the filelists.xml. I have not tested but am reconsidering SCL.

**Comment by jgeorgeson** [comment]
I am also at an organization using RHEL6 pretty heavily and we're looking at migrating to Git, and have a great deal of IT policy on installing software. Would you consider building a git19-git-lfs rpm against the git19 SCL for CentOS/RHEL 6? Maybe in addition to the regular git-lfs rpm so that people building their own git rpm or using something like IUS aren't covered too.

As far as having to _enable_ an SCL in your shell, at least for git19 I just put this in my .bashrc

```bash
[ -f /opt/rh/git19/enable ] && . /opt/rh/git19/enable
```

So it's not too bad.

**Comment by ttaylorr** [comment]
Thanks everyone for the useful discussion. I am going to close this issue for now, since I agree with the remark in https://github.com/git-lfs/git-lfs/issues/878#issuecomment-161361570, even moreso almost two and a half years after it was written.
