### ISSUE TITLE
Git lfs issues in MAC

### ISSUE THREAD

**Issue by ARaqeeb** [git-lfs/git-lfs#893]
ARMac:AR$ git lfs install
Updated pre-push hook.
Git LFS initialized.

git lfs env
git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1; git 258acf1)
git version 2.4.9 (Apple Git-60)

Endpoint=https://github.com/IntBitTech/NamewellWebServices.git/info/lfs (auth=none)
LocalWorkingDir=/Users/AR/Documents/Projects/Dot Net/Namewell/NamewellWebServices/NamewellWebServices
LocalGitDir=/Users/AR/Documents/Projects/Dot Net/Namewell/NamewellWebServices/NamewellWebServices/.git
LocalGitStorageDir=/Users/AR/Documents/Projects/Dot Net/Namewell/NamewellWebServices/NamewellWebServices/.git
LocalMediaDir=/Users/AR/Documents/Projects/Dot Net/Namewell/NamewellWebServices/NamewellWebServices/.git/lfs/objects
TempDir=/Users/AR/Documents/Projects/Dot Net/Namewell/NamewellWebServices/NamewellWebServices/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"

git push
Counting objects: 1169, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (1079/1079), done.
Writing objects: 100% (1169/1169), 52.67 MiB | 204.00 KiB/s, done.
Total 1169 (delta 320), reused 0 (delta 0)
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: b1cbc6463eedfb5bcc8f8d564e271f59
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Something.Api/Something.Console/apc140405.xml is 122.24 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/IntBitTech/Something.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/IntBitTech/Something.git'

Even after installing lfs it doesnt work

**Comment by lhuizhan** [comment]
+1 Same issues here with 3 Macs.

**Comment by paulsputer** [comment]
Reading the logs it looks like it is simply a filesize limit you're hitting @ARAtIntBitTech @lhuizhan a few lines from the end of the log indicates what is happening: 

>remote: error: File Something.Api/Something.Console/apc140405.xml is 122.24 MB; this exceeds GitHub's file size limit of 100.00 MB

**Comment by ARAtIntBitTech** [comment]
Yeah..so what's the point you are trying to make? Git doesn't support
uploading larger files?

On Sat, Dec 12, 2015 at 1:18 PM, Paul Martin <notifications@github.com>
wrote:

> Reading the logs it looks like it is simply a filesize limit you're
> hitting @ARAtIntBitTech <https://github.com/ARAtIntBitTech> @lhuizhan
> <https://github.com/lhuizhan> a few lines from the end of the log
> indicates what is happening:
>
> remote: error: File Something.Api/Something.Console/apc140405.xml is
> 122.24 MB; this exceeds GitHub's file size limit of 100.00 MB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/git-lfs/issues/893#issuecomment-164122227>.
>



-- 
[image: IntBit] <http://intbittech.com> *Abdul Raqeeb Abdul Azeez (AR)
<ar@intbittech.com>*, CTOIntbitTech.com <http://intbittech.com>, Idaho
<https://goo.gl/maps/gFJe9>412.908.9471 <+1-412-90-9471>
Disclaimer: This e-mail message may contain confidential or legally
privileged information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution,
copying or the taking of any action in reliance on the information herein
is prohibited. E-mails are not secure and cannot be guaranteed to be error
free as they can be intercepted, amended, or contain viruses. Anyone who
communicates with us by e-mail is deemed to have accepted these risks.
IntBit Technologies, Inc. is not responsible for errors or omissions in
this message and denies any responsibility for any damage arising from the
use of e-mail. Any opinion and other statement contained in this message
and any attachment are solely those of the author and do not necessarily
represent those of the company.

**Comment by paulsputer** [comment]
> Git doesn't support uploading larger files?
Git LFS is not limited, However GitHub will apply limits on your account, best check with GitHub support

**Comment by technoweenie** [comment]
That error message is because "Something.Api/Something.Console/apc140405.xml" was not added with Git LFS. GitHub limits git objects to 100MB, and Git LFS objects to 2GB. To fix this, you'll have to redo your commits and add the file with Git LFS. Here's a guide on removing the file:

https://help.github.com/articles/removing-files-from-a-repository-s-history/

To remove and re-add the file, you should be able to do something like this:

```bash
$ git rm --cached Something.Api/Something.Console/apc140405.xml
$ git lfs track "*.xml"
$ git add Something.Api/Something.Console/apc140405.xml
$ git commit --amend -CHEAD
$ git push
```

If you're pushing more than one commit, and "Something.Api/Something.Console/apc140405.xml" is not added in the most recent commit, the steps will be more complicated.

**Comment by hujunfeng** [comment]
@technoweenie Thanks for the tip. I've rebased commits many times without any luck. Finally saw your instructions and it worked now. The key step is `git rm --cached`.
