### ISSUE TITLE
How to configure large file storage location?

### ISSUE THREAD

**Issue by jamesford42** [git-lfs/git-lfs#895]
I have git and git-lfs installed on my primary, solid-state drive, C:. But I keep my projects and data in general on D:. I would like to configure git-lfs to follow this convention.

**Comment by technoweenie** [comment]
Git LFS stores data relative to the git repository. So if you clone to `d:\projects\my-repo`, the files would be in `d:\projects\my-repo\.git/lfs/objects`.

**Comment by bozaro** [comment]
It's good idea to share lfs storage between working copies.
It's very usefull for:
 * builder farms with multiple working copies of same project;
 * moving local storage outside SSD to HDD.

**Comment by ttaylorr** [comment]
Hi @bozaro, I'm going through old issues and noticed this one. This is supported now via #2023, so I think that this issue can be closed.
