### ISSUE TITLE
Versioning of pre-built Debian packages (wishlist item)

### ISSUE THREAD

**Issue by carsten-AEI** [git-lfs/git-lfs#898]
It may be advantageous to have the Debian release the downloadable packages are targeted for embedded in the version scheme, e.g. add a +deb07 for Wheezy and +deb08 for Jessie.

At least for me that would help tremendously as I would like to have those in a local repository which contains branches for multiple release targets within the same pool.

OTOH, in this case all there is in the package is a static binary which should be pretty much portable between releases. Thus, you may consider this wish just moot.

**Comment by ssgelm** [comment]
My personal vote is that it doesn't matter since the binary should be portable between releases.  I could definitely be convinced otherwise though.

**Comment by carsten-AEI** [comment]
As a conclusion what about: As long as the package contains only static items which are release target agnostic, keep it this way. If in the future something required special attention for a specific target (compiler/linker/whatever), you may look into versioning the binary packages.

Does that sound like a good resolution (for next year ;))

**Comment by ssgelm** [comment]
Seems like a good plan to me.  @technoweenie @andyneff do you agree?

**Comment by andyneff** [comment]
Sounds good.

**Comment by ttaylorr** [comment]
We support this now, since we release to Debian 7, 8, and 9.
