### ISSUE TITLE
Proposal to contribute to docs/training

### ISSUE THREAD

**Issue by exalted** [git-lfs/git-lfs#905]
Following up https://github.com/github/training-kit/issues/339#issuecomment-164561047 I wanted to ask whatever I can help you with some docs/training material about `git-lfs`.

I would :heart: to see `git-lfs` being used in more and more places/contexts and I am ready to give my two cents as much as I can.

@technoweenie if could you please give me some initial directions I would like focus my energy on stuff that is most important for `git-lfs` right now.

/cc: @loranallensmith

**Comment by technoweenie** [comment]
Hi @exalted: First, thanks for offering to help! Documentation is a big thing I want to focus on next year for Git LFS. I'm still not quite sure how I want documentation to work though. Should it be part of git-lfs.github.com? Just some markdown files in the git-lfs repo? I'd recommend hashing out some doc ideas in the [Git LFS wiki](https://github.com/github/git-lfs/wiki) first, while this is figured out. I'm open to ideas here.

Here are some rough ideas I could see being part of the git lfs documentation:

* High level overview
* Installation
* Configuration ([man page](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn))
* Authentication (credential caching, SSH)
* Fetch includes and excludes ([man page](https://github.com/github/git-lfs/blob/e467a119b8ca38bbcd1a9f5479e43bdb14d17f70/docs/man/git-lfs-fetch.1.ronn#L37))
* Extensions ([dev docs](https://github.com/github/git-lfs/blob/e467a119b8ca38bbcd1a9f5479e43bdb14d17f70/docs/extensions.md))
* Converting repositories to LFS

**Comment by exalted** [comment]
@technoweenie thanks. If that’s all right I will draft bunch of text in wiki and we will see where to go from there?

**Comment by technoweenie** [comment]
@exalted Sounds good :+1:

**Comment by exalted** [comment]
Great. Just got back from holidays. Will 👊 on it soon...
--
Ali




On Mon, Jan 4, 2016 at 9:23 AM -0800, "risk danger olson" <notifications@github.com> wrote:












@exalted Sounds good

**Comment by lizaclark** [comment]
@exalted and @technoweenie, as a new git-lfs user, I find that there are a lot of great resources (like the youtube video and the "getting started" section of https://git-lfs.github.com) that describe how to add lfs files to a repo, but there's a big gap in terms of simple workflow level command documentation for how to clone a repo with lfs files to another machine/location and to retrieve those files. I also think that some examples of working with git lfs on a branch when the master branch does not have any lfs files would be useful.

**Comment by exalted** [comment]
@lizaclark thanks for the :sparkles: feedback! Will certainly keep your input in mind.

**Comment by exalted** [comment]
@technoweenie any suggestions where should I put any image assets (what an irony :four_leaf_clover: ) that I might want to use in wiki pages?

[Last time I checked](https://github.com/github/git-lfs/issues/791#issuecomment-151318020) GitHub Pages did not support Git LFS, nor do wikis at this point I guess.

**Comment by technoweenie** [comment]
Just drop them in an issue and copy the url to the wiki page.

**Comment by exalted** [comment]
:clap:

**Comment by ttaylorr** [comment]
Hi @exalted, I wanted to close the loop here. We would be more than happy to help anyone who is interested in writing documentation for the Git LFS project (in fact, this is something that I have had on my list for a while, too).

That said, I am going to close this _particular_ issue, since it is stale. Please note, however, that if anyone is interested in helping out in this way or others, to _not hesitate_ in letting me or @larsxschneider know, and we would both be more than happy to support that interest in whatever way we can.

Thanks :-).

**Comment by exalted** [comment]
Yes, thanks. 🙏


Ali
