### ISSUE TITLE
Files skipped / Connection to github.com closed by remote host / fatal: write error: Invalid arguement

### ISSUE THREAD

**Issue by JTLR** [git-lfs/git-lfs#935]
When I try to push files using git lfs I often get these 3 errors:

Files skipped
Connection to github.com closed by remote host
fatal: write error: Invalid arguement

First some files get skipped, then seemingly because files being uploaded are large (up to over 1gb) the connection times out and drops, then I get the 3rd error.

Any ideas what's wrong?

**Comment by technoweenie** [comment]
If LFS files are skipped, that means they already exist on the server. This isn't a problem. But I'm happy to confirm OIDs are on the server if you want to send me some. Hit up https://github.com/contact so we can chat privately.

The other errors are hard to diagnose without more info. Can you try the operation with `GIT_TRACE=1 git push`?

**Comment by thescratt** [comment]
I see similar issues with large file counts. The upload often fails.
A retry continues by skipping the successful uploads as expected, but then times out again at the max file count, and the whole cycle starts again...

Is there an upper limit on the amount of files you can push in one commit?

**Comment by technoweenie** [comment]
There's no upper limit. However, the client processes files in batches of 100. So if you have 500 files, but 350 already exist on the server, the client will make 155 HTTP requests:

```
500 / 100 = 5 API requests
500 - 350 = 150 HTTP uploads
```

I think we can definitely improve the client's ability to retry uploads.

Is this only happening on large files? Is it the same file?

**Comment by JTLR** [comment]
The original issue I had was just that files were already present on the server and hadn't been modified. However, now I've created a new repo and done an initial commit which is tracking 13 lfs files. However, they all get skipped despite not being on the server already. Any ideas what might be happening?

![image](https://cloud.githubusercontent.com/assets/4439538/12944684/a7194b3e-cfe0-11e5-8535-9190036a4c9d.png)

**Comment by technoweenie** [comment]
@JTLR You definitely have LFS objects uploaded for that repository. Happy to confirm specific OIDs if you have them.

**Comment by ttaylorr** [comment]
Hi @JTLR sorry for the very-late response to this! I am circling back through old issues and noticed this one. I agree that the `x skipped` message is confusing. I changed this behavior to be much clearer in v2.4.0.
