### ISSUE TITLE
[Feedback] Ability to apply categories to file extensions in LFS attributes

### ISSUE THREAD

**Issue by i59** [git-lfs/git-lfs#947]
Hi,

We use LFS for storing binaries required for builds on various platforms, and currently have the issue of checkouts on one platform downloading files not required for builds on that platform. 

What I suggest is a way to append categories to each file extension added via 'git lfs track', for example:
`git lfs track "*.so" Linux`, which would start tracking .so files, and also add them to a category called "Linux". In case ".so" was already tracked, the attributes files would simply be updated to apply the new category to ".so".

This would then be combined with specific LFS commands when for example checking out to set which categories one wants to include (or exclude?), for example
`git lfs category Linux`.

No idea if this is doable in the existing system, but could be interesting for a lot of different LFS use cases.

**Comment by technoweenie** [comment]
The format of the gitattributes files are determined by Git, which we have no control over. Though that just means LFS would just have to track this somewhere else.

Have you seen the [fetch include/exclude feature](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-fetch.1.ronn#L37)? That lets you set up default directories to download in a normal `git lfs pull`. That may be able to do what you want.

**Comment by i59** [comment]
Wasn't able to get the fetch / exclude functionality to work before, has this been tested on the Linux version? (Might have the same result on Windows)

**Comment by technoweenie** [comment]
Can you give some details? Our tests run on Mac, Linux, and Windows, so it _should_ work.

**Comment by ttaylorr** [comment]
> The format of the gitattributes files are determined by Git, which we have no control over. Though that just means LFS would just have to track this somewhere else.

Right; though that being said I don't think that this is a use-case that Git LFS has any plans of supporting, at least in the short term.

I would also be curious if you are having any particular issues with `--include` or `--exclude` (or `lfs.fetch{in,ex}clude`, as well) but please post detailed reproduction steps, and any other information that you think would be useful in tracking this down etc.
